// BMO/SMC 模拟卷 6 —— 从 205 道 SMC 练习池分段抽取、按难度升序装配、重编号（bmo-mk6-qNN），8 套之间零重复。
// 题目内容与练习池一致（原创、程序验算），此处仅重编号用于独立计时模考。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const BMO_MK6_MCQ: MCQQuestion[] = [
  { id: "bmo-mk6-q01", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 1, marks: 4,
    question: "Find the sum of the interior angles of a hexagon.",
    options: [{ key: "A", text: "$720°$" },{ key: "B", text: "$1080°$" },{ key: "C", text: "$900°$" },{ key: "D", text: "$540°$" },{ key: "E", text: "$360°$" }],
    answer: "A", solution: "$(n-2)\\times180°=720°$。" },
  { id: "bmo-mk6-q02", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 1, marks: 4,
    question: "Two fair dice are rolled. Find the probability that the total is $7$.",
    options: [{ key: "A", text: "$\\dfrac16+\\dfrac1{36}$" },{ key: "B", text: "$\\dfrac7{36}$" },{ key: "C", text: "$\\dfrac1{12}$" },{ key: "D", text: "$\\dfrac15$" },{ key: "E", text: "$\\dfrac16$" }],
    answer: "E", solution: "和为 7 的组合 $(1,6)\\dots(6,1)$ 共 6 种，$6/36=1/6$——所有点数和中概率最大。" },
  { id: "bmo-mk6-q03", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 1, marks: 4,
    question: "If $g(x)=2x-3$ and $g(a)=7$, find $a$.",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$\\dfrac72$" },{ key: "C", text: "$4$" },{ key: "D", text: "$11$" },{ key: "E", text: "$5$" }],
    answer: "E", solution: "$2a-3=7\\Rightarrow a=5$。" },
  { id: "bmo-mk6-q04", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "What is the smallest positive integer $n$ such that $n!$ is divisible by $990$?",
    options: [{ key: "A", text: "$11$" },{ key: "B", text: "$9$" },{ key: "C", text: "$99$" },{ key: "D", text: "$12$" },{ key: "E", text: "$10$" }],
    answer: "A", solution: "$990=2\\times3^2\\times5\\times11$：必须包含因子 $11$，而 $11!$ 已含其余全部，故 $n=11$。" },
  { id: "bmo-mk6-q05", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "If $\\alpha,\\beta$ are the roots of $x^2-5x+6=0$, find $\\alpha^2+\\beta^2$.",
    options: [{ key: "A", text: "$25$" },{ key: "B", text: "$12$" },{ key: "C", text: "$13$" },{ key: "D", text: "$37$" },{ key: "E", text: "$19$" }],
    answer: "C", solution: "韦达：$\\alpha+\\beta=5$，$\\alpha\\beta=6$；$\\alpha^2+\\beta^2=(\\alpha+\\beta)^2-2\\alpha\\beta=25-12=13$。" },
  { id: "bmo-mk6-q06", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "A circle has a chord of length $16$ at distance $6$ from the centre. Find the radius.",
    options: [{ key: "A", text: "$12$" },{ key: "B", text: "$14$" },{ key: "C", text: "$10$" },{ key: "D", text: "$8$" },{ key: "E", text: "$\\sqrt{20}$" }],
    answer: "C", solution: "半弦 $8$ 与弦心距 $6$：$r=\\sqrt{64+36}=10$。" },
  { id: "bmo-mk6-q07", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "A trapezium has parallel sides $6$ and $10$ and height $4$. Find its area.",
    options: [{ key: "A", text: "$36$" },{ key: "B", text: "$24$" },{ key: "C", text: "$32$" },{ key: "D", text: "$40$" },{ key: "E", text: "$64$" }],
    answer: "C", solution: "$S=\\tfrac12(6+10)\\times4=32$。" },
  { id: "bmo-mk6-q08", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "How many subsets does a set of $6$ elements have (including the empty set)?",
    options: [{ key: "A", text: "$64$" },{ key: "B", text: "$720$" },{ key: "C", text: "$32$" },{ key: "D", text: "$63$" },{ key: "E", text: "$36$" }],
    answer: "A", solution: "每个元素选或不选：$2^6=64$。" },
  { id: "bmo-mk6-q09", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "How many different triangles can be formed by joining $3$ of the $5$ vertices of a regular pentagon?",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$10$" },{ key: "C", text: "$60$" },{ key: "D", text: "$15$" },{ key: "E", text: "$20$" }],
    answer: "B", solution: "任 3 点不共线：$\\binom53=10$。" },
  { id: "bmo-mk6-q10", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "Find the remainder when $10^6$ is divided by $9$.",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$1$" },{ key: "C", text: "$3$" },{ key: "D", text: "$6$" },{ key: "E", text: "$9$" }],
    answer: "B", solution: "$10\\equiv1\\pmod9$，故任意次幂余 1（数字和法则的根源）。" },
  { id: "bmo-mk6-q11", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Evaluate $1+2+4+8+\\cdots+512$.",
    options: [{ key: "A", text: "$1024$" },{ key: "B", text: "$1023$" },{ key: "C", text: "$2047$" },{ key: "D", text: "$511$" },{ key: "E", text: "$1022$" }],
    answer: "B", solution: "等比求和 $2^{10}-1=1023$。" },
  { id: "bmo-mk6-q12", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "Three runners $A, B, C$ finish a race in random order (all $6$ orders equally likely). Find the probability that $A$ finishes before $B$.",
    options: [{ key: "A", text: "$\\dfrac12$" },{ key: "B", text: "$\\dfrac14$" },{ key: "C", text: "$\\dfrac16$" },{ key: "D", text: "$\\dfrac23$" },{ key: "E", text: "$\\dfrac13$" }],
    answer: "A", solution: "对称性：$A$ 先于 $B$ 与 $B$ 先于 $A$ 等可能，与 $C$ 无关：$1/2$。" },
  { id: "bmo-mk6-q13", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The Fibonacci sequence begins $1, 1, 2, 3, 5, \\dots$ Find the $10$th term.",
    options: [{ key: "A", text: "$61$" },{ key: "B", text: "$89$" },{ key: "C", text: "$55$" },{ key: "D", text: "$34$" },{ key: "E", text: "$45$" }],
    answer: "C", solution: "$1,1,2,3,5,8,13,21,34,55$。" },
  { id: "bmo-mk6-q14", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "For positive reals $a,b$, the AM–GM inequality states $\\dfrac{a+b}{2}\\ge\\sqrt{ab}$. When does equality hold?",
    options: [{ key: "A", text: "$a=b$ 时" },{ key: "B", text: "$ab=1$" },{ key: "C", text: "从不相等" },{ key: "D", text: "$a+b=2$" },{ key: "E", text: "$a=1$ 或 $b=1$" }],
    answer: "A", solution: "配方 $\\left(\\sqrt a-\\sqrt b\\right)^2\\ge0$：当且仅当 $a=b$ 取等。" },
  { id: "bmo-mk6-q15", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "For all real $x$, the expression $x^2-2x+2$ is always",
    options: [{ key: "A", text: "大于 $0$（最小值 $1$）" },{ key: "B", text: "无界向下" },{ key: "C", text: "可能为负" },{ key: "D", text: "最小值 $0$" },{ key: "E", text: "最小值 $2$" }],
    answer: "A", solution: "配方 $(x-1)^2+1\\ge1>0$。" },
  { id: "bmo-mk6-q16", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Which transformation maps $y=f(x)$ to $y=f(-x)$?",
    options: [{ key: "A", text: "关于原点旋转 $180°$" },{ key: "B", text: "上移 1" },{ key: "C", text: "关于 $x$ 轴反射" },{ key: "D", text: "右移 1" },{ key: "E", text: "关于 $y$ 轴反射" }],
    answer: "E", solution: "$x\\to-x$：镜像到 $y$ 轴另一侧。" },
  { id: "bmo-mk6-q17", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "A quadratic has roots $2$ and $-5$ and leading coefficient $1$. Its equation is",
    options: [{ key: "A", text: "$y=x^2+3x-10$" },{ key: "B", text: "$y=x^2-3x-10$" },{ key: "C", text: "$y=x^2-3x+10$" },{ key: "D", text: "$y=x^2+3x+10$" },{ key: "E", text: "$y=x^2-7x+10$" }],
    answer: "A", solution: "$(x-2)(x+5)=x^2+3x-10$。" },
  { id: "bmo-mk6-q18", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "A function satisfies $f(x)+2f\\!\\left(\\dfrac1x\\right)=3x$ for all $x\\neq0$. Find $f(2)$.",
    options: [{ key: "A", text: "$-\\dfrac12$" },{ key: "B", text: "$\\dfrac72$" },{ key: "C", text: "$-1$" },{ key: "D", text: "$2$" },{ key: "E", text: "$1$" }],
    answer: "C", solution: "取 $x=2$：$f(2)+2f(\\tfrac12)=6$；取 $x=\\tfrac12$：$f(\\tfrac12)+2f(2)=\\tfrac32$。消元得 $f(2)=-1$（$f(\\tfrac12)=\\tfrac72$）。" },
  { id: "bmo-mk6-q19", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 3, marks: 4,
    question: "A circle passes through the points $(0,0)$, $(6,0)$ and $(0,8)$. Find its radius.",
    options: [{ key: "A", text: "$10$" },{ key: "B", text: "$5$" },{ key: "C", text: "$4$" },{ key: "D", text: "$7$" },{ key: "E", text: "$\\sqrt{50}$" }],
    answer: "B", solution: "三点构成直角三角形（直角在原点），斜边为直径 $=\\sqrt{36+64}=10$，半径 $5$。" },
  { id: "bmo-mk6-q20", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "Ten points lie on a circle. How many chords joining two of the points are NOT sides of the inscribed decagon?",
    options: [{ key: "A", text: "$45$" },{ key: "B", text: "$35$" },{ key: "C", text: "$40$" },{ key: "D", text: "$25$" },{ key: "E", text: "$36$" }],
    answer: "B", solution: "弦总数 $\\binom{10}2=45$，减去 10 条边得 35 条对角线。" },
  { id: "bmo-mk6-q21", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 3, marks: 4,
    question: "How many integers from $1$ to $20$ are coprime to $20$?",
    options: [{ key: "A", text: "$12$" },{ key: "B", text: "$10$" },{ key: "C", text: "$8$" },{ key: "D", text: "$4$" },{ key: "E", text: "$6$" }],
    answer: "C", solution: "$\\varphi(20)=20\\times\\tfrac12\\times\\tfrac45=8$：即 $1,3,7,9,11,13,17,19$。" },
  { id: "bmo-mk6-q22", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "Evaluate $1^3+2^3+3^3+4^3+5^3$.",
    options: [{ key: "A", text: "$152$" },{ key: "B", text: "$225$" },{ key: "C", text: "$100$" },{ key: "D", text: "$125$" },{ key: "E", text: "$375$" }],
    answer: "B", solution: "$\\sum k^3=\\left(\\sum k\\right)^2=15^2=225$。" },
  { id: "bmo-mk6-q23", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "Two balls are drawn together from six balls numbered $1$–$6$. Find the probability that both numbers are even.",
    options: [{ key: "A", text: "$\\dfrac1{15}$" },{ key: "B", text: "$\\dfrac15$" },{ key: "C", text: "$\\dfrac13$" },{ key: "D", text: "$\\dfrac12$" },{ key: "E", text: "$\\dfrac14$" }],
    answer: "B", solution: "$\\binom32/\\binom62=3/15=1/5$。" },
  { id: "bmo-mk6-q24", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "Numbers that leave remainder $1$ when divided by both $3$ and $4$ form the sequence $1, 13, 25, \\dots$ Find the $10$th term.",
    options: [{ key: "A", text: "$97$" },{ key: "B", text: "$120$" },{ key: "C", text: "$109$" },{ key: "D", text: "$121$" },{ key: "E", text: "$133$" }],
    answer: "C", solution: "公差 $\\mathrm{lcm}(3,4)=12$：$a_{10}=1+9\\times12=109$。" },
  { id: "bmo-mk6-q25", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "For $x>0$, find the minimum of $x+\\dfrac9x$.",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$3$" },{ key: "C", text: "$6$" },{ key: "D", text: "$4.5$" },{ key: "E", text: "$10$" }],
    answer: "C", solution: "AM–GM：$\\ge2\\sqrt9=6$，等号 $x=3$。" }
];
