// BMO/SMC 模拟卷 1 —— 从 205 道 SMC 练习池分段抽取、按难度升序装配、重编号（bmo-mk1-qNN），8 套之间零重复。
// 题目内容与练习池一致（原创、程序验算），此处仅重编号用于独立计时模考。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const BMO_MK1_MCQ: MCQQuestion[] = [
  { id: "bmo-mk1-q01", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 1, marks: 4,
    question: "How many two-digit numbers are divisible by $7$?",
    options: [{ key: "A", text: "$14$" },{ key: "B", text: "$13$ 与 $14$ 都可能" },{ key: "C", text: "$11$" },{ key: "D", text: "$12$" },{ key: "E", text: "$13$" }],
    answer: "E", solution: "From $14=7\\times2$ to $98=7\\times14$: $14-2+1=13$." },
  { id: "bmo-mk1-q02", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 1, marks: 4,
    question: "Find the sum of the digits $1+2+\\cdots+9$.",
    options: [{ key: "A", text: "$44$" },{ key: "B", text: "$36$" },{ key: "C", text: "$45$" },{ key: "D", text: "$50$" },{ key: "E", text: "$55$" }],
    answer: "C", solution: "$\\dfrac{9\\times10}{2}=45$。" },
  { id: "bmo-mk1-q03", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 1, marks: 4,
    question: "A fair die is rolled once. Find the probability of NOT rolling a $6$.",
    options: [{ key: "A", text: "$\\dfrac45$" },{ key: "B", text: "$\\dfrac56$" },{ key: "C", text: "$\\dfrac12$" },{ key: "D", text: "$\\dfrac{5}{36}$" },{ key: "E", text: "$\\dfrac16$" }],
    answer: "B", solution: "$1-1/6=5/6$。" },
  { id: "bmo-mk1-q04", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "How many zeros does $30!$ end in?",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$7$" },{ key: "C", text: "$5$" },{ key: "D", text: "$6$" },{ key: "E", text: "$10$" }],
    answer: "B", solution: "Count factors of 5: $\\lfloor30/5\\rfloor+\\lfloor30/25\\rfloor=6+1=7$ (2s are plentiful)." },
  { id: "bmo-mk1-q05", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "Positive integers $x, y$ satisfy $xy = 2026$. What is the smallest possible value of $x+y$?",
    options: [{ key: "A", text: "$91$" },{ key: "B", text: "$507$" },{ key: "C", text: "$1013$" },{ key: "D", text: "$2027$" },{ key: "E", text: "$1015$" }],
    answer: "E", solution: "$2026=2\\times1013$（1013 素）：因数对只有 $(1,2026),(2,1013)$，和最小 $2+1013=1015$。" },
  { id: "bmo-mk1-q06", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Evaluate $\\log_2\\!\\left(8\\sqrt2\\right)$.",
    options: [{ key: "A", text: "$\\dfrac52$" },{ key: "B", text: "$4$" },{ key: "C", text: "$\\dfrac{7}{4}$" },{ key: "D", text: "$\\dfrac72$" },{ key: "E", text: "$3$" }],
    answer: "D", solution: "$8\\sqrt2=2^3\\cdot2^{1/2}=2^{7/2}$，故对数为 $\\tfrac72$。" },
  { id: "bmo-mk1-q07", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "Triangle $ABC$ is similar to triangle $DEF$ with ratio $2:3$. If the area of $ABC$ is $20$, find the area of $DEF$.",
    options: [{ key: "A", text: "$13\\tfrac13$" },{ key: "B", text: "$40$" },{ key: "C", text: "$30$" },{ key: "D", text: "$60$" },{ key: "E", text: "$45$" }],
    answer: "E", solution: "面积比为相似比平方 $4:9$：$20\\times\\tfrac94=45$。" },
  { id: "bmo-mk1-q08", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "A line has gradient $3$ and passes through $(2, 1)$. Where does it cross the $y$-axis?",
    options: [{ key: "A", text: "$(0, -6)$" },{ key: "B", text: "$(0, 7)$" },{ key: "C", text: "$(0, 5)$" },{ key: "D", text: "$(0, -1)$" },{ key: "E", text: "$(0, -5)$" }],
    answer: "E", solution: "$y=3x+c$ 过 $(2,1)$：$c=1-6=-5$。" },
  { id: "bmo-mk1-q09", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "What is the minimum number of people needed to guarantee that two of them were born in the same month?",
    options: [{ key: "A", text: "$13$" },{ key: "B", text: "$366$" },{ key: "C", text: "$24$" },{ key: "D", text: "$2$" },{ key: "E", text: "$12$" }],
    answer: "A", solution: "鸽笼原理：12 个月为「笼」，13 人必有同月。" },
  { id: "bmo-mk1-q10", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "From the digits $1,2,3,4$ (each used exactly once) how many four-digit numbers greater than $3000$ can be formed?",
    options: [{ key: "A", text: "$24$" },{ key: "B", text: "$8$" },{ key: "C", text: "$18$" },{ key: "D", text: "$6$" },{ key: "E", text: "$12$" }],
    answer: "E", solution: "首位为 3 或 4（2 种），其余 $3!=6$：$2\\times6=12$。" },
  { id: "bmo-mk1-q11", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "How many digits does $2026^2$ have?",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$14$" },{ key: "C", text: "$8$" },{ key: "D", text: "$6$" },{ key: "E", text: "$4$" }],
    answer: "A", solution: "$2026^2=4104676$：7 位。（估算：$2\\times10^3$ 平方 $\\approx4\\times10^6$。）" },
  { id: "bmo-mk1-q12", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Between which two consecutive integers does $\\log_2 10$ lie?",
    options: [{ key: "A", text: "$4$ 与 $5$" },{ key: "B", text: "$1$ 与 $2$" },{ key: "C", text: "$3$ 与 $4$" },{ key: "D", text: "$2$ 与 $3$" },{ key: "E", text: "$5$ 与 $6$" }],
    answer: "C", solution: "$2^3=8<10<16=2^4$。" },
  { id: "bmo-mk1-q13", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "Events $X$ and $Y$ are independent with $P(X)=\\tfrac12$, $P(Y)=\\tfrac13$. Find $P(X \\text{ and } Y)$.",
    options: [{ key: "A", text: "$\\dfrac16$" },{ key: "B", text: "$\\dfrac12$" },{ key: "C", text: "$\\dfrac13$" },{ key: "D", text: "$\\dfrac{2}{5}$" },{ key: "E", text: "$\\dfrac56$" }],
    answer: "A", solution: "独立事件相乘：$\\tfrac12\\times\\tfrac13=\\tfrac16$。" },
  { id: "bmo-mk1-q14", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The triangular numbers are $1, 3, 6, 10, \\dots$ Find the $8$th triangular number.",
    options: [{ key: "A", text: "$55$" },{ key: "B", text: "$36$" },{ key: "C", text: "$45$" },{ key: "D", text: "$28$" },{ key: "E", text: "$32$" }],
    answer: "B", solution: "$T_8=\\dfrac{8\\times9}{2}=36$。" },
  { id: "bmo-mk1-q15", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "How many integers $x$ satisfy $2 < 3x-1 < 11$?",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "无穷多" },{ key: "C", text: "$1$" },{ key: "D", text: "$4$" },{ key: "E", text: "$3$" }],
    answer: "A", solution: "$1<x<4$：$x=2,3$。" },
  { id: "bmo-mk1-q16", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Which is greater: $\\sqrt{50}$ or $7$?",
    options: [{ key: "A", text: "$\\sqrt{50}$（因为 $50>49$）" },{ key: "B", text: "$7$" },{ key: "C", text: "无法比较" },{ key: "D", text: "相等" },{ key: "E", text: "$\\sqrt{50}=7.5$" }],
    answer: "A", solution: "$7=\\sqrt{49}<\\sqrt{50}$。" },
  { id: "bmo-mk1-q17", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The line through $(1, 2)$ and $(3, 8)$ has gradient",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$\\dfrac13$" },{ key: "C", text: "$3$" },{ key: "D", text: "$6$" },{ key: "E", text: "$5$" }],
    answer: "C", solution: "$\\dfrac{8-2}{3-1}=3$。" },
  { id: "bmo-mk1-q18", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "If $y$ is inversely proportional to $x$ and $y=6$ when $x=2$, find $y$ when $x=4$.",
    options: [{ key: "A", text: "$1.5$" },{ key: "B", text: "$3$" },{ key: "C", text: "$12$" },{ key: "D", text: "$8$" },{ key: "E", text: "$4$" }],
    answer: "B", solution: "$xy=12$ 恒定：$y=12/4=3$。" },
  { id: "bmo-mk1-q19", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 3, marks: 4,
    question: "Two tangents are drawn to a circle from an external point, touching at $P$ and $Q$. If the angle between the tangents is $50°$, find $\\angle POQ$ ($O$ the centre).",
    options: [{ key: "A", text: "$100°$" },{ key: "B", text: "$65°$" },{ key: "C", text: "$140°$" },{ key: "D", text: "$130°$" },{ key: "E", text: "$50°$" }],
    answer: "D", solution: "四边形 $OP\\,(\\text{外点})\\,Q$ 中两个切点角为 $90°$：$\\angle POQ=360°-90°-90°-50°=130°$。" },
  { id: "bmo-mk1-q20", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "How many distinct arrangements are there of the letters of COFFEE?",
    options: [{ key: "A", text: "$180$" },{ key: "B", text: "$360$" },{ key: "C", text: "$90$" },{ key: "D", text: "$120$" },{ key: "E", text: "$720$" }],
    answer: "A", solution: "$\\dfrac{6!}{2!\\,2!}=\\dfrac{720}{4}=180$（F 和 E 各重复两次）。" },
  { id: "bmo-mk1-q21", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "In how many ways can the letters of LEVEL be arranged?",
    options: [{ key: "A", text: "$30$" },{ key: "B", text: "$20$" },{ key: "C", text: "$60$" },{ key: "D", text: "$120$" },{ key: "E", text: "$24$" }],
    answer: "A", solution: "$\\dfrac{5!}{2!\\,2!}=30$（L、E 各两个）。" },
  { id: "bmo-mk1-q22", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 3, marks: 4,
    question: "Find the smallest positive integer with exactly $15$ positive divisors.",
    options: [{ key: "A", text: "$120$" },{ key: "B", text: "$60$" },{ key: "C", text: "$144$" },{ key: "D", text: "$96$" },{ key: "E", text: "$210$" }],
    answer: "C", solution: "$15=3\\times5$ 或 $15$：形如 $p^{14}$ 或 $p^4q^2$。最小 $2^43^2=144$。" },
  { id: "bmo-mk1-q23", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "Two cards are drawn without replacement from a standard $52$-card pack. Find the probability that both are aces.",
    options: [{ key: "A", text: "$\\dfrac{1}{2652}$" },{ key: "B", text: "$\\dfrac{4}{52}$" },{ key: "C", text: "$\\dfrac{1}{221}$" },{ key: "D", text: "$\\dfrac{1}{169}$" },{ key: "E", text: "$\\dfrac{2}{52}$" }],
    answer: "C", solution: "$\\dfrac4{52}\\times\\dfrac3{51}=\\dfrac{12}{2652}=\\dfrac1{221}$。" },
  { id: "bmo-mk1-q24", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "Two people each pick a number at random from $\\{1,\\dots,10\\}$ (independently). Find the probability they pick the same number.",
    options: [{ key: "A", text: "$\\dfrac9{10}$" },{ key: "B", text: "$\\dfrac15$" },{ key: "C", text: "$\\dfrac{2}{10}$" },{ key: "D", text: "$\\dfrac1{10}$" },{ key: "E", text: "$\\dfrac1{100}$" }],
    answer: "D", solution: "无论第一人选什么，第二人猜中的概率都是 $1/10$。" },
  { id: "bmo-mk1-q25", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "If $x^2+y^2=8$, find the maximum value of $x+y$.",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$2\\sqrt2$" },{ key: "C", text: "$16$" },{ key: "D", text: "$\\sqrt8$" },{ key: "E", text: "$4$" }],
    answer: "E", solution: "$(x+y)^2\\le2(x^2+y^2)=16$（柯西/QM–AM），故 $x+y\\le4$，等号 $x=y=2$。" }
];
