// BMO/SMC 模拟卷 2 —— 从 205 道 SMC 练习池分段抽取、按难度升序装配、重编号（bmo-mk2-qNN），8 套之间零重复。
// 题目内容与练习池一致（原创、程序验算），此处仅重编号用于独立计时模考。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const BMO_MK2_MCQ: MCQQuestion[] = [
  { id: "bmo-mk2-q01", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 1, marks: 4,
    question: "If $f(x)=2x+3$, find $f(f(2))$.",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$11$" },{ key: "C", text: "$17$" },{ key: "D", text: "$21$" },{ key: "E", text: "$14$" }],
    answer: "C", solution: "$f(2)=7$，$f(7)=17$。" },
  { id: "bmo-mk2-q02", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 1, marks: 4,
    question: "Find the least common multiple of $12$ and $18$.",
    options: [{ key: "A", text: "$216$" },{ key: "B", text: "$54$" },{ key: "C", text: "$36$" },{ key: "D", text: "$72$" },{ key: "E", text: "$6$" }],
    answer: "C", solution: "$\\mathrm{lcm}=\\dfrac{12\\times18}{\\gcd}= \\dfrac{216}{6}=36$。" },
  { id: "bmo-mk2-q03", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 1, marks: 4,
    question: "An arithmetic sequence has first term $5$ and common difference $3$. Find the $10$th term.",
    options: [{ key: "A", text: "$35$" },{ key: "B", text: "$27$" },{ key: "C", text: "$32$" },{ key: "D", text: "$50$" },{ key: "E", text: "$30$" }],
    answer: "C", solution: "$a_{10}=5+9\\times3=32$。" },
  { id: "bmo-mk2-q04", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "What is $\\gcd(2026, 1352)$?",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$338$" },{ key: "C", text: "$13$" },{ key: "D", text: "$26$" },{ key: "E", text: "$1$" }],
    answer: "A", solution: "$2026=2\\times1013$（$1013$ 是素数），$1352=2^3\\times13^2$。公共部分只有一个 $2$。" },
  { id: "bmo-mk2-q05", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "What is the smallest positive integer that leaves remainder $2$ when divided by $3$, and remainder $3$ when divided by $5$?",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$23$" },{ key: "C", text: "$17$" },{ key: "D", text: "$13$" },{ key: "E", text: "$11$" }],
    answer: "A", solution: "逐个试或中国剩余：$8=3\\times2+2=5\\times1+3$ ✓，且 $<15$ 内唯一。" },
  { id: "bmo-mk2-q06", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Find the remainder when $x^3-2x+1$ is divided by $x-2$.",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$3$" },{ key: "C", text: "$1$" },{ key: "D", text: "$-3$" },{ key: "E", text: "$13$" }],
    answer: "A", solution: "余数定理：代入 $x=2$：$8-4+1=5$。" },
  { id: "bmo-mk2-q07", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "Find the length of the space diagonal of a cube with side $4$.",
    options: [{ key: "A", text: "$4\\sqrt3$" },{ key: "B", text: "$4\\sqrt2$" },{ key: "C", text: "$8$" },{ key: "D", text: "$12$" },{ key: "E", text: "$4$" }],
    answer: "A", solution: "$\\sqrt{4^2+4^2+4^2}=4\\sqrt3$。" },
  { id: "bmo-mk2-q08", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "The volume of a sphere is $36\\pi$. Find its radius.",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$3$" },{ key: "C", text: "$9$" },{ key: "D", text: "$2$" },{ key: "E", text: "$\\sqrt[3]{27\\pi}$" }],
    answer: "B", solution: "$\\tfrac43\\pi r^3=36\\pi\\Rightarrow r^3=27\\Rightarrow r=3$。" },
  { id: "bmo-mk2-q09", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "A quiz has $5$ yes/no questions. How many answer patterns have at least one \"yes\"?",
    options: [{ key: "A", text: "$31$" },{ key: "B", text: "$16$" },{ key: "C", text: "$25$" },{ key: "D", text: "$10$" },{ key: "E", text: "$32$" }],
    answer: "A", solution: "总 $2^5=32$ 减去全 no 的 1 种：$31$。" },
  { id: "bmo-mk2-q10", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "Find the sum of the digits of $2^{10}$.",
    options: [{ key: "A", text: "$10$" },{ key: "B", text: "$6$" },{ key: "C", text: "$8$" },{ key: "D", text: "$7$" },{ key: "E", text: "$16$" }],
    answer: "D", solution: "$2^{10}=1024$：$1+0+2+4=7$。" },
  { id: "bmo-mk2-q11", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "Three consecutive odd primes are $3, 5, 7$. Their sum is divisible by",
    options: [{ key: "A", text: "只有 $3$" },{ key: "B", text: "$3$ 和 $5$" },{ key: "C", text: "都不是" },{ key: "D", text: "只有 $5$" },{ key: "E", text: "$7$" }],
    answer: "B", solution: "和 $=15=3\\times5$。" },
  { id: "bmo-mk2-q12", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Two numbers have sum $5$ and product $6$. Find the larger number.",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$3$" },{ key: "C", text: "$6$" },{ key: "D", text: "$5$" },{ key: "E", text: "$4$" }],
    answer: "B", solution: "$t^2-5t+6=0$：$t=2,3$。" },
  { id: "bmo-mk2-q13", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "What is the mean (expected value) of a single roll of a fair six-sided die?",
    options: [{ key: "A", text: "$3.6$" },{ key: "B", text: "$4$" },{ key: "C", text: "$21$" },{ key: "D", text: "$3$" },{ key: "E", text: "$3.5$" }],
    answer: "E", solution: "$(1+\\cdots+6)/6=21/6=3.5$。" },
  { id: "bmo-mk2-q14", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "A sequence doubles each term: $1, 2, 4, 8, \\dots$ What is the first term to exceed $100$?",
    options: [{ key: "A", text: "$128$" },{ key: "B", text: "$102$" },{ key: "C", text: "$100$" },{ key: "D", text: "$256$" },{ key: "E", text: "$64$" }],
    answer: "A", solution: "$2^6=64<100<128=2^7$。" },
  { id: "bmo-mk2-q15", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Which is larger: $2^{300}$ or $3^{200}$?",
    options: [{ key: "A", text: "$3^{200}$" },{ key: "B", text: "$2^{300}$" },{ key: "C", text: "相等" },{ key: "D", text: "无法比较" },{ key: "E", text: "取决于底数" }],
    answer: "A", solution: "同取 100 次根：比较 $2^3=8$ 与 $3^2=9$：$9>8$，故 $3^{200}$ 大。" },
  { id: "bmo-mk2-q16", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The graph of $y=x^2$ is translated $3$ units right and $2$ units up. Its new equation is",
    options: [{ key: "A", text: "$y=x^2+3x+2$" },{ key: "B", text: "$y=(x-3)^2-2$" },{ key: "C", text: "$y=(x+3)^2-2$" },{ key: "D", text: "$y=(x-3)^2+2$" },{ key: "E", text: "$y=(x+3)^2+2$" }],
    answer: "D", solution: "右移用 $x-3$，上移加 2。" },
  { id: "bmo-mk2-q17", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Two lines are perpendicular. One has gradient $\\dfrac25$. The other has gradient",
    options: [{ key: "A", text: "$\\dfrac52$" },{ key: "B", text: "$\\dfrac{5}{2}$ 或 $-\\dfrac{2}{5}$ 都可以" },{ key: "C", text: "$1-\\dfrac25$" },{ key: "D", text: "$-\\dfrac52$" },{ key: "E", text: "$-\\dfrac25$" }],
    answer: "D", solution: "垂直斜率之积 $=-1$：$-\\dfrac52$。" },
  { id: "bmo-mk2-q18", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 3, marks: 4,
    question: "What is the number of digits of the smallest positive integer whose digits sum to $2026$?",
    options: [{ key: "A", text: "$225$" },{ key: "B", text: "$226$" },{ key: "C", text: "$227$" },{ key: "D", text: "$253$" },{ key: "E", text: "$2026$" }],
    answer: "B", solution: "贪心：尽量多用 9。$2026=225\\times9+1$，最小数是 $1$ 后跟 $225$ 个 $9$，共 $226$ 位。" },
  { id: "bmo-mk2-q19", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 3, marks: 4,
    question: "The line $y = 2x + c$ is tangent to the circle $x^2+y^2=5$. Find the positive value of $c$.",
    options: [{ key: "A", text: "$25$" },{ key: "B", text: "$3$" },{ key: "C", text: "$5$" },{ key: "D", text: "$2\\sqrt5$" },{ key: "E", text: "$\\sqrt5$" }],
    answer: "C", solution: "圆心到直线距离等于半径：$\\dfrac{|c|}{\\sqrt{1+4}}=\\sqrt5\\Rightarrow|c|=5$。" },
  { id: "bmo-mk2-q20", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "A committee of $2$ boys and $2$ girls is chosen from $4$ boys and $5$ girls. How many committees are possible?",
    options: [{ key: "A", text: "$36$" },{ key: "B", text: "$126$" },{ key: "C", text: "$60$" },{ key: "D", text: "$120$" },{ key: "E", text: "$30$" }],
    answer: "C", solution: "$\\binom42\\times\\binom52=6\\times10=60$。" },
  { id: "bmo-mk2-q21", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "In how many ways can $6$ players be split into two unlabelled teams of $3$?",
    options: [{ key: "A", text: "$10$" },{ key: "B", text: "$40$" },{ key: "C", text: "$20$" },{ key: "D", text: "$15$" },{ key: "E", text: "$60$" }],
    answer: "A", solution: "$\\dfrac{\\binom63}{2}=10$（两队不区分名字，除以 2）。" },
  { id: "bmo-mk2-q22", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 3, marks: 4,
    question: "$1013$ is prime. What is the remainder when $1013$ is divided by $4$, and can $1013$ be written as a sum of two squares?",
    options: [{ key: "A", text: "余 $3$；可以" },{ key: "B", text: "余 $1$；可以（$1013 = 22^2 + 23^2$）" },{ key: "C", text: "余 $3$；不可以" },{ key: "D", text: "余 $1$；不可以" },{ key: "E", text: "余 $2$；可以" }],
    answer: "B", solution: "$1013=4\\times253+1$。$p\\equiv1\\pmod4$ 的素数必可表为两平方和：$484+529=1013$ ✓。" },
  { id: "bmo-mk2-q23", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "A fair die is rolled three times. Find the probability of rolling at least one six.",
    options: [{ key: "A", text: "$\\dfrac12$" },{ key: "B", text: "$\\dfrac{91}{216}$" },{ key: "C", text: "$\\dfrac{3}{6}$" },{ key: "D", text: "$\\dfrac{1}{216}$" },{ key: "E", text: "$\\dfrac{125}{216}$" }],
    answer: "B", solution: "$1-(5/6)^3=1-125/216=91/216$。" },
  { id: "bmo-mk2-q24", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "A sequence has $a_1=2$ and $a_{n+1}=3a_n-2$. Find $a_5$.",
    options: [{ key: "A", text: "$28$" },{ key: "B", text: "$80$" },{ key: "C", text: "$54$" },{ key: "D", text: "$82$" },{ key: "E", text: "$164$" }],
    answer: "D", solution: "$2,4,10,28,82$（每步 $\\times3-2$；亦可看出 $a_n=3^{n-1}+1$）。" },
  { id: "bmo-mk2-q25", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "For $0<x<1$, arrange in increasing order: $x,\\ x^2,\\ \\sqrt x$.",
    options: [{ key: "A", text: "$x^2<\\sqrt x<x$" },{ key: "B", text: "$\\sqrt x<x<x^2$" },{ key: "C", text: "$x<x^2<\\sqrt x$" },{ key: "D", text: "三者相等" },{ key: "E", text: "$x^2 < x < \\sqrt x$" }],
    answer: "E", solution: "$0<x<1$ 时幂次越高越小：$x^2<x<\\sqrt x$（如 $x=\\tfrac14$：$\\tfrac1{16}<\\tfrac14<\\tfrac12$）。" }
];
