// BMO/SMC 模拟卷 8 —— 从 205 道 SMC 练习池分段抽取、按难度升序装配、重编号（bmo-mk8-qNN），8 套之间零重复。
// 题目内容与练习池一致（原创、程序验算），此处仅重编号用于独立计时模考。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const BMO_MK8_MCQ: MCQQuestion[] = [
  { id: "bmo-mk8-q01", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 1, marks: 4,
    question: "How many three-digit numbers are there?",
    options: [{ key: "A", text: "$999$" },{ key: "B", text: "$899$" },{ key: "C", text: "$100$" },{ key: "D", text: "$1000$" },{ key: "E", text: "$900$" }],
    answer: "E", solution: "$100$ 到 $999$：$9\\times10\\times10=900$。" },
  { id: "bmo-mk8-q02", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 1, marks: 4,
    question: "A box has $3$ red and $4$ green counters. Find the probability of drawing a green one.",
    options: [{ key: "A", text: "$\\dfrac13$" },{ key: "B", text: "$\\dfrac37$" },{ key: "C", text: "$\\dfrac47$" },{ key: "D", text: "$\\dfrac14$" },{ key: "E", text: "$\\dfrac34$" }],
    answer: "C", solution: "$4/7$。" },
  { id: "bmo-mk8-q03", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "What is the last digit of $3^{2026}$?",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$3$" },{ key: "C", text: "$27$" },{ key: "D", text: "$7$" },{ key: "E", text: "$1$" }],
    answer: "A", solution: "Last digits of $3^k$ cycle with period 4: $3,9,7,1$. $2026\\equiv2\\pmod4$, so last digit $=9$." },
  { id: "bmo-mk8-q04", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "How many perfect squares lie strictly between $100$ and $1000$?",
    options: [{ key: "A", text: "$22$" },{ key: "B", text: "$31$" },{ key: "C", text: "$21$" },{ key: "D", text: "$20$" },{ key: "E", text: "$19$" }],
    answer: "C", solution: "$11^2=121$ 到 $31^2=961$：$31-11+1=21$ 个（$10^2=100$ 不算「strictly between」）。" },
  { id: "bmo-mk8-q05", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "How many integers $x$ satisfy $|2x-7|<5$?",
    options: [{ key: "A", text: "无穷多" },{ key: "B", text: "$3$" },{ key: "C", text: "$4$" },{ key: "D", text: "$6$" },{ key: "E", text: "$5$" }],
    answer: "C", solution: "$-5<2x-7<5\\Rightarrow1<x<6$：整数 $2,3,4,5$，共 4 个。" },
  { id: "bmo-mk8-q06", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "Find the area of a regular hexagon with side length $2$.",
    options: [{ key: "A", text: "$4\\sqrt3$" },{ key: "B", text: "$6\\sqrt3$" },{ key: "C", text: "$3\\sqrt3$" },{ key: "D", text: "$12$" },{ key: "E", text: "$12\\sqrt3$" }],
    answer: "B", solution: "六个边长 2 的正三角形：$6\\times\\dfrac{\\sqrt3}{4}\\times4=6\\sqrt3$。" },
  { id: "bmo-mk8-q07", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "Find the midpoint of $A(-3, 5)$ and $B(7, -1)$.",
    options: [{ key: "A", text: "$(4, 2)$" },{ key: "B", text: "$(2, 2)$" },{ key: "C", text: "$(5, 3)$" },{ key: "D", text: "$(5, 2)$" },{ key: "E", text: "$(2, 3)$" }],
    answer: "B", solution: "中点 $\\left(\\dfrac{-3+7}{2},\\dfrac{5-1}{2}\\right)=(2,2)$。" },
  { id: "bmo-mk8-q08", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "How many three-digit codes can be made using digits from $\\{1,2,3,4,5\\}$ without repetition?",
    options: [{ key: "A", text: "$25$" },{ key: "B", text: "$125$" },{ key: "C", text: "$60$" },{ key: "D", text: "$100$" },{ key: "E", text: "$120$" }],
    answer: "C", solution: "$5\\times4\\times3=60$。" },
  { id: "bmo-mk8-q09", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "Each of $4$ questions on a test has $3$ choices. In how many ways can the test be answered (all questions answered)?",
    options: [{ key: "A", text: "$64$" },{ key: "B", text: "$27$" },{ key: "C", text: "$81$" },{ key: "D", text: "$12$" },{ key: "E", text: "$243$" }],
    answer: "C", solution: "$3^4=81$。" },
  { id: "bmo-mk8-q10", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "What is the $10$th prime number?",
    options: [{ key: "A", text: "$23$" },{ key: "B", text: "$27$" },{ key: "C", text: "$31$" },{ key: "D", text: "$37$" },{ key: "E", text: "$29$" }],
    answer: "E", solution: "$2,3,5,7,11,13,17,19,23,29$。" },
  { id: "bmo-mk8-q11", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "If $\\log_{10} x = 2$, find $x$.",
    options: [{ key: "A", text: "$20$" },{ key: "B", text: "$1000$" },{ key: "C", text: "$100$" },{ key: "D", text: "$2$" },{ key: "E", text: "$0.01$" }],
    answer: "C", solution: "$x=10^2=100$。" },
  { id: "bmo-mk8-q12", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "A fair coin is tossed $4$ times. Find the probability of getting at least one tail.",
    options: [{ key: "A", text: "$\\dfrac{1}{16}$" },{ key: "B", text: "$\\dfrac{13}{16}$" },{ key: "C", text: "$\\dfrac{15}{16}$" },{ key: "D", text: "$\\dfrac{3}{4}$" },{ key: "E", text: "$\\dfrac{7}{8}$" }],
    answer: "C", solution: "$1-P(\\text{全正})=1-1/16$。" },
  { id: "bmo-mk8-q13", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Evaluate $\\dfrac12+\\dfrac14+\\cdots+\\dfrac{1}{1024}$.",
    options: [{ key: "A", text: "$\\dfrac{1024}{1023}$" },{ key: "B", text: "$\\dfrac{1023}{1024}$" },{ key: "C", text: "$\\dfrac{511}{512}$" },{ key: "D", text: "$\\dfrac{1}{1024}$" },{ key: "E", text: "$1$" }],
    answer: "B", solution: "$1-\\dfrac1{1024}=\\dfrac{1023}{1024}$。" },
  { id: "bmo-mk8-q14", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Two positive numbers have sum $10$. Find the maximum value of their product.",
    options: [{ key: "A", text: "$50$" },{ key: "B", text: "$20$" },{ key: "C", text: "$100$" },{ key: "D", text: "$24$" },{ key: "E", text: "$25$" }],
    answer: "E", solution: "定和最大积在相等：$5\\times5=25$。" },
  { id: "bmo-mk8-q15", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The sides of a triangle are $5$, $9$ and $x$ (an integer). How many values can $x$ take?",
    options: [{ key: "A", text: "$13$" },{ key: "B", text: "$9$" },{ key: "C", text: "$10$" },{ key: "D", text: "$8$" },{ key: "E", text: "$7$" }],
    answer: "B", solution: "三角不等式：$4<x<14$，整数 $5\\dots13$ 共 9 个。" },
  { id: "bmo-mk8-q16", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "How many solutions does $|x| = 3$ have? And $|x| = -3$?",
    options: [{ key: "A", text: "$2$ 个；$0$ 个" },{ key: "B", text: "$1$ 个；$0$ 个" },{ key: "C", text: "$1$ 个；$1$ 个" },{ key: "D", text: "$2$ 个；$1$ 个" },{ key: "E", text: "$2$ 个；$2$ 个" }],
    answer: "A", solution: "绝对值非负：$|x|=3$ 给 $\\pm3$；$|x|=-3$ 无解。" },
  { id: "bmo-mk8-q17", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Solve $4^x = 2^{x+4}$.",
    options: [{ key: "A", text: "$x=\\dfrac43$" },{ key: "B", text: "$x=2$" },{ key: "C", text: "$x=8$" },{ key: "D", text: "$x=4$" },{ key: "E", text: "$x=1$" }],
    answer: "D", solution: "$2^{2x}=2^{x+4}\\Rightarrow2x=x+4\\Rightarrow x=4$。" },
  { id: "bmo-mk8-q18", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 3, marks: 4,
    question: "A square is inscribed in a circle of radius $r$. Find the ratio of the square's area to the circle's area.",
    options: [{ key: "A", text: "$\\dfrac{\\sqrt2}{\\pi}$" },{ key: "B", text: "$\\dfrac{1}{\\pi}$" },{ key: "C", text: "$\\dfrac{2}{\\pi}$" },{ key: "D", text: "$\\dfrac{\\pi}{4}$" },{ key: "E", text: "$\\dfrac{4}{\\pi}$" }],
    answer: "C", solution: "内接正方形对角线 $=2r$，边 $=r\\sqrt2$，面积 $2r^2$；比 $\\dfrac{2r^2}{\\pi r^2}=\\dfrac2\\pi$。" },
  { id: "bmo-mk8-q19", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 3, marks: 4,
    question: "The sides of a triangle are $7$, $8$, $9$. Is the largest angle acute, right or obtuse?",
    options: [{ key: "A", text: "钝角" },{ key: "B", text: "锐角（acute）——因为 $7^2+8^2 > 9^2$" },{ key: "C", text: "直角" },{ key: "D", text: "等于 $90°$" },{ key: "E", text: "无法判断" }],
    answer: "B", solution: "$49+64=113>81$：最大角的余弦为正 → 锐角三角形。" },
  { id: "bmo-mk8-q20", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "How many three-digit numbers have at least one repeated digit?",
    options: [{ key: "A", text: "$648$" },{ key: "B", text: "$252$" },{ key: "C", text: "$225$" },{ key: "D", text: "$900$" },{ key: "E", text: "$180$" }],
    answer: "B", solution: "全不同：$9\\times9\\times8=648$；$900-648=252$。" },
  { id: "bmo-mk8-q21", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 3, marks: 4,
    question: "Find the last two digits of $7^{4}$.",
    options: [{ key: "A", text: "$07$" },{ key: "B", text: "$43$" },{ key: "C", text: "$21$" },{ key: "D", text: "$01$" },{ key: "E", text: "$49$" }],
    answer: "D", solution: "$7^4=2401$：末两位 $01$（因此 $7^{4k}$ 末两位恒为 01——周期性）。" },
  { id: "bmo-mk8-q22", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "If $f(x)=x^2-4x+7$, find the minimum value of $f(f(x))$ over all real $x$.",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$4$" },{ key: "C", text: "$10$" },{ key: "D", text: "$19$" },{ key: "E", text: "$3$" }],
    answer: "B", solution: "$f(x)=(x-2)^2+3$ 的值域是 $[3,\\infty)$。而 $f(t)$ 的顶点在 $t=2$，故在 $t\\ge3$ 上单调递增：最小值在 $t=3$ 处取得，$f(3)=9-12+7=4$。" },
  { id: "bmo-mk8-q23", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "A drawer has $2$ red and $3$ blue socks. Two are taken at random. Find the probability both are red.",
    options: [{ key: "A", text: "$\\dfrac{2}{5}$" },{ key: "B", text: "$\\dfrac{4}{25}$" },{ key: "C", text: "$\\dfrac{1}{4}$" },{ key: "D", text: "$\\dfrac1{10}$" },{ key: "E", text: "$\\dfrac15$" }],
    answer: "D", solution: "$\\binom22/\\binom52=1/10$。" },
  { id: "bmo-mk8-q24", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "For positive reals with $abc=27$, the minimum of $a+b+c$ is",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$9$" },{ key: "C", text: "$27$" },{ key: "D", text: "$81$" },{ key: "E", text: "$3\\sqrt3$" }],
    answer: "B", solution: "三元 AM–GM：$a+b+c\\ge3\\sqrt[3]{abc}=3\\times3=9$，等号 $a=b=c=3$。" },
  { id: "bmo-mk8-q25", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "The cubic $y=x^3-3x$ has how many turning points?",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$0$" },{ key: "C", text: "$3$" },{ key: "D", text: "$2$" },{ key: "E", text: "无穷多" }],
    answer: "D", solution: "$y'=3x^2-3=0$ 给 $x=\\pm1$：一极大一极小。" }
];
