// BMO/SMC 模拟卷 4 —— 从 205 道 SMC 练习池分段抽取、按难度升序装配、重编号（bmo-mk4-qNN），8 套之间零重复。
// 题目内容与练习池一致（原创、程序验算），此处仅重编号用于独立计时模考。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const BMO_MK4_MCQ: MCQQuestion[] = [
  { id: "bmo-mk4-q01", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 1, marks: 4,
    question: "Find the interior angle of a regular octagon.",
    options: [{ key: "A", text: "$150°$" },{ key: "B", text: "$135°$" },{ key: "C", text: "$144°$" },{ key: "D", text: "$120°$" },{ key: "E", text: "$108°$" }],
    answer: "B", solution: "内角 $=\\dfrac{180°(n-2)}{n}=\\dfrac{180°\\times6}{8}=135°$。" },
  { id: "bmo-mk4-q02", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 1, marks: 4,
    question: "Evaluate $7^2 - 3^2$ using the difference of two squares.",
    options: [{ key: "A", text: "$13$" },{ key: "B", text: "$16$" },{ key: "C", text: "$46$" },{ key: "D", text: "$40$" },{ key: "E", text: "$58$" }],
    answer: "D", solution: "$(7-3)(7+3)=4\\times10=40$。" },
  { id: "bmo-mk4-q03", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 1, marks: 4,
    question: "Find the sum of the first $10$ even numbers $2+4+\\cdots+20$.",
    options: [{ key: "A", text: "$100$" },{ key: "B", text: "$120$" },{ key: "C", text: "$55$" },{ key: "D", text: "$110$" },{ key: "E", text: "$90$" }],
    answer: "D", solution: "$2(1+\\cdots+10)=2\\times55=110$。" },
  { id: "bmo-mk4-q04", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "What is the remainder when $7^{100}$ is divided by $5$?",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$4$" },{ key: "C", text: "$0$" },{ key: "D", text: "$3$" },{ key: "E", text: "$2$" }],
    answer: "A", solution: "$7\\equiv2\\pmod5$，$2^4=16\\equiv1$，而 $100$ 是 $4$ 的倍数，故余 $1$。" },
  { id: "bmo-mk4-q05", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Solve $\\sqrt{x+5} = x-1$.",
    options: [{ key: "A", text: "$x=4$" },{ key: "B", text: "$x=5$" },{ key: "C", text: "$x=-1$" },{ key: "D", text: "无解" },{ key: "E", text: "$x=4$ 或 $x=-1$" }],
    answer: "A", solution: "平方得 $x^2-3x-4=0$，$x=4$ 或 $-1$；但需 $x-1\\ge0$，舍去 $-1$。验证 $\\sqrt9=3=4-1$ ✓。" },
  { id: "bmo-mk4-q06", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Simplify $\\left(\\sqrt5+\\sqrt3\\right)^2-\\left(\\sqrt5-\\sqrt3\\right)^2$.",
    options: [{ key: "A", text: "$2\\sqrt{15}$" },{ key: "B", text: "$4$" },{ key: "C", text: "$4\\sqrt{15}$" },{ key: "D", text: "$8\\sqrt2$" },{ key: "E", text: "$16$" }],
    answer: "C", solution: "平方差：$(a+b)^2-(a-b)^2=4ab=4\\sqrt{15}$。" },
  { id: "bmo-mk4-q07", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "The exterior angle of a regular polygon is $24°$. How many sides does it have?",
    options: [{ key: "A", text: "$18$" },{ key: "B", text: "$15$" },{ key: "C", text: "$10$" },{ key: "D", text: "$12$" },{ key: "E", text: "$24$" }],
    answer: "B", solution: "$n=360°/24°=15$。" },
  { id: "bmo-mk4-q08", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "The angles of a triangle are in the ratio $2:3:4$. Find the largest angle.",
    options: [{ key: "A", text: "$72°$" },{ key: "B", text: "$100°$" },{ key: "C", text: "$60°$" },{ key: "D", text: "$90°$" },{ key: "E", text: "$80°$" }],
    answer: "E", solution: "和 $180°$ 按 $2:3:4$ 分：$4\\times20°=80°$。" },
  { id: "bmo-mk4-q09", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "Each of $3$ children independently chooses one of $4$ ice-cream flavours. How many outcomes are possible?",
    options: [{ key: "A", text: "$24$" },{ key: "B", text: "$64$" },{ key: "C", text: "$36$" },{ key: "D", text: "$12$" },{ key: "E", text: "$81$" }],
    answer: "B", solution: "$4^3=64$。" },
  { id: "bmo-mk4-q10", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "How many integers from $1$ to $100$ are divisible by $3$ or $5$?",
    options: [{ key: "A", text: "$20$" },{ key: "B", text: "$33$" },{ key: "C", text: "$47$" },{ key: "D", text: "$50$" },{ key: "E", text: "$53$" }],
    answer: "C", solution: "容斥：$33+20-6=47$。" },
  { id: "bmo-mk4-q11", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "How many real solutions does $x^4-5x^2+4=0$ have?",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$0$" },{ key: "C", text: "$3$" },{ key: "D", text: "$2$" },{ key: "E", text: "$1$" }],
    answer: "A", solution: "令 $u=x^2$：$u=1,4$ → $x=\\pm1,\\pm2$：4 个。" },
  { id: "bmo-mk4-q12", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "Two fair dice are rolled. Find the probability that at least one shows a six.",
    options: [{ key: "A", text: "$\\dfrac1{36}$" },{ key: "B", text: "$\\dfrac{11}{36}$" },{ key: "C", text: "$\\dfrac13$" },{ key: "D", text: "$\\dfrac{12}{36}$" },{ key: "E", text: "$\\dfrac16$" }],
    answer: "B", solution: "补集：都不是 6 的概率 $\\left(\\tfrac56\\right)^2=\\tfrac{25}{36}$，故 $1-\\tfrac{25}{36}=\\tfrac{11}{36}$。" },
  { id: "bmo-mk4-q13", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "A geometric sequence has first term $3$ and common ratio $2$. Find the $10$th term.",
    options: [{ key: "A", text: "$512$" },{ key: "B", text: "$1536$" },{ key: "C", text: "$3072$" },{ key: "D", text: "$1024$" },{ key: "E", text: "$768$" }],
    answer: "B", solution: "$a_{10}=3\\times2^9=1536$。" },
  { id: "bmo-mk4-q14", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The sequence $a_n = n^2+n$ begins $2, 6, 12, 20, \\dots$ Which term equals $110$?",
    options: [{ key: "A", text: "第 $9$ 项" },{ key: "B", text: "没有这一项" },{ key: "C", text: "第 $12$ 项" },{ key: "D", text: "第 $10$ 项" },{ key: "E", text: "第 $11$ 项" }],
    answer: "D", solution: "$n^2+n=110\\Rightarrow n(n+1)=110=10\\times11\\Rightarrow n=10$。" },
  { id: "bmo-mk4-q15", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "If $a>b$ and $c<0$, which is always true?",
    options: [{ key: "A", text: "$ac<bc$" },{ key: "B", text: "$a+c<b+c$" },{ key: "C", text: "$ac>bc$" },{ key: "D", text: "$a^2>b^2$" },{ key: "E", text: "$\\dfrac ac>\\dfrac bc$" }],
    answer: "A", solution: "乘负数翻转不等号。" },
  { id: "bmo-mk4-q16", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The graphs of $y=x^2$ and $y=2x+3$ intersect at how many points?",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$0$" },{ key: "C", text: "$3$" },{ key: "D", text: "无穷多" },{ key: "E", text: "$1$" }],
    answer: "A", solution: "$x^2-2x-3=(x-3)(x+1)=0$：两交点。" },
  { id: "bmo-mk4-q17", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "How many times do the graphs of $y=\\dfrac1x$ and $y=x$ intersect?",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$2$" },{ key: "C", text: "无穷多" },{ key: "D", text: "$3$" },{ key: "E", text: "$0$" }],
    answer: "B", solution: "$x^2=1$：$(1,1)$ 与 $(-1,-1)$。" },
  { id: "bmo-mk4-q18", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 3, marks: 4,
    question: "Find the sum of all primes $p < 100$ such that $p^2+2$ is also prime.",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$14$" },{ key: "C", text: "$8$" },{ key: "D", text: "$0$" },{ key: "E", text: "$3$" }],
    answer: "E", solution: "$p\\ne3$ 时 $p^2\\equiv1\\pmod3$，故 $p^2+2\\equiv0\\pmod3$ 且 $>3$，必为合数。只剩 $p=3$：$9+2=11$ 素 ✓。和为 $3$。" },
  { id: "bmo-mk4-q19", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 3, marks: 4,
    question: "A rectangle has perimeter $28$ and diagonal $10$. Find its area.",
    options: [{ key: "A", text: "$96$" },{ key: "B", text: "$48$" },{ key: "C", text: "$24$" },{ key: "D", text: "$40$" },{ key: "E", text: "$50$" }],
    answer: "B", solution: "$a+b=14$，$a^2+b^2=100$：$ab=\\dfrac{14^2-100}{2}=48$。" },
  { id: "bmo-mk4-q20", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "Five different letters are placed into five addressed envelopes at random, one per envelope. In how many ways can this be done so that NO letter is in its correct envelope?",
    options: [{ key: "A", text: "$120$" },{ key: "B", text: "$44$" },{ key: "C", text: "$24$" },{ key: "D", text: "$45$" },{ key: "E", text: "$76$" }],
    answer: "B", solution: "错排数 $D_5=44$（$D_n=n!\\sum(-1)^k/k!$：$120(1-1+\\tfrac12-\\tfrac16+\\tfrac1{24}-\\tfrac1{120})=44$）。" },
  { id: "bmo-mk4-q21", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "A $4\\times4$ grid of unit squares is drawn. How many rectangles (of all sizes, including squares) does the figure contain?",
    options: [{ key: "A", text: "$36$" },{ key: "B", text: "$70$" },{ key: "C", text: "$100$" },{ key: "D", text: "$16$" },{ key: "E", text: "$1296$" }],
    answer: "C", solution: "矩形由 5 条横线选 2、5 条竖线选 2 决定：$\\binom52^2=100$。" },
  { id: "bmo-mk4-q22", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 3, marks: 4,
    question: "Two positive integers differ by $2$ and their squares differ by $72$. Find the larger one.",
    options: [{ key: "A", text: "$20$" },{ key: "B", text: "$36$" },{ key: "C", text: "$17$" },{ key: "D", text: "$18$" },{ key: "E", text: "$19$" }],
    answer: "E", solution: "$a^2-b^2=(a+b)(a-b)=2(a+b)=72\\Rightarrow a+b=36$，$a-b=2$：$a=19$。" },
  { id: "bmo-mk4-q23", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "Three fair dice are rolled. Find the probability that all three show the same number.",
    options: [{ key: "A", text: "$\\dfrac{1}{36}$" },{ key: "B", text: "$\\dfrac{1}{216}$" },{ key: "C", text: "$\\dfrac{1}{18}$" },{ key: "D", text: "$\\dfrac{1}{6}$" },{ key: "E", text: "$\\dfrac{3}{216}$" }],
    answer: "A", solution: "$6/216=1/36$（第一枚任意，后两枚各 $1/6$）。" },
  { id: "bmo-mk4-q24", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "Let $S_n=1+2+\\cdots+n$. Find $S_{100}-S_{99}$.",
    options: [{ key: "A", text: "$99$" },{ key: "B", text: "$100$" },{ key: "C", text: "$5050$" },{ key: "D", text: "$1$" },{ key: "E", text: "$199$" }],
    answer: "B", solution: "$S_{100}-S_{99}=$ 第 100 项本身 $=100$。" },
  { id: "bmo-mk4-q25", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "For positive $a, b$, find the minimum value of $(a+b)\\left(\\dfrac1a+\\dfrac1b\\right)$.",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$16$" },{ key: "C", text: "$4$" },{ key: "D", text: "$1$" },{ key: "E", text: "$2$" }],
    answer: "C", solution: "展开 $=2+\\dfrac ab+\\dfrac ba\\ge2+2=4$（AM–GM），等号 $a=b$。" }
];
