// BMO/SMC 模拟卷 7 —— 从 205 道 SMC 练习池分段抽取、按难度升序装配、重编号（bmo-mk7-qNN），8 套之间零重复。
// 题目内容与练习池一致（原创、程序验算），此处仅重编号用于独立计时模考。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const BMO_MK7_MCQ: MCQQuestion[] = [
  { id: "bmo-mk7-q01", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 1, marks: 4,
    question: "In how many ways can $5$ different books be arranged on a shelf?",
    options: [{ key: "A", text: "$100$" },{ key: "B", text: "$720$" },{ key: "C", text: "$120$" },{ key: "D", text: "$60$" },{ key: "E", text: "$25$" }],
    answer: "C", solution: "$5!=120$。" },
  { id: "bmo-mk7-q02", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 1, marks: 4,
    question: "A bag contains $5$ red and $4$ blue balls. One ball is drawn at random. Find the probability it is red.",
    options: [{ key: "A", text: "$\\dfrac15$" },{ key: "B", text: "$\\dfrac59$" },{ key: "C", text: "$\\dfrac54$" },{ key: "D", text: "$\\dfrac49$" },{ key: "E", text: "$\\dfrac12$" }],
    answer: "B", solution: "$5/(5+4)=5/9$。" },
  { id: "bmo-mk7-q03", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 1, marks: 4,
    question: "The graph of $y=x^2-9$ crosses the $x$-axis at",
    options: [{ key: "A", text: "$x=9$" },{ key: "B", text: "$x=\\pm3$" },{ key: "C", text: "$x=\\pm9$" },{ key: "D", text: "$x=3$ 仅" },{ key: "E", text: "$x=0$" }],
    answer: "B", solution: "$x^2=9$。" },
  { id: "bmo-mk7-q04", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "What is the units digit of $1!+2!+3!+\\cdots+2026!$?",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$7$" },{ key: "C", text: "$0$" },{ key: "D", text: "$9$" },{ key: "E", text: "$3$" }],
    answer: "E", solution: "$5!$ 起个位全为 0：$1+2+6+24=33$，个位 $3$。" },
  { id: "bmo-mk7-q05", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "If $x+y=10$ and $x^2-y^2=40$, find $x$.",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$7$" },{ key: "C", text: "$4$" },{ key: "D", text: "$3$" },{ key: "E", text: "$6$" }],
    answer: "B", solution: "$x^2-y^2=(x+y)(x-y)=10(x-y)=40\\Rightarrow x-y=4$；与 $x+y=10$ 联立得 $x=7$。" },
  { id: "bmo-mk7-q06", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "The angle subtended by an arc at the centre is $80°$. What angle does the same arc subtend at a point on the major arc?",
    options: [{ key: "A", text: "$20°$" },{ key: "B", text: "$80°$" },{ key: "C", text: "$100°$" },{ key: "D", text: "$160°$" },{ key: "E", text: "$40°$" }],
    answer: "E", solution: "圆心角是圆周角的两倍：$80°/2=40°$。" },
  { id: "bmo-mk7-q07", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "Points $A(1,2)$ and $B(7,10)$ are given. Find the distance $AB$.",
    options: [{ key: "A", text: "$14$" },{ key: "B", text: "$\\sqrt{52}$" },{ key: "C", text: "$10$" },{ key: "D", text: "$6$" },{ key: "E", text: "$8$" }],
    answer: "C", solution: "$\\sqrt{6^2+8^2}=10$。" },
  { id: "bmo-mk7-q08", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "Eight people at a party all shake hands with each other exactly once. How many handshakes take place?",
    options: [{ key: "A", text: "$56$" },{ key: "B", text: "$36$" },{ key: "C", text: "$64$" },{ key: "D", text: "$28$" },{ key: "E", text: "$16$" }],
    answer: "D", solution: "$\\binom82=28$。" },
  { id: "bmo-mk7-q09", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "Twelve points in the plane, no three collinear. How many straight lines pass through exactly two of them?",
    options: [{ key: "A", text: "$24$" },{ key: "B", text: "$132$" },{ key: "C", text: "$66$" },{ key: "D", text: "$78$" },{ key: "E", text: "$144$" }],
    answer: "C", solution: "$\\binom{12}2=66$。" },
  { id: "bmo-mk7-q10", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "How many primes less than $50$ have units digit $7$?",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$6$" },{ key: "C", text: "$2$" },{ key: "D", text: "$5$" },{ key: "E", text: "$3$" }],
    answer: "A", solution: "$7,17,37,47$（27 非素）。" },
  { id: "bmo-mk7-q11", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Solve $x^2 = x+6$. What is the sum of the solutions?",
    options: [{ key: "A", text: "$-1$" },{ key: "B", text: "$1$" },{ key: "C", text: "$0$" },{ key: "D", text: "$6$" },{ key: "E", text: "$5$" }],
    answer: "B", solution: "$x^2-x-6=0$：韦达 $\\alpha+\\beta=1$（解为 $3,-2$）。" },
  { id: "bmo-mk7-q12", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "Two fair dice are rolled. Find the probability that the sum is even.",
    options: [{ key: "A", text: "$\\dfrac13$" },{ key: "B", text: "$\\dfrac{17}{36}$" },{ key: "C", text: "$\\dfrac12$" },{ key: "D", text: "$\\dfrac{18}{35}$" },{ key: "E", text: "$\\dfrac59$" }],
    answer: "C", solution: "两奇或两偶：$\\tfrac12\\cdot\\tfrac12+\\tfrac12\\cdot\\tfrac12=\\tfrac12$。" },
  { id: "bmo-mk7-q13", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The $n$th odd number is $2n-1$. What is the $2026$th odd number?",
    options: [{ key: "A", text: "$4051$" },{ key: "B", text: "$4052$" },{ key: "C", text: "$2025$" },{ key: "D", text: "$4053$" },{ key: "E", text: "$2026$" }],
    answer: "A", solution: "$2\\times2026-1=4051$。" },
  { id: "bmo-mk7-q14", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "For $x>0$, find the minimum value of $x+\\dfrac1x$.",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$2$" },{ key: "C", text: "没有最小值" },{ key: "D", text: "$0$" },{ key: "E", text: "$\\dfrac12$" }],
    answer: "B", solution: "AM–GM：$x+\\dfrac1x\\ge2\\sqrt{x\\cdot\\tfrac1x}=2$，等号在 $x=1$。" },
  { id: "bmo-mk7-q15", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "If $0<a<b$, which of these is the largest?",
    options: [{ key: "A", text: "$\\dfrac{a}{a+b}$" },{ key: "B", text: "$\\dfrac{b}{a}$" },{ key: "C", text: "$\\dfrac{a+1}{b+1}$" },{ key: "D", text: "$1$" },{ key: "E", text: "$\\dfrac{a}{b}$" }],
    answer: "B", solution: "$b/a>1$ 而其余各项均 $\\le1$（$\\tfrac{a+1}{b+1}<1$ 因 $a<b$）。" },
  { id: "bmo-mk7-q16", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The equation $x^2+y^2-6x+8y=0$ represents a circle. Find its radius.",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$25$" },{ key: "C", text: "$7$" },{ key: "D", text: "$\\sqrt{10}$" },{ key: "E", text: "$10$" }],
    answer: "A", solution: "配方 $(x-3)^2+(y+4)^2=25$：半径 5（过原点）。" },
  { id: "bmo-mk7-q17", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The graph of $y=2^x$ passes through",
    options: [{ key: "A", text: "$(0, 2)$" },{ key: "B", text: "$(0, 1)$ 且恒正" },{ key: "C", text: "可取负值" },{ key: "D", text: "$(1, 1)$" },{ key: "E", text: "$(0, 0)$" }],
    answer: "B", solution: "$2^0=1$；指数函数恒 $>0$。" },
  { id: "bmo-mk7-q18", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "A sequence has $a_1=2$ and $a_{n+1}=\\dfrac{1}{1-a_n}$. Find $a_{2026}$.",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$\\dfrac12$" },{ key: "C", text: "$1$" },{ key: "D", text: "$-1$" },{ key: "E", text: "$\\dfrac{1}{2026}$" }],
    answer: "A", solution: "算前几项：$2,\\,-1,\\,\\tfrac12,\\,2,\\dots$ 周期 3。$2026\\equiv1\\pmod3$，故 $a_{2026}=a_1=2$。" },
  { id: "bmo-mk7-q19", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 3, marks: 4,
    question: "An isosceles triangle has two sides of length $13$ and base $10$. Find its area.",
    options: [{ key: "A", text: "$65$" },{ key: "B", text: "$30$" },{ key: "C", text: "$56$" },{ key: "D", text: "$120$" },{ key: "E", text: "$60$" }],
    answer: "E", solution: "底边高 $=\\sqrt{169-25}=12$：$S=\\tfrac12\\times10\\times12=60$。" },
  { id: "bmo-mk7-q20", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "Two distinct numbers are chosen in order from $\\{1,\\dots,6\\}$. How many ordered pairs are possible?",
    options: [{ key: "A", text: "$12$" },{ key: "B", text: "$25$" },{ key: "C", text: "$15$" },{ key: "D", text: "$30$" },{ key: "E", text: "$36$" }],
    answer: "D", solution: "$6\\times5=30$（有序、不重复）。" },
  { id: "bmo-mk7-q21", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 3, marks: 4,
    question: "Is the sum $1+2+\\cdots+2026$ odd or even?",
    options: [{ key: "A", text: "等于 0" },{ key: "B", text: "偶数（even）" },{ key: "C", text: "取决于排列顺序" },{ key: "D", text: "奇数（odd）" },{ key: "E", text: "无法确定" }],
    answer: "D", solution: "和 $=\\dfrac{2026\\times2027}{2}=1013\\times2027$：奇 × 奇 = 奇。" },
  { id: "bmo-mk7-q22", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "Evaluate $1+2+\\cdots+2025$.",
    options: [{ key: "A", text: "$2049300$" },{ key: "B", text: "$2050300$" },{ key: "C", text: "$2052351$" },{ key: "D", text: "$2051325$" },{ key: "E", text: "$2026\\times2025$" }],
    answer: "D", solution: "$\\dfrac{2025\\times2026}{2}=2025\\times1013=2051325$。" },
  { id: "bmo-mk7-q23", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "Two fair dice are rolled. Find the probability the total is $4$ or $10$.",
    options: [{ key: "A", text: "$\\dfrac{7}{36}$" },{ key: "B", text: "$\\dfrac1{12}$" },{ key: "C", text: "$\\dfrac5{36}$" },{ key: "D", text: "$\\dfrac16$" },{ key: "E", text: "$\\dfrac1{9}$" }],
    answer: "D", solution: "和为 4：3 种；和为 10：3 种。$6/36=1/6$。" },
  { id: "bmo-mk7-q24", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "Which is larger: $\\dfrac{1}{10}+\\dfrac{1}{11}+\\cdots+\\dfrac{1}{19}$ (ten terms) or $\\dfrac12$?",
    options: [{ key: "A", text: "比 $\\dfrac12$ 大" },{ key: "B", text: "等于 $1$" },{ key: "C", text: "比 $\\dfrac12$ 小" },{ key: "D", text: "恰好等于 $\\dfrac12$" },{ key: "E", text: "无法比较" }],
    answer: "A", solution: "十项每项 $>\\dfrac1{20}$，和 $>\\dfrac{10}{20}=\\dfrac12$。（下界打包——调和级数发散论证的雏形。）" },
  { id: "bmo-mk7-q25", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "Real numbers satisfy $a+b=2$. The minimum value of $a^2+b^2$ is",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$2$" },{ key: "C", text: "$4$" },{ key: "D", text: "$1$" },{ key: "E", text: "$\\sqrt2$" }],
    answer: "B", solution: "QM–AM：$a^2+b^2\\ge\\dfrac{(a+b)^2}{2}=2$，等号 $a=b=1$。" }
];
