// BMO/SMC 模拟卷 5 —— 从 205 道 SMC 练习池分段抽取、按难度升序装配、重编号（bmo-mk5-qNN），8 套之间零重复。
// 题目内容与练习池一致（原创、程序验算），此处仅重编号用于独立计时模考。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const BMO_MK5_MCQ: MCQQuestion[] = [
  { id: "bmo-mk5-q01", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 1, marks: 4,
    question: "A right triangle has legs $5$ and $12$. Find its hypotenuse.",
    options: [{ key: "A", text: "$15$" },{ key: "B", text: "$11$" },{ key: "C", text: "$\\sqrt{119}$" },{ key: "D", text: "$17$" },{ key: "E", text: "$13$" }],
    answer: "E", solution: "勾股：$\\sqrt{25+144}=13$。" },
  { id: "bmo-mk5-q02", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 1, marks: 4,
    question: "If $3^x = 81$, find $x$.",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$4$" },{ key: "C", text: "$27$" },{ key: "D", text: "$3$" },{ key: "E", text: "$5$" }],
    answer: "B", solution: "$81=3^4$。" },
  { id: "bmo-mk5-q03", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 1, marks: 4,
    question: "Where does the line $y=3x-6$ cross the $x$-axis?",
    options: [{ key: "A", text: "$(2, 0)$" },{ key: "B", text: "$(6, 0)$" },{ key: "C", text: "$(3, 0)$" },{ key: "D", text: "$(-2, 0)$" },{ key: "E", text: "$(0, -6)$" }],
    answer: "A", solution: "令 $y=0$：$x=2$。" },
  { id: "bmo-mk5-q04", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "How many positive divisors does $2025$ have?",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$10$" },{ key: "C", text: "$18$" },{ key: "D", text: "$15$" },{ key: "E", text: "$12$" }],
    answer: "D", solution: "$2025=3^4\\times5^2$：$(4+1)(2+1)=15$。" },
  { id: "bmo-mk5-q05", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Find the sum of the first $100$ odd numbers: $1+3+5+\\cdots+199$.",
    options: [{ key: "A", text: "$10100$" },{ key: "B", text: "$5050$" },{ key: "C", text: "$9999$" },{ key: "D", text: "$20000$" },{ key: "E", text: "$10000$" }],
    answer: "E", solution: "前 $n$ 个奇数之和 $=n^2$：$100^2=10000$（可由 $n^2-(n-1)^2=2n-1$ 叠缩看出）。" },
  { id: "bmo-mk5-q06", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "Two sides of a triangle have length $10$ and the angle between them is $60°$. Find its area.",
    options: [{ key: "A", text: "$50\\sqrt3$" },{ key: "B", text: "$25\\sqrt3$" },{ key: "C", text: "$50$" },{ key: "D", text: "$25$" },{ key: "E", text: "$\\dfrac{25\\sqrt3}{2}$" }],
    answer: "B", solution: "$S=\\tfrac12ab\\sin C=\\tfrac12\\cdot100\\cdot\\tfrac{\\sqrt3}{2}=25\\sqrt3$。" },
  { id: "bmo-mk5-q07", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "An equilateral triangle has side $8$. Find its height.",
    options: [{ key: "A", text: "$2\\sqrt3$" },{ key: "B", text: "$8\\sqrt3$" },{ key: "C", text: "$6$" },{ key: "D", text: "$4\\sqrt2$" },{ key: "E", text: "$4\\sqrt3$" }],
    answer: "E", solution: "高 $=\\sqrt{8^2-4^2}=\\sqrt{48}=4\\sqrt3$。" },
  { id: "bmo-mk5-q08", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "In how many ways can $3$ people be chosen from $10$?",
    options: [{ key: "A", text: "$1000$" },{ key: "B", text: "$30$" },{ key: "C", text: "$210$" },{ key: "D", text: "$120$" },{ key: "E", text: "$720$" }],
    answer: "D", solution: "$\\binom{10}{3}=\\dfrac{10\\cdot9\\cdot8}{6}=120$。" },
  { id: "bmo-mk5-q09", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "A drawer contains $8$ black and $6$ white socks. What is the minimum number of socks to take (in the dark) to guarantee a matching pair?",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$15$" },{ key: "C", text: "$7$" },{ key: "D", text: "$2$" },{ key: "E", text: "$3$" }],
    answer: "E", solution: "两种颜色为鸽笼：取 3 只必有同色。" },
  { id: "bmo-mk5-q10", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "Which of these primes can be written as the sum of two squares?",
    options: [{ key: "A", text: "$19$" },{ key: "B", text: "$23$" },{ key: "C", text: "$13$" },{ key: "D", text: "$11$" },{ key: "E", text: "$7$" }],
    answer: "C", solution: "$13=4+9=2^2+3^2$。（定理：奇素数可表为两平方和 ⟺ $p\\equiv1\\pmod4$；$7,11,19,23$ 均 $\\equiv3$。）" },
  { id: "bmo-mk5-q11", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The sequence $7, 14, 21, \\dots$ lists multiples of $7$. Is $2026$ a term?",
    options: [{ key: "A", text: "是，第 2026 项" },{ key: "B", text: "是，第 289 项" },{ key: "C", text: "不是——$2026=7\\times289+3$" },{ key: "D", text: "是，第 290 项" },{ key: "E", text: "不是，但 $2027$ 是" }],
    answer: "C", solution: "$2026\\div7=289$ 余 $3$：不是 7 的倍数。" },
  { id: "bmo-mk5-q12", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "A fair coin is tossed $3$ times. Find the probability of exactly two heads.",
    options: [{ key: "A", text: "$\\dfrac12$" },{ key: "B", text: "$\\dfrac14$" },{ key: "C", text: "$\\dfrac23$" },{ key: "D", text: "$\\dfrac18$" },{ key: "E", text: "$\\dfrac38$" }],
    answer: "E", solution: "$\\binom32/2^3=3/8$。" },
  { id: "bmo-mk5-q13", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Find the sum to infinity of $8+4+2+1+\\cdots$",
    options: [{ key: "A", text: "$\\infty$" },{ key: "B", text: "$15$" },{ key: "C", text: "$32$" },{ key: "D", text: "$16$" },{ key: "E", text: "$16.5$" }],
    answer: "D", solution: "$S=\\dfrac{8}{1-\\tfrac12}=16$。" },
  { id: "bmo-mk5-q14", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "What is the units digit of $2026^2$?",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$4$" },{ key: "C", text: "$8$" },{ key: "D", text: "$2$" },{ key: "E", text: "$0$" }],
    answer: "A", solution: "只看个位：$6^2=36$ → 个位 6。" },
  { id: "bmo-mk5-q15", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "A rectangle has perimeter $20$. Its area is at most",
    options: [{ key: "A", text: "$24$" },{ key: "B", text: "$25$" },{ key: "C", text: "$100$" },{ key: "D", text: "$20$" },{ key: "E", text: "$50$" }],
    answer: "B", solution: "半周长 10 定和：最大积在正方形 $5\\times5=25$。" },
  { id: "bmo-mk5-q16", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The function $f(x)=(x-3)^2+1$. Find $f(0)$ and the minimum value of $f$.",
    options: [{ key: "A", text: "$f(0)=9$；最小值 $0$" },{ key: "B", text: "$f(0)=10$；最小值 $3$" },{ key: "C", text: "$f(0)=1$；最小值 $10$" },{ key: "D", text: "$f(0)=10$；最小值 $1$" },{ key: "E", text: "$f(0)=8$；最小值 $1$" }],
    answer: "D", solution: "$f(0)=9+1=10$；顶点值 1。" },
  { id: "bmo-mk5-q17", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The graph of $y=x^2-2x+1$ touches the $x$-axis at",
    options: [{ key: "A", text: "不接触" },{ key: "B", text: "$x=-1$" },{ key: "C", text: "$x=\\pm1$" },{ key: "D", text: "$x=2$" },{ key: "E", text: "$x=1$（相切）" }],
    answer: "E", solution: "$(x-1)^2$：重根相切。" },
  { id: "bmo-mk5-q18", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "Evaluate the infinite sum $3-1+\\dfrac13-\\dfrac19+\\cdots$.",
    options: [{ key: "A", text: "$\\dfrac92$" },{ key: "B", text: "$\\dfrac{27}{8}$" },{ key: "C", text: "$\\dfrac{9}{2}-1$" },{ key: "D", text: "$2$" },{ key: "E", text: "$\\dfrac94$" }],
    answer: "E", solution: "首项 $3$、公比 $-\\tfrac13$：$S=\\dfrac{3}{1+\\tfrac13}=\\dfrac94$。" },
  { id: "bmo-mk5-q19", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 3, marks: 4,
    question: "In triangle $ABC$, $\\angle A = 90°$ and the altitude from $A$ meets $BC$ at $D$ with $BD=4$, $DC=9$. Find $AD$.",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$\\sqrt{13}$" },{ key: "C", text: "$6$" },{ key: "D", text: "$13$" },{ key: "E", text: "$36$" }],
    answer: "C", solution: "直角三角形斜边上的高：$AD^2=BD\\cdot DC=36$，$AD=6$。" },
  { id: "bmo-mk5-q20", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "How many ways are there to write $8$ as an ordered sum of $3$ positive integers (e.g. $1+3+4$ and $3+1+4$ count separately)?",
    options: [{ key: "A", text: "$56$" },{ key: "B", text: "$21$" },{ key: "C", text: "$10$" },{ key: "D", text: "$15$" },{ key: "E", text: "$28$" }],
    answer: "B", solution: "隔板法：8 个球间 7 个空隙放 2 块板：$\\binom72=21$。" },
  { id: "bmo-mk5-q21", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 3, marks: 4,
    question: "Find the remainder when $2^{2026}$ is divided by $7$.",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$1$" },{ key: "C", text: "$3$" },{ key: "D", text: "$4$" },{ key: "E", text: "$2$" }],
    answer: "E", solution: "$2^3=8\\equiv1\\pmod7$，故幂次按 3 循环。$2026=3\\times675+1$，所以 $2^{2026}=2\\cdot(2^3)^{675}\\equiv2\\pmod7$。" },
  { id: "bmo-mk5-q22", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "Evaluate $\\dfrac{1}{1\\cdot2}+\\dfrac{1}{2\\cdot3}+\\cdots+\\dfrac{1}{100\\cdot101}$.",
    options: [{ key: "A", text: "$\\dfrac{101}{100}$" },{ key: "B", text: "$\\dfrac{1}{101}$" },{ key: "C", text: "$\\dfrac{100}{101}$" },{ key: "D", text: "$\\dfrac{99}{100}$" },{ key: "E", text: "$1$" }],
    answer: "C", solution: "裂项：$\\dfrac1{k(k+1)}=\\dfrac1k-\\dfrac1{k+1}$，叠缩得 $1-\\dfrac1{101}=\\dfrac{100}{101}$。" },
  { id: "bmo-mk5-q23", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "A two-digit number is chosen at random. Find the probability that it is divisible by $3$.",
    options: [{ key: "A", text: "$\\dfrac13$" },{ key: "B", text: "$\\dfrac{29}{90}$" },{ key: "C", text: "$\\dfrac{1}{3}-\\dfrac{1}{90}$" },{ key: "D", text: "$\\dfrac{33}{90}$" },{ key: "E", text: "$\\dfrac{30}{99}$" }],
    answer: "A", solution: "两位数 $10\\dots99$ 共 90 个，其中 3 的倍数 $12\\dots99$ 共 30 个：$1/3$。" },
  { id: "bmo-mk5-q24", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "Four numbers are in arithmetic progression with sum $20$ and product $384$? — simplified: an AP of four terms has sum $20$. Find the sum of the middle two terms.",
    options: [{ key: "A", text: "$15$" },{ key: "B", text: "$20$" },{ key: "C", text: "$10$" },{ key: "D", text: "$5$" },{ key: "E", text: "无法确定" }],
    answer: "C", solution: "四项 AP 关于中心对称：首尾对与中间对的和都等于总和的一半 $=10$。" },
  { id: "bmo-mk5-q25", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "Positive reals $x, y$ satisfy $x+2y=6$. Find the maximum of $xy$.",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$9$" },{ key: "C", text: "$3$" },{ key: "D", text: "$\\dfrac92$" },{ key: "E", text: "$\\dfrac{9}{4}$" }],
    answer: "D", solution: "$xy=\\tfrac12\\cdot x\\cdot2y\\le\\tfrac12\\left(\\dfrac{x+2y}{2}\\right)^2=\\tfrac12\\times9=\\dfrac92$，等号 $x=2y=3$。" }
];
