// BMO/SMC 模拟卷 3 —— 从 205 道 SMC 练习池分段抽取、按难度升序装配、重编号（bmo-mk3-qNN），8 套之间零重复。
// 题目内容与练习池一致（原创、程序验算），此处仅重编号用于独立计时模考。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const BMO_MK3_MCQ: MCQQuestion[] = [
  { id: "bmo-mk3-q01", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 1, marks: 4,
    question: "Find the minimum value of $x^2-6x+11$.",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$-2$" },{ key: "C", text: "$11$" },{ key: "D", text: "$3$" },{ key: "E", text: "$2$" }],
    answer: "E", solution: "配方：$(x-3)^2+2\\ge2$，最小值 $2$（在 $x=3$）。" },
  { id: "bmo-mk3-q02", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 1, marks: 4,
    question: "What is the largest proper divisor of $64$?",
    options: [{ key: "A", text: "$63$" },{ key: "B", text: "$32$" },{ key: "C", text: "$16$" },{ key: "D", text: "$4$" },{ key: "E", text: "$8$" }],
    answer: "B", solution: "$64=2^6$，最大真因数 $=64/2=32$。" },
  { id: "bmo-mk3-q03", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 1, marks: 4,
    question: "Evaluate $1+2+3+\\cdots+100$.",
    options: [{ key: "A", text: "$4950$" },{ key: "B", text: "$5000$" },{ key: "C", text: "$5050$" },{ key: "D", text: "$5150$" },{ key: "E", text: "$10100$" }],
    answer: "C", solution: "$\\dfrac{100\\times101}{2}=5050$（高斯配对）。" },
  { id: "bmo-mk3-q04", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "How many twin prime pairs $(p, p+2)$ have both members at most $30$?",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$6$" },{ key: "C", text: "$3$" },{ key: "D", text: "$4$" },{ key: "E", text: "$2$" }],
    answer: "D", solution: "$(3,5),(5,7),(11,13),(17,19)$ 共 4 对（$(29,31)$ 的 31 超界）。" },
  { id: "bmo-mk3-q05", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Given $x+\\dfrac1x=3$, find $x^2+\\dfrac1{x^2}$.",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$8$" },{ key: "C", text: "$11$" },{ key: "D", text: "$6$" },{ key: "E", text: "$7$" }],
    answer: "E", solution: "平方：$\\left(x+\\tfrac1x\\right)^2=x^2+2+\\tfrac1{x^2}=9$，故所求 $=7$。" },
  { id: "bmo-mk3-q06", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "If $a:b = 3:4$ and $b:c = 6:5$, find $a:c$.",
    options: [{ key: "A", text: "$18:20$ 即 $9:10$ 都不对" },{ key: "B", text: "$2:3$" },{ key: "C", text: "$15:8$" },{ key: "D", text: "$3:5$" },{ key: "E", text: "$9:10$" }],
    answer: "E", solution: "统一 $b$：$a:b=9:12$，$b:c=12:10$，故 $a:c=9:10$。" },
  { id: "bmo-mk3-q07", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "Find the area between two concentric circles of radii $3$ and $2$.",
    options: [{ key: "A", text: "$6\\pi$" },{ key: "B", text: "$5\\pi$" },{ key: "C", text: "$9\\pi$" },{ key: "D", text: "$13\\pi$" },{ key: "E", text: "$\\pi$" }],
    answer: "B", solution: "$9\\pi-4\\pi=5\\pi$。" },
  { id: "bmo-mk3-q08", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "How many diagonals does a regular decagon have?",
    options: [{ key: "A", text: "$30$" },{ key: "B", text: "$45$" },{ key: "C", text: "$35$" },{ key: "D", text: "$40$" },{ key: "E", text: "$25$" }],
    answer: "C", solution: "$\\dfrac{n(n-3)}{2}=\\dfrac{10\\times7}{2}=35$。" },
  { id: "bmo-mk3-q09", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "How many routes are there from the bottom-left to the top-right corner of a $3\\times3$ grid of squares, moving only right or up along grid lines?",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$6$" },{ key: "C", text: "$12$" },{ key: "D", text: "$20$" },{ key: "E", text: "$27$" }],
    answer: "D", solution: "共走 6 步选 3 步向右：$\\binom63=20$。" },
  { id: "bmo-mk3-q10", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "What is the smallest perfect number (a number equal to the sum of its proper divisors)?",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$8$" },{ key: "C", text: "$28$" },{ key: "D", text: "$12$" },{ key: "E", text: "$6$" }],
    answer: "E", solution: "$6=1+2+3$。下一个是 $28$。" },
  { id: "bmo-mk3-q11", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "If $a+b=7$ and $a^2+b^2=25$, find $2ab$.",
    options: [{ key: "A", text: "$48$" },{ key: "B", text: "$12$" },{ key: "C", text: "$18$" },{ key: "D", text: "$49$" },{ key: "E", text: "$24$" }],
    answer: "E", solution: "$(a+b)^2=a^2+2ab+b^2$：$49=25+2ab\\Rightarrow2ab=24$。" },
  { id: "bmo-mk3-q12", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "For how many integers $x$ is $x^2 \\le 10$?",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$5$" },{ key: "C", text: "$6$" },{ key: "D", text: "$3$" },{ key: "E", text: "$7$" }],
    answer: "E", solution: "$-3\\le x\\le3$：7 个（含 0）。" },
  { id: "bmo-mk3-q13", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Find the sum of the first $20$ terms of the arithmetic sequence $5, 8, 11, \\dots$",
    options: [{ key: "A", text: "$1340$" },{ key: "B", text: "$700$" },{ key: "C", text: "$670$" },{ key: "D", text: "$620$" },{ key: "E", text: "$650$" }],
    answer: "C", solution: "$S_{20}=\\dfrac{20}{2}\\big(2\\times5+19\\times3\\big)=10\\times67=670$。" },
  { id: "bmo-mk3-q14", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The differences between consecutive square numbers $1,4,9,16,\\dots$ form the sequence",
    options: [{ key: "A", text: "平方数" },{ key: "B", text: "连续偶数" },{ key: "C", text: "连续奇数 $3,5,7,9,\\dots$" },{ key: "D", text: "素数" },{ key: "E", text: "常数 $2$" }],
    answer: "C", solution: "$ (n+1)^2-n^2=2n+1$：奇数列。" },
  { id: "bmo-mk3-q15", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Solve $|x-3|\\le4$. The solution set is",
    options: [{ key: "A", text: "$-1\\le x\\le7$" },{ key: "B", text: "$x\\le7$" },{ key: "C", text: "$-4\\le x\\le4$" },{ key: "D", text: "$x\\ge-1$" },{ key: "E", text: "$-7\\le x\\le1$" }],
    answer: "A", solution: "$-4\\le x-3\\le4$。" },
  { id: "bmo-mk3-q16", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "For what value of $k>0$ does $x^2-4x+k=0$ have exactly one solution?",
    options: [{ key: "A", text: "$k=8$" },{ key: "B", text: "$k=4$" },{ key: "C", text: "$k=2$" },{ key: "D", text: "$k=-4$" },{ key: "E", text: "$k=16$" }],
    answer: "B", solution: "判别式 $16-4k=0\\Rightarrow k=4$。" },
  { id: "bmo-mk3-q17", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "If $f(x)=x+1$ and $g(x)=2x$, find $g(f(4))$.",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$10$" },{ key: "C", text: "$8$" },{ key: "D", text: "$12$" },{ key: "E", text: "$9$" }],
    answer: "B", solution: "$f(4)=5$，$g(5)=10$。" },
  { id: "bmo-mk3-q18", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 3, marks: 4,
    question: "How many $1$s appear when $2026$ is written in binary?",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$8$" },{ key: "C", text: "$6$" },{ key: "D", text: "$10$" },{ key: "E", text: "$7$" }],
    answer: "B", solution: "$2026=1024+512+256+128+64+32+8+2=11111101010_2$：8 个 1。" },
  { id: "bmo-mk3-q19", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 3, marks: 4,
    question: "A cone has base radius $3$ and height $4$. Find its total surface area (base included).",
    options: [{ key: "A", text: "$36\\pi$" },{ key: "B", text: "$15\\pi$" },{ key: "C", text: "$21\\pi$" },{ key: "D", text: "$24\\pi$" },{ key: "E", text: "$9\\pi$" }],
    answer: "D", solution: "母线 $l=5$：侧面 $\\pi rl=15\\pi$，底 $9\\pi$，共 $24\\pi$。" },
  { id: "bmo-mk3-q20", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "In how many ways can $5$ people be seated around a round table (rotations count as the same)?",
    options: [{ key: "A", text: "$25$" },{ key: "B", text: "$60$" },{ key: "C", text: "$120$" },{ key: "D", text: "$24$" },{ key: "E", text: "$12$" }],
    answer: "D", solution: "圆排列 $(5-1)!=24$。" },
  { id: "bmo-mk3-q21", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "At a gathering of $n\\ge2$ people, some pairs shake hands. Which statement is always true?",
    options: [{ key: "A", text: "Someone shook no hands" },{ key: "B", text: "There are two people who shook the same number of hands" },{ key: "C", text: "Everyone shook a different number of hands" },{ key: "D", text: "Someone shook everyone's hand" },{ key: "E", text: "The total number of handshakes is even" }],
    answer: "B", solution: "每人握手数 $\\in\\{0,\\dots,n-1\\}$，但 0 与 $n-1$ 不能同时出现 → 只有 $n-1$ 个可用值给 $n$ 个人：鸽笼原理保证有两人同数。" },
  { id: "bmo-mk3-q22", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 3, marks: 4,
    question: "Find $\\gcd(10!,\\;2^{10})$.",
    options: [{ key: "A", text: "$256$" },{ key: "B", text: "$512$" },{ key: "C", text: "$128$" },{ key: "D", text: "$1024$" },{ key: "E", text: "$64$" }],
    answer: "A", solution: "$10!$ 中 2 的幂次 $=5+2+1=8$：$\\gcd=2^8=256$。" },
  { id: "bmo-mk3-q23", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "A family has two children. Given that at least one is a boy, what is the probability that both are boys? (Assume boys/girls equally likely, independent.)",
    options: [{ key: "A", text: "$\\dfrac23$" },{ key: "B", text: "$\\dfrac13$" },{ key: "C", text: "$\\dfrac14$" },{ key: "D", text: "$\\dfrac34$" },{ key: "E", text: "$\\dfrac12$" }],
    answer: "B", solution: "样本空间限于 $\\{BB,BG,GB\\}$（等可能），其中 $BB$ 占 $\\dfrac13$——经典条件概率陷阱。" },
  { id: "bmo-mk3-q24", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "Evaluate $1-2+3-4+\\cdots+2025-2026$.",
    options: [{ key: "A", text: "$1013$" },{ key: "B", text: "$0$" },{ key: "C", text: "$-2026$" },{ key: "D", text: "$-1$" },{ key: "E", text: "$-1013$" }],
    answer: "E", solution: "两两配对 $(1-2)+(3-4)+\\cdots$ 共 1013 对，每对 $-1$：$-1013$。" },
  { id: "bmo-mk3-q25", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "How many triangles with integer side lengths have perimeter $12$?",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$6$" },{ key: "C", text: "$4$" },{ key: "D", text: "$5$" },{ key: "E", text: "$3$" }],
    answer: "E", solution: "满足 $a\\le b\\le c$、$a+b>c$、和 12：$(2,5,5),(3,4,5),(4,4,4)$，共 3 个。" }
];
