// BPhO Round 2 模拟卷4 —— 4 个「主题阶梯」模块（对标 R2：3小时/4题/全做），链式 MCQ + 程序验算，全部原创。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const BPHO_R2M4_T1: MCQQuestion[] = [
  { id: "bpho-r2m4-t1-01", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：蹦极的物理】体重 $60$ kg 的人从高台跳下，弹性绳自然长度 $20$ m，劲度系数 $k=100\\ \\mathrm{N\\,m^{-1}}$，$g=10$。 第1步：绳开始张紧（下落 $20$ m）瞬间的速度为",
    options: [{ key: "A", text: "$10\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$20\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$40\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$28\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$14\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "B", solution: "自由落体：$v=\\sqrt{2gh}=\\sqrt{2\\times10\\times20}=20\\ \\mathrm{m\\,s^{-1}}$。" },
  { id: "bpho-r2m4-t1-02", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：蹦极的物理】体重 $60$ kg 的人从高台跳下，弹性绳自然长度 $20$ m，劲度系数 $k=100\\ \\mathrm{N\\,m^{-1}}$，$g=10$。 第2步：绳张紧后，人达到**最大速度**的位置在",
    options: [{ key: "A", text: "最低点" },{ key: "B", text: "始终匀速" },{ key: "C", text: "绳伸长 $3$ m 处" },{ key: "D", text: "绳伸长 $x=mg/k=6$ m 处（合力为零点），而不是最低点" },{ key: "E", text: "绳刚张紧处" }],
    answer: "D", solution: "张紧后仍有 $mg>kx$ 的阶段继续加速；$kx=mg$（$x=6$ m）合力为零、速度最大；再往下才减速。最低点速度为零——「最大速度在最低点」是最常见的错觉。" },
  { id: "bpho-r2m4-t1-03", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：蹦极的物理】体重 $60$ kg 的人从高台跳下，弹性绳自然长度 $20$ m，劲度系数 $k=100\\ \\mathrm{N\\,m^{-1}}$，$g=10$。 第3步：用能量守恒求最大速度（绳伸长 $6$ m 处）。",
    options: [{ key: "A", text: "$\\approx24.5\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$20\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$\\approx15\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$\\approx21.4\\ \\mathrm{m\\,s^{-1}}$（比 $20$ 略大）" },{ key: "E", text: "$\\approx26\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "D", solution: "$\\tfrac12mv^2=mg(26)-\\tfrac12k(6)^2$：$v^2=2\\times10\\times26-\\dfrac{100\\times36}{60}=520-60=460$，$v\\approx21.4\\ \\mathrm{m\\,s^{-1}}$。" },
  { id: "bpho-r2m4-t1-04", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：蹦极的物理】体重 $60$ kg 的人从高台跳下，弹性绳自然长度 $20$ m，劲度系数 $k=100\\ \\mathrm{N\\,m^{-1}}$，$g=10$。 第4步：求最低点的绳伸长量 $x_{\\max}$（能量守恒：$mg(20+x)=\\tfrac12kx^2$）。",
    options: [{ key: "A", text: "$\\approx30$ m" },{ key: "B", text: "$\\approx22.6$ m（总下落约 $42.6$ m）" },{ key: "C", text: "$\\approx12$ m" },{ key: "D", text: "$\\approx17$ m" },{ key: "E", text: "$\\approx6$ m" }],
    answer: "B", solution: "$600(20+x)=50x^2\\Rightarrow x^2-12x-240=0\\Rightarrow x=\\dfrac{12+\\sqrt{1104}}{2}\\approx22.6$ m。" },
  { id: "bpho-r2m4-t1-05", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：蹦极的物理】体重 $60$ kg 的人从高台跳下，弹性绳自然长度 $20$ m，劲度系数 $k=100\\ \\mathrm{N\\,m^{-1}}$，$g=10$。 第5步：最低点人受到的加速度约为",
    options: [{ key: "A", text: "$\\approx10g$" },{ key: "B", text: "$\\dfrac{kx_{\\max}-mg}{m}\\approx28\\ \\mathrm{m\\,s^{-2}}\\approx2.8g$（向上）" },{ key: "C", text: "$\\approx1.4g$" },{ key: "D", text: "$g$ 向下" },{ key: "E", text: "零（最低点速度为零）" }],
    answer: "B", solution: "$a=\\dfrac{100\\times22.6-600}{60}\\approx27.7\\ \\mathrm{m\\,s^{-2}}$。速度为零 $\\ne$ 加速度为零——最低点正是加速度最大处。商业蹦极设计控制在 $\\sim3g$ 内。" },
  { id: "bpho-r2m4-t1-06", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：蹦极的物理】体重 $60$ kg 的人从高台跳下，弹性绳自然长度 $20$ m，劲度系数 $k=100\\ \\mathrm{N\\,m^{-1}}$，$g=10$。 第6步：人最终静止悬挂在绳伸长 $6$ m 处。从起跳到静止，初始的重力势能最终去了哪里？",
    options: [{ key: "A", text: "大部分经反复振荡被绳内摩擦与空气阻力耗散为热，小部分存为绳的弹性势能" },{ key: "B", text: "转化为化学能" },{ key: "C", text: "凭空消失" },{ key: "D", text: "全部还在动能里" },{ key: "E", text: "全部存为弹性势能" }],
    answer: "A", solution: "静止悬挂时弹性势能只有 $\\tfrac12k(6)^2=1.8$ kJ，而总势能降 $mg\\times26=15.6$ kJ——差额 $\\approx14$ kJ 在来回弹跳中被阻尼耗散。没有耗散就会永远弹下去。" },
];

export const BPHO_R2M4_T2: MCQQuestion[] = [
  { id: "bpho-r2m4-t2-01", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：人体这台热机】静息代谢功率按 $100$ W 计。$1$ kcal $=4184$ J；汗的汽化潜热 $2.3\\times10^{6}\\ \\mathrm{J\\,kg^{-1}}$。 第1步：一天（$86400$ s）的静息能耗约为",
    options: [{ key: "A", text: "$8.6$ MJ $\\approx2100$ kcal——正是营养学的每日基础摄入量" },{ key: "B", text: "$360$ kJ" },{ key: "C", text: "$8.6$ kJ" },{ key: "D", text: "$0.86$ MJ $\\approx210$ kcal" },{ key: "E", text: "$86$ MJ" }],
    answer: "A", solution: "$E=100\\times86400=8.64\\times10^6$ J $=\\dfrac{8.64\\times10^6}{4184}\\approx2060$ kcal。「每日 2000 大卡」的物理出处。" },
  { id: "bpho-r2m4-t2-02", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：人体这台热机】静息代谢功率按 $100$ W 计。$1$ kcal $=4184$ J；汗的汽化潜热 $2.3\\times10^{6}\\ \\mathrm{J\\,kg^{-1}}$。 第2步：静息的 $100$ W 最终几乎全部以什么形式离开身体？",
    options: [{ key: "A", text: "可见光" },{ key: "B", text: "机械功" },{ key: "C", text: "声音" },{ key: "D", text: "热——人体在能量收支上就是一台 $100$ W 的「暖炉」" },{ key: "E", text: "化学能存回体内" }],
    answer: "D", solution: "静息时对外做功≈0，代谢能全部变热散出（辐射+对流+蒸发）。教室里 30 个人 $=3$ kW 暖气——冬天教室很暖的原因。" },
  { id: "bpho-r2m4-t2-03", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：人体这台热机】静息代谢功率按 $100$ W 计。$1$ kcal $=4184$ J；汗的汽化潜热 $2.3\\times10^{6}\\ \\mathrm{J\\,kg^{-1}}$。 第3步：剧烈运动时总代谢升到 $\\sim900$ W，但肌肉对外输出的机械功率只有 $\\sim200$ W。人体作为「热机」的效率约为",
    options: [{ key: "A", text: "$\\sim50\\%$" },{ key: "B", text: "$\\sim100\\%$" },{ key: "C", text: "$\\sim80\\%$" },{ key: "D", text: "$\\sim2\\%$" },{ key: "E", text: "$\\sim20\\%$——其余 $700$ W 必须当场散掉" }],
    answer: "E", solution: "$\\eta=200/900\\approx22\\%$，与内燃机同量级。剩余 $\\sim700$ W 的散热压力就是出汗的原因。" },
  { id: "bpho-r2m4-t2-04", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：人体这台热机】静息代谢功率按 $100$ W 计。$1$ kcal $=4184$ J；汗的汽化潜热 $2.3\\times10^{6}\\ \\mathrm{J\\,kg^{-1}}$。 第4步：若这 $700$ W 全靠蒸发汗水带走，需要的出汗率约为",
    options: [{ key: "A", text: "$\\approx1.1$ kg/小时" },{ key: "B", text: "$\\approx11$ kg/小时" },{ key: "C", text: "$\\approx0.3$ g/小时" },{ key: "D", text: "$\\approx0.11$ kg/小时" },{ key: "E", text: "$\\approx5$ kg/小时" }],
    answer: "A", solution: "$\\dot m=\\dfrac{700}{2.3\\times10^6}\\approx3\\times10^{-4}\\ \\mathrm{kg\\,s^{-1}}\\approx1.1$ kg/h。马拉松选手确实每小时失水约 1–1.5 L——补水是物理刚需。" },
  { id: "bpho-r2m4-t2-05", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：人体这台热机】静息代谢功率按 $100$ W 计。$1$ kcal $=4184$ J；汗的汽化潜热 $2.3\\times10^{6}\\ \\mathrm{J\\,kg^{-1}}$。 第5步：湿热天气（湿度接近 $100\\%$）远比干热危险，物理原因是",
    options: [{ key: "A", text: "空气近饱和时汗无法蒸发，人体主散热通道失效，核心温度失控上升" },{ key: "B", text: "湿空气含氧更少" },{ key: "C", text: "汗变多稀释了盐分" },{ key: "D", text: "湿空气更重压迫身体" },{ key: "E", text: "湿空气导热更差" }],
    answer: "A", solution: "蒸发需要空气「还装得下」水汽：相对湿度→100% 时净蒸发→0，$700$ W 无处可去。这就是「湿球温度 35 ℃ 是人类生存极限」的由来。" },
  { id: "bpho-r2m4-t2-06", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：人体这台热机】静息代谢功率按 $100$ W 计。$1$ kcal $=4184$ J；汗的汽化潜热 $2.3\\times10^{6}\\ \\mathrm{J\\,kg^{-1}}$。 第6步（估算）：一块 $100$ g 巧克力约 $550$ kcal。要「跑掉它」（净额外消耗按 $700$ W 计），大约需要连续跑",
    options: [{ key: "A", text: "$\\approx2$ 分钟" },{ key: "B", text: "$\\approx5.5$ 分钟" },{ key: "C", text: "$\\approx55$ 分钟" },{ key: "D", text: "$\\approx9$ 小时" },{ key: "E", text: "$\\approx25$ 分钟" }],
    answer: "C", solution: "$E=550\\times4184\\approx2.3\\times10^6$ J；$t=E/700\\approx3.3\\times10^3$ s $\\approx55$ 分钟。「吃进去 1 分钟、跑掉 1 小时」的量化版。" },
];

export const BPHO_R2M4_T3: MCQQuestion[] = [
  { id: "bpho-r2m4-t3-01", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：口袋里的能量】一块手机电池：标称 $3.7$ V、容量 $10$ Wh、质量 $50$ g。 第1步：$10$ Wh 换算成焦耳是",
    options: [{ key: "A", text: "$3.6\\times10^{3}$ J" },{ key: "B", text: "$3.6\\times10^{4}$ J" },{ key: "C", text: "$3.6\\times10^{6}$ J" },{ key: "D", text: "$6\\times10^{2}$ J" },{ key: "E", text: "$10$ J" }],
    answer: "B", solution: "$10\\ \\mathrm{Wh}=10\\times3600=3.6\\times10^4$ J。" },
  { id: "bpho-r2m4-t3-02", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：口袋里的能量】一块手机电池：标称 $3.7$ V、容量 $10$ Wh、质量 $50$ g。 第2步：电池储存的电荷量约为",
    options: [{ key: "A", text: "$\\approx97$ C" },{ key: "B", text: "$Q=E/V\\approx9.7\\times10^{3}$ C（$\\approx2.7$ Ah）" },{ key: "C", text: "$\\approx2.7$ C" },{ key: "D", text: "$\\approx3.6\\times10^{4}$ C" },{ key: "E", text: "$\\approx1.3\\times10^{5}$ C" }],
    answer: "B", solution: "$Q=\\dfrac{3.6\\times10^4}{3.7}\\approx9.7\\times10^3$ C $=\\dfrac{9700}{3600}\\approx2.7$ Ah——正是电池标签上的「2700 mAh」。" },
  { id: "bpho-r2m4-t3-03", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：口袋里的能量】一块手机电池：标称 $3.7$ V、容量 $10$ Wh、质量 $50$ g。 第3步：亮屏耗电约 $2$ W。满电可以连续亮屏",
    options: [{ key: "A", text: "$2$ 小时" },{ key: "B", text: "$10$ 小时" },{ key: "C", text: "$50$ 小时" },{ key: "D", text: "$5$ 小时" },{ key: "E", text: "$18$ 小时" }],
    answer: "D", solution: "$t=\\dfrac{10\\ \\mathrm{Wh}}{2\\ \\mathrm{W}}=5$ h。待机能到几天靠的是把功率压到 $\\sim0.1$ W 以下。" },
  { id: "bpho-r2m4-t3-04", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：口袋里的能量】一块手机电池：标称 $3.7$ V、容量 $10$ Wh、质量 $50$ g。 第4步：快充以 $5$ A 充电（忽略损耗），充满需要",
    options: [{ key: "A", text: "$\\approx11$ 分钟" },{ key: "B", text: "$\\approx97$ 分钟" },{ key: "C", text: "$\\approx3.2$ 分钟" },{ key: "D", text: "$\\approx5.4$ 小时" },{ key: "E", text: "$\\approx32$ 分钟" }],
    answer: "E", solution: "$t=\\dfrac{Q}{I}=\\dfrac{9.7\\times10^3}{5}\\approx1.9\\times10^3$ s $\\approx32$ 分钟。实际末段要降流保护电池，所以「前 80% 快、后 20% 慢」。" },
  { id: "bpho-r2m4-t3-05", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：口袋里的能量】一块手机电池：标称 $3.7$ V、容量 $10$ Wh、质量 $50$ g。 第5步：这块电池的能量密度约为",
    options: [{ key: "A", text: "$46\\ \\mathrm{MJ\\,kg^{-1}}$" },{ key: "B", text: "$0.72\\ \\mathrm{MJ\\,kg^{-1}}$——只有汽油（$46\\ \\mathrm{MJ\\,kg^{-1}}$）的约 $1/60$" },{ key: "C", text: "$7.2\\ \\mathrm{MJ\\,kg^{-1}}$，接近汽油" },{ key: "D", text: "$720\\ \\mathrm{MJ\\,kg^{-1}}$" },{ key: "E", text: "$0.072\\ \\mathrm{MJ\\,kg^{-1}}$" }],
    answer: "B", solution: "$\\dfrac{3.6\\times10^4}{0.05}=7.2\\times10^5\\ \\mathrm{J\\,kg^{-1}}$。差两个数量级——电动车电池占半吨、电动飞机难产的根本物理约束。" },
  { id: "bpho-r2m4-t3-06", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：口袋里的能量】一块手机电池：标称 $3.7$ V、容量 $10$ Wh、质量 $50$ g。 第6步：充电时电池会发热。若充电回路总内阻 $0.1\\ \\Omega$、电流 $5$ A，发热功率为",
    options: [{ key: "A", text: "$0.25$ W" },{ key: "B", text: "$I^2r=2.5$ W——约占充电功率的 $12\\%$，这就是快充发烫的来源" },{ key: "C", text: "$25$ W" },{ key: "D", text: "$18.5$ W" },{ key: "E", text: "$0.5$ W" }],
    answer: "B", solution: "$P=I^2r=25\\times0.1=2.5$ W。损耗 $\\propto I^2$：同样能量，电流越大热越多——快充与电池寿命/安全的根本矛盾。" },
];

export const BPHO_R2M4_T4: MCQQuestion[] = [
  { id: "bpho-r2m4-t4-01", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：GPS 离不开相对论】GPS 卫星轨道半径 $r=2.66\\times10^{7}$ m，$GM_E=3.99\\times10^{14}\\ \\mathrm{m^3\\,s^{-2}}$，地球半径 $6.37\\times10^{6}$ m，$c=3\\times10^{8}$。 第1步：卫星的轨道速度为",
    options: [{ key: "A", text: "$\\sqrt{GM/r}\\approx3.9\\times10^{3}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$\\approx7.9\\times10^{3}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$\\approx3.1\\times10^{2}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$\\approx3.0\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$\\approx1.1\\times10^{4}\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "A", solution: "$v=\\sqrt{\\dfrac{3.99\\times10^{14}}{2.66\\times10^7}}\\approx3.87\\times10^3\\ \\mathrm{m\\,s^{-1}}$（周期约 12 小时）。" },
  { id: "bpho-r2m4-t4-02", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：GPS 离不开相对论】GPS 卫星轨道半径 $r=2.66\\times10^{7}$ m，$GM_E=3.99\\times10^{14}\\ \\mathrm{m^3\\,s^{-2}}$，地球半径 $6.37\\times10^{6}$ m，$c=3\\times10^{8}$。 第2步：狭义相对论：运动的钟变慢，比例约 $\\dfrac{v^2}{2c^2}$。卫星钟因此每天比地面钟",
    options: [{ key: "A", text: "慢约 $7$ ns" },{ key: "B", text: "慢约 $7\\ \\mu$s" },{ key: "C", text: "慢约 $7$ ms" },{ key: "D", text: "快约 $7\\ \\mu$s" },{ key: "E", text: "不变" }],
    answer: "B", solution: "$\\dfrac{v^2}{2c^2}=\\dfrac{(3.87\\times10^3)^2}{2\\times9\\times10^{16}}\\approx8.3\\times10^{-11}$；乘 $86400$ s $\\approx7.2\\ \\mu$s/天（变慢）。" },
  { id: "bpho-r2m4-t4-03", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：GPS 离不开相对论】GPS 卫星轨道半径 $r=2.66\\times10^{7}$ m，$GM_E=3.99\\times10^{14}\\ \\mathrm{m^3\\,s^{-2}}$，地球半径 $6.37\\times10^{6}$ m，$c=3\\times10^{8}$。 第3步：广义相对论：引力势越高（离地球越远）的钟走得越**快**，效应约 $\\dfrac{\\Delta\\Phi}{c^2}=\\dfrac{GM}{c^2}\\left(\\dfrac{1}{R_E}-\\dfrac{1}{r}\\right)$。卫星钟因此每天",
    options: [{ key: "A", text: "快约 $46$ ms" },{ key: "B", text: "不变" },{ key: "C", text: "慢约 $46\\ \\mu$s" },{ key: "D", text: "快约 $46$ ns" },{ key: "E", text: "快约 $46\\ \\mu$s" }],
    answer: "E", solution: "$\\dfrac{3.99\\times10^{14}\\times(1.57\\times10^{-7}-3.76\\times10^{-8})}{9\\times10^{16}}\\approx5.3\\times10^{-10}$；乘 $86400$ s $\\approx46\\ \\mu$s/天（变快）。" },
  { id: "bpho-r2m4-t4-04", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：GPS 离不开相对论】GPS 卫星轨道半径 $r=2.66\\times10^{7}$ m，$GM_E=3.99\\times10^{14}\\ \\mathrm{m^3\\,s^{-2}}$，地球半径 $6.37\\times10^{6}$ m，$c=3\\times10^{8}$。 第4步：两个效应叠加，卫星钟每天净",
    options: [{ key: "A", text: "快约 $7\\ \\mu$s" },{ key: "B", text: "快约 $53\\ \\mu$s" },{ key: "C", text: "恰好抵消为零" },{ key: "D", text: "快约 $38\\ \\mu$s——GPS 出厂前就把星载钟频率预调慢以抵消" },{ key: "E", text: "慢约 $38\\ \\mu$s" }],
    answer: "D", solution: "$+46-7\\approx+38\\ \\mu$s/天：引力效应占上风（GPS 轨道够高）。工程上把 $10.23$ MHz 钟预调低 $4.57\\times10^{-3}$ Hz——相对论写进了出厂参数。" },
  { id: "bpho-r2m4-t4-05", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：GPS 离不开相对论】GPS 卫星轨道半径 $r=2.66\\times10^{7}$ m，$GM_E=3.99\\times10^{14}\\ \\mathrm{m^3\\,s^{-2}}$，地球半径 $6.37\\times10^{6}$ m，$c=3\\times10^{8}$。 第5步：若**不做**相对论修正，定位误差每天累积约",
    options: [{ key: "A", text: "$c\\times38\\ \\mu\\mathrm{s}\\approx11$ km/天——一天后 GPS 彻底报废" },{ key: "B", text: "$\\approx11$ cm/天" },{ key: "C", text: "$\\approx1.1$ km/年" },{ key: "D", text: "没有影响，误差不累积" },{ key: "E", text: "$\\approx11$ m/天，可以容忍" }],
    answer: "A", solution: "定位靠光速×时间差：$3\\times10^8\\times3.8\\times10^{-5}\\approx11.4$ km/天。相对论不是哲学玄谈，是你手机导航每天在用的工程参数。" },
  { id: "bpho-r2m4-t4-06", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：GPS 离不开相对论】GPS 卫星轨道半径 $r=2.66\\times10^{7}$ m，$GM_E=3.99\\times10^{14}\\ \\mathrm{m^3\\,s^{-2}}$，地球半径 $6.37\\times10^{6}$ m，$c=3\\times10^{8}$。 第6步：GPS 定位需要**至少几颗**卫星？为什么比「三维空间三个坐标」多一颗？",
    options: [{ key: "A", text: "4 颗——第 4 颗用来解出接收机自身廉价时钟的未知钟差" },{ key: "B", text: "3 颗，三维三坐标" },{ key: "C", text: "1 颗，测距即可" },{ key: "D", text: "2 颗，三角定位" },{ key: "E", text: "6 颗，每维两颗" }],
    answer: "A", solution: "接收机的石英钟差 $\\Delta t$ 是第 4 个未知数（$x,y,z,\\Delta t$）：4 个伪距方程解 4 个未知量。你的手机借 4 颗卫星「蹭」到了原子钟精度。" },
];
