// BPhO 模拟卷8 —— 模块1对标 Section 1 短题；模块2以高难选择题近似 Section 2 强度（真实 S2 为长题，见练习区 9 道原创长题）。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const BPHO_MK8_S1: MCQQuestion[] = [
  { id: "bpho-mk8-s1-01", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A block is on the verge of sliding down a rough incline when the angle reaches $30°$. Find the coefficient of static friction.",
    options: [{ key: "A", text: "$\\tan 30°\\approx0.58$" },{ key: "B", text: "$1.0$" },{ key: "C", text: "$0.30$" },{ key: "D", text: "$\\sin30°=0.50$" },{ key: "E", text: "$\\cos30°\\approx0.87$" }],
    answer: "A", solution: "At the point of slipping $\\mu=\\tan\\theta=\\tan30°\\approx0.58$ (the angle of friction)." },
  { id: "bpho-mk8-s1-02", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "The gravitational potential energy of a mass $m$ at the surface of a planet (radius $R$, mass $M$) is $-\\dfrac{GMm}{R}$. The minimum launch kinetic energy to escape to infinity is",
    options: [{ key: "A", text: "$\\dfrac{GMm}{R^2}$" },{ key: "B", text: "$\\dfrac{2GMm}{R}$" },{ key: "C", text: "$\\dfrac{GMm}{2R}$" },{ key: "D", text: "$\\dfrac{GMm}{R}$" },{ key: "E", text: "$0$" }],
    answer: "D", solution: "Escape needs total energy $\\ge0$: $KE_{\\min}=+\\dfrac{GMm}{R}$ (to cancel the potential well)." },
  { id: "bpho-mk8-s1-03", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A force of $21$ N pushes two blocks ($2$ kg then $5$ kg) that are in contact on a frictionless surface, pushing on the $2$ kg block. Find the contact force between them.",
    options: [{ key: "A", text: "$21$ N" },{ key: "B", text: "$10.5$ N" },{ key: "C", text: "$15$ N" },{ key: "D", text: "$3$ N" },{ key: "E", text: "$6$ N" }],
    answer: "C", solution: "$a=21/7=3\\ \\mathrm{m\\,s^{-2}}$. Contact force accelerates the $5$ kg block: $F=5\\times3=15$ N." },
  { id: "bpho-mk8-s1-04", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "A constant net force does work on a $2$ kg body, increasing its speed from $2\\ \\mathrm{m\\,s^{-1}}$ to $8\\ \\mathrm{m\\,s^{-1}}$. Find the work done.",
    options: [{ key: "A", text: "$120$ J" },{ key: "B", text: "$60$ J" },{ key: "C", text: "$64$ J" },{ key: "D", text: "$36$ J" },{ key: "E", text: "$30$ J" }],
    answer: "B", solution: "Work–energy: $W=\\tfrac12m(v^2-u^2)=\\tfrac12\\times2\\times(64-4)=60$ J." },
  { id: "bpho-mk8-s1-05", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "A simple pendulum has length $0.25$ m ($g=10$). Find its period.",
    options: [{ key: "A", text: "$\\approx0.25$ s" },{ key: "B", text: "$\\approx0.5$ s" },{ key: "C", text: "$\\approx1.0$ s" },{ key: "D", text: "$\\approx2.0$ s" },{ key: "E", text: "$\\approx3.1$ s" }],
    answer: "C", solution: "$T=2\\pi\\sqrt{L/g}=2\\pi\\sqrt{0.025}=2\\pi\\times0.158\\approx0.99$ s." },
  { id: "bpho-mk8-s1-06", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 4,
    question: "A wave of frequency $250$ Hz travels at $340\\ \\mathrm{m\\,s^{-1}}$. Find its wavelength.",
    options: [{ key: "A", text: "$2.72$ m" },{ key: "B", text: "$1.0$ m" },{ key: "C", text: "$1.36$ m" },{ key: "D", text: "$85$ m" },{ key: "E", text: "$0.74$ m" }],
    answer: "C", solution: "$\\lambda=v/f=340/250=1.36$ m." },
  { id: "bpho-mk8-s1-07", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 4,
    question: "Find the critical angle for total internal reflection at a water–air boundary ($n_{\\text{water}}=1.33$).",
    options: [{ key: "A", text: "$\\approx60°$" },{ key: "B", text: "$\\approx49°$" },{ key: "C", text: "$\\approx33°$" },{ key: "D", text: "$\\approx42°$" },{ key: "E", text: "$\\approx24°$" }],
    answer: "B", solution: "$\\sin C=1/n=1/1.33=0.752$, $C\\approx48.8°\\approx49°$." },
  { id: "bpho-mk8-s1-08", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 3,
    question: "Sound travels from air into water. Which quantity stays the same?",
    options: [{ key: "A", text: "both speed and wavelength" },{ key: "B", text: "speed" },{ key: "C", text: "frequency" },{ key: "D", text: "wavelength" },{ key: "E", text: "amplitude" }],
    answer: "C", solution: "Crossing a boundary, frequency is fixed by the source; speed and wavelength both change ($v=f\\lambda$)." },
  { id: "bpho-mk8-s1-09", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 1, marks: 3,
    question: "Two strings sound notes of $256$ Hz and $260$ Hz together. Find the beat frequency.",
    options: [{ key: "A", text: "$4$ Hz" },{ key: "B", text: "$516$ Hz" },{ key: "C", text: "$8$ Hz" },{ key: "D", text: "$2$ Hz" },{ key: "E", text: "$258$ Hz" }],
    answer: "A", solution: "Beat frequency $=|f_1-f_2|=4$ Hz." },
  { id: "bpho-mk8-s1-10", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 4,
    question: "A pipe closed at one end has length $L$. Its fundamental wavelength is",
    options: [{ key: "A", text: "$4L$" },{ key: "B", text: "$\\dfrac{L}{2}$" },{ key: "C", text: "$2L$" },{ key: "D", text: "$L$" },{ key: "E", text: "$\\dfrac{L}{4}$" }],
    answer: "A", solution: "Closed pipe: node at closed end, antinode at open end $\\Rightarrow L=\\lambda/4$, so $\\lambda=4L$." },
  { id: "bpho-mk8-s1-11", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 3,
    question: "A progressive wave has amplitude $A$. What is the total distance travelled by a particle of the medium in one full period?",
    options: [{ key: "A", text: "$A$" },{ key: "B", text: "$2A$" },{ key: "C", text: "$4A$" },{ key: "D", text: "$0$" },{ key: "E", text: "$8A$" }],
    answer: "C", solution: "In one period the particle goes $A$ up, $2A$ down, $A$ up = total path $4A$ (displacement returns to zero)." },
  { id: "bpho-mk8-s1-12", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 3,
    question: "For a stationary wave, the distance between two adjacent nodes is",
    options: [{ key: "A", text: "$\\lambda$" },{ key: "B", text: "$\\dfrac{\\lambda}{4}$" },{ key: "C", text: "$2\\lambda$" },{ key: "D", text: "$\\dfrac{3\\lambda}{2}$" },{ key: "E", text: "$\\dfrac{\\lambda}{2}$" }],
    answer: "E", solution: "Adjacent nodes are half a wavelength apart." },
  { id: "bpho-mk8-s1-13", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 1, marks: 3,
    question: "Resistors of $6\\ \\Omega$ and $3\\ \\Omega$ are connected in parallel. Find the equivalent resistance.",
    options: [{ key: "A", text: "$18\\ \\Omega$" },{ key: "B", text: "$4.5\\ \\Omega$" },{ key: "C", text: "$1\\ \\Omega$" },{ key: "D", text: "$9\\ \\Omega$" },{ key: "E", text: "$2\\ \\Omega$" }],
    answer: "E", solution: "$\\dfrac1R=\\dfrac16+\\dfrac13=\\dfrac12$, so $R=2\\ \\Omega$." },
];

export const BPHO_MK8_S2: MCQQuestion[] = [
  { id: "bpho-mk8-s2-01", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 5,
    question: "Use the uncertainty principle $\\Delta x\\,\\Delta p\\gtrsim\\hbar$ to estimate the minimum momentum uncertainty of an electron confined to an atom ($\\Delta x\\approx1\\times10^{-10}$ m). ($\\hbar=1.05\\times10^{-34}$ J s)",
    options: [{ key: "A", text: "$\\approx1\\times10^{-44}\\ \\mathrm{kg\\,m\\,s^{-1}}$" },{ key: "B", text: "$\\approx1\\times10^{-10}\\ \\mathrm{kg\\,m\\,s^{-1}}$" },{ key: "C", text: "$\\approx1\\times10^{-34}\\ \\mathrm{kg\\,m\\,s^{-1}}$" },{ key: "D", text: "$\\approx1\\times10^{-19}\\ \\mathrm{kg\\,m\\,s^{-1}}$" },{ key: "E", text: "$\\approx1\\times10^{-24}\\ \\mathrm{kg\\,m\\,s^{-1}}$" }],
    answer: "E", solution: "$\\Delta p\\approx\\dfrac{\\hbar}{\\Delta x}=\\dfrac{1.05\\times10^{-34}}{10^{-10}}\\approx1\\times10^{-24}\\ \\mathrm{kg\\,m\\,s^{-1}}$; the corresponding speed (~$10^6\\ \\mathrm{m\\,s^{-1}}$) sets the scale of electron motion in atoms." },
  { id: "bpho-mk8-s2-02", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A car rounds a frictionless banked curve of radius $50$ m banked at $45°$ ($g=10$). Find the design speed.",
    options: [{ key: "A", text: "$\\sqrt{50}\\approx7.1\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$50\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$500\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$\\sqrt{500}\\approx22\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$\\sqrt{250}\\approx16\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "D", solution: "No friction: $\\tan\\theta=\\dfrac{v^2}{rg}$, so $v=\\sqrt{rg\\tan\\theta}=\\sqrt{50\\times10\\times1}=\\sqrt{500}\\approx22\\ \\mathrm{m\\,s^{-1}}$." },
  { id: "bpho-mk8-s2-03", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A catapult with an ideal spring of stiffness $500\\ \\mathrm{N\\,m^{-1}}$ is drawn back $0.20$ m and launches a $0.20$ kg ball vertically ($g=10$). Neglecting the spring's mass, find the maximum height reached.",
    options: [{ key: "A", text: "$5.0$ m" },{ key: "B", text: "$1.0$ m" },{ key: "C", text: "$25$ m" },{ key: "D", text: "$2.5$ m" },{ key: "E", text: "$10$ m" }],
    answer: "A", solution: "Spring PE $=\\tfrac12kx^2=\\tfrac12\\times500\\times0.04=10$ J $=mgh$, so $h=\\dfrac{10}{0.2\\times10}=5.0$ m." },
  { id: "bpho-mk8-s2-04", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "Estimate the orbital period of the Moon: orbital radius $3.84\\times10^{8}$ m, Earth mass $6.0\\times10^{24}$ kg, $G=6.67\\times10^{-11}$. Give the answer in days.",
    options: [{ key: "A", text: "$\\approx7$ days" },{ key: "B", text: "$\\approx90$ days" },{ key: "C", text: "$\\approx1$ day" },{ key: "D", text: "$\\approx365$ days" },{ key: "E", text: "$\\approx27$ days" }],
    answer: "E", solution: "$T=2\\pi\\sqrt{r^3/GM}=2\\pi\\sqrt{(3.84\\times10^8)^3/(6.67\\times10^{-11}\\times6\\times10^{24})}\\approx2.4\\times10^6$ s $\\approx27$ days." },
  { id: "bpho-mk8-s2-05", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A $2.0$ kg block moving at $4.0\\ \\mathrm{m\\,s^{-1}}$ on a frictionless surface hits a fixed spring of stiffness $2000\\ \\mathrm{N\\,m^{-1}}$. Find the maximum compression.",
    options: [{ key: "A", text: "$0.13$ m" },{ key: "B", text: "$0.04$ m" },{ key: "C", text: "$0.20$ m" },{ key: "D", text: "$0.40$ m" },{ key: "E", text: "$0.08$ m" }],
    answer: "A", solution: "$\\tfrac12mv^2=\\tfrac12kx^2$: $x=v\\sqrt{m/k}=4\\sqrt{2/2000}=4\\times0.0316\\approx0.13$ m." },
  { id: "bpho-mk8-s2-06", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A torque of $12\\ \\mathrm{N\\,m}$ is applied to a uniform disc of mass $2.0$ kg and radius $0.40$ m ($I=\\tfrac12MR^2$). Find its angular acceleration.",
    options: [{ key: "A", text: "$150\\ \\mathrm{rad\\,s^{-2}}$" },{ key: "B", text: "$37.5\\ \\mathrm{rad\\,s^{-2}}$" },{ key: "C", text: "$18.75\\ \\mathrm{rad\\,s^{-2}}$" },{ key: "D", text: "$60\\ \\mathrm{rad\\,s^{-2}}$" },{ key: "E", text: "$75\\ \\mathrm{rad\\,s^{-2}}$" }],
    answer: "E", solution: "$I=\\tfrac12\\times2\\times0.16=0.16\\ \\mathrm{kg\\,m^2}$. $\\alpha=\\tau/I=12/0.16=75\\ \\mathrm{rad\\,s^{-2}}$." },
  { id: "bpho-mk8-s2-07", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A satellite is raised from a circular orbit of radius $2R$ to one of radius $3R$ (Earth radius $R$). Its total mechanical energy",
    options: [{ key: "A", text: "decreases" },{ key: "B", text: "increases (becomes less negative)" },{ key: "C", text: "becomes zero" },{ key: "D", text: "doubles in magnitude" },{ key: "E", text: "stays the same" }],
    answer: "B", solution: "$E=-\\dfrac{GMm}{2r}$; increasing $r$ makes $E$ less negative, i.e. larger. Raising an orbit requires adding energy." },
  { id: "bpho-mk8-s2-08", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "During a crash a $70$ kg passenger decelerates from $20\\ \\mathrm{m\\,s^{-1}}$ to rest in $0.10$ s. Express the average deceleration as a multiple of $g$ ($g=10$).",
    options: [{ key: "A", text: "$20g$" },{ key: "B", text: "$g$" },{ key: "C", text: "$2g$" },{ key: "D", text: "$10g$" },{ key: "E", text: "$200g$" }],
    answer: "A", solution: "$a=\\Delta v/\\Delta t=20/0.10=200\\ \\mathrm{m\\,s^{-2}}=20g$." },
  { id: "bpho-mk8-s2-09", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A $1$ kg ball at $9\\ \\mathrm{m\\,s^{-1}}$ collides head-on and sticks to a stationary $2$ kg ball. Find the kinetic energy converted to heat/deformation.",
    options: [{ key: "A", text: "$40.5$ J" },{ key: "B", text: "$9$ J" },{ key: "C", text: "$27$ J" },{ key: "D", text: "$54$ J" },{ key: "E", text: "$13.5$ J" }],
    answer: "C", solution: "Common speed $=9/3=3\\ \\mathrm{m\\,s^{-1}}$. $\\Delta KE=\\tfrac12(1)(81)-\\tfrac12(3)(9)=40.5-13.5=27$ J." },
  { id: "bpho-mk8-s2-10", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 3, marks: 4,
    question: "In Young's double-slit experiment the fringe spacing is $2.0$ mm. If the screen distance is doubled and the slit separation is halved, the new fringe spacing is",
    options: [{ key: "A", text: "$0.5$ mm" },{ key: "B", text: "$8.0$ mm" },{ key: "C", text: "$1.0$ mm" },{ key: "D", text: "$4.0$ mm" },{ key: "E", text: "$2.0$ mm" }],
    answer: "B", solution: "$w=\\dfrac{\\lambda D}{d}$: doubling $D$ and halving $d$ multiplies $w$ by $4$: $2.0\\times4=8.0$ mm." },
];
