// BPhO 模拟卷5 —— 模块1对标 Section 1 短题；模块2以高难选择题近似 Section 2 强度（真实 S2 为长题，见练习区 9 道原创长题）。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const BPHO_MK5_S1: MCQQuestion[] = [
  { id: "bpho-mk5-s1-01", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 4,
    question: "An ideal transformer steps $240$ V down to $12$ V. The secondary delivers $6.0$ A to a lamp. Find the current drawn from the $240$ V supply.",
    options: [{ key: "A", text: "$0.60$ A" },{ key: "B", text: "$120$ A" },{ key: "C", text: "$6.0$ A" },{ key: "D", text: "$1.2$ A" },{ key: "E", text: "$0.30$ A" }],
    answer: "E", solution: "Ideal: power in = power out. $I_p=\\dfrac{V_sI_s}{V_p}=\\dfrac{12\\times6}{240}=0.30$ A." },
  { id: "bpho-mk5-s1-02", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 3,
    question: "Two long straight parallel wires carry currents in the same direction. The force between them is",
    options: [{ key: "A", text: "repulsive" },{ key: "B", text: "alternating" },{ key: "C", text: "zero" },{ key: "D", text: "attractive" },{ key: "E", text: "perpendicular to the plane of the wires" }],
    answer: "D", solution: "Each wire sits in the magnetic field of the other; applying $F=BI\\ell$ with the field directions shows parallel (same-direction) currents attract, antiparallel repel." },
  { id: "bpho-mk5-s1-03", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 1, marks: 3,
    question: "An ideal gas is compressed isothermally to half its volume. Its pressure",
    options: [{ key: "A", text: "falls to one quarter" },{ key: "B", text: "stays the same" },{ key: "C", text: "doubles" },{ key: "D", text: "quadruples" },{ key: "E", text: "halves" }],
    answer: "C", solution: "Isothermal: $pV=$ const (Boyle), so halving $V$ doubles $p$." },
  { id: "bpho-mk5-s1-04", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 2, marks: 4,
    question: "$100$ g of water at $90\\ ^\\circ$C is mixed with $200$ g of water at $30\\ ^\\circ$C in an insulated container. Find the final temperature.",
    options: [{ key: "A", text: "$45\\ ^\\circ$C" },{ key: "B", text: "$50\\ ^\\circ$C" },{ key: "C", text: "$60\\ ^\\circ$C" },{ key: "D", text: "$40\\ ^\\circ$C" },{ key: "E", text: "$55\\ ^\\circ$C" }],
    answer: "B", solution: "Heat lost = heat gained (same $c$): $100(90-t)=200(t-30)$, so $9000-100t=200t-6000$, $t=50\\ ^\\circ$C — the mass-weighted mean." },
  { id: "bpho-mk5-s1-05", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 2, marks: 3,
    question: "Find the value of $pV$ for $3.0$ mol of an ideal gas at $300$ K. ($R=8.31\\ \\mathrm{J\\,mol^{-1}\\,K^{-1}}$)",
    options: [{ key: "A", text: "$\\approx9.0\\times10^{3}$ J" },{ key: "B", text: "$\\approx7.5\\times10^{2}$ J" },{ key: "C", text: "$\\approx7.5\\times10^{3}$ J" },{ key: "D", text: "$\\approx2.5\\times10^{3}$ J" },{ key: "E", text: "$\\approx2.5\\times10^{4}$ J" }],
    answer: "C", solution: "$pV=nRT=3.0\\times8.31\\times300\\approx7.5\\times10^3$ J." },
  { id: "bpho-mk5-s1-06", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 2, marks: 4,
    question: "A heat engine operates between a hot reservoir at $500$ K and a cold reservoir at $300$ K. Find its maximum possible (Carnot) efficiency.",
    options: [{ key: "A", text: "$100\\%$" },{ key: "B", text: "$40\\%$" },{ key: "C", text: "$67\\%$" },{ key: "D", text: "$60\\%$" },{ key: "E", text: "$30\\%$" }],
    answer: "B", solution: "$\\eta_{\\max}=1-\\dfrac{T_c}{T_h}=1-\\dfrac{300}{500}=0.40$ — temperatures must be in kelvin." },
  { id: "bpho-mk5-s1-07", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 2, marks: 3,
    question: "A steel rail of length $25$ m is heated through $40$ K. The linear expansivity of steel is $1.2\\times10^{-5}\\ \\mathrm{K^{-1}}$. Find the expansion.",
    options: [{ key: "A", text: "$1.2$ mm" },{ key: "B", text: "$48$ mm" },{ key: "C", text: "$12$ mm" },{ key: "D", text: "$4.8$ mm" },{ key: "E", text: "$0.12$ mm" }],
    answer: "C", solution: "$\\Delta L=\\alpha L\\Delta T=1.2\\times10^{-5}\\times25\\times40=1.2\\times10^{-2}$ m $=12$ mm." },
  { id: "bpho-mk5-s1-08", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 2, marks: 4,
    question: "A glass window pane has area $2.0\\ \\mathrm{m^2}$, thickness $6.0$ mm and thermal conductivity $0.80\\ \\mathrm{W\\,m^{-1}\\,K^{-1}}$. The temperature difference across it is $15$ K. Find the rate of heat conduction through it.",
    options: [{ key: "A", text: "$1.6$ kW" },{ key: "B", text: "$400$ W" },{ key: "C", text: "$24$ kW" },{ key: "D", text: "$40$ W" },{ key: "E", text: "$4.0$ kW" }],
    answer: "E", solution: "$P=\\dfrac{kA\\Delta T}{d}=\\dfrac{0.80\\times2.0\\times15}{0.006}=4000$ W. (Why real windows lose far less: still air layers dominate the insulation.)" },
  { id: "bpho-mk5-s1-09", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 2, marks: 3,
    question: "The specific latent heat of vaporisation of water is $2.26\\times10^{6}\\ \\mathrm{J\\,kg^{-1}}$. How much energy is carried away when $1.0$ g of sweat evaporates from the skin?",
    options: [{ key: "A", text: "$\\approx2.3\\times10^{4}$ J" },{ key: "B", text: "$\\approx2.3\\times10^{6}$ J" },{ key: "C", text: "$\\approx230$ J" },{ key: "D", text: "$\\approx23$ J" },{ key: "E", text: "$\\approx2.3\\times10^{3}$ J" }],
    answer: "E", solution: "$Q=mL=10^{-3}\\times2.26\\times10^6\\approx2.3\\times10^3$ J — evaporation is a powerful cooling mechanism." },
  { id: "bpho-mk5-s1-10", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 2, marks: 3,
    question: "At what temperature do the Celsius and Fahrenheit scales read the same value?",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$-40$" },{ key: "C", text: "$-32$" },{ key: "D", text: "$-73$" },{ key: "E", text: "$32$" }],
    answer: "B", solution: "$F=\\tfrac95C+32$; set $F=C$: $C=\\tfrac95C+32\\Rightarrow-\\tfrac45C=32\\Rightarrow C=-40$." },
  { id: "bpho-mk5-s1-11", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 2, marks: 4,
    question: "Light of photon energy $3.1$ eV strikes a metal of work function $2.1$ eV. Find the maximum kinetic energy of the emitted photoelectrons.",
    options: [{ key: "A", text: "$3.1$ eV" },{ key: "B", text: "$1.0$ eV" },{ key: "C", text: "$0.5$ eV" },{ key: "D", text: "$2.1$ eV" },{ key: "E", text: "$5.2$ eV" }],
    answer: "B", solution: "Einstein's photoelectric equation: $KE_{\\max}=hf-\\phi=3.1-2.1=1.0$ eV." },
  { id: "bpho-mk5-s1-12", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 2, marks: 4,
    question: "A sample of carbon-14 (half-life $5730$ years) has decayed until only $1/8$ of the original nuclei remain. How old is the sample?",
    options: [{ key: "A", text: "$5730$ years" },{ key: "B", text: "$45840$ years" },{ key: "C", text: "$22920$ years" },{ key: "D", text: "$17190$ years" },{ key: "E", text: "$11460$ years" }],
    answer: "D", solution: "$1/8=(1/2)^3$: three half-lives, $3\\times5730=17190$ years." },
  { id: "bpho-mk5-s1-13", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 2, marks: 3,
    question: "Using $E=mc^2$, find the energy equivalent of $1.0$ g of mass. ($c=3.0\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$)",
    options: [{ key: "A", text: "$3.0\\times10^{5}$ J" },{ key: "B", text: "$9.0\\times10^{16}$ J" },{ key: "C", text: "$3.0\\times10^{11}$ J" },{ key: "D", text: "$9.0\\times10^{10}$ J" },{ key: "E", text: "$9.0\\times10^{13}$ J" }],
    answer: "E", solution: "$E=10^{-3}\\times(3\\times10^8)^2=9\\times10^{13}$ J — roughly the energy of a small nuclear weapon, from a paperclip's worth of mass." },
];

export const BPHO_MK5_S2: MCQQuestion[] = [
  { id: "bpho-mk5-s2-01", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A force $F(x) = (20 - 3x^2)\\ \\mathrm{N}$ (with $x$ in metres) acts on a body along the $x$-axis. Find the work done as the body moves from $x=0$ to $x=4\\ \\mathrm{m}$.",
    options: [{ key: "A", text: "$64$ J" },{ key: "B", text: "$128$ J" },{ key: "C", text: "$16$ J" },{ key: "D", text: "$80$ J" },{ key: "E", text: "$-16$ J" }],
    answer: "C", solution: "$W=\\int_0^4 (20-3x^2)\\,dx=[20x-x^3]_0^4=80-64=16$ J. The cubic term removes most of the work done by the constant part of the force." },
  { id: "bpho-mk5-s2-02", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A particle moves so that its velocity decreases linearly with position: $v = v_0(1 - x/L)$. Find its acceleration as a function of $x$.",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$\\dfrac{v_0^2}{L^2}x$" },{ key: "C", text: "$-\\dfrac{v_0}{L}$" },{ key: "D", text: "$-\\dfrac{v_0^2}{L}\\left(1-\\dfrac{x}{L}\\right)$" },{ key: "E", text: "$-\\dfrac{v_0^2}{L}$" }],
    answer: "D", solution: "$a=v\\dfrac{dv}{dx}=v_0(1-x/L)\\cdot\\left(-\\dfrac{v_0}{L}\\right)=-\\dfrac{v_0^2}{L}(1-x/L)$. The particle never quite reaches $x=L$ (velocity and acceleration both $\\to0$)." },
  { id: "bpho-mk5-s2-03", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "A rocket in deep space ejects fuel at exhaust speed $u$ relative to itself. Ignoring gravity, what is the change in the rocket's speed when its mass falls from $M_0$ to $M_0/e$?",
    options: [{ key: "A", text: "$2u$" },{ key: "B", text: "$eu$" },{ key: "C", text: "$u/e$" },{ key: "D", text: "$u\\ln 2$" },{ key: "E", text: "$u$" }],
    answer: "E", solution: "Tsiolkovsky: $\\Delta v=u\\ln\\dfrac{M_0}{M}=u\\ln\\dfrac{M_0}{M_0/e}=u\\ln e=u$. Losing a factor $e$ of mass buys exactly one exhaust-speed of $\\Delta v$." },
  { id: "bpho-mk5-s2-04", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A uniform chain hangs vertically with its lower end just touching a table, then is released. Compared with the weight of chain already on the table, the force the falling chain exerts on the table when a length $x$ has landed is",
    options: [{ key: "A", text: "twice that weight" },{ key: "B", text: "three times that weight" },{ key: "C", text: "equal to that weight" },{ key: "D", text: "half that weight" },{ key: "E", text: "four times that weight" }],
    answer: "B", solution: "Two contributions: the static weight of length $x$ ($\\lambda x g$) plus the momentum flux of arriving links moving at $v=\\sqrt{2gx}$: $\\dfrac{dp}{dt}=\\lambda v\\cdot v=\\lambda(2gx)=2\\lambda x g$. Total $=3\\lambda x g$, i.e. three times the resting weight." },
  { id: "bpho-mk5-s2-05", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A ball is thrown at $25\\ \\mathrm{m\\,s^{-1}}$ at an angle with $\\cos\\theta=0.6$, $\\sin\\theta=0.8$ ($g=10$). Find its height above the launch point $1.0$ s after launch.",
    options: [{ key: "A", text: "$15$ m" },{ key: "B", text: "$11$ m" },{ key: "C", text: "$25$ m" },{ key: "D", text: "$20$ m" },{ key: "E", text: "$5$ m" }],
    answer: "A", solution: "$v_y=25\\times0.8=20\\ \\mathrm{m\\,s^{-1}}$; height $=v_y t-\\tfrac12 g t^2=20-5=15$ m." },
  { id: "bpho-mk5-s2-06", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "Two masses, $1$ kg at rest and $3$ kg moving at $8\\ \\mathrm{m\\,s^{-1}}$, are on a frictionless surface. Find the speed of their centre of mass.",
    options: [{ key: "A", text: "$5\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$8\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$2\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$4\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$6\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "E", solution: "$v_{cm}=\\dfrac{1\\cdot0+3\\cdot8}{4}=6\\ \\mathrm{m\\,s^{-1}}$; unaffected by any internal collision." },
  { id: "bpho-mk5-s2-07", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A uniform solid sphere ($I=\\tfrac25 mr^2$) rolls without slipping from rest down a slope, dropping a height of $1.4$ m ($g=10$). Find its speed at the bottom.",
    options: [{ key: "A", text: "$\\sqrt{28}\\approx5.3\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$\\sqrt{14}\\approx3.7\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$5.0\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$\\sqrt{10}\\approx3.2\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$\\sqrt{20}\\approx4.5\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "E", solution: "$mgh=\\tfrac12mv^2(1+\\tfrac25)=\\tfrac{7}{10}mv^2$, so $v=\\sqrt{\\dfrac{10gh}{7}}=\\sqrt{\\dfrac{10\\cdot10\\cdot1.4}{7}}=\\sqrt{20}\\approx4.5$." },
  { id: "bpho-mk5-s2-08", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A projectile is fired vertically from a planet's surface at half the escape speed. Ignoring air resistance, what fraction of the planet's radius does it rise to (as a height above the surface)?",
    options: [{ key: "A", text: "$R$" },{ key: "B", text: "$\\dfrac{1}{3}R$" },{ key: "C", text: "$\\dfrac{1}{2\\sqrt2}R$" },{ key: "D", text: "$\\dfrac{1}{2}R$" },{ key: "E", text: "$\\dfrac{1}{4}R$" }],
    answer: "B", solution: "Energy: $\\tfrac12 v^2-\\dfrac{GM}{R}=-\\dfrac{GM}{R+h}$ with $v=\\tfrac12 v_e=\\tfrac12\\sqrt{2GM/R}$. Then $\\tfrac14\\dfrac{GM}{R}-\\dfrac{GM}{R}=-\\dfrac{GM}{R+h}$ gives $\\dfrac{1}{R+h}=\\dfrac{3}{4R}$, so $R+h=\\tfrac43R$, $h=\\tfrac13R$." },
  { id: "bpho-mk5-s2-09", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "Four point masses $m$ sit at the corners of a square of side $a$. Find the moment of inertia about an axis through the centre, perpendicular to the plane.",
    options: [{ key: "A", text: "$ma^2$" },{ key: "B", text: "$4ma^2$" },{ key: "C", text: "$2ma^2$" },{ key: "D", text: "$\\sqrt2\\,ma^2$" },{ key: "E", text: "$\\dfrac{ma^2}{2}$" }],
    answer: "C", solution: "Each mass is at distance $\\dfrac{a}{\\sqrt2}$ from the centre: $I=4m\\left(\\dfrac{a}{\\sqrt2}\\right)^2=4m\\cdot\\dfrac{a^2}{2}=2ma^2$." },
  { id: "bpho-mk5-s2-10", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A simple pendulum hangs in a lift that accelerates upwards at $5.0\\ \\mathrm{m\\,s^{-2}}$ ($g=10$). By what factor does its oscillation frequency change compared with the lift at rest?",
    options: [{ key: "A", text: "$1.5$" },{ key: "B", text: "$\\sqrt{1.5}\\approx1.22$" },{ key: "C", text: "unchanged" },{ key: "D", text: "$\\sqrt{2}\\approx1.41$" },{ key: "E", text: "$\\sqrt{0.5}\\approx0.71$" }],
    answer: "B", solution: "Effective gravity $g'=g+a=15$. $f\\propto\\sqrt{g'}$, factor $=\\sqrt{15/10}=\\sqrt{1.5}\\approx1.22$." },
];
