// BPhO 模拟卷4 —— 模块1对标 Section 1（短题）；模块2以高难选择题近似 Section 2 强度（真实 S2 为长推导题，请配合练习区 9 道原创长题自评）。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const BPHO_MK4_S1: MCQQuestion[] = [
  { id: "bpho-mk4-s1-01", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 4,
    question: "The length of a simple pendulum is increased by $21\\%$. By what percentage does its period increase?",
    options: [{ key: "A", text: "$5\\%$" },{ key: "B", text: "$21\\%$" },{ key: "C", text: "$10\\%$" },{ key: "D", text: "$4.6\\%$" },{ key: "E", text: "$11\\%$" }],
    answer: "C", solution: "$T\\propto\\sqrt{\\ell}$: factor $\\sqrt{1.21}=1.10$, i.e. a $10\\%$ increase." },
  { id: "bpho-mk4-s1-02", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 3,
    question: "A particle oscillates in SHM with amplitude $5.0$ cm and frequency $2.0$ Hz. Find its maximum speed.",
    options: [{ key: "A", text: "$0.20\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$0.10\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$\\dfrac{\\pi}{5}\\approx0.63\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$2\\pi\\approx6.3\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$\\pi\\approx3.1\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "C", solution: "$v_{\\max}=A\\omega=A\\cdot2\\pi f=0.05\\times4\\pi=\\dfrac{\\pi}{5}\\approx0.63\\ \\mathrm{m\\,s^{-1}}$." },
  { id: "bpho-mk4-s1-03", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 3,
    question: "The intensity of a sound is increased by a factor of $100$. By how much does the sound intensity level rise?",
    options: [{ key: "A", text: "$10$ dB" },{ key: "B", text: "$20$ dB" },{ key: "C", text: "$2$ dB" },{ key: "D", text: "$100$ dB" },{ key: "E", text: "$40$ dB" }],
    answer: "B", solution: "$\\Delta L=10\\log_{10}(I_2/I_1)=10\\log_{10}100=20$ dB." },
  { id: "bpho-mk4-s1-04", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 1, marks: 3,
    question: "Light enters glass of refractive index $1.5$. Find the speed of light in the glass.",
    options: [{ key: "A", text: "$1.0\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$2.0\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$1.5\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$3.0\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$4.5\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "B", solution: "$v=c/n=3.0\\times10^8/1.5=2.0\\times10^8\\ \\mathrm{m\\,s^{-1}}$." },
  { id: "bpho-mk4-s1-05", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 3,
    question: "For a medium of refractive index $\\sqrt{2}$ in air, find the critical angle for total internal reflection.",
    options: [{ key: "A", text: "$90°$" },{ key: "B", text: "$45°$" },{ key: "C", text: "$60°$" },{ key: "D", text: "$35.3°$" },{ key: "E", text: "$30°$" }],
    answer: "B", solution: "$\\sin C=1/n=1/\\sqrt2$, so $C=45°$." },
  { id: "bpho-mk4-s1-06", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 3,
    question: "Two points on a progressive wave are separated by a quarter of a wavelength. What is the phase difference between their oscillations?",
    options: [{ key: "A", text: "$\\pi$" },{ key: "B", text: "$\\dfrac{\\pi}{2}$" },{ key: "C", text: "$\\dfrac{3\\pi}{2}$" },{ key: "D", text: "$2\\pi$" },{ key: "E", text: "$\\dfrac{\\pi}{4}$" }],
    answer: "B", solution: "Phase difference $=\\dfrac{2\\pi}{\\lambda}\\times\\dfrac{\\lambda}{4}=\\dfrac{\\pi}{2}$." },
  { id: "bpho-mk4-s1-07", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 4,
    question: "In a balanced Wheatstone bridge with resistances $R_1,R_2$ in one pair of arms and $R_3,R_4$ in the other (so no current flows through the galvanometer), which relation holds?",
    options: [{ key: "A", text: "$R_1=R_4$" },{ key: "B", text: "$\\dfrac{R_1}{R_3}=\\dfrac{R_4}{R_2}$" },{ key: "C", text: "$\\dfrac{R_1}{R_2}=\\dfrac{R_3}{R_4}$" },{ key: "D", text: "$R_1R_2=R_3R_4$" },{ key: "E", text: "$R_1+R_4=R_2+R_3$" }],
    answer: "C", solution: "No galvanometer current means the two junctions are at equal potential, so the arms divide the voltage identically: $R_1/R_2=R_3/R_4$." },
  { id: "bpho-mk4-s1-08", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 1, marks: 3,
    question: "Two resistors of $6\\ \\Omega$ and $3\\ \\Omega$ are connected in series across a battery. Find the ratio of the power dissipated in the $6\\ \\Omega$ resistor to that in the $3\\ \\Omega$ resistor.",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$1$" },{ key: "C", text: "$\\dfrac{1}{2}$" },{ key: "D", text: "$\\dfrac{1}{4}$" },{ key: "E", text: "$4$" }],
    answer: "A", solution: "Series: same current, $P=I^2R\\propto R$. Ratio $=6/3=2$." },
  { id: "bpho-mk4-s1-09", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 4,
    question: "A battery of e.m.f. $12$ V delivers a current of $4.0$ A while its terminal voltage reads $10$ V. Find its internal resistance.",
    options: [{ key: "A", text: "$2.5\\ \\Omega$" },{ key: "B", text: "$0.50\\ \\Omega$" },{ key: "C", text: "$3.0\\ \\Omega$" },{ key: "D", text: "$1.0\\ \\Omega$" },{ key: "E", text: "$0.25\\ \\Omega$" }],
    answer: "B", solution: "Lost volts $=\\varepsilon-V=2$ V across $r$: $r=2/4=0.50\\ \\Omega$." },
  { id: "bpho-mk4-s1-10", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 4,
    question: "Point charges $+Q$ and $-Q$ are a distance $d$ apart. Find the magnitude of the electric field at the midpoint between them ($k=1/4\\pi\\varepsilon_0$).",
    options: [{ key: "A", text: "$\\dfrac{4kQ}{d^2}$" },{ key: "B", text: "$\\dfrac{8kQ}{d^2}$" },{ key: "C", text: "$\\dfrac{kQ}{d^2}$" },{ key: "D", text: "$0$" },{ key: "E", text: "$\\dfrac{2kQ}{d^2}$" }],
    answer: "B", solution: "Each charge produces $\\dfrac{kQ}{(d/2)^2}=\\dfrac{4kQ}{d^2}$ at the midpoint, and for opposite charges the two fields point the SAME way (from $+$ towards $-$), adding to $\\dfrac{8kQ}{d^2}$." },
  { id: "bpho-mk4-s1-11", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 4,
    question: "A charged particle of mass $m$ and charge $q$ moves at speed $v$ perpendicular to a uniform magnetic field $B$. Find the radius of its circular path.",
    options: [{ key: "A", text: "$\\dfrac{qB}{mv}$" },{ key: "B", text: "$\\dfrac{qvB}{m}$" },{ key: "C", text: "$\\dfrac{v}{qB}$" },{ key: "D", text: "$\\dfrac{mB}{qv}$" },{ key: "E", text: "$\\dfrac{mv}{qB}$" }],
    answer: "E", solution: "Magnetic force provides centripetal force: $qvB=\\dfrac{mv^2}{r}$, so $r=\\dfrac{mv}{qB}$." },
  { id: "bpho-mk4-s1-12", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 3,
    question: "In a velocity selector, an electric field $E$ and magnetic field $B$ are arranged perpendicular to each other and to the beam. Charged particles pass through undeflected when their speed is",
    options: [{ key: "A", text: "$\\dfrac{E}{B}$" },{ key: "B", text: "$\\sqrt{EB}$" },{ key: "C", text: "$EB$" },{ key: "D", text: "$\\dfrac{B}{E}$" },{ key: "E", text: "$\\dfrac{E^2}{B}$" }],
    answer: "A", solution: "Undeflected when electric and magnetic forces balance: $qE=qvB$, so $v=E/B$ — independent of the charge and mass." },
  { id: "bpho-mk4-s1-13", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 4,
    question: "A conducting rod of length $0.40$ m moves at $10\\ \\mathrm{m\\,s^{-1}}$ perpendicular to both its length and a uniform magnetic field of $0.50$ T. Find the e.m.f. induced across the rod.",
    options: [{ key: "A", text: "$0.5$ V" },{ key: "B", text: "$2.0$ V" },{ key: "C", text: "$20$ V" },{ key: "D", text: "$0.2$ V" },{ key: "E", text: "$5.0$ V" }],
    answer: "B", solution: "$\\varepsilon=B\\ell v=0.50\\times0.40\\times10=2.0$ V." },
];

export const BPHO_MK4_S2: MCQQuestion[] = [
  { id: "bpho-mk4-s2-01", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 3, marks: 3,
    question: "The internal energy of $n$ moles of a monatomic ideal gas at temperature $T$ is",
    options: [{ key: "A", text: "$\\dfrac{3}{2}nRT$" },{ key: "B", text: "$\\dfrac{1}{2}nRT$" },{ key: "C", text: "$nRT$" },{ key: "D", text: "$3nRT$" },{ key: "E", text: "$\\dfrac{5}{2}nRT$" }],
    answer: "A", solution: "Three translational degrees of freedom, each contributing $\\tfrac12k_BT$ per molecule: $U=\\tfrac32nRT$." },
  { id: "bpho-mk4-s2-02", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 3, marks: 3,
    question: "A black body's absolute temperature is doubled. The total power it radiates increases by a factor of",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$2$" },{ key: "C", text: "$32$" },{ key: "D", text: "$16$" },{ key: "E", text: "$8$" }],
    answer: "D", solution: "Stefan–Boltzmann: $P\\propto T^4$, so $2^4=16$." },
  { id: "bpho-mk4-s2-03", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 4,
    question: "Find the de Broglie wavelength of an electron moving at $1.0\\times10^{6}\\ \\mathrm{m\\,s^{-1}}$. ($h=6.6\\times10^{-34}$ J s, $m_e=9.1\\times10^{-31}$ kg)",
    options: [{ key: "A", text: "$\\approx7.3\\times10^{-10}$ m" },{ key: "B", text: "$\\approx6.0\\times10^{-28}$ m" },{ key: "C", text: "$\\approx3.6\\times10^{-10}$ m" },{ key: "D", text: "$\\approx1.4\\times10^{-9}$ m" },{ key: "E", text: "$\\approx7.3\\times10^{-7}$ m" }],
    answer: "A", solution: "$\\lambda=\\dfrac{h}{mv}=\\dfrac{6.6\\times10^{-34}}{9.1\\times10^{-31}\\times10^{6}}\\approx7.3\\times10^{-10}$ m — about atomic size, which is why electrons diffract off crystals." },
  { id: "bpho-mk4-s2-04", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 4,
    question: "In the hydrogen atom the energy levels are $E_n=-13.6/n^2$ eV. Find the energy of the photon emitted in the transition $n=2\\to n=1$.",
    options: [{ key: "A", text: "$6.8$ eV" },{ key: "B", text: "$10.2$ eV" },{ key: "C", text: "$1.9$ eV" },{ key: "D", text: "$3.4$ eV" },{ key: "E", text: "$13.6$ eV" }],
    answer: "B", solution: "$\\Delta E=13.6\\left(1-\\dfrac14\\right)=13.6\\times\\dfrac34=10.2$ eV (the Lyman-α line)." },
  { id: "bpho-mk4-s2-05", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 4,
    question: "A muon travels at $0.60c$. Find the Lorentz factor $\\gamma$.",
    options: [{ key: "A", text: "$0.80$" },{ key: "B", text: "$1.36$" },{ key: "C", text: "$1.25$" },{ key: "D", text: "$2.5$" },{ key: "E", text: "$1.67$" }],
    answer: "C", solution: "$\\gamma=\\dfrac{1}{\\sqrt{1-v^2/c^2}}=\\dfrac{1}{\\sqrt{1-0.36}}=\\dfrac{1}{0.8}=1.25$." },
  { id: "bpho-mk4-s2-06", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 4,
    question: "In a nuclear reaction the total mass decreases by $0.030$ u. Find the energy released. ($1$ u $=931.5$ MeV$/c^2$)",
    options: [{ key: "A", text: "$\\approx2.8$ MeV" },{ key: "B", text: "$\\approx931$ MeV" },{ key: "C", text: "$\\approx280$ MeV" },{ key: "D", text: "$\\approx0.03$ MeV" },{ key: "E", text: "$\\approx28$ MeV" }],
    answer: "E", solution: "$E=\\Delta m\\,c^2=0.030\\times931.5\\approx28$ MeV." },
  { id: "bpho-mk4-s2-07", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 3,
    question: "Find the momentum of a photon of wavelength $500$ nm. ($h=6.6\\times10^{-34}$ J s)",
    options: [{ key: "A", text: "$\\approx4.0\\times10^{-19}\\ \\mathrm{kg\\,m\\,s^{-1}}$" },{ key: "B", text: "$0$" },{ key: "C", text: "$\\approx1.3\\times10^{-27}\\ \\mathrm{kg\\,m\\,s^{-1}}$" },{ key: "D", text: "$\\approx1.3\\times10^{-24}\\ \\mathrm{kg\\,m\\,s^{-1}}$" },{ key: "E", text: "$\\approx3.3\\times10^{-40}\\ \\mathrm{kg\\,m\\,s^{-1}}$" }],
    answer: "C", solution: "$p=\\dfrac{h}{\\lambda}=\\dfrac{6.6\\times10^{-34}}{5.0\\times10^{-7}}\\approx1.3\\times10^{-27}\\ \\mathrm{kg\\,m\\,s^{-1}}$." },
  { id: "bpho-mk4-s2-08", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 5,
    question: "Estimate the total mass of the Earth's atmosphere, given atmospheric pressure $1.0\\times10^{5}$ Pa, Earth radius $6.4\\times10^{6}$ m and $g=10\\ \\mathrm{m\\,s^{-2}}$.",
    options: [{ key: "A", text: "$\\approx5\\times10^{22}$ kg" },{ key: "B", text: "$\\approx6\\times10^{24}$ kg" },{ key: "C", text: "$\\approx5\\times10^{18}$ kg" },{ key: "D", text: "$\\approx5\\times10^{16}$ kg" },{ key: "E", text: "$\\approx5\\times10^{14}$ kg" }],
    answer: "C", solution: "Pressure = weight per unit area: $M=\\dfrac{p_0\\times4\\pi R^2}{g}=\\dfrac{10^5\\times4\\pi(6.4\\times10^6)^2}{10}\\approx5\\times10^{18}$ kg." },
  { id: "bpho-mk4-s2-09", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 4,
    question: "In the laboratory frame a muon travels $100$ m through the atmosphere with Lorentz factor $\\gamma=5$. What distance does this correspond to in the muon's own rest frame?",
    options: [{ key: "A", text: "$25$ m" },{ key: "B", text: "$4$ m" },{ key: "C", text: "$100$ m" },{ key: "D", text: "$500$ m" },{ key: "E", text: "$20$ m" }],
    answer: "E", solution: "Length contraction: $L=\\dfrac{L_0}{\\gamma}=\\dfrac{100}{5}=20$ m — from the muon's viewpoint the atmosphere is contracted, which is why muons reach the ground." },
  { id: "bpho-mk4-s2-10", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 4,
    question: "A radioactive source contains $1.0\\times10^{20}$ nuclei with a half-life of $10$ days. Estimate its activity. ($1$ day $=86400$ s)",
    options: [{ key: "A", text: "$\\approx2\\times10^{15}$ Bq" },{ key: "B", text: "$\\approx1\\times10^{19}$ Bq" },{ key: "C", text: "$\\approx8\\times10^{10}$ Bq" },{ key: "D", text: "$\\approx8\\times10^{13}$ Bq" },{ key: "E", text: "$\\approx7\\times10^{18}$ Bq" }],
    answer: "D", solution: "$A=\\lambda N=\\dfrac{\\ln2}{T_{1/2}}N=\\dfrac{0.693}{8.64\\times10^{5}}\\times10^{20}\\approx8\\times10^{13}$ Bq." },
];
