// BPhO 模拟卷3 —— 模块1对标 Section 1（短题）；模块2以高难选择题近似 Section 2 强度（真实 S2 为长推导题，请配合练习区 9 道原创长题自评）。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const BPHO_MK3_S1: MCQQuestion[] = [
  { id: "bpho-mk3-s1-01", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A $0.20$ kg ball hits a wall horizontally at $20\\ \\mathrm{m\\,s^{-1}}$ and rebounds along the same line at $15\\ \\mathrm{m\\,s^{-1}}$. The contact lasts $0.050$ s. Find the average force on the ball.",
    options: [{ key: "A", text: "$140$ N" },{ key: "B", text: "$20$ N" },{ key: "C", text: "$70$ N" },{ key: "D", text: "$100$ N" },{ key: "E", text: "$60$ N" }],
    answer: "A", solution: "Impulse $=\\Delta p=0.20\\times(20+15)=7.0\\ \\mathrm{kg\\,m\\,s^{-1}}$ (velocity reverses). $F=\\Delta p/\\Delta t=7.0/0.050=140$ N." },
  { id: "bpho-mk3-s1-02", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "A ball is dropped from height $h$ and rebounds to height $0.64h$. Find the coefficient of restitution with the floor.",
    options: [{ key: "A", text: "$0.9$" },{ key: "B", text: "$0.4$" },{ key: "C", text: "$0.8$" },{ key: "D", text: "$0.64$" },{ key: "E", text: "$0.36$" }],
    answer: "C", solution: "$e=\\dfrac{v_{\\text{after}}}{v_{\\text{before}}}=\\sqrt{\\dfrac{h_2}{h_1}}=\\sqrt{0.64}=0.8$ (since $v\\propto\\sqrt h$)." },
  { id: "bpho-mk3-s1-03", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "A spring of stiffness $200\\ \\mathrm{N\\,m^{-1}}$ is stretched from an extension of $0.10$ m to an extension of $0.30$ m. Find the work done.",
    options: [{ key: "A", text: "$9.0$ J" },{ key: "B", text: "$16$ J" },{ key: "C", text: "$8.0$ J" },{ key: "D", text: "$1.0$ J" },{ key: "E", text: "$4.0$ J" }],
    answer: "C", solution: "$W=\\tfrac12k(x_2^2-x_1^2)=\\tfrac12\\times200\\times(0.09-0.01)=8.0$ J — NOT $\\tfrac12k(x_2-x_1)^2=4$ J, the classic trap." },
  { id: "bpho-mk3-s1-04", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "A projectile is launched at $60°$ to the horizontal. Find the ratio of its kinetic energy at the top of its flight to its initial kinetic energy.",
    options: [{ key: "A", text: "$\\dfrac{1}{2}$" },{ key: "B", text: "$0$" },{ key: "C", text: "$\\dfrac{1}{4}$" },{ key: "D", text: "$\\dfrac{3}{4}$" },{ key: "E", text: "$\\dfrac{\\sqrt{3}}{2}$" }],
    answer: "C", solution: "At the top only the horizontal component $v\\cos60°=v/2$ remains: ratio $=\\cos^2 60°=\\dfrac14$." },
  { id: "bpho-mk3-s1-05", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 1, marks: 3,
    question: "A child of mass $30$ kg sits $2.0$ m from the pivot of a seesaw. At what distance on the other side must a $40$ kg child sit to balance it?",
    options: [{ key: "A", text: "$1.0$ m" },{ key: "B", text: "$2.7$ m" },{ key: "C", text: "$0.75$ m" },{ key: "D", text: "$2.0$ m" },{ key: "E", text: "$1.5$ m" }],
    answer: "E", solution: "Moments: $30\\times2.0=40\\times x$, so $x=1.5$ m." },
  { id: "bpho-mk3-s1-06", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A flywheel spinning at $20\\ \\mathrm{rad\\,s^{-1}}$ decelerates uniformly to rest in $5.0$ s. How many complete revolutions does it make while stopping?",
    options: [{ key: "A", text: "$50$" },{ key: "B", text: "$16$" },{ key: "C", text: "$8$" },{ key: "D", text: "$25$" },{ key: "E", text: "$7$ (i.e. $\\lfloor 25/\\pi\\rfloor$)" }],
    answer: "E", solution: "Angle turned $=\\bar\\omega t=\\tfrac12\\times20\\times5=50$ rad $=\\dfrac{50}{2\\pi}\\approx7.96$ rev, so $7$ complete revolutions." },
  { id: "bpho-mk3-s1-07", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "Kepler's second law (equal areas in equal times) is a direct consequence of the conservation of which quantity for a planet orbiting the Sun?",
    options: [{ key: "A", text: "Total mechanical energy" },{ key: "B", text: "Linear momentum" },{ key: "C", text: "Angular momentum" },{ key: "D", text: "Angular velocity" },{ key: "E", text: "Kinetic energy" }],
    answer: "C", solution: "The Sun's gravity is central (along the radius), exerting zero torque about the Sun, so angular momentum $L=mvr_\\perp$ is conserved; the areal rate is $\\dfrac{dA}{dt}=\\dfrac{L}{2m}=$ constant." },
  { id: "bpho-mk3-s1-08", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 1, marks: 3,
    question: "A pendulum clock keeps correct time on Earth. Taken to the Moon where $g$ is $1/6$ of Earth's, the period of its pendulum becomes",
    options: [{ key: "A", text: "$\\sqrt{6}$ times shorter" },{ key: "B", text: "unchanged" },{ key: "C", text: "$36$ times longer" },{ key: "D", text: "$\\sqrt{6}$ times longer" },{ key: "E", text: "$6$ times longer" }],
    answer: "D", solution: "$T=2\\pi\\sqrt{\\ell/g}\\propto g^{-1/2}$: with $g\\to g/6$, $T\\to\\sqrt6\\,T$." },
  { id: "bpho-mk3-s1-09", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 4,
    question: "A particle performs SHM with amplitude $A$. When its displacement is $x=A/2$, what fraction of the total energy is kinetic?",
    options: [{ key: "A", text: "$\\dfrac{3}{4}$" },{ key: "B", text: "$\\dfrac{1}{2}$" },{ key: "C", text: "$\\dfrac{2}{3}$" },{ key: "D", text: "$\\dfrac{1}{4}$" },{ key: "E", text: "$\\dfrac{\\sqrt{3}}{2}$" }],
    answer: "A", solution: "$E_p\\propto x^2$: at $x=A/2$, $E_p=\\dfrac14E$, so $E_k=\\dfrac34E$." },
  { id: "bpho-mk3-s1-10", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 4,
    question: "A wave is described by $y=(2.0\\ \\mathrm{mm})\\cos(600t-2.0x)$ with $t$ in seconds and $x$ in metres. Find the wave speed.",
    options: [{ key: "A", text: "$2.0\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$600\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$300\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$1200\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$150\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "C", solution: "Compare with $y=A\\cos(\\omega t-kx)$: $\\omega=600\\ \\mathrm{rad\\,s^{-1}}$, $k=2.0\\ \\mathrm{rad\\,m^{-1}}$. $v=\\omega/k=300\\ \\mathrm{m\\,s^{-1}}$." },
  { id: "bpho-mk3-s1-11", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 4,
    question: "A string of length $1.5$ m is fixed at both ends; waves travel along it at $120\\ \\mathrm{m\\,s^{-1}}$. Find the frequency of the third harmonic.",
    options: [{ key: "A", text: "$80$ Hz" },{ key: "B", text: "$120$ Hz" },{ key: "C", text: "$240$ Hz" },{ key: "D", text: "$40$ Hz" },{ key: "E", text: "$60$ Hz" }],
    answer: "B", solution: "Harmonics: $f_n=\\dfrac{nv}{2L}$. $f_3=\\dfrac{3\\times120}{2\\times1.5}=120$ Hz." },
  { id: "bpho-mk3-s1-12", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 1, marks: 3,
    question: "Two tuning forks of frequencies $512$ Hz and $516$ Hz are sounded together. What beat frequency is heard?",
    options: [{ key: "A", text: "$8$ Hz" },{ key: "B", text: "$2$ Hz" },{ key: "C", text: "$1028$ Hz" },{ key: "D", text: "$514$ Hz" },{ key: "E", text: "$4$ Hz" }],
    answer: "E", solution: "Beat frequency $=|f_1-f_2|=4$ Hz." },
  { id: "bpho-mk3-s1-13", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 4,
    question: "In a double-slit experiment, light of wavelength $600$ nm passes through slits $0.30$ mm apart, and fringes form on a screen $2.0$ m away. Find the fringe spacing.",
    options: [{ key: "A", text: "$4.0$ mm" },{ key: "B", text: "$1.0$ mm" },{ key: "C", text: "$2.0$ mm" },{ key: "D", text: "$0.4$ mm" },{ key: "E", text: "$9.0$ mm" }],
    answer: "A", solution: "$w=\\dfrac{\\lambda D}{d}=\\dfrac{600\\times10^{-9}\\times2.0}{0.30\\times10^{-3}}=4.0\\times10^{-3}$ m." },
];

export const BPHO_MK3_S2: MCQQuestion[] = [
  { id: "bpho-mk3-s2-01", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 3, marks: 4,
    question: "A mass hangs from two identical springs. Let $T_s$ be the oscillation period when the springs are joined in series, and $T_p$ when they are in parallel. Find $T_s/T_p$.",
    options: [{ key: "A", text: "$\\sqrt{2}$" },{ key: "B", text: "$4$" },{ key: "C", text: "$\\dfrac{1}{2}$" },{ key: "D", text: "$1$" },{ key: "E", text: "$2$" }],
    answer: "E", solution: "Series stiffness $k/2$, parallel $2k$. $T\\propto1/\\sqrt{k}$: ratio $=\\sqrt{\\dfrac{2k}{k/2}}=\\sqrt4=2$." },
  { id: "bpho-mk3-s2-02", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 3, marks: 4,
    question: "A siren emitting $640$ Hz approaches a stationary observer at $20\\ \\mathrm{m\\,s^{-1}}$. The speed of sound is $340\\ \\mathrm{m\\,s^{-1}}$. Find the frequency heard.",
    options: [{ key: "A", text: "$680$ Hz" },{ key: "B", text: "$640$ Hz" },{ key: "C", text: "$604$ Hz" },{ key: "D", text: "$660$ Hz" },{ key: "E", text: "$720$ Hz" }],
    answer: "A", solution: "Approaching source: $f'=f\\dfrac{v}{v-v_s}=640\\times\\dfrac{340}{320}=680$ Hz." },
  { id: "bpho-mk3-s2-03", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 5,
    question: "A $500\\ \\mu\\mathrm{F}$ capacitor discharges through a $2.0\\ \\mathrm{k\\Omega}$ resistor. How long does it take for the charge to fall to half its initial value?",
    options: [{ key: "A", text: "$1.0$ s" },{ key: "B", text: "$2.0$ s" },{ key: "C", text: "$\\ln 2\\approx0.69$ s" },{ key: "D", text: "$0.35$ s" },{ key: "E", text: "$0.50$ s" }],
    answer: "C", solution: "$\\tau=RC=2000\\times500\\times10^{-6}=1.0$ s. $Q=Q_0e^{-t/\\tau}$: half at $t=\\tau\\ln2\\approx0.69$ s." },
  { id: "bpho-mk3-s2-04", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 4,
    question: "A battery of e.m.f. $\\varepsilon$ and internal resistance $r$ drives a variable load resistor $R$. For what value of $R$ is the power delivered to the load a maximum, and what is that power?",
    options: [{ key: "A", text: "$R=0$, $P=\\dfrac{\\varepsilon^2}{r}$" },{ key: "B", text: "$R=r$, $P=\\dfrac{\\varepsilon^2}{2r}$" },{ key: "C", text: "$R\\to\\infty$, $P\\to\\dfrac{\\varepsilon^2}{4r}$" },{ key: "D", text: "$R=r$, $P=\\dfrac{\\varepsilon^2}{4r}$" },{ key: "E", text: "$R=2r$, $P=\\dfrac{\\varepsilon^2}{8r}$" }],
    answer: "D", solution: "$P=\\dfrac{\\varepsilon^2R}{(R+r)^2}$; $\\dfrac{dP}{dR}=0$ gives $R=r$, then $P_{\\max}=\\dfrac{\\varepsilon^2}{4r}$ (half the energy is wasted in $r$ at this operating point)." },
  { id: "bpho-mk3-s2-05", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 4,
    question: "Two identical capacitors are connected across the same battery, first in parallel, then in series. Find the ratio of the total energy stored (parallel : series).",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$1$" },{ key: "C", text: "$\\dfrac{1}{2}$" },{ key: "D", text: "$4$" },{ key: "E", text: "$\\dfrac{1}{4}$" }],
    answer: "D", solution: "Same voltage $V$: $E=\\tfrac12C_{\\text{tot}}V^2$. Parallel $C_{\\text{tot}}=2C$; series $C/2$. Ratio $=\\dfrac{2C}{C/2}=4$." },
  { id: "bpho-mk3-s2-06", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 4,
    question: "A uniform wire of resistance $R$ is stretched (volume unchanged) to twice its original length. Its new resistance is",
    options: [{ key: "A", text: "$2R$" },{ key: "B", text: "$8R$" },{ key: "C", text: "$R$" },{ key: "D", text: "$R/2$" },{ key: "E", text: "$4R$" }],
    answer: "E", solution: "$R=\\rho\\ell/A$; doubling $\\ell$ at fixed volume halves $A$, so $R\\to\\rho(2\\ell)/(A/2)=4R$." },
  { id: "bpho-mk3-s2-07", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 4,
    question: "An electron is accelerated from rest through a potential difference of $1000$ V. Find its final speed. ($e=1.6\\times10^{-19}$ C, $m_e=9.1\\times10^{-31}$ kg)",
    options: [{ key: "A", text: "$\\approx1.9\\times10^{7}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$\\approx1.2\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$\\approx5.9\\times10^{6}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$\\approx3.5\\times10^{14}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$\\approx1.9\\times10^{5}\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "A", solution: "$eV=\\tfrac12m_ev^2$: $v=\\sqrt{\\dfrac{2eV}{m_e}}=\\sqrt{\\dfrac{2\\times1.6\\times10^{-19}\\times1000}{9.1\\times10^{-31}}}\\approx1.9\\times10^7\\ \\mathrm{m\\,s^{-1}}$ (about $6\\%$ of $c$ — relativity just beginning to matter)." },
  { id: "bpho-mk3-s2-08", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 3, marks: 4,
    question: "At the same temperature, find the ratio of the r.m.s. speed of hydrogen molecules ($M=2$) to that of oxygen molecules ($M=32$).",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$8$" },{ key: "C", text: "$16$" },{ key: "D", text: "$4$" },{ key: "E", text: "$\\sqrt{2}$" }],
    answer: "D", solution: "$v_{\\mathrm{rms}}=\\sqrt{3RT/M}\\propto M^{-1/2}$: ratio $=\\sqrt{32/2}=4$." },
  { id: "bpho-mk3-s2-09", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 3, marks: 3,
    question: "For one mole of an ideal gas, the difference between the molar heat capacity at constant pressure and at constant volume, $C_p-C_V$, equals",
    options: [{ key: "A", text: "$2R$" },{ key: "B", text: "$0$" },{ key: "C", text: "$\\dfrac{3R}{2}$" },{ key: "D", text: "$\\dfrac{R}{2}$" },{ key: "E", text: "$R$" }],
    answer: "E", solution: "At constant pressure the gas also does work $p\\Delta V=R\\Delta T$ per mole, so $C_p=C_V+R$ (Mayer's relation)." },
  { id: "bpho-mk3-s2-10", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 3, marks: 4,
    question: "An air bubble is released at the bottom of a lake $30$ m deep, where the temperature equals that at the surface. Atmospheric pressure is $1.0\\times10^{5}$ Pa and $\\rho g\\approx10^{4}\\ \\mathrm{Pa\\,m^{-1}}$. By what factor does the bubble's volume grow on reaching the surface?",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$\\sqrt{30}$" },{ key: "C", text: "$30$" },{ key: "D", text: "$1.3$" },{ key: "E", text: "$4$" }],
    answer: "E", solution: "Bottom pressure $=10^5+3\\times10^5=4\\times10^5$ Pa. Isothermal: $V\\propto1/p$, factor $=4$." },
];
