// BPhO Round 2 模拟卷1 —— 4 个「主题阶梯」模块，对标 R2 引导式长题（3小时/4题/全做）。链式 MCQ 化以支持自动判分；全部原创并程序验算。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const BPHO_R2M1_T1: MCQQuestion[] = [
  { id: "bpho-r2m1-t1-01", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：太空电梯】设想一条从赤道垂直伸向太空的缆绳，随地球一起以角速度 $\\omega$ 转动。地球质量 $M=5.97\\times10^{24}$ kg，半径 $R=6.37\\times10^{6}$ m，$G=6.67\\times10^{-11}$，一天取 $86400$ s。 第1步：缆绳上存在一个「平衡点」，该处物体随缆绳转动所需的向心力恰好由引力提供（即同步轨道）。求该点到地心的距离。",
    options: [{ key: "A", text: "$\\approx3.6\\times10^{7}$ m" },{ key: "B", text: "$\\left(\\dfrac{GM}{\\omega^2}\\right)^{1/3}\\approx4.2\\times10^{7}$ m" },{ key: "C", text: "$\\left(\\dfrac{GM}{\\omega}\\right)^{1/2}\\approx6.4\\times10^{6}$ m" },{ key: "D", text: "$\\left(\\dfrac{GM}{\\omega^2}\\right)^{1/2}$" },{ key: "E", text: "$\\approx4.2\\times10^{8}$ m" }],
    answer: "B", solution: "同步条件：$\\dfrac{GM}{r^2}=\\omega^2 r\\Rightarrow r=\\left(\\dfrac{GM}{\\omega^2}\\right)^{1/3}$。代入 $\\omega=2\\pi/86400$ 得 $r\\approx4.2\\times10^7$ m。" },
  { id: "bpho-r2m1-t1-02", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：太空电梯】设想一条从赤道垂直伸向太空的缆绳，随地球一起以角速度 $\\omega$ 转动。地球质量 $M=5.97\\times10^{24}$ kg，半径 $R=6.37\\times10^{6}$ m，$G=6.67\\times10^{-11}$，一天取 $86400$ s。 第2步：考虑缆绳上位于同步点**以下**的一小段。对它而言，引力与所需向心力相比",
    options: [{ key: "A", text: "引力更大，该段被向下拉，需要上方缆绳提供向上的张力" },{ key: "B", text: "引力更小，该段被甩向外" },{ key: "C", text: "该段不受力" },{ key: "D", text: "方向取决于缆绳材料" },{ key: "E", text: "二者恰好相等，处处失重" }],
    answer: "A", solution: "同步点以下 $r$ 小：引力 $\\propto1/r^2$ 大而所需向心力 $\\propto r$ 小，引力过剩 → 向下净拉力，需上方张力平衡。同步点以上则相反（被甩向外）。整条缆绳像被两头「拉紧」。" },
  { id: "bpho-r2m1-t1-03", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：太空电梯】设想一条从赤道垂直伸向太空的缆绳，随地球一起以角速度 $\\omega$ 转动。地球质量 $M=5.97\\times10^{24}$ kg，半径 $R=6.37\\times10^{6}$ m，$G=6.67\\times10^{-11}$，一天取 $86400$ s。 第3步：电梯舱沿缆绳缓慢爬到同步点。求它在同步点随缆绳转动的线速度。",
    options: [{ key: "A", text: "$\\approx7.9\\times10^{3}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$\\approx1.1\\times10^{4}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$\\approx465\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$\\omega r\\approx3.1\\times10^{3}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$0$" }],
    answer: "D", solution: "$v=\\omega r=\\dfrac{2\\pi}{86400}\\times4.2\\times10^7\\approx3.1\\times10^3\\ \\mathrm{m\\,s^{-1}}$——恰为该高度的圆轨道速度，所以在同步点松手就自然入轨。" },
  { id: "bpho-r2m1-t1-04", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：太空电梯】设想一条从赤道垂直伸向太空的缆绳，随地球一起以角速度 $\\omega$ 转动。地球质量 $M=5.97\\times10^{24}$ kg，半径 $R=6.37\\times10^{6}$ m，$G=6.67\\times10^{-11}$，一天取 $86400$ s。 第4步：电梯舱爬升时线速度从赤道的 $\\omega R$ 增大到 $\\omega r$。这份额外的角动量/动能来自哪里？",
    options: [{ key: "A", text: "不需要来源，角动量不守恒" },{ key: "B", text: "来自地磁场" },{ key: "C", text: "来自地球自转——缆绳通过侧向(科里奥利方向)的力对舱做功，同时使地球自转极其微小地变慢" },{ key: "D", text: "来自舱自带的电池，与地球无关" },{ key: "E", text: "来自太阳辐射压" }],
    answer: "C", solution: "在转动系中舱受科里奥利力向后压缆绳，缆绳给舱一个向前(东向)的反作用力做正功；其反作用最终作用于地球，使地球自转角动量微减。总角动量守恒。" },
  { id: "bpho-r2m1-t1-05", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：太空电梯】设想一条从赤道垂直伸向太空的缆绳，随地球一起以角速度 $\\omega$ 转动。地球质量 $M=5.97\\times10^{24}$ kg，半径 $R=6.37\\times10^{6}$ m，$G=6.67\\times10^{-11}$，一天取 $86400$ s。 第5步（估算）：粗略以「密度 $\\rho\\sim8\\times10^{3}\\ \\mathrm{kg\\,m^{-3}}$ 的钢缆、有效自重跨度 $\\sim10^{7}$ m、平均有效重力 $\\sim5\\ \\mathrm{m\\,s^{-2}}$」估算缆绳底部所需承受的应力量级。",
    options: [{ key: "A", text: "$\\sim10^{6}\\ \\mathrm{Pa}$" },{ key: "B", text: "$\\sim10^{11}\\ \\mathrm{Pa}$（远超钢的抗拉强度 $\\sim10^{9}$ Pa）" },{ key: "C", text: "$\\sim10^{4}\\ \\mathrm{Pa}$" },{ key: "D", text: "$\\sim10^{14}\\ \\mathrm{Pa}$" },{ key: "E", text: "$\\sim10^{8}\\ \\mathrm{Pa}$（钢勉强可行）" }],
    answer: "B", solution: "$\\sigma\\sim\\rho\\,g_{\\text{eff}}\\,L\\sim8\\times10^3\\times5\\times10^7=4\\times10^{11}$ Pa，量级 $10^{11}$。钢强度 $\\sim10^9$ Pa 差两个数量级——这就是为什么太空电梯需要碳纳米管级别的比强度。" },
  { id: "bpho-r2m1-t1-06", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：太空电梯】设想一条从赤道垂直伸向太空的缆绳，随地球一起以角速度 $\\omega$ 转动。地球质量 $M=5.97\\times10^{24}$ kg，半径 $R=6.37\\times10^{6}$ m，$G=6.67\\times10^{-11}$，一天取 $86400$ s。 第6步：把 $1$ kg 载荷从地表提升到同步点，仅计引力势能变化，所需能量约为",
    options: [{ key: "A", text: "$GM\\left(\\dfrac{1}{R}-\\dfrac{1}{r}\\right)\\approx5.3\\times10^{7}$ J" },{ key: "B", text: "$\\approx5.3\\times10^{5}$ J" },{ key: "C", text: "$\\approx9.5\\times10^{6}$ J" },{ key: "D", text: "$\\approx6.3\\times10^{7}$ J（即 $GM/R$）" },{ key: "E", text: "$mgh\\approx4.2\\times10^{8}$ J" }],
    answer: "A", solution: "$\\Delta U=GM\\left(\\dfrac1R-\\dfrac1r\\right)\\approx5.3\\times10^7$ J。注意 $mgh$ 在这么大的高度差上严重高估（$g$ 随高度衰减）。" },
];

export const BPHO_R2M1_T2: MCQQuestion[] = [
  { id: "bpho-r2m1-t2-01", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：白炽灯丝的物理】一只 $60$ W 白炽灯，钨丝工作时近似为黑体。$\\sigma=5.67\\times10^{-8}$，维恩常数 $2.9\\times10^{-3}\\ \\mathrm{m\\,K}$。 第1步：设灯丝工作温度 $T=2900$ K，且 $60$ W 全部以热辐射方式发出。求灯丝的表面积。",
    options: [{ key: "A", text: "$\\approx6.0\\times10^{-5}\\ \\mathrm{m^2}$" },{ key: "B", text: "$A=\\dfrac{P}{\\sigma T^4}\\approx1.5\\times10^{-5}\\ \\mathrm{m^2}$" },{ key: "C", text: "$\\approx3.6\\times10^{-6}\\ \\mathrm{m^2}$" },{ key: "D", text: "$\\approx1.5\\times10^{-3}\\ \\mathrm{m^2}$" },{ key: "E", text: "$\\approx1.5\\times10^{-7}\\ \\mathrm{m^2}$" }],
    answer: "B", solution: "$A=\\dfrac{P}{\\sigma T^4}=\\dfrac{60}{5.67\\times10^{-8}\\times(2900)^4}\\approx1.5\\times10^{-5}\\ \\mathrm{m^2}$——约 15 平方毫米，卷成细螺旋。" },
  { id: "bpho-r2m1-t2-02", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：白炽灯丝的物理】一只 $60$ W 白炽灯，钨丝工作时近似为黑体。$\\sigma=5.67\\times10^{-8}$，维恩常数 $2.9\\times10^{-3}\\ \\mathrm{m\\,K}$。 第2步：求灯丝辐射谱的峰值波长，并判断它落在哪个波段。",
    options: [{ key: "A", text: "$\\approx100$ nm，紫外" },{ key: "B", text: "$\\approx2.9$ mm，微波" },{ key: "C", text: "$\\approx1.0\\ \\mu\\mathrm{m}$，红外——大部分能量不是可见光" },{ key: "D", text: "$\\approx10\\ \\mu\\mathrm{m}$，远红外" },{ key: "E", text: "$\\approx500$ nm，可见光正中" }],
    answer: "C", solution: "$\\lambda_{\\max}=\\dfrac{2.9\\times10^{-3}}{2900}=1.0\\times10^{-6}$ m，在近红外。这就是白炽灯效率低（可见光占比 $\\sim5\\%$）的根本原因。" },
  { id: "bpho-r2m1-t2-03", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：白炽灯丝的物理】一只 $60$ W 白炽灯，钨丝工作时近似为黑体。$\\sigma=5.67\\times10^{-8}$，维恩常数 $2.9\\times10^{-3}\\ \\mathrm{m\\,K}$。 第3步：钨的电阻率随温度升高而增大（近似 $\\rho\\propto T$）。由此推断：灯在**刚通电的瞬间**（丝还是室温），流过的电流与稳定工作时相比",
    options: [{ key: "A", text: "大约是工作电流的 10 倍量级——这就是灯泡常在开灯瞬间烧毁的原因" },{ key: "B", text: "约为 2 倍" },{ key: "C", text: "与工作电流相同" },{ key: "D", text: "为零，需要预热才导通" },{ key: "E", text: "约为工作电流的 1/10" }],
    answer: "A", solution: "冷丝（$\\sim300$ K）电阻约为热丝（$\\sim2900$ K）的 $1/10$，$I=V/R$ 故瞬间电流约 $10$ 倍：巨大的浪涌电流 + 局部热应力 → 开灯瞬间最易烧断。" },
  { id: "bpho-r2m1-t2-04", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：白炽灯丝的物理】一只 $60$ W 白炽灯，钨丝工作时近似为黑体。$\\sigma=5.67\\times10^{-8}$，维恩常数 $2.9\\times10^{-3}\\ \\mathrm{m\\,K}$。 第4步：该灯接 $230$ V 电源。求其**工作状态**下的电阻。",
    options: [{ key: "A", text: "$R=\\dfrac{V^2}{P}\\approx880\\ \\Omega$" },{ key: "B", text: "$\\approx260\\ \\Omega$" },{ key: "C", text: "$\\approx3.8\\ \\Omega$" },{ key: "D", text: "$\\approx88\\ \\Omega$" },{ key: "E", text: "$\\approx8800\\ \\Omega$" }],
    answer: "A", solution: "$R=\\dfrac{V^2}{P}=\\dfrac{230^2}{60}\\approx880\\ \\Omega$（热态）；由第3步，冷态约 $88\\ \\Omega$。" },
  { id: "bpho-r2m1-t2-05", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：白炽灯丝的物理】一只 $60$ W 白炽灯，钨丝工作时近似为黑体。$\\sigma=5.67\\times10^{-8}$，维恩常数 $2.9\\times10^{-3}\\ \\mathrm{m\\,K}$。 第5步：灯丝会缓慢蒸发变细。设某处偶然略细一点，那里会发生什么？",
    options: [{ key: "A", text: "更细处电流更小，自动降温自我修复" },{ key: "B", text: "更细处更亮但寿命不变" },{ key: "C", text: "细处会吸附钨蒸气而变粗" },{ key: "D", text: "没有影响，温度处处相同" },{ key: "E", text: "更细处电阻更大 → 同一电流下发热更多 → 更热 → 蒸发更快 → 恶性循环直至烧断（失稳）" }],
    answer: "E", solution: "串联同流：$P=I^2R$，细处 $R\\uparrow$（截面小）发热集中、温度更高、蒸发更快、更细——正反馈失稳。灯丝几乎总是在最细的「热点」烧断。" },
  { id: "bpho-r2m1-t2-06", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：白炽灯丝的物理】一只 $60$ W 白炽灯，钨丝工作时近似为黑体。$\\sigma=5.67\\times10^{-8}$，维恩常数 $2.9\\times10^{-3}\\ \\mathrm{m\\,K}$。 第6步（估算）：结合第2步，白炽灯把电能转化为**可见光**的效率量级约为",
    options: [{ key: "A", text: "$\\sim0.05\\%$" },{ key: "B", text: "$\\sim25\\%$" },{ key: "C", text: "$\\sim50\\%$" },{ key: "D", text: "$\\sim5\\%$" },{ key: "E", text: "$\\sim90\\%$" }],
    answer: "D", solution: "谱峰在 $1\\ \\mu$m 红外，可见窗口只切到谱的一小块：白炽灯光效典型 $\\sim5\\%$（其余成热/红外）。这也是它被 LED（$>30\\%$）淘汰的原因。" },
];

export const BPHO_R2M1_T3: MCQQuestion[] = [
  { id: "bpho-r2m1-t3-01", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：从平行板到闪电】$\\varepsilon_0=8.85\\times10^{-12}\\ \\mathrm{F\\,m^{-1}}$。 第1步：一对面积 $1.0\\ \\mathrm{m^2}$、间距 $1.0$ mm 的平行板（真空）。求其电容。",
    options: [{ key: "A", text: "$\\approx1.0\\ \\mathrm{nF}$" },{ key: "B", text: "$C=\\dfrac{\\varepsilon_0 A}{d}\\approx8.9\\ \\mathrm{nF}$" },{ key: "C", text: "$\\approx8.9\\ \\mu\\mathrm{F}$" },{ key: "D", text: "$\\approx8.9\\ \\mathrm{pF}$" },{ key: "E", text: "$\\approx89\\ \\mathrm{nF}$" }],
    answer: "B", solution: "$C=\\dfrac{\\varepsilon_0A}{d}=\\dfrac{8.85\\times10^{-12}\\times1.0}{10^{-3}}=8.85\\times10^{-9}$ F $\\approx8.9$ nF。" },
  { id: "bpho-r2m1-t3-02", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：从平行板到闪电】$\\varepsilon_0=8.85\\times10^{-12}\\ \\mathrm{F\\,m^{-1}}$。 第2步：空气的击穿场强约 $E=3\\times10^{6}\\ \\mathrm{V\\,m^{-1}}$。求此场强下电场的能量密度 $u=\\tfrac12\\varepsilon_0E^2$。",
    options: [{ key: "A", text: "$\\approx4\\times10^{5}\\ \\mathrm{J\\,m^{-3}}$" },{ key: "B", text: "$\\approx4000\\ \\mathrm{J\\,m^{-3}}$" },{ key: "C", text: "$\\approx13\\ \\mathrm{J\\,m^{-3}}$" },{ key: "D", text: "$\\approx0.4\\ \\mathrm{J\\,m^{-3}}$" },{ key: "E", text: "$\\approx40\\ \\mathrm{J\\,m^{-3}}$" }],
    answer: "E", solution: "$u=\\tfrac12\\times8.85\\times10^{-12}\\times9\\times10^{12}\\approx40\\ \\mathrm{J\\,m^{-3}}$。" },
  { id: "bpho-r2m1-t3-03", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：从平行板到闪电】$\\varepsilon_0=8.85\\times10^{-12}\\ \\mathrm{F\\,m^{-1}}$。 第3步：把充了电、**断开电源**的平行板拉开到原间距的两倍。板上电荷不变。储能变为原来的几倍？多出的能量从哪来？",
    options: [{ key: "A", text: "2 倍；来自拉开两板时抵抗吸引力所做的机械功" },{ key: "B", text: "4 倍；来自电源" },{ key: "C", text: "1/2 倍；能量释放为热" },{ key: "D", text: "不变；能量守恒禁止改变" },{ key: "E", text: "2 倍；凭空产生" }],
    answer: "A", solution: "断电后 $Q$ 不变：$E=\\dfrac{Q^2}{2C}$，$C\\propto1/d$ 减半 → 储能加倍。异号板互相吸引，把它们拉开要做正功，恰好存进电场。" },
  { id: "bpho-r2m1-t3-04", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：从平行板到闪电】$\\varepsilon_0=8.85\\times10^{-12}\\ \\mathrm{F\\,m^{-1}}$。 第4步：由「拉开 $\\delta x$ 做功 $=$ 储能增量」证明两板吸引力为 $F=\\dfrac{Q^2}{2\\varepsilon_0 A}$。当 $Q=1.0\\ \\mu$C、$A=1.0\\ \\mathrm{m^2}$ 时 $F$ 为",
    options: [{ key: "A", text: "$\\approx0.056$ N" },{ key: "B", text: "$\\approx0.028$ N" },{ key: "C", text: "$\\approx5.6\\times10^{-4}$ N" },{ key: "D", text: "$\\approx0.11$ N" },{ key: "E", text: "$\\approx56$ N" }],
    answer: "A", solution: "$F=\\dfrac{dE}{dx}=\\dfrac{Q^2}{2\\varepsilon_0A}=\\dfrac{10^{-12}}{2\\times8.85\\times10^{-12}}\\approx0.056$ N。（注意不是 $QE$——每板只感受**对方**的场，即总场的一半。）" },
  { id: "bpho-r2m1-t3-05", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：从平行板到闪电】$\\varepsilon_0=8.85\\times10^{-12}\\ \\mathrm{F\\,m^{-1}}$。 第5步（建模）：把雷雨云—大地粗略当作平行板：面积 $\\sim20\\ \\mathrm{km^2}$、高度 $\\sim1.5$ km。其「电容」量级为",
    options: [{ key: "A", text: "$\\sim0.1\\ \\mu\\mathrm{F}$" },{ key: "B", text: "$\\sim10\\ \\mathrm{nF}$" },{ key: "C", text: "$\\sim100\\ \\mu\\mathrm{F}$" },{ key: "D", text: "$\\sim1$ F" },{ key: "E", text: "$\\sim1$ pF" }],
    answer: "A", solution: "$C\\sim\\dfrac{\\varepsilon_0A}{d}=\\dfrac{8.85\\times10^{-12}\\times2\\times10^7}{1.5\\times10^3}\\approx1.2\\times10^{-7}$ F $\\sim0.1\\ \\mu$F。" },
  { id: "bpho-r2m1-t3-06", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：从平行板到闪电】$\\varepsilon_0=8.85\\times10^{-12}\\ \\mathrm{F\\,m^{-1}}$。 第6步（估算）：若云地电压达 $\\sim10^{8}$ V，用第5步的电容估算一次闪电释放的能量量级。",
    options: [{ key: "A", text: "$\\sim10^{8}$–$10^{9}$ J（几百千克 TNT 当量）" },{ key: "B", text: "$\\sim10^{5}$ J" },{ key: "C", text: "$\\sim1$ J" },{ key: "D", text: "$\\sim10^{15}$ J" },{ key: "E", text: "$\\sim10^{3}$ J" }],
    answer: "A", solution: "$E=\\tfrac12CV^2\\sim\\tfrac12\\times10^{-7}\\times10^{16}=5\\times10^{8}$ J。与实测闪电（$10^8$–$10^9$ J）一致——但一次只够普通家庭用电几天，「收集闪电发电」并不划算。" },
];

export const BPHO_R2M1_T4: MCQQuestion[] = [
  { id: "bpho-r2m1-t4-01", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：原子核的尺度】核半径经验式 $r=r_0A^{1/3}$，$r_0=1.2\\times10^{-15}$ m；核子质量 $\\approx1.67\\times10^{-27}$ kg。 第1步：证明核物质密度与 $A$ 无关，并求其数值。",
    options: [{ key: "A", text: "$\\approx2.3\\times10^{14}\\ \\mathrm{kg\\,m^{-3}}$" },{ key: "B", text: "$\\approx2.3\\times10^{20}\\ \\mathrm{kg\\,m^{-3}}$" },{ key: "C", text: "随 $A$ 增大而增大" },{ key: "D", text: "$\\approx10^{3}\\ \\mathrm{kg\\,m^{-3}}$" },{ key: "E", text: "$\\rho=\\dfrac{3m_u}{4\\pi r_0^3}\\approx2.3\\times10^{17}\\ \\mathrm{kg\\,m^{-3}}$" }],
    answer: "E", solution: "$\\rho=\\dfrac{Am_u}{\\frac43\\pi r_0^3A}=\\dfrac{3m_u}{4\\pi r_0^3}$——$A$ 消掉，密度约 $2.3\\times10^{17}\\ \\mathrm{kg\\,m^{-3}}$：核像不可压缩的「液滴」。" },
  { id: "bpho-r2m1-t4-02", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：原子核的尺度】核半径经验式 $r=r_0A^{1/3}$，$r_0=1.2\\times10^{-15}$ m；核子质量 $\\approx1.67\\times10^{-27}$ kg。 第2步：一茶匙（$\\sim5\\ \\mathrm{cm^3}$）核物质的质量量级为",
    options: [{ key: "A", text: "$\\sim10^{3}$ kg" },{ key: "B", text: "$\\sim10^{12}$ kg（约十亿吨）" },{ key: "C", text: "$\\sim10^{18}$ kg" },{ key: "D", text: "$\\sim10^{9}$ kg" },{ key: "E", text: "$\\sim10^{6}$ kg" }],
    answer: "B", solution: "$m=\\rho V\\sim2.3\\times10^{17}\\times5\\times10^{-6}\\approx10^{12}$ kg。中子星就是这种密度的宏观天体。" },
  { id: "bpho-r2m1-t4-03", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：原子核的尺度】核半径经验式 $r=r_0A^{1/3}$，$r_0=1.2\\times10^{-15}$ m；核子质量 $\\approx1.67\\times10^{-27}$ kg。 第3步：求铀-238 核的半径。",
    options: [{ key: "A", text: "$\\approx2.4\\times10^{-14}$ m" },{ key: "B", text: "$\\approx1.2\\times10^{-15}$ m" },{ key: "C", text: "$\\approx7.4\\times10^{-14}$ m" },{ key: "D", text: "$\\approx7.4\\times10^{-15}$ m" },{ key: "E", text: "$\\approx2.9\\times10^{-13}$ m" }],
    answer: "D", solution: "$r=1.2\\times10^{-15}\\times238^{1/3}=1.2\\times10^{-15}\\times6.2\\approx7.4\\times10^{-15}$ m。" },
  { id: "bpho-r2m1-t4-04", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：原子核的尺度】核半径经验式 $r=r_0A^{1/3}$，$r_0=1.2\\times10^{-15}$ m；核子质量 $\\approx1.67\\times10^{-27}$ kg。 第4步：「结合能/核子」曲线在 $A\\approx56$（铁）附近最高。由此判断哪些反应放能：",
    options: [{ key: "A", text: "只有聚变放能" },{ key: "B", text: "只有裂变放能" },{ key: "C", text: "轻核聚变（向铁靠拢）与重核裂变（向铁靠拢）都放能" },{ key: "D", text: "所有核反应都放能" },{ key: "E", text: "铁的裂变放能最多" }],
    answer: "C", solution: "向「每核子束缚得更紧」的方向演化就放能：$A<56$ 聚变上坡放能；$A>56$ 裂变下坡放能；铁本身是「核燃料的灰烬」。" },
  { id: "bpho-r2m1-t4-05", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：原子核的尺度】核半径经验式 $r=r_0A^{1/3}$，$r_0=1.2\\times10^{-15}$ m；核子质量 $\\approx1.67\\times10^{-27}$ kg。 第5步（估算）：每次裂变放能约 $200$ MeV。$1$ g 铀-238 若全部裂变，放出的能量量级为",
    options: [{ key: "A", text: "$\\sim10^{3}$ J" },{ key: "B", text: "$\\sim10^{7}$ J" },{ key: "C", text: "$\\sim10^{16}$ J" },{ key: "D", text: "$\\sim10^{10}$–$10^{11}$ J（约等于 20 吨 TNT）" },{ key: "E", text: "$\\sim10^{5}$ J" }],
    answer: "D", solution: "$N=\\dfrac{1}{238}\\times6\\times10^{23}\\approx2.5\\times10^{21}$ 个核；$E=N\\times200\\times1.6\\times10^{-13}\\approx8\\times10^{10}$ J。这就是核能量密度：化学燃料的百万倍。" },
  { id: "bpho-r2m1-t4-06", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：原子核的尺度】核半径经验式 $r=r_0A^{1/3}$，$r_0=1.2\\times10^{-15}$ m；核子质量 $\\approx1.67\\times10^{-27}$ kg。 第6步：卢瑟福用 α 粒子散射发现核。若原子半径 $\\sim10^{-10}$ m、核半径 $\\sim10^{-14}$ m，则原子被核「占据」的体积比例量级为",
    options: [{ key: "A", text: "$\\sim10^{-8}$" },{ key: "B", text: "$\\sim10^{-16}$" },{ key: "C", text: "$\\sim10^{-12}$" },{ key: "D", text: "$\\sim10^{-4}$" },{ key: "E", text: "$\\sim10^{-2}$" }],
    answer: "C", solution: "体积比 $=(r_{\\text{核}}/r_{\\text{原子}})^3=(10^{-4})^3=10^{-12}$：原子几乎是空的，这就是绝大多数 α 粒子直穿金箔的原因。" },
];
