// BPhO Round 2 模拟卷3 —— 4 个「主题阶梯」模块（对标 R2：3小时/4题/全做），链式 MCQ + 程序验算，全部原创。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const BPHO_R2M3_T1: MCQQuestion[] = [
  { id: "bpho-r2m3-t1-01", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：引力弹弓】探测器飞掠行星借力加速。先从一个力学类比开始：弹性球撞击迎面开来的重墙。 第1步：球以 $5\\ \\mathrm{m\\,s^{-1}}$ 迎面撞上以 $10\\ \\mathrm{m\\,s^{-1}}$ 驶来的巨重弹性墙。反弹后球的速率（地面系）是",
    options: [{ key: "A", text: "$10\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$15\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$25\\ \\mathrm{m\\,s^{-1}}$（$v+2U$）" },{ key: "D", text: "$5\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$20\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "C", solution: "到墙参考系：球以 $5+10=15$ 接近，弹性反弹以 $15$ 离开；回地面系 $15+10=25$。重物弹性碰撞给轻物 $v+2U$。" },
  { id: "bpho-r2m3-t1-02", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：引力弹弓】探测器飞掠行星借力加速。先从一个力学类比开始：弹性球撞击迎面开来的重墙。 第2步：把「墙」换成运动中的行星、「弹性碰撞」换成引力飞掠。探测器进入并离开行星引力范围时，**相对行星**的速率",
    options: [{ key: "A", text: "变为零" },{ key: "B", text: "增大，因为被引力加速" },{ key: "C", text: "取决于飞掠方向" },{ key: "D", text: "减小，因为要爬出势阱" },{ key: "E", text: "不变——引力是保守力，进出「势阱」能量不亏不赚（相对行星是弹性的）" }],
    answer: "E", solution: "在行星参考系中轨道是双曲线：进入速率=离开速率，只有方向改变——这正是「弹性」的含义。增速全部来自换回太阳系参考系时行星速度的叠加。" },
  { id: "bpho-r2m3-t1-03", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：引力弹弓】探测器飞掠行星借力加速。先从一个力学类比开始：弹性球撞击迎面开来的重墙。 第3步：木星轨道速度约 $13\\ \\mathrm{km\\,s^{-1}}$。由第1步的类比，一次理想的正对飞掠最多能让探测器（太阳系参考系）增速约",
    options: [{ key: "A", text: "$52\\ \\mathrm{km\\,s^{-1}}$" },{ key: "B", text: "$2U\\approx26\\ \\mathrm{km\\,s^{-1}}$" },{ key: "C", text: "不可能增速" },{ key: "D", text: "$6.5\\ \\mathrm{km\\,s^{-1}}$" },{ key: "E", text: "$13\\ \\mathrm{km\\,s^{-1}}$" }],
    answer: "B", solution: "完全「反弹」的极限即 $v\\to v+2U$：增量 $2U\\approx26\\ \\mathrm{km\\,s^{-1}}$。实际几何达不到完全反向，Voyager 单次借力约 $+10\\ \\mathrm{km\\,s^{-1}}$ 量级。" },
  { id: "bpho-r2m3-t1-04", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：引力弹弓】探测器飞掠行星借力加速。先从一个力学类比开始：弹性球撞击迎面开来的重墙。 第4步：探测器增加的动能来自哪里？",
    options: [{ key: "A", text: "来自行星的轨道动能——行星因此极其微小地变慢、轨道极其微小地降低" },{ key: "B", text: "来自行星自转而非公转" },{ key: "C", text: "凭空产生，引力不守恒" },{ key: "D", text: "来自太阳辐射" },{ key: "E", text: "来自探测器燃料" }],
    answer: "A", solution: "总动量与总能量守恒：探测器得到的动量/能量由行星支付。因质量比悬殊（$\\sim10^{-24}$），行星减速完全不可测——但账是平的。" },
  { id: "bpho-r2m3-t1-05", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：引力弹弓】探测器飞掠行星借力加速。先从一个力学类比开始：弹性球撞击迎面开来的重墙。 第5步：若探测器从行星**前方**绕过（顺着行星运动方向离开势阱的反向几何），它会",
    options: [{ key: "A", text: "速率不变只改方向" },{ key: "B", text: "坠入行星" },{ key: "C", text: "获得双倍加速" },{ key: "D", text: "同样加速" },{ key: "E", text: "减速——同一机制反用，这正是探测器进入水星/太阳轨道时的「刹车」手段" }],
    answer: "E", solution: "几何反过来就是「迎面墙」变「后退墙」：$v\\to v-2U$。信使号(MESSENGER)去水星就靠多次这种减速飞掠——往太阳系内圈走反而更「难」。" },
  { id: "bpho-r2m3-t1-06", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：引力弹弓】探测器飞掠行星借力加速。先从一个力学类比开始：弹性球撞击迎面开来的重墙。 第6步（估算）：旅行者2号借木星、土星等多次弹弓后以 $\\sim17\\ \\mathrm{km\\,s^{-1}}$ 逃离太阳系。若纯靠化学火箭从地球轨道直接达到这个日心速度，所需 $\\Delta v$ 与借力方案相比",
    options: [{ key: "A", text: "一样多" },{ key: "B", text: "只多 $1\\ \\mathrm{km\\,s^{-1}}$" },{ key: "C", text: "多出数十 $\\mathrm{km\\,s^{-1}}$ 量级——以火箭方程折算是完全不可行的燃料比" },{ key: "D", text: "无法比较" },{ key: "E", text: "更少" }],
    answer: "C", solution: "地球轨道处太阳逃逸需 $\\sim42\\ \\mathrm{km\\,s^{-1}}$ 日心速度，地球公转只送 $30$：差的十几 $\\mathrm{km\\,s^{-1}}$ 若全靠燃料，按 $\\Delta v=u\\ln(M_0/M_f)$ 质量比呈指数爆炸。弹弓是「免费的 $\\Delta v$」。" },
];

export const BPHO_R2M3_T2: MCQQuestion[] = [
  { id: "bpho-r2m3-t2-01", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：一杯咖啡的冷却】$0.30$ kg 咖啡（按水算，$c=4200\\ \\mathrm{J\\,kg^{-1}K^{-1}}$），室温 $20\\,^\\circ$C。 第1步：咖啡从 $80\\,^\\circ$C 降到 $70\\,^\\circ$C 用了 $5.0$ 分钟。这段时间的平均散热功率约为",
    options: [{ key: "A", text: "$\\approx42$ W" },{ key: "B", text: "$\\approx420$ W" },{ key: "C", text: "$\\approx130$ W" },{ key: "D", text: "$\\approx4.2$ W" },{ key: "E", text: "$\\approx13$ W" }],
    answer: "A", solution: "$P=\\dfrac{mc\\Delta T}{t}=\\dfrac{0.3\\times4200\\times10}{300}=42$ W。" },
  { id: "bpho-r2m3-t2-02", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：一杯咖啡的冷却】$0.30$ kg 咖啡（按水算，$c=4200\\ \\mathrm{J\\,kg^{-1}K^{-1}}$），室温 $20\\,^\\circ$C。 第2步：牛顿冷却定律 $P=hA(T-T_{\\text{室}})$。用第1步（区间中点温差 $\\approx55$ K）估算 $hA$。",
    options: [{ key: "A", text: "$\\approx0.76\\ \\mathrm{W\\,K^{-1}}$" },{ key: "B", text: "$\\approx2.1\\ \\mathrm{W\\,K^{-1}}$" },{ key: "C", text: "$\\approx42\\ \\mathrm{W\\,K^{-1}}$" },{ key: "D", text: "$\\approx0.076\\ \\mathrm{W\\,K^{-1}}$" },{ key: "E", text: "$\\approx7.6\\ \\mathrm{W\\,K^{-1}}$" }],
    answer: "A", solution: "$hA=\\dfrac{P}{\\Delta T}=\\dfrac{42}{55}\\approx0.76\\ \\mathrm{W\\,K^{-1}}$。" },
  { id: "bpho-r2m3-t2-03", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：一杯咖啡的冷却】$0.30$ kg 咖啡（按水算，$c=4200\\ \\mathrm{J\\,kg^{-1}K^{-1}}$），室温 $20\\,^\\circ$C。 第3步：由牛顿冷却写出 $mc\\dfrac{dT}{dt}=-hA(T-T_{\\text{室}})$。温差随时间",
    options: [{ key: "A", text: "先慢后快" },{ key: "B", text: "线性下降，约 $2$ K/分钟恒定" },{ key: "C", text: "按指数衰减，时间常数 $\\tau=\\dfrac{mc}{hA}\\approx28$ 分钟" },{ key: "D", text: "按平方反比下降" },{ key: "E", text: "保持不变" }],
    answer: "C", solution: "一阶线性方程 → $\\Delta T=\\Delta T_0e^{-t/\\tau}$，$\\tau=\\dfrac{0.3\\times4200}{0.76}\\approx1.7\\times10^3$ s $\\approx28$ 分钟：每过一个 $\\tau$，温差缩到 $37\\%$。" },
  { id: "bpho-r2m3-t2-04", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：一杯咖啡的冷却】$0.30$ kg 咖啡（按水算，$c=4200\\ \\mathrm{J\\,kg^{-1}K^{-1}}$），室温 $20\\,^\\circ$C。 第4步：「先加奶再放着」与「先放着最后加奶」哪种 10 分钟后更热？（奶是凉的，奶量相同）",
    options: [{ key: "A", text: "无法判断" },{ key: "B", text: "取决于杯子颜色" },{ key: "C", text: "后加奶更热" },{ key: "D", text: "先加奶更热——尽早降低温差，全程散热更慢" },{ key: "E", text: "完全一样" }],
    answer: "D", solution: "散热率 $\\propto$ 温差：先加奶把前 10 分钟的温差整体压低 → 累计散热更少。经典的牛顿冷却应用题。" },
  { id: "bpho-r2m3-t2-05", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：一杯咖啡的冷却】$0.30$ kg 咖啡（按水算，$c=4200\\ \\mathrm{J\\,kg^{-1}K^{-1}}$），室温 $20\\,^\\circ$C。 第5步：咖啡表面还有蒸发散热。$1$ g 水蒸发带走约 $2.3\\times10^{3}$ J。若表面每分钟蒸发 $0.5$ g，蒸发功率约为",
    options: [{ key: "A", text: "$\\approx1.9$ W" },{ key: "B", text: "$\\approx1900$ W" },{ key: "C", text: "$\\approx19$ W——与对流/传导同一量级，不可忽略" },{ key: "D", text: "$\\approx190$ W，占绝对主导" },{ key: "E", text: "$\\approx0.19$ W，可忽略" }],
    answer: "C", solution: "$P=\\dfrac{0.5\\times10^{-3}\\times2.3\\times10^6}{60}\\approx19$ W。这就是「吹一吹、加个盖」显著影响冷却速度的原因——盖子主要挡的是蒸发。" },
  { id: "bpho-r2m3-t2-06", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：一杯咖啡的冷却】$0.30$ kg 咖啡（按水算，$c=4200\\ \\mathrm{J\\,kg^{-1}K^{-1}}$），室温 $20\\,^\\circ$C。 第6步：把牛顿冷却的指数规律外推：咖啡最终会",
    options: [{ key: "A", text: "渐近趋于室温，但严格说永远「差一点」——实际被环境涨落淹没" },{ key: "B", text: "线性降到室温后停止" },{ key: "C", text: "降到室温后继续降到 $0\\,^\\circ$C" },{ key: "D", text: "在室温上方 $5$ K 停住" },{ key: "E", text: "周期性回暖" }],
    answer: "A", solution: "指数衰减无限逼近渐近线。物理上当温差小到与环境波动同量级时，「冷却」失去意义——所有指数弛豫过程共同的结局。" },
];

export const BPHO_R2M3_T3: MCQQuestion[] = [
  { id: "bpho-r2m3-t3-01", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：为什么要高压输电】一座电站输出 $P=1.0$ GW，输电线路总电阻 $R=10\\ \\Omega$。 第1步：若以 $400$ kV 输电，线路电流为",
    options: [{ key: "A", text: "$2500$ A" },{ key: "B", text: "$25000$ A" },{ key: "C", text: "$250$ A" },{ key: "D", text: "$4000$ A" },{ key: "E", text: "$400$ A" }],
    answer: "A", solution: "$I=\\dfrac{P}{V}=\\dfrac{10^9}{4\\times10^5}=2500$ A。" },
  { id: "bpho-r2m3-t3-02", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：为什么要高压输电】一座电站输出 $P=1.0$ GW，输电线路总电阻 $R=10\\ \\Omega$。 第2步：这条线路上损耗的功率为",
    options: [{ key: "A", text: "$6.25$ MW" },{ key: "B", text: "$1$ GW" },{ key: "C", text: "$I^2R=62.5$ MW（约 $6\\%$）" },{ key: "D", text: "$625$ MW" },{ key: "E", text: "$0.625$ MW" }],
    answer: "C", solution: "$P_{\\text{损}}=I^2R=2500^2\\times10=6.25\\times10^7$ W。注意用 $I^2R$ 而非 $V^2/R$——$V$ 是全线电压不是线路压降。" },
  { id: "bpho-r2m3-t3-03", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：为什么要高压输电】一座电站输出 $P=1.0$ GW，输电线路总电阻 $R=10\\ \\Omega$。 第3步：若改用 $40$ kV（降十倍）输同样的 $1$ GW，线路损耗变为",
    options: [{ key: "A", text: "$1/10$" },{ key: "B", text: "$1/100$" },{ key: "C", text: "$10$ 倍" },{ key: "D", text: "$100$ 倍，达 $6.25$ GW——比输送功率还大，物理上荒谬（说明低压根本送不出去）" },{ key: "E", text: "不变" }],
    answer: "D", solution: "$I$ 增十倍 → $I^2R$ 增百倍 $=6.25$ GW $>1$ GW：电流大到线路先烧毁。损耗 $\\propto1/V^2$——这就是高压输电的全部理由。" },
  { id: "bpho-r2m3-t3-04", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：为什么要高压输电】一座电站输出 $P=1.0$ GW，输电线路总电阻 $R=10\\ \\Omega$。 第4步：交流输电体系能存在的关键器件是变压器。它能高效变压的物理基础是",
    options: [{ key: "A", text: "电磁感应——交变磁通在副绕组感应电动势，匝数比即电压比" },{ key: "B", text: "静电感应" },{ key: "C", text: "欧姆定律" },{ key: "D", text: "压电效应" },{ key: "E", text: "半导体 PN 结" }],
    answer: "A", solution: "交流 → 铁芯中交变磁通 → $\\varepsilon=-N\\,d\\Phi/dt$ 按匝数分配。直流没有 $d\\Phi/dt$，所以早期「电流战争」中直流输不远——直到现代电力电子出现 HVDC。" },
  { id: "bpho-r2m3-t3-05", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：为什么要高压输电】一座电站输出 $P=1.0$ GW，输电线路总电阻 $R=10\\ \\Omega$。 第5步：超高压直流(HVDC)在超长距离上反而优于交流，一个物理原因是",
    options: [{ key: "A", text: "直流电子跑得更快" },{ key: "B", text: "直流不产生任何热损耗" },{ key: "C", text: "直流电压可以无限高" },{ key: "D", text: "交流线路存在电容/电感的无功损耗与趋肤效应，直流没有这些额外负担" },{ key: "E", text: "交流会被地磁场偏转" }],
    answer: "D", solution: "长交流线是巨大的分布电容/电感，来回「搬运」无功电流白白发热；趋肤效应还浪费导线截面。直流满截面、无无功——跨千公里与海底电缆的首选。" },
  { id: "bpho-r2m3-t3-06", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：为什么要高压输电】一座电站输出 $P=1.0$ GW，输电线路总电阻 $R=10\\ \\Omega$。 第6步（估算）：全国电网若平均按 $6\\%$ 线损输送 $\\sim10^{12}$ kWh/年，损耗的电能量级为",
    options: [{ key: "A", text: "$\\sim10^{14}$ kWh/年" },{ key: "B", text: "$\\sim10^{10}$–$10^{11}$ kWh/年——相当于几十座大型电站白烧" },{ key: "C", text: "$\\sim10^{8}$ kWh/年" },{ key: "D", text: "$\\sim10^{6}$ kWh/年" },{ key: "E", text: "可以忽略" }],
    answer: "B", solution: "$6\\%\\times10^{12}=6\\times10^{10}$ kWh。每降低 $0.1\\%$ 线损都值得巨额投资——特高压工程的经济学根源。" },
];

export const BPHO_R2M3_T4: MCQQuestion[] = [
  { id: "bpho-r2m3-t4-01", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：太阳还能烧多久】太阳光度 $L=3.8\\times10^{26}$ W，质量 $M=2.0\\times10^{30}$ kg，$c=3\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$。 第1步：由 $E=mc^2$，太阳每秒失去的质量为",
    options: [{ key: "A", text: "$\\approx1.3\\times10^{18}$ kg" },{ key: "B", text: "$\\dfrac{L}{c^2}\\approx4.2\\times10^{9}$ kg（四百万吨/秒）" },{ key: "C", text: "$\\approx4.2\\times10^{12}$ kg" },{ key: "D", text: "$\\approx4.2\\times10^{6}$ kg" },{ key: "E", text: "$\\approx4.2\\times10^{3}$ kg" }],
    answer: "B", solution: "$\\dot m=\\dfrac{L}{c^2}=\\dfrac{3.8\\times10^{26}}{9\\times10^{16}}\\approx4.2\\times10^9\\ \\mathrm{kg\\,s^{-1}}$。听着吓人，但相对太阳总质量微不足道。" },
  { id: "bpho-r2m3-t4-02", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：太阳还能烧多久】太阳光度 $L=3.8\\times10^{26}$ W，质量 $M=2.0\\times10^{30}$ kg，$c=3\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$。 第2步：氢聚变成氦只把约 $0.7\\%$ 的质量转化为能量。太阳每秒实际「烧掉」的氢约为",
    options: [{ key: "A", text: "$\\approx6\\times10^{11}$ kg" },{ key: "B", text: "$\\approx6\\times10^{9}$ kg" },{ key: "C", text: "$\\approx3\\times10^{8}$ kg" },{ key: "D", text: "$\\approx6\\times10^{13}$ kg" },{ key: "E", text: "$\\approx4.2\\times10^{9}$ kg" }],
    answer: "A", solution: "烧氢率 $=\\dfrac{L}{0.007c^2}=\\dfrac{4.2\\times10^9}{0.007}\\approx6\\times10^{11}\\ \\mathrm{kg\\,s^{-1}}$。" },
  { id: "bpho-r2m3-t4-03", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：太阳还能烧多久】太阳光度 $L=3.8\\times10^{26}$ W，质量 $M=2.0\\times10^{30}$ kg，$c=3\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$。 第3步：只有核心约 $10\\%$ 的氢能参与聚变。由此估算太阳主序寿命的量级。",
    options: [{ key: "A", text: "$\\sim10^{6}$ 年" },{ key: "B", text: "$t\\sim\\dfrac{0.1M}{\\dot m_{\\text{H}}}\\approx10^{10}$ 年" },{ key: "C", text: "$\\sim10^{8}$ 年" },{ key: "D", text: "$\\sim10^{12}$ 年" },{ key: "E", text: "$\\sim10^{14}$ 年" }],
    answer: "B", solution: "$t=\\dfrac{0.1\\times2\\times10^{30}}{6\\times10^{11}}\\approx3\\times10^{17}$ s $\\approx10^{10}$ 年。太阳已 46 亿岁——正值中年。" },
  { id: "bpho-r2m3-t4-04", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：太阳还能烧多久】太阳光度 $L=3.8\\times10^{26}$ W，质量 $M=2.0\\times10^{30}$ kg，$c=3\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$。 第4步：若太阳的能源是**化学燃烧**（每 kg 释放 $\\sim3\\times10^{7}$ J，如煤），同样的光度只能维持",
    options: [{ key: "A", text: "$\\sim10^{4}$–$10^{5}$ 年——远短于地质记录，19 世纪由此断定化学能源不可能" },{ key: "B", text: "$\\sim100$ 年" },{ key: "C", text: "$\\sim10^{10}$ 年，与聚变相当" },{ key: "D", text: "$\\sim10^{7}$ 年" },{ key: "E", text: "$\\sim10^{8}$ 年" }],
    answer: "A", solution: "$t=\\dfrac{Mq}{L}=\\dfrac{2\\times10^{30}\\times3\\times10^7}{3.8\\times10^{26}}\\approx1.6\\times10^{11}$ s $\\approx5000$ 年量级。地球岩石几十亿年历史直接排除化学燃烧——这正是当年指向「未知核能源」的经典估算。" },
  { id: "bpho-r2m3-t4-05", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：太阳还能烧多久】太阳光度 $L=3.8\\times10^{26}$ W，质量 $M=2.0\\times10^{30}$ kg，$c=3\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$。 第5步：聚变要求两个质子克服库仑排斥彼此接近。核心温度 $1.5\\times10^{7}$ K 对应的典型热动能 $\\tfrac32k_BT$ 约为",
    options: [{ key: "A", text: "$\\sim3\\times10^{-19}$ J" },{ key: "B", text: "$\\sim1$ J" },{ key: "C", text: "$\\sim1$ MeV，刚好越过势垒" },{ key: "D", text: "$\\sim3\\times10^{-13}$ J" },{ key: "E", text: "$\\sim3\\times10^{-16}$ J $\\approx2$ keV——远小于库仑势垒(~MeV)，经典物理下根本点不着" }],
    answer: "E", solution: "$\\tfrac32\\times1.38\\times10^{-23}\\times1.5\\times10^7\\approx3\\times10^{-16}$ J。差三个数量级还能烧，靠的是**量子隧穿** + 麦克斯韦分布高能尾——太阳是量子力学点燃的。" },
  { id: "bpho-r2m3-t4-06", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：太阳还能烧多久】太阳光度 $L=3.8\\times10^{26}$ W，质量 $M=2.0\\times10^{30}$ kg，$c=3\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$。 第6步：正因隧穿概率极低，单个质子在核心「等待聚变」的平均时间量级达",
    options: [{ key: "A", text: "$\\sim1$ 秒" },{ key: "B", text: "$\\sim10^{-9}$ 秒" },{ key: "C", text: "$\\sim10^{9}$ 年——反应极慢恰恰是太阳能稳定燃烧百亿年的原因" },{ key: "D", text: "$\\sim10^{3}$ 年" },{ key: "E", text: "$\\sim1$ 年" }],
    answer: "C", solution: "核心单位体积功率其实只有 $\\sim$ 几百 W/m³（比堆肥还低），全靠体积庞大。若反应快，太阳早就炸了——「烧得慢」是恒星长寿与生命演化的前提。" },
];
