// BPhO 模拟卷6 —— 模块1对标 Section 1 短题；模块2以高难选择题近似 Section 2 强度（真实 S2 为长题，见练习区 9 道原创长题）。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const BPHO_MK6_S1: MCQQuestion[] = [
  { id: "bpho-mk6-s1-01", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 2, marks: 4,
    question: "Estimate the order of magnitude of the number of times a human heart beats in an $80$-year lifetime.",
    options: [{ key: "A", text: "$10^{13}$" },{ key: "B", text: "$10^{11}$" },{ key: "C", text: "$10^{9}$" },{ key: "D", text: "$10^{6}$" },{ key: "E", text: "$10^{7}$" }],
    answer: "C", solution: "About $70$ beats/min $\\times60\\times24\\times365\\times80\\approx3\\times10^9$: order $10^9$. (BPhO loves quick order-of-magnitude estimates — practise them.)" },
  { id: "bpho-mk6-s1-02", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 2, marks: 4,
    question: "Estimate the number of water molecules in a $250$ g glass of water. ($M_{\\mathrm{H_2O}}=18\\ \\mathrm{g\\,mol^{-1}}$, $N_A=6.0\\times10^{23}$)",
    options: [{ key: "A", text: "$\\approx6\\times10^{23}$" },{ key: "B", text: "$\\approx8\\times10^{27}$" },{ key: "C", text: "$\\approx1.5\\times10^{22}$" },{ key: "D", text: "$\\approx8\\times10^{24}$" },{ key: "E", text: "$\\approx8\\times10^{21}$" }],
    answer: "D", solution: "$N=\\dfrac{250}{18}\\times6.0\\times10^{23}\\approx8\\times10^{24}$ molecules." },
  { id: "bpho-mk6-s1-03", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "A projectile is launched from ground level with fixed speed. Neglecting air resistance, its horizontal range is greatest at a launch angle of",
    options: [{ key: "A", text: "$60°$" },{ key: "B", text: "$45°$" },{ key: "C", text: "$0°$" },{ key: "D", text: "$30°$" },{ key: "E", text: "$90°$" }],
    answer: "B", solution: "$R=\\dfrac{v^2\\sin 2\\theta}{g}$ is maximised when $\\sin2\\theta=1$, i.e. $\\theta=45°$." },
  { id: "bpho-mk6-s1-04", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A conical pendulum: a bob of mass $m$ on a string makes angle $\\theta$ with the vertical. Find the tension in the string.",
    options: [{ key: "A", text: "$mg$" },{ key: "B", text: "$mg\\tan\\theta$" },{ key: "C", text: "$\\dfrac{mg}{\\cos\\theta}$" },{ key: "D", text: "$mg\\cos\\theta$" },{ key: "E", text: "$mg\\sin\\theta$" }],
    answer: "C", solution: "Vertical balance: $T\\cos\\theta=mg\\Rightarrow T=\\dfrac{mg}{\\cos\\theta}$." },
  { id: "bpho-mk6-s1-05", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "A $2.0$ kg mass on a vertical spring of stiffness $200\\ \\mathrm{N\\,m^{-1}}$ oscillates. Find the period.",
    options: [{ key: "A", text: "$\\dfrac{2\\pi}{5}\\approx1.3$ s" },{ key: "B", text: "$0.1$ s" },{ key: "C", text: "$\\dfrac{\\pi}{10}\\approx0.31$ s" },{ key: "D", text: "$\\pi\\approx3.1$ s" },{ key: "E", text: "$\\dfrac{\\pi}{5}\\approx0.63$ s" }],
    answer: "E", solution: "$T=2\\pi\\sqrt{m/k}=2\\pi\\sqrt{2/200}=2\\pi/10=\\pi/5\\approx0.63$ s. Gravity only shifts the equilibrium, not the period." },
  { id: "bpho-mk6-s1-06", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "Three identical blocks (each mass $m$) connected by light strings are pulled along a frictionless surface by a force $F$ applied to the front block. Find the tension in the string between the middle and rear blocks.",
    options: [{ key: "A", text: "$\\dfrac{F}{2}$" },{ key: "B", text: "$F$" },{ key: "C", text: "$\\dfrac{2F}{3}$" },{ key: "D", text: "$\\dfrac{3F}{2}$" },{ key: "E", text: "$\\dfrac{F}{3}$" }],
    answer: "E", solution: "Whole system: $a=F/3m$. The rear string pulls only the rear block: $T=ma=F/3$." },
  { id: "bpho-mk6-s1-07", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A $0.50$ kg ball on a string of length $2.0$ m is whirled in a vertical circle. At the lowest point its speed is $6.0\\ \\mathrm{m\\,s^{-1}}$ ($g=10$). Find the string tension there.",
    options: [{ key: "A", text: "$23$ N" },{ key: "B", text: "$9$ N" },{ key: "C", text: "$5$ N" },{ key: "D", text: "$14$ N" },{ key: "E", text: "$18$ N" }],
    answer: "D", solution: "At the bottom: $T-mg=\\dfrac{mv^2}{r}$, $T=0.5\\cdot10+\\dfrac{0.5\\cdot36}{2}=5+9=14$ N." },
  { id: "bpho-mk6-s1-08", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "An object of mass $2.0$ kg falls under gravity with a linear drag force $F=bv$ where $b=4.0\\ \\mathrm{kg\\,s^{-1}}$ ($g=10$). Find its terminal velocity.",
    options: [{ key: "A", text: "$10\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$8.0\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$2.5\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$20\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$5.0\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "E", solution: "Terminal: $mg=bv_T$, $v_T=mg/b=20/4=5.0\\ \\mathrm{m\\,s^{-1}}$." },
  { id: "bpho-mk6-s1-09", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 3,
    question: "A stationary wave forms on a string fixed at both ends, vibrating in its third harmonic. How many nodes are there in total (including the two ends)?",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$6$" },{ key: "C", text: "$3$" },{ key: "D", text: "$4$" },{ key: "E", text: "$2$" }],
    answer: "D", solution: "The $n$th harmonic has $n$ antinodes and $n+1$ nodes. Third harmonic: $4$ nodes." },
  { id: "bpho-mk6-s1-10", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 4,
    question: "A sound has intensity level $30$ dB above another. Find the ratio of the two intensities.",
    options: [{ key: "A", text: "$300$" },{ key: "B", text: "$1000$" },{ key: "C", text: "$100$" },{ key: "D", text: "$3$" },{ key: "E", text: "$30$" }],
    answer: "B", solution: "$\\Delta L=10\\log_{10}(I_2/I_1)=30\\Rightarrow I_2/I_1=10^3=1000$." },
  { id: "bpho-mk6-s1-11", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 3,
    question: "Unpolarised light of intensity $I_0$ passes through two ideal polarisers whose transmission axes are at $60°$ to each other. Find the transmitted intensity.",
    options: [{ key: "A", text: "$\\dfrac{I_0}{4}$" },{ key: "B", text: "$\\dfrac{3I_0}{8}$" },{ key: "C", text: "$\\dfrac{I_0}{2}$" },{ key: "D", text: "$\\dfrac{I_0}{8}$" },{ key: "E", text: "$\\dfrac{I_0}{16}$" }],
    answer: "D", solution: "First polariser: $I_0/2$. Malus: $\\times\\cos^2 60°=\\times\\tfrac14$. Total $=\\dfrac{I_0}{2}\\cdot\\dfrac14=\\dfrac{I_0}{8}$." },
  { id: "bpho-mk6-s1-12", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 4,
    question: "A wave has speed $340\\ \\mathrm{m\\,s^{-1}}$ and frequency $170$ Hz. Two points oscillate exactly out of phase (antiphase). Find the smallest possible separation between them.",
    options: [{ key: "A", text: "$0.5$ m" },{ key: "B", text: "$4.0$ m" },{ key: "C", text: "$0.25$ m" },{ key: "D", text: "$1.0$ m" },{ key: "E", text: "$2.0$ m" }],
    answer: "D", solution: "$\\lambda=v/f=340/170=2.0$ m. Antiphase means separation $=\\lambda/2=1.0$ m (smallest)." },
  { id: "bpho-mk6-s1-13", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 4,
    question: "A magnetic flux through a coil of $1$ turn changes uniformly from $0.30$ Wb to $0.10$ Wb in $0.10$ s. Find the magnitude of the induced e.m.f.",
    options: [{ key: "A", text: "$2.0$ V" },{ key: "B", text: "$0.02$ V" },{ key: "C", text: "$20$ V" },{ key: "D", text: "$0.2$ V" },{ key: "E", text: "$4.0$ V" }],
    answer: "A", solution: "$\\varepsilon=-N\\dfrac{d\\Phi}{dt}=\\dfrac{0.20}{0.10}=2.0$ V." },
];

export const BPHO_MK6_S2: MCQQuestion[] = [
  { id: "bpho-mk6-s2-01", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 3, marks: 4,
    question: "Two SHMs of the same frequency and amplitude $A$, with a phase difference of $\\dfrac{\\pi}{2}$, act on a particle along the same line. Find the amplitude of the resulting oscillation.",
    options: [{ key: "A", text: "$A$" },{ key: "B", text: "$\\sqrt{2}\\,A$" },{ key: "C", text: "$0$" },{ key: "D", text: "$\\dfrac{A}{\\sqrt2}$" },{ key: "E", text: "$2A$" }],
    answer: "B", solution: "Phasor addition of two equal amplitudes at $90°$: resultant $=\\sqrt{A^2+A^2}=\\sqrt2\\,A$." },
  { id: "bpho-mk6-s2-02", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 3, marks: 4,
    question: "A diffraction grating has $500$ lines per mm. Light of wavelength $500$ nm is incident normally. Find the angle of the first-order maximum.",
    options: [{ key: "A", text: "$\\approx7.2°$" },{ key: "B", text: "$\\approx45°$" },{ key: "C", text: "$\\approx30°$" },{ key: "D", text: "$\\approx0.5°$" },{ key: "E", text: "$\\approx14.5°$" }],
    answer: "E", solution: "Slit spacing $d=\\dfrac{1}{500}\\ \\mathrm{mm}=2.0\\times10^{-6}$ m. $d\\sin\\theta=m\\lambda$: $\\sin\\theta=\\dfrac{500\\times10^{-9}}{2\\times10^{-6}}=0.25$, $\\theta\\approx14.5°$." },
  { id: "bpho-mk6-s2-03", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 3, marks: 4,
    question: "An observer moves at $20\\ \\mathrm{m\\,s^{-1}}$ towards a stationary source emitting $680$ Hz. The speed of sound is $340\\ \\mathrm{m\\,s^{-1}}$. Find the frequency heard.",
    options: [{ key: "A", text: "$700$ Hz" },{ key: "B", text: "$720$ Hz" },{ key: "C", text: "$640$ Hz" },{ key: "D", text: "$760$ Hz" },{ key: "E", text: "$680$ Hz" }],
    answer: "B", solution: "Moving observer approaching: $f'=f\\dfrac{v+v_o}{v}=680\\times\\dfrac{360}{340}=720$ Hz." },
  { id: "bpho-mk6-s2-04", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 3, marks: 4,
    question: "Light of wavelength $\\lambda$ in air enters a thin soap film of refractive index $n$. For the film to appear bright by reflection at normal incidence, the minimum non-zero film thickness is",
    options: [{ key: "A", text: "$\\dfrac{\\lambda}{n}$" },{ key: "B", text: "$\\dfrac{\\lambda}{2}$" },{ key: "C", text: "$\\dfrac{\\lambda}{4n}$" },{ key: "D", text: "$\\dfrac{\\lambda}{2n}$" },{ key: "E", text: "$\\dfrac{n\\lambda}{4}$" }],
    answer: "C", solution: "One reflection (air→film) has a $\\pi$ phase change, the other (film→air) does not. Constructive reflection needs an extra half-wave in the film: $2nt=\\dfrac{\\lambda}{2}$, so $t=\\dfrac{\\lambda}{4n}$." },
  { id: "bpho-mk6-s2-05", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 3, marks: 4,
    question: "An organ pipe closed at one end has fundamental frequency $f_0$. An identical pipe open at both ends has fundamental frequency",
    options: [{ key: "A", text: "$\\dfrac{3f_0}{2}$" },{ key: "B", text: "$4f_0$" },{ key: "C", text: "$f_0$" },{ key: "D", text: "$\\dfrac{f_0}{2}$" },{ key: "E", text: "$2f_0$" }],
    answer: "E", solution: "Closed pipe: $f_0=\\dfrac{v}{4L}$. Open pipe: $f=\\dfrac{v}{2L}=2f_0$." },
  { id: "bpho-mk6-s2-06", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 3, marks: 4,
    question: "A mass on a spring has SHM amplitude $A$. At what displacement is the kinetic energy equal to the potential energy?",
    options: [{ key: "A", text: "$\\dfrac{A}{\\sqrt3}$" },{ key: "B", text: "$\\dfrac{A}{\\sqrt2}$" },{ key: "C", text: "$\\dfrac{A}{2}$" },{ key: "D", text: "$A$" },{ key: "E", text: "$\\dfrac{\\sqrt3 A}{2}$" }],
    answer: "B", solution: "$E_p=\\tfrac12E$ when $x^2=\\tfrac12A^2$, i.e. $x=\\dfrac{A}{\\sqrt2}$." },
  { id: "bpho-mk6-s2-07", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 4,
    question: "Three capacitors, each $C$, are connected with two in series and that combination in parallel with the third. Find the total capacitance.",
    options: [{ key: "A", text: "$\\dfrac{2C}{3}$" },{ key: "B", text: "$\\dfrac{C}{3}$" },{ key: "C", text: "$2C$" },{ key: "D", text: "$\\dfrac{3C}{2}$" },{ key: "E", text: "$3C$" }],
    answer: "D", solution: "Two in series: $C/2$. In parallel with $C$: $C/2+C=\\dfrac{3C}{2}$." },
  { id: "bpho-mk6-s2-08", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 5,
    question: "A capacitor $C$ charged to voltage $V$ is connected across an identical uncharged capacitor. Find the fraction of the original stored energy that remains after charge redistributes.",
    options: [{ key: "A", text: "$\\dfrac{1}{2}$" },{ key: "B", text: "$\\dfrac{3}{4}$" },{ key: "C", text: "$\\dfrac{1}{4}$" },{ key: "D", text: "$0$" },{ key: "E", text: "$1$" }],
    answer: "A", solution: "Charge conserved: final voltage $V/2$ on total capacitance $2C$. Initial energy $\\tfrac12CV^2$; final $\\tfrac12(2C)(V/2)^2=\\tfrac14CV^2$. Remaining fraction $=\\tfrac12$ (the rest is lost as heat/radiation, independent of resistance)." },
  { id: "bpho-mk6-s2-09", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 4,
    question: "A long straight wire carries $5.0$ A. Find the magnetic flux density at $0.10$ m from it. ($\\mu_0=4\\pi\\times10^{-7}$)",
    options: [{ key: "A", text: "$1.0\\times10^{-5}$ T" },{ key: "B", text: "$5.0\\times10^{-5}$ T" },{ key: "C", text: "$1.0\\times10^{-6}$ T" },{ key: "D", text: "$2.0\\times10^{-5}$ T" },{ key: "E", text: "$1.0\\times10^{-4}$ T" }],
    answer: "A", solution: "$B=\\dfrac{\\mu_0 I}{2\\pi r}=\\dfrac{4\\pi\\times10^{-7}\\times5}{2\\pi\\times0.1}=\\dfrac{2\\times10^{-7}\\times5}{0.1}=1.0\\times10^{-5}$ T." },
  { id: "bpho-mk6-s2-10", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 4,
    question: "Find the cyclotron frequency of an electron in a magnetic field of $0.50$ T. ($e=1.6\\times10^{-19}$ C, $m_e=9.1\\times10^{-31}$ kg)",
    options: [{ key: "A", text: "$\\approx8.8\\times10^{10}$ Hz" },{ key: "B", text: "$\\approx2.2\\times10^{9}$ Hz" },{ key: "C", text: "$\\approx1.4\\times10^{10}$ Hz" },{ key: "D", text: "$\\approx5.6\\times10^{11}$ Hz" },{ key: "E", text: "$\\approx1.4\\times10^{7}$ Hz" }],
    answer: "C", solution: "$f=\\dfrac{eB}{2\\pi m_e}=\\dfrac{1.6\\times10^{-19}\\times0.5}{2\\pi\\times9.1\\times10^{-31}}\\approx1.4\\times10^{10}$ Hz — independent of speed (until relativistic)." },
];
