// BPhO 模拟卷7 —— 模块1对标 Section 1 短题；模块2以高难选择题近似 Section 2 强度（真实 S2 为长题，见练习区 9 道原创长题）。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const BPHO_MK7_S1: MCQQuestion[] = [
  { id: "bpho-mk7-s1-01", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 4,
    question: "A potential divider of two equal $10\\ \\mathrm{k\\Omega}$ resistors is connected across $12$ V. A load of $10\\ \\mathrm{k\\Omega}$ is connected across the lower resistor. Find the output voltage across the load.",
    options: [{ key: "A", text: "$3.0$ V" },{ key: "B", text: "$8.0$ V" },{ key: "C", text: "$4.0$ V" },{ key: "D", text: "$6.0$ V" },{ key: "E", text: "$5.0$ V" }],
    answer: "C", solution: "Lower resistor $\\parallel$ load $=5\\ \\mathrm{k\\Omega}$. Divider: $V=12\\times\\dfrac{5}{10+5}=4.0$ V (loading pulls it below the unloaded $6$ V)." },
  { id: "bpho-mk7-s1-02", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 4,
    question: "Resistors of $2.0\\ \\Omega$ and $3.0\\ \\Omega$ are connected in parallel across a $6.0$ V ideal supply. Find the total power dissipated.",
    options: [{ key: "A", text: "$18$ W" },{ key: "B", text: "$12$ W" },{ key: "C", text: "$7.2$ W" },{ key: "D", text: "$30$ W" },{ key: "E", text: "$60$ W" }],
    answer: "D", solution: "$R_{\\parallel}=\\dfrac{2\\cdot3}{5}=1.2\\ \\Omega$. $P=\\dfrac{V^2}{R}=\\dfrac{36}{1.2}=30$ W. (Or sum $18+12$.)" },
  { id: "bpho-mk7-s1-03", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 2, marks: 4,
    question: "How much energy is needed to melt $0.10$ kg of ice at $0\\ ^\\circ$C? (Specific latent heat of fusion $=3.34\\times10^{5}\\ \\mathrm{J\\,kg^{-1}}$)",
    options: [{ key: "A", text: "$\\approx3.3\\times10^{3}$ J" },{ key: "B", text: "$\\approx3.3\\times10^{4}$ J" },{ key: "C", text: "$\\approx3.3\\times10^{5}$ J" },{ key: "D", text: "$\\approx3.34$ J" },{ key: "E", text: "$\\approx6.7\\times10^{4}$ J" }],
    answer: "B", solution: "$Q=mL=0.10\\times3.34\\times10^5=3.34\\times10^4$ J." },
  { id: "bpho-mk7-s1-04", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 2, marks: 4,
    question: "In a photoelectric experiment, photons of energy $3.0$ eV eject electrons from a metal of work function $2.0$ eV. Find the stopping voltage.",
    options: [{ key: "A", text: "$2.0$ V" },{ key: "B", text: "$0.5$ V" },{ key: "C", text: "$5.0$ V" },{ key: "D", text: "$3.0$ V" },{ key: "E", text: "$1.0$ V" }],
    answer: "E", solution: "$eV_s=hf-\\phi=(3.0-2.0)\\ \\mathrm{eV}=1.0$ eV, so $V_s=1.0$ V (stopping voltage in volts equals max KE in eV per electron)." },
  { id: "bpho-mk7-s1-05", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 2, marks: 4,
    question: "A radioactive nuclide has a half-life of $6.0$ hours. What fraction of a sample remains after $24$ hours?",
    options: [{ key: "A", text: "$\\dfrac{1}{4}$" },{ key: "B", text: "$\\dfrac{1}{16}$" },{ key: "C", text: "$\\dfrac18$" },{ key: "D", text: "$\\dfrac{1}{32}$" },{ key: "E", text: "$\\dfrac14$" }],
    answer: "B", solution: "$24/6=4$ half-lives: fraction $=(1/2)^4=1/16$." },
  { id: "bpho-mk7-s1-06", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 2, marks: 4,
    question: "Using $E(\\mathrm{eV})=\\dfrac{1240}{\\lambda(\\mathrm{nm})}$, find the energy of a photon of wavelength $500$ nm.",
    options: [{ key: "A", text: "$\\approx2.5$ eV" },{ key: "B", text: "$\\approx1.24$ eV" },{ key: "C", text: "$\\approx0.5$ eV" },{ key: "D", text: "$\\approx5.0$ eV" },{ key: "E", text: "$\\approx620$ eV" }],
    answer: "A", solution: "$E=\\dfrac{1240}{500}\\approx2.5$ eV — visible-light photons carry a few eV, comparable to chemical bond energies." },
  { id: "bpho-mk7-s1-07", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 1, marks: 3,
    question: "A block slides down a frictionless incline at $30°$ to the horizontal ($g=10$). Find its acceleration.",
    options: [{ key: "A", text: "$5.0\\ \\mathrm{m\\,s^{-2}}$" },{ key: "B", text: "$8.7\\ \\mathrm{m\\,s^{-2}}$" },{ key: "C", text: "$0$" },{ key: "D", text: "$2.5\\ \\mathrm{m\\,s^{-2}}$" },{ key: "E", text: "$10\\ \\mathrm{m\\,s^{-2}}$" }],
    answer: "A", solution: "$a=g\\sin\\theta=10\\times0.5=5.0\\ \\mathrm{m\\,s^{-2}}$." },
  { id: "bpho-mk7-s1-08", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A car travelling at $15\\ \\mathrm{m\\,s^{-1}}$ brakes with the tyres locked; the coefficient of friction is $0.60$ ($g=10$). Find the stopping distance.",
    options: [{ key: "A", text: "$18.75$ m" },{ key: "B", text: "$25$ m" },{ key: "C", text: "$9.4$ m" },{ key: "D", text: "$12.5$ m" },{ key: "E", text: "$37.5$ m" }],
    answer: "A", solution: "$d=\\dfrac{v^2}{2\\mu g}=\\dfrac{225}{2\\times0.6\\times10}=18.75$ m." },
  { id: "bpho-mk7-s1-09", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A person of mass $70$ kg climbs a staircase of total height $3.6$ m in $12$ s ($g=10$). Find their average power output against gravity.",
    options: [{ key: "A", text: "$420$ W" },{ key: "B", text: "$2520$ W" },{ key: "C", text: "$25$ W" },{ key: "D", text: "$210$ W" },{ key: "E", text: "$105$ W" }],
    answer: "D", solution: "$P=\\dfrac{mgh}{t}=\\dfrac{70\\times10\\times3.6}{12}=210$ W." },
  { id: "bpho-mk7-s1-10", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "A force on a $2$ kg body varies with time so that the force–time graph is a triangle: it rises linearly from $0$ to $6$ N over $4$ s then instantly drops to zero. Find the impulse delivered.",
    options: [{ key: "A", text: "$48\\ \\mathrm{N\\,s}$" },{ key: "B", text: "$24\\ \\mathrm{N\\,s}$" },{ key: "C", text: "$12\\ \\mathrm{N\\,s}$" },{ key: "D", text: "$6\\ \\mathrm{N\\,s}$" },{ key: "E", text: "$3\\ \\mathrm{N\\,s}$" }],
    answer: "C", solution: "Impulse = area under $F$–$t$ graph $=\\tfrac12\\times4\\times6=12\\ \\mathrm{N\\,s}$." },
  { id: "bpho-mk7-s1-11", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "Two equal masses collide and stick. Before impact one moves east at $6\\ \\mathrm{m\\,s^{-1}}$, the other north at $8\\ \\mathrm{m\\,s^{-1}}$. Find the speed of the combined mass just after the collision.",
    options: [{ key: "A", text: "$5\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$14\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$\\sqrt{2}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$7\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$10\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "A", solution: "Each component halves (equal masses stick): $v_x=3$, $v_y=4$, speed $=\\sqrt{3^2+4^2}=5\\ \\mathrm{m\\,s^{-1}}$." },
  { id: "bpho-mk7-s1-12", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A bucket of water is swung in a vertical circle of radius $2.5$ m ($g=10$). Find the minimum speed at the top so the water stays in.",
    options: [{ key: "A", text: "$7.1\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$25\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$10\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$2.5\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$5.0\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "E", solution: "At the top gravity supplies the centripetal force: $g=\\dfrac{v^2}{r}$, $v=\\sqrt{gr}=\\sqrt{25}=5.0\\ \\mathrm{m\\,s^{-1}}$." },
  { id: "bpho-mk7-s1-13", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A uniform ladder leans against a smooth (frictionless) wall and a rough floor. Which statement is correct about the forces at the two contacts?",
    options: [{ key: "A", text: "Both wall and floor exert only vertical forces." },{ key: "B", text: "Both exert horizontal forces only." },{ key: "C", text: "The floor exerts only a vertical force." },{ key: "D", text: "The wall exerts only a horizontal force; the floor exerts both vertical and horizontal forces." },{ key: "E", text: "The wall exerts a vertical force; the floor only horizontal." }],
    answer: "D", solution: "A smooth wall can only push perpendicular to itself (horizontal). The rough floor supplies the upward normal force and the horizontal friction that balances the wall's push." },
];

export const BPHO_MK7_S2: MCQQuestion[] = [
  { id: "bpho-mk7-s2-01", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 4,
    question: "A square conducting loop of side $L$ moves at constant speed $v$ fully into a uniform field $B$ (perpendicular to the loop). While entering, the induced e.m.f. is $BLv$. Once the loop is entirely inside the field, the induced e.m.f. is",
    options: [{ key: "A", text: "$\\dfrac{BLv}{2}$" },{ key: "B", text: "$BL^2v$" },{ key: "C", text: "$2BLv$" },{ key: "D", text: "$0$" },{ key: "E", text: "$BLv$" }],
    answer: "D", solution: "Once fully inside, the enclosed flux is constant ($BL^2$), so $\\dfrac{d\\Phi}{dt}=0$ and the e.m.f. is zero. Only the entering/leaving edges cutting field lines produce e.m.f." },
  { id: "bpho-mk7-s2-02", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 5,
    question: "A copper wire of cross-section $1.0\\ \\mathrm{mm^2}$ carries $5.0$ A. With $n=8.5\\times10^{28}\\ \\mathrm{m^{-3}}$ free electrons and $e=1.6\\times10^{-19}$ C, estimate the electron drift speed.",
    options: [{ key: "A", text: "$\\approx5.0\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$\\approx3.7\\times10^{-4}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$\\approx1.0\\times10^{-3}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$\\approx3.7\\times10^{-7}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$\\approx3.7\\times10^{-2}\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "B", solution: "$v_d=\\dfrac{I}{nAe}=\\dfrac{5.0}{8.5\\times10^{28}\\times10^{-6}\\times1.6\\times10^{-19}}\\approx3.7\\times10^{-4}\\ \\mathrm{m\\,s^{-1}}$ — remarkably slow, yet signals travel near light speed." },
  { id: "bpho-mk7-s2-03", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 4,
    question: "An electron enters a region of uniform electric field $E$ perpendicular to its velocity $v$, travelling a horizontal distance $L$ through the field. Its vertical deflection on leaving is proportional to",
    options: [{ key: "A", text: "$\\dfrac{EL^2}{v}$" },{ key: "B", text: "$\\dfrac{EL}{v}$" },{ key: "C", text: "$\\dfrac{E v^2}{L}$" },{ key: "D", text: "$\\dfrac{EL^2}{v^2}$" },{ key: "E", text: "$\\dfrac{E L}{v^2}$" }],
    answer: "D", solution: "Time in field $t=L/v$; vertical deflection $y=\\tfrac12 a t^2=\\tfrac12\\dfrac{eE}{m}\\dfrac{L^2}{v^2}\\propto\\dfrac{EL^2}{v^2}$ (parabolic path, like projectile motion)." },
  { id: "bpho-mk7-s2-04", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 3, marks: 4,
    question: "An ideal monatomic gas expands adiabatically. Its pressure and volume obey $pV^\\gamma=$ const with $\\gamma=\\dfrac53$. If the volume doubles, the pressure falls to what fraction of its original value?",
    options: [{ key: "A", text: "$2^{-2/3}\\approx0.63$" },{ key: "B", text: "$\\dfrac14$" },{ key: "C", text: "$\\dfrac12$" },{ key: "D", text: "$2^{-1}$" },{ key: "E", text: "$2^{-5/3}\\approx0.31$" }],
    answer: "E", solution: "$p\\propto V^{-\\gamma}$: doubling $V$ gives $p\\to p\\cdot2^{-5/3}\\approx0.31p$ — falls faster than isothermal ($2^{-1}$) because the gas also cools." },
  { id: "bpho-mk7-s2-05", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 3, marks: 4,
    question: "One mole of an ideal gas expands isothermally at $300$ K to twice its volume. Find the work done by the gas. ($R=8.31$, $\\ln2=0.693$)",
    options: [{ key: "A", text: "$\\approx2.5\\times10^{3}$ J" },{ key: "B", text: "$\\approx8.6\\times10^{2}$ J" },{ key: "C", text: "$\\approx1.2\\times10^{3}$ J" },{ key: "D", text: "$\\approx3.5\\times10^{3}$ J" },{ key: "E", text: "$\\approx1.7\\times10^{3}$ J" }],
    answer: "E", solution: "$W=nRT\\ln\\dfrac{V_2}{V_1}=1\\times8.31\\times300\\times\\ln2\\approx1.7\\times10^3$ J." },
  { id: "bpho-mk7-s2-06", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 3, marks: 4,
    question: "Estimate the r.m.s. speed of nitrogen molecules (mass $4.8\\times10^{-26}$ kg) at $300$ K. ($k_B=1.38\\times10^{-23}$)",
    options: [{ key: "A", text: "$\\approx340\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$\\approx50\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$\\approx510\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$\\approx1500\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$\\approx170\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "C", solution: "$v_{rms}=\\sqrt{\\dfrac{3k_BT}{m}}=\\sqrt{\\dfrac{3\\times1.38\\times10^{-23}\\times300}{4.8\\times10^{-26}}}\\approx510\\ \\mathrm{m\\,s^{-1}}$ (comparable to the speed of sound in air)." },
  { id: "bpho-mk7-s2-07", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 3, marks: 4,
    question: "Using Wien's law ($\\lambda_{\\max}T=2.9\\times10^{-3}\\ \\mathrm{m\\,K}$), estimate the peak-emission wavelength of the Sun's surface at $5800$ K.",
    options: [{ key: "A", text: "$\\approx500$ nm" },{ key: "B", text: "$\\approx5000$ nm" },{ key: "C", text: "$\\approx290$ nm" },{ key: "D", text: "$\\approx1000$ nm" },{ key: "E", text: "$\\approx50$ nm" }],
    answer: "A", solution: "$\\lambda_{\\max}=\\dfrac{2.9\\times10^{-3}}{5800}\\approx5.0\\times10^{-7}$ m $=500$ nm — green, the peak of human eye sensitivity." },
  { id: "bpho-mk7-s2-08", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 3, marks: 4,
    question: "The pressure of an ideal gas is $p=\\tfrac13\\rho\\langle c^2\\rangle$. If the absolute temperature is doubled at constant volume, the r.m.s. molecular speed changes by a factor of",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "unchanged" },{ key: "C", text: "$4$" },{ key: "D", text: "$\\dfrac{1}{\\sqrt2}$" },{ key: "E", text: "$\\sqrt{2}$" }],
    answer: "E", solution: "$\\langle c^2\\rangle\\propto T$ so $c_{rms}\\propto\\sqrt T$; doubling $T$ multiplies $c_{rms}$ by $\\sqrt2$." },
  { id: "bpho-mk7-s2-09", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 4,
    question: "The radius of the $n$th Bohr orbit in hydrogen scales as $r_n\\propto n^2$. Find the ratio of the radius of the $n=3$ orbit to the $n=1$ (ground) orbit.",
    options: [{ key: "A", text: "$\\dfrac13$" },{ key: "B", text: "$9$" },{ key: "C", text: "$3$" },{ key: "D", text: "$6$" },{ key: "E", text: "$27$" }],
    answer: "B", solution: "$r_n\\propto n^2$: ratio $=3^2=9$." },
  { id: "bpho-mk7-s2-10", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 4,
    question: "The mass defect when a deuteron forms from a proton and neutron is $0.0024$ u. Find the binding energy. ($1$ u $=931.5$ MeV$/c^2$)",
    options: [{ key: "A", text: "$\\approx0.0024$ MeV" },{ key: "B", text: "$\\approx931$ MeV" },{ key: "C", text: "$\\approx22$ MeV" },{ key: "D", text: "$\\approx2.2$ MeV" },{ key: "E", text: "$\\approx0.22$ MeV" }],
    answer: "D", solution: "$E=\\Delta m\\,c^2=0.0024\\times931.5\\approx2.2$ MeV." },
];
