// BPhO Round 2 模拟卷2 —— 4 个「主题阶梯」模块，对标 R2 引导式长题（3小时/4题/全做）。链式 MCQ 化以支持自动判分；全部原创并程序验算。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const BPHO_R2M2_T1: MCQQuestion[] = [
  { id: "bpho-r2m2-t1-01", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：单摆的极限】一只摆长 $L=1.0$ m 的单摆，$g=9.81\\ \\mathrm{m\\,s^{-2}}$。 第1步：小角近似下求周期。",
    options: [{ key: "A", text: "$\\approx1.0$ s" },{ key: "B", text: "$\\approx3.1$ s" },{ key: "C", text: "$2\\pi\\sqrt{L/g}\\approx2.0$ s" },{ key: "D", text: "$\\approx0.32$ s" },{ key: "E", text: "$\\approx6.3$ s" }],
    answer: "C", solution: "$T=2\\pi\\sqrt{1.0/9.81}\\approx2.0$ s——「秒摆」：半周期恰约 1 秒。" },
  { id: "bpho-r2m2-t1-02", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：单摆的极限】一只摆长 $L=1.0$ m 的单摆，$g=9.81\\ \\mathrm{m\\,s^{-2}}$。 第2步：小角近似的本质是 $\\sin\\theta\\approx\\theta$。当摆角增大到不可忽略时，真实周期与小角公式相比",
    options: [{ key: "A", text: "为零" },{ key: "B", text: "相同（周期与振幅无关是精确结论）" },{ key: "C", text: "可能更长也可能更短" },{ key: "D", text: "更长——回复力比线性近似弱（$\\sin\\theta<\\theta$），摆「回来得更慢」" },{ key: "E", text: "更短" }],
    answer: "D", solution: "$\\sin\\theta<\\theta$：大角度时回复力小于线性模型 → 加速度不足 → 周期变长。「等时性」只是小角极限。（一阶修正 $T\\approx T_0(1+\\theta_0^2/16)$。）" },
  { id: "bpho-r2m2-t1-03", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：单摆的极限】一只摆长 $L=1.0$ m 的单摆，$g=9.81\\ \\mathrm{m\\,s^{-2}}$。 第3步：从 $\\theta_0=60°$ 静止释放。用能量守恒求最低点速度。",
    options: [{ key: "A", text: "$\\approx2.2\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$\\sqrt{2gL(1-\\cos60°)}\\approx3.1\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$\\approx1.6\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$\\approx9.8\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$\\approx4.4\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "B", solution: "下降高度 $h=L(1-\\cos\\theta_0)=0.5$ m：$v=\\sqrt{2gh}=\\sqrt{9.81}\\approx3.1\\ \\mathrm{m\\,s^{-1}}$。" },
  { id: "bpho-r2m2-t1-04", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：单摆的极限】一只摆长 $L=1.0$ m 的单摆，$g=9.81\\ \\mathrm{m\\,s^{-2}}$。 第4步：仍从 $60°$ 释放。求最低点绳的张力（以 $mg$ 为单位）。",
    options: [{ key: "A", text: "$1.5mg$" },{ key: "B", text: "$mg$" },{ key: "C", text: "$\\dfrac{mg}{2}$" },{ key: "D", text: "$3mg$" },{ key: "E", text: "$(3-2\\cos\\theta_0)mg=2mg$" }],
    answer: "E", solution: "最低点：$T-mg=\\dfrac{mv^2}{L}=2mg(1-\\cos\\theta_0)$，故 $T=mg(3-2\\cos\\theta_0)=2mg$（$\\cos60°=\\tfrac12$）。从 $90°$ 放则 $3mg$。" },
  { id: "bpho-r2m2-t1-05", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：单摆的极限】一只摆长 $L=1.0$ m 的单摆，$g=9.81\\ \\mathrm{m\\,s^{-2}}$。 第5步（误差传播）：用这只摆测 $g$（$g=4\\pi^2L/T^2$）。若 $L$ 测准而 $T$ 偏大 $1\\%$，得到的 $g$ 偏差为",
    options: [{ key: "A", text: "不受影响" },{ key: "B", text: "偏大约 $2\\%$" },{ key: "C", text: "偏小约 $2\\%$" },{ key: "D", text: "偏小约 $1\\%$" },{ key: "E", text: "偏小约 $0.5\\%$" }],
    answer: "C", solution: "$g\\propto T^{-2}$：$\\dfrac{\\Delta g}{g}=-2\\dfrac{\\Delta T}{T}=-2\\%$。平方反比使计时误差被放大一倍——所以实验中要测多个周期取平均。" },
  { id: "bpho-r2m2-t1-06", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：单摆的极限】一只摆长 $L=1.0$ m 的单摆，$g=9.81\\ \\mathrm{m\\,s^{-2}}$。 第6步：夏天升温使摆长膨胀 $0.02\\%$。这只摆钟每天大约",
    options: [{ key: "A", text: "慢约 $17$ s" },{ key: "B", text: "慢约 $8.6$ s" },{ key: "C", text: "快约 $8.6$ s" },{ key: "D", text: "慢约 $0.86$ s" },{ key: "E", text: "不变" }],
    answer: "B", solution: "$T\\propto\\sqrt L$：$\\dfrac{\\Delta T}{T}=\\tfrac12\\times0.02\\%=10^{-4}$。每天 $86400$ s 累计慢 $86400\\times10^{-4}\\approx8.6$ s。精密摆钟因此要做温度补偿摆。" },
];

export const BPHO_R2M2_T2: MCQQuestion[] = [
  { id: "bpho-r2m2-t2-01", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：大气有多厚】等温大气模型：$p(h)=p_0e^{-h/H}$，标高 $H=\\dfrac{k_BT}{mg}$；空气分子平均质量 $m\\approx4.8\\times10^{-26}$ kg，$k_B=1.38\\times10^{-23}$，取 $T=280$ K，$g=9.8$。 第1步：计算标高 $H$。",
    options: [{ key: "A", text: "$\\approx82$ km" },{ key: "B", text: "$\\approx2.7$ km" },{ key: "C", text: "$\\approx8.2$ km" },{ key: "D", text: "$\\approx24$ km" },{ key: "E", text: "$\\approx0.82$ km" }],
    answer: "C", solution: "$H=\\dfrac{1.38\\times10^{-23}\\times280}{4.8\\times10^{-26}\\times9.8}\\approx8.2\\times10^3$ m。大气的「厚度尺度」不足 10 km——地球半径的千分之一。" },
  { id: "bpho-r2m2-t2-02", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：大气有多厚】等温大气模型：$p(h)=p_0e^{-h/H}$，标高 $H=\\dfrac{k_BT}{mg}$；空气分子平均质量 $m\\approx4.8\\times10^{-26}$ kg，$k_B=1.38\\times10^{-23}$，取 $T=280$ K，$g=9.8$。 第2步：珠峰顶（$8848$ m）的气压约为海平面的",
    options: [{ key: "A", text: "$\\approx66\\%$" },{ key: "B", text: "$\\approx90\\%$" },{ key: "C", text: "$\\approx50\\%$" },{ key: "D", text: "$\\approx10\\%$" },{ key: "E", text: "$e^{-8848/H}\\approx34\\%$" }],
    answer: "E", solution: "$p/p_0=e^{-8848/8200}=e^{-1.08}\\approx0.34$。三分之一个大气压——这是「死亡地带」缺氧的物理根源。" },
  { id: "bpho-r2m2-t2-03", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：大气有多厚】等温大气模型：$p(h)=p_0e^{-h/H}$，标高 $H=\\dfrac{k_BT}{mg}$；空气分子平均质量 $m\\approx4.8\\times10^{-26}$ kg，$k_B=1.38\\times10^{-23}$，取 $T=280$ K，$g=9.8$。 第3步：气压降低时水的沸点下降（沸腾条件：饱和蒸气压=环境气压）。在高山上用敞口锅煮食物久煮不熟，最本质的原因是",
    options: [{ key: "A", text: "沸点降低——水在远低于 $100\\,^\\circ$C 时就沸腾，达不到烹煮所需温度" },{ key: "B", text: "沸腾吸热更多" },{ key: "C", text: "水的比热容在低压下变大" },{ key: "D", text: "水里氧气太少" },{ key: "E", text: "火焰温度在高山更低" }],
    answer: "A", solution: "沸腾把液温「锁死」在沸点：气压低 → 沸点低（珠峰约 $70\\,^\\circ$C）→ 烹煮化学反应速率大降。解决办法是高压锅——反其道而行。" },
  { id: "bpho-r2m2-t2-04", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：大气有多厚】等温大气模型：$p(h)=p_0e^{-h/H}$，标高 $H=\\dfrac{k_BT}{mg}$；空气分子平均质量 $m\\approx4.8\\times10^{-26}$ kg，$k_B=1.38\\times10^{-23}$，取 $T=280$ K，$g=9.8$。 第4步：标高公式 $H=k_BT/mg$ 说明：同温下，分子质量越小的气体标高越大。由此推断地球大气高层氢、氦稀少的原因是",
    options: [{ key: "A", text: "轻分子速度分布尾部超过逃逸速度的比例大得多，数十亿年间已逃逸殆尽" },{ key: "B", text: "地磁场排斥氢氦" },{ key: "C", text: "太阳风只吹走轻分子且与速度无关" },{ key: "D", text: "地球从未有过氢氦" },{ key: "E", text: "氢氦太轻沉到了地面" }],
    answer: "A", solution: "$v_{rms}\\propto1/\\sqrt m$：氢的典型速度约为氮的 $3.7$ 倍，麦克斯韦分布高速尾部超过 $11.2\\ \\mathrm{km\\,s^{-1}}$ 逃逸速度的比例呈指数级更大——「金斯逃逸」。月球引力更弱，连氮氧都留不住。" },
  { id: "bpho-r2m2-t2-05", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：大气有多厚】等温大气模型：$p(h)=p_0e^{-h/H}$，标高 $H=\\dfrac{k_BT}{mg}$；空气分子平均质量 $m\\approx4.8\\times10^{-26}$ kg，$k_B=1.38\\times10^{-23}$，取 $T=280$ K，$g=9.8$。 第5步：由「气压 $=$ 单位面积上方空气柱重量」估算大气总质量。",
    options: [{ key: "A", text: "$\\approx5\\times10^{14}$ kg" },{ key: "B", text: "$\\approx6\\times10^{24}$ kg" },{ key: "C", text: "$\\approx5\\times10^{22}$ kg" },{ key: "D", text: "$\\approx5\\times10^{16}$ kg" },{ key: "E", text: "$\\dfrac{p_0\\cdot4\\pi R^2}{g}\\approx5\\times10^{18}$ kg" }],
    answer: "E", solution: "$M=\\dfrac{1.01\\times10^5\\times4\\pi(6.37\\times10^6)^2}{9.8}\\approx5.3\\times10^{18}$ kg——只占地球质量的百万分之一。" },
  { id: "bpho-r2m2-t2-06", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：大气有多厚】等温大气模型：$p(h)=p_0e^{-h/H}$，标高 $H=\\dfrac{k_BT}{mg}$；空气分子平均质量 $m\\approx4.8\\times10^{-26}$ kg，$k_B=1.38\\times10^{-23}$，取 $T=280$ K，$g=9.8$。 第6步（一致性检验）：把整个大气「压扁」成密度等于海平面密度 $\\rho_0\\approx1.2\\ \\mathrm{kg\\,m^{-3}}$ 的均匀薄层，它的厚度约为",
    options: [{ key: "A", text: "$\\approx1$ km" },{ key: "B", text: "$\\approx800$ m" },{ key: "C", text: "$\\approx H\\approx8$ km——与标高一致，模型自洽" },{ key: "D", text: "$\\approx100$ km" },{ key: "E", text: "$\\approx6400$ km" }],
    answer: "C", solution: "厚度 $=\\dfrac{p_0/g}{\\rho_0}=\\dfrac{1.01\\times10^5/9.8}{1.2}\\approx8.6$ km $\\approx H$。指数大气的「等效均匀厚度」恰是标高——两条路径互相印证。" },
];

export const BPHO_R2M2_T3: MCQQuestion[] = [
  { id: "bpho-r2m2-t3-01", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：驾驭电子束】$e=1.6\\times10^{-19}$ C，$m_e=9.11\\times10^{-31}$ kg。 第1步：电子从静止经 $2000$ V 加速。求末速度。",
    options: [{ key: "A", text: "$\\approx1.9\\times10^{7}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$\\approx2.7\\times10^{5}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$\\sqrt{2eV/m_e}\\approx2.7\\times10^{7}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$\\approx7.5\\times10^{6}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$\\approx3.0\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "C", solution: "$v=\\sqrt{\\dfrac{2\\times1.6\\times10^{-19}\\times2000}{9.11\\times10^{-31}}}\\approx2.65\\times10^7\\ \\mathrm{m\\,s^{-1}}$（约 $0.09c$，相对论修正 $<1\\%$，尚可忽略）。" },
  { id: "bpho-r2m2-t3-02", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：驾驭电子束】$e=1.6\\times10^{-19}$ C，$m_e=9.11\\times10^{-31}$ kg。 第2步：这束电子进入横向匀强电场区，轨迹是",
    options: [{ key: "A", text: "抛物线——恒力垂直于初速，与平抛运动同构" },{ key: "B", text: "圆弧" },{ key: "C", text: "螺旋线" },{ key: "D", text: "正弦曲线" },{ key: "E", text: "直线" }],
    answer: "A", solution: "横向恒力 $eE$、纵向匀速：与抛体运动完全同构 → 抛物线。（磁场才给圆弧。）" },
  { id: "bpho-r2m2-t3-03", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：驾驭电子束】$e=1.6\\times10^{-19}$ C，$m_e=9.11\\times10^{-31}$ kg。 第3步：改用垂直于速度的匀强磁场 $B=1.0$ mT 控制这束电子。求圆轨道半径。",
    options: [{ key: "A", text: "$\\approx15$ m" },{ key: "B", text: "$\\approx1.5$ m" },{ key: "C", text: "$\\approx1.5$ cm" },{ key: "D", text: "$r=\\dfrac{m_ev}{eB}\\approx15$ cm" },{ key: "E", text: "$\\approx0.15$ mm" }],
    answer: "D", solution: "$r=\\dfrac{9.11\\times10^{-31}\\times2.65\\times10^7}{1.6\\times10^{-19}\\times10^{-3}}\\approx0.15$ m。" },
  { id: "bpho-r2m2-t3-04", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：驾驭电子束】$e=1.6\\times10^{-19}$ C，$m_e=9.11\\times10^{-31}$ kg。 第4步：磁场对电子做的功为",
    options: [{ key: "A", text: "$\\tfrac12m_ev^2$" },{ key: "B", text: "零——磁力始终垂直于速度，只改变方向不改变速率" },{ key: "C", text: "取决于磁场强度" },{ key: "D", text: "负功，使电子减速" },{ key: "E", text: "$evB$ 每秒" }],
    answer: "B", solution: "$\\vec F=-e\\vec v\\times\\vec B\\perp\\vec v$：功率 $\\vec F\\cdot\\vec v=0$。磁场是「免费的方向盘」——只转向不耗能。" },
  { id: "bpho-r2m2-t3-05", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：驾驭电子束】$e=1.6\\times10^{-19}$ C，$m_e=9.11\\times10^{-31}$ kg。 第5步：求该磁场中电子的回旋频率，并指出它与速度的关系。",
    options: [{ key: "A", text: "$\\approx2.8\\times10^{10}$ Hz" },{ key: "B", text: "与半径成正比" },{ key: "C", text: "$\\approx2.8\\times10^{7}$ Hz，正比于速度" },{ key: "D", text: "$f=\\dfrac{eB}{2\\pi m_e}\\approx2.8\\times10^{7}$ Hz，与速度无关" },{ key: "E", text: "$\\approx4.4\\times10^{6}$ Hz，与速度无关" }],
    answer: "D", solution: "$f=\\dfrac{v}{2\\pi r}=\\dfrac{eB}{2\\pi m_e}$——$v$ 消掉。快电子转大圈、慢电子转小圈，周期相同：回旋加速器的立身之本。" },
  { id: "bpho-r2m2-t3-06", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：驾驭电子束】$e=1.6\\times10^{-19}$ C，$m_e=9.11\\times10^{-31}$ kg。 第6步（估算）：地磁场 $B\\sim5\\times10^{-5}$ T。这束电子若只受地磁场作用，回旋半径量级为",
    options: [{ key: "A", text: "$\\sim3$ mm" },{ key: "B", text: "$\\sim3$ cm" },{ key: "C", text: "$\\sim300$ m" },{ key: "D", text: "$\\sim3$ km" },{ key: "E", text: "$\\sim3$ m——所以老式示波管必须磁屏蔽" }],
    answer: "E", solution: "$r=\\dfrac{m_ev}{eB}\\approx3$ m。在几十厘米的管子里这足以造成可见偏移——CRT 需要 μ 金属屏蔽罩。" },
];

export const BPHO_R2M2_T4: MCQQuestion[] = [
  { id: "bpho-r2m2-t4-01", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：用光当帆】太阳常数（地球轨道处）$I=1.4\\times10^{3}\\ \\mathrm{W\\,m^{-2}}$，$c=3\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$。 第1步：光子动量 $p=E/c$。由此证明**完全吸收**的表面所受辐射压为 $P=I/c$，并求地球轨道处的数值。",
    options: [{ key: "A", text: "$\\approx4.7\\times10^{-9}$ Pa" },{ key: "B", text: "$\\approx9.3\\times10^{-6}$ Pa" },{ key: "C", text: "$\\approx4.7\\times10^{-3}$ Pa" },{ key: "D", text: "$\\approx4.7\\times10^{-6}$ Pa" },{ key: "E", text: "$\\approx1.4\\times10^{-6}$ Pa" }],
    answer: "D", solution: "单位时间单位面积到达能量 $I$ → 到达动量 $I/c$ → 压强 $P=I/c=\\dfrac{1.4\\times10^3}{3\\times10^8}\\approx4.7\\times10^{-6}$ Pa。约为大气压的 $10^{-11}$。" },
  { id: "bpho-r2m2-t4-02", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：用光当帆】太阳常数（地球轨道处）$I=1.4\\times10^{3}\\ \\mathrm{W\\,m^{-2}}$，$c=3\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$。 第2步：若表面是**理想反射镜**，辐射压变为",
    options: [{ key: "A", text: "$I/c$，不变" },{ key: "B", text: "$I/2c$" },{ key: "C", text: "零，因为光被弹回" },{ key: "D", text: "$4I/c$" },{ key: "E", text: "$2I/c$——光子动量反向，动量转移加倍" }],
    answer: "E", solution: "吸收：转移 $p$；反射：转移 $2p$（从 $+p$ 到 $-p$）。所以太阳帆都做成高反射镜面。" },
  { id: "bpho-r2m2-t4-03", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "【主题：用光当帆】太阳常数（地球轨道处）$I=1.4\\times10^{3}\\ \\mathrm{W\\,m^{-2}}$，$c=3\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$。 第3步：一面 $1\\ \\mathrm{km^2}$ 的理想反射帆在地球轨道处受到的光压力为",
    options: [{ key: "A", text: "$\\approx4.7$ N" },{ key: "B", text: "$\\approx9.3$ N" },{ key: "C", text: "$\\approx0.93$ N" },{ key: "D", text: "$\\approx93$ N" },{ key: "E", text: "$\\approx9.3\\times10^{3}$ N" }],
    answer: "B", solution: "$F=\\dfrac{2IA}{c}=\\dfrac{2\\times1.4\\times10^3\\times10^6}{3\\times10^8}\\approx9.3$ N——一平方公里的帆只推得动一个西瓜的重量。" },
  { id: "bpho-r2m2-t4-04", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：用光当帆】太阳常数（地球轨道处）$I=1.4\\times10^{3}\\ \\mathrm{W\\,m^{-2}}$，$c=3\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$。 第4步：设帆+载荷共 $1000$ kg。求加速度，并与地球轨道处太阳引力加速度（$\\approx5.9\\times10^{-3}\\ \\mathrm{m\\,s^{-2}}$）比较。",
    options: [{ key: "A", text: "恰好等于引力" },{ key: "B", text: "$\\approx9.3\\ \\mathrm{m\\,s^{-2}}$" },{ key: "C", text: "$\\approx0.93\\ \\mathrm{m\\,s^{-2}}$" },{ key: "D", text: "$\\approx9.3\\times10^{-6}\\ \\mathrm{m\\,s^{-2}}$，远小于引力" },{ key: "E", text: "$\\approx9.3\\times10^{-3}\\ \\mathrm{m\\,s^{-2}}$——略大于太阳引力，帆能「外逃」" }],
    answer: "E", solution: "$a=F/m=9.3\\times10^{-3}\\ \\mathrm{m\\,s^{-2}}$。且光压与引力都按 $1/r^2$ 衰减——只要在某处压过引力，处处压过：帆可以一路螺旋外逃。" },
  { id: "bpho-r2m2-t4-05", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：用光当帆】太阳常数（地球轨道处）$I=1.4\\times10^{3}\\ \\mathrm{W\\,m^{-2}}$，$c=3\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$。 第5步：光压和太阳引力都 $\\propto1/r^2$。这意味着「帆能否逃离太阳」取决于",
    options: [{ key: "A", text: "帆的颜色而非反射率" },{ key: "B", text: "太阳的温度" },{ key: "C", text: "帆的「面质比」$A/m$——与出发位置无关" },{ key: "D", text: "出发时离太阳的距离" },{ key: "E", text: "出发时的速度方向" }],
    answer: "C", solution: "两者同为 $1/r^2$：比值 $\\dfrac{F_{\\text{光}}}{F_{\\text{引}}}=\\text{const}\\times\\dfrac{A}{m}$，是一个只由帆本身决定的常数。$A/m$ 大于临界值即可逃逸。" },
  { id: "bpho-r2m2-t4-06", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "【主题：用光当帆】太阳常数（地球轨道处）$I=1.4\\times10^{3}\\ \\mathrm{W\\,m^{-2}}$，$c=3\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$。 第6步（量级估算）：若该帆恒以 $\\sim10^{-2}\\ \\mathrm{m\\,s^{-2}}$ 加速，跨越到半人马座 α（$\\sim4\\times10^{16}$ m）的时间量级为",
    options: [{ key: "A", text: "$\\sim10^{2}$ 年" },{ key: "B", text: "$\\sim10^{4}$ 年" },{ key: "C", text: "$\\sim10^{6}$ 年" },{ key: "D", text: "$\\sim10$ 年" },{ key: "E", text: "$\\sim1$ 年" }],
    answer: "A", solution: "$t\\sim\\sqrt{2d/a}=\\sqrt{\\dfrac{2\\times4\\times10^{16}}{10^{-2}}}\\approx2.8\\times10^{9}$ s $\\approx90$ 年，量级 $10^2$ 年。（实际光压随距日衰减，这是乐观下限——所以「突破摄星」计划改用地面激光阵列供能。）" },
];
