// BPhO 模拟卷2 —— 模块1对标 Section 1（短题）；模块2以高难选择题近似 Section 2 强度（真实 S2 为长推导题，请配合练习区长题自评）。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const BPHO_MK2_S1: MCQQuestion[] = [
  { id: "bpho-mk2-s1-01", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "Find the ratio of the escape speed from a planet's surface to the speed of a satellite in a circular orbit just above the surface.",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$\\sqrt{2}$" },{ key: "C", text: "$1$" },{ key: "D", text: "$4$" },{ key: "E", text: "$\\dfrac{1}{\\sqrt{2}}$" }],
    answer: "B", solution: "Escape: $\\tfrac12mv_e^2=\\dfrac{GMm}{R}$ gives $v_e=\\sqrt{2GM/R}$. Orbit: $v_o=\\sqrt{GM/R}$. Ratio $=\\sqrt2$." },
  { id: "bpho-mk2-s1-02", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A Ferris wheel of radius $10$ m rotates at constant angular speed. At what angular speed would a rider at the top momentarily feel weightless? ($g=10\\ \\mathrm{m\\,s^{-2}}$)",
    options: [{ key: "A", text: "$1.0\\ \\mathrm{rad\\,s^{-1}}$" },{ key: "B", text: "$\\sqrt{10}\\ \\mathrm{rad\\,s^{-1}}$" },{ key: "C", text: "$0.5\\ \\mathrm{rad\\,s^{-1}}$" },{ key: "D", text: "$10\\ \\mathrm{rad\\,s^{-1}}$" },{ key: "E", text: "$2.0\\ \\mathrm{rad\\,s^{-1}}$" }],
    answer: "A", solution: "Weightless at top when gravity alone supplies the centripetal force: $g=\\omega^2 r$, so $\\omega=\\sqrt{g/r}=\\sqrt{10/10}=1.0\\ \\mathrm{rad\\,s^{-1}}$." },
  { id: "bpho-mk2-s1-03", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A coin rests on a turntable at $0.10$ m from the axis. The coefficient of friction is $0.4$ and $g=10\\ \\mathrm{m\\,s^{-2}}$. Find the maximum angular speed before the coin slips.",
    options: [{ key: "A", text: "$\\sqrt{40}\\approx6.3\\ \\mathrm{rad\\,s^{-1}}$" },{ key: "B", text: "$4.0\\ \\mathrm{rad\\,s^{-1}}$" },{ key: "C", text: "$\\sqrt{20}\\approx4.5\\ \\mathrm{rad\\,s^{-1}}$" },{ key: "D", text: "$\\sqrt{4}=2.0\\ \\mathrm{rad\\,s^{-1}}$" },{ key: "E", text: "$40\\ \\mathrm{rad\\,s^{-1}}$" }],
    answer: "A", solution: "Friction supplies centripetal force: $\\mu g=\\omega^2 r$, so $\\omega=\\sqrt{\\mu g/r}=\\sqrt{0.4\\times10/0.1}=\\sqrt{40}\\approx6.3\\ \\mathrm{rad\\,s^{-1}}$." },
  { id: "bpho-mk2-s1-04", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 1, marks: 3,
    question: "At what height above the Earth's surface (radius $R$) is the gravitational field strength one quarter of its surface value?",
    options: [{ key: "A", text: "$2R$" },{ key: "B", text: "$3R$" },{ key: "C", text: "$R/4$" },{ key: "D", text: "$R$" },{ key: "E", text: "$R/2$" }],
    answer: "D", solution: "$g\\propto1/r^2$: quarter strength at $r=2R$ from the centre, i.e. height $h=r-R=R$." },
  { id: "bpho-mk2-s1-05", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "A car drives over the crest of a humpback bridge of radius of curvature $40$ m. At what speed do the wheels momentarily lose contact with the road? ($g=10\\ \\mathrm{m\\,s^{-2}}$)",
    options: [{ key: "A", text: "$40\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$4\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$10\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$400\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$20\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "E", solution: "Contact lost when gravity alone provides the centripetal force: $mg=\\dfrac{mv^2}{r}$, $v=\\sqrt{gr}=\\sqrt{400}=20\\ \\mathrm{m\\,s^{-1}}$." },
  { id: "bpho-mk2-s1-06", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A comet moves in an elliptical orbit with perihelion (closest) distance $r_1$ and aphelion (farthest) distance $r_2$ from the Sun. Find the ratio of its speed at perihelion to its speed at aphelion.",
    options: [{ key: "A", text: "$\\dfrac{r_2}{r_1}$" },{ key: "B", text: "$\\dfrac{r_1}{r_2}$" },{ key: "C", text: "$\\left(\\dfrac{r_2}{r_1}\\right)^2$" },{ key: "D", text: "$1$" },{ key: "E", text: "$\\sqrt{\\dfrac{r_2}{r_1}}$" }],
    answer: "A", solution: "At the extreme points velocity is perpendicular to the radius, so conservation of angular momentum gives $mv_1r_1=mv_2r_2$, hence $v_1/v_2=r_2/r_1$." },
  { id: "bpho-mk2-s1-07", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "If a planet had the same uniform density as Earth but twice the radius, its surface gravitational field strength would be",
    options: [{ key: "A", text: "four times Earth's" },{ key: "B", text: "twice Earth's" },{ key: "C", text: "eight times Earth's" },{ key: "D", text: "the same as Earth's" },{ key: "E", text: "half Earth's" }],
    answer: "B", solution: "$g=\\dfrac{GM}{R^2}=\\dfrac{G\\rho\\frac43\\pi R^3}{R^2}=\\dfrac43\\pi G\\rho R\\propto R$ at fixed density, so doubling $R$ doubles $g$." },
  { id: "bpho-mk2-s1-08", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A ball of mass $m$ moving at speed $v$ makes a head-on elastic collision with a stationary ball of mass $2m$. Find the speed of the $2m$ ball after the collision.",
    options: [{ key: "A", text: "$\\dfrac{3v}{4}$" },{ key: "B", text: "$\\dfrac{v}{3}$" },{ key: "C", text: "$\\dfrac{v}{2}$" },{ key: "D", text: "$\\dfrac{2v}{3}$" },{ key: "E", text: "$v$" }],
    answer: "D", solution: "Elastic head-on formulas: $v_2'=\\dfrac{2m_1}{m_1+m_2}v=\\dfrac{2m}{3m}v=\\dfrac{2v}{3}$ (and $v_1'=-v/3$). Check: momentum $m v = m(-v/3)+2m(2v/3)=v m$ ✓." },
  { id: "bpho-mk2-s1-09", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A lump of clay of mass $2$ kg moving at speed $v$ hits and sticks to a stationary block of mass $3$ kg. What fraction of the initial kinetic energy is lost in the collision?",
    options: [{ key: "A", text: "$\\dfrac{3}{5}$" },{ key: "B", text: "$\\dfrac{2}{5}$" },{ key: "C", text: "$\\dfrac{3}{4}$" },{ key: "D", text: "$\\dfrac{1}{2}$" },{ key: "E", text: "$\\dfrac{9}{25}$" }],
    answer: "A", solution: "Common speed $=\\dfrac{2v}{5}$. Fraction remaining $=\\dfrac{\\frac12\\cdot5\\cdot(2v/5)^2}{\\frac12\\cdot2v^2}=\\dfrac{2}{5}$, so fraction lost $=\\dfrac{3}{5}$. In general lost fraction $=\\dfrac{M}{m+M}$." },
  { id: "bpho-mk2-s1-10", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A $10$ g bullet travelling at $400\\ \\mathrm{m\\,s^{-1}}$ embeds itself in a $1.99$ kg block hanging from long strings (a ballistic pendulum). To what height does the block rise? ($g=10\\ \\mathrm{m\\,s^{-2}}$)",
    options: [{ key: "A", text: "$0.10$ m" },{ key: "B", text: "$0.40$ m" },{ key: "C", text: "$0.20$ m" },{ key: "D", text: "$2.0$ m" },{ key: "E", text: "$8.0$ m" }],
    answer: "C", solution: "Momentum: $0.01\\times400=2.00\\times v$, so $v=2.0\\ \\mathrm{m\\,s^{-1}}$. Then energy: $h=\\dfrac{v^2}{2g}=\\dfrac{4}{20}=0.20$ m. (Do NOT equate bullet KE to $mgh$ — most KE is lost in embedding.)" },
  { id: "bpho-mk2-s1-11", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A car of mass $m$ climbs a slope of angle $\\theta$ at constant speed $v$, with negligible resistance. Find the power delivered by the engine.",
    options: [{ key: "A", text: "$mgv$" },{ key: "B", text: "$\\dfrac{mgv}{\\sin\\theta}$" },{ key: "C", text: "$mgv\\tan\\theta$" },{ key: "D", text: "$mgv\\cos\\theta$" },{ key: "E", text: "$mgv\\sin\\theta$" }],
    answer: "E", solution: "At constant speed the engine force balances the weight component along the slope: $F=mg\\sin\\theta$. Power $=Fv=mgv\\sin\\theta$." },
  { id: "bpho-mk2-s1-12", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "Water falls $420$ m down a waterfall. If all the gravitational potential energy is converted to internal energy of the water ($c=4200\\ \\mathrm{J\\,kg^{-1}\\,K^{-1}}$, $g=10\\ \\mathrm{m\\,s^{-2}}$), find the temperature rise.",
    options: [{ key: "A", text: "$0.1$ K" },{ key: "B", text: "$10$ K" },{ key: "C", text: "$4.2$ K" },{ key: "D", text: "$1.0$ K" },{ key: "E", text: "$0.42$ K" }],
    answer: "D", solution: "Per kilogram: $gh=c\\,\\Delta T$, so $\\Delta T=\\dfrac{10\\times420}{4200}=1.0$ K. (Mass cancels.)" },
  { id: "bpho-mk2-s1-13", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "A cannon of mass $1000$ kg, free to roll, fires a $10$ kg shell horizontally at $400\\ \\mathrm{m\\,s^{-1}}$ (relative to the ground). Find the recoil speed of the cannon.",
    options: [{ key: "A", text: "$2\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$40\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$4\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$0.4\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$8\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "C", solution: "Momentum conservation from rest: $1000v=10\\times400$, so $v=4\\ \\mathrm{m\\,s^{-1}}$." },
];

export const BPHO_MK2_S2: MCQQuestion[] = [
  { id: "bpho-mk2-s2-01", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A stationary object explodes into two fragments with masses in the ratio $1:2$. What fraction of the total kinetic energy released is carried by the lighter fragment?",
    options: [{ key: "A", text: "$\\dfrac{2}{3}$" },{ key: "B", text: "$\\dfrac{2}{5}$" },{ key: "C", text: "$\\dfrac{1}{2}$" },{ key: "D", text: "$\\dfrac{4}{9}$" },{ key: "E", text: "$\\dfrac{1}{3}$" }],
    answer: "A", solution: "Equal and opposite momenta $p$: $E_k=\\dfrac{p^2}{2m}\\propto\\dfrac1m$. Energies are in ratio $2:1$ (lighter gets more), so the lighter fragment carries $\\dfrac{2}{3}$ of the total." },
  { id: "bpho-mk2-s2-02", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A $60$ kg person walks $3.0$ m (relative to the boat) from one end of a $120$ kg boat towards the other end. Water resistance is negligible. How far does the boat move (relative to the water)?",
    options: [{ key: "A", text: "$3.0$ m" },{ key: "B", text: "$0.5$ m" },{ key: "C", text: "$1.5$ m" },{ key: "D", text: "$1.0$ m" },{ key: "E", text: "$2.0$ m" }],
    answer: "D", solution: "Centre of mass is fixed. If the boat moves $x$ backwards, the person moves $3-x$ forwards relative to water: $60(3-x)=120x$, so $180=180x+60x\\Rightarrow x=1.0$ m." },
  { id: "bpho-mk2-s2-03", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "A uniform rod of length $\\ell$, pivoted at one end, is released from the vertical position and swings down. Using $I=\\tfrac13 M\\ell^2$ about the end, find the speed of the free end as the rod passes through the horizontal.",
    options: [{ key: "A", text: "$\\sqrt{6g\\ell}$" },{ key: "B", text: "$\\sqrt{g\\ell}$" },{ key: "C", text: "$\\sqrt{\\dfrac{3g\\ell}{2}}$" },{ key: "D", text: "$\\sqrt{3g\\ell}$" },{ key: "E", text: "$\\sqrt{2g\\ell}$" }],
    answer: "D", solution: "Centre of mass falls $\\ell/2$: $Mg\\dfrac{\\ell}{2}=\\dfrac12\\cdot\\dfrac{M\\ell^2}{3}\\omega^2$, so $\\omega^2=\\dfrac{3g}{\\ell}$ and $v_{\\mathrm{end}}=\\omega\\ell=\\sqrt{3g\\ell}$." },
  { id: "bpho-mk2-s2-04", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A solid disc and a thin hoop of equal mass and radius roll (without slipping) from rest down the same slope. Find the ratio $v_{\\text{disc}}/v_{\\text{hoop}}$ of their speeds at the bottom.",
    options: [{ key: "A", text: "$\\dfrac{2}{\\sqrt{3}}$" },{ key: "B", text: "$\\dfrac{4}{3}$" },{ key: "C", text: "$\\dfrac{\\sqrt{3}}{2}$" },{ key: "D", text: "$\\sqrt{2}$" },{ key: "E", text: "$1$" }],
    answer: "A", solution: "Rolling: $mgh=\\tfrac12mv^2(1+k)$ where $I=kmr^2$; $v=\\sqrt{\\dfrac{2gh}{1+k}}$. Disc $k=\\tfrac12$, hoop $k=1$: ratio $=\\sqrt{\\dfrac{2}{3/2}}=\\sqrt{4/3}=\\dfrac{2}{\\sqrt3}$." },
  { id: "bpho-mk2-s2-05", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "An ice skater spinning freely pulls in her arms so that her moment of inertia halves. Her kinetic energy of rotation",
    options: [{ key: "A", text: "quadruples" },{ key: "B", text: "falls to one quarter" },{ key: "C", text: "doubles" },{ key: "D", text: "halves" },{ key: "E", text: "stays the same" }],
    answer: "C", solution: "Angular momentum $L=I\\omega$ is conserved, so $\\omega$ doubles. $E_k=\\tfrac12I\\omega^2=\\dfrac{L^2}{2I}$ doubles when $I$ halves. The extra energy comes from the work done pulling her arms in." },
  { id: "bpho-mk2-s2-06", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "A disc starts from rest with uniform angular acceleration $\\alpha=2\\ \\mathrm{rad\\,s^{-2}}$. For a point at radius $0.50$ m, find the magnitude of its total linear acceleration at $t=1.0$ s.",
    options: [{ key: "A", text: "$\\sqrt{5}\\approx2.2\\ \\mathrm{m\\,s^{-2}}$" },{ key: "B", text: "$1.0\\ \\mathrm{m\\,s^{-2}}$" },{ key: "C", text: "$3.0\\ \\mathrm{m\\,s^{-2}}$" },{ key: "D", text: "$\\sqrt{3}\\approx1.7\\ \\mathrm{m\\,s^{-2}}$" },{ key: "E", text: "$2.0\\ \\mathrm{m\\,s^{-2}}$" }],
    answer: "A", solution: "Tangential: $a_t=\\alpha r=1.0$. At $t=1$: $\\omega=2\\ \\mathrm{rad\\,s^{-1}}$, centripetal $a_c=\\omega^2r=2.0$. Total $=\\sqrt{1^2+2^2}=\\sqrt5\\approx2.2\\ \\mathrm{m\\,s^{-2}}$." },
  { id: "bpho-mk2-s2-07", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A uniform solid sphere rolls without slipping along level ground. What fraction of its total kinetic energy is rotational? ($I=\\tfrac25 mr^2$)",
    options: [{ key: "A", text: "$\\dfrac{5}{7}$" },{ key: "B", text: "$\\dfrac{2}{7}$" },{ key: "C", text: "$\\dfrac{1}{2}$" },{ key: "D", text: "$\\dfrac{1}{3}$" },{ key: "E", text: "$\\dfrac{2}{5}$" }],
    answer: "B", solution: "$E_{\\mathrm{rot}}=\\tfrac12 I\\omega^2=\\tfrac15 mv^2$ and $E_{\\mathrm{tot}}=\\tfrac12mv^2+\\tfrac15mv^2=\\tfrac7{10}mv^2$. Fraction $=\\dfrac{1/5}{7/10}=\\dfrac{2}{7}$." },
  { id: "bpho-mk2-s2-08", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "Masses of $3$ kg and $1$ kg hang from a string over a pulley that is a uniform disc of mass $4$ kg ($I=\\tfrac12MR^2$). The string does not slip. Find the acceleration of the masses. ($g=10\\ \\mathrm{m\\,s^{-2}}$)",
    options: [{ key: "A", text: "$\\dfrac{20}{7}\\ \\mathrm{m\\,s^{-2}}$" },{ key: "B", text: "$\\dfrac{10}{4}\\ \\mathrm{m\\,s^{-2}}$" },{ key: "C", text: "$5\\ \\mathrm{m\\,s^{-2}}$" },{ key: "D", text: "$2.5\\ \\mathrm{m\\,s^{-2}}$" },{ key: "E", text: "$\\dfrac{10}{3}\\ \\mathrm{m\\,s^{-2}}$" }],
    answer: "E", solution: "The pulley adds an effective inertia $I/R^2=\\tfrac12M=2$ kg: $a=\\dfrac{(m_1-m_2)g}{m_1+m_2+\\tfrac12M}=\\dfrac{2\\times10}{3+1+2}=\\dfrac{10}{3}\\ \\mathrm{m\\,s^{-2}}$." },
  { id: "bpho-mk2-s2-09", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "A uniform horizontal beam is hinged at one end to a wall and supported at the other end by a vertical cable. The cable suddenly snaps. Find the initial acceleration of the free end of the beam. ($I=\\tfrac13M\\ell^2$ about the hinge)",
    options: [{ key: "A", text: "$2g$" },{ key: "B", text: "$\\dfrac{2g}{3}$" },{ key: "C", text: "$g$" },{ key: "D", text: "$\\dfrac{3g}{2}$" },{ key: "E", text: "$\\dfrac{g}{2}$" }],
    answer: "D", solution: "Torque about hinge: $Mg\\dfrac{\\ell}{2}=\\dfrac{M\\ell^2}{3}\\alpha$, so $\\alpha=\\dfrac{3g}{2\\ell}$ and $a_{\\mathrm{end}}=\\alpha\\ell=\\dfrac{3g}{2}$ — greater than $g$! (The hinge pulls down initially.)" },
  { id: "bpho-mk2-s2-10", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A uniform rod of mass $M$ and length $\\ell$ is pivoted at a point $\\ell/4$ from one end. Using the parallel axis theorem, find its moment of inertia about the pivot. ($I_{\\mathrm{cm}}=\\tfrac1{12}M\\ell^2$)",
    options: [{ key: "A", text: "$\\dfrac{M\\ell^2}{4}$" },{ key: "B", text: "$\\dfrac{7M\\ell^2}{48}$" },{ key: "C", text: "$\\dfrac{5M\\ell^2}{24}$" },{ key: "D", text: "$\\dfrac{M\\ell^2}{12}$" },{ key: "E", text: "$\\dfrac{M\\ell^2}{16}$" }],
    answer: "B", solution: "Distance from centre to pivot $d=\\ell/4$: $I=\\dfrac{M\\ell^2}{12}+M\\left(\\dfrac{\\ell}{4}\\right)^2=M\\ell^2\\left(\\dfrac1{12}+\\dfrac1{16}\\right)=\\dfrac{7M\\ell^2}{48}$." },
];
