// ESAT 模拟卷二 —— 又一套全新原创题，与卷一及练习题库均不重复。
// 全部五选一（A–E），对标真实 ESAT 结构与难度，含多步推理题。
// id 前缀 esat-mk2-*。

import type { MCQQuestion } from "@/lib/tests/questions/types";

// ── 模块一：数学（27 题 / 40 分钟）────────────────────────────────────────
export const ESAT_MK2_MATH: MCQQuestion[] = [
  { id: "esat-mk2-m-01", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 1, marks: 1,
    question: "If $x+y=7$ and $2x-y=5$, find the value of $xy$.",
    options: [ {key:"A",text:"$5$"},{key:"B",text:"$7$"},{key:"C",text:"$10$"},{key:"D",text:"$12$"},{key:"E",text:"$21$"} ],
    answer: "D", solution: "Adding: $3x=12\\Rightarrow x=4$, so $y=3$ and $xy=12$." },
  { id: "esat-mk2-m-02", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "For what values of $k$ does $x^2-4x+k=0$ have no real roots?",
    options: [ {key:"A",text:"$k<4$"},{key:"B",text:"$k>4$"},{key:"C",text:"$k=4$"},{key:"D",text:"$k<-4$"},{key:"E",text:"$k>16$"} ],
    answer: "B", solution: "No real roots requires discriminant $<0$: $16-4k<0\\Rightarrow k>4$." },
  { id: "esat-mk2-m-03", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "Solve $2^{x+1}=16$.",
    options: [ {key:"A",text:"$x=2$"},{key:"B",text:"$x=3$"},{key:"C",text:"$x=4$"},{key:"D",text:"$x=7$"},{key:"E",text:"$x=8$"} ],
    answer: "B", solution: "$16=2^4$, so $x+1=4\\Rightarrow x=3$." },
  { id: "esat-mk2-m-04", type: "mcq", testId: "esat", topicId: "esat-math3", difficulty: 3, marks: 1,
    question: "The sum of the first 5 terms of the geometric progression $3, 6, 12, \\ldots$ is:",
    options: [ {key:"A",text:"$45$"},{key:"B",text:"$48$"},{key:"C",text:"$93$"},{key:"D",text:"$96$"},{key:"E",text:"$189$"} ],
    answer: "C", solution: "$a=3, r=2$: $S_5=\\dfrac{3(2^5-1)}{2-1}=3\\times31=93$." },
  { id: "esat-mk2-m-05", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 2, marks: 1,
    question: "If $y=4x^2-3x+2$, the value of $\\dfrac{dy}{dx}$ at $x=1$ is:",
    options: [ {key:"A",text:"$1$"},{key:"B",text:"$4$"},{key:"C",text:"$5$"},{key:"D",text:"$8$"},{key:"E",text:"$11$"} ],
    answer: "C", solution: "$\\dfrac{dy}{dx}=8x-3$; at $x=1$: $8-3=5$." },
  { id: "esat-mk2-m-06", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 2, marks: 1,
    question: "Evaluate $\\displaystyle\\int_0^2 3x^2\\,dx$.",
    options: [ {key:"A",text:"$4$"},{key:"B",text:"$6$"},{key:"C",text:"$8$"},{key:"D",text:"$12$"},{key:"E",text:"$24$"} ],
    answer: "C", solution: "$[x^3]_0^2=8-0=8$." },
  { id: "esat-mk2-m-07", type: "mcq", testId: "esat", topicId: "esat-math3", difficulty: 1, marks: 1,
    question: "The distance between the points $(1,2)$ and $(4,6)$ is:",
    options: [ {key:"A",text:"$\\sqrt{13}$"},{key:"B",text:"$5$"},{key:"C",text:"$\\sqrt{7}$"},{key:"D",text:"$7$"},{key:"E",text:"$25$"} ],
    answer: "B", solution: "$\\sqrt{(4-1)^2+(6-2)^2}=\\sqrt{9+16}=5$." },
  { id: "esat-mk2-m-08", type: "mcq", testId: "esat", topicId: "esat-math3", difficulty: 2, marks: 1,
    question: "How many solutions does $\\cos x = 0$ have for $0^\\circ \\le x \\le 360^\\circ$?",
    options: [ {key:"A",text:"$0$"},{key:"B",text:"$1$"},{key:"C",text:"$2$"},{key:"D",text:"$3$"},{key:"E",text:"$4$"} ],
    answer: "C", solution: "$\\cos x=0$ at $x=90^\\circ$ and $270^\\circ$ — two solutions." },
  { id: "esat-mk2-m-09", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 1, marks: 1,
    question: "Simplify $\\dfrac{2^3\\times 2^4}{2^2}$.",
    options: [ {key:"A",text:"$8$"},{key:"B",text:"$16$"},{key:"C",text:"$32$"},{key:"D",text:"$64$"},{key:"E",text:"$2^9$"} ],
    answer: "C", solution: "$2^{3+4-2}=2^5=32$." },
  { id: "esat-mk2-m-10", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "If $f(x)=x^2+1$ and $g(x)=2x$, find $f(g(3))$.",
    options: [ {key:"A",text:"$10$"},{key:"B",text:"$13$"},{key:"C",text:"$19$"},{key:"D",text:"$37$"},{key:"E",text:"$49$"} ],
    answer: "D", solution: "$g(3)=6$, then $f(6)=36+1=37$." },
  { id: "esat-mk2-m-11", type: "mcq", testId: "esat", topicId: "esat-math3", difficulty: 2, marks: 1,
    question: "In the arithmetic progression $7, 10, 13, \\ldots$, the 10th term is:",
    options: [ {key:"A",text:"$28$"},{key:"B",text:"$30$"},{key:"C",text:"$31$"},{key:"D",text:"$34$"},{key:"E",text:"$37$"} ],
    answer: "D", solution: "$a_{10}=7+(10-1)(3)=7+27=34$." },
  { id: "esat-mk2-m-12", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "The solution of $x^2>16$ is:",
    options: [ {key:"A",text:"$-4<x<4$"},{key:"B",text:"$x>4$ only"},{key:"C",text:"$x<-4$ or $x>4$"},{key:"D",text:"$x>16$"},{key:"E",text:"$|x|<4$"} ],
    answer: "C", solution: "$|x|>4\\Rightarrow x<-4$ or $x>4$." },
  { id: "esat-mk2-m-13", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 3, marks: 1,
    question: "The remainder when $x^3+2x^2-x+1$ is divided by $(x+1)$ is:",
    options: [ {key:"A",text:"$-1$"},{key:"B",text:"$1$"},{key:"C",text:"$2$"},{key:"D",text:"$3$"},{key:"E",text:"$5$"} ],
    answer: "D", solution: "Substitute $x=-1$: $-1+2+1+1=3$." },
  { id: "esat-mk2-m-14", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "By completing the square, the minimum value of $x^2+4x+1$ is:",
    options: [ {key:"A",text:"$-5$"},{key:"B",text:"$-4$"},{key:"C",text:"$-3$"},{key:"D",text:"$1$"},{key:"E",text:"$3$"} ],
    answer: "C", solution: "$(x+2)^2-3$; minimum $=-3$ at $x=-2$." },
  { id: "esat-mk2-m-15", type: "mcq", testId: "esat", topicId: "esat-math3", difficulty: 3, marks: 1,
    question: "A line passes through $(0,3)$ with gradient $-2$. Its $x$-intercept is at $x=$:",
    options: [ {key:"A",text:"$-1.5$"},{key:"B",text:"$1.5$"},{key:"C",text:"$2$"},{key:"D",text:"$3$"},{key:"E",text:"$6$"} ],
    answer: "B", solution: "Line: $y=-2x+3$. Set $y=0$: $0=-2x+3\\Rightarrow x=1.5$." },
  { id: "esat-mk2-m-16", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 2, marks: 1,
    question: "The gradient of the tangent to $y=x^3$ at $x=1$ is:",
    options: [ {key:"A",text:"$1$"},{key:"B",text:"$2$"},{key:"C",text:"$3$"},{key:"D",text:"$6$"},{key:"E",text:"$9$"} ],
    answer: "C", solution: "$\\dfrac{dy}{dx}=3x^2=3$ at $x=1$." },
  { id: "esat-mk2-m-17", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 2, marks: 1,
    question: "The curve $y=x^2-6x+5$ has its minimum point at $x=$:",
    options: [ {key:"A",text:"$1$"},{key:"B",text:"$2$"},{key:"C",text:"$3$"},{key:"D",text:"$5$"},{key:"E",text:"$6$"} ],
    answer: "C", solution: "$\\dfrac{dy}{dx}=2x-6=0\\Rightarrow x=3$." },
  { id: "esat-mk2-m-18", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 3, marks: 1,
    question: "The graph of $y=f(x)$ is transformed to $y=f(2x)$. This is a:",
    options: [ {key:"A",text:"horizontal stretch by factor 2"},{key:"B",text:"horizontal compression to half the width"},{key:"C",text:"translation 2 units up"},{key:"D",text:"translation 2 units right"},{key:"E",text:"vertical stretch by factor 2"} ],
    answer: "B", solution: "Replacing $x$ with $2x$ compresses the graph horizontally by a factor of $\\tfrac12$." },
  { id: "esat-mk2-m-19", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "The sum of the solutions of $|x+2|=6$ is:",
    options: [ {key:"A",text:"$-8$"},{key:"B",text:"$-4$"},{key:"C",text:"$2$"},{key:"D",text:"$4$"},{key:"E",text:"$8$"} ],
    answer: "B", solution: "$x+2=6\\Rightarrow x=4$; $x+2=-6\\Rightarrow x=-8$; sum $=-4$." },
  { id: "esat-mk2-m-20", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 1, marks: 1,
    question: "Evaluate $\\log_{10} 1000$.",
    options: [ {key:"A",text:"$1$"},{key:"B",text:"$2$"},{key:"C",text:"$3$"},{key:"D",text:"$10$"},{key:"E",text:"$100$"} ],
    answer: "C", solution: "$10^3=1000$, so $\\log_{10}1000=3$." },
  { id: "esat-mk2-m-21", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 2, marks: 1,
    question: "The area under $y=2x$ between $x=1$ and $x=3$ is:",
    options: [ {key:"A",text:"$4$"},{key:"B",text:"$6$"},{key:"C",text:"$8$"},{key:"D",text:"$9$"},{key:"E",text:"$16$"} ],
    answer: "C", solution: "$\\int_1^3 2x\\,dx=[x^2]_1^3=9-1=8$." },
  { id: "esat-mk2-m-22", type: "mcq", testId: "esat", topicId: "esat-math3", difficulty: 3, marks: 1,
    question: "If $\\theta$ is acute and $\\sin\\theta=\\tfrac{3}{5}$, then $\\tan\\theta=$:",
    options: [ {key:"A",text:"$\\tfrac{3}{5}$"},{key:"B",text:"$\\tfrac{3}{4}$"},{key:"C",text:"$\\tfrac{4}{3}$"},{key:"D",text:"$\\tfrac{5}{4}$"},{key:"E",text:"$\\tfrac{5}{3}$"} ],
    answer: "B", solution: "$\\cos\\theta=\\sqrt{1-\\tfrac{9}{25}}=\\tfrac{4}{5}$, so $\\tan\\theta=\\dfrac{\\sin\\theta}{\\cos\\theta}=\\dfrac{3/5}{4/5}=\\tfrac{3}{4}$." },
  { id: "esat-mk2-m-23", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 3, marks: 1,
    question: "The coefficient of $x^2$ in the expansion of $(2+x)^4$ is:",
    options: [ {key:"A",text:"$6$"},{key:"B",text:"$8$"},{key:"C",text:"$12$"},{key:"D",text:"$16$"},{key:"E",text:"$24$"} ],
    answer: "E", solution: "Term: $\\binom{4}{2}2^2 x^2=6\\times4\\,x^2=24x^2$." },
  { id: "esat-mk2-m-24", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 3, marks: 1,
    question: "If $\\alpha,\\beta$ are the roots of $x^2-7x+10=0$, the value of $\\dfrac{1}{\\alpha}+\\dfrac{1}{\\beta}$ is:",
    options: [ {key:"A",text:"$\\tfrac{1}{7}$"},{key:"B",text:"$\\tfrac{7}{10}$"},{key:"C",text:"$\\tfrac{10}{7}$"},{key:"D",text:"$7$"},{key:"E",text:"$10$"} ],
    answer: "B", solution: "$\\dfrac{1}{\\alpha}+\\dfrac{1}{\\beta}=\\dfrac{\\alpha+\\beta}{\\alpha\\beta}=\\dfrac{7}{10}$." },
  { id: "esat-mk2-m-25", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 2, marks: 1,
    question: "A particle has velocity $v=4t-t^2$ ms⁻¹. Its acceleration at $t=1\\,\\text{s}$ is:",
    options: [ {key:"A",text:"$0\\,\\text{m s}^{-2}$"},{key:"B",text:"$1\\,\\text{m s}^{-2}$"},{key:"C",text:"$2\\,\\text{m s}^{-2}$"},{key:"D",text:"$3\\,\\text{m s}^{-2}$"},{key:"E",text:"$4\\,\\text{m s}^{-2}$"} ],
    answer: "C", solution: "$a=\\dfrac{dv}{dt}=4-2t$; at $t=1$: $4-2=2\\,\\text{m s}^{-2}$." },
  { id: "esat-mk2-m-26", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "Solve $3^{2x}=81$.",
    options: [ {key:"A",text:"$x=1.5$"},{key:"B",text:"$x=2$"},{key:"C",text:"$x=3$"},{key:"D",text:"$x=4$"},{key:"E",text:"$x=1$"} ],
    answer: "B", solution: "$81=3^4$, so $2x=4\\Rightarrow x=2$." },
  { id: "esat-mk2-m-27", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "The curve $y=x^2-4x+3$ crosses the $x$-axis at two points. The sum of their $x$-coordinates is:",
    options: [ {key:"A",text:"$-4$"},{key:"B",text:"$1$"},{key:"C",text:"$3$"},{key:"D",text:"$4$"},{key:"E",text:"$7$"} ],
    answer: "D", solution: "Roots of $x^2-4x+3=(x-1)(x-3)$ are $1$ and $3$; sum $=4$ (equals $-\\tfrac{b}{a}$)." },
];

// ── 模块二：物理（27 题 / 40 分钟）────────────────────────────────────────
export const ESAT_MK2_PHYS: MCQQuestion[] = [
  { id: "esat-mk2-p-01", type: "mcq", testId: "esat", topicId: "esat-phys1", difficulty: 2, marks: 1,
    question: "A body starts from rest and accelerates at $2\\,\\text{m s}^{-2}$ over a distance of $25\\,\\text{m}$. Its final speed is:",
    options: [ {key:"A",text:"$5\\,\\text{m s}^{-1}$"},{key:"B",text:"$10\\,\\text{m s}^{-1}$"},{key:"C",text:"$25\\,\\text{m s}^{-1}$"},{key:"D",text:"$50\\,\\text{m s}^{-1}$"},{key:"E",text:"$100\\,\\text{m s}^{-1}$"} ],
    answer: "B", solution: "$v^2=u^2+2as=0+2(2)(25)=100\\Rightarrow v=10\\,\\text{m s}^{-1}$." },
  { id: "esat-mk2-p-02", type: "mcq", testId: "esat", topicId: "esat-phys1", difficulty: 1, marks: 1,
    question: "The weight of a $5\\,\\text{kg}$ object ($g=10\\,\\text{m s}^{-2}$) is:",
    options: [ {key:"A",text:"$0.5\\,\\text{N}$"},{key:"B",text:"$5\\,\\text{N}$"},{key:"C",text:"$10\\,\\text{N}$"},{key:"D",text:"$50\\,\\text{N}$"},{key:"E",text:"$500\\,\\text{N}$"} ],
    answer: "D", solution: "$W=mg=5\\times10=50\\,\\text{N}$." },
  { id: "esat-mk2-p-03", type: "mcq", testId: "esat", topicId: "esat-phys1", difficulty: 1, marks: 1,
    question: "A constant force of $20\\,\\text{N}$ moves an object $4\\,\\text{m}$ in the direction of the force. The work done is:",
    options: [ {key:"A",text:"$5\\,\\text{J}$"},{key:"B",text:"$16\\,\\text{J}$"},{key:"C",text:"$24\\,\\text{J}$"},{key:"D",text:"$40\\,\\text{J}$"},{key:"E",text:"$80\\,\\text{J}$"} ],
    answer: "E", solution: "$W=Fd=20\\times4=80\\,\\text{J}$." },
  { id: "esat-mk2-p-04", type: "mcq", testId: "esat", topicId: "esat-phys1", difficulty: 1, marks: 1,
    question: "A machine does $600\\,\\text{J}$ of work in $30\\,\\text{s}$. Its power is:",
    options: [ {key:"A",text:"$2\\,\\text{W}$"},{key:"B",text:"$20\\,\\text{W}$"},{key:"C",text:"$30\\,\\text{W}$"},{key:"D",text:"$600\\,\\text{W}$"},{key:"E",text:"$18000\\,\\text{W}$"} ],
    answer: "B", solution: "$P=\\dfrac{W}{t}=\\dfrac{600}{30}=20\\,\\text{W}$." },
  { id: "esat-mk2-p-05", type: "mcq", testId: "esat", topicId: "esat-phys1", difficulty: 2, marks: 1,
    question: "A $3\\,\\text{kg}$ object is accelerated from rest to $4\\,\\text{m s}^{-1}$. The impulse applied is:",
    options: [ {key:"A",text:"$4\\,\\text{N s}$"},{key:"B",text:"$7\\,\\text{N s}$"},{key:"C",text:"$12\\,\\text{N s}$"},{key:"D",text:"$24\\,\\text{N s}$"},{key:"E",text:"$1.33\\,\\text{N s}$"} ],
    answer: "C", solution: "Impulse $=\\Delta p=m\\Delta v=3\\times4=12\\,\\text{N s}$." },
  { id: "esat-mk2-p-06", type: "mcq", testId: "esat", topicId: "esat-phys1", difficulty: 2, marks: 1,
    question: "A spring of stiffness $200\\,\\text{N m}^{-1}$ is extended by $0.05\\,\\text{m}$. The force in the spring is:",
    options: [ {key:"A",text:"$0.25\\,\\text{N}$"},{key:"B",text:"$4\\,\\text{N}$"},{key:"C",text:"$10\\,\\text{N}$"},{key:"D",text:"$40\\,\\text{N}$"},{key:"E",text:"$1000\\,\\text{N}$"} ],
    answer: "C", solution: "Hooke's law $F=kx=200\\times0.05=10\\,\\text{N}$." },
  { id: "esat-mk2-p-07", type: "mcq", testId: "esat", topicId: "esat-phys1", difficulty: 2, marks: 1,
    question: "An object falls freely from rest through $5\\,\\text{m}$ ($g=10$). Its speed at the bottom is:",
    options: [ {key:"A",text:"$5\\,\\text{m s}^{-1}$"},{key:"B",text:"$7\\,\\text{m s}^{-1}$"},{key:"C",text:"$10\\,\\text{m s}^{-1}$"},{key:"D",text:"$50\\,\\text{m s}^{-1}$"},{key:"E",text:"$100\\,\\text{m s}^{-1}$"} ],
    answer: "C", solution: "$v=\\sqrt{2gh}=\\sqrt{2(10)(5)}=\\sqrt{100}=10\\,\\text{m s}^{-1}$." },
  { id: "esat-mk2-p-08", type: "mcq", testId: "esat", topicId: "esat-phys1", difficulty: 1, marks: 1,
    question: "A force of $20\\,\\text{N}$ acts at a perpendicular distance of $0.3\\,\\text{m}$ from a pivot. The moment is:",
    options: [ {key:"A",text:"$0.6\\,\\text{N m}$"},{key:"B",text:"$3\\,\\text{N m}$"},{key:"C",text:"$6\\,\\text{N m}$"},{key:"D",text:"$20\\,\\text{N m}$"},{key:"E",text:"$60\\,\\text{N m}$"} ],
    answer: "C", solution: "Moment $=F\\times d=20\\times0.3=6\\,\\text{N m}$." },
  { id: "esat-mk2-p-09", type: "mcq", testId: "esat", topicId: "esat-phys1", difficulty: 2, marks: 1,
    question: "An object has mass $240\\,\\text{g}$ and volume $30\\,\\text{cm}^3$. Its density is:",
    options: [ {key:"A",text:"$0.125\\,\\text{g cm}^{-3}$"},{key:"B",text:"$8\\,\\text{g cm}^{-3}$"},{key:"C",text:"$80\\,\\text{g cm}^{-3}$"},{key:"D",text:"$210\\,\\text{g cm}^{-3}$"},{key:"E",text:"$270\\,\\text{g cm}^{-3}$"} ],
    answer: "B", solution: "$\\rho=\\dfrac{m}{V}=\\dfrac{240}{30}=8\\,\\text{g cm}^{-3}$." },
  { id: "esat-mk2-p-10", type: "mcq", testId: "esat", topicId: "esat-phys1", difficulty: 2, marks: 1,
    question: "A force of $50\\,\\text{N}$ acts on an area of $0.02\\,\\text{m}^2$. The pressure is:",
    options: [ {key:"A",text:"$1\\,\\text{Pa}$"},{key:"B",text:"$25\\,\\text{Pa}$"},{key:"C",text:"$100\\,\\text{Pa}$"},{key:"D",text:"$1000\\,\\text{Pa}$"},{key:"E",text:"$2500\\,\\text{Pa}$"} ],
    answer: "E", solution: "$P=\\dfrac{F}{A}=\\dfrac{50}{0.02}=2500\\,\\text{Pa}$." },
  { id: "esat-mk2-p-11", type: "mcq", testId: "esat", topicId: "esat-phys2", difficulty: 1, marks: 1,
    question: "Resistors of $2\\,\\Omega$, $3\\,\\Omega$ and $5\\,\\Omega$ are connected in series. The total resistance is:",
    options: [ {key:"A",text:"$0.97\\,\\Omega$"},{key:"B",text:"$5\\,\\Omega$"},{key:"C",text:"$10\\,\\Omega$"},{key:"D",text:"$15\\,\\Omega$"},{key:"E",text:"$30\\,\\Omega$"} ],
    answer: "C", solution: "In series: $2+3+5=10\\,\\Omega$." },
  { id: "esat-mk2-p-12", type: "mcq", testId: "esat", topicId: "esat-phys2", difficulty: 1, marks: 1,
    question: "A potential difference of $24\\,\\text{V}$ drives a current through an $8\\,\\Omega$ resistor. The current is:",
    options: [ {key:"A",text:"$0.33\\,\\text{A}$"},{key:"B",text:"$2\\,\\text{A}$"},{key:"C",text:"$3\\,\\text{A}$"},{key:"D",text:"$4\\,\\text{A}$"},{key:"E",text:"$32\\,\\text{A}$"} ],
    answer: "C", solution: "$I=\\dfrac{V}{R}=\\dfrac{24}{8}=3\\,\\text{A}$." },
  { id: "esat-mk2-p-13", type: "mcq", testId: "esat", topicId: "esat-phys2", difficulty: 2, marks: 1,
    question: "A current of $3\\,\\text{A}$ flows through a $4\\,\\Omega$ resistor. The power dissipated is:",
    options: [ {key:"A",text:"$9\\,\\text{W}$"},{key:"B",text:"$12\\,\\text{W}$"},{key:"C",text:"$36\\,\\text{W}$"},{key:"D",text:"$48\\,\\text{W}$"},{key:"E",text:"$144\\,\\text{W}$"} ],
    answer: "C", solution: "$P=I^2R=3^2\\times4=36\\,\\text{W}$." },
  { id: "esat-mk2-p-14", type: "mcq", testId: "esat", topicId: "esat-phys2", difficulty: 2, marks: 1,
    question: "A $60\\,\\text{W}$ device runs for $2$ minutes. The energy it uses is:",
    options: [ {key:"A",text:"$30\\,\\text{J}$"},{key:"B",text:"$72\\,\\text{J}$"},{key:"C",text:"$120\\,\\text{J}$"},{key:"D",text:"$3600\\,\\text{J}$"},{key:"E",text:"$7200\\,\\text{J}$"} ],
    answer: "E", solution: "$E=Pt=60\\times(2\\times60)=60\\times120=7200\\,\\text{J}$." },
  { id: "esat-mk2-p-15", type: "mcq", testId: "esat", topicId: "esat-phys2", difficulty: 2, marks: 1,
    question: "Two parallel plates $0.04\\,\\text{m}$ apart have $200\\,\\text{V}$ between them. The electric field strength is:",
    options: [ {key:"A",text:"$8\\,\\text{V m}^{-1}$"},{key:"B",text:"$50\\,\\text{V m}^{-1}$"},{key:"C",text:"$500\\,\\text{V m}^{-1}$"},{key:"D",text:"$5000\\,\\text{V m}^{-1}$"},{key:"E",text:"$0.0002\\,\\text{V m}^{-1}$"} ],
    answer: "D", solution: "$E=\\dfrac{V}{d}=\\dfrac{200}{0.04}=5000\\,\\text{V m}^{-1}$." },
  { id: "esat-mk2-p-16", type: "mcq", testId: "esat", topicId: "esat-phys2", difficulty: 3, marks: 1,
    question: "A charge of $0.003\\,\\text{C}$ sits in a uniform field of $2000\\,\\text{V m}^{-1}$. The force on it is:",
    options: [ {key:"A",text:"$0.6\\,\\text{N}$"},{key:"B",text:"$1.5\\,\\text{N}$"},{key:"C",text:"$3\\,\\text{N}$"},{key:"D",text:"$6\\,\\text{N}$"},{key:"E",text:"$60\\,\\text{N}$"} ],
    answer: "D", solution: "$F=EQ=2000\\times0.003=6\\,\\text{N}$." },
  { id: "esat-mk2-p-17", type: "mcq", testId: "esat", topicId: "esat-phys2", difficulty: 3, marks: 1,
    question: "A charge of $0.4\\,\\text{C}$ moves at $10\\,\\text{m s}^{-1}$ perpendicular to a $0.5\\,\\text{T}$ field. The magnetic force is:",
    options: [ {key:"A",text:"$0.5\\,\\text{N}$"},{key:"B",text:"$2\\,\\text{N}$"},{key:"C",text:"$4\\,\\text{N}$"},{key:"D",text:"$5\\,\\text{N}$"},{key:"E",text:"$20\\,\\text{N}$"} ],
    answer: "B", solution: "$F=BQv=0.5\\times0.4\\times10=2\\,\\text{N}$." },
  { id: "esat-mk2-p-18", type: "mcq", testId: "esat", topicId: "esat-phys2", difficulty: 3, marks: 1,
    question: "An ideal transformer raises $12\\,\\text{V}$ to $240\\,\\text{V}$. If the secondary current is $0.50\\,\\text{A}$, what is the primary current?",
    options: [ {key:"A",text:"$0.025\\,\\text{A}$"},{key:"B",text:"$0.50\\,\\text{A}$"},{key:"C",text:"$2.0\\,\\text{A}$"},{key:"D",text:"$10\\,\\text{A}$"},{key:"E",text:"$20\\,\\text{A}$"} ],
    answer: "D", solution: "For an ideal transformer, $V_pI_p=V_sI_s$. Hence $12I_p=240\\times0.50$, so $I_p=10\\,\\text{A}$." },
  { id: "esat-mk2-p-19", type: "mcq", testId: "esat", topicId: "esat-phys3", difficulty: 3, marks: 1,
    question: "A wave travelling at $300\\,\\text{m s}^{-1}$ has a wavelength of $0.5\\,\\text{m}$. Its frequency is:",
    options: [ {key:"A",text:"$1.67\\,\\text{Hz}$"},{key:"B",text:"$150\\,\\text{Hz}$"},{key:"C",text:"$300\\,\\text{Hz}$"},{key:"D",text:"$600\\,\\text{Hz}$"},{key:"E",text:"$1200\\,\\text{Hz}$"} ],
    answer: "D", solution: "$f=\\dfrac{v}{\\lambda}=\\dfrac{300}{0.5}=600\\,\\text{Hz}$." },
  { id: "esat-mk2-p-20", type: "mcq", testId: "esat", topicId: "esat-phys3", difficulty: 1, marks: 1,
    question: "A wave has a period of $0.002\\,\\text{s}$. Its frequency is:",
    options: [ {key:"A",text:"$5\\,\\text{Hz}$"},{key:"B",text:"$50\\,\\text{Hz}$"},{key:"C",text:"$200\\,\\text{Hz}$"},{key:"D",text:"$500\\,\\text{Hz}$"},{key:"E",text:"$2000\\,\\text{Hz}$"} ],
    answer: "D", solution: "$f=\\dfrac{1}{T}=\\dfrac{1}{0.002}=500\\,\\text{Hz}$." },
  { id: "esat-mk2-p-21", type: "mcq", testId: "esat", topicId: "esat-phys3", difficulty: 1, marks: 1,
    question: "Which part of the electromagnetic spectrum has the LOWEST frequency?",
    options: [ {key:"A",text:"Radio waves"},{key:"B",text:"Microwaves"},{key:"C",text:"Visible light"},{key:"D",text:"X-rays"},{key:"E",text:"Gamma rays"} ],
    answer: "A", solution: "Radio waves have the longest wavelength and therefore the lowest frequency of the EM spectrum." },
  { id: "esat-mk2-p-22", type: "mcq", testId: "esat", topicId: "esat-phys3", difficulty: 2, marks: 1,
    question: "If the frequency of a photon is doubled, its energy:",
    options: [ {key:"A",text:"halves"},{key:"B",text:"is unchanged"},{key:"C",text:"doubles"},{key:"D",text:"quadruples"},{key:"E",text:"becomes zero"} ],
    answer: "C", solution: "$E=hf$, so energy is directly proportional to frequency — doubling $f$ doubles $E$." },
  { id: "esat-mk2-p-23", type: "mcq", testId: "esat", topicId: "esat-phys3", difficulty: 3, marks: 1,
    question: "A source has a half-life of $10\\,\\text{min}$ and an initial activity of $1600\\,\\text{Bq}$. After $30\\,\\text{min}$, its activity is:",
    options: [ {key:"A",text:"$100\\,\\text{Bq}$"},{key:"B",text:"$160\\,\\text{Bq}$"},{key:"C",text:"$200\\,\\text{Bq}$"},{key:"D",text:"$400\\,\\text{Bq}$"},{key:"E",text:"$800\\,\\text{Bq}$"} ],
    answer: "C", solution: "$30\\,\\text{min}=3$ half-lives: $1600\\to800\\to400\\to200\\,\\text{Bq}$." },
  { id: "esat-mk2-p-24", type: "mcq", testId: "esat", topicId: "esat-phys3", difficulty: 2, marks: 1,
    question: "In beta-minus decay, a neutron changes into a proton and emits:",
    options: [ {key:"A",text:"an alpha particle"},{key:"B",text:"an electron"},{key:"C",text:"a proton"},{key:"D",text:"a gamma photon"},{key:"E",text:"a neutron"} ],
    answer: "B", solution: "In $\\beta^-$ decay a neutron becomes a proton, emitting a fast electron (and an antineutrino)." },
  { id: "esat-mk2-p-25", type: "mcq", testId: "esat", topicId: "esat-phys3", difficulty: 3, marks: 1,
    question: "In the decay $^{14}_{\\,6}\\text{C}\\rightarrow{}^{14}_{\\,7}\\text{N}+X$, particle $X$ is:",
    options: [ {key:"A",text:"an alpha particle"},{key:"B",text:"a beta-minus particle (electron)"},{key:"C",text:"a neutron"},{key:"D",text:"a gamma photon"},{key:"E",text:"a positron"} ],
    answer: "B", solution: "Mass number unchanged (14) while atomic number rises 6→7 — characteristic of $\\beta^-$ decay." },
  { id: "esat-mk2-p-26", type: "mcq", testId: "esat", topicId: "esat-phys3", difficulty: 1, marks: 1,
    question: "Which statement about nuclear fusion is correct?",
    options: [ {key:"A",text:"A heavy nucleus splits into lighter ones"},{key:"B",text:"Two light nuclei combine, releasing energy"},{key:"C",text:"An electron is captured by the nucleus"},{key:"D",text:"Only a gamma photon is emitted"},{key:"E",text:"The total mass increases"} ],
    answer: "B", solution: "Fusion joins light nuclei into a heavier one with release of energy (the process powering stars)." },
  { id: "esat-mk2-p-27", type: "mcq", testId: "esat", topicId: "esat-phys1", difficulty: 2, marks: 1,
    question: "Two perpendicular forces of $3\\,\\text{N}$ and $4\\,\\text{N}$ act on a point. Their resultant has magnitude:",
    options: [ {key:"A",text:"$1\\,\\text{N}$"},{key:"B",text:"$3.5\\,\\text{N}$"},{key:"C",text:"$5\\,\\text{N}$"},{key:"D",text:"$7\\,\\text{N}$"},{key:"E",text:"$12\\,\\text{N}$"} ],
    answer: "C", solution: "Perpendicular forces add in quadrature: $\\sqrt{3^2+4^2}=\\sqrt{25}=5\\,\\text{N}$." },
];
