// ESAT 模拟卷一 —— 全新原创题，专供「完整模拟卷」计时考试使用。
// 与练习/模拟题库（esat.ts / esat-topup.ts）完全隔离，保证考试时是「没做过的题」。
// 全部五选一（A–E），对标真实 ESAT 结构与难度，含多步推理题。
// id 前缀 esat-mk1-* 不与任何练习题冲突。

import type { MCQQuestion } from "@/lib/tests/questions/types";

// ── 模块一：数学（27 题 / 40 分钟）────────────────────────────────────────
export const ESAT_MK1_MATH: MCQQuestion[] = [
  { id: "esat-mk1-m-01", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "For what values of $k$ does $x^2+kx+9=0$ have two equal real roots?",
    options: [ {key:"A",text:"$k=6$ only"},{key:"B",text:"$k=\\pm 6$"},{key:"C",text:"$k=\\pm 3$"},{key:"D",text:"$k=9$"},{key:"E",text:"$k=\\pm 9$"} ],
    answer: "B", solution: "Equal roots need discriminant $=0$: $k^2-36=0\\Rightarrow k=\\pm 6$." },
  { id: "esat-mk1-m-02", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 3, marks: 1,
    question: "The coefficient of $x^3$ in the expansion of $(1+2x)^5$ is:",
    options: [ {key:"A",text:"$10$"},{key:"B",text:"$20$"},{key:"C",text:"$40$"},{key:"D",text:"$80$"},{key:"E",text:"$160$"} ],
    answer: "D", solution: "$\\binom{5}{3}(2x)^3=10\\cdot 8x^3=80x^3$." },
  { id: "esat-mk1-m-03", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 3, marks: 1,
    question: "Solve $\\log_2 x + \\log_2(x-2) = 3$.",
    options: [ {key:"A",text:"$x=4$"},{key:"B",text:"$x=-2$"},{key:"C",text:"$x=4$ or $x=-2$"},{key:"D",text:"$x=8$"},{key:"E",text:"$x=2$"} ],
    answer: "A", solution: "$\\log_2[x(x-2)]=3\\Rightarrow x^2-2x=8\\Rightarrow (x-4)(x+2)=0$. Reject $x=-2$ (log domain), so $x=4$." },
  { id: "esat-mk1-m-04", type: "mcq", testId: "esat", topicId: "esat-math3", difficulty: 2, marks: 1,
    question: "Find the sum to infinity of $12 + 6 + 3 + \\cdots$",
    options: [ {key:"A",text:"$12$"},{key:"B",text:"$18$"},{key:"C",text:"$24$"},{key:"D",text:"$36$"},{key:"E",text:"$48$"} ],
    answer: "C", solution: "$r=\\tfrac12$, $S_\\infty=\\dfrac{a}{1-r}=\\dfrac{12}{0.5}=24$." },
  { id: "esat-mk1-m-05", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 2, marks: 1,
    question: "The gradient of the curve $y=x^3-3x$ at $x=2$ is:",
    options: [ {key:"A",text:"$3$"},{key:"B",text:"$6$"},{key:"C",text:"$9$"},{key:"D",text:"$12$"},{key:"E",text:"$15$"} ],
    answer: "C", solution: "$\\dfrac{dy}{dx}=3x^2-3$; at $x=2$: $12-3=9$." },
  { id: "esat-mk1-m-06", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 2, marks: 1,
    question: "Evaluate $\\displaystyle\\int_1^3 (2x+1)\\,dx$.",
    options: [ {key:"A",text:"$6$"},{key:"B",text:"$8$"},{key:"C",text:"$10$"},{key:"D",text:"$12$"},{key:"E",text:"$14$"} ],
    answer: "C", solution: "$[x^2+x]_1^3=(9+3)-(1+1)=12-2=10$." },
  { id: "esat-mk1-m-07", type: "mcq", testId: "esat", topicId: "esat-math3", difficulty: 3, marks: 1,
    question: "How many points of intersection does the line $y=x+1$ have with the circle $x^2+y^2=25$?",
    options: [ {key:"A",text:"$0$"},{key:"B",text:"$1$"},{key:"C",text:"$2$"},{key:"D",text:"$3$"},{key:"E",text:"infinitely many"} ],
    answer: "C", solution: "Substituting: $x^2+(x+1)^2=25\\Rightarrow 2x^2+2x-24=0\\Rightarrow x^2+x-12=0$, discriminant $1+48=49>0$, so two points." },
  { id: "esat-mk1-m-08", type: "mcq", testId: "esat", topicId: "esat-math3", difficulty: 2, marks: 1,
    question: "How many solutions does $2\\sin x = 1$ have for $0^\\circ \\le x \\le 360^\\circ$?",
    options: [ {key:"A",text:"$0$"},{key:"B",text:"$1$"},{key:"C",text:"$2$"},{key:"D",text:"$3$"},{key:"E",text:"$4$"} ],
    answer: "C", solution: "$\\sin x=0.5\\Rightarrow x=30^\\circ,150^\\circ$ — two solutions." },
  { id: "esat-mk1-m-09", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 1, marks: 1,
    question: "Simplify $\\sqrt{8}+\\sqrt{2}$.",
    options: [ {key:"A",text:"$\\sqrt{10}$"},{key:"B",text:"$2\\sqrt{3}$"},{key:"C",text:"$3\\sqrt{2}$"},{key:"D",text:"$4\\sqrt{2}$"},{key:"E",text:"$\\sqrt{6}$"} ],
    answer: "C", solution: "$\\sqrt{8}=2\\sqrt2$, so $2\\sqrt2+\\sqrt2=3\\sqrt2$." },
  { id: "esat-mk1-m-10", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "If $f(x)=3x-2$, find $f^{-1}(x)$.",
    options: [ {key:"A",text:"$\\dfrac{x+2}{3}$"},{key:"B",text:"$\\dfrac{x-2}{3}$"},{key:"C",text:"$3x+2$"},{key:"D",text:"$\\dfrac{2-x}{3}$"},{key:"E",text:"$\\dfrac{1}{3x-2}$"} ],
    answer: "A", solution: "Let $y=3x-2$; solve $x=\\dfrac{y+2}{3}$, so $f^{-1}(x)=\\dfrac{x+2}{3}$." },
  { id: "esat-mk1-m-11", type: "mcq", testId: "esat", topicId: "esat-math3", difficulty: 3, marks: 1,
    question: "An arithmetic progression is $5, 9, 13, \\ldots$. The sum of its first 20 terms is:",
    options: [ {key:"A",text:"$800$"},{key:"B",text:"$840$"},{key:"C",text:"$860$"},{key:"D",text:"$880$"},{key:"E",text:"$900$"} ],
    answer: "C", solution: "$a=5,d=4$: $S_{20}=\\tfrac{20}{2}[2(5)+19(4)]=10(10+76)=860$." },
  { id: "esat-mk1-m-12", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "Solve the inequality $x^2-x-6 \\le 0$.",
    options: [ {key:"A",text:"$x\\le-2$ or $x\\ge3$"},{key:"B",text:"$-2\\le x\\le3$"},{key:"C",text:"$-3\\le x\\le2$"},{key:"D",text:"$x\\ge3$"},{key:"E",text:"$-2<x<3$"} ],
    answer: "B", solution: "$(x-3)(x+2)\\le0\\Rightarrow -2\\le x\\le3$ (between the roots)." },
  { id: "esat-mk1-m-13", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 3, marks: 1,
    question: "Given that $(x-2)$ is a factor of $x^3-3x^2+kx-2$, the value of $k$ is:",
    options: [ {key:"A",text:"$1$"},{key:"B",text:"$2$"},{key:"C",text:"$3$"},{key:"D",text:"$4$"},{key:"E",text:"$6$"} ],
    answer: "C", solution: "Factor theorem: $f(2)=8-12+2k-2=2k-6=0\\Rightarrow k=3$." },
  { id: "esat-mk1-m-14", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "The minimum value of $2x^2-8x+3$ is:",
    options: [ {key:"A",text:"$-13$"},{key:"B",text:"$-8$"},{key:"C",text:"$-5$"},{key:"D",text:"$-3$"},{key:"E",text:"$3$"} ],
    answer: "C", solution: "$2(x-2)^2-5$; minimum $=-5$ at $x=2$." },
  { id: "esat-mk1-m-15", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "Solving $y=x^2$ and $y=x+2$ simultaneously, the sum of the $x$-values of the solutions is:",
    options: [ {key:"A",text:"$-1$"},{key:"B",text:"$0$"},{key:"C",text:"$1$"},{key:"D",text:"$2$"},{key:"E",text:"$3$"} ],
    answer: "C", solution: "$x^2-x-2=0\\Rightarrow (x-2)(x+1)=0$, $x=2,-1$; sum $=1$." },
  { id: "esat-mk1-m-16", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 3, marks: 1,
    question: "The equation of the tangent to $y=x^2$ at the point $(1,1)$ is:",
    options: [ {key:"A",text:"$y=2x-1$"},{key:"B",text:"$y=2x+1$"},{key:"C",text:"$y=x$"},{key:"D",text:"$y=2x$"},{key:"E",text:"$y=x-1$"} ],
    answer: "A", solution: "Gradient $=2x=2$ at $x=1$; line through $(1,1)$: $y-1=2(x-1)\\Rightarrow y=2x-1$." },
  { id: "esat-mk1-m-17", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 2, marks: 1,
    question: "The curve $y=x^3-3x^2$ has stationary points at:",
    options: [ {key:"A",text:"$x=0$ only"},{key:"B",text:"$x=2$ only"},{key:"C",text:"$x=0$ and $x=2$"},{key:"D",text:"$x=-2$ and $x=0$"},{key:"E",text:"$x=1$"} ],
    answer: "C", solution: "$\\dfrac{dy}{dx}=3x^2-6x=3x(x-2)=0\\Rightarrow x=0,2$." },
  { id: "esat-mk1-m-18", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 1, marks: 1,
    question: "The graph of $y=f(x)$ is transformed to $y=f(x)+3$. This is a translation of:",
    options: [ {key:"A",text:"$3$ units up"},{key:"B",text:"$3$ units down"},{key:"C",text:"$3$ units right"},{key:"D",text:"$3$ units left"},{key:"E",text:"a vertical stretch"} ],
    answer: "A", solution: "Adding 3 to the output shifts the graph 3 units up." },
  { id: "esat-mk1-m-19", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 3, marks: 1,
    question: "The product of the solutions of $|3x-6|=9$ is:",
    options: [ {key:"A",text:"$-5$"},{key:"B",text:"$-3$"},{key:"C",text:"$4$"},{key:"D",text:"$5$"},{key:"E",text:"$15$"} ],
    answer: "A", solution: "$3x-6=9\\Rightarrow x=5$; $3x-6=-9\\Rightarrow x=-1$. Product $=5\\times(-1)=-5$." },
  { id: "esat-mk1-m-20", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "A population is modelled by $N=200\\times 2^{t}$ where $t$ is in hours. After 3 hours, $N$ is:",
    options: [ {key:"A",text:"$600$"},{key:"B",text:"$800$"},{key:"C",text:"$1200$"},{key:"D",text:"$1600$"},{key:"E",text:"$2400$"} ],
    answer: "D", solution: "$N=200\\times 2^3=200\\times 8=1600$." },
  { id: "esat-mk1-m-21", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 3, marks: 1,
    question: "The area enclosed between $y=x$ and $y=x^2$ from $x=0$ to $x=1$ is:",
    options: [ {key:"A",text:"$\\tfrac{1}{12}$"},{key:"B",text:"$\\tfrac{1}{6}$"},{key:"C",text:"$\\tfrac{1}{3}$"},{key:"D",text:"$\\tfrac{1}{2}$"},{key:"E",text:"$\\tfrac{2}{3}$"} ],
    answer: "B", solution: "$\\int_0^1 (x-x^2)\\,dx=\\left[\\tfrac{x^2}{2}-\\tfrac{x^3}{3}\\right]_0^1=\\tfrac12-\\tfrac13=\\tfrac16$." },
  { id: "esat-mk1-m-22", type: "mcq", testId: "esat", topicId: "esat-math3", difficulty: 2, marks: 1,
    question: "Simplify $\\dfrac{\\sin^2\\theta}{1-\\cos^2\\theta}$.",
    options: [ {key:"A",text:"$0$"},{key:"B",text:"$1$"},{key:"C",text:"$\\sin\\theta$"},{key:"D",text:"$\\cos^2\\theta$"},{key:"E",text:"$\\tan^2\\theta$"} ],
    answer: "B", solution: "Since $1-\\cos^2\\theta=\\sin^2\\theta$, the expression equals $1$." },
  { id: "esat-mk1-m-23", type: "mcq", testId: "esat", topicId: "esat-math3", difficulty: 3, marks: 1,
    question: "In a geometric progression the 3rd term is 18 and the 5th term is 162. The first term and common ratio are:",
    options: [ {key:"A",text:"$a=2,\\ r=3$"},{key:"B",text:"$a=6,\\ r=3$"},{key:"C",text:"$a=2,\\ r=9$"},{key:"D",text:"$a=3,\\ r=3$"},{key:"E",text:"$a=9,\\ r=2$"} ],
    answer: "A", solution: "$\\dfrac{ar^4}{ar^2}=r^2=\\dfrac{162}{18}=9\\Rightarrow r=3$; then $ar^2=18\\Rightarrow 9a=18\\Rightarrow a=2$." },
  { id: "esat-mk1-m-24", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 3, marks: 1,
    question: "If $\\alpha$ and $\\beta$ are the roots of $x^2-6x+8=0$, the value of $\\alpha^2+\\beta^2$ is:",
    options: [ {key:"A",text:"$4$"},{key:"B",text:"$16$"},{key:"C",text:"$20$"},{key:"D",text:"$28$"},{key:"E",text:"$36$"} ],
    answer: "C", solution: "$\\alpha+\\beta=6,\\ \\alpha\\beta=8$; $\\alpha^2+\\beta^2=(\\alpha+\\beta)^2-2\\alpha\\beta=36-16=20$." },
  { id: "esat-mk1-m-25", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 3, marks: 1,
    question: "A particle's displacement is $s=t^3-6t^2$ metres. Its velocity is zero (for $t>0$) at $t=$:",
    options: [ {key:"A",text:"$2\\,\\text{s}$"},{key:"B",text:"$3\\,\\text{s}$"},{key:"C",text:"$4\\,\\text{s}$"},{key:"D",text:"$6\\,\\text{s}$"},{key:"E",text:"$8\\,\\text{s}$"} ],
    answer: "C", solution: "$v=\\dfrac{ds}{dt}=3t^2-12t=3t(t-4)=0\\Rightarrow t=0$ or $4$; for $t>0$, $t=4\\,\\text{s}$." },
  { id: "esat-mk1-m-26", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 3, marks: 1,
    question: "Evaluate $2\\log_3 9 - \\log_3\\!\\left(\\tfrac{1}{3}\\right)$.",
    options: [ {key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$4$"},{key:"D",text:"$5$"},{key:"E",text:"$6$"} ],
    answer: "D", solution: "$\\log_3 9=2$ and $\\log_3(\\tfrac13)=-1$, so $2(2)-(-1)=4+1=5$." },
  { id: "esat-mk1-m-27", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 3, marks: 1,
    question: "The gradient of the normal to the curve $y=x^2$ at the point $(1,1)$ is:",
    options: [ {key:"A",text:"$2$"},{key:"B",text:"$-2$"},{key:"C",text:"$\\tfrac12$"},{key:"D",text:"$-\\tfrac12$"},{key:"E",text:"$-1$"} ],
    answer: "D", solution: "Tangent gradient $=2x=2$; normal gradient $=-\\dfrac{1}{2}$ (negative reciprocal)." },
];

// ── 模块二：物理（27 题 / 40 分钟）────────────────────────────────────────
export const ESAT_MK1_PHYS: MCQQuestion[] = [
  { id: "esat-mk1-p-01", type: "mcq", testId: "esat", topicId: "esat-phys1", difficulty: 1, marks: 1,
    question: "A car accelerates from rest at $4\\,\\text{m s}^{-2}$ for $5\\,\\text{s}$. Its final velocity is:",
    options: [ {key:"A",text:"$4\\,\\text{m s}^{-1}$"},{key:"B",text:"$9\\,\\text{m s}^{-1}$"},{key:"C",text:"$20\\,\\text{m s}^{-1}$"},{key:"D",text:"$40\\,\\text{m s}^{-1}$"},{key:"E",text:"$80\\,\\text{m s}^{-1}$"} ],
    answer: "C", solution: "$v=u+at=0+4(5)=20\\,\\text{m s}^{-1}$." },
  { id: "esat-mk1-p-02", type: "mcq", testId: "esat", topicId: "esat-phys1", difficulty: 1, marks: 1,
    question: "A force of $12\\,\\text{N}$ acts on a $3\\,\\text{kg}$ mass. Its acceleration is:",
    options: [ {key:"A",text:"$0.25\\,\\text{m s}^{-2}$"},{key:"B",text:"$4\\,\\text{m s}^{-2}$"},{key:"C",text:"$9\\,\\text{m s}^{-2}$"},{key:"D",text:"$15\\,\\text{m s}^{-2}$"},{key:"E",text:"$36\\,\\text{m s}^{-2}$"} ],
    answer: "B", solution: "$a=F/m=12/3=4\\,\\text{m s}^{-2}$." },
  { id: "esat-mk1-p-03", type: "mcq", testId: "esat", topicId: "esat-phys1", difficulty: 1, marks: 1,
    question: "The kinetic energy of a $4\\,\\text{kg}$ object moving at $5\\,\\text{m s}^{-1}$ is:",
    options: [ {key:"A",text:"$10\\,\\text{J}$"},{key:"B",text:"$20\\,\\text{J}$"},{key:"C",text:"$50\\,\\text{J}$"},{key:"D",text:"$100\\,\\text{J}$"},{key:"E",text:"$200\\,\\text{J}$"} ],
    answer: "C", solution: "$E_k=\\tfrac12 mv^2=\\tfrac12(4)(25)=50\\,\\text{J}$." },
  { id: "esat-mk1-p-04", type: "mcq", testId: "esat", topicId: "esat-phys1", difficulty: 1, marks: 1,
    question: "Lifting a $2\\,\\text{kg}$ mass by $3\\,\\text{m}$ ($g=10\\,\\text{m s}^{-2}$) increases its gravitational potential energy by:",
    options: [ {key:"A",text:"$6\\,\\text{J}$"},{key:"B",text:"$20\\,\\text{J}$"},{key:"C",text:"$30\\,\\text{J}$"},{key:"D",text:"$60\\,\\text{J}$"},{key:"E",text:"$600\\,\\text{J}$"} ],
    answer: "D", solution: "$\\Delta E_p=mgh=2(10)(3)=60\\,\\text{J}$." },
  { id: "esat-mk1-p-05", type: "mcq", testId: "esat", topicId: "esat-phys1", difficulty: 1, marks: 1,
    question: "The momentum of a $2\\,\\text{kg}$ object moving at $8\\,\\text{m s}^{-1}$ is:",
    options: [ {key:"A",text:"$4\\,\\text{kg m s}^{-1}$"},{key:"B",text:"$10\\,\\text{kg m s}^{-1}$"},{key:"C",text:"$16\\,\\text{kg m s}^{-1}$"},{key:"D",text:"$32\\,\\text{kg m s}^{-1}$"},{key:"E",text:"$64\\,\\text{kg m s}^{-1}$"} ],
    answer: "C", solution: "$p=mv=2\\times8=16\\,\\text{kg m s}^{-1}$." },
  { id: "esat-mk1-p-06", type: "mcq", testId: "esat", topicId: "esat-phys1", difficulty: 2, marks: 1,
    question: "A $4\\,\\text{kg}$ trolley at $3\\,\\text{m s}^{-1}$ collides with a stationary $2\\,\\text{kg}$ trolley and they move off together. Their common velocity is:",
    options: [ {key:"A",text:"$1\\,\\text{m s}^{-1}$"},{key:"B",text:"$1.5\\,\\text{m s}^{-1}$"},{key:"C",text:"$2\\,\\text{m s}^{-1}$"},{key:"D",text:"$3\\,\\text{m s}^{-1}$"},{key:"E",text:"$4\\,\\text{m s}^{-1}$"} ],
    answer: "C", solution: "Momentum: $(4)(3)=(4+2)v\\Rightarrow v=12/6=2\\,\\text{m s}^{-1}$." },
  { id: "esat-mk1-p-07", type: "mcq", testId: "esat", topicId: "esat-phys1", difficulty: 2, marks: 1,
    question: "A crane lifts a $60\\,\\text{kg}$ load at a steady $0.5\\,\\text{m s}^{-1}$ ($g=10$). The output power is:",
    options: [ {key:"A",text:"$30\\,\\text{W}$"},{key:"B",text:"$150\\,\\text{W}$"},{key:"C",text:"$300\\,\\text{W}$"},{key:"D",text:"$600\\,\\text{W}$"},{key:"E",text:"$3000\\,\\text{W}$"} ],
    answer: "C", solution: "$P=Fv=mgv=60(10)(0.5)=300\\,\\text{W}$." },
  { id: "esat-mk1-p-08", type: "mcq", testId: "esat", topicId: "esat-phys1", difficulty: 2, marks: 1,
    question: "A ball is dropped from rest from a height of $45\\,\\text{m}$ ($g=10$). The time to reach the ground is:",
    options: [ {key:"A",text:"$1.5\\,\\text{s}$"},{key:"B",text:"$2\\,\\text{s}$"},{key:"C",text:"$3\\,\\text{s}$"},{key:"D",text:"$4.5\\,\\text{s}$"},{key:"E",text:"$9\\,\\text{s}$"} ],
    answer: "C", solution: "$h=\\tfrac12 g t^2\\Rightarrow 45=5t^2\\Rightarrow t=3\\,\\text{s}$." },
  { id: "esat-mk1-p-09", type: "mcq", testId: "esat", topicId: "esat-phys1", difficulty: 3, marks: 1,
    question: "A ball is thrown horizontally at $15\\,\\text{m s}^{-1}$ from a $20\\,\\text{m}$ high cliff ($g=10$). Its horizontal range is:",
    options: [ {key:"A",text:"$7.5\\,\\text{m}$"},{key:"B",text:"$15\\,\\text{m}$"},{key:"C",text:"$30\\,\\text{m}$"},{key:"D",text:"$45\\,\\text{m}$"},{key:"E",text:"$60\\,\\text{m}$"} ],
    answer: "C", solution: "Time to fall: $t=\\sqrt{2h/g}=\\sqrt{4}=2\\,\\text{s}$; range $=15\\times2=30\\,\\text{m}$." },
  { id: "esat-mk1-p-10", type: "mcq", testId: "esat", topicId: "esat-phys1", difficulty: 2, marks: 1,
    question: "A $2\\,\\text{kg}$ mass moves in a circle of radius $1.5\\,\\text{m}$ at $3\\,\\text{m s}^{-1}$. The centripetal force is:",
    options: [ {key:"A",text:"$4\\,\\text{N}$"},{key:"B",text:"$6\\,\\text{N}$"},{key:"C",text:"$9\\,\\text{N}$"},{key:"D",text:"$12\\,\\text{N}$"},{key:"E",text:"$18\\,\\text{N}$"} ],
    answer: "D", solution: "$F=\\dfrac{mv^2}{r}=\\dfrac{2\\times9}{1.5}=12\\,\\text{N}$." },
  { id: "esat-mk1-p-11", type: "mcq", testId: "esat", topicId: "esat-phys2", difficulty: 1, marks: 1,
    question: "Two $4\\,\\Omega$ resistors connected in parallel have a combined resistance of:",
    options: [ {key:"A",text:"$1\\,\\Omega$"},{key:"B",text:"$2\\,\\Omega$"},{key:"C",text:"$4\\,\\Omega$"},{key:"D",text:"$8\\,\\Omega$"},{key:"E",text:"$16\\,\\Omega$"} ],
    answer: "B", solution: "Identical resistors in parallel: $R=4/2=2\\,\\Omega$." },
  { id: "esat-mk1-p-12", type: "mcq", testId: "esat", topicId: "esat-phys2", difficulty: 2, marks: 1,
    question: "A $3\\,\\Omega$ resistor has $12\\,\\text{V}$ across it. The power dissipated is:",
    options: [ {key:"A",text:"$4\\,\\text{W}$"},{key:"B",text:"$12\\,\\text{W}$"},{key:"C",text:"$16\\,\\text{W}$"},{key:"D",text:"$36\\,\\text{W}$"},{key:"E",text:"$48\\,\\text{W}$"} ],
    answer: "E", solution: "$P=\\dfrac{V^2}{R}=\\dfrac{144}{3}=48\\,\\text{W}$." },
  { id: "esat-mk1-p-13", type: "mcq", testId: "esat", topicId: "esat-phys2", difficulty: 2, marks: 1,
    question: "A current of $0.5\\,\\text{A}$ flows for $2$ minutes. The charge transferred is:",
    options: [ {key:"A",text:"$0.25\\,\\text{C}$"},{key:"B",text:"$1\\,\\text{C}$"},{key:"C",text:"$30\\,\\text{C}$"},{key:"D",text:"$60\\,\\text{C}$"},{key:"E",text:"$120\\,\\text{C}$"} ],
    answer: "D", solution: "$Q=It=0.5\\times(2\\times60)=0.5\\times120=60\\,\\text{C}$." },
  { id: "esat-mk1-p-14", type: "mcq", testId: "esat", topicId: "esat-phys2", difficulty: 3, marks: 1,
    question: "A cell of EMF $9\\,\\text{V}$ and internal resistance $1\\,\\Omega$ is connected to a $2\\,\\Omega$ resistor. The current is:",
    options: [ {key:"A",text:"$1\\,\\text{A}$"},{key:"B",text:"$2\\,\\text{A}$"},{key:"C",text:"$3\\,\\text{A}$"},{key:"D",text:"$4.5\\,\\text{A}$"},{key:"E",text:"$9\\,\\text{A}$"} ],
    answer: "C", solution: "$I=\\dfrac{\\varepsilon}{R+r}=\\dfrac{9}{2+1}=3\\,\\text{A}$." },
  { id: "esat-mk1-p-15", type: "mcq", testId: "esat", topicId: "esat-phys2", difficulty: 1, marks: 1,
    question: "A $4\\,\\mu\\text{F}$ capacitor is charged to $5\\,\\text{V}$. The charge stored is:",
    options: [ {key:"A",text:"$0.8\\,\\mu\\text{C}$"},{key:"B",text:"$1.25\\,\\mu\\text{C}$"},{key:"C",text:"$9\\,\\mu\\text{C}$"},{key:"D",text:"$20\\,\\mu\\text{C}$"},{key:"E",text:"$80\\,\\mu\\text{C}$"} ],
    answer: "D", solution: "$Q=CV=4\\times5=20\\,\\mu\\text{C}$." },
  { id: "esat-mk1-p-16", type: "mcq", testId: "esat", topicId: "esat-phys2", difficulty: 3, marks: 1,
    question: "The energy stored in a $2\\,\\mu\\text{F}$ capacitor charged to $100\\,\\text{V}$ is:",
    options: [ {key:"A",text:"$1\\times10^{-6}\\,\\text{J}$"},{key:"B",text:"$1\\times10^{-4}\\,\\text{J}$"},{key:"C",text:"$1\\times10^{-2}\\,\\text{J}$"},{key:"D",text:"$2\\times10^{-2}\\,\\text{J}$"},{key:"E",text:"$1\\times10^{-1}\\,\\text{J}$"} ],
    answer: "C", solution: "$E=\\tfrac12 CV^2=\\tfrac12(2\\times10^{-6})(100^2)=1\\times10^{-2}\\,\\text{J}$." },
  { id: "esat-mk1-p-17", type: "mcq", testId: "esat", topicId: "esat-phys2", difficulty: 2, marks: 1,
    question: "A $0.2\\,\\text{m}$ wire carries $5\\,\\text{A}$ at right angles to a $0.4\\,\\text{T}$ field. The force on it is:",
    options: [ {key:"A",text:"$0.04\\,\\text{N}$"},{key:"B",text:"$0.4\\,\\text{N}$"},{key:"C",text:"$0.8\\,\\text{N}$"},{key:"D",text:"$2\\,\\text{N}$"},{key:"E",text:"$4\\,\\text{N}$"} ],
    answer: "B", solution: "$F=BIL=0.4\\times5\\times0.2=0.4\\,\\text{N}$." },
  { id: "esat-mk1-p-18", type: "mcq", testId: "esat", topicId: "esat-phys2", difficulty: 2, marks: 1,
    question: "A transformer has 200 primary turns and 50 secondary turns. With $240\\,\\text{V}$ on the primary, the secondary voltage is:",
    options: [ {key:"A",text:"$30\\,\\text{V}$"},{key:"B",text:"$60\\,\\text{V}$"},{key:"C",text:"$120\\,\\text{V}$"},{key:"D",text:"$480\\,\\text{V}$"},{key:"E",text:"$960\\,\\text{V}$"} ],
    answer: "B", solution: "$V_s=V_p\\dfrac{N_s}{N_p}=240\\times\\dfrac{50}{200}=60\\,\\text{V}$." },
  { id: "esat-mk1-p-19", type: "mcq", testId: "esat", topicId: "esat-phys2", difficulty: 3, marks: 1,
    question: "An ideal transformer outputs $12\\,\\text{V}$ at $5\\,\\text{A}$ from its secondary. If the primary voltage is $240\\,\\text{V}$, the primary current is:",
    options: [ {key:"A",text:"$0.1\\,\\text{A}$"},{key:"B",text:"$0.25\\,\\text{A}$"},{key:"C",text:"$2.5\\,\\text{A}$"},{key:"D",text:"$5\\,\\text{A}$"},{key:"E",text:"$10\\,\\text{A}$"} ],
    answer: "B", solution: "$V_pI_p=V_sI_s\\Rightarrow I_p=\\dfrac{12\\times5}{240}=\\dfrac{60}{240}=0.25\\,\\text{A}$." },
  { id: "esat-mk1-p-20", type: "mcq", testId: "esat", topicId: "esat-phys3", difficulty: 1, marks: 1,
    question: "A wave has frequency $250\\,\\text{Hz}$ and wavelength $1.4\\,\\text{m}$. Its speed is:",
    options: [ {key:"A",text:"$175\\,\\text{m s}^{-1}$"},{key:"B",text:"$178\\,\\text{m s}^{-1}$"},{key:"C",text:"$250\\,\\text{m s}^{-1}$"},{key:"D",text:"$350\\,\\text{m s}^{-1}$"},{key:"E",text:"$500\\,\\text{m s}^{-1}$"} ],
    answer: "D", solution: "$v=f\\lambda=250\\times1.4=350\\,\\text{m s}^{-1}$." },
  { id: "esat-mk1-p-21", type: "mcq", testId: "esat", topicId: "esat-phys3", difficulty: 1, marks: 1,
    question: "The period of a $400\\,\\text{Hz}$ wave is:",
    options: [ {key:"A",text:"$0.0025\\,\\text{s}$"},{key:"B",text:"$0.004\\,\\text{s}$"},{key:"C",text:"$0.04\\,\\text{s}$"},{key:"D",text:"$2.5\\,\\text{s}$"},{key:"E",text:"$400\\,\\text{s}$"} ],
    answer: "A", solution: "$T=1/f=1/400=0.0025\\,\\text{s}$." },
  { id: "esat-mk1-p-22", type: "mcq", testId: "esat", topicId: "esat-phys3", difficulty: 3, marks: 1,
    question: "Taking $h=6.6\\times10^{-34}\\,\\text{J s}$, the energy of a photon of frequency $6\\times10^{14}\\,\\text{Hz}$ is approximately:",
    options: [ {key:"A",text:"$4.0\\times10^{-20}\\,\\text{J}$"},{key:"B",text:"$4.0\\times10^{-19}\\,\\text{J}$"},{key:"C",text:"$6.6\\times10^{-19}\\,\\text{J}$"},{key:"D",text:"$4.0\\times10^{-18}\\,\\text{J}$"},{key:"E",text:"$1.1\\times10^{-48}\\,\\text{J}$"} ],
    answer: "B", solution: "$E=hf=(6.6\\times10^{-34})(6\\times10^{14})\\approx3.96\\times10^{-19}\\approx4.0\\times10^{-19}\\,\\text{J}$." },
  { id: "esat-mk1-p-23", type: "mcq", testId: "esat", topicId: "esat-phys3", difficulty: 2, marks: 1,
    question: "In the photoelectric effect, increasing the intensity of light (frequency unchanged) increases:",
    options: [ {key:"A",text:"the maximum kinetic energy of each electron"},{key:"B",text:"the number of electrons emitted per second"},{key:"C",text:"the threshold frequency"},{key:"D",text:"the work function"},{key:"E",text:"nothing — no electrons are emitted"} ],
    answer: "B", solution: "Higher intensity = more photons per second = more electrons per second; the maximum KE depends only on frequency." },
  { id: "esat-mk1-p-24", type: "mcq", testId: "esat", topicId: "esat-phys3", difficulty: 2, marks: 1,
    question: "A source's activity falls from $800\\,\\text{Bq}$ to $50\\,\\text{Bq}$. This is a decrease of how many half-lives?",
    options: [ {key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$4$"},{key:"D",text:"$5$"},{key:"E",text:"$8$"} ],
    answer: "C", solution: "$800\\to400\\to200\\to100\\to50$ — four halvings, so 4 half-lives." },
  { id: "esat-mk1-p-25", type: "mcq", testId: "esat", topicId: "esat-phys3", difficulty: 3, marks: 1,
    question: "Radium-226 ($^{226}_{\\,88}\\text{Ra}$) decays by alpha emission. The daughter nucleus has mass number and atomic number:",
    options: [ {key:"A",text:"$222$ and $86$"},{key:"B",text:"$224$ and $86$"},{key:"C",text:"$222$ and $88$"},{key:"D",text:"$226$ and $86$"},{key:"E",text:"$224$ and $88$"} ],
    answer: "A", solution: "Alpha emission removes 2 protons and 2 neutrons: mass $226-4=222$, atomic number $88-2=86$." },
  { id: "esat-mk1-p-26", type: "mcq", testId: "esat", topicId: "esat-phys3", difficulty: 3, marks: 1,
    question: "Using $E=mc^2$ with $c=3\\times10^{8}\\,\\text{m s}^{-1}$, the energy from converting a mass of $2\\times10^{-4}\\,\\text{kg}$ is:",
    options: [ {key:"A",text:"$6\\times10^{4}\\,\\text{J}$"},{key:"B",text:"$1.8\\times10^{12}\\,\\text{J}$"},{key:"C",text:"$1.8\\times10^{13}\\,\\text{J}$"},{key:"D",text:"$1.8\\times10^{14}\\,\\text{J}$"},{key:"E",text:"$9\\times10^{16}\\,\\text{J}$"} ],
    answer: "C", solution: "$E=mc^2=(2\\times10^{-4})(9\\times10^{16})=1.8\\times10^{13}\\,\\text{J}$." },
  { id: "esat-mk1-p-27", type: "mcq", testId: "esat", topicId: "esat-phys1", difficulty: 2, marks: 1,
    question: "A block slides down a smooth (frictionless) incline of $30^\\circ$ ($g=10$). Its acceleration down the slope is:",
    options: [ {key:"A",text:"$2.5\\,\\text{m s}^{-2}$"},{key:"B",text:"$5\\,\\text{m s}^{-2}$"},{key:"C",text:"$7.5\\,\\text{m s}^{-2}$"},{key:"D",text:"$8.66\\,\\text{m s}^{-2}$"},{key:"E",text:"$10\\,\\text{m s}^{-2}$"} ],
    answer: "B", solution: "$a=g\\sin\\theta=10\\sin30^\\circ=10\\times0.5=5\\,\\text{m s}^{-2}$." },
];
