// ESAT 模拟卷四 —— 数学（模块一）+ 生物（模块二）。
// 全新原创题，与练习题库及模拟卷一、二、三均不重复。全部五选一（A–E）。
// id 前缀 esat-mk4-*。生物方向（自然科学生物/兽医）考生用此卷做完整计时模拟。

import type { MCQQuestion } from "@/lib/tests/questions/types";

// ── 模块一：数学（27 题 / 40 分钟）────────────────────────────────────────
export const ESAT_MK4_MATH: MCQQuestion[] = [
  { id: "esat-mk4-m-01", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 1, marks: 1,
    question: "Solve $4(x-2)=2x+6$.",
    options: [ {key:"A",text:"$x=5$"},{key:"B",text:"$x=7$"},{key:"C",text:"$x=4$"},{key:"D",text:"$x=2$"},{key:"E",text:"$x=-7$"} ],
    answer: "B", solution: "$4x-8=2x+6\\Rightarrow 2x=14\\Rightarrow x=7$." },
  { id: "esat-mk4-m-02", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "The roots of $x^2+2x-15=0$ are:",
    options: [ {key:"A",text:"$3$ and $-5$"},{key:"B",text:"$-3$ and $5$"},{key:"C",text:"$3$ and $5$"},{key:"D",text:"$-3$ and $-5$"},{key:"E",text:"$1$ and $15$"} ],
    answer: "A", solution: "$x^2+2x-15=(x-3)(x+5)=0\\Rightarrow x=3,-5$." },
  { id: "esat-mk4-m-03", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "Simplify $\\dfrac{6x^3}{2x}$.",
    options: [ {key:"A",text:"$3x^2$"},{key:"B",text:"$3x^3$"},{key:"C",text:"$4x^2$"},{key:"D",text:"$3x$"},{key:"E",text:"$12x^2$"} ],
    answer: "A", solution: "$\\dfrac{6}{2}=3$ and $x^{3-1}=x^2$, giving $3x^2$." },
  { id: "esat-mk4-m-04", type: "mcq", testId: "esat", topicId: "esat-math3", difficulty: 2, marks: 1,
    question: "The sum of the first 6 terms of the arithmetic progression $4, 7, 10, \\ldots$ is:",
    options: [ {key:"A",text:"$57$"},{key:"B",text:"$69$"},{key:"C",text:"$72$"},{key:"D",text:"$81$"},{key:"E",text:"$90$"} ],
    answer: "B", solution: "$S_6=\\tfrac{6}{2}[2(4)+5(3)]=3[8+15]=3\\times23=69$." },
  { id: "esat-mk4-m-05", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 2, marks: 1,
    question: "If $y=x^2+5x$, then $\\dfrac{dy}{dx}$ at $x=3$ is:",
    options: [ {key:"A",text:"$6$"},{key:"B",text:"$8$"},{key:"C",text:"$11$"},{key:"D",text:"$14$"},{key:"E",text:"$24$"} ],
    answer: "C", solution: "$\\dfrac{dy}{dx}=2x+5$; at $x=3$: $6+5=11$." },
  { id: "esat-mk4-m-06", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 2, marks: 1,
    question: "Evaluate $\\displaystyle\\int_0^3 (2x+1)\\,dx$.",
    options: [ {key:"A",text:"$9$"},{key:"B",text:"$10$"},{key:"C",text:"$12$"},{key:"D",text:"$15$"},{key:"E",text:"$6$"} ],
    answer: "C", solution: "$[x^2+x]_0^3=9+3=12$." },
  { id: "esat-mk4-m-07", type: "mcq", testId: "esat", topicId: "esat-math3", difficulty: 1, marks: 1,
    question: "The gradient of the line through $(2,1)$ and $(5,10)$ is:",
    options: [ {key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$\\tfrac13$"},{key:"D",text:"$9$"},{key:"E",text:"$\\tfrac12$"} ],
    answer: "B", solution: "$\\dfrac{10-1}{5-2}=\\dfrac{9}{3}=3$." },
  { id: "esat-mk4-m-08", type: "mcq", testId: "esat", topicId: "esat-math3", difficulty: 2, marks: 1,
    question: "For $0^\\circ\\le x\\le360^\\circ$, how many solutions does $\\cos x = -1$ have?",
    options: [ {key:"A",text:"$0$"},{key:"B",text:"$1$"},{key:"C",text:"$2$"},{key:"D",text:"$3$"},{key:"E",text:"$4$"} ],
    answer: "B", solution: "$\\cos x=-1$ only at $x=180^\\circ$ in this range — one solution." },
  { id: "esat-mk4-m-09", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "Rationalise and simplify $\\dfrac{6}{\\sqrt3}$.",
    options: [ {key:"A",text:"$2\\sqrt3$"},{key:"B",text:"$3\\sqrt3$"},{key:"C",text:"$\\sqrt6$"},{key:"D",text:"$6\\sqrt3$"},{key:"E",text:"$2\\sqrt6$"} ],
    answer: "A", solution: "$\\dfrac{6}{\\sqrt3}\\times\\dfrac{\\sqrt3}{\\sqrt3}=\\dfrac{6\\sqrt3}{3}=2\\sqrt3$." },
  { id: "esat-mk4-m-10", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "If $g(x)=x^2-4$, find $g(g(2))$.",
    options: [ {key:"A",text:"$-4$"},{key:"B",text:"$0$"},{key:"C",text:"$4$"},{key:"D",text:"$12$"},{key:"E",text:"$-12$"} ],
    answer: "A", solution: "$g(2)=4-4=0$; $g(0)=0-4=-4$." },
  { id: "esat-mk4-m-11", type: "mcq", testId: "esat", topicId: "esat-math3", difficulty: 3, marks: 1,
    question: "A geometric progression has first term $5$ and common ratio $2$. Its 6th term is:",
    options: [ {key:"A",text:"$80$"},{key:"B",text:"$120$"},{key:"C",text:"$160$"},{key:"D",text:"$320$"},{key:"E",text:"$32$"} ],
    answer: "C", solution: "$a_6=ar^5=5\\times2^5=5\\times32=160$." },
  { id: "esat-mk4-m-12", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "Solve the inequality $\\dfrac{x}{2}+1 \\ge 4$.",
    options: [ {key:"A",text:"$x\\ge3$"},{key:"B",text:"$x\\ge6$"},{key:"C",text:"$x\\ge10$"},{key:"D",text:"$x\\le6$"},{key:"E",text:"$x\\ge8$"} ],
    answer: "B", solution: "$\\dfrac{x}{2}\\ge3\\Rightarrow x\\ge6$." },
  { id: "esat-mk4-m-13", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 3, marks: 1,
    question: "The remainder when $2x^3-x^2+3$ is divided by $(x-1)$ is:",
    options: [ {key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$4$"},{key:"D",text:"$5$"},{key:"E",text:"$6$"} ],
    answer: "C", solution: "Substitute $x=1$: $2-1+3=4$." },
  { id: "esat-mk4-m-14", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "The minimum value of $x^2-10x+30$ is:",
    options: [ {key:"A",text:"$-5$"},{key:"B",text:"$5$"},{key:"C",text:"$30$"},{key:"D",text:"$25$"},{key:"E",text:"$-25$"} ],
    answer: "B", solution: "$(x-5)^2-25+30=(x-5)^2+5$; minimum $=5$." },
  { id: "esat-mk4-m-15", type: "mcq", testId: "esat", topicId: "esat-math3", difficulty: 2, marks: 1,
    question: "A circle has equation $x^2+y^2=49$. Its radius is:",
    options: [ {key:"A",text:"$7$"},{key:"B",text:"$49$"},{key:"C",text:"$\\sqrt7$"},{key:"D",text:"$14$"},{key:"E",text:"$24.5$"} ],
    answer: "A", solution: "$x^2+y^2=r^2\\Rightarrow r=\\sqrt{49}=7$." },
  { id: "esat-mk4-m-16", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 3, marks: 1,
    question: "The tangent to $y=x^2+x$ is parallel to the line $y=5x+2$ at the point where $x=$:",
    options: [ {key:"A",text:"$1$"},{key:"B",text:"$2$"},{key:"C",text:"$3$"},{key:"D",text:"$4$"},{key:"E",text:"$5$"} ],
    answer: "B", solution: "Parallel means equal gradient: $\\dfrac{dy}{dx}=2x+1=5\\Rightarrow x=2$." },
  { id: "esat-mk4-m-17", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 2, marks: 1,
    question: "How many stationary points does $y=x^3-3x^2+1$ have?",
    options: [ {key:"A",text:"$0$"},{key:"B",text:"$1$"},{key:"C",text:"$2$"},{key:"D",text:"$3$"},{key:"E",text:"infinitely many"} ],
    answer: "C", solution: "$\\dfrac{dy}{dx}=3x^2-6x=3x(x-2)=0\\Rightarrow x=0,2$ — two stationary points." },
  { id: "esat-mk4-m-18", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 1, marks: 1,
    question: "The graph of $y=f(x)$ is transformed to $y=f(x-3)$. This is a translation of:",
    options: [ {key:"A",text:"$3$ units right"},{key:"B",text:"$3$ units left"},{key:"C",text:"$3$ units up"},{key:"D",text:"$3$ units down"},{key:"E",text:"a reflection in the $y$-axis"} ],
    answer: "A", solution: "Replacing $x$ with $x-3$ shifts the graph 3 units to the right." },
  { id: "esat-mk4-m-19", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "Solve $|x-4|=10$.",
    options: [ {key:"A",text:"$x=14$ or $x=-6$"},{key:"B",text:"$x=14$ only"},{key:"C",text:"$x=6$ or $x=-14$"},{key:"D",text:"$x=10$ or $x=-4$"},{key:"E",text:"$x=14$ or $x=6$"} ],
    answer: "A", solution: "$x-4=10\\Rightarrow x=14$; $x-4=-10\\Rightarrow x=-6$." },
  { id: "esat-mk4-m-20", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 3, marks: 1,
    question: "Solve $\\log_3(x)=\\log_3 4 + \\log_3 5$.",
    options: [ {key:"A",text:"$x=9$"},{key:"B",text:"$x=20$"},{key:"C",text:"$x=1$"},{key:"D",text:"$x=45$"},{key:"E",text:"$x=\\tfrac{4}{5}$"} ],
    answer: "B", solution: "$\\log_3 4+\\log_3 5=\\log_3 20$, so $x=20$." },
  { id: "esat-mk4-m-21", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 2, marks: 1,
    question: "The area under $y=3x^2$ between $x=0$ and $x=2$ is:",
    options: [ {key:"A",text:"$4$"},{key:"B",text:"$8$"},{key:"C",text:"$12$"},{key:"D",text:"$24$"},{key:"E",text:"$6$"} ],
    answer: "B", solution: "$\\int_0^2 3x^2\\,dx=[x^3]_0^2=8$." },
  { id: "esat-mk4-m-22", type: "mcq", testId: "esat", topicId: "esat-math3", difficulty: 1, marks: 1,
    question: "The exact value of $\\cos 60^\\circ$ is:",
    options: [ {key:"A",text:"$\\tfrac12$"},{key:"B",text:"$\\tfrac{\\sqrt3}{2}$"},{key:"C",text:"$1$"},{key:"D",text:"$0$"},{key:"E",text:"$\\tfrac{\\sqrt2}{2}$"} ],
    answer: "A", solution: "$\\cos 60^\\circ=\\tfrac12$ (a standard exact value)." },
  { id: "esat-mk4-m-23", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 3, marks: 1,
    question: "The constant term in the expansion of $\\left(x+\\dfrac{2}{x}\\right)^2$ is:",
    options: [ {key:"A",text:"$2$"},{key:"B",text:"$4$"},{key:"C",text:"$6$"},{key:"D",text:"$8$"},{key:"E",text:"$1$"} ],
    answer: "B", solution: "$\\left(x+\\tfrac{2}{x}\\right)^2=x^2+2\\cdot x\\cdot\\tfrac{2}{x}+\\tfrac{4}{x^2}=x^2+4+\\tfrac{4}{x^2}$; the constant term is $4$." },
  { id: "esat-mk4-m-24", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 3, marks: 1,
    question: "If $\\alpha,\\beta$ are roots of $x^2-8x+15=0$, the value of $\\alpha\\beta(\\alpha+\\beta)$ is:",
    options: [ {key:"A",text:"$23$"},{key:"B",text:"$120$"},{key:"C",text:"$15$"},{key:"D",text:"$8$"},{key:"E",text:"$60$"} ],
    answer: "B", solution: "$\\alpha+\\beta=8$, $\\alpha\\beta=15$; product $=15\\times8=120$." },
  { id: "esat-mk4-m-25", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 3, marks: 1,
    question: "A particle's displacement is $s=t^3-3t$ m. Its acceleration at $t=2\\,\\text{s}$ is:",
    options: [ {key:"A",text:"$6\\,\\text{m s}^{-2}$"},{key:"B",text:"$9\\,\\text{m s}^{-2}$"},{key:"C",text:"$12\\,\\text{m s}^{-2}$"},{key:"D",text:"$3\\,\\text{m s}^{-2}$"},{key:"E",text:"$24\\,\\text{m s}^{-2}$"} ],
    answer: "C", solution: "$v=3t^2-3$, $a=\\dfrac{dv}{dt}=6t$; at $t=2$: $12\\,\\text{m s}^{-2}$." },
  { id: "esat-mk4-m-26", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "Simplify $\\dfrac{1}{2}+\\dfrac{1}{3}$.",
    options: [ {key:"A",text:"$\\tfrac{2}{5}$"},{key:"B",text:"$\\tfrac{5}{6}$"},{key:"C",text:"$\\tfrac{1}{6}$"},{key:"D",text:"$\\tfrac{2}{6}$"},{key:"E",text:"$\\tfrac{1}{5}$"} ],
    answer: "B", solution: "Common denominator 6: $\\tfrac{3}{6}+\\tfrac{2}{6}=\\tfrac{5}{6}$." },
  { id: "esat-mk4-m-27", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "For what value of $k$ does $x^2-6x+k=0$ have exactly one (repeated) root?",
    options: [ {key:"A",text:"$3$"},{key:"B",text:"$6$"},{key:"C",text:"$9$"},{key:"D",text:"$12$"},{key:"E",text:"$36$"} ],
    answer: "C", solution: "Repeated root needs discriminant $0$: $36-4k=0\\Rightarrow k=9$." },
];

// ── 模块二：生物（27 题 / 40 分钟）—— 五选一 ─────────────────────────────
export const ESAT_MK4_BIO: MCQQuestion[] = [
  { id: "esat-mk4-b-01", type: "mcq", testId: "esat", topicId: "esat-bio1", difficulty: 1, marks: 1,
    question: "Which organelle is the main site of ATP production by aerobic respiration?",
    options: [ {key:"A",text:"Nucleus"},{key:"B",text:"Mitochondrion"},{key:"C",text:"Ribosome"},{key:"D",text:"Golgi apparatus"},{key:"E",text:"Lysosome"} ],
    answer: "B", solution: "The mitochondrion carries out oxidative phosphorylation on its inner membrane, producing most of the cell's ATP." },
  { id: "esat-mk4-b-02", type: "mcq", testId: "esat", topicId: "esat-bio1", difficulty: 2, marks: 1,
    question: "Which feature is found in a prokaryotic cell but NOT a eukaryotic cell?",
    options: [ {key:"A",text:"A membrane-bound nucleus"},{key:"B",text:"Mitochondria"},{key:"C",text:"A cell wall containing peptidoglycan"},{key:"D",text:"Endoplasmic reticulum"},{key:"E",text:"A Golgi apparatus"} ],
    answer: "C", solution: "Bacterial (prokaryotic) cell walls contain peptidoglycan; prokaryotes lack a true nucleus and membrane-bound organelles." },
  { id: "esat-mk4-b-03", type: "mcq", testId: "esat", topicId: "esat-bio1", difficulty: 2, marks: 1,
    question: "Movement of water across a partially permeable membrane from high to low water potential is called:",
    options: [ {key:"A",text:"Active transport"},{key:"B",text:"Osmosis"},{key:"C",text:"Facilitated diffusion of ions"},{key:"D",text:"Exocytosis"},{key:"E",text:"Phagocytosis"} ],
    answer: "B", solution: "Osmosis is the net diffusion of water across a partially permeable membrane down a water-potential gradient." },
  { id: "esat-mk4-b-04", type: "mcq", testId: "esat", topicId: "esat-bio1", difficulty: 3, marks: 1,
    question: "Which process requires ATP because it moves substances against a concentration gradient?",
    options: [ {key:"A",text:"Simple diffusion"},{key:"B",text:"Osmosis"},{key:"C",text:"Facilitated diffusion"},{key:"D",text:"Active transport"},{key:"E",text:"Evaporation"} ],
    answer: "D", solution: "Active transport uses carrier proteins and energy from ATP to move substances against (up) their concentration gradient." },
  { id: "esat-mk4-b-05", type: "mcq", testId: "esat", topicId: "esat-bio1", difficulty: 2, marks: 1,
    question: "Enzymes speed up reactions by:",
    options: [ {key:"A",text:"increasing the activation energy"},{key:"B",text:"lowering the activation energy"},{key:"C",text:"raising the temperature of the cell"},{key:"D",text:"changing the products formed"},{key:"E",text:"being used up in the reaction"} ],
    answer: "B", solution: "Enzymes are catalysts that provide an alternative pathway with a lower activation energy; they are not used up." },
  { id: "esat-mk4-b-06", type: "mcq", testId: "esat", topicId: "esat-bio1", difficulty: 3, marks: 1,
    question: "Above its optimum temperature, an enzyme's activity falls sharply mainly because:",
    options: [ {key:"A",text:"the substrate is destroyed"},{key:"B",text:"the enzyme denatures, changing the active site's shape"},{key:"C",text:"the pH always rises"},{key:"D",text:"more enzyme is produced"},{key:"E",text:"diffusion stops completely"} ],
    answer: "B", solution: "High temperature breaks the bonds holding the enzyme's tertiary structure, denaturing it so the active site no longer fits the substrate." },
  { id: "esat-mk4-b-07", type: "mcq", testId: "esat", topicId: "esat-bio1", difficulty: 2, marks: 1,
    question: "In DNA, which bases pair together?",
    options: [ {key:"A",text:"A–G and C–T"},{key:"B",text:"A–T and C–G"},{key:"C",text:"A–C and G–T"},{key:"D",text:"A–U and C–G"},{key:"E",text:"A–A and G–G"} ],
    answer: "B", solution: "Complementary base pairing: adenine with thymine (A–T), cytosine with guanine (C–G)." },
  { id: "esat-mk4-b-08", type: "mcq", testId: "esat", topicId: "esat-bio1", difficulty: 3, marks: 1,
    question: "A length of mRNA contains 90 nucleotides. The maximum number of amino acids it could code for is:",
    options: [ {key:"A",text:"30"},{key:"B",text:"45"},{key:"C",text:"90"},{key:"D",text:"180"},{key:"E",text:"270"} ],
    answer: "A", solution: "Each amino acid is coded by a triplet (codon) of 3 nucleotides: $90\\div3=30$." },
  { id: "esat-mk4-b-09", type: "mcq", testId: "esat", topicId: "esat-bio1", difficulty: 2, marks: 1,
    question: "Which process produces two genetically identical diploid cells for growth and repair?",
    options: [ {key:"A",text:"Meiosis"},{key:"B",text:"Mitosis"},{key:"C",text:"Fertilisation"},{key:"D",text:"Translation"},{key:"E",text:"Binary fission only"} ],
    answer: "B", solution: "Mitosis produces two diploid daughter cells genetically identical to the parent, used in growth and repair." },
  { id: "esat-mk4-b-10", type: "mcq", testId: "esat", topicId: "esat-bio2", difficulty: 1, marks: 1,
    question: "A cross between two heterozygotes (Bb × Bb) gives an expected phenotype ratio of:",
    options: [ {key:"A",text:"1 : 1"},{key:"B",text:"3 : 1"},{key:"C",text:"9 : 3 : 3 : 1"},{key:"D",text:"1 : 2 : 1"},{key:"E",text:"2 : 1"} ],
    answer: "B", solution: "Bb × Bb gives 3 dominant : 1 recessive in the offspring phenotypes." },
  { id: "esat-mk4-b-11", type: "mcq", testId: "esat", topicId: "esat-bio2", difficulty: 3, marks: 1,
    question: "Two carriers of a recessive allele (Aa) have a child. The probability the child is a carrier (Aa) is:",
    options: [ {key:"A",text:"1/4"},{key:"B",text:"1/2"},{key:"C",text:"3/4"},{key:"D",text:"1"},{key:"E",text:"1/3"} ],
    answer: "B", solution: "Aa × Aa gives 1 AA : 2 Aa : 1 aa, so the probability of Aa (carrier) is 2/4 = 1/2." },
  { id: "esat-mk4-b-12", type: "mcq", testId: "esat", topicId: "esat-bio2", difficulty: 2, marks: 1,
    question: "In humans, a male's sex chromosomes are XY. From which parent does a son inherit his Y chromosome?",
    options: [ {key:"A",text:"His mother"},{key:"B",text:"His father"},{key:"C",text:"Either parent equally"},{key:"D",text:"Neither — it is new"},{key:"E",text:"Both parents"} ],
    answer: "B", solution: "A son inherits his X from his mother and his Y from his father (so the father determines the sex)." },
  { id: "esat-mk4-b-13", type: "mcq", testId: "esat", topicId: "esat-bio2", difficulty: 2, marks: 1,
    question: "Which is a source of genetic variation unique to sexual reproduction (meiosis and fertilisation)?",
    options: [ {key:"A",text:"DNA replication errors only"},{key:"B",text:"Crossing over and independent assortment"},{key:"C",text:"Mitosis"},{key:"D",text:"Diffusion of gametes"},{key:"E",text:"Active transport"} ],
    answer: "B", solution: "Crossing over and independent assortment in meiosis, plus random fertilisation, generate genetic variation in sexual reproduction." },
  { id: "esat-mk4-b-14", type: "mcq", testId: "esat", topicId: "esat-bio2", difficulty: 3, marks: 1,
    question: "A recessive genetic condition affects 1 in 400 people in a population in Hardy–Weinberg equilibrium. The frequency of the recessive allele (q) is:",
    options: [ {key:"A",text:"0.0025"},{key:"B",text:"0.05"},{key:"C",text:"0.5"},{key:"D",text:"0.1"},{key:"E",text:"0.95"} ],
    answer: "B", solution: "$q^2=\\tfrac{1}{400}=0.0025\\Rightarrow q=\\sqrt{0.0025}=0.05$." },
  { id: "esat-mk4-b-15", type: "mcq", testId: "esat", topicId: "esat-bio2", difficulty: 2, marks: 1,
    question: "The increasing frequency of antibiotic resistance in bacteria is an example of:",
    options: [ {key:"A",text:"natural selection"},{key:"B",text:"meiosis"},{key:"C",text:"active transport"},{key:"D",text:"osmosis"},{key:"E",text:"genetic engineering"} ],
    answer: "A", solution: "Resistant bacteria survive and reproduce more, so the resistance allele increases in frequency over generations — natural selection." },
  { id: "esat-mk4-b-16", type: "mcq", testId: "esat", topicId: "esat-bio2", difficulty: 3, marks: 1,
    question: "A red-flowered plant (RR) is crossed with a white-flowered plant (rr); all offspring are pink. This is an example of:",
    options: [ {key:"A",text:"complete dominance"},{key:"B",text:"incomplete dominance"},{key:"C",text:"sex linkage"},{key:"D",text:"a mutation"},{key:"E",text:"epistasis"} ],
    answer: "B", solution: "Heterozygotes (Rr) showing an intermediate (pink) phenotype indicates incomplete dominance." },
  { id: "esat-mk4-b-17", type: "mcq", testId: "esat", topicId: "esat-bio3", difficulty: 1, marks: 1,
    question: "The word equation for aerobic respiration is glucose + oxygen →:",
    options: [ {key:"A",text:"carbon dioxide + water"},{key:"B",text:"lactic acid only"},{key:"C",text:"ethanol + carbon dioxide"},{key:"D",text:"glucose + oxygen"},{key:"E",text:"starch + water"} ],
    answer: "A", solution: "Aerobic respiration: glucose + oxygen → carbon dioxide + water (+ energy/ATP)." },
  { id: "esat-mk4-b-18", type: "mcq", testId: "esat", topicId: "esat-bio3", difficulty: 2, marks: 1,
    question: "In photosynthesis, the oxygen released comes from:",
    options: [ {key:"A",text:"carbon dioxide"},{key:"B",text:"glucose"},{key:"C",text:"water (photolysis)"},{key:"D",text:"the chlorophyll"},{key:"E",text:"the soil"} ],
    answer: "C", solution: "The oxygen evolved in photosynthesis comes from the light-driven splitting (photolysis) of water, not from CO₂." },
  { id: "esat-mk4-b-19", type: "mcq", testId: "esat", topicId: "esat-bio3", difficulty: 3, marks: 1,
    question: "Producers in a grassland fix $50000\\,\\text{kJ m}^{-2}\\text{yr}^{-1}$. Assuming 10% energy transfer per trophic level, the energy reaching primary consumers is:",
    options: [ {key:"A",text:"$50\\,\\text{kJ m}^{-2}\\text{yr}^{-1}$"},{key:"B",text:"$500\\,\\text{kJ m}^{-2}\\text{yr}^{-1}$"},{key:"C",text:"$5000\\,\\text{kJ m}^{-2}\\text{yr}^{-1}$"},{key:"D",text:"$500000\\,\\text{kJ m}^{-2}\\text{yr}^{-1}$"},{key:"E",text:"$25000\\,\\text{kJ m}^{-2}\\text{yr}^{-1}$"} ],
    answer: "C", solution: "Primary consumers receive 10% of the producers' energy: $50000\\times0.1=5000\\,\\text{kJ m}^{-2}\\text{yr}^{-1}$." },
  { id: "esat-mk4-b-20", type: "mcq", testId: "esat", topicId: "esat-bio3", difficulty: 2, marks: 1,
    question: "Which adaptation does NOT help gas exchange in the alveoli?",
    options: [ {key:"A",text:"Large surface area"},{key:"B",text:"Thin (one-cell) walls"},{key:"C",text:"A rich blood supply"},{key:"D",text:"A thick, waterproof covering"},{key:"E",text:"A moist surface"} ],
    answer: "D", solution: "Efficient exchange needs a large, thin, moist, well-supplied surface; a thick waterproof covering would increase diffusion distance and reduce exchange." },
  { id: "esat-mk4-b-21", type: "mcq", testId: "esat", topicId: "esat-bio3", difficulty: 2, marks: 1,
    question: "After a meal raises blood glucose, the pancreas releases insulin, which causes the liver to:",
    options: [ {key:"A",text:"convert glycogen to glucose"},{key:"B",text:"convert glucose to glycogen"},{key:"C",text:"release glucagon"},{key:"D",text:"stop respiring"},{key:"E",text:"break down proteins"} ],
    answer: "B", solution: "Insulin promotes uptake of glucose and its conversion to glycogen in the liver, lowering blood glucose — a negative-feedback response." },
  { id: "esat-mk4-b-22", type: "mcq", testId: "esat", topicId: "esat-bio3", difficulty: 2, marks: 1,
    question: "Keeping the body's internal conditions (e.g. temperature, blood glucose) stable is called:",
    options: [ {key:"A",text:"homeostasis"},{key:"B",text:"osmosis"},{key:"C",text:"respiration"},{key:"D",text:"transcription"},{key:"E",text:"diffusion"} ],
    answer: "A", solution: "Homeostasis is the maintenance of a stable internal environment, typically by negative feedback." },
  { id: "esat-mk4-b-23", type: "mcq", testId: "esat", topicId: "esat-bio3", difficulty: 1, marks: 1,
    question: "In a synapse, transmission occurs in one direction only because:",
    options: [ {key:"A",text:"neurotransmitter is released only from the presynaptic membrane and receptors are only on the postsynaptic membrane"},{key:"B",text:"the axon is myelinated"},{key:"C",text:"the synapse is very wide"},{key:"D",text:"impulses are electrical across the gap"},{key:"E",text:"there is no neurotransmitter involved"} ],
    answer: "A", solution: "Vesicles of neurotransmitter are only in the presynaptic neurone and receptors only on the postsynaptic membrane, so transmission is unidirectional." },
  { id: "esat-mk4-b-24", type: "mcq", testId: "esat", topicId: "esat-bio3", difficulty: 3, marks: 1,
    question: "Anaerobic respiration in human muscle cells produces:",
    options: [ {key:"A",text:"carbon dioxide and water"},{key:"B",text:"lactic acid"},{key:"C",text:"ethanol and carbon dioxide"},{key:"D",text:"glucose and oxygen"},{key:"E",text:"starch"} ],
    answer: "B", solution: "In humans, anaerobic respiration converts glucose to lactic acid, releasing a small amount of energy without oxygen." },
  { id: "esat-mk4-b-25", type: "mcq", testId: "esat", topicId: "esat-bio1", difficulty: 2, marks: 1,
    question: "An object measured under the microscope appears $8\\,\\text{mm}$ long at a magnification of ×500. Its actual length is:",
    options: [ {key:"A",text:"$1.6\\,\\mu\\text{m}$"},{key:"B",text:"$16\\,\\mu\\text{m}$"},{key:"C",text:"$160\\,\\mu\\text{m}$"},{key:"D",text:"$4000\\,\\mu\\text{m}$"},{key:"E",text:"$0.16\\,\\mu\\text{m}$"} ],
    answer: "B", solution: "Actual size = image ÷ magnification = $8\\,\\text{mm}\\div500=0.016\\,\\text{mm}=16\\,\\mu\\text{m}$." },
  { id: "esat-mk4-b-26", type: "mcq", testId: "esat", topicId: "esat-bio2", difficulty: 3, marks: 1,
    question: "Two parents have blood groups $I^A i$ (group A) and $I^B i$ (group B). Which blood group is NOT possible in their children?",
    options: [ {key:"A",text:"A"},{key:"B",text:"B"},{key:"C",text:"AB"},{key:"D",text:"O"},{key:"E",text:"all four are possible"} ],
    answer: "E", solution: "The cross $I^A i \\times I^B i$ gives $I^A I^B$ (AB), $I^A i$ (A), $I^B i$ (B) and $ii$ (O) — all four groups are possible." },
  { id: "esat-mk4-b-27", type: "mcq", testId: "esat", topicId: "esat-bio3", difficulty: 2, marks: 1,
    question: "In a food chain, roughly what percentage of energy is typically transferred from one trophic level to the next?",
    options: [ {key:"A",text:"1%"},{key:"B",text:"10%"},{key:"C",text:"50%"},{key:"D",text:"90%"},{key:"E",text:"100%"} ],
    answer: "B", solution: "Only about 10% of the energy is passed on; the rest is lost mainly as heat from respiration, in movement and in undigested material." },
];
