// ESAT 模拟卷三 —— 数学（模块一）+ 化学（模块二）。
// 全新原创题，与练习题库及模拟卷一、二均不重复。全部五选一（A–E）。
// id 前缀 esat-mk3-*。化学方向考生用此卷做完整计时模拟。

import type { MCQQuestion } from "@/lib/tests/questions/types";

// ── 模块一：数学（27 题 / 40 分钟）────────────────────────────────────────
export const ESAT_MK3_MATH: MCQQuestion[] = [
  { id: "esat-mk3-m-01", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 1, marks: 1,
    question: "Solve $5x-3=2x+9$.",
    options: [ {key:"A",text:"$x=2$"},{key:"B",text:"$x=3$"},{key:"C",text:"$x=4$"},{key:"D",text:"$x=6$"},{key:"E",text:"$x=-4$"} ],
    answer: "C", solution: "$5x-2x=9+3\\Rightarrow 3x=12\\Rightarrow x=4$." },
  { id: "esat-mk3-m-02", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "The roots of $x^2-7x+12=0$ are:",
    options: [ {key:"A",text:"$2$ and $6$"},{key:"B",text:"$3$ and $4$"},{key:"C",text:"$-3$ and $-4$"},{key:"D",text:"$1$ and $12$"},{key:"E",text:"$2$ and $5$"} ],
    answer: "B", solution: "$x^2-7x+12=(x-3)(x-4)=0\\Rightarrow x=3,4$." },
  { id: "esat-mk3-m-03", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "Simplify $\\dfrac{x^2-9}{x-3}$ (for $x\\neq3$).",
    options: [ {key:"A",text:"$x-3$"},{key:"B",text:"$x+3$"},{key:"C",text:"$x^2-3$"},{key:"D",text:"$3$"},{key:"E",text:"$x-9$"} ],
    answer: "B", solution: "$\\dfrac{(x-3)(x+3)}{x-3}=x+3$." },
  { id: "esat-mk3-m-04", type: "mcq", testId: "esat", topicId: "esat-math3", difficulty: 2, marks: 1,
    question: "The 8th term of the arithmetic progression $2, 5, 8, \\ldots$ is:",
    options: [ {key:"A",text:"$21$"},{key:"B",text:"$23$"},{key:"C",text:"$24$"},{key:"D",text:"$26$"},{key:"E",text:"$29$"} ],
    answer: "B", solution: "$a_8=2+(8-1)(3)=2+21=23$." },
  { id: "esat-mk3-m-05", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 2, marks: 1,
    question: "If $y=2x^3-x$, then $\\dfrac{dy}{dx}$ at $x=2$ is:",
    options: [ {key:"A",text:"$11$"},{key:"B",text:"$15$"},{key:"C",text:"$23$"},{key:"D",text:"$24$"},{key:"E",text:"$5$"} ],
    answer: "C", solution: "$\\dfrac{dy}{dx}=6x^2-1$; at $x=2$: $24-1=23$." },
  { id: "esat-mk3-m-06", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 2, marks: 1,
    question: "What is the area bounded by $y=2x+3$, the $x$-axis, and the lines $x=0$ and $x=2$?",
    options: [ {key:"A",text:"$6$"},{key:"B",text:"$8$"},{key:"C",text:"$10$"},{key:"D",text:"$12$"},{key:"E",text:"$14$"} ],
    answer: "C", solution: "The area is $\\int_0^2(2x+3)\\,dx=[x^2+3x]_0^2=10$." },
  { id: "esat-mk3-m-07", type: "mcq", testId: "esat", topicId: "esat-math3", difficulty: 2, marks: 1,
    question: "The midpoint of the segment joining $(-2,5)$ and $(4,1)$ is:",
    options: [ {key:"A",text:"$(1,3)$"},{key:"B",text:"$(2,6)$"},{key:"C",text:"$(3,2)$"},{key:"D",text:"$(1,2)$"},{key:"E",text:"$(6,4)$"} ],
    answer: "A", solution: "$\\left(\\dfrac{-2+4}{2},\\dfrac{5+1}{2}\\right)=(1,3)$." },
  { id: "esat-mk3-m-08", type: "mcq", testId: "esat", topicId: "esat-math3", difficulty: 3, marks: 1,
    question: "For $0^\\circ\\le x\\le360^\\circ$, the solutions of $\\tan x = 1$ are:",
    options: [ {key:"A",text:"$45^\\circ$ only"},{key:"B",text:"$45^\\circ$ and $135^\\circ$"},{key:"C",text:"$45^\\circ$ and $225^\\circ$"},{key:"D",text:"$135^\\circ$ and $315^\\circ$"},{key:"E",text:"$45^\\circ$ and $315^\\circ$"} ],
    answer: "C", solution: "$\\tan$ is positive in the 1st and 3rd quadrants: $x=45^\\circ$ and $45^\\circ+180^\\circ=225^\\circ$." },
  { id: "esat-mk3-m-09", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "Express $\\sqrt{12}+\\sqrt{27}$ in simplest surd form.",
    options: [ {key:"A",text:"$5\\sqrt{3}$"},{key:"B",text:"$\\sqrt{39}$"},{key:"C",text:"$6\\sqrt{3}$"},{key:"D",text:"$13\\sqrt{3}$"},{key:"E",text:"$5\\sqrt{6}$"} ],
    answer: "A", solution: "$\\sqrt{12}=2\\sqrt3$, $\\sqrt{27}=3\\sqrt3$; sum $=5\\sqrt3$." },
  { id: "esat-mk3-m-10", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "If $f(x)=2x-5$, solve $f(x)=11$.",
    options: [ {key:"A",text:"$x=3$"},{key:"B",text:"$x=8$"},{key:"C",text:"$x=17$"},{key:"D",text:"$x=6$"},{key:"E",text:"$x=2.5$"} ],
    answer: "B", solution: "$2x-5=11\\Rightarrow 2x=16\\Rightarrow x=8$." },
  { id: "esat-mk3-m-11", type: "mcq", testId: "esat", topicId: "esat-math3", difficulty: 3, marks: 1,
    question: "The sum to infinity of $16 + 4 + 1 + \\cdots$ is:",
    options: [ {key:"A",text:"$\\tfrac{64}{3}$"},{key:"B",text:"$20$"},{key:"C",text:"$21$"},{key:"D",text:"$24$"},{key:"E",text:"$32$"} ],
    answer: "A", solution: "$a=16,r=\\tfrac14$: $S_\\infty=\\dfrac{16}{1-\\tfrac14}=\\dfrac{16}{3/4}=\\dfrac{64}{3}$." },
  { id: "esat-mk3-m-12", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "Solve $2x^2-8=0$.",
    options: [ {key:"A",text:"$x=\\pm2$"},{key:"B",text:"$x=\\pm4$"},{key:"C",text:"$x=2$ only"},{key:"D",text:"$x=\\pm\\sqrt2$"},{key:"E",text:"$x=\\pm8$"} ],
    answer: "A", solution: "$2x^2=8\\Rightarrow x^2=4\\Rightarrow x=\\pm2$." },
  { id: "esat-mk3-m-13", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 3, marks: 1,
    question: "Given $(x-1)$ is a factor of $2x^3-3x^2+ax-1$, the value of $a$ is:",
    options: [ {key:"A",text:"$1$"},{key:"B",text:"$2$"},{key:"C",text:"$3$"},{key:"D",text:"$4$"},{key:"E",text:"$0$"} ],
    answer: "B", solution: "$f(1)=2-3+a-1=a-2=0\\Rightarrow a=2$." },
  { id: "esat-mk3-m-14", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "Write $x^2-6x+11$ in completed-square form.",
    options: [ {key:"A",text:"$(x-3)^2+2$"},{key:"B",text:"$(x-3)^2-2$"},{key:"C",text:"$(x-6)^2+11$"},{key:"D",text:"$(x+3)^2+2$"},{key:"E",text:"$(x-3)^2+11$"} ],
    answer: "A", solution: "$(x-3)^2-9+11=(x-3)^2+2$." },
  { id: "esat-mk3-m-15", type: "mcq", testId: "esat", topicId: "esat-math3", difficulty: 2, marks: 1,
    question: "A line has equation $2y=6x-4$. Its gradient is:",
    options: [ {key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$6$"},{key:"D",text:"$-2$"},{key:"E",text:"$\\tfrac12$"} ],
    answer: "B", solution: "Rearrange: $y=3x-2$, so the gradient is $3$." },
  { id: "esat-mk3-m-16", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 3, marks: 1,
    question: "The curve $y=x^2-2x+3$ has a tangent of gradient $4$ at the point where $x=$:",
    options: [ {key:"A",text:"$1$"},{key:"B",text:"$2$"},{key:"C",text:"$3$"},{key:"D",text:"$4$"},{key:"E",text:"$-3$"} ],
    answer: "C", solution: "$\\dfrac{dy}{dx}=2x-2=4\\Rightarrow x=3$." },
  { id: "esat-mk3-m-17", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 3, marks: 1,
    question: "The curve $y=x^3-12x$ has a local maximum at $x=$:",
    options: [ {key:"A",text:"$2$"},{key:"B",text:"$-2$"},{key:"C",text:"$0$"},{key:"D",text:"$4$"},{key:"E",text:"$-4$"} ],
    answer: "B", solution: "$\\dfrac{dy}{dx}=3x^2-12=0\\Rightarrow x=\\pm2$. $\\dfrac{d^2y}{dx^2}=6x$; at $x=-2$ it is $-12<0$, a maximum." },
  { id: "esat-mk3-m-18", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 1, marks: 1,
    question: "The graph of $y=f(x)$ is transformed to $y=-f(x)$. This is a reflection in the:",
    options: [ {key:"A",text:"$x$-axis"},{key:"B",text:"$y$-axis"},{key:"C",text:"line $y=x$"},{key:"D",text:"origin"},{key:"E",text:"line $x=1$"} ],
    answer: "A", solution: "Negating the output reflects the graph in the $x$-axis." },
  { id: "esat-mk3-m-19", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "Solve $|2x-3|=7$.",
    options: [ {key:"A",text:"$x=5$ or $x=-2$"},{key:"B",text:"$x=5$ only"},{key:"C",text:"$x=2$ or $x=-5$"},{key:"D",text:"$x=4$ or $x=-2$"},{key:"E",text:"$x=5$ or $x=2$"} ],
    answer: "A", solution: "$2x-3=7\\Rightarrow x=5$; $2x-3=-7\\Rightarrow x=-2$." },
  { id: "esat-mk3-m-20", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "Evaluate $\\log_2 32$.",
    options: [ {key:"A",text:"$4$"},{key:"B",text:"$5$"},{key:"C",text:"$6$"},{key:"D",text:"$16$"},{key:"E",text:"$2$"} ],
    answer: "B", solution: "$2^5=32$, so $\\log_2 32=5$." },
  { id: "esat-mk3-m-21", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 3, marks: 1,
    question: "The area enclosed between the curve $y=x^2$ and the line $y=4$ is:",
    options: [ {key:"A",text:"$\\tfrac{16}{3}$"},{key:"B",text:"$\\tfrac{32}{3}$"},{key:"C",text:"$8$"},{key:"D",text:"$16$"},{key:"E",text:"$\\tfrac{64}{3}$"} ],
    answer: "B", solution: "Curve meets line at $x=\\pm2$. Area $=\\int_{-2}^{2}(4-x^2)\\,dx=\\left[4x-\\tfrac{x^3}{3}\\right]_{-2}^{2}=\\left(8-\\tfrac83\\right)-\\left(-8+\\tfrac83\\right)=\\tfrac{32}{3}$." },
  { id: "esat-mk3-m-22", type: "mcq", testId: "esat", topicId: "esat-math3", difficulty: 2, marks: 1,
    question: "Evaluate $\\sin^2 60^\\circ + \\cos^2 60^\\circ$.",
    options: [ {key:"A",text:"$0$"},{key:"B",text:"$\\tfrac12$"},{key:"C",text:"$1$"},{key:"D",text:"$\\tfrac{\\sqrt3}{2}$"},{key:"E",text:"$2$"} ],
    answer: "C", solution: "By the identity $\\sin^2\\theta+\\cos^2\\theta=1$ for any $\\theta$." },
  { id: "esat-mk3-m-23", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 3, marks: 1,
    question: "The coefficient of $x^3$ in $(1+x)^6$ is:",
    options: [ {key:"A",text:"$6$"},{key:"B",text:"$15$"},{key:"C",text:"$20$"},{key:"D",text:"$30$"},{key:"E",text:"$64$"} ],
    answer: "C", solution: "$\\binom{6}{3}=\\dfrac{6\\times5\\times4}{3\\times2\\times1}=20$." },
  { id: "esat-mk3-m-24", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 3, marks: 1,
    question: "If the roots of $x^2+bx+c=0$ are $-2$ and $5$, then $b$ and $c$ are:",
    options: [ {key:"A",text:"$b=-3,\\ c=-10$"},{key:"B",text:"$b=3,\\ c=-10$"},{key:"C",text:"$b=-3,\\ c=10$"},{key:"D",text:"$b=3,\\ c=10$"},{key:"E",text:"$b=7,\\ c=-10$"} ],
    answer: "A", solution: "Sum of roots $=-2+5=3=-b\\Rightarrow b=-3$; product $=-10=c$." },
  { id: "esat-mk3-m-25", type: "mcq", testId: "esat", topicId: "esat-math2", difficulty: 2, marks: 1,
    question: "A particle's displacement is $s=2t^2-3t$ m. Its velocity at $t=2\\,\\text{s}$ is:",
    options: [ {key:"A",text:"$2\\,\\text{m s}^{-1}$"},{key:"B",text:"$5\\,\\text{m s}^{-1}$"},{key:"C",text:"$8\\,\\text{m s}^{-1}$"},{key:"D",text:"$11\\,\\text{m s}^{-1}$"},{key:"E",text:"$1\\,\\text{m s}^{-1}$"} ],
    answer: "B", solution: "$v=\\dfrac{ds}{dt}=4t-3$; at $t=2$: $8-3=5\\,\\text{m s}^{-1}$." },
  { id: "esat-mk3-m-26", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 2, marks: 1,
    question: "Solve the inequality $3x+2 < x+10$.",
    options: [ {key:"A",text:"$x<4$"},{key:"B",text:"$x>4$"},{key:"C",text:"$x<6$"},{key:"D",text:"$x>6$"},{key:"E",text:"$x<3$"} ],
    answer: "A", solution: "$3x-x<10-2\\Rightarrow 2x<8\\Rightarrow x<4$." },
  { id: "esat-mk3-m-27", type: "mcq", testId: "esat", topicId: "esat-math1", difficulty: 1, marks: 1,
    question: "Simplify $(3x^2y)(4xy^3)$.",
    options: [ {key:"A",text:"$7x^3y^4$"},{key:"B",text:"$12x^2y^3$"},{key:"C",text:"$12x^3y^4$"},{key:"D",text:"$12x^3y^3$"},{key:"E",text:"$7x^2y^4$"} ],
    answer: "C", solution: "$3\\times4=12$; $x^{2+1}=x^3$; $y^{1+3}=y^4$, giving $12x^3y^4$." },
];

// ── 模块二：化学（27 题 / 40 分钟）—— 五选一 ─────────────────────────────
export const ESAT_MK3_CHEM: MCQQuestion[] = [
  { id: "esat-mk3-c-01", type: "mcq", testId: "esat", topicId: "esat-chem1", difficulty: 1, marks: 1,
    question: "How many protons, neutrons and electrons are in a neutral atom of $^{19}_{\\,9}\\text{F}$?",
    options: [ {key:"A",text:"9 p, 9 n, 9 e"},{key:"B",text:"9 p, 10 n, 9 e"},{key:"C",text:"9 p, 19 n, 9 e"},{key:"D",text:"10 p, 9 n, 10 e"},{key:"E",text:"19 p, 9 n, 19 e"} ],
    answer: "B", solution: "Protons = atomic number = 9; neutrons = 19−9 = 10; a neutral atom has 9 electrons." },
  { id: "esat-mk3-c-02", type: "mcq", testId: "esat", topicId: "esat-chem1", difficulty: 2, marks: 1,
    question: "The electron configuration of a chlorine atom (atomic number 17) is:",
    options: [ {key:"A",text:"1s² 2s² 2p⁶ 3s² 3p⁵"},{key:"B",text:"1s² 2s² 2p⁶ 3s² 3p⁶"},{key:"C",text:"1s² 2s² 2p⁶ 3s² 3p³"},{key:"D",text:"1s² 2s² 2p⁹ 3s⁶"},{key:"E",text:"1s² 2s² 2p⁶ 3p⁷"} ],
    answer: "A", solution: "17 electrons: 2+2+6+2+5 = 17, ending 3p⁵." },
  { id: "esat-mk3-c-03", type: "mcq", testId: "esat", topicId: "esat-chem1", difficulty: 2, marks: 1,
    question: "Which type of bonding holds the compound magnesium oxide (MgO) together?",
    options: [ {key:"A",text:"Covalent"},{key:"B",text:"Ionic"},{key:"C",text:"Metallic"},{key:"D",text:"Hydrogen bonding"},{key:"E",text:"Van der Waals forces"} ],
    answer: "B", solution: "A metal (Mg) with a non-metal (O), formed by electron transfer (Mg²⁺ and O²⁻) — ionic bonding." },
  { id: "esat-mk3-c-04", type: "mcq", testId: "esat", topicId: "esat-chem1", difficulty: 2, marks: 1,
    question: "What is the shape of a $\\text{BF}_3$ molecule (3 bonding pairs, no lone pairs on boron)?",
    options: [ {key:"A",text:"Linear"},{key:"B",text:"Bent"},{key:"C",text:"Trigonal planar"},{key:"D",text:"Tetrahedral"},{key:"E",text:"Trigonal pyramidal"} ],
    answer: "C", solution: "Three bonding pairs and no lone pairs spread to 120° in a plane — trigonal planar." },
  { id: "esat-mk3-c-05", type: "mcq", testId: "esat", topicId: "esat-chem1", difficulty: 3, marks: 1,
    question: "Which molecule is non-polar overall despite containing polar bonds?",
    options: [ {key:"A",text:"H₂O"},{key:"B",text:"NH₃"},{key:"C",text:"HCl"},{key:"D",text:"CO₂"},{key:"E",text:"HF"} ],
    answer: "D", solution: "CO₂ is linear and symmetric, so its two bond dipoles cancel, making the molecule non-polar." },
  { id: "esat-mk3-c-06", type: "mcq", testId: "esat", topicId: "esat-chem1", difficulty: 1, marks: 1,
    question: "How many electrons does a calcium ion, Ca²⁺ (atomic number 20), have?",
    options: [ {key:"A",text:"18"},{key:"B",text:"20"},{key:"C",text:"22"},{key:"D",text:"2"},{key:"E",text:"40"} ],
    answer: "A", solution: "Neutral Ca has 20 electrons; losing 2 to form Ca²⁺ leaves 18 (argon configuration)." },
  { id: "esat-mk3-c-07", type: "mcq", testId: "esat", topicId: "esat-chem2", difficulty: 1, marks: 1,
    question: "What is the molecular formula of butane?",
    options: [ {key:"A",text:"C₄H₈"},{key:"B",text:"C₄H₁₀"},{key:"C",text:"C₃H₈"},{key:"D",text:"C₄H₆"},{key:"E",text:"C₅H₁₂"} ],
    answer: "B", solution: "Butane is an alkane with 4 carbons: CₙH₂ₙ₊₂ with n=4 gives C₄H₁₀." },
  { id: "esat-mk3-c-08", type: "mcq", testId: "esat", topicId: "esat-chem2", difficulty: 2, marks: 1,
    question: "Which compound will decolourise bromine water?",
    options: [ {key:"A",text:"Ethane (C₂H₆)"},{key:"B",text:"Propane (C₃H₈)"},{key:"C",text:"Ethene (C₂H₄)"},{key:"D",text:"Methane (CH₄)"},{key:"E",text:"Butane (C₄H₁₀)"} ],
    answer: "C", solution: "Only the alkene (ethene) has a C=C double bond and undergoes addition with bromine, decolourising it." },
  { id: "esat-mk3-c-09", type: "mcq", testId: "esat", topicId: "esat-chem2", difficulty: 2, marks: 1,
    question: "Complete combustion of methane (CH₄) gives:",
    options: [ {key:"A",text:"CO + H₂O"},{key:"B",text:"CO₂ + H₂O"},{key:"C",text:"C + H₂O"},{key:"D",text:"CO₂ + H₂"},{key:"E",text:"CH₃OH"} ],
    answer: "B", solution: "Complete combustion of a hydrocarbon gives carbon dioxide and water: CH₄ + 2O₂ → CO₂ + 2H₂O." },
  { id: "esat-mk3-c-10", type: "mcq", testId: "esat", topicId: "esat-chem2", difficulty: 2, marks: 1,
    question: "Ethanol can be oxidised (acidified dichromate) first to ethanal and then to:",
    options: [ {key:"A",text:"Ethane"},{key:"B",text:"Ethene"},{key:"C",text:"Ethanoic acid"},{key:"D",text:"An ester"},{key:"E",text:"Methanol"} ],
    answer: "C", solution: "A primary alcohol oxidises to an aldehyde, then on further oxidation to a carboxylic acid (ethanoic acid)." },
  { id: "esat-mk3-c-11", type: "mcq", testId: "esat", topicId: "esat-chem2", difficulty: 2, marks: 1,
    question: "Reacting ethanoic acid with ethanol (acid catalyst) produces ethyl ethanoate and:",
    options: [ {key:"A",text:"hydrogen"},{key:"B",text:"water"},{key:"C",text:"carbon dioxide"},{key:"D",text:"oxygen"},{key:"E",text:"an alkene"} ],
    answer: "B", solution: "Esterification: carboxylic acid + alcohol ⇌ ester + water." },
  { id: "esat-mk3-c-12", type: "mcq", testId: "esat", topicId: "esat-chem2", difficulty: 3, marks: 1,
    question: "How many structural isomers have the molecular formula C₅H₁₂?",
    options: [ {key:"A",text:"2"},{key:"B",text:"3"},{key:"C",text:"4"},{key:"D",text:"5"},{key:"E",text:"6"} ],
    answer: "B", solution: "C₅H₁₂ has three isomers: pentane, 2-methylbutane and 2,2-dimethylpropane." },
  { id: "esat-mk3-c-13", type: "mcq", testId: "esat", topicId: "esat-chem2", difficulty: 1, marks: 1,
    question: "The repeating addition polymer made from ethene is:",
    options: [ {key:"A",text:"poly(ethene)"},{key:"B",text:"poly(propene)"},{key:"C",text:"PVC"},{key:"D",text:"polyester"},{key:"E",text:"nylon"} ],
    answer: "A", solution: "Ethene monomers undergo addition polymerisation to form poly(ethene) (polythene)." },
  { id: "esat-mk3-c-14", type: "mcq", testId: "esat", topicId: "esat-chem3", difficulty: 1, marks: 1,
    question: "An exothermic reaction has an enthalpy change ($\\Delta H$) that is:",
    options: [ {key:"A",text:"positive"},{key:"B",text:"negative"},{key:"C",text:"zero"},{key:"D",text:"always 100 kJ"},{key:"E",text:"undefined"} ],
    answer: "B", solution: "Exothermic reactions release heat, so the products are lower in enthalpy and $\\Delta H$ is negative." },
  { id: "esat-mk3-c-15", type: "mcq", testId: "esat", topicId: "esat-chem3", difficulty: 2, marks: 1,
    question: "A solution has $[\\text{H}^+]=1\\times10^{-4}\\,\\text{mol dm}^{-3}$. Its pH is:",
    options: [ {key:"A",text:"2"},{key:"B",text:"4"},{key:"C",text:"7"},{key:"D",text:"10"},{key:"E",text:"14"} ],
    answer: "B", solution: "$\\text{pH}=-\\log_{10}(10^{-4})=4$." },
  { id: "esat-mk3-c-16", type: "mcq", testId: "esat", topicId: "esat-chem3", difficulty: 2, marks: 1,
    question: "Adding a catalyst to a reaction at equilibrium:",
    options: [ {key:"A",text:"shifts equilibrium right"},{key:"B",text:"shifts equilibrium left"},{key:"C",text:"speeds both directions equally; position unchanged"},{key:"D",text:"increases the yield"},{key:"E",text:"changes $K_c$"} ],
    answer: "C", solution: "A catalyst lowers the activation energy for both directions equally, so equilibrium is reached faster but its position is unchanged." },
  { id: "esat-mk3-c-17", type: "mcq", testId: "esat", topicId: "esat-chem3", difficulty: 3, marks: 1,
    question: "For the exothermic equilibrium $2\\text{SO}_2 + \\text{O}_2 \\rightleftharpoons 2\\text{SO}_3$, increasing the temperature will:",
    options: [ {key:"A",text:"increase the yield of SO₃"},{key:"B",text:"decrease the yield of SO₃"},{key:"C",text:"have no effect on yield"},{key:"D",text:"stop the reaction"},{key:"E",text:"change SO₃ into a solid"} ],
    answer: "B", solution: "Higher temperature favours the endothermic (reverse) direction, so the equilibrium shifts left and the yield of SO₃ falls." },
  { id: "esat-mk3-c-18", type: "mcq", testId: "esat", topicId: "esat-chem3", difficulty: 2, marks: 1,
    question: "Increasing the pressure on the equilibrium $\\text{N}_2 + 3\\text{H}_2 \\rightleftharpoons 2\\text{NH}_3$ shifts it:",
    options: [ {key:"A",text:"to the left (4 → fewer)"},{key:"B",text:"to the right (toward 2 moles of gas)"},{key:"C",text:"no change"},{key:"D",text:"toward the side with more moles"},{key:"E",text:"it decomposes the NH₃"} ],
    answer: "B", solution: "Higher pressure favours the side with fewer gas moles: 4 moles (left) → 2 moles (right), so equilibrium shifts right." },
  { id: "esat-mk3-c-19", type: "mcq", testId: "esat", topicId: "esat-chem3", difficulty: 1, marks: 1,
    question: "In terms of electrons, oxidation is:",
    options: [ {key:"A",text:"gain of electrons"},{key:"B",text:"loss of electrons"},{key:"C",text:"gain of protons"},{key:"D",text:"loss of neutrons"},{key:"E",text:"gain of oxygen only"} ],
    answer: "B", solution: "OIL RIG: Oxidation Is Loss of electrons." },
  { id: "esat-mk3-c-20", type: "mcq", testId: "esat", topicId: "esat-chem3", difficulty: 2, marks: 1,
    question: "What is the oxidation number of nitrogen in the nitrate ion, NO₃⁻? (O = −2)",
    options: [ {key:"A",text:"+3"},{key:"B",text:"+5"},{key:"C",text:"−3"},{key:"D",text:"+1"},{key:"E",text:"−5"} ],
    answer: "B", solution: "Let N = x: $x+3(-2)=-1\\Rightarrow x-6=-1\\Rightarrow x=+5$." },
  { id: "esat-mk3-c-21", type: "mcq", testId: "esat", topicId: "esat-chem3", difficulty: 2, marks: 1,
    question: "Which change would slow down a reaction between marble chips and acid?",
    options: [ {key:"A",text:"using larger (less powdered) chips"},{key:"B",text:"increasing the acid concentration"},{key:"C",text:"raising the temperature"},{key:"D",text:"adding a catalyst"},{key:"E",text:"grinding the chips to powder" } ],
    answer: "A", solution: "Larger chips have a smaller surface area, so fewer collisions per second and a slower rate." },
  { id: "esat-mk3-c-22", type: "mcq", testId: "esat", topicId: "esat-chem3", difficulty: 1, marks: 1,
    question: "Neutralising hydrochloric acid with sodium hydroxide produces water and:",
    options: [ {key:"A",text:"sodium chloride"},{key:"B",text:"hydrogen gas"},{key:"C",text:"chlorine gas"},{key:"D",text:"sodium hydride"},{key:"E",text:"carbon dioxide"} ],
    answer: "A", solution: "Acid + alkali → salt + water: HCl + NaOH → NaCl + H₂O." },
  { id: "esat-mk3-c-23", type: "mcq", testId: "esat", topicId: "esat-chem1", difficulty: 2, marks: 1,
    question: "Isotopes of the same element have identical chemical properties because they have the same:",
    options: [ {key:"A",text:"number of neutrons"},{key:"B",text:"mass number"},{key:"C",text:"number (and arrangement) of electrons"},{key:"D",text:"number of nucleons"},{key:"E",text:"density"} ],
    answer: "C", solution: "Chemical behaviour depends on the electron arrangement, which is the same for isotopes (same proton/electron count); only neutron number differs." },
  { id: "esat-mk3-c-24", type: "mcq", testId: "esat", topicId: "esat-chem3", difficulty: 3, marks: 1,
    question: "Using bond energies, $\\Delta H$ of a reaction equals:",
    options: [ {key:"A",text:"(bonds formed) − (bonds broken)"},{key:"B",text:"(bonds broken) − (bonds formed)"},{key:"C",text:"(bonds broken) + (bonds formed)"},{key:"D",text:"(bonds broken) × (bonds formed)"},{key:"E",text:"always zero"} ],
    answer: "B", solution: "Breaking bonds absorbs energy (+), forming bonds releases it (−): $\\Delta H = \\text{(broken)} - \\text{(formed)}$." },
  { id: "esat-mk3-c-25", type: "mcq", testId: "esat", topicId: "esat-chem1", difficulty: 2, marks: 1,
    question: "Why do metals conduct electricity?",
    options: [ {key:"A",text:"ions are free to move in the solid"},{key:"B",text:"delocalised electrons are free to move"},{key:"C",text:"covalent bonds break easily"},{key:"D",text:"they are made of molecules"},{key:"E",text:"they contain water"} ],
    answer: "B", solution: "Metallic structure has a sea of delocalised electrons that move through the lattice and carry charge." },
  { id: "esat-mk3-c-26", type: "mcq", testId: "esat", topicId: "esat-chem2", difficulty: 3, marks: 1,
    question: "Long-chain alkanes from crude oil are broken into smaller alkanes and alkenes by:",
    options: [ {key:"A",text:"fractional distillation"},{key:"B",text:"cracking"},{key:"C",text:"esterification"},{key:"D",text:"neutralisation"},{key:"E",text:"electrolysis"} ],
    answer: "B", solution: "Cracking uses heat and a catalyst to split long-chain molecules into shorter, more useful alkanes and reactive alkenes." },
  { id: "esat-mk3-c-27", type: "mcq", testId: "esat", topicId: "esat-chem3", difficulty: 2, marks: 1,
    question: "During electrolysis of molten sodium chloride, what happens at the negative cathode?",
    options: [ {key:"A",text:"Cl⁻ ions are oxidised to chlorine"},{key:"B",text:"Na⁺ ions gain electrons to form sodium"},{key:"C",text:"Na⁺ ions are oxidised"},{key:"D",text:"water is reduced"},{key:"E",text:"nothing happens"} ],
    answer: "B", solution: "Positive Na⁺ ions migrate to the cathode and gain electrons (reduction): Na⁺ + e⁻ → Na." },
];
