import type { MCQQuestion } from "@/lib/tests/questions/types";

type Item = {
  topicId: "lnat-read" | "lnat-analyse";
  difficulty: 1 | 2 | 3;
  question: string;
  options: [string, string, string, string, string];
  answer: "A" | "B" | "C" | "D" | "E";
  solution: string;
};

const KEYS = ["A", "B", "C", "D", "E"] as const;

function passageItems(start: number, passage: string, items: Item[]): MCQQuestion[] {
  return items.map((item, index) => ({
    id: `lnat-mk1-${String(start + index).padStart(2, "0")}`,
    type: "mcq",
    testId: "lnat",
    topicId: item.topicId,
    difficulty: item.difficulty,
    marks: 1,
    question: `**Passage**\n\n${passage}\n\n**Question**\n\n${item.question}`,
    options: item.options.map((text, optionIndex) => ({ key: KEYS[optionIndex], text })),
    answer: item.answer,
    solution: item.solution,
  }));
}

const EMERGENCY_POWERS = `A constitution that permits emergency powers accepts a dangerous instrument because ordinary law may be too slow for extraordinary threats. The familiar response is to insist that the legislature approve each use. Yet approval alone is a weak safeguard when legislators receive the same alarming intelligence as ministers, fear blame for appearing complacent, and must vote before the evidence can be tested. A large majority may then reveal common pressure rather than independent judgment.

The stronger safeguard is not to forbid emergency action, but to make it temporary unless renewed after the immediate panic has passed. Renewal should require publication of the evidence that can safely be disclosed, an account of measures taken, and review by a court able to hear challenges from affected people. These requirements do not guarantee wisdom. They do, however, change the burden of justification: the executive must repeatedly show why exceptional power remains necessary rather than leaving citizens to prove why a permanent restriction should end. Emergency authority is least dangerous when its continuation is harder than its creation.`;

const MEDICAL_PREDICTION = `Suppose a blood test can reveal a high probability of developing an incurable neurological condition decades later. Some argue that doctors should disclose such results whenever the information is reliable: patients, not professionals, should decide how to live with knowledge about their own bodies. But the appeal to autonomy is incomplete. A person may also autonomously choose not to know, especially where no treatment exists and the prediction is probabilistic rather than certain.

This does not mean doctors should suppress results by default. Before testing, patients should be offered a genuine choice about which categories of findings they wish to receive. Consent obtained through a dense form signed minutes before a routine appointment is not enough; the significance of knowing and not knowing must be explained. Respect for autonomy therefore requires more than transferring every available fact. It requires arranging the decision so that the patient's preference about information, including a preference for ignorance, can be informed and deliberate.`;

const MONUMENTS = `Debates about public monuments are often framed as a choice between preserving history and erasing it. That framing mistakes a monument for an archive. An archive preserves evidence for investigation; a monument occupies honoured public space and normally asks citizens to regard its subject as worthy of admiration. Removing a statue need not remove records, books or museum exhibits about the person. It changes the form in which a community presents that past.

Nor does this distinction prove that every offensive monument should come down. A work may have artistic importance, may commemorate an achievement inseparable from serious wrongdoing, or may itself have become evidence of how later generations constructed national memory. Contextual plaques can sometimes expose rather than endorse those layers. But context is not a universal solvent. If a monument's location and design continue to confer honour that a small label cannot plausibly undo, relocation to a museum may preserve the object while ending the official tribute. The relevant question is not whether history should survive, but what civic meaning the present placement gives it now.`;

const ALGORITHMIC_TRANSPARENCY = `When a public agency uses software to decide who receives an inspection, a benefit or an investigation, critics often demand that the code be published. Suppliers reply that publication would reveal trade secrets and allow people to game the system. Both positions treat transparency as if it had only two settings: total disclosure or complete secrecy.

Citizens rarely need every line of code. They need enough information to contest a decision: which data mattered, what general rule connected those data to the outcome, how often the system errs, and who is responsible for correcting it. Independent auditors may need deeper access under confidentiality. A supplier's commercial interest can justify withholding some implementation details, but it cannot justify a system whose decisions are impossible to explain or challenge. The proper demand is therefore functional transparency, calibrated to the role of the person asking, rather than indiscriminate publication.`;

const RESTORATIVE_JUSTICE = `Restorative justice brings offenders and victims into a structured process focused on acknowledging harm and agreeing steps to repair it. Its supporters sometimes present it as a humane replacement for punishment. That claim goes too far. A meeting cannot by itself express the public condemnation appropriate to grave violence, and a victim should never carry responsibility for deciding how society responds to an offender.

Yet these limits do not make restoration irrelevant. Criminal proceedings usually ask whether the accused broke a rule and what penalty follows. Victims may want answers that a trial is poorly designed to provide: Why me? Do you understand what you did? What will stop it happening again? Where participation is voluntary, guilt has been established, and trained facilitators prevent intimidation, a restorative process can answer those needs while complementing a proportionate sentence. Its value lies not in replacing public justice but in addressing dimensions of harm that punishment alone leaves untouched.`;

const ACADEMIC_NEUTRALITY = `Universities are often urged to remain neutral on disputed political questions so that scholars and students can inquire without institutional pressure. The principle is attractive, but it cannot mean that a university takes no value-laden positions. A commitment to evidence, open criticism and equal access already rejects censorship, fraud and discrimination. Even deciding which research to fund allocates prestige and resources according to judgments about importance.

Institutional neutrality is more defensible when understood narrowly. A university should avoid announcing a collective verdict on controversies that members are employed or enrolled to debate, especially where no operational decision is required. It may still defend the conditions of inquiry and take positions necessary to govern itself. The aim is not a value-free institution, which is impossible, but one that does not convert administrative authority into an official answer to questions its academic community should remain free to contest.`;

const CARBON_BORDER = `A country that taxes domestic carbon emissions may watch production move abroad to factories facing no equivalent charge. A border levy on carbon-intensive imports is intended to prevent that leakage. Opponents call the levy protectionism dressed in environmental language, noting that rich countries industrialised using cheap fossil energy and now propose to penalise poorer exporters.

That objection has force if the levy simply shields local firms or ignores differences in capacity. But it does not show that every border measure is illegitimate. Without some adjustment, domestic regulation can reduce emissions on paper while global emissions rise. A defensible levy would estimate embedded carbon by a transparent method, allow exporters to prove cleaner production, and return part of the revenue to help lower-income trading partners decarbonise. Such a scheme may still be administratively difficult. The relevant comparison, however, is not with a perfectly fair world; it is with a policy that may otherwise relocate pollution and reward the least regulated production.`;

const ANONYMOUS_SOURCES = `Reports based on anonymous sources ask readers to trust information while withholding the identity that would help them assess it. A rule banning anonymity would therefore seem to promote accountability. It would also prevent reporting on matters that powerful institutions can effectively conceal, because employees who identify themselves may lose their jobs or face prosecution.

The choice is not between anonymous claims accepted blindly and named claims accepted safely. Editors can require a reporter to know the source's identity, seek corroboration, explain the source's access to the information, and tell readers why anonymity was granted. The more serious the allegation, the stronger those checks should be. Anonymity reduces the evidence available to readers and should count against confidence in a report, but it need not reduce confidence to zero. What matters is whether the publication compensates for the missing name with other grounds for trust.`;

const PUBLIC_CONSULTATION = `City authorities increasingly consult residents before redesigning streets. The meetings are praised as democratic, yet attendance is often dominated by people with flexible schedules, established organisations and strong objections. Treating the loudest meeting as a miniature electorate can therefore make policy less representative rather than more.

The remedy is not to abandon consultation. Local knowledge can reveal delivery routes, unsafe crossings or access needs that a citywide survey misses. But consultation should be treated as evidence, not a referendum. Officials should combine open meetings with random-sample surveys, targeted outreach to affected groups and observation of how the street is actually used. They should also explain which considerations changed the design and which did not. Participation improves a decision when it broadens the information available and exposes reasons to scrutiny; it distorts a decision when attendance is mistaken for a mandate.`;

export const LNAT_MK1_EXPANSION: MCQQuestion[] = [
  ...passageItems(12, EMERGENCY_POWERS, [
    { topicId: "lnat-analyse", difficulty: 2, question: "What is the passage's main argument?", options: ["Emergency powers should never be available.", "Legislative approval is a complete safeguard against abuse.", "Emergency powers should expire unless renewed under stronger evidence and review requirements.", "Courts should make every emergency decision in place of government.", "Published evidence always eliminates political pressure."], answer: "C", solution: "The author accepts that emergency powers may be needed but argues that temporary authority, evidence, renewal and review better constrain its continuation." },
    { topicId: "lnat-read", difficulty: 2, question: "Why does the author regard an initial legislative vote as a weak safeguard?", options: ["Legislators are legally forbidden to reject emergency measures.", "Courts always overturn legislative votes.", "The executive never shares intelligence with legislators.", "Legislators may face the same fear, limited evidence and political pressure as ministers.", "A vote necessarily makes emergency powers permanent."], answer: "D", solution: "The first paragraph says legislators may share the alarming information, urgency and fear of blame, so a majority need not represent independent scrutiny." },
    { topicId: "lnat-analyse", difficulty: 3, question: "Which principle most closely underlies the proposed renewal process?", options: ["Any restriction approved by a majority is legitimate.", "Secret evidence should never influence public policy.", "Courts should govern whenever risks are uncertain.", "Temporary laws require less justification than ordinary laws.", "Those continuing exceptional restrictions should bear the burden of showing that they remain necessary."], answer: "E", solution: "The final paragraph explicitly shifts the burden to the executive to justify continuation rather than making citizens prove why restrictions should end." },
    { topicId: "lnat-read", difficulty: 1, question: "The phrase 'common pressure rather than independent judgment' distinguishes between:", options: ["agreement produced by shared fear and agreement produced by separate scrutiny" , "executive power and judicial power", "published evidence and secret evidence", "temporary restrictions and permanent constitutions", "citizens and legislators"], answer: "A", solution: "The author warns that the same pressure can produce the same vote without each legislator independently testing the case." },
  ]),
  ...passageItems(16, MEDICAL_PREDICTION, [
    { topicId: "lnat-read", difficulty: 1, question: "Which statement best captures the author's view of autonomy?", options: ["Autonomy requires doctors to disclose every reliable result automatically.", "Autonomy has no relevance where a condition is incurable.", "Autonomy can protect both a wish to know and an informed wish not to know.", "Only doctors can decide whether information is beneficial.", "A patient's first preference must never be questioned."], answer: "C", solution: "The passage argues that self-direction includes deciding whether to receive predictive information, including choosing informed ignorance." },
    { topicId: "lnat-analyse", difficulty: 2, question: "Why is the example of a dense consent form included?", options: ["To show that all written consent is invalid.", "To argue that routine appointments should be abolished.", "To prove that patients dislike medical language.", "To illustrate that formal agreement may not amount to an informed, deliberate choice.", "To show that predictive tests are always inaccurate."], answer: "D", solution: "The example contrasts a signature with meaningful explanation of the consequences of knowing and not knowing." },
    { topicId: "lnat-analyse", difficulty: 3, question: "Which fact would most weaken the author's proposed approach?", options: ["Some patients prefer to discuss tests with relatives.", "Neurological conditions can affect people at different ages.", "Doctors sometimes disagree about probability estimates.", "The test requires a blood sample rather than a scan.", "Patients' stated disclosure preferences change unpredictably even after thorough pre-test explanation, leaving no stable choice to follow."], answer: "E", solution: "The proposal relies on eliciting an informed preference that can guide disclosure. If no sufficiently stable preference can be obtained, that mechanism is weakened." },
  ]),
  ...passageItems(19, MONUMENTS, [
    { topicId: "lnat-read", difficulty: 2, question: "What distinction is central to the passage?", options: ["Preserving evidence of a person differs from continuing to honour that person in public space.", "Museums preserve objects while archives destroy them.", "Artistic merit always outweighs moral criticism.", "Older monuments are more accurate than newer histories.", "Public space has no effect on civic meaning."], answer: "A", solution: "The author separates historical preservation in archives or museums from the honour normally conveyed by a monument's public placement." },
    { topicId: "lnat-analyse", difficulty: 3, question: "The author says that 'context is not a universal solvent' chiefly to reject the claim that:", options: ["plaques can never add useful historical information", "all monuments should be destroyed rather than moved", "adding explanatory material necessarily removes the honour conveyed by every monument", "artistic importance is irrelevant to public decisions", "museums are unable to preserve controversial objects"], answer: "C", solution: "A plaque may expose complexity, but the author denies that it always dissolves the honour created by location and design." },
    { topicId: "lnat-read", difficulty: 2, question: "Which action would the author most likely support in at least some cases?", options: ["Erasing every documentary reference to a wrongdoer", "Leaving every monument unchanged because it is old", "Judging monuments solely by the intentions of their sculptors", "Moving an object to a museum when its public setting continues to confer an indefensible honour", "Replacing archives with commemorative statues"], answer: "D", solution: "The passage explicitly presents museum relocation as a way to preserve the object while ending an official tribute that context cannot undo." },
    { topicId: "lnat-read", difficulty: 1, question: "According to the passage, the relevant present-day question is:", options: ["whether the person commemorated ever existed", "whether all citizens agree about the past", "whether museums have enough storage", "whether the monument was expensive to build", "what civic meaning the monument's current placement now communicates"], answer: "E", solution: "The final sentence states that current civic meaning, rather than bare historical survival, is the relevant issue." },
  ]),
  ...passageItems(23, ALGORITHMIC_TRANSPARENCY, [
    { topicId: "lnat-analyse", difficulty: 2, question: "Which position does the author defend?", options: ["Transparency should provide the information needed for explanation, challenge and oversight, with access varying by role.", "All public software must publish every line of source code.", "Trade secrecy should defeat every request for explanation.", "Only software suppliers should audit public decisions.", "Citizens need technical implementation details but not reasons for outcomes."], answer: "A", solution: "The author rejects the all-or-nothing choice and supports functional, role-sensitive transparency." },
    { topicId: "lnat-analyse", difficulty: 3, question: "Which assumption is most necessary for the author's compromise?", options: ["Published code can never be understood by anyone.", "People never attempt to manipulate public systems.", "Meaningful accountability can sometimes be achieved without revealing every implementation detail to everyone.", "Commercial software is always more accurate than public software.", "Independent auditors should make final benefit decisions."], answer: "C", solution: "The proposed middle position requires that explanations, performance data and controlled audit access can provide accountability short of universal code publication." },
    { topicId: "lnat-read", difficulty: 1, question: "Why might independent auditors receive deeper access than individual citizens?", options: ["Auditors own the public agency.", "Citizens have no right to challenge decisions.", "Auditors are permitted to change the law.", "They can examine implementation under confidentiality while citizens mainly need reasons relevant to contesting their own decisions.", "Trade secrets have no value when shown to auditors."], answer: "D", solution: "The passage calibrates access by function: auditors inspect the system in depth, while affected citizens need intelligible grounds and routes to challenge." },
  ]),
  ...passageItems(26, RESTORATIVE_JUSTICE, [
    { topicId: "lnat-read", difficulty: 2, question: "What is the author's overall assessment of restorative justice?", options: ["It should replace criminal punishment in all cases.", "It is useful only when guilt remains uncertain.", "It unfairly gives victims any role in justice.", "It is valuable mainly because it reduces court costs.", "It can complement proportionate punishment by addressing needs that trials often leave unanswered."], answer: "E", solution: "The author rejects replacement but supports voluntary, safeguarded restoration as a complement that addresses otherwise neglected harms." },
    { topicId: "lnat-read", difficulty: 3, question: "Why does the author say a victim should not decide society's response to an offender?", options: ["Public condemnation and sentencing are social responsibilities, not burdens to be transferred to an individual victim.", "Victims never understand the harm they suffered.", "All victims necessarily demand the harshest penalty.", "A restorative meeting can establish guilt more reliably than a trial.", "Trained facilitators should determine guilt."], answer: "A", solution: "The first paragraph distinguishes public justice from the victim's personal needs and refuses to place society's penal responsibility on the victim." },
    { topicId: "lnat-analyse", difficulty: 2, question: "Which condition is NOT among the safeguards the author identifies?", options: ["Participation is voluntary.", "Guilt has already been established.", "The victim agrees to waive any proportionate sentence.", "Trained facilitators prevent intimidation.", "The process complements rather than automatically replaces public justice."], answer: "C", solution: "The author never requires victims to waive sentencing; on the contrary, restoration is presented as complementing a proportionate sentence." },
    { topicId: "lnat-analyse", difficulty: 3, question: "Which objection would most directly challenge the claimed distinctive value of restoration?", options: ["Some trials take a long time.", "Many offences violate written rules.", "Sentences can include financial penalties.", "Well-run ordinary proceedings already provide reliable answers to victims' questions about motive, understanding and prevention.", "Some offenders deny guilt before conviction."], answer: "D", solution: "The author's positive case rests on restoration answering needs that trials are poorly designed to meet. If trials already meet them, that distinctive benefit shrinks." },
  ]),
  ...passageItems(30, ACADEMIC_NEUTRALITY, [
    { topicId: "lnat-read", difficulty: 1, question: "Why does the author reject a completely value-free university?", options: ["Universities are required to endorse political parties.", "Students cannot understand neutral arguments.", "Research funding is always controlled by governments.", "Every academic agrees on the same values.", "Core commitments and ordinary governance already involve judgments about values and importance."], answer: "E", solution: "The passage cites commitments to evidence, criticism, access and funding choices as unavoidable value judgments." },
    { topicId: "lnat-analyse", difficulty: 2, question: "Under the author's narrower principle, when should a university usually avoid taking a collective position?", options: ["When a disputed issue is one its members should remain free to investigate and no operational decision requires a verdict.", "Whenever discrimination affects access to the institution.", "Whenever evidence of research fraud emerges.", "Whenever administrators must allocate research funding.", "Whenever the conditions of open inquiry are threatened."], answer: "A", solution: "The narrow principle targets official verdicts on controversies the academic community is meant to debate, unless governance requires action." },
    { topicId: "lnat-analyse", difficulty: 3, question: "Which action is most consistent with the passage?", options: ["The university endorses one side in every national election.", "The university refuses to discipline fabricated research in the name of neutrality.", "The university protects a controversial seminar from disruption while declining to endorse the seminar's conclusion.", "The university treats every funding decision as politically neutral by definition.", "The university prohibits staff from criticising its policies."], answer: "C", solution: "Protecting the conditions of inquiry while withholding an institutional verdict exemplifies the author's narrower form of neutrality." },
  ]),
  ...passageItems(33, CARBON_BORDER, [
    { topicId: "lnat-read", difficulty: 1, question: "What problem is a carbon border levy intended to address?", options: ["A shortage of domestic customs officials", "The use of any imported raw material", "Disagreement about historical emissions", "Production and emissions moving to less regulated countries after domestic carbon charges", "A fall in global demand for energy"], answer: "D", solution: "The opening sentence identifies carbon leakage: production relocates abroad where emissions face no equivalent charge." },
    { topicId: "lnat-analyse", difficulty: 2, question: "How does the author treat the fairness objection raised by poorer exporters?", options: ["As wholly irrelevant because climate policy overrides fairness", "As proof that domestic carbon taxes should end", "As evidence that all trade measures are protectionist", "As a reason to exempt every imported product", "As a serious concern that can shape the levy without proving every border adjustment illegitimate"], answer: "E", solution: "The objection has force, but the author argues that transparent calculation, cleaner-production evidence and revenue support can answer it in part." },
    { topicId: "lnat-analyse", difficulty: 3, question: "The phrase 'the relevant comparison is not with a perfectly fair world' warns against:", options: ["rejecting a workable policy merely because it is imperfect while ignoring the defects of the realistic alternative", "using transparent methods to estimate embedded carbon", "allowing exporters to demonstrate cleaner production", "considering the historical position of poorer countries", "measuring whether global emissions rise"], answer: "A", solution: "The author insists on comparing the levy with the actual alternative of leakage, not with an unavailable ideal." },
    { topicId: "lnat-read", difficulty: 2, question: "Which feature would most clearly make the levy resemble the protectionism criticised by opponents?", options: ["Publishing the carbon-estimation method", "Allowing importers to submit evidence of lower emissions", "Setting charges to favour domestic firms even when foreign producers have equally low emissions", "Using revenue to support decarbonisation abroad", "Reviewing whether the policy reduces leakage"], answer: "C", solution: "Discriminating in favour of domestic firms despite equal carbon performance would reveal protection rather than an environmental adjustment." },
  ]),
  ...passageItems(37, ANONYMOUS_SOURCES, [
    { topicId: "lnat-read", difficulty: 1, question: "What is the author's conclusion about anonymous sources?", options: ["They should always be trusted when an editor knows their identity.", "They should be prohibited in allegations against institutions.", "They provide exactly the same evidence as named sources.", "They reduce confidence, but careful corroboration and explanation can sometimes justify publication.", "They are acceptable only when a source faces criminal prosecution."], answer: "D", solution: "The author treats anonymity as an evidential cost that can be offset, though not erased, by other safeguards." },
    { topicId: "lnat-analyse", difficulty: 2, question: "Which policy best follows from the passage?", options: ["Publish every anonymous allegation immediately.", "Require readers to identify confidential sources themselves.", "Treat a reporter's assurance as sufficient for every claim.", "Ban anonymous reporting unless the source is a public official.", "Demand stronger corroboration as the seriousness of an anonymously sourced allegation increases."], answer: "E", solution: "The passage explicitly links the strength of required checks to the seriousness of the allegation." },
    { topicId: "lnat-analyse", difficulty: 3, question: "Which assumption supports the argument against a complete ban?", options: ["Some important, well-founded information would remain unavailable if every source had to be publicly identified.", "Named sources are never mistaken.", "Editors should conceal whether they know a source's identity.", "Powerful institutions always prosecute employees who speak.", "Readers do not care how reports are verified."], answer: "A", solution: "The case against a ban depends on anonymity sometimes being necessary to reveal information that could not safely be supplied by a named source." },
  ]),
  ...passageItems(40, PUBLIC_CONSULTATION, [
    { topicId: "lnat-read", difficulty: 1, question: "Why can an open meeting be unrepresentative?", options: ["Officials prevent residents from speaking.", "Local knowledge is always inaccurate.", "Those able and motivated to attend may differ systematically from the wider affected population.", "Random surveys include too many people.", "Street design never affects organised groups."], answer: "C", solution: "The passage notes that flexible schedules, organisation and strong objections influence attendance, so attendees are not a miniature electorate." },
    { topicId: "lnat-analyse", difficulty: 2, question: "What role should consultation play according to the author?", options: ["It should automatically decide policy by majority vote.", "It should replace observation and representative surveys.", "It should be limited to people who support the proposal.", "It should supply local evidence and reasons alongside more representative methods, not be mistaken for a mandate.", "It should occur only after the final design is fixed."], answer: "D", solution: "The author values local evidence but insists it be combined with other methods and treated as input rather than a referendum." },
    { topicId: "lnat-analyse", difficulty: 3, question: "Which consultation process would the author most likely criticise?", options: ["Officials survey a random sample and publish their response to concerns.", "Planners observe delivery patterns before changing kerb access.", "Targeted outreach identifies access needs missed in an open meeting.", "A design is revised after several sources reveal an unsafe crossing.", "Officials treat opposition at one poorly attended evening meeting as conclusive proof that the whole district rejects the plan."], answer: "E", solution: "This treats a self-selected meeting as a representative mandate, the precise error criticised in the passage." },
  ]),
];
