// MAT 模拟卷4 —— 生成器出题，sympy 计算答案。25 道五选一，id 前缀 mat-mk4-*。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const MAT_MK4_MCQ: MCQQuestion[] = [
  { id: "mat-mk4-01", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 3, marks: 3,
    question: "The coefficient of $x^{4}$ in $(1+x)^{6}+(1+x)^{5}$ is:",
    options: [{ key: "A", text: "$20$" },{ key: "B", text: "$5$" },{ key: "C", text: "$15$" },{ key: "D", text: "$21$" },{ key: "E", text: "$19$" }],
    answer: "A", solution: "$\\binom{6}{4}+\\binom{5}{4}=15+5=20$." },
  { id: "mat-mk4-02", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 2, marks: 2,
    question: "Evaluate $\\displaystyle\\int_{0}^{2} x^{3}\\,dx$.",
    options: [{ key: "A", text: "$\\frac{23}{6}$" },{ key: "B", text: "$8$" },{ key: "C", text: "$\\frac{25}{6}$" },{ key: "D", text: "$4$" },{ key: "E", text: "$2$" }],
    answer: "D", solution: "$\\int x^{3}\\,dx$ evaluated from $0$ to $2$ gives $4$." },
  { id: "mat-mk4-03", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 2, marks: 2,
    question: "Evaluate $\\displaystyle\\int_{1}^{3} x^{2} + 1\\,dx$.",
    options: [{ key: "A", text: "$\\frac{16}{3}$" },{ key: "B", text: "$\\frac{65}{6}$" },{ key: "C", text: "$\\frac{64}{3}$" },{ key: "D", text: "$\\frac{32}{3}$" },{ key: "E", text: "$\\frac{21}{2}$" }],
    answer: "D", solution: "$\\int x^{2} + 1\\,dx$ evaluated from $1$ to $3$ gives $\\frac{32}{3}$." },
  { id: "mat-mk4-04", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 2,
    question: "The sum $1+2+4+\\cdots+2^{12}$ equals:",
    options: [{ key: "A", text: "$2^{14}-1$" },{ key: "B", text: "$2^{13}-1$" },{ key: "C", text: "$2^{13}$" },{ key: "D", text: "$2^{12}-1$" },{ key: "E", text: "$2^{12}$" }],
    answer: "B", solution: "Geometric series with ratio $2$: sum $=\\dfrac{2^{13}-1}{2-1}=2^{13}-1=8191$." },
  { id: "mat-mk4-05", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 2,
    question: "The minimum value of $y=x^2 + 6x + 11$ is:",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$3$" },{ key: "C", text: "$2$" },{ key: "D", text: "$-7$" },{ key: "E", text: "$11$" }],
    answer: "C", solution: "Complete the square: $x^2+6x+11=(x+3)^2 + 2$, minimum $2$." },
  { id: "mat-mk4-06", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 2, marks: 2,
    question: "The shortest distance from $(0,0)$ to the line $3x + 4y - 25=0$ is:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$6$" },{ key: "C", text: "$\\frac{9}{5}$" },{ key: "D", text: "$5$" },{ key: "E", text: "$7$" }],
    answer: "D", solution: "Distance $=\\dfrac{|3(0)+4(0)-25|}{\\sqrt{3^2+4^2}}=5$." },
  { id: "mat-mk4-07", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 2, marks: 2,
    question: "Outer loop $i=1,\\dots,4$; for each $i$ the inner loop runs $j=1,\\dots,i$. How many times does the inner body run in total?",
    options: [{ key: "A", text: "$16$" },{ key: "B", text: "$6$" },{ key: "C", text: "$11$" },{ key: "D", text: "$9$" },{ key: "E", text: "$10$" }],
    answer: "E", solution: "Total $=1+2+\\cdots+4=\\dfrac{4\\cdot5}{2}=10$." },
  { id: "mat-mk4-08", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 2, marks: 2,
    question: "Evaluate $\\displaystyle\\int_{0}^{1} x^{2} \\left(x - 1\\right)\\,dx$.",
    options: [{ key: "A", text: "$- \\frac{1}{6}$" },{ key: "B", text: "$- \\frac{1}{24}$" },{ key: "C", text: "$\\frac{1}{12}$" },{ key: "D", text: "$- \\frac{1}{12}$" },{ key: "E", text: "$- \\frac{1}{4}$" }],
    answer: "D", solution: "$\\int x^{2} \\left(x - 1\\right)\\,dx$ evaluated from $0$ to $1$ gives $- \\frac{1}{12}$." },
  { id: "mat-mk4-09", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 3,
    question: "The value of $\\log_{3} 10\\times\\log_{10} 9$ is:",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$1$" },{ key: "C", text: "$0$" },{ key: "D", text: "$4$" },{ key: "E", text: "$3$" }],
    answer: "A", solution: "$\\log_{3}10\\cdot\\log_{10}9=\\dfrac{\\ln 10}{\\ln 3}\\cdot\\dfrac{\\ln 9}{\\ln 10}$; with $10=10^{k}$ the chain gives $\\log_{3}9=2$." },
  { id: "mat-mk4-10", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 2,
    question: "The sum $1+2+4+\\cdots+2^{8}$ equals:",
    options: [{ key: "A", text: "$2^{9}$" },{ key: "B", text: "$2^{8}$" },{ key: "C", text: "$2^{10}-1$" },{ key: "D", text: "$2^{9}-1$" },{ key: "E", text: "$2^{8}-1$" }],
    answer: "D", solution: "Geometric series with ratio $2$: sum $=\\dfrac{2^{9}-1}{2-1}=2^{9}-1=511$." },
  { id: "mat-mk4-11", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 2, marks: 2,
    question: "Evaluate $\\displaystyle\\int_{0}^{1} \\left(x + 2\\right)^{2}\\,dx$.",
    options: [{ key: "A", text: "$\\frac{19}{3}$" },{ key: "B", text: "$\\frac{19}{6}$" },{ key: "C", text: "$\\frac{37}{6}$" },{ key: "D", text: "$\\frac{13}{2}$" },{ key: "E", text: "$\\frac{38}{3}$" }],
    answer: "A", solution: "$\\int \\left(x + 2\\right)^{2}\\,dx$ evaluated from $0$ to $1$ gives $\\frac{19}{3}$." },
  { id: "mat-mk4-12", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 2,
    question: "The minimum value of $y=x^2 + 4x + 9$ is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$9$" },{ key: "C", text: "$4$" },{ key: "D", text: "$6$" },{ key: "E", text: "$1$" }],
    answer: "A", solution: "Complete the square: $x^2+4x+9=(x+2)^2 + 5$, minimum $5$." },
  { id: "mat-mk4-13", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 3, marks: 3,
    question: "The coefficient of $x^{3}$ in $(1+x)^{5}+(1+x)^{4}$ is:",
    options: [{ key: "A", text: "$13$" },{ key: "B", text: "$15$" },{ key: "C", text: "$4$" },{ key: "D", text: "$14$" },{ key: "E", text: "$10$" }],
    answer: "D", solution: "$\\binom{5}{3}+\\binom{4}{3}=10+4=14$." },
  { id: "mat-mk4-14", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 3, marks: 3,
    question: "The radius of the circle $x^2+y^2 - 2x + 0y - 3=0$ is:",
    options: [{ key: "A", text: "$\\sqrt{2}$" },{ key: "B", text: "$\\sqrt{5}$" },{ key: "C", text: "$4$" },{ key: "D", text: "$3$" },{ key: "E", text: "$2$" }],
    answer: "E", solution: "Centre $(1,0)$, radius $=\\sqrt{(1)^2+(0)^2-(-3)}=\\sqrt{4}=2$." },
  { id: "mat-mk4-15", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 2, marks: 2,
    question: "How many $1$s appear in the binary representation of $85$?",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$5$" },{ key: "C", text: "$3$" },{ key: "D", text: "$7$" },{ key: "E", text: "$6$" }],
    answer: "A", solution: "$85_{10}=1010101_2$, which contains $4$ ones." },
  { id: "mat-mk4-16", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 2,
    question: "The minimum value of $y=x^2 - 6x + 13$ is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$13$" },{ key: "C", text: "$4$" },{ key: "D", text: "$5$" },{ key: "E", text: "$-5$" }],
    answer: "C", solution: "Complete the square: $x^2-6x+13=(x-3)^2 + 4$, minimum $4$." },
  { id: "mat-mk4-17", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 2,
    question: "The sum to infinity of the geometric series with first term $2$ and common ratio $\\frac{1}{2}$ is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$8$" },{ key: "C", text: "$4$" },{ key: "D", text: "$1$" },{ key: "E", text: "$5$" }],
    answer: "C", solution: "$S_\\infty=\\dfrac{a}{1-r}=\\dfrac{2}{1-\\frac{1}{2}}=4$." },
  { id: "mat-mk4-18", type: "mcq", testId: "mat", topicId: "mat-trig", difficulty: 2, marks: 2,
    question: "If $\\tan\\theta=\\tfrac{20}{21}$ with $\\theta$ acute, then $\\sin\\theta+\\cos\\theta$ equals:",
    options: [{ key: "A", text: "$\\frac{41}{29}$" },{ key: "B", text: "$\\frac{1}{29}$" },{ key: "C", text: "$\\frac{21}{29}$" },{ key: "D", text: "$\\frac{20}{29}$" },{ key: "E", text: "$1$" }],
    answer: "A", solution: "A $20$–$21$–$29$ right triangle: $\\sin\\theta=\\tfrac{20}{29}$, $\\cos\\theta=\\tfrac{21}{29}$, sum $=\\frac{41}{29}$." },
  { id: "mat-mk4-19", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 2, marks: 2,
    question: "How many $1$s appear in the binary representation of $127$?",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$6$" },{ key: "C", text: "$9$" },{ key: "D", text: "$10$" },{ key: "E", text: "$8$" }],
    answer: "A", solution: "$127_{10}=1111111_2$, which contains $7$ ones." },
  { id: "mat-mk4-20", type: "mcq", testId: "mat", topicId: "mat-trig", difficulty: 3, marks: 3,
    question: "Solve type $2\\cos^2\\theta+\\dots=0$: the number of solutions of $(2\\cos \\theta-1)(\\cos \\theta-1)=0$ in $0\\le\\theta<2\\pi$ is:",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$2$" },{ key: "C", text: "$4$" },{ key: "D", text: "$5$" },{ key: "E", text: "$3$" }],
    answer: "E", solution: "$\\cos\\theta=\\frac{1}{2}$ (2); $\\cos\\theta=1\\Rightarrow\\theta=0$ (1). Total 3." },
  { id: "mat-mk4-21", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 2,
    question: "When $x^{3} + 2 x^{2} - x + 5$ is divided by $(x - 1)$, the remainder is:",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$6$" },{ key: "C", text: "$8$" },{ key: "D", text: "$5$" },{ key: "E", text: "$7$" }],
    answer: "E", solution: "By the remainder theorem, remainder $=f(1)=7$." },
  { id: "mat-mk4-22", type: "mcq", testId: "mat", topicId: "mat-trig", difficulty: 2, marks: 2,
    question: "How many solutions does $\\sin(2\\theta)=\\tfrac12$ have for $0\\le\\theta<2\\pi$?",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$3$" },{ key: "C", text: "$2$" },{ key: "D", text: "$6$" },{ key: "E", text: "$5$" }],
    answer: "A", solution: "Let $\\phi=2\\theta\\in[0,4\\pi)$. $\\sin\\phi=\\tfrac12$ has $2$ solutions per $2\\pi$, so $2\\times2=4$ in total." },
  { id: "mat-mk4-23", type: "mcq", testId: "mat", topicId: "mat-trig", difficulty: 2, marks: 2,
    question: "If $\\tan\\theta=\\tfrac{5}{12}$ with $\\theta$ acute, then $\\sin\\theta+\\cos\\theta$ equals:",
    options: [{ key: "A", text: "$\\frac{7}{13}$" },{ key: "B", text: "$\\frac{12}{13}$" },{ key: "C", text: "$1$" },{ key: "D", text: "$\\frac{17}{13}$" },{ key: "E", text: "$\\frac{5}{13}$" }],
    answer: "D", solution: "A $5$–$12$–$13$ right triangle: $\\sin\\theta=\\tfrac{5}{13}$, $\\cos\\theta=\\tfrac{12}{13}$, sum $=\\frac{17}{13}$." },
  { id: "mat-mk4-24", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 2,
    question: "How many distinct real roots does $x^4 - 10x^2 + 9 = 0$ have?",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$1$" },{ key: "C", text: "$3$" },{ key: "D", text: "$0$" },{ key: "E", text: "$2$" }],
    answer: "A", solution: "Let $u=x^2$: $u^2 - 10u + 9=(u-(1))(u-(9))=0$, so $u=1$ or $u=9$. Each positive $u$ gives two real $x$, a negative $u$ gives none. Total: 4." },
  { id: "mat-mk4-25", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 3, marks: 3,
    question: "The coefficient of $x^{2}$ in $(1+x)^{5}+(1+x)^{3}$ is:",
    options: [{ key: "A", text: "$14$" },{ key: "B", text: "$13$" },{ key: "C", text: "$10$" },{ key: "D", text: "$12$" },{ key: "E", text: "$3$" }],
    answer: "B", solution: "$\\binom{5}{2}+\\binom{3}{2}=10+3=13$." },
];
