// MAT 模拟卷3 —— 生成器出题，sympy 计算答案。25 道五选一，id 前缀 mat-mk3-*。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const MAT_MK3_MCQ: MCQQuestion[] = [
  { id: "mat-mk3-01", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 3, marks: 3,
    question: "How many $3$-digit numbers are there with all digits distinct and even?",
    options: [{ key: "A", text: "$288$" },{ key: "B", text: "$328$" },{ key: "C", text: "$320$" },{ key: "D", text: "$336$" },{ key: "E", text: "$368$" }],
    answer: "B", solution: "Direct count by casework on the units digit gives $328$." },
  { id: "mat-mk3-02", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 3, marks: 3,
    question: "The radius of the circle $x^2+y^2 - 6x + 8y + 0=0$ is:",
    options: [{ key: "A", text: "$\\sqrt{23}$" },{ key: "B", text: "$6$" },{ key: "C", text: "$\\sqrt{26}$" },{ key: "D", text: "$5$" },{ key: "E", text: "$25$" }],
    answer: "D", solution: "Centre $(3,-4)$, radius $=\\sqrt{(3)^2+(-4)^2-(0)}=\\sqrt{25}=5$." },
  { id: "mat-mk3-03", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 2,
    question: "How many distinct real roots does $x^4 + 3x^2 - 4 = 0$ have?",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$2$" },{ key: "C", text: "$4$" },{ key: "D", text: "$0$" },{ key: "E", text: "$3$" }],
    answer: "B", solution: "Let $u=x^2$: $u^2 + 3u - 4=(u-(-4))(u-(1))=0$, so $u=-4$ or $u=1$. Each positive $u$ gives two real $x$, a negative $u$ gives none. Total: 2." },
  { id: "mat-mk3-04", type: "mcq", testId: "mat", topicId: "mat-trig", difficulty: 3, marks: 3,
    question: "Solve type $2\\cos^2\\theta+\\dots=0$: the number of solutions of $(2\\cos \\theta+1)(\\cos \\theta-1)=0$ in $0\\le\\theta<2\\pi$ is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$3$" },{ key: "C", text: "$4$" },{ key: "D", text: "$2$" },{ key: "E", text: "$1$" }],
    answer: "B", solution: "$\\cos\\theta=- \\frac{1}{2}$ (2); $\\cos\\theta=1\\Rightarrow\\theta=0$ (1). Total 3." },
  { id: "mat-mk3-05", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 3, marks: 3,
    question: "The radius of the circle $x^2+y^2 + 4x + 4y - 1=0$ is:",
    options: [{ key: "A", text: "$\\sqrt{10}$" },{ key: "B", text: "$\\sqrt{7}$" },{ key: "C", text: "$4$" },{ key: "D", text: "$9$" },{ key: "E", text: "$3$" }],
    answer: "E", solution: "Centre $(-2,-2)$, radius $=\\sqrt{(-2)^2+(-2)^2-(-1)}=\\sqrt{9}=3$." },
  { id: "mat-mk3-06", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 2,
    question: "When $x^{3} + 3 x^{2} - 5$ is divided by $(x - 2)$, the remainder is:",
    options: [{ key: "A", text: "$14$" },{ key: "B", text: "$15$" },{ key: "C", text: "$16$" },{ key: "D", text: "$17$" },{ key: "E", text: "$13$" }],
    answer: "B", solution: "By the remainder theorem, remainder $=f(2)=15$." },
  { id: "mat-mk3-07", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 2,
    question: "How many distinct real roots does $x^4 - 25x^2 + 144 = 0$ have?",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$3$" },{ key: "C", text: "$4$" },{ key: "D", text: "$1$" },{ key: "E", text: "$0$" }],
    answer: "C", solution: "Let $u=x^2$: $u^2 - 25u + 144=(u-(9))(u-(16))=0$, so $u=9$ or $u=16$. Each positive $u$ gives two real $x$, a negative $u$ gives none. Total: 4." },
  { id: "mat-mk3-08", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 2, marks: 2,
    question: "Evaluate $\\displaystyle\\int_{0}^{1} 1 - x^{2}\\,dx$.",
    options: [{ key: "A", text: "$\\frac{5}{6}$" },{ key: "B", text: "$\\frac{1}{3}$" },{ key: "C", text: "$\\frac{2}{3}$" },{ key: "D", text: "$\\frac{1}{2}$" },{ key: "E", text: "$\\frac{4}{3}$" }],
    answer: "C", solution: "$\\int 1 - x^{2}\\,dx$ evaluated from $0$ to $1$ gives $\\frac{2}{3}$." },
  { id: "mat-mk3-09", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 2, marks: 2,
    question: "How many $1$s appear in the binary representation of $23$?",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$7$" },{ key: "C", text: "$6$" },{ key: "D", text: "$4$" },{ key: "E", text: "$3$" }],
    answer: "D", solution: "$23_{10}=10111_2$, which contains $4$ ones." },
  { id: "mat-mk3-10", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 3,
    question: "The sum of the real solutions of $4^{x} - 9\\cdot 2^{x} + 8 = 0$ is:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$5$" },{ key: "C", text: "$3$" },{ key: "D", text: "$1$" },{ key: "E", text: "$2$" }],
    answer: "C", solution: "Let $y=2^x$: $y^2-9y+8=0\\Rightarrow y=2^{0},2^{3}$, so $x=0,3$; sum $=3$." },
  { id: "mat-mk3-11", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 2, marks: 2,
    question: "Outer loop $i=1,\\dots,9$; for each $i$ the inner loop runs $j=1,\\dots,i$. How many times does the inner body run in total?",
    options: [{ key: "A", text: "$36$" },{ key: "B", text: "$44$" },{ key: "C", text: "$81$" },{ key: "D", text: "$46$" },{ key: "E", text: "$45$" }],
    answer: "E", solution: "Total $=1+2+\\cdots+9=\\dfrac{9\\cdot10}{2}=45$." },
  { id: "mat-mk3-12", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 2,
    question: "The sum $1+2+4+\\cdots+2^{11}$ equals:",
    options: [{ key: "A", text: "$2^{12}$" },{ key: "B", text: "$2^{12}-1$" },{ key: "C", text: "$2^{13}-1$" },{ key: "D", text: "$2^{11}-1$" },{ key: "E", text: "$2^{11}$" }],
    answer: "B", solution: "Geometric series with ratio $2$: sum $=\\dfrac{2^{12}-1}{2-1}=2^{12}-1=4095$." },
  { id: "mat-mk3-13", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 3,
    question: "The sum of the real solutions of $4^{x} - 12\\cdot 2^{x} + 32 = 0$ is:",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$6$" },{ key: "C", text: "$3$" },{ key: "D", text: "$5$" },{ key: "E", text: "$4$" }],
    answer: "D", solution: "Let $y=2^x$: $y^2-12y+32=0\\Rightarrow y=2^{2},2^{3}$, so $x=2,3$; sum $=5$." },
  { id: "mat-mk3-14", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 2,
    question: "How many distinct real roots does $x^4 - 5x^2 - 36 = 0$ have?",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$1$" },{ key: "C", text: "$2$" },{ key: "D", text: "$4$" },{ key: "E", text: "$3$" }],
    answer: "C", solution: "Let $u=x^2$: $u^2 - 5u - 36=(u-(-4))(u-(9))=0$, so $u=-4$ or $u=9$. Each positive $u$ gives two real $x$, a negative $u$ gives none. Total: 2." },
  { id: "mat-mk3-15", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 2, marks: 2,
    question: "How many $1$s appear in the binary representation of $45$?",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$7$" },{ key: "C", text: "$4$" },{ key: "D", text: "$3$" },{ key: "E", text: "$5$" }],
    answer: "C", solution: "$45_{10}=101101_2$, which contains $4$ ones." },
  { id: "mat-mk3-16", type: "mcq", testId: "mat", topicId: "mat-trig", difficulty: 2, marks: 2,
    question: "If $\\tan\\theta=\\tfrac{8}{15}$ with $\\theta$ acute, then $\\sin\\theta+\\cos\\theta$ equals:",
    options: [{ key: "A", text: "$\\frac{15}{17}$" },{ key: "B", text: "$1$" },{ key: "C", text: "$\\frac{8}{17}$" },{ key: "D", text: "$\\frac{7}{17}$" },{ key: "E", text: "$\\frac{23}{17}$" }],
    answer: "E", solution: "A $8$–$15$–$17$ right triangle: $\\sin\\theta=\\tfrac{8}{17}$, $\\cos\\theta=\\tfrac{15}{17}$, sum $=\\frac{23}{17}$." },
  { id: "mat-mk3-17", type: "mcq", testId: "mat", topicId: "mat-trig", difficulty: 2, marks: 2,
    question: "How many solutions does $\\sin(4\\theta)=\\tfrac12$ have for $0\\le\\theta<2\\pi$?",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$8$" },{ key: "C", text: "$10$" },{ key: "D", text: "$4$" },{ key: "E", text: "$5$" }],
    answer: "B", solution: "Let $\\phi=4\\theta\\in[0,8\\pi)$. $\\sin\\phi=\\tfrac12$ has $2$ solutions per $2\\pi$, so $2\\times4=8$ in total." },
  { id: "mat-mk3-18", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 2, marks: 2,
    question: "The shortest distance from $(2,3)$ to the line $5x + 12y + 0=0$ is:",
    options: [{ key: "A", text: "$\\frac{72}{13}$" },{ key: "B", text: "$\\frac{46}{13}$" },{ key: "C", text: "$\\frac{33}{13}$" },{ key: "D", text: "$\\frac{9}{5}$" },{ key: "E", text: "$\\frac{59}{13}$" }],
    answer: "B", solution: "Distance $=\\dfrac{|5(2)+12(3)+0|}{\\sqrt{5^2+12^2}}=\\frac{46}{13}$." },
  { id: "mat-mk3-19", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 3,
    question: "The value of $\\log_{2} 7\\times\\log_{7} 8$ is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$5$" },{ key: "C", text: "$2$" },{ key: "D", text: "$4$" },{ key: "E", text: "$1$" }],
    answer: "A", solution: "$\\log_{2}7\\cdot\\log_{7}8=\\dfrac{\\ln 7}{\\ln 2}\\cdot\\dfrac{\\ln 8}{\\ln 7}$; with $7=7^{k}$ the chain gives $\\log_{2}8=3$." },
  { id: "mat-mk3-20", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 2,
    question: "How many distinct real roots does $x^4 - 13x^2 + 36 = 0$ have?",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$3$" },{ key: "C", text: "$2$" },{ key: "D", text: "$0$" },{ key: "E", text: "$4$" }],
    answer: "E", solution: "Let $u=x^2$: $u^2 - 13u + 36=(u-(4))(u-(9))=0$, so $u=4$ or $u=9$. Each positive $u$ gives two real $x$, a negative $u$ gives none. Total: 4." },
  { id: "mat-mk3-21", type: "mcq", testId: "mat", topicId: "mat-logic", difficulty: 1, marks: 2,
    question: "The negation of the statement $x\\ge 0$ is:",
    options: [{ key: "A", text: "$x<0$" },{ key: "B", text: "$x>0$" },{ key: "C", text: "$x\\le 0$" },{ key: "D", text: "$x=0$" },{ key: "E", text: "$x\\ne 0$" }],
    answer: "A", solution: "The negation of $x\\ge 0$ is $x<0$." },
  { id: "mat-mk3-22", type: "mcq", testId: "mat", topicId: "mat-logic", difficulty: 1, marks: 2,
    question: "The negation of the statement $x<7$ is:",
    options: [{ key: "A", text: "$x>7$" },{ key: "B", text: "$x=7$" },{ key: "C", text: "$x\\ge 7$" },{ key: "D", text: "$x\\ne 7$" },{ key: "E", text: "$x\\le 7$" }],
    answer: "C", solution: "The negation of $x<7$ is $x\\ge 7$." },
  { id: "mat-mk3-23", type: "mcq", testId: "mat", topicId: "mat-logic", difficulty: 3, marks: 3,
    question: "For how many integers $n$ with $1\\le n\\le 20$ is $n^2 + 0$ divisible by $4$?",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$10$" },{ key: "C", text: "$12$" },{ key: "D", text: "$11$" },{ key: "E", text: "$8$" }],
    answer: "B", solution: "Checking residues mod $4$, exactly $10$ values of $n$ in $1..20$ satisfy $4\\mid n^2+0$." },
  { id: "mat-mk3-24", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 2,
    question: "The sum to infinity of the geometric series with first term $3$ and common ratio $\\frac{1}{4}$ is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$\\frac{9}{4}$" },{ key: "C", text: "$8$" },{ key: "D", text: "$4$" },{ key: "E", text: "$3$" }],
    answer: "D", solution: "$S_\\infty=\\dfrac{a}{1-r}=\\dfrac{3}{1-\\frac{1}{4}}=4$." },
  { id: "mat-mk3-25", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 2, marks: 2,
    question: "How many $1$s appear in the binary representation of $100$?",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$7$" },{ key: "C", text: "$2$" },{ key: "D", text: "$4$" },{ key: "E", text: "$5$" }],
    answer: "A", solution: "$100_{10}=1100100_2$, which contains $3$ ones." },
];
