// MAT 模拟卷一 —— 全新原创题，专供「完整模拟卷」计时考试使用。
// 对标真实 Oxford MAT 选择部分：25 道五选一（A–E），无负分。真实 MAT 另含 2 道长题（Q26/27），
// 因模考模块仅支持选择题，长题请到 MAT 练习库（mat.ts 的 Part B / STEP 风格大题）单独训练。
// 仅以官方结构与考纲做校准，未照搬任何真题。id 前缀 mat-mk1-*。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const MAT_MK1_MCQ: MCQQuestion[] = [
  { id: "mat-mk1-01", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 2,
    question: "The graph of $y=x^2-4x+7$ has its minimum value at:",
    options: [ {key:"A",text:"$y=1$"},{key:"B",text:"$y=3$"},{key:"C",text:"$y=7$"},{key:"D",text:"$y=-3$"},{key:"E",text:"$y=4$"} ],
    answer: "B", solution: "Completing the square: $x^2-4x+7=(x-2)^2+3$, minimum $y=3$ at $x=2$." },
  { id: "mat-mk1-02", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 2,
    question: "The number of real roots of $x^4-5x^2+4=0$ is:",
    options: [ {key:"A",text:"$0$"},{key:"B",text:"$1$"},{key:"C",text:"$2$"},{key:"D",text:"$3$"},{key:"E",text:"$4$"} ],
    answer: "E", solution: "Let $u=x^2$: $u^2-5u+4=(u-1)(u-4)=0\\Rightarrow u=1,4$, so $x=\\pm1,\\pm2$: four real roots." },
  { id: "mat-mk1-03", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 3,
    question: "The value of $\\log_2 3\\times\\log_3 4\\times\\log_4 8$ is:",
    options: [ {key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$\\log_2 8$"},{key:"D",text:"$\\tfrac32$"},{key:"E",text:"$4$"} ],
    answer: "B", solution: "By the change-of-base chain, the product telescopes to $\\log_2 8=3$." },
  { id: "mat-mk1-04", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 2, marks: 2,
    question: "The gradient of the curve $y=x^3-3x+2$ is zero at exactly:",
    options: [ {key:"A",text:"no points"},{key:"B",text:"one point"},{key:"C",text:"two points"},{key:"D",text:"three points"},{key:"E",text:"all points"} ],
    answer: "C", solution: "$y'=3x^2-3=0\\Rightarrow x=\\pm1$: two stationary points." },
  { id: "mat-mk1-05", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 3, marks: 3,
    question: "$\\displaystyle\\int_1^2\\left(2x+\\frac{1}{x^2}\\right)\\mathrm{d}x$ equals:",
    options: [ {key:"A",text:"$3\\tfrac12$"},{key:"B",text:"$3$"},{key:"C",text:"$4$"},{key:"D",text:"$2\\tfrac12$"},{key:"E",text:"$4\\tfrac12$"} ],
    answer: "A", solution: "$\\int\\left(2x+x^{-2}\\right)dx=x^2-\\tfrac1x$. Evaluating: $(4-\\tfrac12)-(1-1)=\\tfrac72=3\\tfrac12.$" },
  { id: "mat-mk1-06", type: "mcq", testId: "mat", topicId: "mat-trig", difficulty: 3, marks: 3,
    question: "The number of solutions of $2\\sin^2 x=\\cos x+1$ in $0\\le x<2\\pi$ is:",
    options: [ {key:"A",text:"$1$"},{key:"B",text:"$2$"},{key:"C",text:"$3$"},{key:"D",text:"$4$"},{key:"E",text:"$5$"} ],
    answer: "C", solution: "$2(1-\\cos^2x)=\\cos x+1\\Rightarrow 2\\cos^2x+\\cos x-1=0\\Rightarrow(2\\cos x-1)(\\cos x+1)=0$. $\\cos x=\\tfrac12$ gives $x=\\tfrac\\pi3,\\tfrac{5\\pi}3$; $\\cos x=-1$ gives $x=\\pi$: three solutions." },
  { id: "mat-mk1-07", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 2,
    question: "The sum $1+2+4+8+\\cdots+2^{10}$ equals:",
    options: [ {key:"A",text:"$2^{10}$"},{key:"B",text:"$2^{11}-1$"},{key:"C",text:"$2^{11}$"},{key:"D",text:"$2^{10}-1$"},{key:"E",text:"$2^{12}-1$"} ],
    answer: "B", solution: "Geometric sum $\\dfrac{2^{11}-1}{2-1}=2^{11}-1.$" },
  { id: "mat-mk1-08", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 2, marks: 2,
    question: "The line $y=2x+c$ is a tangent to the circle $x^2+y^2=5$. A possible value of $c$ is:",
    options: [ {key:"A",text:"$3$"},{key:"B",text:"$5$"},{key:"C",text:"$\\sqrt5$"},{key:"D",text:"$2\\sqrt5$"},{key:"E",text:"$\\sqrt{10}$"} ],
    answer: "B", solution: "Distance from origin to $2x-y+c=0$ is $\\dfrac{|c|}{\\sqrt5}=\\sqrt5\\Rightarrow|c|=5$; $c=5$ works." },
  { id: "mat-mk1-09", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 3, marks: 3,
    question: "If $x^3-2x^2-5x+6=0$ has a root $x=1$, the other two roots multiply to give:",
    options: [ {key:"A",text:"$-6$"},{key:"B",text:"$6$"},{key:"C",text:"$-5$"},{key:"D",text:"$3$"},{key:"E",text:"$-3$"} ],
    answer: "A", solution: "Product of all three roots $=-6$ (i.e. $-\\tfrac{6}{1}$). Dividing by the root $1$ leaves the other two roots multiplying to $-6.$" },
  { id: "mat-mk1-10", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 3, marks: 3,
    question: "The area enclosed between $y=x$ and $y=x^2$ is:",
    options: [ {key:"A",text:"$\\tfrac16$"},{key:"B",text:"$\\tfrac13$"},{key:"C",text:"$\\tfrac12$"},{key:"D",text:"$1$"},{key:"E",text:"$\\tfrac23$"} ],
    answer: "A", solution: "They meet at $x=0,1$. Area $=\\int_0^1(x-x^2)dx=\\tfrac12-\\tfrac13=\\tfrac16.$" },
  { id: "mat-mk1-11", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 2, marks: 2,
    question: "The solution of $3^{2x-1}=27$ is:",
    options: [ {key:"A",text:"$x=1$"},{key:"B",text:"$x=2$"},{key:"C",text:"$x=\\tfrac32$"},{key:"D",text:"$x=3$"},{key:"E",text:"$x=\\tfrac52$"} ],
    answer: "B", solution: "$27=3^3$, so $2x-1=3\\Rightarrow x=2.$" },
  { id: "mat-mk1-12", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 3, marks: 3,
    question: "A geometric series has sum to infinity $12$ and first term $8$. Its common ratio is:",
    options: [ {key:"A",text:"$\\tfrac13$"},{key:"B",text:"$\\tfrac12$"},{key:"C",text:"$\\tfrac23$"},{key:"D",text:"$\\tfrac14$"},{key:"E",text:"$\\tfrac35$"} ],
    answer: "A", solution: "$\\dfrac{8}{1-r}=12\\Rightarrow 1-r=\\tfrac23\\Rightarrow r=\\tfrac13.$" },
  { id: "mat-mk1-13", type: "mcq", testId: "mat", topicId: "mat-trig", difficulty: 2, marks: 2,
    question: "The maximum value of $5\\cos x-12\\sin x$ is:",
    options: [ {key:"A",text:"$7$"},{key:"B",text:"$13$"},{key:"C",text:"$17$"},{key:"D",text:"$\\sqrt{17}$"},{key:"E",text:"$12$"} ],
    answer: "B", solution: "Amplitude $=\\sqrt{5^2+12^2}=13$, so the maximum is $13.$" },
  { id: "mat-mk1-14", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 3, marks: 3,
    question: "How many ways can $5$ distinct books be arranged on a shelf so that two particular books are together?",
    options: [ {key:"A",text:"$24$"},{key:"B",text:"$48$"},{key:"C",text:"$120$"},{key:"D",text:"$60$"},{key:"E",text:"$12$"} ],
    answer: "B", solution: "Glue the two books (treat as one block): $4!$ arrangements, $\\times 2!$ for their internal order $=24\\times2=48.$" },
  { id: "mat-mk1-15", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 3, marks: 3,
    question: "The set of values of $k$ for which $x^2+kx+k=0$ has no real roots is:",
    options: [ {key:"A",text:"$0<k<4$"},{key:"B",text:"$k<0$ or $k>4$"},{key:"C",text:"$-4<k<0$"},{key:"D",text:"$k>4$"},{key:"E",text:"$0\\le k\\le4$"} ],
    answer: "A", solution: "No real roots $\\Leftrightarrow$ discriminant $<0$: $k^2-4k<0\\Rightarrow k(k-4)<0\\Rightarrow 0<k<4.$" },
  { id: "mat-mk1-16", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 3, marks: 3,
    question: "The tangent to $y=x^2$ at $x=a$ passes through the point $(0,-1)$. The positive value of $a$ is:",
    options: [ {key:"A",text:"$1$"},{key:"B",text:"$\\tfrac12$"},{key:"C",text:"$2$"},{key:"D",text:"$\\sqrt2$"},{key:"E",text:"$\\tfrac1{\\sqrt2}$"} ],
    answer: "A", solution: "Tangent at $x=a$: $y=2a x-a^2$. Through $(0,-1)$: $-a^2=-1\\Rightarrow a=1$ (positive)." },
  { id: "mat-mk1-17", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 2, marks: 2,
    question: "The distance between the points $(1,2)$ and $(4,6)$ is:",
    options: [ {key:"A",text:"$5$"},{key:"B",text:"$7$"},{key:"C",text:"$\\sqrt{7}$"},{key:"D",text:"$\\sqrt{25}$"},{key:"E",text:"$25$"} ],
    answer: "A", solution: "$\\sqrt{(4-1)^2+(6-2)^2}=\\sqrt{9+16}=\\sqrt{25}=5$ (simplest form)." },
  { id: "mat-mk1-18", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 3,
    question: "The number of real solutions of $2^{2x}-6\\cdot2^{x}+8=0$ is:",
    options: [ {key:"A",text:"$0$"},{key:"B",text:"$1$"},{key:"C",text:"$2$"},{key:"D",text:"$3$"},{key:"E",text:"$4$"} ],
    answer: "C", solution: "Let $y=2^x$: $y^2-6y+8=(y-2)(y-4)=0\\Rightarrow y=2,4$, both positive, so $x=1,2$: two solutions." },
  { id: "mat-mk1-19", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 3, marks: 3,
    question: "How many $3$-digit numbers have all digits distinct and are even?",
    options: [ {key:"A",text:"$328$"},{key:"B",text:"$360$"},{key:"C",text:"$320$"},{key:"D",text:"$300$"},{key:"E",text:"$288$"} ],
    answer: "A", solution: "Units $=0$: $9\\times8=72$. Units $\\in\\{2,4,6,8\\}$ (4 choices): hundreds $\\ne0,\\ne$units $=8$, tens $=8$ remaining: $4\\times8\\times8=256$. Total $72+256=328.$" },
  { id: "mat-mk1-20", type: "mcq", testId: "mat", topicId: "mat-trig", difficulty: 3, marks: 3,
    question: "If $\\tan\\theta=\\tfrac34$ and $\\theta$ is acute, then $\\sin\\theta+\\cos\\theta$ equals:",
    options: [ {key:"A",text:"$\\tfrac{7}{5}$"},{key:"B",text:"$1$"},{key:"C",text:"$\\tfrac{6}{5}$"},{key:"D",text:"$\\tfrac{5}{7}$"},{key:"E",text:"$\\tfrac{12}{5}$"} ],
    answer: "A", solution: "A $3$–$4$–$5$ triangle: $\\sin\\theta=\\tfrac35$, $\\cos\\theta=\\tfrac45$, sum $=\\tfrac75.$" },
  { id: "mat-mk1-21", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 3, marks: 3,
    question: "The function $f(x)=x^3-3x^2+3x+1$ is:",
    options: [ {key:"A",text:"increasing for all $x$"},{key:"B",text:"decreasing for all $x$"},{key:"C",text:"increasing then decreasing"},{key:"D",text:"decreasing then increasing"},{key:"E",text:"constant"} ],
    answer: "A", solution: "$f'(x)=3x^2-6x+3=3(x-1)^2\\ge0$ for all $x$, so $f$ is increasing (never decreasing)." },
  { id: "mat-mk1-22", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 2,
    question: "When $x^3+2x^2-x+5$ is divided by $(x-1)$, the remainder is:",
    options: [ {key:"A",text:"$5$"},{key:"B",text:"$7$"},{key:"C",text:"$6$"},{key:"D",text:"$8$"},{key:"E",text:"$3$"} ],
    answer: "B", solution: "By the remainder theorem, remainder $=f(1)=1+2-1+5=7.$" },
  { id: "mat-mk1-23", type: "mcq", testId: "mat", topicId: "mat-logic", difficulty: 3, marks: 3,
    question: "For how many integers $n$ with $1\\le n\\le 20$ is $n^2+3$ divisible by $4$?",
    options: [ {key:"A",text:"$0$"},{key:"B",text:"$5$"},{key:"C",text:"$10$"},{key:"D",text:"$15$"},{key:"E",text:"$20$"} ],
    answer: "C", solution: "$n^2\\equiv1\\pmod4$ when $n$ is odd, giving $n^2+3\\equiv0$; when $n$ even, $n^2\\equiv0$, giving $3$. So it works for all odd $n$: there are $10$ in $1..20.$" },
  { id: "mat-mk1-24", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 3, marks: 3,
    question: "The coefficient of $x^4$ in $(1+x)^6+(1+x)^5$ is:",
    options: [ {key:"A",text:"$15$"},{key:"B",text:"$20$"},{key:"C",text:"$25$"},{key:"D",text:"$30$"},{key:"E",text:"$35$"} ],
    answer: "B", solution: "The coefficient of $x^4$ is $\\binom{6}{4}+\\binom{5}{4}=15+5=20.$" },
  { id: "mat-mk1-25", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 3, marks: 3,
    question: "The shortest distance from the point $(3,4)$ to the line $3x+4y-10=0$ is:",
    options: [ {key:"A",text:"$3$"},{key:"B",text:"$2$"},{key:"C",text:"$5$"},{key:"D",text:"$\\tfrac{9}{5}$"},{key:"E",text:"$\\tfrac{7}{5}$"} ],
    answer: "A", solution: "Distance $=\\dfrac{|3(3)+4(4)-10|}{\\sqrt{3^2+4^2}}=\\dfrac{|9+16-10|}{5}=\\dfrac{15}{5}=3.$" },
];
