// MAT 模拟卷2 —— 生成器出题，sympy 计算答案。25 道五选一，id 前缀 mat-mk2-*。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const MAT_MK2_MCQ: MCQQuestion[] = [
  { id: "mat-mk2-01", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 2, marks: 2,
    question: "How many $1$s appear in the binary representation of $170$?",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$3$" },{ key: "C", text: "$4$" },{ key: "D", text: "$5$" },{ key: "E", text: "$6$" }],
    answer: "C", solution: "$170_{10}=10101010_2$, which contains $4$ ones." },
  { id: "mat-mk2-02", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 2,
    question: "The sum $1+2+4+\\cdots+2^{9}$ equals:",
    options: [{ key: "A", text: "$2^{9}-1$" },{ key: "B", text: "$2^{10}-1$" },{ key: "C", text: "$2^{9}$" },{ key: "D", text: "$2^{10}$" },{ key: "E", text: "$2^{11}-1$" }],
    answer: "B", solution: "Geometric series with ratio $2$: sum $=\\dfrac{2^{10}-1}{2-1}=2^{10}-1=1023$." },
  { id: "mat-mk2-03", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 2,
    question: "The sum $1+2+4+\\cdots+2^{10}$ equals:",
    options: [{ key: "A", text: "$2^{11}$" },{ key: "B", text: "$2^{12}-1$" },{ key: "C", text: "$2^{10}-1$" },{ key: "D", text: "$2^{11}-1$" },{ key: "E", text: "$2^{10}$" }],
    answer: "D", solution: "Geometric series with ratio $2$: sum $=\\dfrac{2^{11}-1}{2-1}=2^{11}-1=2047$." },
  { id: "mat-mk2-04", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 3,
    question: "The sum of the real solutions of $4^{x} - 18\\cdot 2^{x} + 32 = 0$ is:",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$4$" },{ key: "C", text: "$3$" },{ key: "D", text: "$5$" },{ key: "E", text: "$6$" }],
    answer: "D", solution: "Let $y=2^x$: $y^2-18y+32=0\\Rightarrow y=2^{1},2^{4}$, so $x=1,4$; sum $=5$." },
  { id: "mat-mk2-05", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 3, marks: 3,
    question: "The coefficient of $x^{3}$ in $(1+x)^{8}+(1+x)^{5}$ is:",
    options: [{ key: "A", text: "$65$" },{ key: "B", text: "$67$" },{ key: "C", text: "$10$" },{ key: "D", text: "$66$" },{ key: "E", text: "$56$" }],
    answer: "D", solution: "$\\binom{8}{3}+\\binom{5}{3}=56+10=66$." },
  { id: "mat-mk2-06", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 2,
    question: "When $x^{3} + x^{2} - 4 x + 6$ is divided by $(x - 3)$, the remainder is:",
    options: [{ key: "A", text: "$32$" },{ key: "B", text: "$29$" },{ key: "C", text: "$28$" },{ key: "D", text: "$30$" },{ key: "E", text: "$31$" }],
    answer: "D", solution: "By the remainder theorem, remainder $=f(3)=30$." },
  { id: "mat-mk2-07", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 2,
    question: "The minimum value of $y=x^2 + 10x + 30$ is:",
    options: [{ key: "A", text: "$-20$" },{ key: "B", text: "$30$" },{ key: "C", text: "$6$" },{ key: "D", text: "$4$" },{ key: "E", text: "$5$" }],
    answer: "E", solution: "Complete the square: $x^2+10x+30=(x+5)^2 + 5$, minimum $5$." },
  { id: "mat-mk2-08", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 2,
    question: "The sum to infinity of the geometric series with first term $2$ and common ratio $\\frac{1}{3}$ is:",
    options: [{ key: "A", text: "$\\frac{4}{3}$" },{ key: "B", text: "$4$" },{ key: "C", text: "$3$" },{ key: "D", text: "$6$" },{ key: "E", text: "$2$" }],
    answer: "C", solution: "$S_\\infty=\\dfrac{a}{1-r}=\\dfrac{2}{1-\\frac{1}{3}}=3$." },
  { id: "mat-mk2-09", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 2, marks: 2,
    question: "Outer loop $i=1,\\dots,7$; for each $i$ the inner loop runs $j=1,\\dots,i$. How many times does the inner body run in total?",
    options: [{ key: "A", text: "$49$" },{ key: "B", text: "$21$" },{ key: "C", text: "$28$" },{ key: "D", text: "$27$" },{ key: "E", text: "$29$" }],
    answer: "C", solution: "Total $=1+2+\\cdots+7=\\dfrac{7\\cdot8}{2}=28$." },
  { id: "mat-mk2-10", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 2,
    question: "The sum $1+2+4+\\cdots+2^{6}$ equals:",
    options: [{ key: "A", text: "$2^{6}$" },{ key: "B", text: "$2^{6}-1$" },{ key: "C", text: "$2^{8}-1$" },{ key: "D", text: "$2^{7}$" },{ key: "E", text: "$2^{7}-1$" }],
    answer: "E", solution: "Geometric series with ratio $2$: sum $=\\dfrac{2^{7}-1}{2-1}=2^{7}-1=127$." },
  { id: "mat-mk2-11", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 2,
    question: "The sum to infinity of the geometric series with first term $1$ and common ratio $\\frac{1}{2}$ is:",
    options: [{ key: "A", text: "$\\frac{1}{2}$" },{ key: "B", text: "$1$" },{ key: "C", text: "$2$" },{ key: "D", text: "$4$" },{ key: "E", text: "$3$" }],
    answer: "C", solution: "$S_\\infty=\\dfrac{a}{1-r}=\\dfrac{1}{1-\\frac{1}{2}}=2$." },
  { id: "mat-mk2-12", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 2,
    question: "How many distinct real roots does $x^4 + 5x^2 + 4 = 0$ have?",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$3$" },{ key: "C", text: "$1$" },{ key: "D", text: "$0$" },{ key: "E", text: "$2$" }],
    answer: "D", solution: "Let $u=x^2$: $u^2 + 5u + 4=(u-(-4))(u-(-1))=0$, so $u=-4$ or $u=-1$. Each positive $u$ gives two real $x$, a negative $u$ gives none. Total: 0." },
  { id: "mat-mk2-13", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 3,
    question: "The value of $\\log_{3} 4\\times\\log_{4} 9$ is:",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$4$" },{ key: "C", text: "$3$" },{ key: "D", text: "$1$" },{ key: "E", text: "$2$" }],
    answer: "E", solution: "$\\log_{3}4\\cdot\\log_{4}9=\\dfrac{\\ln 4}{\\ln 3}\\cdot\\dfrac{\\ln 9}{\\ln 4}$; with $4=4^{k}$ the chain gives $\\log_{3}9=2$." },
  { id: "mat-mk2-14", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 2, marks: 2,
    question: "How many $1$s appear in the binary representation of $200$?",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$3$" },{ key: "C", text: "$4$" },{ key: "D", text: "$5$" },{ key: "E", text: "$8$" }],
    answer: "B", solution: "$200_{10}=11001000_2$, which contains $3$ ones." },
  { id: "mat-mk2-15", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 3,
    question: "The sum of the real solutions of $4^{x} - 10\\cdot 2^{x} + 16 = 0$ is:",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$5$" },{ key: "C", text: "$4$" },{ key: "D", text: "$2$" },{ key: "E", text: "$3$" }],
    answer: "C", solution: "Let $y=2^x$: $y^2-10y+16=0\\Rightarrow y=2^{1},2^{3}$, so $x=1,3$; sum $=4$." },
  { id: "mat-mk2-16", type: "mcq", testId: "mat", topicId: "mat-logic", difficulty: 3, marks: 3,
    question: "For how many integers $n$ with $1\\le n\\le 30$ is $n^2 + 0$ divisible by $3$?",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$12$" },{ key: "C", text: "$11$" },{ key: "D", text: "$8$" },{ key: "E", text: "$10$" }],
    answer: "E", solution: "Checking residues mod $3$, exactly $10$ values of $n$ in $1..30$ satisfy $3\\mid n^2+0$." },
  { id: "mat-mk2-17", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 2,
    question: "How many distinct real roots does $x^4 - 5x^2 + 4 = 0$ have?",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$2$" },{ key: "C", text: "$4$" },{ key: "D", text: "$1$" },{ key: "E", text: "$0$" }],
    answer: "C", solution: "Let $u=x^2$: $u^2 - 5u + 4=(u-(1))(u-(4))=0$, so $u=1$ or $u=4$. Each positive $u$ gives two real $x$, a negative $u$ gives none. Total: 4." },
  { id: "mat-mk2-18", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 2,
    question: "The sum $1+2+4+\\cdots+2^{7}$ equals:",
    options: [{ key: "A", text: "$2^{9}-1$" },{ key: "B", text: "$2^{8}$" },{ key: "C", text: "$2^{8}-1$" },{ key: "D", text: "$2^{7}$" },{ key: "E", text: "$2^{7}-1$" }],
    answer: "C", solution: "Geometric series with ratio $2$: sum $=\\dfrac{2^{8}-1}{2-1}=2^{8}-1=255$." },
  { id: "mat-mk2-19", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 2, marks: 2,
    question: "Evaluate $\\displaystyle\\int_{0}^{2} 6 x^{2}\\,dx$.",
    options: [{ key: "A", text: "$32$" },{ key: "B", text: "$8$" },{ key: "C", text: "$\\frac{95}{6}$" },{ key: "D", text: "$16$" },{ key: "E", text: "$\\frac{97}{6}$" }],
    answer: "D", solution: "$\\int 6 x^{2}\\,dx$ evaluated from $0$ to $2$ gives $16$." },
  { id: "mat-mk2-20", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 2, marks: 2,
    question: "Evaluate $\\displaystyle\\int_{1}^{2} 2 x\\,dx$.",
    options: [{ key: "A", text: "$\\frac{19}{6}$" },{ key: "B", text: "$6$" },{ key: "C", text: "$\\frac{17}{6}$" },{ key: "D", text: "$3$" },{ key: "E", text: "$\\frac{3}{2}$" }],
    answer: "D", solution: "$\\int 2 x\\,dx$ evaluated from $1$ to $2$ gives $3$." },
  { id: "mat-mk2-21", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 2,
    question: "The sum $1+2+4+\\cdots+2^{5}$ equals:",
    options: [{ key: "A", text: "$2^{5}$" },{ key: "B", text: "$2^{7}-1$" },{ key: "C", text: "$2^{5}-1$" },{ key: "D", text: "$2^{6}-1$" },{ key: "E", text: "$2^{6}$" }],
    answer: "D", solution: "Geometric series with ratio $2$: sum $=\\dfrac{2^{6}-1}{2-1}=2^{6}-1=63$." },
  { id: "mat-mk2-22", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 3, marks: 3,
    question: "The radius of the circle $x^2+y^2 - 4x - 6y + 4=0$ is:",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$4$" },{ key: "C", text: "$3$" },{ key: "D", text: "$\\sqrt{10}$" },{ key: "E", text: "$\\sqrt{7}$" }],
    answer: "C", solution: "Centre $(2,3)$, radius $=\\sqrt{(2)^2+(3)^2-(4)}=\\sqrt{9}=3$." },
  { id: "mat-mk2-23", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 3, marks: 3,
    question: "The radius of the circle $x^2+y^2 + 0x + 0y - 9=0$ is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$\\sqrt{7}$" },{ key: "C", text: "$\\sqrt{10}$" },{ key: "D", text: "$4$" },{ key: "E", text: "$9$" }],
    answer: "A", solution: "Centre $(0,0)$, radius $=\\sqrt{(0)^2+(0)^2-(-9)}=\\sqrt{9}=3$." },
  { id: "mat-mk2-24", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 3,
    question: "The value of $\\log_{2} 3\\times\\log_{3} 16$ is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$4$" },{ key: "C", text: "$2$" },{ key: "D", text: "$6$" },{ key: "E", text: "$5$" }],
    answer: "B", solution: "$\\log_{2}3\\cdot\\log_{3}16=\\dfrac{\\ln 3}{\\ln 2}\\cdot\\dfrac{\\ln 16}{\\ln 3}$; with $3=3^{k}$ the chain gives $\\log_{2}16=4$." },
  { id: "mat-mk2-25", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 3, marks: 3,
    question: "The radius of the circle $x^2+y^2 - 8x + 6y + 0=0$ is:",
    options: [{ key: "A", text: "$25$" },{ key: "B", text: "$\\sqrt{23}$" },{ key: "C", text: "$\\sqrt{26}$" },{ key: "D", text: "$5$" },{ key: "E", text: "$6$" }],
    answer: "D", solution: "Centre $(4,-3)$, radius $=\\sqrt{(4)^2+(-3)^2-(0)}=\\sqrt{25}=5$." },
];
