// PAT 模拟卷2 —— 25 题五选一，id 前缀 pat-mk2-*。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const PAT_MK2_MCQ: MCQQuestion[] = [
  { id: "pat-mk2-01", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "Evaluate $\\displaystyle\\int_{1}^{4} 1x\\,dx$ (e.g. work done by a force $F=1x$):",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$\\frac{17}{2}$" },{ key: "C", text: "$4$" },{ key: "D", text: "$\\frac{15}{2}$" },{ key: "E", text: "$3$" }],
    answer: "D", solution: "$\\int_{1}^{4}1x\\,dx=\\left[\\tfrac{1}{2}x^2\\right]_{1}^{4}=\\frac{15}{2}.$" },
  { id: "pat-mk2-02", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "A current of $2\\,\\text{A}$ flows for $5\\,\\text{s}$. The charge transferred is:",
    options: [{ key: "A", text: "$\\frac{5}{2}\\,\\text{C}$" },{ key: "B", text: "$7\\,\\text{C}$" },{ key: "C", text: "$5\\,\\text{C}$" },{ key: "D", text: "$10\\,\\text{C}$" },{ key: "E", text: "$20\\,\\text{C}$" }],
    answer: "D", solution: "$Q=It=2\\times5=10\\,$C." },
  { id: "pat-mk2-03", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "A $2\\,\\text{kg}$ trolley moving at $9\\,\\text{m/s}$ collides and sticks to a stationary $1\\,\\text{kg}$ trolley. Their common velocity is:",
    options: [{ key: "A", text: "$7\\,\\text{m/s}$" },{ key: "B", text: "$6\\,\\text{m/s}$" },{ key: "C", text: "$18\\,\\text{m/s}$" },{ key: "D", text: "$\\frac{9}{2}\\,\\text{m/s}$" },{ key: "E", text: "$9\\,\\text{m/s}$" }],
    answer: "B", solution: "Momentum: $m_1u_1=(m_1+m_2)v\\Rightarrow v=\\dfrac{2\\cdot9}{3}=6\\,$m/s." },
  { id: "pat-mk2-04", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 1, marks: 4,
    question: "The scalar (dot) product $(2\\,\\mathbf{i}+3\\,\\mathbf{j})\\cdot(4\\,\\mathbf{i}+1\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$11$" },{ key: "C", text: "$13$" },{ key: "D", text: "$10$" },{ key: "E", text: "$14$" }],
    answer: "B", solution: "$\\mathbf{a}\\cdot\\mathbf{b}=2\\cdot4+3\\cdot1=11.$" },
  { id: "pat-mk2-05", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 3, marks: 4,
    question: "A particle has momentum $6\\times10^{-24}\\,\\text{kg·m/s}$. With $h=6.6\\times10^{-34}$, its de Broglie wavelength (in $10^{-10}\\,\\text{m}$) is:",
    options: [{ key: "A", text: "$\\frac{10}{11}$" },{ key: "B", text: "$\\frac{1}{11}$" },{ key: "C", text: "$\\frac{11}{10}$" },{ key: "D", text: "$396$" },{ key: "E", text: "$\\frac{11}{5}$" }],
    answer: "C", solution: "$\\lambda=\\dfrac{h}{p}=\\dfrac{6.6\\times10^{-34}}{6\\times10^{-24}}=\\frac{11}{10}\\times10^{-10}\\,$m." },
  { id: "pat-mk2-06", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 1, marks: 4,
    question: "After $4$ half-lives, the fraction of a radioactive sample remaining is:",
    options: [{ key: "A", text: "$\\frac{1}{4}$" },{ key: "B", text: "$\\frac{1}{16}$" },{ key: "C", text: "$\\frac{1}{5}$" },{ key: "D", text: "$\\frac{1}{8}$" },{ key: "E", text: "$\\frac{15}{16}$" }],
    answer: "B", solution: "Remaining fraction $=\\left(\\tfrac12\\right)^{4}=\\frac{1}{16}.$" },
  { id: "pat-mk2-07", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "The kinetic energy of a $2\\,\\text{kg}$ mass moving at $3\\,\\text{m/s}$ is:",
    options: [{ key: "A", text: "$18\\,\\text{J}$" },{ key: "B", text: "$3\\,\\text{J}$" },{ key: "C", text: "$6\\,\\text{J}$" },{ key: "D", text: "$\\frac{9}{2}\\,\\text{J}$" },{ key: "E", text: "$9\\,\\text{J}$" }],
    answer: "E", solution: "$E_k=\\tfrac12 mv^2=\\tfrac12(2)(3)^2=9\\,$J." },
  { id: "pat-mk2-08", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 1, marks: 4,
    question: "The magnitude of the vector $(7\\,\\mathbf{i}+24\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$31$" },{ key: "B", text: "$25$" },{ key: "C", text: "$17$" },{ key: "D", text: "$26$" },{ key: "E", text: "$\\frac{31}{2}$" }],
    answer: "B", solution: "$|\\mathbf{v}|=\\sqrt{7^2+24^2}=25.$" },
  { id: "pat-mk2-09", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "Heating $3\\,\\text{kg}$ of a substance ($c=500\\,\\text{J/kg·K}$) by $4\\,\\text{K}$ requires energy:",
    options: [{ key: "A", text: "$3000\\,\\text{J}$" },{ key: "B", text: "$12000\\,\\text{J}$" },{ key: "C", text: "$6000\\,\\text{J}$" },{ key: "D", text: "$375\\,\\text{J}$" },{ key: "E", text: "$1504\\,\\text{J}$" }],
    answer: "C", solution: "$Q=mc\\Delta T=3\\cdot500\\cdot4=6000\\,$J." },
  { id: "pat-mk2-10", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "In a potential divider, $9\\,\\text{V}$ is across $3\\,\\Omega$ and $6\\,\\Omega$ in series. The voltage across $6\\,\\Omega$ is:",
    options: [{ key: "A", text: "$3\\,\\text{V}$" },{ key: "B", text: "$6\\,\\text{V}$" },{ key: "C", text: "$\\frac{9}{2}\\,\\text{V}$" },{ key: "D", text: "$18\\,\\text{V}$" },{ key: "E", text: "$7\\,\\text{V}$" }],
    answer: "B", solution: "$V_2=V_{in}\\dfrac{R_2}{R_1+R_2}=9\\cdot\\dfrac{6}{9}=6\\,$V." },
  { id: "pat-mk2-11", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "An object is $24\\,\\text{cm}$ from a converging lens of focal length $12\\,\\text{cm}$. The image distance is:",
    options: [{ key: "A", text: "$26\\,\\text{cm}$" },{ key: "B", text: "$8\\,\\text{cm}$" },{ key: "C", text: "$24\\,\\text{cm}$" },{ key: "D", text: "$12\\,\\text{cm}$" },{ key: "E", text: "$36\\,\\text{cm}$" }],
    answer: "C", solution: "$\\dfrac1f=\\dfrac1u+\\dfrac1v\\Rightarrow v=\\dfrac{fu}{u-f}=\\dfrac{12\\cdot24}{12}=24\\,$cm." },
  { id: "pat-mk2-12", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "A fixed mass of gas at constant temperature has $P_1=2$, $V_1=6$. When pressure becomes $P_2=3$, the new volume is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$9$" },{ key: "C", text: "$4$" },{ key: "D", text: "$5$" },{ key: "E", text: "$36$" }],
    answer: "C", solution: "Boyle's law $P_1V_1=P_2V_2\\Rightarrow V_2=\\dfrac{2\\cdot6}{3}=4.$" },
  { id: "pat-mk2-13", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "In a potential divider, $10\\,\\text{V}$ is across $1\\,\\Omega$ and $4\\,\\Omega$ in series. The voltage across $4\\,\\Omega$ is:",
    options: [{ key: "A", text: "$2\\,\\text{V}$" },{ key: "B", text: "$6\\,\\text{V}$" },{ key: "C", text: "$40\\,\\text{V}$" },{ key: "D", text: "$5\\,\\text{V}$" },{ key: "E", text: "$8\\,\\text{V}$" }],
    answer: "E", solution: "$V_2=V_{in}\\dfrac{R_2}{R_1+R_2}=10\\cdot\\dfrac{4}{5}=8\\,$V." },
  { id: "pat-mk2-14", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "In a potential divider, $12\\,\\text{V}$ is across $2\\,\\Omega$ and $4\\,\\Omega$ in series. The voltage across $4\\,\\Omega$ is:",
    options: [{ key: "A", text: "$9\\,\\text{V}$" },{ key: "B", text: "$8\\,\\text{V}$" },{ key: "C", text: "$4\\,\\text{V}$" },{ key: "D", text: "$6\\,\\text{V}$" },{ key: "E", text: "$24\\,\\text{V}$" }],
    answer: "B", solution: "$V_2=V_{in}\\dfrac{R_2}{R_1+R_2}=12\\cdot\\dfrac{4}{6}=8\\,$V." },
  { id: "pat-mk2-15", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "A photon has frequency $8\\times10^{14}\\,\\text{Hz}$. Using $h=6.6\\times10^{-34}\\,\\text{J·s}$, its energy (in $10^{-20}\\,\\text{J}$) is:",
    options: [{ key: "A", text: "$528$" },{ key: "B", text: "$\\frac{400}{33}$" },{ key: "C", text: "$\\frac{33}{4}$" },{ key: "D", text: "$\\frac{264}{5}$" },{ key: "E", text: "$\\frac{528}{5}$" }],
    answer: "D", solution: "$E=hf=6.6\\times10^{-34}\\times8\\times10^{14}=\\frac{264}{5}\\times10^{-20}\\,$J." },
  { id: "pat-mk2-16", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "Light travels inside a medium of refractive index $\\frac{3}{2}$ towards air. The sine of the critical angle is:",
    options: [{ key: "A", text: "$\\frac{3}{4}$" },{ key: "B", text: "$\\frac{1}{3}$" },{ key: "C", text: "$\\frac{2}{3}$" },{ key: "D", text: "$\\frac{23}{30}$" },{ key: "E", text: "$\\frac{3}{2}$" }],
    answer: "C", solution: "At the critical angle $\\sin\\theta_c=\\dfrac{1}{n}=\\dfrac{1}{\\frac{3}{2}}=\\frac{2}{3}.$" },
  { id: "pat-mk2-17", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "A $2\\,\\text{kg}$ mass moves in a circle of radius $5\\,\\text{m}$ at $10\\,\\text{m/s}$. The centripetal force is:",
    options: [{ key: "A", text: "$4\\,\\text{N}$" },{ key: "B", text: "$41\\,\\text{N}$" },{ key: "C", text: "$20\\,\\text{N}$" },{ key: "D", text: "$40\\,\\text{N}$" },{ key: "E", text: "$200\\,\\text{N}$" }],
    answer: "D", solution: "$F=\\dfrac{mv^2}{r}=\\dfrac{2\\cdot10^2}{5}=40\\,$N." },
  { id: "pat-mk2-18", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "An object is $20\\,\\text{cm}$ from a converging lens of focal length $10\\,\\text{cm}$. The image distance is:",
    options: [{ key: "A", text: "$22\\,\\text{cm}$" },{ key: "B", text: "$10\\,\\text{cm}$" },{ key: "C", text: "$30\\,\\text{cm}$" },{ key: "D", text: "$20\\,\\text{cm}$" },{ key: "E", text: "$\\frac{20}{3}\\,\\text{cm}$" }],
    answer: "D", solution: "$\\dfrac1f=\\dfrac1u+\\dfrac1v\\Rightarrow v=\\dfrac{fu}{u-f}=\\dfrac{10\\cdot20}{10}=20\\,$cm." },
  { id: "pat-mk2-19", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 1, marks: 4,
    question: "The magnitude of the vector $(6\\,\\mathbf{i}+8\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$10$" },{ key: "C", text: "$14$" },{ key: "D", text: "$7$" },{ key: "E", text: "$11$" }],
    answer: "B", solution: "$|\\mathbf{v}|=\\sqrt{6^2+8^2}=10.$" },
  { id: "pat-mk2-20", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "Light travels inside a medium of refractive index $\\frac{5}{3}$ towards air. The sine of the critical angle is:",
    options: [{ key: "A", text: "$\\frac{3}{10}$" },{ key: "B", text: "$\\frac{2}{5}$" },{ key: "C", text: "$\\frac{5}{6}$" },{ key: "D", text: "$\\frac{3}{5}$" },{ key: "E", text: "$\\frac{5}{3}$" }],
    answer: "D", solution: "At the critical angle $\\sin\\theta_c=\\dfrac{1}{n}=\\dfrac{1}{\\frac{5}{3}}=\\frac{3}{5}.$" },
  { id: "pat-mk2-21", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "A particle's position is $s(t)=2 x^{3} - 4 x$. Its velocity at $t=1$ is:",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$-2$" },{ key: "C", text: "$3$" },{ key: "D", text: "$12$" },{ key: "E", text: "$0$" }],
    answer: "A", solution: "$v=\\dfrac{ds}{dt}=6 x^{2} - 4$; at $t=1$, $v=2.$" },
  { id: "pat-mk2-22", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "A fixed mass of gas at constant temperature has $P_1=3$, $V_1=4$. When pressure becomes $P_2=6$, the new volume is:",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$2$" },{ key: "C", text: "$8$" },{ key: "D", text: "$72$" },{ key: "E", text: "$3$" }],
    answer: "B", solution: "Boyle's law $P_1V_1=P_2V_2\\Rightarrow V_2=\\dfrac{3\\cdot4}{6}=2.$" },
  { id: "pat-mk2-23", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "A $3\\,\\text{kg}$ mass moves in a circle of radius $4\\,\\text{m}$ at $2\\,\\text{m/s}$. The centripetal force is:",
    options: [{ key: "A", text: "$12\\,\\text{N}$" },{ key: "B", text: "$3\\,\\text{N}$" },{ key: "C", text: "$\\frac{3}{2}\\,\\text{N}$" },{ key: "D", text: "$1\\,\\text{N}$" },{ key: "E", text: "$4\\,\\text{N}$" }],
    answer: "B", solution: "$F=\\dfrac{mv^2}{r}=\\dfrac{3\\cdot2^2}{4}=3\\,$N." },
  { id: "pat-mk2-24", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "The power dissipated by a $8\\,\\Omega$ resistor across $24\\,\\text{V}$ is:",
    options: [{ key: "A", text: "$3\\,\\text{W}$" },{ key: "B", text: "$576\\,\\text{W}$" },{ key: "C", text: "$192\\,\\text{W}$" },{ key: "D", text: "$72\\,\\text{W}$" },{ key: "E", text: "$36\\,\\text{W}$" }],
    answer: "D", solution: "$P=\\dfrac{V^2}{R}=\\dfrac{24^2}{8}=72\\,$W." },
  { id: "pat-mk2-25", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "An object is $60\\,\\text{cm}$ from a converging lens of focal length $20\\,\\text{cm}$. The image distance is:",
    options: [{ key: "A", text: "$30\\,\\text{cm}$" },{ key: "B", text: "$32\\,\\text{cm}$" },{ key: "C", text: "$40\\,\\text{cm}$" },{ key: "D", text: "$80\\,\\text{cm}$" },{ key: "E", text: "$15\\,\\text{cm}$" }],
    answer: "A", solution: "$\\dfrac1f=\\dfrac1u+\\dfrac1v\\Rightarrow v=\\dfrac{fu}{u-f}=\\dfrac{20\\cdot60}{40}=30\\,$cm." },
];
