// PAT 模拟卷1 —— 25 题五选一，id 前缀 pat-mk1-*。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const PAT_MK1_MCQ: MCQQuestion[] = [
  { id: "pat-mk1-01", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "A fixed mass of gas at constant temperature has $P_1=4$, $V_1=3$. When pressure becomes $P_2=2$, the new volume is:",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$6$" },{ key: "C", text: "$5$" },{ key: "D", text: "$\\frac{3}{2}$" },{ key: "E", text: "$24$" }],
    answer: "B", solution: "Boyle's law $P_1V_1=P_2V_2\\Rightarrow V_2=\\dfrac{4\\cdot3}{2}=6.$" },
  { id: "pat-mk1-02", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 1, marks: 4,
    question: "The scalar (dot) product $(3\\,\\mathbf{i}+-2\\,\\mathbf{j})\\cdot(4\\,\\mathbf{i}+5\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$10$" },{ key: "C", text: "$4$" },{ key: "D", text: "$2$" },{ key: "E", text: "$22$" }],
    answer: "D", solution: "$\\mathbf{a}\\cdot\\mathbf{b}=3\\cdot4+-2\\cdot5=2.$" },
  { id: "pat-mk1-03", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "The kinetic energy of a $2\\,\\text{kg}$ mass moving at $6\\,\\text{m/s}$ is:",
    options: [{ key: "A", text: "$12\\,\\text{J}$" },{ key: "B", text: "$72\\,\\text{J}$" },{ key: "C", text: "$36\\,\\text{J}$" },{ key: "D", text: "$18\\,\\text{J}$" },{ key: "E", text: "$6\\,\\text{J}$" }],
    answer: "C", solution: "$E_k=\\tfrac12 mv^2=\\tfrac12(2)(6)^2=36\\,$J." },
  { id: "pat-mk1-04", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 1, marks: 4,
    question: "The magnitude of the vector $(5\\,\\mathbf{i}+12\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$14$" },{ key: "B", text: "$17$" },{ key: "C", text: "$13$" },{ key: "D", text: "$7$" },{ key: "E", text: "$\\frac{17}{2}$" }],
    answer: "C", solution: "$|\\mathbf{v}|=\\sqrt{5^2+12^2}=13.$" },
  { id: "pat-mk1-05", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "An object is $30\\,\\text{cm}$ from a converging lens of focal length $20\\,\\text{cm}$. The image distance is:",
    options: [{ key: "A", text: "$10\\,\\text{cm}$" },{ key: "B", text: "$12\\,\\text{cm}$" },{ key: "C", text: "$50\\,\\text{cm}$" },{ key: "D", text: "$15\\,\\text{cm}$" },{ key: "E", text: "$60\\,\\text{cm}$" }],
    answer: "E", solution: "$\\dfrac1f=\\dfrac1u+\\dfrac1v\\Rightarrow v=\\dfrac{fu}{u-f}=\\dfrac{20\\cdot30}{10}=60\\,$cm." },
  { id: "pat-mk1-06", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "The power dissipated by a $10\\,\\Omega$ resistor across $20\\,\\text{V}$ is:",
    options: [{ key: "A", text: "$40\\,\\text{W}$" },{ key: "B", text: "$400\\,\\text{W}$" },{ key: "C", text: "$2\\,\\text{W}$" },{ key: "D", text: "$200\\,\\text{W}$" },{ key: "E", text: "$20\\,\\text{W}$" }],
    answer: "A", solution: "$P=\\dfrac{V^2}{R}=\\dfrac{20^2}{10}=40\\,$W." },
  { id: "pat-mk1-07", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "A particle's position is $s(t)=x^{3}$. Its velocity at $t=2$ is:",
    options: [{ key: "A", text: "$13$" },{ key: "B", text: "$10$" },{ key: "C", text: "$24$" },{ key: "D", text: "$12$" },{ key: "E", text: "$8$" }],
    answer: "D", solution: "$v=\\dfrac{ds}{dt}=3 x^{2}$; at $t=2$, $v=12.$" },
  { id: "pat-mk1-08", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "Two resistors $12\\,\\Omega$ and $4\\,\\Omega$ are connected in parallel. The combined resistance is:",
    options: [{ key: "A", text: "$16\\,\\Omega$" },{ key: "B", text: "$3\\,\\Omega$" },{ key: "C", text: "$8\\,\\Omega$" },{ key: "D", text: "$24\\,\\Omega$" },{ key: "E", text: "$4\\,\\Omega$" }],
    answer: "B", solution: "$\\dfrac1{R}=\\dfrac1{12}+\\dfrac1{4}\\Rightarrow R=\\dfrac{12\\cdot4}{16}=3\\,\\Omega.$" },
  { id: "pat-mk1-09", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "A $4\\,\\text{kg}$ trolley moving at $5\\,\\text{m/s}$ collides and sticks to a stationary $6\\,\\text{kg}$ trolley. Their common velocity is:",
    options: [{ key: "A", text: "$5\\,\\text{m/s}$" },{ key: "B", text: "$\\frac{10}{3}\\,\\text{m/s}$" },{ key: "C", text: "$2\\,\\text{m/s}$" },{ key: "D", text: "$\\frac{5}{2}\\,\\text{m/s}$" },{ key: "E", text: "$3\\,\\text{m/s}$" }],
    answer: "C", solution: "Momentum: $m_1u_1=(m_1+m_2)v\\Rightarrow v=\\dfrac{4\\cdot5}{10}=2\\,$m/s." },
  { id: "pat-mk1-10", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "A $1\\,\\text{kg}$ trolley moving at $10\\,\\text{m/s}$ collides and sticks to a stationary $4\\,\\text{kg}$ trolley. Their common velocity is:",
    options: [{ key: "A", text: "$3\\,\\text{m/s}$" },{ key: "B", text: "$\\frac{5}{2}\\,\\text{m/s}$" },{ key: "C", text: "$2\\,\\text{m/s}$" },{ key: "D", text: "$10\\,\\text{m/s}$" },{ key: "E", text: "$5\\,\\text{m/s}$" }],
    answer: "C", solution: "Momentum: $m_1u_1=(m_1+m_2)v\\Rightarrow v=\\dfrac{1\\cdot10}{5}=2\\,$m/s." },
  { id: "pat-mk1-11", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 1, marks: 4,
    question: "The magnitude of the vector $(3\\,\\mathbf{i}+4\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$5$" },{ key: "C", text: "$\\frac{7}{2}$" },{ key: "D", text: "$7$" },{ key: "E", text: "$6$" }],
    answer: "B", solution: "$|\\mathbf{v}|=\\sqrt{3^2+4^2}=5.$" },
  { id: "pat-mk1-12", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 3, marks: 4,
    question: "A particle has momentum $5\\times10^{-24}\\,\\text{kg·m/s}$. With $h=6.6\\times10^{-34}$, its de Broglie wavelength (in $10^{-10}\\,\\text{m}$) is:",
    options: [{ key: "A", text: "$\\frac{66}{25}$" },{ key: "B", text: "$\\frac{5}{66}$" },{ key: "C", text: "$\\frac{33}{25}$" },{ key: "D", text: "$\\frac{25}{33}$" },{ key: "E", text: "$330$" }],
    answer: "C", solution: "$\\lambda=\\dfrac{h}{p}=\\dfrac{6.6\\times10^{-34}}{5\\times10^{-24}}=\\frac{33}{25}\\times10^{-10}\\,$m." },
  { id: "pat-mk1-13", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "Light travels inside a medium of refractive index $\\frac{5}{4}$ towards air. The sine of the critical angle is:",
    options: [{ key: "A", text: "$\\frac{2}{5}$" },{ key: "B", text: "$\\frac{4}{5}$" },{ key: "C", text: "$\\frac{1}{5}$" },{ key: "D", text: "$\\frac{5}{8}$" },{ key: "E", text: "$\\frac{5}{4}$" }],
    answer: "B", solution: "At the critical angle $\\sin\\theta_c=\\dfrac{1}{n}=\\dfrac{1}{\\frac{5}{4}}=\\frac{4}{5}.$" },
  { id: "pat-mk1-14", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "Heating $2\\,\\text{kg}$ of a substance ($c=4\\,\\text{J/kg·K}$) by $5\\,\\text{K}$ requires energy:",
    options: [{ key: "A", text: "$80\\,\\text{J}$" },{ key: "B", text: "$13\\,\\text{J}$" },{ key: "C", text: "$\\frac{8}{5}\\,\\text{J}$" },{ key: "D", text: "$20\\,\\text{J}$" },{ key: "E", text: "$40\\,\\text{J}$" }],
    answer: "E", solution: "$Q=mc\\Delta T=2\\cdot4\\cdot5=40\\,$J." },
  { id: "pat-mk1-15", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "A $20\\,\\text{V}$ supply drives a $4\\,\\Omega$ resistor. The current is:",
    options: [{ key: "A", text: "$16\\,\\text{A}$" },{ key: "B", text: "$80\\,\\text{A}$" },{ key: "C", text: "$\\frac{5}{2}\\,\\text{A}$" },{ key: "D", text: "$\\frac{1}{5}\\,\\text{A}$" },{ key: "E", text: "$5\\,\\text{A}$" }],
    answer: "E", solution: "$I=\\dfrac{V}{R}=\\dfrac{20}{4}=5\\,$A." },
  { id: "pat-mk1-16", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "An object has initial velocity $10\\,\\text{m/s}$ and acceleration $-2\\,\\text{m/s}^2$. After $3\\,\\text{s}$ its velocity is:",
    options: [{ key: "A", text: "$4\\,\\text{m/s}$" },{ key: "B", text: "$-17\\,\\text{m/s}$" },{ key: "C", text: "$16\\,\\text{m/s}$" },{ key: "D", text: "$-2\\,\\text{m/s}$" },{ key: "E", text: "$-6\\,\\text{m/s}$" }],
    answer: "A", solution: "$v=u+at=10+(-2)(3)=4\\,$m/s." },
  { id: "pat-mk1-17", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "Heating $5\\,\\text{kg}$ of a substance ($c=400\\,\\text{J/kg·K}$) by $2\\,\\text{K}$ requires energy:",
    options: [{ key: "A", text: "$8000\\,\\text{J}$" },{ key: "B", text: "$1000\\,\\text{J}$" },{ key: "C", text: "$4000\\,\\text{J}$" },{ key: "D", text: "$2002\\,\\text{J}$" },{ key: "E", text: "$2000\\,\\text{J}$" }],
    answer: "C", solution: "$Q=mc\\Delta T=5\\cdot400\\cdot2=4000\\,$J." },
  { id: "pat-mk1-18", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 3, marks: 4,
    question: "A particle has momentum $3\\times10^{-24}\\,\\text{kg·m/s}$. With $h=6.6\\times10^{-34}$, its de Broglie wavelength (in $10^{-10}\\,\\text{m}$) is:",
    options: [{ key: "A", text: "$198$" },{ key: "B", text: "$\\frac{1}{22}$" },{ key: "C", text: "$\\frac{11}{5}$" },{ key: "D", text: "$\\frac{22}{5}$" },{ key: "E", text: "$\\frac{5}{11}$" }],
    answer: "C", solution: "$\\lambda=\\dfrac{h}{p}=\\dfrac{6.6\\times10^{-34}}{3\\times10^{-24}}=\\frac{11}{5}\\times10^{-10}\\,$m." },
  { id: "pat-mk1-19", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "In a double-slit experiment (consistent units), $\\lambda=5$, slit–screen distance $D=4$, slit separation $d=2$. The fringe spacing is:",
    options: [{ key: "A", text: "$\\frac{1}{10}$" },{ key: "B", text: "$2$" },{ key: "C", text: "$\\frac{5}{2}$" },{ key: "D", text: "$40$" },{ key: "E", text: "$10$" }],
    answer: "E", solution: "$w=\\dfrac{\\lambda D}{d}=\\dfrac{5\\cdot4}{2}=10$ (same units)." },
  { id: "pat-mk1-20", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "A photon has frequency $5\\times10^{14}\\,\\text{Hz}$. Using $h=6.6\\times10^{-34}\\,\\text{J·s}$, its energy (in $10^{-20}\\,\\text{J}$) is:",
    options: [{ key: "A", text: "$330$" },{ key: "B", text: "$33$" },{ key: "C", text: "$66$" },{ key: "D", text: "$\\frac{66}{5}$" },{ key: "E", text: "$\\frac{250}{33}$" }],
    answer: "B", solution: "$E=hf=6.6\\times10^{-34}\\times5\\times10^{14}=33\\times10^{-20}\\,$J." },
  { id: "pat-mk1-21", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "The power dissipated by a $6\\,\\Omega$ resistor across $12\\,\\text{V}$ is:",
    options: [{ key: "A", text: "$24\\,\\text{W}$" },{ key: "B", text: "$12\\,\\text{W}$" },{ key: "C", text: "$144\\,\\text{W}$" },{ key: "D", text: "$2\\,\\text{W}$" },{ key: "E", text: "$72\\,\\text{W}$" }],
    answer: "A", solution: "$P=\\dfrac{V^2}{R}=\\dfrac{12^2}{6}=24\\,$W." },
  { id: "pat-mk1-22", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "A $24\\,\\text{V}$ supply drives a $6\\,\\Omega$ resistor. The current is:",
    options: [{ key: "A", text: "$4\\,\\text{A}$" },{ key: "B", text: "$\\frac{1}{4}\\,\\text{A}$" },{ key: "C", text: "$18\\,\\text{A}$" },{ key: "D", text: "$2\\,\\text{A}$" },{ key: "E", text: "$144\\,\\text{A}$" }],
    answer: "A", solution: "$I=\\dfrac{V}{R}=\\dfrac{24}{6}=4\\,$A." },
  { id: "pat-mk1-23", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "In a double-slit experiment (consistent units), $\\lambda=6$, slit–screen distance $D=2$, slit separation $d=3$. The fringe spacing is:",
    options: [{ key: "A", text: "$\\frac{1}{4}$" },{ key: "B", text: "$36$" },{ key: "C", text: "$4$" },{ key: "D", text: "$\\frac{2}{3}$" },{ key: "E", text: "$2$" }],
    answer: "C", solution: "$w=\\dfrac{\\lambda D}{d}=\\dfrac{6\\cdot2}{3}=4$ (same units)." },
  { id: "pat-mk1-24", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "In a double-slit experiment (consistent units), $\\lambda=5$, slit–screen distance $D=2$, slit separation $d=5$. The fringe spacing is:",
    options: [{ key: "A", text: "$\\frac{2}{5}$" },{ key: "B", text: "$1$" },{ key: "C", text: "$\\frac{1}{2}$" },{ key: "D", text: "$50$" },{ key: "E", text: "$2$" }],
    answer: "E", solution: "$w=\\dfrac{\\lambda D}{d}=\\dfrac{5\\cdot2}{5}=2$ (same units)." },
  { id: "pat-mk1-25", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "A $2\\,\\text{kg}$ mass moves in a circle of radius $8\\,\\text{m}$ at $4\\,\\text{m/s}$. The centripetal force is:",
    options: [{ key: "A", text: "$5\\,\\text{N}$" },{ key: "B", text: "$1\\,\\text{N}$" },{ key: "C", text: "$32\\,\\text{N}$" },{ key: "D", text: "$4\\,\\text{N}$" },{ key: "E", text: "$2\\,\\text{N}$" }],
    answer: "D", solution: "$F=\\dfrac{mv^2}{r}=\\dfrac{2\\cdot4^2}{8}=4\\,$N." },
];
