// PAT 模拟卷5 —— 25 题五选一，id 前缀 pat-mk5-*。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const PAT_MK5_MCQ: MCQQuestion[] = [
  { id: "pat-mk5-01", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "Photons of energy $10\\times10^{-19}\\,\\text{J}$ hit a metal of work function $6\\times10^{-19}\\,\\text{J}$. The maximum photoelectron KE (in $10^{-19}\\,\\text{J}$) is:",
    options: [{ key: "A", text: "$\\frac{5}{3}$" },{ key: "B", text: "$5$" },{ key: "C", text: "$16$" },{ key: "D", text: "$4$" },{ key: "E", text: "$60$" }],
    answer: "D", solution: "$KE_{max}=hf-\\phi=10-6=4\\ (\\times10^{-19}\\,$J$)$." },
  { id: "pat-mk5-02", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "On Earth ($g=10$), the weight of a $5\\,\\text{kg}$ mass is:",
    options: [{ key: "A", text: "$15\\,\\text{N}$" },{ key: "B", text: "$100\\,\\text{N}$" },{ key: "C", text: "$5\\,\\text{N}$" },{ key: "D", text: "$\\frac{1}{2}\\,\\text{N}$" },{ key: "E", text: "$50\\,\\text{N}$" }],
    answer: "E", solution: "$W=mg=5\\times10=50\\,$N." },
  { id: "pat-mk5-03", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "The energy stored in a $1\\,\\text{F}$ capacitor at $6\\,\\text{V}$ is:",
    options: [{ key: "A", text: "$3\\,\\text{J}$" },{ key: "B", text: "$20\\,\\text{J}$" },{ key: "C", text: "$18\\,\\text{J}$" },{ key: "D", text: "$6\\,\\text{J}$" },{ key: "E", text: "$36\\,\\text{J}$" }],
    answer: "C", solution: "$E=\\tfrac12CV^2=\\tfrac12\\cdot1\\cdot6^2=18\\,$J." },
  { id: "pat-mk5-04", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "An object starts at $3\\,\\text{m/s}$ with acceleration $4\\,\\text{m/s}^2$. The distance travelled in $2\\,\\text{s}$ is:",
    options: [{ key: "A", text: "$16\\,\\text{m}$" },{ key: "B", text: "$14\\,\\text{m}$" },{ key: "C", text: "$6\\,\\text{m}$" },{ key: "D", text: "$22\\,\\text{m}$" },{ key: "E", text: "$11\\,\\text{m}$" }],
    answer: "B", solution: "$s=ut+\\tfrac12at^2=3\\cdot2+\\tfrac12\\cdot4\\cdot2^2=14\\,$m." },
  { id: "pat-mk5-05", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 3, marks: 4,
    question: "A gas goes from $(P_1{=}2,V_1{=}3,T_1{=}300)$ to $(P_2{=}3,T_2{=}600)$. Its new volume $V_2$ is:",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$5$" },{ key: "C", text: "$3$" },{ key: "D", text: "$4$" },{ key: "E", text: "$2$" }],
    answer: "D", solution: "$\\dfrac{P_1V_1}{T_1}=\\dfrac{P_2V_2}{T_2}\\Rightarrow V_2=\\dfrac{P_1V_1T_2}{T_1P_2}=4.$" },
  { id: "pat-mk5-06", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "On Earth ($g=10$), the weight of a $2\\,\\text{kg}$ mass is:",
    options: [{ key: "A", text: "$40\\,\\text{N}$" },{ key: "B", text: "$20\\,\\text{N}$" },{ key: "C", text: "$\\frac{1}{5}\\,\\text{N}$" },{ key: "D", text: "$12\\,\\text{N}$" },{ key: "E", text: "$2\\,\\text{N}$" }],
    answer: "B", solution: "$W=mg=2\\times10=20\\,$N." },
  { id: "pat-mk5-07", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "The energy stored in a $2\\,\\text{F}$ capacitor at $4\\,\\text{V}$ is:",
    options: [{ key: "A", text: "$16\\,\\text{J}$" },{ key: "B", text: "$4\\,\\text{J}$" },{ key: "C", text: "$32\\,\\text{J}$" },{ key: "D", text: "$18\\,\\text{J}$" },{ key: "E", text: "$8\\,\\text{J}$" }],
    answer: "A", solution: "$E=\\tfrac12CV^2=\\tfrac12\\cdot2\\cdot4^2=16\\,$J." },
  { id: "pat-mk5-08", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "A force $12\\,\\text{N}$ acts on area $3\\,\\text{m}^2$. The pressure is:",
    options: [{ key: "A", text: "$\\frac{1}{4}\\,\\text{Pa}$" },{ key: "B", text: "$4\\,\\text{Pa}$" },{ key: "C", text: "$36\\,\\text{Pa}$" },{ key: "D", text: "$9\\,\\text{Pa}$" },{ key: "E", text: "$15\\,\\text{Pa}$" }],
    answer: "B", solution: "$P=\\dfrac{F}{A}=\\dfrac{12}{3}=4\\,$Pa." },
  { id: "pat-mk5-09", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "A force $50\\,\\text{N}$ acts on area $5\\,\\text{m}^2$. The pressure is:",
    options: [{ key: "A", text: "$250\\,\\text{Pa}$" },{ key: "B", text: "$45\\,\\text{Pa}$" },{ key: "C", text: "$55\\,\\text{Pa}$" },{ key: "D", text: "$\\frac{1}{10}\\,\\text{Pa}$" },{ key: "E", text: "$10\\,\\text{Pa}$" }],
    answer: "E", solution: "$P=\\dfrac{F}{A}=\\dfrac{50}{5}=10\\,$Pa." },
  { id: "pat-mk5-10", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 1, marks: 4,
    question: "A wave has frequency $100\\,\\text{Hz}$. Its period is:",
    options: [{ key: "A", text: "$\\frac{1}{50}\\,\\text{s}$" },{ key: "B", text: "$200\\,\\text{s}$" },{ key: "C", text: "$100\\,\\text{s}$" },{ key: "D", text: "$50\\,\\text{s}$" },{ key: "E", text: "$\\frac{1}{100}\\,\\text{s}$" }],
    answer: "E", solution: "$T=\\dfrac1f=\\dfrac1{100}=\\frac{1}{100}\\,$s." },
  { id: "pat-mk5-11", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "For $f(x)=x^{2} - 6 x + 2$, the second derivative $f''(2)$ is:",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$-2$" },{ key: "C", text: "$3$" },{ key: "D", text: "$2$" },{ key: "E", text: "$-6$" }],
    answer: "D", solution: "$f''(x)=2$, so $f''(2)=2.$" },
  { id: "pat-mk5-12", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "For a converging lens $f=15\\,\\text{cm}$, object at $45\\,\\text{cm}$, the magnification $|m|$ is:",
    options: [{ key: "A", text: "$\\frac{3}{2}$" },{ key: "B", text: "$\\frac{1}{2}$" },{ key: "C", text: "$\\frac{45}{2}$" },{ key: "D", text: "$\\frac{1}{3}$" },{ key: "E", text: "$2$" }],
    answer: "B", solution: "$v=\\dfrac{fu}{u-f}=\\frac{45}{2}$; $|m|=\\dfrac{v}{u}=\\frac{1}{2}.$" },
  { id: "pat-mk5-13", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "A force $12\\,\\text{N}$ moves an object $6\\,\\text{m}$ in $4\\,\\text{s}$. The average power is:",
    options: [{ key: "A", text: "$3\\,\\text{W}$" },{ key: "B", text: "$\\frac{3}{2}\\,\\text{W}$" },{ key: "C", text: "$72\\,\\text{W}$" },{ key: "D", text: "$18\\,\\text{W}$" },{ key: "E", text: "$288\\,\\text{W}$" }],
    answer: "D", solution: "$P=\\dfrac{W}{t}=\\dfrac{Fd}{t}=\\dfrac{12\\cdot6}{4}=18\\,$W." },
  { id: "pat-mk5-14", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "A sample decays to $\\tfrac1{32}$ of its initial amount. The number of half-lives elapsed is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$10$" },{ key: "C", text: "$32$" },{ key: "D", text: "$6$" },{ key: "E", text: "$4$" }],
    answer: "A", solution: "$\\left(\\tfrac12\\right)^k=\\tfrac1{32}\\Rightarrow k=5.$" },
  { id: "pat-mk5-15", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "The uniform field between plates $3\\,\\text{m}$ apart at $12\\,\\text{V}$ is:",
    options: [{ key: "A", text: "$36\\,\\text{V/m}$" },{ key: "B", text: "$9\\,\\text{V/m}$" },{ key: "C", text: "$4\\,\\text{V/m}$" },{ key: "D", text: "$\\frac{1}{4}\\,\\text{V/m}$" },{ key: "E", text: "$8\\,\\text{V/m}$" }],
    answer: "C", solution: "$E=\\dfrac{V}{d}=\\dfrac{12}{3}=4\\,$V/m." },
  { id: "pat-mk5-16", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "Photons of energy $8\\times10^{-19}\\,\\text{J}$ hit a metal of work function $3\\times10^{-19}\\,\\text{J}$. The maximum photoelectron KE (in $10^{-19}\\,\\text{J}$) is:",
    options: [{ key: "A", text: "$24$" },{ key: "B", text: "$\\frac{8}{3}$" },{ key: "C", text: "$11$" },{ key: "D", text: "$6$" },{ key: "E", text: "$5$" }],
    answer: "E", solution: "$KE_{max}=hf-\\phi=8-3=5\\ (\\times10^{-19}\\,$J$)$." },
  { id: "pat-mk5-17", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "Melting $3\\,\\text{kg}$ of a solid (specific latent heat $L=500\\,\\text{J/kg}$) needs energy:",
    options: [{ key: "A", text: "$\\frac{3}{500}\\,\\text{J}$" },{ key: "B", text: "$750\\,\\text{J}$" },{ key: "C", text: "$1500\\,\\text{J}$" },{ key: "D", text: "$3000\\,\\text{J}$" },{ key: "E", text: "$503\\,\\text{J}$" }],
    answer: "C", solution: "$Q=mL=3\\cdot500=1500\\,$J." },
  { id: "pat-mk5-18", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "For $f(x)=x^{2} - 4$, the second derivative $f''(1)$ is:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$0$" },{ key: "C", text: "$3$" },{ key: "D", text: "$2$" },{ key: "E", text: "$-3$" }],
    answer: "D", solution: "$f''(x)=2$, so $f''(1)=2.$" },
  { id: "pat-mk5-19", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "Melting $2\\,\\text{kg}$ of a solid (specific latent heat $L=300\\,\\text{J/kg}$) needs energy:",
    options: [{ key: "A", text: "$300\\,\\text{J}$" },{ key: "B", text: "$600\\,\\text{J}$" },{ key: "C", text: "$302\\,\\text{J}$" },{ key: "D", text: "$\\frac{1}{150}\\,\\text{J}$" },{ key: "E", text: "$1200\\,\\text{J}$" }],
    answer: "B", solution: "$Q=mL=2\\cdot300=600\\,$J." },
  { id: "pat-mk5-20", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "Light crosses from medium $n_1=1$ into $n_2=\\frac{3}{2}$ with $\\sin\\theta_1=\\frac{3}{5}$. Then $\\sin\\theta_2$ is:",
    options: [{ key: "A", text: "$\\frac{2}{5}$" },{ key: "B", text: "$\\frac{3}{10}$" },{ key: "C", text: "$\\frac{1}{2}$" },{ key: "D", text: "$\\frac{9}{10}$" },{ key: "E", text: "$\\frac{3}{5}$" }],
    answer: "A", solution: "Snell: $n_1\\sin\\theta_1=n_2\\sin\\theta_2\\Rightarrow\\sin\\theta_2=\\dfrac{1\\cdot\\frac{3}{5}}{\\frac{3}{2}}=\\frac{2}{5}.$" },
  { id: "pat-mk5-21", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "On Earth ($g=10$), the weight of a $3\\,\\text{kg}$ mass is:",
    options: [{ key: "A", text: "$3\\,\\text{N}$" },{ key: "B", text: "$13\\,\\text{N}$" },{ key: "C", text: "$60\\,\\text{N}$" },{ key: "D", text: "$\\frac{3}{10}\\,\\text{N}$" },{ key: "E", text: "$30\\,\\text{N}$" }],
    answer: "E", solution: "$W=mg=3\\times10=30\\,$N." },
  { id: "pat-mk5-22", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "An object starts at $4\\,\\text{m/s}$ with acceleration $3\\,\\text{m/s}^2$. The distance travelled in $3\\,\\text{s}$ is:",
    options: [{ key: "A", text: "$27\\,\\text{m}$" },{ key: "B", text: "$39\\,\\text{m}$" },{ key: "C", text: "$\\frac{35}{2}\\,\\text{m}$" },{ key: "D", text: "$\\frac{51}{2}\\,\\text{m}$" },{ key: "E", text: "$12\\,\\text{m}$" }],
    answer: "D", solution: "$s=ut+\\tfrac12at^2=4\\cdot3+\\tfrac12\\cdot3\\cdot3^2=\\frac{51}{2}\\,$m." },
  { id: "pat-mk5-23", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "Two resistors $10\\,\\Omega$ and $15\\,\\Omega$ in series give:",
    options: [{ key: "A", text: "$25\\,\\Omega$" },{ key: "B", text: "$5\\,\\Omega$" },{ key: "C", text: "$\\frac{25}{2}\\,\\Omega$" },{ key: "D", text: "$6\\,\\Omega$" },{ key: "E", text: "$150\\,\\Omega$" }],
    answer: "A", solution: "Series: $R=10+15=25\\,\\Omega$." },
  { id: "pat-mk5-24", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "An object starts at $10\\,\\text{m/s}$ with acceleration $-2\\,\\text{m/s}^2$. The distance travelled in $2\\,\\text{s}$ is:",
    options: [{ key: "A", text: "$12\\,\\text{m}$" },{ key: "B", text: "$20\\,\\text{m}$" },{ key: "C", text: "$-8\\,\\text{m}$" },{ key: "D", text: "$6\\,\\text{m}$" },{ key: "E", text: "$16\\,\\text{m}$" }],
    answer: "E", solution: "$s=ut+\\tfrac12at^2=10\\cdot2+\\tfrac12\\cdot-2\\cdot2^2=16\\,$m." },
  { id: "pat-mk5-25", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "Using $hc=20$ (in units of $10^{-26}\\,\\text{J·m}$), a photon of wavelength $2\\times10^{-7}\\,\\text{m}$ has energy (in $10^{-19}\\,\\text{J}$):",
    options: [{ key: "A", text: "$11$" },{ key: "B", text: "$40$" },{ key: "C", text: "$\\frac{1}{10}$" },{ key: "D", text: "$10$" },{ key: "E", text: "$22$" }],
    answer: "D", solution: "$E=\\dfrac{hc}{\\lambda}=\\dfrac{20}{2}=10\\ (\\times10^{-19}\\,$J$)$." },
];
