// PAT 模拟卷4 —— 25 题五选一，id 前缀 pat-mk4-*。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const PAT_MK4_MCQ: MCQQuestion[] = [
  { id: "pat-mk4-01", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "Using $hc=20$ (in units of $10^{-26}\\,\\text{J·m}$), a photon of wavelength $5\\times10^{-7}\\,\\text{m}$ has energy (in $10^{-19}\\,\\text{J}$):",
    options: [{ key: "A", text: "$100$" },{ key: "B", text: "$5$" },{ key: "C", text: "$4$" },{ key: "D", text: "$\\frac{1}{4}$" },{ key: "E", text: "$25$" }],
    answer: "C", solution: "$E=\\dfrac{hc}{\\lambda}=\\dfrac{20}{5}=4\\ (\\times10^{-19}\\,$J$)$." },
  { id: "pat-mk4-02", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "The gravitational PE gained lifting $3\\,\\text{kg}$ by $10\\,\\text{m}$ ($g=10$) is:",
    options: [{ key: "A", text: "$310\\,\\text{J}$" },{ key: "B", text: "$300\\,\\text{J}$" },{ key: "C", text: "$150\\,\\text{J}$" },{ key: "D", text: "$100\\,\\text{J}$" },{ key: "E", text: "$30\\,\\text{J}$" }],
    answer: "B", solution: "$E_p=mgh=3\\cdot10\\cdot10=300\\,$J." },
  { id: "pat-mk4-03", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 3, marks: 4,
    question: "A gas goes from $(P_1{=}1,V_1{=}4,T_1{=}200)$ to $(P_2{=}2,T_2{=}300)$. Its new volume $V_2$ is:",
    options: [{ key: "A", text: "$12$" },{ key: "B", text: "$2$" },{ key: "C", text: "$4$" },{ key: "D", text: "$6$" },{ key: "E", text: "$3$" }],
    answer: "E", solution: "$\\dfrac{P_1V_1}{T_1}=\\dfrac{P_2V_2}{T_2}\\Rightarrow V_2=\\dfrac{P_1V_1T_2}{T_1P_2}=3.$" },
  { id: "pat-mk4-04", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "With initial speed $4\\,\\text{m/s}$, acceleration $2\\,\\text{m/s}^2$, over $6\\,\\text{m}$, the final speed is:",
    options: [{ key: "A", text: "$2 \\sqrt{10}\\,\\text{m/s}$" },{ key: "B", text: "$1 + 2 \\sqrt{6}\\,\\text{m/s}$" },{ key: "C", text: "$24\\,\\text{m/s}$" },{ key: "D", text: "$2 \\sqrt{7}\\,\\text{m/s}$" },{ key: "E", text: "$16\\,\\text{m/s}$" }],
    answer: "A", solution: "$v^2=u^2+2as=4^2+2\\cdot2\\cdot6$, so $v=2 \\sqrt{10}\\,$m/s." },
  { id: "pat-mk4-05", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 3, marks: 4,
    question: "The cosine of the angle between $(1\\,\\mathbf{i}+2\\,\\mathbf{j})$ and $(2\\,\\mathbf{i}+4\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$\\frac{11}{10}$" },{ key: "B", text: "$-1$" },{ key: "C", text: "$1$" },{ key: "D", text: "$\\frac{1}{2}$" },{ key: "E", text: "$10$" }],
    answer: "C", solution: "$\\cos\\theta=\\dfrac{\\mathbf{a}\\cdot\\mathbf{b}}{|\\mathbf{a}||\\mathbf{b}|}=1.$" },
  { id: "pat-mk4-06", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "A current $2\\,\\text{A}$ flows through $3\\,\\Omega$. The power dissipated is:",
    options: [{ key: "A", text: "$\\frac{3}{2}\\,\\text{W}$" },{ key: "B", text: "$6\\,\\text{W}$" },{ key: "C", text: "$12\\,\\text{W}$" },{ key: "D", text: "$4\\,\\text{W}$" },{ key: "E", text: "$14\\,\\text{W}$" }],
    answer: "C", solution: "$P=I^2R=2^2\\cdot3=12\\,$W." },
  { id: "pat-mk4-07", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 3, marks: 4,
    question: "Two charges $6\\,\\mu\\text{C}$ and $3\\,\\mu\\text{C}$ are $3\\,\\text{m}$ apart ($k=9\\times10^9$). The force (in mN) is:",
    options: [{ key: "A", text: "$18\\,\\text{mN}$" },{ key: "B", text: "$162\\,\\text{mN}$" },{ key: "C", text: "$19\\,\\text{mN}$" },{ key: "D", text: "$2\\,\\text{mN}$" },{ key: "E", text: "$54\\,\\text{mN}$" }],
    answer: "A", solution: "$F=\\dfrac{kq_1q_2}{r^2}=\\dfrac{9\\cdot6\\cdot3}{3^2}=18\\,$mN." },
  { id: "pat-mk4-08", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "Melting $4\\,\\text{kg}$ of a solid (specific latent heat $L=250\\,\\text{J/kg}$) needs energy:",
    options: [{ key: "A", text: "$500\\,\\text{J}$" },{ key: "B", text: "$2000\\,\\text{J}$" },{ key: "C", text: "$254\\,\\text{J}$" },{ key: "D", text: "$\\frac{2}{125}\\,\\text{J}$" },{ key: "E", text: "$1000\\,\\text{J}$" }],
    answer: "E", solution: "$Q=mL=4\\cdot250=1000\\,$J." },
  { id: "pat-mk4-09", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "A sample decays to $\\tfrac1{64}$ of its initial amount. The number of half-lives elapsed is:",
    options: [{ key: "A", text: "$64$" },{ key: "B", text: "$6$" },{ key: "C", text: "$12$" },{ key: "D", text: "$5$" },{ key: "E", text: "$7$" }],
    answer: "B", solution: "$\\left(\\tfrac12\\right)^k=\\tfrac1{64}\\Rightarrow k=6.$" },
  { id: "pat-mk4-10", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "The larger root of $x^{2} - 4 x + 4=0$ is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$1$" },{ key: "C", text: "$2$" },{ key: "D", text: "$4$" },{ key: "E", text: "$-2$" }],
    answer: "C", solution: "Factorising/quadratic formula gives roots $2,2$; the larger is $2.$" },
  { id: "pat-mk4-11", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 3, marks: 4,
    question: "Two charges $2\\,\\mu\\text{C}$ and $2\\,\\mu\\text{C}$ are $3\\,\\text{m}$ apart ($k=9\\times10^9$). The force (in mN) is:",
    options: [{ key: "A", text: "$12\\,\\text{mN}$" },{ key: "B", text: "$\\frac{4}{9}\\,\\text{mN}$" },{ key: "C", text: "$5\\,\\text{mN}$" },{ key: "D", text: "$4\\,\\text{mN}$" },{ key: "E", text: "$36\\,\\text{mN}$" }],
    answer: "D", solution: "$F=\\dfrac{kq_1q_2}{r^2}=\\dfrac{9\\cdot2\\cdot2}{3^2}=4\\,$mN." },
  { id: "pat-mk4-12", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 1, marks: 4,
    question: "A wave has frequency $25\\,\\text{Hz}$. Its period is:",
    options: [{ key: "A", text: "$25\\,\\text{s}$" },{ key: "B", text: "$\\frac{25}{2}\\,\\text{s}$" },{ key: "C", text: "$\\frac{1}{25}\\,\\text{s}$" },{ key: "D", text: "$\\frac{2}{25}\\,\\text{s}$" },{ key: "E", text: "$50\\,\\text{s}$" }],
    answer: "C", solution: "$T=\\dfrac1f=\\dfrac1{25}=\\frac{1}{25}\\,$s." },
  { id: "pat-mk4-13", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 3, marks: 4,
    question: "The cosine of the angle between $(3\\,\\mathbf{i}+4\\,\\mathbf{j})$ and $(4\\,\\mathbf{i}+3\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$- \\frac{24}{25}$" },{ key: "B", text: "$\\frac{53}{50}$" },{ key: "C", text: "$24$" },{ key: "D", text: "$\\frac{24}{25}$" },{ key: "E", text: "$\\frac{1}{2}$" }],
    answer: "D", solution: "$\\cos\\theta=\\dfrac{\\mathbf{a}\\cdot\\mathbf{b}}{|\\mathbf{a}||\\mathbf{b}|}=\\frac{24}{25}.$" },
  { id: "pat-mk4-14", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "The larger root of $x^{2} - 5 x + 6=0$ is:",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$4$" },{ key: "C", text: "$-3$" },{ key: "D", text: "$3$" },{ key: "E", text: "$2$" }],
    answer: "D", solution: "Factorising/quadratic formula gives roots $2,3$; the larger is $3.$" },
  { id: "pat-mk4-15", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 3, marks: 4,
    question: "Two charges $1\\,\\mu\\text{C}$ and $4\\,\\mu\\text{C}$ are $2\\,\\text{m}$ apart ($k=9\\times10^9$). The force (in mN) is:",
    options: [{ key: "A", text: "$18\\,\\text{mN}$" },{ key: "B", text: "$10\\,\\text{mN}$" },{ key: "C", text: "$36\\,\\text{mN}$" },{ key: "D", text: "$9\\,\\text{mN}$" },{ key: "E", text: "$1\\,\\text{mN}$" }],
    answer: "D", solution: "$F=\\dfrac{kq_1q_2}{r^2}=\\dfrac{9\\cdot1\\cdot4}{2^2}=9\\,$mN." },
  { id: "pat-mk4-16", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "A $3\\,\\text{F}$ capacitor is charged to $4\\,\\text{V}$. The charge stored is:",
    options: [{ key: "A", text: "$\\frac{3}{4}\\,\\text{C}$" },{ key: "B", text: "$\\frac{4}{3}\\,\\text{C}$" },{ key: "C", text: "$7\\,\\text{C}$" },{ key: "D", text: "$24\\,\\text{C}$" },{ key: "E", text: "$12\\,\\text{C}$" }],
    answer: "E", solution: "$Q=CV=3\\cdot4=12\\,$C." },
  { id: "pat-mk4-17", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 1, marks: 4,
    question: "A wave has frequency $500\\,\\text{Hz}$. Its period is:",
    options: [{ key: "A", text: "$250\\,\\text{s}$" },{ key: "B", text: "$\\frac{1}{250}\\,\\text{s}$" },{ key: "C", text: "$500\\,\\text{s}$" },{ key: "D", text: "$\\frac{1}{500}\\,\\text{s}$" },{ key: "E", text: "$1000\\,\\text{s}$" }],
    answer: "D", solution: "$T=\\dfrac1f=\\dfrac1{500}=\\frac{1}{500}\\,$s." },
  { id: "pat-mk4-18", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 1, marks: 4,
    question: "A wave has frequency $4\\,\\text{Hz}$. Its period is:",
    options: [{ key: "A", text: "$2\\,\\text{s}$" },{ key: "B", text: "$\\frac{1}{4}\\,\\text{s}$" },{ key: "C", text: "$8\\,\\text{s}$" },{ key: "D", text: "$\\frac{1}{2}\\,\\text{s}$" },{ key: "E", text: "$4\\,\\text{s}$" }],
    answer: "B", solution: "$T=\\dfrac1f=\\dfrac1{4}=\\frac{1}{4}\\,$s." },
  { id: "pat-mk4-19", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "Two resistors $3\\,\\Omega$ and $5\\,\\Omega$ in series give:",
    options: [{ key: "A", text: "$\\frac{15}{8}\\,\\Omega$" },{ key: "B", text: "$8\\,\\Omega$" },{ key: "C", text: "$4\\,\\Omega$" },{ key: "D", text: "$15\\,\\Omega$" },{ key: "E", text: "$2\\,\\Omega$" }],
    answer: "B", solution: "Series: $R=3+5=8\\,\\Omega$." },
  { id: "pat-mk4-20", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "With initial speed $0\\,\\text{m/s}$, acceleration $5\\,\\text{m/s}^2$, over $10\\,\\text{m}$, the final speed is:",
    options: [{ key: "A", text: "$100\\,\\text{m/s}$" },{ key: "B", text: "$10\\,\\text{m/s}$" },{ key: "C", text: "$11\\,\\text{m/s}$" },{ key: "D", text: "$5 \\sqrt{2}\\,\\text{m/s}$" },{ key: "E", text: "$50\\,\\text{m/s}$" }],
    answer: "B", solution: "$v^2=u^2+2as=0^2+2\\cdot5\\cdot10$, so $v=10\\,$m/s." },
  { id: "pat-mk4-21", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 3, marks: 4,
    question: "The cosine of the angle between $(1\\,\\mathbf{i}+1\\,\\mathbf{j})$ and $(1\\,\\mathbf{i}+-1\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$\\frac{1}{2}$" },{ key: "B", text: "$\\frac{1}{10}$" },{ key: "C", text: "$1$" },{ key: "D", text: "$0$" },{ key: "E", text: "$2$" }],
    answer: "D", solution: "$\\cos\\theta=\\dfrac{\\mathbf{a}\\cdot\\mathbf{b}}{|\\mathbf{a}||\\mathbf{b}|}=0.$" },
  { id: "pat-mk4-22", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "On Earth ($g=10$), the weight of a $8\\,\\text{kg}$ mass is:",
    options: [{ key: "A", text: "$\\frac{4}{5}\\,\\text{N}$" },{ key: "B", text: "$8\\,\\text{N}$" },{ key: "C", text: "$160\\,\\text{N}$" },{ key: "D", text: "$80\\,\\text{N}$" },{ key: "E", text: "$18\\,\\text{N}$" }],
    answer: "D", solution: "$W=mg=8\\times10=80\\,$N." },
  { id: "pat-mk4-23", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "The energy stored in a $5\\,\\text{F}$ capacitor at $4\\,\\text{V}$ is:",
    options: [{ key: "A", text: "$20\\,\\text{J}$" },{ key: "B", text: "$10\\,\\text{J}$" },{ key: "C", text: "$42\\,\\text{J}$" },{ key: "D", text: "$80\\,\\text{J}$" },{ key: "E", text: "$40\\,\\text{J}$" }],
    answer: "E", solution: "$E=\\tfrac12CV^2=\\tfrac12\\cdot5\\cdot4^2=40\\,$J." },
  { id: "pat-mk4-24", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 2, marks: 4,
    question: "At constant pressure a gas has $V_1=3$ at $T_1=400\\,\\text{K}$. At $T_2=200\\,\\text{K}$ its volume is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$\\frac{1}{2}$" },{ key: "C", text: "$\\frac{3}{2}$" },{ key: "D", text: "$6$" },{ key: "E", text: "$-197$" }],
    answer: "C", solution: "Charles: $\\dfrac{V_1}{T_1}=\\dfrac{V_2}{T_2}\\Rightarrow V_2=\\dfrac{3\\cdot200}{400}=\\frac{3}{2}.$" },
  { id: "pat-mk4-25", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "The gravitational PE gained lifting $5\\,\\text{kg}$ by $4\\,\\text{m}$ ($g=10$) is:",
    options: [{ key: "A", text: "$20\\,\\text{J}$" },{ key: "B", text: "$200\\,\\text{J}$" },{ key: "C", text: "$100\\,\\text{J}$" },{ key: "D", text: "$50\\,\\text{J}$" },{ key: "E", text: "$40\\,\\text{J}$" }],
    answer: "B", solution: "$E_p=mgh=5\\cdot10\\cdot4=200\\,$J." },
];
