// PAT 模拟卷3 —— 25 题五选一，id 前缀 pat-mk3-*。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const PAT_MK3_MCQ: MCQQuestion[] = [
  { id: "pat-mk3-01", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "Heating $1\\,\\text{kg}$ of a substance ($c=900\\,\\text{J/kg·K}$) by $10\\,\\text{K}$ requires energy:",
    options: [{ key: "A", text: "$9000\\,\\text{J}$" },{ key: "B", text: "$910\\,\\text{J}$" },{ key: "C", text: "$18000\\,\\text{J}$" },{ key: "D", text: "$4500\\,\\text{J}$" },{ key: "E", text: "$90\\,\\text{J}$" }],
    answer: "A", solution: "$Q=mc\\Delta T=1\\cdot900\\cdot10=9000\\,$J." },
  { id: "pat-mk3-02", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 1, marks: 4,
    question: "A wave has frequency $200\\,\\text{Hz}$ and wavelength $2\\,\\text{m}$. Its speed is:",
    options: [{ key: "A", text: "$202\\,\\text{m/s}$" },{ key: "B", text: "$800\\,\\text{m/s}$" },{ key: "C", text: "$400\\,\\text{m/s}$" },{ key: "D", text: "$100\\,\\text{m/s}$" },{ key: "E", text: "$0.01\\,\\text{m/s}$" }],
    answer: "C", solution: "$v=f\\lambda=200\\times2=400\\,$m/s." },
  { id: "pat-mk3-03", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "An object is $30\\,\\text{cm}$ from a converging lens of focal length $15\\,\\text{cm}$. The image distance is:",
    options: [{ key: "A", text: "$15\\,\\text{cm}$" },{ key: "B", text: "$45\\,\\text{cm}$" },{ key: "C", text: "$10\\,\\text{cm}$" },{ key: "D", text: "$30\\,\\text{cm}$" },{ key: "E", text: "$32\\,\\text{cm}$" }],
    answer: "D", solution: "$\\dfrac1f=\\dfrac1u+\\dfrac1v\\Rightarrow v=\\dfrac{fu}{u-f}=\\dfrac{15\\cdot30}{15}=30\\,$cm." },
  { id: "pat-mk3-04", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "In a double-slit experiment (consistent units), $\\lambda=4$, slit–screen distance $D=3$, slit separation $d=6$. The fringe spacing is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$72$" },{ key: "C", text: "$2$" },{ key: "D", text: "$0.5$" },{ key: "E", text: "$0.6667$" }],
    answer: "C", solution: "$w=\\dfrac{\\lambda D}{d}=\\dfrac{4\\cdot3}{6}=2$ (same units)." },
  { id: "pat-mk3-05", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "Two resistors $10\\,\\Omega$ and $10\\,\\Omega$ are connected in parallel. The combined resistance is:",
    options: [{ key: "A", text: "$6\\,\\Omega$" },{ key: "B", text: "$20\\,\\Omega$" },{ key: "C", text: "$10\\,\\Omega$" },{ key: "D", text: "$50\\,\\Omega$" },{ key: "E", text: "$5\\,\\Omega$" }],
    answer: "E", solution: "$\\dfrac1{R}=\\dfrac1{10}+\\dfrac1{10}\\Rightarrow R=\\dfrac{10\\cdot10}{20}=5\\,\\Omega.$" },
  { id: "pat-mk3-06", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "A photon has frequency $6\\times10^{14}\\,\\text{Hz}$. Using $h=6.6\\times10^{-34}\\,\\text{J·s}$, its energy (in $10^{-20}\\,\\text{J}$) is:",
    options: [{ key: "A", text: "$39.6$" },{ key: "B", text: "$396$" },{ key: "C", text: "$9.0909$" },{ key: "D", text: "$79.2$" },{ key: "E", text: "$11$" }],
    answer: "A", solution: "$E=hf=6.6\\times10^{-34}\\times6\\times10^{14}=\\frac{198}{5}\\times10^{-20}\\,$J." },
  { id: "pat-mk3-07", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "A current of $\\frac{1}{2}\\,\\text{A}$ flows for $10\\,\\text{s}$. The charge transferred is:",
    options: [{ key: "A", text: "$10.5\\,\\text{C}$" },{ key: "B", text: "$5\\,\\text{C}$" },{ key: "C", text: "$20\\,\\text{C}$" },{ key: "D", text: "$10\\,\\text{C}$" },{ key: "E", text: "$2.5\\,\\text{C}$" }],
    answer: "B", solution: "$Q=It=\\frac{1}{2}\\times10=5\\,$C." },
  { id: "pat-mk3-08", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "An object has initial velocity $0\\,\\text{m/s}$ and acceleration $10\\,\\text{m/s}^2$. After $3\\,\\text{s}$ its velocity is:",
    options: [{ key: "A", text: "$3\\,\\text{m/s}$" },{ key: "B", text: "$-30\\,\\text{m/s}$" },{ key: "C", text: "$60\\,\\text{m/s}$" },{ key: "D", text: "$30\\,\\text{m/s}$" },{ key: "E", text: "$32\\,\\text{m/s}$" }],
    answer: "D", solution: "$v=u+at=0+(10)(3)=30\\,$m/s." },
  { id: "pat-mk3-09", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "Light travels inside a medium of refractive index $2$ towards air. The sine of the critical angle is:",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$0.6$" },{ key: "C", text: "$0.5$" },{ key: "D", text: "$1$" },{ key: "E", text: "$0.25$" }],
    answer: "C", solution: "At the critical angle $\\sin\\theta_c=\\dfrac{1}{n}=\\dfrac{1}{2}=\\frac{1}{2}.$" },
  { id: "pat-mk3-10", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 2, marks: 4,
    question: "At constant volume, a gas has $P_1=2$ at $T_1=300\\,\\text{K}$. When pressure rises to $P_2=3$, the temperature is:",
    options: [{ key: "A", text: "$200\\,\\text{K}$" },{ key: "B", text: "$900\\,\\text{K}$" },{ key: "C", text: "$450\\,\\text{K}$" },{ key: "D", text: "$150\\,\\text{K}$" },{ key: "E", text: "$301\\,\\text{K}$" }],
    answer: "C", solution: "$\\dfrac{P_1}{T_1}=\\dfrac{P_2}{T_2}\\Rightarrow T_2=\\dfrac{3\\cdot300}{2}=450\\,$K." },
  { id: "pat-mk3-11", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "A $9\\,\\text{V}$ supply drives a $3\\,\\Omega$ resistor. The current is:",
    options: [{ key: "A", text: "$27\\,\\text{A}$" },{ key: "B", text: "$0.3333\\,\\text{A}$" },{ key: "C", text: "$3\\,\\text{A}$" },{ key: "D", text: "$1.5\\,\\text{A}$" },{ key: "E", text: "$6\\,\\text{A}$" }],
    answer: "C", solution: "$I=\\dfrac{V}{R}=\\dfrac{9}{3}=3\\,$A." },
  { id: "pat-mk3-12", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 3, marks: 4,
    question: "A particle has momentum $4\\times10^{-24}\\,\\text{kg·m/s}$. With $h=6.6\\times10^{-34}$, its de Broglie wavelength (in $10^{-10}\\,\\text{m}$) is:",
    options: [{ key: "A", text: "$264$" },{ key: "B", text: "$3.3$" },{ key: "C", text: "$0.0606$" },{ key: "D", text: "$1.65$" },{ key: "E", text: "$0.6061$" }],
    answer: "D", solution: "$\\lambda=\\dfrac{h}{p}=\\dfrac{6.6\\times10^{-34}}{4\\times10^{-24}}=\\frac{33}{20}\\times10^{-10}\\,$m." },
  { id: "pat-mk3-13", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 1, marks: 4,
    question: "A wave has frequency $25\\,\\text{Hz}$ and wavelength $8\\,\\text{m}$. Its speed is:",
    options: [{ key: "A", text: "$400\\,\\text{m/s}$" },{ key: "B", text: "$0.32\\,\\text{m/s}$" },{ key: "C", text: "$33\\,\\text{m/s}$" },{ key: "D", text: "$200\\,\\text{m/s}$" },{ key: "E", text: "$3.125\\,\\text{m/s}$" }],
    answer: "D", solution: "$v=f\\lambda=25\\times8=200\\,$m/s." },
  { id: "pat-mk3-14", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 1, marks: 4,
    question: "The scalar (dot) product $(6\\,\\mathbf{i}+1\\,\\mathbf{j})\\cdot(2\\,\\mathbf{i}+2\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$10$" },{ key: "B", text: "$11$" },{ key: "C", text: "$13$" },{ key: "D", text: "$16$" },{ key: "E", text: "$14$" }],
    answer: "E", solution: "$\\mathbf{a}\\cdot\\mathbf{b}=6\\cdot2+1\\cdot2=14.$" },
  { id: "pat-mk3-15", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "A photon has frequency $3\\times10^{14}\\,\\text{Hz}$. Using $h=6.6\\times10^{-34}\\,\\text{J·s}$, its energy (in $10^{-20}\\,\\text{J}$) is:",
    options: [{ key: "A", text: "$198$" },{ key: "B", text: "$19.8$" },{ key: "C", text: "$22$" },{ key: "D", text: "$39.6$" },{ key: "E", text: "$4.5455$" }],
    answer: "B", solution: "$E=hf=6.6\\times10^{-34}\\times3\\times10^{14}=\\frac{99}{5}\\times10^{-20}\\,$J." },
  { id: "pat-mk3-16", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "A particle's position is $s(t)=2 x^{3} - x^{2}$. Its velocity at $t=1$ is:",
    options: [{ key: "A", text: "$10$" },{ key: "B", text: "$2$" },{ key: "C", text: "$1$" },{ key: "D", text: "$4$" },{ key: "E", text: "$5$" }],
    answer: "D", solution: "$v=\\dfrac{ds}{dt}=6 x^{2} - 2 x$; at $t=1$, $v=4.$" },
  { id: "pat-mk3-17", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "A $3\\,\\text{kg}$ trolley moving at $8\\,\\text{m/s}$ collides and sticks to a stationary $1\\,\\text{kg}$ trolley. Their common velocity is:",
    options: [{ key: "A", text: "$6\\,\\text{m/s}$" },{ key: "B", text: "$24\\,\\text{m/s}$" },{ key: "C", text: "$4\\,\\text{m/s}$" },{ key: "D", text: "$8\\,\\text{m/s}$" },{ key: "E", text: "$7\\,\\text{m/s}$" }],
    answer: "A", solution: "Momentum: $m_1u_1=(m_1+m_2)v\\Rightarrow v=\\dfrac{3\\cdot8}{4}=6\\,$m/s." },
  { id: "pat-mk3-18", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 1, marks: 4,
    question: "The magnitude of the vector $(9\\,\\mathbf{i}+12\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$21$" },{ key: "B", text: "$10.5$" },{ key: "C", text: "$16$" },{ key: "D", text: "$3$" },{ key: "E", text: "$15$" }],
    answer: "E", solution: "$|\\mathbf{v}|=\\sqrt{9^2+12^2}=15.$" },
  { id: "pat-mk3-19", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 1, marks: 4,
    question: "A wave has frequency $100\\,\\text{Hz}$ and wavelength $3\\,\\text{m}$. Its speed is:",
    options: [{ key: "A", text: "$300\\,\\text{m/s}$" },{ key: "B", text: "$33.3333\\,\\text{m/s}$" },{ key: "C", text: "$103\\,\\text{m/s}$" },{ key: "D", text: "$600\\,\\text{m/s}$" },{ key: "E", text: "$0.03\\,\\text{m/s}$" }],
    answer: "A", solution: "$v=f\\lambda=100\\times3=300\\,$m/s." },
  { id: "pat-mk3-20", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "A current of $3\\,\\text{A}$ flows for $4\\,\\text{s}$. The charge transferred is:",
    options: [{ key: "A", text: "$1.3333\\,\\text{C}$" },{ key: "B", text: "$7\\,\\text{C}$" },{ key: "C", text: "$12\\,\\text{C}$" },{ key: "D", text: "$6\\,\\text{C}$" },{ key: "E", text: "$24\\,\\text{C}$" }],
    answer: "C", solution: "$Q=It=3\\times4=12\\,$C." },
  { id: "pat-mk3-21", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "A fixed mass of gas at constant temperature has $P_1=1$, $V_1=10$. When pressure becomes $P_2=5$, the new volume is:",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$5$" },{ key: "C", text: "$6$" },{ key: "D", text: "$50$" },{ key: "E", text: "$3$" }],
    answer: "A", solution: "Boyle's law $P_1V_1=P_2V_2\\Rightarrow V_2=\\dfrac{1\\cdot10}{5}=2.$" },
  { id: "pat-mk3-22", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "The power dissipated by a $3\\,\\Omega$ resistor across $6\\,\\text{V}$ is:",
    options: [{ key: "A", text: "$36\\,\\text{W}$" },{ key: "B", text: "$6\\,\\text{W}$" },{ key: "C", text: "$2\\,\\text{W}$" },{ key: "D", text: "$12\\,\\text{W}$" },{ key: "E", text: "$18\\,\\text{W}$" }],
    answer: "D", solution: "$P=\\dfrac{V^2}{R}=\\dfrac{6^2}{3}=12\\,$W." },
  { id: "pat-mk3-23", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "Evaluate $\\displaystyle\\int_{1}^{3} 2x\\,dx$ (e.g. work done by a force $F=2x$):",
    options: [{ key: "A", text: "$16$" },{ key: "B", text: "$4$" },{ key: "C", text: "$6$" },{ key: "D", text: "$8$" },{ key: "E", text: "$9$" }],
    answer: "D", solution: "$\\int_{1}^{3}2x\\,dx=\\left[\\tfrac{2}{2}x^2\\right]_{1}^{3}=8.$" },
  { id: "pat-mk3-24", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "A photon has frequency $4\\times10^{14}\\,\\text{Hz}$. Using $h=6.6\\times10^{-34}\\,\\text{J·s}$, its energy (in $10^{-20}\\,\\text{J}$) is:",
    options: [{ key: "A", text: "$26.4$" },{ key: "B", text: "$6.0606$" },{ key: "C", text: "$16.5$" },{ key: "D", text: "$52.8$" },{ key: "E", text: "$264$" }],
    answer: "A", solution: "$E=hf=6.6\\times10^{-34}\\times4\\times10^{14}=\\frac{132}{5}\\times10^{-20}\\,$J." },
  { id: "pat-mk3-25", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "The kinetic energy of a $3\\,\\text{kg}$ mass moving at $4\\,\\text{m/s}$ is:",
    options: [{ key: "A", text: "$26\\,\\text{J}$" },{ key: "B", text: "$24\\,\\text{J}$" },{ key: "C", text: "$6\\,\\text{J}$" },{ key: "D", text: "$12\\,\\text{J}$" },{ key: "E", text: "$48\\,\\text{J}$" }],
    answer: "B", solution: "$E_k=\\tfrac12 mv^2=\\tfrac12(3)(4)^2=24\\,$J." },
];
