// STEP 模拟卷3 —— 25 道 STEP 难度选择题，id 前缀 step-mk3-*。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const STEP_MK3_MCQ: MCQQuestion[] = [
  { id: "step-mk3-01", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "For $X\\sim B(10,\\frac{1}{2})$, the variance $\\operatorname{Var}(X)$ is:",
    options: [{ key: "A", text: "$10$" },{ key: "B", text: "$\\frac{5}{2}$" },{ key: "C", text: "$\\frac{7}{2}$" },{ key: "D", text: "$5$" },{ key: "E", text: "$2$" }],
    answer: "B", solution: "$\\operatorname{Var}(X)=np(1-p)=10\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{5}{2}.$" },
  { id: "step-mk3-02", type: "mcq", testId: "step", topicId: "step-pure3", difficulty: 2, marks: 20,
    question: "The area between $y=\\sin{\\left(x \\right)}$ and the $x$-axis from $x=0$ to $x=\\pi$ (taking the definite integral) is:",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$3$" },{ key: "C", text: "$2$" },{ key: "D", text: "$4$" },{ key: "E", text: "$\\frac{5}{2}$" }],
    answer: "C", solution: "$\\int_{0}^{\\pi}\\sin{\\left(x \\right)}\\,dx=2.$" },
  { id: "step-mk3-03", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 1, marks: 20,
    question: "The determinant of $\\begin{pmatrix}1&2\\\\3&4\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$-4$" },{ key: "B", text: "$-2$" },{ key: "C", text: "$-5$" },{ key: "D", text: "$10$" },{ key: "E", text: "$-1$" }],
    answer: "B", solution: "$\\det=ad-bc=(1)(4)-(2)(3)=-2.$" },
  { id: "step-mk3-04", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The discriminant $-4p^3-27q^2$ of $x^3 + 3x + 1$ equals:",
    options: [{ key: "A", text: "$-135$" },{ key: "B", text: "$-134$" },{ key: "C", text: "$-81$" },{ key: "D", text: "$135$" },{ key: "E", text: "$-137$" }],
    answer: "A", solution: "$-4(3)^3-27(1)^2=-135.$ (Zero indicates a repeated root.)" },
  { id: "step-mk3-05", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 1, marks: 20,
    question: "The determinant of $\\begin{pmatrix}5&2\\\\1&3\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$11$" },{ key: "B", text: "$17$" },{ key: "C", text: "$-1$" },{ key: "D", text: "$13$" },{ key: "E", text: "$14$" }],
    answer: "D", solution: "$\\det=ad-bc=(5)(3)-(2)(1)=13.$" },
  { id: "step-mk3-06", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "The value of $\\displaystyle\\int_0^{\\pi/2}\\sin^{3} x\\,dx$ is:",
    options: [{ key: "A", text: "$\\frac{4}{3}$" },{ key: "B", text: "$\\frac{45 \\cdot 2^{\\frac{46}{389}} \\cdot 3^{\\frac{122}{389}} \\cdot 5^{\\frac{365}{389}} \\cdot 7^{\\frac{232}{389}}}{686}$" },{ key: "C", text: "$\\frac{1}{3}$" },{ key: "D", text: "$\\frac{2}{3}$" },{ key: "E", text: "$1$" }],
    answer: "D", solution: "By the reduction formula $I_n=\\frac{n-1}{n}I_{n-2}$, $I_{3}=\\frac{2}{3}.$" },
  { id: "step-mk3-07", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 2, marks: 20,
    question: "The improper integral $\\displaystyle\\int_1^\\infty x^{-\\frac{5}{2}}\\,dx$ equals:",
    options: [{ key: "A", text: "$\\frac{2}{3}$" },{ key: "B", text: "$\\frac{4}{3}$" },{ key: "C", text: "$\\frac{2}{5}$" },{ key: "D", text: "$\\frac{5}{2}$" },{ key: "E", text: "$\\frac{3}{2}$" }],
    answer: "A", solution: "$\\int_1^\\infty x^{-\\frac{5}{2}}dx=\\left[\\frac{x^{1-\\frac{5}{2}}}{1-\\frac{5}{2}}\\right]_1^\\infty=\\frac{1}{\\frac{5}{2}-1}=\\frac{2}{3}.$" },
  { id: "step-mk3-08", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 3, marks: 20,
    question: "The larger eigenvalue of $\\begin{pmatrix}2&0\\\\0&3\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$6$" },{ key: "C", text: "$5$" },{ key: "D", text: "$2$" },{ key: "E", text: "$4$" }],
    answer: "A", solution: "Solve $\\det(M-\\lambda I)=0$: $\\lambda^2-(5)\\lambda+(6)=0$; larger root $=3.$" },
  { id: "step-mk3-09", type: "mcq", testId: "step", topicId: "step-pure3", difficulty: 3, marks: 20,
    question: "The arc length of $y=4x$ from $x=0$ to $x=2$ is:",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$2 \\sqrt{17}$" },{ key: "C", text: "$4 \\sqrt{17}$" },{ key: "D", text: "$2$" },{ key: "E", text: "$10$" }],
    answer: "B", solution: "$L=\\int_0^2\\sqrt{1+(4)^2}\\,dx=(2)\\sqrt{17}=2 \\sqrt{17}.$" },
  { id: "step-mk3-10", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 3, marks: 20,
    question: "For roots $\\alpha,\\beta,\\gamma$ of $x^3 - 3x^2 + 2x + 0=0$, the value of $\\alpha^3+\\beta^3+\\gamma^3$ is:",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$9$" },{ key: "C", text: "$12$" },{ key: "D", text: "$6$" },{ key: "E", text: "$27$" }],
    answer: "B", solution: "$\\sum\\alpha^3=e_1^3-3e_1e_2+3e_3=(3)^3-3(3)(2)+3(0)=9.$" },
  { id: "step-mk3-11", type: "mcq", testId: "step", topicId: "step-mech", difficulty: 3, marks: 20,
    question: "A particle in SHM has amplitude $3\\,\\text{m}$ and angular frequency $2\\,\\text{rad/s}$. Its maximum speed is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$\\frac{3}{2}$" },{ key: "C", text: "$6$" },{ key: "D", text: "$12$" },{ key: "E", text: "$7$" }],
    answer: "C", solution: "Maximum speed $=a\\omega=3\\times2=6$ m/s." },
  { id: "step-mk3-12", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The discriminant $-4p^3-27q^2$ of $x^3 - 6x + 4$ equals:",
    options: [{ key: "A", text: "$-432$" },{ key: "B", text: "$430$" },{ key: "C", text: "$432$" },{ key: "D", text: "$1296$" },{ key: "E", text: "$433$" }],
    answer: "C", solution: "$-4(-6)^3-27(4)^2=432.$ (Zero indicates a repeated root.)" },
  { id: "step-mk3-13", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "A discrete random variable takes values with probabilities $P(1)=\\frac{1}{4}; P(2)=\\frac{1}{2}; P(4)=\\frac{1}{4}$. Its expectation is:",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$\\frac{9}{4}$" },{ key: "C", text: "$\\frac{13}{4}$" },{ key: "D", text: "$\\frac{25}{4}$" },{ key: "E", text: "$\\frac{7}{4}$" }],
    answer: "B", solution: "$E(X)=\\sum x P(x)=\\frac{9}{4}.$" },
  { id: "step-mk3-14", type: "mcq", testId: "step", topicId: "step-mech", difficulty: 2, marks: 20,
    question: "Mass $1\\,\\text{kg}$ at $10\\,\\text{m/s}$ collides and coalesces with a stationary $4\\,\\text{kg}$ mass. Their common speed is:",
    options: [{ key: "A", text: "$\\frac{5}{2}$" },{ key: "B", text: "$3$" },{ key: "C", text: "$5$" },{ key: "D", text: "$10$" },{ key: "E", text: "$2$" }],
    answer: "E", solution: "Momentum: $v=\\frac{m_1u_1}{m_1+m_2}=2$ m/s." },
  { id: "step-mk3-15", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 2, marks: 20,
    question: "The improper integral $\\displaystyle\\int_1^\\infty x^{-5}\\,dx$ equals:",
    options: [{ key: "A", text: "$\\frac{1}{2}$" },{ key: "B", text: "$\\frac{1}{4}$" },{ key: "C", text: "$4$" },{ key: "D", text: "$5$" },{ key: "E", text: "$\\frac{1}{5}$" }],
    answer: "B", solution: "$\\int_1^\\infty x^{-5}dx=\\left[\\frac{x^{1-5}}{1-5}\\right]_1^\\infty=\\frac{1}{5-1}=\\frac{1}{4}.$" },
  { id: "step-mk3-16", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The roots of $x^3 - 3x^2 + 2x + 0=0$ are $\\alpha,\\beta,\\gamma$. The value of $\\alpha^2+\\beta^2+\\gamma^2$ is:",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$-4$" },{ key: "C", text: "$13$" },{ key: "D", text: "$9$" },{ key: "E", text: "$5$" }],
    answer: "E", solution: "$\\sum\\alpha^2=(\\sum\\alpha)^2-2\\sum\\alpha\\beta=(3)^2-2(2)=5.$" },
  { id: "step-mk3-17", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The roots of $x^3 + 0x^2 - 7x + 6=0$ are $\\alpha,\\beta,\\gamma$. The value of $\\alpha^2+\\beta^2+\\gamma^2$ is:",
    options: [{ key: "A", text: "$-14$" },{ key: "B", text: "$14$" },{ key: "C", text: "$15$" },{ key: "D", text: "$0$" },{ key: "E", text: "$12$" }],
    answer: "B", solution: "$\\sum\\alpha^2=(\\sum\\alpha)^2-2\\sum\\alpha\\beta=(0)^2-2(-7)=14.$" },
  { id: "step-mk3-18", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 3, marks: 20,
    question: "The larger eigenvalue of $\\begin{pmatrix}5&2\\\\2&5\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$21$" },{ key: "C", text: "$8$" },{ key: "D", text: "$10$" },{ key: "E", text: "$3$" }],
    answer: "A", solution: "Solve $\\det(M-\\lambda I)=0$: $\\lambda^2-(10)\\lambda+(21)=0$; larger root $=7.$" },
  { id: "step-mk3-19", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 2, marks: 20,
    question: "The modulus $|(1+i)^{4}|$ equals:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$16$" },{ key: "C", text: "$4 \\sqrt{2}$" },{ key: "D", text: "$8$" },{ key: "E", text: "$5$" }],
    answer: "A", solution: "$|1+i|=\\sqrt2$, so $|(1+i)^{4}|=(\\sqrt2)^{4}=4.$" },
  { id: "step-mk3-20", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 3, marks: 20,
    question: "The sum of all the $n$-th roots of unity for $n=4$ is:",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$-1$" },{ key: "C", text: "$3$" },{ key: "D", text: "$4$" },{ key: "E", text: "$1$" }],
    answer: "A", solution: "The $n$-th roots of unity are roots of $z^{4}-1=0$; by Vieta their sum (coefficient of $z^{3}$ is $0$) is $0$." },
  { id: "step-mk3-21", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The roots of $x^3 - 4x^2 + 5x - 2=0$ are $\\alpha,\\beta,\\gamma$. The value of $\\alpha^2+\\beta^2+\\gamma^2$ is:",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$7$" },{ key: "C", text: "$-10$" },{ key: "D", text: "$26$" },{ key: "E", text: "$16$" }],
    answer: "A", solution: "$\\sum\\alpha^2=(\\sum\\alpha)^2-2\\sum\\alpha\\beta=(4)^2-2(5)=6.$" },
  { id: "step-mk3-22", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_{0}^{2} x^{3}\\,dx$.",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$2$" },{ key: "C", text: "$8$" },{ key: "D", text: "$3$" },{ key: "E", text: "$4$" }],
    answer: "E", solution: "Integration gives $\\int x^{3}\\,dx$; evaluating from $0$ to $2$ yields $4$." },
  { id: "step-mk3-23", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 3, marks: 20,
    question: "The sum of all the $n$-th roots of unity for $n=3$ is:",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$3$" },{ key: "C", text: "$1$" },{ key: "D", text: "$-1$" },{ key: "E", text: "$2$" }],
    answer: "A", solution: "The $n$-th roots of unity are roots of $z^{3}-1=0$; by Vieta their sum (coefficient of $z^{2}$ is $0$) is $0$." },
  { id: "step-mk3-24", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The discriminant $-4p^3-27q^2$ of $x^3 - 7x + 6$ equals:",
    options: [{ key: "A", text: "$2344$" },{ key: "B", text: "$-400$" },{ key: "C", text: "$398$" },{ key: "D", text: "$400$" },{ key: "E", text: "$401$" }],
    answer: "D", solution: "$-4(-7)^3-27(6)^2=400.$ (Zero indicates a repeated root.)" },
  { id: "step-mk3-25", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "The value of $\\displaystyle\\int_0^{\\pi/2}\\sin^{6} x\\,dx$ is:",
    options: [{ key: "A", text: "$\\frac{1}{3} + \\frac{5 \\pi}{32}$" },{ key: "B", text: "$\\frac{5 \\pi}{32}$" },{ key: "C", text: "$\\frac{5 \\pi}{16}$" },{ key: "D", text: "$\\frac{8 \\cdot 2^{\\frac{87}{226}} \\cdot 3^{\\frac{19}{113}} \\cdot 5^{\\frac{88}{113}} \\cdot 7^{\\frac{35}{113}}}{63}$" },{ key: "E", text: "$\\frac{5 \\pi}{64}$" }],
    answer: "B", solution: "By the reduction formula $I_n=\\frac{n-1}{n}I_{n-2}$, $I_{6}=\\frac{5 \\pi}{32}.$" },
];
