// STEP 模拟卷4 —— 25 道 STEP 难度选择题，id 前缀 step-mk4-*。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const STEP_MK4_MCQ: MCQQuestion[] = [
  { id: "step-mk4-01", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 1, marks: 20,
    question: "For $X\\sim B(12,\\frac{1}{3})$, the mean $E(X)$ is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$\\frac{1}{3}$" },{ key: "C", text: "$12$" },{ key: "D", text: "$\\frac{8}{3}$" },{ key: "E", text: "$4$" }],
    answer: "E", solution: "$E(X)=np=12\\cdot\\frac{1}{3}=4.$" },
  { id: "step-mk4-02", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "For $X\\sim B(5,\\frac{1}{2})$, $P(X=2)$ equals:",
    options: [{ key: "A", text: "$\\frac{5}{16}$" },{ key: "B", text: "$\\frac{1}{4}$" },{ key: "C", text: "$\\frac{5}{2}$" },{ key: "D", text: "$\\frac{33}{80}$" },{ key: "E", text: "$\\frac{5}{8}$" }],
    answer: "A", solution: "$P(X=2)=\\binom{5}{2}(\\frac{1}{2})^{2}(\\frac{1}{2})^{3}=\\frac{5}{16}.$" },
  { id: "step-mk4-03", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 3, marks: 20,
    question: "The larger eigenvalue of $\\begin{pmatrix}4&1\\\\2&3\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$2$" },{ key: "C", text: "$6$" },{ key: "D", text: "$5$" },{ key: "E", text: "$10$" }],
    answer: "D", solution: "Solve $\\det(M-\\lambda I)=0$: $\\lambda^2-(7)\\lambda+(10)=0$; larger root $=5.$" },
  { id: "step-mk4-04", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 1, marks: 20,
    question: "The determinant of $\\begin{pmatrix}2&1\\\\3&4\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$2$" },{ key: "C", text: "$3$" },{ key: "D", text: "$11$" },{ key: "E", text: "$5$" }],
    answer: "E", solution: "$\\det=ad-bc=(2)(4)-(1)(3)=5.$" },
  { id: "step-mk4-05", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 2, marks: 20,
    question: "The modulus $|(1+i)^{6}|$ equals:",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$8$" },{ key: "C", text: "$8 \\sqrt{2}$" },{ key: "D", text: "$16$" },{ key: "E", text: "$64$" }],
    answer: "B", solution: "$|1+i|=\\sqrt2$, so $|(1+i)^{6}|=(\\sqrt2)^{6}=8.$" },
  { id: "step-mk4-06", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 2, marks: 20,
    question: "The modulus $|(1+i)^{5}|$ equals:",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$4 \\sqrt{2}$" },{ key: "C", text: "$32$" },{ key: "D", text: "$8 \\sqrt{2}$" },{ key: "E", text: "$1 + 4 \\sqrt{2}$" }],
    answer: "B", solution: "$|1+i|=\\sqrt2$, so $|(1+i)^{5}|=(\\sqrt2)^{5}=4 \\sqrt{2}.$" },
  { id: "step-mk4-07", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_{1}^{e} \\log{\\left(x \\right)}\\,dx$.",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$\\frac{3}{2}$" },{ key: "C", text: "$2$" },{ key: "D", text: "$1$" },{ key: "E", text: "$\\frac{1}{2}$" }],
    answer: "D", solution: "Integration gives $\\int \\log{\\left(x \\right)}\\,dx$; evaluating from $1$ to $e$ yields $1$." },
  { id: "step-mk4-08", type: "mcq", testId: "step", topicId: "step-mech", difficulty: 3, marks: 20,
    question: "A particle in SHM has amplitude $4\\,\\text{m}$ and angular frequency $2\\,\\text{rad/s}$. Its maximum speed is:",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$8$" },{ key: "C", text: "$16$" },{ key: "D", text: "$2$" },{ key: "E", text: "$9$" }],
    answer: "B", solution: "Maximum speed $=a\\omega=4\\times2=8$ m/s." },
  { id: "step-mk4-09", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 3, marks: 20,
    question: "A disease affects a proportion $\\frac{1}{50}$ of a population. A test is positive with probability $\\frac{4}{5}$ if diseased and $\\frac{1}{20}$ if not. Given a positive test, the probability of disease is:",
    options: [{ key: "A", text: "$\\frac{16}{65}$" },{ key: "B", text: "$\\frac{1}{50}$" },{ key: "C", text: "$\\frac{9}{26}$" },{ key: "D", text: "$\\frac{4}{5}$" },{ key: "E", text: "$\\frac{49}{65}$" }],
    answer: "A", solution: "By Bayes: $P(D\\mid+)=\\dfrac{P(+\\mid D)P(D)}{P(+)}=\\frac{16}{65}.$" },
  { id: "step-mk4-10", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 1, marks: 20,
    question: "The determinant of $\\begin{pmatrix}3&3\\\\1&2\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$3$" },{ key: "C", text: "$4$" },{ key: "D", text: "$1$" },{ key: "E", text: "$-3$" }],
    answer: "B", solution: "$\\det=ad-bc=(3)(2)-(3)(1)=3.$" },
  { id: "step-mk4-11", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "For $X\\sim B(12,\\frac{1}{3})$, the variance $\\operatorname{Var}(X)$ is:",
    options: [{ key: "A", text: "$\\frac{13}{6}$" },{ key: "B", text: "$\\frac{8}{3}$" },{ key: "C", text: "$4$" },{ key: "D", text: "$12$" },{ key: "E", text: "$\\frac{11}{3}$" }],
    answer: "B", solution: "$\\operatorname{Var}(X)=np(1-p)=12\\cdot\\frac{1}{3}\\cdot\\frac{2}{3}=\\frac{8}{3}.$" },
  { id: "step-mk4-12", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_{0}^{\\pi} x \\sin{\\left(x \\right)}\\,dx$.",
    options: [{ key: "A", text: "$-1 + \\pi$" },{ key: "B", text: "$\\pi$" },{ key: "C", text: "$1 + \\pi$" },{ key: "D", text: "$\\frac{\\pi}{2}$" },{ key: "E", text: "$2 \\pi$" }],
    answer: "B", solution: "Integration gives $\\int x \\sin{\\left(x \\right)}\\,dx$; evaluating from $0$ to $\\pi$ yields $\\pi$." },
  { id: "step-mk4-13", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_{1}^{3} \\frac{1}{x^{2}}\\,dx$.",
    options: [{ key: "A", text: "$\\frac{2}{3}$" },{ key: "B", text: "$\\frac{5}{3}$" },{ key: "C", text: "$\\frac{1}{3}$" },{ key: "D", text: "$- \\frac{1}{3}$" },{ key: "E", text: "$\\frac{4}{3}$" }],
    answer: "A", solution: "Integration gives $\\int \\frac{1}{x^{2}}\\,dx$; evaluating from $1$ to $3$ yields $\\frac{2}{3}$." },
  { id: "step-mk4-14", type: "mcq", testId: "step", topicId: "step-pure3", difficulty: 2, marks: 20,
    question: "The area between $y=x^{3} - x$ and the $x$-axis from $x=0$ to $x=1$ (taking the definite integral) is:",
    options: [{ key: "A", text: "$- \\frac{1}{4}$" },{ key: "B", text: "$- \\frac{1}{2}$" },{ key: "C", text: "$- \\frac{1}{8}$" },{ key: "D", text: "$- \\frac{5}{4}$" },{ key: "E", text: "$\\frac{3}{4}$" }],
    answer: "A", solution: "$\\int_{0}^{1}x^{3} - x\\,dx=- \\frac{1}{4}.$" },
  { id: "step-mk4-15", type: "mcq", testId: "step", topicId: "step-mech", difficulty: 3, marks: 20,
    question: "A $2\\,\\text{kg}$ mass hangs and pulls a $3\\,\\text{kg}$ mass on a smooth horizontal table via a pulley ($g=10$). The acceleration is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$6$" },{ key: "C", text: "$\\frac{20}{3}$" },{ key: "D", text: "$4$" },{ key: "E", text: "$10$" }],
    answer: "D", solution: "$a=\\frac{m_1 g}{m_1+m_2}=\\frac{2\\cdot10}{5}=4$ m/s²." },
  { id: "step-mk4-16", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 2, marks: 20,
    question: "The improper integral $\\displaystyle\\int_1^\\infty x^{-4}\\,dx$ equals:",
    options: [{ key: "A", text: "$\\frac{2}{3}$" },{ key: "B", text: "$\\frac{1}{4}$" },{ key: "C", text: "$\\frac{1}{3}$" },{ key: "D", text: "$4$" },{ key: "E", text: "$3$" }],
    answer: "C", solution: "$\\int_1^\\infty x^{-4}dx=\\left[\\frac{x^{1-4}}{1-4}\\right]_1^\\infty=\\frac{1}{4-1}=\\frac{1}{3}.$" },
  { id: "step-mk4-17", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 2, marks: 20,
    question: "The determinant of $\\begin{pmatrix}2&1&0\\\\0&1&1\\\\0&0&4\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$8$" },{ key: "C", text: "$7$" },{ key: "D", text: "$6$" },{ key: "E", text: "$2$" }],
    answer: "B", solution: "For an upper-triangular matrix the determinant is the product of the diagonal: $2\\cdot1\\cdot4=8.$" },
  { id: "step-mk4-18", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "A discrete random variable takes values with probabilities $P(0)=\\frac{1}{2}; P(1)=\\frac{1}{3}; P(3)=\\frac{1}{6}$. Its expectation is:",
    options: [{ key: "A", text: "$\\frac{5}{3}$" },{ key: "B", text: "$\\frac{1}{3}$" },{ key: "C", text: "$\\frac{11}{6}$" },{ key: "D", text: "$4$" },{ key: "E", text: "$\\frac{5}{6}$" }],
    answer: "E", solution: "$E(X)=\\sum x P(x)=\\frac{5}{6}.$" },
  { id: "step-mk4-19", type: "mcq", testId: "step", topicId: "step-mech", difficulty: 3, marks: 20,
    question: "A particle in SHM has amplitude $2\\,\\text{m}$ and angular frequency $3\\,\\text{rad/s}$. Its maximum speed is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$\\frac{2}{3}$" },{ key: "C", text: "$6$" },{ key: "D", text: "$7$" },{ key: "E", text: "$18$" }],
    answer: "C", solution: "Maximum speed $=a\\omega=2\\times3=6$ m/s." },
  { id: "step-mk4-20", type: "mcq", testId: "step", topicId: "step-pure3", difficulty: 2, marks: 20,
    question: "The area between $y=x^{2}$ and the $x$-axis from $x=0$ to $x=3$ (taking the definite integral) is:",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$\\frac{9}{2}$" },{ key: "C", text: "$10$" },{ key: "D", text: "$18$" },{ key: "E", text: "$9$" }],
    answer: "E", solution: "$\\int_{0}^{3}x^{2}\\,dx=9.$" },
  { id: "step-mk4-21", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_{0}^{1} x e^{x}\\,dx$.",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$\\frac{1}{2}$" },{ key: "C", text: "$1$" },{ key: "D", text: "$0$" },{ key: "E", text: "$\\frac{3}{2}$" }],
    answer: "C", solution: "Integration gives $\\int x e^{x}\\,dx$; evaluating from $0$ to $1$ yields $1$." },
  { id: "step-mk4-22", type: "mcq", testId: "step", topicId: "step-mech", difficulty: 3, marks: 20,
    question: "A $3\\,\\text{kg}$ mass hangs and pulls a $2\\,\\text{kg}$ mass on a smooth horizontal table via a pulley ($g=10$). The acceleration is:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$6$" },{ key: "C", text: "$7$" },{ key: "D", text: "$10$" },{ key: "E", text: "$15$" }],
    answer: "B", solution: "$a=\\frac{m_1 g}{m_1+m_2}=\\frac{3\\cdot10}{5}=6$ m/s²." },
  { id: "step-mk4-23", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The roots of $x^3 + 3x^2 + 3x + 1=0$ are $\\alpha,\\beta,\\gamma$. The value of $\\alpha^2+\\beta^2+\\gamma^2$ is:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$-6$" },{ key: "C", text: "$3$" },{ key: "D", text: "$9$" },{ key: "E", text: "$15$" }],
    answer: "C", solution: "$\\sum\\alpha^2=(\\sum\\alpha)^2-2\\sum\\alpha\\beta=(-3)^2-2(3)=3.$" },
  { id: "step-mk4-24", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 2, marks: 20,
    question: "The determinant of $\\begin{pmatrix}1&1&0\\\\0&1&1\\\\0&0&5\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$5$" },{ key: "C", text: "$3$" },{ key: "D", text: "$7$" },{ key: "E", text: "$1$" }],
    answer: "B", solution: "For an upper-triangular matrix the determinant is the product of the diagonal: $1\\cdot1\\cdot5=5.$" },
  { id: "step-mk4-25", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The discriminant $-4p^3-27q^2$ of $x^3 - 1x + 0$ equals:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$2$" },{ key: "C", text: "$-4$" },{ key: "D", text: "$0$" },{ key: "E", text: "$4$" }],
    answer: "E", solution: "$-4(-1)^3-27(0)^2=4.$ (Zero indicates a repeated root.)" },
];
