// STEP 模拟卷1 —— 25 道 STEP 难度选择题，id 前缀 step-mk1-*。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const STEP_MK1_MCQ: MCQQuestion[] = [
  { id: "step-mk1-01", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The discriminant $-4p^3-27q^2$ of $x^3 - 3x + 2$ equals:",
    options: [{ key: "A", text: "$-108$" },{ key: "B", text: "$-2$" },{ key: "C", text: "$1$" },{ key: "D", text: "$216$" },{ key: "E", text: "$0$" }],
    answer: "E", solution: "$-4(-3)^3-27(2)^2=0.$ (Zero indicates a repeated root.)" },
  { id: "step-mk1-02", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_{0}^{\\frac{\\pi}{2}} x \\cos{\\left(x \\right)}\\,dx$.",
    options: [{ key: "A", text: "$-1 + \\frac{\\pi}{2}$" },{ key: "B", text: "$-2 + \\frac{\\pi}{2}$" },{ key: "C", text: "$-2 + \\pi$" },{ key: "D", text: "$\\frac{\\pi}{2}$" },{ key: "E", text: "$- \\frac{1}{2} + \\frac{\\pi}{4}$" }],
    answer: "A", solution: "Integration gives $\\int x \\cos{\\left(x \\right)}\\,dx$; evaluating from $0$ to $\\frac{\\pi}{2}$ yields $-1 + \\frac{\\pi}{2}$." },
  { id: "step-mk1-03", type: "mcq", testId: "step", topicId: "step-mech", difficulty: 2, marks: 20,
    question: "A particle is projected vertically upward at $30\\,\\text{m/s}$ ($g=10$). The greatest height reached is:",
    options: [{ key: "A", text: "$\\frac{45}{2}$" },{ key: "B", text: "$90$" },{ key: "C", text: "$45$" },{ key: "D", text: "$50$" },{ key: "E", text: "$30$" }],
    answer: "C", solution: "$h=\\frac{u^2}{2g}=\\frac{30^2}{20}=45$ m." },
  { id: "step-mk1-04", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "For $X\\sim B(6,\\frac{1}{2})$, $P(X=3)$ equals:",
    options: [{ key: "A", text: "$\\frac{5}{2}$" },{ key: "B", text: "$\\frac{1}{8}$" },{ key: "C", text: "$\\frac{5}{8}$" },{ key: "D", text: "$\\frac{33}{80}$" },{ key: "E", text: "$\\frac{5}{16}$" }],
    answer: "E", solution: "$P(X=3)=\\binom{6}{3}(\\frac{1}{2})^{3}(\\frac{1}{2})^{3}=\\frac{5}{16}.$" },
  { id: "step-mk1-05", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "The value of $\\displaystyle\\int_0^{\\pi/2}\\sin^{2} x\\,dx$ is:",
    options: [{ key: "A", text: "$\\frac{1}{7} + \\frac{\\pi}{4}$" },{ key: "B", text: "$\\frac{\\pi}{2}$" },{ key: "C", text: "$\\frac{\\pi}{8}$" },{ key: "D", text: "$\\frac{\\pi}{4}$" },{ key: "E", text: "$\\frac{1}{3} + \\frac{\\pi}{4}$" }],
    answer: "D", solution: "By the reduction formula $I_n=\\frac{n-1}{n}I_{n-2}$, $I_{2}=\\frac{\\pi}{4}.$" },
  { id: "step-mk1-06", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "The value of $\\displaystyle\\int_0^{\\pi/2}\\sin^{4} x\\,dx$ is:",
    options: [{ key: "A", text: "$\\frac{7 \\pi}{16}$" },{ key: "B", text: "$\\frac{1}{3} + \\frac{3 \\pi}{16}$" },{ key: "C", text: "$\\frac{3 \\pi}{16}$" },{ key: "D", text: "$\\frac{3 \\pi}{8}$" },{ key: "E", text: "$\\frac{3 \\pi}{32}$" }],
    answer: "C", solution: "By the reduction formula $I_n=\\frac{n-1}{n}I_{n-2}$, $I_{4}=\\frac{3 \\pi}{16}.$" },
  { id: "step-mk1-07", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 2, marks: 20,
    question: "The modulus $|(1+i)^{3}|$ equals:",
    options: [{ key: "A", text: "$1 + 2 \\sqrt{2}$" },{ key: "B", text: "$4$" },{ key: "C", text: "$8$" },{ key: "D", text: "$2 \\sqrt{2}$" },{ key: "E", text: "$4 \\sqrt{2}$" }],
    answer: "D", solution: "$|1+i|=\\sqrt2$, so $|(1+i)^{3}|=(\\sqrt2)^{3}=2 \\sqrt{2}.$" },
  { id: "step-mk1-08", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 1, marks: 20,
    question: "The determinant of $\\begin{pmatrix}1&-2\\\\3&1\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$1$" },{ key: "C", text: "$-5$" },{ key: "D", text: "$8$" },{ key: "E", text: "$5$" }],
    answer: "A", solution: "$\\det=ad-bc=(1)(1)-(-2)(3)=7.$" },
  { id: "step-mk1-09", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_{0}^{1} e^{2 x}\\,dx$.",
    options: [{ key: "A", text: "$\\frac{1}{2} + \\frac{e^{2}}{2}$" },{ key: "B", text: "$-1 + e^{2}$" },{ key: "C", text: "$- \\frac{3}{2} + \\frac{e^{2}}{2}$" },{ key: "D", text: "$- \\frac{1}{2} + \\frac{e^{2}}{2}$" },{ key: "E", text: "$- \\frac{1}{4} + \\frac{e^{2}}{4}$" }],
    answer: "D", solution: "Integration gives $\\int e^{2 x}\\,dx$; evaluating from $0$ to $1$ yields $- \\frac{1}{2} + \\frac{e^{2}}{2}$." },
  { id: "step-mk1-10", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 3, marks: 20,
    question: "For roots $\\alpha,\\beta,\\gamma$ of $x^3 - 6x^2 + 11x - 6=0$, the value of $\\alpha^3+\\beta^3+\\gamma^3$ is:",
    options: [{ key: "A", text: "$39$" },{ key: "B", text: "$18$" },{ key: "C", text: "$33$" },{ key: "D", text: "$36$" },{ key: "E", text: "$216$" }],
    answer: "D", solution: "$\\sum\\alpha^3=e_1^3-3e_1e_2+3e_3=(6)^3-3(6)(11)+3(6)=36.$" },
  { id: "step-mk1-11", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 3, marks: 20,
    question: "The sum of all the $n$-th roots of unity for $n=6$ is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$1$" },{ key: "C", text: "$-1$" },{ key: "D", text: "$0$" },{ key: "E", text: "$6$" }],
    answer: "D", solution: "The $n$-th roots of unity are roots of $z^{6}-1=0$; by Vieta their sum (coefficient of $z^{5}$ is $0$) is $0$." },
  { id: "step-mk1-12", type: "mcq", testId: "step", topicId: "step-pure3", difficulty: 3, marks: 20,
    question: "The arc length of $y=3x$ from $x=1$ to $x=4$ is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$3 \\sqrt{10}$" },{ key: "C", text: "$6 \\sqrt{10}$" },{ key: "D", text: "$12$" },{ key: "E", text: "$9$" }],
    answer: "B", solution: "$L=\\int_1^4\\sqrt{1+(3)^2}\\,dx=(3)\\sqrt{10}=3 \\sqrt{10}.$" },
  { id: "step-mk1-13", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "For $X\\sim B(5,\\frac{2}{5})$, $P(X=3)$ equals:",
    options: [{ key: "A", text: "$\\frac{16}{25}$" },{ key: "B", text: "$\\frac{144}{625}$" },{ key: "C", text: "$\\frac{8}{125}$" },{ key: "D", text: "$\\frac{288}{625}$" },{ key: "E", text: "$\\frac{413}{1250}$" }],
    answer: "B", solution: "$P(X=3)=\\binom{5}{3}(\\frac{2}{5})^{3}(\\frac{3}{5})^{2}=\\frac{144}{625}.$" },
  { id: "step-mk1-14", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 2, marks: 20,
    question: "The improper integral $\\displaystyle\\int_1^\\infty x^{-3}\\,dx$ equals:",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$\\frac{1}{3}$" },{ key: "C", text: "$2$" },{ key: "D", text: "$3$" },{ key: "E", text: "$\\frac{1}{2}$" }],
    answer: "E", solution: "$\\int_1^\\infty x^{-3}dx=\\left[\\frac{x^{1-3}}{1-3}\\right]_1^\\infty=\\frac{1}{3-1}=\\frac{1}{2}.$" },
  { id: "step-mk1-15", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "The value of $\\displaystyle\\int_0^{\\pi/2}\\sin^{5} x\\,dx$ is:",
    options: [{ key: "A", text: "$\\frac{13}{15}$" },{ key: "B", text: "$\\frac{16}{15}$" },{ key: "C", text: "$\\frac{8}{15}$" },{ key: "D", text: "$\\frac{8}{15} + \\frac{\\pi}{4}$" },{ key: "E", text: "$\\frac{4}{15}$" }],
    answer: "C", solution: "By the reduction formula $I_n=\\frac{n-1}{n}I_{n-2}$, $I_{5}=\\frac{8}{15}.$" },
  { id: "step-mk1-16", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 1, marks: 20,
    question: "For $X\\sim B(8,\\frac{3}{4})$, the mean $E(X)$ is:",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$\\frac{3}{2}$" },{ key: "C", text: "$6$" },{ key: "D", text: "$\\frac{3}{4}$" },{ key: "E", text: "$7$" }],
    answer: "C", solution: "$E(X)=np=8\\cdot\\frac{3}{4}=6.$" },
  { id: "step-mk1-17", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 3, marks: 20,
    question: "The larger eigenvalue of $\\begin{pmatrix}6&2\\\\1&3\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$\\frac{9}{2} - \\frac{\\sqrt{17}}{2}$" },{ key: "C", text: "$\\frac{\\sqrt{17}}{2} + \\frac{11}{2}$" },{ key: "D", text: "$16$" },{ key: "E", text: "$\\frac{\\sqrt{17}}{2} + \\frac{9}{2}$" }],
    answer: "E", solution: "Solve $\\det(M-\\lambda I)=0$: $\\lambda^2-(9)\\lambda+(16)=0$; larger root $=\\frac{\\sqrt{17}}{2} + \\frac{9}{2}.$" },
  { id: "step-mk1-18", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The roots of $x^3 - 6x^2 + 11x - 6=0$ are $\\alpha,\\beta,\\gamma$. The value of $\\alpha^2+\\beta^2+\\gamma^2$ is:",
    options: [{ key: "A", text: "$15$" },{ key: "B", text: "$58$" },{ key: "C", text: "$14$" },{ key: "D", text: "$36$" },{ key: "E", text: "$-22$" }],
    answer: "C", solution: "$\\sum\\alpha^2=(\\sum\\alpha)^2-2\\sum\\alpha\\beta=(6)^2-2(11)=14.$" },
  { id: "step-mk1-19", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "For $X\\sim B(6,\\frac{1}{3})$, $P(X=2)$ equals:",
    options: [{ key: "A", text: "$\\frac{5}{3}$" },{ key: "B", text: "$\\frac{1}{9}$" },{ key: "C", text: "$\\frac{1043}{2430}$" },{ key: "D", text: "$\\frac{80}{243}$" },{ key: "E", text: "$\\frac{160}{243}$" }],
    answer: "D", solution: "$P(X=2)=\\binom{6}{2}(\\frac{1}{3})^{2}(\\frac{2}{3})^{4}=\\frac{80}{243}.$" },
  { id: "step-mk1-20", type: "mcq", testId: "step", topicId: "step-pure3", difficulty: 3, marks: 20,
    question: "The arc length of $y=2x$ from $x=0$ to $x=3$ is:",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$6$" },{ key: "C", text: "$3$" },{ key: "D", text: "$3 \\sqrt{5}$" },{ key: "E", text: "$6 \\sqrt{5}$" }],
    answer: "D", solution: "$L=\\int_0^3\\sqrt{1+(2)^2}\\,dx=(3)\\sqrt{5}=3 \\sqrt{5}.$" },
  { id: "step-mk1-21", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 3, marks: 20,
    question: "Using De Moivre, the real part of $(\\cos\\tfrac{1\\pi}{3}+i\\sin\\tfrac{1\\pi}{3})^{2}$ is:",
    options: [{ key: "A", text: "$\\frac{\\sqrt{3}}{2}$" },{ key: "B", text: "$-1$" },{ key: "C", text: "$- \\frac{1}{2}$" },{ key: "D", text: "$\\frac{1}{2}$" },{ key: "E", text: "$- \\frac{3}{2}$" }],
    answer: "C", solution: "$(\\cos\\theta+i\\sin\\theta)^{2}=\\cos 2\\theta+i\\sin 2\\theta$; real part $=\\cos(2\\cdot\\tfrac{1\\pi}{3})=- \\frac{1}{2}.$" },
  { id: "step-mk1-22", type: "mcq", testId: "step", topicId: "step-pure3", difficulty: 2, marks: 20,
    question: "The area swept by the polar curve $r=3$ from $\\theta=0$ to $\\theta=\\pi$ is:",
    options: [{ key: "A", text: "$9 \\pi$" },{ key: "B", text: "$\\frac{9 \\pi}{2}$" },{ key: "C", text: "$\\frac{3 \\pi}{2}$" },{ key: "D", text: "$3 \\pi$" },{ key: "E", text: "$\\frac{11 \\pi}{2}$" }],
    answer: "B", solution: "$A=\\int_0^{\\pi}\\tfrac12 r^2\\,d\\theta=\\tfrac12(3)^2(\\pi)=\\frac{9 \\pi}{2}.$" },
  { id: "step-mk1-23", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 2, marks: 20,
    question: "The modulus $|(1+i)^{8}|$ equals:",
    options: [{ key: "A", text: "$17$" },{ key: "B", text: "$256$" },{ key: "C", text: "$32$" },{ key: "D", text: "$16$" },{ key: "E", text: "$16 \\sqrt{2}$" }],
    answer: "D", solution: "$|1+i|=\\sqrt2$, so $|(1+i)^{8}|=(\\sqrt2)^{8}=16.$" },
  { id: "step-mk1-24", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 3, marks: 20,
    question: "A disease affects a proportion $\\frac{1}{100}$ of a population. A test is positive with probability $\\frac{9}{10}$ if diseased and $\\frac{1}{10}$ if not. Given a positive test, the probability of disease is:",
    options: [{ key: "A", text: "$\\frac{11}{12}$" },{ key: "B", text: "$\\frac{1}{100}$" },{ key: "C", text: "$\\frac{1}{12}$" },{ key: "D", text: "$\\frac{11}{60}$" },{ key: "E", text: "$\\frac{9}{10}$" }],
    answer: "C", solution: "By Bayes: $P(D\\mid+)=\\dfrac{P(+\\mid D)P(D)}{P(+)}=\\frac{1}{12}.$" },
  { id: "step-mk1-25", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 1, marks: 20,
    question: "For $X\\sim B(15,\\frac{2}{5})$, the mean $E(X)$ is:",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$15$" },{ key: "C", text: "$6$" },{ key: "D", text: "$\\frac{2}{5}$" },{ key: "E", text: "$\\frac{18}{5}$" }],
    answer: "C", solution: "$E(X)=np=15\\cdot\\frac{2}{5}=6.$" },
];
