// STEP 模拟卷2 —— 25 道 STEP 难度选择题，id 前缀 step-mk2-*。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const STEP_MK2_MCQ: MCQQuestion[] = [
  { id: "step-mk2-01", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 2, marks: 20,
    question: "The improper integral $\\displaystyle\\int_1^\\infty x^{-\\frac{3}{2}}\\,dx$ equals:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$\\frac{2}{3}$" },{ key: "C", text: "$\\frac{1}{2}$" },{ key: "D", text: "$\\frac{3}{2}$" },{ key: "E", text: "$2$" }],
    answer: "E", solution: "$\\int_1^\\infty x^{-\\frac{3}{2}}dx=\\left[\\frac{x^{1-\\frac{3}{2}}}{1-\\frac{3}{2}}\\right]_1^\\infty=\\frac{1}{\\frac{3}{2}-1}=2.$" },
  { id: "step-mk2-02", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "A discrete random variable takes values with probabilities $P(1)=\\frac{1}{2}; P(3)=\\frac{1}{4}; P(5)=\\frac{1}{4}$. Its expectation is:",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$\\frac{5}{2}$" },{ key: "C", text: "$5$" },{ key: "D", text: "$2$" },{ key: "E", text: "$\\frac{7}{2}$" }],
    answer: "B", solution: "$E(X)=\\sum x P(x)=\\frac{5}{2}.$" },
  { id: "step-mk2-03", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 1, marks: 20,
    question: "For $X\\sim B(10,\\frac{1}{2})$, the mean $E(X)$ is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$6$" },{ key: "C", text: "$\\frac{5}{2}$" },{ key: "D", text: "$\\frac{1}{2}$" },{ key: "E", text: "$10$" }],
    answer: "A", solution: "$E(X)=np=10\\cdot\\frac{1}{2}=5.$" },
  { id: "step-mk2-04", type: "mcq", testId: "step", topicId: "step-pure3", difficulty: 2, marks: 20,
    question: "The area between $y=\\frac{1}{x}$ and the $x$-axis from $x=1$ to $x=e$ (taking the definite integral) is:",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$0$" },{ key: "C", text: "$2$" },{ key: "D", text: "$\\frac{3}{2}$" },{ key: "E", text: "$\\frac{1}{2}$" }],
    answer: "A", solution: "$\\int_{1}^{e}\\frac{1}{x}\\,dx=1.$" },
  { id: "step-mk2-05", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 1, marks: 20,
    question: "The determinant of $\\begin{pmatrix}2&0\\\\1&6\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$13$" },{ key: "B", text: "$10$" },{ key: "C", text: "$7$" },{ key: "D", text: "$2$" },{ key: "E", text: "$12$" }],
    answer: "E", solution: "$\\det=ad-bc=(2)(6)-(0)(1)=12.$" },
  { id: "step-mk2-06", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_{1}^{e} x \\log{\\left(x \\right)}\\,dx$.",
    options: [{ key: "A", text: "$\\frac{5}{4} + \\frac{e^{2}}{4}$" },{ key: "B", text: "$- \\frac{3}{4} + \\frac{e^{2}}{4}$" },{ key: "C", text: "$\\frac{1}{2} + \\frac{e^{2}}{2}$" },{ key: "D", text: "$\\frac{1}{8} + \\frac{e^{2}}{8}$" },{ key: "E", text: "$\\frac{1}{4} + \\frac{e^{2}}{4}$" }],
    answer: "E", solution: "Integration gives $\\int x \\log{\\left(x \\right)}\\,dx$; evaluating from $1$ to $e$ yields $\\frac{1}{4} + \\frac{e^{2}}{4}$." },
  { id: "step-mk2-07", type: "mcq", testId: "step", topicId: "step-mech", difficulty: 3, marks: 20,
    question: "A particle in SHM has amplitude $5\\,\\text{m}$ and angular frequency $4\\,\\text{rad/s}$. Its maximum speed is:",
    options: [{ key: "A", text: "$21$" },{ key: "B", text: "$\\frac{5}{4}$" },{ key: "C", text: "$80$" },{ key: "D", text: "$9$" },{ key: "E", text: "$20$" }],
    answer: "E", solution: "Maximum speed $=a\\omega=5\\times4=20$ m/s." },
  { id: "step-mk2-08", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 3, marks: 20,
    question: "For roots $\\alpha,\\beta,\\gamma$ of $x^3 - 4x^2 + 5x - 2=0$, the value of $\\alpha^3+\\beta^3+\\gamma^3$ is:",
    options: [{ key: "A", text: "$13$" },{ key: "B", text: "$10$" },{ key: "C", text: "$64$" },{ key: "D", text: "$7$" },{ key: "E", text: "$4$" }],
    answer: "B", solution: "$\\sum\\alpha^3=e_1^3-3e_1e_2+3e_3=(4)^3-3(4)(5)+3(2)=10.$" },
  { id: "step-mk2-09", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "For $X\\sim B(8,\\frac{3}{4})$, the variance $\\operatorname{Var}(X)$ is:",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$\\frac{3}{2}$" },{ key: "C", text: "$6$" },{ key: "D", text: "$1$" },{ key: "E", text: "$\\frac{5}{2}$" }],
    answer: "B", solution: "$\\operatorname{Var}(X)=np(1-p)=8\\cdot\\frac{3}{4}\\cdot\\frac{1}{4}=\\frac{3}{2}.$" },
  { id: "step-mk2-10", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The discriminant $-4p^3-27q^2$ of $x^3 - 12x + 16$ equals:",
    options: [{ key: "A", text: "$13824$" },{ key: "B", text: "$-6912$" },{ key: "C", text: "$1$" },{ key: "D", text: "$-2$" },{ key: "E", text: "$0$" }],
    answer: "E", solution: "$-4(-12)^3-27(16)^2=0.$ (Zero indicates a repeated root.)" },
  { id: "step-mk2-11", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 2, marks: 20,
    question: "The determinant of $\\begin{pmatrix}2&1&0\\\\0&3&1\\\\0&0&2\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$7$" },{ key: "C", text: "$10$" },{ key: "D", text: "$12$" },{ key: "E", text: "$13$" }],
    answer: "D", solution: "For an upper-triangular matrix the determinant is the product of the diagonal: $2\\cdot3\\cdot2=12.$" },
  { id: "step-mk2-12", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "A discrete random variable takes values with probabilities $P(0)=\\frac{1}{3}; P(2)=\\frac{1}{3}; P(5)=\\frac{1}{3}$. Its expectation is:",
    options: [{ key: "A", text: "$\\frac{29}{3}$" },{ key: "B", text: "$\\frac{11}{6}$" },{ key: "C", text: "$\\frac{10}{3}$" },{ key: "D", text: "$7$" },{ key: "E", text: "$\\frac{7}{3}$" }],
    answer: "E", solution: "$E(X)=\\sum x P(x)=\\frac{7}{3}.$" },
  { id: "step-mk2-13", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "For $X\\sim B(20,\\frac{1}{4})$, the variance $\\operatorname{Var}(X)$ is:",
    options: [{ key: "A", text: "$\\frac{19}{4}$" },{ key: "B", text: "$\\frac{13}{4}$" },{ key: "C", text: "$5$" },{ key: "D", text: "$20$" },{ key: "E", text: "$\\frac{15}{4}$" }],
    answer: "E", solution: "$\\operatorname{Var}(X)=np(1-p)=20\\cdot\\frac{1}{4}\\cdot\\frac{3}{4}=\\frac{15}{4}.$" },
  { id: "step-mk2-14", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The roots of $x^3 - 1x^2 - 4x + 4=0$ are $\\alpha,\\beta,\\gamma$. The value of $\\alpha^2+\\beta^2+\\gamma^2$ is:",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$10$" },{ key: "C", text: "$8$" },{ key: "D", text: "$9$" },{ key: "E", text: "$-7$" }],
    answer: "D", solution: "$\\sum\\alpha^2=(\\sum\\alpha)^2-2\\sum\\alpha\\beta=(1)^2-2(-4)=9.$" },
  { id: "step-mk2-15", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 1, marks: 20,
    question: "The determinant of $\\begin{pmatrix}4&1\\\\2&5\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$18$" },{ key: "B", text: "$22$" },{ key: "C", text: "$16$" },{ key: "D", text: "$19$" },{ key: "E", text: "$3$" }],
    answer: "A", solution: "$\\det=ad-bc=(4)(5)-(1)(2)=18.$" },
  { id: "step-mk2-16", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 3, marks: 20,
    question: "A disease affects a proportion $\\frac{1}{10}$ of a population. A test is positive with probability $1$ if diseased and $\\frac{1}{10}$ if not. Given a positive test, the probability of disease is:",
    options: [{ key: "A", text: "$\\frac{119}{190}$" },{ key: "B", text: "$1$" },{ key: "C", text: "$\\frac{9}{19}$" },{ key: "D", text: "$\\frac{10}{19}$" },{ key: "E", text: "$\\frac{1}{10}$" }],
    answer: "D", solution: "By Bayes: $P(D\\mid+)=\\dfrac{P(+\\mid D)P(D)}{P(+)}=\\frac{10}{19}.$" },
  { id: "step-mk2-17", type: "mcq", testId: "step", topicId: "step-mech", difficulty: 3, marks: 20,
    question: "A $1\\,\\text{kg}$ mass hangs and pulls a $4\\,\\text{kg}$ mass on a smooth horizontal table via a pulley ($g=10$). The acceleration is:",
    options: [{ key: "A", text: "$10$" },{ key: "B", text: "$8$" },{ key: "C", text: "$3$" },{ key: "D", text: "$\\frac{5}{2}$" },{ key: "E", text: "$2$" }],
    answer: "E", solution: "$a=\\frac{m_1 g}{m_1+m_2}=\\frac{1\\cdot10}{5}=2$ m/s²." },
  { id: "step-mk2-18", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 1, marks: 20,
    question: "For $X\\sim B(20,\\frac{1}{4})$, the mean $E(X)$ is:",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$20$" },{ key: "C", text: "$5$" },{ key: "D", text: "$\\frac{15}{4}$" },{ key: "E", text: "$\\frac{1}{4}$" }],
    answer: "C", solution: "$E(X)=np=20\\cdot\\frac{1}{4}=5.$" },
  { id: "step-mk2-19", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 2, marks: 20,
    question: "The determinant of $\\begin{pmatrix}1&1&0\\\\0&2&1\\\\0&0&3\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$6$" },{ key: "C", text: "$7$" },{ key: "D", text: "$4$" },{ key: "E", text: "$2$" }],
    answer: "B", solution: "For an upper-triangular matrix the determinant is the product of the diagonal: $1\\cdot2\\cdot3=6.$" },
  { id: "step-mk2-20", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 3, marks: 20,
    question: "The sum of all the $n$-th roots of unity for $n=5$ is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$4$" },{ key: "C", text: "$-1$" },{ key: "D", text: "$0$" },{ key: "E", text: "$1$" }],
    answer: "D", solution: "The $n$-th roots of unity are roots of $z^{5}-1=0$; by Vieta their sum (coefficient of $z^{4}$ is $0$) is $0$." },
  { id: "step-mk2-21", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 3, marks: 20,
    question: "The larger eigenvalue of $\\begin{pmatrix}3&1\\\\0&2\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$5$" },{ key: "C", text: "$3$" },{ key: "D", text: "$6$" },{ key: "E", text: "$2$" }],
    answer: "C", solution: "Solve $\\det(M-\\lambda I)=0$: $\\lambda^2-(5)\\lambda+(6)=0$; larger root $=3.$" },
  { id: "step-mk2-22", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 3, marks: 20,
    question: "For roots $\\alpha,\\beta,\\gamma$ of $x^3 - 1x^2 - 4x + 4=0$, the value of $\\alpha^3+\\beta^3+\\gamma^3$ is:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$-2$" },{ key: "C", text: "$-12$" },{ key: "D", text: "$1$" },{ key: "E", text: "$13$" }],
    answer: "D", solution: "$\\sum\\alpha^3=e_1^3-3e_1e_2+3e_3=(1)^3-3(1)(-4)+3(-4)=1.$" },
  { id: "step-mk2-23", type: "mcq", testId: "step", topicId: "step-mech", difficulty: 2, marks: 20,
    question: "Mass $3\\,\\text{kg}$ at $8\\,\\text{m/s}$ collides and coalesces with a stationary $1\\,\\text{kg}$ mass. Their common speed is:",
    options: [{ key: "A", text: "$24$" },{ key: "B", text: "$6$" },{ key: "C", text: "$7$" },{ key: "D", text: "$4$" },{ key: "E", text: "$8$" }],
    answer: "B", solution: "Momentum: $v=\\frac{m_1u_1}{m_1+m_2}=6$ m/s." },
  { id: "step-mk2-24", type: "mcq", testId: "step", topicId: "step-pure3", difficulty: 3, marks: 20,
    question: "The arc length of $y=1x$ from $x=0$ to $x=5$ is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$1 + 5 \\sqrt{2}$" },{ key: "C", text: "$10 \\sqrt{2}$" },{ key: "D", text: "$5 \\sqrt{2}$" },{ key: "E", text: "$10$" }],
    answer: "D", solution: "$L=\\int_0^5\\sqrt{1+(1)^2}\\,dx=(5)\\sqrt{2}=5 \\sqrt{2}.$" },
  { id: "step-mk2-25", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 3, marks: 20,
    question: "The sum of all the $n$-th roots of unity for $n=7$ is:",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$0$" },{ key: "C", text: "$-1$" },{ key: "D", text: "$6$" },{ key: "E", text: "$1$" }],
    answer: "B", solution: "The $n$-th roots of unity are roots of $z^{7}-1=0$; by Vieta their sum (coefficient of $z^{6}$ is $0$) is $0$." },
];
