// TARA 模拟卷1 —— 批判性思维 22 + 问题解决 22（两模块，各 40 分钟）。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const TARA_MK1_CT: MCQQuestion[] = [
  { id: "tara-mk1-ct-01", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "The new bypass was built to reduce traffic in the town centre. Since it opened, congestion in the centre has indeed fallen. However, traffic on the residential roads leading to the bypass has increased sharply, and accidents there have risen. The bypass has simply moved the problem rather than solving it.\n\nWhich of the following best expresses the main conclusion of the argument?",
    options: [{ key: "A", text: "The bypass was built to reduce town-centre traffic." },{ key: "B", text: "Congestion in the town centre has fallen." },{ key: "C", text: "The bypass has moved the traffic problem rather than solving it." },{ key: "D", text: "Accidents on residential roads have risen." },{ key: "E", text: "Traffic on residential roads has increased." }],
    answer: "C", solution: "The final sentence is the conclusion; the earlier statements are evidence leading to it. B, D and E are supporting facts, and A is background." },
  { id: "tara-mk1-ct-02", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "Companies claim that longer opening hours improve customer service. But staff forced to work late become tired and make more errors, and customers report worse experiences in the final hours. Extending opening hours can therefore harm the very service it is meant to improve.\n\nWhich of the following is the main conclusion?",
    options: [{ key: "A", text: "Staff who work late become tired." },{ key: "B", text: "Extending opening hours can harm customer service." },{ key: "C", text: "Companies want to improve customer service." },{ key: "D", text: "Tired staff make more errors." },{ key: "E", text: "Customers report worse experiences late at night." }],
    answer: "B", solution: "The conclusion is signalled by 'therefore'; the rest are premises supporting it." },
  { id: "tara-mk1-ct-03", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "The council plans to cut street lighting at night to save money. A spokesperson argued that this is safe, since most burglaries happen during the day.\n\nWhich of the following is an assumption underlying the spokesperson's argument?",
    options: [{ key: "A", text: "Street lighting is expensive to maintain." },{ key: "B", text: "Reducing night lighting will not significantly increase crime or other harms at night." },{ key: "C", text: "Burglaries are the most common crime." },{ key: "D", text: "People prefer darker streets." },{ key: "E", text: "The council has a limited budget." }],
    answer: "B", solution: "For 'safe' to follow, the argument must assume darkness at night won't raise night-time crime or accidents; deny this and the safety claim collapses." },
  { id: "tara-mk1-ct-04", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "A commentator argues that since exam results have improved every year, schools must be teaching better than before.\n\nWhich of the following is an assumption on which this argument depends?",
    options: [{ key: "A", text: "Students work harder than before." },{ key: "B", text: "The improvement in results reflects better teaching rather than, say, easier exams." },{ key: "C", text: "Exams are taken every year." },{ key: "D", text: "Schools employ more teachers." },{ key: "E", text: "Results are published annually." }],
    answer: "B", solution: "The inference from 'results improved' to 'teaching improved' assumes the results measure teaching quality and are not explained by easier exams or other factors." },
  { id: "tara-mk1-ct-05", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "Every successful entrepreneur I have read about wakes up before 6 a.m. So if you want to be successful, the key is to start waking up before 6 a.m.\n\nWhich of the following best describes the flaw in this reasoning?",
    options: [{ key: "A", text: "It relies on an unrepresentative sample." },{ key: "B", text: "It treats a feature that may merely accompany success as though it causes success." },{ key: "C", text: "It appeals to the reader's emotions." },{ key: "D", text: "It contradicts itself." },{ key: "E", text: "It attacks the entrepreneurs personally." }],
    answer: "B", solution: "The argument assumes early rising causes success, when it may just correlate with it (or result from other traits)—mistaking correlation for cause." },
  { id: "tara-mk1-ct-06", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "My opponent argues that we should invest more in flood defences. But he owns a house near the river, so his argument should be dismissed.\n\nWhich of the following best describes the flaw in this argument?",
    options: [{ key: "A", text: "It generalises from too few cases." },{ key: "B", text: "It rejects a claim by attacking the person making it rather than its merits." },{ key: "C", text: "It presents only two options." },{ key: "D", text: "It confuses cause and effect." },{ key: "E", text: "It appeals to popularity." }],
    answer: "B", solution: "The argument dismisses the proposal because of who makes it (and their interest), not by addressing whether the proposal is sound—an ad hominem." },
  { id: "tara-mk1-ct-07", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "Either we allow the new factory to be built, or the town will suffer permanent economic decline. We cannot accept decline, so the factory must be built.\n\nWhich of the following best identifies the weakness in the argument?",
    options: [{ key: "A", text: "It assumes there are only two possible outcomes when others may exist." },{ key: "B", text: "It attacks the character of opponents." },{ key: "C", text: "It relies on a biased sample." },{ key: "D", text: "It uses circular reasoning." },{ key: "E", text: "It confuses correlation with causation." }],
    answer: "A", solution: "The argument offers a false dilemma: it presents 'factory or permanent decline' as the only options, ignoring other ways the town might avoid decline." },
  { id: "tara-mk1-ct-08", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "A study found that towns with more libraries have lower crime rates. The researchers concluded that building libraries reduces crime.\n\nWhich of the following, if true, would most weaken the researchers' conclusion?",
    options: [{ key: "A", text: "Some libraries are open on weekends." },{ key: "B", text: "Wealthier towns tend both to build more libraries and to have less crime for other reasons." },{ key: "C", text: "Libraries are popular with residents." },{ key: "D", text: "Crime rates vary from year to year." },{ key: "E", text: "Some towns have very large libraries." }],
    answer: "B", solution: "If wealth independently causes both more libraries and less crime, the library–crime link is explained by a third factor, undermining the causal conclusion." },
  { id: "tara-mk1-ct-09", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "The airline argues that its new booking system is better because complaints about booking have fallen by half since it was introduced.\n\nWhich of the following, if true, would most weaken this argument?",
    options: [{ key: "A", text: "The airline received an award for customer service." },{ key: "B", text: "Over the same period, the airline made it much harder for customers to submit complaints." },{ key: "C", text: "The new system was expensive to install." },{ key: "D", text: "Some passengers still prefer to book by phone." },{ key: "E", text: "The number of flights increased slightly." }],
    answer: "B", solution: "If complaints fell because they became harder to submit, the drop no longer shows the system is better—removing the support for the conclusion." },
  { id: "tara-mk1-ct-10", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "A school introduced a free breakfast programme and, over the following year, attendance improved. The head teacher claims the breakfast caused the improvement.\n\nWhich of the following, if true, would most strengthen the head teacher's claim?",
    options: [{ key: "A", text: "The breakfasts were popular with students." },{ key: "B", text: "Comparable schools without the programme saw no change in attendance over the same year." },{ key: "C", text: "The programme was funded by donations." },{ key: "D", text: "Attendance is recorded each morning." },{ key: "E", text: "Some students already ate breakfast at home." }],
    answer: "B", solution: "A comparison group that saw no change isolates the programme as the likely cause, strengthening the causal claim." },
  { id: "tara-mk1-ct-11", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "Principle: A person should not be blamed for an outcome they could not reasonably have foreseen or prevented.\n\nApplying this principle, in which case should the person NOT be blamed?",
    options: [{ key: "A", text: "A driver obeying all rules brakes immediately when a child suddenly darts into the road, but cannot avoid a collision." },{ key: "B", text: "A driver who was texting causes a crash." },{ key: "C", text: "A shopkeeper knowingly sells food past its safe date and customers fall ill." },{ key: "D", text: "A cyclist rides through a red light and hits a pedestrian." },{ key: "E", text: "A builder uses materials he knows to be unsafe and a wall collapses." }],
    answer: "A", solution: "Only A involves an outcome the person could neither foresee nor prevent; by the principle they should not be blamed. In the others the person could have foreseen or prevented the harm." },
  { id: "tara-mk1-ct-12", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "If the bridge were unsafe, it would have been closed. It has not been closed. So the bridge is not unsafe.\n\nWhich of the following arguments has the same logical structure as the argument above?",
    options: [{ key: "A", text: "If it rains, the match is cancelled. The match was not cancelled. So it did not rain." },{ key: "B", text: "If it rains, the match is cancelled. It rained. So the match was cancelled." },{ key: "C", text: "The match is cancelled only when it rains. It did not rain. So the match went ahead." },{ key: "D", text: "If it rains, the match is cancelled. The match was cancelled. So it rained." },{ key: "E", text: "It never rains during matches, so matches are never cancelled." }],
    answer: "A", solution: "The original is: if P then Q; not Q; therefore not P (valid, modus tollens). A matches exactly: if rain then cancelled; not cancelled; so no rain." },
  { id: "tara-mk1-ct-13", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "Supporters of the ban on advertising unhealthy food to children say it will reduce childhood obesity. Yet children see such adverts mainly through programmes streamed from abroad, which the ban cannot reach. The ban is therefore unlikely to achieve its aim.\n\nWhich of the following is the main conclusion?",
    options: [{ key: "A", text: "The ban aims to reduce childhood obesity." },{ key: "B", text: "Children mainly see the adverts through foreign streaming." },{ key: "C", text: "The ban is unlikely to achieve its aim." },{ key: "D", text: "Advertising influences children." },{ key: "E", text: "Childhood obesity is a problem." }],
    answer: "C", solution: "'Therefore' marks the conclusion; the point about foreign streaming is the reason supporting it." },
  { id: "tara-mk1-ct-14", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "The minister said that because the number of people in work has reached a record high, the economy must be healthy.\n\nWhich assumption does the minister's argument rely on?",
    options: [{ key: "A", text: "A record number in work reliably indicates a healthy economy, ignoring factors such as low pay or underemployment." },{ key: "B", text: "The population has grown." },{ key: "C", text: "Ministers understand economics." },{ key: "D", text: "Employment is measured accurately." },{ key: "E", text: "The economy was previously unhealthy." }],
    answer: "A", solution: "Inferring 'healthy economy' from 'record employment' assumes employment numbers capture economic health, overlooking pay, hours or underemployment." },
  { id: "tara-mk1-ct-15", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "Whenever the school football team wins, the local shop sells more pies the next day. Last Monday the shop sold a record number of pies. So the team must have won on Sunday.\n\nWhich of the following best describes the flaw in this reasoning?",
    options: [{ key: "A", text: "It assumes that because one thing follows another, the second must have been caused by the first." },{ key: "B", text: "It treats a possible cause of the pie sales as the only possible cause." },{ key: "C", text: "It attacks the shopkeeper." },{ key: "D", text: "It relies on an unrepresentative sample." },{ key: "E", text: "It presents a false dilemma." }],
    answer: "B", solution: "A win is only one possible reason for high pie sales; the argument wrongly treats it as the only explanation, ignoring other causes." },
  { id: "tara-mk1-ct-16", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "A newspaper claims its readers are the best informed, citing a survey in which its own readers rated themselves highly on current affairs.\n\nWhich of the following, if true, would most weaken the newspaper's claim?",
    options: [{ key: "A", text: "The newspaper has many readers." },{ key: "B", text: "When tested on current affairs, the newspaper's readers scored no higher than average." },{ key: "C", text: "The survey was conducted online." },{ key: "D", text: "Readers enjoy the newspaper." },{ key: "E", text: "Other newspapers also run surveys." }],
    answer: "B", solution: "Self-rating is unreliable; an objective test showing no advantage undermines the claim that the readers are best informed." },
  { id: "tara-mk1-ct-17", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "A politician argues that lowering the speed limit will save lives, because slower cars cause less severe injuries in a crash.\n\nWhich of the following, if true, would most strengthen this argument?",
    options: [{ key: "A", text: "Drivers dislike lower speed limits." },{ key: "B", text: "In areas where the limit was lowered, the number of serious injuries fell significantly." },{ key: "C", text: "Cars are safer than they used to be." },{ key: "D", text: "Speed limits are set by law." },{ key: "E", text: "Some drivers exceed the limit." }],
    answer: "B", solution: "Evidence that lowering the limit actually reduced serious injuries directly supports the claim that it saves lives." },
  { id: "tara-mk1-ct-18", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "All the members of the committee I have spoken to support the proposal. Therefore the whole committee supports it.\n\nWhich of the following best describes the weakness in this argument?",
    options: [{ key: "A", text: "It generalises to the whole committee from possibly only some of its members." },{ key: "B", text: "It confuses cause and effect." },{ key: "C", text: "It attacks the members personally." },{ key: "D", text: "It offers only two options." },{ key: "E", text: "It reasons in a circle." }],
    answer: "A", solution: "The speaker has only spoken to some members but concludes about all of them—an unwarranted generalisation from a partial sample." },
  { id: "tara-mk1-ct-19", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "The report recommends replacing the old boilers because doing so will cut heating bills. But the new boilers cost far more to install than the bills they would save over their lifetime.\n\nWhich of the following is the main conclusion implicitly supported by the second sentence?",
    options: [{ key: "A", text: "The old boilers should be replaced." },{ key: "B", text: "Replacing the boilers is not, overall, worth the cost." },{ key: "C", text: "Heating bills are high." },{ key: "D", text: "New boilers are efficient." },{ key: "E", text: "The report is long." }],
    answer: "B", solution: "The second sentence gives a reason cutting against the recommendation, supporting the implicit conclusion that replacement is not worthwhile overall." },
  { id: "tara-mk1-ct-20", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "Principle: People should be free to take risks that affect only themselves.\n\nWhich of the following judgements best conforms to this principle?",
    options: [{ key: "A", text: "An adult who fully understands the risks should be allowed to climb a dangerous mountain alone." },{ key: "B", text: "A factory should be allowed to release toxic fumes over a neighbourhood." },{ key: "C", text: "A driver should be allowed to drive drunk on public roads." },{ key: "D", text: "A person should be allowed to set fires that spread to others' homes." },{ key: "E", text: "A company should be allowed to sell unsafe toys." }],
    answer: "A", solution: "Only A involves a risk affecting only the person taking it; the others impose risks on other people, which the principle does not license." },
  { id: "tara-mk1-ct-21", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "Since the introduction of the new software, the team has completed more tasks each week. The manager concludes that the software has made the team more productive.\n\nWhich of the following, if true, would most weaken the manager's conclusion?",
    options: [{ key: "A", text: "The team likes the new software." },{ key: "B", text: "At the same time as the software was introduced, two extra staff joined the team." },{ key: "C", text: "The software was recommended by experts." },{ key: "D", text: "Tasks are logged automatically." },{ key: "E", text: "The team meets every Monday." }],
    answer: "B", solution: "If extra staff arrived simultaneously, the increased output may be due to them rather than the software, weakening the causal claim." },
  { id: "tara-mk1-ct-22", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "A charity states that donations rose after it launched an advertising campaign, proving that the campaign was effective.\n\nWhich of the following is an assumption the charity's reasoning depends on?",
    options: [{ key: "A", text: "The rise in donations was due to the campaign rather than to some other cause." },{ key: "B", text: "The campaign was expensive." },{ key: "C", text: "Donors are generous." },{ key: "D", text: "The charity is well known." },{ key: "E", text: "Advertising is common." }],
    answer: "A", solution: "Concluding the campaign was effective assumes it, rather than an unrelated factor (a news event, the season), caused the rise in donations." },
];

export const TARA_MK1_PS: MCQQuestion[] = [
  { id: "tara-mk1-ps-01", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "A cyclist rides to a town at $30$ km/h and returns along the same road at $60$ km/h. What is the average speed for the whole journey?",
    options: [{ key: "A", text: "$40$ km/h" },{ key: "B", text: "$60$ km/h" },{ key: "C", text: "$30$ km/h" },{ key: "D", text: "$20$ km/h" },{ key: "E", text: "$45$ km/h" }],
    answer: "A", solution: "Average speed $=\\dfrac{2v_1v_2}{v_1+v_2}=\\dfrac{2\\cdot30\\cdot60}{90}=40$ km/h (not the arithmetic mean)." },
  { id: "tara-mk1-ps-02", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "A cyclist rides to a town at $40$ km/h and returns along the same road at $60$ km/h. What is the average speed for the whole journey?",
    options: [{ key: "A", text: "$60$ km/h" },{ key: "B", text: "$50$ km/h" },{ key: "C", text: "$40$ km/h" },{ key: "D", text: "$48$ km/h" },{ key: "E", text: "$24$ km/h" }],
    answer: "D", solution: "Average speed $=\\dfrac{2v_1v_2}{v_1+v_2}=\\dfrac{2\\cdot40\\cdot60}{100}=48$ km/h (not the arithmetic mean)." },
  { id: "tara-mk1-ps-03", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "A cyclist rides to a town at $20$ km/h and returns along the same road at $30$ km/h. What is the average speed for the whole journey?",
    options: [{ key: "A", text: "$12$ km/h" },{ key: "B", text: "$20$ km/h" },{ key: "C", text: "$24$ km/h" },{ key: "D", text: "$25$ km/h" },{ key: "E", text: "$30$ km/h" }],
    answer: "C", solution: "Average speed $=\\dfrac{2v_1v_2}{v_1+v_2}=\\dfrac{2\\cdot20\\cdot30}{50}=24$ km/h (not the arithmetic mean)." },
  { id: "tara-mk1-ps-04", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "A cyclist rides to a town at $50$ km/h and returns along the same road at $75$ km/h. What is the average speed for the whole journey?",
    options: [{ key: "A", text: "$60$ km/h" },{ key: "B", text: "$\\frac{125}{2}$ km/h" },{ key: "C", text: "$75$ km/h" },{ key: "D", text: "$30$ km/h" },{ key: "E", text: "$50$ km/h" }],
    answer: "A", solution: "Average speed $=\\dfrac{2v_1v_2}{v_1+v_2}=\\dfrac{2\\cdot50\\cdot75}{125}=60$ km/h (not the arithmetic mean)." },
  { id: "tara-mk1-ps-05", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "A cyclist rides to a town at $10$ km/h and returns along the same road at $15$ km/h. What is the average speed for the whole journey?",
    options: [{ key: "A", text: "$6$ km/h" },{ key: "B", text: "$10$ km/h" },{ key: "C", text: "$15$ km/h" },{ key: "D", text: "$12$ km/h" },{ key: "E", text: "$\\frac{25}{2}$ km/h" }],
    answer: "D", solution: "Average speed $=\\dfrac{2v_1v_2}{v_1+v_2}=\\dfrac{2\\cdot10\\cdot15}{25}=12$ km/h (not the arithmetic mean)." },
  { id: "tara-mk1-ps-06", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "A coat priced at £$200$ is reduced by $10\\%$, and the reduced price is then cut by a further $20\\%$ in a sale. What is the final price?",
    options: [{ key: "A", text: "$180$" },{ key: "B", text: "$140$" },{ key: "C", text: "$160$" },{ key: "D", text: "$144$" },{ key: "E", text: "$149$" }],
    answer: "D", solution: "Successive discounts multiply: £$200\\times\\frac{9}{10}\\times\\frac{4}{5}=£144$ (a $10\\%$ then $20\\%$ cut is not a $30\\%$ cut)." },
  { id: "tara-mk1-ps-07", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "A coat priced at £$50$ is reduced by $25\\%$, and the reduced price is then cut by a further $10\\%$ in a sale. What is the final price?",
    options: [{ key: "A", text: "$\\frac{155}{4}$" },{ key: "B", text: "$\\frac{65}{2}$" },{ key: "C", text: "$45$" },{ key: "D", text: "$\\frac{135}{4}$" },{ key: "E", text: "$\\frac{75}{2}$" }],
    answer: "D", solution: "Successive discounts multiply: £$50\\times\\frac{3}{4}\\times\\frac{9}{10}=£\\frac{135}{4}$ (a $25\\%$ then $10\\%$ cut is not a $35\\%$ cut)." },
  { id: "tara-mk1-ps-08", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "A coat priced at £$120$ is reduced by $50\\%$, and the reduced price is then cut by a further $25\\%$ in a sale. What is the final price?",
    options: [{ key: "A", text: "$50$" },{ key: "B", text: "$45$" },{ key: "C", text: "$30$" },{ key: "D", text: "$90$" },{ key: "E", text: "$60$" }],
    answer: "B", solution: "Successive discounts multiply: £$120\\times\\frac{1}{2}\\times\\frac{3}{4}=£45$ (a $50\\%$ then $25\\%$ cut is not a $75\\%$ cut)." },
  { id: "tara-mk1-ps-09", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "A coat priced at £$80$ is reduced by $20\\%$, and the reduced price is then cut by a further $15\\%$ in a sale. What is the final price?",
    options: [{ key: "A", text: "$68$" },{ key: "B", text: "$52$" },{ key: "C", text: "$\\frac{297}{5}$" },{ key: "D", text: "$64$" },{ key: "E", text: "$\\frac{272}{5}$" }],
    answer: "E", solution: "Successive discounts multiply: £$80\\times\\frac{4}{5}\\times\\frac{17}{20}=£\\frac{272}{5}$ (a $20\\%$ then $15\\%$ cut is not a $35\\%$ cut)." },
  { id: "tara-mk1-ps-10", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "A coat priced at £$300$ is reduced by $30\\%$, and the reduced price is then cut by a further $10\\%$ in a sale. What is the final price?",
    options: [{ key: "A", text: "$210$" },{ key: "B", text: "$180$" },{ key: "C", text: "$194$" },{ key: "D", text: "$189$" },{ key: "E", text: "$270$" }],
    answer: "D", solution: "Successive discounts multiply: £$300\\times\\frac{7}{10}\\times\\frac{9}{10}=£189$ (a $30\\%$ then $10\\%$ cut is not a $40\\%$ cut)." },
  { id: "tara-mk1-ps-11", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "One tap fills a tank in $4$ hours and another fills it in $6$ hours. How long do they take to fill it together?",
    options: [{ key: "A", text: "$5$ 小时" },{ key: "B", text: "$\\frac{12}{5}$ 小时" },{ key: "C", text: "$12$ 小时" },{ key: "D", text: "$\\frac{17}{5}$ 小时" },{ key: "E", text: "$4$ 小时" }],
    answer: "B", solution: "Combined rate $=\\tfrac1{4}+\\tfrac1{6}$ tanks/hour; time $=\\dfrac1{1/4+1/6}=\\frac{12}{5}$ hours." },
  { id: "tara-mk1-ps-12", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "One tap fills a tank in $2$ hours and another fills it in $3$ hours. How long do they take to fill it together?",
    options: [{ key: "A", text: "$2$ 小时" },{ key: "B", text: "$\\frac{6}{5}$ 小时" },{ key: "C", text: "$3$ 小时" },{ key: "D", text: "$\\frac{11}{5}$ 小时" },{ key: "E", text: "$\\frac{5}{2}$ 小时" }],
    answer: "B", solution: "Combined rate $=\\tfrac1{2}+\\tfrac1{3}$ tanks/hour; time $=\\dfrac1{1/2+1/3}=\\frac{6}{5}$ hours." },
  { id: "tara-mk1-ps-13", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "One tap fills a tank in $6$ hours and another fills it in $12$ hours. How long do they take to fill it together?",
    options: [{ key: "A", text: "$4$ 小时" },{ key: "B", text: "$9$ 小时" },{ key: "C", text: "$36$ 小时" },{ key: "D", text: "$6$ 小时" },{ key: "E", text: "$5$ 小时" }],
    answer: "A", solution: "Combined rate $=\\tfrac1{6}+\\tfrac1{12}$ tanks/hour; time $=\\dfrac1{1/6+1/12}=4$ hours." },
  { id: "tara-mk1-ps-14", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "At a meeting of $6$ people, everyone shakes hands exactly once with everyone else. How many handshakes take place?",
    options: [{ key: "A", text: "$15$" },{ key: "B", text: "$6$" },{ key: "C", text: "$36$" },{ key: "D", text: "$30$" },{ key: "E", text: "$21$" }],
    answer: "A", solution: "Number of handshakes $=\\binom{6}2=\\dfrac{6\\cdot5}2=15.$" },
  { id: "tara-mk1-ps-15", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "At a meeting of $8$ people, everyone shakes hands exactly once with everyone else. How many handshakes take place?",
    options: [{ key: "A", text: "$36$" },{ key: "B", text: "$28$" },{ key: "C", text: "$8$" },{ key: "D", text: "$64$" },{ key: "E", text: "$56$" }],
    answer: "B", solution: "Number of handshakes $=\\binom{8}2=\\dfrac{8\\cdot7}2=28.$" },
  { id: "tara-mk1-ps-16", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "At a meeting of $10$ people, everyone shakes hands exactly once with everyone else. How many handshakes take place?",
    options: [{ key: "A", text: "$10$" },{ key: "B", text: "$90$" },{ key: "C", text: "$100$" },{ key: "D", text: "$45$" },{ key: "E", text: "$55$" }],
    answer: "D", solution: "Number of handshakes $=\\binom{10}2=\\dfrac{10\\cdot9}2=45.$" },
  { id: "tara-mk1-ps-17", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "At a meeting of $12$ people, everyone shakes hands exactly once with everyone else. How many handshakes take place?",
    options: [{ key: "A", text: "$132$" },{ key: "B", text: "$144$" },{ key: "C", text: "$66$" },{ key: "D", text: "$12$" },{ key: "E", text: "$78$" }],
    answer: "C", solution: "Number of handshakes $=\\binom{12}2=\\dfrac{12\\cdot11}2=66.$" },
  { id: "tara-mk1-ps-18", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "At a meeting of $5$ people, everyone shakes hands exactly once with everyone else. How many handshakes take place?",
    options: [{ key: "A", text: "$25$" },{ key: "B", text: "$20$" },{ key: "C", text: "$10$" },{ key: "D", text: "$5$" },{ key: "E", text: "$15$" }],
    answer: "C", solution: "Number of handshakes $=\\binom{5}2=\\dfrac{5\\cdot4}2=10.$" },
  { id: "tara-mk1-ps-19", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 3, marks: 1,
    question: "A large cube of side $3$ units is painted on all outer faces and then cut into unit cubes. How many small cubes have exactly two painted faces?",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$36$" },{ key: "C", text: "$6$" },{ key: "D", text: "$8$" },{ key: "E", text: "$12$" }],
    answer: "E", solution: "Two-face cubes lie along edges (excluding corners): $12(n-2)=12(3-2)=12.$" },
  { id: "tara-mk1-ps-20", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 3, marks: 1,
    question: "A large cube of side $5$ units is painted on all outer faces and then cut into unit cubes. How many small cubes have exactly two painted faces?",
    options: [{ key: "A", text: "$60$" },{ key: "B", text: "$27$" },{ key: "C", text: "$54$" },{ key: "D", text: "$36$" },{ key: "E", text: "$8$" }],
    answer: "D", solution: "Two-face cubes lie along edges (excluding corners): $12(n-2)=12(5-2)=36.$" },
  { id: "tara-mk1-ps-21", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 3, marks: 1,
    question: "A large cube of side $6$ units is painted on all outer faces and then cut into unit cubes. How many small cubes have exactly two painted faces?",
    options: [{ key: "A", text: "$96$" },{ key: "B", text: "$72$" },{ key: "C", text: "$48$" },{ key: "D", text: "$8$" },{ key: "E", text: "$64$" }],
    answer: "C", solution: "Two-face cubes lie along edges (excluding corners): $12(n-2)=12(6-2)=48.$" },
  { id: "tara-mk1-ps-22", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 3, marks: 1,
    question: "A cube of side $3$ is painted and cut into unit cubes. How many have exactly one painted face?",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$12$" },{ key: "C", text: "$54$" },{ key: "D", text: "$1$" },{ key: "E", text: "$8$" }],
    answer: "A", solution: "One-face cubes lie on faces (excluding edges): $6(n-2)^2=6(3-2)^2=6.$" },
];
