// TARA 模拟卷3 —— 批判性思维 22 + 问题解决 22（两模块，各 40 分钟）。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const TARA_MK3_CT: MCQQuestion[] = [
  { id: "tara-mk3-ct-01", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "If the alarm had been set, it would have rung. It did ring. So the alarm had been set.\n\nWhich of the following has the same (flawed) structure?",
    options: [{ key: "A", text: "If it snowed, school would close. School closed. So it snowed." },{ key: "B", text: "If it snowed, school would close. It snowed. So school closed." },{ key: "C", text: "If it snowed, school would close. School did not close. So it did not snow." },{ key: "D", text: "School closes only when it snows. It did not snow. So school did not close." },{ key: "E", text: "It snowed, so school will close." }],
    answer: "A", solution: "The original affirms the consequent (if P then Q; Q; so P)—invalid. A has the same invalid form." },
  { id: "tara-mk3-ct-02", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "Since introducing background music, the café reports that customers stay longer. The owner concludes the music makes customers want to stay.\n\nWhich assumption does this conclusion depend on?",
    options: [{ key: "A", text: "The longer stays are due to the music rather than to some other change made at the same time." },{ key: "B", text: "Customers like music." },{ key: "C", text: "The café is busy." },{ key: "D", text: "Music is cheap to play." },{ key: "E", text: "Staff enjoy the music." }],
    answer: "A", solution: "Concluding the music caused longer stays assumes nothing else (new seating, menu, weather) explains the change." },
  { id: "tara-mk3-ct-03", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "A report notes that neighbourhoods with more CCTV cameras record more reported crime, and concludes that CCTV increases crime.\n\nWhich of the following best describes the flaw?",
    options: [{ key: "A", text: "More cameras may lead to more crimes being detected and reported, not more crimes occurring." },{ key: "B", text: "CCTV is expensive." },{ key: "C", text: "The report attacks residents." },{ key: "D", text: "It presents only two options." },{ key: "E", text: "The sample is too small." }],
    answer: "A", solution: "Higher reported crime may reflect better detection by cameras, not a real increase—so the causal conclusion is unwarranted." },
  { id: "tara-mk3-ct-04", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "A shopkeeper argues that since his most expensive coffee is his best seller, customers must prefer more expensive coffee.\n\nWhich of the following, if true, would most weaken this argument?",
    options: [{ key: "A", text: "The expensive coffee is the only large-sized option, which is why most people buy it." },{ key: "B", text: "The shop sells several coffees." },{ key: "C", text: "Coffee is popular." },{ key: "D", text: "The shop is busy in the morning." },{ key: "E", text: "Some customers buy tea." }],
    answer: "A", solution: "If it sells because it is the only large size, its popularity is not evidence that customers prefer higher prices." },
  { id: "tara-mk3-ct-05", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "The minister claims the new curriculum is a success because national test scores rose the year it was introduced.\n\nWhich of the following, if true, would most weaken the minister's claim?",
    options: [{ key: "A", text: "The tests taken that year were found to be easier than in previous years." },{ key: "B", text: "The curriculum was widely publicised." },{ key: "C", text: "Teachers were trained in the new curriculum." },{ key: "D", text: "Scores are published nationally." },{ key: "E", text: "The minister supports education." }],
    answer: "A", solution: "If the tests were easier, higher scores need not reflect a better curriculum, undermining the success claim." },
  { id: "tara-mk3-ct-06", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "A commentator argues that reading fiction makes people more empathetic, citing that keen fiction readers score highly on empathy tests.\n\nWhich of the following is an assumption of this argument?",
    options: [{ key: "A", text: "Reading fiction increases empathy, rather than empathetic people being drawn to fiction." },{ key: "B", text: "Fiction is widely read." },{ key: "C", text: "Empathy tests are long." },{ key: "D", text: "Novels are cheap." },{ key: "E", text: "Readers enjoy fiction." }],
    answer: "A", solution: "The causal claim assumes fiction causes empathy, not that empathetic people simply prefer fiction." },
  { id: "tara-mk3-ct-07", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "If a bridge is well maintained, it will not collapse. The old bridge collapsed. Therefore it was not well maintained.\n\nWhich of the following has the same (valid) structure?",
    options: [{ key: "A", text: "If a plant is healthy, it will not wilt. This plant wilted. So it was not healthy." },{ key: "B", text: "If a plant is healthy, it will not wilt. This plant is healthy. So it will not wilt." },{ key: "C", text: "If a plant is healthy, it will not wilt. This plant did not wilt. So it is healthy." },{ key: "D", text: "A plant wilts only if neglected. It was not neglected. So it did not wilt." },{ key: "E", text: "This plant wilted, so all plants wilt." }],
    answer: "A", solution: "Original: if P then not Q; Q; so not P (valid modus tollens). A matches exactly." },
  { id: "tara-mk3-ct-08", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "A newspaper claims the economy is booming because the stock market has reached a record high.\n\nWhich of the following, if true, would most weaken this claim?",
    options: [{ key: "A", text: "The stock market can rise even when wages fall and unemployment grows." },{ key: "B", text: "Many people own shares." },{ key: "C", text: "The market is watched closely." },{ key: "D", text: "Records are set occasionally." },{ key: "E", text: "The newspaper is widely read." }],
    answer: "A", solution: "If the market can rise while ordinary economic conditions worsen, a record high does not show the economy is booming." },
  { id: "tara-mk3-ct-09", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "A school claims its pupils are exceptionally talented, pointing out that its entrance exam is extremely selective.\n\nWhich of the following best describes the weakness in using exam results later to prove the school teaches well?",
    options: [{ key: "A", text: "Strong later results may reflect the pupils' ability on entry rather than the school's teaching." },{ key: "B", text: "The exam is difficult." },{ key: "C", text: "The school is popular." },{ key: "D", text: "Pupils wear uniforms." },{ key: "E", text: "Teachers are experienced." }],
    answer: "A", solution: "If only able pupils are admitted, their later success may be due to their ability, not the teaching—so results don't prove good teaching." },
  { id: "tara-mk3-ct-10", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "A manager says overtime must be increasing productivity, because the month with the most overtime also had the highest output.\n\nWhich of the following best describes the flaw?",
    options: [{ key: "A", text: "A single month's coincidence of overtime and output does not establish that one caused the other." },{ key: "B", text: "Overtime is unpopular." },{ key: "C", text: "The argument attacks the workers." },{ key: "D", text: "It offers only two options." },{ key: "E", text: "It reasons in a circle." }],
    answer: "A", solution: "One month in which both were high does not show overtime caused the output; it may be coincidence or a shared cause." },
  { id: "tara-mk3-ct-11", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "A charity argues that people are becoming more generous, because the total amount donated rose last year.\n\nWhich of the following, if true, would most weaken this argument?",
    options: [{ key: "A", text: "The population and average incomes both grew substantially last year." },{ key: "B", text: "The charity is well known." },{ key: "C", text: "Donations can be made online." },{ key: "D", text: "Some people donate anonymously." },{ key: "E", text: "The charity ran a campaign." }],
    answer: "A", solution: "If there were more, richer people, a higher total need not mean each person is more generous—weakening the claim." },
  { id: "tara-mk3-ct-12", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "Principle: One should not be praised for an achievement that was entirely due to luck.\n\nWhich judgement best conforms to this principle?",
    options: [{ key: "A", text: "A lottery winner should not be praised for their 'financial success'." },{ key: "B", text: "A student who studied hard and passed should not be praised." },{ key: "C", text: "An athlete who trained for years should not be praised for winning." },{ key: "D", text: "A scientist who worked carefully should not be credited with a discovery." },{ key: "E", text: "A writer who spent years on a novel deserves no praise." }],
    answer: "A", solution: "Only A is an outcome purely due to luck; the principle then says praise is inappropriate. The others involved effort." },
  { id: "tara-mk3-ct-13", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "A blogger insists that a claim must be false because it is believed only by a small minority.\n\nWhich of the following best describes the flaw?",
    options: [{ key: "A", text: "It treats the number of believers as a test of truth." },{ key: "B", text: "It confuses cause and effect." },{ key: "C", text: "It attacks the believers personally." },{ key: "D", text: "It offers a false dilemma." },{ key: "E", text: "It generalises from one case." }],
    answer: "A", solution: "How many people hold a belief is not evidence of whether it is true—an appeal to (un)popularity." },
  { id: "tara-mk3-ct-14", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "Supporters argue that lowering the voting age will engage young people in politics, because countries that lowered it saw higher youth turnout at the next election.\n\nWhich of the following, if true, would most weaken this argument?",
    options: [{ key: "A", text: "Those countries also ran large, one-off campaigns to register young voters that year." },{ key: "B", text: "Young people use social media." },{ key: "C", text: "Elections are held regularly." },{ key: "D", text: "The voting age varies by country." },{ key: "E", text: "Some young people are political." }],
    answer: "A", solution: "If special campaigns drove the turnout, the rise cannot be attributed to lowering the voting age itself." },
  { id: "tara-mk3-ct-15", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "A firm concludes that its adverts are effective because sales rose during the advertising campaign.\n\nWhich assumption does this conclusion rely on?",
    options: [{ key: "A", text: "The rise in sales was caused by the adverts rather than by other factors such as the season." },{ key: "B", text: "The adverts were seen by many people." },{ key: "C", text: "The firm is large." },{ key: "D", text: "Advertising is common." },{ key: "E", text: "Sales are recorded." }],
    answer: "A", solution: "Concluding the adverts were effective assumes they, not seasonal demand or other causes, produced the rise in sales." },
  { id: "tara-mk3-ct-16", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "The council argues that the new cycle lane is unnecessary because a survey found most road users do not cycle.\n\nWhich of the following best describes the weakness in this reasoning?",
    options: [{ key: "A", text: "Few may cycle precisely because there is no safe lane, so current numbers understate potential demand." },{ key: "B", text: "Surveys are expensive." },{ key: "C", text: "The council dislikes cyclists." },{ key: "D", text: "It offers only two options." },{ key: "E", text: "Roads are busy." }],
    answer: "A", solution: "Measuring cycling under current unsafe conditions may understate how many would cycle if a lane existed—so low numbers don't settle the matter." },
  { id: "tara-mk3-ct-17", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "A columnist argues that because two events happened in the same week, one must have caused the other.\n\nWhich of the following best describes the flaw?",
    options: [{ key: "A", text: "Events occurring close in time need not be causally related." },{ key: "B", text: "The columnist attacks a person." },{ key: "C", text: "It offers a false dilemma." },{ key: "D", text: "It appeals to popularity." },{ key: "E", text: "It generalises from a small sample." }],
    answer: "A", solution: "Temporal proximity alone does not establish causation; the events may be unrelated or share a common cause." },
  { id: "tara-mk3-ct-18", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "A restaurant claims its food is the best in town because it has the longest queue.\n\nWhich of the following, if true, would most weaken this claim?",
    options: [{ key: "A", text: "The queue is long only because the restaurant is very small and serves slowly." },{ key: "B", text: "The food is expensive." },{ key: "C", text: "The restaurant is popular with tourists." },{ key: "D", text: "It opens in the evening." },{ key: "E", text: "The chef is experienced." }],
    answer: "A", solution: "If the queue reflects slow service in a tiny venue rather than quality, its length is not evidence that the food is best." },
  { id: "tara-mk3-ct-19", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "A study finds that students who use laptops in lectures get lower grades, and concludes that laptops harm learning.\n\nWhich of the following, if true, would most weaken the conclusion?",
    options: [{ key: "A", text: "Students who were already struggling were the most likely to use laptops to look things up." },{ key: "B", text: "Laptops are common." },{ key: "C", text: "Lectures are recorded." },{ key: "D", text: "Some students prefer notebooks." },{ key: "E", text: "Laptops are expensive." }],
    answer: "A", solution: "If weaker students self-select into laptop use, the lower grades may reflect prior struggle, not harm caused by laptops." },
  { id: "tara-mk3-ct-20", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "A politician argues: 'My critics say the policy has failed, but they have always opposed me, so their criticism is worthless.'\n\nWhich of the following best describes the flaw?",
    options: [{ key: "A", text: "It dismisses the criticism by pointing to the critics' motives instead of addressing whether the policy failed." },{ key: "B", text: "It confuses cause and effect." },{ key: "C", text: "It presents a false dilemma." },{ key: "D", text: "It generalises from a small sample." },{ key: "E", text: "It appeals to popularity." }],
    answer: "A", solution: "Longstanding opposition does not make a criticism false; the argument attacks the critics rather than the point—an ad hominem." },
  { id: "tara-mk3-ct-21", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "A firm notes that its highest-paid employees are also its most productive, and concludes that paying people more makes them more productive.\n\nWhich of the following, if true, would most weaken this conclusion?",
    options: [{ key: "A", text: "The firm's policy is to pay its already-most-productive employees the most." },{ key: "B", text: "The firm is profitable." },{ key: "C", text: "Employees value fair pay." },{ key: "D", text: "Productivity is measured monthly." },{ key: "E", text: "Some employees work part-time." }],
    answer: "A", solution: "If high pay follows from being productive, the causation runs the other way, undermining 'pay makes people productive'." },
  { id: "tara-mk3-ct-22", type: "mcq", testId: "tara", topicId: "tara-critical", difficulty: 2, marks: 1,
    question: "Because the medicine relieved my headache within an hour, it must have been the medicine that cured it.\n\nWhich of the following best describes the weakness in this reasoning?",
    options: [{ key: "A", text: "The headache might have faded on its own in that time." },{ key: "B", text: "The medicine was expensive." },{ key: "C", text: "It attacks the doctor." },{ key: "D", text: "It offers only two options." },{ key: "E", text: "It appeals to popularity." }],
    answer: "A", solution: "Many headaches subside naturally; recovery after taking the medicine doesn't establish that the medicine caused it." },
];

export const TARA_MK3_PS: MCQQuestion[] = [
  { id: "tara-mk3-ps-01", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "One bus leaves every $9$ minutes and another every $12$ minutes; both leave together now. After how many minutes will they next leave together?",
    options: [{ key: "A", text: "$45$ 分钟" },{ key: "B", text: "$36$ 分钟" },{ key: "C", text: "$108$ 分钟" },{ key: "D", text: "$21$ 分钟" },{ key: "E", text: "$3$ 分钟" }],
    answer: "B", solution: "They coincide at the lowest common multiple: $\\text{lcm}(9,12)=36$ minutes." },
  { id: "tara-mk3-ps-02", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "One bus leaves every $20$ minutes and another every $30$ minutes; both leave together now. After how many minutes will they next leave together?",
    options: [{ key: "A", text: "$60$ 分钟" },{ key: "B", text: "$50$ 分钟" },{ key: "C", text: "$600$ 分钟" },{ key: "D", text: "$80$ 分钟" },{ key: "E", text: "$10$ 分钟" }],
    answer: "A", solution: "They coincide at the lowest common multiple: $\\text{lcm}(20,30)=60$ minutes." },
  { id: "tara-mk3-ps-03", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "A group of $10$ students averages $60$ marks and another group of $20$ students averages $90$. What is the overall average?",
    options: [{ key: "A", text: "$90$" },{ key: "B", text: "$80$" },{ key: "C", text: "$75$" },{ key: "D", text: "$82$" },{ key: "E", text: "$1200$" }],
    answer: "B", solution: "Overall $=\\dfrac{10\\cdot60+20\\cdot90}{30}=80$ (weighted, not simple, mean)." },
  { id: "tara-mk3-ps-04", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "A group of $5$ students averages $70$ marks and another group of $15$ students averages $50$. What is the overall average?",
    options: [{ key: "A", text: "$60$" },{ key: "B", text: "$70$" },{ key: "C", text: "$57$" },{ key: "D", text: "$55$" },{ key: "E", text: "$550$" }],
    answer: "D", solution: "Overall $=\\dfrac{5\\cdot70+15\\cdot50}{20}=55$ (weighted, not simple, mean)." },
  { id: "tara-mk3-ps-05", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "A group of $8$ students averages $80$ marks and another group of $12$ students averages $55$. What is the overall average?",
    options: [{ key: "A", text: "$\\frac{135}{2}$" },{ key: "B", text: "$650$" },{ key: "C", text: "$80$" },{ key: "D", text: "$67$" },{ key: "E", text: "$65$" }],
    answer: "E", solution: "Overall $=\\dfrac{8\\cdot80+12\\cdot55}{20}=65$ (weighted, not simple, mean)." },
  { id: "tara-mk3-ps-06", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "A group of $20$ students averages $40$ marks and another group of $30$ students averages $65$. What is the overall average?",
    options: [{ key: "A", text: "$57$" },{ key: "B", text: "$55$" },{ key: "C", text: "$65$" },{ key: "D", text: "$1375$" },{ key: "E", text: "$\\frac{105}{2}$" }],
    answer: "B", solution: "Overall $=\\dfrac{20\\cdot40+30\\cdot65}{50}=55$ (weighted, not simple, mean)." },
  { id: "tara-mk3-ps-07", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "A right-angled triangle has the two shorter sides $3$ and $4$. What is the length of the hypotenuse?",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$6$" },{ key: "C", text: "$4$" },{ key: "D", text: "$7$" },{ key: "E", text: "$2$" }],
    answer: "A", solution: "Hypotenuse $=\\sqrt{3^2+4^2}=\\sqrt{25}=5.$" },
  { id: "tara-mk3-ps-08", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "A right-angled triangle has the two shorter sides $6$ and $8$. What is the length of the hypotenuse?",
    options: [{ key: "A", text: "$14$" },{ key: "B", text: "$10$" },{ key: "C", text: "$5$" },{ key: "D", text: "$9$" },{ key: "E", text: "$11$" }],
    answer: "B", solution: "Hypotenuse $=\\sqrt{6^2+8^2}=\\sqrt{100}=10.$" },
  { id: "tara-mk3-ps-09", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "A right-angled triangle has the two shorter sides $5$ and $12$. What is the length of the hypotenuse?",
    options: [{ key: "A", text: "$14$" },{ key: "B", text: "$17$" },{ key: "C", text: "$12$" },{ key: "D", text: "$10$" },{ key: "E", text: "$13$" }],
    answer: "E", solution: "Hypotenuse $=\\sqrt{5^2+12^2}=\\sqrt{169}=13.$" },
  { id: "tara-mk3-ps-10", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "A right-angled triangle has the two shorter sides $8$ and $15$. What is the length of the hypotenuse?",
    options: [{ key: "A", text: "$18$" },{ key: "B", text: "$16$" },{ key: "C", text: "$12$" },{ key: "D", text: "$17$" },{ key: "E", text: "$23$" }],
    answer: "D", solution: "Hypotenuse $=\\sqrt{8^2+15^2}=\\sqrt{289}=17.$" },
  { id: "tara-mk3-ps-11", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "A right-angled triangle has the two shorter sides $9$ and $12$. What is the length of the hypotenuse?",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$21$" },{ key: "C", text: "$16$" },{ key: "D", text: "$15$" },{ key: "E", text: "$14$" }],
    answer: "D", solution: "Hypotenuse $=\\sqrt{9^2+12^2}=\\sqrt{225}=15.$" },
  { id: "tara-mk3-ps-12", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "A triangle has base $10$ and perpendicular height $6$. What is its area?",
    options: [{ key: "A", text: "$60$" },{ key: "B", text: "$16$" },{ key: "C", text: "$20$" },{ key: "D", text: "$32$" },{ key: "E", text: "$30$" }],
    answer: "E", solution: "Area $=\\tfrac12\\cdot10\\cdot6=30.$" },
  { id: "tara-mk3-ps-13", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "A triangle has base $8$ and perpendicular height $5$. What is its area?",
    options: [{ key: "A", text: "$\\frac{40}{3}$" },{ key: "B", text: "$22$" },{ key: "C", text: "$40$" },{ key: "D", text: "$20$" },{ key: "E", text: "$13$" }],
    answer: "D", solution: "Area $=\\tfrac12\\cdot8\\cdot5=20.$" },
  { id: "tara-mk3-ps-14", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "A triangle has base $12$ and perpendicular height $7$. What is its area?",
    options: [{ key: "A", text: "$19$" },{ key: "B", text: "$42$" },{ key: "C", text: "$44$" },{ key: "D", text: "$28$" },{ key: "E", text: "$84$" }],
    answer: "B", solution: "Area $=\\tfrac12\\cdot12\\cdot7=42.$" },
  { id: "tara-mk3-ps-15", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "A triangle has base $15$ and perpendicular height $4$. What is its area?",
    options: [{ key: "A", text: "$20$" },{ key: "B", text: "$60$" },{ key: "C", text: "$30$" },{ key: "D", text: "$19$" },{ key: "E", text: "$32$" }],
    answer: "C", solution: "Area $=\\tfrac12\\cdot15\\cdot4=30.$" },
  { id: "tara-mk3-ps-16", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "A box measures $5\\times4\\times3$. What is its volume?",
    options: [{ key: "A", text: "$94$" },{ key: "B", text: "$20$" },{ key: "C", text: "$60$" },{ key: "D", text: "$65$" },{ key: "E", text: "$12$" }],
    answer: "C", solution: "Volume $=5\\times4\\times3=60.$" },
  { id: "tara-mk3-ps-17", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "A box measures $10\\times3\\times2$. What is its volume?",
    options: [{ key: "A", text: "$60$" },{ key: "B", text: "$30$" },{ key: "C", text: "$15$" },{ key: "D", text: "$112$" },{ key: "E", text: "$70$" }],
    answer: "A", solution: "Volume $=10\\times3\\times2=60.$" },
  { id: "tara-mk3-ps-18", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "A box measures $7\\times5\\times2$. What is its volume?",
    options: [{ key: "A", text: "$77$" },{ key: "B", text: "$118$" },{ key: "C", text: "$14$" },{ key: "D", text: "$70$" },{ key: "E", text: "$35$" }],
    answer: "D", solution: "Volume $=7\\times5\\times2=70.$" },
  { id: "tara-mk3-ps-19", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "A recipe for $4$ people needs $300$ g of flour. How much is needed for $6$ people?",
    options: [{ key: "A", text: "$50$ g" },{ key: "B", text: "$1800$ g" },{ key: "C", text: "$300$ g" },{ key: "D", text: "$460$ g" },{ key: "E", text: "$450$ g" }],
    answer: "E", solution: "Scale by $\\tfrac{6}{4}$: $300\\times\\tfrac{6}{4}=450$ g." },
  { id: "tara-mk3-ps-20", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "A recipe for $8$ people needs $200$ g of flour. How much is needed for $2$ people?",
    options: [{ key: "A", text: "$50$ g" },{ key: "B", text: "$100$ g" },{ key: "C", text: "$60$ g" },{ key: "D", text: "$400$ g" },{ key: "E", text: "$200$ g" }],
    answer: "A", solution: "Scale by $\\tfrac{2}{8}$: $200\\times\\tfrac{2}{8}=50$ g." },
  { id: "tara-mk3-ps-21", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "A recipe for $3$ people needs $150$ g of flour. How much is needed for $5$ people?",
    options: [{ key: "A", text: "$260$ g" },{ key: "B", text: "$30$ g" },{ key: "C", text: "$150$ g" },{ key: "D", text: "$250$ g" },{ key: "E", text: "$750$ g" }],
    answer: "D", solution: "Scale by $\\tfrac{5}{3}$: $150\\times\\tfrac{5}{3}=250$ g." },
  { id: "tara-mk3-ps-22", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "A recipe for $6$ people needs $240$ g of flour. How much is needed for $4$ people?",
    options: [{ key: "A", text: "$60$ g" },{ key: "B", text: "$960$ g" },{ key: "C", text: "$240$ g" },{ key: "D", text: "$170$ g" },{ key: "E", text: "$160$ g" }],
    answer: "E", solution: "Scale by $\\tfrac{4}{6}$: $240\\times\\tfrac{4}{6}=160$ g." },
];
