// TMUA 模拟卷四 —— 全新原创题，与卷一/二/三、练习题均不重复。两卷各 20 题、各 75 分钟、五选一、无负分。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const TMUA_MK4_P1: MCQQuestion[] = [
  { id:"tmua-mk4-p1-01", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The positive root of $x^2+2x-15=0$ is:", options:[{key:"A",text:"$3$"},{key:"B",text:"$5$"},{key:"C",text:"$-5$"},{key:"D",text:"$-3$"},{key:"E",text:"$15$"}],
    answer:"A", solution:"$(x+5)(x-3)=0$; positive root $3.$" },
  { id:"tmua-mk4-p1-02", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Evaluate $27^{2/3}$.", options:[{key:"A",text:"$6$"},{key:"B",text:"$9$"},{key:"C",text:"$3$"},{key:"D",text:"$18$"},{key:"E",text:"$81$"}],
    answer:"B", solution:"$27^{1/3}=3$, then $3^2=9.$" },
  { id:"tmua-mk4-p1-03", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:1, marks:1,
    question:"Simplify $\\sqrt8\\times\\sqrt2$.", options:[{key:"A",text:"$4$"},{key:"B",text:"$2$"},{key:"C",text:"$\\sqrt{10}$"},{key:"D",text:"$8$"},{key:"E",text:"$16$"}],
    answer:"A", solution:"$\\sqrt{8\\times2}=\\sqrt{16}=4.$" },
  { id:"tmua-mk4-p1-04", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The $20$th term of $1,4,7,\\ldots$ is:", options:[{key:"A",text:"$58$"},{key:"B",text:"$57$"},{key:"C",text:"$60$"},{key:"D",text:"$61$"},{key:"E",text:"$55$"}],
    answer:"A", solution:"$a=1,d=3$: $1+19\\times3=58.$" },
  { id:"tmua-mk4-p1-05", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Evaluate $8+4+2+1+\\cdots$ (sum to infinity).", options:[{key:"A",text:"$16$"},{key:"B",text:"$12$"},{key:"C",text:"$8$"},{key:"D",text:"$32$"},{key:"E",text:"$24$"}],
    answer:"A", solution:"$\\dfrac{8}{1-\\tfrac12}=16.$" },
  { id:"tmua-mk4-p1-06", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"The line of gradient $3$ through $(2,1)$ has $y$-intercept:", options:[{key:"A",text:"$-5$"},{key:"B",text:"$5$"},{key:"C",text:"$1$"},{key:"D",text:"$-1$"},{key:"E",text:"$3$"}],
    answer:"A", solution:"$y=3x+c$, $1=6+c\\Rightarrow c=-5.$" },
  { id:"tmua-mk4-p1-07", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:3, marks:1,
    question:"The radius of the circle $x^2+y^2-6x-8y=0$ is:", options:[{key:"A",text:"$5$"},{key:"B",text:"$4$"},{key:"C",text:"$3$"},{key:"D",text:"$\\sqrt7$"},{key:"E",text:"$10$"}],
    answer:"A", solution:"$(x-3)^2+(y-4)^2=25$, so $r=5.$" },
  { id:"tmua-mk4-p1-08", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"Evaluate $\\cos 90^\\circ$.", options:[{key:"A",text:"$0$"},{key:"B",text:"$1$"},{key:"C",text:"$-1$"},{key:"D",text:"$\\tfrac12$"},{key:"E",text:"$\\tfrac{\\sqrt3}{2}$"}],
    answer:"A", solution:"$\\cos90^\\circ=0.$" },
  { id:"tmua-mk4-p1-09", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"If $\\cos\\theta=0.6$ and $\\theta$ is acute, then $\\sin\\theta=$", options:[{key:"A",text:"$0.8$"},{key:"B",text:"$0.6$"},{key:"C",text:"$0.4$"},{key:"D",text:"$1$"},{key:"E",text:"$0.36$"}],
    answer:"A", solution:"$\\sin\\theta=\\sqrt{1-0.36}=\\sqrt{0.64}=0.8.$" },
  { id:"tmua-mk4-p1-10", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Solve $2^{x}=\\dfrac18$.", options:[{key:"A",text:"$-3$"},{key:"B",text:"$3$"},{key:"C",text:"$-2$"},{key:"D",text:"$\\tfrac13$"},{key:"E",text:"$8$"}],
    answer:"A", solution:"$\\tfrac18=2^{-3}$, so $x=-3.$" },
  { id:"tmua-mk4-p1-11", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Evaluate $\\log_3\\tfrac19$.", options:[{key:"A",text:"$-2$"},{key:"B",text:"$2$"},{key:"C",text:"$-3$"},{key:"D",text:"$9$"},{key:"E",text:"$\\tfrac12$"}],
    answer:"A", solution:"$\\tfrac19=3^{-2}$, so $\\log_3\\tfrac19=-2.$" },
  { id:"tmua-mk4-p1-12", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:3, marks:1,
    question:"Solve $\\log_5 x+\\log_5 2=2$.", options:[{key:"A",text:"$12.5$"},{key:"B",text:"$10$"},{key:"C",text:"$5$"},{key:"D",text:"$25$"},{key:"E",text:"$2.5$"}],
    answer:"A", solution:"$\\log_5(2x)=2\\Rightarrow 2x=25\\Rightarrow x=12.5.$" },
  { id:"tmua-mk4-p1-13", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"Find $\\dfrac{d}{dx}(2x^3+x)$ at $x=1$.", options:[{key:"A",text:"$7$"},{key:"B",text:"$6$"},{key:"C",text:"$3$"},{key:"D",text:"$9$"},{key:"E",text:"$1$"}],
    answer:"A", solution:"$6x^2+1$; at $x=1$, $7.$" },
  { id:"tmua-mk4-p1-14", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"The curve $y=x^2-2x$ has gradient zero at $x=$", options:[{key:"A",text:"$1$"},{key:"B",text:"$0$"},{key:"C",text:"$2$"},{key:"D",text:"$-1$"},{key:"E",text:"$-2$"}],
    answer:"A", solution:"$y'=2x-2=0\\Rightarrow x=1.$" },
  { id:"tmua-mk4-p1-15", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"Evaluate $\\displaystyle\\int_0^3 2\\,\\mathrm{d}x$.", options:[{key:"A",text:"$6$"},{key:"B",text:"$3$"},{key:"C",text:"$2$"},{key:"D",text:"$9$"},{key:"E",text:"$0$"}],
    answer:"A", solution:"$[2x]_0^3=6.$" },
  { id:"tmua-mk4-p1-16", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"The area under $y=x$ from $x=0$ to $x=4$ is:", options:[{key:"A",text:"$8$"},{key:"B",text:"$4$"},{key:"C",text:"$16$"},{key:"D",text:"$2$"},{key:"E",text:"$12$"}],
    answer:"A", solution:"$\\int_0^4 x\\,dx=\\left[\\tfrac{x^2}{2}\\right]_0^4=8.$" },
  { id:"tmua-mk4-p1-17", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The graph of $y=f(x)-2$ is $y=f(x)$ shifted:", options:[{key:"A",text:"down 2"},{key:"B",text:"up 2"},{key:"C",text:"left 2"},{key:"D",text:"right 2"},{key:"E",text:"down 2 and left 2"}],
    answer:"A", solution:"Subtracting $2$ from the output shifts the graph down by $2.$" },
  { id:"tmua-mk4-p1-18", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Given $f(x)=x+1$ and $g(x)=2x$, find $f(g(3))$.", options:[{key:"A",text:"$7$"},{key:"B",text:"$8$"},{key:"C",text:"$6$"},{key:"D",text:"$12$"},{key:"E",text:"$13$"}],
    answer:"A", solution:"$g(3)=6$, then $f(6)=7.$" },
  { id:"tmua-mk4-p1-19", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:1, marks:1,
    question:"Solve $3-x>0$.", options:[{key:"A",text:"$x<3$"},{key:"B",text:"$x>3$"},{key:"C",text:"$x<-3$"},{key:"D",text:"$x>-3$"},{key:"E",text:"$x<0$"}],
    answer:"A", solution:"$3>x$, i.e. $x<3.$" },
  { id:"tmua-mk4-p1-20", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The coefficient of $x$ in $(1+3x)^4$ is:", options:[{key:"A",text:"$12$"},{key:"B",text:"$4$"},{key:"C",text:"$3$"},{key:"D",text:"$9$"},{key:"E",text:"$6$"}],
    answer:"A", solution:"$\\binom{4}{1}(3)=12.$" },
];

export const TMUA_MK4_P2: MCQQuestion[] = [
  { id:"tmua-mk4-p2-01", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"For a quadrilateral to be a square, being a rectangle is:", options:[{key:"A",text:"sufficient but not necessary"},{key:"B",text:"necessary but not sufficient"},{key:"C",text:"both"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"B", solution:"Every square is a rectangle (necessary), but a rectangle need not be a square (not sufficient)." },
  { id:"tmua-mk4-p2-02", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Is the converse of 'if $x=0$ then $x^2=0$' true?", options:[{key:"A",text:"true"},{key:"B",text:"false; e.g. $x=1$"},{key:"C",text:"false; e.g. $x=-1$"},{key:"D",text:"the same statement"},{key:"E",text:"undecidable"}],
    answer:"A", solution:"Converse: 'if $x^2=0$ then $x=0$', which is true since $x^2=0$ forces $x=0.$" },
  { id:"tmua-mk4-p2-03", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:3, marks:1,
    question:"The contrapositive of 'if $x>0$ then $|x|=x$' is:", options:[{key:"A",text:"if $|x|=x$ then $x>0$"},{key:"B",text:"if $|x|\\ne x$ then $x\\le0$"},{key:"C",text:"if $x\\le0$ then $|x|\\ne x$"},{key:"D",text:"if $x>0$ then $|x|\\ne x$"},{key:"E",text:"if $|x|=x$ then $x\\le0$"}],
    answer:"B", solution:"Contrapositive $\\lnot Q\\Rightarrow\\lnot P$: 'if $|x|\\ne x$ then $x\\le0$'." },
  { id:"tmua-mk4-p2-04", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:1, marks:1,
    question:"Which value disproves 'all even numbers are multiples of $4$'?", options:[{key:"A",text:"$4$"},{key:"B",text:"$6$"},{key:"C",text:"$8$"},{key:"D",text:"$12$"},{key:"E",text:"none"}],
    answer:"B", solution:"$6$ is even but not a multiple of $4$ — a counterexample." },
  { id:"tmua-mk4-p2-05", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The negation of 'every prime is odd' is:", options:[{key:"A",text:"no prime is odd"},{key:"B",text:"at least one prime is not odd"},{key:"C",text:"all primes are even"},{key:"D",text:"some prime is odd"},{key:"E",text:"there are no primes"}],
    answer:"B", solution:"Negation of 'for all $x$: odd' is 'there exists $x$: not odd' — some prime is not odd (namely 2)." },
  { id:"tmua-mk4-p2-06", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The negation of '$x=1$ or $x=2$' is:", options:[{key:"A",text:"$x\\ne1$ or $x\\ne2$"},{key:"B",text:"$x\\ne1$ and $x\\ne2$"},{key:"C",text:"$x=1$ and $x=2$"},{key:"D",text:"$x>2$"},{key:"E",text:"$x\\ne1$"}],
    answer:"B", solution:"not($A$ or $B$) $=$ not $A$ and not $B$: $x\\ne1$ and $x\\ne2.$" },
  { id:"tmua-mk4-p2-07", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:1, marks:1,
    question:"The inclusive statement '$A$ or $B$' is false exactly when:", options:[{key:"A",text:"$A$ true, $B$ false"},{key:"B",text:"both are false"},{key:"C",text:"both are true"},{key:"D",text:"$A$ false, $B$ true"},{key:"E",text:"it is never false"}],
    answer:"B", solution:"Inclusive 'or' fails only when neither part holds." },
  { id:"tmua-mk4-p2-08", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:1, marks:1,
    question:"Given $A\\Rightarrow B$ and $B\\Rightarrow C$ are true and $A$ is true, which must hold?", options:[{key:"A",text:"only $B$"},{key:"B",text:"$C$"},{key:"C",text:"neither"},{key:"D",text:"$\\lnot C$"},{key:"E",text:"$\\lnot A$"}],
    answer:"B", solution:"Chaining from $A$: $B$ then $C$; in particular $C$ holds." },
  { id:"tmua-mk4-p2-09", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:3, marks:1,
    question:"A student writes '$\\sqrt{x^2}=x$ for all real $x$'. The flaw is that it:", options:[{key:"A",text:"fails when $x<0$, since $\\sqrt{x^2}=|x|$"},{key:"B",text:"divides by zero"},{key:"C",text:"has no flaw"},{key:"D",text:"fails only when $x=0$"},{key:"E",text:"assumes $x$ is an integer"}],
    answer:"A", solution:"$\\sqrt{x^2}=|x|$; for $x<0$ this is $-x\\ne x.$" },
  { id:"tmua-mk4-p2-10", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:3, marks:1,
    question:"'From $f(a)=f(b)$ we conclude $a=b$.' This is valid only if:", options:[{key:"A",text:"$f$ is increasing at $a$"},{key:"B",text:"$f$ is one-to-one (injective)"},{key:"C",text:"$f$ is continuous"},{key:"D",text:"$a,b>0$"},{key:"E",text:"always valid"}],
    answer:"B", solution:"Cancelling $f$ requires $f$ to be injective; otherwise different inputs can share an output." },
  { id:"tmua-mk4-p2-11", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Assuming there is a largest prime and deriving an absurdity is an example of:", options:[{key:"A",text:"proof by contradiction"},{key:"B",text:"proof by cases"},{key:"C",text:"disproof by counterexample"},{key:"D",text:"direct proof"},{key:"E",text:"a converse argument"}],
    answer:"A", solution:"Assuming the negation of the claim to reach a contradiction is proof by contradiction." },
  { id:"tmua-mk4-p2-12", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Proving a statement for all integers by treating $n=3k,\\,3k+1,\\,3k+2$ separately is:", options:[{key:"A",text:"proof by contradiction"},{key:"B",text:"proof by cases"},{key:"C",text:"disproof by counterexample"},{key:"D",text:"induction"},{key:"E",text:"a circular argument"}],
    answer:"B", solution:"Exhausting all residue classes mod 3 is proof by cases." },
  { id:"tmua-mk4-p2-13", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:3, marks:1,
    question:"The $n$-th term of the sequence $1,3,6,10,15,\\ldots$ (triangular numbers) is:", options:[{key:"A",text:"$n^2$"},{key:"B",text:"$\\tfrac{n(n+1)}{2}$"},{key:"C",text:"$2n-1$"},{key:"D",text:"$n(n-1)$"},{key:"E",text:"$n+2$"}],
    answer:"B", solution:"The $n$-th triangular number is $1+2+\\cdots+n=\\tfrac{n(n+1)}{2}.$" },
  { id:"tmua-mk4-p2-14", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The condition '$|x|=3$' is ______ for '$x^2=9$'.", options:[{key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both necessary and sufficient"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"C", solution:"$|x|=3\\Leftrightarrow x=\\pm3\\Leftrightarrow x^2=9$: the conditions are equivalent." },
  { id:"tmua-mk4-p2-15", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"Six people each shake hands once with every other person. How many handshakes occur?", options:[{key:"A",text:"$12$"},{key:"B",text:"$15$"},{key:"C",text:"$30$"},{key:"D",text:"$36$"},{key:"E",text:"$21$"}],
    answer:"B", solution:"$\\binom{6}{2}=15.$" },
  { id:"tmua-mk4-p2-16", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"For a number to be positive, being greater than $10$ is:", options:[{key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"B", solution:"$>10\\Rightarrow>0$ (sufficient); but a positive number need not exceed $10$ (not necessary)." },
  { id:"tmua-mk4-p2-17", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The negation of 'for all real $x$, $x^2\\ge0$' is:", options:[{key:"A",text:"for all real $x$, $x^2<0$"},{key:"B",text:"there exists a real $x$ with $x^2<0$"},{key:"C",text:"there exists a real $x$ with $x^2\\ge0$"},{key:"D",text:"for all real $x$, $x^2\\le0$"},{key:"E",text:"no real numbers exist"}],
    answer:"B", solution:"Negate 'for all' to 'there exists' and negate $\\ge$ to $<$: there exists $x$ with $x^2<0$ (which is in fact false, confirming the original is true)." },
  { id:"tmua-mk4-p2-18", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"Which value shows 'if $n$ is divisible by $6$ then $n$ is divisible by $12$' is false?", options:[{key:"A",text:"$6$"},{key:"B",text:"$12$"},{key:"C",text:"$24$"},{key:"D",text:"$36$"},{key:"E",text:"none"}],
    answer:"A", solution:"$6$ is divisible by $6$ but not by $12$ — a counterexample." },
  { id:"tmua-mk4-p2-19", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"Using $1+2+\\cdots+n=\\tfrac{n(n+1)}{2}$, find $1+2+\\cdots+20$.", options:[{key:"A",text:"$210$"},{key:"B",text:"$200$"},{key:"C",text:"$190$"},{key:"D",text:"$220$"},{key:"E",text:"$400$"}],
    answer:"A", solution:"$\\tfrac{20\\times21}{2}=210.$" },
  { id:"tmua-mk4-p2-20", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:3, marks:1,
    question:"Being divisible by both $2$ and $3$ is ______ for being divisible by $6$.", options:[{key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both necessary and sufficient"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"C", solution:"Since $2$ and $3$ are coprime, divisible by both $\\Leftrightarrow$ divisible by $6$: both necessary and sufficient." },
];
