// TMUA 模拟卷六 —— 全新原创题，与卷一~五、练习题均不重复。两卷各 20 题、各 75 分钟、五选一、无负分。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const TMUA_MK6_P1: MCQQuestion[] = [
  { id:"tmua-mk6-p1-01", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The positive root of $x^2-x-12=0$ is:", options:[{key:"A",text:"$4$"},{key:"B",text:"$3$"},{key:"C",text:"$-3$"},{key:"D",text:"$12$"},{key:"E",text:"$1$"}],
    answer:"A", solution:"$(x-4)(x+3)=0$; positive root $4.$" },
  { id:"tmua-mk6-p1-02", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:1, marks:1,
    question:"Evaluate $64^{1/2}$.", options:[{key:"A",text:"$6$"},{key:"B",text:"$8$"},{key:"C",text:"$4$"},{key:"D",text:"$16$"},{key:"E",text:"$32$"}],
    answer:"B", solution:"$\\sqrt{64}=8.$" },
  { id:"tmua-mk6-p1-03", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Simplify $\\sqrt{18}+\\sqrt{2}$.", options:[{key:"A",text:"$4\\sqrt2$"},{key:"B",text:"$3\\sqrt2$"},{key:"C",text:"$\\sqrt{20}$"},{key:"D",text:"$5\\sqrt2$"},{key:"E",text:"$2\\sqrt2$"}],
    answer:"A", solution:"$3\\sqrt2+\\sqrt2=4\\sqrt2.$" },
  { id:"tmua-mk6-p1-04", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Find the sum of the first $8$ terms of $2+5+8+\\cdots$.", options:[{key:"A",text:"$100$"},{key:"B",text:"$96$"},{key:"C",text:"$104$"},{key:"D",text:"$92$"},{key:"E",text:"$110$"}],
    answer:"A", solution:"$a=2,d=3$: $S_8=\\tfrac{8}{2}(4+7\\cdot3)=4\\times25=100.$" },
  { id:"tmua-mk6-p1-05", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Evaluate $9+3+1+\\tfrac13+\\cdots$ (sum to infinity).", options:[{key:"A",text:"$13.5$"},{key:"B",text:"$12$"},{key:"C",text:"$18$"},{key:"D",text:"$27$"},{key:"E",text:"$9$"}],
    answer:"A", solution:"$\\dfrac{9}{1-\\tfrac13}=\\dfrac{9}{2/3}=13.5.$" },
  { id:"tmua-mk6-p1-06", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"The gradient of the line through $(0,5)$ and $(4,13)$ is:", options:[{key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$8$"},{key:"D",text:"$1$"},{key:"E",text:"$\\tfrac12$"}],
    answer:"A", solution:"$\\tfrac{13-5}{4-0}=2.$" },
  { id:"tmua-mk6-p1-07", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"The equation of the circle with centre $(3,-1)$ and radius $4$ is:", options:[{key:"A",text:"$(x-3)^2+(y+1)^2=16$"},{key:"B",text:"$(x+3)^2+(y-1)^2=16$"},{key:"C",text:"$(x-3)^2+(y-1)^2=4$"},{key:"D",text:"$(x-3)^2+(y+1)^2=4$"},{key:"E",text:"$(x+3)^2+(y+1)^2=16$"}],
    answer:"A", solution:"$(x-a)^2+(y-b)^2=r^2$: $(x-3)^2+(y+1)^2=16.$" },
  { id:"tmua-mk6-p1-08", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"Evaluate $\\tan 30^\\circ$.", options:[{key:"A",text:"$\\tfrac{1}{\\sqrt3}$"},{key:"B",text:"$\\sqrt3$"},{key:"C",text:"$1$"},{key:"D",text:"$\\tfrac12$"},{key:"E",text:"$\\tfrac{\\sqrt3}{2}$"}],
    answer:"A", solution:"$\\tan30^\\circ=\\tfrac{1}{\\sqrt3}.$" },
  { id:"tmua-mk6-p1-09", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"If $\\tan\\theta=\\tfrac43$ and $\\theta$ is acute, then $\\sin\\theta=$", options:[{key:"A",text:"$\\tfrac45$"},{key:"B",text:"$\\tfrac35$"},{key:"C",text:"$\\tfrac43$"},{key:"D",text:"$\\tfrac54$"},{key:"E",text:"$1$"}],
    answer:"A", solution:"A $3$–$4$–$5$ triangle gives $\\sin\\theta=\\tfrac45.$" },
  { id:"tmua-mk6-p1-10", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:1, marks:1,
    question:"Solve $5^{x}=125$.", options:[{key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$5$"},{key:"D",text:"$25$"},{key:"E",text:"$4$"}],
    answer:"B", solution:"$125=5^3$, so $x=3.$" },
  { id:"tmua-mk6-p1-11", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Evaluate $\\log_2 32$.", options:[{key:"A",text:"$4$"},{key:"B",text:"$5$"},{key:"C",text:"$6$"},{key:"D",text:"$16$"},{key:"E",text:"$8$"}],
    answer:"B", solution:"$32=2^5$, so $\\log_2 32=5.$" },
  { id:"tmua-mk6-p1-12", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Solve $\\log_{10}x=3$.", options:[{key:"A",text:"$100$"},{key:"B",text:"$1000$"},{key:"C",text:"$30$"},{key:"D",text:"$300$"},{key:"E",text:"$3$"}],
    answer:"B", solution:"$x=10^3=1000.$" },
  { id:"tmua-mk6-p1-13", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"Find $\\dfrac{d}{dx}(x^2+3x)$ at $x=1$.", options:[{key:"A",text:"$5$"},{key:"B",text:"$4$"},{key:"C",text:"$3$"},{key:"D",text:"$2$"},{key:"E",text:"$6$"}],
    answer:"A", solution:"$2x+3$; at $x=1$, $5.$" },
  { id:"tmua-mk6-p1-14", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"The gradient of $y=x^3$ at $x=1$ is:", options:[{key:"A",text:"$1$"},{key:"B",text:"$3$"},{key:"C",text:"$6$"},{key:"D",text:"$9$"},{key:"E",text:"$2$"}],
    answer:"B", solution:"$y'=3x^2=3$ at $x=1.$" },
  { id:"tmua-mk6-p1-15", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"Evaluate $\\displaystyle\\int_1^3 2x\\,\\mathrm{d}x$.", options:[{key:"A",text:"$6$"},{key:"B",text:"$8$"},{key:"C",text:"$9$"},{key:"D",text:"$4$"},{key:"E",text:"$12$"}],
    answer:"B", solution:"$[x^2]_1^3=9-1=8.$" },
  { id:"tmua-mk6-p1-16", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"The area under $y=2x+1$ from $x=0$ to $x=2$ is:", options:[{key:"A",text:"$4$"},{key:"B",text:"$6$"},{key:"C",text:"$8$"},{key:"D",text:"$2$"},{key:"E",text:"$5$"}],
    answer:"B", solution:"$\\int_0^2(2x+1)\\,dx=[x^2+x]_0^2=6.$" },
  { id:"tmua-mk6-p1-17", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The graph of $y=-f(x)$ is $y=f(x)$ reflected in the:", options:[{key:"A",text:"$x$-axis"},{key:"B",text:"$y$-axis"},{key:"C",text:"origin"},{key:"D",text:"line $y=x$"},{key:"E",text:"line $x=1$"}],
    answer:"A", solution:"Negating the output reflects the graph in the $x$-axis." },
  { id:"tmua-mk6-p1-18", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Given $f(x)=2x-1$ and $g(x)=x^2$, find $g(f(2))$.", options:[{key:"A",text:"$9$"},{key:"B",text:"$6$"},{key:"C",text:"$4$"},{key:"D",text:"$8$"},{key:"E",text:"$3$"}],
    answer:"A", solution:"$f(2)=3$, then $g(3)=9.$" },
  { id:"tmua-mk6-p1-19", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:1, marks:1,
    question:"Solve $\\dfrac{x}{2}>3$.", options:[{key:"A",text:"$x>6$"},{key:"B",text:"$x>3$"},{key:"C",text:"$x<6$"},{key:"D",text:"$x>1.5$"},{key:"E",text:"$x>9$"}],
    answer:"A", solution:"Multiply both sides by $2$: $x>6.$" },
  { id:"tmua-mk6-p1-20", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The coefficient of $x^2$ in $(2+x)^4$ is:", options:[{key:"A",text:"$24$"},{key:"B",text:"$12$"},{key:"C",text:"$6$"},{key:"D",text:"$48$"},{key:"E",text:"$16$"}],
    answer:"A", solution:"$\\binom{4}{2}(2)^2=6\\times4=24.$" },
];

export const TMUA_MK6_P2: MCQQuestion[] = [
  { id:"tmua-mk6-p2-01", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"For an integer to be divisible by $8$, being divisible by $2$ is:", options:[{key:"A",text:"sufficient but not necessary"},{key:"B",text:"necessary but not sufficient"},{key:"C",text:"both"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"B", solution:"Divisible by 8 $\\Rightarrow$ divisible by 2 (necessary), but 2 is divisible by 2 not 8 (not sufficient)." },
  { id:"tmua-mk6-p2-02", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Is the converse of 'if $x>0$ then $x^2>0$' true?", options:[{key:"A",text:"true"},{key:"B",text:"false; e.g. $x=-1$"},{key:"C",text:"false; e.g. $x=1$"},{key:"D",text:"the same statement"},{key:"E",text:"undecidable"}],
    answer:"B", solution:"Converse: 'if $x^2>0$ then $x>0$', false since $x=-1$ gives $x^2>0$ but $x<0.$" },
  { id:"tmua-mk6-p2-03", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The contrapositive of 'if a number is prime then it has exactly two positive factors' is:", options:[{key:"A",text:"if a number has exactly two factors then it is prime"},{key:"B",text:"if a number does not have exactly two factors then it is not prime"},{key:"C",text:"if a number is not prime then it does not have exactly two factors"},{key:"D",text:"if a number is prime then it has more than two factors"},{key:"E",text:"all numbers are prime"}],
    answer:"B", solution:"Contrapositive $\\lnot Q\\Rightarrow\\lnot P$: 'if not exactly two factors then not prime'." },
  { id:"tmua-mk6-p2-04", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:1, marks:1,
    question:"Which value disproves 'all perfect squares are even'?", options:[{key:"A",text:"$4$"},{key:"B",text:"$9$"},{key:"C",text:"$16$"},{key:"D",text:"$36$"},{key:"E",text:"none"}],
    answer:"B", solution:"$9=3^2$ is a perfect square but odd — a counterexample." },
  { id:"tmua-mk6-p2-05", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The negation of 'there exists an integer $x$ with $x+3=x$' is:", options:[{key:"A",text:"there exists an integer $x$ with $x+3\\ne x$"},{key:"B",text:"for all integers $x$, $x+3\\ne x$"},{key:"C",text:"for all integers $x$, $x+3=x$"},{key:"D",text:"no integer exists"},{key:"E",text:"$x=3$"}],
    answer:"B", solution:"Negate 'there exists' to 'for all' with the inner statement negated: for all $x$, $x+3\\ne x.$" },
  { id:"tmua-mk6-p2-06", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The negation of '$x<0$ or $x>10$' is:", options:[{key:"A",text:"$x>0$ and $x<10$"},{key:"B",text:"$0\\le x\\le10$"},{key:"C",text:"$x\\le0$ or $x\\ge10$"},{key:"D",text:"$x\\ge0$ or $x\\le10$"},{key:"E",text:"$x\\ne0$"}],
    answer:"B", solution:"not($A$ or $B$) $=$ not $A$ and not $B$: $x\\ge0$ and $x\\le10$, i.e. $0\\le x\\le10.$" },
  { id:"tmua-mk6-p2-07", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"What is the truth value of the implication 'if $2>3$ then $5>1$'?", options:[{key:"A",text:"true"},{key:"B",text:"false"},{key:"C",text:"undefined"},{key:"D",text:"depends on the numbers"},{key:"E",text:"cannot be evaluated"}],
    answer:"A", solution:"The hypothesis $2>3$ is false, so the implication is vacuously true." },
  { id:"tmua-mk6-p2-08", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:3, marks:1,
    question:"Given $A\\Rightarrow B$, $B\\Rightarrow C$, $C\\Rightarrow D$ are true and $D$ is false, what follows?", options:[{key:"A",text:"$A$ is true"},{key:"B",text:"$A$ is false"},{key:"C",text:"$C$ is true"},{key:"D",text:"nothing"},{key:"E",text:"$D$ is true"}],
    answer:"B", solution:"Contrapositive chain: $\\lnot D\\Rightarrow\\lnot C\\Rightarrow\\lnot B\\Rightarrow\\lnot A$; so $A$ is false." },
  { id:"tmua-mk6-p2-09", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:3, marks:1,
    question:"'Since $a>b$, it follows that $a^2>b^2$.' The flaw is that it:", options:[{key:"A",text:"fails when negatives are involved, e.g. $a=1,b=-2$"},{key:"B",text:"divides by zero"},{key:"C",text:"has no flaw"},{key:"D",text:"assumes $a,b>0$ correctly"},{key:"E",text:"takes square roots"}],
    answer:"A", solution:"With $a=1,b=-2$: $a>b$ holds but $a^2=1<4=b^2$; squaring does not preserve order when negatives appear." },
  { id:"tmua-mk6-p2-10", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"'Every equilateral triangle is isosceles, therefore every isosceles triangle is equilateral.' The error is:", options:[{key:"A",text:"a false premise"},{key:"B",text:"assuming the converse"},{key:"C",text:"dividing by zero"},{key:"D",text:"proof by contradiction"},{key:"E",text:"a counterexample"}],
    answer:"B", solution:"Concluding $Q\\Rightarrow P$ from $P\\Rightarrow Q$ assumes the converse, which is invalid." },
  { id:"tmua-mk6-p2-11", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Assuming $\\sqrt3$ is rational and deriving a contradiction is an example of:", options:[{key:"A",text:"proof by contradiction"},{key:"B",text:"proof by cases"},{key:"C",text:"disproof by counterexample"},{key:"D",text:"direct proof"},{key:"E",text:"induction"}],
    answer:"A", solution:"Assuming the negation of the claim to reach a contradiction is proof by contradiction." },
  { id:"tmua-mk6-p2-12", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Proving that $|x|\\ge0$ by considering $x\\ge0$ and $x<0$ separately is:", options:[{key:"A",text:"proof by contradiction"},{key:"B",text:"proof by cases"},{key:"C",text:"disproof by counterexample"},{key:"D",text:"a converse argument"},{key:"E",text:"circular reasoning"}],
    answer:"B", solution:"Splitting into the exhaustive cases $x\\ge0$ and $x<0$ is proof by cases." },
  { id:"tmua-mk6-p2-13", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"The $n$-th term of $1,4,9,16,25,\\ldots$ is:", options:[{key:"A",text:"$2n-1$"},{key:"B",text:"$n^2$"},{key:"C",text:"$n^2+1$"},{key:"D",text:"$2n$"},{key:"E",text:"$n(n+1)$"}],
    answer:"B", solution:"These are the perfect squares $n^2.$" },
  { id:"tmua-mk6-p2-14", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:3, marks:1,
    question:"For real $x$, the condition '$x^2=x$' is ______ for '$x\\in\\{0,1\\}$'.", options:[{key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both necessary and sufficient"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"C", solution:"$x^2=x\\Leftrightarrow x(x-1)=0\\Leftrightarrow x\\in\\{0,1\\}$: the conditions are equivalent." },
  { id:"tmua-mk6-p2-15", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"Seven people each shake hands once with every other person. How many handshakes occur?", options:[{key:"A",text:"$14$"},{key:"B",text:"$21$"},{key:"C",text:"$42$"},{key:"D",text:"$28$"},{key:"E",text:"$7$"}],
    answer:"B", solution:"$\\binom{7}{2}=21.$" },
  { id:"tmua-mk6-p2-16", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"For a quadrilateral to be a square, having four equal sides is:", options:[{key:"A",text:"sufficient but not necessary"},{key:"B",text:"necessary but not sufficient"},{key:"C",text:"both"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"B", solution:"A square has four equal sides (necessary), but a rhombus has four equal sides without being a square (not sufficient)." },
  { id:"tmua-mk6-p2-17", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The negation of 'every even number is divisible by $2$' is:", options:[{key:"A",text:"no even number is divisible by 2"},{key:"B",text:"at least one even number is not divisible by 2"},{key:"C",text:"every even number is divisible by 4"},{key:"D",text:"some even number is divisible by 2"},{key:"E",text:"even numbers do not exist"}],
    answer:"B", solution:"Negation of 'for all $x$: $P$' is 'there exists $x$: not $P$' (here false, but that is the negation)." },
  { id:"tmua-mk6-p2-18", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Which value shows 'if $n$ is odd then $n$ is prime' is false?", options:[{key:"A",text:"$3$"},{key:"B",text:"$9$"},{key:"C",text:"$5$"},{key:"D",text:"$7$"},{key:"E",text:"none"}],
    answer:"B", solution:"$9$ is odd but not prime ($9=3\\times3$), a counterexample." },
  { id:"tmua-mk6-p2-19", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"Using $2+4+\\cdots+2n=n(n+1)$, find $2+4+\\cdots+30$.", options:[{key:"A",text:"$210$"},{key:"B",text:"$240$"},{key:"C",text:"$225$"},{key:"D",text:"$255$"},{key:"E",text:"$120$"}],
    answer:"B", solution:"Last term $30=2n\\Rightarrow n=15$; sum $=15\\times16=240.$" },
  { id:"tmua-mk6-p2-20", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:3, marks:1,
    question:"Being a multiple of $6$ is ______ for being a multiple of $3$.", options:[{key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both necessary and sufficient"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"B", solution:"A multiple of $6$ is a multiple of $3$ (sufficient), but $9$ is a multiple of $3$ not of $6$ (not necessary)." },
];
