// TMUA 模拟卷七 —— 全新原创题，与卷一~六、练习题均不重复。两卷各 20 题、各 75 分钟、五选一、无负分。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const TMUA_MK7_P1: MCQQuestion[] = [
  { id:"tmua-mk7-p1-01", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The smaller root of $x^2-9x+20=0$ is:", options:[{key:"A",text:"$4$"},{key:"B",text:"$5$"},{key:"C",text:"$9$"},{key:"D",text:"$20$"},{key:"E",text:"$1$"}],
    answer:"A", solution:"$(x-4)(x-5)=0$; smaller root $4.$" },
  { id:"tmua-mk7-p1-02", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Evaluate $125^{2/3}$.", options:[{key:"A",text:"$5$"},{key:"B",text:"$25$"},{key:"C",text:"$15$"},{key:"D",text:"$625$"},{key:"E",text:"$10$"}],
    answer:"B", solution:"$125^{1/3}=5$, then $5^2=25.$" },
  { id:"tmua-mk7-p1-03", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Simplify $\\sqrt{48}+\\sqrt{3}$.", options:[{key:"A",text:"$5\\sqrt3$"},{key:"B",text:"$4\\sqrt3$"},{key:"C",text:"$\\sqrt{51}$"},{key:"D",text:"$6\\sqrt3$"},{key:"E",text:"$3\\sqrt3$"}],
    answer:"A", solution:"$4\\sqrt3+\\sqrt3=5\\sqrt3.$" },
  { id:"tmua-mk7-p1-04", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Find the sum of the first $10$ terms of $4+9+14+\\cdots$.", options:[{key:"A",text:"$265$"},{key:"B",text:"$255$"},{key:"C",text:"$275$"},{key:"D",text:"$250$"},{key:"E",text:"$260$"}],
    answer:"A", solution:"$a=4,d=5$: $S_{10}=\\tfrac{10}{2}(8+9\\cdot5)=5\\times53=265.$" },
  { id:"tmua-mk7-p1-05", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The $5$th term of the geometric sequence $2,4,8,\\ldots$ is:", options:[{key:"A",text:"$32$"},{key:"B",text:"$16$"},{key:"C",text:"$64$"},{key:"D",text:"$24$"},{key:"E",text:"$48$"}],
    answer:"A", solution:"$ar^4=2\\cdot2^4=32.$" },
  { id:"tmua-mk7-p1-06", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"The gradient of the line through $(2,3)$ and $(6,15)$ is:", options:[{key:"A",text:"$3$"},{key:"B",text:"$2$"},{key:"C",text:"$4$"},{key:"D",text:"$1$"},{key:"E",text:"$\\tfrac13$"}],
    answer:"A", solution:"$\\tfrac{15-3}{6-2}=\\tfrac{12}{4}=3.$" },
  { id:"tmua-mk7-p1-07", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:3, marks:1,
    question:"The radius of the circle $x^2+y^2+6x-2y-6=0$ is:", options:[{key:"A",text:"$4$"},{key:"B",text:"$16$"},{key:"C",text:"$\\sqrt6$"},{key:"D",text:"$3$"},{key:"E",text:"$5$"}],
    answer:"A", solution:"$(x+3)^2+(y-1)^2=6+9+1=16$, so $r=4.$" },
  { id:"tmua-mk7-p1-08", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"Evaluate $\\sin 60^\\circ$.", options:[{key:"A",text:"$\\tfrac{\\sqrt3}{2}$"},{key:"B",text:"$\\tfrac12$"},{key:"C",text:"$1$"},{key:"D",text:"$0$"},{key:"E",text:"$\\tfrac{\\sqrt2}{2}$"}],
    answer:"A", solution:"$\\sin60^\\circ=\\tfrac{\\sqrt3}{2}.$" },
  { id:"tmua-mk7-p1-09", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"If $\\cos\\theta=\\tfrac{8}{17}$ and $\\theta$ is acute, then $\\sin\\theta=$", options:[{key:"A",text:"$\\tfrac{15}{17}$"},{key:"B",text:"$\\tfrac{8}{17}$"},{key:"C",text:"$\\tfrac{17}{15}$"},{key:"D",text:"$\\tfrac{9}{17}$"},{key:"E",text:"$1$"}],
    answer:"A", solution:"$\\sin\\theta=\\sqrt{1-\\tfrac{64}{289}}=\\sqrt{\\tfrac{225}{289}}=\\tfrac{15}{17}.$" },
  { id:"tmua-mk7-p1-10", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:1, marks:1,
    question:"Solve $2^{x}=64$.", options:[{key:"A",text:"$5$"},{key:"B",text:"$6$"},{key:"C",text:"$7$"},{key:"D",text:"$32$"},{key:"E",text:"$8$"}],
    answer:"B", solution:"$64=2^6$, so $x=6.$" },
  { id:"tmua-mk7-p1-11", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Evaluate $\\log_3 27$.", options:[{key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$9$"},{key:"D",text:"$27$"},{key:"E",text:"$1$"}],
    answer:"B", solution:"$27=3^3$, so $\\log_3 27=3.$" },
  { id:"tmua-mk7-p1-12", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Solve $\\log_2 x=6$.", options:[{key:"A",text:"$12$"},{key:"B",text:"$36$"},{key:"C",text:"$64$"},{key:"D",text:"$32$"},{key:"E",text:"$128$"}],
    answer:"C", solution:"$x=2^6=64.$" },
  { id:"tmua-mk7-p1-13", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"Find $\\dfrac{d}{dx}(x^2+2x-1)$ at $x=3$.", options:[{key:"A",text:"$8$"},{key:"B",text:"$6$"},{key:"C",text:"$5$"},{key:"D",text:"$4$"},{key:"E",text:"$10$"}],
    answer:"A", solution:"$2x+2$; at $x=3$, $8.$" },
  { id:"tmua-mk7-p1-14", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"The gradient of $y=5x^2$ at $x=1$ is:", options:[{key:"A",text:"$5$"},{key:"B",text:"$10$"},{key:"C",text:"$1$"},{key:"D",text:"$25$"},{key:"E",text:"$2$"}],
    answer:"B", solution:"$y'=10x=10$ at $x=1.$" },
  { id:"tmua-mk7-p1-15", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"Evaluate $\\displaystyle\\int_0^3 2x\\,\\mathrm{d}x$.", options:[{key:"A",text:"$6$"},{key:"B",text:"$9$"},{key:"C",text:"$12$"},{key:"D",text:"$3$"},{key:"E",text:"$18$"}],
    answer:"B", solution:"$[x^2]_0^3=9.$" },
  { id:"tmua-mk7-p1-16", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"The area under $y=3x^2$ from $x=0$ to $x=1$ is:", options:[{key:"A",text:"$1$"},{key:"B",text:"$3$"},{key:"C",text:"$\\tfrac13$"},{key:"D",text:"$2$"},{key:"E",text:"$6$"}],
    answer:"A", solution:"$\\int_0^1 3x^2\\,dx=[x^3]_0^1=1.$" },
  { id:"tmua-mk7-p1-17", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The graph of $y=f(x)+4$ is $y=f(x)$ shifted:", options:[{key:"A",text:"up 4"},{key:"B",text:"down 4"},{key:"C",text:"left 4"},{key:"D",text:"right 4"},{key:"E",text:"up 4 and right 4"}],
    answer:"A", solution:"Adding $4$ to the output shifts the graph up by $4.$" },
  { id:"tmua-mk7-p1-18", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Given $f(x)=x-3$ and $g(x)=2x$, find $f(g(5))$.", options:[{key:"A",text:"$7$"},{key:"B",text:"$13$"},{key:"C",text:"$2$"},{key:"D",text:"$10$"},{key:"E",text:"$17$"}],
    answer:"A", solution:"$g(5)=10$, then $f(10)=7.$" },
  { id:"tmua-mk7-p1-19", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:1, marks:1,
    question:"Solve $5x-2>13$.", options:[{key:"A",text:"$x>3$"},{key:"B",text:"$x<3$"},{key:"C",text:"$x>15$"},{key:"D",text:"$x>2.2$"},{key:"E",text:"$x\\ge3$"}],
    answer:"A", solution:"$5x>15\\Rightarrow x>3.$" },
  { id:"tmua-mk7-p1-20", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The coefficient of $x^2$ in $(1+2x)^3$ is:", options:[{key:"A",text:"$12$"},{key:"B",text:"$6$"},{key:"C",text:"$8$"},{key:"D",text:"$3$"},{key:"E",text:"$4$"}],
    answer:"A", solution:"$\\binom{3}{2}(2)^2=3\\times4=12.$" },
];

export const TMUA_MK7_P2: MCQQuestion[] = [
  { id:"tmua-mk7-p2-01", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"For an integer to be divisible by $9$, being divisible by $3$ is:", options:[{key:"A",text:"sufficient but not necessary"},{key:"B",text:"necessary but not sufficient"},{key:"C",text:"both"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"B", solution:"Divisible by 9 $\\Rightarrow$ divisible by 3 (necessary), but 6 is divisible by 3 not 9 (not sufficient)." },
  { id:"tmua-mk7-p2-02", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Is the converse of 'if $n$ is divisible by $6$ then $n$ is divisible by $3$' true?", options:[{key:"A",text:"true"},{key:"B",text:"false; e.g. $n=9$"},{key:"C",text:"false; e.g. $n=12$"},{key:"D",text:"the same statement"},{key:"E",text:"true only for even $n$"}],
    answer:"B", solution:"Converse: 'if divisible by 3 then divisible by 6', false since $9$ is divisible by 3 not 6." },
  { id:"tmua-mk7-p2-03", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The contrapositive of 'if $x>5$ then $x>0$' is:", options:[{key:"A",text:"if $x>0$ then $x>5$"},{key:"B",text:"if $x\\le0$ then $x\\le5$"},{key:"C",text:"if $x\\le5$ then $x\\le0$"},{key:"D",text:"if $x>5$ then $x\\le0$"},{key:"E",text:"if $x\\le0$ then $x>5$"}],
    answer:"B", solution:"Contrapositive $\\lnot Q\\Rightarrow\\lnot P$: 'if $x\\le0$ then $x\\le5$'." },
  { id:"tmua-mk7-p2-04", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:1, marks:1,
    question:"Which value disproves 'all odd numbers are prime'?", options:[{key:"A",text:"$3$"},{key:"B",text:"$9$"},{key:"C",text:"$5$"},{key:"D",text:"$7$"},{key:"E",text:"none"}],
    answer:"B", solution:"$9$ is odd but not prime — a counterexample." },
  { id:"tmua-mk7-p2-05", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The negation of 'for all integers $n$, $2n$ is even' is:", options:[{key:"A",text:"for all $n$, $2n$ is odd"},{key:"B",text:"there exists an integer $n$ with $2n$ odd"},{key:"C",text:"there exists an integer $n$ with $2n$ even"},{key:"D",text:"no integer exists"},{key:"E",text:"$2n=0$"}],
    answer:"B", solution:"Negate 'for all' to 'there exists' with the statement negated: some $n$ with $2n$ odd." },
  { id:"tmua-mk7-p2-06", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The negation of '$x>2$ and $x<8$' is:", options:[{key:"A",text:"$x<2$ and $x>8$"},{key:"B",text:"$x\\le2$ or $x\\ge8$"},{key:"C",text:"$x\\le2$ and $x\\ge8$"},{key:"D",text:"$2<x<8$"},{key:"E",text:"$x\\ne2$"}],
    answer:"B", solution:"not($A$ and $B$) $=$ not $A$ or not $B$: $x\\le2$ or $x\\ge8.$" },
  { id:"tmua-mk7-p2-07", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:1, marks:1,
    question:"If $A$ is true and $B$ is true, what is the truth value of '$A\\Rightarrow B$'?", options:[{key:"A",text:"true"},{key:"B",text:"false"},{key:"C",text:"undefined"},{key:"D",text:"depends on other facts"},{key:"E",text:"cannot be evaluated"}],
    answer:"A", solution:"An implication with true hypothesis and true conclusion is true." },
  { id:"tmua-mk7-p2-08", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Given $P\\Rightarrow Q$ is true and $P$ is false, what can be concluded about $Q$?", options:[{key:"A",text:"$Q$ is true"},{key:"B",text:"$Q$ is false"},{key:"C",text:"$P$ is true"},{key:"D",text:"nothing about $Q$"},{key:"E",text:"$P$ and $Q$ are equivalent"}],
    answer:"D", solution:"An implication with a false hypothesis places no restriction on its conclusion. $Q$ may be true or false." },
  { id:"tmua-mk7-p2-09", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:3, marks:1,
    question:"A student writes $(a+b)^2=a^2+b^2$. The error is that it:", options:[{key:"A",text:"omits the $2ab$ term"},{key:"B",text:"divides by zero"},{key:"C",text:"has no error"},{key:"D",text:"assumes $a=b$"},{key:"E",text:"omits an $a^2b^2$ term"}],
    answer:"A", solution:"$(a+b)^2=a^2+2ab+b^2$; the cross term $2ab$ is missing." },
  { id:"tmua-mk7-p2-10", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"'Every square is a rectangle, therefore every rectangle is a square.' The error is:", options:[{key:"A",text:"a false premise"},{key:"B",text:"assuming the converse"},{key:"C",text:"dividing by zero"},{key:"D",text:"proof by contradiction"},{key:"E",text:"a counterexample"}],
    answer:"B", solution:"Deducing $Q\\Rightarrow P$ from $P\\Rightarrow Q$ assumes the converse, which is invalid." },
  { id:"tmua-mk7-p2-11", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:1, marks:1,
    question:"Rejecting a universal claim by exhibiting the case $n=6$ is:", options:[{key:"A",text:"proof by contradiction"},{key:"B",text:"disproof by counterexample"},{key:"C",text:"proof by cases"},{key:"D",text:"direct proof"},{key:"E",text:"induction"}],
    answer:"B", solution:"One failing case disproves a 'for all' statement." },
  { id:"tmua-mk7-p2-12", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Proving a result by treating $x<0$, $x=0$ and $x>0$ separately is:", options:[{key:"A",text:"proof by contradiction"},{key:"B",text:"proof by cases"},{key:"C",text:"disproof by counterexample"},{key:"D",text:"a converse argument"},{key:"E",text:"circular reasoning"}],
    answer:"B", solution:"Exhaustive sign cases is proof by cases." },
  { id:"tmua-mk7-p2-13", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"The $n$-th term of $5,8,11,14,\\ldots$ is:", options:[{key:"A",text:"$3n+2$"},{key:"B",text:"$3n$"},{key:"C",text:"$2n+3$"},{key:"D",text:"$5n$"},{key:"E",text:"$n^2+4$"}],
    answer:"A", solution:"Arithmetic $a=5,d=3$: $u_n=5+(n-1)3=3n+2.$" },
  { id:"tmua-mk7-p2-14", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The condition '$x=2$' is ______ for '$x-2=0$'.", options:[{key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both necessary and sufficient"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"C", solution:"$x=2\\Leftrightarrow x-2=0$: the conditions are equivalent." },
  { id:"tmua-mk7-p2-15", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"Everyone in a group shakes hands once with everyone else, giving $21$ handshakes. How many people are there?", options:[{key:"A",text:"$6$"},{key:"B",text:"$7$"},{key:"C",text:"$8$"},{key:"D",text:"$21$"},{key:"E",text:"$9$"}],
    answer:"B", solution:"$\\binom{n}{2}=21\\Rightarrow n(n-1)=42\\Rightarrow n=7.$" },
  { id:"tmua-mk7-p2-16", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"For '$x\\ge0$', the condition '$x\\ge5$' is:", options:[{key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"B", solution:"$x\\ge5\\Rightarrow x\\ge0$ (sufficient); $x\\ge0$ does not force $x\\ge5$ (not necessary)." },
  { id:"tmua-mk7-p2-17", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The negation of 'some number is negative' is:", options:[{key:"A",text:"some number is positive"},{key:"B",text:"every number is non-negative"},{key:"C",text:"no number is non-negative"},{key:"D",text:"every number is negative"},{key:"E",text:"numbers do not exist"}],
    answer:"B", solution:"Negation of 'there exists $x$: negative' is 'for all $x$: not negative' — every number is $\\ge0.$" },
  { id:"tmua-mk7-p2-18", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:3, marks:1,
    question:"Which value shows 'if $n^2$ is divisible by $4$ then $n$ is divisible by $4$' is false?", options:[{key:"A",text:"$2$"},{key:"B",text:"$4$"},{key:"C",text:"$8$"},{key:"D",text:"$16$"},{key:"E",text:"none"}],
    answer:"A", solution:"$n=2$: $n^2=4$ is divisible by $4$, but $2$ is not divisible by $4$ — a counterexample." },
  { id:"tmua-mk7-p2-19", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"Using $2+4+\\cdots+2n=n(n+1)$, find $2+4+\\cdots+40$.", options:[{key:"A",text:"$420$"},{key:"B",text:"$400$"},{key:"C",text:"$440$"},{key:"D",text:"$210$"},{key:"E",text:"$380$"}],
    answer:"A", solution:"Last term $40=2n\\Rightarrow n=20$; sum $=20\\times21=420.$" },
  { id:"tmua-mk7-p2-20", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"For '$x^2=4$', the condition '$x=-2$' is:", options:[{key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"B", solution:"$x=-2\\Rightarrow x^2=4$ (sufficient); but $x=2$ also works, so not necessary." },
];
