// TMUA 模拟卷二 —— 全新原创题，与模拟卷一、练习题均不重复。
// 对标真实 TMUA：两卷各 20 题、各 75 分钟、五选一（A–E）、无负分、无计算器。
// Paper 1 = 数学应用；Paper 2 = 数学推理与逻辑。仅以真题题型/结构做校准，未复制真题。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const TMUA_MK2_P1: MCQQuestion[] = [
  { id: "tmua-mk2-p1-01", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "The quadratic $x^2+kx+16$ has a repeated root and $k>0$. Find $k$.",
    options: [ {key:"A",text:"$4$"},{key:"B",text:"$8$"},{key:"C",text:"$16$"},{key:"D",text:"$32$"},{key:"E",text:"$2$"} ],
    answer: "B", solution: "Discriminant $k^2-64=0\\Rightarrow k=\\pm8$; with $k>0$, $k=8.$" },
  { id: "tmua-mk2-p1-02", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 1, marks: 1,
    question: "Simplify $\\dfrac{(2^3)^2}{2^4}$.",
    options: [ {key:"A",text:"$2$"},{key:"B",text:"$4$"},{key:"C",text:"$8$"},{key:"D",text:"$16$"},{key:"E",text:"$1$"} ],
    answer: "B", solution: "$\\dfrac{2^6}{2^4}=2^2=4.$" },
  { id: "tmua-mk2-p1-03", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "Simplify $\\sqrt{50}-\\sqrt{8}$.",
    options: [ {key:"A",text:"$3\\sqrt2$"},{key:"B",text:"$2\\sqrt2$"},{key:"C",text:"$\\sqrt{42}$"},{key:"D",text:"$7\\sqrt2$"},{key:"E",text:"$\\sqrt2$"} ],
    answer: "A", solution: "$5\\sqrt2-2\\sqrt2=3\\sqrt2.$" },
  { id: "tmua-mk2-p1-04", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 1, marks: 1,
    question: "Find $1+2+3+\\cdots+50$.",
    options: [ {key:"A",text:"$1225$"},{key:"B",text:"$1275$"},{key:"C",text:"$2550$"},{key:"D",text:"$1250$"},{key:"E",text:"$1300$"} ],
    answer: "B", solution: "$\\dfrac{50\\times51}{2}=1275.$" },
  { id: "tmua-mk2-p1-05", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "Find the sum $3+6+12+\\cdots$ to $6$ terms.",
    options: [ {key:"A",text:"$189$"},{key:"B",text:"$192$"},{key:"C",text:"$96$"},{key:"D",text:"$186$"},{key:"E",text:"$93$"} ],
    answer: "A", solution: "Geometric, $a=3,r=2$: $S_6=\\dfrac{3(2^6-1)}{2-1}=3\\times63=189.$" },
  { id: "tmua-mk2-p1-06", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 1, marks: 1,
    question: "The midpoint of $(2,3)$ and $(8,11)$ is:",
    options: [ {key:"A",text:"$(5,7)$"},{key:"B",text:"$(4,6)$"},{key:"C",text:"$(6,8)$"},{key:"D",text:"$(5,8)$"},{key:"E",text:"$(3,4)$"} ],
    answer: "A", solution: "$\\left(\\tfrac{2+8}{2},\\tfrac{3+11}{2}\\right)=(5,7).$" },
  { id: "tmua-mk2-p1-07", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 2, marks: 1,
    question: "The circle $x^2+y^2-4x+6y-12=0$ has radius:",
    options: [ {key:"A",text:"$4$"},{key:"B",text:"$5$"},{key:"C",text:"$6$"},{key:"D",text:"$\\sqrt{12}$"},{key:"E",text:"$25$"} ],
    answer: "B", solution: "Complete the square: $(x-2)^2+(y+3)^2=12+4+9=25$, so $r=5.$" },
  { id: "tmua-mk2-p1-08", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 1, marks: 1,
    question: "Evaluate $\\cos 120^\\circ$.",
    options: [ {key:"A",text:"$\\tfrac12$"},{key:"B",text:"$-\\tfrac12$"},{key:"C",text:"$\\tfrac{\\sqrt3}{2}$"},{key:"D",text:"$-\\tfrac{\\sqrt3}{2}$"},{key:"E",text:"$0$"} ],
    answer: "B", solution: "$\\cos120^\\circ=-\\cos60^\\circ=-\\tfrac12.$" },
  { id: "tmua-mk2-p1-09", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 2, marks: 1,
    question: "If $\\sin\\theta=\\tfrac35$ and $\\theta$ is acute, then $\\cos\\theta=$",
    options: [ {key:"A",text:"$\\tfrac45$"},{key:"B",text:"$\\tfrac35$"},{key:"C",text:"$\\tfrac54$"},{key:"D",text:"$\\tfrac25$"},{key:"E",text:"$\\tfrac15$"} ],
    answer: "A", solution: "$\\cos\\theta=\\sqrt{1-\\tfrac{9}{25}}=\\sqrt{\\tfrac{16}{25}}=\\tfrac45.$" },
  { id: "tmua-mk2-p1-10", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "Solve $5^{x}=\\dfrac{1}{25}$.",
    options: [ {key:"A",text:"$x=-2$"},{key:"B",text:"$x=2$"},{key:"C",text:"$x=-1$"},{key:"D",text:"$x=\\tfrac12$"},{key:"E",text:"$x=5$"} ],
    answer: "A", solution: "$\\dfrac1{25}=5^{-2}$, so $x=-2.$" },
  { id: "tmua-mk2-p1-11", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 1, marks: 1,
    question: "Evaluate $\\log_2\\tfrac18$.",
    options: [ {key:"A",text:"$3$"},{key:"B",text:"$-3$"},{key:"C",text:"$\\tfrac18$"},{key:"D",text:"$-\\tfrac13$"},{key:"E",text:"$8$"} ],
    answer: "B", solution: "$\\tfrac18=2^{-3}$, so $\\log_2\\tfrac18=-3.$" },
  { id: "tmua-mk2-p1-12", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 3, marks: 1,
    question: "Solve $\\log_{10}x+\\log_{10}(x-3)=1$.",
    options: [ {key:"A",text:"$x=5$"},{key:"B",text:"$x=-2$"},{key:"C",text:"$x=5$ or $x=-2$"},{key:"D",text:"$x=10$"},{key:"E",text:"$x=2$"} ],
    answer: "A", solution: "$x(x-3)=10\\Rightarrow x^2-3x-10=0\\Rightarrow(x-5)(x+2)=0$. Only $x=5$ keeps both logs defined." },
  { id: "tmua-mk2-p1-13", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 2, marks: 1,
    question: "Find the derivative of $2x^3-3x$ at $x=2$.",
    options: [ {key:"A",text:"$18$"},{key:"B",text:"$21$"},{key:"C",text:"$24$"},{key:"D",text:"$9$"},{key:"E",text:"$15$"} ],
    answer: "B", solution: "$\\dfrac{d}{dx}=6x^2-3$; at $x=2$: $24-3=21.$" },
  { id: "tmua-mk2-p1-14", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 2, marks: 1,
    question: "The gradient of $y=x^2+2x$ is zero at $x=$",
    options: [ {key:"A",text:"$0$"},{key:"B",text:"$-1$"},{key:"C",text:"$1$"},{key:"D",text:"$-2$"},{key:"E",text:"$2$"} ],
    answer: "B", solution: "$y'=2x+2=0\\Rightarrow x=-1.$" },
  { id: "tmua-mk2-p1-15", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 2, marks: 1,
    question: "Evaluate $\\displaystyle\\int_0^1(3x^2+2x)\\,\\mathrm{d}x$.",
    options: [ {key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$1$"},{key:"D",text:"$\\tfrac52$"},{key:"E",text:"$4$"} ],
    answer: "A", solution: "$[x^3+x^2]_0^1=1+1=2.$" },
  { id: "tmua-mk2-p1-16", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 3, marks: 1,
    question: "Find the area enclosed between $y=x^2$ and the line $y=4$.",
    options: [ {key:"A",text:"$\\tfrac{16}{3}$"},{key:"B",text:"$\\tfrac{32}{3}$"},{key:"C",text:"$8$"},{key:"D",text:"$16$"},{key:"E",text:"$\\tfrac{20}{3}$"} ],
    answer: "B", solution: "They meet at $x=\\pm2$. Area $=\\int_{-2}^{2}(4-x^2)\\,dx=\\left[4x-\\tfrac{x^3}{3}\\right]_{-2}^{2}=\\tfrac{32}{3}.$" },
  { id: "tmua-mk2-p1-17", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "The graph of $y=f(x)$ is transformed to $y=2f(x)$. This is a:",
    options: [ {key:"A",text:"vertical stretch, factor 2"},{key:"B",text:"horizontal stretch, factor 2"},{key:"C",text:"translation up 2"},{key:"D",text:"reflection in the $x$-axis"},{key:"E",text:"horizontal stretch, factor $\\tfrac12$"} ],
    answer: "A", solution: "Multiplying the output by 2 stretches the graph vertically by a factor of 2." },
  { id: "tmua-mk2-p1-18", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "Given $f(x)=x^2$ and $g(x)=x-1$, find $f(g(4))$.",
    options: [ {key:"A",text:"$9$"},{key:"B",text:"$15$"},{key:"C",text:"$16$"},{key:"D",text:"$3$"},{key:"E",text:"$25$"} ],
    answer: "A", solution: "$g(4)=3$, then $f(3)=9.$" },
  { id: "tmua-mk2-p1-19", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "Solve $x^2>9$.",
    options: [ {key:"A",text:"$-3<x<3$"},{key:"B",text:"$x<-3$ or $x>3$"},{key:"C",text:"$x>3$"},{key:"D",text:"$x>9$"},{key:"E",text:"$x<3$"} ],
    answer: "B", solution: "$x^2>9\\Leftrightarrow|x|>3\\Leftrightarrow x<-3$ or $x>3.$" },
  { id: "tmua-mk2-p1-20", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 3, marks: 1,
    question: "The coefficient of $x^3$ in the expansion of $(2+x)^4$ is:",
    options: [ {key:"A",text:"$4$"},{key:"B",text:"$8$"},{key:"C",text:"$12$"},{key:"D",text:"$16$"},{key:"E",text:"$6$"} ],
    answer: "B", solution: "$\\binom{4}{3}(2)^{1}(x)^3=4\\times2=8$, so the coefficient is $8.$" },
];

export const TMUA_MK2_P2: MCQQuestion[] = [
  { id: "tmua-mk2-p2-01", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "For an integer to be divisible by $12$, being divisible by $4$ is:",
    options: [ {key:"A",text:"sufficient but not necessary"},{key:"B",text:"necessary but not sufficient"},{key:"C",text:"both"},{key:"D",text:"neither"},{key:"E",text:"undecidable"} ],
    answer: "B", solution: "Divisible by 12 $\\Rightarrow$ divisible by 4 (necessary), but 8 is divisible by 4 yet not 12 (not sufficient)." },
  { id: "tmua-mk2-p2-02", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "The converse of 'if $x=3$ then $x^2=9$' is:",
    options: [ {key:"A",text:"'if $x^2=9$ then $x=3$'; it is true"},{key:"B",text:"'if $x^2=9$ then $x=3$'; it is false"},{key:"C",text:"'if $x\\ne3$ then $x^2\\ne9$'; true"},{key:"D",text:"'if $x=3$ then $x^2\\ne9$'; false"},{key:"E",text:"the converse is identical"} ],
    answer: "B", solution: "Converse swaps the parts; it is false because $x=-3$ also gives $x^2=9.$" },
  { id: "tmua-mk2-p2-03", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "The contrapositive of 'if a shape is a square then it has four equal sides' is:",
    options: [ {key:"A",text:"if a shape has four equal sides then it is a square"},{key:"B",text:"if a shape does not have four equal sides then it is not a square"},{key:"C",text:"if a shape is not a square then it does not have four equal sides"},{key:"D",text:"if a shape is a square then it is a rectangle"},{key:"E",text:"if a shape has four equal sides then it is not a square"} ],
    answer: "B", solution: "Contrapositive: $\\lnot Q\\Rightarrow\\lnot P$ — 'if not four equal sides then not a square'." },
  { id: "tmua-mk2-p2-04", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 1, marks: 1,
    question: "Which value disproves 'all prime numbers are odd'?",
    options: [ {key:"A",text:"$1$"},{key:"B",text:"$2$"},{key:"C",text:"$9$"},{key:"D",text:"$3$"},{key:"E",text:"$7$"} ],
    answer: "B", solution: "$2$ is prime and even, giving the required counterexample." },
  { id: "tmua-mk2-p2-05", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "The negation of 'for all real $x$, $x^2>0$' is:",
    options: [ {key:"A",text:"for all real $x$, $x^2\\le0$"},{key:"B",text:"there exists a real $x$ with $x^2\\le0$"},{key:"C",text:"there exists a real $x$ with $x^2>0$"},{key:"D",text:"for all real $x$, $x^2<0$"},{key:"E",text:"$x^2=0$ always"} ],
    answer: "B", solution: "Negate 'for all' to 'there exists' and negate the inner statement: $x^2\\le0$ (true at $x=0$)." },
  { id: "tmua-mk2-p2-06", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "The negation of '$a>0$ or $b>0$' is:",
    options: [ {key:"A",text:"$a<0$ or $b<0$"},{key:"B",text:"$a\\le0$ and $b\\le0$"},{key:"C",text:"$a\\le0$ or $b\\le0$"},{key:"D",text:"$a>0$ and $b>0$"},{key:"E",text:"$a=0$ and $b=0$"} ],
    answer: "B", solution: "By De Morgan, not($A$ or $B$) $=$ (not $A$) and (not $B$): $a\\le0$ and $b\\le0.$" },
  { id: "tmua-mk2-p2-07", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 1, marks: 1,
    question: "Under the TMUA convention for 'or', is '$A$ or $B$' true when both $A$ and $B$ are true?",
    options: [ {key:"A",text:"yes, because 'or' is inclusive"},{key:"B",text:"no, because 'or' is exclusive"},{key:"C",text:"only if $A=B$"},{key:"D",text:"it is undefined"},{key:"E",text:"only if one is false"} ],
    answer: "A", solution: "In the TMUA, 'or' is the inclusive or, so it is true when at least one — including both — holds." },
  { id: "tmua-mk2-p2-08", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 1, marks: 1,
    question: "Given $P\\Rightarrow Q$ and $Q\\Rightarrow R$ are true and $P$ is true, which must be true?",
    options: [ {key:"A",text:"only $Q$"},{key:"B",text:"$R$"},{key:"C",text:"neither"},{key:"D",text:"$\\lnot R$"},{key:"E",text:"$\\lnot P$"} ],
    answer: "B", solution: "Chaining: $P$ true $\\Rightarrow Q$ true $\\Rightarrow R$ true." },
  { id: "tmua-mk2-p2-09", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 3, marks: 1,
    question: "'From $a^2=ab$, dividing both sides by $a$ gives $a=b$.' The error is:",
    options: [ {key:"A",text:"there is no error"},{key:"B",text:"dividing by $a$, which may be zero"},{key:"C",text:"squaring both sides"},{key:"D",text:"$a^2\\ne ab$ in general"},{key:"E",text:"$a=b$ is impossible"} ],
    answer: "B", solution: "If $a=0$ the division is invalid; then $a^2=ab$ holds for any $b$. Cancelling $a$ requires $a\\ne0.$" },
  { id: "tmua-mk2-p2-10", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "'Since $x^2=y^2$, it follows that $x=y$.' The flaw is that it:",
    options: [ {key:"A",text:"ignores the possibility $x=-y$"},{key:"B",text:"divides by zero"},{key:"C",text:"assumes $x,y>0$ correctly"},{key:"D",text:"has no flaw"},{key:"E",text:"uses the contrapositive"} ],
    answer: "A", solution: "$x^2=y^2\\Rightarrow x=\\pm y$; the argument overlooks $x=-y.$" },
  { id: "tmua-mk2-p2-11", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 1, marks: 1,
    question: "Proving a statement by assuming its negation and reaching an absurdity is:",
    options: [ {key:"A",text:"proof by contradiction"},{key:"B",text:"proof by cases"},{key:"C",text:"direct proof"},{key:"D",text:"disproof by counterexample"},{key:"E",text:"proof by construction"} ],
    answer: "A", solution: "This is the definition of proof by contradiction." },
  { id: "tmua-mk2-p2-12", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "Establishing a result for integers by checking $n\\le0$ and $n\\ge1$ separately is:",
    options: [ {key:"A",text:"proof by contradiction"},{key:"B",text:"proof by cases"},{key:"C",text:"disproof by counterexample"},{key:"D",text:"a converse argument"},{key:"E",text:"circular reasoning"} ],
    answer: "B", solution: "Dividing the domain into exhaustive cases and proving each is proof by cases." },
  { id: "tmua-mk2-p2-13", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 3, marks: 1,
    question: "The sequence $2, 5, 10, 17, \\ldots$ has $n$-th term:",
    options: [ {key:"A",text:"$3n-1$"},{key:"B",text:"$n^2+1$"},{key:"C",text:"$2n^2$"},{key:"D",text:"$n^2+n$"},{key:"E",text:"$2^n$"} ],
    answer: "B", solution: "The terms are $1^2+1,2^2+1,3^2+1,4^2+1,\\ldots$, so the $n$-th term is $n^2+1.$" },
  { id: "tmua-mk2-p2-14", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 3, marks: 1,
    question: "Given $A\\Rightarrow B$ and $B\\Rightarrow C$ are true, and $C$ is false, what follows?",
    options: [ {key:"A",text:"$A$ is true"},{key:"B",text:"$A$ is false"},{key:"C",text:"$B$ is true"},{key:"D",text:"nothing"},{key:"E",text:"$C$ is true"} ],
    answer: "B", solution: "Contrapositive chain: $\\lnot C\\Rightarrow\\lnot B\\Rightarrow\\lnot A$; so $A$ is false." },
  { id: "tmua-mk2-p2-15", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "The condition '$x^2=1$' is ______ for '$|x|=1$'.",
    options: [ {key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both necessary and sufficient"},{key:"D",text:"neither"},{key:"E",text:"undecidable"} ],
    answer: "C", solution: "$x^2=1\\Leftrightarrow x=\\pm1\\Leftrightarrow|x|=1$; the conditions are equivalent." },
  { id: "tmua-mk2-p2-16", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 2, marks: 1,
    question: "In a group where everyone shakes hands with everyone else exactly once, there are $15$ handshakes. How many people are there?",
    options: [ {key:"A",text:"$5$"},{key:"B",text:"$6$"},{key:"C",text:"$7$"},{key:"D",text:"$8$"},{key:"E",text:"$15$"} ],
    answer: "B", solution: "$\\binom{n}{2}=15\\Rightarrow\\dfrac{n(n-1)}{2}=15\\Rightarrow n(n-1)=30\\Rightarrow n=6.$" },
  { id: "tmua-mk2-p2-17", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "For a quadrilateral to be a rectangle, having four right angles is:",
    options: [ {key:"A",text:"sufficient but not necessary"},{key:"B",text:"necessary but not sufficient"},{key:"C",text:"both necessary and sufficient"},{key:"D",text:"neither"},{key:"E",text:"undecidable"} ],
    answer: "C", solution: "A quadrilateral is a rectangle iff it has four right angles, so the condition is both necessary and sufficient." },
  { id: "tmua-mk2-p2-18", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "Is 'for all integers $n$, if $n^2$ is even then $n$ is even' true or false?",
    options: [ {key:"A",text:"true"},{key:"B",text:"false, counterexample $n=3$"},{key:"C",text:"false, counterexample $n=2$"},{key:"D",text:"cannot be determined"},{key:"E",text:"true only for $n>0$"} ],
    answer: "A", solution: "True. Contrapositive: if $n$ is odd then $n^2$ is odd, which is easily verified, so the statement holds." },
  { id: "tmua-mk2-p2-19", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 2, marks: 1,
    question: "Using $1+3+5+\\cdots+(2n-1)=n^2$, find $1+3+5+\\cdots+99$.",
    options: [ {key:"A",text:"$2500$"},{key:"B",text:"$4950$"},{key:"C",text:"$9801$"},{key:"D",text:"$5000$"},{key:"E",text:"$9900$"} ],
    answer: "A", solution: "The last term $99=2n-1\\Rightarrow n=50$, so the sum is $50^2=2500.$" },
  { id: "tmua-mk2-p2-20", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "The condition '$x>5$' is ______ for '$x>3$'.",
    options: [ {key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both necessary and sufficient"},{key:"D",text:"neither"},{key:"E",text:"undecidable"} ],
    answer: "B", solution: "$x>5\\Rightarrow x>3$ (sufficient), but $x>3$ does not force $x>5$ (e.g. $x=4$), so not necessary." },
];
