import type { MCQOption, MCQQuestion } from "@/lib/tests/questions/types";

const COMBINATION_OPTIONS: MCQOption[] = [
  { key: "A", text: "I, II and III" },
  { key: "B", text: "I and II only" },
  { key: "C", text: "I and III only" },
  { key: "D", text: "I only" },
  { key: "E", text: "II and III only" },
  { key: "F", text: "II only" },
  { key: "G", text: "III only" },
  { key: "H", text: "None of I, II and III" },
];

export const TMUA_CALIBRATION_1_P1: MCQQuestion[] = [
  {
    id: "tmua-cal1-p1-01", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "The roots of $x^2-(k+1)x+k=0$ are integers whose difference is $3$. What are the possible values of $k$?",
    options: [
      { key: "A", text: "$4$ only" }, { key: "B", text: "$-2$ only" },
      { key: "C", text: "$4$ and $-2$" }, { key: "D", text: "$3$ and $-3$" },
      { key: "E", text: "$2$ and $-4$" }, { key: "F", text: "There are no such values" },
    ],
    answer: "C",
    solution: "The quadratic factors as $(x-1)(x-k)$. Its roots are $1$ and $k$, so $|k-1|=3$. Hence $k=4$ or $k=-2$.",
  },
  {
    id: "tmua-cal1-p1-02", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 1, marks: 1,
    question: "For $x>0$, what is the least possible value of $x+\\dfrac9x$?",
    options: [
      { key: "A", text: "$3$" }, { key: "B", text: "$6$" }, { key: "C", text: "$9$" },
      { key: "D", text: "$10$" }, { key: "E", text: "There is no least value" },
    ],
    answer: "B",
    solution: "By AM-GM, $x+9/x\\ge 2\\sqrt{9}=6$, with equality when $x=9/x$, i.e. $x=3$.",
  },
  {
    id: "tmua-cal1-p1-03", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 3, marks: 1,
    question: "The sum of the first three terms of a positive geometric sequence is $21$, and the sum of the next three terms is $168$. What is the sixth term?",
    options: [
      { key: "A", text: "$24$" }, { key: "B", text: "$48$" }, { key: "C", text: "$64$" },
      { key: "D", text: "$84$" }, { key: "E", text: "$96$" }, { key: "F", text: "$192$" },
    ],
    answer: "E",
    solution: "The second block of three terms is $r^3$ times the first, so $r^3=168/21=8$ and $r=2$. Then $a(1+2+4)=21$, giving $a=3$. The sixth term is $ar^5=3\\cdot32=96$.",
  },
  {
    id: "tmua-cal1-p1-04", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "Solve $\\log_2(x-1)+\\log_2(x-3)=3$.",
    options: [
      { key: "A", text: "$x=-1$" }, { key: "B", text: "$x=1$" }, { key: "C", text: "$x=3$" },
      { key: "D", text: "$x=5$" }, { key: "E", text: "$x=-1$ or $x=5$" },
    ],
    answer: "D",
    solution: "The domain requires $x>3$. Combining logs gives $(x-1)(x-3)=8$, so $x^2-4x-5=0$ and $x=5$ or $-1$. Only $x=5$ is in the domain.",
  },
  {
    id: "tmua-cal1-p1-05", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 1, marks: 1,
    question: "What is the coefficient of $x^3$ in $(1+2x)^5$?",
    options: [
      { key: "A", text: "$10$" }, { key: "B", text: "$20$" }, { key: "C", text: "$40$" },
      { key: "D", text: "$80$" }, { key: "E", text: "$160$" }, { key: "F", text: "$240$" },
    ],
    answer: "D",
    solution: "The $x^3$ term is $\\binom53(2x)^3=10\\cdot8x^3$, so the coefficient is $80$.",
  },
  {
    id: "tmua-cal1-p1-06", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 3, marks: 1,
    question: "For which real values of $k$ is $x^2-2kx+k+3>0$ for every real $x$?",
    options: [
      { key: "A", text: "$k<\\dfrac{1-\\sqrt{13}}2$" },
      { key: "B", text: "$k>\\dfrac{1+\\sqrt{13}}2$" },
      { key: "C", text: "$\\dfrac{1-\\sqrt{13}}2<k<\\dfrac{1+\\sqrt{13}}2$" },
      { key: "D", text: "$\\dfrac{1-\\sqrt{13}}2\\le k\\le\\dfrac{1+\\sqrt{13}}2$" },
      { key: "E", text: "$k<0$" }, { key: "F", text: "$k>0$" },
    ],
    answer: "C",
    solution: "The leading coefficient is positive, so strict positivity for all $x$ requires discriminant $<0$. Thus $4k^2-4(k+3)<0$, or $k^2-k-3<0$. This holds strictly between its roots $(1\\pm\\sqrt{13})/2$.",
  },
  {
    id: "tmua-cal1-p1-07", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 2, marks: 1,
    question: "How many solutions does $2\\cos^2x=1$ have in the interval $0\\le x<2\\pi$?",
    options: [
      { key: "A", text: "$1$" }, { key: "B", text: "$2$" }, { key: "C", text: "$3$" },
      { key: "D", text: "$4$" }, { key: "E", text: "$8$" },
    ],
    answer: "D",
    solution: "$\\cos x=\\pm1/\\sqrt2$. In one full period these occur at $\\pi/4,3\\pi/4,5\\pi/4,7\\pi/4$, giving four solutions.",
  },
  {
    id: "tmua-cal1-p1-08", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 3, marks: 1,
    question: "The line $y=x+c$, where $c>0$, is tangent to the circle $x^2+y^2=25$. What is $c$?",
    options: [
      { key: "A", text: "$5$" }, { key: "B", text: "$5\\sqrt2$" }, { key: "C", text: "$10$" },
      { key: "D", text: "$\\dfrac5{\\sqrt2}$" }, { key: "E", text: "$25$" }, { key: "F", text: "$10\\sqrt2$" },
    ],
    answer: "B",
    solution: "Write the line as $x-y+c=0$. Its distance from the origin is $c/\\sqrt2$. Tangency requires this to equal the radius $5$, so $c=5\\sqrt2$.",
  },
  {
    id: "tmua-cal1-p1-09", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 2, marks: 1,
    question: "The vertices of a triangle are $(0,0)$, $(6,0)$ and $(2,4)$. What is the perpendicular distance from its centroid to the line through $(6,0)$ and $(2,4)$?",
    options: [
      { key: "A", text: "$1$" }, { key: "B", text: "$\\sqrt2$" }, { key: "C", text: "$2$" },
      { key: "D", text: "$2\\sqrt2$" }, { key: "E", text: "$\\dfrac4{\\sqrt2}$" },
    ],
    answer: "B",
    solution: "The centroid is $(8/3,4/3)$. The line through the last two vertices is $x+y=6$. The distance is $|8/3+4/3-6|/\\sqrt2=2/\\sqrt2=\\sqrt2$.",
  },
  {
    id: "tmua-cal1-p1-10", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "How many points of intersection do the graphs $y=|x^2-4|$ and $y=3$ have?",
    options: [
      { key: "A", text: "$0$" }, { key: "B", text: "$1$" }, { key: "C", text: "$2$" },
      { key: "D", text: "$3$" }, { key: "E", text: "$4$" }, { key: "F", text: "$5$" }, { key: "G", text: "$6$" },
    ],
    answer: "E",
    solution: "$|x^2-4|=3$ gives $x^2-4=3$ or $x^2-4=-3$. Hence $x=\\pm\\sqrt7$ or $x=\\pm1$, four distinct values.",
  },
  {
    id: "tmua-cal1-p1-11", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 3, marks: 1,
    question: "For how many integer values of $a$ does the equation $x^3-3x=a$ have three distinct real roots?",
    options: [
      { key: "A", text: "$1$" }, { key: "B", text: "$2$" }, { key: "C", text: "$3$" },
      { key: "D", text: "$4$" }, { key: "E", text: "$5$" }, { key: "F", text: "Infinitely many" },
    ],
    answer: "C",
    solution: "For $f(x)=x^3-3x$, stationary points occur at $x=\\pm1$, with values $2$ and $-2$. A horizontal line $y=a$ meets the curve three times exactly when $-2<a<2$. The integer values are $-1,0,1$, so there are three.",
  },
  {
    id: "tmua-cal1-p1-12", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 2, marks: 1,
    question: "The tangent to $y=x^2+2x$ at $x=1$ meets the $x$-axis at which value of $x$?",
    options: [
      { key: "A", text: "$-1$" }, { key: "B", text: "$-\\dfrac14$" }, { key: "C", text: "$0$" },
      { key: "D", text: "$\\dfrac14$" }, { key: "E", text: "$1$" },
    ],
    answer: "D",
    solution: "At $x=1$, the point is $(1,3)$ and the gradient is $2x+2=4$. The tangent is $y-3=4(x-1)$, so $y=4x-1$. Setting $y=0$ gives $x=1/4$.",
  },
  {
    id: "tmua-cal1-p1-13", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 2, marks: 1,
    question: "Evaluate $\\displaystyle\\\int_0^3 |2x-2|\\,\\mathrm dx$.",
    options: [
      { key: "A", text: "$3$" }, { key: "B", text: "$4$" }, { key: "C", text: "$5$" },
      { key: "D", text: "$6$" }, { key: "E", text: "$7$" }, { key: "F", text: "$9$" },
    ],
    answer: "C",
    solution: "The graph crosses the axis at $x=1$. From $0$ to $1$ the triangular area is $1$, and from $1$ to $3$ it is $\\tfrac12\\cdot2\\cdot4=4$. The total is $5$.",
  },
  {
    id: "tmua-cal1-p1-14", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 2, marks: 1,
    question: "A rectangle lies in the first quadrant with two sides on the coordinate axes and its opposite vertex on the line $x+2y=12$. What is its greatest possible area?",
    options: [
      { key: "A", text: "$12$" }, { key: "B", text: "$16$" }, { key: "C", text: "$18$" },
      { key: "D", text: "$24$" }, { key: "E", text: "$36$" },
    ],
    answer: "C",
    solution: "$y=(12-x)/2$, so the area is $A=x(12-x)/2=18-(x-6)^2/2$. Its maximum is $18$, attained at $(x,y)=(6,3)$.",
  },
  {
    id: "tmua-cal1-p1-15", type: "mcq", testId: "tmua", topicId: "tmua-stats", difficulty: 2, marks: 1,
    question: "Two fair six-sided dice are rolled. Given that their sum is even, what is the probability that both dice show odd numbers?",
    options: [
      { key: "A", text: "$\\dfrac14$" }, { key: "B", text: "$\\dfrac13$" }, { key: "C", text: "$\\dfrac12$" },
      { key: "D", text: "$\\dfrac23$" }, { key: "E", text: "$\\dfrac34$" }, { key: "F", text: "$\\dfrac56$" },
    ],
    answer: "C",
    solution: "An even sum occurs when both dice have the same parity: $9$ odd-odd outcomes and $9$ even-even outcomes. Thus the conditional probability is $9/18=1/2$.",
  },
  {
    id: "tmua-cal1-p1-16", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 3, marks: 1,
    question: "Three positions are selected from six positions arranged in a row. No two selected positions may be adjacent. How many selections are possible?",
    options: [
      { key: "A", text: "$3$" }, { key: "B", text: "$4$" }, { key: "C", text: "$6$" },
      { key: "D", text: "$8$" }, { key: "E", text: "$10$" }, { key: "F", text: "$20$" },
    ],
    answer: "B",
    solution: "If the selected positions are $a<b<c$, set $u=a$, $v=b-1$, $w=c-2$. Then $1\\le u<v<w\\le4$, so the count is $\\binom43=4$. The selections are $135,136,146,246$.",
  },
  {
    id: "tmua-cal1-p1-17", type: "mcq", testId: "tmua", topicId: "tmua-number", difficulty: 2, marks: 1,
    question: "What is the remainder when $2^{2026}$ is divided by $7$?",
    options: [
      { key: "A", text: "$0$" }, { key: "B", text: "$1$" }, { key: "C", text: "$2$" },
      { key: "D", text: "$3$" }, { key: "E", text: "$4$" },
    ],
    answer: "C",
    solution: "$2^3\\equiv1\\\pmod7$, and $2026\\equiv1\\\pmod3$. Therefore $2^{2026}\\equiv2^1\\equiv2\\\pmod7$.",
  },
  {
    id: "tmua-cal1-p1-18", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 2, marks: 1,
    question: "How many four-digit numbers can be formed from the digits $1,2,3,4,5$ without repetition and are divisible by $5$?",
    options: [
      { key: "A", text: "$12$" }, { key: "B", text: "$18$" }, { key: "C", text: "$20$" },
      { key: "D", text: "$24$" }, { key: "E", text: "$36$" }, { key: "F", text: "$48$" },
    ],
    answer: "D",
    solution: "The final digit must be $5$. The first three positions are filled by an ordered selection of three of the remaining four digits: $4\\cdot3\\cdot2=24$.",
  },
  {
    id: "tmua-cal1-p1-19", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 2, marks: 1,
    question: "Two sides of a triangle have lengths $5$ and $7$, and the included angle is $60^\\circ$. What is the length of the third side?",
    options: [
      { key: "A", text: "$\\sqrt{24}$" }, { key: "B", text: "$\\sqrt{39}$" }, { key: "C", text: "$\\sqrt{49}$" },
      { key: "D", text: "$\\sqrt{74}$" }, { key: "E", text: "$6$" }, { key: "F", text: "$8$" },
    ],
    answer: "B",
    solution: "By the cosine rule, $c^2=5^2+7^2-2\\cdot5\\cdot7\\cos60^\\circ=25+49-35=39$. Hence $c=\\sqrt{39}$.",
  },
  {
    id: "tmua-cal1-p1-20", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 3, marks: 1,
    question: "For which positive value of $k$ does the equation $|x^2-4|=k$ have exactly three distinct real solutions?",
    options: [
      { key: "A", text: "$k=1$" }, { key: "B", text: "$k=2$" }, { key: "C", text: "$k=3$" },
      { key: "D", text: "$k=4$" }, { key: "E", text: "$k=5$" }, { key: "F", text: "$0<k<4$" },
      { key: "G", text: "$k>4$" }, { key: "H", text: "No positive value of $k$" },
    ],
    answer: "D",
    solution: "The branch $x^2=4+k$ always gives two roots. The branch $x^2=4-k$ gives two further roots for $0<k<4$, one root when $k=4$, and none when $k>4$. Exactly three roots therefore occur only at $k=4$.",
  },
];

export const TMUA_CALIBRATION_1_P2: MCQQuestion[] = [
  {
    id: "tmua-cal1-p2-01", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "Let $n$ be an integer and let $P$ be the statement '$n$ is divisible by $12$'. Consider the following statements.\n\nI. Divisibility by $6$ is necessary for $P$.\n\nII. Divisibility by $4$ is sufficient for $P$.\n\nIII. Divisibility by both $3$ and $4$ is necessary and sufficient for $P$.\n\nWhich statements are true?",
    options: COMBINATION_OPTIONS,
    answer: "C",
    solution: "I is true because every multiple of $12$ is a multiple of $6$. II is false, since $8$ is divisible by $4$ but not $12$. III is true because $3$ and $4$ are coprime, so divisibility by both is equivalent to divisibility by $12$. Thus I and III only are true.",
  },
  {
    id: "tmua-cal1-p2-02", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "For a real number $x$, let $P$ mean $x>2$, $Q$ mean $x^2>4$, and $R$ mean $|x|>2$.\n\nI. $P$ is sufficient for $Q$.\n\nII. $Q$ is sufficient for $P$.\n\nIII. $Q$ is necessary and sufficient for $R$.\n\nWhich statements are true?",
    options: COMBINATION_OPTIONS,
    answer: "C",
    solution: "I is true. II is false because $x=-3$ satisfies $Q$ but not $P$. III is true because $x^2>4$ is equivalent to $|x|>2$. Therefore I and III only are true.",
  },
  {
    id: "tmua-cal1-p2-03", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "A student argues: '$x^2\\ge x$ for every real $x$, because $x^2-x=x(x-1)$ and a product of two real numbers is non-negative.' What is the flaw?",
    options: [
      { key: "A", text: "The factorisation of $x^2-x$ is incorrect" },
      { key: "B", text: "A product of two real numbers need not be non-negative" },
      { key: "C", text: "The argument assumes that $x$ is an integer" },
      { key: "D", text: "The inequality should be strict" },
      { key: "E", text: "The argument divides by a quantity that may be zero" },
      { key: "F", text: "There is no flaw" },
    ],
    answer: "B",
    solution: "The factorisation is correct, but the sign claim is false: when $0<x<1$, $x>0$ and $x-1<0$, so $x(x-1)<0$. For example, $x=1/2$ gives $x^2<x$.",
  },
  {
    id: "tmua-cal1-p2-04", type: "mcq", testId: "tmua", topicId: "tmua-number", difficulty: 3, marks: 1,
    question: "Let $n$ be an integer.\n\nI. If $8$ divides $n^2$, then $4$ divides $n$.\n\nII. If $4$ divides $n$, then $8$ divides $n^2$.\n\nIII. $8$ divides $n^2$ if and only if $8$ divides $n$.\n\nWhich statements are true?",
    options: COMBINATION_OPTIONS,
    answer: "B",
    solution: "For I, $8\\mid n^2$ forces the exponent of $2$ in $n$ to be at least $2$, so $4\\mid n$. II is immediate since $n=4m$ gives $n^2=16m^2$. III is false: $n=4$ has $8\\mid n^2$ but $8\\nmid n$. Thus I and II only are true.",
  },
  {
    id: "tmua-cal1-p2-05", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 3, marks: 1,
    question: "Which statement is the negation of 'for every real number $x$, there exists an integer $n$ such that $n>x$'?",
    options: [
      { key: "A", text: "For every real $x$, every integer $n$ satisfies $n\\le x$" },
      { key: "B", text: "There exists a real $x$ such that every integer $n$ satisfies $n\\le x$" },
      { key: "C", text: "There exists an integer $n$ such that every real $x$ satisfies $n\\le x$" },
      { key: "D", text: "For every integer $n$, there exists a real $x$ such that $n\\le x$" },
      { key: "E", text: "There exists a real $x$ and an integer $n$ such that $n\\le x$" },
      { key: "F", text: "No integer is greater than every real number" },
    ],
    answer: "B",
    solution: "Negating $\\forall x\\,\\exists n\\,(n>x)$ changes the quantifiers and negates the inequality: $\\exists x\\,\\forall n\\,(n\\le x)$. This is option B.",
  },
  {
    id: "tmua-cal1-p2-06", type: "mcq", testId: "tmua", topicId: "tmua-number", difficulty: 1, marks: 1,
    question: "Which pair of integers is a counterexample to the claim 'if $ab$ is even, then both $a$ and $b$ are even'?",
    options: [
      { key: "A", text: "$a=2,\ b=3$" }, { key: "B", text: "$a=2,\ b=4$" },
      { key: "C", text: "$a=3,\ b=5$" }, { key: "D", text: "$a=4,\ b=6$" },
      { key: "E", text: "$a=1,\ b=1$" },
    ],
    answer: "A",
    solution: "For $a=2$ and $b=3$, the product $ab=6$ is even but $b$ is odd, so the conclusion that both factors are even fails.",
  },
  {
    id: "tmua-cal1-p2-07", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 3, marks: 1,
    question: "Let $f$ be defined for all real numbers and let $a$ be a fixed real number.\n\nI. The condition $f(2a-x)=f(x)$ for every real $x$ is necessary and sufficient for the graph of $y=f(x)$ to have reflection symmetry in $x=a$.\n\nII. The condition $f(a-x)=f(a+x)$ for every real $x$ is necessary and sufficient for the same symmetry.\n\nIII. The condition $f(-x)=f(x)$ for every real $x$ is sufficient for the same symmetry for every value of $a$.\n\nWhich statements are true?",
    options: COMBINATION_OPTIONS,
    answer: "B",
    solution: "I is precisely the reflection rule about $x=a$. Replacing $x$ by $a+t$ shows II is equivalent to I. III guarantees symmetry about $x=0$, not about every vertical line. Hence I and II only are true.",
  },
  {
    id: "tmua-cal1-p2-08", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "A proof by induction claims that $6$ divides $7^n-1$ for every positive integer $n$. It verifies $n=1$, assumes $7^k-1=6m$, and writes\n$$7^{k+1}-1=7(7^k-1)+6=42m+6.$$\n\nI. The base case is valid.\n\nII. The induction step proves the result for $k+1$ from the result for $k$.\n\nIII. The argument proves the claim for every positive integer $n$.\n\nWhich statements are true?",
    options: COMBINATION_OPTIONS,
    answer: "A",
    solution: "At $n=1$, $7^1-1=6$. Under the induction hypothesis, $42m+6=6(7m+1)$ is divisible by $6$, so the step is valid. With a valid base and step, induction proves the result for all positive integers. All three statements are true.",
  },
  {
    id: "tmua-cal1-p2-09", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 3, marks: 1,
    question: "Let $f$ have a continuous derivative on $[a,b]$.\n\nI. $\\displaystyle\\\int_a^b f'(x)\\,\\mathrm dx=f(b)-f(a)$.\n\nII. If $\\displaystyle\\\int_a^b f(x)\\,\\mathrm dx=0$, then $f(x)=0$ for every $x\\in[a,b]$.\n\nIII. If $f(x)\\ge0$ throughout $[a,b]$ and $\\displaystyle\\\int_a^b f(x)\\,\\mathrm dx=0$, then $f(x)=0$ throughout $[a,b]$.\n\nWhich statements are true?",
    options: COMBINATION_OPTIONS,
    answer: "C",
    solution: "I is the fundamental theorem of calculus. II is false because positive and negative areas can cancel, for example $f(x)=x$ on $[-1,1]$. III is true: a continuous non-negative function that is positive anywhere is positive on a small interval and would have positive integral. Thus I and III only are true.",
  },
  {
    id: "tmua-cal1-p2-10", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 3, marks: 1,
    question: "A sequence is defined by $a_1=1$ and $a_{n+1}=2-\\dfrac12a_n$.\n\nI. Every term lies between $\\dfrac54$ and $\\dfrac32$, inclusive.\n\nII. The sequence is increasing.\n\nIII. The sequence converges to $\\dfrac43$.\n\nWhich statements are true?",
    options: COMBINATION_OPTIONS,
    answer: "G",
    solution: "The first term $a_1=1$ makes I false. The next terms are $3/2,5/4,11/8,\\ldots$, so the sequence alternates and II is false. Since $a_{n+1}-4/3=-\\tfrac12(a_n-4/3)$, the error shrinks geometrically to zero; III alone is true.",
  },
  {
    id: "tmua-cal1-p2-11", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "For the quadratic $x^2+bx+c=0$, where $b$ and $c$ are real:\n\nI. $b^2>4c$ is necessary and sufficient for the equation to have real roots.\n\nII. $c<0$ is sufficient for the equation to have two distinct real roots.\n\nIII. $b=0$ is sufficient for the equation to have two real roots that are negatives of each other.\n\nWhich statements are true?",
    options: COMBINATION_OPTIONS,
    answer: "F",
    solution: "I is false because equality $b^2=4c$ still gives a repeated real root. If $c<0$, then the discriminant $b^2-4c>0$, so II is true. III is false: $x^2+1=0$ has $b=0$ but no real roots. Thus II alone is true.",
  },
  {
    id: "tmua-cal1-p2-12", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "For a real number $x$:\n\nI. $x^2>4$ implies $x>2$.\n\nII. $|x|>2$ implies $x^2>4$.\n\nIII. $x^2>4$ if and only if $|x|>2$.\n\nWhich statements are true?",
    options: COMBINATION_OPTIONS,
    answer: "E",
    solution: "I is false because $x=-3$ is a counterexample. Squaring the non-negative quantities in $|x|>2$ gives $x^2>4$, and the implication reverses as well. Thus II and III only are true.",
  },
  {
    id: "tmua-cal1-p2-13", type: "mcq", testId: "tmua", topicId: "tmua-stats", difficulty: 3, marks: 1,
    question: "Events $A$ and $B$ are independent, with $P(A)=\\dfrac12$ and $P(B)=\\dfrac13$.\n\nI. $P(A\\cap B)=\\dfrac16$.\n\nII. $A$ and $B$ are mutually exclusive.\n\nIII. $A^c$ and $B^c$ are independent.\n\nWhich statements are true?",
    options: COMBINATION_OPTIONS,
    answer: "C",
    solution: "Independence gives $P(A\\cap B)=P(A)P(B)=1/6$, so I is true and II is false. Also $P(A^c\\cap B^c)=1-P(A)-P(B)+P(A\\cap B)=1/3=P(A^c)P(B^c)$, so III is true. Hence I and III only.",
  },
  {
    id: "tmua-cal1-p2-14", type: "mcq", testId: "tmua", topicId: "tmua-number", difficulty: 2, marks: 1,
    question: "The expression $n^3-n$ can be written as $(n-1)n(n+1)$. For every integer $n$:\n\nI. These are three consecutive integers.\n\nII. The middle factor $n$ is divisible by $3$.\n\nIII. The middle factor $n$ is even.\n\nWhich statements are true?",
    options: COMBINATION_OPTIONS,
    answer: "D",
    solution: "I is true by inspection. II is false, for example at $n=1$, and III is false for the same example. Although one of the three consecutive factors must be divisible by $3$ and at least one must be even, that factor need not be the middle one. Thus I alone is true.",
  },
  {
    id: "tmua-cal1-p2-15", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 3, marks: 1,
    question: "In triangle $ABC$:\n\nI. If $AB=AC$, then $\\angle B=\\angle C$.\n\nII. If $\\angle B=\\angle C$, then $AB=AC$.\n\nIII. If the medians from $B$ and $C$ have equal length, then $AB=AC$.\n\nWhich statements are true?",
    options: COMBINATION_OPTIONS,
    answer: "A",
    solution: "I and II are the two directions of the isosceles triangle theorem. For III, the median formulae give $m_b^2=(2a^2+2c^2-b^2)/4$ and $m_c^2=(2a^2+2b^2-c^2)/4$. Equality gives $3c^2=3b^2$, hence $b=c$, which is $AB=AC$. All three are true.",
  },
  {
    id: "tmua-cal1-p2-16", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "What does the statement 'a function is differentiable at $x=a$ only if it is continuous at $x=a$' mean?",
    options: [
      { key: "A", text: "Differentiability at $a$ implies continuity at $a$" },
      { key: "B", text: "Continuity at $a$ implies differentiability at $a$" },
      { key: "C", text: "The function is differentiable at $a$ if and only if it is continuous there" },
      { key: "D", text: "The function is neither differentiable nor continuous at $a$" },
      { key: "E", text: "Differentiability and continuity at $a$ are unrelated" },
      { key: "F", text: "The function is differentiable at every point except $a$" },
    ],
    answer: "A",
    solution: "'$P$ only if $Q$' means $P\\Rightarrow Q$. Here $P$ is differentiability at $a$ and $Q$ is continuity at $a$.",
  },
  {
    id: "tmua-cal1-p2-17", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "Let $f(x)=x^2$ with domain $[0,\\\infty)$.\n\nI. $f$ is one-to-one.\n\nII. The inverse function is $f^{-1}(x)=\\sqrt{x}$ for $x\\ge0$.\n\nIII. $f^{-1}(x^2)=x$ for every real $x$.\n\nWhich statements are true?",
    options: COMBINATION_OPTIONS,
    answer: "B",
    solution: "On $[0,\\\infty)$, squaring is strictly increasing, so I is true and its inverse is the principal square root, so II is true. But $f^{-1}(x^2)=\\sqrt{x^2}=|x|$, which is not $x$ when $x<0$. Thus III is false.",
  },
  {
    id: "tmua-cal1-p2-18", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "In a proof that $\\sqrt2$ is irrational, one assumes $\\sqrt2=p/q$ where $p$ and $q$ are coprime integers, then deduces that both $p$ and $q$ are even. Why is this a contradiction?",
    options: [
      { key: "A", text: "No even integer can be squared" },
      { key: "B", text: "Two even integers have a common factor $2$, contrary to coprimality" },
      { key: "C", text: "The quotient of two even integers is always an integer" },
      { key: "D", text: "Every rational number has an odd numerator" },
      { key: "E", text: "$p^2$ and $q^2$ cannot both be even" },
      { key: "F", text: "The assumption already states that $p$ and $q$ are even" },
    ],
    answer: "B",
    solution: "If both $p$ and $q$ are even, they share the factor $2$. This contradicts the initial choice of $p/q$ in lowest terms, so the rationality assumption must be false.",
  },
  {
    id: "tmua-cal1-p2-19", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 3, marks: 1,
    question: "Consider non-constant polynomials with real coefficients.\n\nI. Every polynomial of odd degree has exactly one real root.\n\nII. Every polynomial of even degree has no real roots.\n\nIII. If a polynomial has no real roots, then its degree is even.\n\nWhich statements are true?",
    options: COMBINATION_OPTIONS,
    answer: "G",
    solution: "I is false because $x^3-x$ has three distinct real roots. II is false because $x^2-1$ has two real roots. Every odd-degree real polynomial has at least one real root, so a polynomial with no real roots cannot have odd degree; III alone is true.",
  },
  {
    id: "tmua-cal1-p2-20", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 3, marks: 1,
    question: "Let $f:\\mathbb R\\to\\mathbb R$.\n\nI. If $f$ is non-decreasing, then $f$ is one-to-one.\n\nII. Being onto $\\mathbb R$ is necessary for $f$ to have an inverse function defined on its range.\n\nIII. The condition $f(x)=f(-x)$ for every real $x$ is sufficient for $f$ to be one-to-one.\n\nWhich statements are true?",
    options: COMBINATION_OPTIONS,
    answer: "H",
    solution: "I is false because a non-decreasing function may be constant on an interval. II is false: $f(x)=e^x$ is not onto $\\mathbb R$ but has an inverse on its range $(0,\\\infty)$. III is false because $x$ and $-x$ have the same output; $f(x)=x^2$ is a counterexample. None of the statements is true.",
  },
];
