import type { MCQOptionKey, MCQQuestion, QuestionDifficulty } from "@/lib/tests/questions/types";

const KEYS = "ABCDEFGH" as const;
const COMBOS = ["I, II and III", "I and II only", "I and III only", "I only", "II and III only", "II only", "III only", "None of I, II and III"];

function q(
  id: string,
  topicId: string,
  difficulty: QuestionDifficulty,
  question: string,
  options: string[],
  answerIndex: number,
  solution: string,
): MCQQuestion {
  return {
    id, type: "mcq", testId: "tmua", topicId, difficulty, marks: 1, question,
    options: options.map((text, index) => ({ key: KEYS[index] as MCQOptionKey, text })),
    answer: KEYS[answerIndex] as MCQOptionKey,
    solution,
  };
}

export const TMUA_MK6_P1_CALIBRATED: MCQQuestion[] = [
  q("tmua-mk6-cal-p1-13", "tmua-algebra", 2, "The equation $|2x-3|=x+4$ has two solutions. What is their sum?", ["$-1/3$", "$7$", "$20/3$", "$22/3$", "$8$", "$10$"], 2, "The two sign cases give $x=7$ and $x=-1/3$, both valid. Their sum is $20/3$."),
  q("tmua-mk6-cal-p1-14", "tmua-stats", 2, "A fair coin is tossed three times. Given that at least one head occurs, what is the probability of exactly one head?", ["$1/4$", "$3/8$", "$3/7$", "$1/2$", "$4/7$", "$3/4$"], 2, "Seven equally likely outcomes remain after TTT is excluded. Exactly three, HTT, THT and TTH, contain one head, so the probability is $3/7$."),
  q("tmua-mk6-cal-p1-15", "tmua-algebra", 3, "For which real values of $k$ does $x^2-kx+1=0$ have two distinct positive roots?", ["$k<-2$", "$k=-2$", "$-2<k<2$", "$k=2$", "$k>2$", "$|k|>2$"], 4, "Distinct real roots require $k^2-4>0$. Their product is positive and their sum is $k$; both are positive exactly when $k>2$."),
  q("tmua-mk6-cal-p1-16", "tmua-geometry", 3, "The line $y=mx+4$ is tangent to the circle $x^2+y^2=4$. What is the sum of the squares of the possible values of $m$?", ["$2$", "$3$", "$4$", "$6$", "$8$", "$12$"], 3, "The distance from the origin to $mx-y+4=0$ is $4/(m^2+1)^{1/2}$. Equating this to radius $2$ gives $m^2=3$. There are two values, so the sum of their squares is $6$."),
  q("tmua-mk6-cal-p1-17", "tmua-calc", 3, "What is the area enclosed by $y=x$ and $y=x^3$ between $x=0$ and $x=1$?", ["$1/6$", "$1/4$", "$1/3$", "$1/2$", "$3/4$"], 1, "On this interval $x\\ge x^3$. The area is $[x^2/2-x^4/4]_0^1=1/4$."),
  q("tmua-mk6-cal-p1-18", "tmua-discrete", 3, "How many arrangements of the letters A, B, C, D, E have A before B and C before D?", ["$20$", "$24$", "$30$", "$36$", "$40$", "$60$", "$120$"], 2, "Among all $5!=120$ arrangements, each independent ordering condition halves the count. Hence $120/4=30$."),
  q("tmua-mk6-cal-p1-19", "tmua-number", 3, "What is the remainder when $3^{100}$ is divided by $10$?", ["$0$", "$1$", "$3$", "$7$", "$9$"], 1, "Powers of $3$ modulo $10$ cycle $3,9,7,1$ with period $4$. Since $100$ is divisible by $4$, the remainder is $1$."),
  q("tmua-mk6-cal-p1-20", "tmua-algebra", 3, "How many distinct points of intersection do $y=x^2$ and $y=|2x|$ have?", ["$0$", "$1$", "$2$", "$3$", "$4$", "$5$", "$6$", "$8$"], 3, "The equation is $x^2=2|x|$. Let $u=|x|\\ge0$; then $u(u-2)=0$. This gives $x=0,2,-2$, so there are three points."),
];

export const TMUA_MK6_P2_CALIBRATED: MCQQuestion[] = [
  q("tmua-mk6-cal-p2-13", "tmua-logic", 2, "What is the contrapositive of 'if $n^2$ is odd, then $n$ is odd'?", ["If $n$ is odd, then $n^2$ is odd", "If $n$ is even, then $n^2$ is odd", "If $n^2$ is even, then $n$ is even", "If $n$ is not odd, then $n^2$ is not odd", "If $n^2$ is odd, then $n$ is not even"], 3, "Negating the conclusion and premise gives: if $n$ is not odd, then $n^2$ is not odd. This is option D."),
  q("tmua-mk6-cal-p2-14", "tmua-logic", 2, "Which is the negation of 'there exists a real $x$ such that $x^2+x<0$'?", ["For every real $x$, $x^2+x\\ge0$", "For every real $x$, $x^2+x>0$", "There exists a real $x$ such that $x^2+x\\ge0$", "There is no real $x$", "$x^2+x=0$ for every real $x$"], 0, "Negating an existential statement produces a universal statement, and the negation of $<0$ is $\\ge0$."),
  q("tmua-mk6-cal-p2-15", "tmua-discrete", 3, "A sequence satisfies $a_{n+1}=a_n+2n+1$ and $a_1=1$.\nI. $a_n=n^2+1$ for every positive integer $n$.\nII. The sequence is strictly increasing.\nIII. $a_n$ is odd for every $n$.\nWhich statements are true?", COMBOS, 5, "In fact $a_n=n^2$, so I is false. The positive increments make II true. III is false when $n$ is even. Thus II only."),
  q("tmua-mk6-cal-p2-16", "tmua-algebra", 3, "Let $p(x)=x^2+ax+b$.\nI. If $p$ has roots $r$ and $-r$, then $b=0$.\nII. If $a=0$, then $p$ has two real roots.\nIII. If $b<0$, then $p$ has two distinct real roots.\nWhich statements are true?", COMBOS, 6, "I is false because the product of the roots is $-r^2$, not generally zero. II fails for $x^2+1$. If $b<0$, the discriminant $a^2-4b$ is positive, so III alone is true."),
  q("tmua-mk6-cal-p2-17", "tmua-logic", 3, "A student squares both sides of $x-1=-3$ to obtain $(x-1)^2=9$, then concludes $x=4$ or $x=-2$. Why is the conclusion invalid?", ["Squaring can introduce solutions that do not satisfy the original signed equation", "The square of $-3$ is $-9$", "The equation has no solution", "Both resulting values satisfy the original equation", "The student divided by zero", "Squaring is never allowed in an equation"], 0, "The original equation has only $x=-2$. Squaring loses sign information, so $x=4$ is introduced but does not satisfy $x-1=-3$."),
  q("tmua-mk6-cal-p2-18", "tmua-stats", 3, "Events $A$ and $B$ satisfy $P(A)=P(B)=1/2$.\nI. If they are independent, then $P(A\\cap B)=1/4$.\nII. If $P(A\\cap B)=1/4$, then they are independent.\nIII. If they are mutually exclusive, then they are independent.\nWhich statements are true?", COMBOS, 1, "I follows from independence. With the stated marginal probabilities, II is the defining equality and is true. III is false because mutually exclusive events here have intersection probability $0$, not $1/4$."),
  q("tmua-mk6-cal-p2-19", "tmua-algebra", 3, "Let $f(x)=x^2$.\nI. $f$ is one-to-one on the real numbers.\nII. $f$ is onto the real numbers.\nIII. $f$ has an inverse function on the real numbers.\nWhich statements are true?", COMBOS, 7, "The values at $x$ and $-x$ are equal, so I is false. Negative numbers are not in the range, so II is false. Without one-to-one behaviour, no inverse exists on the stated domain. None is true."),
  q("tmua-mk6-cal-p2-20", "tmua-number", 3, "For an integer $n$:\nI. If $6$ divides $n^2$, then $6$ divides $n$.\nII. If $12$ divides $n^2$, then $12$ divides $n$.\nIII. If $n$ is prime and $n$ divides $ab$, then $n$ divides $a$ or $n$ divides $b$.\nWhich statements are true?", COMBOS, 2, "I is true by prime factorisation. II is false: $n=6$ gives $12\\mid36$ but $12\\nmid6$. III is Euclid's lemma. Thus I and III only."),
];

export const TMUA_MK9_P1_CALIBRATED: MCQQuestion[] = [
  q("tmua-mk9-cal-p1-13", "tmua-algebra", 2, "If $x+1/x=3$, what is $x^2+1/x^2$?", ["$5$", "$7$", "$8$", "$9$", "$11$"], 1, "Squaring gives $x^2+2+1/x^2=9$, hence the required value is $7$."),
  q("tmua-mk9-cal-p1-14", "tmua-stats", 2, "A box contains two red and three blue balls. Two are selected without replacement. What is the probability of selecting exactly one red ball?", ["$1/5$", "$2/5$", "$1/2$", "$3/5$", "$4/5$", "$9/10$"], 3, "There are $10$ unordered pairs. Favourable pairs choose one of two red and one of three blue balls, giving $6$, so the probability is $3/5$."),
  q("tmua-mk9-cal-p1-15", "tmua-algebra", 3, "For $x\\ne0$, what is the least value of $x^2+16/x^2$?", ["$4$", "$6$", "$8$", "$10$", "$16$", "There is no least value"], 2, "AM-GM gives $x^2+16/x^2\\ge2\\sqrt{16}=8$, attained when $x^2=4$."),
  q("tmua-mk9-cal-p1-16", "tmua-geometry", 3, "A chord of a circle of radius $5$ is at distance $3$ from the centre. What is the chord length?", ["$4$", "$6$", "$8$", "$10$", "$12$", "$16$"], 2, "The perpendicular from the centre bisects the chord. Half its length is $(5^2-3^2)^{1/2}=4$, so the chord has length $8$."),
  q("tmua-mk9-cal-p1-17", "tmua-calc", 3, "For which values of $a$ does $f(x)=x^3-3ax$ have two distinct stationary points?", ["$a<0$", "$a=0$", "$a>0$", "$a\\ge0$", "$a\\ne0$", "All real $a$"], 2, "$f'(x)=3(x^2-a)$. It has two distinct real zeros exactly when $a>0$."),
  q("tmua-mk9-cal-p1-18", "tmua-discrete", 3, "Four people are divided into two non-empty unlabeled teams. How many divisions are possible?", ["$4$", "$6$", "$7$", "$8$", "$12$", "$14$", "$16$"], 2, "There are $2^4-2=14$ assignments to two labeled non-empty teams. Swapping team labels changes no division, so the answer is $14/2=7$."),
  q("tmua-mk9-cal-p1-19", "tmua-number", 3, "How many integers from $1$ to $100$ inclusive are divisible by $4$ or by $6$?", ["$25$", "$30$", "$32$", "$33$", "$41$", "$42$"], 3, "There are $25$ multiples of $4$ and $16$ of $6$. The $8$ multiples of $12$ were counted twice, so the total is $25+16-8=33$."),
  q("tmua-mk9-cal-p1-20", "tmua-stats", 3, "A random variable $X$ has variance $4$. What is the variance of $3X-2$?", ["$4$", "$10$", "$12$", "$18$", "$36$", "$100$"], 4, "Adding a constant does not change variance, while multiplication by $3$ multiplies variance by $3^2$. Hence the variance is $9\\cdot4=36$."),
];

export const TMUA_MK9_P2_CALIBRATED: MCQQuestion[] = [
  q("tmua-mk9-cal-p2-13", "tmua-logic", 2, "The statement '$n$ is divisible by $8$ only if $n$ is divisible by $4$' means:", ["$4\\mid n$ implies $8\\mid n$", "$8\\mid n$ implies $4\\mid n$", "$8\\mid n$ if and only if $4\\mid n$", "$n$ is divisible by neither", "$n$ is divisible by $32$"], 1, "'$P$ only if $Q$' means $P$ implies $Q$. Here divisibility by $8$ implies divisibility by $4$."),
  q("tmua-mk9-cal-p2-14", "tmua-logic", 2, "Which value is a counterexample to 'if $x^2>x$, then $x>1$'?", ["$x=-2$", "$x=0$", "$x=1/2$", "$x=1$", "$x=2$"], 0, "At $x=-2$, $x^2=4>-2$ but $x>1$ is false. The other options do not disprove the implication."),
  q("tmua-mk9-cal-p2-15", "tmua-calc", 3, "Let $f$ be differentiable.\nI. If $f'(x)\\ge0$ everywhere, then $f$ is strictly increasing.\nII. If $f$ is strictly increasing, then $f'(x)>0$ everywhere.\nIII. If $f'(x)=0$ everywhere, then $f$ is constant.\nWhich statements are true?", COMBOS, 6, "I is false for a constant function. II is false for $f(x)=x^3$ at $x=0$. III follows from the mean value theorem, so III alone is true."),
  q("tmua-mk9-cal-p2-16", "tmua-number", 3, "For every integer $n$:\nI. $n(n+1)$ is even.\nII. $n(n+1)(n+2)$ is divisible by $6$.\nIII. $n^2+n+1$ is odd.\nWhich statements are true?", COMBOS, 0, "I is true for consecutive integers. II is true because among three consecutive integers one is divisible by $3$ and one is even. Since $n(n+1)$ is always even, adding $1$ is always odd, so III is true. All three statements hold."),
  q("tmua-mk9-cal-p2-17", "tmua-algebra", 3, "Let $f(x)=x^2+1$.\nI. $f$ is one-to-one on the real numbers.\nII. $f$ is one-to-one on $[0,\\infty)$.\nIII. The range of $f$ on the real numbers is $[1,\\infty)$.\nWhich statements are true?", COMBOS, 4, "I is false because $f(x)=f(-x)$. On the non-negative domain it is strictly increasing, so II is true, and its full real range is $[1,\\infty)$, so III is true."),
  q("tmua-mk9-cal-p2-18", "tmua-stats", 3, "Events $A$ and $B$ are mutually exclusive and both have positive probability.\nI. $P(A\\cap B)=0$.\nII. $A$ and $B$ are independent.\nIII. $P(A\\cup B)=P(A)+P(B)$.\nWhich statements are true?", COMBOS, 2, "Mutual exclusivity gives I and III. Independence would require $P(A\\cap B)=P(A)P(B)>0$, so II is false."),
  q("tmua-mk9-cal-p2-19", "tmua-geometry", 3, "In a triangle:\nI. Unequal sides have equal opposite angles.\nII. Equal angles have equal opposite sides.\nIII. A right triangle can be equilateral.\nWhich statements are true?", COMBOS, 5, "I contradicts the side-angle ordering theorem. II is the converse isosceles triangle theorem. III is impossible because an equilateral triangle has three $60$ degree angles. Thus II only."),
  q("tmua-mk9-cal-p2-20", "tmua-logic", 3, "A proof assumes a statement $P$ and derives both $Q$ and not-$Q$.\nI. This establishes $P$ by direct proof.\nII. The contradiction proves that $Q$ is always false.\nIII. The contradiction proves that $P$ is true.\nWhich statements are true?", COMBOS, 7, "A contradiction refutes the assumption $P$; it neither proves $P$ nor makes a universal claim about $Q$. None of the three descriptions is correct."),
];

export const TMUA_MK10_P1_CALIBRATED: MCQQuestion[] = [
  q("tmua-mk10-cal-p1-13", "tmua-discrete", 2, "An arithmetic sequence has first term $5$ and common difference $3$. Which term is $50$?", ["the 14th", "the 15th", "the 16th", "the 17th", "the 18th"], 2, "$5+3(n-1)=50$ gives $n-1=15$, so $n=16$."),
  q("tmua-mk10-cal-p1-14", "tmua-stats", 2, "Two fair dice are rolled. Given that the first die is greater than the second, what is the probability that their sum is $7$?", ["$1/10$", "$1/5$", "$1/4$", "$1/3$", "$2/5$", "$1/2$"], 1, "There are $15$ ordered outcomes with first die greater. Three, $(6,1),(5,2),(4,3)$, have sum $7$, so the probability is $3/15=1/5$."),
  q("tmua-mk10-cal-p1-15", "tmua-algebra", 3, "How many real solutions does $2^x+2^{-x}=5/2$ have?", ["$0$", "$1$", "$2$", "$3$", "$4$", "Infinitely many"], 2, "Let $t=2^x>0$. Then $t+1/t=5/2$, so $2t^2-5t+2=0$ and $t=2$ or $1/2$. Hence $x=1$ or $-1$."),
  q("tmua-mk10-cal-p1-16", "tmua-algebra", 3, "When $x^4+2x^3-x+5$ is divided by $x+1$, what is the remainder?", ["$1$", "$3$", "$4$", "$5$", "$7$", "$9$"], 3, "By the remainder theorem, substitute $x=-1$: $1-2+1+5=5$."),
  q("tmua-mk10-cal-p1-17", "tmua-geometry", 3, "What is the area of the triangle with vertices $(1,1)$, $(5,2)$ and $(3,6)$?", ["$7$", "$8$", "$9$", "$10$", "$11$", "$12$"], 2, "Using vectors $(4,1)$ and $(2,5)$ from $(1,1)$, the area is half the determinant magnitude: $|4\\cdot5-1\\cdot2|/2=9$."),
  q("tmua-mk10-cal-p1-18", "tmua-calc", 3, "What is the maximum value of $x(8-x)^2$ for $0\\le x\\le8$?", ["$128/9$", "$256/9$", "$512/27$", "$2048/27$", "$32$", "$64$"], 3, "Differentiation gives $(8-x)(8-3x)$, so the interior maximum occurs at $x=8/3$. The value is $(8/3)(16/3)^2=2048/27$; the endpoint values are both zero."),
  q("tmua-mk10-cal-p1-19", "tmua-discrete", 3, "Six people sit around a circular table. In how many arrangements are two specified people not adjacent?", ["$48$", "$60$", "$72$", "$84$", "$96$", "$120$"], 2, "There are $5!=120$ circular arrangements. Treating the specified pair as a block gives $2\\cdot4!=48$ adjacent arrangements, leaving $72$."),
  q("tmua-mk10-cal-p1-20", "tmua-number", 3, "How many trailing zeros does $100!$ have?", ["$20$", "$21$", "$22$", "$23$", "$24$", "$25$", "$26$", "$30$"], 4, "The number of factors $5$ is $\\lfloor100/5\\rfloor+\\lfloor100/25\\rfloor=20+4=24$."),
];

export const TMUA_MK10_P2_CALIBRATED: MCQQuestion[] = [
  q("tmua-mk10-cal-p2-11", "tmua-logic", 2, "Which statement is equivalent to 'not every integer is positive'?", ["Every integer is non-positive", "No integer is positive", "At least one integer is not positive", "At least one integer is positive", "Every integer is negative"], 2, "The negation of a universal statement is an existential counterexample: at least one integer is not positive."),
  q("tmua-mk10-cal-p2-12", "tmua-logic", 2, "If $P$ implies $Q$ and $Q$ is false, what must follow?", ["$P$ is true", "$P$ is false", "$Q$ is true", "$P$ and $Q$ are equivalent", "Nothing follows"], 1, "By the contrapositive, not-$Q$ implies not-$P$, so $P$ must be false."),
  q("tmua-mk10-cal-p2-13", "tmua-algebra", 3, "For real $x$:\nI. $x^2=9$ is sufficient for $|x|=3$.\nII. $|x|=3$ is sufficient for $x=3$.\nIII. $x=3$ is necessary for $x^2=9$.\nWhich statements are true?", COMBOS, 3, "I is true because $x^2=9$ gives $x=\\pm3$. II and III are false because $x=-3$ is a counterexample. Thus I only."),
  q("tmua-mk10-cal-p2-14", "tmua-number", 3, "For an integer $n$:\nI. If $n^2$ is even, then $n$ is divisible by $4$.\nII. If $n^2$ is divisible by $4$, then $n$ is divisible by $4$.\nIII. If $n$ is odd, then $n^2$ is odd.\nWhich statements are true?", COMBOS, 6, "I and II are both false for $n=2$. III is the standard parity result, so III alone is true."),
  q("tmua-mk10-cal-p2-15", "tmua-calc", 3, "Let $f$ be continuous on $[0,1]$.\nI. If $f(0)f(1)\\le0$, then $f$ has a zero in $(0,1)$.\nII. If $f$ has a zero in $(0,1)$, then $f(0)f(1)<0$.\nIII. If $f(x)\\ge0$ throughout $[0,1]$, then its integral over $[0,1]$ is positive.\nWhich statements are true?", COMBOS, 7, "I can fail when the only zero is an endpoint. II fails when the graph touches the axis without changing sign. III fails for the zero function. None is always true."),
  q("tmua-mk10-cal-p2-16", "tmua-discrete", 3, "A sequence has $a_1=2$ and $a_{n+1}=3a_n$.\nI. $a_n=2\\cdot3^{n-1}$.\nII. Every term is even.\nIII. Every term after the first is divisible by $6$.\nWhich statements are true?", COMBOS, 0, "The closed form follows by induction. It is always twice an integer, and for $n\\ge2$ it also contains a factor $3$. All three statements are true."),
  q("tmua-mk10-cal-p2-17", "tmua-stats", 3, "A fair die is rolled twice.\nI. The events 'first roll is even' and 'second roll is even' are independent.\nII. The events 'sum is odd' and 'first roll is even' are independent.\nIII. The events 'sum is $2$' and 'first roll is $1$' are independent.\nWhich statements are true?", COMBOS, 1, "I is true by separate rolls. For II, the conditional probability of an odd sum given an even first roll is $1/2$, equal to its marginal probability. III is false because the intersection has probability $1/36$, while the product is $(1/36)(1/6)$."),
  q("tmua-mk10-cal-p2-18", "tmua-geometry", 3, "For two non-degenerate triangles:\nI. Equal corresponding angles are sufficient for congruence.\nII. Proportional corresponding sides are sufficient for similarity.\nIII. Equal areas are sufficient for congruence.\nWhich statements are true?", COMBOS, 5, "Equal angles establish similarity, not congruence, so I is false. SSS proportionality establishes similarity, so II is true. Equal area alone is insufficient for congruence, so III is false."),
  q("tmua-mk10-cal-p2-19", "tmua-algebra", 3, "Let $p$ be a real polynomial.\nI. If $p(1)=0$, then $x-1$ is a factor.\nII. If $x-1$ is a factor, then $p(1)=0$.\nIII. If $p(1)p(2)<0$, then $p$ has a root between $1$ and $2$.\nWhich statements are true?", COMBOS, 0, "I and II are the factor theorem. Polynomials are continuous, so III follows from the intermediate value theorem. All three are true."),
  q("tmua-mk10-cal-p2-20", "tmua-logic", 3, "A theorem states: if $P$, then $Q$.\nI. A proof of not-$Q$ implies not-$P$ proves the theorem.\nII. A single example where both $P$ and $Q$ hold proves the theorem.\nIII. A single example where $P$ holds and $Q$ fails disproves the theorem.\nWhich statements are true?", COMBOS, 2, "I proves the contrapositive and is valid. II verifies only one case. III is a counterexample and disproves the universal implication. Thus I and III only."),
];
