// TMUA 模拟卷三 —— 全新原创题，与卷一/二、练习题均不重复。两卷各 20 题、各 75 分钟、五选一、无负分。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const TMUA_MK3_P1: MCQQuestion[] = [
  { id:"tmua-mk3-p1-01", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The larger root of $x^2-8x+12=0$ is:", options:[{key:"A",text:"$2$"},{key:"B",text:"$6$"},{key:"C",text:"$4$"},{key:"D",text:"$8$"},{key:"E",text:"$12$"}],
    answer:"B", solution:"$(x-2)(x-6)=0$; larger root $6.$" },
  { id:"tmua-mk3-p1-02", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Evaluate $16^{3/4}$.", options:[{key:"A",text:"$4$"},{key:"B",text:"$8$"},{key:"C",text:"$12$"},{key:"D",text:"$2$"},{key:"E",text:"$64$"}],
    answer:"B", solution:"$16^{1/4}=2$, then $2^3=8.$" },
  { id:"tmua-mk3-p1-03", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Simplify $\\sqrt{27}+\\sqrt{12}$.", options:[{key:"A",text:"$5\\sqrt3$"},{key:"B",text:"$6\\sqrt3$"},{key:"C",text:"$\\sqrt{39}$"},{key:"D",text:"$5\\sqrt6$"},{key:"E",text:"$\\sqrt3$"}],
    answer:"A", solution:"$3\\sqrt3+2\\sqrt3=5\\sqrt3.$" },
  { id:"tmua-mk3-p1-04", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Find the sum of the first $10$ terms of $3+7+11+\\cdots$.", options:[{key:"A",text:"$210$"},{key:"B",text:"$190$"},{key:"C",text:"$200$"},{key:"D",text:"$220$"},{key:"E",text:"$180$"}],
    answer:"A", solution:"$a=3,d=4$: $S_{10}=\\tfrac{10}{2}(6+9\\cdot4)=5\\times42=210.$" },
  { id:"tmua-mk3-p1-05", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Find the sum of the first $5$ terms of $2+6+18+\\cdots$.", options:[{key:"A",text:"$242$"},{key:"B",text:"$240$"},{key:"C",text:"$243$"},{key:"D",text:"$162$"},{key:"E",text:"$80$"}],
    answer:"A", solution:"$a=2,r=3$: $S_5=\\dfrac{2(3^5-1)}{3-1}=3^5-1=242.$" },
  { id:"tmua-mk3-p1-06", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"The gradient of the line through $(1,4)$ and $(3,10)$ is:", options:[{key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$6$"},{key:"D",text:"$1$"},{key:"E",text:"$\\tfrac13$"}],
    answer:"B", solution:"$\\tfrac{10-4}{3-1}=3.$" },
  { id:"tmua-mk3-p1-07", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:3, marks:1,
    question:"The centre of the circle $x^2+y^2+2x-8y+1=0$ is:", options:[{key:"A",text:"$(-1,4)$"},{key:"B",text:"$(1,-4)$"},{key:"C",text:"$(-1,-4)$"},{key:"D",text:"$(1,4)$"},{key:"E",text:"$(2,-8)$"}],
    answer:"A", solution:"$(x+1)^2+(y-4)^2=16$, centre $(-1,4).$" },
  { id:"tmua-mk3-p1-08", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"Evaluate $\\sin 30^\\circ+\\cos 60^\\circ$.", options:[{key:"A",text:"$1$"},{key:"B",text:"$\\tfrac12$"},{key:"C",text:"$\\tfrac{\\sqrt3}{2}$"},{key:"D",text:"$0$"},{key:"E",text:"$2$"}],
    answer:"A", solution:"$\\tfrac12+\\tfrac12=1.$" },
  { id:"tmua-mk3-p1-09", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"Evaluate $\\tan 45^\\circ$.", options:[{key:"A",text:"$1$"},{key:"B",text:"$0$"},{key:"C",text:"$\\sqrt3$"},{key:"D",text:"$\\tfrac{1}{\\sqrt3}$"},{key:"E",text:"undefined"}],
    answer:"A", solution:"$\\tan45^\\circ=1.$" },
  { id:"tmua-mk3-p1-10", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:1, marks:1,
    question:"Solve $3^{x}=81$.", options:[{key:"A",text:"$3$"},{key:"B",text:"$4$"},{key:"C",text:"$5$"},{key:"D",text:"$27$"},{key:"E",text:"$9$"}],
    answer:"B", solution:"$81=3^4$, so $x=4.$" },
  { id:"tmua-mk3-p1-11", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Evaluate $\\log_4 64$.", options:[{key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$4$"},{key:"D",text:"$16$"},{key:"E",text:"$8$"}],
    answer:"B", solution:"$64=4^3$, so $\\log_4 64=3.$" },
  { id:"tmua-mk3-p1-12", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Solve $\\log_2 x=5$.", options:[{key:"A",text:"$10$"},{key:"B",text:"$25$"},{key:"C",text:"$32$"},{key:"D",text:"$16$"},{key:"E",text:"$64$"}],
    answer:"C", solution:"$x=2^5=32.$" },
  { id:"tmua-mk3-p1-13", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"Find $\\dfrac{d}{dx}(x^2-4x+1)$ at $x=0$.", options:[{key:"A",text:"$-4$"},{key:"B",text:"$0$"},{key:"C",text:"$1$"},{key:"D",text:"$4$"},{key:"E",text:"$-1$"}],
    answer:"A", solution:"$2x-4$; at $x=0$, $-4.$" },
  { id:"tmua-mk3-p1-14", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"The gradient of $y=3x^2$ at $x=1$ is:", options:[{key:"A",text:"$3$"},{key:"B",text:"$6$"},{key:"C",text:"$1$"},{key:"D",text:"$9$"},{key:"E",text:"$2$"}],
    answer:"B", solution:"$y'=6x=6$ at $x=1.$" },
  { id:"tmua-mk3-p1-15", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"Evaluate $\\displaystyle\\int_1^2 4x\\,\\mathrm{d}x$.", options:[{key:"A",text:"$4$"},{key:"B",text:"$6$"},{key:"C",text:"$8$"},{key:"D",text:"$2$"},{key:"E",text:"$12$"}],
    answer:"B", solution:"$[2x^2]_1^2=8-2=6.$" },
  { id:"tmua-mk3-p1-16", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"The area under $y=3x^2$ from $x=0$ to $x=2$ is:", options:[{key:"A",text:"$4$"},{key:"B",text:"$8$"},{key:"C",text:"$6$"},{key:"D",text:"$12$"},{key:"E",text:"$24$"}],
    answer:"B", solution:"$\\int_0^2 3x^2\\,dx=[x^3]_0^2=8.$" },
  { id:"tmua-mk3-p1-17", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The graph of $y=f(x+3)$ is $y=f(x)$ shifted:", options:[{key:"A",text:"left 3"},{key:"B",text:"right 3"},{key:"C",text:"up 3"},{key:"D",text:"down 3"},{key:"E",text:"left 3 and up 3"}],
    answer:"A", solution:"Replacing $x$ by $x+3$ shifts the graph $3$ to the left." },
  { id:"tmua-mk3-p1-18", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Given $f(x)=3x$ and $g(x)=x+2$, find $g(f(2))$.", options:[{key:"A",text:"$8$"},{key:"B",text:"$12$"},{key:"C",text:"$6$"},{key:"D",text:"$10$"},{key:"E",text:"$14$"}],
    answer:"A", solution:"$f(2)=6$, then $g(6)=8.$" },
  { id:"tmua-mk3-p1-19", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:1, marks:1,
    question:"Solve $2x+1\\ge7$.", options:[{key:"A",text:"$x\\ge3$"},{key:"B",text:"$x\\le3$"},{key:"C",text:"$x\\ge4$"},{key:"D",text:"$x>3$"},{key:"E",text:"$x\\ge6$"}],
    answer:"A", solution:"$2x\\ge6\\Rightarrow x\\ge3.$" },
  { id:"tmua-mk3-p1-20", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The coefficient of $x^2$ in $(1+x)^6$ is:", options:[{key:"A",text:"$15$"},{key:"B",text:"$20$"},{key:"C",text:"$6$"},{key:"D",text:"$30$"},{key:"E",text:"$12$"}],
    answer:"A", solution:"$\\binom{6}{2}=15.$" },
];

export const TMUA_MK3_P2: MCQQuestion[] = [
  { id:"tmua-mk3-p2-01", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"For an integer to be divisible by $10$, being divisible by $5$ is:", options:[{key:"A",text:"sufficient but not necessary"},{key:"B",text:"necessary but not sufficient"},{key:"C",text:"both"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"B", solution:"Divisible by 10 $\\Rightarrow$ divisible by 5 (necessary), but 15 is divisible by 5 and not 10 (not sufficient)." },
  { id:"tmua-mk3-p2-02", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The converse of 'if $n>5$ then $n>3$' is:", options:[{key:"A",text:"true"},{key:"B",text:"false; e.g. $n=4$"},{key:"C",text:"false; e.g. $n=6$"},{key:"D",text:"the same statement"},{key:"E",text:"always true"}],
    answer:"B", solution:"Converse: 'if $n>3$ then $n>5$', false since $n=4$ satisfies $n>3$ but not $n>5.$" },
  { id:"tmua-mk3-p2-03", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The contrapositive of 'if a shape is a circle then it is round' is:", options:[{key:"A",text:"if a shape is round then it is a circle"},{key:"B",text:"if a shape is not round then it is not a circle"},{key:"C",text:"if a shape is not a circle then it is not round"},{key:"D",text:"if a shape is a circle then it is not round"},{key:"E",text:"all round shapes are circles"}],
    answer:"B", solution:"Contrapositive $\\lnot Q\\Rightarrow\\lnot P$: 'if not round then not a circle'." },
  { id:"tmua-mk3-p2-04", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:1, marks:1,
    question:"Which value disproves 'all multiples of $3$ are odd'?", options:[{key:"A",text:"$3$"},{key:"B",text:"$6$"},{key:"C",text:"$9$"},{key:"D",text:"$15$"},{key:"E",text:"none"}],
    answer:"B", solution:"$6$ is a multiple of $3$ but even — a counterexample." },
  { id:"tmua-mk3-p2-05", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:3, marks:1,
    question:"The negation of 'for all integers $n$, $n+1>n$' is:", options:[{key:"A",text:"for all $n$, $n+1\\le n$"},{key:"B",text:"there exists an integer $n$ with $n+1\\le n$"},{key:"C",text:"there exists an integer $n$ with $n+1>n$"},{key:"D",text:"for all $n$, $n+1<n$"},{key:"E",text:"no integer exists"}],
    answer:"B", solution:"Negate 'for all' to 'there exists' and negate the inequality: $n+1\\le n.$" },
  { id:"tmua-mk3-p2-06", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The negation of '$x>0$ and $x<5$' is:", options:[{key:"A",text:"$x<0$ and $x>5$"},{key:"B",text:"$x\\le0$ or $x\\ge5$"},{key:"C",text:"$x\\le0$ and $x\\ge5$"},{key:"D",text:"$0<x<5$"},{key:"E",text:"$x\\ne0$"}],
    answer:"B", solution:"not($A$ and $B$) $=$ not $A$ or not $B$: $x\\le0$ or $x\\ge5.$" },
  { id:"tmua-mk3-p2-07", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:1, marks:1,
    question:"If $A$ is true and $B$ is false, what is the truth value of '$A$ or $B$' (inclusive)?", options:[{key:"A",text:"true"},{key:"B",text:"false"},{key:"C",text:"undefined"},{key:"D",text:"depends on $B$"},{key:"E",text:"depends on both"}],
    answer:"A", solution:"Inclusive 'or' is true whenever at least one part is true; here $A$ is true." },
  { id:"tmua-mk3-p2-08", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Given $P\\Rightarrow Q$ and $Q\\Rightarrow R$ are true and $R$ is false, what follows?", options:[{key:"A",text:"$P$ is true"},{key:"B",text:"$P$ is false"},{key:"C",text:"$Q$ is true"},{key:"D",text:"nothing"},{key:"E",text:"$R$ is true"}],
    answer:"B", solution:"Contrapositive chain: $\\lnot R\\Rightarrow\\lnot Q\\Rightarrow\\lnot P.$" },
  { id:"tmua-mk3-p2-09", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:3, marks:1,
    question:"'From $xy=0$ we conclude $x=0$.' The flaw is that it:", options:[{key:"A",text:"ignores that $y$ could be $0$"},{key:"B",text:"divides by zero"},{key:"C",text:"has no flaw"},{key:"D",text:"assumes $x\\ne0$"},{key:"E",text:"squares both sides"}],
    answer:"A", solution:"$xy=0$ means $x=0$ or $y=0$; concluding $x=0$ alone overlooks $y=0.$" },
  { id:"tmua-mk3-p2-10", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"'All A are B, therefore all B are A.' The logical error is:", options:[{key:"A",text:"a false premise"},{key:"B",text:"assuming the converse"},{key:"C",text:"dividing by zero"},{key:"D",text:"proof by contradiction"},{key:"E",text:"a counterexample"}],
    answer:"B", solution:"Concluding $Q\\Rightarrow P$ from $P\\Rightarrow Q$ assumes the converse, which is invalid." },
  { id:"tmua-mk3-p2-11", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:1, marks:1,
    question:"Checking that a claim fails for $n=7$ in order to reject it is:", options:[{key:"A",text:"proof by contradiction"},{key:"B",text:"disproof by counterexample"},{key:"C",text:"proof by cases"},{key:"D",text:"direct proof"},{key:"E",text:"induction"}],
    answer:"B", solution:"A single failing case disproves a universal claim." },
  { id:"tmua-mk3-p2-12", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Proving a result by treating $x$ rational and $x$ irrational separately is:", options:[{key:"A",text:"proof by contradiction"},{key:"B",text:"proof by cases"},{key:"C",text:"disproof by counterexample"},{key:"D",text:"a converse argument"},{key:"E",text:"circular reasoning"}],
    answer:"B", solution:"Splitting into exhaustive cases is proof by cases." },
  { id:"tmua-mk3-p2-13", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"The $n$-th term of $3,7,11,15,\\ldots$ is:", options:[{key:"A",text:"$4n-1$"},{key:"B",text:"$3n$"},{key:"C",text:"$4n+1$"},{key:"D",text:"$2n+1$"},{key:"E",text:"$n^2+2$"}],
    answer:"A", solution:"Arithmetic with $a=3,d=4$: $u_n=3+(n-1)4=4n-1.$" },
  { id:"tmua-mk3-p2-14", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The condition '$n$ is even' is ______ for '$n^2$ is even' (over the integers).", options:[{key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both necessary and sufficient"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"C", solution:"$n$ even $\\Leftrightarrow n^2$ even, so the condition is both necessary and sufficient." },
  { id:"tmua-mk3-p2-15", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"In a group where everyone shakes hands with everyone else once there are $10$ handshakes. How many people are there?", options:[{key:"A",text:"$4$"},{key:"B",text:"$5$"},{key:"C",text:"$6$"},{key:"D",text:"$10$"},{key:"E",text:"$7$"}],
    answer:"B", solution:"$\\binom{n}{2}=10\\Rightarrow n(n-1)=20\\Rightarrow n=5.$" },
  { id:"tmua-mk3-p2-16", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"For a number to be greater than $100$, being greater than $200$ is:", options:[{key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"B", solution:"$>200\\Rightarrow>100$ (sufficient); but $>100$ does not force $>200$ (not necessary)." },
  { id:"tmua-mk3-p2-17", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The negation of 'there is a student who failed' is:", options:[{key:"A",text:"some student passed"},{key:"B",text:"every student passed"},{key:"C",text:"no student passed"},{key:"D",text:"most students failed"},{key:"E",text:"at least one failed"}],
    answer:"B", solution:"Negation of 'there exists $x$: failed' is 'for all $x$: not failed' — every student passed." },
  { id:"tmua-mk3-p2-18", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Is the converse of 'if a number ends in $5$ then it is divisible by $5$' true?", options:[{key:"A",text:"true"},{key:"B",text:"false; e.g. $10$"},{key:"C",text:"false; e.g. $25$"},{key:"D",text:"the same statement"},{key:"E",text:"true only for odd numbers"}],
    answer:"B", solution:"Converse: 'if divisible by 5 then ends in 5', false since $10$ is divisible by 5 but ends in $0.$" },
  { id:"tmua-mk3-p2-19", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"Using $2+4+\\cdots+2n=n(n+1)$, find $2+4+\\cdots+20$.", options:[{key:"A",text:"$100$"},{key:"B",text:"$110$"},{key:"C",text:"$120$"},{key:"D",text:"$90$"},{key:"E",text:"$210$"}],
    answer:"B", solution:"Last term $20=2n\\Rightarrow n=10$; sum $=10\\times11=110.$" },
  { id:"tmua-mk3-p2-20", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The condition '$x=2$' is ______ for '$x^2-4=0$'.", options:[{key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"B", solution:"$x=2\\Rightarrow x^2-4=0$ (sufficient), but $x=-2$ also works, so not necessary." },
];
