// TMUA 模拟卷八 —— 全新原创题，与卷一~七、练习题均不重复。两卷各 20 题、各 75 分钟、五选一、无负分。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const TMUA_MK8_P1: MCQQuestion[] = [
  { id:"tmua-mk8-p1-01", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The positive root of $x^2+x-6=0$ is:", options:[{key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$-3$"},{key:"D",text:"$6$"},{key:"E",text:"$1$"}],
    answer:"A", solution:"$(x+3)(x-2)=0$; positive root $2.$" },
  { id:"tmua-mk8-p1-02", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:1, marks:1,
    question:"Evaluate $16^{1/2}$.", options:[{key:"A",text:"$2$"},{key:"B",text:"$4$"},{key:"C",text:"$8$"},{key:"D",text:"$16$"},{key:"E",text:"$32$"}],
    answer:"B", solution:"$\\sqrt{16}=4.$" },
  { id:"tmua-mk8-p1-03", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Simplify $\\sqrt{72}-\\sqrt{18}$.", options:[{key:"A",text:"$3\\sqrt2$"},{key:"B",text:"$9\\sqrt2$"},{key:"C",text:"$\\sqrt{54}$"},{key:"D",text:"$2\\sqrt2$"},{key:"E",text:"$6\\sqrt2$"}],
    answer:"A", solution:"$6\\sqrt2-3\\sqrt2=3\\sqrt2.$" },
  { id:"tmua-mk8-p1-04", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:3, marks:1,
    question:"Find the sum of the first $6$ terms of $10+7+4+\\cdots$.", options:[{key:"A",text:"$15$"},{key:"B",text:"$12$"},{key:"C",text:"$18$"},{key:"D",text:"$9$"},{key:"E",text:"$21$"}],
    answer:"A", solution:"$a=10,d=-3$: $S_6=\\tfrac{6}{2}(20+5(-3))=3\\times5=15.$" },
  { id:"tmua-mk8-p1-05", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Evaluate $12+6+3+\\cdots$ (sum to infinity).", options:[{key:"A",text:"$24$"},{key:"B",text:"$18$"},{key:"C",text:"$12$"},{key:"D",text:"$36$"},{key:"E",text:"$48$"}],
    answer:"A", solution:"$\\dfrac{12}{1-\\tfrac12}=24.$" },
  { id:"tmua-mk8-p1-06", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"The gradient of the line through $(1,1)$ and $(5,3)$ is:", options:[{key:"A",text:"$\\tfrac12$"},{key:"B",text:"$2$"},{key:"C",text:"$1$"},{key:"D",text:"$4$"},{key:"E",text:"$\\tfrac14$"}],
    answer:"A", solution:"$\\tfrac{3-1}{5-1}=\\tfrac{2}{4}=\\tfrac12.$" },
  { id:"tmua-mk8-p1-07", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"The equation of the circle with centre $(-2,3)$ and radius $6$ is:", options:[{key:"A",text:"$(x+2)^2+(y-3)^2=36$"},{key:"B",text:"$(x-2)^2+(y+3)^2=36$"},{key:"C",text:"$(x+2)^2+(y-3)^2=6$"},{key:"D",text:"$(x-2)^2+(y-3)^2=36$"},{key:"E",text:"$(x+2)^2+(y+3)^2=36$"}],
    answer:"A", solution:"$(x-a)^2+(y-b)^2=r^2$: $(x+2)^2+(y-3)^2=36.$" },
  { id:"tmua-mk8-p1-08", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"Evaluate $\\tan 60^\\circ$.", options:[{key:"A",text:"$\\sqrt3$"},{key:"B",text:"$\\tfrac{1}{\\sqrt3}$"},{key:"C",text:"$1$"},{key:"D",text:"$\\tfrac12$"},{key:"E",text:"$\\tfrac{\\sqrt3}{2}$"}],
    answer:"A", solution:"$\\tan60^\\circ=\\sqrt3.$" },
  { id:"tmua-mk8-p1-09", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"If $\\sin\\theta=\\tfrac{8}{17}$ and $\\theta$ is acute, then $\\cos\\theta=$", options:[{key:"A",text:"$\\tfrac{15}{17}$"},{key:"B",text:"$\\tfrac{8}{17}$"},{key:"C",text:"$\\tfrac{17}{15}$"},{key:"D",text:"$\\tfrac{9}{17}$"},{key:"E",text:"$1$"}],
    answer:"A", solution:"$\\cos\\theta=\\sqrt{1-\\tfrac{64}{289}}=\\tfrac{15}{17}.$" },
  { id:"tmua-mk8-p1-10", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Solve $3^{x}=\\dfrac{1}{27}$.", options:[{key:"A",text:"$-3$"},{key:"B",text:"$3$"},{key:"C",text:"$-2$"},{key:"D",text:"$\\tfrac13$"},{key:"E",text:"$27$"}],
    answer:"A", solution:"$\\tfrac1{27}=3^{-3}$, so $x=-3.$" },
  { id:"tmua-mk8-p1-11", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:1, marks:1,
    question:"Evaluate $\\log_4 16$.", options:[{key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$4$"},{key:"D",text:"$16$"},{key:"E",text:"$8$"}],
    answer:"A", solution:"$16=4^2$, so $\\log_4 16=2.$" },
  { id:"tmua-mk8-p1-12", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Solve $\\log_5 x=2$.", options:[{key:"A",text:"$10$"},{key:"B",text:"$25$"},{key:"C",text:"$5$"},{key:"D",text:"$125$"},{key:"E",text:"$7$"}],
    answer:"B", solution:"$x=5^2=25.$" },
  { id:"tmua-mk8-p1-13", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"Find $\\dfrac{d}{dx}(2x^2-x)$ at $x=2$.", options:[{key:"A",text:"$7$"},{key:"B",text:"$8$"},{key:"C",text:"$6$"},{key:"D",text:"$5$"},{key:"E",text:"$3$"}],
    answer:"A", solution:"$4x-1$; at $x=2$, $7.$" },
  { id:"tmua-mk8-p1-14", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"The curve $y=x^2+4x$ has gradient zero at $x=$", options:[{key:"A",text:"$-2$"},{key:"B",text:"$2$"},{key:"C",text:"$0$"},{key:"D",text:"$-4$"},{key:"E",text:"$4$"}],
    answer:"A", solution:"$y'=2x+4=0\\Rightarrow x=-2.$" },
  { id:"tmua-mk8-p1-15", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"Evaluate $\\displaystyle\\int_1^2 6x^2\\,\\mathrm{d}x$.", options:[{key:"A",text:"$14$"},{key:"B",text:"$12$"},{key:"C",text:"$16$"},{key:"D",text:"$8$"},{key:"E",text:"$6$"}],
    answer:"A", solution:"$[2x^3]_1^2=16-2=14.$" },
  { id:"tmua-mk8-p1-16", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"The area under $y=4x$ from $x=0$ to $x=2$ is:", options:[{key:"A",text:"$8$"},{key:"B",text:"$4$"},{key:"C",text:"$16$"},{key:"D",text:"$2$"},{key:"E",text:"$12$"}],
    answer:"A", solution:"$\\int_0^2 4x\\,dx=[2x^2]_0^2=8.$" },
  { id:"tmua-mk8-p1-17", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The graph of $y=f(x-1)$ is $y=f(x)$ shifted:", options:[{key:"A",text:"right 1"},{key:"B",text:"left 1"},{key:"C",text:"up 1"},{key:"D",text:"down 1"},{key:"E",text:"right 1 and up 1"}],
    answer:"A", solution:"Replacing $x$ by $x-1$ shifts the graph $1$ to the right." },
  { id:"tmua-mk8-p1-18", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Given $f(x)=3x+1$ and $g(x)=x-2$, find $f(g(4))$.", options:[{key:"A",text:"$7$"},{key:"B",text:"$13$"},{key:"C",text:"$10$"},{key:"D",text:"$5$"},{key:"E",text:"$2$"}],
    answer:"A", solution:"$g(4)=2$, then $f(2)=7.$" },
  { id:"tmua-mk8-p1-19", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:1, marks:1,
    question:"Solve $2(x+1)<10$.", options:[{key:"A",text:"$x<4$"},{key:"B",text:"$x>4$"},{key:"C",text:"$x<5$"},{key:"D",text:"$x<9$"},{key:"E",text:"$x<3$"}],
    answer:"A", solution:"$x+1<5\\Rightarrow x<4.$" },
  { id:"tmua-mk8-p1-20", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The coefficient of $x$ in $(2+x)^3$ is:", options:[{key:"A",text:"$12$"},{key:"B",text:"$6$"},{key:"C",text:"$8$"},{key:"D",text:"$3$"},{key:"E",text:"$4$"}],
    answer:"A", solution:"$\\binom{3}{1}(2)^2=3\\times4=12.$" },
];

export const TMUA_MK8_P2: MCQQuestion[] = [
  { id:"tmua-mk8-p2-01", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"For an integer to be divisible by $25$, being divisible by $5$ is:", options:[{key:"A",text:"sufficient but not necessary"},{key:"B",text:"necessary but not sufficient"},{key:"C",text:"both"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"B", solution:"Divisible by 25 $\\Rightarrow$ divisible by 5 (necessary), but 10 is divisible by 5 not 25 (not sufficient)." },
  { id:"tmua-mk8-p2-02", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Is the converse of 'if $x=5$ then $x^2=25$' true?", options:[{key:"A",text:"true"},{key:"B",text:"false; e.g. $x=-5$"},{key:"C",text:"false; e.g. $x=25$"},{key:"D",text:"the same statement"},{key:"E",text:"undecidable"}],
    answer:"B", solution:"Converse: 'if $x^2=25$ then $x=5$', false since $x=-5$ also gives $x^2=25.$" },
  { id:"tmua-mk8-p2-03", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The contrapositive of 'if a shape is a square then it has four sides' is:", options:[{key:"A",text:"if a shape has four sides then it is a square"},{key:"B",text:"if a shape does not have four sides then it is not a square"},{key:"C",text:"if a shape is not a square then it does not have four sides"},{key:"D",text:"if a shape is a square then it has three sides"},{key:"E",text:"all four-sided shapes are squares"}],
    answer:"B", solution:"Contrapositive $\\lnot Q\\Rightarrow\\lnot P$: 'if not four sides then not a square'." },
  { id:"tmua-mk8-p2-04", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:1, marks:1,
    question:"Which value disproves 'all numbers greater than $2$ are prime'?", options:[{key:"A",text:"$3$"},{key:"B",text:"$4$"},{key:"C",text:"$5$"},{key:"D",text:"$7$"},{key:"E",text:"none"}],
    answer:"B", solution:"$4>2$ but $4$ is not prime — a counterexample." },
  { id:"tmua-mk8-p2-05", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The negation of 'there exists a real $x$ with $x^2=-1$' is:", options:[{key:"A",text:"there exists a real $x$ with $x^2\\ne-1$"},{key:"B",text:"for all real $x$, $x^2\\ne-1$"},{key:"C",text:"for all real $x$, $x^2=-1$"},{key:"D",text:"no real numbers exist"},{key:"E",text:"$x=1$"}],
    answer:"B", solution:"Negate 'there exists' to 'for all' with negated statement: for all real $x$, $x^2\\ne-1.$" },
  { id:"tmua-mk8-p2-06", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The negation of '$x=0$ or $x=3$' is:", options:[{key:"A",text:"$x\\ne0$ or $x\\ne3$"},{key:"B",text:"$x\\ne0$ and $x\\ne3$"},{key:"C",text:"$x=0$ and $x=3$"},{key:"D",text:"$x>3$"},{key:"E",text:"$x\\ne0$"}],
    answer:"B", solution:"not($A$ or $B$) $=$ not $A$ and not $B$: $x\\ne0$ and $x\\ne3.$" },
  { id:"tmua-mk8-p2-07", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"What is the truth value of 'if $5>4$ then $3>7$'?", options:[{key:"A",text:"true"},{key:"B",text:"false"},{key:"C",text:"undefined"},{key:"D",text:"depends on other facts"},{key:"E",text:"cannot be evaluated"}],
    answer:"B", solution:"The hypothesis $5>4$ is true but the conclusion $3>7$ is false, so the implication is false." },
  { id:"tmua-mk8-p2-08", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:1, marks:1,
    question:"Given $A\\Rightarrow B$ and $B\\Rightarrow C$ are true and $A$ is true, which must hold?", options:[{key:"A",text:"only $B$"},{key:"B",text:"$C$"},{key:"C",text:"neither"},{key:"D",text:"$\\lnot C$"},{key:"E",text:"$\\lnot A$"}],
    answer:"B", solution:"Chaining from $A$: $B$ then $C$; in particular $C$ holds." },
  { id:"tmua-mk8-p2-09", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:3, marks:1,
    question:"A student writes $\\sqrt{a^2+b^2}=a+b$. The error is that:", options:[{key:"A",text:"the square root does not distribute over addition"},{key:"B",text:"it divides by zero"},{key:"C",text:"there is no error"},{key:"D",text:"it assumes $a=b$"},{key:"E",text:"$a^2+b^2$ is always negative"}],
    answer:"A", solution:"$\\sqrt{a^2+b^2}\\ne a+b$ in general (e.g. $a=b=1$: $\\sqrt2\\ne2$); the root does not split over a sum." },
  { id:"tmua-mk8-p2-10", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"'Since $x^2=y^2$, therefore $x=y$.' The flaw is that it:", options:[{key:"A",text:"ignores the possibility $x=-y$"},{key:"B",text:"divides by zero"},{key:"C",text:"has no flaw"},{key:"D",text:"assumes $x,y>0$ correctly"},{key:"E",text:"uses the contrapositive"}],
    answer:"A", solution:"$x^2=y^2\\Rightarrow x=\\pm y$; the deduction overlooks $x=-y.$" },
  { id:"tmua-mk8-p2-11", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Assuming there are only finitely many primes and deriving a contradiction is:", options:[{key:"A",text:"proof by contradiction"},{key:"B",text:"proof by cases"},{key:"C",text:"disproof by counterexample"},{key:"D",text:"direct proof"},{key:"E",text:"a converse argument"}],
    answer:"A", solution:"Assuming the negation of the claim to reach a contradiction is proof by contradiction (Euclid's argument)." },
  { id:"tmua-mk8-p2-12", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Proving a claim by treating $n$ even and $n$ odd separately is:", options:[{key:"A",text:"proof by contradiction"},{key:"B",text:"proof by cases"},{key:"C",text:"disproof by counterexample"},{key:"D",text:"a converse argument"},{key:"E",text:"circular reasoning"}],
    answer:"B", solution:"Exhaustive even/odd cases is proof by cases." },
  { id:"tmua-mk8-p2-13", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"The $n$-th term of $1,2,4,8,16,\\ldots$ is:", options:[{key:"A",text:"$2^{n-1}$"},{key:"B",text:"$2^n$"},{key:"C",text:"$n^2$"},{key:"D",text:"$2n-1$"},{key:"E",text:"$n!$"}],
    answer:"A", solution:"Geometric with first term $1$ and ratio $2$: $u_n=2^{n-1}.$" },
  { id:"tmua-mk8-p2-14", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:3, marks:1,
    question:"For real $x$, the condition '$x^2=4$' is ______ for '$|x|=2$'.", options:[{key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both necessary and sufficient"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"C", solution:"$x^2=4\\Leftrightarrow x=\\pm2\\Leftrightarrow|x|=2$: the conditions are equivalent." },
  { id:"tmua-mk8-p2-15", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"Everyone in a group shakes hands once with everyone else, giving $28$ handshakes. How many people are there?", options:[{key:"A",text:"$7$"},{key:"B",text:"$8$"},{key:"C",text:"$9$"},{key:"D",text:"$28$"},{key:"E",text:"$14$"}],
    answer:"B", solution:"$\\binom{n}{2}=28\\Rightarrow n(n-1)=56\\Rightarrow n=8.$" },
  { id:"tmua-mk8-p2-16", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"For '$x>0$', the condition '$x>-1$' is:", options:[{key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"A", solution:"$x>0\\Rightarrow x>-1$, so $x>-1$ is necessary; but $x>-1$ does not force $x>0$ (e.g. $x=-\\tfrac12$), so not sufficient." },
  { id:"tmua-mk8-p2-17", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The negation of 'all birds can fly' is:", options:[{key:"A",text:"no birds can fly"},{key:"B",text:"at least one bird cannot fly"},{key:"C",text:"all birds cannot fly"},{key:"D",text:"some birds can fly"},{key:"E",text:"birds do not exist"}],
    answer:"B", solution:"Negation of 'for all $x$: $P$' is 'there exists $x$: not $P$'." },
  { id:"tmua-mk8-p2-18", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"Which value shows 'if $n>10$ then $n>20$' is false?", options:[{key:"A",text:"$15$"},{key:"B",text:"$25$"},{key:"C",text:"$30$"},{key:"D",text:"$5$"},{key:"E",text:"none"}],
    answer:"A", solution:"$15>10$ but $15\\not>20$ — a counterexample." },
  { id:"tmua-mk8-p2-19", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"Using $1+3+5+\\cdots+(2n-1)=n^2$, find $1+3+5+\\cdots+29$.", options:[{key:"A",text:"$225$"},{key:"B",text:"$196$"},{key:"C",text:"$256$"},{key:"D",text:"$210$"},{key:"E",text:"$289$"}],
    answer:"A", solution:"Last term $29=2n-1\\Rightarrow n=15$; sum $=15^2=225.$" },
  { id:"tmua-mk8-p2-20", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:3, marks:1,
    question:"Being divisible by $4$ is ______ for being even.", options:[{key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both necessary and sufficient"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"B", solution:"Divisible by 4 $\\Rightarrow$ even (sufficient); but $6$ is even without being divisible by 4 (not necessary)." },
];
