// TMUA 模拟卷九 —— 全新原创题，与卷一~八、练习题均不重复。两卷各 20 题、各 75 分钟、五选一、无负分。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const TMUA_MK9_P1: MCQQuestion[] = [
  { id:"tmua-mk9-p1-01", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The smaller root of $x^2-11x+30=0$ is:", options:[{key:"A",text:"$5$"},{key:"B",text:"$6$"},{key:"C",text:"$11$"},{key:"D",text:"$30$"},{key:"E",text:"$1$"}],
    answer:"A", solution:"$(x-5)(x-6)=0$; smaller root $5.$" },
  { id:"tmua-mk9-p1-02", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Evaluate $81^{3/4}$.", options:[{key:"A",text:"$9$"},{key:"B",text:"$27$"},{key:"C",text:"$3$"},{key:"D",text:"$81$"},{key:"E",text:"$243$"}],
    answer:"B", solution:"$81^{1/4}=3$, then $3^3=27.$" },
  { id:"tmua-mk9-p1-03", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Simplify $\\sqrt{80}-\\sqrt{20}$.", options:[{key:"A",text:"$2\\sqrt5$"},{key:"B",text:"$6\\sqrt5$"},{key:"C",text:"$\\sqrt{60}$"},{key:"D",text:"$\\sqrt5$"},{key:"E",text:"$4\\sqrt5$"}],
    answer:"A", solution:"$4\\sqrt5-2\\sqrt5=2\\sqrt5.$" },
  { id:"tmua-mk9-p1-04", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Find the sum of the first $9$ terms of $6+10+14+\\cdots$.", options:[{key:"A",text:"$198$"},{key:"B",text:"$180$"},{key:"C",text:"$216$"},{key:"D",text:"$200$"},{key:"E",text:"$190$"}],
    answer:"A", solution:"$a=6,d=4$: $S_9=\\tfrac{9}{2}(12+8\\cdot4)=\\tfrac{9}{2}\\times44=198.$" },
  { id:"tmua-mk9-p1-05", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The $4$th term of the geometric sequence $5,10,20,\\ldots$ is:", options:[{key:"A",text:"$40$"},{key:"B",text:"$20$"},{key:"C",text:"$80$"},{key:"D",text:"$30$"},{key:"E",text:"$60$"}],
    answer:"A", solution:"$ar^3=5\\cdot2^3=40.$" },
  { id:"tmua-mk9-p1-06", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"The gradient of the line through $(0,-2)$ and $(3,7)$ is:", options:[{key:"A",text:"$3$"},{key:"B",text:"$2$"},{key:"C",text:"$9$"},{key:"D",text:"$1$"},{key:"E",text:"$\\tfrac13$"}],
    answer:"A", solution:"$\\tfrac{7-(-2)}{3-0}=\\tfrac{9}{3}=3.$" },
  { id:"tmua-mk9-p1-07", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:3, marks:1,
    question:"The radius of the circle $x^2+y^2-8x+2y+8=0$ is:", options:[{key:"A",text:"$3$"},{key:"B",text:"$9$"},{key:"C",text:"$\\sqrt8$"},{key:"D",text:"$4$"},{key:"E",text:"$5$"}],
    answer:"A", solution:"$(x-4)^2+(y+1)^2=16+1-8=9$, so $r=3.$" },
  { id:"tmua-mk9-p1-08", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"Evaluate $\\cos 60^\\circ$.", options:[{key:"A",text:"$\\tfrac12$"},{key:"B",text:"$\\tfrac{\\sqrt3}{2}$"},{key:"C",text:"$1$"},{key:"D",text:"$0$"},{key:"E",text:"$\\tfrac{\\sqrt2}{2}$"}],
    answer:"A", solution:"$\\cos60^\\circ=\\tfrac12.$" },
  { id:"tmua-mk9-p1-09", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"If $\\cos\\theta=\\tfrac{7}{25}$ and $\\theta$ is acute, then $\\sin\\theta=$", options:[{key:"A",text:"$\\tfrac{24}{25}$"},{key:"B",text:"$\\tfrac{7}{25}$"},{key:"C",text:"$\\tfrac{25}{24}$"},{key:"D",text:"$\\tfrac{18}{25}$"},{key:"E",text:"$1$"}],
    answer:"A", solution:"$\\sin\\theta=\\sqrt{1-\\tfrac{49}{625}}=\\sqrt{\\tfrac{576}{625}}=\\tfrac{24}{25}.$" },
  { id:"tmua-mk9-p1-10", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:1, marks:1,
    question:"Solve $2^{x}=128$.", options:[{key:"A",text:"$6$"},{key:"B",text:"$7$"},{key:"C",text:"$8$"},{key:"D",text:"$64$"},{key:"E",text:"$14$"}],
    answer:"B", solution:"$128=2^7$, so $x=7.$" },
  { id:"tmua-mk9-p1-11", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:1, marks:1,
    question:"Evaluate $\\log_{10}100$.", options:[{key:"A",text:"$1$"},{key:"B",text:"$2$"},{key:"C",text:"$10$"},{key:"D",text:"$100$"},{key:"E",text:"$3$"}],
    answer:"B", solution:"$100=10^2$, so $\\log_{10}100=2.$" },
  { id:"tmua-mk9-p1-12", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Solve $\\log_3 x=3$.", options:[{key:"A",text:"$9$"},{key:"B",text:"$27$"},{key:"C",text:"$81$"},{key:"D",text:"$6$"},{key:"E",text:"$3$"}],
    answer:"B", solution:"$x=3^3=27.$" },
  { id:"tmua-mk9-p1-13", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"Find $\\dfrac{d}{dx}(3x^2-2x)$ at $x=1$.", options:[{key:"A",text:"$4$"},{key:"B",text:"$6$"},{key:"C",text:"$3$"},{key:"D",text:"$2$"},{key:"E",text:"$5$"}],
    answer:"A", solution:"$6x-2$; at $x=1$, $4.$" },
  { id:"tmua-mk9-p1-14", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"The gradient of $y=6x^2$ at $x=1$ is:", options:[{key:"A",text:"$6$"},{key:"B",text:"$12$"},{key:"C",text:"$1$"},{key:"D",text:"$36$"},{key:"E",text:"$2$"}],
    answer:"B", solution:"$y'=12x=12$ at $x=1.$" },
  { id:"tmua-mk9-p1-15", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"Evaluate $\\displaystyle\\int_0^4 x\\,\\mathrm{d}x$.", options:[{key:"A",text:"$4$"},{key:"B",text:"$8$"},{key:"C",text:"$16$"},{key:"D",text:"$2$"},{key:"E",text:"$12$"}],
    answer:"B", solution:"$\\left[\\tfrac{x^2}{2}\\right]_0^4=8.$" },
  { id:"tmua-mk9-p1-16", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"The area under $y=2x^2$ from $x=0$ to $x=3$ is:", options:[{key:"A",text:"$9$"},{key:"B",text:"$18$"},{key:"C",text:"$12$"},{key:"D",text:"$6$"},{key:"E",text:"$27$"}],
    answer:"B", solution:"$\\int_0^3 2x^2\\,dx=\\left[\\tfrac{2x^3}{3}\\right]_0^3=18.$" },
  { id:"tmua-mk9-p1-17", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The graph of $y=f(x)-3$ is $y=f(x)$ shifted:", options:[{key:"A",text:"down 3"},{key:"B",text:"up 3"},{key:"C",text:"left 3"},{key:"D",text:"right 3"},{key:"E",text:"down 3 and left 3"}],
    answer:"A", solution:"Subtracting $3$ from the output shifts the graph down by $3.$" },
  { id:"tmua-mk9-p1-18", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Given $f(x)=x^2+1$ and $g(x)=x-1$, find $f(g(3))$.", options:[{key:"A",text:"$5$"},{key:"B",text:"$10$"},{key:"C",text:"$4$"},{key:"D",text:"$8$"},{key:"E",text:"$9$"}],
    answer:"A", solution:"$g(3)=2$, then $f(2)=5.$" },
  { id:"tmua-mk9-p1-19", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:1, marks:1,
    question:"Solve $3x+4\\le16$.", options:[{key:"A",text:"$x\\le4$"},{key:"B",text:"$x\\ge4$"},{key:"C",text:"$x\\le12$"},{key:"D",text:"$x<4$"},{key:"E",text:"$x\\le6$"}],
    answer:"A", solution:"$3x\\le12\\Rightarrow x\\le4.$" },
  { id:"tmua-mk9-p1-20", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The coefficient of $x^3$ in $(1+x)^4$ is:", options:[{key:"A",text:"$4$"},{key:"B",text:"$6$"},{key:"C",text:"$1$"},{key:"D",text:"$8$"},{key:"E",text:"$12$"}],
    answer:"A", solution:"$\\binom{4}{3}=4.$" },
];

export const TMUA_MK9_P2: MCQQuestion[] = [
  { id:"tmua-mk9-p2-01", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"For an integer to be divisible by $20$, being divisible by $4$ is:", options:[{key:"A",text:"sufficient but not necessary"},{key:"B",text:"necessary but not sufficient"},{key:"C",text:"both"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"B", solution:"Divisible by 20 $\\Rightarrow$ divisible by 4 (necessary), but 8 is divisible by 4 not 20 (not sufficient)." },
  { id:"tmua-mk9-p2-02", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Is the converse of 'if $n$ is divisible by $10$ then $n$ is divisible by $5$' true?", options:[{key:"A",text:"true"},{key:"B",text:"false; e.g. $n=15$"},{key:"C",text:"false; e.g. $n=20$"},{key:"D",text:"the same statement"},{key:"E",text:"true only for even $n$"}],
    answer:"B", solution:"Converse: 'if divisible by 5 then divisible by 10', false since $15$ is divisible by 5 not 10." },
  { id:"tmua-mk9-p2-03", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:3, marks:1,
    question:"The contrapositive of 'if $x$ is even then $x^2$ is even' is:", options:[{key:"A",text:"if $x^2$ is even then $x$ is even"},{key:"B",text:"if $x^2$ is odd then $x$ is odd"},{key:"C",text:"if $x$ is odd then $x^2$ is odd"},{key:"D",text:"if $x$ is even then $x^2$ is odd"},{key:"E",text:"if $x^2$ is even then $x$ is odd"}],
    answer:"B", solution:"Contrapositive $\\lnot Q\\Rightarrow\\lnot P$: 'if $x^2$ is odd (not even) then $x$ is odd (not even)'." },
  { id:"tmua-mk9-p2-04", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:1, marks:1,
    question:"Which value disproves 'all multiples of $5$ end in $5$'?", options:[{key:"A",text:"$5$"},{key:"B",text:"$10$"},{key:"C",text:"$15$"},{key:"D",text:"$25$"},{key:"E",text:"none"}],
    answer:"B", solution:"$10$ is a multiple of $5$ but ends in $0$ — a counterexample." },
  { id:"tmua-mk9-p2-05", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The negation of 'for all integers $n$, $n^2\\ge n$' is:", options:[{key:"A",text:"for all $n$, $n^2<n$"},{key:"B",text:"there exists an integer $n$ with $n^2<n$"},{key:"C",text:"there exists an integer $n$ with $n^2\\ge n$"},{key:"D",text:"no integer exists"},{key:"E",text:"$n^2=n$"}],
    answer:"B", solution:"Negate 'for all' to 'there exists' with the inequality negated: some $n$ with $n^2<n.$" },
  { id:"tmua-mk9-p2-06", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The negation of '$x\\ge1$ and $x\\le10$' is:", options:[{key:"A",text:"$x<1$ or $x>10$"},{key:"B",text:"$x<1$ and $x>10$"},{key:"C",text:"$x\\le1$ or $x\\ge10$"},{key:"D",text:"$1<x<10$"},{key:"E",text:"$x\\ne1$"}],
    answer:"A", solution:"not($A$ and $B$) $=$ not $A$ or not $B$: $x<1$ or $x>10.$" },
  { id:"tmua-mk9-p2-07", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:3, marks:1,
    question:"If both $P$ and $Q$ are false, what is the truth value of '$P\\Rightarrow Q$'?", options:[{key:"A",text:"true (vacuously)"},{key:"B",text:"false"},{key:"C",text:"depends on $Q$"},{key:"D",text:"undefined"},{key:"E",text:"depends on both"}],
    answer:"A", solution:"An implication with a false hypothesis is vacuously true, regardless of $Q.$" },
  { id:"tmua-mk9-p2-08", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Given $P\\Rightarrow Q$ and $Q\\Rightarrow R$ are true and $R$ is false, what follows?", options:[{key:"A",text:"$P$ is true"},{key:"B",text:"$P$ is false"},{key:"C",text:"$Q$ is true"},{key:"D",text:"nothing"},{key:"E",text:"$R$ is true"}],
    answer:"B", solution:"Contrapositive chain $\\lnot R\\Rightarrow\\lnot Q\\Rightarrow\\lnot P$; so $P$ is false." },
  { id:"tmua-mk9-p2-09", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:3, marks:1,
    question:"'Since $\\tfrac{a}{b}=\\tfrac{c}{d}$, it follows that $a=c$ and $b=d$.' The flaw is that:", options:[{key:"A",text:"equal fractions need not have equal numerators and denominators"},{key:"B",text:"it divides by zero"},{key:"C",text:"there is no flaw"},{key:"D",text:"fractions cannot be equal"},{key:"E",text:"it assumes $b=d$"}],
    answer:"A", solution:"For example $\\tfrac12=\\tfrac24$, yet $1\\ne2$ and $2\\ne4$; equal value does not force equal numerator/denominator." },
  { id:"tmua-mk9-p2-10", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"'Every multiple of $4$ is even, therefore every even number is a multiple of $4$.' The error is:", options:[{key:"A",text:"a false premise"},{key:"B",text:"assuming the converse"},{key:"C",text:"dividing by zero"},{key:"D",text:"proof by contradiction"},{key:"E",text:"a counterexample"}],
    answer:"B", solution:"Deducing $Q\\Rightarrow P$ from $P\\Rightarrow Q$ assumes the converse, which is invalid (e.g. $6$ is even but not a multiple of 4)." },
  { id:"tmua-mk9-p2-11", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:1, marks:1,
    question:"Rejecting a universal claim by exhibiting the case $n=8$ is:", options:[{key:"A",text:"proof by contradiction"},{key:"B",text:"disproof by counterexample"},{key:"C",text:"proof by cases"},{key:"D",text:"direct proof"},{key:"E",text:"induction"}],
    answer:"B", solution:"One failing case disproves a 'for all' statement." },
  { id:"tmua-mk9-p2-12", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Proving a result by treating $n=4k,\\,4k+1,\\,4k+2,\\,4k+3$ separately is:", options:[{key:"A",text:"proof by contradiction"},{key:"B",text:"proof by cases"},{key:"C",text:"disproof by counterexample"},{key:"D",text:"a converse argument"},{key:"E",text:"circular reasoning"}],
    answer:"B", solution:"Exhausting all residue classes mod 4 is proof by cases." },
  { id:"tmua-mk9-p2-13", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"The $n$-th term of $4,7,10,13,\\ldots$ is:", options:[{key:"A",text:"$3n+1$"},{key:"B",text:"$3n$"},{key:"C",text:"$4n$"},{key:"D",text:"$2n+2$"},{key:"E",text:"$n^2+3$"}],
    answer:"A", solution:"Arithmetic $a=4,d=3$: $u_n=4+(n-1)3=3n+1.$" },
  { id:"tmua-mk9-p2-14", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The condition '$x=-3$' is ______ for '$x+3=0$'.", options:[{key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both necessary and sufficient"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"C", solution:"$x=-3\\Leftrightarrow x+3=0$: the conditions are equivalent." },
  { id:"tmua-mk9-p2-15", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"Everyone in a group shakes hands once with everyone else, giving $36$ handshakes. How many people are there?", options:[{key:"A",text:"$8$"},{key:"B",text:"$9$"},{key:"C",text:"$10$"},{key:"D",text:"$36$"},{key:"E",text:"$12$"}],
    answer:"B", solution:"$\\binom{n}{2}=36\\Rightarrow n(n-1)=72\\Rightarrow n=9.$" },
  { id:"tmua-mk9-p2-16", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"For '$x<10$', the condition '$x<5$' is:", options:[{key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"B", solution:"$x<5\\Rightarrow x<10$ (sufficient); $x<10$ does not force $x<5$ (not necessary)." },
  { id:"tmua-mk9-p2-17", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The negation of 'every integer is positive' is:", options:[{key:"A",text:"every integer is negative"},{key:"B",text:"at least one integer is not positive"},{key:"C",text:"no integer is positive"},{key:"D",text:"some integer is positive"},{key:"E",text:"integers do not exist"}],
    answer:"B", solution:"Negation of 'for all $x$: positive' is 'there exists $x$: not positive'." },
  { id:"tmua-mk9-p2-18", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"Which value shows 'if $n$ is a multiple of $3$ then $n$ is a multiple of $9$' is false?", options:[{key:"A",text:"$3$"},{key:"B",text:"$9$"},{key:"C",text:"$18$"},{key:"D",text:"$27$"},{key:"E",text:"none"}],
    answer:"A", solution:"$3$ is a multiple of $3$ but not of $9$ — a counterexample." },
  { id:"tmua-mk9-p2-19", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"Using $2+4+\\cdots+2n=n(n+1)$, find $2+4+\\cdots+50$.", options:[{key:"A",text:"$650$"},{key:"B",text:"$600$"},{key:"C",text:"$625$"},{key:"D",text:"$675$"},{key:"E",text:"$325$"}],
    answer:"A", solution:"Last term $50=2n\\Rightarrow n=25$; sum $=25\\times26=650.$" },
  { id:"tmua-mk9-p2-20", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:3, marks:1,
    question:"Being a multiple of $10$ is ______ for being even.", options:[{key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both necessary and sufficient"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"B", solution:"A multiple of $10$ is even (sufficient); but $4$ is even without being a multiple of $10$ (not necessary)." },
];
