// TMUA 模拟卷十（收官）—— 全新原创题，与卷一~九、练习题均不重复。两卷各 20 题、各 75 分钟、五选一、无负分。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const TMUA_MK10_P1: MCQQuestion[] = [
  { id:"tmua-mk10-p1-01", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The larger root of $x^2+5x+6=0$ is:", options:[{key:"A",text:"$-2$"},{key:"B",text:"$-3$"},{key:"C",text:"$2$"},{key:"D",text:"$3$"},{key:"E",text:"$6$"}],
    answer:"A", solution:"$(x+2)(x+3)=0$; roots $-2,-3$; larger is $-2.$" },
  { id:"tmua-mk10-p1-02", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Evaluate $100^{3/2}$.", options:[{key:"A",text:"$100$"},{key:"B",text:"$1000$"},{key:"C",text:"$10$"},{key:"D",text:"$10000$"},{key:"E",text:"$300$"}],
    answer:"B", solution:"$100^{1/2}=10$, then $10^3=1000.$" },
  { id:"tmua-mk10-p1-03", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Simplify $\\sqrt{98}+\\sqrt{2}$.", options:[{key:"A",text:"$8\\sqrt2$"},{key:"B",text:"$7\\sqrt2$"},{key:"C",text:"$10$"},{key:"D",text:"$6\\sqrt2$"},{key:"E",text:"$9\\sqrt2$"}],
    answer:"A", solution:"$7\\sqrt2+\\sqrt2=8\\sqrt2.$" },
  { id:"tmua-mk10-p1-04", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Find the sum of the first $7$ terms of $3+6+9+\\cdots$.", options:[{key:"A",text:"$84$"},{key:"B",text:"$77$"},{key:"C",text:"$91$"},{key:"D",text:"$70$"},{key:"E",text:"$88$"}],
    answer:"A", solution:"$a=3,d=3$: $S_7=\\tfrac{7}{2}(6+6\\cdot3)=\\tfrac{7}{2}\\times24=84.$" },
  { id:"tmua-mk10-p1-05", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Evaluate $16+8+4+\\cdots$ (sum to infinity).", options:[{key:"A",text:"$32$"},{key:"B",text:"$24$"},{key:"C",text:"$16$"},{key:"D",text:"$48$"},{key:"E",text:"$64$"}],
    answer:"A", solution:"$\\dfrac{16}{1-\\tfrac12}=32.$" },
  { id:"tmua-mk10-p1-06", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"The gradient of the line through $(1,2)$ and $(4,2)$ is:", options:[{key:"A",text:"$0$"},{key:"B",text:"$1$"},{key:"C",text:"$3$"},{key:"D",text:"undefined"},{key:"E",text:"$-1$"}],
    answer:"A", solution:"Equal $y$-values give a horizontal line: gradient $0.$" },
  { id:"tmua-mk10-p1-07", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"The equation of the circle with centre $(0,0)$ and radius $7$ is:", options:[{key:"A",text:"$x^2+y^2=49$"},{key:"B",text:"$x^2+y^2=7$"},{key:"C",text:"$(x-7)^2+y^2=49$"},{key:"D",text:"$x^2+y^2=14$"},{key:"E",text:"$x^2-y^2=49$"}],
    answer:"A", solution:"Centre origin, radius $7$: $x^2+y^2=7^2=49.$" },
  { id:"tmua-mk10-p1-08", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"Evaluate $\\sin 45^\\circ$.", options:[{key:"A",text:"$\\tfrac{\\sqrt2}{2}$"},{key:"B",text:"$\\tfrac12$"},{key:"C",text:"$\\tfrac{\\sqrt3}{2}$"},{key:"D",text:"$1$"},{key:"E",text:"$0$"}],
    answer:"A", solution:"$\\sin45^\\circ=\\tfrac{\\sqrt2}{2}=\\tfrac{1}{\\sqrt2}.$" },
  { id:"tmua-mk10-p1-09", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"If $\\tan\\theta=1$ and $\\theta$ is acute, then $\\theta=$", options:[{key:"A",text:"$45^\\circ$"},{key:"B",text:"$30^\\circ$"},{key:"C",text:"$60^\\circ$"},{key:"D",text:"$90^\\circ$"},{key:"E",text:"$0^\\circ$"}],
    answer:"A", solution:"$\\tan45^\\circ=1.$" },
  { id:"tmua-mk10-p1-10", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:1, marks:1,
    question:"Solve $4^{x}=16$.", options:[{key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$4$"},{key:"D",text:"$8$"},{key:"E",text:"$1$"}],
    answer:"A", solution:"$16=4^2$, so $x=2.$" },
  { id:"tmua-mk10-p1-11", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:1, marks:1,
    question:"Evaluate $\\log_2 16$.", options:[{key:"A",text:"$3$"},{key:"B",text:"$4$"},{key:"C",text:"$5$"},{key:"D",text:"$16$"},{key:"E",text:"$2$"}],
    answer:"B", solution:"$16=2^4$, so $\\log_2 16=4.$" },
  { id:"tmua-mk10-p1-12", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Solve $\\log_4 x=2$.", options:[{key:"A",text:"$8$"},{key:"B",text:"$16$"},{key:"C",text:"$4$"},{key:"D",text:"$6$"},{key:"E",text:"$2$"}],
    answer:"B", solution:"$x=4^2=16.$" },
  { id:"tmua-mk10-p1-13", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"Find $\\dfrac{d}{dx}(x^2-5x+2)$ at $x=2$.", options:[{key:"A",text:"$-1$"},{key:"B",text:"$1$"},{key:"C",text:"$2$"},{key:"D",text:"$-5$"},{key:"E",text:"$4$"}],
    answer:"A", solution:"$2x-5$; at $x=2$, $-1.$" },
  { id:"tmua-mk10-p1-14", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"The curve $y=x^2-6x$ has gradient zero at $x=$", options:[{key:"A",text:"$3$"},{key:"B",text:"$6$"},{key:"C",text:"$0$"},{key:"D",text:"$-3$"},{key:"E",text:"$2$"}],
    answer:"A", solution:"$y'=2x-6=0\\Rightarrow x=3.$" },
  { id:"tmua-mk10-p1-15", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"Evaluate $\\displaystyle\\int_0^2 3x^2\\,\\mathrm{d}x$.", options:[{key:"A",text:"$6$"},{key:"B",text:"$8$"},{key:"C",text:"$12$"},{key:"D",text:"$4$"},{key:"E",text:"$24$"}],
    answer:"B", solution:"$[x^3]_0^2=8.$" },
  { id:"tmua-mk10-p1-16", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"The area under $y=x$ from $x=0$ to $x=6$ is:", options:[{key:"A",text:"$18$"},{key:"B",text:"$12$"},{key:"C",text:"$36$"},{key:"D",text:"$6$"},{key:"E",text:"$9$"}],
    answer:"A", solution:"$\\int_0^6 x\\,dx=\\left[\\tfrac{x^2}{2}\\right]_0^6=18.$" },
  { id:"tmua-mk10-p1-17", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The graph of $y=f(-x)$ is $y=f(x)$ reflected in the:", options:[{key:"A",text:"$y$-axis"},{key:"B",text:"$x$-axis"},{key:"C",text:"origin"},{key:"D",text:"line $y=x$"},{key:"E",text:"line $x=1$"}],
    answer:"A", solution:"Replacing $x$ by $-x$ reflects the graph in the $y$-axis." },
  { id:"tmua-mk10-p1-18", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Given $f(x)=2x$ and $g(x)=x+4$, find $f(g(1))$.", options:[{key:"A",text:"$10$"},{key:"B",text:"$6$"},{key:"C",text:"$8$"},{key:"D",text:"$9$"},{key:"E",text:"$14$"}],
    answer:"A", solution:"$g(1)=5$, then $f(5)=10.$" },
  { id:"tmua-mk10-p1-19", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:1, marks:1,
    question:"Solve $6-x\\ge2$.", options:[{key:"A",text:"$x\\le4$"},{key:"B",text:"$x\\ge4$"},{key:"C",text:"$x\\le8$"},{key:"D",text:"$x<4$"},{key:"E",text:"$x\\le-4$"}],
    answer:"A", solution:"$-x\\ge-4\\Rightarrow x\\le4.$" },
  { id:"tmua-mk10-p1-20", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The coefficient of $x^2$ in $(3+x)^3$ is:", options:[{key:"A",text:"$9$"},{key:"B",text:"$6$"},{key:"C",text:"$3$"},{key:"D",text:"$27$"},{key:"E",text:"$12$"}],
    answer:"A", solution:"$\\binom{3}{2}(3)^1=3\\times3=9.$" },
];

export const TMUA_MK10_P2: MCQQuestion[] = [
  { id:"tmua-mk10-p2-01", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"For an integer to be divisible by $100$, being divisible by $10$ is:", options:[{key:"A",text:"sufficient but not necessary"},{key:"B",text:"necessary but not sufficient"},{key:"C",text:"both"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"B", solution:"Divisible by 100 $\\Rightarrow$ divisible by 10 (necessary), but 30 is divisible by 10 not 100 (not sufficient)." },
  { id:"tmua-mk10-p2-02", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Is the converse of 'if $x=2$ then $x^2=4$' true?", options:[{key:"A",text:"true"},{key:"B",text:"false; e.g. $x=-2$"},{key:"C",text:"false; e.g. $x=4$"},{key:"D",text:"the same statement"},{key:"E",text:"undecidable"}],
    answer:"B", solution:"Converse: 'if $x^2=4$ then $x=2$', false since $x=-2$ also gives $x^2=4.$" },
  { id:"tmua-mk10-p2-03", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The contrapositive of 'if $n>10$ then $n>5$' is:", options:[{key:"A",text:"if $n>5$ then $n>10$"},{key:"B",text:"if $n\\le5$ then $n\\le10$"},{key:"C",text:"if $n\\le10$ then $n\\le5$"},{key:"D",text:"if $n>10$ then $n\\le5$"},{key:"E",text:"if $n\\le5$ then $n>10$"}],
    answer:"B", solution:"Contrapositive $\\lnot Q\\Rightarrow\\lnot P$: 'if $n\\le5$ then $n\\le10$'." },
  { id:"tmua-mk10-p2-04", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:1, marks:1,
    question:"Which integer disproves 'if $n$ is divisible by $4$, then $n$ is divisible by $8$'?", options:[{key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$8$"},{key:"D",text:"$4$"},{key:"E",text:"$16$"}],
    answer:"D", solution:"At $n=4$ the hypothesis is true but the conclusion is false, so $4$ is a counterexample." },
  { id:"tmua-mk10-p2-05", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The negation of 'there exists a real $x$ with $x^2+1=0$' is:", options:[{key:"A",text:"there exists a real $x$ with $x^2+1\\ne0$"},{key:"B",text:"for all real $x$, $x^2+1\\ne0$"},{key:"C",text:"for all real $x$, $x^2+1=0$"},{key:"D",text:"no real numbers exist"},{key:"E",text:"$x=1$"}],
    answer:"B", solution:"Negate 'there exists' to 'for all' with negated statement: for all real $x$, $x^2+1\\ne0.$" },
  { id:"tmua-mk10-p2-06", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The negation of '$x\\le0$ or $x\\ge5$' is:", options:[{key:"A",text:"$x>0$ and $x<5$"},{key:"B",text:"$0<x<5$"},{key:"C",text:"$x>0$ or $x<5$"},{key:"D",text:"$x\\ge0$ and $x\\le5$"},{key:"E",text:"$x\\ne0$"}],
    answer:"B", solution:"not($A$ or $B$) $=$ not $A$ and not $B$: $x>0$ and $x<5$, i.e. $0<x<5.$" },
  { id:"tmua-mk10-p2-07", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:1, marks:1,
    question:"What is the truth value of 'if $3>2$ then $4>1$'?", options:[{key:"A",text:"true"},{key:"B",text:"false"},{key:"C",text:"undefined"},{key:"D",text:"depends on other facts"},{key:"E",text:"cannot be evaluated"}],
    answer:"A", solution:"Both hypothesis and conclusion are true, so the implication is true." },
  { id:"tmua-mk10-p2-08", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Given $A\\Rightarrow B$, $B\\Rightarrow C$, $C\\Rightarrow D$ are true and $A$ is true, which must hold?", options:[{key:"A",text:"only $B$"},{key:"B",text:"only $C$"},{key:"C",text:"$D$"},{key:"D",text:"$\\lnot D$"},{key:"E",text:"nothing"}],
    answer:"C", solution:"Chaining from $A$ through $B,C$ gives $D$; in particular $D$ holds." },
  { id:"tmua-mk10-p2-09", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"'Since $x^2=x$, divide by $x$ to get $x=1$.' The flaw is that it:", options:[{key:"A",text:"loses the solution $x=0$"},{key:"B",text:"divides by a non-zero number"},{key:"C",text:"has no flaw"},{key:"D",text:"assumes $x=1$"},{key:"E",text:"squares both sides"}],
    answer:"A", solution:"Dividing by $x$ assumes $x\\ne0$, discarding the valid solution $x=0.$" },
  { id:"tmua-mk10-p2-10", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"'Since $x,y\\ge0$, $\\sqrt{x+y}=\\sqrt{x}+\\sqrt{y}$.' The flaw is that it:", options:[{key:"A",text:"requires $x,y<0$"},{key:"B",text:"divides by zero"},{key:"C",text:"incorrectly distributes a square root over addition"},{key:"D",text:"uses the contrapositive"},{key:"E",text:"has no flaw"}],
    answer:"C", solution:"Square roots do not distribute over addition; for example, $x=y=1$ gives $\\sqrt2\\ne2$." },
  { id:"tmua-mk10-p2-11", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Assuming $\\sqrt5$ is rational and deriving a contradiction is an example of:", options:[{key:"A",text:"proof by contradiction"},{key:"B",text:"proof by cases"},{key:"C",text:"disproof by counterexample"},{key:"D",text:"direct proof"},{key:"E",text:"induction"}],
    answer:"A", solution:"Assuming the negation of the claim to reach a contradiction is proof by contradiction." },
  { id:"tmua-mk10-p2-12", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Proving a claim by treating $x$ positive, negative and zero separately is:", options:[{key:"A",text:"proof by contradiction"},{key:"B",text:"proof by cases"},{key:"C",text:"disproof by counterexample"},{key:"D",text:"a converse argument"},{key:"E",text:"circular reasoning"}],
    answer:"B", solution:"Exhaustive sign cases is proof by cases." },
  { id:"tmua-mk10-p2-13", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:1, marks:1,
    question:"The $n$-th term of $1,3,5,7,9,\\ldots$ is:", options:[{key:"A",text:"$2n-1$"},{key:"B",text:"$2n$"},{key:"C",text:"$n^2$"},{key:"D",text:"$n+2$"},{key:"E",text:"$2n+1$"}],
    answer:"A", solution:"Odd numbers: $u_n=2n-1.$" },
  { id:"tmua-mk10-p2-14", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:3, marks:1,
    question:"For real $x$, the condition '$|x|=5$' is ______ for '$x^2=25$'.", options:[{key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both necessary and sufficient"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"C", solution:"$|x|=5\\Leftrightarrow x=\\pm5\\Leftrightarrow x^2=25$: the conditions are equivalent." },
  { id:"tmua-mk10-p2-15", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"Everyone in a group shakes hands once with everyone else, giving $45$ handshakes. How many people are there?", options:[{key:"A",text:"$9$"},{key:"B",text:"$10$"},{key:"C",text:"$11$"},{key:"D",text:"$45$"},{key:"E",text:"$12$"}],
    answer:"B", solution:"$\\binom{n}{2}=45\\Rightarrow n(n-1)=90\\Rightarrow n=10.$" },
  { id:"tmua-mk10-p2-16", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"For a quadrilateral to be a rectangle, having four right angles is:", options:[{key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both necessary and sufficient"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"C", solution:"A quadrilateral is a rectangle iff it has four right angles: both necessary and sufficient." },
  { id:"tmua-mk10-p2-17", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The negation of 'all cats are mammals' is:", options:[{key:"A",text:"no cats are mammals"},{key:"B",text:"at least one cat is not a mammal"},{key:"C",text:"all cats are not mammals"},{key:"D",text:"some cats are mammals"},{key:"E",text:"cats do not exist"}],
    answer:"B", solution:"Negation of 'for all $x$: $P$' is 'there exists $x$: not $P$'." },
  { id:"tmua-mk10-p2-18", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"Is the statement 'if $n^2$ is even then $n$ is odd' true or false?", options:[{key:"A",text:"true"},{key:"B",text:"false; e.g. $n=2$"},{key:"C",text:"false; e.g. $n=3$"},{key:"D",text:"cannot be determined"},{key:"E",text:"true only for $n>0$"}],
    answer:"B", solution:"At $n=2$: $n^2=4$ is even but $n=2$ is not odd — a counterexample, so the statement is false." },
  { id:"tmua-mk10-p2-19", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"Using $1+3+5+\\cdots+(2n-1)=n^2$, find $1+3+5+\\cdots+39$.", options:[{key:"A",text:"$400$"},{key:"B",text:"$361$"},{key:"C",text:"$441$"},{key:"D",text:"$380$"},{key:"E",text:"$420$"}],
    answer:"A", solution:"Last term $39=2n-1\\Rightarrow n=20$; sum $=20^2=400.$" },
  { id:"tmua-mk10-p2-20", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The condition '$x=0$' is ______ for '$x\\cdot y=0$'.", options:[{key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"B", solution:"$x=0\\Rightarrow xy=0$ (sufficient); but $xy=0$ can hold via $y=0$ instead, so not necessary." },
];
