// TMUA 模拟卷一 —— 全新原创题，专供「完整模拟卷」计时考试使用。
// 对标真实 TMUA 结构：两卷各 20 题、各 75 分钟、五选一（A–E）、无负分、无计算器。
// Paper 1 = 数学应用；Paper 2 = 数学推理与逻辑。仅以官方考纲/结构校准，未照搬任何真题。
// id 前缀 tmua-mk1-* 不与练习题冲突。
import type { MCQQuestion } from "@/lib/tests/questions/types";

// ── Paper 1：数学应用（20 题 / 75 分钟）─────────────────────────────
export const TMUA_MK1_P1: MCQQuestion[] = [
  { id: "tmua-mk1-p1-01", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "The quadratic $x^2-6x+k$ has a repeated root. Find $k$.",
    options: [ {key:"A",text:"$9$"},{key:"B",text:"$6$"},{key:"C",text:"$3$"},{key:"D",text:"$12$"},{key:"E",text:"$36$"} ],
    answer: "A", solution: "Repeated root $\\Leftrightarrow$ discriminant $=0$: $36-4k=0\\Rightarrow k=9$." },
  { id: "tmua-mk1-p1-02", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "Simplify $\\dfrac{8^{x+1}}{2^{3x}}$.",
    options: [ {key:"A",text:"$2$"},{key:"B",text:"$8$"},{key:"C",text:"$4$"},{key:"D",text:"$2^x$"},{key:"E",text:"$16$"} ],
    answer: "B", solution: "$\\dfrac{2^{3(x+1)}}{2^{3x}}=2^{3x+3-3x}=2^3=8.$" },
  { id: "tmua-mk1-p1-03", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 1, marks: 1,
    question: "Write $\\dfrac{6}{\\sqrt3}$ in simplest surd form.",
    options: [ {key:"A",text:"$2\\sqrt3$"},{key:"B",text:"$3\\sqrt2$"},{key:"C",text:"$6\\sqrt3$"},{key:"D",text:"$\\sqrt6$"},{key:"E",text:"$2\\sqrt6$"} ],
    answer: "A", solution: "$\\dfrac{6}{\\sqrt3}=\\dfrac{6\\sqrt3}{3}=2\\sqrt3.$" },
  { id: "tmua-mk1-p1-04", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "An arithmetic sequence has first term $5$ and tenth term $32$. Find the common difference.",
    options: [ {key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$4$"},{key:"D",text:"$27$"},{key:"E",text:"$9$"} ],
    answer: "B", solution: "$a+9d=32$ with $a=5\\Rightarrow 9d=27\\Rightarrow d=3.$" },
  { id: "tmua-mk1-p1-05", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "A geometric series has first term $8$ and common ratio $\\tfrac12$. Find its sum to infinity.",
    options: [ {key:"A",text:"$8$"},{key:"B",text:"$12$"},{key:"C",text:"$16$"},{key:"D",text:"$24$"},{key:"E",text:"$32$"} ],
    answer: "C", solution: "$S_\\infty=\\dfrac{a}{1-r}=\\dfrac{8}{1-\\tfrac12}=16.$" },
  { id: "tmua-mk1-p1-06", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 1, marks: 1,
    question: "Find the gradient of the line through $(1,2)$ and $(5,10)$.",
    options: [ {key:"A",text:"$1$"},{key:"B",text:"$2$"},{key:"C",text:"$3$"},{key:"D",text:"$4$"},{key:"E",text:"$\\tfrac12$"} ],
    answer: "B", solution: "$\\dfrac{10-2}{5-1}=\\dfrac{8}{4}=2.$" },
  { id: "tmua-mk1-p1-07", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "Which is the equation of the circle with centre $(2,-3)$ and radius $5$?",
    options: [ {key:"A",text:"$(x-2)^2+(y+3)^2=25$"},{key:"B",text:"$(x+2)^2+(y-3)^2=25$"},{key:"C",text:"$(x-2)^2+(y-3)^2=5$"},{key:"D",text:"$(x-2)^2+(y+3)^2=5$"},{key:"E",text:"$(x+2)^2+(y+3)^2=25$"} ],
    answer: "A", solution: "Centre $(a,b)$, radius $r$: $(x-a)^2+(y-b)^2=r^2$, so $(x-2)^2+(y+3)^2=25.$" },
  { id: "tmua-mk1-p1-08", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 2, marks: 1,
    question: "How many solutions does $\\sin\\theta=\\tfrac12$ have for $0^\\circ\\le\\theta<360^\\circ$?",
    options: [ {key:"A",text:"$1$"},{key:"B",text:"$2$"},{key:"C",text:"$3$"},{key:"D",text:"$4$"},{key:"E",text:"$0$"} ],
    answer: "B", solution: "$\\theta=30^\\circ$ and $\\theta=150^\\circ$: two solutions." },
  { id: "tmua-mk1-p1-09", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 3, marks: 1,
    question: "Simplify $\\dfrac{\\sin^2\\theta}{1-\\cos\\theta}$ (for $\\cos\\theta\\ne1$).",
    options: [ {key:"A",text:"$1-\\cos\\theta$"},{key:"B",text:"$1+\\cos\\theta$"},{key:"C",text:"$\\sin\\theta$"},{key:"D",text:"$\\cos\\theta$"},{key:"E",text:"$2$"} ],
    answer: "B", solution: "$\\sin^2\\theta=1-\\cos^2\\theta=(1-\\cos\\theta)(1+\\cos\\theta)$; cancelling gives $1+\\cos\\theta.$" },
  { id: "tmua-mk1-p1-10", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 1, marks: 1,
    question: "Solve $2^{x}=32$.",
    options: [ {key:"A",text:"$4$"},{key:"B",text:"$5$"},{key:"C",text:"$6$"},{key:"D",text:"$3$"},{key:"E",text:"$16$"} ],
    answer: "B", solution: "$32=2^5$, so $x=5.$" },
  { id: "tmua-mk1-p1-11", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 1, marks: 1,
    question: "Evaluate $\\log_3 81$.",
    options: [ {key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$4$"},{key:"D",text:"$9$"},{key:"E",text:"$27$"} ],
    answer: "C", solution: "$81=3^4$, so $\\log_3 81=4.$" },
  { id: "tmua-mk1-p1-12", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 3, marks: 1,
    question: "Solve $\\log_2(x+2)+\\log_2 x=3$.",
    options: [ {key:"A",text:"$x=2$"},{key:"B",text:"$x=4$"},{key:"C",text:"$x=-4$"},{key:"D",text:"$x=6$"},{key:"E",text:"$x=8$"} ],
    answer: "A", solution: "$\\log_2\\big(x(x+2)\\big)=3\\Rightarrow x^2+2x=8\\Rightarrow(x+4)(x-2)=0$. Since $x>0$, $x=2.$" },
  { id: "tmua-mk1-p1-13", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 3, marks: 1,
    question: "How many stationary points does $f(x)=x^3-6x^2+9x$ have?",
    options: [ {key:"A",text:"$0$"},{key:"B",text:"$1$"},{key:"C",text:"$2$"},{key:"D",text:"$3$"},{key:"E",text:"$4$"} ],
    answer: "C", solution: "$f'(x)=3x^2-12x+9=3(x-1)(x-3)$, giving two stationary points at $x=1,3.$" },
  { id: "tmua-mk1-p1-14", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 1, marks: 1,
    question: "Find the gradient of $y=x^2-4x$ at $x=3$.",
    options: [ {key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$-1$"},{key:"D",text:"$6$"},{key:"E",text:"$0$"} ],
    answer: "A", solution: "$y'=2x-4$; at $x=3$, $y'=2.$" },
  { id: "tmua-mk1-p1-15", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 1, marks: 1,
    question: "Evaluate $\\displaystyle\\int_0^2 3x^2\\,\\mathrm{d}x$.",
    options: [ {key:"A",text:"$4$"},{key:"B",text:"$6$"},{key:"C",text:"$8$"},{key:"D",text:"$12$"},{key:"E",text:"$2$"} ],
    answer: "C", solution: "$\\int 3x^2\\,dx=x^3$; $[x^3]_0^2=8.$" },
  { id: "tmua-mk1-p1-16", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 2, marks: 1,
    question: "Find the area between $y=x^2$ and the $x$-axis from $x=0$ to $x=3$.",
    options: [ {key:"A",text:"$3$"},{key:"B",text:"$6$"},{key:"C",text:"$9$"},{key:"D",text:"$27$"},{key:"E",text:"$18$"} ],
    answer: "C", solution: "$\\int_0^3 x^2\\,dx=\\left[\\tfrac{x^3}{3}\\right]_0^3=9.$" },
  { id: "tmua-mk1-p1-17", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "The graph of $y=f(x)$ is transformed to $y=f(x-2)+3$. Describe the transformation.",
    options: [ {key:"A",text:"left 2, up 3"},{key:"B",text:"right 2, up 3"},{key:"C",text:"right 2, down 3"},{key:"D",text:"left 2, down 3"},{key:"E",text:"up 2, right 3"} ],
    answer: "B", solution: "$f(x-2)$ shifts right by 2; $+3$ shifts up by 3." },
  { id: "tmua-mk1-p1-18", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "Given $f(x)=2x+1$ and $g(x)=x^2$, find $f(g(3))$.",
    options: [ {key:"A",text:"$19$"},{key:"B",text:"$49$"},{key:"C",text:"$13$"},{key:"D",text:"$7$"},{key:"E",text:"$37$"} ],
    answer: "A", solution: "$g(3)=9$, then $f(9)=2(9)+1=19.$" },
  { id: "tmua-mk1-p1-19", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "Solve the inequality $x^2-x-6<0$.",
    options: [ {key:"A",text:"$x<-2$ or $x>3$"},{key:"B",text:"$-2<x<3$"},{key:"C",text:"$-3<x<2$"},{key:"D",text:"$x>3$"},{key:"E",text:"$x<3$"} ],
    answer: "B", solution: "$(x-3)(x+2)<0\\Rightarrow -2<x<3.$" },
  { id: "tmua-mk1-p1-20", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "Find the coefficient of $x^2$ in the expansion of $(1+2x)^5$.",
    options: [ {key:"A",text:"$10$"},{key:"B",text:"$20$"},{key:"C",text:"$40$"},{key:"D",text:"$80$"},{key:"E",text:"$5$"} ],
    answer: "C", solution: "$\\binom{5}{2}(2)^2=10\\times4=40.$" },
];

// ── Paper 2：数学推理与逻辑（20 题 / 75 分钟）───────────────────────
export const TMUA_MK1_P2: MCQQuestion[] = [
  { id: "tmua-mk1-p2-01", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "What is the contrapositive of 'if $x>0$ then $x^2>0$'?",
    options: [ {key:"A",text:"if $x^2>0$ then $x>0$"},{key:"B",text:"if $x\\le0$ then $x^2\\le0$"},{key:"C",text:"if $x^2\\le0$ then $x\\le0$"},{key:"D",text:"if $x<0$ then $x^2<0$"},{key:"E",text:"if $x^2\\ge0$ then $x\\ge0$"} ],
    answer: "C", solution: "The contrapositive of $P\\Rightarrow Q$ is $\\lnot Q\\Rightarrow\\lnot P$: 'if $x^2\\le0$ then $x\\le0$'." },
  { id: "tmua-mk1-p2-02", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 3, marks: 1,
    question: "Consider the converse of 'if $a=b$ then $a^2=b^2$'. Which statement is correct?",
    options: [ {key:"A",text:"converse: 'if $a^2=b^2$ then $a=b$'; it is true"},{key:"B",text:"converse: 'if $a^2=b^2$ then $a=b$'; it is false"},{key:"C",text:"converse: 'if $a\\ne b$ then $a^2\\ne b^2$'; it is true"},{key:"D",text:"converse: 'if $a=b$ then $a^2\\ne b^2$'; it is false"},{key:"E",text:"the converse is the same statement"} ],
    answer: "B", solution: "The converse swaps hypothesis and conclusion. It is false: $a=-b$ gives $a^2=b^2$ but $a\\ne b$." },
  { id: "tmua-mk1-p2-03", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "For an integer to be divisible by $6$, being divisible by $3$ is:",
    options: [ {key:"A",text:"sufficient but not necessary"},{key:"B",text:"necessary but not sufficient"},{key:"C",text:"both necessary and sufficient"},{key:"D",text:"neither"},{key:"E",text:"impossible to say"} ],
    answer: "B", solution: "Divisible by 6 $\\Rightarrow$ divisible by 3 (necessary), but 3 alone is not enough, e.g. 9 (not sufficient)." },
  { id: "tmua-mk1-p2-04", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 1, marks: 1,
    question: "Which single value disproves 'all prime numbers are odd'?",
    options: [ {key:"A",text:"$1$"},{key:"B",text:"$2$"},{key:"C",text:"$9$"},{key:"D",text:"$15$"},{key:"E",text:"none exists"} ],
    answer: "B", solution: "$2$ is prime and even, a counterexample." },
  { id: "tmua-mk1-p2-05", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "What is the negation of 'all swans are white'?",
    options: [ {key:"A",text:"no swans are white"},{key:"B",text:"at least one swan is not white"},{key:"C",text:"all swans are not white"},{key:"D",text:"some swans are white"},{key:"E",text:"most swans are white"} ],
    answer: "B", solution: "The negation of 'for all $x$, $P(x)$' is 'there exists $x$ with not $P(x)$'." },
  { id: "tmua-mk1-p2-06", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "To prove $\\sqrt2$ is irrational by contradiction, one assumes that:",
    options: [ {key:"A",text:"$\\sqrt2$ is rational (a fraction in lowest terms)"},{key:"B",text:"$\\sqrt2$ is irrational"},{key:"C",text:"$2$ is prime"},{key:"D",text:"$\\sqrt2>1$"},{key:"E",text:"$\\sqrt2$ is an integer"} ],
    answer: "A", solution: "Proof by contradiction assumes the negation of the claim: that $\\sqrt2$ is rational." },
  { id: "tmua-mk1-p2-07", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 3, marks: 1,
    question: "Rule: 'If it is raining or sunny, I stay in.' Today it is neither raining nor sunny. What follows about whether I stay in?",
    options: [ {key:"A",text:"I stay in"},{key:"B",text:"I do not stay in"},{key:"C",text:"It cannot be determined"},{key:"D",text:"It is cloudy"},{key:"E",text:"I go out"} ],
    answer: "C", solution: "The rule only specifies what happens when it rains or is sunny; it says nothing about other conditions, so no conclusion follows." },
  { id: "tmua-mk1-p2-08", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 1, marks: 1,
    question: "Given $A\\Rightarrow B$, $B\\Rightarrow C$, $C\\Rightarrow D$, and that $A$ is true, which must be true?",
    options: [ {key:"A",text:"only $B$"},{key:"B",text:"only $C$"},{key:"C",text:"$C$ and $D$ only"},{key:"D",text:"$D$"},{key:"E",text:"nothing"} ],
    answer: "D", solution: "Chaining the implications from $A$ gives $B$, then $C$, then $D$; in particular $D$ is true." },
  { id: "tmua-mk1-p2-09", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 2, marks: 1,
    question: "For every integer $n$, the expression $n^2+n$ is always:",
    options: [ {key:"A",text:"odd"},{key:"B",text:"even"},{key:"C",text:"prime"},{key:"D",text:"divisible by 3"},{key:"E",text:"a perfect square"} ],
    answer: "B", solution: "$n^2+n=n(n+1)$ is a product of two consecutive integers, one of which is even, so it is always even." },
  { id: "tmua-mk1-p2-10", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 3, marks: 1,
    question: "A flawed argument 'proves' $1=2$. Its hidden error is:",
    options: [ {key:"A",text:"adding equal quantities to both sides"},{key:"B",text:"dividing both sides by $(a-b)$, which is zero"},{key:"C",text:"squaring both sides"},{key:"D",text:"factorising a difference of squares"},{key:"E",text:"multiplying by a constant"} ],
    answer: "B", solution: "The classic fallacy divides by $a-b$; when $a=b$ this is division by zero, which is invalid." },
  { id: "tmua-mk1-p2-11", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "In the deduction '$x^2=9$, therefore $x=3$', the error is:",
    options: [ {key:"A",text:"there is no error"},{key:"B",text:"it ignores the root $x=-3$"},{key:"C",text:"$9$ is not a perfect square"},{key:"D",text:"you cannot square-root both sides"},{key:"E",text:"$x$ must be an integer"} ],
    answer: "B", solution: "$x^2=9$ gives $x=\\pm3$; the deduction drops the negative solution $x=-3$." },
  { id: "tmua-mk1-p2-12", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "For a quadrilateral to be a square, having four equal sides is:",
    options: [ {key:"A",text:"sufficient but not necessary"},{key:"B",text:"necessary but not sufficient"},{key:"C",text:"both necessary and sufficient"},{key:"D",text:"neither"},{key:"E",text:"impossible to decide"} ],
    answer: "B", solution: "A square must have four equal sides (necessary), but a rhombus also has four equal sides without being a square (not sufficient)." },
  { id: "tmua-mk1-p2-13", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 3, marks: 1,
    question: "For every integer $n$, the product $n(n+1)(n+2)$ is always divisible by:",
    options: [ {key:"A",text:"$2$ only"},{key:"B",text:"$3$ only"},{key:"C",text:"$6$"},{key:"D",text:"$4$"},{key:"E",text:"$5$"} ],
    answer: "C", solution: "Among three consecutive integers there is a multiple of 2 and a multiple of 3, so the product is divisible by $2\\times3=6$." },
  { id: "tmua-mk1-p2-14", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 3, marks: 1,
    question: "The statement '$A$ only if $B$' is logically equivalent to:",
    options: [ {key:"A",text:"$B\\Rightarrow A$"},{key:"B",text:"$A\\Rightarrow B$"},{key:"C",text:"$A\\Leftrightarrow B$"},{key:"D",text:"$\\lnot A$"},{key:"E",text:"$\\lnot B\\Rightarrow A$"} ],
    answer: "B", solution: "'$A$ only if $B$' means $A$ cannot hold without $B$, i.e. $A\\Rightarrow B$." },
  { id: "tmua-mk1-p2-15", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "Is the statement 'for all integers $n$, if $n^2$ is odd then $n$ is odd' true or false?",
    options: [ {key:"A",text:"true"},{key:"B",text:"false, counterexample $n=2$"},{key:"C",text:"false, counterexample $n=1$"},{key:"D",text:"cannot be determined"},{key:"E",text:"true only for $n>0$"} ],
    answer: "A", solution: "True. Contrapositive: if $n$ is even then $n^2$ is even — clearly true — so the original holds." },
  { id: "tmua-mk1-p2-16", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 2, marks: 1,
    question: "Five people each shake hands exactly once with every other person. How many handshakes occur?",
    options: [ {key:"A",text:"$5$"},{key:"B",text:"$10$"},{key:"C",text:"$20$"},{key:"D",text:"$25$"},{key:"E",text:"$15$"} ],
    answer: "B", solution: "$\\binom{5}{2}=\\dfrac{5\\cdot4}{2}=10.$" },
  { id: "tmua-mk1-p2-17", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "If 'no A are B' is true, which statement must also be true?",
    options: [ {key:"A",text:"all B are A"},{key:"B",text:"some B are A"},{key:"C",text:"no B are A"},{key:"D",text:"some A are B"},{key:"E",text:"all A are B"} ],
    answer: "C", solution: "'No A are B' is symmetric: it is equivalent to 'no B are A'." },
  { id: "tmua-mk1-p2-18", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "To prove 'if $n^2$ is even then $n$ is even' by contradiction, one assumes:",
    options: [ {key:"A",text:"$n$ is even"},{key:"B",text:"$n$ is odd (while $n^2$ is even)"},{key:"C",text:"$n^2$ is odd"},{key:"D",text:"$n^2=0$"},{key:"E",text:"$n$ is prime"} ],
    answer: "B", solution: "Assume the negation of the conclusion while keeping the hypothesis: $n$ odd but $n^2$ even, then derive a contradiction." },
  { id: "tmua-mk1-p2-19", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 2, marks: 1,
    question: "The sum of the first $n$ odd numbers $1+3+5+\\cdots+(2n-1)$ equals:",
    options: [ {key:"A",text:"$\\tfrac{n(n+1)}{2}$"},{key:"B",text:"$n^2$"},{key:"C",text:"$2n-1$"},{key:"D",text:"$n(n+1)$"},{key:"E",text:"$n^2+1$"} ],
    answer: "B", solution: "The sum of the first $n$ odd numbers is $n^2$ (a standard result, provable by induction)." },
  { id: "tmua-mk1-p2-20", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "The condition '$x=2$' is ______ for '$x^2=4$'.",
    options: [ {key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both necessary and sufficient"},{key:"D",text:"neither"},{key:"E",text:"undecidable"} ],
    answer: "B", solution: "$x=2\\Rightarrow x^2=4$ (sufficient), but $x^2=4$ also holds for $x=-2$, so $x=2$ is not necessary." },
];
