// TMUA 模拟卷五 —— 全新原创题，与卷一~四、练习题均不重复。两卷各 20 题、各 75 分钟、五选一、无负分。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const TMUA_MK5_P1: MCQQuestion[] = [
  { id:"tmua-mk5-p1-01", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The smaller root of $x^2-10x+21=0$ is:", options:[{key:"A",text:"$3$"},{key:"B",text:"$7$"},{key:"C",text:"$10$"},{key:"D",text:"$21$"},{key:"E",text:"$4$"}],
    answer:"A", solution:"$(x-3)(x-7)=0$; smaller root $3.$" },
  { id:"tmua-mk5-p1-02", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Evaluate $32^{2/5}$.", options:[{key:"A",text:"$2$"},{key:"B",text:"$4$"},{key:"C",text:"$8$"},{key:"D",text:"$16$"},{key:"E",text:"$64$"}],
    answer:"B", solution:"$32^{1/5}=2$, then $2^2=4.$" },
  { id:"tmua-mk5-p1-03", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Simplify $\\sqrt{45}-\\sqrt{20}$.", options:[{key:"A",text:"$\\sqrt5$"},{key:"B",text:"$5\\sqrt5$"},{key:"C",text:"$5$"},{key:"D",text:"$2\\sqrt5$"},{key:"E",text:"$\\sqrt{65}$"}],
    answer:"A", solution:"$3\\sqrt5-2\\sqrt5=\\sqrt5.$" },
  { id:"tmua-mk5-p1-04", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Find the sum of the first $12$ terms of $5+8+11+\\cdots$.", options:[{key:"A",text:"$258$"},{key:"B",text:"$248$"},{key:"C",text:"$268$"},{key:"D",text:"$240$"},{key:"E",text:"$276$"}],
    answer:"A", solution:"$a=5,d=3$: $S_{12}=\\tfrac{12}{2}(10+11\\cdot3)=6\\times43=258.$" },
  { id:"tmua-mk5-p1-05", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The $4$th term of the geometric sequence $1,3,9,\\ldots$ is:", options:[{key:"A",text:"$27$"},{key:"B",text:"$9$"},{key:"C",text:"$81$"},{key:"D",text:"$18$"},{key:"E",text:"$24$"}],
    answer:"A", solution:"$ar^3=1\\cdot3^3=27.$" },
  { id:"tmua-mk5-p1-06", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"The gradient of the line through $(-1,2)$ and $(2,11)$ is:", options:[{key:"A",text:"$3$"},{key:"B",text:"$2$"},{key:"C",text:"$9$"},{key:"D",text:"$1$"},{key:"E",text:"$\\tfrac13$"}],
    answer:"A", solution:"$\\tfrac{11-2}{2-(-1)}=\\tfrac{9}{3}=3.$" },
  { id:"tmua-mk5-p1-07", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:3, marks:1,
    question:"The radius of the circle $x^2+y^2-10x+4y+20=0$ is:", options:[{key:"A",text:"$3$"},{key:"B",text:"$9$"},{key:"C",text:"$5$"},{key:"D",text:"$\\sqrt{29}$"},{key:"E",text:"$7$"}],
    answer:"A", solution:"$(x-5)^2+(y+2)^2=25+4-20=9$, so $r=3.$" },
  { id:"tmua-mk5-p1-08", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"Evaluate $\\sin 90^\\circ$.", options:[{key:"A",text:"$1$"},{key:"B",text:"$0$"},{key:"C",text:"$-1$"},{key:"D",text:"$\\tfrac12$"},{key:"E",text:"$\\tfrac{\\sqrt3}{2}$"}],
    answer:"A", solution:"$\\sin90^\\circ=1.$" },
  { id:"tmua-mk5-p1-09", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"If $\\sin\\theta=\\tfrac{5}{13}$ and $\\theta$ is acute, then $\\cos\\theta=$", options:[{key:"A",text:"$\\tfrac{12}{13}$"},{key:"B",text:"$\\tfrac{5}{13}$"},{key:"C",text:"$\\tfrac{13}{12}$"},{key:"D",text:"$\\tfrac{8}{13}$"},{key:"E",text:"$1$"}],
    answer:"A", solution:"$\\cos\\theta=\\sqrt{1-\\tfrac{25}{169}}=\\sqrt{\\tfrac{144}{169}}=\\tfrac{12}{13}.$" },
  { id:"tmua-mk5-p1-10", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:1, marks:1,
    question:"Solve $4^{x}=64$.", options:[{key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$4$"},{key:"D",text:"$16$"},{key:"E",text:"$32$"}],
    answer:"B", solution:"$64=4^3$, so $x=3.$" },
  { id:"tmua-mk5-p1-11", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Evaluate $\\log_5 125$.", options:[{key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$5$"},{key:"D",text:"$25$"},{key:"E",text:"$4$"}],
    answer:"B", solution:"$125=5^3$, so $\\log_5 125=3.$" },
  { id:"tmua-mk5-p1-12", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Solve $\\log_3 x=4$.", options:[{key:"A",text:"$12$"},{key:"B",text:"$64$"},{key:"C",text:"$81$"},{key:"D",text:"$27$"},{key:"E",text:"$9$"}],
    answer:"C", solution:"$x=3^4=81.$" },
  { id:"tmua-mk5-p1-13", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"Find $\\dfrac{d}{dx}(x^3-x)$ at $x=2$.", options:[{key:"A",text:"$11$"},{key:"B",text:"$12$"},{key:"C",text:"$7$"},{key:"D",text:"$5$"},{key:"E",text:"$10$"}],
    answer:"A", solution:"$3x^2-1$; at $x=2$, $12-1=11.$" },
  { id:"tmua-mk5-p1-14", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"The gradient of $y=4x^2$ at $x=2$ is:", options:[{key:"A",text:"$8$"},{key:"B",text:"$16$"},{key:"C",text:"$4$"},{key:"D",text:"$32$"},{key:"E",text:"$2$"}],
    answer:"B", solution:"$y'=8x=16$ at $x=2.$" },
  { id:"tmua-mk5-p1-15", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:1, marks:1,
    question:"Evaluate $\\displaystyle\\int_0^2 6x\\,\\mathrm{d}x$.", options:[{key:"A",text:"$6$"},{key:"B",text:"$12$"},{key:"C",text:"$18$"},{key:"D",text:"$24$"},{key:"E",text:"$3$"}],
    answer:"B", solution:"$[3x^2]_0^2=12.$" },
  { id:"tmua-mk5-p1-16", type:"mcq", testId:"tmua", topicId:"tmua-calc", difficulty:2, marks:1,
    question:"The area under $y=x^2+1$ from $x=0$ to $x=3$ is:", options:[{key:"A",text:"$9$"},{key:"B",text:"$12$"},{key:"C",text:"$10$"},{key:"D",text:"$6$"},{key:"E",text:"$15$"}],
    answer:"B", solution:"$\\int_0^3(x^2+1)\\,dx=\\left[\\tfrac{x^3}{3}+x\\right]_0^3=9+3=12.$" },
  { id:"tmua-mk5-p1-17", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The graph of $y=f(2x)$ is $y=f(x)$ subjected to a:", options:[{key:"A",text:"horizontal stretch, factor $\\tfrac12$"},{key:"B",text:"horizontal stretch, factor $2$"},{key:"C",text:"shift left $2$"},{key:"D",text:"shift right $2$"},{key:"E",text:"reflection in the $y$-axis"}],
    answer:"A", solution:"Replacing $x$ by $2x$ compresses horizontally by a factor of $\\tfrac12.$" },
  { id:"tmua-mk5-p1-18", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"Given $f(x)=x^2$ and $g(x)=x+3$, find $f(g(1))$.", options:[{key:"A",text:"$16$"},{key:"B",text:"$4$"},{key:"C",text:"$8$"},{key:"D",text:"$10$"},{key:"E",text:"$9$"}],
    answer:"A", solution:"$g(1)=4$, then $f(4)=16.$" },
  { id:"tmua-mk5-p1-19", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:1, marks:1,
    question:"Solve $4-2x\\le0$.", options:[{key:"A",text:"$x\\ge2$"},{key:"B",text:"$x\\le2$"},{key:"C",text:"$x\\ge4$"},{key:"D",text:"$x>2$"},{key:"E",text:"$x\\le4$"}],
    answer:"A", solution:"$4\\le2x\\Rightarrow x\\ge2.$" },
  { id:"tmua-mk5-p1-20", type:"mcq", testId:"tmua", topicId:"tmua-algebra", difficulty:2, marks:1,
    question:"The coefficient of $x^3$ in $(1+x)^5$ is:", options:[{key:"A",text:"$10$"},{key:"B",text:"$20$"},{key:"C",text:"$5$"},{key:"D",text:"$30$"},{key:"E",text:"$15$"}],
    answer:"A", solution:"$\\binom{5}{3}=10.$" },
];

export const TMUA_MK5_P2: MCQQuestion[] = [
  { id:"tmua-mk5-p2-01", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"For an integer to be divisible by $15$, being divisible by $3$ is:", options:[{key:"A",text:"sufficient but not necessary"},{key:"B",text:"necessary but not sufficient"},{key:"C",text:"both"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"B", solution:"Divisible by 15 $\\Rightarrow$ divisible by 3 (necessary), but 9 is divisible by 3 not 15 (not sufficient)." },
  { id:"tmua-mk5-p2-02", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Is the converse of 'if $n$ is a multiple of $4$ then $n$ is even' true?", options:[{key:"A",text:"true"},{key:"B",text:"false; e.g. $n=2$"},{key:"C",text:"false; e.g. $n=8$"},{key:"D",text:"the same statement"},{key:"E",text:"true only for $n>0$"}],
    answer:"B", solution:"Converse: 'if $n$ is even then $n$ is a multiple of 4', false since $2$ is even but not a multiple of $4.$" },
  { id:"tmua-mk5-p2-03", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:3, marks:1,
    question:"The contrapositive of 'if $x$ is negative then $x<1$' is:", options:[{key:"A",text:"if $x<1$ then $x$ is negative"},{key:"B",text:"if $x\\ge1$ then $x$ is not negative"},{key:"C",text:"if $x$ is not negative then $x\\ge1$"},{key:"D",text:"if $x$ is negative then $x\\ge1$"},{key:"E",text:"if $x\\ge1$ then $x$ is negative"}],
    answer:"B", solution:"Contrapositive $\\lnot Q\\Rightarrow\\lnot P$: 'if $x\\ge1$ then $x$ is not negative'." },
  { id:"tmua-mk5-p2-04", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:1, marks:1,
    question:"Which value disproves 'all multiples of $4$ are multiples of $8$'?", options:[{key:"A",text:"$4$"},{key:"B",text:"$8$"},{key:"C",text:"$16$"},{key:"D",text:"$24$"},{key:"E",text:"none"}],
    answer:"A", solution:"$4$ is a multiple of $4$ but not of $8$ — a counterexample." },
  { id:"tmua-mk5-p2-05", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The negation of 'for some integer $n$, $n^2<0$' is:", options:[{key:"A",text:"for some integer $n$, $n^2\\ge0$"},{key:"B",text:"for all integers $n$, $n^2\\ge0$"},{key:"C",text:"for all integers $n$, $n^2<0$"},{key:"D",text:"no integer exists"},{key:"E",text:"$n^2=0$"}],
    answer:"B", solution:"Negate 'there exists' to 'for all' and negate the inequality: for all $n$, $n^2\\ge0.$" },
  { id:"tmua-mk5-p2-06", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The negation of '$a\\ge0$ and $b\\ge0$' is:", options:[{key:"A",text:"$a<0$ or $b<0$"},{key:"B",text:"$a<0$ and $b<0$"},{key:"C",text:"$a\\le0$ or $b\\le0$"},{key:"D",text:"$a>0$ or $b>0$"},{key:"E",text:"$a\\ne0$"}],
    answer:"A", solution:"not($A$ and $B$) $=$ not $A$ or not $B$: $a<0$ or $b<0.$" },
  { id:"tmua-mk5-p2-07", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:3, marks:1,
    question:"If $P$ is false, what is the truth value of the implication '$P\\Rightarrow Q$'?", options:[{key:"A",text:"true (vacuously)"},{key:"B",text:"false"},{key:"C",text:"depends on $Q$"},{key:"D",text:"undefined"},{key:"E",text:"depends on both"}],
    answer:"A", solution:"An implication with a false hypothesis is vacuously true regardless of $Q.$" },
  { id:"tmua-mk5-p2-08", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Given $P\\Rightarrow Q$ is true and $Q$ is false, what follows?", options:[{key:"A",text:"$P$ is true"},{key:"B",text:"$P$ is false"},{key:"C",text:"$P$ is unknown"},{key:"D",text:"$Q$ is true"},{key:"E",text:"nothing"}],
    answer:"B", solution:"By the contrapositive $\\lnot Q\\Rightarrow\\lnot P$; since $Q$ is false, $P$ is false." },
  { id:"tmua-mk5-p2-09", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:3, marks:1,
    question:"'Since $x^2>x$, it follows that $x>1$.' The flaw is that it:", options:[{key:"A",text:"fails for negative $x$, e.g. $x=-2$"},{key:"B",text:"divides by zero"},{key:"C",text:"has no flaw"},{key:"D",text:"assumes $x>0$ correctly"},{key:"E",text:"squares both sides"}],
    answer:"A", solution:"At $x=-2$, $x^2=4>-2=x$ holds, yet $x=-2<1$; the deduction fails for negative $x.$" },
  { id:"tmua-mk5-p2-10", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"'If it is a dog then it is a mammal, therefore if it is a mammal then it is a dog.' The error is:", options:[{key:"A",text:"a false premise"},{key:"B",text:"assuming the converse"},{key:"C",text:"dividing by zero"},{key:"D",text:"proof by contradiction"},{key:"E",text:"a counterexample"}],
    answer:"B", solution:"Deriving $Q\\Rightarrow P$ from $P\\Rightarrow Q$ assumes the converse, which is invalid." },
  { id:"tmua-mk5-p2-11", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:1, marks:1,
    question:"Rejecting a universal claim by exhibiting the single case $n=4$ is:", options:[{key:"A",text:"proof by contradiction"},{key:"B",text:"disproof by counterexample"},{key:"C",text:"proof by cases"},{key:"D",text:"direct proof"},{key:"E",text:"induction"}],
    answer:"B", solution:"One failing case disproves a 'for all' statement." },
  { id:"tmua-mk5-p2-12", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"Proving a claim for all integers by considering $n$ odd and $n$ even separately is:", options:[{key:"A",text:"proof by contradiction"},{key:"B",text:"proof by cases"},{key:"C",text:"disproof by counterexample"},{key:"D",text:"a converse argument"},{key:"E",text:"circular reasoning"}],
    answer:"B", solution:"Exhaustive odd/even cases is proof by cases." },
  { id:"tmua-mk5-p2-13", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:3, marks:1,
    question:"The $n$-th term of $2,6,12,20,\\ldots$ is:", options:[{key:"A",text:"$n(n+1)$"},{key:"B",text:"$2n$"},{key:"C",text:"$n^2+1$"},{key:"D",text:"$2n^2$"},{key:"E",text:"$n^2+n+1$"}],
    answer:"A", solution:"$1\\cdot2,\\,2\\cdot3,\\,3\\cdot4,\\,4\\cdot5,\\ldots$, so the $n$-th term is $n(n+1).$" },
  { id:"tmua-mk5-p2-14", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"For real $x$, the condition '$x=1$' is ______ for '$x^3=1$'.", options:[{key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both necessary and sufficient"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"C", solution:"Over the reals $x^3=1$ has the single solution $x=1$, so the conditions are equivalent." },
  { id:"tmua-mk5-p2-15", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"Everyone in a group shakes hands once with everyone else, giving $6$ handshakes. How many people are there?", options:[{key:"A",text:"$3$"},{key:"B",text:"$4$"},{key:"C",text:"$5$"},{key:"D",text:"$6$"},{key:"E",text:"$7$"}],
    answer:"B", solution:"$\\binom{n}{2}=6\\Rightarrow n(n-1)=12\\Rightarrow n=4.$" },
  { id:"tmua-mk5-p2-16", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"For '$x>3$', the condition '$x>5$' is:", options:[{key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"B", solution:"$x>5\\Rightarrow x>3$ (sufficient); $x>3$ does not force $x>5$ (not necessary)." },
  { id:"tmua-mk5-p2-17", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"The negation of 'all triangles have three sides' is:", options:[{key:"A",text:"no triangle has three sides"},{key:"B",text:"at least one triangle does not have three sides"},{key:"C",text:"all triangles have four sides"},{key:"D",text:"some triangles have three sides"},{key:"E",text:"triangles do not exist"}],
    answer:"B", solution:"Negation of 'for all $x$: $P$' is 'there exists $x$: not $P$'." },
  { id:"tmua-mk5-p2-18", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:3, marks:1,
    question:"Which value shows 'if $n^2>4$ then $n>2$' is false?", options:[{key:"A",text:"$3$"},{key:"B",text:"$-3$"},{key:"C",text:"$0$"},{key:"D",text:"$2$"},{key:"E",text:"$5$"}],
    answer:"B", solution:"At $n=-3$: $n^2=9>4$ but $n=-3\\not>2$, a counterexample." },
  { id:"tmua-mk5-p2-19", type:"mcq", testId:"tmua", topicId:"tmua-discrete", difficulty:2, marks:1,
    question:"Using $1+3+5+\\cdots+(2n-1)=n^2$, find $1+3+5+\\cdots+19$.", options:[{key:"A",text:"$81$"},{key:"B",text:"$100$"},{key:"C",text:"$121$"},{key:"D",text:"$90$"},{key:"E",text:"$99$"}],
    answer:"B", solution:"Last term $19=2n-1\\Rightarrow n=10$; sum $=10^2=100.$" },
  { id:"tmua-mk5-p2-20", type:"mcq", testId:"tmua", topicId:"tmua-logic", difficulty:2, marks:1,
    question:"For '$x^2=9$', the condition '$x=3$' is:", options:[{key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both"},{key:"D",text:"neither"},{key:"E",text:"undecidable"}],
    answer:"B", solution:"$x=3\\Rightarrow x^2=9$ (sufficient); but $x=-3$ also works, so not necessary." },
];
