import type { MCQOptionKey, MCQQuestion, QuestionDifficulty } from "@/lib/tests/questions/types";

const KEYS = "ABCDEFGH" as const;
const COMBOS = ["I, II and III", "I and II only", "I and III only", "I only", "II and III only", "II only", "III only", "None of I, II and III"];
const COMBOS_ALT = ["None of I, II and III", "III only", "II only", "II and III only", "I only", "I and III only", "I and II only", "I, II and III"];

function q(id: string, topicId: string, difficulty: QuestionDifficulty, question: string, options: string[], answerIndex: number, solution: string): MCQQuestion {
  const spreadCombinationAnswers = options === COMBOS && answerIndex === 1;
  const finalOptions = spreadCombinationAnswers ? COMBOS_ALT : options;
  const finalAnswerIndex = spreadCombinationAnswers ? 6 : answerIndex;
  return { id, type: "mcq", testId: "tmua", topicId, difficulty, marks: 1, question,
    options: finalOptions.map((text, index) => ({ key: KEYS[index] as MCQOptionKey, text })),
    answer: KEYS[finalAnswerIndex] as MCQOptionKey, solution };
}

export const TMUA_MK3_P1_CALIBRATED: MCQQuestion[] = [
  q("tmua-mk3-cal-p1-13", "tmua-algebra", 2, "For which real values of $k$ does $x^2-(k+1)x+k=0$ have two distinct positive roots?", ["$k<0$", "$k=0$", "$k>0$", "$k>0$ and $k\\ne1$", "$k\\ne1$"], 3, "The quadratic factors as $(x-1)(x-k)$. Its roots are $1$ and $k$, so they are distinct and positive exactly when $k>0$ and $k\\ne1$."),
  q("tmua-mk3-cal-p1-14", "tmua-stats", 2, "Two fair dice are rolled. Given that their sum is even, what is the probability that both scores are even?", ["$1/4$", "$1/3$", "$1/2$", "$2/3$", "$3/4$", "$1$"], 2, "An even sum occurs when both scores have the same parity: $18$ outcomes. Nine of these have both scores even, so the conditional probability is $9/18=1/2$."),
  q("tmua-mk3-cal-p1-15", "tmua-algebra", 3, "What is the range of $f(x)=(2x^2+1)/(x^2+1)$ for real $x$?", ["$0<f<2$", "$1\\le f<2$", "$1<f\\le2$", "$1\\le f\\le2$", "$f\\ge1$", "all real values"], 1, "Write $f=2-1/(x^2+1)$. The value $1$ occurs at $x=0$, while $2$ is approached but never reached, so $1\\le f<2$."),
  q("tmua-mk3-cal-p1-16", "tmua-geometry", 3, "The line $y=mx+5$ is tangent to the circle $x^2+y^2=9$. What is $m^2$?", ["$4/9$", "$9/16$", "$16/9$", "$25/9$", "$3$", "$4$"], 2, "The distance from the origin to $mx-y+5=0$ is $5/\\sqrt{m^2+1}$. Equating this to $3$ gives $25=9(m^2+1)$, hence $m^2=16/9$."),
  q("tmua-mk3-cal-p1-17", "tmua-calc", 3, "The curves $y=x^2$ and $y=6x-x^2$ enclose a finite region. What is its area?", ["$6$", "$8$", "$9$", "$12$", "$18$", "$36$"], 2, "The curves meet at $x=0,3$. The area is $\\int_0^3(6x-2x^2)\\,dx=[3x^2-2x^3/3]_0^3=9$."),
  q("tmua-mk3-cal-p1-18", "tmua-discrete", 3, "How many arrangements of the letters in BANANA have no two Ns adjacent?", ["$20$", "$30$", "$40$", "$60$", "$80$", "$120$", "$180$"], 2, "Arrange the three As and one B in $4!/3!=4$ ways. They create five gaps; choose two for the identical Ns in $\\binom52=10$ ways. Total $4\\cdot10=40$."),
  q("tmua-mk3-cal-p1-19", "tmua-number", 3, "What is the remainder when $2^{50}+3^{50}$ is divided by $5$?", ["$0$", "$1$", "$2$", "$3$", "$4$"], 3, "$2^{50}\\equiv2^2=4\\pmod5$ and $3^{50}\\equiv3^2=9\\equiv4\\pmod5$, since powers have period $4$. Their sum has remainder $8\\equiv3$."),
  q("tmua-mk3-cal-p1-20", "tmua-geometry", 3, "How many solutions does $2\\sin^2x=1$ have for $0\\le x<2\\pi$?", ["$1$", "$2$", "$3$", "$4$", "$6$", "$8$"], 3, "$\\sin x=\\pm1/\\sqrt2$. Each sign occurs twice on a full turn, giving four solutions."),
];

export const TMUA_MK3_P2_CALIBRATED: MCQQuestion[] = [
  q("tmua-mk3-cal-p2-13", "tmua-discrete", 2, "A sequence satisfies $a_1=1$ and $a_{n+1}=a_n+2n+1$.\nI. $a_n=n^2$.\nII. Every term is odd.\nIII. The sequence is strictly increasing.\nWhich statements are true?", COMBOS, 2, "The recurrence gives $a_n=n^2$. Thus I is true, II is false because $a_2=4$, and the positive increments make III true. Therefore I and III only."),
  q("tmua-mk3-cal-p2-14", "tmua-algebra", 3, "For $p(x)=x^2+bx+c$:\nI. If $c<0$, then $p$ has two distinct real roots.\nII. If $b^2=4c$, then $p$ has exactly one real root.\nIII. If $p(0)>0$, then $p$ has no real roots.\nWhich statements are true?", COMBOS, 1, "If $c<0$, the discriminant $b^2-4c$ is positive, so I is true. Equality gives a repeated real root, so II is true. III fails, for example for $x^2-3x+2$."),
  q("tmua-mk3-cal-p2-15", "tmua-number", 3, "For every integer $n$:\nI. If $n^2$ is divisible by $3$, then $n$ is divisible by $3$.\nII. If $n^2$ is divisible by $8$, then $n$ is divisible by $4$.\nIII. If $n^2$ is divisible by $12$, then $n$ is divisible by $6$.\nWhich statements are true?", COMBOS, 0, "I follows from residues modulo $3$. For II, divisibility by $8$ forces at least two factors of $2$ in $n$. For III, the square condition forces both $2$ and $3$ to divide $n$. All three hold."),
  q("tmua-mk3-cal-p2-16", "tmua-stats", 3, "Events $A$ and $B$ have positive probability.\nI. If $A$ and $B$ are independent, then $P(A\\mid B)=P(A)$.\nII. If $P(A\\mid B)=P(A)$, then $A$ and $B$ are independent.\nIII. If $A\\subseteq B$, then $A$ and $B$ are independent.\nWhich statements are true?", COMBOS, 1, "I is the conditional form of independence, and with $P(B)>0$ its converse II also holds. III is generally false: containment makes the events dependent unless a probability is $0$ or $1$."),
  q("tmua-mk3-cal-p2-17", "tmua-logic", 3, "A proof assumes $P$ and correctly derives $Q$. It then observes that $Q$ is true.\nI. This proves $P$.\nII. This proves $P\\Rightarrow Q$.\nIII. This proves $Q\\Rightarrow P$.\nWhich statements are true?", COMBOS, 5, "Deriving $Q$ under the assumption $P$ proves $P\\Rightarrow Q$, so II is true. The truth of $Q$ does not establish $P$ or the converse. Thus II only."),
  q("tmua-mk3-cal-p2-18", "tmua-logic", 3, "For predicates $P(x)$ and $Q(x)$:\nI. $\\neg\\forall x\,P(x)$ is equivalent to $\\exists x\,\\neg P(x)$.\nII. $\\neg\\exists x\,P(x)$ is equivalent to $\\exists x\,\\neg P(x)$.\nIII. $\\forall x(P(x)\\land Q(x))$ implies $\\forall xP(x)$.\nWhich statements are true?", COMBOS, 2, "I is the correct negation of a universal statement. II should have a universal quantifier on the right. III follows by conjunction elimination for every $x$. Hence I and III only."),
  q("tmua-mk3-cal-p2-19", "tmua-geometry", 3, "For two non-degenerate triangles:\nI. Equal corresponding sides imply congruence.\nII. Equal corresponding angles imply congruence.\nIII. Congruence implies equal areas.\nWhich statements are true?", COMBOS, 2, "SSS gives congruence, so I is true. Equal angles give only similarity, so II is false. Congruent triangles have equal area, so III is true."),
  q("tmua-mk3-cal-p2-20", "tmua-algebra", 3, "Let $f(x)=x^3$.\nI. $f$ is one-to-one on the real numbers.\nII. $f$ is onto the real numbers.\nIII. $f^{-1}(x)=x^{1/3}$ on the real numbers.\nWhich statements are true?", COMBOS, 0, "$x^3$ is strictly increasing and has every real value in its range, so it is bijective. Solving $y=x^3$ gives the stated cube-root inverse. All three hold."),
];

export const TMUA_MK7_P1_CALIBRATED: MCQQuestion[] = [
  q("tmua-mk7-cal-p1-13", "tmua-algebra", 2, "The roots of $2x^2-7x+3=0$ are $\\alpha,\\beta$. What is $\\alpha^2+\\beta^2$?", ["$25/4$", "$29/4$", "$37/4$", "$41/4$", "$49/4$"], 2, "$\\alpha+\\beta=7/2$ and $\\alpha\\beta=3/2$. Thus $\\alpha^2+\\beta^2=(7/2)^2-2(3/2)=37/4$."),
  q("tmua-mk7-cal-p1-14", "tmua-stats", 2, "A fair coin is tossed until a head appears or three tosses have been made. What is the probability that exactly three tosses are made?", ["$1/8$", "$1/4$", "$3/8$", "$1/2$", "$3/4$"], 1, "A third toss occurs exactly when the first two tosses are tails, which has probability $(1/2)^2=1/4$."),
  q("tmua-mk7-cal-p1-15", "tmua-algebra", 3, "How many real solutions does $|x^2-4|=x$ have?", ["$0$", "$1$", "$2$", "$3$", "$4$", "$5$"], 2, "The right side requires $x\\ge0$. For $0\\le x\\le2$, $4-x^2=x$ has one valid root; for $x\\ge2$, $x^2-4=x$ has one. Total: two."),
  q("tmua-mk7-cal-p1-16", "tmua-geometry", 3, "A circle has equation $x^2+y^2-4x+6y-12=0$. What is the length of the chord cut by the $x$-axis?", ["$4$", "$2\\sqrt5$", "$4\\sqrt2$", "$6$", "$8$"], 4, "On the $x$-axis, $y=0$, so $x^2-4x-12=0$ and $x=-2,6$. The chord length is $8$."),
  q("tmua-mk7-cal-p1-17", "tmua-calc", 3, "For $x>0$, the tangent to $y=\\ln x$ at $x=a$ passes through the origin. What is $a$?", ["$1/e$", "$1$", "$e$", "$e^2$", "no such value"], 2, "The tangent is $y-\\ln a=(x-a)/a$. At the origin, $-\\ln a=-1$, so $a=e$."),
  q("tmua-mk7-cal-p1-18", "tmua-discrete", 3, "How many five-digit numbers can be formed from $1,2,3,4,5$ without repetition if the number is divisible by $4$?", ["$12$", "$18$", "$24$", "$30$", "$36$", "$48$"], 2, "The last two digits must be $12,24,32,$ or $52$. For each ending, the remaining three digits can be arranged in $3!=6$ ways, giving $24$."),
  q("tmua-mk7-cal-p1-19", "tmua-number", 3, "How many positive divisors of $2^5\\cdot3^3$ are perfect squares?", ["$4$", "$6$", "$8$", "$10$", "$12$"], 1, "A square divisor uses exponent $0,2,$ or $4$ for $2$ and exponent $0$ or $2$ for $3$. This gives $3\\cdot2=6$."),
  q("tmua-mk7-cal-p1-20", "tmua-calc", 3, "What is the maximum value of $x^2(4-x)$ for $0\\le x\\le4$?", ["$64/27$", "$128/27$", "$256/27$", "$8$", "$16$"], 2, "The derivative is $x(8-3x)$, so the interior maximum occurs at $x=8/3$. Its value is $256/27$."),
];

export const TMUA_MK7_P2_CALIBRATED: MCQQuestion[] = [
  q("tmua-mk7-cal-p2-13", "tmua-logic", 2, "A theorem says $P$ is sufficient for $Q$.\nI. $P\\Rightarrow Q$.\nII. $Q\\Rightarrow P$.\nIII. $\\neg Q\\Rightarrow\\neg P$.\nWhich statements are true?", COMBOS, 2, "Sufficiency means $P\\Rightarrow Q$, and the contrapositive III is equivalent. The converse II need not hold."),
  q("tmua-mk7-cal-p2-14", "tmua-number", 3, "For an integer $n$:\nI. $n^3-n$ is divisible by $3$.\nII. $n^3-n$ is always even.\nIII. $n^3-n$ is divisible by $12$.\nWhich statements are true?", COMBOS, 1, "$n^3-n=n(n-1)(n+1)$ is a product of three consecutive integers, so I and II hold. For $n=2$ it equals $6$, so III is false."),
  q("tmua-mk7-cal-p2-15", "tmua-algebra", 3, "Let $p(x)$ be a real polynomial.\nI. If $p(0)p(1)<0$, then $p$ has a root in $(0,1)$.\nII. If $p$ has a root in $(0,1)$, then $p(0)p(1)<0$.\nIII. If $p(0)=p(1)=0$, then $x(x-1)$ divides $p(x)$.\nWhich statements are true?", COMBOS, 2, "I follows from continuity. II can fail when a graph touches the axis or crosses it twice. III follows from the factor theorem. Thus I and III only."),
  q("tmua-mk7-cal-p2-16", "tmua-stats", 3, "Events $A,B$ satisfy $P(A)=1/3$, $P(B)=1/2$.\nI. If independent, $P(A\\cup B)=2/3$.\nII. If mutually exclusive, $P(A\\cup B)=5/6$.\nIII. They cannot be both independent and mutually exclusive.\nWhich statements are true?", COMBOS, 0, "Under independence the intersection is $1/6$, giving union $2/3$. Under mutual exclusivity the union is $5/6$. Positive-probability mutually exclusive events cannot be independent."),
  q("tmua-mk7-cal-p2-17", "tmua-calc", 3, "Let $f$ be differentiable at an interior point $a$.\nI. If $a$ is a local maximum, then $f'(a)=0$.\nII. If $f'(a)=0$, then $a$ is a local maximum or minimum.\nIII. If $f'$ changes from positive to negative at $a$, then $a$ is a local maximum.\nWhich statements are true?", COMBOS, 2, "I is Fermat's theorem. A stationary point may be an inflection, so II fails. The sign change in III gives a local maximum."),
  q("tmua-mk7-cal-p2-18", "tmua-discrete", 3, "A finite graph has every vertex of degree $3$.\nI. The number of vertices is even.\nII. The number of edges is divisible by $3$.\nIII. The graph must be connected.\nWhich statements are true?", COMBOS, 1, "If there are $v$ vertices, $3v=2e$, so $v$ is even and $e=3v/2$ is divisible by $3$. A regular graph need not be connected."),
  q("tmua-mk7-cal-p2-19", "tmua-geometry", 3, "For a circle:\nI. The perpendicular from the centre to a chord bisects the chord.\nII. Equal chords subtend equal angles at the centre.\nIII. A tangent is parallel to the radius at the point of contact.\nWhich statements are true?", COMBOS, 1, "I and II are standard circle theorems. A tangent is perpendicular, not parallel, to the radius, so III is false."),
  q("tmua-mk7-cal-p2-20", "tmua-logic", 3, "A statement has the form $\\forall x\\exists y\,P(x,y)$.\nI. The same $y$ must work for every $x$.\nII. $y$ may depend on $x$.\nIII. Its negation is $\\exists x\\forall y\,\\neg P(x,y)$.\nWhich statements are true?", COMBOS, 4, "The existential choice may depend on $x$, so I is false and II true. Negating swaps both quantifiers and negates the predicate, so III is true."),
];

export const TMUA_MK8_P1_CALIBRATED: MCQQuestion[] = [
  q("tmua-mk8-cal-p1-13", "tmua-algebra", 2, "If $x-1/x=2$, what is $x^2+1/x^2$?", ["$2$", "$4$", "$6$", "$8$", "$10$"], 2, "Squaring gives $x^2-2+1/x^2=4$, hence the required value is $6$."),
  q("tmua-mk8-cal-p1-14", "tmua-stats", 2, "Three cards numbered $1,2,3$ are shuffled. What is the probability that no card is in its original position?", ["$1/6$", "$1/3$", "$1/2$", "$2/3$", "$5/6$"], 1, "Of the $3!=6$ permutations, two have no fixed point. The probability is $2/6=1/3$."),
  q("tmua-mk8-cal-p1-15", "tmua-algebra", 3, "For how many real values of $k$ does the line $y=kx+1$ pass through a stationary point of $y=x^3-3x$?", ["$0$", "$1$", "$2$", "$3$", "infinitely many"], 2, "The stationary points are $(1,-2)$ and $(-1,2)$. The corresponding values of $k$ are $-3$ and $-1$, so there are two."),
  q("tmua-mk8-cal-p1-16", "tmua-geometry", 3, "A triangle has sides $7,8,9$. What is its area?", ["$6\\sqrt5$", "$10\\sqrt3$", "$12\\sqrt5$", "$18\\sqrt3$", "$24$"], 2, "Heron's formula gives semiperimeter $12$ and area $\\sqrt{12\\cdot5\\cdot4\\cdot3}=12\\sqrt5$."),
  q("tmua-mk8-cal-p1-17", "tmua-calc", 3, "The tangent to $y=x^2+1/x$ at $x=1$ meets the $y$-axis at what value?", ["$0$", "$1$", "$2$", "$3$", "$4$"], 1, "At $x=1$, $y=2$ and $y'=1$. The tangent is $y=x+1$, so its $y$-intercept is $1$."),
  q("tmua-mk8-cal-p1-18", "tmua-discrete", 3, "How many ways can six people be divided into three unlabeled pairs?", ["$8$", "$12$", "$15$", "$30$", "$45$", "$90$"], 2, "$6!/(2^3 3!)=15$: divide by the order within each pair and by the order of the three pairs."),
  q("tmua-mk8-cal-p1-19", "tmua-number", 3, "What is the smallest positive integer $n$ for which $2^n\\equiv1\\pmod{31}$?", ["$3$", "$4$", "$5$", "$6$", "$10$"], 2, "$2^5=32\\equiv1\\pmod{31}$, while the earlier powers $2,4,8,16$ are not congruent to $1$."),
  q("tmua-mk8-cal-p1-20", "tmua-calc", 3, "Evaluate $\\int_0^1 x(1-x)^2\\,dx$.", ["$1/6$", "$1/10$", "$1/12$", "$1/15$", "$1/20$"], 2, "Expand and integrate: $\\int_0^1(x-2x^2+x^3)dx=1/2-2/3+1/4=1/12$."),
];

export const TMUA_MK8_P2_CALIBRATED: MCQQuestion[] = [
  q("tmua-mk8-cal-p2-13", "tmua-logic", 2, "The statement '$P$ only if $Q$' is true.\nI. $P\\Rightarrow Q$.\nII. $Q\\Rightarrow P$.\nIII. $\\neg Q\\Rightarrow\\neg P$.\nWhich statements are true?", COMBOS, 2, "'Only if' gives $P\\Rightarrow Q$, and III is its contrapositive. The converse II need not hold."),
  q("tmua-mk8-cal-p2-14", "tmua-number", 3, "For every integer $n$:\nI. $n^2+n$ is even.\nII. $n^4-n^2$ is divisible by $12$.\nIII. $n^2+n+1$ is prime.\nWhich statements are true?", COMBOS, 1, "I is a product of consecutive integers. For II, $n^2(n-1)(n+1)$ is divisible by both $3$ and $4$. III fails at $n=4$, where the value is $21$."),
  q("tmua-mk8-cal-p2-15", "tmua-algebra", 3, "Let $f(x)=|x|$.\nI. $f$ is continuous on the real numbers.\nII. $f$ is differentiable at $0$.\nIII. $f$ is one-to-one on the real numbers.\nWhich statements are true?", COMBOS, 3, "The function is continuous, so I holds. Its one-sided derivatives at zero differ, and $f(x)=f(-x)$, so II and III are false."),
  q("tmua-mk8-cal-p2-16", "tmua-stats", 3, "A fair die is rolled twice.\nI. 'The first score is even' and 'the sum is even' are independent.\nII. 'The sum is $7$' and 'the first score is $1$' are independent.\nIII. 'The scores are equal' and 'the first score is $1$' are independent.\nWhich statements are true?", COMBOS, 0, "For I, the intersection has probability $1/4$, equal to the product $1/2\\cdot1/2$. For II and III, each intersection is $1/36$, equal to $(1/6)(1/6)$. All three hold."),
  q("tmua-mk8-cal-p2-17", "tmua-calc", 3, "Let $f$ be differentiable on the real numbers.\nI. If $f'(x)>0$ everywhere, then $f$ is one-to-one.\nII. If $f$ is one-to-one, then $f'(x)>0$ everywhere.\nIII. If $f'(x)=0$ everywhere, then $f$ is constant.\nWhich statements are true?", COMBOS, 2, "I follows from strict increase. II fails for decreasing one-to-one functions and for $x^3$ at zero. III follows from the mean value theorem."),
  q("tmua-mk8-cal-p2-18", "tmua-discrete", 3, "A tree has $n\\ge2$ vertices.\nI. It has $n-1$ edges.\nII. It has at least two vertices of degree $1$.\nIII. Adding any new edge between existing vertices creates exactly one cycle.\nWhich statements are true?", COMBOS, 0, "All three are standard structural properties of trees: the edge count, existence of leaves, and the unique path between each pair of vertices."),
  q("tmua-mk8-cal-p2-19", "tmua-geometry", 3, "For a non-degenerate triangle:\nI. The three medians meet at one point.\nII. The three perpendicular bisectors meet at one point.\nIII. These two intersection points are always the same.\nWhich statements are true?", COMBOS, 1, "I defines the centroid and II the circumcentre. They coincide only in special triangles, so III is false."),
  q("tmua-mk8-cal-p2-20", "tmua-logic", 3, "A universal claim is tested on the first $1000$ positive integers and holds every time.\nI. The claim has been proved.\nII. The evidence may suggest the claim is true.\nIII. A single later counterexample would disprove the claim.\nWhich statements are true?", COMBOS, 4, "Finite checking does not prove an unrestricted universal claim, so I is false. It is evidence, and one counterexample is enough to disprove the claim."),
];

export const TMUA_MK2_P1_CALIBRATED: MCQQuestion[] = [
  q("tmua-mk2-cal-p1-13", "tmua-algebra", 2, "The equation $x+4/x=5$ has two positive roots. What is the difference between the larger and smaller root?", ["$1$", "$2$", "$3$", "$4$", "$5$"], 2, "$x^2-5x+4=0$ has roots $1$ and $4$, whose difference is $3$."),
  q("tmua-mk2-cal-p1-14", "tmua-stats", 2, "A box contains $3$ red, $2$ blue and $1$ green ball. Two are selected without replacement. What is the probability that they have different colours?", ["$7/15$", "$8/15$", "$3/5$", "$11/15$", "$4/5$"], 3, "There are $15$ unordered pairs. Same-colour pairs number $\\binom32+\\binom22=4$, so the probability of different colours is $11/15$."),
  q("tmua-mk2-cal-p1-15", "tmua-algebra", 3, "For which values of $k$ does $x^2-2kx+k+2=0$ have two distinct real roots?", ["$k<-1$", "$k<-1$ or $k>2$", "$-1<k<2$", "$k>2$", "$k\\ne0$"], 1, "The discriminant is $4(k^2-k-2)=4(k-2)(k+1)$. It is positive when $k<-1$ or $k>2$."),
  q("tmua-mk2-cal-p1-16", "tmua-geometry", 3, "The point $(a,2a)$ lies on the circle $x^2+y^2-6x+4y=0$. What is the sum of the possible values of $a$?", ["$-2/5$", "$-1/5$", "$0$", "$1/5$", "$2/5$"], 0, "Substitution gives $5a^2+2a=0$. The roots are $0$ and $-2/5$, so their sum is $-2/5$."),
  q("tmua-mk2-cal-p1-17", "tmua-calc", 3, "The function $f(x)=x^3-6x^2+9x$ has a local maximum and a local minimum. What is the difference between their values?", ["$2$", "$3$", "$4$", "$5$", "$6$"], 2, "$f'(x)=3(x-1)(x-3)$, so the stationary values are $f(1)=4$ and $f(3)=0$. Their difference is $4$."),
  q("tmua-mk2-cal-p1-18", "tmua-discrete", 3, "How many four-digit even numbers can be formed from $1,2,3,4,5$ without repetition?", ["$24$", "$36$", "$40$", "$48$", "$60$"], 3, "The final digit has two choices. The remaining positions can be filled in $4\\cdot3\\cdot2=24$ ways, giving $48$."),
  q("tmua-mk2-cal-p1-19", "tmua-number", 3, "How many integers from $1$ to $200$ are divisible by exactly one of $6$ and $10$?", ["$20$", "$26$", "$33$", "$40$", "$41$"], 4, "There are $33$ multiples of $6$, $20$ of $10$, and $6$ of both. Exactly one count is $33+20-2(6)=41$."),
  q("tmua-mk2-cal-p1-20", "tmua-calc", 3, "What is the area under $y=|x^2-1|$ from $x=-1$ to $x=1$?", ["$2/3$", "$1$", "$4/3$", "$3/2$", "$2$"], 2, "On this interval $|x^2-1|=1-x^2$. Thus the area is $\\int_{-1}^1(1-x^2)dx=4/3$."),
];

export const TMUA_MK2_P2_CALIBRATED: MCQQuestion[] = [
  q("tmua-mk2-cal-p2-13", "tmua-logic", 2, "For real $x$, $x>4$ is sufficient for $x^2>16$.\nI. The implication is true.\nII. Its converse is true.\nIII. Its contrapositive is true.\nWhich statements are true?", COMBOS, 2, "I is true. The converse fails at $x=-5$. The contrapositive is equivalent to I and is true. Thus I and III only."),
  q("tmua-mk2-cal-p2-14", "tmua-number", 3, "For every integer $n$:\nI. If $n$ is odd, then $n^2\\equiv1\\pmod8$.\nII. If $n^2\\equiv1\\pmod8$, then $n$ is odd.\nIII. If $n$ is even, then $n^2$ is divisible by $8$.\nWhich statements are true?", COMBOS, 1, "Every odd integer has square congruent to $1$ modulo $8$, and the congruence forces odd parity. III fails for $n=2$."),
  q("tmua-mk2-cal-p2-15", "tmua-algebra", 3, "Let $f(x)=x^2-2x$.\nI. $f$ is one-to-one on $[1,\\infty)$.\nII. The range of $f$ on the real numbers is $[-1,\\infty)$.\nIII. $f(x)=0$ has exactly one real solution.\nWhich statements are true?", COMBOS, 1, "$f=(x-1)^2-1$ is increasing on $[1,\\infty)$ and has the stated range. Its zeros are $0$ and $2$, so III is false."),
  q("tmua-mk2-cal-p2-16", "tmua-stats", 3, "A fair coin is tossed twice.\nI. 'At least one head' and 'first toss is a head' are independent.\nII. 'Exactly one head' and 'first toss is a head' are independent.\nIII. 'Both tosses match' and 'first toss is a head' are independent.\nWhich statements are true?", COMBOS, 4, "I is false since the conditional probability is $1$, not $3/4$. For II and III, the intersection and product probabilities are each $1/4$, so both hold."),
  q("tmua-mk2-cal-p2-17", "tmua-calc", 3, "Let $f$ be continuous on $[-1,1]$.\nI. If $f(-1)f(1)<0$, then $f$ has a zero in $(-1,1)$.\nII. If $f$ has exactly one zero in $(-1,1)$, then $f(-1)f(1)<0$.\nIII. If $f(-1)=f(1)$, then $f$ is constant.\nWhich statements are true?", COMBOS, 3, "I is the intermediate value theorem. II can fail if the function touches zero, and III is false for many non-constant functions. Thus I only."),
  q("tmua-mk2-cal-p2-18", "tmua-discrete", 3, "For a graph with $v$ vertices and $e$ edges:\nI. The sum of the degrees is $2e$.\nII. The number of odd-degree vertices is even.\nIII. If $e=v-1$, the graph is a tree.\nWhich statements are true?", COMBOS, 1, "I is the handshaking lemma and implies II. III also needs connectedness, so it is not sufficient. Thus I and II only."),
  q("tmua-mk2-cal-p2-19", "tmua-geometry", 3, "For two circles:\nI. Equal radii are sufficient for congruence.\nII. Equal circumferences are necessary for congruence.\nIII. Equal areas are sufficient for congruence.\nWhich statements are true?", COMBOS, 0, "A circle is determined up to congruence by its radius. Equal radius, circumference, or area each determines the same radius, so all three hold."),
  q("tmua-mk2-cal-p2-20", "tmua-logic", 3, "A proposed proof of $P\\Rightarrow Q$ begins by assuming $Q$ and derives $P$.\nI. It proves the desired implication.\nII. It proves the converse.\nIII. It is sufficient if $P$ and $Q$ are independently known to be equivalent.\nWhich statements are true?", COMBOS, 4, "The argument establishes $Q\\Rightarrow P$, the converse, so II holds but I does not. If equivalence is independently known, the reverse implication is already guaranteed, so III holds."),
];

export const TMUA_MK5_P1_CALIBRATED: MCQQuestion[] = [
  q("tmua-mk5-cal-p1-13", "tmua-algebra", 2, "The roots of $x^2-4x-1=0$ are $\\alpha,\\beta$. What is $(\\alpha-\\beta)^2$?", ["$12$", "$16$", "$20$", "$24$", "$28$"], 2, "$(\\alpha-\\beta)^2=(\\alpha+\\beta)^2-4\\alpha\\beta=4^2-4(-1)=20$."),
  q("tmua-mk5-cal-p1-14", "tmua-stats", 2, "A fair die is rolled twice. Given that the sum is at least $10$, what is the probability that both scores are equal?", ["$1/6$", "$1/4$", "$1/3$", "$1/2$", "$2/3$"], 2, "There are six ordered outcomes with sum at least $10$. Two, $(5,5)$ and $(6,6)$, are doubles, so the probability is $1/3$."),
  q("tmua-mk5-cal-p1-15", "tmua-algebra", 3, "How many real solutions does $2^x=3-x$ have?", ["$0$", "$1$", "$2$", "$3$", "infinitely many"], 1, "$2^x$ is strictly increasing while $3-x$ is strictly decreasing, so there is at most one intersection. Since $x=1$ satisfies the equation, there is exactly one."),
  q("tmua-mk5-cal-p1-16", "tmua-geometry", 3, "A chord of length $16$ lies in a circle of radius $10$. What is its distance from the centre?", ["$4$", "$5$", "$6$", "$8$", "$12$"], 2, "The perpendicular from the centre bisects the chord. The distance is $\\sqrt{10^2-8^2}=6$."),
  q("tmua-mk5-cal-p1-17", "tmua-calc", 3, "For $a>0$, the curve $y=x^3-3a^2x$ has two stationary points. What is the vertical distance between them?", ["$2a^3$", "$3a^3$", "$4a^3$", "$6a^3$", "$8a^3$"], 2, "Stationary points occur at $x=\\pm a$. Their values are $2a^3$ and $-2a^3$, so the vertical distance is $4a^3$."),
  q("tmua-mk5-cal-p1-18", "tmua-discrete", 3, "How many shortest paths are there from $(0,0)$ to $(5,3)$ using only unit moves right or up?", ["$28$", "$35$", "$56$", "$70$", "$120$"], 2, "Each path has five right moves and three up moves. Choose the positions of the up moves: $\\binom83=56$."),
  q("tmua-mk5-cal-p1-19", "tmua-number", 3, "What is the smallest positive integer divisible by $12$ that leaves remainder $1$ when divided by $5$?", ["$12$", "$24$", "$36$", "$48$", "$60$"], 2, "The first multiples of $12$ are $12,24,36,48$. The first congruent to $1$ modulo $5$ is $36$."),
  q("tmua-mk5-cal-p1-20", "tmua-calc", 3, "What is the area enclosed by $y=4x-x^2$ and the $x$-axis?", ["$16/3$", "$8$", "$32/3$", "$12$", "$64/3$"], 2, "The curve meets the axis at $0$ and $4$. The area is $\\int_0^4(4x-x^2)dx=32/3$."),
];

export const TMUA_MK5_P2_CALIBRATED: MCQQuestion[] = [
  q("tmua-mk5-cal-p2-13", "tmua-logic", 2, "A condition $A$ is necessary but not sufficient for $B$.\nI. $B\\Rightarrow A$.\nII. $A\\Rightarrow B$.\nIII. There is a case where $A$ holds but $B$ does not.\nWhich statements are true?", COMBOS, 2, "Necessity gives $B\\Rightarrow A$. Failure of sufficiency means some case has $A$ true and $B$ false. Thus I and III hold."),
  q("tmua-mk5-cal-p2-14", "tmua-number", 3, "For a prime $p$ and integers $a,b$:\nI. If $p\\mid ab$, then $p\\mid a$ or $p\\mid b$.\nII. If $p\\mid a+b$, then $p\\mid a$ or $p\\mid b$.\nIII. If $p\\mid a^2$, then $p\\mid a$.\nWhich statements are true?", COMBOS, 2, "I is Euclid's lemma. II is false, for example $5\\mid2+3$ but divides neither addend. III follows by applying I to $a\\cdot a$."),
  q("tmua-mk5-cal-p2-15", "tmua-algebra", 3, "Let $f(x)=1/(x-1)$.\nI. The domain excludes $1$.\nII. The range excludes $0$.\nIII. $f(f(x))=x$ wherever both sides are defined.\nWhich statements are true?", COMBOS, 1, "I and II hold. But $f(f(x))=(x-1)/(2-x)$, not $x$ in general, so III is false."),
  q("tmua-mk5-cal-p2-16", "tmua-stats", 3, "Random variables $X,Y$ have finite variance.\nI. $E(X+Y)=E(X)+E(Y)$.\nII. $\\operatorname{Var}(X+Y)=\\operatorname{Var}(X)+\\operatorname{Var}(Y)$ always.\nIII. If $X,Y$ are independent, their variances add.\nWhich statements are true?", COMBOS, 2, "Expectation is linear without independence, so I holds. Variance includes a covariance term, so II is not always true. Independence gives III."),
  q("tmua-mk5-cal-p2-17", "tmua-calc", 3, "Let $f$ be twice differentiable and $f'(a)=0$.\nI. If $f''(a)>0$, then $a$ is a local minimum.\nII. If $f''(a)=0$, then $a$ is not an extremum.\nIII. If $a$ is a local maximum, then $f''(a)<0$.\nWhich statements are true?", COMBOS, 3, "I is the second derivative test. II fails for $x^4$ at zero, and III fails for $-x^4$ at zero. Thus I only."),
  q("tmua-mk5-cal-p2-18", "tmua-discrete", 3, "A simple graph has $6$ vertices.\nI. It has at most $15$ edges.\nII. If every vertex has degree $5$, it is complete.\nIII. It can have exactly one vertex of odd degree.\nWhich statements are true?", COMBOS, 1, "The maximum is $\\binom62=15$, and degree $5$ joins each vertex to all others. The handshaking lemma forbids exactly one odd-degree vertex."),
  q("tmua-mk5-cal-p2-19", "tmua-geometry", 3, "For two similar figures with linear scale factor $k>0$:\nI. Perimeters scale by $k$.\nII. Areas scale by $k^2$.\nIII. Volumes scale by $k^2$.\nWhich statements are true?", COMBOS, 1, "Perimeters scale by $k$, areas by $k^2$, and volumes by $k^3$. Hence I and II only."),
  q("tmua-mk5-cal-p2-20", "tmua-logic", 3, "A proof checks a claim for $n=1$, then assumes it for $n=k$ and proves it for $n=k+2$.\nI. This proves the claim for every positive integer.\nII. It proves the claim for every positive odd integer.\nIII. Adding a base case at $n=2$ would prove it for every positive integer.\nWhich statements are true?", COMBOS, 4, "Starting at $1$ and stepping by $2$ reaches only odd integers, so II holds but I does not. A base case at $2$ starts the even chain, making III true."),
];
