// TSA 模拟卷2 —— Section 1（批判性思维 + 问题解决），id 前缀 tsa-mk2-*。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const TSA_MK2_MCQ: MCQQuestion[] = [
  { id: "tsa-mk2-01", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "Supporters of the ban on advertising unhealthy food to children say it will reduce childhood obesity. Yet children see such adverts mainly through programmes streamed from abroad, which the ban cannot reach. The ban is therefore unlikely to achieve its aim.\n\nWhich of the following is the main conclusion?",
    options: [{ key: "A", text: "The ban aims to reduce childhood obesity." },{ key: "B", text: "Children mainly see the adverts through foreign streaming." },{ key: "C", text: "The ban is unlikely to achieve its aim." },{ key: "D", text: "Advertising influences children." },{ key: "E", text: "Childhood obesity is a problem." }],
    answer: "C", solution: "'Therefore' marks the conclusion; the point about foreign streaming is the reason supporting it." },
  { id: "tsa-mk2-02", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "The minister said that because the number of people in work has reached a record high, the economy must be healthy.\n\nWhich assumption does the minister's argument rely on?",
    options: [{ key: "A", text: "A record number in work reliably indicates a healthy economy, ignoring factors such as low pay or underemployment." },{ key: "B", text: "The population has grown." },{ key: "C", text: "Ministers understand economics." },{ key: "D", text: "Employment is measured accurately." },{ key: "E", text: "The economy was previously unhealthy." }],
    answer: "A", solution: "Inferring 'healthy economy' from 'record employment' assumes employment numbers capture economic health, overlooking pay, hours or underemployment." },
  { id: "tsa-mk2-03", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "Whenever the school football team wins, the local shop sells more pies the next day. Last Monday the shop sold a record number of pies. So the team must have won on Sunday.\n\nWhich of the following best describes the flaw in this reasoning?",
    options: [{ key: "A", text: "It assumes that because one thing follows another, the second must have been caused by the first." },{ key: "B", text: "It treats a possible cause of the pie sales as the only possible cause." },{ key: "C", text: "It attacks the shopkeeper." },{ key: "D", text: "It relies on an unrepresentative sample." },{ key: "E", text: "It presents a false dilemma." }],
    answer: "B", solution: "A win is only one possible reason for high pie sales; the argument wrongly treats it as the only explanation, ignoring other causes." },
  { id: "tsa-mk2-04", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "A newspaper claims its readers are the best informed, citing a survey in which its own readers rated themselves highly on current affairs.\n\nWhich of the following, if true, would most weaken the newspaper's claim?",
    options: [{ key: "A", text: "The newspaper has many readers." },{ key: "B", text: "When tested on current affairs, the newspaper's readers scored no higher than average." },{ key: "C", text: "The survey was conducted online." },{ key: "D", text: "Readers enjoy the newspaper." },{ key: "E", text: "Other newspapers also run surveys." }],
    answer: "B", solution: "Self-rating is unreliable; an objective test showing no advantage undermines the claim that the readers are best informed." },
  { id: "tsa-mk2-05", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "A politician argues that lowering the speed limit will save lives, because slower cars cause less severe injuries in a crash.\n\nWhich of the following, if true, would most strengthen this argument?",
    options: [{ key: "A", text: "Drivers dislike lower speed limits." },{ key: "B", text: "In areas where the limit was lowered, the number of serious injuries fell significantly." },{ key: "C", text: "Cars are safer than they used to be." },{ key: "D", text: "Speed limits are set by law." },{ key: "E", text: "Some drivers exceed the limit." }],
    answer: "B", solution: "Evidence that lowering the limit actually reduced serious injuries directly supports the claim that it saves lives." },
  { id: "tsa-mk2-06", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "All the members of the committee I have spoken to support the proposal. Therefore the whole committee supports it.\n\nWhich of the following best describes the weakness in this argument?",
    options: [{ key: "A", text: "It generalises to the whole committee from possibly only some of its members." },{ key: "B", text: "It confuses cause and effect." },{ key: "C", text: "It attacks the members personally." },{ key: "D", text: "It offers only two options." },{ key: "E", text: "It reasons in a circle." }],
    answer: "A", solution: "The speaker has only spoken to some members but concludes about all of them—an unwarranted generalisation from a partial sample." },
  { id: "tsa-mk2-07", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "The report recommends replacing the old boilers because doing so will cut heating bills. But the new boilers cost far more to install than the bills they would save over their lifetime.\n\nWhich of the following is the main conclusion implicitly supported by the second sentence?",
    options: [{ key: "A", text: "The old boilers should be replaced." },{ key: "B", text: "Replacing the boilers is not, overall, worth the cost." },{ key: "C", text: "Heating bills are high." },{ key: "D", text: "New boilers are efficient." },{ key: "E", text: "The report is long." }],
    answer: "B", solution: "The second sentence gives a reason cutting against the recommendation, supporting the implicit conclusion that replacement is not worthwhile overall." },
  { id: "tsa-mk2-08", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "Principle: People should be free to take risks that affect only themselves.\n\nWhich of the following judgements best conforms to this principle?",
    options: [{ key: "A", text: "An adult who fully understands the risks should be allowed to climb a dangerous mountain alone." },{ key: "B", text: "A factory should be allowed to release toxic fumes over a neighbourhood." },{ key: "C", text: "A driver should be allowed to drive drunk on public roads." },{ key: "D", text: "A person should be allowed to set fires that spread to others' homes." },{ key: "E", text: "A company should be allowed to sell unsafe toys." }],
    answer: "A", solution: "Only A involves a risk affecting only the person taking it; the others impose risks on other people, which the principle does not license." },
  { id: "tsa-mk2-09", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "Since the introduction of the new software, the team has completed more tasks each week. The manager concludes that the software has made the team more productive.\n\nWhich of the following, if true, would most weaken the manager's conclusion?",
    options: [{ key: "A", text: "The team likes the new software." },{ key: "B", text: "At the same time as the software was introduced, two extra staff joined the team." },{ key: "C", text: "The software was recommended by experts." },{ key: "D", text: "Tasks are logged automatically." },{ key: "E", text: "The team meets every Monday." }],
    answer: "B", solution: "If extra staff arrived simultaneously, the increased output may be due to them rather than the software, weakening the causal claim." },
  { id: "tsa-mk2-10", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "A charity states that donations rose after it launched an advertising campaign, proving that the campaign was effective.\n\nWhich of the following is an assumption the charity's reasoning depends on?",
    options: [{ key: "A", text: "The rise in donations was due to the campaign rather than to some other cause." },{ key: "B", text: "The campaign was expensive." },{ key: "C", text: "Donors are generous." },{ key: "D", text: "The charity is well known." },{ key: "E", text: "Advertising is common." }],
    answer: "A", solution: "Concluding the campaign was effective assumes it, rather than an unrelated factor (a news event, the season), caused the rise in donations." },
  { id: "tsa-mk2-11", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "If a student has revised properly, they will pass. Priya has not passed. So Priya cannot have revised properly.\n\nWhich of the following arguments has the same structure as the one above?",
    options: [{ key: "A", text: "If a plant is watered, it grows. This plant has not grown. So it was not watered." },{ key: "B", text: "If a plant is watered, it grows. This plant was watered. So it grew." },{ key: "C", text: "If a plant is watered, it grows. This plant grew. So it was watered." },{ key: "D", text: "Plants grow only in summer. It is not summer. So plants are not growing." },{ key: "E", text: "This plant grew, so it must be summer." }],
    answer: "A", solution: "Original: if P then Q; not Q; so not P (modus tollens). A has exactly this form: if watered then grows; not grown; so not watered." },
  { id: "tsa-mk2-12", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "The manager says the office should return to full-time in-person work, because the most productive week last year was one when everyone happened to be in the office.\n\nWhich of the following best describes the weakness in the manager's reasoning?",
    options: [{ key: "A", text: "It draws a general conclusion from a single, possibly untypical, week." },{ key: "B", text: "It attacks remote workers personally." },{ key: "C", text: "It offers only two options." },{ key: "D", text: "It reasons in a circle." },{ key: "E", text: "It appeals to authority." }],
    answer: "A", solution: "One exceptional week is a very small and possibly unrepresentative sample from which to conclude that full-time in-person work is generally more productive." },
  { id: "tsa-mk2-13", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "One tap fills a tank in $6$ hours and another fills it in $12$ hours. How long do they take to fill it together?",
    options: [{ key: "A", text: "$4$ 小时" },{ key: "B", text: "$9$ 小时" },{ key: "C", text: "$36$ 小时" },{ key: "D", text: "$6$ 小时" },{ key: "E", text: "$5$ 小时" }],
    answer: "A", solution: "Combined rate $=\\tfrac1{6}+\\tfrac1{12}$ tanks/hour; time $=\\dfrac1{1/6+1/12}=4$ hours." },
  { id: "tsa-mk2-14", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "At a meeting of $6$ people, everyone shakes hands exactly once with everyone else. How many handshakes take place?",
    options: [{ key: "A", text: "$15$" },{ key: "B", text: "$6$" },{ key: "C", text: "$36$" },{ key: "D", text: "$30$" },{ key: "E", text: "$21$" }],
    answer: "A", solution: "Number of handshakes $=\\binom{6}2=\\dfrac{6\\cdot5}2=15.$" },
  { id: "tsa-mk2-15", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "At a meeting of $8$ people, everyone shakes hands exactly once with everyone else. How many handshakes take place?",
    options: [{ key: "A", text: "$36$" },{ key: "B", text: "$28$" },{ key: "C", text: "$8$" },{ key: "D", text: "$64$" },{ key: "E", text: "$56$" }],
    answer: "B", solution: "Number of handshakes $=\\binom{8}2=\\dfrac{8\\cdot7}2=28.$" },
  { id: "tsa-mk2-16", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "At a meeting of $10$ people, everyone shakes hands exactly once with everyone else. How many handshakes take place?",
    options: [{ key: "A", text: "$10$" },{ key: "B", text: "$90$" },{ key: "C", text: "$100$" },{ key: "D", text: "$45$" },{ key: "E", text: "$55$" }],
    answer: "D", solution: "Number of handshakes $=\\binom{10}2=\\dfrac{10\\cdot9}2=45.$" },
  { id: "tsa-mk2-17", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "At a meeting of $12$ people, everyone shakes hands exactly once with everyone else. How many handshakes take place?",
    options: [{ key: "A", text: "$132$" },{ key: "B", text: "$144$" },{ key: "C", text: "$66$" },{ key: "D", text: "$12$" },{ key: "E", text: "$78$" }],
    answer: "C", solution: "Number of handshakes $=\\binom{12}2=\\dfrac{12\\cdot11}2=66.$" },
  { id: "tsa-mk2-18", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "At a meeting of $5$ people, everyone shakes hands exactly once with everyone else. How many handshakes take place?",
    options: [{ key: "A", text: "$25$" },{ key: "B", text: "$20$" },{ key: "C", text: "$10$" },{ key: "D", text: "$5$" },{ key: "E", text: "$15$" }],
    answer: "C", solution: "Number of handshakes $=\\binom{5}2=\\dfrac{5\\cdot4}2=10.$" },
  { id: "tsa-mk2-19", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 3, marks: 1,
    question: "A large cube of side $3$ units is painted on all outer faces and then cut into unit cubes. How many small cubes have exactly two painted faces?",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$36$" },{ key: "C", text: "$6$" },{ key: "D", text: "$8$" },{ key: "E", text: "$12$" }],
    answer: "E", solution: "Two-face cubes lie along edges (excluding corners): $12(n-2)=12(3-2)=12.$" },
  { id: "tsa-mk2-20", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 3, marks: 1,
    question: "A large cube of side $5$ units is painted on all outer faces and then cut into unit cubes. How many small cubes have exactly two painted faces?",
    options: [{ key: "A", text: "$60$" },{ key: "B", text: "$27$" },{ key: "C", text: "$54$" },{ key: "D", text: "$36$" },{ key: "E", text: "$8$" }],
    answer: "D", solution: "Two-face cubes lie along edges (excluding corners): $12(n-2)=12(5-2)=36.$" },
  { id: "tsa-mk2-21", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 3, marks: 1,
    question: "A large cube of side $6$ units is painted on all outer faces and then cut into unit cubes. How many small cubes have exactly two painted faces?",
    options: [{ key: "A", text: "$96$" },{ key: "B", text: "$72$" },{ key: "C", text: "$48$" },{ key: "D", text: "$8$" },{ key: "E", text: "$64$" }],
    answer: "C", solution: "Two-face cubes lie along edges (excluding corners): $12(n-2)=12(6-2)=48.$" },
  { id: "tsa-mk2-22", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 3, marks: 1,
    question: "A cube of side $3$ is painted and cut into unit cubes. How many have exactly one painted face?",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$12$" },{ key: "C", text: "$54$" },{ key: "D", text: "$1$" },{ key: "E", text: "$8$" }],
    answer: "A", solution: "One-face cubes lie on faces (excluding edges): $6(n-2)^2=6(3-2)^2=6.$" },
  { id: "tsa-mk2-23", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 3, marks: 1,
    question: "A cube of side $5$ is painted and cut into unit cubes. How many have exactly one painted face?",
    options: [{ key: "A", text: "$54$" },{ key: "B", text: "$36$" },{ key: "C", text: "$150$" },{ key: "D", text: "$27$" },{ key: "E", text: "$8$" }],
    answer: "A", solution: "One-face cubes lie on faces (excluding edges): $6(n-2)^2=6(5-2)^2=54.$" },
  { id: "tsa-mk2-24", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 3, marks: 1,
    question: "A cube of side $6$ is painted and cut into unit cubes. How many have exactly one painted face?",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$96$" },{ key: "C", text: "$48$" },{ key: "D", text: "$216$" },{ key: "E", text: "$64$" }],
    answer: "B", solution: "One-face cubes lie on faces (excluding edges): $6(n-2)^2=6(6-2)^2=96.$" }
];
