// TSA 模拟卷1 —— Section 1（批判性思维 + 问题解决），id 前缀 tsa-mk1-*。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const TSA_MK1_MCQ: MCQQuestion[] = [
  { id: "tsa-mk1-01", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "The new bypass was built to reduce traffic in the town centre. Since it opened, congestion in the centre has indeed fallen. However, traffic on the residential roads leading to the bypass has increased sharply, and accidents there have risen. The bypass has simply moved the problem rather than solving it.\n\nWhich of the following best expresses the main conclusion of the argument?",
    options: [{ key: "A", text: "The bypass was built to reduce town-centre traffic." },{ key: "B", text: "Congestion in the town centre has fallen." },{ key: "C", text: "The bypass has moved the traffic problem rather than solving it." },{ key: "D", text: "Accidents on residential roads have risen." },{ key: "E", text: "Traffic on residential roads has increased." }],
    answer: "C", solution: "The final sentence is the conclusion; the earlier statements are evidence leading to it. B, D and E are supporting facts, and A is background." },
  { id: "tsa-mk1-02", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "Companies claim that longer opening hours improve customer service. But staff forced to work late become tired and make more errors, and customers report worse experiences in the final hours. Extending opening hours can therefore harm the very service it is meant to improve.\n\nWhich of the following is the main conclusion?",
    options: [{ key: "A", text: "Staff who work late become tired." },{ key: "B", text: "Extending opening hours can harm customer service." },{ key: "C", text: "Companies want to improve customer service." },{ key: "D", text: "Tired staff make more errors." },{ key: "E", text: "Customers report worse experiences late at night." }],
    answer: "B", solution: "The conclusion is signalled by 'therefore'; the rest are premises supporting it." },
  { id: "tsa-mk1-03", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "The council plans to cut street lighting at night to save money. A spokesperson argued that this is safe, since most burglaries happen during the day.\n\nWhich of the following is an assumption underlying the spokesperson's argument?",
    options: [{ key: "A", text: "Street lighting is expensive to maintain." },{ key: "B", text: "Reducing night lighting will not significantly increase crime or other harms at night." },{ key: "C", text: "Burglaries are the most common crime." },{ key: "D", text: "People prefer darker streets." },{ key: "E", text: "The council has a limited budget." }],
    answer: "B", solution: "For 'safe' to follow, the argument must assume darkness at night won't raise night-time crime or accidents; deny this and the safety claim collapses." },
  { id: "tsa-mk1-04", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "A commentator argues that since exam results have improved every year, schools must be teaching better than before.\n\nWhich of the following is an assumption on which this argument depends?",
    options: [{ key: "A", text: "Students work harder than before." },{ key: "B", text: "The improvement in results reflects better teaching rather than, say, easier exams." },{ key: "C", text: "Exams are taken every year." },{ key: "D", text: "Schools employ more teachers." },{ key: "E", text: "Results are published annually." }],
    answer: "B", solution: "The inference from 'results improved' to 'teaching improved' assumes the results measure teaching quality and are not explained by easier exams or other factors." },
  { id: "tsa-mk1-05", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "Every successful entrepreneur I have read about wakes up before 6 a.m. So if you want to be successful, the key is to start waking up before 6 a.m.\n\nWhich of the following best describes the flaw in this reasoning?",
    options: [{ key: "A", text: "It relies on an unrepresentative sample." },{ key: "B", text: "It treats a feature that may merely accompany success as though it causes success." },{ key: "C", text: "It appeals to the reader's emotions." },{ key: "D", text: "It contradicts itself." },{ key: "E", text: "It attacks the entrepreneurs personally." }],
    answer: "B", solution: "The argument assumes early rising causes success, when it may just correlate with it (or result from other traits)—mistaking correlation for cause." },
  { id: "tsa-mk1-06", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "My opponent argues that we should invest more in flood defences. But he owns a house near the river, so his argument should be dismissed.\n\nWhich of the following best describes the flaw in this argument?",
    options: [{ key: "A", text: "It generalises from too few cases." },{ key: "B", text: "It rejects a claim by attacking the person making it rather than its merits." },{ key: "C", text: "It presents only two options." },{ key: "D", text: "It confuses cause and effect." },{ key: "E", text: "It appeals to popularity." }],
    answer: "B", solution: "The argument dismisses the proposal because of who makes it (and their interest), not by addressing whether the proposal is sound—an ad hominem." },
  { id: "tsa-mk1-07", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "Either we allow the new factory to be built, or the town will suffer permanent economic decline. We cannot accept decline, so the factory must be built.\n\nWhich of the following best identifies the weakness in the argument?",
    options: [{ key: "A", text: "It assumes there are only two possible outcomes when others may exist." },{ key: "B", text: "It attacks the character of opponents." },{ key: "C", text: "It relies on a biased sample." },{ key: "D", text: "It uses circular reasoning." },{ key: "E", text: "It confuses correlation with causation." }],
    answer: "A", solution: "The argument offers a false dilemma: it presents 'factory or permanent decline' as the only options, ignoring other ways the town might avoid decline." },
  { id: "tsa-mk1-08", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "A study found that towns with more libraries have lower crime rates. The researchers concluded that building libraries reduces crime.\n\nWhich of the following, if true, would most weaken the researchers' conclusion?",
    options: [{ key: "A", text: "Some libraries are open on weekends." },{ key: "B", text: "Wealthier towns tend both to build more libraries and to have less crime for other reasons." },{ key: "C", text: "Libraries are popular with residents." },{ key: "D", text: "Crime rates vary from year to year." },{ key: "E", text: "Some towns have very large libraries." }],
    answer: "B", solution: "If wealth independently causes both more libraries and less crime, the library–crime link is explained by a third factor, undermining the causal conclusion." },
  { id: "tsa-mk1-09", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "The airline argues that its new booking system is better because complaints about booking have fallen by half since it was introduced.\n\nWhich of the following, if true, would most weaken this argument?",
    options: [{ key: "A", text: "The airline received an award for customer service." },{ key: "B", text: "Over the same period, the airline made it much harder for customers to submit complaints." },{ key: "C", text: "The new system was expensive to install." },{ key: "D", text: "Some passengers still prefer to book by phone." },{ key: "E", text: "The number of flights increased slightly." }],
    answer: "B", solution: "If complaints fell because they became harder to submit, the drop no longer shows the system is better—removing the support for the conclusion." },
  { id: "tsa-mk1-10", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "A school introduced a free breakfast programme and, over the following year, attendance improved. The head teacher claims the breakfast caused the improvement.\n\nWhich of the following, if true, would most strengthen the head teacher's claim?",
    options: [{ key: "A", text: "The breakfasts were popular with students." },{ key: "B", text: "Comparable schools without the programme saw no change in attendance over the same year." },{ key: "C", text: "The programme was funded by donations." },{ key: "D", text: "Attendance is recorded each morning." },{ key: "E", text: "Some students already ate breakfast at home." }],
    answer: "B", solution: "A comparison group that saw no change isolates the programme as the likely cause, strengthening the causal claim." },
  { id: "tsa-mk1-11", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "Principle: A person should not be blamed for an outcome they could not reasonably have foreseen or prevented.\n\nApplying this principle, in which case should the person NOT be blamed?",
    options: [{ key: "A", text: "A driver obeying all rules brakes immediately when a child suddenly darts into the road, but cannot avoid a collision." },{ key: "B", text: "A driver who was texting causes a crash." },{ key: "C", text: "A shopkeeper knowingly sells food past its safe date and customers fall ill." },{ key: "D", text: "A cyclist rides through a red light and hits a pedestrian." },{ key: "E", text: "A builder uses materials he knows to be unsafe and a wall collapses." }],
    answer: "A", solution: "Only A involves an outcome the person could neither foresee nor prevent; by the principle they should not be blamed. In the others the person could have foreseen or prevented the harm." },
  { id: "tsa-mk1-12", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "If the bridge were unsafe, it would have been closed. It has not been closed. So the bridge is not unsafe.\n\nWhich of the following arguments has the same logical structure as the argument above?",
    options: [{ key: "A", text: "If it rains, the match is cancelled. The match was not cancelled. So it did not rain." },{ key: "B", text: "If it rains, the match is cancelled. It rained. So the match was cancelled." },{ key: "C", text: "The match is cancelled only when it rains. It did not rain. So the match went ahead." },{ key: "D", text: "If it rains, the match is cancelled. The match was cancelled. So it rained." },{ key: "E", text: "It never rains during matches, so matches are never cancelled." }],
    answer: "A", solution: "The original is: if P then Q; not Q; therefore not P (valid, modus tollens). A matches exactly: if rain then cancelled; not cancelled; so no rain." },
  { id: "tsa-mk1-13", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A cyclist rides to a town at $30$ km/h and returns along the same road at $60$ km/h. What is the average speed for the whole journey?",
    options: [{ key: "A", text: "$40$ km/h" },{ key: "B", text: "$60$ km/h" },{ key: "C", text: "$30$ km/h" },{ key: "D", text: "$20$ km/h" },{ key: "E", text: "$45$ km/h" }],
    answer: "A", solution: "Average speed $=\\dfrac{2v_1v_2}{v_1+v_2}=\\dfrac{2\\cdot30\\cdot60}{90}=40$ km/h (not the arithmetic mean)." },
  { id: "tsa-mk1-14", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A cyclist rides to a town at $40$ km/h and returns along the same road at $60$ km/h. What is the average speed for the whole journey?",
    options: [{ key: "A", text: "$60$ km/h" },{ key: "B", text: "$50$ km/h" },{ key: "C", text: "$40$ km/h" },{ key: "D", text: "$48$ km/h" },{ key: "E", text: "$24$ km/h" }],
    answer: "D", solution: "Average speed $=\\dfrac{2v_1v_2}{v_1+v_2}=\\dfrac{2\\cdot40\\cdot60}{100}=48$ km/h (not the arithmetic mean)." },
  { id: "tsa-mk1-15", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A cyclist rides to a town at $20$ km/h and returns along the same road at $30$ km/h. What is the average speed for the whole journey?",
    options: [{ key: "A", text: "$12$ km/h" },{ key: "B", text: "$20$ km/h" },{ key: "C", text: "$24$ km/h" },{ key: "D", text: "$25$ km/h" },{ key: "E", text: "$30$ km/h" }],
    answer: "C", solution: "Average speed $=\\dfrac{2v_1v_2}{v_1+v_2}=\\dfrac{2\\cdot20\\cdot30}{50}=24$ km/h (not the arithmetic mean)." },
  { id: "tsa-mk1-16", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A cyclist rides to a town at $50$ km/h and returns along the same road at $75$ km/h. What is the average speed for the whole journey?",
    options: [{ key: "A", text: "$60$ km/h" },{ key: "B", text: "$\\frac{125}{2}$ km/h" },{ key: "C", text: "$75$ km/h" },{ key: "D", text: "$30$ km/h" },{ key: "E", text: "$50$ km/h" }],
    answer: "A", solution: "Average speed $=\\dfrac{2v_1v_2}{v_1+v_2}=\\dfrac{2\\cdot50\\cdot75}{125}=60$ km/h (not the arithmetic mean)." },
  { id: "tsa-mk1-17", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A cyclist rides to a town at $10$ km/h and returns along the same road at $15$ km/h. What is the average speed for the whole journey?",
    options: [{ key: "A", text: "$6$ km/h" },{ key: "B", text: "$10$ km/h" },{ key: "C", text: "$15$ km/h" },{ key: "D", text: "$12$ km/h" },{ key: "E", text: "$\\frac{25}{2}$ km/h" }],
    answer: "D", solution: "Average speed $=\\dfrac{2v_1v_2}{v_1+v_2}=\\dfrac{2\\cdot10\\cdot15}{25}=12$ km/h (not the arithmetic mean)." },
  { id: "tsa-mk1-18", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A coat priced at £$200$ is reduced by $10\\%$, and the reduced price is then cut by a further $20\\%$ in a sale. What is the final price?",
    options: [{ key: "A", text: "$180$" },{ key: "B", text: "$140$" },{ key: "C", text: "$160$" },{ key: "D", text: "$144$" },{ key: "E", text: "$149$" }],
    answer: "D", solution: "Successive discounts multiply: £$200\\times\\frac{9}{10}\\times\\frac{4}{5}=£144$ (a $10\\%$ then $20\\%$ cut is not a $30\\%$ cut)." },
  { id: "tsa-mk1-19", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A coat priced at £$50$ is reduced by $25\\%$, and the reduced price is then cut by a further $10\\%$ in a sale. What is the final price?",
    options: [{ key: "A", text: "$\\frac{155}{4}$" },{ key: "B", text: "$\\frac{65}{2}$" },{ key: "C", text: "$45$" },{ key: "D", text: "$\\frac{135}{4}$" },{ key: "E", text: "$\\frac{75}{2}$" }],
    answer: "D", solution: "Successive discounts multiply: £$50\\times\\frac{3}{4}\\times\\frac{9}{10}=£\\frac{135}{4}$ (a $25\\%$ then $10\\%$ cut is not a $35\\%$ cut)." },
  { id: "tsa-mk1-20", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A coat priced at £$120$ is reduced by $50\\%$, and the reduced price is then cut by a further $25\\%$ in a sale. What is the final price?",
    options: [{ key: "A", text: "$50$" },{ key: "B", text: "$45$" },{ key: "C", text: "$30$" },{ key: "D", text: "$90$" },{ key: "E", text: "$60$" }],
    answer: "B", solution: "Successive discounts multiply: £$120\\times\\frac{1}{2}\\times\\frac{3}{4}=£45$ (a $50\\%$ then $25\\%$ cut is not a $75\\%$ cut)." },
  { id: "tsa-mk1-21", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A coat priced at £$80$ is reduced by $20\\%$, and the reduced price is then cut by a further $15\\%$ in a sale. What is the final price?",
    options: [{ key: "A", text: "$68$" },{ key: "B", text: "$52$" },{ key: "C", text: "$\\frac{297}{5}$" },{ key: "D", text: "$64$" },{ key: "E", text: "$\\frac{272}{5}$" }],
    answer: "E", solution: "Successive discounts multiply: £$80\\times\\frac{4}{5}\\times\\frac{17}{20}=£\\frac{272}{5}$ (a $20\\%$ then $15\\%$ cut is not a $35\\%$ cut)." },
  { id: "tsa-mk1-22", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A coat priced at £$300$ is reduced by $30\\%$, and the reduced price is then cut by a further $10\\%$ in a sale. What is the final price?",
    options: [{ key: "A", text: "$210$" },{ key: "B", text: "$180$" },{ key: "C", text: "$194$" },{ key: "D", text: "$189$" },{ key: "E", text: "$270$" }],
    answer: "D", solution: "Successive discounts multiply: £$300\\times\\frac{7}{10}\\times\\frac{9}{10}=£189$ (a $30\\%$ then $10\\%$ cut is not a $40\\%$ cut)." },
  { id: "tsa-mk1-23", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "One tap fills a tank in $4$ hours and another fills it in $6$ hours. How long do they take to fill it together?",
    options: [{ key: "A", text: "$5$ 小时" },{ key: "B", text: "$\\frac{12}{5}$ 小时" },{ key: "C", text: "$12$ 小时" },{ key: "D", text: "$\\frac{17}{5}$ 小时" },{ key: "E", text: "$4$ 小时" }],
    answer: "B", solution: "Combined rate $=\\tfrac1{4}+\\tfrac1{6}$ tanks/hour; time $=\\dfrac1{1/4+1/6}=\\frac{12}{5}$ hours." },
  { id: "tsa-mk1-24", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "One tap fills a tank in $2$ hours and another fills it in $3$ hours. How long do they take to fill it together?",
    options: [{ key: "A", text: "$2$ 小时" },{ key: "B", text: "$\\frac{6}{5}$ 小时" },{ key: "C", text: "$3$ 小时" },{ key: "D", text: "$\\frac{11}{5}$ 小时" },{ key: "E", text: "$\\frac{5}{2}$ 小时" }],
    answer: "B", solution: "Combined rate $=\\tfrac1{2}+\\tfrac1{3}$ tanks/hour; time $=\\dfrac1{1/2+1/3}=\\frac{6}{5}$ hours." }
];
