// TSA 模拟卷4 —— Section 1（批判性思维 + 问题解决），id 前缀 tsa-mk4-*。
import type { MCQQuestion } from "@/lib/tests/questions/types";

export const TSA_MK4_MCQ: MCQQuestion[] = [
  { id: "tsa-mk4-01", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "A company claims its staff are happier since it introduced an open-plan office, citing that fewer employees have complained to managers.\n\nWhich of the following, if true, would most weaken this claim?",
    options: [{ key: "A", text: "Employees now sit closer to their managers and are more reluctant to complain." },{ key: "B", text: "The office is brightly lit." },{ key: "C", text: "The company is profitable." },{ key: "D", text: "Some staff prefer working from home." },{ key: "E", text: "The change was expensive." }],
    answer: "A", solution: "If proximity to managers deters complaints, fewer complaints need not mean greater happiness—removing the support." },
  { id: "tsa-mk4-02", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "A study reports that people who drink red wine live longer, and concludes that red wine promotes longevity.\n\nWhich of the following, if true, would most weaken the conclusion?",
    options: [{ key: "A", text: "Red wine is enjoyed worldwide." },{ key: "B", text: "Red-wine drinkers in the study were, on average, wealthier and had better healthcare." },{ key: "C", text: "Some people prefer white wine." },{ key: "D", text: "The study lasted several years." },{ key: "E", text: "Wine contains antioxidants." }],
    answer: "B", solution: "If wealth and healthcare explain both the wine-drinking and the longevity, the causal claim about wine is undermined." },
  { id: "tsa-mk4-03", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "A politician says her policies have worked because unemployment has fallen since she took office.\n\nWhich of the following, if true, would most weaken this claim?",
    options: [{ key: "A", text: "Unemployment fell at the same rate in neighbouring countries with very different policies." },{ key: "B", text: "The politician is popular." },{ key: "C", text: "Some people remain unemployed." },{ key: "D", text: "Unemployment is measured monthly." },{ key: "E", text: "She took office recently." }],
    answer: "A", solution: "If unemployment fell equally where different policies applied, her policies are not shown to be the cause." },
  { id: "tsa-mk4-04", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "A hospital introduced a new hand-washing protocol, and infection rates then fell. The staff claim the protocol caused the fall.\n\nWhich of the following, if true, would most strengthen this claim?",
    options: [{ key: "A", text: "Wards that did not adopt the protocol saw no change in infection rates over the same period." },{ key: "B", text: "The protocol was easy to follow." },{ key: "C", text: "The hospital is large." },{ key: "D", text: "Infection rates are recorded weekly." },{ key: "E", text: "Staff were trained in the protocol." }],
    answer: "A", solution: "A comparison group without the protocol and without change isolates the protocol as the likely cause." },
  { id: "tsa-mk4-05", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "A teacher believes that reading aloud daily improves pupils' vocabulary, because her class that read aloud scored highly on a vocabulary test.\n\nWhich of the following, if true, would most strengthen this belief?",
    options: [{ key: "A", text: "The pupils enjoyed reading aloud." },{ key: "B", text: "A similar class that did not read aloud scored much lower on the same test." },{ key: "C", text: "The test was taken in the morning." },{ key: "D", text: "The class was small." },{ key: "E", text: "Vocabulary is important." }],
    answer: "B", solution: "A comparable class without the practice scoring lower supports the claim that reading aloud, not some other factor, raised scores." },
  { id: "tsa-mk4-06", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "Principle: People should bear the costs of risks they choose to take, provided those risks fall only on themselves.\n\nWhich judgement best conforms to this principle?",
    options: [{ key: "A", text: "A solo sailor who ignores a storm warning and needs rescue should pay the cost of the rescue." },{ key: "B", text: "A pedestrian hit by a speeding driver should pay for their own treatment." },{ key: "C", text: "A child injured by a faulty toy should bear the cost." },{ key: "D", text: "A worker harmed by unsafe machinery should pay for repairs." },{ key: "E", text: "A passenger in a crash caused by the driver should pay the damages." }],
    answer: "A", solution: "Only A involves a freely chosen risk falling on the risk-taker; the principle then says they should bear its cost." },
  { id: "tsa-mk4-07", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "Principle: A rule is fair only if it can be applied consistently to everyone, including those who make it.\n\nWhich of the following best conforms to this principle?",
    options: [{ key: "A", text: "A committee sets a rule that all members, themselves included, must declare any conflict of interest." },{ key: "B", text: "A manager exempts himself from the dress code he imposes on staff." },{ key: "C", text: "Lawmakers pass a tax from which they alone are exempt." },{ key: "D", text: "A teacher bans phones but uses hers freely in class." },{ key: "E", text: "A club's founders are excused from the fees others must pay." }],
    answer: "A", solution: "Only A applies the rule to its makers as well; the others exempt the rule-makers, violating the principle." },
  { id: "tsa-mk4-08", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "All the cakes that sold out were chocolate. This cake is chocolate, so it will sell out.\n\nWhich of the following arguments is flawed in the same way?",
    options: [{ key: "A", text: "All the students who passed revised. Sam revised, so Sam will pass." },{ key: "B", text: "All who passed revised. Sam passed, so Sam revised." },{ key: "C", text: "No one who revised failed. Sam failed, so Sam did not revise." },{ key: "D", text: "Everyone who revised passed. Sam did not revise, so Sam failed." },{ key: "E", text: "Sam passed and revised, so revising guarantees passing." }],
    answer: "A", solution: "The original wrongly infers 'chocolate ⇒ sells out' from 'sold out ⇒ chocolate'. A repeats this: from 'passed ⇒ revised' it wrongly infers 'revised ⇒ pass'." },
  { id: "tsa-mk4-09", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "If the alarm had been set, it would have rung. It did ring. So the alarm had been set.\n\nWhich of the following has the same (flawed) structure?",
    options: [{ key: "A", text: "If it snowed, school would close. School closed. So it snowed." },{ key: "B", text: "If it snowed, school would close. It snowed. So school closed." },{ key: "C", text: "If it snowed, school would close. School did not close. So it did not snow." },{ key: "D", text: "School closes only when it snows. It did not snow. So school did not close." },{ key: "E", text: "It snowed, so school will close." }],
    answer: "A", solution: "The original affirms the consequent (if P then Q; Q; so P)—invalid. A has the same invalid form." },
  { id: "tsa-mk4-10", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "Since introducing background music, the café reports that customers stay longer. The owner concludes the music makes customers want to stay.\n\nWhich assumption does this conclusion depend on?",
    options: [{ key: "A", text: "The longer stays are due to the music rather than to some other change made at the same time." },{ key: "B", text: "Customers like music." },{ key: "C", text: "The café is busy." },{ key: "D", text: "Music is cheap to play." },{ key: "E", text: "Staff enjoy the music." }],
    answer: "A", solution: "Concluding the music caused longer stays assumes nothing else (new seating, menu, weather) explains the change." },
  { id: "tsa-mk4-11", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "A report notes that neighbourhoods with more CCTV cameras record more reported crime, and concludes that CCTV increases crime.\n\nWhich of the following best describes the flaw?",
    options: [{ key: "A", text: "More cameras may lead to more crimes being detected and reported, not more crimes occurring." },{ key: "B", text: "CCTV is expensive." },{ key: "C", text: "The report attacks residents." },{ key: "D", text: "It presents only two options." },{ key: "E", text: "The sample is too small." }],
    answer: "A", solution: "Higher reported crime may reflect better detection by cameras, not a real increase—so the causal conclusion is unwarranted." },
  { id: "tsa-mk4-12", type: "mcq", testId: "tsa", topicId: "tsa-critical", difficulty: 2, marks: 1,
    question: "A shopkeeper argues that since his most expensive coffee is his best seller, customers must prefer more expensive coffee.\n\nWhich of the following, if true, would most weaken this argument?",
    options: [{ key: "A", text: "The expensive coffee is the only large-sized option, which is why most people buy it." },{ key: "B", text: "The shop sells several coffees." },{ key: "C", text: "Coffee is popular." },{ key: "D", text: "The shop is busy in the morning." },{ key: "E", text: "Some customers buy tea." }],
    answer: "A", solution: "If it sells because it is the only large size, its popularity is not evidence that customers prefer higher prices." },
  { id: "tsa-mk4-13", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "One bus leaves every $20$ minutes and another every $30$ minutes; both leave together now. After how many minutes will they next leave together?",
    options: [{ key: "A", text: "$60$ 分钟" },{ key: "B", text: "$50$ 分钟" },{ key: "C", text: "$600$ 分钟" },{ key: "D", text: "$80$ 分钟" },{ key: "E", text: "$10$ 分钟" }],
    answer: "A", solution: "They coincide at the lowest common multiple: $\\text{lcm}(20,30)=60$ minutes." },
  { id: "tsa-mk4-14", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A group of $10$ students averages $60$ marks and another group of $20$ students averages $90$. What is the overall average?",
    options: [{ key: "A", text: "$90$" },{ key: "B", text: "$80$" },{ key: "C", text: "$75$" },{ key: "D", text: "$82$" },{ key: "E", text: "$1200$" }],
    answer: "B", solution: "Overall $=\\dfrac{10\\cdot60+20\\cdot90}{30}=80$ (weighted, not simple, mean)." },
  { id: "tsa-mk4-15", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A group of $5$ students averages $70$ marks and another group of $15$ students averages $50$. What is the overall average?",
    options: [{ key: "A", text: "$60$" },{ key: "B", text: "$70$" },{ key: "C", text: "$57$" },{ key: "D", text: "$55$" },{ key: "E", text: "$550$" }],
    answer: "D", solution: "Overall $=\\dfrac{5\\cdot70+15\\cdot50}{20}=55$ (weighted, not simple, mean)." },
  { id: "tsa-mk4-16", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A group of $8$ students averages $80$ marks and another group of $12$ students averages $55$. What is the overall average?",
    options: [{ key: "A", text: "$\\frac{135}{2}$" },{ key: "B", text: "$650$" },{ key: "C", text: "$80$" },{ key: "D", text: "$67$" },{ key: "E", text: "$65$" }],
    answer: "E", solution: "Overall $=\\dfrac{8\\cdot80+12\\cdot55}{20}=65$ (weighted, not simple, mean)." },
  { id: "tsa-mk4-17", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A group of $20$ students averages $40$ marks and another group of $30$ students averages $65$. What is the overall average?",
    options: [{ key: "A", text: "$57$" },{ key: "B", text: "$55$" },{ key: "C", text: "$65$" },{ key: "D", text: "$1375$" },{ key: "E", text: "$\\frac{105}{2}$" }],
    answer: "B", solution: "Overall $=\\dfrac{20\\cdot40+30\\cdot65}{50}=55$ (weighted, not simple, mean)." },
  { id: "tsa-mk4-18", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A right-angled triangle has the two shorter sides $3$ and $4$. What is the length of the hypotenuse?",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$6$" },{ key: "C", text: "$4$" },{ key: "D", text: "$7$" },{ key: "E", text: "$2$" }],
    answer: "A", solution: "Hypotenuse $=\\sqrt{3^2+4^2}=\\sqrt{25}=5.$" },
  { id: "tsa-mk4-19", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A right-angled triangle has the two shorter sides $6$ and $8$. What is the length of the hypotenuse?",
    options: [{ key: "A", text: "$14$" },{ key: "B", text: "$10$" },{ key: "C", text: "$5$" },{ key: "D", text: "$9$" },{ key: "E", text: "$11$" }],
    answer: "B", solution: "Hypotenuse $=\\sqrt{6^2+8^2}=\\sqrt{100}=10.$" },
  { id: "tsa-mk4-20", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A right-angled triangle has the two shorter sides $5$ and $12$. What is the length of the hypotenuse?",
    options: [{ key: "A", text: "$14$" },{ key: "B", text: "$17$" },{ key: "C", text: "$12$" },{ key: "D", text: "$10$" },{ key: "E", text: "$13$" }],
    answer: "E", solution: "Hypotenuse $=\\sqrt{5^2+12^2}=\\sqrt{169}=13.$" },
  { id: "tsa-mk4-21", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A right-angled triangle has the two shorter sides $8$ and $15$. What is the length of the hypotenuse?",
    options: [{ key: "A", text: "$18$" },{ key: "B", text: "$16$" },{ key: "C", text: "$12$" },{ key: "D", text: "$17$" },{ key: "E", text: "$23$" }],
    answer: "D", solution: "Hypotenuse $=\\sqrt{8^2+15^2}=\\sqrt{289}=17.$" },
  { id: "tsa-mk4-22", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A right-angled triangle has the two shorter sides $9$ and $12$. What is the length of the hypotenuse?",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$21$" },{ key: "C", text: "$16$" },{ key: "D", text: "$15$" },{ key: "E", text: "$14$" }],
    answer: "D", solution: "Hypotenuse $=\\sqrt{9^2+12^2}=\\sqrt{225}=15.$" },
  { id: "tsa-mk4-23", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A triangle has base $10$ and perpendicular height $6$. What is its area?",
    options: [{ key: "A", text: "$60$" },{ key: "B", text: "$16$" },{ key: "C", text: "$20$" },{ key: "D", text: "$32$" },{ key: "E", text: "$30$" }],
    answer: "E", solution: "Area $=\\tfrac12\\cdot10\\cdot6=30.$" },
  { id: "tsa-mk4-24", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A triangle has base $8$ and perpendicular height $5$. What is its area?",
    options: [{ key: "A", text: "$\\frac{40}{3}$" },{ key: "B", text: "$22$" },{ key: "C", text: "$40$" },{ key: "D", text: "$20$" },{ key: "E", text: "$13$" }],
    answer: "D", solution: "Area $=\\tfrac12\\cdot8\\cdot5=20.$" },
];
