// LNAT 知识讲解卡 —— 批判性阅读、论证分析、议论文写作。原创内容，按官方结构校准。
import type { TopicKnowledge } from "./esat";

export const LNAT_KNOWLEDGE: TopicKnowledge[] = [
  {
    topicId: "lnat-read",
    overview: "批判性阅读与推断是 LNAT 第一节（Section A）的核心。文章多为社会、伦理、法律、政治类的论述文，题目考查你能否准确把握主旨、区分论点与论据、进行必要（而非过度）的推断、理解词句在语境中的含义、判断作者语气与立场。关键心态：只依据文章本身作答，不带入外部常识或个人观点。",
    concepts: [
      { name: "抓主旨与结论（Main point / conclusion）", body: "论述文通常围绕一个**主要结论**展开，其余句子是支撑它的论据。找结论的技巧：\n\n- 问自己「作者最想让我接受哪句话？」\n- 结论常出现在开头或结尾，前有 'therefore'、'so'、'thus'，或在铺陈之后的转折点。\n- 论据回答「为什么」，结论是被论据支撑的那句。", keyPoints: ["主旨题选「作者立场」，不选某个论据或细节", "警惕过强选项（含 always / only / never 而文章没这么说）", "改述正确的选项往往用不同词表达同一意思"] },
      { name: "合理推断（Inference / deduction）", body: "推断题问「根据文章**必然**能得出什么」。正确答案必须由文中信息支持，且不超出文章范围。\n\n- 正确推断 = 文章明说或逻辑上必然蕴含。\n- 错误选项：文章没提（外部知识）、过度延伸、把「可能」说成「必然」。", keyPoints: ["能从原文找到直接依据的才选", "「可能为真」不等于「可推断」", "别用自己的常识补全文章没说的内容"] },
      { name: "语境中的词义（Meaning in context）", body: "考查某个词或短语在**该句语境**下的含义，而非字典义。方法：把选项代回原句，看哪个最贴合作者意图与上下文语气。比喻性表达（如 'a shield'、'a mask'、'a shout carries further than an argument'）要理解其**引申义**。", keyPoints: ["先看该词前后句锁定语境", "比喻要取引申义，不取字面", "选与作者整体立场一致的解释"] },
      { name: "语气与立场（Tone / attitude）", body: "判断作者对某话题的态度：赞同、保留性怀疑、批判、中立存疑等。线索词：'yet'、'but'、'however'（转折，常引出作者真实态度）；'there is something to this...but'（先让步后质疑 = 保留性怀疑）。", keyPoints: ["让步 + 转折 常表示「有条件的怀疑」", "作者立场未必等于文中任一方，可能是「悬置判断」", "注意反讽与保留语气"] },
    ],
    workedExamples: [
      { title: "区分结论与论据", question: "文章：「充电便利、续航提升、价格下降——因此电动车终将取代燃油车。」哪句是结论？", solution: "前三项是论据（回答「为什么」），由破折号后的 'therefore' 引出的「电动车终将取代燃油车」才是结论。主旨/结论题应选它，而非任一论据。", tip: "找 'therefore/so/thus' 后面那句，通常就是结论。" },
      { title: "避免过度推断", question: "文章说「大多数事故发生在雨天」。可否推断「雨天开车一定出事」？", solution: "不可。「大多数事故在雨天」不等于「雨天必然出事」，也未给出雨天与晴天的行驶量对比。把统计相关说成必然结果属过度推断。", tip: "含「一定 / 必然 / 所有」的选项要格外警惕。" },
    ],
  },
  {
    topicId: "lnat-analyse",
    overview: "论证分析考查你评估论证强弱的能力：识别前提与假设、判断什么会削弱或加强结论、指出推理漏洞。这是 LNAT 与法律思维最贴近的部分——律师的核心工作正是拆解论证。",
    concepts: [
      { name: "前提、结论与假设", body: "**前提**是给出的理由，**结论**是被支撑的主张，**假设**是论证成立所必需但**未明说**的前提。\n\n找假设的方法：问「要让前提真正支撑结论，中间还必须默认什么？」若否定某选项会使论证崩塌，它就是关键假设。", keyPoints: ["假设是「隐含且必需」的桥梁", "否定假设 → 论证垮掉（否定测试法）", "别选文章已明说的内容——那是前提不是假设"] },
      { name: "削弱与加强（Weaken / Strengthen）", body: "**削弱**：找一个若为真、会动摇结论或斩断前提到结论之桥的选项。**加强**：反之，补上缺失环节或提供支持证据。\n\n最强的削弱往往直接攻击核心假设或提供反向因果/反例；无关、细枝末节的选项不算。", keyPoints: ["削弱/加强针对的是「结论」，不是随便某句", "实验对照（改变一个变量看结果）是有力的因果证据", "「有些人不喜欢」这类主观、边缘信息通常无关"] },
      { name: "常见推理谬误", body: "- **相关≠因果**：两事同现不代表一个导致另一个（可能反向，或有第三因素）。\n- **滑坡**：假定允许一例就必然滑向一连串极端后果。\n- **非此即彼（假两难）**：把连续/多元选项化约为只有两个极端。\n- **人身攻击（ad hominem）**：攻击提出者而非论点本身。\n- **循环论证**：用结论本身当理由。\n- **以偏概全**：由少数样本推及全体。", keyPoints: ["看到「A 和 B 同时出现，所以 A 导致 B」→ 想相关vs因果", "「一旦……就必然一路……」→ 滑坡", "把「某些城市有效」推成「所有城市都该做」→ 以偏概全"] },
      { name: "论证结构", body: "快速给文章「画骨架」：哪句是主张、哪些是理由、哪里是让步、哪里是反驳。常见结构：\n\n- 主张 + 理由，随后**反证**（'But / Yet' 引出）。\n- 让步（'There is something to this'）+ 转折质疑。\n- 定义 + 举例。\n\n看清结构，题目往往迎刃而解。", keyPoints: ["'But / Yet / However' 是结构的分水岭", "让步不等于同意——常是为反驳作铺垫", "先标出结论，再看每句相对它的作用"] },
    ],
    workedExamples: [
      { title: "用否定测试找假设", question: "论证：「免费夜校会减少犯罪，因为学习者无暇犯罪。」隐含假设是什么？", solution: "假设是「夜校能触及并占据那些原本会犯罪的人」。否定它（夜校吸引不到这些人、也不覆盖犯罪高发时段），论证立刻崩塌——正是批评者的攻击点。", tip: "能让论证「垮掉」的隐含前提，就是关键假设。" },
      { title: "识别相关vs因果", question: "「用社交媒体最多的青少年焦虑也最多，所以社交媒体导致焦虑。」漏洞在哪？", solution: "把相关当成了特定方向的因果。也可能是焦虑者更爱用社媒（反向），或睡眠紊乱等第三因素同时导致两者。要确立因果需对照实验（如减少使用后焦虑是否下降）。", tip: "最强的因果证据来自「改变一个变量、看结果」的对照。" },
    ],
  },
  {
    topicId: "lnat-essay",
    overview: "第二节（Section B）要求 40 分钟内从 3 个话题中选 1 写一篇议论文。不考法律知识，考的是**论证是否清晰、结构是否严谨、立场是否有据**。阅卷看重：明确的论点、有逻辑的展开、对反方的回应、以及得体的英文。",
    concepts: [
      { name: "结构：立论—展开—反驳—结论", body: "经典四段式：\n\n1. **引言 + 论点（thesis）**：直接亮出你的立场，别绕圈。\n2. **主体段（2–3 段）**：每段一个论点，理由 + 例证。\n3. **反方与回应**：主动提出最强的反对意见并加以回应——这是拿高分的关键，显示思维成熟。\n4. **结论**：重申立场，收束升华，不引入新论点。", keyPoints: ["开头就表明立场，避免模棱两可", "一段一个中心论点", "主动驳斥反方 = 展示批判性思维"] },
      { name: "如何把论点讲得有力", body: "- 用**具体理由**支撑，而非口号。\n- 例证可来自历史、时事、法律、伦理常识（不需专业法律知识）。\n- 承认复杂性：好的议论文会区分情形（'in cases where...'），而非一刀切。\n- 保持**分析**而非叙述——不断回答「所以呢？这如何支持我的论点？」。", keyPoints: ["理由要具体，避免空泛断言", "区分情形比绝对化更有说服力", "始终扣回你的核心论点"] },
      { name: "语言与时间管理", body: "40 分钟建议：5 分钟审题列提纲，30 分钟写作，5 分钟检查。语言求**清晰准确**胜过华丽：句子结构清楚、逻辑连接词恰当（'however'、'consequently'、'nevertheless'）、避免语法错误。篇幅约 500–600 词。", keyPoints: ["先列提纲再动笔，避免中途散架", "清晰 > 辞藻；逻辑连接词标示论证走向", "留时间检查语法与拼写"] },
      { name: "常见失误与如何避免", body: "- **骑墙不表态**：通篇「有人认为……也有人认为……」却始终不给出自己的立场——这是阅卷最反感的。必须选边并论证。\\n- **只罗列不论证**：堆砌理由却不展开「为什么成立、如何支持论点」。每个理由都要讲透。\\n- **无视反方**：不提最强的反对意见，论证显得片面幼稚。\\n- **跑题**：回答的不是题目真正问的那个问题；审题时先圈出关键词与限定语。\\n- **例证空泛**：只说「历史证明……」却无具体例子。一个真实贴切的例子胜过十句口号。", keyPoints: ["先明确选边，再展开论证", "每个理由都回答「所以呢？这如何支持我的论点」", "主动写一段最强反方并加以回应"] },
    ],
    workedExamples: [
      { title: "提纲示范：Should voting be compulsory?", question: "先看一个「四段式提纲」怎么搭。", solution: "论点：应有条件地强制（强制到场，但允许投空白/弃权票）。主体一：提高参与度、增强代表制合法性（例：澳大利亚投票率长期 >90%）。主体二：促使政党面向全体选民而非仅动员核心票仓。反方与回应：反对者称强制侵犯自由——回应：允许弃权票即保留了「不选择」的自由，义务仅在于到场。结论：在保障弃权权的前提下，公共收益大于对自由的轻微限制。", tip: "提纲阶段就把「反方与回应」想好，写作时才不慌。" },
      { title: "整篇范文：Should voting be compulsory?", question: "约 450 词的完整范文，展示四段式如何落地。", solution: "Whether citizens should be legally required to vote is often framed as a clash between civic duty and individual liberty. In my view, a well-designed system of compulsory voting—one that requires attendance at the ballot but permits a blank or 'none of the above' vote—is justified, because it secures the benefits of near-universal participation while preserving genuine freedom of choice.\\n\\nThe first case for compulsion is the legitimacy of the outcome. When turnout is low and uneven, those who govern are chosen by an unrepresentative slice of the population, typically the older and wealthier. Compulsory attendance corrects this: in Australia, where voting is required, turnout consistently exceeds ninety per cent, so results reflect the whole electorate rather than the most motivated fraction. A government elected by almost everyone can claim an authority that one elected by a self-selected minority cannot.\\n\\nA second benefit concerns the behaviour of parties. When voting is optional, campaigns concentrate on energising a committed base and suppressing opponents. When everyone must turn out, that strategy loses its force; parties must instead appeal broadly, including to citizens they would otherwise ignore. Compulsory voting thus nudges politics toward the centre and toward the interests of the many.\\n\\nThe most serious objection is that forcing people to vote violates their freedom. If liberty includes the right to abstain, compulsion appears to override it. This objection has real weight, and any defensible scheme must answer it. The answer lies in a distinction: the law can require a citizen to attend and receive a ballot without requiring them to endorse any candidate. A permitted blank vote preserves the freedom that matters—the freedom not to support anyone—while removing only the option of silent non-participation. The burden imposed is minimal: a few minutes, once every few years.\\n\\nIt might be replied that even compelling attendance is an intrusion. But the state already compels many minor civic acts—jury service, census returns—where the collective benefit is large and the individual cost small. Voting fits this pattern. Provided the right to abstain on the ballot itself is protected, the modest imposition of turning up is a reasonable price for a more representative democracy.\\n\\nFor these reasons, compulsory voting is justified in the qualified form I have described. It strengthens the legitimacy of government and broadens political appeal, while the freedom it appears to threaten is safeguarded by the right to cast a blank vote. The duty it imposes is to participate, not to approve—and that is a duty a democracy may fairly ask of its citizens.", tip: "注意反方段：先给出最强反对（侵犯自由），再用「到场 vs 认可」的区分化解它。" },
      { title: "整篇范文：Is it ever justified to break an unjust law?", question: "约 430 词的完整范文，示范如何限定条件、避免绝对化。", solution: "The claim that we must always obey the law has an obvious appeal: if each person broke every rule they disliked, social order would dissolve. Yet stated so broadly, this principle would condemn figures we now honour—those who defied unjust laws to expose injustice. I will argue that breaking an unjust law can be justified, but only under strict conditions that distinguish principled disobedience from mere lawlessness.\\n\\nThe starting point is that obedience to law is normally obligatory, because law makes cooperation possible and no one is entitled to be the sole judge of which rules bind them. This is why disobedience requires justification rather than the reverse. But 'normally' is not 'always'. A law may be so unjust—entrenching cruelty or denying people basic standing—that complicity in it is itself a wrong. Where lawful means of change have been tried and have failed, disobedience may be the only avenue left.\\n\\nWhat separates the conscientious objector from the vandal is not the fact of breaking a law but the manner. Justified disobedience is, first, public: the objector acts openly, not in secret, precisely to draw attention to the injustice. Second, it is non-violent, or at least proportionate, so that it appeals to others' conscience rather than merely imposing the objector's will. Third, the objector accepts the legal penalty, thereby affirming respect for the rule of law in general even while breaking one law in particular. Finally, the aim is reform: the point is to change the law, not to escape its reach for personal gain.\\n\\nAgainst this it may be argued that permitting any disobedience invites chaos, since everyone believes their own cause just. This is a genuine risk, and it is why the conditions above matter. They are demanding: openness, the acceptance of punishment, and the exhaustion of lawful means all raise the cost of disobedience and filter out the merely self-interested. A person willing to be arrested to protest a law is not the same as one who quietly breaks a rule for convenience.\\n\\nIt should be conceded that reasonable people will disagree about which laws are unjust enough to warrant this response. But the existence of hard cases does not collapse the distinction between clear ones. That a boundary is sometimes blurred does not mean there is no boundary.\\n\\nI conclude that breaking an unjust law can be justified, but only as principled, open, non-violent disobedience that accepts the penalty and aims at reform. So confined, it is not a threat to the rule of law but, at its best, a way of holding the law to its own highest standards.", tip: "高分技巧：把「是否可以违法」重构为「在什么条件下可以」，用条件区分立场，避免非黑即白。" },
      { title: "扩充题库（按主题分类）", question: "更多可计时练习的 LNAT 风格题目。", solution: "【法律与正义】1) Is it ever justified to break an unjust law? 2) Should prisons aim at punishment or rehabilitation? 3) Should trial by jury be preserved? 4) 'Better that ten guilty go free than one innocent be convicted.' Discuss.\\n【自由与国家】5) Should the state restrict free speech to prevent offence? 6) Is privacy worth protecting at the cost of security? 7) Should voting be compulsory? 8) Is it right for the state to 'nudge' citizens toward healthier choices?\\n【伦理与社会】9) Do the wealthy have a duty to help the poor? 10) Is inherited wealth unfair? 11) Should we judge historical figures by today's moral standards? 12) Does concern for animals deserve the same weight as concern for humans?\\n【科学与技术】13) Do we place too much faith in scientific experts? 14) Should there be limits on what artificial intelligence is allowed to decide? 15) 'The internet has done more harm than good to public debate.' Discuss.\\n每题限时 40 分钟，强制自己写出一段最强反方并回应。", tip: "练习时优先选「你能想到最强正反理由」的题，而非你最认同的题。" },
    ],
  },
];
