import type { AdmissionsTest } from "./index";
import { CAIE9709_TEST } from "./caie9709-test";

export const ADDITIONAL_TESTS: AdmissionsTest[] = [
  CAIE9709_TEST,
  {
    id: "ielts",
    name: "International English Language Testing System Academic",
    abbr: "IELTS",
    nameZh: "雅思学术类",
    category: "english",
    purpose: "language",
    icon: "Aa",
    universities: ["UK and Hong Kong universities"],
    programs: ["全部需要英语语言证明的专业"],
    programsEn: ["Courses requiring proof of English proficiency"],
    duration: "2 小时 45 分钟（口语另约 11–14 分钟）",
    format: "Academic IELTS: Listening, Reading, Writing and Speaking",
    formatZh: "学术类 IELTS：听力、阅读、写作和口语四部分。本站提供阅读、写作与口语训练；听力使用官方带音频样题。",
    registrationUrl: "https://ielts.org/take-a-test",
    officialSampleUrl: "https://ielts.org/take-a-test/preparation-resources/sample-test-questions/academic-test",
    hasQuestionBank: true,
    overview: "英语要求不是附属材料，而是 Offer 条件和签证准备的一部分。中心将目标院校门槛、四项分差、写作评分和口语演练放在同一条备考路径中。",
    structureDetails: "Listening 约 30 分钟、40 题；Academic Reading 60 分钟、40 题；Writing 60 分钟，Task 1 至少 150 词、Task 2 至少 250 词且权重更高；Speaking 11–14 分钟，共三部分。",
    scoringNote: "四项分别报告 0–9 Band，并给出总分。院校通常同时规定总分和单项下限；具体要求以课程页面和最终 Offer 为准。",
    statusNote: "本站不是 IELTS 官方考点。目标分门槛会变化，申请前须复核课程官网与 Offer 条件。",
    topics: [
      { id: "ielts-listening", title: "听力", titleEn: "Listening", description: "定位、预测词性、拼写与数字信息；音频训练跳转官方样题。" },
      { id: "ielts-reading", title: "学术阅读", titleEn: "Academic Reading", description: "主旨、证据定位、推断、段落匹配与 True/False/Not Given。" },
      { id: "ielts-writing", title: "学术写作", titleEn: "Academic Writing", description: "Task 1 信息概括；Task 2 立场、论证、衔接与语言准确性。" },
      { id: "ielts-speaking", title: "口语", titleEn: "Speaking", description: "Part 1–3 的流利度、词汇、语法与发音；用 AI 进行追问式演练。" },
    ],
    studyPlan: [
      { week: "第 1 周", focus: "确认门槛与四项诊断", tasks: ["核对目标课程总分与单项要求", "完成阅读与写作诊断", "记录四项当前 Band 和最弱项"] },
      { week: "第 2–3 周", focus: "阅读与听力证据定位", tasks: ["阅读按题型限时训练", "使用 IELTS 官方音频样题", "建立拼写、同义替换和定位错题表"] },
      { week: "第 4–5 周", focus: "Task 1 / Task 2 写作", tasks: ["每周各写两篇 Task 1 和 Task 2", "按评分维度复盘而非只改语法", "把反复出现的问题改成检查清单"] },
      { week: "第 6 周", focus: "口语与整套节奏", tasks: ["完成三次 AI 口语模拟", "练习两分钟连续陈述", "按真实时间完成官方完整样题"] },
    ],
    tips: [
      "先看单项下限，再看总分；一个弱项足以让整体不满足 Offer。",
      "Writing Task 2 权重高于 Task 1，时间一般按约 40/20 分钟分配。",
      "阅读的依据必须来自文本；Not Given 不是“我觉得不对”。",
      "听力必须配官方音频训练，文字稿只能用于复盘。",
      "口语目标是清晰、自然地展开和修正，不是背诵模板。",
    ],
    pastPaperLinks: [
      { label: "IELTS Academic 官方样题", url: "https://ielts.org/take-a-test/preparation-resources/sample-test-questions/academic-test", note: "含听力音频与四部分样题" },
    ],
  },
  {
    id: "csat",
    name: "Computer Science Admissions Test",
    abbr: "CSAT",
    nameZh: "剑桥计算机科学学院评估",
    category: "mathematics",
    purpose: "college-assessment",
    icon: "{ }",
    universities: ["University of Cambridge — Peterhouse and Trinity College"],
    programs: ["计算机科学"],
    programsEn: ["Computer Science"],
    duration: "训练卷 3 小时；以当年学院通知为准",
    format: "College assessment with written mathematical and computational problem solving",
    formatZh: "学院附加书面评估，侧重数学、逻辑、算法和计算思维的完整推导。本站按已公开的 2025 训练格式制作小型模块。",
    registrationUrl: "https://www.undergraduate.study.cam.ac.uk/apply/after/college-assessments",
    officialSampleUrl: "https://openclimb.io/csat/",
    hasQuestionBank: true,
    overview: "CSAT 不是所有剑桥计算机申请者统一参加的预注册考试。Peterhouse 和 Trinity 的相关申请者可能在 TMUA 之外收到学院评估安排，最终形式以学院邮件为准。",
    structureDetails: "本站训练卷参照公开的 2025 说明：从多道书面问题中选做，重视推理与过程，较小计算错误仍可能获得步骤分。训练卷采用 8 题选 6 题计分。",
    scoringNote: "学院会综合 TMUA、CSAT、面试与申请材料。本站采用形成性过程评分，不换算为剑桥官方分数。",
    statusNote: "仅 Peterhouse / Trinity 等学院的指定申请者可能参加；训练结构参照已公开 2025 格式，当前申请周期必须以学院通知为准。",
    topics: [
      { id: "csat-algorithms", title: "算法与复杂度", titleEn: "Algorithms & Complexity", description: "递归、搜索、贪心、正确性和增长率。" },
      { id: "csat-logic", title: "逻辑与证明", titleEn: "Logic & Proof", description: "命题、反例、归纳、不变量与严谨论证。" },
      { id: "csat-combinatorics", title: "组合计数", titleEn: "Combinatorics", description: "计数、鸽巢原理、递推和概率化思考。" },
      { id: "csat-graphs", title: "图与网络", titleEn: "Graphs & Networks", description: "路径、树、着色、连通性和网络算法。" },
      { id: "csat-modelling", title: "建模与离散结构", titleEn: "Modelling & Discrete Structures", description: "把陌生情境形式化，选择表示并检验边界情况。" },
    ],
    studyPlan: [
      { week: "第 1 周", focus: "书面表达诊断", tasks: ["完成 3 道不同主题长题", "区分答案错误与论证缺口", "建立定义—观察—证明书写模板"] },
      { week: "第 2–3 周", focus: "算法与组合", tasks: ["练递归和不变量", "每题写正确性理由", "比较暴力方法和更优方法"] },
      { week: "第 4 周", focus: "图论与建模", tasks: ["练树、路径和着色", "对模型写清假设", "主动检查极端与小规模案例"] },
      { week: "第 5 周", focus: "选题型整卷", tasks: ["完成两套固定书面卷", "先浏览再选最有把握的六题", "按评分反馈重写两道失分题"] },
    ],
    tips: [
      "先用小例子找规律，再明确写出猜想和证明。",
      "算法题必须解释为什么终止、为什么正确，而不只写步骤。",
      "不会做完也要保留有效观察和部分推导，过程可能获得分数。",
      "当前是否参加、日期和提交方式完全以学院通知为准。",
    ],
  },
];
