import type { AdmissionsTest } from "./index";

export const CAIE9709_TEST: AdmissionsTest = {
  id: "caie9709",
  name: "Cambridge International AS & A Level Mathematics (9709)",
  abbr: "CAIE 9709",
  nameZh: "剑桥国际 A-Level 数学",
  category: "mathematics",
  purpose: "curriculum",
  icon: "f(x)",
  universities: ["Cambridge International A-Level centres", "UK and Hong Kong universities"],
  programs: ["A-Level 数学课程考试", "大学 Offer 条件准备"],
  programsEn: ["A-Level Mathematics", "University offer preparation"],
  duration: "P3：1 小时 50 分钟，75 分",
  format: "Pure Mathematics 3: 9–11 structured questions, 75 marks",
  formatZh: "首发 Pure Mathematics 3：110 分钟、75 分、9–11 道结构题；当前 16 套原创固定卷均为 11 题。",
  registrationUrl: "https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-international-as-and-a-level-mathematics-9709/",
  officialSampleUrl: "https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-international-as-and-a-level-mathematics-9709/past-papers/",
  hasQuestionBank: true,
  overview: "面向 CAIE 9709 学生的课程考试训练。首期聚焦 Pure Mathematics 3，训练在熟悉知识点被陌生包装、条件隐藏或计算路径不直观时，仍能稳定识别方法并写出得分过程。",
  structureDetails: "完整 A-Level 路线按考生组合涉及 Pure Mathematics 1、Pure Mathematics 3，以及 Mechanics 或 Probability & Statistics。本站首期仅开放 P3，覆盖代数、对数与指数、三角函数、微分、积分、数值方法、向量、微分方程和复数；P1、P4、P5、P6 待对应内容完成后再开放。",
  scoringNote: "P3 总分 75 分，结构题按步骤给分。学生应展示必要推导；非精确数值通常按题目要求给出有效数字。本站 AI 评分用于训练反馈，最终成绩与评分标准以 Cambridge 官方材料为准。",
  statusNote: "参考用户提供的 2026 年 6 月中国区 9709/15、9709/35、9709/45 与 9709/55 答卷，优先补强 P3。8 套 R2 修订卷共 88 道题，44/88 针对已识别错题类型；基础卷与强化卷分开展示，不承诺与官方真卷等难。",
  topics: [
    { id: "caie9709-algebra", title: "代数", titleEn: "Algebra", description: "二项式展开、部分分式、因式与余式、参数条件。" },
    { id: "caie9709-log-exp", title: "对数与指数", titleEn: "Logarithms & Exponentials", description: "指数换元、对数方程、定义域与解的筛选。" },
    { id: "caie9709-trig", title: "三角函数", titleEn: "Trigonometry", description: "恒等变形、三角方程、象限与区间解。" },
    { id: "caie9709-differentiation", title: "微分", titleEn: "Differentiation", description: "隐函数、参数方程、切线与变化率。" },
    { id: "caie9709-integration", title: "积分", titleEn: "Integration", description: "换元、分部、恒等变形、定积分与精确值。" },
    { id: "caie9709-numerical", title: "数值方法", titleEn: "Numerical Methods", description: "夹根、迭代、收敛与精度表达。" },
    { id: "caie9709-vectors", title: "向量", titleEn: "Vectors", description: "直线、交点、垂距、夹角与多条件几何。" },
    { id: "caie9709-de", title: "微分方程", titleEn: "Differential Equations", description: "分离变量、初始条件、模型解释与极限。" },
    { id: "caie9709-complex", title: "复数", titleEn: "Complex Numbers", description: "模与辐角、轨迹、变换、根与几何解释。" },
  ],
  studyPlan: [
    { week: "第 1 周", focus: "真卷结构诊断", tasks: ["完成一套 P3 固定卷", "按方法识别、代数执行和条件检查分类失分", "建立个人易慌题型清单"] },
    { week: "第 2–3 周", focus: "微分与积分补弱", tasks: ["每日完成微分和积分各 2 题", "先写方法选择再开始计算", "把错题改写成一页步骤检查表"] },
    { week: "第 4 周", focus: "陌生包装专项", tasks: ["练参数、精确值和隐藏换元", "每题标出定义域、象限或舍根条件", "限时完成一套固定卷"] },
    { week: "第 5–6 周", focus: "四套卷校准", tasks: ["每周完成两套 110 分钟整卷", "逐题核对步骤分而非只看答案", "比较四套卷中后半程的稳定性"] },
  ],
  tips: [
    "先识别题目实际考查的方法，再进入计算；陌生叙述不等于超纲。",
    "指数换元、反三角函数、复数辐角和根式结果都要检查定义域、象限与应舍解。",
    "积分先观察导数配对、次数差和可拆结构，避免一开始就展开长算式。",
    "向量题把每个几何条件翻译成独立方程，再联立，别在脑中同时处理全部条件。",
    "整卷复盘记录错误发生在识别、执行、检查还是时间分配，才能区分知识弱点与临场波动。",
  ],
  pastPaperLinks: [
    { label: "Cambridge 9709 syllabus 2026–2027", url: "https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf", note: "官方考试结构、内容范围与计算器规则。" },
    { label: "Cambridge 9709 past papers", url: "https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-international-as-and-a-level-mathematics-9709/past-papers/", note: "官方样题、历年试卷与评分材料入口。" },
  ],
};
