// BMO/UKMT SMC 批B —— 概率/数列/不等式/函数图像。原创，逐题程序断言。
import type { MCQQuestion } from "./types";

export const BMO_SMC_B: MCQQuestion[] = [
  { id: "bmo-smc-b-001", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 1, marks: 4,
    question: "Two fair dice are rolled. Find the probability that the total is $7$.",
    options: [{ key: "A", text: "$\\dfrac16+\\dfrac1{36}$" },{ key: "B", text: "$\\dfrac7{36}$" },{ key: "C", text: "$\\dfrac1{12}$" },{ key: "D", text: "$\\dfrac15$" },{ key: "E", text: "$\\dfrac16$" }],
    answer: "E", solution: "和为 7 的组合 $(1,6)\\dots(6,1)$ 共 6 种，$6/36=1/6$——所有点数和中概率最大。" },
  { id: "bmo-smc-b-002", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "Two fair dice are rolled. Find the probability that at least one shows a six.",
    options: [{ key: "A", text: "$\\dfrac1{36}$" },{ key: "B", text: "$\\dfrac{11}{36}$" },{ key: "C", text: "$\\dfrac13$" },{ key: "D", text: "$\\dfrac{12}{36}$" },{ key: "E", text: "$\\dfrac16$" }],
    answer: "B", solution: "补集：都不是 6 的概率 $\\left(\\tfrac56\\right)^2=\\tfrac{25}{36}$，故 $1-\\tfrac{25}{36}=\\tfrac{11}{36}$。" },
  { id: "bmo-smc-b-003", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "Two cards are drawn without replacement from a standard $52$-card pack. Find the probability that both are aces.",
    options: [{ key: "A", text: "$\\dfrac{1}{2652}$" },{ key: "B", text: "$\\dfrac{4}{52}$" },{ key: "C", text: "$\\dfrac{1}{221}$" },{ key: "D", text: "$\\dfrac{1}{169}$" },{ key: "E", text: "$\\dfrac{2}{52}$" }],
    answer: "C", solution: "$\\dfrac4{52}\\times\\dfrac3{51}=\\dfrac{12}{2652}=\\dfrac1{221}$。" },
  { id: "bmo-smc-b-004", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "A fair coin is tossed $3$ times. Find the probability of exactly two heads.",
    options: [{ key: "A", text: "$\\dfrac12$" },{ key: "B", text: "$\\dfrac14$" },{ key: "C", text: "$\\dfrac23$" },{ key: "D", text: "$\\dfrac18$" },{ key: "E", text: "$\\dfrac38$" }],
    answer: "E", solution: "$\\binom32/2^3=3/8$。" },
  { id: "bmo-smc-b-005", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 1, marks: 4,
    question: "A bag contains $5$ red and $4$ blue balls. One ball is drawn at random. Find the probability it is red.",
    options: [{ key: "A", text: "$\\dfrac15$" },{ key: "B", text: "$\\dfrac59$" },{ key: "C", text: "$\\dfrac54$" },{ key: "D", text: "$\\dfrac49$" },{ key: "E", text: "$\\dfrac12$" }],
    answer: "B", solution: "$5/(5+4)=5/9$。" },
  { id: "bmo-smc-b-006", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "A fair die is rolled three times. Find the probability of rolling at least one six.",
    options: [{ key: "A", text: "$\\dfrac12$" },{ key: "B", text: "$\\dfrac{91}{216}$" },{ key: "C", text: "$\\dfrac{3}{6}$" },{ key: "D", text: "$\\dfrac{1}{216}$" },{ key: "E", text: "$\\dfrac{125}{216}$" }],
    answer: "B", solution: "$1-(5/6)^3=1-125/216=91/216$。" },
  { id: "bmo-smc-b-007", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "A family has two children. Given that at least one is a boy, what is the probability that both are boys? (Assume boys/girls equally likely, independent.)",
    options: [{ key: "A", text: "$\\dfrac23$" },{ key: "B", text: "$\\dfrac13$" },{ key: "C", text: "$\\dfrac14$" },{ key: "D", text: "$\\dfrac34$" },{ key: "E", text: "$\\dfrac12$" }],
    answer: "B", solution: "样本空间限于 $\\{BB,BG,GB\\}$（等可能），其中 $BB$ 占 $\\dfrac13$——经典条件概率陷阱。" },
  { id: "bmo-smc-b-008", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "Three runners $A, B, C$ finish a race in random order (all $6$ orders equally likely). Find the probability that $A$ finishes before $B$.",
    options: [{ key: "A", text: "$\\dfrac12$" },{ key: "B", text: "$\\dfrac14$" },{ key: "C", text: "$\\dfrac16$" },{ key: "D", text: "$\\dfrac23$" },{ key: "E", text: "$\\dfrac13$" }],
    answer: "A", solution: "对称性：$A$ 先于 $B$ 与 $B$ 先于 $A$ 等可能，与 $C$ 无关：$1/2$。" },
  { id: "bmo-smc-b-009", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "Two fair dice are rolled. Find the probability that the sum is even.",
    options: [{ key: "A", text: "$\\dfrac13$" },{ key: "B", text: "$\\dfrac{17}{36}$" },{ key: "C", text: "$\\dfrac12$" },{ key: "D", text: "$\\dfrac{18}{35}$" },{ key: "E", text: "$\\dfrac59$" }],
    answer: "C", solution: "两奇或两偶：$\\tfrac12\\cdot\\tfrac12+\\tfrac12\\cdot\\tfrac12=\\tfrac12$。" },
  { id: "bmo-smc-b-010", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "Three fair dice are rolled. Find the probability that all three show the same number.",
    options: [{ key: "A", text: "$\\dfrac{1}{36}$" },{ key: "B", text: "$\\dfrac{1}{216}$" },{ key: "C", text: "$\\dfrac{1}{18}$" },{ key: "D", text: "$\\dfrac{1}{6}$" },{ key: "E", text: "$\\dfrac{3}{216}$" }],
    answer: "A", solution: "$6/216=1/36$（第一枚任意，后两枚各 $1/6$）。" },
  { id: "bmo-smc-b-011", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 1, marks: 4,
    question: "A box has $3$ red and $4$ green counters. Find the probability of drawing a green one.",
    options: [{ key: "A", text: "$\\dfrac13$" },{ key: "B", text: "$\\dfrac37$" },{ key: "C", text: "$\\dfrac47$" },{ key: "D", text: "$\\dfrac14$" },{ key: "E", text: "$\\dfrac34$" }],
    answer: "C", solution: "$4/7$。" },
  { id: "bmo-smc-b-012", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "A two-digit number is chosen at random. Find the probability that it is divisible by $3$.",
    options: [{ key: "A", text: "$\\dfrac13$" },{ key: "B", text: "$\\dfrac{29}{90}$" },{ key: "C", text: "$\\dfrac{1}{3}-\\dfrac{1}{90}$" },{ key: "D", text: "$\\dfrac{33}{90}$" },{ key: "E", text: "$\\dfrac{30}{99}$" }],
    answer: "A", solution: "两位数 $10\\dots99$ 共 90 个，其中 3 的倍数 $12\\dots99$ 共 30 个：$1/3$。" },
  { id: "bmo-smc-b-013", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "A fair coin is tossed $4$ times. Find the probability of getting at least one tail.",
    options: [{ key: "A", text: "$\\dfrac{1}{16}$" },{ key: "B", text: "$\\dfrac{13}{16}$" },{ key: "C", text: "$\\dfrac{15}{16}$" },{ key: "D", text: "$\\dfrac{3}{4}$" },{ key: "E", text: "$\\dfrac{7}{8}$" }],
    answer: "C", solution: "$1-P(\\text{全正})=1-1/16$。" },
  { id: "bmo-smc-b-014", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "Two balls are drawn together from six balls numbered $1$–$6$. Find the probability that both numbers are even.",
    options: [{ key: "A", text: "$\\dfrac1{15}$" },{ key: "B", text: "$\\dfrac15$" },{ key: "C", text: "$\\dfrac13$" },{ key: "D", text: "$\\dfrac12$" },{ key: "E", text: "$\\dfrac14$" }],
    answer: "B", solution: "$\\binom32/\\binom62=3/15=1/5$。" },
  { id: "bmo-smc-b-015", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "Events $X$ and $Y$ are independent with $P(X)=\\tfrac12$, $P(Y)=\\tfrac13$. Find $P(X \\text{ and } Y)$.",
    options: [{ key: "A", text: "$\\dfrac16$" },{ key: "B", text: "$\\dfrac12$" },{ key: "C", text: "$\\dfrac13$" },{ key: "D", text: "$\\dfrac{2}{5}$" },{ key: "E", text: "$\\dfrac56$" }],
    answer: "A", solution: "独立事件相乘：$\\tfrac12\\times\\tfrac13=\\tfrac16$。" },
  { id: "bmo-smc-b-016", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 1, marks: 4,
    question: "A fair die is rolled once. Find the probability of NOT rolling a $6$.",
    options: [{ key: "A", text: "$\\dfrac45$" },{ key: "B", text: "$\\dfrac56$" },{ key: "C", text: "$\\dfrac12$" },{ key: "D", text: "$\\dfrac{5}{36}$" },{ key: "E", text: "$\\dfrac16$" }],
    answer: "B", solution: "$1-1/6=5/6$。" },
  { id: "bmo-smc-b-017", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "Two fair dice are rolled. Find the probability the total is $4$ or $10$.",
    options: [{ key: "A", text: "$\\dfrac{7}{36}$" },{ key: "B", text: "$\\dfrac1{12}$" },{ key: "C", text: "$\\dfrac5{36}$" },{ key: "D", text: "$\\dfrac16$" },{ key: "E", text: "$\\dfrac1{9}$" }],
    answer: "D", solution: "和为 4：3 种；和为 10：3 种。$6/36=1/6$。" },
  { id: "bmo-smc-b-018", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "A drawer has $2$ red and $3$ blue socks. Two are taken at random. Find the probability both are red.",
    options: [{ key: "A", text: "$\\dfrac{2}{5}$" },{ key: "B", text: "$\\dfrac{4}{25}$" },{ key: "C", text: "$\\dfrac{1}{4}$" },{ key: "D", text: "$\\dfrac1{10}$" },{ key: "E", text: "$\\dfrac15$" }],
    answer: "D", solution: "$\\binom22/\\binom52=1/10$。" },
  { id: "bmo-smc-b-019", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "What is the mean (expected value) of a single roll of a fair six-sided die?",
    options: [{ key: "A", text: "$3.6$" },{ key: "B", text: "$4$" },{ key: "C", text: "$21$" },{ key: "D", text: "$3$" },{ key: "E", text: "$3.5$" }],
    answer: "E", solution: "$(1+\\cdots+6)/6=21/6=3.5$。" },
  { id: "bmo-smc-b-020", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "Two people each pick a number at random from $\\{1,\\dots,10\\}$ (independently). Find the probability they pick the same number.",
    options: [{ key: "A", text: "$\\dfrac9{10}$" },{ key: "B", text: "$\\dfrac15$" },{ key: "C", text: "$\\dfrac{2}{10}$" },{ key: "D", text: "$\\dfrac1{10}$" },{ key: "E", text: "$\\dfrac1{100}$" }],
    answer: "D", solution: "无论第一人选什么，第二人猜中的概率都是 $1/10$。" },
  { id: "bmo-smc-b-021", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 1, marks: 4,
    question: "An arithmetic sequence has first term $5$ and common difference $3$. Find the $10$th term.",
    options: [{ key: "A", text: "$35$" },{ key: "B", text: "$27$" },{ key: "C", text: "$32$" },{ key: "D", text: "$50$" },{ key: "E", text: "$30$" }],
    answer: "C", solution: "$a_{10}=5+9\\times3=32$。" },
  { id: "bmo-smc-b-022", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Find the sum of the first $20$ terms of the arithmetic sequence $5, 8, 11, \\dots$",
    options: [{ key: "A", text: "$1340$" },{ key: "B", text: "$700$" },{ key: "C", text: "$670$" },{ key: "D", text: "$620$" },{ key: "E", text: "$650$" }],
    answer: "C", solution: "$S_{20}=\\dfrac{20}{2}\\big(2\\times5+19\\times3\\big)=10\\times67=670$。" },
  { id: "bmo-smc-b-023", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "A geometric sequence has first term $3$ and common ratio $2$. Find the $10$th term.",
    options: [{ key: "A", text: "$512$" },{ key: "B", text: "$1536$" },{ key: "C", text: "$3072$" },{ key: "D", text: "$1024$" },{ key: "E", text: "$768$" }],
    answer: "B", solution: "$a_{10}=3\\times2^9=1536$。" },
  { id: "bmo-smc-b-024", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Find the sum to infinity of $8+4+2+1+\\cdots$",
    options: [{ key: "A", text: "$\\infty$" },{ key: "B", text: "$15$" },{ key: "C", text: "$32$" },{ key: "D", text: "$16$" },{ key: "E", text: "$16.5$" }],
    answer: "D", solution: "$S=\\dfrac{8}{1-\\tfrac12}=16$。" },
  { id: "bmo-smc-b-025", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The Fibonacci sequence begins $1, 1, 2, 3, 5, \\dots$ Find the $10$th term.",
    options: [{ key: "A", text: "$61$" },{ key: "B", text: "$89$" },{ key: "C", text: "$55$" },{ key: "D", text: "$34$" },{ key: "E", text: "$45$" }],
    answer: "C", solution: "$1,1,2,3,5,8,13,21,34,55$。" },
  { id: "bmo-smc-b-026", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The $n$th odd number is $2n-1$. What is the $2026$th odd number?",
    options: [{ key: "A", text: "$4051$" },{ key: "B", text: "$4052$" },{ key: "C", text: "$2025$" },{ key: "D", text: "$4053$" },{ key: "E", text: "$2026$" }],
    answer: "A", solution: "$2\\times2026-1=4051$。" },
  { id: "bmo-smc-b-027", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 1, marks: 4,
    question: "Evaluate $1+2+3+\\cdots+100$.",
    options: [{ key: "A", text: "$4950$" },{ key: "B", text: "$5000$" },{ key: "C", text: "$5050$" },{ key: "D", text: "$5150$" },{ key: "E", text: "$10100$" }],
    answer: "C", solution: "$\\dfrac{100\\times101}{2}=5050$（高斯配对）。" },
  { id: "bmo-smc-b-028", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "A sequence has $a_1=2$ and $a_{n+1}=3a_n-2$. Find $a_5$.",
    options: [{ key: "A", text: "$28$" },{ key: "B", text: "$80$" },{ key: "C", text: "$54$" },{ key: "D", text: "$82$" },{ key: "E", text: "$164$" }],
    answer: "D", solution: "$2,4,10,28,82$（每步 $\\times3-2$；亦可看出 $a_n=3^{n-1}+1$）。" },
  { id: "bmo-smc-b-029", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "Evaluate $1-2+3-4+\\cdots+2025-2026$.",
    options: [{ key: "A", text: "$1013$" },{ key: "B", text: "$0$" },{ key: "C", text: "$-2026$" },{ key: "D", text: "$-1$" },{ key: "E", text: "$-1013$" }],
    answer: "E", solution: "两两配对 $(1-2)+(3-4)+\\cdots$ 共 1013 对，每对 $-1$：$-1013$。" },
  { id: "bmo-smc-b-030", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Evaluate $\\dfrac12+\\dfrac14+\\cdots+\\dfrac{1}{1024}$.",
    options: [{ key: "A", text: "$\\dfrac{1024}{1023}$" },{ key: "B", text: "$\\dfrac{1023}{1024}$" },{ key: "C", text: "$\\dfrac{511}{512}$" },{ key: "D", text: "$\\dfrac{1}{1024}$" },{ key: "E", text: "$1$" }],
    answer: "B", solution: "$1-\\dfrac1{1024}=\\dfrac{1023}{1024}$。" },
  { id: "bmo-smc-b-031", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "Let $S_n=1+2+\\cdots+n$. Find $S_{100}-S_{99}$.",
    options: [{ key: "A", text: "$99$" },{ key: "B", text: "$100$" },{ key: "C", text: "$5050$" },{ key: "D", text: "$1$" },{ key: "E", text: "$199$" }],
    answer: "B", solution: "$S_{100}-S_{99}=$ 第 100 项本身 $=100$。" },
  { id: "bmo-smc-b-032", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The triangular numbers are $1, 3, 6, 10, \\dots$ Find the $8$th triangular number.",
    options: [{ key: "A", text: "$55$" },{ key: "B", text: "$36$" },{ key: "C", text: "$45$" },{ key: "D", text: "$28$" },{ key: "E", text: "$32$" }],
    answer: "B", solution: "$T_8=\\dfrac{8\\times9}{2}=36$。" },
  { id: "bmo-smc-b-033", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "A sequence doubles each term: $1, 2, 4, 8, \\dots$ What is the first term to exceed $100$?",
    options: [{ key: "A", text: "$128$" },{ key: "B", text: "$102$" },{ key: "C", text: "$100$" },{ key: "D", text: "$256$" },{ key: "E", text: "$64$" }],
    answer: "A", solution: "$2^6=64<100<128=2^7$。" },
  { id: "bmo-smc-b-034", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The differences between consecutive square numbers $1,4,9,16,\\dots$ form the sequence",
    options: [{ key: "A", text: "平方数" },{ key: "B", text: "连续偶数" },{ key: "C", text: "连续奇数 $3,5,7,9,\\dots$" },{ key: "D", text: "素数" },{ key: "E", text: "常数 $2$" }],
    answer: "C", solution: "$ (n+1)^2-n^2=2n+1$：奇数列。" },
  { id: "bmo-smc-b-035", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "Four numbers are in arithmetic progression with sum $20$ and product $384$? — simplified: an AP of four terms has sum $20$. Find the sum of the middle two terms.",
    options: [{ key: "A", text: "$15$" },{ key: "B", text: "$20$" },{ key: "C", text: "$10$" },{ key: "D", text: "$5$" },{ key: "E", text: "无法确定" }],
    answer: "C", solution: "四项 AP 关于中心对称：首尾对与中间对的和都等于总和的一半 $=10$。" },
  { id: "bmo-smc-b-036", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "Numbers that leave remainder $1$ when divided by both $3$ and $4$ form the sequence $1, 13, 25, \\dots$ Find the $10$th term.",
    options: [{ key: "A", text: "$97$" },{ key: "B", text: "$120$" },{ key: "C", text: "$109$" },{ key: "D", text: "$121$" },{ key: "E", text: "$133$" }],
    answer: "C", solution: "公差 $\\mathrm{lcm}(3,4)=12$：$a_{10}=1+9\\times12=109$。" },
  { id: "bmo-smc-b-037", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The sequence $a_n = n^2+n$ begins $2, 6, 12, 20, \\dots$ Which term equals $110$?",
    options: [{ key: "A", text: "第 $9$ 项" },{ key: "B", text: "没有这一项" },{ key: "C", text: "第 $12$ 项" },{ key: "D", text: "第 $10$ 项" },{ key: "E", text: "第 $11$ 项" }],
    answer: "D", solution: "$n^2+n=110\\Rightarrow n(n+1)=110=10\\times11\\Rightarrow n=10$。" },
  { id: "bmo-smc-b-038", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "Which is larger: $\\dfrac{1}{10}+\\dfrac{1}{11}+\\cdots+\\dfrac{1}{19}$ (ten terms) or $\\dfrac12$?",
    options: [{ key: "A", text: "比 $\\dfrac12$ 大" },{ key: "B", text: "等于 $1$" },{ key: "C", text: "比 $\\dfrac12$ 小" },{ key: "D", text: "恰好等于 $\\dfrac12$" },{ key: "E", text: "无法比较" }],
    answer: "A", solution: "十项每项 $>\\dfrac1{20}$，和 $>\\dfrac{10}{20}=\\dfrac12$。（下界打包——调和级数发散论证的雏形。）" },
  { id: "bmo-smc-b-039", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 1, marks: 4,
    question: "Find the sum of the first $10$ even numbers $2+4+\\cdots+20$.",
    options: [{ key: "A", text: "$100$" },{ key: "B", text: "$120$" },{ key: "C", text: "$55$" },{ key: "D", text: "$110$" },{ key: "E", text: "$90$" }],
    answer: "D", solution: "$2(1+\\cdots+10)=2\\times55=110$。" },
  { id: "bmo-smc-b-040", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "What is the units digit of $2026^2$?",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$4$" },{ key: "C", text: "$8$" },{ key: "D", text: "$2$" },{ key: "E", text: "$0$" }],
    answer: "A", solution: "只看个位：$6^2=36$ → 个位 6。" },
  { id: "bmo-smc-b-041", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "For positive reals $a,b$, the AM–GM inequality states $\\dfrac{a+b}{2}\\ge\\sqrt{ab}$. When does equality hold?",
    options: [{ key: "A", text: "$a=b$ 时" },{ key: "B", text: "$ab=1$" },{ key: "C", text: "从不相等" },{ key: "D", text: "$a+b=2$" },{ key: "E", text: "$a=1$ 或 $b=1$" }],
    answer: "A", solution: "配方 $\\left(\\sqrt a-\\sqrt b\\right)^2\\ge0$：当且仅当 $a=b$ 取等。" },
  { id: "bmo-smc-b-042", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "For $x>0$, find the minimum value of $x+\\dfrac1x$.",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$2$" },{ key: "C", text: "没有最小值" },{ key: "D", text: "$0$" },{ key: "E", text: "$\\dfrac12$" }],
    answer: "B", solution: "AM–GM：$x+\\dfrac1x\\ge2\\sqrt{x\\cdot\\tfrac1x}=2$，等号在 $x=1$。" },
  { id: "bmo-smc-b-043", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Two positive numbers have sum $10$. Find the maximum value of their product.",
    options: [{ key: "A", text: "$50$" },{ key: "B", text: "$20$" },{ key: "C", text: "$100$" },{ key: "D", text: "$24$" },{ key: "E", text: "$25$" }],
    answer: "E", solution: "定和最大积在相等：$5\\times5=25$。" },
  { id: "bmo-smc-b-044", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "How many integers $x$ satisfy $2 < 3x-1 < 11$?",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "无穷多" },{ key: "C", text: "$1$" },{ key: "D", text: "$4$" },{ key: "E", text: "$3$" }],
    answer: "A", solution: "$1<x<4$：$x=2,3$。" },
  { id: "bmo-smc-b-045", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "For positive reals with $abc=27$, the minimum of $a+b+c$ is",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$9$" },{ key: "C", text: "$27$" },{ key: "D", text: "$81$" },{ key: "E", text: "$3\\sqrt3$" }],
    answer: "B", solution: "三元 AM–GM：$a+b+c\\ge3\\sqrt[3]{abc}=3\\times3=9$，等号 $a=b=c=3$。" },
  { id: "bmo-smc-b-046", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "If $x^2+y^2=8$, find the maximum value of $x+y$.",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$2\\sqrt2$" },{ key: "C", text: "$16$" },{ key: "D", text: "$\\sqrt8$" },{ key: "E", text: "$4$" }],
    answer: "E", solution: "$(x+y)^2\\le2(x^2+y^2)=16$（柯西/QM–AM），故 $x+y\\le4$，等号 $x=y=2$。" },
  { id: "bmo-smc-b-047", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Which is larger: $2^{300}$ or $3^{200}$?",
    options: [{ key: "A", text: "$3^{200}$" },{ key: "B", text: "$2^{300}$" },{ key: "C", text: "相等" },{ key: "D", text: "无法比较" },{ key: "E", text: "取决于底数" }],
    answer: "A", solution: "同取 100 次根：比较 $2^3=8$ 与 $3^2=9$：$9>8$，故 $3^{200}$ 大。" },
  { id: "bmo-smc-b-048", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Solve $|x-3|\\le4$. The solution set is",
    options: [{ key: "A", text: "$-1\\le x\\le7$" },{ key: "B", text: "$x\\le7$" },{ key: "C", text: "$-4\\le x\\le4$" },{ key: "D", text: "$x\\ge-1$" },{ key: "E", text: "$-7\\le x\\le1$" }],
    answer: "A", solution: "$-4\\le x-3\\le4$。" },
  { id: "bmo-smc-b-049", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "For $0<x<1$, arrange in increasing order: $x,\\ x^2,\\ \\sqrt x$.",
    options: [{ key: "A", text: "$x^2<\\sqrt x<x$" },{ key: "B", text: "$\\sqrt x<x<x^2$" },{ key: "C", text: "$x<x^2<\\sqrt x$" },{ key: "D", text: "三者相等" },{ key: "E", text: "$x^2 < x < \\sqrt x$" }],
    answer: "E", solution: "$0<x<1$ 时幂次越高越小：$x^2<x<\\sqrt x$（如 $x=\\tfrac14$：$\\tfrac1{16}<\\tfrac14<\\tfrac12$）。" },
  { id: "bmo-smc-b-050", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "How many triangles with integer side lengths have perimeter $12$?",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$6$" },{ key: "C", text: "$4$" },{ key: "D", text: "$5$" },{ key: "E", text: "$3$" }],
    answer: "E", solution: "满足 $a\\le b\\le c$、$a+b>c$、和 12：$(2,5,5),(3,4,5),(4,4,4)$，共 3 个。" },
  { id: "bmo-smc-b-051", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "If $a>b$ and $c<0$, which is always true?",
    options: [{ key: "A", text: "$ac<bc$" },{ key: "B", text: "$a+c<b+c$" },{ key: "C", text: "$ac>bc$" },{ key: "D", text: "$a^2>b^2$" },{ key: "E", text: "$\\dfrac ac>\\dfrac bc$" }],
    answer: "A", solution: "乘负数翻转不等号。" },
  { id: "bmo-smc-b-052", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "For positive $a, b$, find the minimum value of $(a+b)\\left(\\dfrac1a+\\dfrac1b\\right)$.",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$16$" },{ key: "C", text: "$4$" },{ key: "D", text: "$1$" },{ key: "E", text: "$2$" }],
    answer: "C", solution: "展开 $=2+\\dfrac ab+\\dfrac ba\\ge2+2=4$（AM–GM），等号 $a=b$。" },
  { id: "bmo-smc-b-053", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "A rectangle has perimeter $20$. Its area is at most",
    options: [{ key: "A", text: "$24$" },{ key: "B", text: "$25$" },{ key: "C", text: "$100$" },{ key: "D", text: "$20$" },{ key: "E", text: "$50$" }],
    answer: "B", solution: "半周长 10 定和：最大积在正方形 $5\\times5=25$。" },
  { id: "bmo-smc-b-054", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "For all real $x$, the expression $x^2-2x+2$ is always",
    options: [{ key: "A", text: "大于 $0$（最小值 $1$）" },{ key: "B", text: "无界向下" },{ key: "C", text: "可能为负" },{ key: "D", text: "最小值 $0$" },{ key: "E", text: "最小值 $2$" }],
    answer: "A", solution: "配方 $(x-1)^2+1\\ge1>0$。" },
  { id: "bmo-smc-b-055", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "Positive reals $x, y$ satisfy $x+2y=6$. Find the maximum of $xy$.",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$9$" },{ key: "C", text: "$3$" },{ key: "D", text: "$\\dfrac92$" },{ key: "E", text: "$\\dfrac{9}{4}$" }],
    answer: "D", solution: "$xy=\\tfrac12\\cdot x\\cdot2y\\le\\tfrac12\\left(\\dfrac{x+2y}{2}\\right)^2=\\tfrac12\\times9=\\dfrac92$，等号 $x=2y=3$。" },
  { id: "bmo-smc-b-056", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "If $0<a<b$, which of these is the largest?",
    options: [{ key: "A", text: "$\\dfrac{a}{a+b}$" },{ key: "B", text: "$\\dfrac{b}{a}$" },{ key: "C", text: "$\\dfrac{a+1}{b+1}$" },{ key: "D", text: "$1$" },{ key: "E", text: "$\\dfrac{a}{b}$" }],
    answer: "B", solution: "$b/a>1$ 而其余各项均 $\\le1$（$\\tfrac{a+1}{b+1}<1$ 因 $a<b$）。" },
  { id: "bmo-smc-b-057", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "For $x>0$, find the minimum of $x+\\dfrac9x$.",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$3$" },{ key: "C", text: "$6$" },{ key: "D", text: "$4.5$" },{ key: "E", text: "$10$" }],
    answer: "C", solution: "AM–GM：$\\ge2\\sqrt9=6$，等号 $x=3$。" },
  { id: "bmo-smc-b-058", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "Real numbers satisfy $a+b=2$. The minimum value of $a^2+b^2$ is",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$2$" },{ key: "C", text: "$4$" },{ key: "D", text: "$1$" },{ key: "E", text: "$\\sqrt2$" }],
    answer: "B", solution: "QM–AM：$a^2+b^2\\ge\\dfrac{(a+b)^2}{2}=2$，等号 $a=b=1$。" },
  { id: "bmo-smc-b-059", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The sides of a triangle are $5$, $9$ and $x$ (an integer). How many values can $x$ take?",
    options: [{ key: "A", text: "$13$" },{ key: "B", text: "$9$" },{ key: "C", text: "$10$" },{ key: "D", text: "$8$" },{ key: "E", text: "$7$" }],
    answer: "B", solution: "三角不等式：$4<x<14$，整数 $5\\dots13$ 共 9 个。" },
  { id: "bmo-smc-b-060", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Which is greater: $\\sqrt{50}$ or $7$?",
    options: [{ key: "A", text: "$\\sqrt{50}$（因为 $50>49$）" },{ key: "B", text: "$7$" },{ key: "C", text: "无法比较" },{ key: "D", text: "相等" },{ key: "E", text: "$\\sqrt{50}=7.5$" }],
    answer: "A", solution: "$7=\\sqrt{49}<\\sqrt{50}$。" },
  { id: "bmo-smc-b-061", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The graph of $y=x^2$ is translated $3$ units right and $2$ units up. Its new equation is",
    options: [{ key: "A", text: "$y=x^2+3x+2$" },{ key: "B", text: "$y=(x-3)^2-2$" },{ key: "C", text: "$y=(x+3)^2-2$" },{ key: "D", text: "$y=(x-3)^2+2$" },{ key: "E", text: "$y=(x+3)^2+2$" }],
    answer: "D", solution: "右移用 $x-3$，上移加 2。" },
  { id: "bmo-smc-b-062", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "For what value of $k>0$ does $x^2-4x+k=0$ have exactly one solution?",
    options: [{ key: "A", text: "$k=8$" },{ key: "B", text: "$k=4$" },{ key: "C", text: "$k=2$" },{ key: "D", text: "$k=-4$" },{ key: "E", text: "$k=16$" }],
    answer: "B", solution: "判别式 $16-4k=0\\Rightarrow k=4$。" },
  { id: "bmo-smc-b-063", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 1, marks: 4,
    question: "Where does the line $y=3x-6$ cross the $x$-axis?",
    options: [{ key: "A", text: "$(2, 0)$" },{ key: "B", text: "$(6, 0)$" },{ key: "C", text: "$(3, 0)$" },{ key: "D", text: "$(-2, 0)$" },{ key: "E", text: "$(0, -6)$" }],
    answer: "A", solution: "令 $y=0$：$x=2$。" },
  { id: "bmo-smc-b-064", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The graphs of $y=x^2$ and $y=2x+3$ intersect at how many points?",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$0$" },{ key: "C", text: "$3$" },{ key: "D", text: "无穷多" },{ key: "E", text: "$1$" }],
    answer: "A", solution: "$x^2-2x-3=(x-3)(x+1)=0$：两交点。" },
  { id: "bmo-smc-b-065", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The function $f(x)=(x-3)^2+1$. Find $f(0)$ and the minimum value of $f$.",
    options: [{ key: "A", text: "$f(0)=9$；最小值 $0$" },{ key: "B", text: "$f(0)=10$；最小值 $3$" },{ key: "C", text: "$f(0)=1$；最小值 $10$" },{ key: "D", text: "$f(0)=10$；最小值 $1$" },{ key: "E", text: "$f(0)=8$；最小值 $1$" }],
    answer: "D", solution: "$f(0)=9+1=10$；顶点值 1。" },
  { id: "bmo-smc-b-066", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Which transformation maps $y=f(x)$ to $y=f(-x)$?",
    options: [{ key: "A", text: "关于原点旋转 $180°$" },{ key: "B", text: "上移 1" },{ key: "C", text: "关于 $x$ 轴反射" },{ key: "D", text: "右移 1" },{ key: "E", text: "关于 $y$ 轴反射" }],
    answer: "E", solution: "$x\\to-x$：镜像到 $y$ 轴另一侧。" },
  { id: "bmo-smc-b-067", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The equation $x^2+y^2-6x+8y=0$ represents a circle. Find its radius.",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$25$" },{ key: "C", text: "$7$" },{ key: "D", text: "$\\sqrt{10}$" },{ key: "E", text: "$10$" }],
    answer: "A", solution: "配方 $(x-3)^2+(y+4)^2=25$：半径 5（过原点）。" },
  { id: "bmo-smc-b-068", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "The cubic $y=x^3-3x$ has how many turning points?",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$0$" },{ key: "C", text: "$3$" },{ key: "D", text: "$2$" },{ key: "E", text: "无穷多" }],
    answer: "D", solution: "$y'=3x^2-3=0$ 给 $x=\\pm1$：一极大一极小。" },
  { id: "bmo-smc-b-069", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 1, marks: 4,
    question: "If $g(x)=2x-3$ and $g(a)=7$, find $a$.",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$\\dfrac72$" },{ key: "C", text: "$4$" },{ key: "D", text: "$11$" },{ key: "E", text: "$5$" }],
    answer: "E", solution: "$2a-3=7\\Rightarrow a=5$。" },
  { id: "bmo-smc-b-070", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "The function $f(x)=\\dfrac{1}{x-2}$ has a vertical asymptote at",
    options: [{ key: "A", text: "$x=0$" },{ key: "B", text: "$x=-2$" },{ key: "C", text: "$y=0$" },{ key: "D", text: "$x=2$" },{ key: "E", text: "$y=2$" }],
    answer: "D", solution: "分母为零处：$x=2$。（水平渐近线为 $y=0$。）" },
  { id: "bmo-smc-b-071", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "How many solutions does $|x| = 3$ have? And $|x| = -3$?",
    options: [{ key: "A", text: "$2$ 个；$0$ 个" },{ key: "B", text: "$1$ 个；$0$ 个" },{ key: "C", text: "$1$ 个；$1$ 个" },{ key: "D", text: "$2$ 个；$1$ 个" },{ key: "E", text: "$2$ 个；$2$ 个" }],
    answer: "A", solution: "绝对值非负：$|x|=3$ 给 $\\pm3$；$|x|=-3$ 无解。" },
  { id: "bmo-smc-b-072", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The line through $(1, 2)$ and $(3, 8)$ has gradient",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$\\dfrac13$" },{ key: "C", text: "$3$" },{ key: "D", text: "$6$" },{ key: "E", text: "$5$" }],
    answer: "C", solution: "$\\dfrac{8-2}{3-1}=3$。" },
  { id: "bmo-smc-b-073", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Two lines are perpendicular. One has gradient $\\dfrac25$. The other has gradient",
    options: [{ key: "A", text: "$\\dfrac52$" },{ key: "B", text: "$\\dfrac{5}{2}$ 或 $-\\dfrac{2}{5}$ 都可以" },{ key: "C", text: "$1-\\dfrac25$" },{ key: "D", text: "$-\\dfrac52$" },{ key: "E", text: "$-\\dfrac25$" }],
    answer: "D", solution: "垂直斜率之积 $=-1$：$-\\dfrac52$。" },
  { id: "bmo-smc-b-074", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 1, marks: 4,
    question: "The graph of $y=x^2-9$ crosses the $x$-axis at",
    options: [{ key: "A", text: "$x=9$" },{ key: "B", text: "$x=\\pm3$" },{ key: "C", text: "$x=\\pm9$" },{ key: "D", text: "$x=3$ 仅" },{ key: "E", text: "$x=0$" }],
    answer: "B", solution: "$x^2=9$。" },
  { id: "bmo-smc-b-075", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "For the quadratic $y=ax^2+bx+c$ with $a<0$ and discriminant $<0$, the graph",
    options: [{ key: "A", text: "穿过 $x$ 轴两次" },{ key: "B", text: "全部位于 $x$ 轴上方" },{ key: "C", text: "与 $x$ 轴相切" },{ key: "D", text: "经过原点" },{ key: "E", text: "全部位于 $x$ 轴下方" }],
    answer: "E", solution: "开口向下且无实根：整条在轴下。" },
  { id: "bmo-smc-b-076", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "If $f(x)=x+1$ and $g(x)=2x$, find $g(f(4))$.",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$10$" },{ key: "C", text: "$8$" },{ key: "D", text: "$12$" },{ key: "E", text: "$9$" }],
    answer: "B", solution: "$f(4)=5$，$g(5)=10$。" },
  { id: "bmo-smc-b-077", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "The inverse function of $f(x)=\\dfrac{x-1}{2}$ is",
    options: [{ key: "A", text: "$\\dfrac{2}{x-1}$" },{ key: "B", text: "$1-2x$" },{ key: "C", text: "$f^{-1}(x)=2x+1$" },{ key: "D", text: "$\\dfrac{x+1}{2}$" },{ key: "E", text: "$2x-1$" }],
    answer: "C", solution: "解 $y=\\dfrac{x-1}2$ 得 $x=2y+1$。" },
  { id: "bmo-smc-b-078", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "How many times do the graphs of $y=\\dfrac1x$ and $y=x$ intersect?",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$2$" },{ key: "C", text: "无穷多" },{ key: "D", text: "$3$" },{ key: "E", text: "$0$" }],
    answer: "B", solution: "$x^2=1$：$(1,1)$ 与 $(-1,-1)$。" },
  { id: "bmo-smc-b-079", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The graph of $y=x^2-2x+1$ touches the $x$-axis at",
    options: [{ key: "A", text: "不接触" },{ key: "B", text: "$x=-1$" },{ key: "C", text: "$x=\\pm1$" },{ key: "D", text: "$x=2$" },{ key: "E", text: "$x=1$（相切）" }],
    answer: "E", solution: "$(x-1)^2$：重根相切。" },
  { id: "bmo-smc-b-080", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "A quadratic has roots $2$ and $-5$ and leading coefficient $1$. Its equation is",
    options: [{ key: "A", text: "$y=x^2+3x-10$" },{ key: "B", text: "$y=x^2-3x-10$" },{ key: "C", text: "$y=x^2-3x+10$" },{ key: "D", text: "$y=x^2+3x+10$" },{ key: "E", text: "$y=x^2-7x+10$" }],
    answer: "A", solution: "$(x-2)(x+5)=x^2+3x-10$。" },
  { id: "bmo-smc-b-081", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "The range of $f(x)=\\sqrt{x-4}$ (real values) is",
    options: [{ key: "A", text: "$f(x)\\ge4$" },{ key: "B", text: "一切实数" },{ key: "C", text: "$f(x)>0$ 严格" },{ key: "D", text: "$x\\ge0$" },{ key: "E", text: "$f(x)\\ge0$，定义域 $x\\ge4$" }],
    answer: "E", solution: "根号输出非负；被开方数须 $\\ge0$。" },
  { id: "bmo-smc-b-082", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The graph of $y=2^x$ passes through",
    options: [{ key: "A", text: "$(0, 2)$" },{ key: "B", text: "$(0, 1)$ 且恒正" },{ key: "C", text: "可取负值" },{ key: "D", text: "$(1, 1)$" },{ key: "E", text: "$(0, 0)$" }],
    answer: "B", solution: "$2^0=1$；指数函数恒 $>0$。" },
  { id: "bmo-smc-b-083", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Solve $4^x = 2^{x+4}$.",
    options: [{ key: "A", text: "$x=\\dfrac43$" },{ key: "B", text: "$x=2$" },{ key: "C", text: "$x=8$" },{ key: "D", text: "$x=4$" },{ key: "E", text: "$x=1$" }],
    answer: "D", solution: "$2^{2x}=2^{x+4}\\Rightarrow2x=x+4\\Rightarrow x=4$。" },
  { id: "bmo-smc-b-084", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "The maximum value of $f(x)=5-|x-2|$ is",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$7$" },{ key: "C", text: "$5$（在 $x=2$）" },{ key: "D", text: "无最大值" },{ key: "E", text: "$2$" }],
    answer: "C", solution: "$|x-2|\\ge0$，取 0 时 $f=5$。" },
  { id: "bmo-smc-b-085", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "If $y$ is inversely proportional to $x$ and $y=6$ when $x=2$, find $y$ when $x=4$.",
    options: [{ key: "A", text: "$1.5$" },{ key: "B", text: "$3$" },{ key: "C", text: "$12$" },{ key: "D", text: "$8$" },{ key: "E", text: "$4$" }],
    answer: "B", solution: "$xy=12$ 恒定：$y=12/4=3$。" },
];
