// BMO/UKMT —— SMC 风格打样批（数论+代数）。原创，逐题 sympy/程序断言。
import type { MCQQuestion } from "./types";

export const BMO_SMC_SAMPLE: MCQQuestion[] = [
  { id: "bmo-smc-001", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "What is the last digit of $3^{2026}$?",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$3$" },{ key: "C", text: "$27$" },{ key: "D", text: "$7$" },{ key: "E", text: "$1$" }],
    answer: "A", solution: "Last digits of $3^k$ cycle with period 4: $3,9,7,1$. $2026\\equiv2\\pmod4$, so last digit $=9$." },
  { id: "bmo-smc-002", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "How many zeros does $30!$ end in?",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$7$" },{ key: "C", text: "$5$" },{ key: "D", text: "$6$" },{ key: "E", text: "$10$" }],
    answer: "B", solution: "Count factors of 5: $\\lfloor30/5\\rfloor+\\lfloor30/25\\rfloor=6+1=7$ (2s are plentiful)." },
  { id: "bmo-smc-003", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 1, marks: 4,
    question: "How many two-digit numbers are divisible by $7$?",
    options: [{ key: "A", text: "$14$" },{ key: "B", text: "$13$ 与 $14$ 都可能" },{ key: "C", text: "$11$" },{ key: "D", text: "$12$" },{ key: "E", text: "$13$" }],
    answer: "E", solution: "From $14=7\\times2$ to $98=7\\times14$: $14-2+1=13$." },
  { id: "bmo-smc-004", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "What is $\\gcd(2026, 1352)$?",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$338$" },{ key: "C", text: "$13$" },{ key: "D", text: "$26$" },{ key: "E", text: "$1$" }],
    answer: "A", solution: "$2026=2\\times1013$（$1013$ 是素数），$1352=2^3\\times13^2$。公共部分只有一个 $2$。" },
  { id: "bmo-smc-005", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 3, marks: 4,
    question: "What is the number of digits of the smallest positive integer whose digits sum to $2026$?",
    options: [{ key: "A", text: "$225$" },{ key: "B", text: "$226$" },{ key: "C", text: "$227$" },{ key: "D", text: "$253$" },{ key: "E", text: "$2026$" }],
    answer: "B", solution: "贪心：尽量多用 9。$2026=225\\times9+1$，最小数是 $1$ 后跟 $225$ 个 $9$，共 $226$ 位。" },
  { id: "bmo-smc-006", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "How many twin prime pairs $(p, p+2)$ have both members at most $30$?",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$6$" },{ key: "C", text: "$3$" },{ key: "D", text: "$4$" },{ key: "E", text: "$2$" }],
    answer: "D", solution: "$(3,5),(5,7),(11,13),(17,19)$ 共 4 对（$(29,31)$ 的 31 超界）。" },
  { id: "bmo-smc-007", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "What is the remainder when $7^{100}$ is divided by $5$?",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$4$" },{ key: "C", text: "$0$" },{ key: "D", text: "$3$" },{ key: "E", text: "$2$" }],
    answer: "A", solution: "$7\\equiv2\\pmod5$，$2^4=16\\equiv1$，而 $100$ 是 $4$ 的倍数，故余 $1$。" },
  { id: "bmo-smc-008", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "How many positive divisors does $2025$ have?",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$10$" },{ key: "C", text: "$18$" },{ key: "D", text: "$15$" },{ key: "E", text: "$12$" }],
    answer: "D", solution: "$2025=3^4\\times5^2$：$(4+1)(2+1)=15$。" },
  { id: "bmo-smc-009", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 3, marks: 4,
    question: "How many $1$s appear when $2026$ is written in binary?",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$8$" },{ key: "C", text: "$6$" },{ key: "D", text: "$10$" },{ key: "E", text: "$7$" }],
    answer: "B", solution: "$2026=1024+512+256+128+64+32+8+2=11111101010_2$：8 个 1。" },
  { id: "bmo-smc-010", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "What is the smallest positive integer $n$ such that $n!$ is divisible by $990$?",
    options: [{ key: "A", text: "$11$" },{ key: "B", text: "$9$" },{ key: "C", text: "$99$" },{ key: "D", text: "$12$" },{ key: "E", text: "$10$" }],
    answer: "A", solution: "$990=2\\times3^2\\times5\\times11$：必须包含因子 $11$，而 $11!$ 已含其余全部，故 $n=11$。" },
  { id: "bmo-smc-011", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "What is the units digit of $1!+2!+3!+\\cdots+2026!$?",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$7$" },{ key: "C", text: "$0$" },{ key: "D", text: "$9$" },{ key: "E", text: "$3$" }],
    answer: "E", solution: "$5!$ 起个位全为 0：$1+2+6+24=33$，个位 $3$。" },
  { id: "bmo-smc-012", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "How many perfect squares lie strictly between $100$ and $1000$?",
    options: [{ key: "A", text: "$22$" },{ key: "B", text: "$31$" },{ key: "C", text: "$21$" },{ key: "D", text: "$20$" },{ key: "E", text: "$19$" }],
    answer: "C", solution: "$11^2=121$ 到 $31^2=961$：$31-11+1=21$ 个（$10^2=100$ 不算「strictly between」）。" },
  { id: "bmo-smc-013", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "Positive integers $x, y$ satisfy $xy = 2026$. What is the smallest possible value of $x+y$?",
    options: [{ key: "A", text: "$91$" },{ key: "B", text: "$507$" },{ key: "C", text: "$1013$" },{ key: "D", text: "$2027$" },{ key: "E", text: "$1015$" }],
    answer: "E", solution: "$2026=2\\times1013$（1013 素）：因数对只有 $(1,2026),(2,1013)$，和最小 $2+1013=1015$。" },
  { id: "bmo-smc-014", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "What is the smallest positive integer that leaves remainder $2$ when divided by $3$, and remainder $3$ when divided by $5$?",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$23$" },{ key: "C", text: "$17$" },{ key: "D", text: "$13$" },{ key: "E", text: "$11$" }],
    answer: "A", solution: "逐个试或中国剩余：$8=3\\times2+2=5\\times1+3$ ✓，且 $<15$ 内唯一。" },
  { id: "bmo-smc-015", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 3, marks: 4,
    question: "Find the sum of all primes $p < 100$ such that $p^2+2$ is also prime.",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$14$" },{ key: "C", text: "$8$" },{ key: "D", text: "$0$" },{ key: "E", text: "$3$" }],
    answer: "E", solution: "$p\\ne3$ 时 $p^2\\equiv1\\pmod3$，故 $p^2+2\\equiv0\\pmod3$ 且 $>3$，必为合数。只剩 $p=3$：$9+2=11$ 素 ✓。和为 $3$。" },
  { id: "bmo-smc-016", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Given $x+\\dfrac1x=3$, find $x^2+\\dfrac1{x^2}$.",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$8$" },{ key: "C", text: "$11$" },{ key: "D", text: "$6$" },{ key: "E", text: "$7$" }],
    answer: "E", solution: "平方：$\\left(x+\\tfrac1x\\right)^2=x^2+2+\\tfrac1{x^2}=9$，故所求 $=7$。" },
  { id: "bmo-smc-017", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Solve $\\sqrt{x+5} = x-1$.",
    options: [{ key: "A", text: "$x=4$" },{ key: "B", text: "$x=5$" },{ key: "C", text: "$x=-1$" },{ key: "D", text: "无解" },{ key: "E", text: "$x=4$ 或 $x=-1$" }],
    answer: "A", solution: "平方得 $x^2-3x-4=0$，$x=4$ 或 $-1$；但需 $x-1\\ge0$，舍去 $-1$。验证 $\\sqrt9=3=4-1$ ✓。" },
  { id: "bmo-smc-018", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 1, marks: 4,
    question: "If $f(x)=2x+3$, find $f(f(2))$.",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$11$" },{ key: "C", text: "$17$" },{ key: "D", text: "$21$" },{ key: "E", text: "$14$" }],
    answer: "C", solution: "$f(2)=7$，$f(7)=17$。" },
  { id: "bmo-smc-019", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Find the sum of the first $100$ odd numbers: $1+3+5+\\cdots+199$.",
    options: [{ key: "A", text: "$10100$" },{ key: "B", text: "$5050$" },{ key: "C", text: "$9999$" },{ key: "D", text: "$20000$" },{ key: "E", text: "$10000$" }],
    answer: "E", solution: "前 $n$ 个奇数之和 $=n^2$：$100^2=10000$（可由 $n^2-(n-1)^2=2n-1$ 叠缩看出）。" },
  { id: "bmo-smc-020", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "If $\\alpha,\\beta$ are the roots of $x^2-5x+6=0$, find $\\alpha^2+\\beta^2$.",
    options: [{ key: "A", text: "$25$" },{ key: "B", text: "$12$" },{ key: "C", text: "$13$" },{ key: "D", text: "$37$" },{ key: "E", text: "$19$" }],
    answer: "C", solution: "韦达：$\\alpha+\\beta=5$，$\\alpha\\beta=6$；$\\alpha^2+\\beta^2=(\\alpha+\\beta)^2-2\\alpha\\beta=25-12=13$。" },
  { id: "bmo-smc-021", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "Evaluate the infinite sum $3-1+\\dfrac13-\\dfrac19+\\cdots$.",
    options: [{ key: "A", text: "$\\dfrac92$" },{ key: "B", text: "$\\dfrac{27}{8}$" },{ key: "C", text: "$\\dfrac{9}{2}-1$" },{ key: "D", text: "$2$" },{ key: "E", text: "$\\dfrac94$" }],
    answer: "E", solution: "首项 $3$、公比 $-\\tfrac13$：$S=\\dfrac{3}{1+\\tfrac13}=\\dfrac94$。" },
  { id: "bmo-smc-022", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "If $x+y=10$ and $x^2-y^2=40$, find $x$.",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$7$" },{ key: "C", text: "$4$" },{ key: "D", text: "$3$" },{ key: "E", text: "$6$" }],
    answer: "B", solution: "$x^2-y^2=(x+y)(x-y)=10(x-y)=40\\Rightarrow x-y=4$；与 $x+y=10$ 联立得 $x=7$。" },
  { id: "bmo-smc-023", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "How many integers $x$ satisfy $|2x-7|<5$?",
    options: [{ key: "A", text: "无穷多" },{ key: "B", text: "$3$" },{ key: "C", text: "$4$" },{ key: "D", text: "$6$" },{ key: "E", text: "$5$" }],
    answer: "C", solution: "$-5<2x-7<5\\Rightarrow1<x<6$：整数 $2,3,4,5$，共 4 个。" },
  { id: "bmo-smc-024", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Evaluate $\\log_2\\!\\left(8\\sqrt2\\right)$.",
    options: [{ key: "A", text: "$\\dfrac52$" },{ key: "B", text: "$4$" },{ key: "C", text: "$\\dfrac{7}{4}$" },{ key: "D", text: "$\\dfrac72$" },{ key: "E", text: "$3$" }],
    answer: "D", solution: "$8\\sqrt2=2^3\\cdot2^{1/2}=2^{7/2}$，故对数为 $\\tfrac72$。" },
  { id: "bmo-smc-025", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Find the remainder when $x^3-2x+1$ is divided by $x-2$.",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$3$" },{ key: "C", text: "$1$" },{ key: "D", text: "$-3$" },{ key: "E", text: "$13$" }],
    answer: "A", solution: "余数定理：代入 $x=2$：$8-4+1=5$。" },
  { id: "bmo-smc-026", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "If $a:b = 3:4$ and $b:c = 6:5$, find $a:c$.",
    options: [{ key: "A", text: "$18:20$ 即 $9:10$ 都不对" },{ key: "B", text: "$2:3$" },{ key: "C", text: "$15:8$" },{ key: "D", text: "$3:5$" },{ key: "E", text: "$9:10$" }],
    answer: "E", solution: "统一 $b$：$a:b=9:12$，$b:c=12:10$，故 $a:c=9:10$。" },
  { id: "bmo-smc-027", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "A function satisfies $f(x)+2f\\!\\left(\\dfrac1x\\right)=3x$ for all $x\\neq0$. Find $f(2)$.",
    options: [{ key: "A", text: "$-\\dfrac12$" },{ key: "B", text: "$\\dfrac72$" },{ key: "C", text: "$-1$" },{ key: "D", text: "$2$" },{ key: "E", text: "$1$" }],
    answer: "C", solution: "取 $x=2$：$f(2)+2f(\\tfrac12)=6$；取 $x=\\tfrac12$：$f(\\tfrac12)+2f(2)=\\tfrac32$。消元得 $f(2)=-1$（$f(\\tfrac12)=\\tfrac72$）。" },
  { id: "bmo-smc-028", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Simplify $\\left(\\sqrt5+\\sqrt3\\right)^2-\\left(\\sqrt5-\\sqrt3\\right)^2$.",
    options: [{ key: "A", text: "$2\\sqrt{15}$" },{ key: "B", text: "$4$" },{ key: "C", text: "$4\\sqrt{15}$" },{ key: "D", text: "$8\\sqrt2$" },{ key: "E", text: "$16$" }],
    answer: "C", solution: "平方差：$(a+b)^2-(a-b)^2=4ab=4\\sqrt{15}$。" },
  { id: "bmo-smc-029", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "A sequence has $a_1=2$ and $a_{n+1}=\\dfrac{1}{1-a_n}$. Find $a_{2026}$.",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$\\dfrac12$" },{ key: "C", text: "$1$" },{ key: "D", text: "$-1$" },{ key: "E", text: "$\\dfrac{1}{2026}$" }],
    answer: "A", solution: "算前几项：$2,\\,-1,\\,\\tfrac12,\\,2,\\dots$ 周期 3。$2026\\equiv1\\pmod3$，故 $a_{2026}=a_1=2$。" },
  { id: "bmo-smc-030", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 1, marks: 4,
    question: "Find the minimum value of $x^2-6x+11$.",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$-2$" },{ key: "C", text: "$11$" },{ key: "D", text: "$3$" },{ key: "E", text: "$2$" }],
    answer: "E", solution: "配方：$(x-3)^2+2\\ge2$，最小值 $2$（在 $x=3$）。" },
];
