// BMO/UKMT SMC 主批 —— 几何/组合/数论/代数。原创，逐题程序断言。
import type { MCQQuestion } from "./types";

export const BMO_SMC_MAIN: MCQQuestion[] = [
  { id: "bmo-smc-m-001", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 1, marks: 4,
    question: "Find the interior angle of a regular octagon.",
    options: [{ key: "A", text: "$150°$" },{ key: "B", text: "$135°$" },{ key: "C", text: "$144°$" },{ key: "D", text: "$120°$" },{ key: "E", text: "$108°$" }],
    answer: "B", solution: "内角 $=\\dfrac{180°(n-2)}{n}=\\dfrac{180°\\times6}{8}=135°$。" },
  { id: "bmo-smc-m-002", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 1, marks: 4,
    question: "A right triangle has legs $5$ and $12$. Find its hypotenuse.",
    options: [{ key: "A", text: "$15$" },{ key: "B", text: "$11$" },{ key: "C", text: "$\\sqrt{119}$" },{ key: "D", text: "$17$" },{ key: "E", text: "$13$" }],
    answer: "E", solution: "勾股：$\\sqrt{25+144}=13$。" },
  { id: "bmo-smc-m-003", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "Two sides of a triangle have length $10$ and the angle between them is $60°$. Find its area.",
    options: [{ key: "A", text: "$50\\sqrt3$" },{ key: "B", text: "$25\\sqrt3$" },{ key: "C", text: "$50$" },{ key: "D", text: "$25$" },{ key: "E", text: "$\\dfrac{25\\sqrt3}{2}$" }],
    answer: "B", solution: "$S=\\tfrac12ab\\sin C=\\tfrac12\\cdot100\\cdot\\tfrac{\\sqrt3}{2}=25\\sqrt3$。" },
  { id: "bmo-smc-m-004", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "A circle has a chord of length $16$ at distance $6$ from the centre. Find the radius.",
    options: [{ key: "A", text: "$12$" },{ key: "B", text: "$14$" },{ key: "C", text: "$10$" },{ key: "D", text: "$8$" },{ key: "E", text: "$\\sqrt{20}$" }],
    answer: "C", solution: "半弦 $8$ 与弦心距 $6$：$r=\\sqrt{64+36}=10$。" },
  { id: "bmo-smc-m-005", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "The angle subtended by an arc at the centre is $80°$. What angle does the same arc subtend at a point on the major arc?",
    options: [{ key: "A", text: "$20°$" },{ key: "B", text: "$80°$" },{ key: "C", text: "$100°$" },{ key: "D", text: "$160°$" },{ key: "E", text: "$40°$" }],
    answer: "E", solution: "圆心角是圆周角的两倍：$80°/2=40°$。" },
  { id: "bmo-smc-m-006", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "Find the area of a regular hexagon with side length $2$.",
    options: [{ key: "A", text: "$4\\sqrt3$" },{ key: "B", text: "$6\\sqrt3$" },{ key: "C", text: "$3\\sqrt3$" },{ key: "D", text: "$12$" },{ key: "E", text: "$12\\sqrt3$" }],
    answer: "B", solution: "六个边长 2 的正三角形：$6\\times\\dfrac{\\sqrt3}{4}\\times4=6\\sqrt3$。" },
  { id: "bmo-smc-m-007", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "Triangle $ABC$ is similar to triangle $DEF$ with ratio $2:3$. If the area of $ABC$ is $20$, find the area of $DEF$.",
    options: [{ key: "A", text: "$13\\tfrac13$" },{ key: "B", text: "$40$" },{ key: "C", text: "$30$" },{ key: "D", text: "$60$" },{ key: "E", text: "$45$" }],
    answer: "E", solution: "面积比为相似比平方 $4:9$：$20\\times\\tfrac94=45$。" },
  { id: "bmo-smc-m-008", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "Find the length of the space diagonal of a cube with side $4$.",
    options: [{ key: "A", text: "$4\\sqrt3$" },{ key: "B", text: "$4\\sqrt2$" },{ key: "C", text: "$8$" },{ key: "D", text: "$12$" },{ key: "E", text: "$4$" }],
    answer: "A", solution: "$\\sqrt{4^2+4^2+4^2}=4\\sqrt3$。" },
  { id: "bmo-smc-m-009", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "Find the area between two concentric circles of radii $3$ and $2$.",
    options: [{ key: "A", text: "$6\\pi$" },{ key: "B", text: "$5\\pi$" },{ key: "C", text: "$9\\pi$" },{ key: "D", text: "$13\\pi$" },{ key: "E", text: "$\\pi$" }],
    answer: "B", solution: "$9\\pi-4\\pi=5\\pi$。" },
  { id: "bmo-smc-m-010", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 3, marks: 4,
    question: "A square is inscribed in a circle of radius $r$. Find the ratio of the square's area to the circle's area.",
    options: [{ key: "A", text: "$\\dfrac{\\sqrt2}{\\pi}$" },{ key: "B", text: "$\\dfrac{1}{\\pi}$" },{ key: "C", text: "$\\dfrac{2}{\\pi}$" },{ key: "D", text: "$\\dfrac{\\pi}{4}$" },{ key: "E", text: "$\\dfrac{4}{\\pi}$" }],
    answer: "C", solution: "内接正方形对角线 $=2r$，边 $=r\\sqrt2$，面积 $2r^2$；比 $\\dfrac{2r^2}{\\pi r^2}=\\dfrac2\\pi$。" },
  { id: "bmo-smc-m-011", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "The exterior angle of a regular polygon is $24°$. How many sides does it have?",
    options: [{ key: "A", text: "$18$" },{ key: "B", text: "$15$" },{ key: "C", text: "$10$" },{ key: "D", text: "$12$" },{ key: "E", text: "$24$" }],
    answer: "B", solution: "$n=360°/24°=15$。" },
  { id: "bmo-smc-m-012", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "An equilateral triangle has side $8$. Find its height.",
    options: [{ key: "A", text: "$2\\sqrt3$" },{ key: "B", text: "$8\\sqrt3$" },{ key: "C", text: "$6$" },{ key: "D", text: "$4\\sqrt2$" },{ key: "E", text: "$4\\sqrt3$" }],
    answer: "E", solution: "高 $=\\sqrt{8^2-4^2}=\\sqrt{48}=4\\sqrt3$。" },
  { id: "bmo-smc-m-013", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 3, marks: 4,
    question: "Two tangents are drawn to a circle from an external point, touching at $P$ and $Q$. If the angle between the tangents is $50°$, find $\\angle POQ$ ($O$ the centre).",
    options: [{ key: "A", text: "$100°$" },{ key: "B", text: "$65°$" },{ key: "C", text: "$140°$" },{ key: "D", text: "$130°$" },{ key: "E", text: "$50°$" }],
    answer: "D", solution: "四边形 $OP\\,(\\text{外点})\\,Q$ 中两个切点角为 $90°$：$\\angle POQ=360°-90°-90°-50°=130°$。" },
  { id: "bmo-smc-m-014", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "A trapezium has parallel sides $6$ and $10$ and height $4$. Find its area.",
    options: [{ key: "A", text: "$36$" },{ key: "B", text: "$24$" },{ key: "C", text: "$32$" },{ key: "D", text: "$40$" },{ key: "E", text: "$64$" }],
    answer: "C", solution: "$S=\\tfrac12(6+10)\\times4=32$。" },
  { id: "bmo-smc-m-015", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 3, marks: 4,
    question: "The line $y = 2x + c$ is tangent to the circle $x^2+y^2=5$. Find the positive value of $c$.",
    options: [{ key: "A", text: "$25$" },{ key: "B", text: "$3$" },{ key: "C", text: "$5$" },{ key: "D", text: "$2\\sqrt5$" },{ key: "E", text: "$\\sqrt5$" }],
    answer: "C", solution: "圆心到直线距离等于半径：$\\dfrac{|c|}{\\sqrt{1+4}}=\\sqrt5\\Rightarrow|c|=5$。" },
  { id: "bmo-smc-m-016", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "Points $A(1,2)$ and $B(7,10)$ are given. Find the distance $AB$.",
    options: [{ key: "A", text: "$14$" },{ key: "B", text: "$\\sqrt{52}$" },{ key: "C", text: "$10$" },{ key: "D", text: "$6$" },{ key: "E", text: "$8$" }],
    answer: "C", solution: "$\\sqrt{6^2+8^2}=10$。" },
  { id: "bmo-smc-m-017", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "Find the midpoint of $A(-3, 5)$ and $B(7, -1)$.",
    options: [{ key: "A", text: "$(4, 2)$" },{ key: "B", text: "$(2, 2)$" },{ key: "C", text: "$(5, 3)$" },{ key: "D", text: "$(5, 2)$" },{ key: "E", text: "$(2, 3)$" }],
    answer: "B", solution: "中点 $\\left(\\dfrac{-3+7}{2},\\dfrac{5-1}{2}\\right)=(2,2)$。" },
  { id: "bmo-smc-m-018", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "A line has gradient $3$ and passes through $(2, 1)$. Where does it cross the $y$-axis?",
    options: [{ key: "A", text: "$(0, -6)$" },{ key: "B", text: "$(0, 7)$" },{ key: "C", text: "$(0, 5)$" },{ key: "D", text: "$(0, -1)$" },{ key: "E", text: "$(0, -5)$" }],
    answer: "E", solution: "$y=3x+c$ 过 $(2,1)$：$c=1-6=-5$。" },
  { id: "bmo-smc-m-019", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 3, marks: 4,
    question: "A cone has base radius $3$ and height $4$. Find its total surface area (base included).",
    options: [{ key: "A", text: "$36\\pi$" },{ key: "B", text: "$15\\pi$" },{ key: "C", text: "$21\\pi$" },{ key: "D", text: "$24\\pi$" },{ key: "E", text: "$9\\pi$" }],
    answer: "D", solution: "母线 $l=5$：侧面 $\\pi rl=15\\pi$，底 $9\\pi$，共 $24\\pi$。" },
  { id: "bmo-smc-m-020", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "The volume of a sphere is $36\\pi$. Find its radius.",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$3$" },{ key: "C", text: "$9$" },{ key: "D", text: "$2$" },{ key: "E", text: "$\\sqrt[3]{27\\pi}$" }],
    answer: "B", solution: "$\\tfrac43\\pi r^3=36\\pi\\Rightarrow r^3=27\\Rightarrow r=3$。" },
  { id: "bmo-smc-m-021", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 3, marks: 4,
    question: "A rectangle has perimeter $28$ and diagonal $10$. Find its area.",
    options: [{ key: "A", text: "$96$" },{ key: "B", text: "$48$" },{ key: "C", text: "$24$" },{ key: "D", text: "$40$" },{ key: "E", text: "$50$" }],
    answer: "B", solution: "$a+b=14$，$a^2+b^2=100$：$ab=\\dfrac{14^2-100}{2}=48$。" },
  { id: "bmo-smc-m-022", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 3, marks: 4,
    question: "In triangle $ABC$, $\\angle A = 90°$ and the altitude from $A$ meets $BC$ at $D$ with $BD=4$, $DC=9$. Find $AD$.",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$\\sqrt{13}$" },{ key: "C", text: "$6$" },{ key: "D", text: "$13$" },{ key: "E", text: "$36$" }],
    answer: "C", solution: "直角三角形斜边上的高：$AD^2=BD\\cdot DC=36$，$AD=6$。" },
  { id: "bmo-smc-m-023", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "How many diagonals does a regular decagon have?",
    options: [{ key: "A", text: "$30$" },{ key: "B", text: "$45$" },{ key: "C", text: "$35$" },{ key: "D", text: "$40$" },{ key: "E", text: "$25$" }],
    answer: "C", solution: "$\\dfrac{n(n-3)}{2}=\\dfrac{10\\times7}{2}=35$。" },
  { id: "bmo-smc-m-024", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 2, marks: 4,
    question: "The angles of a triangle are in the ratio $2:3:4$. Find the largest angle.",
    options: [{ key: "A", text: "$72°$" },{ key: "B", text: "$100°$" },{ key: "C", text: "$60°$" },{ key: "D", text: "$90°$" },{ key: "E", text: "$80°$" }],
    answer: "E", solution: "和 $180°$ 按 $2:3:4$ 分：$4\\times20°=80°$。" },
  { id: "bmo-smc-m-025", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 3, marks: 4,
    question: "A circle passes through the points $(0,0)$, $(6,0)$ and $(0,8)$. Find its radius.",
    options: [{ key: "A", text: "$10$" },{ key: "B", text: "$5$" },{ key: "C", text: "$4$" },{ key: "D", text: "$7$" },{ key: "E", text: "$\\sqrt{50}$" }],
    answer: "B", solution: "三点构成直角三角形（直角在原点），斜边为直径 $=\\sqrt{36+64}=10$，半径 $5$。" },
  { id: "bmo-smc-m-026", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 3, marks: 4,
    question: "An isosceles triangle has two sides of length $13$ and base $10$. Find its area.",
    options: [{ key: "A", text: "$65$" },{ key: "B", text: "$30$" },{ key: "C", text: "$56$" },{ key: "D", text: "$120$" },{ key: "E", text: "$60$" }],
    answer: "E", solution: "底边高 $=\\sqrt{169-25}=12$：$S=\\tfrac12\\times10\\times12=60$。" },
  { id: "bmo-smc-m-027", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 3, marks: 4,
    question: "The sides of a triangle are $7$, $8$, $9$. Is the largest angle acute, right or obtuse?",
    options: [{ key: "A", text: "钝角" },{ key: "B", text: "锐角（acute）——因为 $7^2+8^2 > 9^2$" },{ key: "C", text: "直角" },{ key: "D", text: "等于 $90°$" },{ key: "E", text: "无法判断" }],
    answer: "B", solution: "$49+64=113>81$：最大角的余弦为正 → 锐角三角形。" },
  { id: "bmo-smc-m-028", type: "mcq", testId: "bmo", topicId: "bmo-geometry", difficulty: 1, marks: 4,
    question: "Find the sum of the interior angles of a hexagon.",
    options: [{ key: "A", text: "$720°$" },{ key: "B", text: "$1080°$" },{ key: "C", text: "$900°$" },{ key: "D", text: "$540°$" },{ key: "E", text: "$360°$" }],
    answer: "A", solution: "$(n-2)\\times180°=720°$。" },
  { id: "bmo-smc-m-029", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "In how many ways can $3$ people be chosen from $10$?",
    options: [{ key: "A", text: "$1000$" },{ key: "B", text: "$30$" },{ key: "C", text: "$210$" },{ key: "D", text: "$120$" },{ key: "E", text: "$720$" }],
    answer: "D", solution: "$\\binom{10}{3}=\\dfrac{10\\cdot9\\cdot8}{6}=120$。" },
  { id: "bmo-smc-m-030", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 1, marks: 4,
    question: "In how many ways can $5$ different books be arranged on a shelf?",
    options: [{ key: "A", text: "$100$" },{ key: "B", text: "$720$" },{ key: "C", text: "$120$" },{ key: "D", text: "$60$" },{ key: "E", text: "$25$" }],
    answer: "C", solution: "$5!=120$。" },
  { id: "bmo-smc-m-031", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "How many distinct arrangements are there of the letters of COFFEE?",
    options: [{ key: "A", text: "$180$" },{ key: "B", text: "$360$" },{ key: "C", text: "$90$" },{ key: "D", text: "$120$" },{ key: "E", text: "$720$" }],
    answer: "A", solution: "$\\dfrac{6!}{2!\\,2!}=\\dfrac{720}{4}=180$（F 和 E 各重复两次）。" },
  { id: "bmo-smc-m-032", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "How many subsets does a set of $6$ elements have (including the empty set)?",
    options: [{ key: "A", text: "$64$" },{ key: "B", text: "$720$" },{ key: "C", text: "$32$" },{ key: "D", text: "$63$" },{ key: "E", text: "$36$" }],
    answer: "A", solution: "每个元素选或不选：$2^6=64$。" },
  { id: "bmo-smc-m-033", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "Eight people at a party all shake hands with each other exactly once. How many handshakes take place?",
    options: [{ key: "A", text: "$56$" },{ key: "B", text: "$36$" },{ key: "C", text: "$64$" },{ key: "D", text: "$28$" },{ key: "E", text: "$16$" }],
    answer: "D", solution: "$\\binom82=28$。" },
  { id: "bmo-smc-m-034", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "How many three-digit codes can be made using digits from $\\{1,2,3,4,5\\}$ without repetition?",
    options: [{ key: "A", text: "$25$" },{ key: "B", text: "$125$" },{ key: "C", text: "$60$" },{ key: "D", text: "$100$" },{ key: "E", text: "$120$" }],
    answer: "C", solution: "$5\\times4\\times3=60$。" },
  { id: "bmo-smc-m-035", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "A committee of $2$ boys and $2$ girls is chosen from $4$ boys and $5$ girls. How many committees are possible?",
    options: [{ key: "A", text: "$36$" },{ key: "B", text: "$126$" },{ key: "C", text: "$60$" },{ key: "D", text: "$120$" },{ key: "E", text: "$30$" }],
    answer: "C", solution: "$\\binom42\\times\\binom52=6\\times10=60$。" },
  { id: "bmo-smc-m-036", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "What is the minimum number of people needed to guarantee that two of them were born in the same month?",
    options: [{ key: "A", text: "$13$" },{ key: "B", text: "$366$" },{ key: "C", text: "$24$" },{ key: "D", text: "$2$" },{ key: "E", text: "$12$" }],
    answer: "A", solution: "鸽笼原理：12 个月为「笼」，13 人必有同月。" },
  { id: "bmo-smc-m-037", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "In how many ways can $5$ people be seated around a round table (rotations count as the same)?",
    options: [{ key: "A", text: "$25$" },{ key: "B", text: "$60$" },{ key: "C", text: "$120$" },{ key: "D", text: "$24$" },{ key: "E", text: "$12$" }],
    answer: "D", solution: "圆排列 $(5-1)!=24$。" },
  { id: "bmo-smc-m-038", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "A quiz has $5$ yes/no questions. How many answer patterns have at least one \"yes\"?",
    options: [{ key: "A", text: "$31$" },{ key: "B", text: "$16$" },{ key: "C", text: "$25$" },{ key: "D", text: "$10$" },{ key: "E", text: "$32$" }],
    answer: "A", solution: "总 $2^5=32$ 减去全 no 的 1 种：$31$。" },
  { id: "bmo-smc-m-039", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "How many routes are there from the bottom-left to the top-right corner of a $3\\times3$ grid of squares, moving only right or up along grid lines?",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$6$" },{ key: "C", text: "$12$" },{ key: "D", text: "$20$" },{ key: "E", text: "$27$" }],
    answer: "D", solution: "共走 6 步选 3 步向右：$\\binom63=20$。" },
  { id: "bmo-smc-m-040", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "Five different letters are placed into five addressed envelopes at random, one per envelope. In how many ways can this be done so that NO letter is in its correct envelope?",
    options: [{ key: "A", text: "$120$" },{ key: "B", text: "$44$" },{ key: "C", text: "$24$" },{ key: "D", text: "$45$" },{ key: "E", text: "$76$" }],
    answer: "B", solution: "错排数 $D_5=44$（$D_n=n!\\sum(-1)^k/k!$：$120(1-1+\\tfrac12-\\tfrac16+\\tfrac1{24}-\\tfrac1{120})=44$）。" },
  { id: "bmo-smc-m-041", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "How many ways are there to write $8$ as an ordered sum of $3$ positive integers (e.g. $1+3+4$ and $3+1+4$ count separately)?",
    options: [{ key: "A", text: "$56$" },{ key: "B", text: "$21$" },{ key: "C", text: "$10$" },{ key: "D", text: "$15$" },{ key: "E", text: "$28$" }],
    answer: "B", solution: "隔板法：8 个球间 7 个空隙放 2 块板：$\\binom72=21$。" },
  { id: "bmo-smc-m-042", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "Each of $3$ children independently chooses one of $4$ ice-cream flavours. How many outcomes are possible?",
    options: [{ key: "A", text: "$24$" },{ key: "B", text: "$64$" },{ key: "C", text: "$36$" },{ key: "D", text: "$12$" },{ key: "E", text: "$81$" }],
    answer: "B", solution: "$4^3=64$。" },
  { id: "bmo-smc-m-043", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "Ten points lie on a circle. How many chords joining two of the points are NOT sides of the inscribed decagon?",
    options: [{ key: "A", text: "$45$" },{ key: "B", text: "$35$" },{ key: "C", text: "$40$" },{ key: "D", text: "$25$" },{ key: "E", text: "$36$" }],
    answer: "B", solution: "弦总数 $\\binom{10}2=45$，减去 10 条边得 35 条对角线。" },
  { id: "bmo-smc-m-044", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "A drawer contains $8$ black and $6$ white socks. What is the minimum number of socks to take (in the dark) to guarantee a matching pair?",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$15$" },{ key: "C", text: "$7$" },{ key: "D", text: "$2$" },{ key: "E", text: "$3$" }],
    answer: "E", solution: "两种颜色为鸽笼：取 3 只必有同色。" },
  { id: "bmo-smc-m-045", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "Two distinct numbers are chosen in order from $\\{1,\\dots,6\\}$. How many ordered pairs are possible?",
    options: [{ key: "A", text: "$12$" },{ key: "B", text: "$25$" },{ key: "C", text: "$15$" },{ key: "D", text: "$30$" },{ key: "E", text: "$36$" }],
    answer: "D", solution: "$6\\times5=30$（有序、不重复）。" },
  { id: "bmo-smc-m-046", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "How many different triangles can be formed by joining $3$ of the $5$ vertices of a regular pentagon?",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$10$" },{ key: "C", text: "$60$" },{ key: "D", text: "$15$" },{ key: "E", text: "$20$" }],
    answer: "B", solution: "任 3 点不共线：$\\binom53=10$。" },
  { id: "bmo-smc-m-047", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 1, marks: 4,
    question: "How many three-digit numbers are there?",
    options: [{ key: "A", text: "$999$" },{ key: "B", text: "$899$" },{ key: "C", text: "$100$" },{ key: "D", text: "$1000$" },{ key: "E", text: "$900$" }],
    answer: "E", solution: "$100$ 到 $999$：$9\\times10\\times10=900$。" },
  { id: "bmo-smc-m-048", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "How many three-digit numbers have at least one repeated digit?",
    options: [{ key: "A", text: "$648$" },{ key: "B", text: "$252$" },{ key: "C", text: "$225$" },{ key: "D", text: "$900$" },{ key: "E", text: "$180$" }],
    answer: "B", solution: "全不同：$9\\times9\\times8=648$；$900-648=252$。" },
  { id: "bmo-smc-m-049", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "Twelve points in the plane, no three collinear. How many straight lines pass through exactly two of them?",
    options: [{ key: "A", text: "$24$" },{ key: "B", text: "$132$" },{ key: "C", text: "$66$" },{ key: "D", text: "$78$" },{ key: "E", text: "$144$" }],
    answer: "C", solution: "$\\binom{12}2=66$。" },
  { id: "bmo-smc-m-050", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "In how many ways can the letters of LEVEL be arranged?",
    options: [{ key: "A", text: "$30$" },{ key: "B", text: "$20$" },{ key: "C", text: "$60$" },{ key: "D", text: "$120$" },{ key: "E", text: "$24$" }],
    answer: "A", solution: "$\\dfrac{5!}{2!\\,2!}=30$（L、E 各两个）。" },
  { id: "bmo-smc-m-051", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "Each of $4$ questions on a test has $3$ choices. In how many ways can the test be answered (all questions answered)?",
    options: [{ key: "A", text: "$64$" },{ key: "B", text: "$27$" },{ key: "C", text: "$81$" },{ key: "D", text: "$12$" },{ key: "E", text: "$243$" }],
    answer: "C", solution: "$3^4=81$。" },
  { id: "bmo-smc-m-052", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "In how many ways can $6$ players be split into two unlabelled teams of $3$?",
    options: [{ key: "A", text: "$10$" },{ key: "B", text: "$40$" },{ key: "C", text: "$20$" },{ key: "D", text: "$15$" },{ key: "E", text: "$60$" }],
    answer: "A", solution: "$\\dfrac{\\binom63}{2}=10$（两队不区分名字，除以 2）。" },
  { id: "bmo-smc-m-053", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "At a gathering of $n\\ge2$ people, some pairs shake hands. Which statement is always true?",
    options: [{ key: "A", text: "Someone shook no hands" },{ key: "B", text: "There are two people who shook the same number of hands" },{ key: "C", text: "Everyone shook a different number of hands" },{ key: "D", text: "Someone shook everyone's hand" },{ key: "E", text: "The total number of handshakes is even" }],
    answer: "B", solution: "每人握手数 $\\in\\{0,\\dots,n-1\\}$，但 0 与 $n-1$ 不能同时出现 → 只有 $n-1$ 个可用值给 $n$ 个人：鸽笼原理保证有两人同数。" },
  { id: "bmo-smc-m-054", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 3, marks: 4,
    question: "A $4\\times4$ grid of unit squares is drawn. How many rectangles (of all sizes, including squares) does the figure contain?",
    options: [{ key: "A", text: "$36$" },{ key: "B", text: "$70$" },{ key: "C", text: "$100$" },{ key: "D", text: "$16$" },{ key: "E", text: "$1296$" }],
    answer: "C", solution: "矩形由 5 条横线选 2、5 条竖线选 2 决定：$\\binom52^2=100$。" },
  { id: "bmo-smc-m-055", type: "mcq", testId: "bmo", topicId: "bmo-combinatorics", difficulty: 2, marks: 4,
    question: "From the digits $1,2,3,4$ (each used exactly once) how many four-digit numbers greater than $3000$ can be formed?",
    options: [{ key: "A", text: "$24$" },{ key: "B", text: "$8$" },{ key: "C", text: "$18$" },{ key: "D", text: "$6$" },{ key: "E", text: "$12$" }],
    answer: "E", solution: "首位为 3 或 4（2 种），其余 $3!=6$：$2\\times6=12$。" },
  { id: "bmo-smc-m-056", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 3, marks: 4,
    question: "Find the remainder when $2^{2026}$ is divided by $7$.",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$1$" },{ key: "C", text: "$3$" },{ key: "D", text: "$4$" },{ key: "E", text: "$2$" }],
    answer: "E", solution: "$2^3=8\\equiv1\\pmod7$，故幂次按 3 循环。$2026=3\\times675+1$，所以 $2^{2026}=2\\cdot(2^3)^{675}\\equiv2\\pmod7$。" },
  { id: "bmo-smc-m-057", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "Find the sum of the digits of $2^{10}$.",
    options: [{ key: "A", text: "$10$" },{ key: "B", text: "$6$" },{ key: "C", text: "$8$" },{ key: "D", text: "$7$" },{ key: "E", text: "$16$" }],
    answer: "D", solution: "$2^{10}=1024$：$1+0+2+4=7$。" },
  { id: "bmo-smc-m-058", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 3, marks: 4,
    question: "How many integers from $1$ to $20$ are coprime to $20$?",
    options: [{ key: "A", text: "$12$" },{ key: "B", text: "$10$" },{ key: "C", text: "$8$" },{ key: "D", text: "$4$" },{ key: "E", text: "$6$" }],
    answer: "C", solution: "$\\varphi(20)=20\\times\\tfrac12\\times\\tfrac45=8$：即 $1,3,7,9,11,13,17,19$。" },
  { id: "bmo-smc-m-059", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 1, marks: 4,
    question: "Find the sum of the digits $1+2+\\cdots+9$.",
    options: [{ key: "A", text: "$44$" },{ key: "B", text: "$36$" },{ key: "C", text: "$45$" },{ key: "D", text: "$50$" },{ key: "E", text: "$55$" }],
    answer: "C", solution: "$\\dfrac{9\\times10}{2}=45$。" },
  { id: "bmo-smc-m-060", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "What is the smallest perfect number (a number equal to the sum of its proper divisors)?",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$8$" },{ key: "C", text: "$28$" },{ key: "D", text: "$12$" },{ key: "E", text: "$6$" }],
    answer: "E", solution: "$6=1+2+3$。下一个是 $28$。" },
  { id: "bmo-smc-m-061", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 1, marks: 4,
    question: "Find the least common multiple of $12$ and $18$.",
    options: [{ key: "A", text: "$216$" },{ key: "B", text: "$54$" },{ key: "C", text: "$36$" },{ key: "D", text: "$72$" },{ key: "E", text: "$6$" }],
    answer: "C", solution: "$\\mathrm{lcm}=\\dfrac{12\\times18}{\\gcd}= \\dfrac{216}{6}=36$。" },
  { id: "bmo-smc-m-062", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 3, marks: 4,
    question: "Is the sum $1+2+\\cdots+2026$ odd or even?",
    options: [{ key: "A", text: "等于 0" },{ key: "B", text: "偶数（even）" },{ key: "C", text: "取决于排列顺序" },{ key: "D", text: "奇数（odd）" },{ key: "E", text: "无法确定" }],
    answer: "D", solution: "和 $=\\dfrac{2026\\times2027}{2}=1013\\times2027$：奇 × 奇 = 奇。" },
  { id: "bmo-smc-m-063", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "How many integers from $1$ to $100$ are divisible by $3$ or $5$?",
    options: [{ key: "A", text: "$20$" },{ key: "B", text: "$33$" },{ key: "C", text: "$47$" },{ key: "D", text: "$50$" },{ key: "E", text: "$53$" }],
    answer: "C", solution: "容斥：$33+20-6=47$。" },
  { id: "bmo-smc-m-064", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 3, marks: 4,
    question: "Find the last two digits of $7^{4}$.",
    options: [{ key: "A", text: "$07$" },{ key: "B", text: "$43$" },{ key: "C", text: "$21$" },{ key: "D", text: "$01$" },{ key: "E", text: "$49$" }],
    answer: "D", solution: "$7^4=2401$：末两位 $01$（因此 $7^{4k}$ 末两位恒为 01——周期性）。" },
  { id: "bmo-smc-m-065", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "Which of these primes can be written as the sum of two squares?",
    options: [{ key: "A", text: "$19$" },{ key: "B", text: "$23$" },{ key: "C", text: "$13$" },{ key: "D", text: "$11$" },{ key: "E", text: "$7$" }],
    answer: "C", solution: "$13=4+9=2^2+3^2$。（定理：奇素数可表为两平方和 ⟺ $p\\equiv1\\pmod4$；$7,11,19,23$ 均 $\\equiv3$。）" },
  { id: "bmo-smc-m-066", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "Find the remainder when $10^6$ is divided by $9$.",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$1$" },{ key: "C", text: "$3$" },{ key: "D", text: "$6$" },{ key: "E", text: "$9$" }],
    answer: "B", solution: "$10\\equiv1\\pmod9$，故任意次幂余 1（数字和法则的根源）。" },
  { id: "bmo-smc-m-067", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 1, marks: 4,
    question: "What is the largest proper divisor of $64$?",
    options: [{ key: "A", text: "$63$" },{ key: "B", text: "$32$" },{ key: "C", text: "$16$" },{ key: "D", text: "$4$" },{ key: "E", text: "$8$" }],
    answer: "B", solution: "$64=2^6$，最大真因数 $=64/2=32$。" },
  { id: "bmo-smc-m-068", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "How many primes less than $50$ have units digit $7$?",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$6$" },{ key: "C", text: "$2$" },{ key: "D", text: "$5$" },{ key: "E", text: "$3$" }],
    answer: "A", solution: "$7,17,37,47$（27 非素）。" },
  { id: "bmo-smc-m-069", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 3, marks: 4,
    question: "Find the smallest positive integer with exactly $15$ positive divisors.",
    options: [{ key: "A", text: "$120$" },{ key: "B", text: "$60$" },{ key: "C", text: "$144$" },{ key: "D", text: "$96$" },{ key: "E", text: "$210$" }],
    answer: "C", solution: "$15=3\\times5$ 或 $15$：形如 $p^{14}$ 或 $p^4q^2$。最小 $2^43^2=144$。" },
  { id: "bmo-smc-m-070", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "What is the $10$th prime number?",
    options: [{ key: "A", text: "$23$" },{ key: "B", text: "$27$" },{ key: "C", text: "$31$" },{ key: "D", text: "$37$" },{ key: "E", text: "$29$" }],
    answer: "E", solution: "$2,3,5,7,11,13,17,19,23,29$。" },
  { id: "bmo-smc-m-071", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 3, marks: 4,
    question: "$1013$ is prime. What is the remainder when $1013$ is divided by $4$, and can $1013$ be written as a sum of two squares?",
    options: [{ key: "A", text: "余 $3$；可以" },{ key: "B", text: "余 $1$；可以（$1013 = 22^2 + 23^2$）" },{ key: "C", text: "余 $3$；不可以" },{ key: "D", text: "余 $1$；不可以" },{ key: "E", text: "余 $2$；可以" }],
    answer: "B", solution: "$1013=4\\times253+1$。$p\\equiv1\\pmod4$ 的素数必可表为两平方和：$484+529=1013$ ✓。" },
  { id: "bmo-smc-m-072", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 3, marks: 4,
    question: "Find $\\gcd(10!,\\;2^{10})$.",
    options: [{ key: "A", text: "$256$" },{ key: "B", text: "$512$" },{ key: "C", text: "$128$" },{ key: "D", text: "$1024$" },{ key: "E", text: "$64$" }],
    answer: "A", solution: "$10!$ 中 2 的幂次 $=5+2+1=8$：$\\gcd=2^8=256$。" },
  { id: "bmo-smc-m-073", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "How many digits does $2026^2$ have?",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$14$" },{ key: "C", text: "$8$" },{ key: "D", text: "$6$" },{ key: "E", text: "$4$" }],
    answer: "A", solution: "$2026^2=4104676$：7 位。（估算：$2\\times10^3$ 平方 $\\approx4\\times10^6$。）" },
  { id: "bmo-smc-m-074", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 2, marks: 4,
    question: "Three consecutive odd primes are $3, 5, 7$. Their sum is divisible by",
    options: [{ key: "A", text: "只有 $3$" },{ key: "B", text: "$3$ 和 $5$" },{ key: "C", text: "都不是" },{ key: "D", text: "只有 $5$" },{ key: "E", text: "$7$" }],
    answer: "B", solution: "和 $=15=3\\times5$。" },
  { id: "bmo-smc-m-075", type: "mcq", testId: "bmo", topicId: "bmo-number", difficulty: 3, marks: 4,
    question: "Two positive integers differ by $2$ and their squares differ by $72$. Find the larger one.",
    options: [{ key: "A", text: "$20$" },{ key: "B", text: "$36$" },{ key: "C", text: "$17$" },{ key: "D", text: "$18$" },{ key: "E", text: "$19$" }],
    answer: "E", solution: "$a^2-b^2=(a+b)(a-b)=2(a+b)=72\\Rightarrow a+b=36$，$a-b=2$：$a=19$。" },
  { id: "bmo-smc-m-076", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "If $a+b=7$ and $a^2+b^2=25$, find $2ab$.",
    options: [{ key: "A", text: "$48$" },{ key: "B", text: "$12$" },{ key: "C", text: "$18$" },{ key: "D", text: "$49$" },{ key: "E", text: "$24$" }],
    answer: "E", solution: "$(a+b)^2=a^2+2ab+b^2$：$49=25+2ab\\Rightarrow2ab=24$。" },
  { id: "bmo-smc-m-077", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "Evaluate $\\dfrac{1}{1\\cdot2}+\\dfrac{1}{2\\cdot3}+\\cdots+\\dfrac{1}{100\\cdot101}$.",
    options: [{ key: "A", text: "$\\dfrac{101}{100}$" },{ key: "B", text: "$\\dfrac{1}{101}$" },{ key: "C", text: "$\\dfrac{100}{101}$" },{ key: "D", text: "$\\dfrac{99}{100}$" },{ key: "E", text: "$1$" }],
    answer: "C", solution: "裂项：$\\dfrac1{k(k+1)}=\\dfrac1k-\\dfrac1{k+1}$，叠缩得 $1-\\dfrac1{101}=\\dfrac{100}{101}$。" },
  { id: "bmo-smc-m-078", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "How many real solutions does $x^4-5x^2+4=0$ have?",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$0$" },{ key: "C", text: "$3$" },{ key: "D", text: "$2$" },{ key: "E", text: "$1$" }],
    answer: "A", solution: "令 $u=x^2$：$u=1,4$ → $x=\\pm1,\\pm2$：4 个。" },
  { id: "bmo-smc-m-079", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "The sequence $7, 14, 21, \\dots$ lists multiples of $7$. Is $2026$ a term?",
    options: [{ key: "A", text: "是，第 2026 项" },{ key: "B", text: "是，第 289 项" },{ key: "C", text: "不是——$2026=7\\times289+3$" },{ key: "D", text: "是，第 290 项" },{ key: "E", text: "不是，但 $2027$ 是" }],
    answer: "C", solution: "$2026\\div7=289$ 余 $3$：不是 7 的倍数。" },
  { id: "bmo-smc-m-080", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "Evaluate $1^3+2^3+3^3+4^3+5^3$.",
    options: [{ key: "A", text: "$152$" },{ key: "B", text: "$225$" },{ key: "C", text: "$100$" },{ key: "D", text: "$125$" },{ key: "E", text: "$375$" }],
    answer: "B", solution: "$\\sum k^3=\\left(\\sum k\\right)^2=15^2=225$。" },
  { id: "bmo-smc-m-081", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Evaluate $1+2+4+8+\\cdots+512$.",
    options: [{ key: "A", text: "$1024$" },{ key: "B", text: "$1023$" },{ key: "C", text: "$2047$" },{ key: "D", text: "$511$" },{ key: "E", text: "$1022$" }],
    answer: "B", solution: "等比求和 $2^{10}-1=1023$。" },
  { id: "bmo-smc-m-082", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Solve $x^2 = x+6$. What is the sum of the solutions?",
    options: [{ key: "A", text: "$-1$" },{ key: "B", text: "$1$" },{ key: "C", text: "$0$" },{ key: "D", text: "$6$" },{ key: "E", text: "$5$" }],
    answer: "B", solution: "$x^2-x-6=0$：韦达 $\\alpha+\\beta=1$（解为 $3,-2$）。" },
  { id: "bmo-smc-m-083", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "If $\\log_{10} x = 2$, find $x$.",
    options: [{ key: "A", text: "$20$" },{ key: "B", text: "$1000$" },{ key: "C", text: "$100$" },{ key: "D", text: "$2$" },{ key: "E", text: "$0.01$" }],
    answer: "C", solution: "$x=10^2=100$。" },
  { id: "bmo-smc-m-084", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Between which two consecutive integers does $\\log_2 10$ lie?",
    options: [{ key: "A", text: "$4$ 与 $5$" },{ key: "B", text: "$1$ 与 $2$" },{ key: "C", text: "$3$ 与 $4$" },{ key: "D", text: "$2$ 与 $3$" },{ key: "E", text: "$5$ 与 $6$" }],
    answer: "C", solution: "$2^3=8<10<16=2^4$。" },
  { id: "bmo-smc-m-085", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 1, marks: 4,
    question: "Evaluate $7^2 - 3^2$ using the difference of two squares.",
    options: [{ key: "A", text: "$13$" },{ key: "B", text: "$16$" },{ key: "C", text: "$46$" },{ key: "D", text: "$40$" },{ key: "E", text: "$58$" }],
    answer: "D", solution: "$(7-3)(7+3)=4\\times10=40$。" },
  { id: "bmo-smc-m-086", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "Two numbers have sum $5$ and product $6$. Find the larger number.",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$3$" },{ key: "C", text: "$6$" },{ key: "D", text: "$5$" },{ key: "E", text: "$4$" }],
    answer: "B", solution: "$t^2-5t+6=0$：$t=2,3$。" },
  { id: "bmo-smc-m-087", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 2, marks: 4,
    question: "For how many integers $x$ is $x^2 \\le 10$?",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$5$" },{ key: "C", text: "$6$" },{ key: "D", text: "$3$" },{ key: "E", text: "$7$" }],
    answer: "E", solution: "$-3\\le x\\le3$：7 个（含 0）。" },
  { id: "bmo-smc-m-088", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "Evaluate $1+2+\\cdots+2025$.",
    options: [{ key: "A", text: "$2049300$" },{ key: "B", text: "$2050300$" },{ key: "C", text: "$2052351$" },{ key: "D", text: "$2051325$" },{ key: "E", text: "$2026\\times2025$" }],
    answer: "D", solution: "$\\dfrac{2025\\times2026}{2}=2025\\times1013=2051325$。" },
  { id: "bmo-smc-m-089", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 3, marks: 4,
    question: "If $f(x)=x^2-4x+7$, find the minimum value of $f(f(x))$ over all real $x$.",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$4$" },{ key: "C", text: "$10$" },{ key: "D", text: "$19$" },{ key: "E", text: "$3$" }],
    answer: "B", solution: "$f(x)=(x-2)^2+3$ 的值域是 $[3,\\infty)$。而 $f(t)$ 的顶点在 $t=2$，故在 $t\\ge3$ 上单调递增：最小值在 $t=3$ 处取得，$f(3)=9-12+7=4$。" },
  { id: "bmo-smc-m-090", type: "mcq", testId: "bmo", topicId: "bmo-algebra", difficulty: 1, marks: 4,
    question: "If $3^x = 81$, find $x$.",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$4$" },{ key: "C", text: "$27$" },{ key: "D", text: "$3$" },{ key: "E", text: "$5$" }],
    answer: "B", solution: "$81=3^4$。" },
];
