// BPhO S1 主批 —— 圆周引力/能量动量/转动/振动波/电磁/热学/现代与估算。原创，生成时逐题 sympy/数值断言。
import type { MCQQuestion } from "./types";

export const BPHO_S1_MAIN: MCQQuestion[] = [
  { id: "bpho-s1-001", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A conical pendulum consists of a mass on a light string of length $\\ell$, the string making a constant angle $\\theta$ with the vertical. Find the period of the circular motion.",
    options: [{ key: "A", text: "$2\\pi\\sqrt{\\dfrac{\\ell}{g}}$" },{ key: "B", text: "$2\\pi\\sqrt{\\dfrac{\\ell\\tan\\theta}{g}}$" },{ key: "C", text: "$2\\pi\\sqrt{\\dfrac{\\ell\\cos\\theta}{g}}$" },{ key: "D", text: "$2\\pi\\sqrt{\\dfrac{\\ell\\sin\\theta}{g}}$" },{ key: "E", text: "$2\\pi\\sqrt{\\dfrac{\\ell}{g\\cos\\theta}}$" }],
    answer: "C", solution: "Resolve: $T\\cos\\theta=mg$, $T\\sin\\theta=m\\omega^2 r$ with $r=\\ell\\sin\\theta$. Dividing: $\\tan\\theta=\\omega^2\\ell\\sin\\theta/g$, so $\\omega^2=g/(\\ell\\cos\\theta)$ and $T_{\\mathrm{period}}=2\\pi\\sqrt{\\ell\\cos\\theta/g}$." },
  { id: "bpho-s1-002", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 1, marks: 3,
    question: "Satellite P orbits a planet in a circular orbit of radius $R$; satellite Q orbits at radius $4R$. Find the ratio of orbital speeds $v_Q/v_P$.",
    options: [{ key: "A", text: "$\\dfrac{1}{4}$" },{ key: "B", text: "$\\dfrac{1}{\\sqrt{2}}$" },{ key: "C", text: "$2$" },{ key: "D", text: "$\\dfrac{1}{2}$" },{ key: "E", text: "$\\dfrac{1}{8}$" }],
    answer: "D", solution: "For circular orbits $\\dfrac{GMm}{r^2}=\\dfrac{mv^2}{r}$ so $v=\\sqrt{GM/r}\\propto r^{-1/2}$. Ratio $=\\sqrt{R/4R}=1/2$." },
  { id: "bpho-s1-003", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "Using $g=10\\ \\mathrm{m\\,s^{-2}}$ at the Earth's surface and Earth radius $R=6.4\\times10^6$ m, estimate the orbital radius of a geostationary satellite (period $24$ h). [Hint: $GM=gR^2$.]",
    options: [{ key: "A", text: "$\\approx 4.2\\times10^7$ m" },{ key: "B", text: "$\\approx 3.6\\times10^7$ m" },{ key: "C", text: "$\\approx 8.5\\times10^7$ m" },{ key: "D", text: "$\\approx 1.6\\times10^8$ m" },{ key: "E", text: "$\\approx 6.4\\times10^6$ m" }],
    answer: "A", solution: "Equate gravity to centripetal: $\\dfrac{gR^2}{r^2}=\\dfrac{4\\pi^2 r}{T^2}$, so $r=\\left(\\dfrac{gR^2T^2}{4\\pi^2}\\right)^{1/3}=\\left(\\dfrac{10\\times(6.4\\times10^6)^2\\times86400^2}{4\\pi^2}\\right)^{1/3}\\approx4.2\\times10^7$ m." },
  { id: "bpho-s1-004", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A ball on a string moves in a vertical circle of radius $r$. At the top its speed is the minimum needed to keep the string taut. Find the tension at the bottom of the circle (mass $m$).",
    options: [{ key: "A", text: "$4mg$" },{ key: "B", text: "$mg$" },{ key: "C", text: "$6mg$" },{ key: "D", text: "$5mg$" },{ key: "E", text: "$3mg$" }],
    answer: "C", solution: "Top: $v_{\\mathrm{top}}^2=gr$. Energy to bottom: $v_{\\mathrm{bot}}^2=v_{\\mathrm{top}}^2+4gr=5gr$. Bottom: $T-mg=\\dfrac{mv_{\\mathrm{bot}}^2}{r}=5mg$, so $T=6mg$." },
  { id: "bpho-s1-005", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "A car rounds a flat bend of radius $45$ m. The coefficient of friction between tyres and road is $0.5$ and $g=10\\ \\mathrm{m\\,s^{-2}}$. Find the maximum speed at which the bend can be taken.",
    options: [{ key: "A", text: "$10\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$22.5\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$15\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$30\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$12\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "C", solution: "Friction provides centripetal force: $\\mu mg = \\dfrac{mv^2}{r}$, so $v=\\sqrt{\\mu g r}=\\sqrt{0.5\\times10\\times45}=15\\ \\mathrm{m\\,s^{-1}}$." },
  { id: "bpho-s1-006", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "Planet A orbits a star at four times the orbital radius of planet B (both circular). Find the ratio of orbital periods $T_A/T_B$.",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$8$" },{ key: "C", text: "$16$" },{ key: "D", text: "$4$" },{ key: "E", text: "$\\sqrt{2}$" }],
    answer: "B", solution: "Kepler's third law: $T^2\\propto r^3$, so $T_A/T_B=(4)^{3/2}=8$." },
  { id: "bpho-s1-007", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "Find the ratio of the escape speed from a planet's surface to the speed of a satellite in a circular orbit just above the surface.",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$\\sqrt{2}$" },{ key: "C", text: "$1$" },{ key: "D", text: "$4$" },{ key: "E", text: "$\\dfrac{1}{\\sqrt{2}}$" }],
    answer: "B", solution: "Escape: $\\tfrac12mv_e^2=\\dfrac{GMm}{R}$ gives $v_e=\\sqrt{2GM/R}$. Orbit: $v_o=\\sqrt{GM/R}$. Ratio $=\\sqrt2$." },
  { id: "bpho-s1-008", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A Ferris wheel of radius $10$ m rotates at constant angular speed. At what angular speed would a rider at the top momentarily feel weightless? ($g=10\\ \\mathrm{m\\,s^{-2}}$)",
    options: [{ key: "A", text: "$1.0\\ \\mathrm{rad\\,s^{-1}}$" },{ key: "B", text: "$\\sqrt{10}\\ \\mathrm{rad\\,s^{-1}}$" },{ key: "C", text: "$0.5\\ \\mathrm{rad\\,s^{-1}}$" },{ key: "D", text: "$10\\ \\mathrm{rad\\,s^{-1}}$" },{ key: "E", text: "$2.0\\ \\mathrm{rad\\,s^{-1}}$" }],
    answer: "A", solution: "Weightless at top when gravity alone supplies the centripetal force: $g=\\omega^2 r$, so $\\omega=\\sqrt{g/r}=\\sqrt{10/10}=1.0\\ \\mathrm{rad\\,s^{-1}}$." },
  { id: "bpho-s1-009", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A coin rests on a turntable at $0.10$ m from the axis. The coefficient of friction is $0.4$ and $g=10\\ \\mathrm{m\\,s^{-2}}$. Find the maximum angular speed before the coin slips.",
    options: [{ key: "A", text: "$\\sqrt{40}\\approx6.3\\ \\mathrm{rad\\,s^{-1}}$" },{ key: "B", text: "$4.0\\ \\mathrm{rad\\,s^{-1}}$" },{ key: "C", text: "$\\sqrt{20}\\approx4.5\\ \\mathrm{rad\\,s^{-1}}$" },{ key: "D", text: "$\\sqrt{4}=2.0\\ \\mathrm{rad\\,s^{-1}}$" },{ key: "E", text: "$40\\ \\mathrm{rad\\,s^{-1}}$" }],
    answer: "A", solution: "Friction supplies centripetal force: $\\mu g=\\omega^2 r$, so $\\omega=\\sqrt{\\mu g/r}=\\sqrt{0.4\\times10/0.1}=\\sqrt{40}\\approx6.3\\ \\mathrm{rad\\,s^{-1}}$." },
  { id: "bpho-s1-010", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 1, marks: 3,
    question: "At what height above the Earth's surface (radius $R$) is the gravitational field strength one quarter of its surface value?",
    options: [{ key: "A", text: "$2R$" },{ key: "B", text: "$3R$" },{ key: "C", text: "$R/4$" },{ key: "D", text: "$R$" },{ key: "E", text: "$R/2$" }],
    answer: "D", solution: "$g\\propto1/r^2$: quarter strength at $r=2R$ from the centre, i.e. height $h=r-R=R$." },
  { id: "bpho-s1-011", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "A car drives over the crest of a humpback bridge of radius of curvature $40$ m. At what speed do the wheels momentarily lose contact with the road? ($g=10\\ \\mathrm{m\\,s^{-2}}$)",
    options: [{ key: "A", text: "$40\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$4\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$10\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$400\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$20\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "E", solution: "Contact lost when gravity alone provides the centripetal force: $mg=\\dfrac{mv^2}{r}$, $v=\\sqrt{gr}=\\sqrt{400}=20\\ \\mathrm{m\\,s^{-1}}$." },
  { id: "bpho-s1-012", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A comet moves in an elliptical orbit with perihelion (closest) distance $r_1$ and aphelion (farthest) distance $r_2$ from the Sun. Find the ratio of its speed at perihelion to its speed at aphelion.",
    options: [{ key: "A", text: "$\\dfrac{r_2}{r_1}$" },{ key: "B", text: "$\\dfrac{r_1}{r_2}$" },{ key: "C", text: "$\\left(\\dfrac{r_2}{r_1}\\right)^2$" },{ key: "D", text: "$1$" },{ key: "E", text: "$\\sqrt{\\dfrac{r_2}{r_1}}$" }],
    answer: "A", solution: "At the extreme points velocity is perpendicular to the radius, so conservation of angular momentum gives $mv_1r_1=mv_2r_2$, hence $v_1/v_2=r_2/r_1$." },
  { id: "bpho-s1-013", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "For a satellite in a circular orbit, let $E_k$ be its kinetic energy and $E$ its total mechanical energy (taking potential energy zero at infinity). Which relation holds?",
    options: [{ key: "A", text: "$E=-E_k$" },{ key: "B", text: "$E=2E_k$" },{ key: "C", text: "$E=-2E_k$" },{ key: "D", text: "$E=0$" },{ key: "E", text: "$E=E_k$" }],
    answer: "A", solution: "For a circular orbit $E_k=\\dfrac{GMm}{2r}$ and $E_p=-\\dfrac{GMm}{r}=-2E_k$. Total $E=E_k+E_p=-E_k$: the total energy is negative and equal in magnitude to the kinetic energy (virial theorem)." },
  { id: "bpho-s1-014", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "If a planet had the same uniform density as Earth but twice the radius, its surface gravitational field strength would be",
    options: [{ key: "A", text: "four times Earth's" },{ key: "B", text: "twice Earth's" },{ key: "C", text: "eight times Earth's" },{ key: "D", text: "the same as Earth's" },{ key: "E", text: "half Earth's" }],
    answer: "B", solution: "$g=\\dfrac{GM}{R^2}=\\dfrac{G\\rho\\frac43\\pi R^3}{R^2}=\\dfrac43\\pi G\\rho R\\propto R$ at fixed density, so doubling $R$ doubles $g$." },
  { id: "bpho-s1-015", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A ball of mass $m$ moving at speed $v$ makes a head-on elastic collision with a stationary ball of mass $2m$. Find the speed of the $2m$ ball after the collision.",
    options: [{ key: "A", text: "$\\dfrac{3v}{4}$" },{ key: "B", text: "$\\dfrac{v}{3}$" },{ key: "C", text: "$\\dfrac{v}{2}$" },{ key: "D", text: "$\\dfrac{2v}{3}$" },{ key: "E", text: "$v$" }],
    answer: "D", solution: "Elastic head-on formulas: $v_2'=\\dfrac{2m_1}{m_1+m_2}v=\\dfrac{2m}{3m}v=\\dfrac{2v}{3}$ (and $v_1'=-v/3$). Check: momentum $m v = m(-v/3)+2m(2v/3)=v m$ ✓." },
  { id: "bpho-s1-016", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A lump of clay of mass $2$ kg moving at speed $v$ hits and sticks to a stationary block of mass $3$ kg. What fraction of the initial kinetic energy is lost in the collision?",
    options: [{ key: "A", text: "$\\dfrac{3}{5}$" },{ key: "B", text: "$\\dfrac{2}{5}$" },{ key: "C", text: "$\\dfrac{3}{4}$" },{ key: "D", text: "$\\dfrac{1}{2}$" },{ key: "E", text: "$\\dfrac{9}{25}$" }],
    answer: "A", solution: "Common speed $=\\dfrac{2v}{5}$. Fraction remaining $=\\dfrac{\\frac12\\cdot5\\cdot(2v/5)^2}{\\frac12\\cdot2v^2}=\\dfrac{2}{5}$, so fraction lost $=\\dfrac{3}{5}$. In general lost fraction $=\\dfrac{M}{m+M}$." },
  { id: "bpho-s1-017", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A $10$ g bullet travelling at $400\\ \\mathrm{m\\,s^{-1}}$ embeds itself in a $1.99$ kg block hanging from long strings (a ballistic pendulum). To what height does the block rise? ($g=10\\ \\mathrm{m\\,s^{-2}}$)",
    options: [{ key: "A", text: "$0.10$ m" },{ key: "B", text: "$0.40$ m" },{ key: "C", text: "$0.20$ m" },{ key: "D", text: "$2.0$ m" },{ key: "E", text: "$8.0$ m" }],
    answer: "C", solution: "Momentum: $0.01\\times400=2.00\\times v$, so $v=2.0\\ \\mathrm{m\\,s^{-1}}$. Then energy: $h=\\dfrac{v^2}{2g}=\\dfrac{4}{20}=0.20$ m. (Do NOT equate bullet KE to $mgh$ — most KE is lost in embedding.)" },
  { id: "bpho-s1-018", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "A $1$ kg trolley moving at $6\\ \\mathrm{m\\,s^{-1}}$ approaches a stationary $2$ kg trolley carrying an ideal spring buffer. Find the elastic energy stored in the spring at the moment of maximum compression.",
    options: [{ key: "A", text: "$12$ J" },{ key: "B", text: "$18$ J" },{ key: "C", text: "$6$ J" },{ key: "D", text: "$9$ J" },{ key: "E", text: "$0$ J" }],
    answer: "A", solution: "At maximum compression both move together at $v=\\dfrac{1\\times6}{3}=2\\ \\mathrm{m\\,s^{-1}}$. Stored energy $=\\text{KE}_i-\\text{KE}_{\\text{common}}=\\dfrac12(1)(36)-\\dfrac12(3)(4)=18-6=12$ J." },
  { id: "bpho-s1-019", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A car of mass $m$ climbs a slope of angle $\\theta$ at constant speed $v$, with negligible resistance. Find the power delivered by the engine.",
    options: [{ key: "A", text: "$mgv$" },{ key: "B", text: "$\\dfrac{mgv}{\\sin\\theta}$" },{ key: "C", text: "$mgv\\tan\\theta$" },{ key: "D", text: "$mgv\\cos\\theta$" },{ key: "E", text: "$mgv\\sin\\theta$" }],
    answer: "E", solution: "At constant speed the engine force balances the weight component along the slope: $F=mg\\sin\\theta$. Power $=Fv=mgv\\sin\\theta$." },
  { id: "bpho-s1-020", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "Water falls $420$ m down a waterfall. If all the gravitational potential energy is converted to internal energy of the water ($c=4200\\ \\mathrm{J\\,kg^{-1}\\,K^{-1}}$, $g=10\\ \\mathrm{m\\,s^{-2}}$), find the temperature rise.",
    options: [{ key: "A", text: "$0.1$ K" },{ key: "B", text: "$10$ K" },{ key: "C", text: "$4.2$ K" },{ key: "D", text: "$1.0$ K" },{ key: "E", text: "$0.42$ K" }],
    answer: "D", solution: "Per kilogram: $gh=c\\,\\Delta T$, so $\\Delta T=\\dfrac{10\\times420}{4200}=1.0$ K. (Mass cancels.)" },
  { id: "bpho-s1-021", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "A cannon of mass $1000$ kg, free to roll, fires a $10$ kg shell horizontally at $400\\ \\mathrm{m\\,s^{-1}}$ (relative to the ground). Find the recoil speed of the cannon.",
    options: [{ key: "A", text: "$2\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$40\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$4\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$0.4\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$8\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "C", solution: "Momentum conservation from rest: $1000v=10\\times400$, so $v=4\\ \\mathrm{m\\,s^{-1}}$." },
  { id: "bpho-s1-022", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A stationary object explodes into two fragments with masses in the ratio $1:2$. What fraction of the total kinetic energy released is carried by the lighter fragment?",
    options: [{ key: "A", text: "$\\dfrac{2}{3}$" },{ key: "B", text: "$\\dfrac{2}{5}$" },{ key: "C", text: "$\\dfrac{1}{2}$" },{ key: "D", text: "$\\dfrac{4}{9}$" },{ key: "E", text: "$\\dfrac{1}{3}$" }],
    answer: "A", solution: "Equal and opposite momenta $p$: $E_k=\\dfrac{p^2}{2m}\\propto\\dfrac1m$. Energies are in ratio $2:1$ (lighter gets more), so the lighter fragment carries $\\dfrac{2}{3}$ of the total." },
  { id: "bpho-s1-023", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A $60$ kg person walks $3.0$ m (relative to the boat) from one end of a $120$ kg boat towards the other end. Water resistance is negligible. How far does the boat move (relative to the water)?",
    options: [{ key: "A", text: "$3.0$ m" },{ key: "B", text: "$0.5$ m" },{ key: "C", text: "$1.5$ m" },{ key: "D", text: "$1.0$ m" },{ key: "E", text: "$2.0$ m" }],
    answer: "D", solution: "Centre of mass is fixed. If the boat moves $x$ backwards, the person moves $3-x$ forwards relative to water: $60(3-x)=120x$, so $180=180x+60x\\Rightarrow x=1.0$ m." },
  { id: "bpho-s1-024", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A $0.20$ kg ball hits a wall horizontally at $20\\ \\mathrm{m\\,s^{-1}}$ and rebounds along the same line at $15\\ \\mathrm{m\\,s^{-1}}$. The contact lasts $0.050$ s. Find the average force on the ball.",
    options: [{ key: "A", text: "$140$ N" },{ key: "B", text: "$20$ N" },{ key: "C", text: "$70$ N" },{ key: "D", text: "$100$ N" },{ key: "E", text: "$60$ N" }],
    answer: "A", solution: "Impulse $=\\Delta p=0.20\\times(20+15)=7.0\\ \\mathrm{kg\\,m\\,s^{-1}}$ (velocity reverses). $F=\\Delta p/\\Delta t=7.0/0.050=140$ N." },
  { id: "bpho-s1-025", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "A ball is dropped from height $h$ and rebounds to height $0.64h$. Find the coefficient of restitution with the floor.",
    options: [{ key: "A", text: "$0.9$" },{ key: "B", text: "$0.4$" },{ key: "C", text: "$0.8$" },{ key: "D", text: "$0.64$" },{ key: "E", text: "$0.36$" }],
    answer: "C", solution: "$e=\\dfrac{v_{\\text{after}}}{v_{\\text{before}}}=\\sqrt{\\dfrac{h_2}{h_1}}=\\sqrt{0.64}=0.8$ (since $v\\propto\\sqrt h$)." },
  { id: "bpho-s1-026", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "A spring of stiffness $200\\ \\mathrm{N\\,m^{-1}}$ is stretched from an extension of $0.10$ m to an extension of $0.30$ m. Find the work done.",
    options: [{ key: "A", text: "$9.0$ J" },{ key: "B", text: "$16$ J" },{ key: "C", text: "$8.0$ J" },{ key: "D", text: "$1.0$ J" },{ key: "E", text: "$4.0$ J" }],
    answer: "C", solution: "$W=\\tfrac12k(x_2^2-x_1^2)=\\tfrac12\\times200\\times(0.09-0.01)=8.0$ J — NOT $\\tfrac12k(x_2-x_1)^2=4$ J, the classic trap." },
  { id: "bpho-s1-027", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "A projectile is launched at $60°$ to the horizontal. Find the ratio of its kinetic energy at the top of its flight to its initial kinetic energy.",
    options: [{ key: "A", text: "$\\dfrac{1}{2}$" },{ key: "B", text: "$0$" },{ key: "C", text: "$\\dfrac{1}{4}$" },{ key: "D", text: "$\\dfrac{3}{4}$" },{ key: "E", text: "$\\dfrac{\\sqrt{3}}{2}$" }],
    answer: "C", solution: "At the top only the horizontal component $v\\cos60°=v/2$ remains: ratio $=\\cos^2 60°=\\dfrac14$." },
  { id: "bpho-s1-028", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "A uniform rod of length $\\ell$, pivoted at one end, is released from the vertical position and swings down. Using $I=\\tfrac13 M\\ell^2$ about the end, find the speed of the free end as the rod passes through the horizontal.",
    options: [{ key: "A", text: "$\\sqrt{6g\\ell}$" },{ key: "B", text: "$\\sqrt{g\\ell}$" },{ key: "C", text: "$\\sqrt{\\dfrac{3g\\ell}{2}}$" },{ key: "D", text: "$\\sqrt{3g\\ell}$" },{ key: "E", text: "$\\sqrt{2g\\ell}$" }],
    answer: "D", solution: "Centre of mass falls $\\ell/2$: $Mg\\dfrac{\\ell}{2}=\\dfrac12\\cdot\\dfrac{M\\ell^2}{3}\\omega^2$, so $\\omega^2=\\dfrac{3g}{\\ell}$ and $v_{\\mathrm{end}}=\\omega\\ell=\\sqrt{3g\\ell}$." },
  { id: "bpho-s1-029", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A solid disc and a thin hoop of equal mass and radius roll (without slipping) from rest down the same slope. Find the ratio $v_{\\text{disc}}/v_{\\text{hoop}}$ of their speeds at the bottom.",
    options: [{ key: "A", text: "$\\dfrac{2}{\\sqrt{3}}$" },{ key: "B", text: "$\\dfrac{4}{3}$" },{ key: "C", text: "$\\dfrac{\\sqrt{3}}{2}$" },{ key: "D", text: "$\\sqrt{2}$" },{ key: "E", text: "$1$" }],
    answer: "A", solution: "Rolling: $mgh=\\tfrac12mv^2(1+k)$ where $I=kmr^2$; $v=\\sqrt{\\dfrac{2gh}{1+k}}$. Disc $k=\\tfrac12$, hoop $k=1$: ratio $=\\sqrt{\\dfrac{2}{3/2}}=\\sqrt{4/3}=\\dfrac{2}{\\sqrt3}$." },
  { id: "bpho-s1-030", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 1, marks: 3,
    question: "A child of mass $30$ kg sits $2.0$ m from the pivot of a seesaw. At what distance on the other side must a $40$ kg child sit to balance it?",
    options: [{ key: "A", text: "$1.0$ m" },{ key: "B", text: "$2.7$ m" },{ key: "C", text: "$0.75$ m" },{ key: "D", text: "$2.0$ m" },{ key: "E", text: "$1.5$ m" }],
    answer: "E", solution: "Moments: $30\\times2.0=40\\times x$, so $x=1.5$ m." },
  { id: "bpho-s1-031", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "An ice skater spinning freely pulls in her arms so that her moment of inertia halves. Her kinetic energy of rotation",
    options: [{ key: "A", text: "quadruples" },{ key: "B", text: "falls to one quarter" },{ key: "C", text: "doubles" },{ key: "D", text: "halves" },{ key: "E", text: "stays the same" }],
    answer: "C", solution: "Angular momentum $L=I\\omega$ is conserved, so $\\omega$ doubles. $E_k=\\tfrac12I\\omega^2=\\dfrac{L^2}{2I}$ doubles when $I$ halves. The extra energy comes from the work done pulling her arms in." },
  { id: "bpho-s1-032", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A flywheel spinning at $20\\ \\mathrm{rad\\,s^{-1}}$ decelerates uniformly to rest in $5.0$ s. How many complete revolutions does it make while stopping?",
    options: [{ key: "A", text: "$50$" },{ key: "B", text: "$16$" },{ key: "C", text: "$8$" },{ key: "D", text: "$25$" },{ key: "E", text: "$7$ (i.e. $\\lfloor 25/\\pi\\rfloor$)" }],
    answer: "E", solution: "Angle turned $=\\bar\\omega t=\\tfrac12\\times20\\times5=50$ rad $=\\dfrac{50}{2\\pi}\\approx7.96$ rev, so $7$ complete revolutions." },
  { id: "bpho-s1-033", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "A disc starts from rest with uniform angular acceleration $\\alpha=2\\ \\mathrm{rad\\,s^{-2}}$. For a point at radius $0.50$ m, find the magnitude of its total linear acceleration at $t=1.0$ s.",
    options: [{ key: "A", text: "$\\sqrt{5}\\approx2.2\\ \\mathrm{m\\,s^{-2}}$" },{ key: "B", text: "$1.0\\ \\mathrm{m\\,s^{-2}}$" },{ key: "C", text: "$3.0\\ \\mathrm{m\\,s^{-2}}$" },{ key: "D", text: "$\\sqrt{3}\\approx1.7\\ \\mathrm{m\\,s^{-2}}$" },{ key: "E", text: "$2.0\\ \\mathrm{m\\,s^{-2}}$" }],
    answer: "A", solution: "Tangential: $a_t=\\alpha r=1.0$. At $t=1$: $\\omega=2\\ \\mathrm{rad\\,s^{-1}}$, centripetal $a_c=\\omega^2r=2.0$. Total $=\\sqrt{1^2+2^2}=\\sqrt5\\approx2.2\\ \\mathrm{m\\,s^{-2}}$." },
  { id: "bpho-s1-034", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A uniform solid sphere rolls without slipping along level ground. What fraction of its total kinetic energy is rotational? ($I=\\tfrac25 mr^2$)",
    options: [{ key: "A", text: "$\\dfrac{5}{7}$" },{ key: "B", text: "$\\dfrac{2}{7}$" },{ key: "C", text: "$\\dfrac{1}{2}$" },{ key: "D", text: "$\\dfrac{1}{3}$" },{ key: "E", text: "$\\dfrac{2}{5}$" }],
    answer: "B", solution: "$E_{\\mathrm{rot}}=\\tfrac12 I\\omega^2=\\tfrac15 mv^2$ and $E_{\\mathrm{tot}}=\\tfrac12mv^2+\\tfrac15mv^2=\\tfrac7{10}mv^2$. Fraction $=\\dfrac{1/5}{7/10}=\\dfrac{2}{7}$." },
  { id: "bpho-s1-035", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "Masses of $3$ kg and $1$ kg hang from a string over a pulley that is a uniform disc of mass $4$ kg ($I=\\tfrac12MR^2$). The string does not slip. Find the acceleration of the masses. ($g=10\\ \\mathrm{m\\,s^{-2}}$)",
    options: [{ key: "A", text: "$\\dfrac{20}{7}\\ \\mathrm{m\\,s^{-2}}$" },{ key: "B", text: "$\\dfrac{10}{4}\\ \\mathrm{m\\,s^{-2}}$" },{ key: "C", text: "$5\\ \\mathrm{m\\,s^{-2}}$" },{ key: "D", text: "$2.5\\ \\mathrm{m\\,s^{-2}}$" },{ key: "E", text: "$\\dfrac{10}{3}\\ \\mathrm{m\\,s^{-2}}$" }],
    answer: "E", solution: "The pulley adds an effective inertia $I/R^2=\\tfrac12M=2$ kg: $a=\\dfrac{(m_1-m_2)g}{m_1+m_2+\\tfrac12M}=\\dfrac{2\\times10}{3+1+2}=\\dfrac{10}{3}\\ \\mathrm{m\\,s^{-2}}$." },
  { id: "bpho-s1-036", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "A uniform horizontal beam is hinged at one end to a wall and supported at the other end by a vertical cable. The cable suddenly snaps. Find the initial acceleration of the free end of the beam. ($I=\\tfrac13M\\ell^2$ about the hinge)",
    options: [{ key: "A", text: "$2g$" },{ key: "B", text: "$\\dfrac{2g}{3}$" },{ key: "C", text: "$g$" },{ key: "D", text: "$\\dfrac{3g}{2}$" },{ key: "E", text: "$\\dfrac{g}{2}$" }],
    answer: "D", solution: "Torque about hinge: $Mg\\dfrac{\\ell}{2}=\\dfrac{M\\ell^2}{3}\\alpha$, so $\\alpha=\\dfrac{3g}{2\\ell}$ and $a_{\\mathrm{end}}=\\alpha\\ell=\\dfrac{3g}{2}$ — greater than $g$! (The hinge pulls down initially.)" },
  { id: "bpho-s1-037", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "Kepler's second law (equal areas in equal times) is a direct consequence of the conservation of which quantity for a planet orbiting the Sun?",
    options: [{ key: "A", text: "Total mechanical energy" },{ key: "B", text: "Linear momentum" },{ key: "C", text: "Angular momentum" },{ key: "D", text: "Angular velocity" },{ key: "E", text: "Kinetic energy" }],
    answer: "C", solution: "The Sun's gravity is central (along the radius), exerting zero torque about the Sun, so angular momentum $L=mvr_\\perp$ is conserved; the areal rate is $\\dfrac{dA}{dt}=\\dfrac{L}{2m}=$ constant." },
  { id: "bpho-s1-038", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A uniform rod of mass $M$ and length $\\ell$ is pivoted at a point $\\ell/4$ from one end. Using the parallel axis theorem, find its moment of inertia about the pivot. ($I_{\\mathrm{cm}}=\\tfrac1{12}M\\ell^2$)",
    options: [{ key: "A", text: "$\\dfrac{M\\ell^2}{4}$" },{ key: "B", text: "$\\dfrac{7M\\ell^2}{48}$" },{ key: "C", text: "$\\dfrac{5M\\ell^2}{24}$" },{ key: "D", text: "$\\dfrac{M\\ell^2}{12}$" },{ key: "E", text: "$\\dfrac{M\\ell^2}{16}$" }],
    answer: "B", solution: "Distance from centre to pivot $d=\\ell/4$: $I=\\dfrac{M\\ell^2}{12}+M\\left(\\dfrac{\\ell}{4}\\right)^2=M\\ell^2\\left(\\dfrac1{12}+\\dfrac1{16}\\right)=\\dfrac{7M\\ell^2}{48}$." },
  { id: "bpho-s1-039", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 3, marks: 4,
    question: "A mass hangs from two identical springs. Let $T_s$ be the oscillation period when the springs are joined in series, and $T_p$ when they are in parallel. Find $T_s/T_p$.",
    options: [{ key: "A", text: "$\\sqrt{2}$" },{ key: "B", text: "$4$" },{ key: "C", text: "$\\dfrac{1}{2}$" },{ key: "D", text: "$1$" },{ key: "E", text: "$2$" }],
    answer: "E", solution: "Series stiffness $k/2$, parallel $2k$. $T\\propto1/\\sqrt{k}$: ratio $=\\sqrt{\\dfrac{2k}{k/2}}=\\sqrt4=2$." },
  { id: "bpho-s1-040", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 1, marks: 3,
    question: "A pendulum clock keeps correct time on Earth. Taken to the Moon where $g$ is $1/6$ of Earth's, the period of its pendulum becomes",
    options: [{ key: "A", text: "$\\sqrt{6}$ times shorter" },{ key: "B", text: "unchanged" },{ key: "C", text: "$36$ times longer" },{ key: "D", text: "$\\sqrt{6}$ times longer" },{ key: "E", text: "$6$ times longer" }],
    answer: "D", solution: "$T=2\\pi\\sqrt{\\ell/g}\\propto g^{-1/2}$: with $g\\to g/6$, $T\\to\\sqrt6\\,T$." },
  { id: "bpho-s1-041", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 4,
    question: "A particle performs SHM with amplitude $A$. When its displacement is $x=A/2$, what fraction of the total energy is kinetic?",
    options: [{ key: "A", text: "$\\dfrac{3}{4}$" },{ key: "B", text: "$\\dfrac{1}{2}$" },{ key: "C", text: "$\\dfrac{2}{3}$" },{ key: "D", text: "$\\dfrac{1}{4}$" },{ key: "E", text: "$\\dfrac{\\sqrt{3}}{2}$" }],
    answer: "A", solution: "$E_p\\propto x^2$: at $x=A/2$, $E_p=\\dfrac14E$, so $E_k=\\dfrac34E$." },
  { id: "bpho-s1-042", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 4,
    question: "A wave is described by $y=(2.0\\ \\mathrm{mm})\\cos(600t-2.0x)$ with $t$ in seconds and $x$ in metres. Find the wave speed.",
    options: [{ key: "A", text: "$2.0\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$600\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$300\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$1200\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$150\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "C", solution: "Compare with $y=A\\cos(\\omega t-kx)$: $\\omega=600\\ \\mathrm{rad\\,s^{-1}}$, $k=2.0\\ \\mathrm{rad\\,m^{-1}}$. $v=\\omega/k=300\\ \\mathrm{m\\,s^{-1}}$." },
  { id: "bpho-s1-043", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 4,
    question: "A string of length $1.5$ m is fixed at both ends; waves travel along it at $120\\ \\mathrm{m\\,s^{-1}}$. Find the frequency of the third harmonic.",
    options: [{ key: "A", text: "$80$ Hz" },{ key: "B", text: "$120$ Hz" },{ key: "C", text: "$240$ Hz" },{ key: "D", text: "$40$ Hz" },{ key: "E", text: "$60$ Hz" }],
    answer: "B", solution: "Harmonics: $f_n=\\dfrac{nv}{2L}$. $f_3=\\dfrac{3\\times120}{2\\times1.5}=120$ Hz." },
  { id: "bpho-s1-044", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 3, marks: 4,
    question: "A siren emitting $640$ Hz approaches a stationary observer at $20\\ \\mathrm{m\\,s^{-1}}$. The speed of sound is $340\\ \\mathrm{m\\,s^{-1}}$. Find the frequency heard.",
    options: [{ key: "A", text: "$680$ Hz" },{ key: "B", text: "$640$ Hz" },{ key: "C", text: "$604$ Hz" },{ key: "D", text: "$660$ Hz" },{ key: "E", text: "$720$ Hz" }],
    answer: "A", solution: "Approaching source: $f'=f\\dfrac{v}{v-v_s}=640\\times\\dfrac{340}{320}=680$ Hz." },
  { id: "bpho-s1-045", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 1, marks: 3,
    question: "Two tuning forks of frequencies $512$ Hz and $516$ Hz are sounded together. What beat frequency is heard?",
    options: [{ key: "A", text: "$8$ Hz" },{ key: "B", text: "$2$ Hz" },{ key: "C", text: "$1028$ Hz" },{ key: "D", text: "$514$ Hz" },{ key: "E", text: "$4$ Hz" }],
    answer: "E", solution: "Beat frequency $=|f_1-f_2|=4$ Hz." },
  { id: "bpho-s1-046", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 4,
    question: "In a double-slit experiment, light of wavelength $600$ nm passes through slits $0.30$ mm apart, and fringes form on a screen $2.0$ m away. Find the fringe spacing.",
    options: [{ key: "A", text: "$4.0$ mm" },{ key: "B", text: "$1.0$ mm" },{ key: "C", text: "$2.0$ mm" },{ key: "D", text: "$0.4$ mm" },{ key: "E", text: "$9.0$ mm" }],
    answer: "A", solution: "$w=\\dfrac{\\lambda D}{d}=\\dfrac{600\\times10^{-9}\\times2.0}{0.30\\times10^{-3}}=4.0\\times10^{-3}$ m." },
  { id: "bpho-s1-047", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 4,
    question: "The length of a simple pendulum is increased by $21\\%$. By what percentage does its period increase?",
    options: [{ key: "A", text: "$5\\%$" },{ key: "B", text: "$21\\%$" },{ key: "C", text: "$10\\%$" },{ key: "D", text: "$4.6\\%$" },{ key: "E", text: "$11\\%$" }],
    answer: "C", solution: "$T\\propto\\sqrt{\\ell}$: factor $\\sqrt{1.21}=1.10$, i.e. a $10\\%$ increase." },
  { id: "bpho-s1-048", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 3,
    question: "A particle oscillates in SHM with amplitude $5.0$ cm and frequency $2.0$ Hz. Find its maximum speed.",
    options: [{ key: "A", text: "$0.20\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$0.10\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$\\dfrac{\\pi}{5}\\approx0.63\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$2\\pi\\approx6.3\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$\\pi\\approx3.1\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "C", solution: "$v_{\\max}=A\\omega=A\\cdot2\\pi f=0.05\\times4\\pi=\\dfrac{\\pi}{5}\\approx0.63\\ \\mathrm{m\\,s^{-1}}$." },
  { id: "bpho-s1-049", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 3,
    question: "The intensity of a sound is increased by a factor of $100$. By how much does the sound intensity level rise?",
    options: [{ key: "A", text: "$10$ dB" },{ key: "B", text: "$20$ dB" },{ key: "C", text: "$2$ dB" },{ key: "D", text: "$100$ dB" },{ key: "E", text: "$40$ dB" }],
    answer: "B", solution: "$\\Delta L=10\\log_{10}(I_2/I_1)=10\\log_{10}100=20$ dB." },
  { id: "bpho-s1-050", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 1, marks: 3,
    question: "Light enters glass of refractive index $1.5$. Find the speed of light in the glass.",
    options: [{ key: "A", text: "$1.0\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$2.0\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$1.5\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$3.0\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$4.5\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "B", solution: "$v=c/n=3.0\\times10^8/1.5=2.0\\times10^8\\ \\mathrm{m\\,s^{-1}}$." },
  { id: "bpho-s1-051", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 3,
    question: "For a medium of refractive index $\\sqrt{2}$ in air, find the critical angle for total internal reflection.",
    options: [{ key: "A", text: "$90°$" },{ key: "B", text: "$45°$" },{ key: "C", text: "$60°$" },{ key: "D", text: "$35.3°$" },{ key: "E", text: "$30°$" }],
    answer: "B", solution: "$\\sin C=1/n=1/\\sqrt2$, so $C=45°$." },
  { id: "bpho-s1-052", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 3,
    question: "Two points on a progressive wave are separated by a quarter of a wavelength. What is the phase difference between their oscillations?",
    options: [{ key: "A", text: "$\\pi$" },{ key: "B", text: "$\\dfrac{\\pi}{2}$" },{ key: "C", text: "$\\dfrac{3\\pi}{2}$" },{ key: "D", text: "$2\\pi$" },{ key: "E", text: "$\\dfrac{\\pi}{4}$" }],
    answer: "B", solution: "Phase difference $=\\dfrac{2\\pi}{\\lambda}\\times\\dfrac{\\lambda}{4}=\\dfrac{\\pi}{2}$." },
  { id: "bpho-s1-053", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 5,
    question: "A $500\\ \\mu\\mathrm{F}$ capacitor discharges through a $2.0\\ \\mathrm{k\\Omega}$ resistor. How long does it take for the charge to fall to half its initial value?",
    options: [{ key: "A", text: "$1.0$ s" },{ key: "B", text: "$2.0$ s" },{ key: "C", text: "$\\ln 2\\approx0.69$ s" },{ key: "D", text: "$0.35$ s" },{ key: "E", text: "$0.50$ s" }],
    answer: "C", solution: "$\\tau=RC=2000\\times500\\times10^{-6}=1.0$ s. $Q=Q_0e^{-t/\\tau}$: half at $t=\\tau\\ln2\\approx0.69$ s." },
  { id: "bpho-s1-054", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 4,
    question: "In a balanced Wheatstone bridge with resistances $R_1,R_2$ in one pair of arms and $R_3,R_4$ in the other (so no current flows through the galvanometer), which relation holds?",
    options: [{ key: "A", text: "$R_1=R_4$" },{ key: "B", text: "$\\dfrac{R_1}{R_3}=\\dfrac{R_4}{R_2}$" },{ key: "C", text: "$\\dfrac{R_1}{R_2}=\\dfrac{R_3}{R_4}$" },{ key: "D", text: "$R_1R_2=R_3R_4$" },{ key: "E", text: "$R_1+R_4=R_2+R_3$" }],
    answer: "C", solution: "No galvanometer current means the two junctions are at equal potential, so the arms divide the voltage identically: $R_1/R_2=R_3/R_4$." },
  { id: "bpho-s1-055", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 1, marks: 3,
    question: "Two resistors of $6\\ \\Omega$ and $3\\ \\Omega$ are connected in series across a battery. Find the ratio of the power dissipated in the $6\\ \\Omega$ resistor to that in the $3\\ \\Omega$ resistor.",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$1$" },{ key: "C", text: "$\\dfrac{1}{2}$" },{ key: "D", text: "$\\dfrac{1}{4}$" },{ key: "E", text: "$4$" }],
    answer: "A", solution: "Series: same current, $P=I^2R\\propto R$. Ratio $=6/3=2$." },
  { id: "bpho-s1-056", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 4,
    question: "A battery of e.m.f. $12$ V delivers a current of $4.0$ A while its terminal voltage reads $10$ V. Find its internal resistance.",
    options: [{ key: "A", text: "$2.5\\ \\Omega$" },{ key: "B", text: "$0.50\\ \\Omega$" },{ key: "C", text: "$3.0\\ \\Omega$" },{ key: "D", text: "$1.0\\ \\Omega$" },{ key: "E", text: "$0.25\\ \\Omega$" }],
    answer: "B", solution: "Lost volts $=\\varepsilon-V=2$ V across $r$: $r=2/4=0.50\\ \\Omega$." },
  { id: "bpho-s1-057", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 4,
    question: "A battery of e.m.f. $\\varepsilon$ and internal resistance $r$ drives a variable load resistor $R$. For what value of $R$ is the power delivered to the load a maximum, and what is that power?",
    options: [{ key: "A", text: "$R=0$, $P=\\dfrac{\\varepsilon^2}{r}$" },{ key: "B", text: "$R=r$, $P=\\dfrac{\\varepsilon^2}{2r}$" },{ key: "C", text: "$R\\to\\infty$, $P\\to\\dfrac{\\varepsilon^2}{4r}$" },{ key: "D", text: "$R=r$, $P=\\dfrac{\\varepsilon^2}{4r}$" },{ key: "E", text: "$R=2r$, $P=\\dfrac{\\varepsilon^2}{8r}$" }],
    answer: "D", solution: "$P=\\dfrac{\\varepsilon^2R}{(R+r)^2}$; $\\dfrac{dP}{dR}=0$ gives $R=r$, then $P_{\\max}=\\dfrac{\\varepsilon^2}{4r}$ (half the energy is wasted in $r$ at this operating point)." },
  { id: "bpho-s1-058", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 4,
    question: "Point charges $+Q$ and $-Q$ are a distance $d$ apart. Find the magnitude of the electric field at the midpoint between them ($k=1/4\\pi\\varepsilon_0$).",
    options: [{ key: "A", text: "$\\dfrac{4kQ}{d^2}$" },{ key: "B", text: "$\\dfrac{8kQ}{d^2}$" },{ key: "C", text: "$\\dfrac{kQ}{d^2}$" },{ key: "D", text: "$0$" },{ key: "E", text: "$\\dfrac{2kQ}{d^2}$" }],
    answer: "B", solution: "Each charge produces $\\dfrac{kQ}{(d/2)^2}=\\dfrac{4kQ}{d^2}$ at the midpoint, and for opposite charges the two fields point the SAME way (from $+$ towards $-$), adding to $\\dfrac{8kQ}{d^2}$." },
  { id: "bpho-s1-059", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 4,
    question: "A charged particle of mass $m$ and charge $q$ moves at speed $v$ perpendicular to a uniform magnetic field $B$. Find the radius of its circular path.",
    options: [{ key: "A", text: "$\\dfrac{qB}{mv}$" },{ key: "B", text: "$\\dfrac{qvB}{m}$" },{ key: "C", text: "$\\dfrac{v}{qB}$" },{ key: "D", text: "$\\dfrac{mB}{qv}$" },{ key: "E", text: "$\\dfrac{mv}{qB}$" }],
    answer: "E", solution: "Magnetic force provides centripetal force: $qvB=\\dfrac{mv^2}{r}$, so $r=\\dfrac{mv}{qB}$." },
  { id: "bpho-s1-060", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 3,
    question: "In a velocity selector, an electric field $E$ and magnetic field $B$ are arranged perpendicular to each other and to the beam. Charged particles pass through undeflected when their speed is",
    options: [{ key: "A", text: "$\\dfrac{E}{B}$" },{ key: "B", text: "$\\sqrt{EB}$" },{ key: "C", text: "$EB$" },{ key: "D", text: "$\\dfrac{B}{E}$" },{ key: "E", text: "$\\dfrac{E^2}{B}$" }],
    answer: "A", solution: "Undeflected when electric and magnetic forces balance: $qE=qvB$, so $v=E/B$ — independent of the charge and mass." },
  { id: "bpho-s1-061", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 4,
    question: "A conducting rod of length $0.40$ m moves at $10\\ \\mathrm{m\\,s^{-1}}$ perpendicular to both its length and a uniform magnetic field of $0.50$ T. Find the e.m.f. induced across the rod.",
    options: [{ key: "A", text: "$0.5$ V" },{ key: "B", text: "$2.0$ V" },{ key: "C", text: "$20$ V" },{ key: "D", text: "$0.2$ V" },{ key: "E", text: "$5.0$ V" }],
    answer: "B", solution: "$\\varepsilon=B\\ell v=0.50\\times0.40\\times10=2.0$ V." },
  { id: "bpho-s1-062", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 4,
    question: "An ideal transformer steps $240$ V down to $12$ V. The secondary delivers $6.0$ A to a lamp. Find the current drawn from the $240$ V supply.",
    options: [{ key: "A", text: "$0.60$ A" },{ key: "B", text: "$120$ A" },{ key: "C", text: "$6.0$ A" },{ key: "D", text: "$1.2$ A" },{ key: "E", text: "$0.30$ A" }],
    answer: "E", solution: "Ideal: power in = power out. $I_p=\\dfrac{V_sI_s}{V_p}=\\dfrac{12\\times6}{240}=0.30$ A." },
  { id: "bpho-s1-063", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 4,
    question: "Two identical capacitors are connected across the same battery, first in parallel, then in series. Find the ratio of the total energy stored (parallel : series).",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$1$" },{ key: "C", text: "$\\dfrac{1}{2}$" },{ key: "D", text: "$4$" },{ key: "E", text: "$\\dfrac{1}{4}$" }],
    answer: "D", solution: "Same voltage $V$: $E=\\tfrac12C_{\\text{tot}}V^2$. Parallel $C_{\\text{tot}}=2C$; series $C/2$. Ratio $=\\dfrac{2C}{C/2}=4$." },
  { id: "bpho-s1-064", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 4,
    question: "A uniform wire of resistance $R$ is stretched (volume unchanged) to twice its original length. Its new resistance is",
    options: [{ key: "A", text: "$2R$" },{ key: "B", text: "$8R$" },{ key: "C", text: "$R$" },{ key: "D", text: "$R/2$" },{ key: "E", text: "$4R$" }],
    answer: "E", solution: "$R=\\rho\\ell/A$; doubling $\\ell$ at fixed volume halves $A$, so $R\\to\\rho(2\\ell)/(A/2)=4R$." },
  { id: "bpho-s1-065", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 4,
    question: "An electron is accelerated from rest through a potential difference of $1000$ V. Find its final speed. ($e=1.6\\times10^{-19}$ C, $m_e=9.1\\times10^{-31}$ kg)",
    options: [{ key: "A", text: "$\\approx1.9\\times10^{7}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$\\approx1.2\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$\\approx5.9\\times10^{6}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$\\approx3.5\\times10^{14}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$\\approx1.9\\times10^{5}\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "A", solution: "$eV=\\tfrac12m_ev^2$: $v=\\sqrt{\\dfrac{2eV}{m_e}}=\\sqrt{\\dfrac{2\\times1.6\\times10^{-19}\\times1000}{9.1\\times10^{-31}}}\\approx1.9\\times10^7\\ \\mathrm{m\\,s^{-1}}$ (about $6\\%$ of $c$ — relativity just beginning to matter)." },
  { id: "bpho-s1-066", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 3,
    question: "Two long straight parallel wires carry currents in the same direction. The force between them is",
    options: [{ key: "A", text: "repulsive" },{ key: "B", text: "alternating" },{ key: "C", text: "zero" },{ key: "D", text: "attractive" },{ key: "E", text: "perpendicular to the plane of the wires" }],
    answer: "D", solution: "Each wire sits in the magnetic field of the other; applying $F=BI\\ell$ with the field directions shows parallel (same-direction) currents attract, antiparallel repel." },
  { id: "bpho-s1-067", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 1, marks: 3,
    question: "An ideal gas is compressed isothermally to half its volume. Its pressure",
    options: [{ key: "A", text: "falls to one quarter" },{ key: "B", text: "stays the same" },{ key: "C", text: "doubles" },{ key: "D", text: "quadruples" },{ key: "E", text: "halves" }],
    answer: "C", solution: "Isothermal: $pV=$ const (Boyle), so halving $V$ doubles $p$." },
  { id: "bpho-s1-068", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 2, marks: 4,
    question: "$100$ g of water at $90\\ ^\\circ$C is mixed with $200$ g of water at $30\\ ^\\circ$C in an insulated container. Find the final temperature.",
    options: [{ key: "A", text: "$45\\ ^\\circ$C" },{ key: "B", text: "$50\\ ^\\circ$C" },{ key: "C", text: "$60\\ ^\\circ$C" },{ key: "D", text: "$40\\ ^\\circ$C" },{ key: "E", text: "$55\\ ^\\circ$C" }],
    answer: "B", solution: "Heat lost = heat gained (same $c$): $100(90-t)=200(t-30)$, so $9000-100t=200t-6000$, $t=50\\ ^\\circ$C — the mass-weighted mean." },
  { id: "bpho-s1-069", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 2, marks: 3,
    question: "Find the value of $pV$ for $3.0$ mol of an ideal gas at $300$ K. ($R=8.31\\ \\mathrm{J\\,mol^{-1}\\,K^{-1}}$)",
    options: [{ key: "A", text: "$\\approx9.0\\times10^{3}$ J" },{ key: "B", text: "$\\approx7.5\\times10^{2}$ J" },{ key: "C", text: "$\\approx7.5\\times10^{3}$ J" },{ key: "D", text: "$\\approx2.5\\times10^{3}$ J" },{ key: "E", text: "$\\approx2.5\\times10^{4}$ J" }],
    answer: "C", solution: "$pV=nRT=3.0\\times8.31\\times300\\approx7.5\\times10^3$ J." },
  { id: "bpho-s1-070", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 2, marks: 4,
    question: "A heat engine operates between a hot reservoir at $500$ K and a cold reservoir at $300$ K. Find its maximum possible (Carnot) efficiency.",
    options: [{ key: "A", text: "$100\\%$" },{ key: "B", text: "$40\\%$" },{ key: "C", text: "$67\\%$" },{ key: "D", text: "$60\\%$" },{ key: "E", text: "$30\\%$" }],
    answer: "B", solution: "$\\eta_{\\max}=1-\\dfrac{T_c}{T_h}=1-\\dfrac{300}{500}=0.40$ — temperatures must be in kelvin." },
  { id: "bpho-s1-071", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 3, marks: 4,
    question: "At the same temperature, find the ratio of the r.m.s. speed of hydrogen molecules ($M=2$) to that of oxygen molecules ($M=32$).",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$8$" },{ key: "C", text: "$16$" },{ key: "D", text: "$4$" },{ key: "E", text: "$\\sqrt{2}$" }],
    answer: "D", solution: "$v_{\\mathrm{rms}}=\\sqrt{3RT/M}\\propto M^{-1/2}$: ratio $=\\sqrt{32/2}=4$." },
  { id: "bpho-s1-072", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 2, marks: 3,
    question: "A steel rail of length $25$ m is heated through $40$ K. The linear expansivity of steel is $1.2\\times10^{-5}\\ \\mathrm{K^{-1}}$. Find the expansion.",
    options: [{ key: "A", text: "$1.2$ mm" },{ key: "B", text: "$48$ mm" },{ key: "C", text: "$12$ mm" },{ key: "D", text: "$4.8$ mm" },{ key: "E", text: "$0.12$ mm" }],
    answer: "C", solution: "$\\Delta L=\\alpha L\\Delta T=1.2\\times10^{-5}\\times25\\times40=1.2\\times10^{-2}$ m $=12$ mm." },
  { id: "bpho-s1-073", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 2, marks: 4,
    question: "A glass window pane has area $2.0\\ \\mathrm{m^2}$, thickness $6.0$ mm and thermal conductivity $0.80\\ \\mathrm{W\\,m^{-1}\\,K^{-1}}$. The temperature difference across it is $15$ K. Find the rate of heat conduction through it.",
    options: [{ key: "A", text: "$1.6$ kW" },{ key: "B", text: "$400$ W" },{ key: "C", text: "$24$ kW" },{ key: "D", text: "$40$ W" },{ key: "E", text: "$4.0$ kW" }],
    answer: "E", solution: "$P=\\dfrac{kA\\Delta T}{d}=\\dfrac{0.80\\times2.0\\times15}{0.006}=4000$ W. (Why real windows lose far less: still air layers dominate the insulation.)" },
  { id: "bpho-s1-074", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 3, marks: 3,
    question: "For one mole of an ideal gas, the difference between the molar heat capacity at constant pressure and at constant volume, $C_p-C_V$, equals",
    options: [{ key: "A", text: "$2R$" },{ key: "B", text: "$0$" },{ key: "C", text: "$\\dfrac{3R}{2}$" },{ key: "D", text: "$\\dfrac{R}{2}$" },{ key: "E", text: "$R$" }],
    answer: "E", solution: "At constant pressure the gas also does work $p\\Delta V=R\\Delta T$ per mole, so $C_p=C_V+R$ (Mayer's relation)." },
  { id: "bpho-s1-075", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 3, marks: 4,
    question: "An air bubble is released at the bottom of a lake $30$ m deep, where the temperature equals that at the surface. Atmospheric pressure is $1.0\\times10^{5}$ Pa and $\\rho g\\approx10^{4}\\ \\mathrm{Pa\\,m^{-1}}$. By what factor does the bubble's volume grow on reaching the surface?",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$\\sqrt{30}$" },{ key: "C", text: "$30$" },{ key: "D", text: "$1.3$" },{ key: "E", text: "$4$" }],
    answer: "E", solution: "Bottom pressure $=10^5+3\\times10^5=4\\times10^5$ Pa. Isothermal: $V\\propto1/p$, factor $=4$." },
  { id: "bpho-s1-076", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 2, marks: 3,
    question: "The specific latent heat of vaporisation of water is $2.26\\times10^{6}\\ \\mathrm{J\\,kg^{-1}}$. How much energy is carried away when $1.0$ g of sweat evaporates from the skin?",
    options: [{ key: "A", text: "$\\approx2.3\\times10^{4}$ J" },{ key: "B", text: "$\\approx2.3\\times10^{6}$ J" },{ key: "C", text: "$\\approx230$ J" },{ key: "D", text: "$\\approx23$ J" },{ key: "E", text: "$\\approx2.3\\times10^{3}$ J" }],
    answer: "E", solution: "$Q=mL=10^{-3}\\times2.26\\times10^6\\approx2.3\\times10^3$ J — evaporation is a powerful cooling mechanism." },
  { id: "bpho-s1-077", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 3, marks: 3,
    question: "The internal energy of $n$ moles of a monatomic ideal gas at temperature $T$ is",
    options: [{ key: "A", text: "$\\dfrac{3}{2}nRT$" },{ key: "B", text: "$\\dfrac{1}{2}nRT$" },{ key: "C", text: "$nRT$" },{ key: "D", text: "$3nRT$" },{ key: "E", text: "$\\dfrac{5}{2}nRT$" }],
    answer: "A", solution: "Three translational degrees of freedom, each contributing $\\tfrac12k_BT$ per molecule: $U=\\tfrac32nRT$." },
  { id: "bpho-s1-078", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 2, marks: 3,
    question: "At what temperature do the Celsius and Fahrenheit scales read the same value?",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$-40$" },{ key: "C", text: "$-32$" },{ key: "D", text: "$-73$" },{ key: "E", text: "$32$" }],
    answer: "B", solution: "$F=\\tfrac95C+32$; set $F=C$: $C=\\tfrac95C+32\\Rightarrow-\\tfrac45C=32\\Rightarrow C=-40$." },
  { id: "bpho-s1-079", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 3, marks: 3,
    question: "A black body's absolute temperature is doubled. The total power it radiates increases by a factor of",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$2$" },{ key: "C", text: "$32$" },{ key: "D", text: "$16$" },{ key: "E", text: "$8$" }],
    answer: "D", solution: "Stefan–Boltzmann: $P\\propto T^4$, so $2^4=16$." },
  { id: "bpho-s1-080", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 2, marks: 4,
    question: "Light of photon energy $3.1$ eV strikes a metal of work function $2.1$ eV. Find the maximum kinetic energy of the emitted photoelectrons.",
    options: [{ key: "A", text: "$3.1$ eV" },{ key: "B", text: "$1.0$ eV" },{ key: "C", text: "$0.5$ eV" },{ key: "D", text: "$2.1$ eV" },{ key: "E", text: "$5.2$ eV" }],
    answer: "B", solution: "Einstein's photoelectric equation: $KE_{\\max}=hf-\\phi=3.1-2.1=1.0$ eV." },
  { id: "bpho-s1-081", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 4,
    question: "Find the de Broglie wavelength of an electron moving at $1.0\\times10^{6}\\ \\mathrm{m\\,s^{-1}}$. ($h=6.6\\times10^{-34}$ J s, $m_e=9.1\\times10^{-31}$ kg)",
    options: [{ key: "A", text: "$\\approx7.3\\times10^{-10}$ m" },{ key: "B", text: "$\\approx6.0\\times10^{-28}$ m" },{ key: "C", text: "$\\approx3.6\\times10^{-10}$ m" },{ key: "D", text: "$\\approx1.4\\times10^{-9}$ m" },{ key: "E", text: "$\\approx7.3\\times10^{-7}$ m" }],
    answer: "A", solution: "$\\lambda=\\dfrac{h}{mv}=\\dfrac{6.6\\times10^{-34}}{9.1\\times10^{-31}\\times10^{6}}\\approx7.3\\times10^{-10}$ m — about atomic size, which is why electrons diffract off crystals." },
  { id: "bpho-s1-082", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 2, marks: 4,
    question: "A sample of carbon-14 (half-life $5730$ years) has decayed until only $1/8$ of the original nuclei remain. How old is the sample?",
    options: [{ key: "A", text: "$5730$ years" },{ key: "B", text: "$45840$ years" },{ key: "C", text: "$22920$ years" },{ key: "D", text: "$17190$ years" },{ key: "E", text: "$11460$ years" }],
    answer: "D", solution: "$1/8=(1/2)^3$: three half-lives, $3\\times5730=17190$ years." },
  { id: "bpho-s1-083", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 2, marks: 3,
    question: "Using $E=mc^2$, find the energy equivalent of $1.0$ g of mass. ($c=3.0\\times10^{8}\\ \\mathrm{m\\,s^{-1}}$)",
    options: [{ key: "A", text: "$3.0\\times10^{5}$ J" },{ key: "B", text: "$9.0\\times10^{16}$ J" },{ key: "C", text: "$3.0\\times10^{11}$ J" },{ key: "D", text: "$9.0\\times10^{10}$ J" },{ key: "E", text: "$9.0\\times10^{13}$ J" }],
    answer: "E", solution: "$E=10^{-3}\\times(3\\times10^8)^2=9\\times10^{13}$ J — roughly the energy of a small nuclear weapon, from a paperclip's worth of mass." },
  { id: "bpho-s1-084", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 4,
    question: "In the hydrogen atom the energy levels are $E_n=-13.6/n^2$ eV. Find the energy of the photon emitted in the transition $n=2\\to n=1$.",
    options: [{ key: "A", text: "$6.8$ eV" },{ key: "B", text: "$10.2$ eV" },{ key: "C", text: "$1.9$ eV" },{ key: "D", text: "$3.4$ eV" },{ key: "E", text: "$13.6$ eV" }],
    answer: "B", solution: "$\\Delta E=13.6\\left(1-\\dfrac14\\right)=13.6\\times\\dfrac34=10.2$ eV (the Lyman-α line)." },
  { id: "bpho-s1-085", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 4,
    question: "A muon travels at $0.60c$. Find the Lorentz factor $\\gamma$.",
    options: [{ key: "A", text: "$0.80$" },{ key: "B", text: "$1.36$" },{ key: "C", text: "$1.25$" },{ key: "D", text: "$2.5$" },{ key: "E", text: "$1.67$" }],
    answer: "C", solution: "$\\gamma=\\dfrac{1}{\\sqrt{1-v^2/c^2}}=\\dfrac{1}{\\sqrt{1-0.36}}=\\dfrac{1}{0.8}=1.25$." },
  { id: "bpho-s1-086", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 4,
    question: "In a nuclear reaction the total mass decreases by $0.030$ u. Find the energy released. ($1$ u $=931.5$ MeV$/c^2$)",
    options: [{ key: "A", text: "$\\approx2.8$ MeV" },{ key: "B", text: "$\\approx931$ MeV" },{ key: "C", text: "$\\approx280$ MeV" },{ key: "D", text: "$\\approx0.03$ MeV" },{ key: "E", text: "$\\approx28$ MeV" }],
    answer: "E", solution: "$E=\\Delta m\\,c^2=0.030\\times931.5\\approx28$ MeV." },
  { id: "bpho-s1-087", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 3,
    question: "Find the momentum of a photon of wavelength $500$ nm. ($h=6.6\\times10^{-34}$ J s)",
    options: [{ key: "A", text: "$\\approx4.0\\times10^{-19}\\ \\mathrm{kg\\,m\\,s^{-1}}$" },{ key: "B", text: "$0$" },{ key: "C", text: "$\\approx1.3\\times10^{-27}\\ \\mathrm{kg\\,m\\,s^{-1}}$" },{ key: "D", text: "$\\approx1.3\\times10^{-24}\\ \\mathrm{kg\\,m\\,s^{-1}}$" },{ key: "E", text: "$\\approx3.3\\times10^{-40}\\ \\mathrm{kg\\,m\\,s^{-1}}$" }],
    answer: "C", solution: "$p=\\dfrac{h}{\\lambda}=\\dfrac{6.6\\times10^{-34}}{5.0\\times10^{-7}}\\approx1.3\\times10^{-27}\\ \\mathrm{kg\\,m\\,s^{-1}}$." },
  { id: "bpho-s1-088", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 2, marks: 4,
    question: "Estimate the order of magnitude of the number of times a human heart beats in an $80$-year lifetime.",
    options: [{ key: "A", text: "$10^{13}$" },{ key: "B", text: "$10^{11}$" },{ key: "C", text: "$10^{9}$" },{ key: "D", text: "$10^{6}$" },{ key: "E", text: "$10^{7}$" }],
    answer: "C", solution: "About $70$ beats/min $\\times60\\times24\\times365\\times80\\approx3\\times10^9$: order $10^9$. (BPhO loves quick order-of-magnitude estimates — practise them.)" },
  { id: "bpho-s1-089", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 5,
    question: "Estimate the total mass of the Earth's atmosphere, given atmospheric pressure $1.0\\times10^{5}$ Pa, Earth radius $6.4\\times10^{6}$ m and $g=10\\ \\mathrm{m\\,s^{-2}}$.",
    options: [{ key: "A", text: "$\\approx5\\times10^{22}$ kg" },{ key: "B", text: "$\\approx6\\times10^{24}$ kg" },{ key: "C", text: "$\\approx5\\times10^{18}$ kg" },{ key: "D", text: "$\\approx5\\times10^{16}$ kg" },{ key: "E", text: "$\\approx5\\times10^{14}$ kg" }],
    answer: "C", solution: "Pressure = weight per unit area: $M=\\dfrac{p_0\\times4\\pi R^2}{g}=\\dfrac{10^5\\times4\\pi(6.4\\times10^6)^2}{10}\\approx5\\times10^{18}$ kg." },
  { id: "bpho-s1-090", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 2, marks: 4,
    question: "Estimate the number of water molecules in a $250$ g glass of water. ($M_{\\mathrm{H_2O}}=18\\ \\mathrm{g\\,mol^{-1}}$, $N_A=6.0\\times10^{23}$)",
    options: [{ key: "A", text: "$\\approx6\\times10^{23}$" },{ key: "B", text: "$\\approx8\\times10^{27}$" },{ key: "C", text: "$\\approx1.5\\times10^{22}$" },{ key: "D", text: "$\\approx8\\times10^{24}$" },{ key: "E", text: "$\\approx8\\times10^{21}$" }],
    answer: "D", solution: "$N=\\dfrac{250}{18}\\times6.0\\times10^{23}\\approx8\\times10^{24}$ molecules." },
  { id: "bpho-s1-091", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 4,
    question: "In the laboratory frame a muon travels $100$ m through the atmosphere with Lorentz factor $\\gamma=5$. What distance does this correspond to in the muon's own rest frame?",
    options: [{ key: "A", text: "$25$ m" },{ key: "B", text: "$4$ m" },{ key: "C", text: "$100$ m" },{ key: "D", text: "$500$ m" },{ key: "E", text: "$20$ m" }],
    answer: "E", solution: "Length contraction: $L=\\dfrac{L_0}{\\gamma}=\\dfrac{100}{5}=20$ m — from the muon's viewpoint the atmosphere is contracted, which is why muons reach the ground." },
  { id: "bpho-s1-092", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 4,
    question: "A radioactive source contains $1.0\\times10^{20}$ nuclei with a half-life of $10$ days. Estimate its activity. ($1$ day $=86400$ s)",
    options: [{ key: "A", text: "$\\approx2\\times10^{15}$ Bq" },{ key: "B", text: "$\\approx1\\times10^{19}$ Bq" },{ key: "C", text: "$\\approx8\\times10^{10}$ Bq" },{ key: "D", text: "$\\approx8\\times10^{13}$ Bq" },{ key: "E", text: "$\\approx7\\times10^{18}$ Bq" }],
    answer: "D", solution: "$A=\\lambda N=\\dfrac{\\ln2}{T_{1/2}}N=\\dfrac{0.693}{8.64\\times10^{5}}\\times10^{20}\\approx8\\times10^{13}$ Bq." },
];
