// BPhO S1 加厚批 B —— 偏中高难，补强波/电磁/热学/现代，多微积分与多步。原创，逐题程序断言。
import type { MCQQuestion } from "./types";

export const BPHO_S1_B: MCQQuestion[] = [
  { id: "bpho-s1-b-001", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A force $F(x) = (20 - 3x^2)\\ \\mathrm{N}$ (with $x$ in metres) acts on a body along the $x$-axis. Find the work done as the body moves from $x=0$ to $x=4\\ \\mathrm{m}$.",
    options: [{ key: "A", text: "$64$ J" },{ key: "B", text: "$128$ J" },{ key: "C", text: "$16$ J" },{ key: "D", text: "$80$ J" },{ key: "E", text: "$-16$ J" }],
    answer: "C", solution: "$W=\\int_0^4 (20-3x^2)\\,dx=[20x-x^3]_0^4=80-64=16$ J. The cubic term removes most of the work done by the constant part of the force." },
  { id: "bpho-s1-b-002", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A particle moves so that its velocity decreases linearly with position: $v = v_0(1 - x/L)$. Find its acceleration as a function of $x$.",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$\\dfrac{v_0^2}{L^2}x$" },{ key: "C", text: "$-\\dfrac{v_0}{L}$" },{ key: "D", text: "$-\\dfrac{v_0^2}{L}\\left(1-\\dfrac{x}{L}\\right)$" },{ key: "E", text: "$-\\dfrac{v_0^2}{L}$" }],
    answer: "D", solution: "$a=v\\dfrac{dv}{dx}=v_0(1-x/L)\\cdot\\left(-\\dfrac{v_0}{L}\\right)=-\\dfrac{v_0^2}{L}(1-x/L)$. The particle never quite reaches $x=L$ (velocity and acceleration both $\\to0$)." },
  { id: "bpho-s1-b-003", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "A rocket in deep space ejects fuel at exhaust speed $u$ relative to itself. Ignoring gravity, what is the change in the rocket's speed when its mass falls from $M_0$ to $M_0/e$?",
    options: [{ key: "A", text: "$2u$" },{ key: "B", text: "$eu$" },{ key: "C", text: "$u/e$" },{ key: "D", text: "$u\\ln 2$" },{ key: "E", text: "$u$" }],
    answer: "E", solution: "Tsiolkovsky: $\\Delta v=u\\ln\\dfrac{M_0}{M}=u\\ln\\dfrac{M_0}{M_0/e}=u\\ln e=u$. Losing a factor $e$ of mass buys exactly one exhaust-speed of $\\Delta v$." },
  { id: "bpho-s1-b-004", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A uniform chain hangs vertically with its lower end just touching a table, then is released. Compared with the weight of chain already on the table, the force the falling chain exerts on the table when a length $x$ has landed is",
    options: [{ key: "A", text: "twice that weight" },{ key: "B", text: "three times that weight" },{ key: "C", text: "equal to that weight" },{ key: "D", text: "half that weight" },{ key: "E", text: "four times that weight" }],
    answer: "B", solution: "Two contributions: the static weight of length $x$ ($\\lambda x g$) plus the momentum flux of arriving links moving at $v=\\sqrt{2gx}$: $\\dfrac{dp}{dt}=\\lambda v\\cdot v=\\lambda(2gx)=2\\lambda x g$. Total $=3\\lambda x g$, i.e. three times the resting weight." },
  { id: "bpho-s1-b-005", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "A projectile is launched from ground level with fixed speed. Neglecting air resistance, its horizontal range is greatest at a launch angle of",
    options: [{ key: "A", text: "$60°$" },{ key: "B", text: "$45°$" },{ key: "C", text: "$0°$" },{ key: "D", text: "$30°$" },{ key: "E", text: "$90°$" }],
    answer: "B", solution: "$R=\\dfrac{v^2\\sin 2\\theta}{g}$ is maximised when $\\sin2\\theta=1$, i.e. $\\theta=45°$." },
  { id: "bpho-s1-b-006", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A ball is thrown at $25\\ \\mathrm{m\\,s^{-1}}$ at an angle with $\\cos\\theta=0.6$, $\\sin\\theta=0.8$ ($g=10$). Find its height above the launch point $1.0$ s after launch.",
    options: [{ key: "A", text: "$15$ m" },{ key: "B", text: "$11$ m" },{ key: "C", text: "$25$ m" },{ key: "D", text: "$20$ m" },{ key: "E", text: "$5$ m" }],
    answer: "A", solution: "$v_y=25\\times0.8=20\\ \\mathrm{m\\,s^{-1}}$; height $=v_y t-\\tfrac12 g t^2=20-5=15$ m." },
  { id: "bpho-s1-b-007", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A conical pendulum: a bob of mass $m$ on a string makes angle $\\theta$ with the vertical. Find the tension in the string.",
    options: [{ key: "A", text: "$mg$" },{ key: "B", text: "$mg\\tan\\theta$" },{ key: "C", text: "$\\dfrac{mg}{\\cos\\theta}$" },{ key: "D", text: "$mg\\cos\\theta$" },{ key: "E", text: "$mg\\sin\\theta$" }],
    answer: "C", solution: "Vertical balance: $T\\cos\\theta=mg\\Rightarrow T=\\dfrac{mg}{\\cos\\theta}$." },
  { id: "bpho-s1-b-008", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "A $2.0$ kg mass on a vertical spring of stiffness $200\\ \\mathrm{N\\,m^{-1}}$ oscillates. Find the period.",
    options: [{ key: "A", text: "$\\dfrac{2\\pi}{5}\\approx1.3$ s" },{ key: "B", text: "$0.1$ s" },{ key: "C", text: "$\\dfrac{\\pi}{10}\\approx0.31$ s" },{ key: "D", text: "$\\pi\\approx3.1$ s" },{ key: "E", text: "$\\dfrac{\\pi}{5}\\approx0.63$ s" }],
    answer: "E", solution: "$T=2\\pi\\sqrt{m/k}=2\\pi\\sqrt{2/200}=2\\pi/10=\\pi/5\\approx0.63$ s. Gravity only shifts the equilibrium, not the period." },
  { id: "bpho-s1-b-009", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "Two masses, $1$ kg at rest and $3$ kg moving at $8\\ \\mathrm{m\\,s^{-1}}$, are on a frictionless surface. Find the speed of their centre of mass.",
    options: [{ key: "A", text: "$5\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$8\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$2\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$4\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$6\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "E", solution: "$v_{cm}=\\dfrac{1\\cdot0+3\\cdot8}{4}=6\\ \\mathrm{m\\,s^{-1}}$; unaffected by any internal collision." },
  { id: "bpho-s1-b-010", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A uniform solid sphere ($I=\\tfrac25 mr^2$) rolls without slipping from rest down a slope, dropping a height of $1.4$ m ($g=10$). Find its speed at the bottom.",
    options: [{ key: "A", text: "$\\sqrt{28}\\approx5.3\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$\\sqrt{14}\\approx3.7\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$5.0\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$\\sqrt{10}\\approx3.2\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$\\sqrt{20}\\approx4.5\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "E", solution: "$mgh=\\tfrac12mv^2(1+\\tfrac25)=\\tfrac{7}{10}mv^2$, so $v=\\sqrt{\\dfrac{10gh}{7}}=\\sqrt{\\dfrac{10\\cdot10\\cdot1.4}{7}}=\\sqrt{20}\\approx4.5$." },
  { id: "bpho-s1-b-011", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "Three identical blocks (each mass $m$) connected by light strings are pulled along a frictionless surface by a force $F$ applied to the front block. Find the tension in the string between the middle and rear blocks.",
    options: [{ key: "A", text: "$\\dfrac{F}{2}$" },{ key: "B", text: "$F$" },{ key: "C", text: "$\\dfrac{2F}{3}$" },{ key: "D", text: "$\\dfrac{3F}{2}$" },{ key: "E", text: "$\\dfrac{F}{3}$" }],
    answer: "E", solution: "Whole system: $a=F/3m$. The rear string pulls only the rear block: $T=ma=F/3$." },
  { id: "bpho-s1-b-012", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A $0.50$ kg ball on a string of length $2.0$ m is whirled in a vertical circle. At the lowest point its speed is $6.0\\ \\mathrm{m\\,s^{-1}}$ ($g=10$). Find the string tension there.",
    options: [{ key: "A", text: "$23$ N" },{ key: "B", text: "$9$ N" },{ key: "C", text: "$5$ N" },{ key: "D", text: "$14$ N" },{ key: "E", text: "$18$ N" }],
    answer: "D", solution: "At the bottom: $T-mg=\\dfrac{mv^2}{r}$, $T=0.5\\cdot10+\\dfrac{0.5\\cdot36}{2}=5+9=14$ N." },
  { id: "bpho-s1-b-013", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A projectile is fired vertically from a planet's surface at half the escape speed. Ignoring air resistance, what fraction of the planet's radius does it rise to (as a height above the surface)?",
    options: [{ key: "A", text: "$R$" },{ key: "B", text: "$\\dfrac{1}{3}R$" },{ key: "C", text: "$\\dfrac{1}{2\\sqrt2}R$" },{ key: "D", text: "$\\dfrac{1}{2}R$" },{ key: "E", text: "$\\dfrac{1}{4}R$" }],
    answer: "B", solution: "Energy: $\\tfrac12 v^2-\\dfrac{GM}{R}=-\\dfrac{GM}{R+h}$ with $v=\\tfrac12 v_e=\\tfrac12\\sqrt{2GM/R}$. Then $\\tfrac14\\dfrac{GM}{R}-\\dfrac{GM}{R}=-\\dfrac{GM}{R+h}$ gives $\\dfrac{1}{R+h}=\\dfrac{3}{4R}$, so $R+h=\\tfrac43R$, $h=\\tfrac13R$." },
  { id: "bpho-s1-b-014", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "Four point masses $m$ sit at the corners of a square of side $a$. Find the moment of inertia about an axis through the centre, perpendicular to the plane.",
    options: [{ key: "A", text: "$ma^2$" },{ key: "B", text: "$4ma^2$" },{ key: "C", text: "$2ma^2$" },{ key: "D", text: "$\\sqrt2\\,ma^2$" },{ key: "E", text: "$\\dfrac{ma^2}{2}$" }],
    answer: "C", solution: "Each mass is at distance $\\dfrac{a}{\\sqrt2}$ from the centre: $I=4m\\left(\\dfrac{a}{\\sqrt2}\\right)^2=4m\\cdot\\dfrac{a^2}{2}=2ma^2$." },
  { id: "bpho-s1-b-015", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "An object of mass $2.0$ kg falls under gravity with a linear drag force $F=bv$ where $b=4.0\\ \\mathrm{kg\\,s^{-1}}$ ($g=10$). Find its terminal velocity.",
    options: [{ key: "A", text: "$10\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$8.0\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$2.5\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$20\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$5.0\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "E", solution: "Terminal: $mg=bv_T$, $v_T=mg/b=20/4=5.0\\ \\mathrm{m\\,s^{-1}}$." },
  { id: "bpho-s1-b-016", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A simple pendulum hangs in a lift that accelerates upwards at $5.0\\ \\mathrm{m\\,s^{-2}}$ ($g=10$). By what factor does its oscillation frequency change compared with the lift at rest?",
    options: [{ key: "A", text: "$1.5$" },{ key: "B", text: "$\\sqrt{1.5}\\approx1.22$" },{ key: "C", text: "unchanged" },{ key: "D", text: "$\\sqrt{2}\\approx1.41$" },{ key: "E", text: "$\\sqrt{0.5}\\approx0.71$" }],
    answer: "B", solution: "Effective gravity $g'=g+a=15$. $f\\propto\\sqrt{g'}$, factor $=\\sqrt{15/10}=\\sqrt{1.5}\\approx1.22$." },
  { id: "bpho-s1-b-017", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 3, marks: 4,
    question: "Two SHMs of the same frequency and amplitude $A$, with a phase difference of $\\dfrac{\\pi}{2}$, act on a particle along the same line. Find the amplitude of the resulting oscillation.",
    options: [{ key: "A", text: "$A$" },{ key: "B", text: "$\\sqrt{2}\\,A$" },{ key: "C", text: "$0$" },{ key: "D", text: "$\\dfrac{A}{\\sqrt2}$" },{ key: "E", text: "$2A$" }],
    answer: "B", solution: "Phasor addition of two equal amplitudes at $90°$: resultant $=\\sqrt{A^2+A^2}=\\sqrt2\\,A$." },
  { id: "bpho-s1-b-018", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 3, marks: 4,
    question: "A diffraction grating has $500$ lines per mm. Light of wavelength $500$ nm is incident normally. Find the angle of the first-order maximum.",
    options: [{ key: "A", text: "$\\approx7.2°$" },{ key: "B", text: "$\\approx45°$" },{ key: "C", text: "$\\approx30°$" },{ key: "D", text: "$\\approx0.5°$" },{ key: "E", text: "$\\approx14.5°$" }],
    answer: "E", solution: "Slit spacing $d=\\dfrac{1}{500}\\ \\mathrm{mm}=2.0\\times10^{-6}$ m. $d\\sin\\theta=m\\lambda$: $\\sin\\theta=\\dfrac{500\\times10^{-9}}{2\\times10^{-6}}=0.25$, $\\theta\\approx14.5°$." },
  { id: "bpho-s1-b-019", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 3, marks: 4,
    question: "An observer moves at $20\\ \\mathrm{m\\,s^{-1}}$ towards a stationary source emitting $680$ Hz. The speed of sound is $340\\ \\mathrm{m\\,s^{-1}}$. Find the frequency heard.",
    options: [{ key: "A", text: "$700$ Hz" },{ key: "B", text: "$720$ Hz" },{ key: "C", text: "$640$ Hz" },{ key: "D", text: "$760$ Hz" },{ key: "E", text: "$680$ Hz" }],
    answer: "B", solution: "Moving observer approaching: $f'=f\\dfrac{v+v_o}{v}=680\\times\\dfrac{360}{340}=720$ Hz." },
  { id: "bpho-s1-b-020", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 3,
    question: "A stationary wave forms on a string fixed at both ends, vibrating in its third harmonic. How many nodes are there in total (including the two ends)?",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$6$" },{ key: "C", text: "$3$" },{ key: "D", text: "$4$" },{ key: "E", text: "$2$" }],
    answer: "D", solution: "The $n$th harmonic has $n$ antinodes and $n+1$ nodes. Third harmonic: $4$ nodes." },
  { id: "bpho-s1-b-021", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 4,
    question: "A sound has intensity level $30$ dB above another. Find the ratio of the two intensities.",
    options: [{ key: "A", text: "$300$" },{ key: "B", text: "$1000$" },{ key: "C", text: "$100$" },{ key: "D", text: "$3$" },{ key: "E", text: "$30$" }],
    answer: "B", solution: "$\\Delta L=10\\log_{10}(I_2/I_1)=30\\Rightarrow I_2/I_1=10^3=1000$." },
  { id: "bpho-s1-b-022", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 3, marks: 4,
    question: "Light of wavelength $\\lambda$ in air enters a thin soap film of refractive index $n$. For the film to appear bright by reflection at normal incidence, the minimum non-zero film thickness is",
    options: [{ key: "A", text: "$\\dfrac{\\lambda}{n}$" },{ key: "B", text: "$\\dfrac{\\lambda}{2}$" },{ key: "C", text: "$\\dfrac{\\lambda}{4n}$" },{ key: "D", text: "$\\dfrac{\\lambda}{2n}$" },{ key: "E", text: "$\\dfrac{n\\lambda}{4}$" }],
    answer: "C", solution: "One reflection (air→film) has a $\\pi$ phase change, the other (film→air) does not. Constructive reflection needs an extra half-wave in the film: $2nt=\\dfrac{\\lambda}{2}$, so $t=\\dfrac{\\lambda}{4n}$." },
  { id: "bpho-s1-b-023", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 3,
    question: "Unpolarised light of intensity $I_0$ passes through two ideal polarisers whose transmission axes are at $60°$ to each other. Find the transmitted intensity.",
    options: [{ key: "A", text: "$\\dfrac{I_0}{4}$" },{ key: "B", text: "$\\dfrac{3I_0}{8}$" },{ key: "C", text: "$\\dfrac{I_0}{2}$" },{ key: "D", text: "$\\dfrac{I_0}{8}$" },{ key: "E", text: "$\\dfrac{I_0}{16}$" }],
    answer: "D", solution: "First polariser: $I_0/2$. Malus: $\\times\\cos^2 60°=\\times\\tfrac14$. Total $=\\dfrac{I_0}{2}\\cdot\\dfrac14=\\dfrac{I_0}{8}$." },
  { id: "bpho-s1-b-024", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 3, marks: 4,
    question: "An organ pipe closed at one end has fundamental frequency $f_0$. An identical pipe open at both ends has fundamental frequency",
    options: [{ key: "A", text: "$\\dfrac{3f_0}{2}$" },{ key: "B", text: "$4f_0$" },{ key: "C", text: "$f_0$" },{ key: "D", text: "$\\dfrac{f_0}{2}$" },{ key: "E", text: "$2f_0$" }],
    answer: "E", solution: "Closed pipe: $f_0=\\dfrac{v}{4L}$. Open pipe: $f=\\dfrac{v}{2L}=2f_0$." },
  { id: "bpho-s1-b-025", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 4,
    question: "A wave has speed $340\\ \\mathrm{m\\,s^{-1}}$ and frequency $170$ Hz. Two points oscillate exactly out of phase (antiphase). Find the smallest possible separation between them.",
    options: [{ key: "A", text: "$0.5$ m" },{ key: "B", text: "$4.0$ m" },{ key: "C", text: "$0.25$ m" },{ key: "D", text: "$1.0$ m" },{ key: "E", text: "$2.0$ m" }],
    answer: "D", solution: "$\\lambda=v/f=340/170=2.0$ m. Antiphase means separation $=\\lambda/2=1.0$ m (smallest)." },
  { id: "bpho-s1-b-026", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 3, marks: 4,
    question: "A mass on a spring has SHM amplitude $A$. At what displacement is the kinetic energy equal to the potential energy?",
    options: [{ key: "A", text: "$\\dfrac{A}{\\sqrt3}$" },{ key: "B", text: "$\\dfrac{A}{\\sqrt2}$" },{ key: "C", text: "$\\dfrac{A}{2}$" },{ key: "D", text: "$A$" },{ key: "E", text: "$\\dfrac{\\sqrt3 A}{2}$" }],
    answer: "B", solution: "$E_p=\\tfrac12E$ when $x^2=\\tfrac12A^2$, i.e. $x=\\dfrac{A}{\\sqrt2}$." },
  { id: "bpho-s1-b-027", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 4,
    question: "Three capacitors, each $C$, are connected with two in series and that combination in parallel with the third. Find the total capacitance.",
    options: [{ key: "A", text: "$\\dfrac{2C}{3}$" },{ key: "B", text: "$\\dfrac{C}{3}$" },{ key: "C", text: "$2C$" },{ key: "D", text: "$\\dfrac{3C}{2}$" },{ key: "E", text: "$3C$" }],
    answer: "D", solution: "Two in series: $C/2$. In parallel with $C$: $C/2+C=\\dfrac{3C}{2}$." },
  { id: "bpho-s1-b-028", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 5,
    question: "A capacitor $C$ charged to voltage $V$ is connected across an identical uncharged capacitor. Find the fraction of the original stored energy that remains after charge redistributes.",
    options: [{ key: "A", text: "$\\dfrac{1}{2}$" },{ key: "B", text: "$\\dfrac{3}{4}$" },{ key: "C", text: "$\\dfrac{1}{4}$" },{ key: "D", text: "$0$" },{ key: "E", text: "$1$" }],
    answer: "A", solution: "Charge conserved: final voltage $V/2$ on total capacitance $2C$. Initial energy $\\tfrac12CV^2$; final $\\tfrac12(2C)(V/2)^2=\\tfrac14CV^2$. Remaining fraction $=\\tfrac12$ (the rest is lost as heat/radiation, independent of resistance)." },
  { id: "bpho-s1-b-029", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 4,
    question: "A long straight wire carries $5.0$ A. Find the magnetic flux density at $0.10$ m from it. ($\\mu_0=4\\pi\\times10^{-7}$)",
    options: [{ key: "A", text: "$1.0\\times10^{-5}$ T" },{ key: "B", text: "$5.0\\times10^{-5}$ T" },{ key: "C", text: "$1.0\\times10^{-6}$ T" },{ key: "D", text: "$2.0\\times10^{-5}$ T" },{ key: "E", text: "$1.0\\times10^{-4}$ T" }],
    answer: "A", solution: "$B=\\dfrac{\\mu_0 I}{2\\pi r}=\\dfrac{4\\pi\\times10^{-7}\\times5}{2\\pi\\times0.1}=\\dfrac{2\\times10^{-7}\\times5}{0.1}=1.0\\times10^{-5}$ T." },
  { id: "bpho-s1-b-030", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 4,
    question: "A magnetic flux through a coil of $1$ turn changes uniformly from $0.30$ Wb to $0.10$ Wb in $0.10$ s. Find the magnitude of the induced e.m.f.",
    options: [{ key: "A", text: "$2.0$ V" },{ key: "B", text: "$0.02$ V" },{ key: "C", text: "$20$ V" },{ key: "D", text: "$0.2$ V" },{ key: "E", text: "$4.0$ V" }],
    answer: "A", solution: "$\\varepsilon=-N\\dfrac{d\\Phi}{dt}=\\dfrac{0.20}{0.10}=2.0$ V." },
  { id: "bpho-s1-b-031", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 4,
    question: "Find the cyclotron frequency of an electron in a magnetic field of $0.50$ T. ($e=1.6\\times10^{-19}$ C, $m_e=9.1\\times10^{-31}$ kg)",
    options: [{ key: "A", text: "$\\approx8.8\\times10^{10}$ Hz" },{ key: "B", text: "$\\approx2.2\\times10^{9}$ Hz" },{ key: "C", text: "$\\approx1.4\\times10^{10}$ Hz" },{ key: "D", text: "$\\approx5.6\\times10^{11}$ Hz" },{ key: "E", text: "$\\approx1.4\\times10^{7}$ Hz" }],
    answer: "C", solution: "$f=\\dfrac{eB}{2\\pi m_e}=\\dfrac{1.6\\times10^{-19}\\times0.5}{2\\pi\\times9.1\\times10^{-31}}\\approx1.4\\times10^{10}$ Hz — independent of speed (until relativistic)." },
  { id: "bpho-s1-b-032", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 4,
    question: "A square conducting loop of side $L$ moves at constant speed $v$ fully into a uniform field $B$ (perpendicular to the loop). While entering, the induced e.m.f. is $BLv$. Once the loop is entirely inside the field, the induced e.m.f. is",
    options: [{ key: "A", text: "$\\dfrac{BLv}{2}$" },{ key: "B", text: "$BL^2v$" },{ key: "C", text: "$2BLv$" },{ key: "D", text: "$0$" },{ key: "E", text: "$BLv$" }],
    answer: "D", solution: "Once fully inside, the enclosed flux is constant ($BL^2$), so $\\dfrac{d\\Phi}{dt}=0$ and the e.m.f. is zero. Only the entering/leaving edges cutting field lines produce e.m.f." },
  { id: "bpho-s1-b-033", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 5,
    question: "A copper wire of cross-section $1.0\\ \\mathrm{mm^2}$ carries $5.0$ A. With $n=8.5\\times10^{28}\\ \\mathrm{m^{-3}}$ free electrons and $e=1.6\\times10^{-19}$ C, estimate the electron drift speed.",
    options: [{ key: "A", text: "$\\approx5.0\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$\\approx3.7\\times10^{-4}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$\\approx1.0\\times10^{-3}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$\\approx3.7\\times10^{-7}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$\\approx3.7\\times10^{-2}\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "B", solution: "$v_d=\\dfrac{I}{nAe}=\\dfrac{5.0}{8.5\\times10^{28}\\times10^{-6}\\times1.6\\times10^{-19}}\\approx3.7\\times10^{-4}\\ \\mathrm{m\\,s^{-1}}$ — remarkably slow, yet signals travel near light speed." },
  { id: "bpho-s1-b-034", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 4,
    question: "A potential divider of two equal $10\\ \\mathrm{k\\Omega}$ resistors is connected across $12$ V. A load of $10\\ \\mathrm{k\\Omega}$ is connected across the lower resistor. Find the output voltage across the load.",
    options: [{ key: "A", text: "$3.0$ V" },{ key: "B", text: "$8.0$ V" },{ key: "C", text: "$4.0$ V" },{ key: "D", text: "$6.0$ V" },{ key: "E", text: "$5.0$ V" }],
    answer: "C", solution: "Lower resistor $\\parallel$ load $=5\\ \\mathrm{k\\Omega}$. Divider: $V=12\\times\\dfrac{5}{10+5}=4.0$ V (loading pulls it below the unloaded $6$ V)." },
  { id: "bpho-s1-b-035", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 4,
    question: "Resistors of $2.0\\ \\Omega$ and $3.0\\ \\Omega$ are connected in parallel across a $6.0$ V ideal supply. Find the total power dissipated.",
    options: [{ key: "A", text: "$18$ W" },{ key: "B", text: "$12$ W" },{ key: "C", text: "$7.2$ W" },{ key: "D", text: "$30$ W" },{ key: "E", text: "$60$ W" }],
    answer: "D", solution: "$R_{\\parallel}=\\dfrac{2\\cdot3}{5}=1.2\\ \\Omega$. $P=\\dfrac{V^2}{R}=\\dfrac{36}{1.2}=30$ W. (Or sum $18+12$.)" },
  { id: "bpho-s1-b-036", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 4,
    question: "An electron enters a region of uniform electric field $E$ perpendicular to its velocity $v$, travelling a horizontal distance $L$ through the field. Its vertical deflection on leaving is proportional to",
    options: [{ key: "A", text: "$\\dfrac{EL^2}{v}$" },{ key: "B", text: "$\\dfrac{EL}{v}$" },{ key: "C", text: "$\\dfrac{E v^2}{L}$" },{ key: "D", text: "$\\dfrac{EL^2}{v^2}$" },{ key: "E", text: "$\\dfrac{E L}{v^2}$" }],
    answer: "D", solution: "Time in field $t=L/v$; vertical deflection $y=\\tfrac12 a t^2=\\tfrac12\\dfrac{eE}{m}\\dfrac{L^2}{v^2}\\propto\\dfrac{EL^2}{v^2}$ (parabolic path, like projectile motion)." },
  { id: "bpho-s1-b-037", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 3, marks: 4,
    question: "An ideal monatomic gas expands adiabatically. Its pressure and volume obey $pV^\\gamma=$ const with $\\gamma=\\dfrac53$. If the volume doubles, the pressure falls to what fraction of its original value?",
    options: [{ key: "A", text: "$2^{-2/3}\\approx0.63$" },{ key: "B", text: "$\\dfrac14$" },{ key: "C", text: "$\\dfrac12$" },{ key: "D", text: "$2^{-1}$" },{ key: "E", text: "$2^{-5/3}\\approx0.31$" }],
    answer: "E", solution: "$p\\propto V^{-\\gamma}$: doubling $V$ gives $p\\to p\\cdot2^{-5/3}\\approx0.31p$ — falls faster than isothermal ($2^{-1}$) because the gas also cools." },
  { id: "bpho-s1-b-038", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 3, marks: 4,
    question: "One mole of an ideal gas expands isothermally at $300$ K to twice its volume. Find the work done by the gas. ($R=8.31$, $\\ln2=0.693$)",
    options: [{ key: "A", text: "$\\approx2.5\\times10^{3}$ J" },{ key: "B", text: "$\\approx8.6\\times10^{2}$ J" },{ key: "C", text: "$\\approx1.2\\times10^{3}$ J" },{ key: "D", text: "$\\approx3.5\\times10^{3}$ J" },{ key: "E", text: "$\\approx1.7\\times10^{3}$ J" }],
    answer: "E", solution: "$W=nRT\\ln\\dfrac{V_2}{V_1}=1\\times8.31\\times300\\times\\ln2\\approx1.7\\times10^3$ J." },
  { id: "bpho-s1-b-039", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 3, marks: 4,
    question: "Estimate the r.m.s. speed of nitrogen molecules (mass $4.8\\times10^{-26}$ kg) at $300$ K. ($k_B=1.38\\times10^{-23}$)",
    options: [{ key: "A", text: "$\\approx340\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$\\approx50\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$\\approx510\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$\\approx1500\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$\\approx170\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "C", solution: "$v_{rms}=\\sqrt{\\dfrac{3k_BT}{m}}=\\sqrt{\\dfrac{3\\times1.38\\times10^{-23}\\times300}{4.8\\times10^{-26}}}\\approx510\\ \\mathrm{m\\,s^{-1}}$ (comparable to the speed of sound in air)." },
  { id: "bpho-s1-b-040", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 2, marks: 4,
    question: "How much energy is needed to melt $0.10$ kg of ice at $0\\ ^\\circ$C? (Specific latent heat of fusion $=3.34\\times10^{5}\\ \\mathrm{J\\,kg^{-1}}$)",
    options: [{ key: "A", text: "$\\approx3.3\\times10^{3}$ J" },{ key: "B", text: "$\\approx3.3\\times10^{4}$ J" },{ key: "C", text: "$\\approx3.3\\times10^{5}$ J" },{ key: "D", text: "$\\approx3.34$ J" },{ key: "E", text: "$\\approx6.7\\times10^{4}$ J" }],
    answer: "B", solution: "$Q=mL=0.10\\times3.34\\times10^5=3.34\\times10^4$ J." },
  { id: "bpho-s1-b-041", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 3, marks: 4,
    question: "Using Wien's law ($\\lambda_{\\max}T=2.9\\times10^{-3}\\ \\mathrm{m\\,K}$), estimate the peak-emission wavelength of the Sun's surface at $5800$ K.",
    options: [{ key: "A", text: "$\\approx500$ nm" },{ key: "B", text: "$\\approx5000$ nm" },{ key: "C", text: "$\\approx290$ nm" },{ key: "D", text: "$\\approx1000$ nm" },{ key: "E", text: "$\\approx50$ nm" }],
    answer: "A", solution: "$\\lambda_{\\max}=\\dfrac{2.9\\times10^{-3}}{5800}\\approx5.0\\times10^{-7}$ m $=500$ nm — green, the peak of human eye sensitivity." },
  { id: "bpho-s1-b-042", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 3, marks: 4,
    question: "The pressure of an ideal gas is $p=\\tfrac13\\rho\\langle c^2\\rangle$. If the absolute temperature is doubled at constant volume, the r.m.s. molecular speed changes by a factor of",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "unchanged" },{ key: "C", text: "$4$" },{ key: "D", text: "$\\dfrac{1}{\\sqrt2}$" },{ key: "E", text: "$\\sqrt{2}$" }],
    answer: "E", solution: "$\\langle c^2\\rangle\\propto T$ so $c_{rms}\\propto\\sqrt T$; doubling $T$ multiplies $c_{rms}$ by $\\sqrt2$." },
  { id: "bpho-s1-b-043", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 2, marks: 4,
    question: "In a photoelectric experiment, photons of energy $3.0$ eV eject electrons from a metal of work function $2.0$ eV. Find the stopping voltage.",
    options: [{ key: "A", text: "$2.0$ V" },{ key: "B", text: "$0.5$ V" },{ key: "C", text: "$5.0$ V" },{ key: "D", text: "$3.0$ V" },{ key: "E", text: "$1.0$ V" }],
    answer: "E", solution: "$eV_s=hf-\\phi=(3.0-2.0)\\ \\mathrm{eV}=1.0$ eV, so $V_s=1.0$ V (stopping voltage in volts equals max KE in eV per electron)." },
  { id: "bpho-s1-b-044", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 4,
    question: "The radius of the $n$th Bohr orbit in hydrogen scales as $r_n\\propto n^2$. Find the ratio of the radius of the $n=3$ orbit to the $n=1$ (ground) orbit.",
    options: [{ key: "A", text: "$\\dfrac13$" },{ key: "B", text: "$9$" },{ key: "C", text: "$3$" },{ key: "D", text: "$6$" },{ key: "E", text: "$27$" }],
    answer: "B", solution: "$r_n\\propto n^2$: ratio $=3^2=9$." },
  { id: "bpho-s1-b-045", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 2, marks: 4,
    question: "A radioactive nuclide has a half-life of $6.0$ hours. What fraction of a sample remains after $24$ hours?",
    options: [{ key: "A", text: "$\\dfrac{1}{4}$" },{ key: "B", text: "$\\dfrac{1}{16}$" },{ key: "C", text: "$\\dfrac18$" },{ key: "D", text: "$\\dfrac{1}{32}$" },{ key: "E", text: "$\\dfrac14$" }],
    answer: "B", solution: "$24/6=4$ half-lives: fraction $=(1/2)^4=1/16$." },
  { id: "bpho-s1-b-046", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 4,
    question: "The mass defect when a deuteron forms from a proton and neutron is $0.0024$ u. Find the binding energy. ($1$ u $=931.5$ MeV$/c^2$)",
    options: [{ key: "A", text: "$\\approx0.0024$ MeV" },{ key: "B", text: "$\\approx931$ MeV" },{ key: "C", text: "$\\approx22$ MeV" },{ key: "D", text: "$\\approx2.2$ MeV" },{ key: "E", text: "$\\approx0.22$ MeV" }],
    answer: "D", solution: "$E=\\Delta m\\,c^2=0.0024\\times931.5\\approx2.2$ MeV." },
  { id: "bpho-s1-b-047", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 2, marks: 4,
    question: "Using $E(\\mathrm{eV})=\\dfrac{1240}{\\lambda(\\mathrm{nm})}$, find the energy of a photon of wavelength $500$ nm.",
    options: [{ key: "A", text: "$\\approx2.5$ eV" },{ key: "B", text: "$\\approx1.24$ eV" },{ key: "C", text: "$\\approx0.5$ eV" },{ key: "D", text: "$\\approx5.0$ eV" },{ key: "E", text: "$\\approx620$ eV" }],
    answer: "A", solution: "$E=\\dfrac{1240}{500}\\approx2.5$ eV — visible-light photons carry a few eV, comparable to chemical bond energies." },
  { id: "bpho-s1-b-048", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 5,
    question: "Use the uncertainty principle $\\Delta x\\,\\Delta p\\gtrsim\\hbar$ to estimate the minimum momentum uncertainty of an electron confined to an atom ($\\Delta x\\approx1\\times10^{-10}$ m). ($\\hbar=1.05\\times10^{-34}$ J s)",
    options: [{ key: "A", text: "$\\approx1\\times10^{-44}\\ \\mathrm{kg\\,m\\,s^{-1}}$" },{ key: "B", text: "$\\approx1\\times10^{-10}\\ \\mathrm{kg\\,m\\,s^{-1}}$" },{ key: "C", text: "$\\approx1\\times10^{-34}\\ \\mathrm{kg\\,m\\,s^{-1}}$" },{ key: "D", text: "$\\approx1\\times10^{-19}\\ \\mathrm{kg\\,m\\,s^{-1}}$" },{ key: "E", text: "$\\approx1\\times10^{-24}\\ \\mathrm{kg\\,m\\,s^{-1}}$" }],
    answer: "E", solution: "$\\Delta p\\approx\\dfrac{\\hbar}{\\Delta x}=\\dfrac{1.05\\times10^{-34}}{10^{-10}}\\approx1\\times10^{-24}\\ \\mathrm{kg\\,m\\,s^{-1}}$; the corresponding speed (~$10^6\\ \\mathrm{m\\,s^{-1}}$) sets the scale of electron motion in atoms." },
];
