// BPhO Round 1 Section 1 —— 运动学与动力学（打样批）。原创，难度对标官方 Round 1；数值/表达式均经 sympy 双重验证。
import type { MCQQuestion } from "./types";

export const BPHO_KINE_S1: MCQQuestion[] = [
  { id: "bpho-s1-kin-001", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "A stone is thrown vertically upwards at $u = 5\\ \\mathrm{m\\,s^{-1}}$ from the top of a tower of height $30\\ \\mathrm{m}$. Taking $g = 10\\ \\mathrm{m\\,s^{-2}}$, find the total time before it hits the ground at the base of the tower.",
    options: [{ key: "A", text: "$3.0$ s" },{ key: "B", text: "$2.0$ s" },{ key: "C", text: "$2.5$ s" },{ key: "D", text: "$4.0$ s" },{ key: "E", text: "$3.5$ s" }],
    answer: "A", solution: "Taking downwards positive after using $s=ut+\\tfrac12at^2$ with up positive: $-30=5t-5t^2$, so $t^2-t-6=0$, $(t-3)(t+2)=0$, giving $t=3.0$ s. (Alternatively: speed on return to launch height is $5\\ \\mathrm{m\\,s^{-1}}$ downward, then solve the drop.)" },
  { id: "bpho-s1-kin-002", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 6,
    question: "A sled accelerates uniformly from rest at $6\\ \\mathrm{m\\,s^{-2}}$ along a straight test track of length $d$, where brakes stop it in negligible time. It is then towed back to the start at a constant $20\\ \\mathrm{m\\,s^{-1}}$. The total time from launch to arriving back at the start is $25$ s. Find $d$.",
    options: [{ key: "A", text: "$450$ m" },{ key: "B", text: "$300$ m" },{ key: "C", text: "$250$ m" },{ key: "D", text: "$360$ m" },{ key: "E", text: "$200$ m" }],
    answer: "B", solution: "Outward: $d=\\tfrac12\\cdot6t_1^2$ so $t_1=\\sqrt{d/3}$. Return: $t_2=d/20$. Then $\\sqrt{d/3}+d/20=25$. Let $x=\\sqrt{d/3}$: $x + \\tfrac{3x^2}{20}=25$, giving $x=10$, so $d=300$ m (check: $t_1=10$ s, $t_2=15$ s)." },
  { id: "bpho-s1-kin-003", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A river of width $120\\ \\mathrm{m}$ flows at $3\\ \\mathrm{m\\,s^{-1}}$. A boat has speed $5\\ \\mathrm{m\\,s^{-1}}$ in still water. Let $t_1$ be the crossing time when the boat is steered to cross in the shortest possible time, and $t_2$ the time when steered to cross by the shortest possible path. Find $t_2 / t_1$.",
    options: [{ key: "A", text: "$\\dfrac{5}{4}$" },{ key: "B", text: "$\\dfrac{5}{3}$" },{ key: "C", text: "$1$" },{ key: "D", text: "$\\dfrac{3}{5}$" },{ key: "E", text: "$\\dfrac{4}{5}$" }],
    answer: "A", solution: "Shortest time: aim straight across, $t_1 = 120/5 = 24$ s (drift doesn't matter). Shortest path: resultant must point straight across, effective speed $\\sqrt{5^2-3^2}=4\\ \\mathrm{m\\,s^{-1}}$, $t_2=120/4=30$ s. Ratio $=30/24=5/4$." },
  { id: "bpho-s1-kin-004", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "Masses of $3$ kg and $2$ kg hang from the ends of a light string over a light, frictionless pulley. Taking $g=10\\ \\mathrm{m\\,s^{-2}}$, find the tension in the string once the system is released.",
    options: [{ key: "A", text: "$25$ N" },{ key: "B", text: "$12$ N" },{ key: "C", text: "$20$ N" },{ key: "D", text: "$30$ N" },{ key: "E", text: "$24$ N" }],
    answer: "E", solution: "Acceleration $a=\\dfrac{(m_1-m_2)g}{m_1+m_2}=\\dfrac{10}{5}=2\\ \\mathrm{m\\,s^{-2}}$. For the $2$ kg mass: $T-m_2g=m_2a$, so $T=2(10+2)=24$ N. (Note $T\\neq$ average of the weights.)" },
  { id: "bpho-s1-kin-005", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 1, marks: 3,
    question: "A person stands on weighing scales in a lift. The lift accelerates uniformly upwards from rest to $6\\ \\mathrm{m\\,s^{-1}}$ in $3$ s. Taking $g=10\\ \\mathrm{m\\,s^{-2}}$, find the ratio of the scale reading during the acceleration to the reading when the lift is stationary.",
    options: [{ key: "A", text: "$\\dfrac{6}{5}$" },{ key: "B", text: "$\\dfrac{5}{6}$" },{ key: "C", text: "$1$" },{ key: "D", text: "$\\dfrac{4}{5}$" },{ key: "E", text: "$\\dfrac{3}{2}$" }],
    answer: "A", solution: "$a = 6/3 = 2\\ \\mathrm{m\\,s^{-2}}$. Scales read the normal force: $N=m(g+a)$. Ratio $=\\dfrac{g+a}{g}=\\dfrac{12}{10}=\\dfrac65$." },
  { id: "bpho-s1-kin-006", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A car passes a stationary police car at a constant $15\\ \\mathrm{m\\,s^{-1}}$. At that instant the police car starts from rest with uniform acceleration $3\\ \\mathrm{m\\,s^{-2}}$ in pursuit. What is the maximum gap between the two cars before the police car catches up?",
    options: [{ key: "A", text: "$50$ m" },{ key: "B", text: "$25$ m" },{ key: "C", text: "$45$ m" },{ key: "D", text: "$75$ m" },{ key: "E", text: "$37.5$ m" }],
    answer: "E", solution: "The gap grows while the car is faster, and is maximum when speeds are equal: $3t=15$, $t=5$ s. Gap $=15\\cdot5-\\tfrac12\\cdot3\\cdot25=75-37.5=37.5$ m. (Equivalently $v^2/2a$.)" },
  { id: "bpho-s1-kin-007", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "A block is projected up a rough slope inclined at angle $\\theta$, comes to rest, and slides back down to its starting point. The coefficient of friction is $\\mu = \\tfrac12\\tan\\theta$. Find the ratio $t_{\\mathrm{up}} / t_{\\mathrm{down}}$ of the times for the upward and downward journeys.",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$\\dfrac{1}{\\sqrt{3}}$" },{ key: "C", text: "$\\dfrac{1}{3}$" },{ key: "D", text: "$\\dfrac{1}{\\sqrt{2}}$" },{ key: "E", text: "$\\sqrt{3}$" }],
    answer: "B", solution: "Up: $a_{\\mathrm{up}}=g(\\sin\\theta+\\mu\\cos\\theta)=\\tfrac32 g\\sin\\theta$. Down: $a_{\\mathrm{down}}=g(\\sin\\theta-\\mu\\cos\\theta)=\\tfrac12 g\\sin\\theta$. Same distance from rest each way: $s=\\tfrac12 a t^2$ so $t\\propto 1/\\sqrt{a}$, giving $t_{\\mathrm{up}}/t_{\\mathrm{down}}=\\sqrt{a_{\\mathrm{down}}/a_{\\mathrm{up}}}=\\sqrt{1/3}=1/\\sqrt3$." },
  { id: "bpho-s1-kin-008", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A particle moves in a straight line with uniform acceleration. It covers a displacement $s_1$ in the first interval of duration $\\tau$, and $s_2$ in the next interval of the same duration $\\tau$. Find its acceleration.",
    options: [{ key: "A", text: "$\\dfrac{s_1+s_2}{\\tau^2}$" },{ key: "B", text: "$\\dfrac{s_2-s_1}{\\tau^2}$" },{ key: "C", text: "$\\dfrac{2(s_2-s_1)}{\\tau^2}$" },{ key: "D", text: "$\\dfrac{s_2-s_1}{2\\tau^2}$" },{ key: "E", text: "$\\dfrac{s_2}{\\tau^2}$" }],
    answer: "B", solution: "With initial speed $u$: $s_1=u\\tau+\\tfrac12 a\\tau^2$ and $s_1+s_2=2u\\tau+2a\\tau^2$. Subtracting twice the first from the second: $s_2-s_1=a\\tau^2$, so $a=(s_2-s_1)/\\tau^2$ — successive equal-time displacements of a uniformly accelerating body differ by $a\\tau^2$." },
  { id: "bpho-s1-kin-009", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "Ball A is thrown vertically upwards from the ground at $40\\ \\mathrm{m\\,s^{-1}}$ at the same instant that ball B is released from rest at a height of $60$ m directly above. Taking $g=10\\ \\mathrm{m\\,s^{-2}}$, at what height do they meet?",
    options: [{ key: "A", text: "$50.5$ m" },{ key: "B", text: "$55$ m" },{ key: "C", text: "$45$ m" },{ key: "D", text: "$40$ m" },{ key: "E", text: "$48.75$ m" }],
    answer: "E", solution: "In the frame of relative motion, gravity cancels: closing speed is $40\\ \\mathrm{m\\,s^{-1}}$, so they meet at $t=60/40=1.5$ s. Height of A: $40(1.5)-5(1.5)^2=60-11.25=48.75$ m." },
  { id: "bpho-s1-kin-010", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "A parcel is placed gently (at rest) on a conveyor belt moving at $3\\ \\mathrm{m\\,s^{-1}}$. The coefficient of friction between parcel and belt is $0.3$, and $g=10\\ \\mathrm{m\\,s^{-2}}$. What is the length of the scratch mark made by the parcel on the belt (the relative sliding distance) before they move together?",
    options: [{ key: "A", text: "$1.0$ m" },{ key: "B", text: "$3.0$ m" },{ key: "C", text: "$4.5$ m" },{ key: "D", text: "$0.75$ m" },{ key: "E", text: "$1.5$ m" }],
    answer: "E", solution: "Friction accelerates the parcel: $a=\\mu g=3\\ \\mathrm{m\\,s^{-2}}$, reaching belt speed at $t=1$ s. Belt moves $3\\times1=3$ m; parcel moves $\\tfrac12\\cdot3\\cdot1^2=1.5$ m. Relative sliding $=3-1.5=1.5$ m." },
  { id: "bpho-s1-kin-011", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A small ball of mass $m$ hangs at rest from two light strings, each making angle $\\theta$ with the vertical (symmetric about it). One string is suddenly cut. What is the magnitude of the ball's acceleration immediately afterwards?",
    options: [{ key: "A", text: "$\\dfrac{g\\sin\\theta}{\\cos\\theta}+g$" },{ key: "B", text: "$g\\tan\\theta$" },{ key: "C", text: "$g\\sin\\theta$" },{ key: "D", text: "$g\\cos\\theta$" },{ key: "E", text: "$g$" }],
    answer: "C", solution: "Immediately after cutting, the ball moves on a circle about the remaining string's support, so acceleration is purely tangential (speed is still zero, no centripetal term): $a=g\\sin\\theta$. The trap: computing the net of gravity and the *old* tension gives $g\\tan\\theta$, but the tension changes instantly when the other string is cut." },
  { id: "bpho-s1-kin-012", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A bullet travelling at $400\\ \\mathrm{m\\,s^{-1}}$ passes completely through a wooden plank and emerges at $200\\ \\mathrm{m\\,s^{-1}}$. Identical planks are stacked one after another, and the deceleration inside the wood is constant. In which plank does the bullet finally come to rest? (Count the first plank as plank 1.)",
    options: [{ key: "A", text: "Plank 5" },{ key: "B", text: "Plank 4" },{ key: "C", text: "Plank 3" },{ key: "D", text: "It passes through all planks" },{ key: "E", text: "Plank 2" }],
    answer: "E", solution: "With constant deceleration, each plank of thickness $d$ removes the same amount of $v^2$ (since $v^2 = v_0^2 - 2ad$). Plank 1 removed $400^2-200^2=120000$; the bullet has $200^2=40000$ left, which is only $\\tfrac13$ of a plank's worth. So it stops one-third of the way into plank 2." },
  { id: "bpho-s1-kin-013", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "When standing still, a person sees rain falling vertically. When walking at speed $v$, the rain appears to make an angle $\\theta$ with the vertical. What is the speed of the raindrops relative to the ground?",
    options: [{ key: "A", text: "$\\dfrac{v}{\\cos\\theta}$" },{ key: "B", text: "$v\\sin\\theta$" },{ key: "C", text: "$v\\cot\\theta$" },{ key: "D", text: "$v\\tan\\theta$" },{ key: "E", text: "$v$" }],
    answer: "C", solution: "Relative to the walker, the rain gains a horizontal component $v$ (backwards). $\\tan\\theta = \\dfrac{v}{v_{\\mathrm{rain}}}$, so $v_{\\mathrm{rain}} = \\dfrac{v}{\\tan\\theta} = v\\cot\\theta$." },
  { id: "bpho-s1-kin-014", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "An object is released from rest and falls freely. It falls $45$ m during the final second before hitting the ground. Taking $g=10\\ \\mathrm{m\\,s^{-2}}$, from what height was it released?",
    options: [{ key: "A", text: "$125$ m" },{ key: "B", text: "$80$ m" },{ key: "C", text: "$100$ m" },{ key: "D", text: "$145$ m" },{ key: "E", text: "$180$ m" }],
    answer: "A", solution: "Distance in the last second: $\\tfrac12 g t^2 - \\tfrac12 g(t-1)^2 = g t - \\tfrac g2 = 45$, so $10t-5=45$, $t=5$ s. Height $=\\tfrac12\\cdot10\\cdot25=125$ m." },
  { id: "bpho-s1-kin-015", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "A particle moves along the $x$-axis such that its speed is $v = k\\sqrt{x}$, where $k$ is a positive constant. Find its acceleration.",
    options: [{ key: "A", text: "$k^2\\sqrt{x}$" },{ key: "B", text: "$\\dfrac{k}{2\\sqrt{x}}$" },{ key: "C", text: "$\\dfrac{k^2}{2}$ (constant)" },{ key: "D", text: "$k^2 x$" },{ key: "E", text: "$\\dfrac{k^2}{2\\sqrt{x}}$" }],
    answer: "C", solution: "Use $a = \\dfrac{dv}{dt} = v\\dfrac{dv}{dx}$. Here $\\dfrac{dv}{dx} = \\dfrac{k}{2\\sqrt{x}}$, so $a = k\\sqrt{x}\\cdot\\dfrac{k}{2\\sqrt{x}} = \\dfrac{k^2}{2}$ — uniform acceleration in disguise (indeed $v^2=k^2x$ matches $v^2=2ax$ with $a=k^2/2$)." },
];
