// BPhO S1 加厚批 C —— 均衡补五大主题至 200+。原创，逐题程序断言。
import type { MCQQuestion } from "./types";

export const BPHO_S1_C: MCQQuestion[] = [
  { id: "bpho-s1-c-001", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 1, marks: 3,
    question: "A block slides down a frictionless incline at $30°$ to the horizontal ($g=10$). Find its acceleration.",
    options: [{ key: "A", text: "$5.0\\ \\mathrm{m\\,s^{-2}}$" },{ key: "B", text: "$8.7\\ \\mathrm{m\\,s^{-2}}$" },{ key: "C", text: "$0$" },{ key: "D", text: "$2.5\\ \\mathrm{m\\,s^{-2}}$" },{ key: "E", text: "$10\\ \\mathrm{m\\,s^{-2}}$" }],
    answer: "A", solution: "$a=g\\sin\\theta=10\\times0.5=5.0\\ \\mathrm{m\\,s^{-2}}$." },
  { id: "bpho-s1-c-002", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A car travelling at $15\\ \\mathrm{m\\,s^{-1}}$ brakes with the tyres locked; the coefficient of friction is $0.60$ ($g=10$). Find the stopping distance.",
    options: [{ key: "A", text: "$18.75$ m" },{ key: "B", text: "$25$ m" },{ key: "C", text: "$9.4$ m" },{ key: "D", text: "$12.5$ m" },{ key: "E", text: "$37.5$ m" }],
    answer: "A", solution: "$d=\\dfrac{v^2}{2\\mu g}=\\dfrac{225}{2\\times0.6\\times10}=18.75$ m." },
  { id: "bpho-s1-c-003", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A car rounds a frictionless banked curve of radius $50$ m banked at $45°$ ($g=10$). Find the design speed.",
    options: [{ key: "A", text: "$\\sqrt{50}\\approx7.1\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$50\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$500\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$\\sqrt{500}\\approx22\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$\\sqrt{250}\\approx16\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "D", solution: "No friction: $\\tan\\theta=\\dfrac{v^2}{rg}$, so $v=\\sqrt{rg\\tan\\theta}=\\sqrt{50\\times10\\times1}=\\sqrt{500}\\approx22\\ \\mathrm{m\\,s^{-1}}$." },
  { id: "bpho-s1-c-004", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A person of mass $70$ kg climbs a staircase of total height $3.6$ m in $12$ s ($g=10$). Find their average power output against gravity.",
    options: [{ key: "A", text: "$420$ W" },{ key: "B", text: "$2520$ W" },{ key: "C", text: "$25$ W" },{ key: "D", text: "$210$ W" },{ key: "E", text: "$105$ W" }],
    answer: "D", solution: "$P=\\dfrac{mgh}{t}=\\dfrac{70\\times10\\times3.6}{12}=210$ W." },
  { id: "bpho-s1-c-005", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "A force on a $2$ kg body varies with time so that the force–time graph is a triangle: it rises linearly from $0$ to $6$ N over $4$ s then instantly drops to zero. Find the impulse delivered.",
    options: [{ key: "A", text: "$48\\ \\mathrm{N\\,s}$" },{ key: "B", text: "$24\\ \\mathrm{N\\,s}$" },{ key: "C", text: "$12\\ \\mathrm{N\\,s}$" },{ key: "D", text: "$6\\ \\mathrm{N\\,s}$" },{ key: "E", text: "$3\\ \\mathrm{N\\,s}$" }],
    answer: "C", solution: "Impulse = area under $F$–$t$ graph $=\\tfrac12\\times4\\times6=12\\ \\mathrm{N\\,s}$." },
  { id: "bpho-s1-c-006", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A catapult with an ideal spring of stiffness $500\\ \\mathrm{N\\,m^{-1}}$ is drawn back $0.20$ m and launches a $0.20$ kg ball vertically ($g=10$). Neglecting the spring's mass, find the maximum height reached.",
    options: [{ key: "A", text: "$5.0$ m" },{ key: "B", text: "$1.0$ m" },{ key: "C", text: "$25$ m" },{ key: "D", text: "$2.5$ m" },{ key: "E", text: "$10$ m" }],
    answer: "A", solution: "Spring PE $=\\tfrac12kx^2=\\tfrac12\\times500\\times0.04=10$ J $=mgh$, so $h=\\dfrac{10}{0.2\\times10}=5.0$ m." },
  { id: "bpho-s1-c-007", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "Two equal masses collide and stick. Before impact one moves east at $6\\ \\mathrm{m\\,s^{-1}}$, the other north at $8\\ \\mathrm{m\\,s^{-1}}$. Find the speed of the combined mass just after the collision.",
    options: [{ key: "A", text: "$5\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$14\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$\\sqrt{2}\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$7\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$10\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "A", solution: "Each component halves (equal masses stick): $v_x=3$, $v_y=4$, speed $=\\sqrt{3^2+4^2}=5\\ \\mathrm{m\\,s^{-1}}$." },
  { id: "bpho-s1-c-008", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A bucket of water is swung in a vertical circle of radius $2.5$ m ($g=10$). Find the minimum speed at the top so the water stays in.",
    options: [{ key: "A", text: "$7.1\\ \\mathrm{m\\,s^{-1}}$" },{ key: "B", text: "$25\\ \\mathrm{m\\,s^{-1}}$" },{ key: "C", text: "$10\\ \\mathrm{m\\,s^{-1}}$" },{ key: "D", text: "$2.5\\ \\mathrm{m\\,s^{-1}}$" },{ key: "E", text: "$5.0\\ \\mathrm{m\\,s^{-1}}$" }],
    answer: "E", solution: "At the top gravity supplies the centripetal force: $g=\\dfrac{v^2}{r}$, $v=\\sqrt{gr}=\\sqrt{25}=5.0\\ \\mathrm{m\\,s^{-1}}$." },
  { id: "bpho-s1-c-009", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 5,
    question: "Estimate the orbital period of the Moon: orbital radius $3.84\\times10^{8}$ m, Earth mass $6.0\\times10^{24}$ kg, $G=6.67\\times10^{-11}$. Give the answer in days.",
    options: [{ key: "A", text: "$\\approx7$ days" },{ key: "B", text: "$\\approx90$ days" },{ key: "C", text: "$\\approx1$ day" },{ key: "D", text: "$\\approx365$ days" },{ key: "E", text: "$\\approx27$ days" }],
    answer: "E", solution: "$T=2\\pi\\sqrt{r^3/GM}=2\\pi\\sqrt{(3.84\\times10^8)^3/(6.67\\times10^{-11}\\times6\\times10^{24})}\\approx2.4\\times10^6$ s $\\approx27$ days." },
  { id: "bpho-s1-c-010", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A $2.0$ kg block moving at $4.0\\ \\mathrm{m\\,s^{-1}}$ on a frictionless surface hits a fixed spring of stiffness $2000\\ \\mathrm{N\\,m^{-1}}$. Find the maximum compression.",
    options: [{ key: "A", text: "$0.13$ m" },{ key: "B", text: "$0.04$ m" },{ key: "C", text: "$0.20$ m" },{ key: "D", text: "$0.40$ m" },{ key: "E", text: "$0.08$ m" }],
    answer: "A", solution: "$\\tfrac12mv^2=\\tfrac12kx^2$: $x=v\\sqrt{m/k}=4\\sqrt{2/2000}=4\\times0.0316\\approx0.13$ m." },
  { id: "bpho-s1-c-011", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A torque of $12\\ \\mathrm{N\\,m}$ is applied to a uniform disc of mass $2.0$ kg and radius $0.40$ m ($I=\\tfrac12MR^2$). Find its angular acceleration.",
    options: [{ key: "A", text: "$150\\ \\mathrm{rad\\,s^{-2}}$" },{ key: "B", text: "$37.5\\ \\mathrm{rad\\,s^{-2}}$" },{ key: "C", text: "$18.75\\ \\mathrm{rad\\,s^{-2}}$" },{ key: "D", text: "$60\\ \\mathrm{rad\\,s^{-2}}$" },{ key: "E", text: "$75\\ \\mathrm{rad\\,s^{-2}}$" }],
    answer: "E", solution: "$I=\\tfrac12\\times2\\times0.16=0.16\\ \\mathrm{kg\\,m^2}$. $\\alpha=\\tau/I=12/0.16=75\\ \\mathrm{rad\\,s^{-2}}$." },
  { id: "bpho-s1-c-012", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A uniform ladder leans against a smooth (frictionless) wall and a rough floor. Which statement is correct about the forces at the two contacts?",
    options: [{ key: "A", text: "Both wall and floor exert only vertical forces." },{ key: "B", text: "Both exert horizontal forces only." },{ key: "C", text: "The floor exerts only a vertical force." },{ key: "D", text: "The wall exerts only a horizontal force; the floor exerts both vertical and horizontal forces." },{ key: "E", text: "The wall exerts a vertical force; the floor only horizontal." }],
    answer: "D", solution: "A smooth wall can only push perpendicular to itself (horizontal). The rough floor supplies the upward normal force and the horizontal friction that balances the wall's push." },
  { id: "bpho-s1-c-013", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A satellite is raised from a circular orbit of radius $2R$ to one of radius $3R$ (Earth radius $R$). Its total mechanical energy",
    options: [{ key: "A", text: "decreases" },{ key: "B", text: "increases (becomes less negative)" },{ key: "C", text: "becomes zero" },{ key: "D", text: "doubles in magnitude" },{ key: "E", text: "stays the same" }],
    answer: "B", solution: "$E=-\\dfrac{GMm}{2r}$; increasing $r$ makes $E$ less negative, i.e. larger. Raising an orbit requires adding energy." },
  { id: "bpho-s1-c-014", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A block is on the verge of sliding down a rough incline when the angle reaches $30°$. Find the coefficient of static friction.",
    options: [{ key: "A", text: "$\\tan 30°\\approx0.58$" },{ key: "B", text: "$1.0$" },{ key: "C", text: "$0.30$" },{ key: "D", text: "$\\sin30°=0.50$" },{ key: "E", text: "$\\cos30°\\approx0.87$" }],
    answer: "A", solution: "At the point of slipping $\\mu=\\tan\\theta=\\tan30°\\approx0.58$ (the angle of friction)." },
  { id: "bpho-s1-c-015", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "The gravitational potential energy of a mass $m$ at the surface of a planet (radius $R$, mass $M$) is $-\\dfrac{GMm}{R}$. The minimum launch kinetic energy to escape to infinity is",
    options: [{ key: "A", text: "$\\dfrac{GMm}{R^2}$" },{ key: "B", text: "$\\dfrac{2GMm}{R}$" },{ key: "C", text: "$\\dfrac{GMm}{2R}$" },{ key: "D", text: "$\\dfrac{GMm}{R}$" },{ key: "E", text: "$0$" }],
    answer: "D", solution: "Escape needs total energy $\\ge0$: $KE_{\\min}=+\\dfrac{GMm}{R}$ (to cancel the potential well)." },
  { id: "bpho-s1-c-016", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 4,
    question: "A force of $21$ N pushes two blocks ($2$ kg then $5$ kg) that are in contact on a frictionless surface, pushing on the $2$ kg block. Find the contact force between them.",
    options: [{ key: "A", text: "$21$ N" },{ key: "B", text: "$10.5$ N" },{ key: "C", text: "$15$ N" },{ key: "D", text: "$3$ N" },{ key: "E", text: "$6$ N" }],
    answer: "C", solution: "$a=21/7=3\\ \\mathrm{m\\,s^{-2}}$. Contact force accelerates the $5$ kg block: $F=5\\times3=15$ N." },
  { id: "bpho-s1-c-017", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "A constant net force does work on a $2$ kg body, increasing its speed from $2\\ \\mathrm{m\\,s^{-1}}$ to $8\\ \\mathrm{m\\,s^{-1}}$. Find the work done.",
    options: [{ key: "A", text: "$120$ J" },{ key: "B", text: "$60$ J" },{ key: "C", text: "$64$ J" },{ key: "D", text: "$36$ J" },{ key: "E", text: "$30$ J" }],
    answer: "B", solution: "Work–energy: $W=\\tfrac12m(v^2-u^2)=\\tfrac12\\times2\\times(64-4)=60$ J." },
  { id: "bpho-s1-c-018", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "During a crash a $70$ kg passenger decelerates from $20\\ \\mathrm{m\\,s^{-1}}$ to rest in $0.10$ s. Express the average deceleration as a multiple of $g$ ($g=10$).",
    options: [{ key: "A", text: "$20g$" },{ key: "B", text: "$g$" },{ key: "C", text: "$2g$" },{ key: "D", text: "$10g$" },{ key: "E", text: "$200g$" }],
    answer: "A", solution: "$a=\\Delta v/\\Delta t=20/0.10=200\\ \\mathrm{m\\,s^{-2}}=20g$." },
  { id: "bpho-s1-c-019", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 3, marks: 4,
    question: "A $1$ kg ball at $9\\ \\mathrm{m\\,s^{-1}}$ collides head-on and sticks to a stationary $2$ kg ball. Find the kinetic energy converted to heat/deformation.",
    options: [{ key: "A", text: "$40.5$ J" },{ key: "B", text: "$9$ J" },{ key: "C", text: "$27$ J" },{ key: "D", text: "$54$ J" },{ key: "E", text: "$13.5$ J" }],
    answer: "C", solution: "Common speed $=9/3=3\\ \\mathrm{m\\,s^{-1}}$. $\\Delta KE=\\tfrac12(1)(81)-\\tfrac12(3)(9)=40.5-13.5=27$ J." },
  { id: "bpho-s1-c-020", type: "mcq", testId: "bpho", topicId: "bpho-mechanics", difficulty: 2, marks: 3,
    question: "A simple pendulum has length $0.25$ m ($g=10$). Find its period.",
    options: [{ key: "A", text: "$\\approx0.25$ s" },{ key: "B", text: "$\\approx0.5$ s" },{ key: "C", text: "$\\approx1.0$ s" },{ key: "D", text: "$\\approx2.0$ s" },{ key: "E", text: "$\\approx3.1$ s" }],
    answer: "C", solution: "$T=2\\pi\\sqrt{L/g}=2\\pi\\sqrt{0.025}=2\\pi\\times0.158\\approx0.99$ s." },
  { id: "bpho-s1-c-021", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 4,
    question: "A wave of frequency $250$ Hz travels at $340\\ \\mathrm{m\\,s^{-1}}$. Find its wavelength.",
    options: [{ key: "A", text: "$2.72$ m" },{ key: "B", text: "$1.0$ m" },{ key: "C", text: "$1.36$ m" },{ key: "D", text: "$85$ m" },{ key: "E", text: "$0.74$ m" }],
    answer: "C", solution: "$\\lambda=v/f=340/250=1.36$ m." },
  { id: "bpho-s1-c-022", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 3, marks: 4,
    question: "In Young's double-slit experiment the fringe spacing is $2.0$ mm. If the screen distance is doubled and the slit separation is halved, the new fringe spacing is",
    options: [{ key: "A", text: "$0.5$ mm" },{ key: "B", text: "$8.0$ mm" },{ key: "C", text: "$1.0$ mm" },{ key: "D", text: "$4.0$ mm" },{ key: "E", text: "$2.0$ mm" }],
    answer: "B", solution: "$w=\\dfrac{\\lambda D}{d}$: doubling $D$ and halving $d$ multiplies $w$ by $4$: $2.0\\times4=8.0$ mm." },
  { id: "bpho-s1-c-023", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 4,
    question: "Find the critical angle for total internal reflection at a water–air boundary ($n_{\\text{water}}=1.33$).",
    options: [{ key: "A", text: "$\\approx60°$" },{ key: "B", text: "$\\approx49°$" },{ key: "C", text: "$\\approx33°$" },{ key: "D", text: "$\\approx42°$" },{ key: "E", text: "$\\approx24°$" }],
    answer: "B", solution: "$\\sin C=1/n=1/1.33=0.752$, $C\\approx48.8°\\approx49°$." },
  { id: "bpho-s1-c-024", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 3,
    question: "Sound travels from air into water. Which quantity stays the same?",
    options: [{ key: "A", text: "both speed and wavelength" },{ key: "B", text: "speed" },{ key: "C", text: "frequency" },{ key: "D", text: "wavelength" },{ key: "E", text: "amplitude" }],
    answer: "C", solution: "Crossing a boundary, frequency is fixed by the source; speed and wavelength both change ($v=f\\lambda$)." },
  { id: "bpho-s1-c-025", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 1, marks: 3,
    question: "Two strings sound notes of $256$ Hz and $260$ Hz together. Find the beat frequency.",
    options: [{ key: "A", text: "$4$ Hz" },{ key: "B", text: "$516$ Hz" },{ key: "C", text: "$8$ Hz" },{ key: "D", text: "$2$ Hz" },{ key: "E", text: "$258$ Hz" }],
    answer: "A", solution: "Beat frequency $=|f_1-f_2|=4$ Hz." },
  { id: "bpho-s1-c-026", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 3, marks: 4,
    question: "A source of sound moves away from a stationary observer at $34\\ \\mathrm{m\\,s^{-1}}$; the speed of sound is $340\\ \\mathrm{m\\,s^{-1}}$. The observed frequency is what fraction of the emitted frequency?",
    options: [{ key: "A", text: "$\\dfrac{11}{10}$" },{ key: "B", text: "$\\dfrac{1}{10}$" },{ key: "C", text: "$\\dfrac{10}{11}$" },{ key: "D", text: "$\\dfrac{9}{10}$" },{ key: "E", text: "$1$" }],
    answer: "C", solution: "Receding source: $f'=f\\dfrac{v}{v+v_s}=f\\dfrac{340}{374}=\\dfrac{10}{11}f$." },
  { id: "bpho-s1-c-027", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 4,
    question: "A pipe closed at one end has length $L$. Its fundamental wavelength is",
    options: [{ key: "A", text: "$4L$" },{ key: "B", text: "$\\dfrac{L}{2}$" },{ key: "C", text: "$2L$" },{ key: "D", text: "$L$" },{ key: "E", text: "$\\dfrac{L}{4}$" }],
    answer: "A", solution: "Closed pipe: node at closed end, antinode at open end $\\Rightarrow L=\\lambda/4$, so $\\lambda=4L$." },
  { id: "bpho-s1-c-028", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 3, marks: 4,
    question: "Two coherent waves of equal amplitude interfere constructively. The resulting intensity compared with one wave alone is",
    options: [{ key: "A", text: "the same" },{ key: "B", text: "$8$ times" },{ key: "C", text: "$\\sqrt2$ times" },{ key: "D", text: "$4$ times" },{ key: "E", text: "$2$ times" }],
    answer: "D", solution: "Amplitudes add ($2A$); intensity $\\propto$ amplitude$^2$, so $\\times4$. (Energy conservation is maintained because destructive regions elsewhere have zero intensity.)" },
  { id: "bpho-s1-c-029", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 3,
    question: "A progressive wave has amplitude $A$. What is the total distance travelled by a particle of the medium in one full period?",
    options: [{ key: "A", text: "$A$" },{ key: "B", text: "$2A$" },{ key: "C", text: "$4A$" },{ key: "D", text: "$0$" },{ key: "E", text: "$8A$" }],
    answer: "C", solution: "In one period the particle goes $A$ up, $2A$ down, $A$ up = total path $4A$ (displacement returns to zero)." },
  { id: "bpho-s1-c-030", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 3, marks: 4,
    question: "Light of wavelength $600$ nm in vacuum enters glass of refractive index $1.5$. Its wavelength in the glass is",
    options: [{ key: "A", text: "$900$ nm" },{ key: "B", text: "$450$ nm" },{ key: "C", text: "$300$ nm" },{ key: "D", text: "$400$ nm" },{ key: "E", text: "$600$ nm" }],
    answer: "D", solution: "$\\lambda_{\\text{glass}}=\\lambda_0/n=600/1.5=400$ nm (frequency unchanged, speed drops)." },
  { id: "bpho-s1-c-031", type: "mcq", testId: "bpho", topicId: "bpho-waves", difficulty: 2, marks: 3,
    question: "For a stationary wave, the distance between two adjacent nodes is",
    options: [{ key: "A", text: "$\\lambda$" },{ key: "B", text: "$\\dfrac{\\lambda}{4}$" },{ key: "C", text: "$2\\lambda$" },{ key: "D", text: "$\\dfrac{3\\lambda}{2}$" },{ key: "E", text: "$\\dfrac{\\lambda}{2}$" }],
    answer: "E", solution: "Adjacent nodes are half a wavelength apart." },
  { id: "bpho-s1-c-032", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 1, marks: 3,
    question: "Resistors of $6\\ \\Omega$ and $3\\ \\Omega$ are connected in parallel. Find the equivalent resistance.",
    options: [{ key: "A", text: "$18\\ \\Omega$" },{ key: "B", text: "$4.5\\ \\Omega$" },{ key: "C", text: "$1\\ \\Omega$" },{ key: "D", text: "$9\\ \\Omega$" },{ key: "E", text: "$2\\ \\Omega$" }],
    answer: "E", solution: "$\\dfrac1R=\\dfrac16+\\dfrac13=\\dfrac12$, so $R=2\\ \\Omega$." },
  { id: "bpho-s1-c-033", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 1, marks: 3,
    question: "Find the charge stored on a $100\\ \\mu\\mathrm{F}$ capacitor charged to $12$ V.",
    options: [{ key: "A", text: "$12\\ \\mathrm{mC}$" },{ key: "B", text: "$1.2\\ \\mu\\mathrm{C}$" },{ key: "C", text: "$0.12\\ \\mathrm{mC}$" },{ key: "D", text: "$8.3\\ \\mathrm{mC}$" },{ key: "E", text: "$1.2\\ \\mathrm{mC}$" }],
    answer: "E", solution: "$Q=CV=100\\times10^{-6}\\times12=1.2\\times10^{-3}$ C $=1.2$ mC." },
  { id: "bpho-s1-c-034", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 3,
    question: "Two parallel plates $2.0$ cm apart have a potential difference of $5.0$ kV. Find the electric field between them.",
    options: [{ key: "A", text: "$2.5\\times10^{3}\\ \\mathrm{V\\,m^{-1}}$" },{ key: "B", text: "$1.0\\times10^{5}\\ \\mathrm{V\\,m^{-1}}$" },{ key: "C", text: "$1.0\\times10^{4}\\ \\mathrm{V\\,m^{-1}}$" },{ key: "D", text: "$5.0\\times10^{5}\\ \\mathrm{V\\,m^{-1}}$" },{ key: "E", text: "$2.5\\times10^{5}\\ \\mathrm{V\\,m^{-1}}$" }],
    answer: "E", solution: "$E=V/d=5000/0.02=2.5\\times10^5\\ \\mathrm{V\\,m^{-1}}$." },
  { id: "bpho-s1-c-035", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 4,
    question: "A proton moves at $3.0\\times10^{7}\\ \\mathrm{m\\,s^{-1}}$ perpendicular to a $0.20$ T field ($e=1.6\\times10^{-19}$ C). Find the magnetic force on it.",
    options: [{ key: "A", text: "$\\approx6.0\\times10^{-13}$ N" },{ key: "B", text: "$\\approx1.6\\times10^{-13}$ N" },{ key: "C", text: "$\\approx9.6\\times10^{-13}$ N" },{ key: "D", text: "$\\approx3.2\\times10^{-12}$ N" },{ key: "E", text: "$\\approx9.6\\times10^{-15}$ N" }],
    answer: "C", solution: "$F=qvB=1.6\\times10^{-19}\\times3\\times10^7\\times0.2\\approx9.6\\times10^{-13}$ N." },
  { id: "bpho-s1-c-036", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 4,
    question: "Find the energy stored in a $200\\ \\mu\\mathrm{F}$ capacitor charged to $50$ V.",
    options: [{ key: "A", text: "$0.25$ J" },{ key: "B", text: "$0.025$ J" },{ key: "C", text: "$2.5$ J" },{ key: "D", text: "$5.0$ J" },{ key: "E", text: "$0.50$ J" }],
    answer: "A", solution: "$E=\\tfrac12CV^2=\\tfrac12\\times200\\times10^{-6}\\times2500=0.25$ J." },
  { id: "bpho-s1-c-037", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 3,
    question: "A resistor dissipates $60$ W when connected to a supply, and its resistance is $15\\ \\Omega$. Find the current through it.",
    options: [{ key: "A", text: "$2.0$ A" },{ key: "B", text: "$1.0$ A" },{ key: "C", text: "$8.0$ A" },{ key: "D", text: "$4.0$ A" },{ key: "E", text: "$0.5$ A" }],
    answer: "A", solution: "$P=I^2R$: $I=\\sqrt{P/R}=\\sqrt{60/15}=2.0$ A." },
  { id: "bpho-s1-c-038", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 4,
    question: "Two point charges $+q$ and $+q$ are separated by $d$. At the midpoint the electric field and the electric potential are, respectively,",
    options: [{ key: "A", text: "non-zero field, zero potential" },{ key: "B", text: "non-zero field, non-zero potential" },{ key: "C", text: "zero field, zero potential" },{ key: "D", text: "zero field, non-zero potential" },{ key: "E", text: "both infinite" }],
    answer: "D", solution: "By symmetry the two fields cancel (zero field), but potentials are scalars and add: $V=2\\times\\dfrac{kq}{d/2}\\ne0$." },
  { id: "bpho-s1-c-039", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 4,
    question: "A solenoid has $1000$ turns per metre and carries $2.0$ A ($\\mu_0=4\\pi\\times10^{-7}$). Find the magnetic field inside it.",
    options: [{ key: "A", text: "$\\approx2.5\\times10^{-3}$ T" },{ key: "B", text: "$\\approx2.5\\times10^{-1}$ T" },{ key: "C", text: "$\\approx1.3\\times10^{-3}$ T" },{ key: "D", text: "$\\approx2.5\\times10^{-6}$ T" },{ key: "E", text: "$\\approx8.0\\times10^{-3}$ T" }],
    answer: "A", solution: "$B=\\mu_0 nI=4\\pi\\times10^{-7}\\times1000\\times2\\approx2.5\\times10^{-3}$ T." },
  { id: "bpho-s1-c-040", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 3,
    question: "A potential divider has a $10\\ \\mathrm{k\\Omega}$ and a $20\\ \\mathrm{k\\Omega}$ resistor in series across $9.0$ V (no load). Find the voltage across the $20\\ \\mathrm{k\\Omega}$ resistor.",
    options: [{ key: "A", text: "$4.5$ V" },{ key: "B", text: "$1.5$ V" },{ key: "C", text: "$9.0$ V" },{ key: "D", text: "$6.0$ V" },{ key: "E", text: "$3.0$ V" }],
    answer: "D", solution: "$V=9\\times\\dfrac{20}{30}=6.0$ V." },
  { id: "bpho-s1-c-041", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 2, marks: 4,
    question: "Find the time constant of a circuit with a $470\\ \\mathrm{k\\Omega}$ resistor and a $2.2\\ \\mu\\mathrm{F}$ capacitor.",
    options: [{ key: "A", text: "$\\approx10$ s" },{ key: "B", text: "$\\approx100$ s" },{ key: "C", text: "$\\approx0.1$ s" },{ key: "D", text: "$\\approx1.0$ s" },{ key: "E", text: "$\\approx0.01$ s" }],
    answer: "D", solution: "$\\tau=RC=470\\times10^3\\times2.2\\times10^{-6}\\approx1.0$ s." },
  { id: "bpho-s1-c-042", type: "mcq", testId: "bpho", topicId: "bpho-em", difficulty: 3, marks: 4,
    question: "An ideal transformer has $1200$ turns on the primary and $100$ turns on the secondary. The primary is connected to $240$ V a.c. Find the secondary voltage.",
    options: [{ key: "A", text: "$2880$ V" },{ key: "B", text: "$120$ V" },{ key: "C", text: "$20$ V" },{ key: "D", text: "$240$ V" },{ key: "E", text: "$12$ V" }],
    answer: "C", solution: "$\\dfrac{V_s}{V_p}=\\dfrac{N_s}{N_p}$: $V_s=240\\times\\dfrac{100}{1200}=20$ V." },
  { id: "bpho-s1-c-043", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 1, marks: 3,
    question: "How much energy is needed to heat $0.50$ kg of water by $30\\ ^\\circ$C? ($c=4200\\ \\mathrm{J\\,kg^{-1}\\,K^{-1}}$)",
    options: [{ key: "A", text: "$6.3\\times10^{4}$ J" },{ key: "B", text: "$6.3\\times10^{5}$ J" },{ key: "C", text: "$1.26\\times10^{5}$ J" },{ key: "D", text: "$6.3\\times10^{3}$ J" },{ key: "E", text: "$2.1\\times10^{3}$ J" }],
    answer: "A", solution: "$Q=mc\\Delta T=0.5\\times4200\\times30=6.3\\times10^4$ J." },
  { id: "bpho-s1-c-044", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 2, marks: 4,
    question: "An ideal gas at $27\\ ^\\circ$C is heated at constant pressure until its volume doubles. Find its final temperature.",
    options: [{ key: "A", text: "$600\\ ^\\circ$C" },{ key: "B", text: "$273\\ ^\\circ$C" },{ key: "C", text: "$54\\ ^\\circ$C" },{ key: "D", text: "$327\\ ^\\circ$C" },{ key: "E", text: "$150\\ ^\\circ$C" }],
    answer: "D", solution: "Constant $p$: $V\\propto T$ (in kelvin). $T_1=300$ K, doubling gives $600$ K $=327\\ ^\\circ$C. (Doubling $27\\ ^\\circ$C is wrong—must use kelvin.)" },
  { id: "bpho-s1-c-045", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 2, marks: 4,
    question: "A fixed mass of gas at $300$ K and $100$ kPa is cooled at constant volume to $150$ K. Find the new pressure.",
    options: [{ key: "A", text: "$150$ kPa" },{ key: "B", text: "$200$ kPa" },{ key: "C", text: "$50$ kPa" },{ key: "D", text: "$100$ kPa" },{ key: "E", text: "$25$ kPa" }],
    answer: "C", solution: "Constant $V$: $p\\propto T$. Halving $T$ (300→150 K) halves $p$: $50$ kPa." },
  { id: "bpho-s1-c-046", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 3, marks: 4,
    question: "Find the average translational kinetic energy of a gas molecule at $300$ K. ($k_B=1.38\\times10^{-23}$)",
    options: [{ key: "A", text: "$\\approx6.2\\times10^{-21}$ J" },{ key: "B", text: "$\\approx2.1\\times10^{-21}$ J" },{ key: "C", text: "$\\approx1.2\\times10^{-20}$ J" },{ key: "D", text: "$\\approx4.1\\times10^{-21}$ J" },{ key: "E", text: "$\\approx6.2\\times10^{-23}$ J" }],
    answer: "A", solution: "$\\langle E_k\\rangle=\\tfrac32k_BT=\\tfrac32\\times1.38\\times10^{-23}\\times300\\approx6.2\\times10^{-21}$ J." },
  { id: "bpho-s1-c-047", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 2, marks: 3,
    question: "A heat engine takes in $800$ J per cycle from a source at $500$ K and rejects heat to a sink at $250$ K. Find the maximum work it can do per cycle.",
    options: [{ key: "A", text: "$160$ J" },{ key: "B", text: "$400$ J" },{ key: "C", text: "$500$ J" },{ key: "D", text: "$250$ J" },{ key: "E", text: "$800$ J" }],
    answer: "B", solution: "$\\eta_{\\max}=1-250/500=0.5$; $W_{\\max}=0.5\\times800=400$ J." },
  { id: "bpho-s1-c-048", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 3, marks: 4,
    question: "When an ideal gas is compressed adiabatically, its temperature",
    options: [{ key: "A", text: "depends on the gas" },{ key: "B", text: "falls" },{ key: "C", text: "first rises then falls" },{ key: "D", text: "rises" },{ key: "E", text: "stays the same" }],
    answer: "D", solution: "Adiabatic ($Q=0$): work done ON the gas increases its internal energy, so temperature rises (no heat escapes). This is why a bicycle pump warms up." },
  { id: "bpho-s1-c-049", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 2, marks: 4,
    question: "A $2.0$ kW kettle heats water. Ignoring losses, how long does it take to boil away (vaporise) $0.10$ kg of water already at $100\\ ^\\circ$C? ($L_v=2.3\\times10^{6}\\ \\mathrm{J\\,kg^{-1}}$)",
    options: [{ key: "A", text: "$\\approx23$ s" },{ key: "B", text: "$\\approx460$ s" },{ key: "C", text: "$\\approx12$ s" },{ key: "D", text: "$\\approx115$ s" },{ key: "E", text: "$\\approx1150$ s" }],
    answer: "D", solution: "$Q=mL_v=0.1\\times2.3\\times10^6=2.3\\times10^5$ J. $t=Q/P=2.3\\times10^5/2000=115$ s." },
  { id: "bpho-s1-c-050", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 3, marks: 3,
    question: "For a fixed mass of ideal gas, the quantity $\\dfrac{pV}{T}$ is",
    options: [{ key: "A", text: "proportional to $V$" },{ key: "B", text: "proportional to $T$" },{ key: "C", text: "proportional to $p$" },{ key: "D", text: "zero" },{ key: "E", text: "constant" }],
    answer: "E", solution: "The ideal gas law $pV=nRT$ gives $\\dfrac{pV}{T}=nR=$ constant for fixed amount of gas." },
  { id: "bpho-s1-c-051", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 2, marks: 4,
    question: "The r.m.s. speed of a gas at $1200$ K compared with the same gas at $300$ K is larger by a factor of",
    options: [{ key: "A", text: "$16$" },{ key: "B", text: "$\\sqrt2$" },{ key: "C", text: "$8$" },{ key: "D", text: "$2$" },{ key: "E", text: "$4$" }],
    answer: "D", solution: "$v_{rms}\\propto\\sqrt T$: factor $=\\sqrt{1200/300}=\\sqrt4=2$." },
  { id: "bpho-s1-c-052", type: "mcq", testId: "bpho", topicId: "bpho-thermal", difficulty: 3, marks: 4,
    question: "A black body of surface area $1.0\\ \\mathrm{m^2}$ is at $300$ K. Find the power it radiates. ($\\sigma=5.67\\times10^{-8}$)",
    options: [{ key: "A", text: "$\\approx4600$ W" },{ key: "B", text: "$\\approx17$ W" },{ key: "C", text: "$\\approx46$ W" },{ key: "D", text: "$\\approx170$ W" },{ key: "E", text: "$\\approx460$ W" }],
    answer: "E", solution: "$P=\\sigma A T^4=5.67\\times10^{-8}\\times1\\times300^4\\approx460$ W." },
  { id: "bpho-s1-c-053", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 2, marks: 4,
    question: "Find the energy of a photon of frequency $5.0\\times10^{14}$ Hz. ($h=6.63\\times10^{-34}$)",
    options: [{ key: "A", text: "$\\approx3.3\\times10^{-19}$ J" },{ key: "B", text: "$\\approx1.3\\times10^{-19}$ J" },{ key: "C", text: "$\\approx3.3\\times10^{-48}$ J" },{ key: "D", text: "$\\approx6.6\\times10^{-19}$ J" },{ key: "E", text: "$\\approx3.3\\times10^{-20}$ J" }],
    answer: "A", solution: "$E=hf=6.63\\times10^{-34}\\times5\\times10^{14}\\approx3.3\\times10^{-19}$ J ($\\approx2.1$ eV)." },
  { id: "bpho-s1-c-054", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 2, marks: 4,
    question: "Cobalt-60 has a half-life of about $5.3$ years. After approximately $16$ years, the fraction remaining is closest to",
    options: [{ key: "A", text: "$\\dfrac14$" },{ key: "B", text: "$\\dfrac12$" },{ key: "C", text: "$\\dfrac{1}{8}$" },{ key: "D", text: "$\\dfrac{1}{16}$" },{ key: "E", text: "$\\dfrac{1}{3}$" }],
    answer: "C", solution: "$16/5.3\\approx3$ half-lives, so $(1/2)^3=1/8$." },
  { id: "bpho-s1-c-055", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 4,
    question: "In a nuclear fission event, about $200$ MeV is released per fission. Roughly how many joules is this? ($1$ MeV $=1.6\\times10^{-13}$ J)",
    options: [{ key: "A", text: "$\\approx3.2\\times10^{-11}$ J" },{ key: "B", text: "$\\approx3.2\\times10^{-8}$ J" },{ key: "C", text: "$\\approx200$ J" },{ key: "D", text: "$\\approx1.6\\times10^{-13}$ J" },{ key: "E", text: "$\\approx3.2\\times10^{-13}$ J" }],
    answer: "A", solution: "$200\\times1.6\\times10^{-13}=3.2\\times10^{-11}$ J per fission." },
  { id: "bpho-s1-c-056", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 1, marks: 3,
    question: "Which of these electromagnetic radiations has photons of the highest energy?",
    options: [{ key: "A", text: "microwaves" },{ key: "B", text: "visible light" },{ key: "C", text: "infrared" },{ key: "D", text: "radio waves" },{ key: "E", text: "gamma rays" }],
    answer: "E", solution: "Photon energy $E=hf$ increases with frequency; gamma rays have the highest frequency of the listed options." },
  { id: "bpho-s1-c-057", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 4,
    question: "Find the de Broglie wavelength of an electron moving at $2.0\\times10^{6}\\ \\mathrm{m\\,s^{-1}}$. ($h=6.63\\times10^{-34}$, $m_e=9.11\\times10^{-31}$)",
    options: [{ key: "A", text: "$\\approx3.6\\times10^{-13}$ m" },{ key: "B", text: "$\\approx3.6\\times10^{-7}$ m" },{ key: "C", text: "$\\approx7.3\\times10^{-10}$ m" },{ key: "D", text: "$\\approx3.6\\times10^{-10}$ m" },{ key: "E", text: "$\\approx1.8\\times10^{-10}$ m" }],
    answer: "D", solution: "$\\lambda=h/mv=6.63\\times10^{-34}/(9.11\\times10^{-31}\\times2\\times10^6)\\approx3.6\\times10^{-10}$ m." },
  { id: "bpho-s1-c-058", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 2, marks: 4,
    question: "A hydrogen atom has energy levels $E_n=-13.6/n^2$ eV. The energy needed to ionise a hydrogen atom from its ground state is",
    options: [{ key: "A", text: "$3.4$ eV" },{ key: "B", text: "$27.2$ eV" },{ key: "C", text: "$13.6$ eV" },{ key: "D", text: "$10.2$ eV" },{ key: "E", text: "$1.5$ eV" }],
    answer: "C", solution: "Ionisation from $n=1$ to $n=\\infty$: $\\Delta E=0-(-13.6)=13.6$ eV." },
  { id: "bpho-s1-c-059", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 3, marks: 4,
    question: "The activity of a radioactive source falls from $8000$ Bq to $1000$ Bq in $30$ minutes. Find the half-life.",
    options: [{ key: "A", text: "$15$ minutes" },{ key: "B", text: "$10$ minutes" },{ key: "C", text: "$30$ minutes" },{ key: "D", text: "$3.75$ minutes" },{ key: "E", text: "$5$ minutes" }],
    answer: "B", solution: "$8000\\to1000$ is a factor $8=2^3$, i.e. $3$ half-lives in $30$ min, so $T_{1/2}=10$ min." },
  { id: "bpho-s1-c-060", type: "mcq", testId: "bpho", topicId: "bpho-modern", difficulty: 2, marks: 4,
    question: "A star's surface temperature doubles. Compared with before, the wavelength at which it emits most strongly (Wien's law) becomes",
    options: [{ key: "A", text: "twice as long" },{ key: "B", text: "one quarter as long" },{ key: "C", text: "half as long" },{ key: "D", text: "four times as long" },{ key: "E", text: "unchanged" }],
    answer: "C", solution: "Wien: $\\lambda_{\\max}\\propto1/T$; doubling $T$ halves $\\lambda_{\\max}$ (the star looks bluer)." },
];
