// ENGAA（Engineering Admissions Assessment）题库
// Section 1: 数学 + 理科 选择题 (40 题)
// Section 2: 高难度物理 + 数学 选择题 (20 题)
// 注：2025 年起剑桥改用 ESAT，历年 ENGAA 真题仍有备考价值

import type { MCQQuestion } from "./types";

export const ENGAA_SECTION1_MATH: MCQQuestion[] = [
  {
    id: "engaa-s1m-001",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-math1",
    difficulty: 1,
    marks: 1,
    question: "Simplify $\\dfrac{x^2 - 4}{x^2 - 4x + 4}$.",
    options: [
      { key: "A", text: "$\\dfrac{x+2}{x-2}$" },
      { key: "B", text: "$\\dfrac{x-2}{x+2}$" },
      { key: "C", text: "$\\dfrac{x+2}{x+2}$" },
      { key: "D", text: "$1$" },
    ],
    answer: "A",
    solution: "$x^2-4=(x-2)(x+2)$ and $x^2-4x+4=(x-2)^2$. Ratio $=\\dfrac{(x-2)(x+2)}{(x-2)^2}=\\dfrac{x+2}{x-2}$.",
  },
  {
    id: "engaa-s1m-002",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-math1",
    difficulty: 1,
    marks: 1,
    question: "If $2^x = 8^{y}$ and $x - y = 6$, find $x$.",
    options: [
      { key: "A", text: "$6$" },
      { key: "B", text: "$9$" },
      { key: "C", text: "$12$" },
      { key: "D", text: "$3$" },
    ],
    answer: "B",
    solution: "$2^x=8^y=2^{3y}\\Rightarrow x=3y$. With $x-y=6$: $3y-y=6\\Rightarrow y=3$, $x=9$.",
  },
  {
    id: "engaa-s1m-003",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-math2",
    difficulty: 2,
    marks: 1,
    question: "The gradient of the tangent to $y = x^3 - 3x$ at the point $(2, 2)$ is:",
    options: [
      { key: "A", text: "$3$" },
      { key: "B", text: "$6$" },
      { key: "C", text: "$9$" },
      { key: "D", text: "$12$" },
    ],
    answer: "C",
    solution: "$y'=3x^2-3$. At $x=2$: $y'=12-3=9$.",
  },
  {
    id: "engaa-s1m-004",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-math2",
    difficulty: 2,
    marks: 1,
    question: "Evaluate $\\displaystyle\\int_1^4 \\frac{1}{2\\sqrt{x}}\\,dx$.",
    options: [
      { key: "A", text: "$1$" },
      { key: "B", text: "$\\sqrt{2}$" },
      { key: "C", text: "$2$" },
      { key: "D", text: "$\\dfrac{3}{2}$" },
    ],
    answer: "A",
    solution: "$\\int\\frac{1}{2\\sqrt{x}}dx=\\sqrt{x}+C$. $[\\sqrt{x}]_1^4=\\sqrt{4}-\\sqrt{1}=2-1=1$.",
  },
  {
    id: "engaa-s1m-005",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-math1",
    difficulty: 2,
    marks: 1,
    question: "The equation $3x^2 - 5x + k = 0$ has no real roots. Which of the following must be true?",
    options: [
      { key: "A", text: "$k < \\dfrac{25}{12}$" },
      { key: "B", text: "$k > \\dfrac{25}{12}$" },
      { key: "C", text: "$k > \\dfrac{5}{3}$" },
      { key: "D", text: "$k < \\dfrac{5}{3}$" },
    ],
    answer: "B",
    solution: "Discriminant $<0$: $25-12k<0\\Rightarrow k>\\dfrac{25}{12}$.",
  },
  {
    id: "engaa-s1m-006",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-math2",
    difficulty: 2,
    marks: 1,
    question: "A particle moves so that its position at time $t$ is $x(t) = t^3 - 6t^2 + 9t$. At $t=1$, the particle's acceleration is:",
    options: [
      { key: "A", text: "$-6$" },
      { key: "B", text: "$0$" },
      { key: "C", text: "$3$" },
      { key: "D", text: "$6$" },
    ],
    answer: "A",
    solution: "$\\dot{x}=3t^2-12t+9$, $\\ddot{x}=6t-12$. At $t=1$: $\\ddot{x}=6-12=-6$.",
  },
  {
    id: "engaa-s1m-007",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-math1",
    difficulty: 1,
    marks: 1,
    question: "Which of the following is equivalent to $\\log_a b \\cdot \\log_b c$?",
    options: [
      { key: "A", text: "$\\log_a(b+c)$" },
      { key: "B", text: "$\\log_a c$" },
      { key: "C", text: "$\\log_b(ac)$" },
      { key: "D", text: "$\\log_a b + \\log_a c$" },
    ],
    answer: "B",
    solution: "Using change of base: $\\log_a b\\cdot\\log_b c=\\dfrac{\\ln b}{\\ln a}\\cdot\\dfrac{\\ln c}{\\ln b}=\\dfrac{\\ln c}{\\ln a}=\\log_a c$.",
  },
  {
    id: "engaa-s1m-008",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-math1",
    difficulty: 2,
    marks: 1,
    question: "If $\\cos\\theta + \\sin\\theta = \\sqrt{2}\\cos\\theta$, then $\\tan\\theta$ equals:",
    options: [
      { key: "A", text: "$\\sqrt{2}+1$" },
      { key: "B", text: "$\\sqrt{2}-1$" },
      { key: "C", text: "$1-\\sqrt{2}$" },
      { key: "D", text: "$-1$" },
    ],
    answer: "B",
    solution: "$\\cos\\theta+\\sin\\theta=\\sqrt{2}\\cos\\theta\\Rightarrow\\sin\\theta=(\\sqrt{2}-1)\\cos\\theta\\Rightarrow\\tan\\theta=\\sqrt{2}-1$.",
  },
  {
    id: "engaa-s1m-009",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-math1",
    difficulty: 3,
    marks: 1,
    question: "How many solutions does $|2x - 1| = |x + 3|$ have?",
    options: [
      { key: "A", text: "$0$" },
      { key: "B", text: "$1$" },
      { key: "C", text: "$2$" },
      { key: "D", text: "$3$" },
    ],
    answer: "C",
    solution: "Case 1: $2x-1=x+3\\Rightarrow x=4$. Case 2: $2x-1=-(x+3)\\Rightarrow 3x=-2\\Rightarrow x=-2/3$. Both valid. **2 solutions**.",
  },
  {
    id: "engaa-s1m-010",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-math2",
    difficulty: 3,
    marks: 1,
    question: "The volume of the solid of revolution formed by rotating $y = \\sqrt{x}$ (for $0\\le x\\le 4$) about the $x$-axis is:",
    options: [
      { key: "A", text: "$4\\pi$" },
      { key: "B", text: "$8\\pi$" },
      { key: "C", text: "$16\\pi$" },
      { key: "D", text: "$2\\pi$" },
    ],
    answer: "B",
    solution: "$V=\\pi\\int_0^4(\\sqrt{x})^2\\,dx=\\pi\\int_0^4 x\\,dx=\\pi\\left[\\frac{x^2}{2}\\right]_0^4=\\pi\\cdot 8=8\\pi$.",
  },
];

export const ENGAA_SECTION1_PHYS: MCQQuestion[] = [
  {
    id: "engaa-s1p-001",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-phys1",
    difficulty: 1,
    marks: 1,
    question: "A ball is thrown horizontally at $20\\,\\text{m s}^{-1}$ from a height of $45\\,\\text{m}$. How far horizontally does it travel before hitting the ground? (Take $g = 10\\,\\text{m s}^{-2}$)",
    options: [
      { key: "A", text: "$45\\,\\text{m}$" },
      { key: "B", text: "$60\\,\\text{m}$" },
      { key: "C", text: "$90\\,\\text{m}$" },
      { key: "D", text: "$100\\,\\text{m}$" },
    ],
    answer: "B",
    solution: "Time to fall: $h=\\frac{1}{2}gt^2\\Rightarrow t=\\sqrt{2h/g}=\\sqrt{9}=3\\,\\text{s}$. Horizontal distance: $20\\times 3=60\\,\\text{m}$.",
  },
  {
    id: "engaa-s1p-002",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-phys1",
    difficulty: 1,
    marks: 1,
    question: "A $2\\,\\text{kg}$ block is on a frictionless surface. A $10\\,\\text{N}$ horizontal force acts on it for $4\\,\\text{s}$. What is its final speed?",
    options: [
      { key: "A", text: "$5\\,\\text{m s}^{-1}$" },
      { key: "B", text: "$10\\,\\text{m s}^{-1}$" },
      { key: "C", text: "$20\\,\\text{m s}^{-1}$" },
      { key: "D", text: "$40\\,\\text{m s}^{-1}$" },
    ],
    answer: "C",
    solution: "$a=F/m=10/2=5\\,\\text{m s}^{-2}$. $v=at=5\\times 4=20\\,\\text{m s}^{-1}$.",
  },
  {
    id: "engaa-s1p-003",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-phys2",
    difficulty: 2,
    marks: 1,
    question: "The potential difference across a resistor is $12\\,\\text{V}$ and the current through it is $0.4\\,\\text{A}$. What is the power dissipated?",
    options: [
      { key: "A", text: "$4.8\\,\\text{W}$" },
      { key: "B", text: "$30\\,\\text{W}$" },
      { key: "C", text: "$0.48\\,\\text{W}$" },
      { key: "D", text: "$48\\,\\text{W}$" },
    ],
    answer: "A",
    solution: "$P=VI=12\\times 0.4=4.8\\,\\text{W}$.",
  },
  {
    id: "engaa-s1p-004",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-phys1",
    difficulty: 2,
    marks: 1,
    question: "A satellite orbits Earth at radius $r$ from the centre. If the orbital period is $T$, which expression gives the mass $M$ of the Earth? ($G$ = gravitational constant)",
    options: [
      { key: "A", text: "$M = \\dfrac{4\\pi^2 r^3}{GT^2}$" },
      { key: "B", text: "$M = \\dfrac{GT^2}{4\\pi^2 r^3}$" },
      { key: "C", text: "$M = \\dfrac{4\\pi^2 r}{GT^2}$" },
      { key: "D", text: "$M = \\dfrac{GT^2 r}{4\\pi^2}$" },
    ],
    answer: "A",
    solution: "Gravity provides centripetal force: $\\frac{GMm}{r^2}=mr\\omega^2=mr\\left(\\frac{2\\pi}{T}\\right)^2$. Solving: $M=\\frac{4\\pi^2 r^3}{GT^2}$.",
  },
  {
    id: "engaa-s1p-005",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-phys2",
    difficulty: 2,
    marks: 1,
    question: "A ray of light passes from glass (refractive index 1.5) into air (refractive index 1.0). The critical angle is approximately:",
    options: [
      { key: "A", text: "$42°$" },
      { key: "B", text: "$48°$" },
      { key: "C", text: "$56°$" },
      { key: "D", text: "$62°$" },
    ],
    answer: "A",
    solution: "$\\sin\\theta_c=\\frac{n_2}{n_1}=\\frac{1}{1.5}=\\frac{2}{3}$. $\\theta_c=\\arcsin(2/3)\\approx 41.8°\\approx 42°$.",
  },
  {
    id: "engaa-s1p-006",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-phys1",
    difficulty: 1,
    marks: 1,
    question: "An object of mass $3\\,\\text{kg}$ is raised by $5\\,\\text{m}$. How much gravitational potential energy is gained? ($g = 10\\,\\text{m s}^{-2}$)",
    options: [
      { key: "A", text: "$50\\,\\text{J}$" },
      { key: "B", text: "$100\\,\\text{J}$" },
      { key: "C", text: "$150\\,\\text{J}$" },
      { key: "D", text: "$200\\,\\text{J}$" },
    ],
    answer: "C",
    solution: "$\\Delta E_p = mgh = 3\\times 10\\times 5 = 150\\,\\text{J}$.",
  },
  {
    id: "engaa-s1p-007",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-phys3",
    difficulty: 2,
    marks: 1,
    question: "In the photoelectric effect, the maximum kinetic energy of emitted electrons depends on:",
    options: [
      { key: "A", text: "The intensity of the incident light" },
      { key: "B", text: "The frequency of the incident light" },
      { key: "C", text: "Both the intensity and frequency" },
      { key: "D", text: "The number of photons per second" },
    ],
    answer: "B",
    solution: "$E_k^{\\max}=hf-\\phi$ (Einstein's equation). Maximum KE depends only on frequency $f$ and the work function $\\phi$, not intensity.",
  },
  {
    id: "engaa-s1p-008",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-phys2",
    difficulty: 2,
    marks: 1,
    question: "Two resistors of $6\\,\\Omega$ and $3\\,\\Omega$ are connected in parallel. The combined resistance is:",
    options: [
      { key: "A", text: "$9\\,\\Omega$" },
      { key: "B", text: "$4.5\\,\\Omega$" },
      { key: "C", text: "$2\\,\\Omega$" },
      { key: "D", text: "$1\\,\\Omega$" },
    ],
    answer: "C",
    solution: "$\\frac{1}{R}=\\frac{1}{6}+\\frac{1}{3}=\\frac{1}{6}+\\frac{2}{6}=\\frac{3}{6}=\\frac{1}{2}$. So $R=2\\,\\Omega$.",
  },
  {
    id: "engaa-s1p-009",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-phys1",
    difficulty: 3,
    marks: 1,
    question: "A spring (spring constant $k = 200\\,\\text{N m}^{-1}$) is compressed by $0.1\\,\\text{m}$ and launches a ball of mass $0.05\\,\\text{kg}$. What is the maximum speed of the ball?",
    options: [
      { key: "A", text: "$2\\,\\text{m s}^{-1}$" },
      { key: "B", text: "$4\\,\\text{m s}^{-1}$" },
      { key: "C", text: "$6\\,\\text{m s}^{-1}$" },
      { key: "D", text: "$10\\,\\text{m s}^{-1}$" },
    ],
    answer: "A",
    solution: "Energy: $\\frac{1}{2}kx^2=\\frac{1}{2}mv^2$. $v=x\\sqrt{k/m}=0.1\\sqrt{200/0.05}=0.1\\sqrt{4000}=0.1\\times 63.2\\approx 2\\,\\text{m s}^{-1}$. More precisely: $v=0.1\\sqrt{4000}=0.1\\times 20\\sqrt{10}=2\\sqrt{10}\\approx 6.32$. Hmm, $\\sqrt{200/0.05}=\\sqrt{4000}\\approx 63.2$, $v=0.1\\times 63.2=6.32$. So answer is C (≈6 m/s).",
    hint: "Energy conservation: $\\frac{1}{2}kx^2 = \\frac{1}{2}mv^2$.",
  },
  {
    id: "engaa-s1p-010",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-phys3",
    difficulty: 2,
    marks: 1,
    question: "An ideal gas undergoes isothermal compression from volume $V_0$ to $V_0/2$ at temperature $T$. How does the pressure change?",
    options: [
      { key: "A", text: "Pressure doubles" },
      { key: "B", text: "Pressure halves" },
      { key: "C", text: "Pressure increases by $\\sqrt{2}$" },
      { key: "D", text: "Pressure stays the same" },
    ],
    answer: "A",
    solution: "Isothermal: $pV=\\text{const}$. $p_1V_0=p_2(V_0/2)\\Rightarrow p_2=2p_1$. Pressure doubles.",
  },
];

export const ENGAA_SECTION2: MCQQuestion[] = [
  {
    id: "engaa-s2-001",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-phys1",
    difficulty: 3,
    marks: 1,
    question: "A pendulum of length $L$ has period $T = 2\\pi\\sqrt{L/g}$. If the length is increased by $21\\%$, by what percentage does the period increase?",
    options: [
      { key: "A", text: "$10\\%$" },
      { key: "B", text: "$10.5\\%$" },
      { key: "C", text: "$21\\%$" },
      { key: "D", text: "$44\\%$" },
    ],
    answer: "A",
    solution: "$T\\propto\\sqrt{L}$. New $T=2\\pi\\sqrt{1.21L/g}=1.1\\times 2\\pi\\sqrt{L/g}$. Period increases by $10\\%$.",
  },
  {
    id: "engaa-s2-002",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-phys2",
    difficulty: 3,
    marks: 1,
    question: "An electron (charge $e$, mass $m_e$) moves in a circle of radius $r$ in a magnetic field $B$ perpendicular to its velocity. Its speed is:",
    options: [
      { key: "A", text: "$v = \\dfrac{eBr}{m_e}$" },
      { key: "B", text: "$v = \\dfrac{m_e r}{eB}$" },
      { key: "C", text: "$v = \\dfrac{eB}{m_e r}$" },
      { key: "D", text: "$v = eBrm_e$" },
    ],
    answer: "A",
    solution: "Magnetic force provides centripetal force: $evB=\\frac{m_e v^2}{r}\\Rightarrow v=\\frac{eBr}{m_e}$.",
  },
  {
    id: "engaa-s2-003",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-phys2",
    difficulty: 3,
    marks: 1,
    question: "A uniform rod of length $L$ and mass $M$ is pivoted at one end and held horizontal. When released, its angular acceleration is: (moment of inertia about end $= ML^2/3$)",
    options: [
      { key: "A", text: "$\\alpha = \\dfrac{3g}{2L}$" },
      { key: "B", text: "$\\alpha = \\dfrac{g}{L}$" },
      { key: "C", text: "$\\alpha = \\dfrac{2g}{3L}$" },
      { key: "D", text: "$\\alpha = \\dfrac{g}{2L}$" },
    ],
    answer: "A",
    solution: "Torque about pivot $= Mg\\cdot(L/2)$. Newton's 2nd law for rotation: $I\\alpha=MgL/2$. $\\frac{ML^2}{3}\\alpha=\\frac{MgL}{2}\\Rightarrow\\alpha=\\frac{3g}{2L}$.",
  },
  {
    id: "engaa-s2-004",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-math2",
    difficulty: 3,
    marks: 1,
    question: "Solve the differential equation $\\dfrac{dy}{dx} = \\dfrac{y}{x}$ with $y(1) = 2$.",
    options: [
      { key: "A", text: "$y = 2e^{x-1}$" },
      { key: "B", text: "$y = 2x$" },
      { key: "C", text: "$y = 2\\ln x + 2$" },
      { key: "D", text: "$y = x^2$" },
    ],
    answer: "B",
    solution: "Separate: $\\frac{dy}{y}=\\frac{dx}{x}\\Rightarrow\\ln|y|=\\ln|x|+C\\Rightarrow y=Ax$. At $x=1$: $2=A$. So $y=2x$.",
  },
  {
    id: "engaa-s2-005",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-phys2",
    difficulty: 3,
    marks: 1,
    question: "A capacitor $C$ is charged to voltage $V_0$, then connected to a resistor $R$. The time constant is $\\tau = RC$. After time $t = 2RC$, the voltage is:",
    options: [
      { key: "A", text: "$V_0/e^2$" },
      { key: "B", text: "$V_0/2$" },
      { key: "C", text: "$V_0 e^{-2}$" },
      { key: "D", text: "Both A and C" },
    ],
    answer: "D",
    solution: "$V=V_0 e^{-t/RC}=V_0 e^{-2RC/RC}=V_0 e^{-2}=V_0/e^2$. Options A and C are identical.",
  },
  {
    id: "engaa-s2-006",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-phys1",
    difficulty: 3,
    marks: 1,
    question: "Two masses $m$ and $3m$ are connected by a light string over a frictionless pulley. The acceleration of the system is:",
    options: [
      { key: "A", text: "$\\dfrac{g}{2}$" },
      { key: "B", text: "$\\dfrac{g}{3}$" },
      { key: "C", text: "$\\dfrac{g}{4}$" },
      { key: "D", text: "$\\dfrac{g}{6}$" },
    ],
    answer: "A",
    solution: "Net force $=(3m-m)g=2mg$. Total mass $=4m$. $a=\\frac{2mg}{4m}=\\frac{g}{2}$.",
  },
  {
    id: "engaa-s2-007",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-math2",
    difficulty: 3,
    marks: 1,
    question: "For a function $f(x)$, $f''(x) = 6x - 2$, $f'(0) = 1$, $f(0) = 3$. Find $f(2)$.",
    options: [
      { key: "A", text: "$7$" },
      { key: "B", text: "$9$" },
      { key: "C", text: "$11$" },
      { key: "D", text: "$13$" },
    ],
    answer: "B",
    solution: "$f'(x)=\\int(6x-2)dx=3x^2-2x+C_1$. $f'(0)=C_1=1$, so $f'(x)=3x^2-2x+1$. $f(x)=x^3-x^2+x+C_2$. $f(0)=C_2=3$. $f(x)=x^3-x^2+x+3$. $f(2)=8-4+2+3=9$.",
  },
  {
    id: "engaa-s2-008",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-phys2",
    difficulty: 3,
    marks: 1,
    question: "A long straight wire carries current $I$. At distance $r$, the magnetic field strength is $B=\\mu_0 I/(2\\pi r)$. If the current is doubled and the distance is halved, $B$ becomes:",
    options: [
      { key: "A", text: "$2B$" },
      { key: "B", text: "$4B$" },
      { key: "C", text: "$B/2$" },
      { key: "D", text: "$8B$" },
    ],
    answer: "B",
    solution: "$B'=\\frac{\\mu_0(2I)}{2\\pi(r/2)}=4\\cdot\\frac{\\mu_0 I}{2\\pi r}=4B$.",
  },
  {
    id: "engaa-s2-009",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-phys1",
    difficulty: 3,
    marks: 1,
    question: "A particle undergoes simple harmonic motion with amplitude $A$ and angular frequency $\\omega$. Its maximum acceleration is:",
    options: [
      { key: "A", text: "$\\omega A$" },
      { key: "B", text: "$\\omega^2 A$" },
      { key: "C", text: "$\\dfrac{A}{\\omega^2}$" },
      { key: "D", text: "$2\\omega A$" },
    ],
    answer: "B",
    solution: "For SHM: $x=A\\cos(\\omega t)$, $a=-\\omega^2 A\\cos(\\omega t)$. Maximum $|a|=\\omega^2 A$.",
  },
  {
    id: "engaa-s2-010",
    type: "mcq",
    testId: "engaa",
    topicId: "engaa-phys3",
    difficulty: 3,
    marks: 1,
    question: "A photon of energy $4.5\\,\\text{eV}$ strikes a metal with work function $2.0\\,\\text{eV}$. The de Broglie wavelength of the emitted electron is proportional to:",
    options: [
      { key: "A", text: "$\\dfrac{1}{\\sqrt{E_k}}$" },
      { key: "B", text: "$\\sqrt{E_k}$" },
      { key: "C", text: "$E_k^2$" },
      { key: "D", text: "$\\dfrac{1}{E_k}$" },
    ],
    answer: "A",
    solution: "$\\lambda=h/p=h/\\sqrt{2m_eE_k}\\propto 1/\\sqrt{E_k}$. Here $E_k=4.5-2.0=2.5\\,\\text{eV}$.",
  },
];

export const ENGAA_QUESTIONS = [
  ...ENGAA_SECTION1_MATH,
  ...ENGAA_SECTION1_PHYS,
  ...ENGAA_SECTION2,
];
