// MAT 练习题扩展库 —— 由生成器 + sympy 计算答案，答案天生正确，另经多轮独立复核。
// 仅以官方结构/考纲校准，未照搬任何真题。id 前缀 mat-ex-*。
import type { MCQQuestion } from "./types";

export const MAT_EXPANSION: MCQQuestion[] = [
  { id: "mat-ex-001", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 4,
    question: "How many distinct real roots does $x^4 + 5x^2 + 4 = 0$ have?",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$1$" },{ key: "C", text: "$4$" },{ key: "D", text: "$2$" },{ key: "E", text: "$3$" }],
    answer: "A", solution: "Let $u=x^2$: $u^2 + 5u + 4=(u-(-4))(u-(-1))=0$, so $u=-4$ or $u=-1$. Each positive $u$ gives two real $x$, a negative $u$ gives none. Total: 0." },
  { id: "mat-ex-002", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 4,
    question: "What is the sum of the positive real roots of $x^4 - 5x^2 + 4 = 0$?",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$2$" },{ key: "C", text: "$3$" },{ key: "D", text: "$4$" },{ key: "E", text: "$5$" }],
    answer: "C", solution: "Let $u=x^2$. Then $(u-1)(u-4)=0$, so the real roots are $-2,-1,1,2$. The positive roots sum to $1+2=3$." },
  { id: "mat-ex-003", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 4,
    question: "How many distinct real roots does $x^4 - 8x^2 - 9 = 0$ have?",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$4$" },{ key: "C", text: "$3$" },{ key: "D", text: "$2$" },{ key: "E", text: "$0$" }],
    answer: "D", solution: "Let $u=x^2$: $u^2 - 8u - 9=(u-(-1))(u-(9))=0$, so $u=-1$ or $u=9$. Each positive $u$ gives two real $x$, a negative $u$ gives none. Total: 2." },
  { id: "mat-ex-004", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 4,
    question: "How many distinct real roots does $x^4 - 10x^2 + 9 = 0$ have?",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$1$" },{ key: "C", text: "$3$" },{ key: "D", text: "$4$" },{ key: "E", text: "$0$" }],
    answer: "D", solution: "Let $u=x^2$: $u^2 - 10u + 9=(u-(1))(u-(9))=0$, so $u=1$ or $u=9$. Each positive $u$ gives two real $x$, a negative $u$ gives none. Total: 4." },
  { id: "mat-ex-005", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 4,
    question: "How many distinct real roots does $x^4 + 3x^2 - 4 = 0$ have?",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$3$" },{ key: "C", text: "$1$" },{ key: "D", text: "$0$" },{ key: "E", text: "$4$" }],
    answer: "A", solution: "Let $u=x^2$: $u^2 + 3u - 4=(u-(-4))(u-(1))=0$, so $u=-4$ or $u=1$. Each positive $u$ gives two real $x$, a negative $u$ gives none. Total: 2." },
  { id: "mat-ex-006", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 4,
    question: "How many distinct real roots does $x^4 - 13x^2 + 36 = 0$ have?",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$4$" },{ key: "C", text: "$3$" },{ key: "D", text: "$1$" },{ key: "E", text: "$2$" }],
    answer: "B", solution: "Let $u=x^2$: $u^2 - 13u + 36=(u-(4))(u-(9))=0$, so $u=4$ or $u=9$. Each positive $u$ gives two real $x$, a negative $u$ gives none. Total: 4." },
  { id: "mat-ex-007", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 4,
    question: "How many distinct real roots does $x^4 - 17x^2 + 16 = 0$ have?",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$1$" },{ key: "C", text: "$0$" },{ key: "D", text: "$4$" },{ key: "E", text: "$2$" }],
    answer: "D", solution: "Let $u=x^2$: $u^2 - 17u + 16=(u-(1))(u-(16))=0$, so $u=1$ or $u=16$. Each positive $u$ gives two real $x$, a negative $u$ gives none. Total: 4." },
  { id: "mat-ex-008", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 4,
    question: "How many distinct real roots does $x^4 - 3x^2 - 4 = 0$ have?",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$3$" },{ key: "C", text: "$4$" },{ key: "D", text: "$0$" },{ key: "E", text: "$1$" }],
    answer: "A", solution: "Let $u=x^2$: $u^2 - 3u - 4=(u-(-1))(u-(4))=0$, so $u=-1$ or $u=4$. Each positive $u$ gives two real $x$, a negative $u$ gives none. Total: 2." },
  { id: "mat-ex-009", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 4,
    question: "How many distinct real roots does $x^4 - 25x^2 + 144 = 0$ have?",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$3$" },{ key: "C", text: "$4$" },{ key: "D", text: "$0$" },{ key: "E", text: "$1$" }],
    answer: "C", solution: "Let $u=x^2$: $u^2 - 25u + 144=(u-(9))(u-(16))=0$, so $u=9$ or $u=16$. Each positive $u$ gives two real $x$, a negative $u$ gives none. Total: 4." },
  { id: "mat-ex-010", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 4,
    question: "How many distinct real roots does $x^4 - 5x^2 - 36 = 0$ have?",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$3$" },{ key: "C", text: "$1$" },{ key: "D", text: "$4$" },{ key: "E", text: "$2$" }],
    answer: "E", solution: "Let $u=x^2$: $u^2 - 5u - 36=(u-(-4))(u-(9))=0$, so $u=-4$ or $u=9$. Each positive $u$ gives two real $x$, a negative $u$ gives none. Total: 2." },
  { id: "mat-ex-011", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 4,
    question: "The minimum value of $y=x^2 - 4x + 7$ is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$-1$" },{ key: "C", text: "$2$" },{ key: "D", text: "$7$" },{ key: "E", text: "$4$" }],
    answer: "A", solution: "Complete the square: $x^2-4x+7=(x-2)^2 + 3$, minimum $3$." },
  { id: "mat-ex-012", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 4,
    question: "The minimum value of $y=x^2 + 6x + 11$ is:",
    options: [{ key: "A", text: "$-7$" },{ key: "B", text: "$2$" },{ key: "C", text: "$1$" },{ key: "D", text: "$3$" },{ key: "E", text: "$11$" }],
    answer: "B", solution: "Complete the square: $x^2+6x+11=(x+3)^2 + 2$, minimum $2$." },
  { id: "mat-ex-013", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 4,
    question: "The minimum value of $y=x^2 + 4x + 9$ is:",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$9$" },{ key: "C", text: "$5$" },{ key: "D", text: "$1$" },{ key: "E", text: "$4$" }],
    answer: "C", solution: "Complete the square: $x^2+4x+9=(x+2)^2 + 5$, minimum $5$." },
  { id: "mat-ex-014", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 4,
    question: "The minimum value of $y=x^2 - 6x + 13$ is:",
    options: [{ key: "A", text: "$13$" },{ key: "B", text: "$3$" },{ key: "C", text: "$5$" },{ key: "D", text: "$4$" },{ key: "E", text: "$-5$" }],
    answer: "D", solution: "Complete the square: $x^2-6x+13=(x-3)^2 + 4$, minimum $4$." },
  { id: "mat-ex-015", type: "mcq", testId: "mat", topicId: "mat-trig", difficulty: 2, marks: 4,
    question: "How many solutions does $\\sin(2\\theta)=\\tfrac12$ have for $0\\le\\theta<2\\pi$?",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$5$" },{ key: "C", text: "$3$" },{ key: "D", text: "$4$" },{ key: "E", text: "$2$" }],
    answer: "D", solution: "Let $\\phi=2\\theta\\in[0,4\\pi)$. $\\sin\\phi=\\tfrac12$ has $2$ solutions per $2\\pi$, so $2\\times2=4$ in total." },
  { id: "mat-ex-016", type: "mcq", testId: "mat", topicId: "mat-trig", difficulty: 2, marks: 4,
    question: "How many solutions does $\\sin(3\\theta)=\\tfrac12$ have for $0\\le\\theta<2\\pi$?",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$8$" },{ key: "C", text: "$6$" },{ key: "D", text: "$5$" },{ key: "E", text: "$3$" }],
    answer: "C", solution: "Let $\\phi=3\\theta\\in[0,6\\pi)$. $\\sin\\phi=\\tfrac12$ has $2$ solutions per $2\\pi$, so $2\\times3=6$ in total." },
  { id: "mat-ex-017", type: "mcq", testId: "mat", topicId: "mat-trig", difficulty: 2, marks: 4,
    question: "How many solutions does $\\sin(4\\theta)=\\tfrac12$ have for $0\\le\\theta<2\\pi$?",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$5$" },{ key: "C", text: "$7$" },{ key: "D", text: "$8$" },{ key: "E", text: "$10$" }],
    answer: "D", solution: "Let $\\phi=4\\theta\\in[0,8\\pi)$. $\\sin\\phi=\\tfrac12$ has $2$ solutions per $2\\pi$, so $2\\times4=8$ in total." },
  { id: "mat-ex-018", type: "mcq", testId: "mat", topicId: "mat-trig", difficulty: 3, marks: 4,
    question: "Solve type $2\\cos^2\\theta+\\dots=0$: the number of solutions of $(2\\cos \\theta-1)(\\cos \\theta+1)=0$ in $0\\le\\theta<2\\pi$ is:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$1$" },{ key: "C", text: "$5$" },{ key: "D", text: "$3$" },{ key: "E", text: "$2$" }],
    answer: "D", solution: "$\\cos\\theta=\\frac{1}{2}$ (2); $\\cos\\theta=-1\\Rightarrow\\theta=\\pi$ (1). Total 3." },
  { id: "mat-ex-019", type: "mcq", testId: "mat", topicId: "mat-trig", difficulty: 3, marks: 4,
    question: "Solve type $2\\cos^2\\theta+\\dots=0$: the number of solutions of $(2\\cos \\theta-1)(\\cos \\theta-1)=0$ in $0\\le\\theta<2\\pi$ is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$1$" },{ key: "C", text: "$5$" },{ key: "D", text: "$4$" },{ key: "E", text: "$2$" }],
    answer: "A", solution: "$\\cos\\theta=\\frac{1}{2}$ (2); $\\cos\\theta=1\\Rightarrow\\theta=0$ (1). Total 3." },
  { id: "mat-ex-020", type: "mcq", testId: "mat", topicId: "mat-trig", difficulty: 3, marks: 4,
    question: "Solve type $2\\cos^2\\theta+\\dots=0$: the number of solutions of $(2\\cos \\theta+1)(\\cos \\theta-1)=0$ in $0\\le\\theta<2\\pi$ is:",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$5$" },{ key: "C", text: "$1$" },{ key: "D", text: "$3$" },{ key: "E", text: "$4$" }],
    answer: "D", solution: "$\\cos\\theta=- \\frac{1}{2}$ (2); $\\cos\\theta=1\\Rightarrow\\theta=0$ (1). Total 3." },
  { id: "mat-ex-021", type: "mcq", testId: "mat", topicId: "mat-trig", difficulty: 3, marks: 4,
    question: "Solve type $2\\cos^2\\theta+\\dots=0$: the number of solutions of $(2\\cos \\theta-1)(2\\cos \\theta+1)=0$ in $0\\le\\theta<2\\pi$ is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$2$" },{ key: "C", text: "$5$" },{ key: "D", text: "$4$" },{ key: "E", text: "$1$" }],
    answer: "D", solution: "$\\cos\\theta=\\frac{1}{2}$ (2); $\\cos\\theta=- \\frac{1}{2}$ (2). Total 4." },
  { id: "mat-ex-022", type: "mcq", testId: "mat", topicId: "mat-trig", difficulty: 2, marks: 4,
    question: "If $\\tan\\theta=\\tfrac{3}{4}$ with $\\theta$ acute, then $\\sin\\theta+\\cos\\theta$ equals:",
    options: [{ key: "A", text: "$\\frac{1}{5}$" },{ key: "B", text: "$\\frac{3}{5}$" },{ key: "C", text: "$\\frac{4}{5}$" },{ key: "D", text: "$1$" },{ key: "E", text: "$\\frac{7}{5}$" }],
    answer: "E", solution: "A $3$–$4$–$5$ right triangle: $\\sin\\theta=\\tfrac{3}{5}$, $\\cos\\theta=\\tfrac{4}{5}$, sum $=\\frac{7}{5}$." },
  { id: "mat-ex-023", type: "mcq", testId: "mat", topicId: "mat-trig", difficulty: 2, marks: 4,
    question: "If $\\tan\\theta=\\tfrac{5}{12}$ with $\\theta$ acute, then $\\sin\\theta+\\cos\\theta$ equals:",
    options: [{ key: "A", text: "$\\frac{17}{13}$" },{ key: "B", text: "$\\frac{12}{13}$" },{ key: "C", text: "$1$" },{ key: "D", text: "$\\frac{7}{13}$" },{ key: "E", text: "$\\frac{5}{13}$" }],
    answer: "A", solution: "A $5$–$12$–$13$ right triangle: $\\sin\\theta=\\tfrac{5}{13}$, $\\cos\\theta=\\tfrac{12}{13}$, sum $=\\frac{17}{13}$." },
  { id: "mat-ex-024", type: "mcq", testId: "mat", topicId: "mat-trig", difficulty: 2, marks: 4,
    question: "If $\\tan\\theta=\\tfrac{8}{15}$ with $\\theta$ acute, then $\\sin\\theta+\\cos\\theta$ equals:",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$\\frac{23}{17}$" },{ key: "C", text: "$\\frac{7}{17}$" },{ key: "D", text: "$\\frac{15}{17}$" },{ key: "E", text: "$\\frac{8}{17}$" }],
    answer: "B", solution: "A $8$–$15$–$17$ right triangle: $\\sin\\theta=\\tfrac{8}{17}$, $\\cos\\theta=\\tfrac{15}{17}$, sum $=\\frac{23}{17}$." },
  { id: "mat-ex-025", type: "mcq", testId: "mat", topicId: "mat-trig", difficulty: 2, marks: 4,
    question: "If $\\tan\\theta=\\tfrac{7}{24}$ with $\\theta$ acute, then $\\sin\\theta+\\cos\\theta$ equals:",
    options: [{ key: "A", text: "$\\frac{31}{25}$" },{ key: "B", text: "$\\frac{17}{25}$" },{ key: "C", text: "$\\frac{7}{25}$" },{ key: "D", text: "$1$" },{ key: "E", text: "$\\frac{24}{25}$" }],
    answer: "A", solution: "A $7$–$24$–$25$ right triangle: $\\sin\\theta=\\tfrac{7}{25}$, $\\cos\\theta=\\tfrac{24}{25}$, sum $=\\frac{31}{25}$." },
  { id: "mat-ex-026", type: "mcq", testId: "mat", topicId: "mat-trig", difficulty: 2, marks: 4,
    question: "If $\\tan\\theta=\\tfrac{20}{21}$ with $\\theta$ acute, then $\\sin\\theta+\\cos\\theta$ equals:",
    options: [{ key: "A", text: "$\\frac{21}{29}$" },{ key: "B", text: "$\\frac{1}{29}$" },{ key: "C", text: "$1$" },{ key: "D", text: "$\\frac{20}{29}$" },{ key: "E", text: "$\\frac{41}{29}$" }],
    answer: "E", solution: "A $20$–$21$–$29$ right triangle: $\\sin\\theta=\\tfrac{20}{29}$, $\\cos\\theta=\\tfrac{21}{29}$, sum $=\\frac{41}{29}$." },
  { id: "mat-ex-027", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 2, marks: 4,
    question: "Evaluate $\\displaystyle\\int_{0}^{1} x^{2} \\left(1 - x\\right)^{2}\\,dx$.",
    options: [{ key: "A", text: "$\\frac{1}{60}$" },{ key: "B", text: "$\\frac{1}{15}$" },{ key: "C", text: "$\\frac{1}{5}$" },{ key: "D", text: "$- \\frac{2}{15}$" },{ key: "E", text: "$\\frac{1}{30}$" }],
    answer: "E", solution: "$\\int x^{2} \\left(1 - x\\right)^{2}\\,dx$ evaluated from $0$ to $1$ gives $\\frac{1}{30}$." },
  { id: "mat-ex-028", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 2, marks: 4,
    question: "Evaluate $\\displaystyle\\int_{1}^{2} 2 x\\,dx$.",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$\\frac{3}{2}$" },{ key: "C", text: "$6$" },{ key: "D", text: "$\\frac{19}{6}$" },{ key: "E", text: "$\\frac{17}{6}$" }],
    answer: "A", solution: "$\\int 2 x\\,dx$ evaluated from $1$ to $2$ gives $3$." },
  { id: "mat-ex-029", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 2, marks: 4,
    question: "Evaluate $\\displaystyle\\int_{0}^{2} 3 x^{2} - 2 x\\,dx$.",
    options: [{ key: "A", text: "$\\frac{23}{6}$" },{ key: "B", text: "$4$" },{ key: "C", text: "$8$" },{ key: "D", text: "$\\frac{25}{6}$" },{ key: "E", text: "$2$" }],
    answer: "B", solution: "$\\int 3 x^{2} - 2 x\\,dx$ evaluated from $0$ to $2$ gives $4$." },
  { id: "mat-ex-030", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 2, marks: 4,
    question: "Evaluate $\\displaystyle\\int_{0}^{2} x^{3}\\,dx$.",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$4$" },{ key: "C", text: "$\\frac{23}{6}$" },{ key: "D", text: "$\\frac{25}{6}$" },{ key: "E", text: "$8$" }],
    answer: "B", solution: "$\\int x^{3}\\,dx$ evaluated from $0$ to $2$ gives $4$." },
  { id: "mat-ex-031", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 2, marks: 4,
    question: "Evaluate $\\displaystyle\\int_{1}^{3} x^{2} + 1\\,dx$.",
    options: [{ key: "A", text: "$\\frac{64}{3}$" },{ key: "B", text: "$\\frac{32}{3}$" },{ key: "C", text: "$\\frac{16}{3}$" },{ key: "D", text: "$\\frac{21}{2}$" },{ key: "E", text: "$\\frac{65}{6}$" }],
    answer: "B", solution: "$\\int x^{2} + 1\\,dx$ evaluated from $1$ to $3$ gives $\\frac{32}{3}$." },
  { id: "mat-ex-032", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 2, marks: 4,
    question: "Evaluate $\\displaystyle\\int_{1}^{4} 4 x - 1\\,dx$.",
    options: [{ key: "A", text: "$54$" },{ key: "B", text: "$27$" },{ key: "C", text: "$\\frac{161}{6}$" },{ key: "D", text: "$\\frac{27}{2}$" },{ key: "E", text: "$\\frac{163}{6}$" }],
    answer: "B", solution: "$\\int 4 x - 1\\,dx$ evaluated from $1$ to $4$ gives $27$." },
  { id: "mat-ex-033", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 2, marks: 4,
    question: "Evaluate $\\displaystyle\\int_{0}^{1} x^{2} \\left(x - 1\\right)\\,dx$.",
    options: [{ key: "A", text: "$- \\frac{1}{6}$" },{ key: "B", text: "$- \\frac{1}{12}$" },{ key: "C", text: "$- \\frac{1}{4}$" },{ key: "D", text: "$- \\frac{1}{24}$" },{ key: "E", text: "$\\frac{1}{12}$" }],
    answer: "B", solution: "$\\int x^{2} \\left(x - 1\\right)\\,dx$ evaluated from $0$ to $1$ gives $- \\frac{1}{12}$." },
  { id: "mat-ex-034", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 2, marks: 4,
    question: "Evaluate $\\displaystyle\\int_{0}^{2} 6 x^{2}\\,dx$.",
    options: [{ key: "A", text: "$32$" },{ key: "B", text: "$8$" },{ key: "C", text: "$\\frac{95}{6}$" },{ key: "D", text: "$16$" },{ key: "E", text: "$\\frac{97}{6}$" }],
    answer: "D", solution: "$\\int 6 x^{2}\\,dx$ evaluated from $0$ to $2$ gives $16$." },
  { id: "mat-ex-035", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 2, marks: 4,
    question: "Evaluate $\\displaystyle\\int_{0}^{1} \\left(x + 2\\right)^{2}\\,dx$.",
    options: [{ key: "A", text: "$\\frac{37}{6}$" },{ key: "B", text: "$\\frac{38}{3}$" },{ key: "C", text: "$\\frac{13}{2}$" },{ key: "D", text: "$\\frac{19}{3}$" },{ key: "E", text: "$\\frac{19}{6}$" }],
    answer: "D", solution: "$\\int \\left(x + 2\\right)^{2}\\,dx$ evaluated from $0$ to $1$ gives $\\frac{19}{3}$." },
  { id: "mat-ex-036", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 2, marks: 4,
    question: "Evaluate $\\displaystyle\\int_{0}^{1} 1 - x^{2}\\,dx$.",
    options: [{ key: "A", text: "$\\frac{4}{3}$" },{ key: "B", text: "$\\frac{2}{3}$" },{ key: "C", text: "$\\frac{5}{6}$" },{ key: "D", text: "$\\frac{1}{3}$" },{ key: "E", text: "$\\frac{1}{2}$" }],
    answer: "B", solution: "$\\int 1 - x^{2}\\,dx$ evaluated from $0$ to $1$ gives $\\frac{2}{3}$." },
  { id: "mat-ex-037", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 2, marks: 4,
    question: "The shortest distance from $(3,4)$ to the line $3x + 4y - 10=0$ is:",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$\\frac{9}{5}$" },{ key: "C", text: "$4$" },{ key: "D", text: "$3$" },{ key: "E", text: "$5$" }],
    answer: "D", solution: "Distance $=\\dfrac{|3(3)+4(4)-10|}{\\sqrt{3^2+4^2}}=3$." },
  { id: "mat-ex-038", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 2, marks: 4,
    question: "The shortest distance from $(1,1)$ to the line $5x + 12y - 13=0$ is:",
    options: [{ key: "A", text: "$\\frac{17}{13}$" },{ key: "B", text: "$\\frac{9}{5}$" },{ key: "C", text: "$\\frac{4}{13}$" },{ key: "D", text: "$\\frac{30}{13}$" },{ key: "E", text: "$- \\frac{9}{13}$" }],
    answer: "C", solution: "Distance $=\\dfrac{|5(1)+12(1)-13|}{\\sqrt{5^2+12^2}}=\\frac{4}{13}$." },
  { id: "mat-ex-039", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 2, marks: 4,
    question: "The shortest distance from $(3,4)$ to the line $3x - 4y + 0=0$ is:",
    options: [{ key: "A", text: "$\\frac{9}{5}$" },{ key: "B", text: "$\\frac{12}{5}$" },{ key: "C", text: "$\\frac{2}{5}$" },{ key: "D", text: "$\\frac{17}{5}$" },{ key: "E", text: "$\\frac{7}{5}$" }],
    answer: "E", solution: "Distance $=\\dfrac{|3(3)-4(4)+0|}{\\sqrt{3^2+-4^2}}=\\frac{7}{5}$." },
  { id: "mat-ex-040", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 2, marks: 4,
    question: "The shortest distance from $(2,1)$ to the line $4x + 3y - 5=0$ is:",
    options: [{ key: "A", text: "$\\frac{6}{5}$" },{ key: "B", text: "$\\frac{1}{5}$" },{ key: "C", text: "$\\frac{11}{5}$" },{ key: "D", text: "$\\frac{16}{5}$" },{ key: "E", text: "$\\frac{9}{5}$" }],
    answer: "A", solution: "Distance $=\\dfrac{|4(2)+3(1)-5|}{\\sqrt{4^2+3^2}}=\\frac{6}{5}$." },
  { id: "mat-ex-041", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 2, marks: 4,
    question: "The shortest distance from $(1,1)$ to the line $8x + 15y + 0=0$ is:",
    options: [{ key: "A", text: "$\\frac{9}{5}$" },{ key: "B", text: "$\\frac{40}{17}$" },{ key: "C", text: "$\\frac{57}{17}$" },{ key: "D", text: "$\\frac{6}{17}$" },{ key: "E", text: "$\\frac{23}{17}$" }],
    answer: "E", solution: "Distance $=\\dfrac{|8(1)+15(1)+0|}{\\sqrt{8^2+15^2}}=\\frac{23}{17}$." },
  { id: "mat-ex-042", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 2, marks: 4,
    question: "The shortest distance from $(0,0)$ to the line $3x + 4y - 25=0$ is:",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$4$" },{ key: "C", text: "$\\frac{9}{5}$" },{ key: "D", text: "$6$" },{ key: "E", text: "$5$" }],
    answer: "E", solution: "Distance $=\\dfrac{|3(0)+4(0)-25|}{\\sqrt{3^2+4^2}}=5$." },
  { id: "mat-ex-043", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 2, marks: 4,
    question: "The shortest distance from $(2,3)$ to the line $5x + 12y + 0=0$ is:",
    options: [{ key: "A", text: "$\\frac{33}{13}$" },{ key: "B", text: "$\\frac{46}{13}$" },{ key: "C", text: "$\\frac{72}{13}$" },{ key: "D", text: "$\\frac{59}{13}$" },{ key: "E", text: "$\\frac{9}{5}$" }],
    answer: "B", solution: "Distance $=\\dfrac{|5(2)+12(3)+0|}{\\sqrt{5^2+12^2}}=\\frac{46}{13}$." },
  { id: "mat-ex-044", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 2, marks: 4,
    question: "The shortest distance from $(1,1)$ to the line $6x + 8y - 20=0$ is:",
    options: [{ key: "A", text: "$\\frac{13}{5}$" },{ key: "B", text: "$- \\frac{2}{5}$" },{ key: "C", text: "$\\frac{3}{5}$" },{ key: "D", text: "$\\frac{8}{5}$" },{ key: "E", text: "$\\frac{9}{5}$" }],
    answer: "C", solution: "Distance $=\\dfrac{|6(1)+8(1)-20|}{\\sqrt{6^2+8^2}}=\\frac{3}{5}$." },
  { id: "mat-ex-045", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 3, marks: 4,
    question: "The radius of the circle $x^2+y^2 - 4x - 6y + 4=0$ is:",
    options: [{ key: "A", text: "$\\sqrt{10}$" },{ key: "B", text: "$3$" },{ key: "C", text: "$4$" },{ key: "D", text: "$9$" },{ key: "E", text: "$\\sqrt{7}$" }],
    answer: "B", solution: "Centre $(2,3)$, radius $=\\sqrt{(2)^2+(3)^2-(4)}=\\sqrt{9}=3$." },
  { id: "mat-ex-046", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 3, marks: 4,
    question: "The radius of the circle $x^2+y^2 + 2x - 4y - 4=0$ is:",
    options: [{ key: "A", text: "$\\sqrt{10}$" },{ key: "B", text: "$4$" },{ key: "C", text: "$9$" },{ key: "D", text: "$\\sqrt{7}$" },{ key: "E", text: "$3$" }],
    answer: "E", solution: "Centre $(-1,2)$, radius $=\\sqrt{(-1)^2+(2)^2-(-4)}=\\sqrt{9}=3$." },
  { id: "mat-ex-047", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 3, marks: 4,
    question: "The radius of the circle $x^2+y^2 - 6x + 8y + 0=0$ is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$25$" },{ key: "C", text: "$\\sqrt{23}$" },{ key: "D", text: "$\\sqrt{26}$" },{ key: "E", text: "$6$" }],
    answer: "A", solution: "Centre $(3,-4)$, radius $=\\sqrt{(3)^2+(-4)^2-(0)}=\\sqrt{25}=5$." },
  { id: "mat-ex-048", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 3, marks: 4,
    question: "The radius of the circle $x^2+y^2 + 0x + 0y - 9=0$ is:",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$3$" },{ key: "C", text: "$4$" },{ key: "D", text: "$\\sqrt{10}$" },{ key: "E", text: "$\\sqrt{7}$" }],
    answer: "B", solution: "Centre $(0,0)$, radius $=\\sqrt{(0)^2+(0)^2-(-9)}=\\sqrt{9}=3$." },
  { id: "mat-ex-049", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 3, marks: 4,
    question: "The radius of the circle $x^2+y^2 - 2x + 0y - 3=0$ is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$\\sqrt{2}$" },{ key: "C", text: "$2$" },{ key: "D", text: "$\\sqrt{5}$" },{ key: "E", text: "$4$" }],
    answer: "C", solution: "Centre $(1,0)$, radius $=\\sqrt{(1)^2+(0)^2-(-3)}=\\sqrt{4}=2$." },
  { id: "mat-ex-050", type: "mcq", testId: "mat", topicId: "mat-geo", difficulty: 3, marks: 4,
    question: "The radius of the circle $x^2+y^2 + 4x + 4y - 1=0$ is:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$3$" },{ key: "C", text: "$\\sqrt{10}$" },{ key: "D", text: "$\\sqrt{7}$" },{ key: "E", text: "$9$" }],
    answer: "B", solution: "Centre $(-2,-2)$, radius $=\\sqrt{(-2)^2+(-2)^2-(-1)}=\\sqrt{9}=3$." },
  { id: "mat-ex-051", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 4,
    question: "The value of $\\log_{2} 3\\times\\log_{3} 8$ is:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$1$" },{ key: "C", text: "$5$" },{ key: "D", text: "$3$" },{ key: "E", text: "$2$" }],
    answer: "D", solution: "$\\log_{2}3\\cdot\\log_{3}8=\\dfrac{\\ln 3}{\\ln 2}\\cdot\\dfrac{\\ln 8}{\\ln 3}$; with $3=3^{k}$ the chain gives $\\log_{2}8=3$." },
  { id: "mat-ex-052", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 4,
    question: "The value of $\\log_{2} 5\\times\\log_{5} 16$ is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$6$" },{ key: "C", text: "$4$" },{ key: "D", text: "$3$" },{ key: "E", text: "$2$" }],
    answer: "C", solution: "$\\log_{2}5\\cdot\\log_{5}16=\\dfrac{\\ln 5}{\\ln 2}\\cdot\\dfrac{\\ln 16}{\\ln 5}$; with $5=5^{k}$ the chain gives $\\log_{2}16=4$." },
  { id: "mat-ex-053", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 4,
    question: "The value of $\\log_{3} 4\\times\\log_{4} 9$ is:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$0$" },{ key: "C", text: "$2$" },{ key: "D", text: "$1$" },{ key: "E", text: "$3$" }],
    answer: "C", solution: "$\\log_{3}4\\cdot\\log_{4}9=\\dfrac{\\ln 4}{\\ln 3}\\cdot\\dfrac{\\ln 9}{\\ln 4}$; with $4=4^{k}$ the chain gives $\\log_{3}9=2$." },
  { id: "mat-ex-054", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 4,
    question: "The value of $\\log_{2} 7\\times\\log_{7} 8$ is:",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$4$" },{ key: "C", text: "$5$" },{ key: "D", text: "$3$" },{ key: "E", text: "$1$" }],
    answer: "D", solution: "$\\log_{2}7\\cdot\\log_{7}8=\\dfrac{\\ln 7}{\\ln 2}\\cdot\\dfrac{\\ln 8}{\\ln 7}$; with $7=7^{k}$ the chain gives $\\log_{2}8=3$." },
  { id: "mat-ex-055", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 4,
    question: "The value of $\\log_{5} 6\\times\\log_{6} 25$ is:",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$1$" },{ key: "C", text: "$3$" },{ key: "D", text: "$4$" },{ key: "E", text: "$2$" }],
    answer: "E", solution: "$\\log_{5}6\\cdot\\log_{6}25=\\dfrac{\\ln 6}{\\ln 5}\\cdot\\dfrac{\\ln 25}{\\ln 6}$; with $6=6^{k}$ the chain gives $\\log_{5}25=2$." },
  { id: "mat-ex-056", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 4,
    question: "The value of $\\log_{2} 9\\times\\log_{9} 8$ is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$4$" },{ key: "C", text: "$1$" },{ key: "D", text: "$3$" },{ key: "E", text: "$2$" }],
    answer: "D", solution: "$\\log_{2}9\\cdot\\log_{9}8=\\dfrac{\\ln 9}{\\ln 2}\\cdot\\dfrac{\\ln 8}{\\ln 9}$; with $9=9^{k}$ the chain gives $\\log_{2}8=3$." },
  { id: "mat-ex-057", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 4,
    question: "The value of $\\log_{3} 10\\times\\log_{10} 9$ is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$1$" },{ key: "C", text: "$2$" },{ key: "D", text: "$0$" },{ key: "E", text: "$4$" }],
    answer: "C", solution: "$\\log_{3}10\\cdot\\log_{10}9=\\dfrac{\\ln 10}{\\ln 3}\\cdot\\dfrac{\\ln 9}{\\ln 10}$; with $10=10^{k}$ the chain gives $\\log_{3}9=2$." },
  { id: "mat-ex-058", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 4,
    question: "The value of $\\log_{2} 3\\times\\log_{3} 16$ is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$6$" },{ key: "C", text: "$3$" },{ key: "D", text: "$2$" },{ key: "E", text: "$4$" }],
    answer: "E", solution: "$\\log_{2}3\\cdot\\log_{3}16=\\dfrac{\\ln 3}{\\ln 2}\\cdot\\dfrac{\\ln 16}{\\ln 3}$; with $3=3^{k}$ the chain gives $\\log_{2}16=4$." },
  { id: "mat-ex-059", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 4,
    question: "The sum of the real solutions of $4^{x} - 6\\cdot 2^{x} + 8 = 0$ is:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$5$" },{ key: "C", text: "$3$" },{ key: "D", text: "$1$" },{ key: "E", text: "$2$" }],
    answer: "C", solution: "Let $y=2^x$: $y^2-6y+8=0\\Rightarrow y=2^{1},2^{2}$, so $x=1,2$; sum $=3$." },
  { id: "mat-ex-060", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 4,
    question: "The sum of the real solutions of $4^{x} - 5\\cdot 2^{x} + 4 = 0$ is:",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$1$" },{ key: "C", text: "$3$" },{ key: "D", text: "$4$" },{ key: "E", text: "$2$" }],
    answer: "E", solution: "Let $y=2^x$: $y^2-5y+4=0\\Rightarrow y=2^{0},2^{2}$, so $x=0,2$; sum $=2$." },
  { id: "mat-ex-061", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 4,
    question: "The sum of the real solutions of $4^{x} - 10\\cdot 2^{x} + 16 = 0$ is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$3$" },{ key: "C", text: "$6$" },{ key: "D", text: "$4$" },{ key: "E", text: "$2$" }],
    answer: "D", solution: "Let $y=2^x$: $y^2-10y+16=0\\Rightarrow y=2^{1},2^{3}$, so $x=1,3$; sum $=4$." },
  { id: "mat-ex-062", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 4,
    question: "The sum of the real solutions of $4^{x} - 9\\cdot 2^{x} + 8 = 0$ is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$3$" },{ key: "C", text: "$1$" },{ key: "D", text: "$4$" },{ key: "E", text: "$2$" }],
    answer: "B", solution: "Let $y=2^x$: $y^2-9y+8=0\\Rightarrow y=2^{0},2^{3}$, so $x=0,3$; sum $=3$." },
  { id: "mat-ex-063", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 4,
    question: "The sum of the real solutions of $4^{x} - 12\\cdot 2^{x} + 32 = 0$ is:",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$6$" },{ key: "C", text: "$3$" },{ key: "D", text: "$4$" },{ key: "E", text: "$5$" }],
    answer: "E", solution: "Let $y=2^x$: $y^2-12y+32=0\\Rightarrow y=2^{2},2^{3}$, so $x=2,3$; sum $=5$." },
  { id: "mat-ex-064", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 4,
    question: "The sum of the real solutions of $4^{x} - 3\\cdot 2^{x} + 2 = 0$ is:",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$3$" },{ key: "C", text: "$-1$" },{ key: "D", text: "$2$" },{ key: "E", text: "$0$" }],
    answer: "A", solution: "Let $y=2^x$: $y^2-3y+2=0\\Rightarrow y=2^{0},2^{1}$, so $x=0,1$; sum $=1$." },
  { id: "mat-ex-065", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 4,
    question: "The sum $1+2+4+\\cdots+2^{6}$ equals:",
    options: [{ key: "A", text: "$2^{7}-1$" },{ key: "B", text: "$2^{7}$" },{ key: "C", text: "$2^{6}$" },{ key: "D", text: "$2^{8}-1$" },{ key: "E", text: "$2^{6}-1$" }],
    answer: "A", solution: "Geometric series with ratio $2$: sum $=\\dfrac{2^{7}-1}{2-1}=2^{7}-1=127$." },
  { id: "mat-ex-066", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 4,
    question: "The sum $1+2+4+\\cdots+2^{8}$ equals:",
    options: [{ key: "A", text: "$2^{9}$" },{ key: "B", text: "$2^{8}-1$" },{ key: "C", text: "$2^{9}-1$" },{ key: "D", text: "$2^{8}$" },{ key: "E", text: "$2^{10}-1$" }],
    answer: "C", solution: "Geometric series with ratio $2$: sum $=\\dfrac{2^{9}-1}{2-1}=2^{9}-1=511$." },
  { id: "mat-ex-067", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 4,
    question: "The sum $1+2+4+\\cdots+2^{10}$ equals:",
    options: [{ key: "A", text: "$2^{12}-1$" },{ key: "B", text: "$2^{11}-1$" },{ key: "C", text: "$2^{10}$" },{ key: "D", text: "$2^{11}$" },{ key: "E", text: "$2^{10}-1$" }],
    answer: "B", solution: "Geometric series with ratio $2$: sum $=\\dfrac{2^{11}-1}{2-1}=2^{11}-1=2047$." },
  { id: "mat-ex-068", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 4,
    question: "The sum $1+2+4+\\cdots+2^{7}$ equals:",
    options: [{ key: "A", text: "$2^{7}$" },{ key: "B", text: "$2^{8}$" },{ key: "C", text: "$2^{9}-1$" },{ key: "D", text: "$2^{8}-1$" },{ key: "E", text: "$2^{7}-1$" }],
    answer: "D", solution: "Geometric series with ratio $2$: sum $=\\dfrac{2^{8}-1}{2-1}=2^{8}-1=255$." },
  { id: "mat-ex-069", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 4,
    question: "The sum $1+2+4+\\cdots+2^{9}$ equals:",
    options: [{ key: "A", text: "$2^{9}-1$" },{ key: "B", text: "$2^{10}$" },{ key: "C", text: "$2^{9}$" },{ key: "D", text: "$2^{10}-1$" },{ key: "E", text: "$2^{11}-1$" }],
    answer: "D", solution: "Geometric series with ratio $2$: sum $=\\dfrac{2^{10}-1}{2-1}=2^{10}-1=1023$." },
  { id: "mat-ex-070", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 4,
    question: "The sum $1+2+4+\\cdots+2^{5}$ equals:",
    options: [{ key: "A", text: "$2^{5}-1$" },{ key: "B", text: "$2^{6}$" },{ key: "C", text: "$2^{5}$" },{ key: "D", text: "$2^{7}-1$" },{ key: "E", text: "$2^{6}-1$" }],
    answer: "E", solution: "Geometric series with ratio $2$: sum $=\\dfrac{2^{6}-1}{2-1}=2^{6}-1=63$." },
  { id: "mat-ex-071", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 4,
    question: "The sum $1+2+4+\\cdots+2^{11}$ equals:",
    options: [{ key: "A", text: "$2^{11}-1$" },{ key: "B", text: "$2^{13}-1$" },{ key: "C", text: "$2^{11}$" },{ key: "D", text: "$2^{12}$" },{ key: "E", text: "$2^{12}-1$" }],
    answer: "E", solution: "Geometric series with ratio $2$: sum $=\\dfrac{2^{12}-1}{2-1}=2^{12}-1=4095$." },
  { id: "mat-ex-072", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 4,
    question: "The sum $1+2+4+\\cdots+2^{12}$ equals:",
    options: [{ key: "A", text: "$2^{13}$" },{ key: "B", text: "$2^{12}-1$" },{ key: "C", text: "$2^{12}$" },{ key: "D", text: "$2^{13}-1$" },{ key: "E", text: "$2^{14}-1$" }],
    answer: "D", solution: "Geometric series with ratio $2$: sum $=\\dfrac{2^{13}-1}{2-1}=2^{13}-1=8191$." },
  { id: "mat-ex-073", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 4,
    question: "The sum to infinity of the geometric series with first term $1$ and common ratio $\\frac{1}{2}$ is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$\\frac{1}{2}$" },{ key: "C", text: "$2$" },{ key: "D", text: "$4$" },{ key: "E", text: "$1$" }],
    answer: "C", solution: "$S_\\infty=\\dfrac{a}{1-r}=\\dfrac{1}{1-\\frac{1}{2}}=2$." },
  { id: "mat-ex-074", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 4,
    question: "The sum to infinity of the geometric series with first term $2$ and common ratio $\\frac{1}{3}$ is:",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$3$" },{ key: "C", text: "$4$" },{ key: "D", text: "$2$" },{ key: "E", text: "$\\frac{4}{3}$" }],
    answer: "B", solution: "$S_\\infty=\\dfrac{a}{1-r}=\\dfrac{2}{1-\\frac{1}{3}}=3$." },
  { id: "mat-ex-075", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 4,
    question: "The sum to infinity of the geometric series with first term $3$ and common ratio $\\frac{1}{4}$ is:",
    options: [{ key: "A", text: "$\\frac{9}{4}$" },{ key: "B", text: "$3$" },{ key: "C", text: "$8$" },{ key: "D", text: "$4$" },{ key: "E", text: "$5$" }],
    answer: "D", solution: "$S_\\infty=\\dfrac{a}{1-r}=\\dfrac{3}{1-\\frac{1}{4}}=4$." },
  { id: "mat-ex-076", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 4,
    question: "The sum to infinity of the geometric series with first term $1$ and common ratio $\\frac{2}{3}$ is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$2$" },{ key: "C", text: "$\\frac{1}{3}$" },{ key: "D", text: "$4$" },{ key: "E", text: "$6$" }],
    answer: "A", solution: "$S_\\infty=\\dfrac{a}{1-r}=\\dfrac{1}{1-\\frac{2}{3}}=3$." },
  { id: "mat-ex-077", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 4,
    question: "The sum to infinity of the geometric series with first term $4$ and common ratio $\\frac{1}{5}$ is:",
    options: [{ key: "A", text: "$10$" },{ key: "B", text: "$4$" },{ key: "C", text: "$6$" },{ key: "D", text: "$5$" },{ key: "E", text: "$\\frac{16}{5}$" }],
    answer: "D", solution: "$S_\\infty=\\dfrac{a}{1-r}=\\dfrac{4}{1-\\frac{1}{5}}=5$." },
  { id: "mat-ex-078", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 4,
    question: "The sum to infinity of the geometric series with first term $1$ and common ratio $\\frac{3}{4}$ is:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$8$" },{ key: "C", text: "$\\frac{1}{4}$" },{ key: "D", text: "$5$" },{ key: "E", text: "$3$" }],
    answer: "A", solution: "$S_\\infty=\\dfrac{a}{1-r}=\\dfrac{1}{1-\\frac{3}{4}}=4$." },
  { id: "mat-ex-079", type: "mcq", testId: "mat", topicId: "mat-logic", difficulty: 1, marks: 4,
    question: "The negation of the statement $x>5$ is:",
    options: [{ key: "A", text: "$x\\ge 5$" },{ key: "B", text: "$x\\ne 5$" },{ key: "C", text: "$x\\le 5$" },{ key: "D", text: "$x=5$" },{ key: "E", text: "$x<5$" }],
    answer: "C", solution: "The negation of $x>5$ is $x\\le 5$." },
  { id: "mat-ex-080", type: "mcq", testId: "mat", topicId: "mat-logic", difficulty: 1, marks: 4,
    question: "The negation of the statement $x\\ge 0$ is:",
    options: [{ key: "A", text: "$x<0$" },{ key: "B", text: "$x\\ne 0$" },{ key: "C", text: "$x=0$" },{ key: "D", text: "$x>0$" },{ key: "E", text: "$x\\le 0$" }],
    answer: "A", solution: "The negation of $x\\ge 0$ is $x<0$." },
  { id: "mat-ex-081", type: "mcq", testId: "mat", topicId: "mat-logic", difficulty: 1, marks: 4,
    question: "The negation of the statement $x\\le -2$ is:",
    options: [{ key: "A", text: "$x\\ne -2$" },{ key: "B", text: "$x=-2$" },{ key: "C", text: "$x\\ge -2$" },{ key: "D", text: "$x<-2$" },{ key: "E", text: "$x>-2$" }],
    answer: "E", solution: "The negation of $x\\le -2$ is $x>-2$." },
  { id: "mat-ex-082", type: "mcq", testId: "mat", topicId: "mat-logic", difficulty: 1, marks: 4,
    question: "The negation of the statement $x<7$ is:",
    options: [{ key: "A", text: "$x=7$" },{ key: "B", text: "$x\\le 7$" },{ key: "C", text: "$x>7$" },{ key: "D", text: "$x\\ge 7$" },{ key: "E", text: "$x\\ne 7$" }],
    answer: "D", solution: "The negation of $x<7$ is $x\\ge 7$." },
  { id: "mat-ex-083", type: "mcq", testId: "mat", topicId: "mat-logic", difficulty: 3, marks: 4,
    question: "For how many integers $n$ with $1\\le n\\le 20$ is $n^2 + 3$ divisible by $4$?",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$8$" },{ key: "C", text: "$10$" },{ key: "D", text: "$11$" },{ key: "E", text: "$12$" }],
    answer: "C", solution: "Checking residues mod $4$, exactly $10$ values of $n$ in $1..20$ satisfy $4\\mid n^2+3$." },
  { id: "mat-ex-084", type: "mcq", testId: "mat", topicId: "mat-logic", difficulty: 3, marks: 4,
    question: "For how many integers $n$ with $1\\le n\\le 30$ is $n^2 + 0$ divisible by $3$?",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$8$" },{ key: "C", text: "$12$" },{ key: "D", text: "$10$" },{ key: "E", text: "$11$" }],
    answer: "D", solution: "Checking residues mod $3$, exactly $10$ values of $n$ in $1..30$ satisfy $3\\mid n^2+0$." },
  { id: "mat-ex-085", type: "mcq", testId: "mat", topicId: "mat-logic", difficulty: 3, marks: 4,
    question: "For how many integers $n$ with $1\\le n\\le 24$ is $n^2 + 1$ divisible by $2$?",
    options: [{ key: "A", text: "$14$" },{ key: "B", text: "$13$" },{ key: "C", text: "$10$" },{ key: "D", text: "$12$" },{ key: "E", text: "$11$" }],
    answer: "D", solution: "Checking residues mod $2$, exactly $12$ values of $n$ in $1..24$ satisfy $2\\mid n^2+1$." },
  { id: "mat-ex-086", type: "mcq", testId: "mat", topicId: "mat-logic", difficulty: 3, marks: 4,
    question: "For how many integers $n$ with $1\\le n\\le 40$ is $n^2 + 2$ divisible by $5$?",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$8$" },{ key: "C", text: "$0$" },{ key: "D", text: "$1$" },{ key: "E", text: "$20$" }],
    answer: "C", solution: "Checking residues mod $5$, exactly $0$ values of $n$ in $1..40$ satisfy $5\\mid n^2+2$." },
  { id: "mat-ex-087", type: "mcq", testId: "mat", topicId: "mat-logic", difficulty: 3, marks: 4,
    question: "For how many integers $n$ with $1\\le n\\le 20$ is $n^2 + 0$ divisible by $4$?",
    options: [{ key: "A", text: "$12$" },{ key: "B", text: "$9$" },{ key: "C", text: "$10$" },{ key: "D", text: "$11$" },{ key: "E", text: "$8$" }],
    answer: "C", solution: "Checking residues mod $4$, exactly $10$ values of $n$ in $1..20$ satisfy $4\\mid n^2+0$." },
  { id: "mat-ex-088", type: "mcq", testId: "mat", topicId: "mat-logic", difficulty: 3, marks: 4,
    question: "For how many integers $n$ with $1\\le n\\le 36$ is $n^2 + 3$ divisible by $4$?",
    options: [{ key: "A", text: "$17$" },{ key: "B", text: "$19$" },{ key: "C", text: "$16$" },{ key: "D", text: "$20$" },{ key: "E", text: "$18$" }],
    answer: "E", solution: "Checking residues mod $4$, exactly $18$ values of $n$ in $1..36$ satisfy $4\\mid n^2+3$." },
  { id: "mat-ex-089", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 2, marks: 4,
    question: "Outer loop $i=1,\\dots,5$; for each $i$ the inner loop runs $j=1,\\dots,i$. How many times does the inner body run in total?",
    options: [{ key: "A", text: "$14$" },{ key: "B", text: "$10$" },{ key: "C", text: "$25$" },{ key: "D", text: "$15$" },{ key: "E", text: "$16$" }],
    answer: "D", solution: "Total $=1+2+\\cdots+5=\\dfrac{5\\cdot6}{2}=15$." },
  { id: "mat-ex-090", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 2, marks: 4,
    question: "Outer loop $i=1,\\dots,6$; for each $i$ the inner loop runs $j=1,\\dots,i$. How many times does the inner body run in total?",
    options: [{ key: "A", text: "$36$" },{ key: "B", text: "$21$" },{ key: "C", text: "$22$" },{ key: "D", text: "$15$" },{ key: "E", text: "$20$" }],
    answer: "B", solution: "Total $=1+2+\\cdots+6=\\dfrac{6\\cdot7}{2}=21$." },
  { id: "mat-ex-091", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 2, marks: 4,
    question: "Outer loop $i=1,\\dots,8$; for each $i$ the inner loop runs $j=1,\\dots,i$. How many times does the inner body run in total?",
    options: [{ key: "A", text: "$37$" },{ key: "B", text: "$36$" },{ key: "C", text: "$28$" },{ key: "D", text: "$35$" },{ key: "E", text: "$64$" }],
    answer: "B", solution: "Total $=1+2+\\cdots+8=\\dfrac{8\\cdot9}{2}=36$." },
  { id: "mat-ex-092", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 2, marks: 4,
    question: "Outer loop $i=1,\\dots,10$; for each $i$ the inner loop runs $j=1,\\dots,i$. How many times does the inner body run in total?",
    options: [{ key: "A", text: "$100$" },{ key: "B", text: "$45$" },{ key: "C", text: "$56$" },{ key: "D", text: "$55$" },{ key: "E", text: "$54$" }],
    answer: "D", solution: "Total $=1+2+\\cdots+10=\\dfrac{10\\cdot11}{2}=55$." },
  { id: "mat-ex-093", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 2, marks: 4,
    question: "Outer loop $i=1,\\dots,7$; for each $i$ the inner loop runs $j=1,\\dots,i$. How many times does the inner body run in total?",
    options: [{ key: "A", text: "$21$" },{ key: "B", text: "$27$" },{ key: "C", text: "$29$" },{ key: "D", text: "$28$" },{ key: "E", text: "$49$" }],
    answer: "D", solution: "Total $=1+2+\\cdots+7=\\dfrac{7\\cdot8}{2}=28$." },
  { id: "mat-ex-094", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 2, marks: 4,
    question: "Outer loop $i=1,\\dots,9$; for each $i$ the inner loop runs $j=1,\\dots,i$. How many times does the inner body run in total?",
    options: [{ key: "A", text: "$36$" },{ key: "B", text: "$81$" },{ key: "C", text: "$45$" },{ key: "D", text: "$46$" },{ key: "E", text: "$44$" }],
    answer: "C", solution: "Total $=1+2+\\cdots+9=\\dfrac{9\\cdot10}{2}=45$." },
  { id: "mat-ex-095", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 2, marks: 4,
    question: "Outer loop $i=1,\\dots,12$; for each $i$ the inner loop runs $j=1,\\dots,i$. How many times does the inner body run in total?",
    options: [{ key: "A", text: "$144$" },{ key: "B", text: "$78$" },{ key: "C", text: "$79$" },{ key: "D", text: "$66$" },{ key: "E", text: "$77$" }],
    answer: "B", solution: "Total $=1+2+\\cdots+12=\\dfrac{12\\cdot13}{2}=78$." },
  { id: "mat-ex-096", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 2, marks: 4,
    question: "Outer loop $i=1,\\dots,4$; for each $i$ the inner loop runs $j=1,\\dots,i$. How many times does the inner body run in total?",
    options: [{ key: "A", text: "$10$" },{ key: "B", text: "$11$" },{ key: "C", text: "$16$" },{ key: "D", text: "$6$" },{ key: "E", text: "$9$" }],
    answer: "A", solution: "Total $=1+2+\\cdots+4=\\dfrac{4\\cdot5}{2}=10$." },
  { id: "mat-ex-097", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 3, marks: 4,
    question: "How many $3$-digit numbers are there with all digits distinct and even?",
    options: [{ key: "A", text: "$288$" },{ key: "B", text: "$336$" },{ key: "C", text: "$320$" },{ key: "D", text: "$328$" },{ key: "E", text: "$368$" }],
    answer: "D", solution: "Direct count by casework on the units digit gives $328$." },
  { id: "mat-ex-098", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 3, marks: 4,
    question: "How many $3$-digit numbers are there with all digits distinct?",
    options: [{ key: "A", text: "$648$" },{ key: "B", text: "$608$" },{ key: "C", text: "$688$" },{ key: "D", text: "$656$" },{ key: "E", text: "$640$" }],
    answer: "A", solution: "Direct count by casework on the units digit gives $648$." },
  { id: "mat-ex-099", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 3, marks: 4,
    question: "How many $3$-digit numbers are there that are even?",
    options: [{ key: "A", text: "$458$" },{ key: "B", text: "$410$" },{ key: "C", text: "$490$" },{ key: "D", text: "$450$" },{ key: "E", text: "$442$" }],
    answer: "D", solution: "Direct count by casework on the units digit gives $450$." },
  { id: "mat-ex-100", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 2, marks: 4,
    question: "How many $1$s appear in the binary representation of $23$?",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$4$" },{ key: "C", text: "$6$" },{ key: "D", text: "$3$" },{ key: "E", text: "$7$" }],
    answer: "B", solution: "$23_{10}=10111_2$, which contains $4$ ones." },
  { id: "mat-ex-101", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 2, marks: 4,
    question: "How many $1$s appear in the binary representation of $45$?",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$4$" },{ key: "C", text: "$5$" },{ key: "D", text: "$3$" },{ key: "E", text: "$7$" }],
    answer: "B", solution: "$45_{10}=101101_2$, which contains $4$ ones." },
  { id: "mat-ex-102", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 2, marks: 4,
    question: "How many $1$s appear in the binary representation of $60$?",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$4$" },{ key: "C", text: "$3$" },{ key: "D", text: "$5$" },{ key: "E", text: "$6$" }],
    answer: "B", solution: "$60_{10}=111100_2$, which contains $4$ ones." },
];
