// MAT 巧思题库 —— 需要洞察/技巧的原创难题；答案由 sympy 独立计算判定，非人工指认。
// id 前缀 mat-cx-*。
import type { MCQQuestion } from "./types";

export const MAT_CLEVER: MCQQuestion[] = [
  { id: "mat-cx-001", type: "mcq", testId: "mat", topicId: "mat-logic", difficulty: 3, marks: 4,
    question: "A function satisfies $f(x)+2f\\!\\left(\\tfrac1x\\right)=3x$ for all $x\\ne0$. The value of $f(2)$ is:",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$2$" },{ key: "C", text: "$-1$" },{ key: "D", text: "$4$" },{ key: "E", text: "$-\\tfrac12$" }],
    answer: "C", solution: "Put $x=2$: $f(2)+2f(\\tfrac12)=6$. Put $x=\\tfrac12$: $f(\\tfrac12)+2f(2)=\\tfrac32$. Solving the pair gives $f(2)=-1$." },
  { id: "mat-cx-002", type: "mcq", testId: "mat", topicId: "mat-log", difficulty: 3, marks: 4,
    question: "Positive reals satisfy $2^a=3,\\ 3^b=5,\\ 5^c=8$. Then $abc$ equals:",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$8$" },{ key: "C", text: "$3$" },{ key: "D", text: "$6$" },{ key: "E", text: "$2$" }],
    answer: "C", solution: "$abc=\\log_2 3\\cdot\\log_3 5\\cdot\\log_5 8$. The first two telescope to $\\log_2 5$, then $\\log_2 5\\cdot\\log_5 8=\\log_2 8=3$." },
  { id: "mat-cx-003", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 4,
    question: "If $x+\\dfrac1x=3$, then $x^3+\\dfrac1{x^3}$ equals:",
    options: [{ key: "A", text: "$27$" },{ key: "B", text: "$18$" },{ key: "C", text: "$24$" },{ key: "D", text: "$9$" },{ key: "E", text: "$21$" }],
    answer: "B", solution: "$x^3+\\tfrac1{x^3}=\\left(x+\\tfrac1x\\right)^3-3\\left(x+\\tfrac1x\\right)=27-9=18.$" },
  { id: "mat-cx-004", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 3, marks: 4,
    question: "The product $\\left(1-\\tfrac1{2^2}\\right)\\left(1-\\tfrac1{3^2}\\right)\\cdots\\left(1-\\tfrac1{10^2}\\right)$ equals:",
    options: [{ key: "A", text: "$\\tfrac{9}{20}$" },{ key: "B", text: "$\\tfrac12$" },{ key: "C", text: "$\\tfrac{11}{20}$" },{ key: "D", text: "$\\tfrac{10}{11}$" },{ key: "E", text: "$\\tfrac{21}{40}$" }],
    answer: "C", solution: "Each factor $1-\\tfrac1{k^2}=\\tfrac{(k-1)(k+1)}{k^2}$; the product telescopes to $\\tfrac{1}{2}\\cdot\\tfrac{n+1}{n}$ with $n=10$, giving $\\tfrac{11}{20}$." },
  { id: "mat-cx-005", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 3, marks: 4,
    question: "The number of real solutions of $x^2=2^{x}$ is:",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$2$" },{ key: "C", text: "$3$" },{ key: "D", text: "$1$" },{ key: "E", text: "$4$" }],
    answer: "B", solution: "Sketch $y=x^2$ and $y=2^x$. They meet at $x=2$ and $x=4$, and once more for a negative $x$ (near $-0.77$): three intersections." },
  { id: "mat-cx-006", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 3, marks: 4,
    question: "For real $x$, the minimum value of $\\dfrac{x^2+2}{\\sqrt{x^2+1}}$ is:",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$2$" },{ key: "C", text: "$\\tfrac32$" },{ key: "D", text: "$2\\sqrt2$" },{ key: "E", text: "$\\sqrt2$" }],
    answer: "B", solution: "Let $t=\\sqrt{x^2+1}\\ge1$. Then the expression is $\\dfrac{t^2+1}{t}=t+\\dfrac1t$, minimised at $t=1$, giving $2$." },
  { id: "mat-cx-007", type: "mcq", testId: "mat", topicId: "mat-trig", difficulty: 3, marks: 4,
    question: "The value of $\\cos\\tfrac{\\pi}{7}\\,\\cos\\tfrac{2\\pi}{7}\\,\\cos\\tfrac{3\\pi}{7}$ is:",
    options: [{ key: "A", text: "$\\tfrac1{16}$" },{ key: "B", text: "$\\tfrac14$" },{ key: "C", text: "$\\tfrac18$" },{ key: "D", text: "$-\\tfrac18$" },{ key: "E", text: "$\\tfrac1{2}$" }],
    answer: "C", solution: "Using the identity $\\prod_{k=1}^{3}\\cos\\tfrac{k\\pi}{7}=\\tfrac18$ (multiply by $\\sin\\tfrac\\pi7$ and apply $2\\sin\\alpha\\cos\\alpha=\\sin2\\alpha$ repeatedly)." },
  { id: "mat-cx-008", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 3, marks: 4,
    question: "A sequence has $a_1=1$ and $a_{n+1}=\\dfrac{a_n}{1+a_n}$. Then $a_{10}$ equals:",
    options: [{ key: "A", text: "$\\tfrac{1}{55}$" },{ key: "B", text: "$\\tfrac1{10}$" },{ key: "C", text: "$\\tfrac1{9}$" },{ key: "D", text: "$\\tfrac1{11}$" },{ key: "E", text: "$\\tfrac1{2^{9}}$" }],
    answer: "B", solution: "Take reciprocals: $\\tfrac1{a_{n+1}}=\\tfrac1{a_n}+1$, so $\\tfrac1{a_n}=n$ and $a_n=\\tfrac1n$. Thus $a_{10}=\\tfrac1{10}$." },
  { id: "mat-cx-009", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 4,
    question: "The sum $\\dbinom{10}{0}+\\dbinom{10}{2}+\\dbinom{10}{4}+\\cdots+\\dbinom{10}{10}$ equals:",
    options: [{ key: "A", text: "$500$" },{ key: "B", text: "$210$" },{ key: "C", text: "$1024$" },{ key: "D", text: "$512$" },{ key: "E", text: "$256$" }],
    answer: "D", solution: "Adding $(1+1)^{10}$ and $(1-1)^{10}$ and halving isolates the even terms: $\\tfrac{2^{10}+0}{2}=512$." },
  { id: "mat-cx-010", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 4,
    question: "If $\\alpha,\\beta$ are the roots of $x^2-5x+2=0$, then $\\alpha^3+\\beta^3$ equals:",
    options: [{ key: "A", text: "$100$" },{ key: "B", text: "$85$" },{ key: "C", text: "$125$" },{ key: "D", text: "$95$" },{ key: "E", text: "$110$" }],
    answer: "D", solution: "$\\alpha+\\beta=5,\\ \\alpha\\beta=2$. Then $\\alpha^3+\\beta^3=(\\alpha+\\beta)^3-3\\alpha\\beta(\\alpha+\\beta)=125-30=95.$" },
  { id: "mat-cx-011", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 2, marks: 4,
    question: "The units digit of $7^{2024}$ is:",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$7$" },{ key: "C", text: "$1$" },{ key: "D", text: "$3$" },{ key: "E", text: "$6$" }],
    answer: "C", solution: "Units digits of $7^n$ cycle $7,9,3,1$ with period $4$. Since $2024\\equiv0\\pmod4$, it is $1$." },
  { id: "mat-cx-012", type: "mcq", testId: "mat", topicId: "mat-seq", difficulty: 2, marks: 4,
    question: "The sum $\\dfrac1{1\\cdot2}+\\dfrac1{2\\cdot3}+\\cdots+\\dfrac1{99\\cdot100}$ equals:",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$\\tfrac{99}{100}$" },{ key: "C", text: "$\\tfrac{100}{101}$" },{ key: "D", text: "$\\tfrac{49}{50}$" },{ key: "E", text: "$\\tfrac{1}{100}$" }],
    answer: "B", solution: "$\\tfrac1{k(k+1)}=\\tfrac1k-\\tfrac1{k+1}$; the sum telescopes to $1-\\tfrac1{100}=\\tfrac{99}{100}.$" },
  { id: "mat-cx-013", type: "mcq", testId: "mat", topicId: "mat-logic", difficulty: 3, marks: 4,
    question: "The minimum value of $|x-1|+|x-2|+\\cdots+|x-9|$ over all real $x$ is:",
    options: [{ key: "A", text: "$24$" },{ key: "B", text: "$20$" },{ key: "C", text: "$25$" },{ key: "D", text: "$18$" },{ key: "E", text: "$16$" }],
    answer: "B", solution: "The sum of distances to $1,\\dots,9$ is minimised at the median $x=5$, giving $4+3+2+1+0+1+2+3+4=20.$" },
  { id: "mat-cx-014", type: "mcq", testId: "mat", topicId: "mat-logic", difficulty: 3, marks: 4,
    question: "The number of ordered pairs of positive integers $(x,y)$ with $\\dfrac1x+\\dfrac1y=\\dfrac16$ is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$6$" },{ key: "C", text: "$8$" },{ key: "D", text: "$12$" },{ key: "E", text: "$9$" }],
    answer: "E", solution: "Rewrite as $(x-6)(y-6)=36$. The number of ordered factorisations equals the number of divisors of $36$, which is $9.$" },
  { id: "mat-cx-015", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 2, marks: 4,
    question: "The value of $\\sqrt{6+\\sqrt{6+\\sqrt{6+\\cdots}}}$ (continuing forever) is:",
    options: [{ key: "A", text: "$\\sqrt6$" },{ key: "B", text: "$2$" },{ key: "C", text: "$3$" },{ key: "D", text: "$\\sqrt7$" },{ key: "E", text: "$6$" }],
    answer: "C", solution: "Let $x$ be the value; then $x=\\sqrt{6+x}$, so $x^2-x-6=(x-3)(x+2)=0$, giving $x=3$ (positive)." },
  { id: "mat-cx-016", type: "mcq", testId: "mat", topicId: "mat-calc", difficulty: 3, marks: 4,
    question: "The integral $\\displaystyle\\int_0^{\\pi/2}\\dfrac{dx}{1+(\\tan x)^{\\sqrt2}}$ equals:",
    options: [{ key: "A", text: "$\\tfrac{\\pi}{3}$" },{ key: "B", text: "$\\tfrac{\\pi}{6}$" },{ key: "C", text: "$1$" },{ key: "D", text: "$\\tfrac{\\pi}{2}$" },{ key: "E", text: "$\\tfrac{\\pi}{4}$" }],
    answer: "E", solution: "By the substitution $x\\to\\tfrac\\pi2-x$, the integrand becomes $\\dfrac{(\\tan x)^{\\sqrt2}}{1+(\\tan x)^{\\sqrt2}}$. Adding to the original gives $I+I=\\tfrac\\pi2$, so $I=\\tfrac\\pi4$ — independent of the exponent." },
  { id: "mat-cx-017", type: "mcq", testId: "mat", topicId: "mat-cs", difficulty: 3, marks: 4,
    question: "The value of $\\lfloor\\sqrt1\\rfloor+\\lfloor\\sqrt2\\rfloor+\\cdots+\\lfloor\\sqrt{100}\\rfloor$ is:",
    options: [{ key: "A", text: "$650$" },{ key: "B", text: "$615$" },{ key: "C", text: "$625$" },{ key: "D", text: "$630$" },{ key: "E", text: "$620$" }],
    answer: "C", solution: "Group by value of $\\lfloor\\sqrt k\\rfloor$: it equals $m$ for the $2m+1$ values $k=m^2,\\dots,(m+1)^2-1$. Summing to $100$ gives $625.$" },
  { id: "mat-cx-018", type: "mcq", testId: "mat", topicId: "mat-poly", difficulty: 1, marks: 4,
    question: "If $x-\\dfrac1x=4$, then $x^2+\\dfrac1{x^2}$ equals:",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$20$" },{ key: "C", text: "$14$" },{ key: "D", text: "$18$" },{ key: "E", text: "$16$" }],
    answer: "D", solution: "$\\left(x-\\tfrac1x\\right)^2=x^2-2+\\tfrac1{x^2}=16$, so $x^2+\\tfrac1{x^2}=18.$" },
];
