// PAT 巧思题库 —— 经典物理妙题；答案由程序独立计算/解网络验证。id 前缀 pat-cx-*。
import type { MCQQuestion } from "./types";

export const PAT_CLEVER: MCQQuestion[] = [
  { id: "pat-cx-001", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 3, marks: 4,
    question: "A bead moves on the inside of a vertical circular loop of radius $10\\,\\text{m}$ ($g=10$). The minimum speed at the top to maintain contact is:",
    options: [{ key: "A", text: "$5\\,\\text{m/s}$" },{ key: "B", text: "$20\\,\\text{m/s}$" },{ key: "C", text: "$\\sqrt{200}\\,\\text{m/s}$" },{ key: "D", text: "$10\\,\\text{m/s}$" },{ key: "E", text: "$\\sqrt{50}\\,\\text{m/s}$" }],
    answer: "D", solution: "At the top, gravity supplies the centripetal force: $mg=\\dfrac{mv^2}{r}\\Rightarrow v=\\sqrt{gr}=\\sqrt{100}=10\\,$m/s." },
  { id: "pat-cx-002", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 3, marks: 4,
    question: "For a mass to just complete a vertical loop of radius $2\\,\\text{m}$ ($g=10$), its minimum speed at the bottom is:",
    options: [{ key: "A", text: "$\\sqrt{20}\\,\\text{m/s}$" },{ key: "B", text: "$20\\,\\text{m/s}$" },{ key: "C", text: "$10\\,\\text{m/s}$" },{ key: "D", text: "$\\sqrt{60}\\,\\text{m/s}$" },{ key: "E", text: "$\\sqrt{40}\\,\\text{m/s}$" }],
    answer: "C", solution: "Energy + top condition give $v_{bottom}=\\sqrt{5gr}=\\sqrt{5\\cdot10\\cdot2}=\\sqrt{100}=10\\,$m/s." },
  { id: "pat-cx-003", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "A projectile is launched at $20\\,\\text{m/s}$ ($g=10$). Its maximum possible range (at $45^\\circ$) is:",
    options: [{ key: "A", text: "$20\\,\\text{m}$" },{ key: "B", text: "$45\\,\\text{m}$" },{ key: "C", text: "$60\\,\\text{m}$" },{ key: "D", text: "$80\\,\\text{m}$" },{ key: "E", text: "$40\\,\\text{m}$" }],
    answer: "E", solution: "Range $=\\dfrac{u^2\\sin2\\theta}{g}$, maximal at $\\theta=45^\\circ$: $\\dfrac{u^2}{g}=\\dfrac{400}{10}=40\\,$m." },
  { id: "pat-cx-004", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 3, marks: 4,
    question: "Two masses $3\\,\\text{kg}$ and $1\\,\\text{kg}$ hang over a frictionless pulley ($g=10$). The acceleration of the system is:",
    options: [{ key: "A", text: "$20\\,\\text{m/s}^2$" },{ key: "B", text: "$7.5\\,\\text{m/s}^2$" },{ key: "C", text: "$5\\,\\text{m/s}^2$" },{ key: "D", text: "$10\\,\\text{m/s}^2$" },{ key: "E", text: "$2.5\\,\\text{m/s}^2$" }],
    answer: "C", solution: "$a=\\dfrac{(m_1-m_2)g}{m_1+m_2}=\\dfrac{2\\cdot10}{4}=5\\,$m/s$^2$." },
  { id: "pat-cx-005", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 3, marks: 4,
    question: "Twelve identical $6\\,\\Omega$ resistors form the edges of a cube. The resistance between two opposite corners is:",
    options: [{ key: "A", text: "$7\\,\\Omega$" },{ key: "B", text: "$3\\,\\Omega$" },{ key: "C", text: "$4\\,\\Omega$" },{ key: "D", text: "$5\\,\\Omega$" },{ key: "E", text: "$6\\,\\Omega$" }],
    answer: "D", solution: "By symmetry the resistance between opposite corners is $\\tfrac{5}{6}R=\\tfrac56\\cdot6=5\\,\\Omega$ (verified by solving the network)." },
  { id: "pat-cx-006", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 3, marks: 4,
    question: "An infinite ladder repeats: a series resistor $R$ then a shunt resistor $R$ to the bottom rail, forever. With $R=1\\,\\Omega$, the input resistance is:",
    options: [{ key: "A", text: "$\\sqrt2\\,\\Omega$" },{ key: "B", text: "$\\tfrac{1+\\sqrt3}{2}\\,\\Omega$" },{ key: "C", text: "$\\sqrt3\\,\\Omega$" },{ key: "D", text: "$\\tfrac{1+\\sqrt5}{2}\\,\\Omega$" },{ key: "E", text: "$2\\,\\Omega$" }],
    answer: "D", solution: "Self-similarity: $R_t=R+\\dfrac{R\\,R_t}{R+R_t}$. With $R=1$: $R_t^2-R_t-1=0\\Rightarrow R_t=\\tfrac{1+\\sqrt5}{2}.$" },
  { id: "pat-cx-007", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "A $2\\,\\text{kg}$ object falls under gravity ($g=10$) with drag $F=kv$, $k=4\\,\\text{kg/s}$. Its terminal velocity is:",
    options: [{ key: "A", text: "$10\\,\\text{m/s}$" },{ key: "B", text: "$20\\,\\text{m/s}$" },{ key: "C", text: "$8\\,\\text{m/s}$" },{ key: "D", text: "$2.5\\,\\text{m/s}$" },{ key: "E", text: "$5\\,\\text{m/s}$" }],
    answer: "E", solution: "At terminal velocity weight balances drag: $mg=kv\\Rightarrow v=\\dfrac{mg}{k}=\\dfrac{20}{4}=5\\,$m/s." },
  { id: "pat-cx-008", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 3, marks: 4,
    question: "A $1\\,\\text{kg}$ lump embeds in a $9\\,\\text{kg}$ block; the pair rises $\\frac{1}{5}\\,\\text{m}$ ($g=10$). The lump's initial speed was:",
    options: [{ key: "A", text: "$20\\,\\text{m/s}$" },{ key: "B", text: "$18\\,\\text{m/s}$" },{ key: "C", text: "$2\\,\\text{m/s}$" },{ key: "D", text: "$10\\,\\text{m/s}$" },{ key: "E", text: "$40\\,\\text{m/s}$" }],
    answer: "A", solution: "Rise gives $V=\\sqrt{2gh}=\\sqrt{4}=2$. Momentum: $m v=(M+m)V\\Rightarrow v=\\dfrac{10}{1}\\cdot2=20\\,$m/s." },
  { id: "pat-cx-009", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 3, marks: 4,
    question: "On a planet where surface $g=10$ and radius corresponds to $2gr=100$ (with $r=5$), the escape speed is:",
    options: [{ key: "A", text: "$\\sqrt{150}\\,\\text{m/s}$" },{ key: "B", text: "$5\\,\\text{m/s}$" },{ key: "C", text: "$10\\,\\text{m/s}$" },{ key: "D", text: "$\\sqrt{50}\\,\\text{m/s}$" },{ key: "E", text: "$20\\,\\text{m/s}$" }],
    answer: "C", solution: "Escape speed $=\\sqrt{2GM/r}=\\sqrt{2gr}=\\sqrt{2\\cdot10\\cdot5}=\\sqrt{100}=10\\,$m/s." },
  { id: "pat-cx-010", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "A simple pendulum's length is quadrupled. Its period becomes this many times the original:",
    options: [{ key: "A", text: "$\\tfrac12$" },{ key: "B", text: "$4$" },{ key: "C", text: "$8$" },{ key: "D", text: "$\\sqrt2$" },{ key: "E", text: "$2$" }],
    answer: "E", solution: "$T=2\\pi\\sqrt{L/g}\\propto\\sqrt L$; quadrupling $L$ multiplies $T$ by $\\sqrt4=2$." },
  { id: "pat-cx-011", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 3, marks: 4,
    question: "By dimensional analysis, a pendulum's period $T$ depends on length $L$ and $g$ as $T\\propto L^a g^b$. The exponent $a$ is:",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$2$" },{ key: "C", text: "$-\\tfrac12$" },{ key: "D", text: "$\\tfrac12$" },{ key: "E", text: "$0$" }],
    answer: "D", solution: "$[T]=[L]^a[LT^{-2}]^b\\Rightarrow a+b=0,\\ -2b=1\\Rightarrow b=-\\tfrac12,\\ a=\\tfrac12.$" },
  { id: "pat-cx-012", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 3, marks: 4,
    question: "A planet's orbital radius is increased by a factor of $4$. By Kepler's third law, its period increases by a factor of:",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$64$" },{ key: "C", text: "$2$" },{ key: "D", text: "$4$" },{ key: "E", text: "$16$" }],
    answer: "A", solution: "$T^2\\propto r^3\\Rightarrow T\\propto r^{3/2}$; $4^{3/2}=8$." },
  { id: "pat-cx-013", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "$5$ identical resistors each $1\\,\\Omega$ are connected in parallel. The total resistance is:",
    options: [{ key: "A", text: "$0.2\\,\\Omega$" },{ key: "B", text: "$0.5\\,\\Omega$" },{ key: "C", text: "$5\\,\\Omega$" },{ key: "D", text: "$2\\,\\Omega$" },{ key: "E", text: "$1\\,\\Omega$" }],
    answer: "A", solution: "$n$ equal resistors in parallel give $R/n=1/5=0.2\\,\\Omega$." },
  { id: "pat-cx-014", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "In a head-on elastic collision between two equal masses, one moving at $u$ and one at rest, the speed of the initially-moving mass afterwards is:",
    options: [{ key: "A", text: "$2u$" },{ key: "B", text: "$\\tfrac{u}{4}$" },{ key: "C", text: "$0$" },{ key: "D", text: "$u$" },{ key: "E", text: "$\\tfrac{u}{2}$" }],
    answer: "C", solution: "Equal masses exchange velocities in an elastic collision, so the incoming mass stops." },
  { id: "pat-cx-015", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 3, marks: 4,
    question: "A $2\\,\\text{kg}$ block at $4\\,\\text{m/s}$ compresses a spring ($k=8\\,\\text{N/m}$). The maximum compression is:",
    options: [{ key: "A", text: "$4\\,\\text{m}$" },{ key: "B", text: "$2\\,\\text{m}$" },{ key: "C", text: "$8\\,\\text{m}$" },{ key: "D", text: "$\\sqrt2\\,\\text{m}$" },{ key: "E", text: "$1\\,\\text{m}$" }],
    answer: "B", solution: "Energy: $\\tfrac12 mv^2=\\tfrac12 kx^2\\Rightarrow x=v\\sqrt{m/k}=4\\sqrt{2/8}=4\\cdot\\tfrac12=2\\,$m." },
  { id: "pat-cx-016", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "A photon of energy $E$ has momentum:",
    options: [{ key: "A", text: "$Ec$" },{ key: "B", text: "$\\dfrac{E}{c^2}$" },{ key: "C", text: "$E c^2$" },{ key: "D", text: "$\\dfrac{E}{c}$" },{ key: "E", text: "$\\dfrac{c}{E}$" }],
    answer: "D", solution: "For a photon $E=pc$, so $p=E/c$." },
];
