// PAT 练习题库 —— 生成器 + 精确算术计算答案，答案天生正确，另经独立复核。
// id 前缀 pat-ex-*。
import type { MCQQuestion } from "./types";

export const PAT_EXPANSION: MCQQuestion[] = [
  { id: "pat-ex-001", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "An object has initial velocity $0\\,\\text{m/s}$ and acceleration $2\\,\\text{m/s}^2$. After $5\\,\\text{s}$ its velocity is:",
    options: [{ key: "A", text: "$-10\\,\\text{m/s}$" },{ key: "B", text: "$10\\,\\text{m/s}$" },{ key: "C", text: "$20\\,\\text{m/s}$" },{ key: "D", text: "$5\\,\\text{m/s}$" },{ key: "E", text: "$12\\,\\text{m/s}$" }],
    answer: "B", solution: "$v=u+at=0+(2)(5)=10\\,$m/s." },
  { id: "pat-ex-002", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "An object has initial velocity $5\\,\\text{m/s}$ and acceleration $3\\,\\text{m/s}^2$. After $4\\,\\text{s}$ its velocity is:",
    options: [{ key: "A", text: "$19\\,\\text{m/s}$" },{ key: "B", text: "$29\\,\\text{m/s}$" },{ key: "C", text: "$17\\,\\text{m/s}$" },{ key: "D", text: "$12\\,\\text{m/s}$" },{ key: "E", text: "$-7\\,\\text{m/s}$" }],
    answer: "C", solution: "$v=u+at=5+(3)(4)=17\\,$m/s." },
  { id: "pat-ex-003", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "An object has initial velocity $10\\,\\text{m/s}$ and acceleration $-2\\,\\text{m/s}^2$. After $3\\,\\text{s}$ its velocity is:",
    options: [{ key: "A", text: "$4\\,\\text{m/s}$" },{ key: "B", text: "$-17\\,\\text{m/s}$" },{ key: "C", text: "$16\\,\\text{m/s}$" },{ key: "D", text: "$-2\\,\\text{m/s}$" },{ key: "E", text: "$-6\\,\\text{m/s}$" }],
    answer: "A", solution: "$v=u+at=10+(-2)(3)=4\\,$m/s." },
  { id: "pat-ex-004", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "An object has initial velocity $2\\,\\text{m/s}$ and acceleration $4\\,\\text{m/s}^2$. After $6\\,\\text{s}$ its velocity is:",
    options: [{ key: "A", text: "$50\\,\\text{m/s}$" },{ key: "B", text: "$-22\\,\\text{m/s}$" },{ key: "C", text: "$14\\,\\text{m/s}$" },{ key: "D", text: "$26\\,\\text{m/s}$" },{ key: "E", text: "$24\\,\\text{m/s}$" }],
    answer: "D", solution: "$v=u+at=2+(4)(6)=26\\,$m/s." },
  { id: "pat-ex-005", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "An object has initial velocity $0\\,\\text{m/s}$ and acceleration $10\\,\\text{m/s}^2$. After $3\\,\\text{s}$ its velocity is:",
    options: [{ key: "A", text: "$3\\,\\text{m/s}$" },{ key: "B", text: "$-30\\,\\text{m/s}$" },{ key: "C", text: "$60\\,\\text{m/s}$" },{ key: "D", text: "$30\\,\\text{m/s}$" },{ key: "E", text: "$32\\,\\text{m/s}$" }],
    answer: "D", solution: "$v=u+at=0+(10)(3)=30\\,$m/s." },
  { id: "pat-ex-006", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "An object has initial velocity $8\\,\\text{m/s}$ and acceleration $-1\\,\\text{m/s}^2$. After $4\\,\\text{s}$ its velocity is:",
    options: [{ key: "A", text: "$0\\,\\text{m/s}$" },{ key: "B", text: "$4\\,\\text{m/s}$" },{ key: "C", text: "$6\\,\\text{m/s}$" },{ key: "D", text: "$12\\,\\text{m/s}$" },{ key: "E", text: "$-4\\,\\text{m/s}$" }],
    answer: "B", solution: "$v=u+at=8+(-1)(4)=4\\,$m/s." },
  { id: "pat-ex-007", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "A $3\\,\\text{kg}$ trolley moving at $8\\,\\text{m/s}$ collides and sticks to a stationary $1\\,\\text{kg}$ trolley. Their common velocity is:",
    options: [{ key: "A", text: "$6\\,\\text{m/s}$" },{ key: "B", text: "$24\\,\\text{m/s}$" },{ key: "C", text: "$4\\,\\text{m/s}$" },{ key: "D", text: "$8\\,\\text{m/s}$" },{ key: "E", text: "$7\\,\\text{m/s}$" }],
    answer: "A", solution: "Momentum: $m_1u_1=(m_1+m_2)v\\Rightarrow v=\\dfrac{3\\cdot8}{4}=6\\,$m/s." },
  { id: "pat-ex-008", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "A $1\\,\\text{kg}$ trolley moving at $10\\,\\text{m/s}$ collides and sticks to a stationary $4\\,\\text{kg}$ trolley. Their common velocity is:",
    options: [{ key: "A", text: "$3\\,\\text{m/s}$" },{ key: "B", text: "$\\frac{5}{2}\\,\\text{m/s}$" },{ key: "C", text: "$2\\,\\text{m/s}$" },{ key: "D", text: "$10\\,\\text{m/s}$" },{ key: "E", text: "$5\\,\\text{m/s}$" }],
    answer: "C", solution: "Momentum: $m_1u_1=(m_1+m_2)v\\Rightarrow v=\\dfrac{1\\cdot10}{5}=2\\,$m/s." },
  { id: "pat-ex-009", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "A $2\\,\\text{kg}$ trolley moving at $9\\,\\text{m/s}$ collides and sticks to a stationary $1\\,\\text{kg}$ trolley. Their common velocity is:",
    options: [{ key: "A", text: "$7\\,\\text{m/s}$" },{ key: "B", text: "$6\\,\\text{m/s}$" },{ key: "C", text: "$18\\,\\text{m/s}$" },{ key: "D", text: "$\\frac{9}{2}\\,\\text{m/s}$" },{ key: "E", text: "$9\\,\\text{m/s}$" }],
    answer: "B", solution: "Momentum: $m_1u_1=(m_1+m_2)v\\Rightarrow v=\\dfrac{2\\cdot9}{3}=6\\,$m/s." },
  { id: "pat-ex-010", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "A $4\\,\\text{kg}$ trolley moving at $5\\,\\text{m/s}$ collides and sticks to a stationary $6\\,\\text{kg}$ trolley. Their common velocity is:",
    options: [{ key: "A", text: "$5\\,\\text{m/s}$" },{ key: "B", text: "$\\frac{10}{3}\\,\\text{m/s}$" },{ key: "C", text: "$2\\,\\text{m/s}$" },{ key: "D", text: "$\\frac{5}{2}\\,\\text{m/s}$" },{ key: "E", text: "$3\\,\\text{m/s}$" }],
    answer: "C", solution: "Momentum: $m_1u_1=(m_1+m_2)v\\Rightarrow v=\\dfrac{4\\cdot5}{10}=2\\,$m/s." },
  { id: "pat-ex-011", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "The kinetic energy of a $2\\,\\text{kg}$ mass moving at $3\\,\\text{m/s}$ is:",
    options: [{ key: "A", text: "$18\\,\\text{J}$" },{ key: "B", text: "$3\\,\\text{J}$" },{ key: "C", text: "$6\\,\\text{J}$" },{ key: "D", text: "$\\frac{9}{2}\\,\\text{J}$" },{ key: "E", text: "$9\\,\\text{J}$" }],
    answer: "E", solution: "$E_k=\\tfrac12 mv^2=\\tfrac12(2)(3)^2=9\\,$J." },
  { id: "pat-ex-012", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "The kinetic energy of a $4\\,\\text{kg}$ mass moving at $5\\,\\text{m/s}$ is:",
    options: [{ key: "A", text: "$100\\,\\text{J}$" },{ key: "B", text: "$25\\,\\text{J}$" },{ key: "C", text: "$50\\,\\text{J}$" },{ key: "D", text: "$20\\,\\text{J}$" },{ key: "E", text: "$10\\,\\text{J}$" }],
    answer: "C", solution: "$E_k=\\tfrac12 mv^2=\\tfrac12(4)(5)^2=50\\,$J." },
  { id: "pat-ex-013", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "The kinetic energy of a $1\\,\\text{kg}$ mass moving at $10\\,\\text{m/s}$ is:",
    options: [{ key: "A", text: "$100\\,\\text{J}$" },{ key: "B", text: "$25\\,\\text{J}$" },{ key: "C", text: "$5\\,\\text{J}$" },{ key: "D", text: "$50\\,\\text{J}$" },{ key: "E", text: "$10\\,\\text{J}$" }],
    answer: "D", solution: "$E_k=\\tfrac12 mv^2=\\tfrac12(1)(10)^2=50\\,$J." },
  { id: "pat-ex-014", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "The kinetic energy of a $3\\,\\text{kg}$ mass moving at $4\\,\\text{m/s}$ is:",
    options: [{ key: "A", text: "$26\\,\\text{J}$" },{ key: "B", text: "$24\\,\\text{J}$" },{ key: "C", text: "$6\\,\\text{J}$" },{ key: "D", text: "$12\\,\\text{J}$" },{ key: "E", text: "$48\\,\\text{J}$" }],
    answer: "B", solution: "$E_k=\\tfrac12 mv^2=\\tfrac12(3)(4)^2=24\\,$J." },
  { id: "pat-ex-015", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "The kinetic energy of a $2\\,\\text{kg}$ mass moving at $6\\,\\text{m/s}$ is:",
    options: [{ key: "A", text: "$12\\,\\text{J}$" },{ key: "B", text: "$72\\,\\text{J}$" },{ key: "C", text: "$36\\,\\text{J}$" },{ key: "D", text: "$18\\,\\text{J}$" },{ key: "E", text: "$6\\,\\text{J}$" }],
    answer: "C", solution: "$E_k=\\tfrac12 mv^2=\\tfrac12(2)(6)^2=36\\,$J." },
  { id: "pat-ex-016", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "A $2\\,\\text{kg}$ mass moves in a circle of radius $8\\,\\text{m}$ at $4\\,\\text{m/s}$. The centripetal force is:",
    options: [{ key: "A", text: "$5\\,\\text{N}$" },{ key: "B", text: "$1\\,\\text{N}$" },{ key: "C", text: "$32\\,\\text{N}$" },{ key: "D", text: "$4\\,\\text{N}$" },{ key: "E", text: "$2\\,\\text{N}$" }],
    answer: "D", solution: "$F=\\dfrac{mv^2}{r}=\\dfrac{2\\cdot4^2}{8}=4\\,$N." },
  { id: "pat-ex-017", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "A $1\\,\\text{kg}$ mass moves in a circle of radius $3\\,\\text{m}$ at $6\\,\\text{m/s}$. The centripetal force is:",
    options: [{ key: "A", text: "$6\\,\\text{N}$" },{ key: "B", text: "$13\\,\\text{N}$" },{ key: "C", text: "$36\\,\\text{N}$" },{ key: "D", text: "$2\\,\\text{N}$" },{ key: "E", text: "$12\\,\\text{N}$" }],
    answer: "E", solution: "$F=\\dfrac{mv^2}{r}=\\dfrac{1\\cdot6^2}{3}=12\\,$N." },
  { id: "pat-ex-018", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "A $3\\,\\text{kg}$ mass moves in a circle of radius $4\\,\\text{m}$ at $2\\,\\text{m/s}$. The centripetal force is:",
    options: [{ key: "A", text: "$12\\,\\text{N}$" },{ key: "B", text: "$3\\,\\text{N}$" },{ key: "C", text: "$\\frac{3}{2}\\,\\text{N}$" },{ key: "D", text: "$1\\,\\text{N}$" },{ key: "E", text: "$4\\,\\text{N}$" }],
    answer: "B", solution: "$F=\\dfrac{mv^2}{r}=\\dfrac{3\\cdot2^2}{4}=3\\,$N." },
  { id: "pat-ex-019", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "A $2\\,\\text{kg}$ mass moves in a circle of radius $5\\,\\text{m}$ at $10\\,\\text{m/s}$. The centripetal force is:",
    options: [{ key: "A", text: "$4\\,\\text{N}$" },{ key: "B", text: "$41\\,\\text{N}$" },{ key: "C", text: "$20\\,\\text{N}$" },{ key: "D", text: "$40\\,\\text{N}$" },{ key: "E", text: "$200\\,\\text{N}$" }],
    answer: "D", solution: "$F=\\dfrac{mv^2}{r}=\\dfrac{2\\cdot10^2}{5}=40\\,$N." },
  { id: "pat-ex-020", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "A $4\\,\\text{kg}$ mass moves in a circle of radius $6\\,\\text{m}$ at $3\\,\\text{m/s}$. The centripetal force is:",
    options: [{ key: "A", text: "$2\\,\\text{N}$" },{ key: "B", text: "$6\\,\\text{N}$" },{ key: "C", text: "$3\\,\\text{N}$" },{ key: "D", text: "$36\\,\\text{N}$" },{ key: "E", text: "$\\frac{3}{2}\\,\\text{N}$" }],
    answer: "B", solution: "$F=\\dfrac{mv^2}{r}=\\dfrac{4\\cdot3^2}{6}=6\\,$N." },
  { id: "pat-ex-021", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "Two resistors $12\\,\\Omega$ and $4\\,\\Omega$ are connected in parallel. The combined resistance is:",
    options: [{ key: "A", text: "$16\\,\\Omega$" },{ key: "B", text: "$3\\,\\Omega$" },{ key: "C", text: "$8\\,\\Omega$" },{ key: "D", text: "$24\\,\\Omega$" },{ key: "E", text: "$4\\,\\Omega$" }],
    answer: "B", solution: "$\\dfrac1{R}=\\dfrac1{12}+\\dfrac1{4}\\Rightarrow R=\\dfrac{12\\cdot4}{16}=3\\,\\Omega.$" },
  { id: "pat-ex-022", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "Two resistors $10\\,\\Omega$ and $10\\,\\Omega$ are connected in parallel. The combined resistance is:",
    options: [{ key: "A", text: "$6\\,\\Omega$" },{ key: "B", text: "$20\\,\\Omega$" },{ key: "C", text: "$10\\,\\Omega$" },{ key: "D", text: "$50\\,\\Omega$" },{ key: "E", text: "$5\\,\\Omega$" }],
    answer: "E", solution: "$\\dfrac1{R}=\\dfrac1{10}+\\dfrac1{10}\\Rightarrow R=\\dfrac{10\\cdot10}{20}=5\\,\\Omega.$" },
  { id: "pat-ex-023", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "Two resistors $8\\,\\Omega$ and $8\\,\\Omega$ are connected in parallel. The combined resistance is:",
    options: [{ key: "A", text: "$32\\,\\Omega$" },{ key: "B", text: "$16\\,\\Omega$" },{ key: "C", text: "$4\\,\\Omega$" },{ key: "D", text: "$8\\,\\Omega$" },{ key: "E", text: "$5\\,\\Omega$" }],
    answer: "C", solution: "$\\dfrac1{R}=\\dfrac1{8}+\\dfrac1{8}\\Rightarrow R=\\dfrac{8\\cdot8}{16}=4\\,\\Omega.$" },
  { id: "pat-ex-024", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "A $12\\,\\text{V}$ supply drives a $4\\,\\Omega$ resistor. The current is:",
    options: [{ key: "A", text: "$\\frac{1}{3}\\,\\text{A}$" },{ key: "B", text: "$48\\,\\text{A}$" },{ key: "C", text: "$8\\,\\text{A}$" },{ key: "D", text: "$3\\,\\text{A}$" },{ key: "E", text: "$\\frac{3}{2}\\,\\text{A}$" }],
    answer: "D", solution: "$I=\\dfrac{V}{R}=\\dfrac{12}{4}=3\\,$A." },
  { id: "pat-ex-025", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "A $9\\,\\text{V}$ supply drives a $3\\,\\Omega$ resistor. The current is:",
    options: [{ key: "A", text: "$27\\,\\text{A}$" },{ key: "B", text: "$\\frac{1}{3}\\,\\text{A}$" },{ key: "C", text: "$3\\,\\text{A}$" },{ key: "D", text: "$\\frac{3}{2}\\,\\text{A}$" },{ key: "E", text: "$6\\,\\text{A}$" }],
    answer: "C", solution: "$I=\\dfrac{V}{R}=\\dfrac{9}{3}=3\\,$A." },
  { id: "pat-ex-026", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "A $6\\,\\text{V}$ supply drives a $2\\,\\Omega$ resistor. The current is:",
    options: [{ key: "A", text: "$\\frac{3}{2}\\,\\text{A}$" },{ key: "B", text: "$3\\,\\text{A}$" },{ key: "C", text: "$12\\,\\text{A}$" },{ key: "D", text: "$4\\,\\text{A}$" },{ key: "E", text: "$\\frac{1}{3}\\,\\text{A}$" }],
    answer: "B", solution: "$I=\\dfrac{V}{R}=\\dfrac{6}{2}=3\\,$A." },
  { id: "pat-ex-027", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "A $24\\,\\text{V}$ supply drives a $6\\,\\Omega$ resistor. The current is:",
    options: [{ key: "A", text: "$4\\,\\text{A}$" },{ key: "B", text: "$\\frac{1}{4}\\,\\text{A}$" },{ key: "C", text: "$18\\,\\text{A}$" },{ key: "D", text: "$2\\,\\text{A}$" },{ key: "E", text: "$144\\,\\text{A}$" }],
    answer: "A", solution: "$I=\\dfrac{V}{R}=\\dfrac{24}{6}=4\\,$A." },
  { id: "pat-ex-028", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "A $10\\,\\text{V}$ supply drives a $5\\,\\Omega$ resistor. The current is:",
    options: [{ key: "A", text: "$5\\,\\text{A}$" },{ key: "B", text: "$1\\,\\text{A}$" },{ key: "C", text: "$2\\,\\text{A}$" },{ key: "D", text: "$50\\,\\text{A}$" },{ key: "E", text: "$\\frac{1}{2}\\,\\text{A}$" }],
    answer: "C", solution: "$I=\\dfrac{V}{R}=\\dfrac{10}{5}=2\\,$A." },
  { id: "pat-ex-029", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "A $20\\,\\text{V}$ supply drives a $4\\,\\Omega$ resistor. The current is:",
    options: [{ key: "A", text: "$16\\,\\text{A}$" },{ key: "B", text: "$80\\,\\text{A}$" },{ key: "C", text: "$\\frac{5}{2}\\,\\text{A}$" },{ key: "D", text: "$\\frac{1}{5}\\,\\text{A}$" },{ key: "E", text: "$5\\,\\text{A}$" }],
    answer: "E", solution: "$I=\\dfrac{V}{R}=\\dfrac{20}{4}=5\\,$A." },
  { id: "pat-ex-030", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "The power dissipated by a $6\\,\\Omega$ resistor across $12\\,\\text{V}$ is:",
    options: [{ key: "A", text: "$24\\,\\text{W}$" },{ key: "B", text: "$12\\,\\text{W}$" },{ key: "C", text: "$144\\,\\text{W}$" },{ key: "D", text: "$2\\,\\text{W}$" },{ key: "E", text: "$72\\,\\text{W}$" }],
    answer: "A", solution: "$P=\\dfrac{V^2}{R}=\\dfrac{12^2}{6}=24\\,$W." },
  { id: "pat-ex-031", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "The power dissipated by a $5\\,\\Omega$ resistor across $10\\,\\text{V}$ is:",
    options: [{ key: "A", text: "$100\\,\\text{W}$" },{ key: "B", text: "$10\\,\\text{W}$" },{ key: "C", text: "$50\\,\\text{W}$" },{ key: "D", text: "$20\\,\\text{W}$" },{ key: "E", text: "$2\\,\\text{W}$" }],
    answer: "D", solution: "$P=\\dfrac{V^2}{R}=\\dfrac{10^2}{5}=20\\,$W." },
  { id: "pat-ex-032", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "The power dissipated by a $3\\,\\Omega$ resistor across $6\\,\\text{V}$ is:",
    options: [{ key: "A", text: "$36\\,\\text{W}$" },{ key: "B", text: "$6\\,\\text{W}$" },{ key: "C", text: "$2\\,\\text{W}$" },{ key: "D", text: "$12\\,\\text{W}$" },{ key: "E", text: "$18\\,\\text{W}$" }],
    answer: "D", solution: "$P=\\dfrac{V^2}{R}=\\dfrac{6^2}{3}=12\\,$W." },
  { id: "pat-ex-033", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "The power dissipated by a $8\\,\\Omega$ resistor across $24\\,\\text{V}$ is:",
    options: [{ key: "A", text: "$3\\,\\text{W}$" },{ key: "B", text: "$576\\,\\text{W}$" },{ key: "C", text: "$192\\,\\text{W}$" },{ key: "D", text: "$72\\,\\text{W}$" },{ key: "E", text: "$36\\,\\text{W}$" }],
    answer: "D", solution: "$P=\\dfrac{V^2}{R}=\\dfrac{24^2}{8}=72\\,$W." },
  { id: "pat-ex-034", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "The power dissipated by a $10\\,\\Omega$ resistor across $20\\,\\text{V}$ is:",
    options: [{ key: "A", text: "$40\\,\\text{W}$" },{ key: "B", text: "$400\\,\\text{W}$" },{ key: "C", text: "$2\\,\\text{W}$" },{ key: "D", text: "$200\\,\\text{W}$" },{ key: "E", text: "$20\\,\\text{W}$" }],
    answer: "A", solution: "$P=\\dfrac{V^2}{R}=\\dfrac{20^2}{10}=40\\,$W." },
  { id: "pat-ex-035", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "A current of $2\\,\\text{A}$ flows for $5\\,\\text{s}$. The charge transferred is:",
    options: [{ key: "A", text: "$\\frac{5}{2}\\,\\text{C}$" },{ key: "B", text: "$7\\,\\text{C}$" },{ key: "C", text: "$5\\,\\text{C}$" },{ key: "D", text: "$10\\,\\text{C}$" },{ key: "E", text: "$20\\,\\text{C}$" }],
    answer: "D", solution: "$Q=It=2\\times5=10\\,$C." },
  { id: "pat-ex-036", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "A current of $3\\,\\text{A}$ flows for $4\\,\\text{s}$. The charge transferred is:",
    options: [{ key: "A", text: "$\\frac{4}{3}\\,\\text{C}$" },{ key: "B", text: "$7\\,\\text{C}$" },{ key: "C", text: "$12\\,\\text{C}$" },{ key: "D", text: "$6\\,\\text{C}$" },{ key: "E", text: "$24\\,\\text{C}$" }],
    answer: "C", solution: "$Q=It=3\\times4=12\\,$C." },
  { id: "pat-ex-037", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "A current of $\\frac{1}{2}\\,\\text{A}$ flows for $10\\,\\text{s}$. The charge transferred is:",
    options: [{ key: "A", text: "$\\frac{21}{2}\\,\\text{C}$" },{ key: "B", text: "$5\\,\\text{C}$" },{ key: "C", text: "$20\\,\\text{C}$" },{ key: "D", text: "$10\\,\\text{C}$" },{ key: "E", text: "$\\frac{5}{2}\\,\\text{C}$" }],
    answer: "B", solution: "$Q=It=\\frac{1}{2}\\times10=5\\,$C." },
  { id: "pat-ex-038", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "A current of $5\\,\\text{A}$ flows for $2\\,\\text{s}$. The charge transferred is:",
    options: [{ key: "A", text: "$10\\,\\text{C}$" },{ key: "B", text: "$\\frac{2}{5}\\,\\text{C}$" },{ key: "C", text: "$20\\,\\text{C}$" },{ key: "D", text: "$5\\,\\text{C}$" },{ key: "E", text: "$7\\,\\text{C}$" }],
    answer: "A", solution: "$Q=It=5\\times2=10\\,$C." },
  { id: "pat-ex-039", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "A current of $4\\,\\text{A}$ flows for $3\\,\\text{s}$. The charge transferred is:",
    options: [{ key: "A", text: "$12\\,\\text{C}$" },{ key: "B", text: "$24\\,\\text{C}$" },{ key: "C", text: "$6\\,\\text{C}$" },{ key: "D", text: "$\\frac{3}{4}\\,\\text{C}$" },{ key: "E", text: "$7\\,\\text{C}$" }],
    answer: "A", solution: "$Q=It=4\\times3=12\\,$C." },
  { id: "pat-ex-040", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "In a potential divider, $12\\,\\text{V}$ is across $2\\,\\Omega$ and $4\\,\\Omega$ in series. The voltage across $4\\,\\Omega$ is:",
    options: [{ key: "A", text: "$9\\,\\text{V}$" },{ key: "B", text: "$8\\,\\text{V}$" },{ key: "C", text: "$4\\,\\text{V}$" },{ key: "D", text: "$6\\,\\text{V}$" },{ key: "E", text: "$24\\,\\text{V}$" }],
    answer: "B", solution: "$V_2=V_{in}\\dfrac{R_2}{R_1+R_2}=12\\cdot\\dfrac{4}{6}=8\\,$V." },
  { id: "pat-ex-041", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "In a potential divider, $10\\,\\text{V}$ is across $1\\,\\Omega$ and $4\\,\\Omega$ in series. The voltage across $4\\,\\Omega$ is:",
    options: [{ key: "A", text: "$2\\,\\text{V}$" },{ key: "B", text: "$6\\,\\text{V}$" },{ key: "C", text: "$40\\,\\text{V}$" },{ key: "D", text: "$5\\,\\text{V}$" },{ key: "E", text: "$8\\,\\text{V}$" }],
    answer: "E", solution: "$V_2=V_{in}\\dfrac{R_2}{R_1+R_2}=10\\cdot\\dfrac{4}{5}=8\\,$V." },
  { id: "pat-ex-042", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "In a potential divider, $9\\,\\text{V}$ is across $3\\,\\Omega$ and $6\\,\\Omega$ in series. The voltage across $6\\,\\Omega$ is:",
    options: [{ key: "A", text: "$3\\,\\text{V}$" },{ key: "B", text: "$6\\,\\text{V}$" },{ key: "C", text: "$\\frac{9}{2}\\,\\text{V}$" },{ key: "D", text: "$18\\,\\text{V}$" },{ key: "E", text: "$7\\,\\text{V}$" }],
    answer: "B", solution: "$V_2=V_{in}\\dfrac{R_2}{R_1+R_2}=9\\cdot\\dfrac{6}{9}=6\\,$V." },
  { id: "pat-ex-043", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "In a potential divider, $20\\,\\text{V}$ is across $5\\,\\Omega$ and $15\\,\\Omega$ in series. The voltage across $15\\,\\Omega$ is:",
    options: [{ key: "A", text: "$10\\,\\text{V}$" },{ key: "B", text: "$16\\,\\text{V}$" },{ key: "C", text: "$5\\,\\text{V}$" },{ key: "D", text: "$60\\,\\text{V}$" },{ key: "E", text: "$15\\,\\text{V}$" }],
    answer: "E", solution: "$V_2=V_{in}\\dfrac{R_2}{R_1+R_2}=20\\cdot\\dfrac{15}{20}=15\\,$V." },
  { id: "pat-ex-044", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 1, marks: 4,
    question: "A wave has frequency $50\\,\\text{Hz}$ and wavelength $4\\,\\text{m}$. Its speed is:",
    options: [{ key: "A", text: "$54\\,\\text{m/s}$" },{ key: "B", text: "$400\\,\\text{m/s}$" },{ key: "C", text: "$200\\,\\text{m/s}$" },{ key: "D", text: "$\\frac{2}{25}\\,\\text{m/s}$" },{ key: "E", text: "$\\frac{25}{2}\\,\\text{m/s}$" }],
    answer: "C", solution: "$v=f\\lambda=50\\times4=200\\,$m/s." },
  { id: "pat-ex-045", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 1, marks: 4,
    question: "A wave has frequency $100\\,\\text{Hz}$ and wavelength $3\\,\\text{m}$. Its speed is:",
    options: [{ key: "A", text: "$300\\,\\text{m/s}$" },{ key: "B", text: "$\\frac{100}{3}\\,\\text{m/s}$" },{ key: "C", text: "$103\\,\\text{m/s}$" },{ key: "D", text: "$600\\,\\text{m/s}$" },{ key: "E", text: "$\\frac{3}{100}\\,\\text{m/s}$" }],
    answer: "A", solution: "$v=f\\lambda=100\\times3=300\\,$m/s." },
  { id: "pat-ex-046", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 1, marks: 4,
    question: "A wave has frequency $25\\,\\text{Hz}$ and wavelength $8\\,\\text{m}$. Its speed is:",
    options: [{ key: "A", text: "$400\\,\\text{m/s}$" },{ key: "B", text: "$\\frac{8}{25}\\,\\text{m/s}$" },{ key: "C", text: "$33\\,\\text{m/s}$" },{ key: "D", text: "$200\\,\\text{m/s}$" },{ key: "E", text: "$\\frac{25}{8}\\,\\text{m/s}$" }],
    answer: "D", solution: "$v=f\\lambda=25\\times8=200\\,$m/s." },
  { id: "pat-ex-047", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 1, marks: 4,
    question: "A wave has frequency $200\\,\\text{Hz}$ and wavelength $2\\,\\text{m}$. Its speed is:",
    options: [{ key: "A", text: "$202\\,\\text{m/s}$" },{ key: "B", text: "$800\\,\\text{m/s}$" },{ key: "C", text: "$400\\,\\text{m/s}$" },{ key: "D", text: "$100\\,\\text{m/s}$" },{ key: "E", text: "$\\frac{1}{100}\\,\\text{m/s}$" }],
    answer: "C", solution: "$v=f\\lambda=200\\times2=400\\,$m/s." },
  { id: "pat-ex-048", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 1, marks: 4,
    question: "A wave has frequency $10\\,\\text{Hz}$ and wavelength $34\\,\\text{m}$. Its speed is:",
    options: [{ key: "A", text: "$44\\,\\text{m/s}$" },{ key: "B", text: "$\\frac{17}{5}\\,\\text{m/s}$" },{ key: "C", text: "$340\\,\\text{m/s}$" },{ key: "D", text: "$\\frac{5}{17}\\,\\text{m/s}$" },{ key: "E", text: "$680\\,\\text{m/s}$" }],
    answer: "C", solution: "$v=f\\lambda=10\\times34=340\\,$m/s." },
  { id: "pat-ex-049", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 1, marks: 4,
    question: "A wave has frequency $500\\,\\text{Hz}$ and wavelength $1\\,\\text{m}$. Its speed is:",
    options: [{ key: "A", text: "$\\frac{1}{500}\\,\\text{m/s}$" },{ key: "B", text: "$1000\\,\\text{m/s}$" },{ key: "C", text: "$501\\,\\text{m/s}$" },{ key: "D", text: "$510\\,\\text{m/s}$" },{ key: "E", text: "$500\\,\\text{m/s}$" }],
    answer: "E", solution: "$v=f\\lambda=500\\times1=500\\,$m/s." },
  { id: "pat-ex-050", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "An object is $15\\,\\text{cm}$ from a converging lens of focal length $10\\,\\text{cm}$. The image distance is:",
    options: [{ key: "A", text: "$30\\,\\text{cm}$" },{ key: "B", text: "$\\frac{15}{2}\\,\\text{cm}$" },{ key: "C", text: "$25\\,\\text{cm}$" },{ key: "D", text: "$6\\,\\text{cm}$" },{ key: "E", text: "$5\\,\\text{cm}$" }],
    answer: "A", solution: "$\\dfrac1f=\\dfrac1u+\\dfrac1v\\Rightarrow v=\\dfrac{fu}{u-f}=\\dfrac{10\\cdot15}{5}=30\\,$cm." },
  { id: "pat-ex-051", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "An object is $30\\,\\text{cm}$ from a converging lens of focal length $20\\,\\text{cm}$. The image distance is:",
    options: [{ key: "A", text: "$10\\,\\text{cm}$" },{ key: "B", text: "$12\\,\\text{cm}$" },{ key: "C", text: "$50\\,\\text{cm}$" },{ key: "D", text: "$15\\,\\text{cm}$" },{ key: "E", text: "$60\\,\\text{cm}$" }],
    answer: "E", solution: "$\\dfrac1f=\\dfrac1u+\\dfrac1v\\Rightarrow v=\\dfrac{fu}{u-f}=\\dfrac{20\\cdot30}{10}=60\\,$cm." },
  { id: "pat-ex-052", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "An object is $20\\,\\text{cm}$ from a converging lens of focal length $10\\,\\text{cm}$. The image distance is:",
    options: [{ key: "A", text: "$22\\,\\text{cm}$" },{ key: "B", text: "$10\\,\\text{cm}$" },{ key: "C", text: "$30\\,\\text{cm}$" },{ key: "D", text: "$20\\,\\text{cm}$" },{ key: "E", text: "$\\frac{20}{3}\\,\\text{cm}$" }],
    answer: "D", solution: "$\\dfrac1f=\\dfrac1u+\\dfrac1v\\Rightarrow v=\\dfrac{fu}{u-f}=\\dfrac{10\\cdot20}{10}=20\\,$cm." },
  { id: "pat-ex-053", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "An object is $24\\,\\text{cm}$ from a converging lens of focal length $12\\,\\text{cm}$. The image distance is:",
    options: [{ key: "A", text: "$26\\,\\text{cm}$" },{ key: "B", text: "$8\\,\\text{cm}$" },{ key: "C", text: "$24\\,\\text{cm}$" },{ key: "D", text: "$12\\,\\text{cm}$" },{ key: "E", text: "$36\\,\\text{cm}$" }],
    answer: "C", solution: "$\\dfrac1f=\\dfrac1u+\\dfrac1v\\Rightarrow v=\\dfrac{fu}{u-f}=\\dfrac{12\\cdot24}{12}=24\\,$cm." },
  { id: "pat-ex-054", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "An object is $30\\,\\text{cm}$ from a converging lens of focal length $15\\,\\text{cm}$. The image distance is:",
    options: [{ key: "A", text: "$15\\,\\text{cm}$" },{ key: "B", text: "$45\\,\\text{cm}$" },{ key: "C", text: "$10\\,\\text{cm}$" },{ key: "D", text: "$30\\,\\text{cm}$" },{ key: "E", text: "$32\\,\\text{cm}$" }],
    answer: "D", solution: "$\\dfrac1f=\\dfrac1u+\\dfrac1v\\Rightarrow v=\\dfrac{fu}{u-f}=\\dfrac{15\\cdot30}{15}=30\\,$cm." },
  { id: "pat-ex-055", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "An object is $60\\,\\text{cm}$ from a converging lens of focal length $20\\,\\text{cm}$. The image distance is:",
    options: [{ key: "A", text: "$30\\,\\text{cm}$" },{ key: "B", text: "$32\\,\\text{cm}$" },{ key: "C", text: "$40\\,\\text{cm}$" },{ key: "D", text: "$80\\,\\text{cm}$" },{ key: "E", text: "$15\\,\\text{cm}$" }],
    answer: "A", solution: "$\\dfrac1f=\\dfrac1u+\\dfrac1v\\Rightarrow v=\\dfrac{fu}{u-f}=\\dfrac{20\\cdot60}{40}=30\\,$cm." },
  { id: "pat-ex-056", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "Light travels inside a medium of refractive index $\\frac{3}{2}$ towards air. The sine of the critical angle is:",
    options: [{ key: "A", text: "$\\frac{3}{4}$" },{ key: "B", text: "$\\frac{1}{3}$" },{ key: "C", text: "$\\frac{2}{3}$" },{ key: "D", text: "$\\frac{23}{30}$" },{ key: "E", text: "$\\frac{3}{2}$" }],
    answer: "C", solution: "At the critical angle $\\sin\\theta_c=\\dfrac{1}{n}=\\dfrac{1}{\\frac{3}{2}}=\\frac{2}{3}.$" },
  { id: "pat-ex-057", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "Light travels inside a medium of refractive index $\\frac{4}{3}$ towards air. The sine of the critical angle is:",
    options: [{ key: "A", text: "$\\frac{3}{8}$" },{ key: "B", text: "$\\frac{1}{4}$" },{ key: "C", text: "$\\frac{4}{3}$" },{ key: "D", text: "$\\frac{3}{4}$" },{ key: "E", text: "$\\frac{2}{3}$" }],
    answer: "D", solution: "At the critical angle $\\sin\\theta_c=\\dfrac{1}{n}=\\dfrac{1}{\\frac{4}{3}}=\\frac{3}{4}.$" },
  { id: "pat-ex-058", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "Light travels inside a medium of refractive index $2$ towards air. The sine of the critical angle is:",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$\\frac{3}{5}$" },{ key: "C", text: "$\\frac{1}{2}$" },{ key: "D", text: "$1$" },{ key: "E", text: "$\\frac{1}{4}$" }],
    answer: "C", solution: "At the critical angle $\\sin\\theta_c=\\dfrac{1}{n}=\\dfrac{1}{2}=\\frac{1}{2}.$" },
  { id: "pat-ex-059", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "Light travels inside a medium of refractive index $\\frac{5}{3}$ towards air. The sine of the critical angle is:",
    options: [{ key: "A", text: "$\\frac{3}{10}$" },{ key: "B", text: "$\\frac{2}{5}$" },{ key: "C", text: "$\\frac{5}{6}$" },{ key: "D", text: "$\\frac{3}{5}$" },{ key: "E", text: "$\\frac{5}{3}$" }],
    answer: "D", solution: "At the critical angle $\\sin\\theta_c=\\dfrac{1}{n}=\\dfrac{1}{\\frac{5}{3}}=\\frac{3}{5}.$" },
  { id: "pat-ex-060", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "Light travels inside a medium of refractive index $\\frac{5}{4}$ towards air. The sine of the critical angle is:",
    options: [{ key: "A", text: "$\\frac{2}{5}$" },{ key: "B", text: "$\\frac{4}{5}$" },{ key: "C", text: "$\\frac{1}{5}$" },{ key: "D", text: "$\\frac{5}{8}$" },{ key: "E", text: "$\\frac{5}{4}$" }],
    answer: "B", solution: "At the critical angle $\\sin\\theta_c=\\dfrac{1}{n}=\\dfrac{1}{\\frac{5}{4}}=\\frac{4}{5}.$" },
  { id: "pat-ex-061", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "In a double-slit experiment (consistent units), $\\lambda=6$, slit–screen distance $D=2$, slit separation $d=3$. The fringe spacing is:",
    options: [{ key: "A", text: "$\\frac{1}{4}$" },{ key: "B", text: "$36$" },{ key: "C", text: "$4$" },{ key: "D", text: "$\\frac{2}{3}$" },{ key: "E", text: "$2$" }],
    answer: "C", solution: "$w=\\dfrac{\\lambda D}{d}=\\dfrac{6\\cdot2}{3}=4$ (same units)." },
  { id: "pat-ex-062", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "In a double-slit experiment (consistent units), $\\lambda=5$, slit–screen distance $D=4$, slit separation $d=2$. The fringe spacing is:",
    options: [{ key: "A", text: "$\\frac{1}{10}$" },{ key: "B", text: "$2$" },{ key: "C", text: "$\\frac{5}{2}$" },{ key: "D", text: "$40$" },{ key: "E", text: "$10$" }],
    answer: "E", solution: "$w=\\dfrac{\\lambda D}{d}=\\dfrac{5\\cdot4}{2}=10$ (same units)." },
  { id: "pat-ex-063", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "In a double-slit experiment (consistent units), $\\lambda=4$, slit–screen distance $D=3$, slit separation $d=6$. The fringe spacing is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$72$" },{ key: "C", text: "$2$" },{ key: "D", text: "$\\frac{1}{2}$" },{ key: "E", text: "$\\frac{2}{3}$" }],
    answer: "C", solution: "$w=\\dfrac{\\lambda D}{d}=\\dfrac{4\\cdot3}{6}=2$ (same units)." },
  { id: "pat-ex-064", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "In a double-slit experiment (consistent units), $\\lambda=6$, slit–screen distance $D=3$, slit separation $d=2$. The fringe spacing is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$\\frac{1}{9}$" },{ key: "C", text: "$9$" },{ key: "D", text: "$36$" },{ key: "E", text: "$\\frac{3}{2}$" }],
    answer: "C", solution: "$w=\\dfrac{\\lambda D}{d}=\\dfrac{6\\cdot3}{2}=9$ (same units)." },
  { id: "pat-ex-065", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "In a double-slit experiment (consistent units), $\\lambda=5$, slit–screen distance $D=2$, slit separation $d=5$. The fringe spacing is:",
    options: [{ key: "A", text: "$\\frac{2}{5}$" },{ key: "B", text: "$1$" },{ key: "C", text: "$\\frac{1}{2}$" },{ key: "D", text: "$50$" },{ key: "E", text: "$2$" }],
    answer: "E", solution: "$w=\\dfrac{\\lambda D}{d}=\\dfrac{5\\cdot2}{5}=2$ (same units)." },
  { id: "pat-ex-066", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "A fixed mass of gas at constant temperature has $P_1=2$, $V_1=6$. When pressure becomes $P_2=3$, the new volume is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$9$" },{ key: "C", text: "$4$" },{ key: "D", text: "$5$" },{ key: "E", text: "$36$" }],
    answer: "C", solution: "Boyle's law $P_1V_1=P_2V_2\\Rightarrow V_2=\\dfrac{2\\cdot6}{3}=4.$" },
  { id: "pat-ex-067", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "A fixed mass of gas at constant temperature has $P_1=4$, $V_1=3$. When pressure becomes $P_2=2$, the new volume is:",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$6$" },{ key: "C", text: "$5$" },{ key: "D", text: "$\\frac{3}{2}$" },{ key: "E", text: "$24$" }],
    answer: "B", solution: "Boyle's law $P_1V_1=P_2V_2\\Rightarrow V_2=\\dfrac{4\\cdot3}{2}=6.$" },
  { id: "pat-ex-068", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "A fixed mass of gas at constant temperature has $P_1=1$, $V_1=10$. When pressure becomes $P_2=5$, the new volume is:",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$5$" },{ key: "C", text: "$6$" },{ key: "D", text: "$50$" },{ key: "E", text: "$3$" }],
    answer: "A", solution: "Boyle's law $P_1V_1=P_2V_2\\Rightarrow V_2=\\dfrac{1\\cdot10}{5}=2.$" },
  { id: "pat-ex-069", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "A fixed mass of gas at constant temperature has $P_1=3$, $V_1=4$. When pressure becomes $P_2=6$, the new volume is:",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$2$" },{ key: "C", text: "$8$" },{ key: "D", text: "$72$" },{ key: "E", text: "$3$" }],
    answer: "B", solution: "Boyle's law $P_1V_1=P_2V_2\\Rightarrow V_2=\\dfrac{3\\cdot4}{6}=2.$" },
  { id: "pat-ex-070", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "A fixed mass of gas at constant temperature has $P_1=5$, $V_1=2$. When pressure becomes $P_2=1$, the new volume is:",
    options: [{ key: "A", text: "$\\frac{2}{5}$" },{ key: "B", text: "$6$" },{ key: "C", text: "$10$" },{ key: "D", text: "$11$" },{ key: "E", text: "$1$" }],
    answer: "C", solution: "Boyle's law $P_1V_1=P_2V_2\\Rightarrow V_2=\\dfrac{5\\cdot2}{1}=10.$" },
  { id: "pat-ex-071", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 2, marks: 4,
    question: "At constant volume, a gas has $P_1=2$ at $T_1=300\\,\\text{K}$. When pressure rises to $P_2=3$, the temperature is:",
    options: [{ key: "A", text: "$200\\,\\text{K}$" },{ key: "B", text: "$900\\,\\text{K}$" },{ key: "C", text: "$450\\,\\text{K}$" },{ key: "D", text: "$150\\,\\text{K}$" },{ key: "E", text: "$301\\,\\text{K}$" }],
    answer: "C", solution: "$\\dfrac{P_1}{T_1}=\\dfrac{P_2}{T_2}\\Rightarrow T_2=\\dfrac{3\\cdot300}{2}=450\\,$K." },
  { id: "pat-ex-072", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 2, marks: 4,
    question: "At constant volume, a gas has $P_1=4$ at $T_1=400\\,\\text{K}$. When pressure rises to $P_2=5$, the temperature is:",
    options: [{ key: "A", text: "$500\\,\\text{K}$" },{ key: "B", text: "$320\\,\\text{K}$" },{ key: "C", text: "$2000\\,\\text{K}$" },{ key: "D", text: "$200\\,\\text{K}$" },{ key: "E", text: "$401\\,\\text{K}$" }],
    answer: "A", solution: "$\\dfrac{P_1}{T_1}=\\dfrac{P_2}{T_2}\\Rightarrow T_2=\\dfrac{5\\cdot400}{4}=500\\,$K." },
  { id: "pat-ex-073", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 2, marks: 4,
    question: "At constant volume, a gas has $P_1=3$ at $T_1=600\\,\\text{K}$. When pressure rises to $P_2=4$, the temperature is:",
    options: [{ key: "A", text: "$450\\,\\text{K}$" },{ key: "B", text: "$300\\,\\text{K}$" },{ key: "C", text: "$2400\\,\\text{K}$" },{ key: "D", text: "$800\\,\\text{K}$" },{ key: "E", text: "$601\\,\\text{K}$" }],
    answer: "D", solution: "$\\dfrac{P_1}{T_1}=\\dfrac{P_2}{T_2}\\Rightarrow T_2=\\dfrac{4\\cdot600}{3}=800\\,$K." },
  { id: "pat-ex-074", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 2, marks: 4,
    question: "At constant volume, a gas has $P_1=2$ at $T_1=250\\,\\text{K}$. When pressure rises to $P_2=4$, the temperature is:",
    options: [{ key: "A", text: "$500\\,\\text{K}$" },{ key: "B", text: "$125\\,\\text{K}$" },{ key: "C", text: "$510\\,\\text{K}$" },{ key: "D", text: "$252\\,\\text{K}$" },{ key: "E", text: "$1000\\,\\text{K}$" }],
    answer: "A", solution: "$\\dfrac{P_1}{T_1}=\\dfrac{P_2}{T_2}\\Rightarrow T_2=\\dfrac{4\\cdot250}{2}=500\\,$K." },
  { id: "pat-ex-075", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "Heating $2\\,\\text{kg}$ of a substance ($c=4\\,\\text{J/kg·K}$) by $5\\,\\text{K}$ requires energy:",
    options: [{ key: "A", text: "$80\\,\\text{J}$" },{ key: "B", text: "$13\\,\\text{J}$" },{ key: "C", text: "$\\frac{8}{5}\\,\\text{J}$" },{ key: "D", text: "$20\\,\\text{J}$" },{ key: "E", text: "$40\\,\\text{J}$" }],
    answer: "E", solution: "$Q=mc\\Delta T=2\\cdot4\\cdot5=40\\,$J." },
  { id: "pat-ex-076", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "Heating $1\\,\\text{kg}$ of a substance ($c=900\\,\\text{J/kg·K}$) by $10\\,\\text{K}$ requires energy:",
    options: [{ key: "A", text: "$9000\\,\\text{J}$" },{ key: "B", text: "$910\\,\\text{J}$" },{ key: "C", text: "$18000\\,\\text{J}$" },{ key: "D", text: "$4500\\,\\text{J}$" },{ key: "E", text: "$90\\,\\text{J}$" }],
    answer: "A", solution: "$Q=mc\\Delta T=1\\cdot900\\cdot10=9000\\,$J." },
  { id: "pat-ex-077", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "Heating $3\\,\\text{kg}$ of a substance ($c=500\\,\\text{J/kg·K}$) by $4\\,\\text{K}$ requires energy:",
    options: [{ key: "A", text: "$3000\\,\\text{J}$" },{ key: "B", text: "$12000\\,\\text{J}$" },{ key: "C", text: "$6000\\,\\text{J}$" },{ key: "D", text: "$375\\,\\text{J}$" },{ key: "E", text: "$1504\\,\\text{J}$" }],
    answer: "C", solution: "$Q=mc\\Delta T=3\\cdot500\\cdot4=6000\\,$J." },
  { id: "pat-ex-078", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "Heating $2\\,\\text{kg}$ of a substance ($c=2000\\,\\text{J/kg·K}$) by $3\\,\\text{K}$ requires energy:",
    options: [{ key: "A", text: "$24000\\,\\text{J}$" },{ key: "B", text: "$6000\\,\\text{J}$" },{ key: "C", text: "$12000\\,\\text{J}$" },{ key: "D", text: "$4003\\,\\text{J}$" },{ key: "E", text: "$\\frac{4000}{3}\\,\\text{J}$" }],
    answer: "C", solution: "$Q=mc\\Delta T=2\\cdot2000\\cdot3=12000\\,$J." },
  { id: "pat-ex-079", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "Heating $5\\,\\text{kg}$ of a substance ($c=400\\,\\text{J/kg·K}$) by $2\\,\\text{K}$ requires energy:",
    options: [{ key: "A", text: "$8000\\,\\text{J}$" },{ key: "B", text: "$1000\\,\\text{J}$" },{ key: "C", text: "$4000\\,\\text{J}$" },{ key: "D", text: "$2002\\,\\text{J}$" },{ key: "E", text: "$2000\\,\\text{J}$" }],
    answer: "C", solution: "$Q=mc\\Delta T=5\\cdot400\\cdot2=4000\\,$J." },
  { id: "pat-ex-080", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "A photon has frequency $5\\times10^{14}\\,\\text{Hz}$. Using $h=6.6\\times10^{-34}\\,\\text{J·s}$, its energy (in $10^{-20}\\,\\text{J}$) is:",
    options: [{ key: "A", text: "$330$" },{ key: "B", text: "$33$" },{ key: "C", text: "$66$" },{ key: "D", text: "$\\frac{66}{5}$" },{ key: "E", text: "$\\frac{250}{33}$" }],
    answer: "B", solution: "$E=hf=6.6\\times10^{-34}\\times5\\times10^{14}=33\\times10^{-20}\\,$J." },
  { id: "pat-ex-081", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "A photon has frequency $4\\times10^{14}\\,\\text{Hz}$. Using $h=6.6\\times10^{-34}\\,\\text{J·s}$, its energy (in $10^{-20}\\,\\text{J}$) is:",
    options: [{ key: "A", text: "$\\frac{132}{5}$" },{ key: "B", text: "$\\frac{200}{33}$" },{ key: "C", text: "$\\frac{33}{2}$" },{ key: "D", text: "$\\frac{264}{5}$" },{ key: "E", text: "$264$" }],
    answer: "A", solution: "$E=hf=6.6\\times10^{-34}\\times4\\times10^{14}=\\frac{132}{5}\\times10^{-20}\\,$J." },
  { id: "pat-ex-082", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "A photon has frequency $6\\times10^{14}\\,\\text{Hz}$. Using $h=6.6\\times10^{-34}\\,\\text{J·s}$, its energy (in $10^{-20}\\,\\text{J}$) is:",
    options: [{ key: "A", text: "$\\frac{198}{5}$" },{ key: "B", text: "$396$" },{ key: "C", text: "$\\frac{100}{11}$" },{ key: "D", text: "$\\frac{396}{5}$" },{ key: "E", text: "$11$" }],
    answer: "A", solution: "$E=hf=6.6\\times10^{-34}\\times6\\times10^{14}=\\frac{198}{5}\\times10^{-20}\\,$J." },
  { id: "pat-ex-083", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "A photon has frequency $3\\times10^{14}\\,\\text{Hz}$. Using $h=6.6\\times10^{-34}\\,\\text{J·s}$, its energy (in $10^{-20}\\,\\text{J}$) is:",
    options: [{ key: "A", text: "$198$" },{ key: "B", text: "$\\frac{99}{5}$" },{ key: "C", text: "$22$" },{ key: "D", text: "$\\frac{198}{5}$" },{ key: "E", text: "$\\frac{50}{11}$" }],
    answer: "B", solution: "$E=hf=6.6\\times10^{-34}\\times3\\times10^{14}=\\frac{99}{5}\\times10^{-20}\\,$J." },
  { id: "pat-ex-084", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "A photon has frequency $8\\times10^{14}\\,\\text{Hz}$. Using $h=6.6\\times10^{-34}\\,\\text{J·s}$, its energy (in $10^{-20}\\,\\text{J}$) is:",
    options: [{ key: "A", text: "$528$" },{ key: "B", text: "$\\frac{400}{33}$" },{ key: "C", text: "$\\frac{33}{4}$" },{ key: "D", text: "$\\frac{264}{5}$" },{ key: "E", text: "$\\frac{528}{5}$" }],
    answer: "D", solution: "$E=hf=6.6\\times10^{-34}\\times8\\times10^{14}=\\frac{264}{5}\\times10^{-20}\\,$J." },
  { id: "pat-ex-085", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 1, marks: 4,
    question: "After $3$ half-lives, the fraction of a radioactive sample remaining is:",
    options: [{ key: "A", text: "$\\frac{1}{8}$" },{ key: "B", text: "$\\frac{7}{8}$" },{ key: "C", text: "$\\frac{1}{6}$" },{ key: "D", text: "$\\frac{3}{8}$" },{ key: "E", text: "$\\frac{1}{4}$" }],
    answer: "A", solution: "Remaining fraction $=\\left(\\tfrac12\\right)^{3}=\\frac{1}{8}.$" },
  { id: "pat-ex-086", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 1, marks: 4,
    question: "After $4$ half-lives, the fraction of a radioactive sample remaining is:",
    options: [{ key: "A", text: "$\\frac{1}{4}$" },{ key: "B", text: "$\\frac{1}{16}$" },{ key: "C", text: "$\\frac{1}{5}$" },{ key: "D", text: "$\\frac{1}{8}$" },{ key: "E", text: "$\\frac{15}{16}$" }],
    answer: "B", solution: "Remaining fraction $=\\left(\\tfrac12\\right)^{4}=\\frac{1}{16}.$" },
  { id: "pat-ex-087", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 1, marks: 4,
    question: "After $5$ half-lives, the fraction of a radioactive sample remaining is:",
    options: [{ key: "A", text: "$\\frac{31}{32}$" },{ key: "B", text: "$\\frac{1}{10}$" },{ key: "C", text: "$\\frac{5}{32}$" },{ key: "D", text: "$\\frac{1}{6}$" },{ key: "E", text: "$\\frac{1}{32}$" }],
    answer: "E", solution: "Remaining fraction $=\\left(\\tfrac12\\right)^{5}=\\frac{1}{32}.$" },
  { id: "pat-ex-088", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 3, marks: 4,
    question: "A particle has momentum $2\\times10^{-24}\\,\\text{kg·m/s}$. With $h=6.6\\times10^{-34}$, its de Broglie wavelength (in $10^{-10}\\,\\text{m}$) is:",
    options: [{ key: "A", text: "$\\frac{10}{33}$" },{ key: "B", text: "$\\frac{33}{5}$" },{ key: "C", text: "$\\frac{1}{33}$" },{ key: "D", text: "$\\frac{33}{10}$" },{ key: "E", text: "$132$" }],
    answer: "D", solution: "$\\lambda=\\dfrac{h}{p}=\\dfrac{6.6\\times10^{-34}}{2\\times10^{-24}}=\\frac{33}{10}\\times10^{-10}\\,$m." },
  { id: "pat-ex-089", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 3, marks: 4,
    question: "A particle has momentum $3\\times10^{-24}\\,\\text{kg·m/s}$. With $h=6.6\\times10^{-34}$, its de Broglie wavelength (in $10^{-10}\\,\\text{m}$) is:",
    options: [{ key: "A", text: "$198$" },{ key: "B", text: "$\\frac{1}{22}$" },{ key: "C", text: "$\\frac{11}{5}$" },{ key: "D", text: "$\\frac{22}{5}$" },{ key: "E", text: "$\\frac{5}{11}$" }],
    answer: "C", solution: "$\\lambda=\\dfrac{h}{p}=\\dfrac{6.6\\times10^{-34}}{3\\times10^{-24}}=\\frac{11}{5}\\times10^{-10}\\,$m." },
  { id: "pat-ex-090", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 3, marks: 4,
    question: "A particle has momentum $4\\times10^{-24}\\,\\text{kg·m/s}$. With $h=6.6\\times10^{-34}$, its de Broglie wavelength (in $10^{-10}\\,\\text{m}$) is:",
    options: [{ key: "A", text: "$264$" },{ key: "B", text: "$\\frac{33}{10}$" },{ key: "C", text: "$\\frac{2}{33}$" },{ key: "D", text: "$\\frac{33}{20}$" },{ key: "E", text: "$\\frac{20}{33}$" }],
    answer: "D", solution: "$\\lambda=\\dfrac{h}{p}=\\dfrac{6.6\\times10^{-34}}{4\\times10^{-24}}=\\frac{33}{20}\\times10^{-10}\\,$m." },
  { id: "pat-ex-091", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 3, marks: 4,
    question: "A particle has momentum $6\\times10^{-24}\\,\\text{kg·m/s}$. With $h=6.6\\times10^{-34}$, its de Broglie wavelength (in $10^{-10}\\,\\text{m}$) is:",
    options: [{ key: "A", text: "$\\frac{10}{11}$" },{ key: "B", text: "$\\frac{1}{11}$" },{ key: "C", text: "$\\frac{11}{10}$" },{ key: "D", text: "$396$" },{ key: "E", text: "$\\frac{11}{5}$" }],
    answer: "C", solution: "$\\lambda=\\dfrac{h}{p}=\\dfrac{6.6\\times10^{-34}}{6\\times10^{-24}}=\\frac{11}{10}\\times10^{-10}\\,$m." },
  { id: "pat-ex-092", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 3, marks: 4,
    question: "A particle has momentum $5\\times10^{-24}\\,\\text{kg·m/s}$. With $h=6.6\\times10^{-34}$, its de Broglie wavelength (in $10^{-10}\\,\\text{m}$) is:",
    options: [{ key: "A", text: "$\\frac{66}{25}$" },{ key: "B", text: "$\\frac{5}{66}$" },{ key: "C", text: "$\\frac{33}{25}$" },{ key: "D", text: "$\\frac{25}{33}$" },{ key: "E", text: "$330$" }],
    answer: "C", solution: "$\\lambda=\\dfrac{h}{p}=\\dfrac{6.6\\times10^{-34}}{5\\times10^{-24}}=\\frac{33}{25}\\times10^{-10}\\,$m." },
  { id: "pat-ex-093", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 1, marks: 4,
    question: "The magnitude of the vector $(3\\,\\mathbf{i}+4\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$5$" },{ key: "C", text: "$\\frac{7}{2}$" },{ key: "D", text: "$7$" },{ key: "E", text: "$6$" }],
    answer: "B", solution: "$|\\mathbf{v}|=\\sqrt{3^2+4^2}=5.$" },
  { id: "pat-ex-094", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 1, marks: 4,
    question: "The magnitude of the vector $(6\\,\\mathbf{i}+8\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$10$" },{ key: "C", text: "$14$" },{ key: "D", text: "$7$" },{ key: "E", text: "$11$" }],
    answer: "B", solution: "$|\\mathbf{v}|=\\sqrt{6^2+8^2}=10.$" },
  { id: "pat-ex-095", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 1, marks: 4,
    question: "The magnitude of the vector $(5\\,\\mathbf{i}+12\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$14$" },{ key: "B", text: "$17$" },{ key: "C", text: "$13$" },{ key: "D", text: "$7$" },{ key: "E", text: "$\\frac{17}{2}$" }],
    answer: "C", solution: "$|\\mathbf{v}|=\\sqrt{5^2+12^2}=13.$" },
  { id: "pat-ex-096", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 1, marks: 4,
    question: "The magnitude of the vector $(8\\,\\mathbf{i}+15\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$23$" },{ key: "B", text: "$7$" },{ key: "C", text: "$18$" },{ key: "D", text: "$\\frac{23}{2}$" },{ key: "E", text: "$17$" }],
    answer: "E", solution: "$|\\mathbf{v}|=\\sqrt{8^2+15^2}=17.$" },
  { id: "pat-ex-097", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 1, marks: 4,
    question: "The magnitude of the vector $(9\\,\\mathbf{i}+12\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$21$" },{ key: "B", text: "$\\frac{21}{2}$" },{ key: "C", text: "$16$" },{ key: "D", text: "$3$" },{ key: "E", text: "$15$" }],
    answer: "E", solution: "$|\\mathbf{v}|=\\sqrt{9^2+12^2}=15.$" },
  { id: "pat-ex-098", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 1, marks: 4,
    question: "The magnitude of the vector $(7\\,\\mathbf{i}+24\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$31$" },{ key: "B", text: "$25$" },{ key: "C", text: "$17$" },{ key: "D", text: "$26$" },{ key: "E", text: "$\\frac{31}{2}$" }],
    answer: "B", solution: "$|\\mathbf{v}|=\\sqrt{7^2+24^2}=25.$" },
  { id: "pat-ex-099", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 1, marks: 4,
    question: "The scalar (dot) product $(2\\,\\mathbf{i}+3\\,\\mathbf{j})\\cdot(4\\,\\mathbf{i}+1\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$11$" },{ key: "C", text: "$13$" },{ key: "D", text: "$10$" },{ key: "E", text: "$14$" }],
    answer: "B", solution: "$\\mathbf{a}\\cdot\\mathbf{b}=2\\cdot4+3\\cdot1=11.$" },
  { id: "pat-ex-100", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 1, marks: 4,
    question: "The scalar (dot) product $(1\\,\\mathbf{i}+5\\,\\mathbf{j})\\cdot(2\\,\\mathbf{i}+3\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$11$" },{ key: "B", text: "$-13$" },{ key: "C", text: "$19$" },{ key: "D", text: "$17$" },{ key: "E", text: "$13$" }],
    answer: "D", solution: "$\\mathbf{a}\\cdot\\mathbf{b}=1\\cdot2+5\\cdot3=17.$" },
  { id: "pat-ex-101", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 1, marks: 4,
    question: "The scalar (dot) product $(3\\,\\mathbf{i}+-2\\,\\mathbf{j})\\cdot(4\\,\\mathbf{i}+5\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$10$" },{ key: "C", text: "$4$" },{ key: "D", text: "$2$" },{ key: "E", text: "$22$" }],
    answer: "D", solution: "$\\mathbf{a}\\cdot\\mathbf{b}=3\\cdot4+-2\\cdot5=2.$" },
  { id: "pat-ex-102", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 1, marks: 4,
    question: "The scalar (dot) product $(6\\,\\mathbf{i}+1\\,\\mathbf{j})\\cdot(2\\,\\mathbf{i}+2\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$10$" },{ key: "B", text: "$11$" },{ key: "C", text: "$13$" },{ key: "D", text: "$16$" },{ key: "E", text: "$14$" }],
    answer: "E", solution: "$\\mathbf{a}\\cdot\\mathbf{b}=6\\cdot2+1\\cdot2=14.$" },
  { id: "pat-ex-103", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 1, marks: 4,
    question: "The scalar (dot) product $(2\\,\\mathbf{i}+2\\,\\mathbf{j})\\cdot(3\\,\\mathbf{i}+3\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$12$" },{ key: "B", text: "$11$" },{ key: "C", text: "$0$" },{ key: "D", text: "$14$" },{ key: "E", text: "$10$" }],
    answer: "A", solution: "$\\mathbf{a}\\cdot\\mathbf{b}=2\\cdot3+2\\cdot3=12.$" },
  { id: "pat-ex-104", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "A particle's position is $s(t)=x^{3} - 3 x$. Its velocity at $t=2$ is:",
    options: [{ key: "A", text: "$12$" },{ key: "B", text: "$9$" },{ key: "C", text: "$7$" },{ key: "D", text: "$10$" },{ key: "E", text: "$2$" }],
    answer: "B", solution: "$v=\\dfrac{ds}{dt}=3 x^{2} - 3$; at $t=2$, $v=9.$" },
  { id: "pat-ex-105", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "A particle's position is $s(t)=2 x^{3} - x^{2}$. Its velocity at $t=1$ is:",
    options: [{ key: "A", text: "$10$" },{ key: "B", text: "$2$" },{ key: "C", text: "$1$" },{ key: "D", text: "$4$" },{ key: "E", text: "$5$" }],
    answer: "D", solution: "$v=\\dfrac{ds}{dt}=6 x^{2} - 2 x$; at $t=1$, $v=4.$" },
  { id: "pat-ex-106", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "A particle's position is $s(t)=x^{3} - 2 x^{2} + x$. Its velocity at $t=3$ is:",
    options: [{ key: "A", text: "$16$" },{ key: "B", text: "$32$" },{ key: "C", text: "$14$" },{ key: "D", text: "$12$" },{ key: "E", text: "$17$" }],
    answer: "A", solution: "$v=\\dfrac{ds}{dt}=3 x^{2} - 4 x + 1$; at $t=3$, $v=16.$" },
  { id: "pat-ex-107", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "A particle's position is $s(t)=x^{3}$. Its velocity at $t=2$ is:",
    options: [{ key: "A", text: "$13$" },{ key: "B", text: "$10$" },{ key: "C", text: "$24$" },{ key: "D", text: "$12$" },{ key: "E", text: "$8$" }],
    answer: "D", solution: "$v=\\dfrac{ds}{dt}=3 x^{2}$; at $t=2$, $v=12.$" },
  { id: "pat-ex-108", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "A particle's position is $s(t)=2 x^{3} - 4 x$. Its velocity at $t=1$ is:",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$-2$" },{ key: "C", text: "$3$" },{ key: "D", text: "$12$" },{ key: "E", text: "$0$" }],
    answer: "A", solution: "$v=\\dfrac{ds}{dt}=6 x^{2} - 4$; at $t=1$, $v=2.$" },
  { id: "pat-ex-109", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "Evaluate $\\displaystyle\\int_{1}^{4} 1x\\,dx$ (e.g. work done by a force $F=1x$):",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$\\frac{17}{2}$" },{ key: "C", text: "$4$" },{ key: "D", text: "$\\frac{15}{2}$" },{ key: "E", text: "$3$" }],
    answer: "D", solution: "$\\int_{1}^{4}1x\\,dx=\\left[\\tfrac{1}{2}x^2\\right]_{1}^{4}=\\frac{15}{2}.$" },
  { id: "pat-ex-110", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "Evaluate $\\displaystyle\\int_{1}^{3} 2x\\,dx$ (e.g. work done by a force $F=2x$):",
    options: [{ key: "A", text: "$16$" },{ key: "B", text: "$4$" },{ key: "C", text: "$6$" },{ key: "D", text: "$8$" },{ key: "E", text: "$9$" }],
    answer: "D", solution: "$\\int_{1}^{3}2x\\,dx=\\left[\\tfrac{2}{2}x^2\\right]_{1}^{3}=8.$" },
];
