// PAT 练习题库（第二批扩容）—— 全新题型，精确算术计算答案，经独立复核。id 前缀 pat-ex2-*。
import type { MCQQuestion } from "./types";

export const PAT_EXPANSION_2: MCQQuestion[] = [
  { id: "pat-ex2-001", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "An object starts at $5\\,\\text{m/s}$ with acceleration $2\\,\\text{m/s}^2$. The distance travelled in $3\\,\\text{s}$ is:",
    options: [{ key: "A", text: "$14\\,\\text{m}$" },{ key: "B", text: "$33\\,\\text{m}$" },{ key: "C", text: "$18\\,\\text{m}$" },{ key: "D", text: "$15\\,\\text{m}$" },{ key: "E", text: "$24\\,\\text{m}$" }],
    answer: "E", solution: "$s=ut+\\tfrac12at^2=5\\cdot3+\\tfrac12\\cdot2\\cdot3^2=24\\,$m." },
  { id: "pat-ex2-002", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "An object starts at $10\\,\\text{m/s}$ with acceleration $-2\\,\\text{m/s}^2$. The distance travelled in $2\\,\\text{s}$ is:",
    options: [{ key: "A", text: "$12\\,\\text{m}$" },{ key: "B", text: "$20\\,\\text{m}$" },{ key: "C", text: "$-8\\,\\text{m}$" },{ key: "D", text: "$6\\,\\text{m}$" },{ key: "E", text: "$16\\,\\text{m}$" }],
    answer: "E", solution: "$s=ut+\\tfrac12at^2=10\\cdot2+\\tfrac12\\cdot-2\\cdot2^2=16\\,$m." },
  { id: "pat-ex2-003", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "An object starts at $3\\,\\text{m/s}$ with acceleration $4\\,\\text{m/s}^2$. The distance travelled in $2\\,\\text{s}$ is:",
    options: [{ key: "A", text: "$16\\,\\text{m}$" },{ key: "B", text: "$14\\,\\text{m}$" },{ key: "C", text: "$6\\,\\text{m}$" },{ key: "D", text: "$22\\,\\text{m}$" },{ key: "E", text: "$11\\,\\text{m}$" }],
    answer: "B", solution: "$s=ut+\\tfrac12at^2=3\\cdot2+\\tfrac12\\cdot4\\cdot2^2=14\\,$m." },
  { id: "pat-ex2-004", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "An object starts at $4\\,\\text{m/s}$ with acceleration $3\\,\\text{m/s}^2$. The distance travelled in $3\\,\\text{s}$ is:",
    options: [{ key: "A", text: "$27\\,\\text{m}$" },{ key: "B", text: "$39\\,\\text{m}$" },{ key: "C", text: "$\\frac{35}{2}\\,\\text{m}$" },{ key: "D", text: "$\\frac{51}{2}\\,\\text{m}$" },{ key: "E", text: "$12\\,\\text{m}$" }],
    answer: "D", solution: "$s=ut+\\tfrac12at^2=4\\cdot3+\\tfrac12\\cdot3\\cdot3^2=\\frac{51}{2}\\,$m." },
  { id: "pat-ex2-005", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "With initial speed $0\\,\\text{m/s}$, acceleration $2\\,\\text{m/s}^2$, over $9\\,\\text{m}$, the final speed is:",
    options: [{ key: "A", text: "$18\\,\\text{m/s}$" },{ key: "B", text: "$36\\,\\text{m/s}$" },{ key: "C", text: "$3 \\sqrt{2}\\,\\text{m/s}$" },{ key: "D", text: "$6\\,\\text{m/s}$" },{ key: "E", text: "$7\\,\\text{m/s}$" }],
    answer: "D", solution: "$v^2=u^2+2as=0^2+2\\cdot2\\cdot9$, so $v=6\\,$m/s." },
  { id: "pat-ex2-006", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "With initial speed $3\\,\\text{m/s}$, acceleration $4\\,\\text{m/s}^2$, over $2\\,\\text{m}$, the final speed is:",
    options: [{ key: "A", text: "$16\\,\\text{m/s}$" },{ key: "B", text: "$11\\,\\text{m/s}$" },{ key: "C", text: "$5\\,\\text{m/s}$" },{ key: "D", text: "$\\sqrt{17}\\,\\text{m/s}$" },{ key: "E", text: "$6\\,\\text{m/s}$" }],
    answer: "C", solution: "$v^2=u^2+2as=3^2+2\\cdot4\\cdot2$, so $v=5\\,$m/s." },
  { id: "pat-ex2-007", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "With initial speed $0\\,\\text{m/s}$, acceleration $5\\,\\text{m/s}^2$, over $10\\,\\text{m}$, the final speed is:",
    options: [{ key: "A", text: "$100\\,\\text{m/s}$" },{ key: "B", text: "$10\\,\\text{m/s}$" },{ key: "C", text: "$11\\,\\text{m/s}$" },{ key: "D", text: "$5 \\sqrt{2}\\,\\text{m/s}$" },{ key: "E", text: "$50\\,\\text{m/s}$" }],
    answer: "B", solution: "$v^2=u^2+2as=0^2+2\\cdot5\\cdot10$, so $v=10\\,$m/s." },
  { id: "pat-ex2-008", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "With initial speed $4\\,\\text{m/s}$, acceleration $2\\,\\text{m/s}^2$, over $6\\,\\text{m}$, the final speed is:",
    options: [{ key: "A", text: "$2 \\sqrt{10}\\,\\text{m/s}$" },{ key: "B", text: "$1 + 2 \\sqrt{6}\\,\\text{m/s}$" },{ key: "C", text: "$24\\,\\text{m/s}$" },{ key: "D", text: "$2 \\sqrt{7}\\,\\text{m/s}$" },{ key: "E", text: "$16\\,\\text{m/s}$" }],
    answer: "A", solution: "$v^2=u^2+2as=4^2+2\\cdot2\\cdot6$, so $v=2 \\sqrt{10}\\,$m/s." },
  { id: "pat-ex2-009", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "With initial speed $1\\,\\text{m/s}$, acceleration $8\\,\\text{m/s}^2$, over $3\\,\\text{m}$, the final speed is:",
    options: [{ key: "A", text: "$48\\,\\text{m/s}$" },{ key: "B", text: "$7\\,\\text{m/s}$" },{ key: "C", text: "$25\\,\\text{m/s}$" },{ key: "D", text: "$5\\,\\text{m/s}$" },{ key: "E", text: "$1 + 4 \\sqrt{3}\\,\\text{m/s}$" }],
    answer: "B", solution: "$v^2=u^2+2as=1^2+2\\cdot8\\cdot3$, so $v=7\\,$m/s." },
  { id: "pat-ex2-010", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "On Earth ($g=10$), the weight of a $2\\,\\text{kg}$ mass is:",
    options: [{ key: "A", text: "$40\\,\\text{N}$" },{ key: "B", text: "$20\\,\\text{N}$" },{ key: "C", text: "$\\frac{1}{5}\\,\\text{N}$" },{ key: "D", text: "$12\\,\\text{N}$" },{ key: "E", text: "$2\\,\\text{N}$" }],
    answer: "B", solution: "$W=mg=2\\times10=20\\,$N." },
  { id: "pat-ex2-011", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "On Earth ($g=10$), the weight of a $5\\,\\text{kg}$ mass is:",
    options: [{ key: "A", text: "$15\\,\\text{N}$" },{ key: "B", text: "$100\\,\\text{N}$" },{ key: "C", text: "$5\\,\\text{N}$" },{ key: "D", text: "$\\frac{1}{2}\\,\\text{N}$" },{ key: "E", text: "$50\\,\\text{N}$" }],
    answer: "E", solution: "$W=mg=5\\times10=50\\,$N." },
  { id: "pat-ex2-012", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "On Earth ($g=10$), the weight of a $10\\,\\text{kg}$ mass is:",
    options: [{ key: "A", text: "$200\\,\\text{N}$" },{ key: "B", text: "$20\\,\\text{N}$" },{ key: "C", text: "$100\\,\\text{N}$" },{ key: "D", text: "$1\\,\\text{N}$" },{ key: "E", text: "$10\\,\\text{N}$" }],
    answer: "C", solution: "$W=mg=10\\times10=100\\,$N." },
  { id: "pat-ex2-013", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "On Earth ($g=10$), the weight of a $3\\,\\text{kg}$ mass is:",
    options: [{ key: "A", text: "$3\\,\\text{N}$" },{ key: "B", text: "$13\\,\\text{N}$" },{ key: "C", text: "$60\\,\\text{N}$" },{ key: "D", text: "$\\frac{3}{10}\\,\\text{N}$" },{ key: "E", text: "$30\\,\\text{N}$" }],
    answer: "E", solution: "$W=mg=3\\times10=30\\,$N." },
  { id: "pat-ex2-014", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "On Earth ($g=10$), the weight of a $8\\,\\text{kg}$ mass is:",
    options: [{ key: "A", text: "$\\frac{4}{5}\\,\\text{N}$" },{ key: "B", text: "$8\\,\\text{N}$" },{ key: "C", text: "$160\\,\\text{N}$" },{ key: "D", text: "$80\\,\\text{N}$" },{ key: "E", text: "$18\\,\\text{N}$" }],
    answer: "D", solution: "$W=mg=8\\times10=80\\,$N." },
  { id: "pat-ex2-015", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "On Earth ($g=10$), the weight of a $1\\,\\text{kg}$ mass is:",
    options: [{ key: "A", text: "$\\frac{1}{10}\\,\\text{N}$" },{ key: "B", text: "$10\\,\\text{N}$" },{ key: "C", text: "$20\\,\\text{N}$" },{ key: "D", text: "$11\\,\\text{N}$" },{ key: "E", text: "$1\\,\\text{N}$" }],
    answer: "B", solution: "$W=mg=1\\times10=10\\,$N." },
  { id: "pat-ex2-016", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "A force $10\\,\\text{N}$ moves an object $4\\,\\text{m}$ in $2\\,\\text{s}$. The average power is:",
    options: [{ key: "A", text: "$80\\,\\text{W}$" },{ key: "B", text: "$2\\,\\text{W}$" },{ key: "C", text: "$40\\,\\text{W}$" },{ key: "D", text: "$5\\,\\text{W}$" },{ key: "E", text: "$20\\,\\text{W}$" }],
    answer: "E", solution: "$P=\\dfrac{W}{t}=\\dfrac{Fd}{t}=\\dfrac{10\\cdot4}{2}=20\\,$W." },
  { id: "pat-ex2-017", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "A force $20\\,\\text{N}$ moves an object $3\\,\\text{m}$ in $5\\,\\text{s}$. The average power is:",
    options: [{ key: "A", text: "$300\\,\\text{W}$" },{ key: "B", text: "$4\\,\\text{W}$" },{ key: "C", text: "$60\\,\\text{W}$" },{ key: "D", text: "$\\frac{3}{5}\\,\\text{W}$" },{ key: "E", text: "$12\\,\\text{W}$" }],
    answer: "E", solution: "$P=\\dfrac{W}{t}=\\dfrac{Fd}{t}=\\dfrac{20\\cdot3}{5}=12\\,$W." },
  { id: "pat-ex2-018", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "A force $6\\,\\text{N}$ moves an object $5\\,\\text{m}$ in $3\\,\\text{s}$. The average power is:",
    options: [{ key: "A", text: "$\\frac{5}{3}\\,\\text{W}$" },{ key: "B", text: "$90\\,\\text{W}$" },{ key: "C", text: "$30\\,\\text{W}$" },{ key: "D", text: "$2\\,\\text{W}$" },{ key: "E", text: "$10\\,\\text{W}$" }],
    answer: "E", solution: "$P=\\dfrac{W}{t}=\\dfrac{Fd}{t}=\\dfrac{6\\cdot5}{3}=10\\,$W." },
  { id: "pat-ex2-019", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "A force $15\\,\\text{N}$ moves an object $2\\,\\text{m}$ in $3\\,\\text{s}$. The average power is:",
    options: [{ key: "A", text: "$90\\,\\text{W}$" },{ key: "B", text: "$5\\,\\text{W}$" },{ key: "C", text: "$30\\,\\text{W}$" },{ key: "D", text: "$\\frac{2}{3}\\,\\text{W}$" },{ key: "E", text: "$10\\,\\text{W}$" }],
    answer: "E", solution: "$P=\\dfrac{W}{t}=\\dfrac{Fd}{t}=\\dfrac{15\\cdot2}{3}=10\\,$W." },
  { id: "pat-ex2-020", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 2, marks: 4,
    question: "A force $12\\,\\text{N}$ moves an object $6\\,\\text{m}$ in $4\\,\\text{s}$. The average power is:",
    options: [{ key: "A", text: "$3\\,\\text{W}$" },{ key: "B", text: "$\\frac{3}{2}\\,\\text{W}$" },{ key: "C", text: "$72\\,\\text{W}$" },{ key: "D", text: "$18\\,\\text{W}$" },{ key: "E", text: "$288\\,\\text{W}$" }],
    answer: "D", solution: "$P=\\dfrac{W}{t}=\\dfrac{Fd}{t}=\\dfrac{12\\cdot6}{4}=18\\,$W." },
  { id: "pat-ex2-021", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "The gravitational PE gained lifting $2\\,\\text{kg}$ by $5\\,\\text{m}$ ($g=10$) is:",
    options: [{ key: "A", text: "$20\\,\\text{J}$" },{ key: "B", text: "$10\\,\\text{J}$" },{ key: "C", text: "$100\\,\\text{J}$" },{ key: "D", text: "$50\\,\\text{J}$" },{ key: "E", text: "$110\\,\\text{J}$" }],
    answer: "C", solution: "$E_p=mgh=2\\cdot10\\cdot5=100\\,$J." },
  { id: "pat-ex2-022", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "The gravitational PE gained lifting $3\\,\\text{kg}$ by $10\\,\\text{m}$ ($g=10$) is:",
    options: [{ key: "A", text: "$310\\,\\text{J}$" },{ key: "B", text: "$300\\,\\text{J}$" },{ key: "C", text: "$150\\,\\text{J}$" },{ key: "D", text: "$100\\,\\text{J}$" },{ key: "E", text: "$30\\,\\text{J}$" }],
    answer: "B", solution: "$E_p=mgh=3\\cdot10\\cdot10=300\\,$J." },
  { id: "pat-ex2-023", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "The gravitational PE gained lifting $1\\,\\text{kg}$ by $20\\,\\text{m}$ ($g=10$) is:",
    options: [{ key: "A", text: "$100\\,\\text{J}$" },{ key: "B", text: "$210\\,\\text{J}$" },{ key: "C", text: "$20\\,\\text{J}$" },{ key: "D", text: "$200\\,\\text{J}$" },{ key: "E", text: "$10\\,\\text{J}$" }],
    answer: "D", solution: "$E_p=mgh=1\\cdot10\\cdot20=200\\,$J." },
  { id: "pat-ex2-024", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "The gravitational PE gained lifting $5\\,\\text{kg}$ by $4\\,\\text{m}$ ($g=10$) is:",
    options: [{ key: "A", text: "$20\\,\\text{J}$" },{ key: "B", text: "$200\\,\\text{J}$" },{ key: "C", text: "$100\\,\\text{J}$" },{ key: "D", text: "$50\\,\\text{J}$" },{ key: "E", text: "$40\\,\\text{J}$" }],
    answer: "B", solution: "$E_p=mgh=5\\cdot10\\cdot4=200\\,$J." },
  { id: "pat-ex2-025", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "The gravitational PE gained lifting $4\\,\\text{kg}$ by $6\\,\\text{m}$ ($g=10$) is:",
    options: [{ key: "A", text: "$24\\,\\text{J}$" },{ key: "B", text: "$60\\,\\text{J}$" },{ key: "C", text: "$240\\,\\text{J}$" },{ key: "D", text: "$40\\,\\text{J}$" },{ key: "E", text: "$120\\,\\text{J}$" }],
    answer: "C", solution: "$E_p=mgh=4\\cdot10\\cdot6=240\\,$J." },
  { id: "pat-ex2-026", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "A force $20\\,\\text{N}$ acts on area $4\\,\\text{m}^2$. The pressure is:",
    options: [{ key: "A", text: "$\\frac{1}{5}\\,\\text{Pa}$" },{ key: "B", text: "$24\\,\\text{Pa}$" },{ key: "C", text: "$5\\,\\text{Pa}$" },{ key: "D", text: "$16\\,\\text{Pa}$" },{ key: "E", text: "$80\\,\\text{Pa}$" }],
    answer: "C", solution: "$P=\\dfrac{F}{A}=\\dfrac{20}{4}=5\\,$Pa." },
  { id: "pat-ex2-027", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "A force $12\\,\\text{N}$ acts on area $3\\,\\text{m}^2$. The pressure is:",
    options: [{ key: "A", text: "$\\frac{1}{4}\\,\\text{Pa}$" },{ key: "B", text: "$4\\,\\text{Pa}$" },{ key: "C", text: "$36\\,\\text{Pa}$" },{ key: "D", text: "$9\\,\\text{Pa}$" },{ key: "E", text: "$15\\,\\text{Pa}$" }],
    answer: "B", solution: "$P=\\dfrac{F}{A}=\\dfrac{12}{3}=4\\,$Pa." },
  { id: "pat-ex2-028", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "A force $50\\,\\text{N}$ acts on area $5\\,\\text{m}^2$. The pressure is:",
    options: [{ key: "A", text: "$250\\,\\text{Pa}$" },{ key: "B", text: "$45\\,\\text{Pa}$" },{ key: "C", text: "$55\\,\\text{Pa}$" },{ key: "D", text: "$\\frac{1}{10}\\,\\text{Pa}$" },{ key: "E", text: "$10\\,\\text{Pa}$" }],
    answer: "E", solution: "$P=\\dfrac{F}{A}=\\dfrac{50}{5}=10\\,$Pa." },
  { id: "pat-ex2-029", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "A force $9\\,\\text{N}$ acts on area $3\\,\\text{m}^2$. The pressure is:",
    options: [{ key: "A", text: "$3\\,\\text{Pa}$" },{ key: "B", text: "$27\\,\\text{Pa}$" },{ key: "C", text: "$6\\,\\text{Pa}$" },{ key: "D", text: "$\\frac{1}{3}\\,\\text{Pa}$" },{ key: "E", text: "$12\\,\\text{Pa}$" }],
    answer: "A", solution: "$P=\\dfrac{F}{A}=\\dfrac{9}{3}=3\\,$Pa." },
  { id: "pat-ex2-030", type: "mcq", testId: "pat", topicId: "pat-mech", difficulty: 1, marks: 4,
    question: "A force $100\\,\\text{N}$ acts on area $10\\,\\text{m}^2$. The pressure is:",
    options: [{ key: "A", text: "$110\\,\\text{Pa}$" },{ key: "B", text: "$\\frac{1}{10}\\,\\text{Pa}$" },{ key: "C", text: "$1000\\,\\text{Pa}$" },{ key: "D", text: "$10\\,\\text{Pa}$" },{ key: "E", text: "$90\\,\\text{Pa}$" }],
    answer: "D", solution: "$P=\\dfrac{F}{A}=\\dfrac{100}{10}=10\\,$Pa." },
  { id: "pat-ex2-031", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "Two resistors $3\\,\\Omega$ and $5\\,\\Omega$ in series give:",
    options: [{ key: "A", text: "$\\frac{15}{8}\\,\\Omega$" },{ key: "B", text: "$8\\,\\Omega$" },{ key: "C", text: "$4\\,\\Omega$" },{ key: "D", text: "$15\\,\\Omega$" },{ key: "E", text: "$2\\,\\Omega$" }],
    answer: "B", solution: "Series: $R=3+5=8\\,\\Omega$." },
  { id: "pat-ex2-032", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "Two resistors $2\\,\\Omega$ and $8\\,\\Omega$ in series give:",
    options: [{ key: "A", text: "$6\\,\\Omega$" },{ key: "B", text: "$16\\,\\Omega$" },{ key: "C", text: "$10\\,\\Omega$" },{ key: "D", text: "$5\\,\\Omega$" },{ key: "E", text: "$\\frac{8}{5}\\,\\Omega$" }],
    answer: "C", solution: "Series: $R=2+8=10\\,\\Omega$." },
  { id: "pat-ex2-033", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "Two resistors $10\\,\\Omega$ and $15\\,\\Omega$ in series give:",
    options: [{ key: "A", text: "$25\\,\\Omega$" },{ key: "B", text: "$5\\,\\Omega$" },{ key: "C", text: "$\\frac{25}{2}\\,\\Omega$" },{ key: "D", text: "$6\\,\\Omega$" },{ key: "E", text: "$150\\,\\Omega$" }],
    answer: "A", solution: "Series: $R=10+15=25\\,\\Omega$." },
  { id: "pat-ex2-034", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "Two resistors $4\\,\\Omega$ and $6\\,\\Omega$ in series give:",
    options: [{ key: "A", text: "$10\\,\\Omega$" },{ key: "B", text: "$24\\,\\Omega$" },{ key: "C", text: "$2\\,\\Omega$" },{ key: "D", text: "$\\frac{12}{5}\\,\\Omega$" },{ key: "E", text: "$5\\,\\Omega$" }],
    answer: "A", solution: "Series: $R=4+6=10\\,\\Omega$." },
  { id: "pat-ex2-035", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "Two resistors $7\\,\\Omega$ and $3\\,\\Omega$ in series give:",
    options: [{ key: "A", text: "$21\\,\\Omega$" },{ key: "B", text: "$\\frac{21}{10}\\,\\Omega$" },{ key: "C", text: "$10\\,\\Omega$" },{ key: "D", text: "$4\\,\\Omega$" },{ key: "E", text: "$5\\,\\Omega$" }],
    answer: "C", solution: "Series: $R=7+3=10\\,\\Omega$." },
  { id: "pat-ex2-036", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "Two resistors $12\\,\\Omega$ and $8\\,\\Omega$ in series give:",
    options: [{ key: "A", text: "$\\frac{24}{5}\\,\\Omega$" },{ key: "B", text: "$10\\,\\Omega$" },{ key: "C", text: "$20\\,\\Omega$" },{ key: "D", text: "$96\\,\\Omega$" },{ key: "E", text: "$4\\,\\Omega$" }],
    answer: "C", solution: "Series: $R=12+8=20\\,\\Omega$." },
  { id: "pat-ex2-037", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "A current $2\\,\\text{A}$ flows through $3\\,\\Omega$. The power dissipated is:",
    options: [{ key: "A", text: "$\\frac{3}{2}\\,\\text{W}$" },{ key: "B", text: "$6\\,\\text{W}$" },{ key: "C", text: "$12\\,\\text{W}$" },{ key: "D", text: "$4\\,\\text{W}$" },{ key: "E", text: "$14\\,\\text{W}$" }],
    answer: "C", solution: "$P=I^2R=2^2\\cdot3=12\\,$W." },
  { id: "pat-ex2-038", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "A current $3\\,\\text{A}$ flows through $4\\,\\Omega$. The power dissipated is:",
    options: [{ key: "A", text: "$\\frac{4}{3}\\,\\text{W}$" },{ key: "B", text: "$12\\,\\text{W}$" },{ key: "C", text: "$9\\,\\text{W}$" },{ key: "D", text: "$24\\,\\text{W}$" },{ key: "E", text: "$36\\,\\text{W}$" }],
    answer: "E", solution: "$P=I^2R=3^2\\cdot4=36\\,$W." },
  { id: "pat-ex2-039", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "A current $5\\,\\text{A}$ flows through $2\\,\\Omega$. The power dissipated is:",
    options: [{ key: "A", text: "$50\\,\\text{W}$" },{ key: "B", text: "$20\\,\\text{W}$" },{ key: "C", text: "$25\\,\\text{W}$" },{ key: "D", text: "$\\frac{2}{5}\\,\\text{W}$" },{ key: "E", text: "$10\\,\\text{W}$" }],
    answer: "A", solution: "$P=I^2R=5^2\\cdot2=50\\,$W." },
  { id: "pat-ex2-040", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "A current $4\\,\\text{A}$ flows through $5\\,\\Omega$. The power dissipated is:",
    options: [{ key: "A", text: "$40\\,\\text{W}$" },{ key: "B", text: "$16\\,\\text{W}$" },{ key: "C", text: "$20\\,\\text{W}$" },{ key: "D", text: "$\\frac{5}{4}\\,\\text{W}$" },{ key: "E", text: "$80\\,\\text{W}$" }],
    answer: "E", solution: "$P=I^2R=4^2\\cdot5=80\\,$W." },
  { id: "pat-ex2-041", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "A $2\\,\\text{F}$ capacitor is charged to $5\\,\\text{V}$. The charge stored is:",
    options: [{ key: "A", text: "$\\frac{5}{2}\\,\\text{C}$" },{ key: "B", text: "$20\\,\\text{C}$" },{ key: "C", text: "$7\\,\\text{C}$" },{ key: "D", text: "$\\frac{2}{5}\\,\\text{C}$" },{ key: "E", text: "$10\\,\\text{C}$" }],
    answer: "E", solution: "$Q=CV=2\\cdot5=10\\,$C." },
  { id: "pat-ex2-042", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "A $4\\,\\text{F}$ capacitor is charged to $3\\,\\text{V}$. The charge stored is:",
    options: [{ key: "A", text: "$24\\,\\text{C}$" },{ key: "B", text: "$\\frac{3}{4}\\,\\text{C}$" },{ key: "C", text: "$12\\,\\text{C}$" },{ key: "D", text: "$\\frac{4}{3}\\,\\text{C}$" },{ key: "E", text: "$7\\,\\text{C}$" }],
    answer: "C", solution: "$Q=CV=4\\cdot3=12\\,$C." },
  { id: "pat-ex2-043", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "A $3\\,\\text{F}$ capacitor is charged to $4\\,\\text{V}$. The charge stored is:",
    options: [{ key: "A", text: "$\\frac{3}{4}\\,\\text{C}$" },{ key: "B", text: "$\\frac{4}{3}\\,\\text{C}$" },{ key: "C", text: "$7\\,\\text{C}$" },{ key: "D", text: "$24\\,\\text{C}$" },{ key: "E", text: "$12\\,\\text{C}$" }],
    answer: "E", solution: "$Q=CV=3\\cdot4=12\\,$C." },
  { id: "pat-ex2-044", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "A $5\\,\\text{F}$ capacitor is charged to $2\\,\\text{V}$. The charge stored is:",
    options: [{ key: "A", text: "$7\\,\\text{C}$" },{ key: "B", text: "$\\frac{5}{2}\\,\\text{C}$" },{ key: "C", text: "$20\\,\\text{C}$" },{ key: "D", text: "$10\\,\\text{C}$" },{ key: "E", text: "$\\frac{2}{5}\\,\\text{C}$" }],
    answer: "D", solution: "$Q=CV=5\\cdot2=10\\,$C." },
  { id: "pat-ex2-045", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "The energy stored in a $2\\,\\text{F}$ capacitor at $4\\,\\text{V}$ is:",
    options: [{ key: "A", text: "$16\\,\\text{J}$" },{ key: "B", text: "$4\\,\\text{J}$" },{ key: "C", text: "$32\\,\\text{J}$" },{ key: "D", text: "$18\\,\\text{J}$" },{ key: "E", text: "$8\\,\\text{J}$" }],
    answer: "A", solution: "$E=\\tfrac12CV^2=\\tfrac12\\cdot2\\cdot4^2=16\\,$J." },
  { id: "pat-ex2-046", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "The energy stored in a $1\\,\\text{F}$ capacitor at $6\\,\\text{V}$ is:",
    options: [{ key: "A", text: "$3\\,\\text{J}$" },{ key: "B", text: "$20\\,\\text{J}$" },{ key: "C", text: "$18\\,\\text{J}$" },{ key: "D", text: "$6\\,\\text{J}$" },{ key: "E", text: "$36\\,\\text{J}$" }],
    answer: "C", solution: "$E=\\tfrac12CV^2=\\tfrac12\\cdot1\\cdot6^2=18\\,$J." },
  { id: "pat-ex2-047", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 2, marks: 4,
    question: "The energy stored in a $5\\,\\text{F}$ capacitor at $4\\,\\text{V}$ is:",
    options: [{ key: "A", text: "$20\\,\\text{J}$" },{ key: "B", text: "$10\\,\\text{J}$" },{ key: "C", text: "$42\\,\\text{J}$" },{ key: "D", text: "$80\\,\\text{J}$" },{ key: "E", text: "$40\\,\\text{J}$" }],
    answer: "E", solution: "$E=\\tfrac12CV^2=\\tfrac12\\cdot5\\cdot4^2=40\\,$J." },
  { id: "pat-ex2-048", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 3, marks: 4,
    question: "Two charges $2\\,\\mu\\text{C}$ and $2\\,\\mu\\text{C}$ are $3\\,\\text{m}$ apart ($k=9\\times10^9$). The force (in mN) is:",
    options: [{ key: "A", text: "$12\\,\\text{mN}$" },{ key: "B", text: "$\\frac{4}{9}\\,\\text{mN}$" },{ key: "C", text: "$5\\,\\text{mN}$" },{ key: "D", text: "$4\\,\\text{mN}$" },{ key: "E", text: "$36\\,\\text{mN}$" }],
    answer: "D", solution: "$F=\\dfrac{kq_1q_2}{r^2}=\\dfrac{9\\cdot2\\cdot2}{3^2}=4\\,$mN." },
  { id: "pat-ex2-049", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 3, marks: 4,
    question: "Two charges $3\\,\\mu\\text{C}$ and $3\\,\\mu\\text{C}$ are $3\\,\\text{m}$ apart ($k=9\\times10^9$). The force (in mN) is:",
    options: [{ key: "A", text: "$10\\,\\text{mN}$" },{ key: "B", text: "$1\\,\\text{mN}$" },{ key: "C", text: "$81\\,\\text{mN}$" },{ key: "D", text: "$9\\,\\text{mN}$" },{ key: "E", text: "$27\\,\\text{mN}$" }],
    answer: "D", solution: "$F=\\dfrac{kq_1q_2}{r^2}=\\dfrac{9\\cdot3\\cdot3}{3^2}=9\\,$mN." },
  { id: "pat-ex2-050", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 3, marks: 4,
    question: "Two charges $1\\,\\mu\\text{C}$ and $4\\,\\mu\\text{C}$ are $2\\,\\text{m}$ apart ($k=9\\times10^9$). The force (in mN) is:",
    options: [{ key: "A", text: "$18\\,\\text{mN}$" },{ key: "B", text: "$10\\,\\text{mN}$" },{ key: "C", text: "$36\\,\\text{mN}$" },{ key: "D", text: "$9\\,\\text{mN}$" },{ key: "E", text: "$1\\,\\text{mN}$" }],
    answer: "D", solution: "$F=\\dfrac{kq_1q_2}{r^2}=\\dfrac{9\\cdot1\\cdot4}{2^2}=9\\,$mN." },
  { id: "pat-ex2-051", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 3, marks: 4,
    question: "Two charges $6\\,\\mu\\text{C}$ and $3\\,\\mu\\text{C}$ are $3\\,\\text{m}$ apart ($k=9\\times10^9$). The force (in mN) is:",
    options: [{ key: "A", text: "$18\\,\\text{mN}$" },{ key: "B", text: "$162\\,\\text{mN}$" },{ key: "C", text: "$19\\,\\text{mN}$" },{ key: "D", text: "$2\\,\\text{mN}$" },{ key: "E", text: "$54\\,\\text{mN}$" }],
    answer: "A", solution: "$F=\\dfrac{kq_1q_2}{r^2}=\\dfrac{9\\cdot6\\cdot3}{3^2}=18\\,$mN." },
  { id: "pat-ex2-052", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "The uniform field between plates $3\\,\\text{m}$ apart at $12\\,\\text{V}$ is:",
    options: [{ key: "A", text: "$36\\,\\text{V/m}$" },{ key: "B", text: "$9\\,\\text{V/m}$" },{ key: "C", text: "$4\\,\\text{V/m}$" },{ key: "D", text: "$\\frac{1}{4}\\,\\text{V/m}$" },{ key: "E", text: "$8\\,\\text{V/m}$" }],
    answer: "C", solution: "$E=\\dfrac{V}{d}=\\dfrac{12}{3}=4\\,$V/m." },
  { id: "pat-ex2-053", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "The uniform field between plates $4\\,\\text{m}$ apart at $20\\,\\text{V}$ is:",
    options: [{ key: "A", text: "$16\\,\\text{V/m}$" },{ key: "B", text: "$\\frac{1}{5}\\,\\text{V/m}$" },{ key: "C", text: "$10\\,\\text{V/m}$" },{ key: "D", text: "$5\\,\\text{V/m}$" },{ key: "E", text: "$80\\,\\text{V/m}$" }],
    answer: "D", solution: "$E=\\dfrac{V}{d}=\\dfrac{20}{4}=5\\,$V/m." },
  { id: "pat-ex2-054", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "The uniform field between plates $2\\,\\text{m}$ apart at $6\\,\\text{V}$ is:",
    options: [{ key: "A", text: "$12\\,\\text{V/m}$" },{ key: "B", text: "$3\\,\\text{V/m}$" },{ key: "C", text: "$\\frac{1}{3}\\,\\text{V/m}$" },{ key: "D", text: "$4\\,\\text{V/m}$" },{ key: "E", text: "$6\\,\\text{V/m}$" }],
    answer: "B", solution: "$E=\\dfrac{V}{d}=\\dfrac{6}{2}=3\\,$V/m." },
  { id: "pat-ex2-055", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "The uniform field between plates $5\\,\\text{m}$ apart at $100\\,\\text{V}$ is:",
    options: [{ key: "A", text: "$40\\,\\text{V/m}$" },{ key: "B", text: "$20\\,\\text{V/m}$" },{ key: "C", text: "$\\frac{1}{20}\\,\\text{V/m}$" },{ key: "D", text: "$500\\,\\text{V/m}$" },{ key: "E", text: "$95\\,\\text{V/m}$" }],
    answer: "B", solution: "$E=\\dfrac{V}{d}=\\dfrac{100}{5}=20\\,$V/m." },
  { id: "pat-ex2-056", type: "mcq", testId: "pat", topicId: "pat-em", difficulty: 1, marks: 4,
    question: "The uniform field between plates $3\\,\\text{m}$ apart at $9\\,\\text{V}$ is:",
    options: [{ key: "A", text: "$4\\,\\text{V/m}$" },{ key: "B", text: "$3\\,\\text{V/m}$" },{ key: "C", text: "$\\frac{1}{3}\\,\\text{V/m}$" },{ key: "D", text: "$27\\,\\text{V/m}$" },{ key: "E", text: "$6\\,\\text{V/m}$" }],
    answer: "B", solution: "$E=\\dfrac{V}{d}=\\dfrac{9}{3}=3\\,$V/m." },
  { id: "pat-ex2-057", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 1, marks: 4,
    question: "A wave has frequency $50\\,\\text{Hz}$. Its period is:",
    options: [{ key: "A", text: "$\\frac{1}{25}\\,\\text{s}$" },{ key: "B", text: "$25\\,\\text{s}$" },{ key: "C", text: "$\\frac{1}{50}\\,\\text{s}$" },{ key: "D", text: "$100\\,\\text{s}$" },{ key: "E", text: "$50\\,\\text{s}$" }],
    answer: "C", solution: "$T=\\dfrac1f=\\dfrac1{50}=\\frac{1}{50}\\,$s." },
  { id: "pat-ex2-058", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 1, marks: 4,
    question: "A wave has frequency $100\\,\\text{Hz}$. Its period is:",
    options: [{ key: "A", text: "$\\frac{1}{50}\\,\\text{s}$" },{ key: "B", text: "$200\\,\\text{s}$" },{ key: "C", text: "$100\\,\\text{s}$" },{ key: "D", text: "$50\\,\\text{s}$" },{ key: "E", text: "$\\frac{1}{100}\\,\\text{s}$" }],
    answer: "E", solution: "$T=\\dfrac1f=\\dfrac1{100}=\\frac{1}{100}\\,$s." },
  { id: "pat-ex2-059", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 1, marks: 4,
    question: "A wave has frequency $25\\,\\text{Hz}$. Its period is:",
    options: [{ key: "A", text: "$25\\,\\text{s}$" },{ key: "B", text: "$\\frac{25}{2}\\,\\text{s}$" },{ key: "C", text: "$\\frac{1}{25}\\,\\text{s}$" },{ key: "D", text: "$\\frac{2}{25}\\,\\text{s}$" },{ key: "E", text: "$50\\,\\text{s}$" }],
    answer: "C", solution: "$T=\\dfrac1f=\\dfrac1{25}=\\frac{1}{25}\\,$s." },
  { id: "pat-ex2-060", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 1, marks: 4,
    question: "A wave has frequency $200\\,\\text{Hz}$. Its period is:",
    options: [{ key: "A", text: "$\\frac{1}{200}\\,\\text{s}$" },{ key: "B", text: "$100\\,\\text{s}$" },{ key: "C", text: "$200\\,\\text{s}$" },{ key: "D", text: "$400\\,\\text{s}$" },{ key: "E", text: "$\\frac{1}{100}\\,\\text{s}$" }],
    answer: "A", solution: "$T=\\dfrac1f=\\dfrac1{200}=\\frac{1}{200}\\,$s." },
  { id: "pat-ex2-061", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 1, marks: 4,
    question: "A wave has frequency $4\\,\\text{Hz}$. Its period is:",
    options: [{ key: "A", text: "$2\\,\\text{s}$" },{ key: "B", text: "$\\frac{1}{4}\\,\\text{s}$" },{ key: "C", text: "$8\\,\\text{s}$" },{ key: "D", text: "$\\frac{1}{2}\\,\\text{s}$" },{ key: "E", text: "$4\\,\\text{s}$" }],
    answer: "B", solution: "$T=\\dfrac1f=\\dfrac1{4}=\\frac{1}{4}\\,$s." },
  { id: "pat-ex2-062", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 1, marks: 4,
    question: "A wave has frequency $500\\,\\text{Hz}$. Its period is:",
    options: [{ key: "A", text: "$250\\,\\text{s}$" },{ key: "B", text: "$\\frac{1}{250}\\,\\text{s}$" },{ key: "C", text: "$500\\,\\text{s}$" },{ key: "D", text: "$\\frac{1}{500}\\,\\text{s}$" },{ key: "E", text: "$1000\\,\\text{s}$" }],
    answer: "D", solution: "$T=\\dfrac1f=\\dfrac1{500}=\\frac{1}{500}\\,$s." },
  { id: "pat-ex2-063", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "Light crosses from medium $n_1=\\frac{3}{2}$ into $n_2=1$ with $\\sin\\theta_1=\\frac{1}{3}$. Then $\\sin\\theta_2$ is:",
    options: [{ key: "A", text: "$\\frac{1}{6}$" },{ key: "B", text: "$\\frac{1}{2}$" },{ key: "C", text: "$\\frac{1}{3}$" },{ key: "D", text: "$\\frac{3}{5}$" },{ key: "E", text: "$\\frac{2}{9}$" }],
    answer: "B", solution: "Snell: $n_1\\sin\\theta_1=n_2\\sin\\theta_2\\Rightarrow\\sin\\theta_2=\\dfrac{\\frac{3}{2}\\cdot\\frac{1}{3}}{1}=\\frac{1}{2}.$" },
  { id: "pat-ex2-064", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "Light crosses from medium $n_1=\\frac{4}{3}$ into $n_2=1$ with $\\sin\\theta_1=\\frac{1}{2}$. Then $\\sin\\theta_2$ is:",
    options: [{ key: "A", text: "$\\frac{23}{30}$" },{ key: "B", text: "$\\frac{1}{2}$" },{ key: "C", text: "$\\frac{1}{4}$" },{ key: "D", text: "$\\frac{3}{8}$" },{ key: "E", text: "$\\frac{2}{3}$" }],
    answer: "E", solution: "Snell: $n_1\\sin\\theta_1=n_2\\sin\\theta_2\\Rightarrow\\sin\\theta_2=\\dfrac{\\frac{4}{3}\\cdot\\frac{1}{2}}{1}=\\frac{2}{3}.$" },
  { id: "pat-ex2-065", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "Light crosses from medium $n_1=1$ into $n_2=\\frac{3}{2}$ with $\\sin\\theta_1=\\frac{3}{5}$. Then $\\sin\\theta_2$ is:",
    options: [{ key: "A", text: "$\\frac{2}{5}$" },{ key: "B", text: "$\\frac{3}{10}$" },{ key: "C", text: "$\\frac{1}{2}$" },{ key: "D", text: "$\\frac{9}{10}$" },{ key: "E", text: "$\\frac{3}{5}$" }],
    answer: "A", solution: "Snell: $n_1\\sin\\theta_1=n_2\\sin\\theta_2\\Rightarrow\\sin\\theta_2=\\dfrac{1\\cdot\\frac{3}{5}}{\\frac{3}{2}}=\\frac{2}{5}.$" },
  { id: "pat-ex2-066", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "For a converging lens $f=10\\,\\text{cm}$, object at $15\\,\\text{cm}$, the magnification $|m|$ is:",
    options: [{ key: "A", text: "$30$" },{ key: "B", text: "$\\frac{1}{2}$" },{ key: "C", text: "$3$" },{ key: "D", text: "$\\frac{2}{3}$" },{ key: "E", text: "$2$" }],
    answer: "E", solution: "$v=\\dfrac{fu}{u-f}=30$; $|m|=\\dfrac{v}{u}=2.$" },
  { id: "pat-ex2-067", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "For a converging lens $f=20\\,\\text{cm}$, object at $30\\,\\text{cm}$, the magnification $|m|$ is:",
    options: [{ key: "A", text: "$\\frac{1}{2}$" },{ key: "B", text: "$3$" },{ key: "C", text: "$2$" },{ key: "D", text: "$\\frac{2}{3}$" },{ key: "E", text: "$60$" }],
    answer: "C", solution: "$v=\\dfrac{fu}{u-f}=60$; $|m|=\\dfrac{v}{u}=2.$" },
  { id: "pat-ex2-068", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "For a converging lens $f=15\\,\\text{cm}$, object at $45\\,\\text{cm}$, the magnification $|m|$ is:",
    options: [{ key: "A", text: "$\\frac{3}{2}$" },{ key: "B", text: "$\\frac{1}{2}$" },{ key: "C", text: "$\\frac{45}{2}$" },{ key: "D", text: "$\\frac{1}{3}$" },{ key: "E", text: "$2$" }],
    answer: "B", solution: "$v=\\dfrac{fu}{u-f}=\\frac{45}{2}$; $|m|=\\dfrac{v}{u}=\\frac{1}{2}.$" },
  { id: "pat-ex2-069", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "A diffraction grating (consistent units) has $d=6$, wavelength $\\lambda=2$, order $n=1$. Then $\\sin\\theta$ is:",
    options: [{ key: "A", text: "$\\frac{1}{3}$" },{ key: "B", text: "$\\frac{13}{30}$" },{ key: "C", text: "$3$" },{ key: "D", text: "$12$" },{ key: "E", text: "$\\frac{2}{3}$" }],
    answer: "A", solution: "$d\\sin\\theta=n\\lambda\\Rightarrow\\sin\\theta=\\dfrac{n\\lambda}{d}=\\dfrac{1\\cdot2}{6}=\\frac{1}{3}.$" },
  { id: "pat-ex2-070", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "A diffraction grating (consistent units) has $d=8$, wavelength $\\lambda=1$, order $n=2$. Then $\\sin\\theta$ is:",
    options: [{ key: "A", text: "$\\frac{1}{4}$" },{ key: "B", text: "$4$" },{ key: "C", text: "$\\frac{7}{20}$" },{ key: "D", text: "$16$" },{ key: "E", text: "$\\frac{1}{8}$" }],
    answer: "A", solution: "$d\\sin\\theta=n\\lambda\\Rightarrow\\sin\\theta=\\dfrac{n\\lambda}{d}=\\dfrac{2\\cdot1}{8}=\\frac{1}{4}.$" },
  { id: "pat-ex2-071", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "A diffraction grating (consistent units) has $d=6$, wavelength $\\lambda=3$, order $n=1$. Then $\\sin\\theta$ is:",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$1$" },{ key: "C", text: "$18$" },{ key: "D", text: "$\\frac{1}{2}$" },{ key: "E", text: "$\\frac{3}{5}$" }],
    answer: "D", solution: "$d\\sin\\theta=n\\lambda\\Rightarrow\\sin\\theta=\\dfrac{n\\lambda}{d}=\\dfrac{1\\cdot3}{6}=\\frac{1}{2}.$" },
  { id: "pat-ex2-072", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "A diffraction grating (consistent units) has $d=10$, wavelength $\\lambda=2$, order $n=2$. Then $\\sin\\theta$ is:",
    options: [{ key: "A", text: "$\\frac{1}{2}$" },{ key: "B", text: "$\\frac{5}{2}$" },{ key: "C", text: "$40$" },{ key: "D", text: "$\\frac{2}{5}$" },{ key: "E", text: "$\\frac{1}{5}$" }],
    answer: "D", solution: "$d\\sin\\theta=n\\lambda\\Rightarrow\\sin\\theta=\\dfrac{n\\lambda}{d}=\\dfrac{2\\cdot2}{10}=\\frac{2}{5}.$" },
  { id: "pat-ex2-073", type: "mcq", testId: "pat", topicId: "pat-wave", difficulty: 2, marks: 4,
    question: "A diffraction grating (consistent units) has $d=5$, wavelength $\\lambda=4$, order $n=1$. Then $\\sin\\theta$ is:",
    options: [{ key: "A", text: "$\\frac{8}{5}$" },{ key: "B", text: "$\\frac{5}{4}$" },{ key: "C", text: "$20$" },{ key: "D", text: "$\\frac{9}{10}$" },{ key: "E", text: "$\\frac{4}{5}$" }],
    answer: "E", solution: "$d\\sin\\theta=n\\lambda\\Rightarrow\\sin\\theta=\\dfrac{n\\lambda}{d}=\\dfrac{1\\cdot4}{5}=\\frac{4}{5}.$" },
  { id: "pat-ex2-074", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 2, marks: 4,
    question: "At constant pressure a gas has $V_1=2$ at $T_1=300\\,\\text{K}$. At $T_2=600\\,\\text{K}$ its volume is:",
    options: [{ key: "A", text: "$302$" },{ key: "B", text: "$1$" },{ key: "C", text: "$2$" },{ key: "D", text: "$5$" },{ key: "E", text: "$4$" }],
    answer: "E", solution: "Charles: $\\dfrac{V_1}{T_1}=\\dfrac{V_2}{T_2}\\Rightarrow V_2=\\dfrac{2\\cdot600}{300}=4.$" },
  { id: "pat-ex2-075", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 2, marks: 4,
    question: "At constant pressure a gas has $V_1=4$ at $T_1=200\\,\\text{K}$. At $T_2=300\\,\\text{K}$ its volume is:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$\\frac{8}{3}$" },{ key: "C", text: "$104$" },{ key: "D", text: "$6$" },{ key: "E", text: "$\\frac{3}{2}$" }],
    answer: "D", solution: "Charles: $\\dfrac{V_1}{T_1}=\\dfrac{V_2}{T_2}\\Rightarrow V_2=\\dfrac{4\\cdot300}{200}=6.$" },
  { id: "pat-ex2-076", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 2, marks: 4,
    question: "At constant pressure a gas has $V_1=3$ at $T_1=400\\,\\text{K}$. At $T_2=200\\,\\text{K}$ its volume is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$\\frac{1}{2}$" },{ key: "C", text: "$\\frac{3}{2}$" },{ key: "D", text: "$6$" },{ key: "E", text: "$-197$" }],
    answer: "C", solution: "Charles: $\\dfrac{V_1}{T_1}=\\dfrac{V_2}{T_2}\\Rightarrow V_2=\\dfrac{3\\cdot200}{400}=\\frac{3}{2}.$" },
  { id: "pat-ex2-077", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 2, marks: 4,
    question: "At constant pressure a gas has $V_1=1$ at $T_1=250\\,\\text{K}$. At $T_2=500\\,\\text{K}$ its volume is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$251$" },{ key: "C", text: "$2$" },{ key: "D", text: "$1$" },{ key: "E", text: "$\\frac{1}{2}$" }],
    answer: "C", solution: "Charles: $\\dfrac{V_1}{T_1}=\\dfrac{V_2}{T_2}\\Rightarrow V_2=\\dfrac{1\\cdot500}{250}=2.$" },
  { id: "pat-ex2-078", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 2, marks: 4,
    question: "At constant pressure a gas has $V_1=6$ at $T_1=300\\,\\text{K}$. At $T_2=400\\,\\text{K}$ its volume is:",
    options: [{ key: "A", text: "$106$" },{ key: "B", text: "$\\frac{4}{3}$" },{ key: "C", text: "$\\frac{9}{2}$" },{ key: "D", text: "$6$" },{ key: "E", text: "$8$" }],
    answer: "E", solution: "Charles: $\\dfrac{V_1}{T_1}=\\dfrac{V_2}{T_2}\\Rightarrow V_2=\\dfrac{6\\cdot400}{300}=8.$" },
  { id: "pat-ex2-079", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 3, marks: 4,
    question: "A gas goes from $(P_1{=}2,V_1{=}3,T_1{=}300)$ to $(P_2{=}3,T_2{=}600)$. Its new volume $V_2$ is:",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$5$" },{ key: "C", text: "$3$" },{ key: "D", text: "$4$" },{ key: "E", text: "$2$" }],
    answer: "D", solution: "$\\dfrac{P_1V_1}{T_1}=\\dfrac{P_2V_2}{T_2}\\Rightarrow V_2=\\dfrac{P_1V_1T_2}{T_1P_2}=4.$" },
  { id: "pat-ex2-080", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 3, marks: 4,
    question: "A gas goes from $(P_1{=}1,V_1{=}4,T_1{=}200)$ to $(P_2{=}2,T_2{=}300)$. Its new volume $V_2$ is:",
    options: [{ key: "A", text: "$12$" },{ key: "B", text: "$2$" },{ key: "C", text: "$4$" },{ key: "D", text: "$6$" },{ key: "E", text: "$3$" }],
    answer: "E", solution: "$\\dfrac{P_1V_1}{T_1}=\\dfrac{P_2V_2}{T_2}\\Rightarrow V_2=\\dfrac{P_1V_1T_2}{T_1P_2}=3.$" },
  { id: "pat-ex2-081", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 3, marks: 4,
    question: "A gas goes from $(P_1{=}3,V_1{=}2,T_1{=}300)$ to $(P_2{=}1,T_2{=}400)$. Its new volume $V_2$ is:",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$2$" },{ key: "C", text: "$6$" },{ key: "D", text: "$\\frac{8}{9}$" },{ key: "E", text: "$8$" }],
    answer: "E", solution: "$\\dfrac{P_1V_1}{T_1}=\\dfrac{P_2V_2}{T_2}\\Rightarrow V_2=\\dfrac{P_1V_1T_2}{T_1P_2}=8.$" },
  { id: "pat-ex2-082", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "Melting $2\\,\\text{kg}$ of a solid (specific latent heat $L=300\\,\\text{J/kg}$) needs energy:",
    options: [{ key: "A", text: "$300\\,\\text{J}$" },{ key: "B", text: "$600\\,\\text{J}$" },{ key: "C", text: "$302\\,\\text{J}$" },{ key: "D", text: "$\\frac{1}{150}\\,\\text{J}$" },{ key: "E", text: "$1200\\,\\text{J}$" }],
    answer: "B", solution: "$Q=mL=2\\cdot300=600\\,$J." },
  { id: "pat-ex2-083", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "Melting $3\\,\\text{kg}$ of a solid (specific latent heat $L=500\\,\\text{J/kg}$) needs energy:",
    options: [{ key: "A", text: "$\\frac{3}{500}\\,\\text{J}$" },{ key: "B", text: "$750\\,\\text{J}$" },{ key: "C", text: "$1500\\,\\text{J}$" },{ key: "D", text: "$3000\\,\\text{J}$" },{ key: "E", text: "$503\\,\\text{J}$" }],
    answer: "C", solution: "$Q=mL=3\\cdot500=1500\\,$J." },
  { id: "pat-ex2-084", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "Melting $1\\,\\text{kg}$ of a solid (specific latent heat $L=2000\\,\\text{J/kg}$) needs energy:",
    options: [{ key: "A", text: "$2001\\,\\text{J}$" },{ key: "B", text: "$1000\\,\\text{J}$" },{ key: "C", text: "$2000\\,\\text{J}$" },{ key: "D", text: "$4000\\,\\text{J}$" },{ key: "E", text: "$\\frac{1}{2000}\\,\\text{J}$" }],
    answer: "C", solution: "$Q=mL=1\\cdot2000=2000\\,$J." },
  { id: "pat-ex2-085", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "Melting $5\\,\\text{kg}$ of a solid (specific latent heat $L=400\\,\\text{J/kg}$) needs energy:",
    options: [{ key: "A", text: "$2000\\,\\text{J}$" },{ key: "B", text: "$4000\\,\\text{J}$" },{ key: "C", text: "$1000\\,\\text{J}$" },{ key: "D", text: "$405\\,\\text{J}$" },{ key: "E", text: "$\\frac{1}{80}\\,\\text{J}$" }],
    answer: "A", solution: "$Q=mL=5\\cdot400=2000\\,$J." },
  { id: "pat-ex2-086", type: "mcq", testId: "pat", topicId: "pat-thermo", difficulty: 1, marks: 4,
    question: "Melting $4\\,\\text{kg}$ of a solid (specific latent heat $L=250\\,\\text{J/kg}$) needs energy:",
    options: [{ key: "A", text: "$500\\,\\text{J}$" },{ key: "B", text: "$2000\\,\\text{J}$" },{ key: "C", text: "$254\\,\\text{J}$" },{ key: "D", text: "$\\frac{2}{125}\\,\\text{J}$" },{ key: "E", text: "$1000\\,\\text{J}$" }],
    answer: "E", solution: "$Q=mL=4\\cdot250=1000\\,$J." },
  { id: "pat-ex2-087", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "Photons of energy $5\\times10^{-19}\\,\\text{J}$ hit a metal of work function $2\\times10^{-19}\\,\\text{J}$. The maximum photoelectron KE (in $10^{-19}\\,\\text{J}$) is:",
    options: [{ key: "A", text: "$10$" },{ key: "B", text: "$7$" },{ key: "C", text: "$\\frac{5}{2}$" },{ key: "D", text: "$3$" },{ key: "E", text: "$4$" }],
    answer: "D", solution: "$KE_{max}=hf-\\phi=5-2=3\\ (\\times10^{-19}\\,$J$)$." },
  { id: "pat-ex2-088", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "Photons of energy $8\\times10^{-19}\\,\\text{J}$ hit a metal of work function $3\\times10^{-19}\\,\\text{J}$. The maximum photoelectron KE (in $10^{-19}\\,\\text{J}$) is:",
    options: [{ key: "A", text: "$24$" },{ key: "B", text: "$\\frac{8}{3}$" },{ key: "C", text: "$11$" },{ key: "D", text: "$6$" },{ key: "E", text: "$5$" }],
    answer: "E", solution: "$KE_{max}=hf-\\phi=8-3=5\\ (\\times10^{-19}\\,$J$)$." },
  { id: "pat-ex2-089", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "Photons of energy $6\\times10^{-19}\\,\\text{J}$ hit a metal of work function $4\\times10^{-19}\\,\\text{J}$. The maximum photoelectron KE (in $10^{-19}\\,\\text{J}$) is:",
    options: [{ key: "A", text: "$\\frac{3}{2}$" },{ key: "B", text: "$3$" },{ key: "C", text: "$10$" },{ key: "D", text: "$2$" },{ key: "E", text: "$24$" }],
    answer: "D", solution: "$KE_{max}=hf-\\phi=6-4=2\\ (\\times10^{-19}\\,$J$)$." },
  { id: "pat-ex2-090", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "Photons of energy $10\\times10^{-19}\\,\\text{J}$ hit a metal of work function $6\\times10^{-19}\\,\\text{J}$. The maximum photoelectron KE (in $10^{-19}\\,\\text{J}$) is:",
    options: [{ key: "A", text: "$\\frac{5}{3}$" },{ key: "B", text: "$5$" },{ key: "C", text: "$16$" },{ key: "D", text: "$4$" },{ key: "E", text: "$60$" }],
    answer: "D", solution: "$KE_{max}=hf-\\phi=10-6=4\\ (\\times10^{-19}\\,$J$)$." },
  { id: "pat-ex2-091", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "Photons of energy $7\\times10^{-19}\\,\\text{J}$ hit a metal of work function $2\\times10^{-19}\\,\\text{J}$. The maximum photoelectron KE (in $10^{-19}\\,\\text{J}$) is:",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$9$" },{ key: "C", text: "$14$" },{ key: "D", text: "$5$" },{ key: "E", text: "$\\frac{7}{2}$" }],
    answer: "D", solution: "$KE_{max}=hf-\\phi=7-2=5\\ (\\times10^{-19}\\,$J$)$." },
  { id: "pat-ex2-092", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "Using $hc=20$ (in units of $10^{-26}\\,\\text{J·m}$), a photon of wavelength $2\\times10^{-7}\\,\\text{m}$ has energy (in $10^{-19}\\,\\text{J}$):",
    options: [{ key: "A", text: "$11$" },{ key: "B", text: "$40$" },{ key: "C", text: "$\\frac{1}{10}$" },{ key: "D", text: "$10$" },{ key: "E", text: "$22$" }],
    answer: "D", solution: "$E=\\dfrac{hc}{\\lambda}=\\dfrac{20}{2}=10\\ (\\times10^{-19}\\,$J$)$." },
  { id: "pat-ex2-093", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "Using $hc=20$ (in units of $10^{-26}\\,\\text{J·m}$), a photon of wavelength $4\\times10^{-7}\\,\\text{m}$ has energy (in $10^{-19}\\,\\text{J}$):",
    options: [{ key: "A", text: "$\\frac{1}{5}$" },{ key: "B", text: "$6$" },{ key: "C", text: "$5$" },{ key: "D", text: "$80$" },{ key: "E", text: "$24$" }],
    answer: "C", solution: "$E=\\dfrac{hc}{\\lambda}=\\dfrac{20}{4}=5\\ (\\times10^{-19}\\,$J$)$." },
  { id: "pat-ex2-094", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "Using $hc=20$ (in units of $10^{-26}\\,\\text{J·m}$), a photon of wavelength $5\\times10^{-7}\\,\\text{m}$ has energy (in $10^{-19}\\,\\text{J}$):",
    options: [{ key: "A", text: "$100$" },{ key: "B", text: "$5$" },{ key: "C", text: "$4$" },{ key: "D", text: "$\\frac{1}{4}$" },{ key: "E", text: "$25$" }],
    answer: "C", solution: "$E=\\dfrac{hc}{\\lambda}=\\dfrac{20}{5}=4\\ (\\times10^{-19}\\,$J$)$." },
  { id: "pat-ex2-095", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "Using $hc=20$ (in units of $10^{-26}\\,\\text{J·m}$), a photon of wavelength $8\\times10^{-7}\\,\\text{m}$ has energy (in $10^{-19}\\,\\text{J}$):",
    options: [{ key: "A", text: "$\\frac{5}{2}$" },{ key: "B", text: "$\\frac{7}{2}$" },{ key: "C", text: "$\\frac{2}{5}$" },{ key: "D", text: "$28$" },{ key: "E", text: "$160$" }],
    answer: "A", solution: "$E=\\dfrac{hc}{\\lambda}=\\dfrac{20}{8}=\\frac{5}{2}\\ (\\times10^{-19}\\,$J$)$." },
  { id: "pat-ex2-096", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "A sample decays to $\\tfrac1{8}$ of its initial amount. The number of half-lives elapsed is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$6$" },{ key: "C", text: "$8$" },{ key: "D", text: "$2$" },{ key: "E", text: "$4$" }],
    answer: "A", solution: "$\\left(\\tfrac12\\right)^k=\\tfrac1{8}\\Rightarrow k=3.$" },
  { id: "pat-ex2-097", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "A sample decays to $\\tfrac1{16}$ of its initial amount. The number of half-lives elapsed is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$3$" },{ key: "C", text: "$4$" },{ key: "D", text: "$16$" },{ key: "E", text: "$8$" }],
    answer: "C", solution: "$\\left(\\tfrac12\\right)^k=\\tfrac1{16}\\Rightarrow k=4.$" },
  { id: "pat-ex2-098", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "A sample decays to $\\tfrac1{32}$ of its initial amount. The number of half-lives elapsed is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$10$" },{ key: "C", text: "$32$" },{ key: "D", text: "$6$" },{ key: "E", text: "$4$" }],
    answer: "A", solution: "$\\left(\\tfrac12\\right)^k=\\tfrac1{32}\\Rightarrow k=5.$" },
  { id: "pat-ex2-099", type: "mcq", testId: "pat", topicId: "pat-modern", difficulty: 2, marks: 4,
    question: "A sample decays to $\\tfrac1{64}$ of its initial amount. The number of half-lives elapsed is:",
    options: [{ key: "A", text: "$64$" },{ key: "B", text: "$6$" },{ key: "C", text: "$12$" },{ key: "D", text: "$5$" },{ key: "E", text: "$7$" }],
    answer: "B", solution: "$\\left(\\tfrac12\\right)^k=\\tfrac1{64}\\Rightarrow k=6.$" },
  { id: "pat-ex2-100", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "For $f(x)=3 x^{2} - 2 x + 1$, the second derivative $f''(2)$ is:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$9$" },{ key: "C", text: "$6$" },{ key: "D", text: "$10$" },{ key: "E", text: "$7$" }],
    answer: "C", solution: "$f''(x)=6$, so $f''(2)=6.$" },
  { id: "pat-ex2-101", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "For $f(x)=x^{2} - 4$, the second derivative $f''(1)$ is:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$0$" },{ key: "C", text: "$3$" },{ key: "D", text: "$2$" },{ key: "E", text: "$-3$" }],
    answer: "D", solution: "$f''(x)=2$, so $f''(1)=2.$" },
  { id: "pat-ex2-102", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "For $f(x)=2 x^{2} + x$, the second derivative $f''(3)$ is:",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$4$" },{ key: "C", text: "$21$" },{ key: "D", text: "$5$" },{ key: "E", text: "$13$" }],
    answer: "B", solution: "$f''(x)=4$, so $f''(3)=4.$" },
  { id: "pat-ex2-103", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "For $f(x)=x^{2} - 6 x + 2$, the second derivative $f''(2)$ is:",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$-2$" },{ key: "C", text: "$3$" },{ key: "D", text: "$2$" },{ key: "E", text: "$-6$" }],
    answer: "D", solution: "$f''(x)=2$, so $f''(2)=2.$" },
  { id: "pat-ex2-104", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "For $f(x)=4 x^{2} - 1$, the second derivative $f''(1)$ is:",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$16$" },{ key: "C", text: "$3$" },{ key: "D", text: "$6$" },{ key: "E", text: "$8$" }],
    answer: "E", solution: "$f''(x)=8$, so $f''(1)=8.$" },
  { id: "pat-ex2-105", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 3, marks: 4,
    question: "The cosine of the angle between $(3\\,\\mathbf{i}+4\\,\\mathbf{j})$ and $(4\\,\\mathbf{i}+3\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$- \\frac{24}{25}$" },{ key: "B", text: "$\\frac{53}{50}$" },{ key: "C", text: "$24$" },{ key: "D", text: "$\\frac{24}{25}$" },{ key: "E", text: "$\\frac{1}{2}$" }],
    answer: "D", solution: "$\\cos\\theta=\\dfrac{\\mathbf{a}\\cdot\\mathbf{b}}{|\\mathbf{a}||\\mathbf{b}|}=\\frac{24}{25}.$" },
  { id: "pat-ex2-106", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 3, marks: 4,
    question: "The cosine of the angle between $(1\\,\\mathbf{i}+1\\,\\mathbf{j})$ and $(1\\,\\mathbf{i}+-1\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$\\frac{1}{2}$" },{ key: "B", text: "$\\frac{1}{10}$" },{ key: "C", text: "$1$" },{ key: "D", text: "$0$" },{ key: "E", text: "$2$" }],
    answer: "D", solution: "$\\cos\\theta=\\dfrac{\\mathbf{a}\\cdot\\mathbf{b}}{|\\mathbf{a}||\\mathbf{b}|}=0.$" },
  { id: "pat-ex2-107", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 3, marks: 4,
    question: "The cosine of the angle between $(2\\,\\mathbf{i}+0\\,\\mathbf{j})$ and $(0\\,\\mathbf{i}+3\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$\\frac{1}{2}$" },{ key: "C", text: "$6$" },{ key: "D", text: "$\\frac{1}{10}$" },{ key: "E", text: "$1$" }],
    answer: "A", solution: "$\\cos\\theta=\\dfrac{\\mathbf{a}\\cdot\\mathbf{b}}{|\\mathbf{a}||\\mathbf{b}|}=0.$" },
  { id: "pat-ex2-108", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 3, marks: 4,
    question: "The cosine of the angle between $(1\\,\\mathbf{i}+2\\,\\mathbf{j})$ and $(2\\,\\mathbf{i}+4\\,\\mathbf{j})$ is:",
    options: [{ key: "A", text: "$\\frac{11}{10}$" },{ key: "B", text: "$-1$" },{ key: "C", text: "$1$" },{ key: "D", text: "$\\frac{1}{2}$" },{ key: "E", text: "$10$" }],
    answer: "C", solution: "$\\cos\\theta=\\dfrac{\\mathbf{a}\\cdot\\mathbf{b}}{|\\mathbf{a}||\\mathbf{b}|}=1.$" },
  { id: "pat-ex2-109", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "The larger root of $x^{2} - 5 x + 6=0$ is:",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$4$" },{ key: "C", text: "$-3$" },{ key: "D", text: "$3$" },{ key: "E", text: "$2$" }],
    answer: "D", solution: "Factorising/quadratic formula gives roots $2,3$; the larger is $3.$" },
  { id: "pat-ex2-110", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "The larger root of $x^{2} - x - 6=0$ is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$-6$" },{ key: "C", text: "$-3$" },{ key: "D", text: "$-2$" },{ key: "E", text: "$4$" }],
    answer: "A", solution: "Factorising/quadratic formula gives roots $-2,3$; the larger is $3.$" },
  { id: "pat-ex2-111", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "The larger root of $2 x^{2} - 7 x + 3=0$ is:",
    options: [{ key: "A", text: "$\\frac{1}{2}$" },{ key: "B", text: "$-3$" },{ key: "C", text: "$6$" },{ key: "D", text: "$4$" },{ key: "E", text: "$3$" }],
    answer: "E", solution: "Factorising/quadratic formula gives roots $\\frac{1}{2},3$; the larger is $3.$" },
  { id: "pat-ex2-112", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "The larger root of $x^{2} - 4 x + 4=0$ is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$1$" },{ key: "C", text: "$2$" },{ key: "D", text: "$4$" },{ key: "E", text: "$-2$" }],
    answer: "C", solution: "Factorising/quadratic formula gives roots $2,2$; the larger is $2.$" },
  { id: "pat-ex2-113", type: "mcq", testId: "pat", topicId: "pat-math", difficulty: 2, marks: 4,
    question: "The larger root of $x^{2} + x - 12=0$ is:",
    options: [{ key: "A", text: "$-3$" },{ key: "B", text: "$-12$" },{ key: "C", text: "$4$" },{ key: "D", text: "$-4$" },{ key: "E", text: "$3$" }],
    answer: "E", solution: "Factorising/quadratic formula gives roots $-4,3$; the larger is $3.$" },
];
