// STEP 巧思/进阶选择题 —— 洞见来自设计，正确性由 sympy 精确计算+内建二次复核保证。id 前缀 step-cx-*。
import type { MCQQuestion } from "./types";

export const STEP_CLEVER: MCQQuestion[] = [
  { id: "step-cx-001", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\sum_{k=1}^{9}\\frac1{k(k+1)}$.",
    options: [{ key: "A", text: "$\\frac{9}{10}$" },{ key: "B", text: "$\\frac{9}{19}$" },{ key: "C", text: "$\\frac{8}{9}$" },{ key: "D", text: "$1$" },{ key: "E", text: "$\\frac{1}{10}$" }],
    answer: "A", solution: "Telescoping: $\\frac1{k(k+1)}=\\frac1k-\\frac1{k+1}$, so the sum $=1-\\frac1{10}=\\frac{9}{10}.$" },
  { id: "step-cx-002", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\sum_{k=1}^{49}\\frac1{k(k+1)}$.",
    options: [{ key: "A", text: "$\\frac{48}{49}$" },{ key: "B", text: "$\\frac{49}{99}$" },{ key: "C", text: "$\\frac{49}{50}$" },{ key: "D", text: "$\\frac{1}{50}$" },{ key: "E", text: "$1$" }],
    answer: "C", solution: "Telescoping: $\\frac1{k(k+1)}=\\frac1k-\\frac1{k+1}$, so the sum $=1-\\frac1{50}=\\frac{49}{50}.$" },
  { id: "step-cx-003", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\sum_{k=1}^{99}\\frac1{k(k+1)}$.",
    options: [{ key: "A", text: "$\\frac{99}{199}$" },{ key: "B", text: "$\\frac{98}{99}$" },{ key: "C", text: "$1$" },{ key: "D", text: "$\\frac{99}{100}$" },{ key: "E", text: "$\\frac{1}{100}$" }],
    answer: "D", solution: "Telescoping: $\\frac1{k(k+1)}=\\frac1k-\\frac1{k+1}$, so the sum $=1-\\frac1{100}=\\frac{99}{100}.$" },
  { id: "step-cx-004", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\sum_{k=1}^{10}\\frac1{(2k-1)(2k+1)}$.",
    options: [{ key: "A", text: "$\\frac{1}{21}$" },{ key: "B", text: "$\\frac{10}{21}$" },{ key: "C", text: "$\\frac{1}{2}$" },{ key: "D", text: "$\\frac{20}{21}$" },{ key: "E", text: "$\\frac{10}{11}$" }],
    answer: "B", solution: "$\\frac1{(2k-1)(2k+1)}=\\frac12\\!\\left(\\frac1{2k-1}-\\frac1{2k+1}\\right)$; telescopes to $\\frac12(1-\\frac1{21})=\\frac{10}{21}.$" },
  { id: "step-cx-005", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\sum_{k=1}^{50}\\frac1{(2k-1)(2k+1)}$.",
    options: [{ key: "A", text: "$\\frac{1}{2}$" },{ key: "B", text: "$\\frac{100}{101}$" },{ key: "C", text: "$\\frac{50}{51}$" },{ key: "D", text: "$\\frac{50}{101}$" },{ key: "E", text: "$\\frac{1}{101}$" }],
    answer: "D", solution: "$\\frac1{(2k-1)(2k+1)}=\\frac12\\!\\left(\\frac1{2k-1}-\\frac1{2k+1}\\right)$; telescopes to $\\frac12(1-\\frac1{101})=\\frac{50}{101}.$" },
  { id: "step-cx-006", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 2, marks: 20,
    question: "Evaluate $\\displaystyle\\int_{-2}^{2} (x^{3} \\cos{\\left(x \\right)})\\,dx$.",
    options: [{ key: "A", text: "$-1$" },{ key: "B", text: "$2$" },{ key: "C", text: "$0$" },{ key: "D", text: "$4$" },{ key: "E", text: "$1$" }],
    answer: "C", solution: "The integrand is an odd function, and the interval is symmetric about $0$, so the integral is $0$." },
  { id: "step-cx-007", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 2, marks: 20,
    question: "Evaluate $\\displaystyle\\int_{-2}^{2} (x^{5} + x^{3})\\,dx$.",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$-1$" },{ key: "C", text: "$1$" },{ key: "D", text: "$2$" },{ key: "E", text: "$4$" }],
    answer: "A", solution: "The integrand is an odd function, and the interval is symmetric about $0$, so the integral is $0$." },
  { id: "step-cx-008", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 2, marks: 20,
    question: "Evaluate $\\displaystyle\\int_{-2}^{2} (x^{7})\\,dx$.",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$1$" },{ key: "C", text: "$2$" },{ key: "D", text: "$4$" },{ key: "E", text: "$-1$" }],
    answer: "A", solution: "The integrand is an odd function, and the interval is symmetric about $0$, so the integral is $0$." },
  { id: "step-cx-009", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_0^{\\pi/2}\\frac{dx}{1+\\tan^{2}x}$.",
    options: [{ key: "A", text: "$\\frac{\\pi}{6}$" },{ key: "B", text: "$\\frac{\\pi}{3}$" },{ key: "C", text: "$\\frac{\\pi}{2}$" },{ key: "D", text: "$\\pi$" },{ key: "E", text: "$\\frac{\\pi}{4}$" }],
    answer: "E", solution: "By the substitution $x\\to\\frac\\pi2-x$, the integral $I$ satisfies $2I=\\int_0^{\\pi/2}1\\,dx=\\frac\\pi2$, so $I=\\frac\\pi4$." },
  { id: "step-cx-010", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_0^{\\pi/2}\\frac{dx}{1+\\tan^{3}x}$.",
    options: [{ key: "A", text: "$\\frac{\\pi}{2}$" },{ key: "B", text: "$\\pi$" },{ key: "C", text: "$\\frac{\\pi}{6}$" },{ key: "D", text: "$\\frac{\\pi}{4}$" },{ key: "E", text: "$\\frac{\\pi}{3}$" }],
    answer: "D", solution: "By the substitution $x\\to\\frac\\pi2-x$, the integral $I$ satisfies $2I=\\int_0^{\\pi/2}1\\,dx=\\frac\\pi2$, so $I=\\frac\\pi4$." },
  { id: "step-cx-011", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_0^{\\pi/2}\\frac{dx}{1+\\tan^{\\frac{1}{2}}x}$.",
    options: [{ key: "A", text: "$\\frac{\\pi}{6}$" },{ key: "B", text: "$\\frac{\\pi}{2}$" },{ key: "C", text: "$\\pi$" },{ key: "D", text: "$\\frac{\\pi}{4}$" },{ key: "E", text: "$\\frac{\\pi}{3}$" }],
    answer: "D", solution: "By the substitution $x\\to\\frac\\pi2-x$, the integral $I$ satisfies $2I=\\int_0^{\\pi/2}1\\,dx=\\frac\\pi2$, so $I=\\frac\\pi4$." },
  { id: "step-cx-012", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\prod_{k=2}^{5}\\left(1-\\frac1{k^2}\\right)$.",
    options: [{ key: "A", text: "$\\frac{1}{2}$" },{ key: "B", text: "$\\frac{4}{5}$" },{ key: "C", text: "$\\frac{6}{5}$" },{ key: "D", text: "$\\frac{3}{5}$" },{ key: "E", text: "$\\frac{3}{10}$" }],
    answer: "D", solution: "$1-\\frac1{k^2}=\\frac{(k-1)(k+1)}{k^2}$; the product telescopes to $\\frac{N+1}{2N}=\\frac{6}{10}.$" },
  { id: "step-cx-013", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\prod_{k=2}^{10}\\left(1-\\frac1{k^2}\\right)$.",
    options: [{ key: "A", text: "$\\frac{1}{2}$" },{ key: "B", text: "$\\frac{11}{20}$" },{ key: "C", text: "$\\frac{9}{10}$" },{ key: "D", text: "$\\frac{11}{40}$" },{ key: "E", text: "$\\frac{11}{10}$" }],
    answer: "B", solution: "$1-\\frac1{k^2}=\\frac{(k-1)(k+1)}{k^2}$; the product telescopes to $\\frac{N+1}{2N}=\\frac{11}{20}.$" },
  { id: "step-cx-014", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\prod_{k=2}^{20}\\left(1-\\frac1{k^2}\\right)$.",
    options: [{ key: "A", text: "$\\frac{21}{20}$" },{ key: "B", text: "$\\frac{19}{20}$" },{ key: "C", text: "$\\frac{1}{2}$" },{ key: "D", text: "$\\frac{21}{40}$" },{ key: "E", text: "$\\frac{21}{80}$" }],
    answer: "D", solution: "$1-\\frac1{k^2}=\\frac{(k-1)(k+1)}{k^2}$; the product telescopes to $\\frac{N+1}{2N}=\\frac{21}{40}.$" },
  { id: "step-cx-015", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "Evaluate $\\displaystyle\\sum_{k=1}^{10} k^3$.",
    options: [{ key: "A", text: "$3025$" },{ key: "B", text: "$1000$" },{ key: "C", text: "$3026$" },{ key: "D", text: "$3015$" },{ key: "E", text: "$385$" }],
    answer: "A", solution: "$\\sum_{k=1}^{N}k^3=\\left(\\frac{N(N+1)}2\\right)^2=\\left(\\frac{10\\cdot11}2\\right)^2=3025.$" },
  { id: "step-cx-016", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "Evaluate $\\displaystyle\\sum_{k=1}^{15} k^3$.",
    options: [{ key: "A", text: "$14401$" },{ key: "B", text: "$1240$" },{ key: "C", text: "$14400$" },{ key: "D", text: "$3375$" },{ key: "E", text: "$14385$" }],
    answer: "C", solution: "$\\sum_{k=1}^{N}k^3=\\left(\\frac{N(N+1)}2\\right)^2=\\left(\\frac{15\\cdot16}2\\right)^2=14400.$" },
  { id: "step-cx-017", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "Evaluate $\\displaystyle\\sum_{k=1}^{20} k^3$.",
    options: [{ key: "A", text: "$44101$" },{ key: "B", text: "$2870$" },{ key: "C", text: "$44100$" },{ key: "D", text: "$8000$" },{ key: "E", text: "$44080$" }],
    answer: "C", solution: "$\\sum_{k=1}^{N}k^3=\\left(\\frac{N(N+1)}2\\right)^2=\\left(\\frac{20\\cdot21}2\\right)^2=44100.$" },
  { id: "step-cx-018", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "Evaluate $\\displaystyle\\sum_{k=1}^{10} k^2$.",
    options: [{ key: "A", text: "$386$" },{ key: "B", text: "$385$" },{ key: "C", text: "$100$" },{ key: "D", text: "$3025$" },{ key: "E", text: "$55$" }],
    answer: "B", solution: "$\\sum k^2=\\frac{N(N+1)(2N+1)}6=\\frac{10\\cdot11\\cdot21}6=385.$" },
  { id: "step-cx-019", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "Evaluate $\\displaystyle\\sum_{k=1}^{12} k^2$.",
    options: [{ key: "A", text: "$6084$" },{ key: "B", text: "$144$" },{ key: "C", text: "$651$" },{ key: "D", text: "$78$" },{ key: "E", text: "$650$" }],
    answer: "E", solution: "$\\sum k^2=\\frac{N(N+1)(2N+1)}6=\\frac{12\\cdot13\\cdot25}6=650.$" },
  { id: "step-cx-020", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "Evaluate $\\displaystyle\\sum_{k=1}^{20} k^2$.",
    options: [{ key: "A", text: "$400$" },{ key: "B", text: "$210$" },{ key: "C", text: "$2871$" },{ key: "D", text: "$44100$" },{ key: "E", text: "$2870$" }],
    answer: "E", solution: "$\\sum k^2=\\frac{N(N+1)(2N+1)}6=\\frac{20\\cdot21\\cdot41}6=2870.$" },
  { id: "step-cx-021", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\sum_{k=1}^{5} k\\cdot k!$.",
    options: [{ key: "A", text: "$720$" },{ key: "B", text: "$119$" },{ key: "C", text: "$718$" },{ key: "D", text: "$719$" },{ key: "E", text: "$120$" }],
    answer: "D", solution: "Since $k\\cdot k!=(k+1)!-k!$, the sum telescopes to $(N+1)!-1=719.$" },
  { id: "step-cx-022", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\sum_{k=1}^{6} k\\cdot k!$.",
    options: [{ key: "A", text: "$720$" },{ key: "B", text: "$5038$" },{ key: "C", text: "$719$" },{ key: "D", text: "$5040$" },{ key: "E", text: "$5039$" }],
    answer: "E", solution: "Since $k\\cdot k!=(k+1)!-k!$, the sum telescopes to $(N+1)!-1=5039.$" },
  { id: "step-cx-023", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "Evaluate $\\displaystyle\\sum_{k=0}^{8}\\binom{8}{k}$.",
    options: [{ key: "A", text: "$257$" },{ key: "B", text: "$256$" },{ key: "C", text: "$512$" },{ key: "D", text: "$128$" },{ key: "E", text: "$64$" }],
    answer: "B", solution: "$\\sum_{k=0}^{n}\\binom nk=2^n=2^{8}=256$ (put $x=1$ in the binomial theorem)." },
  { id: "step-cx-024", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 1, marks: 20,
    question: "Evaluate $\\displaystyle\\sum_{k=0}^{10}\\binom{10}{k}$.",
    options: [{ key: "A", text: "$512$" },{ key: "B", text: "$1024$" },{ key: "C", text: "$100$" },{ key: "D", text: "$2048$" },{ key: "E", text: "$1025$" }],
    answer: "B", solution: "$\\sum_{k=0}^{n}\\binom nk=2^n=2^{10}=1024$ (put $x=1$ in the binomial theorem)." },
  { id: "step-cx-025", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\sum_{k=0}^{6} k\\binom{6}{k}$.",
    options: [{ key: "A", text: "$96$" },{ key: "B", text: "$192$" },{ key: "C", text: "$193$" },{ key: "D", text: "$64$" },{ key: "E", text: "$384$" }],
    answer: "B", solution: "Differentiating $(1+x)^n$ and setting $x=1$: $\\sum k\\binom nk=n2^{n-1}=6\\cdot2^{5}=192.$" },
  { id: "step-cx-026", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\sum_{k=0}^{8} k\\binom{8}{k}$.",
    options: [{ key: "A", text: "$512$" },{ key: "B", text: "$1025$" },{ key: "C", text: "$256$" },{ key: "D", text: "$1024$" },{ key: "E", text: "$2048$" }],
    answer: "D", solution: "Differentiating $(1+x)^n$ and setting $x=1$: $\\sum k\\binom nk=n2^{n-1}=8\\cdot2^{7}=1024.$" },
  { id: "step-cx-027", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_0^\\infty x^{3} e^{-x}\\,dx$.",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$24$" },{ key: "C", text: "$7$" },{ key: "D", text: "$6$" },{ key: "E", text: "$5$" }],
    answer: "D", solution: "$\\int_0^\\infty x^m e^{-x}dx=m!=6$ (the Gamma integral $\\Gamma(m+1)$)." },
  { id: "step-cx-028", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_0^\\infty x^{4} e^{-x}\\,dx$.",
    options: [{ key: "A", text: "$24$" },{ key: "B", text: "$6$" },{ key: "C", text: "$23$" },{ key: "D", text: "$25$" },{ key: "E", text: "$120$" }],
    answer: "A", solution: "$\\int_0^\\infty x^m e^{-x}dx=m!=24$ (the Gamma integral $\\Gamma(m+1)$)." },
  { id: "step-cx-029", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_0^\\infty x^{5} e^{-x}\\,dx$.",
    options: [{ key: "A", text: "$720$" },{ key: "B", text: "$121$" },{ key: "C", text: "$119$" },{ key: "D", text: "$120$" },{ key: "E", text: "$24$" }],
    answer: "D", solution: "$\\int_0^\\infty x^m e^{-x}dx=m!=120$ (the Gamma integral $\\Gamma(m+1)$)." },
  { id: "step-cx-030", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\sum_{k=0}^{4}\\binom{4}{k}^2$.",
    options: [{ key: "A", text: "$16$" },{ key: "B", text: "$71$" },{ key: "C", text: "$69$" },{ key: "D", text: "$56$" },{ key: "E", text: "$70$" }],
    answer: "E", solution: "By Vandermonde's identity, $\\sum_k\\binom nk^2=\\binom{2n}{n}=\\binom{8}{4}=70.$" },
  { id: "step-cx-031", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\sum_{k=0}^{5}\\binom{5}{k}^2$.",
    options: [{ key: "A", text: "$210$" },{ key: "B", text: "$252$" },{ key: "C", text: "$32$" },{ key: "D", text: "$251$" },{ key: "E", text: "$253$" }],
    answer: "B", solution: "By Vandermonde's identity, $\\sum_k\\binom nk^2=\\binom{2n}{n}=\\binom{10}{5}=252.$" },
  { id: "step-cx-032", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 2, marks: 20,
    question: "For $A=\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}$, the top-right entry of $A^{7}$ is:",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$8$" },{ key: "C", text: "$128$" },{ key: "D", text: "$49$" },{ key: "E", text: "$7$" }],
    answer: "E", solution: "By induction $A^m=\\begin{pmatrix}1&m\\\\0&1\\end{pmatrix}$, so the entry is $m=7.$" },
  { id: "step-cx-033", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 2, marks: 20,
    question: "For $A=\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}$, the top-right entry of $A^{12}$ is:",
    options: [{ key: "A", text: "$13$" },{ key: "B", text: "$144$" },{ key: "C", text: "$12$" },{ key: "D", text: "$1$" },{ key: "E", text: "$4096$" }],
    answer: "C", solution: "By induction $A^m=\\begin{pmatrix}1&m\\\\0&1\\end{pmatrix}$, so the entry is $m=12.$" },
  { id: "step-cx-034", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 2, marks: 20,
    question: "For $A=\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}$, the top-right entry of $A^{20}$ is:",
    options: [{ key: "A", text: "$21$" },{ key: "B", text: "$400$" },{ key: "C", text: "$1048576$" },{ key: "D", text: "$20$" },{ key: "E", text: "$1$" }],
    answer: "D", solution: "By induction $A^m=\\begin{pmatrix}1&m\\\\0&1\\end{pmatrix}$, so the entry is $m=20.$" },
  { id: "step-cx-035", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "For $x>0$, the minimum value of $x+\\dfrac{9}{x}$ is:",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$7$" },{ key: "C", text: "$3$" },{ key: "D", text: "$10$" },{ key: "E", text: "$9$" }],
    answer: "A", solution: "By AM–GM, $x+\\frac{9}x\\ge2\\sqrt{9}=6$, with equality at $x=\\sqrt{9}$." },
  { id: "step-cx-036", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "For $x>0$, the minimum value of $x+\\dfrac{16}{x}$ is:",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$9$" },{ key: "C", text: "$17$" },{ key: "D", text: "$4$" },{ key: "E", text: "$16$" }],
    answer: "A", solution: "By AM–GM, $x+\\frac{16}x\\ge2\\sqrt{16}=8$, with equality at $x=\\sqrt{16}$." },
  { id: "step-cx-037", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 3, marks: 20,
    question: "The positive value of the infinite continued fraction $x=1+\\dfrac1{1+\\dfrac1{1+\\cdots}}$ is:",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$\\frac{1}{2} + \\frac{\\sqrt{5}}{2}$" },{ key: "C", text: "$\\sqrt{2}$" },{ key: "D", text: "$\\frac{1}{2} + \\frac{\\sqrt{3}}{2}$" },{ key: "E", text: "$- \\frac{1}{2} + \\frac{\\sqrt{5}}{2}$" }],
    answer: "B", solution: "It satisfies $x=1+\\frac1x$, i.e. $x^2-x-1=0$, giving $x=\\frac{1+\\sqrt5}2$ (positive root)." },
  { id: "step-cx-038", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 3, marks: 20,
    question: "The value of $\\sqrt{6+\\sqrt{6+\\sqrt{6+\\cdots}}}$ is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$6$" },{ key: "C", text: "$\\sqrt{6}$" },{ key: "D", text: "$4$" },{ key: "E", text: "$2$" }],
    answer: "A", solution: "If $y=\\sqrt{6+y}$ then $y^2-y-6=0$, so $y=\\frac{1+\\sqrt{25}}2=3.$" },
  { id: "step-cx-039", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 3, marks: 20,
    question: "The value of $\\sqrt{12+\\sqrt{12+\\sqrt{12+\\cdots}}}$ is:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$5$" },{ key: "C", text: "$3$" },{ key: "D", text: "$2 \\sqrt{3}$" },{ key: "E", text: "$12$" }],
    answer: "A", solution: "If $y=\\sqrt{12+y}$ then $y^2-y-12=0$, so $y=\\frac{1+\\sqrt{49}}2=4.$" },
  { id: "step-cx-040", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 3, marks: 20,
    question: "If $\\omega$ is a primitive cube root of unity, the value of $(1+\\omega)(1+\\omega^2)$ is:",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$-1$" },{ key: "C", text: "$3$" },{ key: "D", text: "$1$" },{ key: "E", text: "$0$" }],
    answer: "D", solution: "Since $1+\\omega+\\omega^2=0$, $1+\\omega=-\\omega^2$ and $1+\\omega^2=-\\omega$; product $=\\omega^3=1.$" },
  { id: "step-cx-041", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 2, marks: 20,
    question: "If $z=e^{i\\pi/3}$, the value of $z+\\dfrac1z$ is:",
    options: [{ key: "A", text: "$-1$" },{ key: "B", text: "$\\frac{1}{2}$" },{ key: "C", text: "$0$" },{ key: "D", text: "$1$" },{ key: "E", text: "$2$" }],
    answer: "D", solution: "$z+\\frac1z=2\\cos\\frac\\pi3=1$ (real, since $|z|=1$)." },
  { id: "step-cx-042", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 2, marks: 20,
    question: "If $z=e^{i\\pi/4}$, the value of $z+\\dfrac1z$ is:",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$\\sqrt{2}$" },{ key: "C", text: "$1$" },{ key: "D", text: "$- \\sqrt{2}$" },{ key: "E", text: "$1 + \\sqrt{2}$" }],
    answer: "B", solution: "$z+\\frac1z=2\\cos\\frac\\pi4=\\sqrt{2}$ (real, since $|z|=1$)." },
  { id: "step-cx-043", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 2, marks: 20,
    question: "If $z=e^{i\\pi/6}$, the value of $z+\\dfrac1z$ is:",
    options: [{ key: "A", text: "$1 + \\sqrt{3}$" },{ key: "B", text: "$\\sqrt{3}$" },{ key: "C", text: "$- \\sqrt{3}$" },{ key: "D", text: "$0$" },{ key: "E", text: "$1$" }],
    answer: "B", solution: "$z+\\frac1z=2\\cos\\frac\\pi6=\\sqrt{3}$ (real, since $|z|=1$)." },
  { id: "step-cx-044", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 3, marks: 20,
    question: "The number of derangements of $4$ objects (permutations with no fixed point) is:",
    options: [{ key: "A", text: "$12$" },{ key: "B", text: "$9$" },{ key: "C", text: "$8$" },{ key: "D", text: "$24$" },{ key: "E", text: "$10$" }],
    answer: "B", solution: "$D_n=n!\\sum_{r=0}^n\\frac{(-1)^r}{r!}$; for $n=4$, $D_{4}=9$ (nearest integer to $n!/e$)." },
  { id: "step-cx-045", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 3, marks: 20,
    question: "The number of derangements of $5$ objects (permutations with no fixed point) is:",
    options: [{ key: "A", text: "$120$" },{ key: "B", text: "$44$" },{ key: "C", text: "$43$" },{ key: "D", text: "$45$" },{ key: "E", text: "$60$" }],
    answer: "B", solution: "$D_n=n!\\sum_{r=0}^n\\frac{(-1)^r}{r!}$; for $n=5$, $D_{5}=44$ (nearest integer to $n!/e$)." },
  { id: "step-cx-046", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 3, marks: 20,
    question: "The number of derangements of $6$ objects (permutations with no fixed point) is:",
    options: [{ key: "A", text: "$720$" },{ key: "B", text: "$264$" },{ key: "C", text: "$265$" },{ key: "D", text: "$266$" },{ key: "E", text: "$360$" }],
    answer: "C", solution: "$D_n=n!\\sum_{r=0}^n\\frac{(-1)^r}{r!}$; for $n=6$, $D_{6}=265$ (nearest integer to $n!/e$)." },
  { id: "step-cx-047", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_0^1 x^{2}(1-x)^{3}\\,dx$.",
    options: [{ key: "A", text: "$\\frac{1}{30}$" },{ key: "B", text: "$\\frac{1}{60}$" },{ key: "C", text: "$\\frac{1}{6}$" },{ key: "D", text: "$\\frac{1}{12}$" },{ key: "E", text: "$\\frac{7}{60}$" }],
    answer: "B", solution: "$\\int_0^1 x^a(1-x)^b dx=\\frac{a!\\,b!}{(a+b+1)!}=\\frac{1}{60}$ (the Beta integral)." },
  { id: "step-cx-048", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_0^1 x^{3}(1-x)^{2}\\,dx$.",
    options: [{ key: "A", text: "$\\frac{1}{6}$" },{ key: "B", text: "$\\frac{7}{60}$" },{ key: "C", text: "$\\frac{1}{60}$" },{ key: "D", text: "$\\frac{1}{12}$" },{ key: "E", text: "$\\frac{1}{30}$" }],
    answer: "C", solution: "$\\int_0^1 x^a(1-x)^b dx=\\frac{a!\\,b!}{(a+b+1)!}=\\frac{1}{60}$ (the Beta integral)." },
  { id: "step-cx-049", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_0^1 x^{1}(1-x)^{4}\\,dx$.",
    options: [{ key: "A", text: "$\\frac{2}{15}$" },{ key: "B", text: "$\\frac{1}{30}$" },{ key: "C", text: "$\\frac{1}{6}$" },{ key: "D", text: "$\\frac{1}{10}$" },{ key: "E", text: "$\\frac{1}{15}$" }],
    answer: "B", solution: "$\\int_0^1 x^a(1-x)^b dx=\\frac{a!\\,b!}{(a+b+1)!}=\\frac{1}{30}$ (the Beta integral)." },
];
