// STEP 练习题库（可计算选择题扩展）—— sympy 计算答案，天生正确，经独立复核。
// 注：真 STEP 为长证明大题（见 step.ts 的 long 题）；本文件为 STEP 难度的选择题练习。id 前缀 step-ex-*。
import type { MCQQuestion } from "./types";

export const STEP_EXPANSION: MCQQuestion[] = [
  { id: "step-ex-001", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The roots of $x^3 - 6x^2 + 11x - 6=0$ are $\\alpha,\\beta,\\gamma$. The value of $\\alpha^2+\\beta^2+\\gamma^2$ is:",
    options: [{ key: "A", text: "$15$" },{ key: "B", text: "$58$" },{ key: "C", text: "$14$" },{ key: "D", text: "$36$" },{ key: "E", text: "$-22$" }],
    answer: "C", solution: "$\\sum\\alpha^2=(\\sum\\alpha)^2-2\\sum\\alpha\\beta=(6)^2-2(11)=14.$" },
  { id: "step-ex-002", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The roots of $x^3 + 0x^2 - 7x + 6=0$ are $\\alpha,\\beta,\\gamma$. The value of $\\alpha^2+\\beta^2+\\gamma^2$ is:",
    options: [{ key: "A", text: "$-14$" },{ key: "B", text: "$14$" },{ key: "C", text: "$15$" },{ key: "D", text: "$0$" },{ key: "E", text: "$12$" }],
    answer: "B", solution: "$\\sum\\alpha^2=(\\sum\\alpha)^2-2\\sum\\alpha\\beta=(0)^2-2(-7)=14.$" },
  { id: "step-ex-003", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The roots of $x^3 - 3x^2 + 2x + 0=0$ are $\\alpha,\\beta,\\gamma$. The value of $\\alpha^2+\\beta^2+\\gamma^2$ is:",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$-4$" },{ key: "C", text: "$13$" },{ key: "D", text: "$9$" },{ key: "E", text: "$5$" }],
    answer: "E", solution: "$\\sum\\alpha^2=(\\sum\\alpha)^2-2\\sum\\alpha\\beta=(3)^2-2(2)=5.$" },
  { id: "step-ex-004", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The roots of $x^3 - 4x^2 + 5x - 2=0$ are $\\alpha,\\beta,\\gamma$. The value of $\\alpha^2+\\beta^2+\\gamma^2$ is:",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$7$" },{ key: "C", text: "$-10$" },{ key: "D", text: "$26$" },{ key: "E", text: "$16$" }],
    answer: "A", solution: "$\\sum\\alpha^2=(\\sum\\alpha)^2-2\\sum\\alpha\\beta=(4)^2-2(5)=6.$" },
  { id: "step-ex-005", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The roots of $x^3 + 0x^2 - 3x - 2=0$ are $\\alpha,\\beta,\\gamma$. The value of $\\alpha^2+\\beta^2+\\gamma^2$ is:",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$0$" },{ key: "C", text: "$-6$" },{ key: "D", text: "$7$" },{ key: "E", text: "$4$" }],
    answer: "A", solution: "$\\sum\\alpha^2=(\\sum\\alpha)^2-2\\sum\\alpha\\beta=(0)^2-2(-3)=6.$" },
  { id: "step-ex-006", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The roots of $x^3 - 1x^2 - 4x + 4=0$ are $\\alpha,\\beta,\\gamma$. The value of $\\alpha^2+\\beta^2+\\gamma^2$ is:",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$10$" },{ key: "C", text: "$8$" },{ key: "D", text: "$9$" },{ key: "E", text: "$-7$" }],
    answer: "D", solution: "$\\sum\\alpha^2=(\\sum\\alpha)^2-2\\sum\\alpha\\beta=(1)^2-2(-4)=9.$" },
  { id: "step-ex-007", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The roots of $x^3 + 3x^2 + 3x + 1=0$ are $\\alpha,\\beta,\\gamma$. The value of $\\alpha^2+\\beta^2+\\gamma^2$ is:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$-6$" },{ key: "C", text: "$3$" },{ key: "D", text: "$9$" },{ key: "E", text: "$15$" }],
    answer: "C", solution: "$\\sum\\alpha^2=(\\sum\\alpha)^2-2\\sum\\alpha\\beta=(-3)^2-2(3)=3.$" },
  { id: "step-ex-008", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 3, marks: 20,
    question: "For roots $\\alpha,\\beta,\\gamma$ of $x^3 - 6x^2 + 11x - 6=0$, the value of $\\alpha^3+\\beta^3+\\gamma^3$ is:",
    options: [{ key: "A", text: "$39$" },{ key: "B", text: "$18$" },{ key: "C", text: "$33$" },{ key: "D", text: "$36$" },{ key: "E", text: "$216$" }],
    answer: "D", solution: "$\\sum\\alpha^3=e_1^3-3e_1e_2+3e_3=(6)^3-3(6)(11)+3(6)=36.$" },
  { id: "step-ex-009", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 3, marks: 20,
    question: "For roots $\\alpha,\\beta,\\gamma$ of $x^3 - 3x^2 + 2x + 0=0$, the value of $\\alpha^3+\\beta^3+\\gamma^3$ is:",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$9$" },{ key: "C", text: "$12$" },{ key: "D", text: "$6$" },{ key: "E", text: "$27$" }],
    answer: "B", solution: "$\\sum\\alpha^3=e_1^3-3e_1e_2+3e_3=(3)^3-3(3)(2)+3(0)=9.$" },
  { id: "step-ex-010", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 3, marks: 20,
    question: "For roots $\\alpha,\\beta,\\gamma$ of $x^3 - 4x^2 + 5x - 2=0$, the value of $\\alpha^3+\\beta^3+\\gamma^3$ is:",
    options: [{ key: "A", text: "$13$" },{ key: "B", text: "$10$" },{ key: "C", text: "$64$" },{ key: "D", text: "$7$" },{ key: "E", text: "$4$" }],
    answer: "B", solution: "$\\sum\\alpha^3=e_1^3-3e_1e_2+3e_3=(4)^3-3(4)(5)+3(2)=10.$" },
  { id: "step-ex-011", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 3, marks: 20,
    question: "For roots $\\alpha,\\beta,\\gamma$ of $x^3 + 2x^2 - 1x - 2=0$, the value of $\\alpha^3+\\beta^3+\\gamma^3$ is:",
    options: [{ key: "A", text: "$-5$" },{ key: "B", text: "$-14$" },{ key: "C", text: "$-8$" },{ key: "D", text: "$6$" },{ key: "E", text: "$-11$" }],
    answer: "C", solution: "$\\sum\\alpha^3=e_1^3-3e_1e_2+3e_3=(-2)^3-3(-2)(-1)+3(2)=-8.$" },
  { id: "step-ex-012", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 3, marks: 20,
    question: "For roots $\\alpha,\\beta,\\gamma$ of $x^3 - 1x^2 - 4x + 4=0$, the value of $\\alpha^3+\\beta^3+\\gamma^3$ is:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$-2$" },{ key: "C", text: "$-12$" },{ key: "D", text: "$1$" },{ key: "E", text: "$13$" }],
    answer: "D", solution: "$\\sum\\alpha^3=e_1^3-3e_1e_2+3e_3=(1)^3-3(1)(-4)+3(-4)=1.$" },
  { id: "step-ex-013", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The discriminant $-4p^3-27q^2$ of $x^3 - 3x + 2$ equals:",
    options: [{ key: "A", text: "$-108$" },{ key: "B", text: "$-2$" },{ key: "C", text: "$1$" },{ key: "D", text: "$216$" },{ key: "E", text: "$0$" }],
    answer: "E", solution: "$-4(-3)^3-27(2)^2=0.$ (Zero indicates a repeated root.)" },
  { id: "step-ex-014", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The discriminant $-4p^3-27q^2$ of $x^3 - 3x - 2$ equals:",
    options: [{ key: "A", text: "$-2$" },{ key: "B", text: "$0$" },{ key: "C", text: "$216$" },{ key: "D", text: "$1$" },{ key: "E", text: "$-108$" }],
    answer: "B", solution: "$-4(-3)^3-27(-2)^2=0.$ (Zero indicates a repeated root.)" },
  { id: "step-ex-015", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The discriminant $-4p^3-27q^2$ of $x^3 - 1x + 0$ equals:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$2$" },{ key: "C", text: "$-4$" },{ key: "D", text: "$0$" },{ key: "E", text: "$4$" }],
    answer: "E", solution: "$-4(-1)^3-27(0)^2=4.$ (Zero indicates a repeated root.)" },
  { id: "step-ex-016", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The discriminant $-4p^3-27q^2$ of $x^3 + 3x + 1$ equals:",
    options: [{ key: "A", text: "$-135$" },{ key: "B", text: "$-134$" },{ key: "C", text: "$-81$" },{ key: "D", text: "$135$" },{ key: "E", text: "$-137$" }],
    answer: "A", solution: "$-4(3)^3-27(1)^2=-135.$ (Zero indicates a repeated root.)" },
  { id: "step-ex-017", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The discriminant $-4p^3-27q^2$ of $x^3 - 6x + 4$ equals:",
    options: [{ key: "A", text: "$-432$" },{ key: "B", text: "$430$" },{ key: "C", text: "$432$" },{ key: "D", text: "$1296$" },{ key: "E", text: "$433$" }],
    answer: "C", solution: "$-4(-6)^3-27(4)^2=432.$ (Zero indicates a repeated root.)" },
  { id: "step-ex-018", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The discriminant $-4p^3-27q^2$ of $x^3 - 12x + 16$ equals:",
    options: [{ key: "A", text: "$13824$" },{ key: "B", text: "$-6912$" },{ key: "C", text: "$1$" },{ key: "D", text: "$-2$" },{ key: "E", text: "$0$" }],
    answer: "E", solution: "$-4(-12)^3-27(16)^2=0.$ (Zero indicates a repeated root.)" },
  { id: "step-ex-019", type: "mcq", testId: "step", topicId: "step-pure1", difficulty: 2, marks: 20,
    question: "The discriminant $-4p^3-27q^2$ of $x^3 - 7x + 6$ equals:",
    options: [{ key: "A", text: "$2344$" },{ key: "B", text: "$-400$" },{ key: "C", text: "$398$" },{ key: "D", text: "$400$" },{ key: "E", text: "$401$" }],
    answer: "D", solution: "$-4(-7)^3-27(6)^2=400.$ (Zero indicates a repeated root.)" },
  { id: "step-ex-020", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_{0}^{1} x e^{x}\\,dx$.",
    options: [{ key: "A", text: "$2$" },{ key: "B", text: "$\\frac{1}{2}$" },{ key: "C", text: "$1$" },{ key: "D", text: "$0$" },{ key: "E", text: "$\\frac{3}{2}$" }],
    answer: "C", solution: "Integration gives $\\int x e^{x}\\,dx$; evaluating from $0$ to $1$ yields $1$." },
  { id: "step-ex-021", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_{0}^{\\frac{\\pi}{2}} x \\cos{\\left(x \\right)}\\,dx$.",
    options: [{ key: "A", text: "$-1 + \\frac{\\pi}{2}$" },{ key: "B", text: "$-2 + \\frac{\\pi}{2}$" },{ key: "C", text: "$-2 + \\pi$" },{ key: "D", text: "$\\frac{\\pi}{2}$" },{ key: "E", text: "$- \\frac{1}{2} + \\frac{\\pi}{4}$" }],
    answer: "A", solution: "Integration gives $\\int x \\cos{\\left(x \\right)}\\,dx$; evaluating from $0$ to $\\frac{\\pi}{2}$ yields $-1 + \\frac{\\pi}{2}$." },
  { id: "step-ex-022", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_{1}^{e} x \\log{\\left(x \\right)}\\,dx$.",
    options: [{ key: "A", text: "$\\frac{5}{4} + \\frac{e^{2}}{4}$" },{ key: "B", text: "$- \\frac{3}{4} + \\frac{e^{2}}{4}$" },{ key: "C", text: "$\\frac{1}{2} + \\frac{e^{2}}{2}$" },{ key: "D", text: "$\\frac{1}{8} + \\frac{e^{2}}{8}$" },{ key: "E", text: "$\\frac{1}{4} + \\frac{e^{2}}{4}$" }],
    answer: "E", solution: "Integration gives $\\int x \\log{\\left(x \\right)}\\,dx$; evaluating from $1$ to $e$ yields $\\frac{1}{4} + \\frac{e^{2}}{4}$." },
  { id: "step-ex-023", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_{1}^{e} \\log{\\left(x \\right)}\\,dx$.",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$\\frac{3}{2}$" },{ key: "C", text: "$2$" },{ key: "D", text: "$1$" },{ key: "E", text: "$\\frac{1}{2}$" }],
    answer: "D", solution: "Integration gives $\\int \\log{\\left(x \\right)}\\,dx$; evaluating from $1$ to $e$ yields $1$." },
  { id: "step-ex-024", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_{0}^{\\pi} x \\sin{\\left(x \\right)}\\,dx$.",
    options: [{ key: "A", text: "$-1 + \\pi$" },{ key: "B", text: "$\\pi$" },{ key: "C", text: "$1 + \\pi$" },{ key: "D", text: "$\\frac{\\pi}{2}$" },{ key: "E", text: "$2 \\pi$" }],
    answer: "B", solution: "Integration gives $\\int x \\sin{\\left(x \\right)}\\,dx$; evaluating from $0$ to $\\pi$ yields $\\pi$." },
  { id: "step-ex-025", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_{0}^{2} x^{3}\\,dx$.",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$2$" },{ key: "C", text: "$8$" },{ key: "D", text: "$3$" },{ key: "E", text: "$4$" }],
    answer: "E", solution: "Integration gives $\\int x^{3}\\,dx$; evaluating from $0$ to $2$ yields $4$." },
  { id: "step-ex-026", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_{1}^{3} \\frac{1}{x^{2}}\\,dx$.",
    options: [{ key: "A", text: "$\\frac{2}{3}$" },{ key: "B", text: "$\\frac{5}{3}$" },{ key: "C", text: "$\\frac{1}{3}$" },{ key: "D", text: "$- \\frac{1}{3}$" },{ key: "E", text: "$\\frac{4}{3}$" }],
    answer: "A", solution: "Integration gives $\\int \\frac{1}{x^{2}}\\,dx$; evaluating from $1$ to $3$ yields $\\frac{2}{3}$." },
  { id: "step-ex-027", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "Evaluate $\\displaystyle\\int_{0}^{1} e^{2 x}\\,dx$.",
    options: [{ key: "A", text: "$\\frac{1}{2} + \\frac{e^{2}}{2}$" },{ key: "B", text: "$-1 + e^{2}$" },{ key: "C", text: "$- \\frac{3}{2} + \\frac{e^{2}}{2}$" },{ key: "D", text: "$- \\frac{1}{2} + \\frac{e^{2}}{2}$" },{ key: "E", text: "$- \\frac{1}{4} + \\frac{e^{2}}{4}$" }],
    answer: "D", solution: "Integration gives $\\int e^{2 x}\\,dx$; evaluating from $0$ to $1$ yields $- \\frac{1}{2} + \\frac{e^{2}}{2}$." },
  { id: "step-ex-028", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 2, marks: 20,
    question: "The improper integral $\\displaystyle\\int_1^\\infty x^{-3}\\,dx$ equals:",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$\\frac{1}{3}$" },{ key: "C", text: "$2$" },{ key: "D", text: "$3$" },{ key: "E", text: "$\\frac{1}{2}$" }],
    answer: "E", solution: "$\\int_1^\\infty x^{-3}dx=\\left[\\frac{x^{1-3}}{1-3}\\right]_1^\\infty=\\frac{1}{3-1}=\\frac{1}{2}.$" },
  { id: "step-ex-029", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 2, marks: 20,
    question: "The improper integral $\\displaystyle\\int_1^\\infty x^{-4}\\,dx$ equals:",
    options: [{ key: "A", text: "$\\frac{2}{3}$" },{ key: "B", text: "$\\frac{1}{4}$" },{ key: "C", text: "$\\frac{1}{3}$" },{ key: "D", text: "$4$" },{ key: "E", text: "$3$" }],
    answer: "C", solution: "$\\int_1^\\infty x^{-4}dx=\\left[\\frac{x^{1-4}}{1-4}\\right]_1^\\infty=\\frac{1}{4-1}=\\frac{1}{3}.$" },
  { id: "step-ex-030", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 2, marks: 20,
    question: "The improper integral $\\displaystyle\\int_1^\\infty x^{-5}\\,dx$ equals:",
    options: [{ key: "A", text: "$\\frac{1}{2}$" },{ key: "B", text: "$\\frac{1}{4}$" },{ key: "C", text: "$4$" },{ key: "D", text: "$5$" },{ key: "E", text: "$\\frac{1}{5}$" }],
    answer: "B", solution: "$\\int_1^\\infty x^{-5}dx=\\left[\\frac{x^{1-5}}{1-5}\\right]_1^\\infty=\\frac{1}{5-1}=\\frac{1}{4}.$" },
  { id: "step-ex-031", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 2, marks: 20,
    question: "The improper integral $\\displaystyle\\int_1^\\infty x^{-\\frac{3}{2}}\\,dx$ equals:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$\\frac{2}{3}$" },{ key: "C", text: "$\\frac{1}{2}$" },{ key: "D", text: "$\\frac{3}{2}$" },{ key: "E", text: "$2$" }],
    answer: "E", solution: "$\\int_1^\\infty x^{-\\frac{3}{2}}dx=\\left[\\frac{x^{1-\\frac{3}{2}}}{1-\\frac{3}{2}}\\right]_1^\\infty=\\frac{1}{\\frac{3}{2}-1}=2.$" },
  { id: "step-ex-032", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 2, marks: 20,
    question: "The improper integral $\\displaystyle\\int_1^\\infty x^{-\\frac{5}{2}}\\,dx$ equals:",
    options: [{ key: "A", text: "$\\frac{2}{3}$" },{ key: "B", text: "$\\frac{4}{3}$" },{ key: "C", text: "$\\frac{2}{5}$" },{ key: "D", text: "$\\frac{5}{2}$" },{ key: "E", text: "$\\frac{3}{2}$" }],
    answer: "A", solution: "$\\int_1^\\infty x^{-\\frac{5}{2}}dx=\\left[\\frac{x^{1-\\frac{5}{2}}}{1-\\frac{5}{2}}\\right]_1^\\infty=\\frac{1}{\\frac{5}{2}-1}=\\frac{2}{3}.$" },
  { id: "step-ex-033", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "The value of $\\displaystyle\\int_0^{\\pi/2}\\sin^{2} x\\,dx$ is:",
    options: [{ key: "A", text: "$\\frac{1}{7} + \\frac{\\pi}{4}$" },{ key: "B", text: "$\\frac{\\pi}{2}$" },{ key: "C", text: "$\\frac{\\pi}{8}$" },{ key: "D", text: "$\\frac{\\pi}{4}$" },{ key: "E", text: "$\\frac{1}{3} + \\frac{\\pi}{4}$" }],
    answer: "D", solution: "By the reduction formula $I_n=\\frac{n-1}{n}I_{n-2}$, $I_{2}=\\frac{\\pi}{4}.$" },
  { id: "step-ex-034", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "The value of $\\displaystyle\\int_0^{\\pi/2}\\sin^{3} x\\,dx$ is:",
    options: [{ key: "A", text: "$\\frac{4}{3}$" },{ key: "B", text: "$\\frac{45 \\cdot 2^{\\frac{46}{389}} \\cdot 3^{\\frac{122}{389}} \\cdot 5^{\\frac{365}{389}} \\cdot 7^{\\frac{232}{389}}}{686}$" },{ key: "C", text: "$\\frac{1}{3}$" },{ key: "D", text: "$\\frac{2}{3}$" },{ key: "E", text: "$1$" }],
    answer: "D", solution: "By the reduction formula $I_n=\\frac{n-1}{n}I_{n-2}$, $I_{3}=\\frac{2}{3}.$" },
  { id: "step-ex-035", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "The value of $\\displaystyle\\int_0^{\\pi/2}\\sin^{4} x\\,dx$ is:",
    options: [{ key: "A", text: "$\\frac{7 \\pi}{16}$" },{ key: "B", text: "$\\frac{1}{3} + \\frac{3 \\pi}{16}$" },{ key: "C", text: "$\\frac{3 \\pi}{16}$" },{ key: "D", text: "$\\frac{3 \\pi}{8}$" },{ key: "E", text: "$\\frac{3 \\pi}{32}$" }],
    answer: "C", solution: "By the reduction formula $I_n=\\frac{n-1}{n}I_{n-2}$, $I_{4}=\\frac{3 \\pi}{16}.$" },
  { id: "step-ex-036", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "The value of $\\displaystyle\\int_0^{\\pi/2}\\sin^{5} x\\,dx$ is:",
    options: [{ key: "A", text: "$\\frac{13}{15}$" },{ key: "B", text: "$\\frac{16}{15}$" },{ key: "C", text: "$\\frac{8}{15}$" },{ key: "D", text: "$\\frac{8}{15} + \\frac{\\pi}{4}$" },{ key: "E", text: "$\\frac{4}{15}$" }],
    answer: "C", solution: "By the reduction formula $I_n=\\frac{n-1}{n}I_{n-2}$, $I_{5}=\\frac{8}{15}.$" },
  { id: "step-ex-037", type: "mcq", testId: "step", topicId: "step-pure2", difficulty: 3, marks: 20,
    question: "The value of $\\displaystyle\\int_0^{\\pi/2}\\sin^{6} x\\,dx$ is:",
    options: [{ key: "A", text: "$\\frac{1}{3} + \\frac{5 \\pi}{32}$" },{ key: "B", text: "$\\frac{5 \\pi}{32}$" },{ key: "C", text: "$\\frac{5 \\pi}{16}$" },{ key: "D", text: "$\\frac{8 \\cdot 2^{\\frac{87}{226}} \\cdot 3^{\\frac{19}{113}} \\cdot 5^{\\frac{88}{113}} \\cdot 7^{\\frac{35}{113}}}{63}$" },{ key: "E", text: "$\\frac{5 \\pi}{64}$" }],
    answer: "B", solution: "By the reduction formula $I_n=\\frac{n-1}{n}I_{n-2}$, $I_{6}=\\frac{5 \\pi}{32}.$" },
  { id: "step-ex-038", type: "mcq", testId: "step", topicId: "step-pure3", difficulty: 2, marks: 20,
    question: "The area swept by the polar curve $r=3$ from $\\theta=0$ to $\\theta=\\pi$ is:",
    options: [{ key: "A", text: "$9 \\pi$" },{ key: "B", text: "$\\frac{9 \\pi}{2}$" },{ key: "C", text: "$\\frac{3 \\pi}{2}$" },{ key: "D", text: "$3 \\pi$" },{ key: "E", text: "$\\frac{11 \\pi}{2}$" }],
    answer: "B", solution: "$A=\\int_0^{\\pi}\\tfrac12 r^2\\,d\\theta=\\tfrac12(3)^2(\\pi)=\\frac{9 \\pi}{2}.$" },
  { id: "step-ex-039", type: "mcq", testId: "step", topicId: "step-pure3", difficulty: 2, marks: 20,
    question: "The area between $y=x^{2}$ and the $x$-axis from $x=0$ to $x=3$ (taking the definite integral) is:",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$\\frac{9}{2}$" },{ key: "C", text: "$10$" },{ key: "D", text: "$18$" },{ key: "E", text: "$9$" }],
    answer: "E", solution: "$\\int_{0}^{3}x^{2}\\,dx=9.$" },
  { id: "step-ex-040", type: "mcq", testId: "step", topicId: "step-pure3", difficulty: 2, marks: 20,
    question: "The area between $y=\\sqrt{x}$ and the $x$-axis from $x=0$ to $x=4$ (taking the definite integral) is:",
    options: [{ key: "A", text: "$\\frac{16}{3}$" },{ key: "B", text: "$\\frac{13}{3}$" },{ key: "C", text: "$\\frac{8}{3}$" },{ key: "D", text: "$\\frac{32}{3}$" },{ key: "E", text: "$\\frac{19}{3}$" }],
    answer: "A", solution: "$\\int_{0}^{4}\\sqrt{x}\\,dx=\\frac{16}{3}.$" },
  { id: "step-ex-041", type: "mcq", testId: "step", topicId: "step-pure3", difficulty: 2, marks: 20,
    question: "The area between $y=\\frac{1}{x}$ and the $x$-axis from $x=1$ to $x=e$ (taking the definite integral) is:",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$0$" },{ key: "C", text: "$2$" },{ key: "D", text: "$\\frac{3}{2}$" },{ key: "E", text: "$\\frac{1}{2}$" }],
    answer: "A", solution: "$\\int_{1}^{e}\\frac{1}{x}\\,dx=1.$" },
  { id: "step-ex-042", type: "mcq", testId: "step", topicId: "step-pure3", difficulty: 2, marks: 20,
    question: "The area between $y=\\sin{\\left(x \\right)}$ and the $x$-axis from $x=0$ to $x=\\pi$ (taking the definite integral) is:",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$3$" },{ key: "C", text: "$2$" },{ key: "D", text: "$4$" },{ key: "E", text: "$\\frac{5}{2}$" }],
    answer: "C", solution: "$\\int_{0}^{\\pi}\\sin{\\left(x \\right)}\\,dx=2.$" },
  { id: "step-ex-043", type: "mcq", testId: "step", topicId: "step-pure3", difficulty: 2, marks: 20,
    question: "The area between $y=x^{3} - x$ and the $x$-axis from $x=0$ to $x=1$ (taking the definite integral) is:",
    options: [{ key: "A", text: "$- \\frac{1}{4}$" },{ key: "B", text: "$- \\frac{1}{2}$" },{ key: "C", text: "$- \\frac{1}{8}$" },{ key: "D", text: "$- \\frac{5}{4}$" },{ key: "E", text: "$\\frac{3}{4}$" }],
    answer: "A", solution: "$\\int_{0}^{1}x^{3} - x\\,dx=- \\frac{1}{4}.$" },
  { id: "step-ex-044", type: "mcq", testId: "step", topicId: "step-pure3", difficulty: 3, marks: 20,
    question: "The arc length of $y=2x$ from $x=0$ to $x=3$ is:",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$6$" },{ key: "C", text: "$3$" },{ key: "D", text: "$3 \\sqrt{5}$" },{ key: "E", text: "$6 \\sqrt{5}$" }],
    answer: "D", solution: "$L=\\int_0^3\\sqrt{1+(2)^2}\\,dx=(3)\\sqrt{5}=3 \\sqrt{5}.$" },
  { id: "step-ex-045", type: "mcq", testId: "step", topicId: "step-pure3", difficulty: 3, marks: 20,
    question: "The arc length of $y=3x$ from $x=1$ to $x=4$ is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$3 \\sqrt{10}$" },{ key: "C", text: "$6 \\sqrt{10}$" },{ key: "D", text: "$12$" },{ key: "E", text: "$9$" }],
    answer: "B", solution: "$L=\\int_1^4\\sqrt{1+(3)^2}\\,dx=(3)\\sqrt{10}=3 \\sqrt{10}.$" },
  { id: "step-ex-046", type: "mcq", testId: "step", topicId: "step-pure3", difficulty: 3, marks: 20,
    question: "The arc length of $y=1x$ from $x=0$ to $x=5$ is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$1 + 5 \\sqrt{2}$" },{ key: "C", text: "$10 \\sqrt{2}$" },{ key: "D", text: "$5 \\sqrt{2}$" },{ key: "E", text: "$10$" }],
    answer: "D", solution: "$L=\\int_0^5\\sqrt{1+(1)^2}\\,dx=(5)\\sqrt{2}=5 \\sqrt{2}.$" },
  { id: "step-ex-047", type: "mcq", testId: "step", topicId: "step-pure3", difficulty: 3, marks: 20,
    question: "The arc length of $y=4x$ from $x=0$ to $x=2$ is:",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$2 \\sqrt{17}$" },{ key: "C", text: "$4 \\sqrt{17}$" },{ key: "D", text: "$2$" },{ key: "E", text: "$10$" }],
    answer: "B", solution: "$L=\\int_0^2\\sqrt{1+(4)^2}\\,dx=(2)\\sqrt{17}=2 \\sqrt{17}.$" },
  { id: "step-ex-048", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 2, marks: 20,
    question: "The modulus $|(1+i)^{4}|$ equals:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$16$" },{ key: "C", text: "$4 \\sqrt{2}$" },{ key: "D", text: "$8$" },{ key: "E", text: "$5$" }],
    answer: "A", solution: "$|1+i|=\\sqrt2$, so $|(1+i)^{4}|=(\\sqrt2)^{4}=4.$" },
  { id: "step-ex-049", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 2, marks: 20,
    question: "The modulus $|(1+i)^{6}|$ equals:",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$8$" },{ key: "C", text: "$8 \\sqrt{2}$" },{ key: "D", text: "$16$" },{ key: "E", text: "$64$" }],
    answer: "B", solution: "$|1+i|=\\sqrt2$, so $|(1+i)^{6}|=(\\sqrt2)^{6}=8.$" },
  { id: "step-ex-050", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 2, marks: 20,
    question: "The modulus $|(1+i)^{8}|$ equals:",
    options: [{ key: "A", text: "$17$" },{ key: "B", text: "$256$" },{ key: "C", text: "$32$" },{ key: "D", text: "$16$" },{ key: "E", text: "$16 \\sqrt{2}$" }],
    answer: "D", solution: "$|1+i|=\\sqrt2$, so $|(1+i)^{8}|=(\\sqrt2)^{8}=16.$" },
  { id: "step-ex-051", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 2, marks: 20,
    question: "The modulus $|(1+i)^{10}|$ equals:",
    options: [{ key: "A", text: "$32$" },{ key: "B", text: "$64$" },{ key: "C", text: "$1024$" },{ key: "D", text: "$32 \\sqrt{2}$" },{ key: "E", text: "$33$" }],
    answer: "A", solution: "$|1+i|=\\sqrt2$, so $|(1+i)^{10}|=(\\sqrt2)^{10}=32.$" },
  { id: "step-ex-052", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 2, marks: 20,
    question: "The modulus $|(1+i)^{3}|$ equals:",
    options: [{ key: "A", text: "$1 + 2 \\sqrt{2}$" },{ key: "B", text: "$4$" },{ key: "C", text: "$8$" },{ key: "D", text: "$2 \\sqrt{2}$" },{ key: "E", text: "$4 \\sqrt{2}$" }],
    answer: "D", solution: "$|1+i|=\\sqrt2$, so $|(1+i)^{3}|=(\\sqrt2)^{3}=2 \\sqrt{2}.$" },
  { id: "step-ex-053", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 2, marks: 20,
    question: "The modulus $|(1+i)^{5}|$ equals:",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$4 \\sqrt{2}$" },{ key: "C", text: "$32$" },{ key: "D", text: "$8 \\sqrt{2}$" },{ key: "E", text: "$1 + 4 \\sqrt{2}$" }],
    answer: "B", solution: "$|1+i|=\\sqrt2$, so $|(1+i)^{5}|=(\\sqrt2)^{5}=4 \\sqrt{2}.$" },
  { id: "step-ex-054", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 3, marks: 20,
    question: "The sum of all the $n$-th roots of unity for $n=3$ is:",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$3$" },{ key: "C", text: "$1$" },{ key: "D", text: "$-1$" },{ key: "E", text: "$2$" }],
    answer: "A", solution: "The $n$-th roots of unity are roots of $z^{3}-1=0$; by Vieta their sum (coefficient of $z^{2}$ is $0$) is $0$." },
  { id: "step-ex-055", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 3, marks: 20,
    question: "The sum of all the $n$-th roots of unity for $n=4$ is:",
    options: [{ key: "A", text: "$0$" },{ key: "B", text: "$-1$" },{ key: "C", text: "$3$" },{ key: "D", text: "$4$" },{ key: "E", text: "$1$" }],
    answer: "A", solution: "The $n$-th roots of unity are roots of $z^{4}-1=0$; by Vieta their sum (coefficient of $z^{3}$ is $0$) is $0$." },
  { id: "step-ex-056", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 3, marks: 20,
    question: "The sum of all the $n$-th roots of unity for $n=5$ is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$4$" },{ key: "C", text: "$-1$" },{ key: "D", text: "$0$" },{ key: "E", text: "$1$" }],
    answer: "D", solution: "The $n$-th roots of unity are roots of $z^{5}-1=0$; by Vieta their sum (coefficient of $z^{4}$ is $0$) is $0$." },
  { id: "step-ex-057", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 3, marks: 20,
    question: "The sum of all the $n$-th roots of unity for $n=6$ is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$1$" },{ key: "C", text: "$-1$" },{ key: "D", text: "$0$" },{ key: "E", text: "$6$" }],
    answer: "D", solution: "The $n$-th roots of unity are roots of $z^{6}-1=0$; by Vieta their sum (coefficient of $z^{5}$ is $0$) is $0$." },
  { id: "step-ex-058", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 3, marks: 20,
    question: "The sum of all the $n$-th roots of unity for $n=7$ is:",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$0$" },{ key: "C", text: "$-1$" },{ key: "D", text: "$6$" },{ key: "E", text: "$1$" }],
    answer: "B", solution: "The $n$-th roots of unity are roots of $z^{7}-1=0$; by Vieta their sum (coefficient of $z^{6}$ is $0$) is $0$." },
  { id: "step-ex-059", type: "mcq", testId: "step", topicId: "step-pure4", difficulty: 3, marks: 20,
    question: "Using De Moivre, the real part of $(\\cos\\tfrac{1\\pi}{3}+i\\sin\\tfrac{1\\pi}{3})^{2}$ is:",
    options: [{ key: "A", text: "$\\frac{\\sqrt{3}}{2}$" },{ key: "B", text: "$-1$" },{ key: "C", text: "$- \\frac{1}{2}$" },{ key: "D", text: "$\\frac{1}{2}$" },{ key: "E", text: "$- \\frac{3}{2}$" }],
    answer: "C", solution: "$(\\cos\\theta+i\\sin\\theta)^{2}=\\cos 2\\theta+i\\sin 2\\theta$; real part $=\\cos(2\\cdot\\tfrac{1\\pi}{3})=- \\frac{1}{2}.$" },
  { id: "step-ex-060", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 1, marks: 20,
    question: "The determinant of $\\begin{pmatrix}2&1\\\\3&4\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$2$" },{ key: "C", text: "$3$" },{ key: "D", text: "$11$" },{ key: "E", text: "$5$" }],
    answer: "E", solution: "$\\det=ad-bc=(2)(4)-(1)(3)=5.$" },
  { id: "step-ex-061", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 1, marks: 20,
    question: "The determinant of $\\begin{pmatrix}1&2\\\\3&4\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$-4$" },{ key: "B", text: "$-2$" },{ key: "C", text: "$-5$" },{ key: "D", text: "$10$" },{ key: "E", text: "$-1$" }],
    answer: "B", solution: "$\\det=ad-bc=(1)(4)-(2)(3)=-2.$" },
  { id: "step-ex-062", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 1, marks: 20,
    question: "The determinant of $\\begin{pmatrix}5&2\\\\1&3\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$11$" },{ key: "B", text: "$17$" },{ key: "C", text: "$-1$" },{ key: "D", text: "$13$" },{ key: "E", text: "$14$" }],
    answer: "D", solution: "$\\det=ad-bc=(5)(3)-(2)(1)=13.$" },
  { id: "step-ex-063", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 1, marks: 20,
    question: "The determinant of $\\begin{pmatrix}2&0\\\\1&6\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$13$" },{ key: "B", text: "$10$" },{ key: "C", text: "$7$" },{ key: "D", text: "$2$" },{ key: "E", text: "$12$" }],
    answer: "E", solution: "$\\det=ad-bc=(2)(6)-(0)(1)=12.$" },
  { id: "step-ex-064", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 1, marks: 20,
    question: "The determinant of $\\begin{pmatrix}3&3\\\\1&2\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$3$" },{ key: "C", text: "$4$" },{ key: "D", text: "$1$" },{ key: "E", text: "$-3$" }],
    answer: "B", solution: "$\\det=ad-bc=(3)(2)-(3)(1)=3.$" },
  { id: "step-ex-065", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 1, marks: 20,
    question: "The determinant of $\\begin{pmatrix}4&1\\\\2&5\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$18$" },{ key: "B", text: "$22$" },{ key: "C", text: "$16$" },{ key: "D", text: "$19$" },{ key: "E", text: "$3$" }],
    answer: "A", solution: "$\\det=ad-bc=(4)(5)-(1)(2)=18.$" },
  { id: "step-ex-066", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 1, marks: 20,
    question: "The determinant of $\\begin{pmatrix}1&-2\\\\3&1\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$1$" },{ key: "C", text: "$-5$" },{ key: "D", text: "$8$" },{ key: "E", text: "$5$" }],
    answer: "A", solution: "$\\det=ad-bc=(1)(1)-(-2)(3)=7.$" },
  { id: "step-ex-067", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 3, marks: 20,
    question: "The larger eigenvalue of $\\begin{pmatrix}2&0\\\\0&3\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$6$" },{ key: "C", text: "$5$" },{ key: "D", text: "$2$" },{ key: "E", text: "$4$" }],
    answer: "A", solution: "Solve $\\det(M-\\lambda I)=0$: $\\lambda^2-(5)\\lambda+(6)=0$; larger root $=3.$" },
  { id: "step-ex-068", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 3, marks: 20,
    question: "The larger eigenvalue of $\\begin{pmatrix}4&1\\\\2&3\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$2$" },{ key: "C", text: "$6$" },{ key: "D", text: "$5$" },{ key: "E", text: "$10$" }],
    answer: "D", solution: "Solve $\\det(M-\\lambda I)=0$: $\\lambda^2-(7)\\lambda+(10)=0$; larger root $=5.$" },
  { id: "step-ex-069", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 3, marks: 20,
    question: "The larger eigenvalue of $\\begin{pmatrix}3&1\\\\0&2\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$5$" },{ key: "C", text: "$3$" },{ key: "D", text: "$6$" },{ key: "E", text: "$2$" }],
    answer: "C", solution: "Solve $\\det(M-\\lambda I)=0$: $\\lambda^2-(5)\\lambda+(6)=0$; larger root $=3.$" },
  { id: "step-ex-070", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 3, marks: 20,
    question: "The larger eigenvalue of $\\begin{pmatrix}5&2\\\\2&5\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$21$" },{ key: "C", text: "$8$" },{ key: "D", text: "$10$" },{ key: "E", text: "$3$" }],
    answer: "A", solution: "Solve $\\det(M-\\lambda I)=0$: $\\lambda^2-(10)\\lambda+(21)=0$; larger root $=7.$" },
  { id: "step-ex-071", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 3, marks: 20,
    question: "The larger eigenvalue of $\\begin{pmatrix}6&2\\\\1&3\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$\\frac{9}{2} - \\frac{\\sqrt{17}}{2}$" },{ key: "C", text: "$\\frac{\\sqrt{17}}{2} + \\frac{11}{2}$" },{ key: "D", text: "$16$" },{ key: "E", text: "$\\frac{\\sqrt{17}}{2} + \\frac{9}{2}$" }],
    answer: "E", solution: "Solve $\\det(M-\\lambda I)=0$: $\\lambda^2-(9)\\lambda+(16)=0$; larger root $=\\frac{\\sqrt{17}}{2} + \\frac{9}{2}.$" },
  { id: "step-ex-072", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 2, marks: 20,
    question: "The determinant of $\\begin{pmatrix}1&1&0\\\\0&2&1\\\\0&0&3\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$3$" },{ key: "B", text: "$6$" },{ key: "C", text: "$7$" },{ key: "D", text: "$4$" },{ key: "E", text: "$2$" }],
    answer: "B", solution: "For an upper-triangular matrix the determinant is the product of the diagonal: $1\\cdot2\\cdot3=6.$" },
  { id: "step-ex-073", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 2, marks: 20,
    question: "The determinant of $\\begin{pmatrix}2&1&0\\\\0&1&1\\\\0&0&4\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$8$" },{ key: "C", text: "$7$" },{ key: "D", text: "$6$" },{ key: "E", text: "$2$" }],
    answer: "B", solution: "For an upper-triangular matrix the determinant is the product of the diagonal: $2\\cdot1\\cdot4=8.$" },
  { id: "step-ex-074", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 2, marks: 20,
    question: "The determinant of $\\begin{pmatrix}1&1&0\\\\0&1&1\\\\0&0&5\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$5$" },{ key: "C", text: "$3$" },{ key: "D", text: "$7$" },{ key: "E", text: "$1$" }],
    answer: "B", solution: "For an upper-triangular matrix the determinant is the product of the diagonal: $1\\cdot1\\cdot5=5.$" },
  { id: "step-ex-075", type: "mcq", testId: "step", topicId: "step-pure5", difficulty: 2, marks: 20,
    question: "The determinant of $\\begin{pmatrix}2&1&0\\\\0&3&1\\\\0&0&2\\end{pmatrix}$ is:",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$7$" },{ key: "C", text: "$10$" },{ key: "D", text: "$12$" },{ key: "E", text: "$13$" }],
    answer: "D", solution: "For an upper-triangular matrix the determinant is the product of the diagonal: $2\\cdot3\\cdot2=12.$" },
  { id: "step-ex-076", type: "mcq", testId: "step", topicId: "step-mech", difficulty: 2, marks: 20,
    question: "A particle is projected vertically upward at $30\\,\\text{m/s}$ ($g=10$). The greatest height reached is:",
    options: [{ key: "A", text: "$\\frac{45}{2}$" },{ key: "B", text: "$90$" },{ key: "C", text: "$45$" },{ key: "D", text: "$50$" },{ key: "E", text: "$30$" }],
    answer: "C", solution: "$h=\\frac{u^2}{2g}=\\frac{30^2}{20}=45$ m." },
  { id: "step-ex-077", type: "mcq", testId: "step", topicId: "step-mech", difficulty: 2, marks: 20,
    question: "A particle is projected vertically upward at $25\\,\\text{m/s}$ ($g=10$). The greatest height reached is:",
    options: [{ key: "A", text: "$25$" },{ key: "B", text: "$\\frac{125}{4}$" },{ key: "C", text: "$\\frac{125}{2}$" },{ key: "D", text: "$\\frac{145}{4}$" },{ key: "E", text: "$\\frac{125}{8}$" }],
    answer: "B", solution: "$h=\\frac{u^2}{2g}=\\frac{25^2}{20}=\\frac{125}{4}$ m." },
  { id: "step-ex-078", type: "mcq", testId: "step", topicId: "step-mech", difficulty: 2, marks: 20,
    question: "Mass $3\\,\\text{kg}$ at $8\\,\\text{m/s}$ collides and coalesces with a stationary $1\\,\\text{kg}$ mass. Their common speed is:",
    options: [{ key: "A", text: "$24$" },{ key: "B", text: "$6$" },{ key: "C", text: "$7$" },{ key: "D", text: "$4$" },{ key: "E", text: "$8$" }],
    answer: "B", solution: "Momentum: $v=\\frac{m_1u_1}{m_1+m_2}=6$ m/s." },
  { id: "step-ex-079", type: "mcq", testId: "step", topicId: "step-mech", difficulty: 2, marks: 20,
    question: "Mass $1\\,\\text{kg}$ at $10\\,\\text{m/s}$ collides and coalesces with a stationary $4\\,\\text{kg}$ mass. Their common speed is:",
    options: [{ key: "A", text: "$\\frac{5}{2}$" },{ key: "B", text: "$3$" },{ key: "C", text: "$5$" },{ key: "D", text: "$10$" },{ key: "E", text: "$2$" }],
    answer: "E", solution: "Momentum: $v=\\frac{m_1u_1}{m_1+m_2}=2$ m/s." },
  { id: "step-ex-080", type: "mcq", testId: "step", topicId: "step-mech", difficulty: 3, marks: 20,
    question: "A particle in SHM has amplitude $2\\,\\text{m}$ and angular frequency $3\\,\\text{rad/s}$. Its maximum speed is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$\\frac{2}{3}$" },{ key: "C", text: "$6$" },{ key: "D", text: "$7$" },{ key: "E", text: "$18$" }],
    answer: "C", solution: "Maximum speed $=a\\omega=2\\times3=6$ m/s." },
  { id: "step-ex-081", type: "mcq", testId: "step", topicId: "step-mech", difficulty: 3, marks: 20,
    question: "A particle in SHM has amplitude $4\\,\\text{m}$ and angular frequency $2\\,\\text{rad/s}$. Its maximum speed is:",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$8$" },{ key: "C", text: "$16$" },{ key: "D", text: "$2$" },{ key: "E", text: "$9$" }],
    answer: "B", solution: "Maximum speed $=a\\omega=4\\times2=8$ m/s." },
  { id: "step-ex-082", type: "mcq", testId: "step", topicId: "step-mech", difficulty: 3, marks: 20,
    question: "A particle in SHM has amplitude $3\\,\\text{m}$ and angular frequency $2\\,\\text{rad/s}$. Its maximum speed is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$\\frac{3}{2}$" },{ key: "C", text: "$6$" },{ key: "D", text: "$12$" },{ key: "E", text: "$7$" }],
    answer: "C", solution: "Maximum speed $=a\\omega=3\\times2=6$ m/s." },
  { id: "step-ex-083", type: "mcq", testId: "step", topicId: "step-mech", difficulty: 3, marks: 20,
    question: "A particle in SHM has amplitude $5\\,\\text{m}$ and angular frequency $4\\,\\text{rad/s}$. Its maximum speed is:",
    options: [{ key: "A", text: "$21$" },{ key: "B", text: "$\\frac{5}{4}$" },{ key: "C", text: "$80$" },{ key: "D", text: "$9$" },{ key: "E", text: "$20$" }],
    answer: "E", solution: "Maximum speed $=a\\omega=5\\times4=20$ m/s." },
  { id: "step-ex-084", type: "mcq", testId: "step", topicId: "step-mech", difficulty: 3, marks: 20,
    question: "A $2\\,\\text{kg}$ mass hangs and pulls a $3\\,\\text{kg}$ mass on a smooth horizontal table via a pulley ($g=10$). The acceleration is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$6$" },{ key: "C", text: "$\\frac{20}{3}$" },{ key: "D", text: "$4$" },{ key: "E", text: "$10$" }],
    answer: "D", solution: "$a=\\frac{m_1 g}{m_1+m_2}=\\frac{2\\cdot10}{5}=4$ m/s²." },
  { id: "step-ex-085", type: "mcq", testId: "step", topicId: "step-mech", difficulty: 3, marks: 20,
    question: "A $1\\,\\text{kg}$ mass hangs and pulls a $4\\,\\text{kg}$ mass on a smooth horizontal table via a pulley ($g=10$). The acceleration is:",
    options: [{ key: "A", text: "$10$" },{ key: "B", text: "$8$" },{ key: "C", text: "$3$" },{ key: "D", text: "$\\frac{5}{2}$" },{ key: "E", text: "$2$" }],
    answer: "E", solution: "$a=\\frac{m_1 g}{m_1+m_2}=\\frac{1\\cdot10}{5}=2$ m/s²." },
  { id: "step-ex-086", type: "mcq", testId: "step", topicId: "step-mech", difficulty: 3, marks: 20,
    question: "A $3\\,\\text{kg}$ mass hangs and pulls a $2\\,\\text{kg}$ mass on a smooth horizontal table via a pulley ($g=10$). The acceleration is:",
    options: [{ key: "A", text: "$4$" },{ key: "B", text: "$6$" },{ key: "C", text: "$7$" },{ key: "D", text: "$10$" },{ key: "E", text: "$15$" }],
    answer: "B", solution: "$a=\\frac{m_1 g}{m_1+m_2}=\\frac{3\\cdot10}{5}=6$ m/s²." },
  { id: "step-ex-087", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 1, marks: 20,
    question: "For $X\\sim B(10,\\frac{1}{2})$, the mean $E(X)$ is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$6$" },{ key: "C", text: "$\\frac{5}{2}$" },{ key: "D", text: "$\\frac{1}{2}$" },{ key: "E", text: "$10$" }],
    answer: "A", solution: "$E(X)=np=10\\cdot\\frac{1}{2}=5.$" },
  { id: "step-ex-088", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "For $X\\sim B(10,\\frac{1}{2})$, the variance $\\operatorname{Var}(X)$ is:",
    options: [{ key: "A", text: "$10$" },{ key: "B", text: "$\\frac{5}{2}$" },{ key: "C", text: "$\\frac{7}{2}$" },{ key: "D", text: "$5$" },{ key: "E", text: "$2$" }],
    answer: "B", solution: "$\\operatorname{Var}(X)=np(1-p)=10\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{5}{2}.$" },
  { id: "step-ex-089", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 1, marks: 20,
    question: "For $X\\sim B(12,\\frac{1}{3})$, the mean $E(X)$ is:",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$\\frac{1}{3}$" },{ key: "C", text: "$12$" },{ key: "D", text: "$\\frac{8}{3}$" },{ key: "E", text: "$4$" }],
    answer: "E", solution: "$E(X)=np=12\\cdot\\frac{1}{3}=4.$" },
  { id: "step-ex-090", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "For $X\\sim B(12,\\frac{1}{3})$, the variance $\\operatorname{Var}(X)$ is:",
    options: [{ key: "A", text: "$\\frac{13}{6}$" },{ key: "B", text: "$\\frac{8}{3}$" },{ key: "C", text: "$4$" },{ key: "D", text: "$12$" },{ key: "E", text: "$\\frac{11}{3}$" }],
    answer: "B", solution: "$\\operatorname{Var}(X)=np(1-p)=12\\cdot\\frac{1}{3}\\cdot\\frac{2}{3}=\\frac{8}{3}.$" },
  { id: "step-ex-091", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 1, marks: 20,
    question: "For $X\\sim B(20,\\frac{1}{4})$, the mean $E(X)$ is:",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$20$" },{ key: "C", text: "$5$" },{ key: "D", text: "$\\frac{15}{4}$" },{ key: "E", text: "$\\frac{1}{4}$" }],
    answer: "C", solution: "$E(X)=np=20\\cdot\\frac{1}{4}=5.$" },
  { id: "step-ex-092", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "For $X\\sim B(20,\\frac{1}{4})$, the variance $\\operatorname{Var}(X)$ is:",
    options: [{ key: "A", text: "$\\frac{19}{4}$" },{ key: "B", text: "$\\frac{13}{4}$" },{ key: "C", text: "$5$" },{ key: "D", text: "$20$" },{ key: "E", text: "$\\frac{15}{4}$" }],
    answer: "E", solution: "$\\operatorname{Var}(X)=np(1-p)=20\\cdot\\frac{1}{4}\\cdot\\frac{3}{4}=\\frac{15}{4}.$" },
  { id: "step-ex-093", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 1, marks: 20,
    question: "For $X\\sim B(8,\\frac{3}{4})$, the mean $E(X)$ is:",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$\\frac{3}{2}$" },{ key: "C", text: "$6$" },{ key: "D", text: "$\\frac{3}{4}$" },{ key: "E", text: "$7$" }],
    answer: "C", solution: "$E(X)=np=8\\cdot\\frac{3}{4}=6.$" },
  { id: "step-ex-094", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "For $X\\sim B(8,\\frac{3}{4})$, the variance $\\operatorname{Var}(X)$ is:",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$\\frac{3}{2}$" },{ key: "C", text: "$6$" },{ key: "D", text: "$1$" },{ key: "E", text: "$\\frac{5}{2}$" }],
    answer: "B", solution: "$\\operatorname{Var}(X)=np(1-p)=8\\cdot\\frac{3}{4}\\cdot\\frac{1}{4}=\\frac{3}{2}.$" },
  { id: "step-ex-095", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 1, marks: 20,
    question: "For $X\\sim B(15,\\frac{2}{5})$, the mean $E(X)$ is:",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$15$" },{ key: "C", text: "$6$" },{ key: "D", text: "$\\frac{2}{5}$" },{ key: "E", text: "$\\frac{18}{5}$" }],
    answer: "C", solution: "$E(X)=np=15\\cdot\\frac{2}{5}=6.$" },
  { id: "step-ex-096", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "For $X\\sim B(15,\\frac{2}{5})$, the variance $\\operatorname{Var}(X)$ is:",
    options: [{ key: "A", text: "$\\frac{31}{10}$" },{ key: "B", text: "$\\frac{23}{5}$" },{ key: "C", text: "$6$" },{ key: "D", text: "$\\frac{18}{5}$" },{ key: "E", text: "$15$" }],
    answer: "D", solution: "$\\operatorname{Var}(X)=np(1-p)=15\\cdot\\frac{2}{5}\\cdot\\frac{3}{5}=\\frac{18}{5}.$" },
  { id: "step-ex-097", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "For $X\\sim B(5,\\frac{1}{2})$, $P(X=2)$ equals:",
    options: [{ key: "A", text: "$\\frac{5}{16}$" },{ key: "B", text: "$\\frac{1}{4}$" },{ key: "C", text: "$\\frac{5}{2}$" },{ key: "D", text: "$\\frac{33}{80}$" },{ key: "E", text: "$\\frac{5}{8}$" }],
    answer: "A", solution: "$P(X=2)=\\binom{5}{2}(\\frac{1}{2})^{2}(\\frac{1}{2})^{3}=\\frac{5}{16}.$" },
  { id: "step-ex-098", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "For $X\\sim B(6,\\frac{1}{3})$, $P(X=2)$ equals:",
    options: [{ key: "A", text: "$\\frac{5}{3}$" },{ key: "B", text: "$\\frac{1}{9}$" },{ key: "C", text: "$\\frac{1043}{2430}$" },{ key: "D", text: "$\\frac{80}{243}$" },{ key: "E", text: "$\\frac{160}{243}$" }],
    answer: "D", solution: "$P(X=2)=\\binom{6}{2}(\\frac{1}{3})^{2}(\\frac{2}{3})^{4}=\\frac{80}{243}.$" },
  { id: "step-ex-099", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "For $X\\sim B(5,\\frac{2}{5})$, $P(X=3)$ equals:",
    options: [{ key: "A", text: "$\\frac{16}{25}$" },{ key: "B", text: "$\\frac{144}{625}$" },{ key: "C", text: "$\\frac{8}{125}$" },{ key: "D", text: "$\\frac{288}{625}$" },{ key: "E", text: "$\\frac{413}{1250}$" }],
    answer: "B", solution: "$P(X=3)=\\binom{5}{3}(\\frac{2}{5})^{3}(\\frac{3}{5})^{2}=\\frac{144}{625}.$" },
  { id: "step-ex-100", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "For $X\\sim B(6,\\frac{1}{2})$, $P(X=3)$ equals:",
    options: [{ key: "A", text: "$\\frac{5}{2}$" },{ key: "B", text: "$\\frac{1}{8}$" },{ key: "C", text: "$\\frac{5}{8}$" },{ key: "D", text: "$\\frac{33}{80}$" },{ key: "E", text: "$\\frac{5}{16}$" }],
    answer: "E", solution: "$P(X=3)=\\binom{6}{3}(\\frac{1}{2})^{3}(\\frac{1}{2})^{3}=\\frac{5}{16}.$" },
  { id: "step-ex-101", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "A discrete random variable takes values with probabilities $P(0)=\\frac{1}{2}; P(1)=\\frac{1}{3}; P(3)=\\frac{1}{6}$. Its expectation is:",
    options: [{ key: "A", text: "$\\frac{5}{3}$" },{ key: "B", text: "$\\frac{1}{3}$" },{ key: "C", text: "$\\frac{11}{6}$" },{ key: "D", text: "$4$" },{ key: "E", text: "$\\frac{5}{6}$" }],
    answer: "E", solution: "$E(X)=\\sum x P(x)=\\frac{5}{6}.$" },
  { id: "step-ex-102", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "A discrete random variable takes values with probabilities $P(1)=\\frac{1}{4}; P(2)=\\frac{1}{2}; P(4)=\\frac{1}{4}$. Its expectation is:",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$\\frac{9}{4}$" },{ key: "C", text: "$\\frac{13}{4}$" },{ key: "D", text: "$\\frac{25}{4}$" },{ key: "E", text: "$\\frac{7}{4}$" }],
    answer: "B", solution: "$E(X)=\\sum x P(x)=\\frac{9}{4}.$" },
  { id: "step-ex-103", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "A discrete random variable takes values with probabilities $P(0)=\\frac{1}{3}; P(2)=\\frac{1}{3}; P(5)=\\frac{1}{3}$. Its expectation is:",
    options: [{ key: "A", text: "$\\frac{29}{3}$" },{ key: "B", text: "$\\frac{11}{6}$" },{ key: "C", text: "$\\frac{10}{3}$" },{ key: "D", text: "$7$" },{ key: "E", text: "$\\frac{7}{3}$" }],
    answer: "E", solution: "$E(X)=\\sum x P(x)=\\frac{7}{3}.$" },
  { id: "step-ex-104", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 2, marks: 20,
    question: "A discrete random variable takes values with probabilities $P(1)=\\frac{1}{2}; P(3)=\\frac{1}{4}; P(5)=\\frac{1}{4}$. Its expectation is:",
    options: [{ key: "A", text: "$9$" },{ key: "B", text: "$\\frac{5}{2}$" },{ key: "C", text: "$5$" },{ key: "D", text: "$2$" },{ key: "E", text: "$\\frac{7}{2}$" }],
    answer: "B", solution: "$E(X)=\\sum x P(x)=\\frac{5}{2}.$" },
  { id: "step-ex-105", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 3, marks: 20,
    question: "A disease affects a proportion $\\frac{1}{100}$ of a population. A test is positive with probability $\\frac{9}{10}$ if diseased and $\\frac{1}{10}$ if not. Given a positive test, the probability of disease is:",
    options: [{ key: "A", text: "$\\frac{11}{12}$" },{ key: "B", text: "$\\frac{1}{100}$" },{ key: "C", text: "$\\frac{1}{12}$" },{ key: "D", text: "$\\frac{11}{60}$" },{ key: "E", text: "$\\frac{9}{10}$" }],
    answer: "C", solution: "By Bayes: $P(D\\mid+)=\\dfrac{P(+\\mid D)P(D)}{P(+)}=\\frac{1}{12}.$" },
  { id: "step-ex-106", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 3, marks: 20,
    question: "A disease affects a proportion $\\frac{1}{50}$ of a population. A test is positive with probability $\\frac{4}{5}$ if diseased and $\\frac{1}{20}$ if not. Given a positive test, the probability of disease is:",
    options: [{ key: "A", text: "$\\frac{16}{65}$" },{ key: "B", text: "$\\frac{1}{50}$" },{ key: "C", text: "$\\frac{9}{26}$" },{ key: "D", text: "$\\frac{4}{5}$" },{ key: "E", text: "$\\frac{49}{65}$" }],
    answer: "A", solution: "By Bayes: $P(D\\mid+)=\\dfrac{P(+\\mid D)P(D)}{P(+)}=\\frac{16}{65}.$" },
  { id: "step-ex-107", type: "mcq", testId: "step", topicId: "step-stats", difficulty: 3, marks: 20,
    question: "A disease affects a proportion $\\frac{1}{10}$ of a population. A test is positive with probability $1$ if diseased and $\\frac{1}{10}$ if not. Given a positive test, the probability of disease is:",
    options: [{ key: "A", text: "$\\frac{119}{190}$" },{ key: "B", text: "$1$" },{ key: "C", text: "$\\frac{9}{19}$" },{ key: "D", text: "$\\frac{10}{19}$" },{ key: "E", text: "$\\frac{1}{10}$" }],
    answer: "D", solution: "By Bayes: $P(D\\mid+)=\\dfrac{P(+\\mid D)P(D)}{P(+)}=\\frac{10}{19}.$" },
];
