// TARA 问题解决题 —— 可计算数字/空间推理，sympy 计算答案，独立复核。id 前缀 tara-ps-*。
import type { MCQQuestion } from "./types";

export const TARA_PROBLEM: MCQQuestion[] = [
  { id: "tara-ps-001", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "A cyclist rides to a town at $30$ km/h and returns along the same road at $60$ km/h. What is the average speed for the whole journey?",
    options: [{ key: "A", text: "$40$ km/h" },{ key: "B", text: "$60$ km/h" },{ key: "C", text: "$30$ km/h" },{ key: "D", text: "$20$ km/h" },{ key: "E", text: "$45$ km/h" }],
    answer: "A", solution: "Average speed $=\\dfrac{2v_1v_2}{v_1+v_2}=\\dfrac{2\\cdot30\\cdot60}{90}=40$ km/h (not the arithmetic mean)." },
  { id: "tara-ps-002", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "A cyclist rides to a town at $40$ km/h and returns along the same road at $60$ km/h. What is the average speed for the whole journey?",
    options: [{ key: "A", text: "$60$ km/h" },{ key: "B", text: "$50$ km/h" },{ key: "C", text: "$40$ km/h" },{ key: "D", text: "$48$ km/h" },{ key: "E", text: "$24$ km/h" }],
    answer: "D", solution: "Average speed $=\\dfrac{2v_1v_2}{v_1+v_2}=\\dfrac{2\\cdot40\\cdot60}{100}=48$ km/h (not the arithmetic mean)." },
  { id: "tara-ps-003", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "A cyclist rides to a town at $20$ km/h and returns along the same road at $30$ km/h. What is the average speed for the whole journey?",
    options: [{ key: "A", text: "$12$ km/h" },{ key: "B", text: "$20$ km/h" },{ key: "C", text: "$24$ km/h" },{ key: "D", text: "$25$ km/h" },{ key: "E", text: "$30$ km/h" }],
    answer: "C", solution: "Average speed $=\\dfrac{2v_1v_2}{v_1+v_2}=\\dfrac{2\\cdot20\\cdot30}{50}=24$ km/h (not the arithmetic mean)." },
  { id: "tara-ps-004", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "A cyclist rides to a town at $50$ km/h and returns along the same road at $75$ km/h. What is the average speed for the whole journey?",
    options: [{ key: "A", text: "$60$ km/h" },{ key: "B", text: "$\\frac{125}{2}$ km/h" },{ key: "C", text: "$75$ km/h" },{ key: "D", text: "$30$ km/h" },{ key: "E", text: "$50$ km/h" }],
    answer: "A", solution: "Average speed $=\\dfrac{2v_1v_2}{v_1+v_2}=\\dfrac{2\\cdot50\\cdot75}{125}=60$ km/h (not the arithmetic mean)." },
  { id: "tara-ps-005", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "A cyclist rides to a town at $10$ km/h and returns along the same road at $15$ km/h. What is the average speed for the whole journey?",
    options: [{ key: "A", text: "$6$ km/h" },{ key: "B", text: "$10$ km/h" },{ key: "C", text: "$15$ km/h" },{ key: "D", text: "$12$ km/h" },{ key: "E", text: "$\\frac{25}{2}$ km/h" }],
    answer: "D", solution: "Average speed $=\\dfrac{2v_1v_2}{v_1+v_2}=\\dfrac{2\\cdot10\\cdot15}{25}=12$ km/h (not the arithmetic mean)." },
  { id: "tara-ps-006", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "A coat priced at £$200$ is reduced by $10\\%$, and the reduced price is then cut by a further $20\\%$ in a sale. What is the final price?",
    options: [{ key: "A", text: "$180$" },{ key: "B", text: "$140$" },{ key: "C", text: "$160$" },{ key: "D", text: "$144$" },{ key: "E", text: "$149$" }],
    answer: "D", solution: "Successive discounts multiply: £$200\\times\\frac{9}{10}\\times\\frac{4}{5}=£144$ (a $10\\%$ then $20\\%$ cut is not a $30\\%$ cut)." },
  { id: "tara-ps-007", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "A coat priced at £$50$ is reduced by $25\\%$, and the reduced price is then cut by a further $10\\%$ in a sale. What is the final price?",
    options: [{ key: "A", text: "$\\frac{155}{4}$" },{ key: "B", text: "$\\frac{65}{2}$" },{ key: "C", text: "$45$" },{ key: "D", text: "$\\frac{135}{4}$" },{ key: "E", text: "$\\frac{75}{2}$" }],
    answer: "D", solution: "Successive discounts multiply: £$50\\times\\frac{3}{4}\\times\\frac{9}{10}=£\\frac{135}{4}$ (a $25\\%$ then $10\\%$ cut is not a $35\\%$ cut)." },
  { id: "tara-ps-008", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "A coat priced at £$120$ is reduced by $50\\%$, and the reduced price is then cut by a further $25\\%$ in a sale. What is the final price?",
    options: [{ key: "A", text: "$50$" },{ key: "B", text: "$45$" },{ key: "C", text: "$30$" },{ key: "D", text: "$90$" },{ key: "E", text: "$60$" }],
    answer: "B", solution: "Successive discounts multiply: £$120\\times\\frac{1}{2}\\times\\frac{3}{4}=£45$ (a $50\\%$ then $25\\%$ cut is not a $75\\%$ cut)." },
  { id: "tara-ps-009", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "A coat priced at £$80$ is reduced by $20\\%$, and the reduced price is then cut by a further $15\\%$ in a sale. What is the final price?",
    options: [{ key: "A", text: "$68$" },{ key: "B", text: "$52$" },{ key: "C", text: "$\\frac{297}{5}$" },{ key: "D", text: "$64$" },{ key: "E", text: "$\\frac{272}{5}$" }],
    answer: "E", solution: "Successive discounts multiply: £$80\\times\\frac{4}{5}\\times\\frac{17}{20}=£\\frac{272}{5}$ (a $20\\%$ then $15\\%$ cut is not a $35\\%$ cut)." },
  { id: "tara-ps-010", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "A coat priced at £$300$ is reduced by $30\\%$, and the reduced price is then cut by a further $10\\%$ in a sale. What is the final price?",
    options: [{ key: "A", text: "$210$" },{ key: "B", text: "$180$" },{ key: "C", text: "$194$" },{ key: "D", text: "$189$" },{ key: "E", text: "$270$" }],
    answer: "D", solution: "Successive discounts multiply: £$300\\times\\frac{7}{10}\\times\\frac{9}{10}=£189$ (a $30\\%$ then $10\\%$ cut is not a $40\\%$ cut)." },
  { id: "tara-ps-011", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "One tap fills a tank in $4$ hours and another fills it in $6$ hours. How long do they take to fill it together?",
    options: [{ key: "A", text: "$5$ 小时" },{ key: "B", text: "$\\frac{12}{5}$ 小时" },{ key: "C", text: "$12$ 小时" },{ key: "D", text: "$\\frac{17}{5}$ 小时" },{ key: "E", text: "$4$ 小时" }],
    answer: "B", solution: "Combined rate $=\\tfrac1{4}+\\tfrac1{6}$ tanks/hour; time $=\\dfrac1{1/4+1/6}=\\frac{12}{5}$ hours." },
  { id: "tara-ps-012", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "One tap fills a tank in $2$ hours and another fills it in $3$ hours. How long do they take to fill it together?",
    options: [{ key: "A", text: "$2$ 小时" },{ key: "B", text: "$\\frac{6}{5}$ 小时" },{ key: "C", text: "$3$ 小时" },{ key: "D", text: "$\\frac{11}{5}$ 小时" },{ key: "E", text: "$\\frac{5}{2}$ 小时" }],
    answer: "B", solution: "Combined rate $=\\tfrac1{2}+\\tfrac1{3}$ tanks/hour; time $=\\dfrac1{1/2+1/3}=\\frac{6}{5}$ hours." },
  { id: "tara-ps-013", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "One tap fills a tank in $6$ hours and another fills it in $12$ hours. How long do they take to fill it together?",
    options: [{ key: "A", text: "$4$ 小时" },{ key: "B", text: "$9$ 小时" },{ key: "C", text: "$36$ 小时" },{ key: "D", text: "$6$ 小时" },{ key: "E", text: "$5$ 小时" }],
    answer: "A", solution: "Combined rate $=\\tfrac1{6}+\\tfrac1{12}$ tanks/hour; time $=\\dfrac1{1/6+1/12}=4$ hours." },
  { id: "tara-ps-014", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "At a meeting of $6$ people, everyone shakes hands exactly once with everyone else. How many handshakes take place?",
    options: [{ key: "A", text: "$15$" },{ key: "B", text: "$6$" },{ key: "C", text: "$36$" },{ key: "D", text: "$30$" },{ key: "E", text: "$21$" }],
    answer: "A", solution: "Number of handshakes $=\\binom{6}2=\\dfrac{6\\cdot5}2=15.$" },
  { id: "tara-ps-015", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "At a meeting of $8$ people, everyone shakes hands exactly once with everyone else. How many handshakes take place?",
    options: [{ key: "A", text: "$36$" },{ key: "B", text: "$28$" },{ key: "C", text: "$8$" },{ key: "D", text: "$64$" },{ key: "E", text: "$56$" }],
    answer: "B", solution: "Number of handshakes $=\\binom{8}2=\\dfrac{8\\cdot7}2=28.$" },
  { id: "tara-ps-016", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "At a meeting of $10$ people, everyone shakes hands exactly once with everyone else. How many handshakes take place?",
    options: [{ key: "A", text: "$10$" },{ key: "B", text: "$90$" },{ key: "C", text: "$100$" },{ key: "D", text: "$45$" },{ key: "E", text: "$55$" }],
    answer: "D", solution: "Number of handshakes $=\\binom{10}2=\\dfrac{10\\cdot9}2=45.$" },
  { id: "tara-ps-017", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "At a meeting of $12$ people, everyone shakes hands exactly once with everyone else. How many handshakes take place?",
    options: [{ key: "A", text: "$132$" },{ key: "B", text: "$144$" },{ key: "C", text: "$66$" },{ key: "D", text: "$12$" },{ key: "E", text: "$78$" }],
    answer: "C", solution: "Number of handshakes $=\\binom{12}2=\\dfrac{12\\cdot11}2=66.$" },
  { id: "tara-ps-018", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "At a meeting of $5$ people, everyone shakes hands exactly once with everyone else. How many handshakes take place?",
    options: [{ key: "A", text: "$25$" },{ key: "B", text: "$20$" },{ key: "C", text: "$10$" },{ key: "D", text: "$5$" },{ key: "E", text: "$15$" }],
    answer: "C", solution: "Number of handshakes $=\\binom{5}2=\\dfrac{5\\cdot4}2=10.$" },
  { id: "tara-ps-019", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 3, marks: 1,
    question: "A large cube of side $3$ units is painted on all outer faces and then cut into unit cubes. How many small cubes have exactly two painted faces?",
    options: [{ key: "A", text: "$1$" },{ key: "B", text: "$36$" },{ key: "C", text: "$6$" },{ key: "D", text: "$8$" },{ key: "E", text: "$12$" }],
    answer: "E", solution: "Two-face cubes lie along edges (excluding corners): $12(n-2)=12(3-2)=12.$" },
  { id: "tara-ps-020", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 3, marks: 1,
    question: "A large cube of side $5$ units is painted on all outer faces and then cut into unit cubes. How many small cubes have exactly two painted faces?",
    options: [{ key: "A", text: "$60$" },{ key: "B", text: "$27$" },{ key: "C", text: "$54$" },{ key: "D", text: "$36$" },{ key: "E", text: "$8$" }],
    answer: "D", solution: "Two-face cubes lie along edges (excluding corners): $12(n-2)=12(5-2)=36.$" },
  { id: "tara-ps-021", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 3, marks: 1,
    question: "A large cube of side $6$ units is painted on all outer faces and then cut into unit cubes. How many small cubes have exactly two painted faces?",
    options: [{ key: "A", text: "$96$" },{ key: "B", text: "$72$" },{ key: "C", text: "$48$" },{ key: "D", text: "$8$" },{ key: "E", text: "$64$" }],
    answer: "C", solution: "Two-face cubes lie along edges (excluding corners): $12(n-2)=12(6-2)=48.$" },
  { id: "tara-ps-022", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 3, marks: 1,
    question: "A cube of side $3$ is painted and cut into unit cubes. How many have exactly one painted face?",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$12$" },{ key: "C", text: "$54$" },{ key: "D", text: "$1$" },{ key: "E", text: "$8$" }],
    answer: "A", solution: "One-face cubes lie on faces (excluding edges): $6(n-2)^2=6(3-2)^2=6.$" },
  { id: "tara-ps-023", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 3, marks: 1,
    question: "A cube of side $5$ is painted and cut into unit cubes. How many have exactly one painted face?",
    options: [{ key: "A", text: "$54$" },{ key: "B", text: "$36$" },{ key: "C", text: "$150$" },{ key: "D", text: "$27$" },{ key: "E", text: "$8$" }],
    answer: "A", solution: "One-face cubes lie on faces (excluding edges): $6(n-2)^2=6(5-2)^2=54.$" },
  { id: "tara-ps-024", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 3, marks: 1,
    question: "A cube of side $6$ is painted and cut into unit cubes. How many have exactly one painted face?",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$96$" },{ key: "C", text: "$48$" },{ key: "D", text: "$216$" },{ key: "E", text: "$64$" }],
    answer: "B", solution: "One-face cubes lie on faces (excluding edges): $6(n-2)^2=6(6-2)^2=96.$" },
  { id: "tara-ps-025", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "A quantity changes from $200$ to $250$. What is the percentage change?",
    options: [{ key: "A", text: "$-25$ %" },{ key: "B", text: "$20$ %" },{ key: "C", text: "$35$ %" },{ key: "D", text: "$50$ %" },{ key: "E", text: "$25$ %" }],
    answer: "E", solution: "Percentage change $=\\dfrac{250-200}{200}\\times100=25\\%.$" },
  { id: "tara-ps-026", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "A quantity changes from $60$ to $90$. What is the percentage change?",
    options: [{ key: "A", text: "$\\frac{100}{3}$ %" },{ key: "B", text: "$50$ %" },{ key: "C", text: "$60$ %" },{ key: "D", text: "$30$ %" },{ key: "E", text: "$-50$ %" }],
    answer: "B", solution: "Percentage change $=\\dfrac{90-60}{60}\\times100=50\\%.$" },
  { id: "tara-ps-027", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 1, marks: 1,
    question: "A quantity changes from $120$ to $96$. What is the percentage change?",
    options: [{ key: "A", text: "$-20$ %" },{ key: "B", text: "$-24$ %" },{ key: "C", text: "$-10$ %" },{ key: "D", text: "$20$ %" },{ key: "E", text: "$-25$ %" }],
    answer: "A", solution: "Percentage change $=\\dfrac{96-120}{120}\\times100=-20\\%.$" },
  { id: "tara-ps-028", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "An item bought for £$50$ is sold for £$75$. What is the percentage profit or loss?",
    options: [{ key: "A", text: "$55$ %" },{ key: "B", text: "$\\frac{100}{3}$ %" },{ key: "C", text: "$-50$ %" },{ key: "D", text: "$50$ %" },{ key: "E", text: "$25$ %" }],
    answer: "D", solution: "Profit $\\%=\\dfrac{75-50}{50}\\times100=50\\%$ (negative means a loss)." },
  { id: "tara-ps-029", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "An item bought for £$200$ is sold for £$170$. What is the percentage profit or loss?",
    options: [{ key: "A", text: "$-15$ %" },{ key: "B", text: "$15$ %" },{ key: "C", text: "$-10$ %" },{ key: "D", text: "$-30$ %" },{ key: "E", text: "$- \\frac{300}{17}$ %" }],
    answer: "A", solution: "Profit $\\%=\\dfrac{170-200}{200}\\times100=-15\\%$ (negative means a loss)." },
  { id: "tara-ps-030", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 2, marks: 1,
    question: "An item bought for £$40$ is sold for £$60$. What is the percentage profit or loss?",
    options: [{ key: "A", text: "$-50$ %" },{ key: "B", text: "$20$ %" },{ key: "C", text: "$55$ %" },{ key: "D", text: "$50$ %" },{ key: "E", text: "$\\frac{100}{3}$ %" }],
    answer: "D", solution: "Profit $\\%=\\dfrac{60-40}{40}\\times100=50\\%$ (negative means a loss)." },
  { id: "tara-ps-031", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 3, marks: 1,
    question: "A bag holds $4$ red and $2$ blue balls. Two are drawn at random without replacement. What is the probability that both are red?",
    options: [{ key: "A", text: "$\\frac{2}{3}$" },{ key: "B", text: "$\\frac{2}{5}$" },{ key: "C", text: "$\\frac{4}{9}$" },{ key: "D", text: "$\\frac{3}{5}$" },{ key: "E", text: "$\\frac{4}{5}$" }],
    answer: "B", solution: "$P(\\text{both red})=\\dfrac{4}{6}\\times\\dfrac{3}{5}=\\frac{2}{5}.$" },
  { id: "tara-ps-032", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 3, marks: 1,
    question: "A bag holds $5$ red and $3$ blue balls. Two are drawn at random without replacement. What is the probability that both are red?",
    options: [{ key: "A", text: "$\\frac{25}{64}$" },{ key: "B", text: "$\\frac{5}{14}$" },{ key: "C", text: "$\\frac{5}{8}$" },{ key: "D", text: "$\\frac{5}{7}$" },{ key: "E", text: "$\\frac{4}{7}$" }],
    answer: "B", solution: "$P(\\text{both red})=\\dfrac{5}{8}\\times\\dfrac{4}{7}=\\frac{5}{14}.$" },
  { id: "tara-ps-033", type: "mcq", testId: "tara", topicId: "tara-problem", difficulty: 3, marks: 1,
    question: "A bag holds $2$ red and $3$ blue balls. Two are drawn at random without replacement. What is the probability that both are red?",
    options: [{ key: "A", text: "$\\frac{1}{4}$" },{ key: "B", text: "$\\frac{4}{25}$" },{ key: "C", text: "$\\frac{2}{5}$" },{ key: "D", text: "$\\frac{1}{10}$" },{ key: "E", text: "$\\frac{1}{5}$" }],
    answer: "D", solution: "$P(\\text{both red})=\\dfrac{2}{5}\\times\\dfrac{1}{4}=\\frac{1}{10}.$" },
];
