// TMUA 题库 —— 40 道全新原创题（5 个知识点 × 8）。全部五选一（A–E）。
// TMUA：Paper 1 数学应用 + Paper 2 数学推理与逻辑，均为多选、无长题。
// 与其它题库不重复。id 前缀 tmua-*。

import type { MCQQuestion } from "@/lib/tests/questions/types";

export const TMUA_QUESTIONS: MCQQuestion[] = [
  // ── 代数与函数 ────────────────────────────────────────────────
  { id: "tmua-alg-01", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 1, marks: 1,
    question: "Solve $|2x-1|<5$.",
    options: [ {key:"A",text:"$-2<x<3$"},{key:"B",text:"$-3<x<2$"},{key:"C",text:"$x<3$"},{key:"D",text:"$-2<x<2$"},{key:"E",text:"$x>3$"} ],
    answer: "A", solution: "$-5<2x-1<5\\Rightarrow -4<2x<6\\Rightarrow -2<x<3$." },
  { id: "tmua-alg-02", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "The range of $f(x)=x^2-4x+7$ (for real $x$) is:",
    options: [ {key:"A",text:"$y\\ge 3$"},{key:"B",text:"$y\\ge 7$"},{key:"C",text:"$y\\ge -3$"},{key:"D",text:"all real $y$"},{key:"E",text:"$y\\ge 0$"} ],
    answer: "A", solution: "$f(x)=(x-2)^2+3$, minimum value $3$, so range is $y\\ge3$." },
  { id: "tmua-alg-03", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 1, marks: 1,
    question: "If $f(x)=x^2-3$ and $g(x)=2x+1$, then $f(g(1))=$",
    options: [ {key:"A",text:"$1$"},{key:"B",text:"$3$"},{key:"C",text:"$6$"},{key:"D",text:"$-1$"},{key:"E",text:"$9$"} ],
    answer: "C", solution: "$g(1)=3$, then $f(3)=9-3=6$." },
  { id: "tmua-alg-04", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 3, marks: 1,
    question: "Solve $2^{2x}-5\\cdot 2^{x}+4=0$.",
    options: [ {key:"A",text:"$x=0$ or $x=2$"},{key:"B",text:"$x=1$ or $x=4$"},{key:"C",text:"$x=2$ only"},{key:"D",text:"$x=0$ or $x=1$"},{key:"E",text:"$x=1$ or $x=2$"} ],
    answer: "A", solution: "Let $u=2^x$: $u^2-5u+4=0\\Rightarrow(u-1)(u-4)=0$, so $2^x=1\\ (x=0)$ or $2^x=4\\ (x=2)$." },
  { id: "tmua-alg-05", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 3, marks: 1,
    question: "The equation $x^2+kx+k=0$ has real roots for:",
    options: [ {key:"A",text:"$0\\le k\\le4$"},{key:"B",text:"$k\\le0$ or $k\\ge4$"},{key:"C",text:"$k\\ge4$ only"},{key:"D",text:"all $k$"},{key:"E",text:"$-4\\le k\\le0$"} ],
    answer: "B", solution: "Discriminant $k^2-4k\\ge0\\Rightarrow k(k-4)\\ge0\\Rightarrow k\\le0$ or $k\\ge4$." },
  { id: "tmua-alg-06", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "Solve $\\log_2 x+\\log_2(x+2)=3$.",
    options: [ {key:"A",text:"$x=2$"},{key:"B",text:"$x=-4$"},{key:"C",text:"$x=2$ or $x=-4$"},{key:"D",text:"$x=4$"},{key:"E",text:"$x=6$"} ],
    answer: "A", solution: "$x(x+2)=8\\Rightarrow x^2+2x-8=0\\Rightarrow(x+4)(x-2)=0$; reject $-4$ (domain), so $x=2$." },
  { id: "tmua-alg-07", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 3, marks: 1,
    question: "The coefficient of $x^2$ in the expansion of $(1+3x)^4$ is:",
    options: [ {key:"A",text:"$6$"},{key:"B",text:"$18$"},{key:"C",text:"$36$"},{key:"D",text:"$54$"},{key:"E",text:"$81$"} ],
    answer: "D", solution: "$\\binom{4}{2}(3)^2=6\\times9=54$." },
  { id: "tmua-alg-08", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "Solve the inequality $\\dfrac{x-1}{x+2}>0$.",
    options: [ {key:"A",text:"$x>1$"},{key:"B",text:"$x<-2$ or $x>1$"},{key:"C",text:"$-2<x<1$"},{key:"D",text:"$x>-2$"},{key:"E",text:"$x<1$"} ],
    answer: "B", solution: "Quotient positive when numerator and denominator share sign: $x>1$ (both $+$) or $x<-2$ (both $-$)." },

  // ── 微积分 ────────────────────────────────────────────────────
  { id: "tmua-calc-01", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 2, marks: 1,
    question: "For $y=x^3-6x^2+9x$, the value of $\\dfrac{dy}{dx}$ at $x=1$ is:",
    options: [ {key:"A",text:"$0$"},{key:"B",text:"$3$"},{key:"C",text:"$-3$"},{key:"D",text:"$6$"},{key:"E",text:"$9$"} ],
    answer: "A", solution: "$\\dfrac{dy}{dx}=3x^2-12x+9$; at $x=1$: $3-12+9=0$." },
  { id: "tmua-calc-02", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 2, marks: 1,
    question: "Evaluate $\\displaystyle\\int_0^1 (3x^2+2x)\\,dx$.",
    options: [ {key:"A",text:"$1$"},{key:"B",text:"$2$"},{key:"C",text:"$3$"},{key:"D",text:"$4$"},{key:"E",text:"$5$"} ],
    answer: "B", solution: "$[x^3+x^2]_0^1=1+1=2$." },
  { id: "tmua-calc-03", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 3, marks: 1,
    question: "The curve $y=x^3-3x$ has a local maximum at $x=$",
    options: [ {key:"A",text:"$1$"},{key:"B",text:"$-1$"},{key:"C",text:"$0$"},{key:"D",text:"$3$"},{key:"E",text:"$-3$"} ],
    answer: "B", solution: "$y'=3x^2-3=0\\Rightarrow x=\\pm1$; $y''=6x$, at $x=-1$ it is $-6<0$, a maximum." },
  { id: "tmua-calc-04", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 3, marks: 1,
    question: "The area enclosed between $y=4-x^2$ and the $x$-axis is:",
    options: [ {key:"A",text:"$8$"},{key:"B",text:"$\\tfrac{16}{3}$"},{key:"C",text:"$\\tfrac{32}{3}$"},{key:"D",text:"$16$"},{key:"E",text:"$\\tfrac{64}{3}$"} ],
    answer: "C", solution: "Roots $x=\\pm2$: $\\int_{-2}^{2}(4-x^2)\\,dx=\\left[4x-\\tfrac{x^3}{3}\\right]_{-2}^{2}=\\tfrac{32}{3}$." },
  { id: "tmua-calc-05", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 1, marks: 1,
    question: "The gradient of the tangent to $y=x^2-2x$ at $x=3$ is:",
    options: [ {key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$4$"},{key:"D",text:"$6$"},{key:"E",text:"$1$"} ],
    answer: "C", solution: "$\\dfrac{dy}{dx}=2x-2$; at $x=3$: $6-2=4$." },
  { id: "tmua-calc-06", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 2, marks: 1,
    question: "Evaluate $\\displaystyle\\int_1^2 \\dfrac{1}{x^2}\\,dx$.",
    options: [ {key:"A",text:"$\\tfrac12$"},{key:"B",text:"$1$"},{key:"C",text:"$\\tfrac13$"},{key:"D",text:"$\\tfrac34$"},{key:"E",text:"$2$"} ],
    answer: "A", solution: "$\\int x^{-2}\\,dx=-x^{-1}$: $\\left[-\\tfrac1x\\right]_1^2=-\\tfrac12+1=\\tfrac12$." },
  { id: "tmua-calc-07", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 3, marks: 1,
    question: "If $y=(2x+1)^3$, the value of $\\dfrac{dy}{dx}$ at $x=0$ is:",
    options: [ {key:"A",text:"$3$"},{key:"B",text:"$6$"},{key:"C",text:"$1$"},{key:"D",text:"$2$"},{key:"E",text:"$12$"} ],
    answer: "B", solution: "Chain rule: $\\dfrac{dy}{dx}=3(2x+1)^2\\cdot2=6(2x+1)^2$; at $x=0$: $6$." },
  { id: "tmua-calc-08", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 2, marks: 1,
    question: "How many stationary points does $y=x^4-2x^2$ have?",
    options: [ {key:"A",text:"$1$"},{key:"B",text:"$2$"},{key:"C",text:"$3$"},{key:"D",text:"$4$"},{key:"E",text:"$0$"} ],
    answer: "C", solution: "$y'=4x^3-4x=4x(x^2-1)=0\\Rightarrow x=0,\\pm1$ — three stationary points." },

  // ── 统计与概率 ────────────────────────────────────────────────
  { id: "tmua-stat-01", type: "mcq", testId: "tmua", topicId: "tmua-stats", difficulty: 1, marks: 1,
    question: "A fair die is rolled. The probability of a prime number is:",
    options: [ {key:"A",text:"$\\tfrac13$"},{key:"B",text:"$\\tfrac12$"},{key:"C",text:"$\\tfrac23$"},{key:"D",text:"$\\tfrac16$"},{key:"E",text:"$\\tfrac56$"} ],
    answer: "B", solution: "Primes on a die: $2,3,5$ — three outcomes, $\\tfrac36=\\tfrac12$." },
  { id: "tmua-stat-02", type: "mcq", testId: "tmua", topicId: "tmua-stats", difficulty: 1, marks: 1,
    question: "Two fair coins are tossed. The probability of exactly one head is:",
    options: [ {key:"A",text:"$\\tfrac14$"},{key:"B",text:"$\\tfrac12$"},{key:"C",text:"$\\tfrac34$"},{key:"D",text:"$\\tfrac13$"},{key:"E",text:"$1$"} ],
    answer: "B", solution: "Outcomes HT and TH out of four equally likely: $\\tfrac24=\\tfrac12$." },
  { id: "tmua-stat-03", type: "mcq", testId: "tmua", topicId: "tmua-stats", difficulty: 1, marks: 1,
    question: "The mean of $4$, $8$ and $x$ is $6$. Then $x=$",
    options: [ {key:"A",text:"$4$"},{key:"B",text:"$5$"},{key:"C",text:"$6$"},{key:"D",text:"$8$"},{key:"E",text:"$12$"} ],
    answer: "C", solution: "$\\dfrac{4+8+x}{3}=6\\Rightarrow 12+x=18\\Rightarrow x=6$." },
  { id: "tmua-stat-04", type: "mcq", testId: "tmua", topicId: "tmua-stats", difficulty: 3, marks: 1,
    question: "A bag has 3 red and 2 blue balls. Two are drawn without replacement. P(both red) is:",
    options: [ {key:"A",text:"$\\tfrac{9}{25}$"},{key:"B",text:"$\\tfrac{3}{10}$"},{key:"C",text:"$\\tfrac{6}{25}$"},{key:"D",text:"$\\tfrac{2}{5}$"},{key:"E",text:"$\\tfrac{1}{2}$"} ],
    answer: "B", solution: "$\\dfrac{3}{5}\\times\\dfrac{2}{4}=\\dfrac{6}{20}=\\dfrac{3}{10}$." },
  { id: "tmua-stat-05", type: "mcq", testId: "tmua", topicId: "tmua-stats", difficulty: 2, marks: 1,
    question: "For a fair die, the expected value of the score is:",
    options: [ {key:"A",text:"$3$"},{key:"B",text:"$3.5$"},{key:"C",text:"$4$"},{key:"D",text:"$21$"},{key:"E",text:"$6$"} ],
    answer: "B", solution: "$E(X)=\\dfrac{1+2+3+4+5+6}{6}=\\dfrac{21}{6}=3.5$." },
  { id: "tmua-stat-06", type: "mcq", testId: "tmua", topicId: "tmua-stats", difficulty: 2, marks: 1,
    question: "Events $A,B$ are independent with $P(A)=0.6$, $P(B)=0.5$. Then $P(A\\cap B)=$",
    options: [ {key:"A",text:"$0.1$"},{key:"B",text:"$0.3$"},{key:"C",text:"$0.5$"},{key:"D",text:"$1.1$"},{key:"E",text:"$0.8$"} ],
    answer: "B", solution: "Independence: $P(A\\cap B)=P(A)P(B)=0.6\\times0.5=0.3$." },
  { id: "tmua-stat-07", type: "mcq", testId: "tmua", topicId: "tmua-stats", difficulty: 2, marks: 1,
    question: "In how many ways can 5 distinct people stand in a line?",
    options: [ {key:"A",text:"$25$"},{key:"B",text:"$60$"},{key:"C",text:"$120$"},{key:"D",text:"$25$"},{key:"E",text:"$720$"} ],
    answer: "C", solution: "$5!=120$." },
  { id: "tmua-stat-08", type: "mcq", testId: "tmua", topicId: "tmua-stats", difficulty: 2, marks: 1,
    question: "How many ways are there to choose 3 people from 6?",
    options: [ {key:"A",text:"$18$"},{key:"B",text:"$20$"},{key:"C",text:"$120$"},{key:"D",text:"$216$"},{key:"E",text:"$6$"} ],
    answer: "B", solution: "$\\binom{6}{3}=\\dfrac{6\\times5\\times4}{3!}=20$." },

  // ── 数学推理与证明（Paper 2） ─────────────────────────────────
  { id: "tmua-log-01", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "For integers $n$, the statement ‘if $n^2$ is even then $n$ is even’ is:",
    options: [ {key:"A",text:"true"},{key:"B",text:"false"},{key:"C",text:"true only for $n>0$"},{key:"D",text:"true only for even $n$"},{key:"E",text:"undecidable"} ],
    answer: "A", solution: "By contrapositive: if $n$ is odd then $n^2$ is odd. So $n^2$ even forces $n$ even. True." },
  { id: "tmua-log-02", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "The negation of ‘all prime numbers are odd’ is:",
    options: [ {key:"A",text:"all primes are even"},{key:"B",text:"there exists a prime that is even"},{key:"C",text:"no prime is odd"},{key:"D",text:"some primes are odd"},{key:"E",text:"there is no prime"} ],
    answer: "B", solution: "Negating a universal gives an existential: ‘there exists a prime that is not odd (i.e. even)’ — true, since 2 is prime." },
  { id: "tmua-log-03", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "Which value is a counterexample to ‘for all positive integers $n$, $n^2\\ge 2n$’?",
    options: [ {key:"A",text:"$n=1$"},{key:"B",text:"$n=2$"},{key:"C",text:"$n=3$"},{key:"D",text:"$n=4$"},{key:"E",text:"no counterexample exists"} ],
    answer: "A", solution: "At $n=1$: $1\\ge2$ is false. (For $n\\ge2$ it holds.) So $n=1$ is a counterexample." },
  { id: "tmua-log-04", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "The statement $P\\Rightarrow Q$ is logically equivalent to:",
    options: [ {key:"A",text:"$Q\\Rightarrow P$"},{key:"B",text:"$\\lnot P\\Rightarrow\\lnot Q$"},{key:"C",text:"$\\lnot Q\\Rightarrow\\lnot P$"},{key:"D",text:"$P\\land Q$"},{key:"E",text:"$\\lnot P\\land Q$"} ],
    answer: "C", solution: "A conditional is equivalent to its contrapositive $\\lnot Q\\Rightarrow\\lnot P$ (not its converse or inverse)." },
  { id: "tmua-log-05", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 3, marks: 1,
    question: "Given ‘$x>2\\Rightarrow x^2>4$’ (for real $x$), is the converse true?",
    options: [ {key:"A",text:"yes, always"},{key:"B",text:"no ($x=-3$ is a counterexample)"},{key:"C",text:"yes, only for $x>0$"},{key:"D",text:"the converse is meaningless"},{key:"E",text:"only for integers"} ],
    answer: "B", solution: "Converse: $x^2>4\\Rightarrow x>2$. But $x=-3$ gives $x^2=9>4$ while $x<2$. So the converse is false." },
  { id: "tmua-log-06", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "The sum of the first $n$ odd numbers $1+3+5+\\cdots+(2n-1)$ equals:",
    options: [ {key:"A",text:"$n^2$"},{key:"B",text:"$2n-1$"},{key:"C",text:"$\\tfrac{n(n+1)}{2}$"},{key:"D",text:"$n(n+1)$"},{key:"E",text:"$2^n-1$"} ],
    answer: "A", solution: "The sum of the first $n$ odd numbers is $n^2$ (provable by induction)." },
  { id: "tmua-log-07", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 3, marks: 1,
    question: "‘There is no largest prime number’ is classically proved by:",
    options: [ {key:"A",text:"direct construction of the largest prime"},{key:"B",text:"proof by contradiction"},{key:"C",text:"a single example"},{key:"D",text:"differentiation"},{key:"E",text:"it cannot be proved"} ],
    answer: "B", solution: "Euclid’s argument assumes finitely many primes, forms $p_1p_2\\cdots p_k+1$, and derives a contradiction — proof by contradiction." },
  { id: "tmua-log-08", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 1, marks: 1,
    question: "The statement ‘for all real $x$, $x^2\\ge 0$’ is:",
    options: [ {key:"A",text:"true"},{key:"B",text:"false"},{key:"C",text:"true only for $x\\ge0$"},{key:"D",text:"true only for integers"},{key:"E",text:"undecidable"} ],
    answer: "A", solution: "A real number squared is never negative, so the statement is true for all real $x$." },

  // ── 离散数学入门 ─────────────────────────────────────────────
  { id: "tmua-dis-01", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 2, marks: 1,
    question: "If $|A|=5$, $|B|=7$ and $|A\\cap B|=3$, then $|A\\cup B|=$",
    options: [ {key:"A",text:"$9$"},{key:"B",text:"$12$"},{key:"C",text:"$15$"},{key:"D",text:"$3$"},{key:"E",text:"$10$"} ],
    answer: "A", solution: "Inclusion–exclusion: $|A\\cup B|=5+7-3=9$." },
  { id: "tmua-dis-02", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 2, marks: 1,
    question: "How many subsets does a set with 4 elements have?",
    options: [ {key:"A",text:"$4$"},{key:"B",text:"$8$"},{key:"C",text:"$16$"},{key:"D",text:"$24$"},{key:"E",text:"$32$"} ],
    answer: "C", solution: "A set with $n$ elements has $2^n$ subsets: $2^4=16$." },
  { id: "tmua-dis-03", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 3, marks: 1,
    question: "A graph has 5 vertices, each of degree 2. How many edges does it have?",
    options: [ {key:"A",text:"$2$"},{key:"B",text:"$5$"},{key:"C",text:"$10$"},{key:"D",text:"$7$"},{key:"E",text:"$25$"} ],
    answer: "B", solution: "Sum of degrees $=5\\times2=10=2\\times(\\text{edges})$, so edges $=5$." },
  { id: "tmua-dis-04", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 2, marks: 1,
    question: "By De Morgan’s law, $\\lnot(A\\land B)$ is equivalent to:",
    options: [ {key:"A",text:"$\\lnot A\\land\\lnot B$"},{key:"B",text:"$\\lnot A\\lor\\lnot B$"},{key:"C",text:"$A\\lor B$"},{key:"D",text:"$A\\land\\lnot B$"},{key:"E",text:"$\\lnot A\\land B$"} ],
    answer: "B", solution: "De Morgan: $\\lnot(A\\land B)=\\lnot A\\lor\\lnot B$." },
  { id: "tmua-dis-05", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 3, marks: 1,
    question: "How many edges are in the complete graph $K_5$ (5 vertices, all joined)?",
    options: [ {key:"A",text:"$5$"},{key:"B",text:"$10$"},{key:"C",text:"$20$"},{key:"D",text:"$25$"},{key:"E",text:"$15$"} ],
    answer: "B", solution: "Each pair of vertices joined once: $\\binom{5}{2}=10$." },
  { id: "tmua-dis-06", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 1, marks: 1,
    question: "If $A\\subseteq B$ and $B\\subseteq A$, then:",
    options: [ {key:"A",text:"$A=B$"},{key:"B",text:"$A\\cap B=\\varnothing$"},{key:"C",text:"$A$ is empty"},{key:"D",text:"$B$ is empty"},{key:"E",text:"nothing can be said"} ],
    answer: "A", solution: "Mutual containment means the two sets have exactly the same elements: $A=B$." },
  { id: "tmua-dis-07", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 1, marks: 1,
    question: "For any proposition $A$, the expression $A\\lor(\\lnot A)$ is:",
    options: [ {key:"A",text:"always true"},{key:"B",text:"always false"},{key:"C",text:"true only when $A$ is true"},{key:"D",text:"true only when $A$ is false"},{key:"E",text:"undefined"} ],
    answer: "A", solution: "$A\\lor\\lnot A$ is a tautology — true regardless of $A$ (law of excluded middle)." },
  { id: "tmua-dis-08", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 2, marks: 1,
    question: "If 6 people each shake hands once with every other person, how many handshakes occur?",
    options: [ {key:"A",text:"$12$"},{key:"B",text:"$15$"},{key:"C",text:"$30$"},{key:"D",text:"$36$"},{key:"E",text:"$21$"} ],
    answer: "B", solution: "Each handshake is a pair: $\\binom{6}{2}=15$." },
  { id: "tmua-alg-09", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 1, marks: 1,
    question: "Solve $|x-2|<3$.",
    options: [ {key:"A",text:"$-1<x<5$"},{key:"B",text:"$x<5$"},{key:"C",text:"$-5<x<1$"},{key:"D",text:"$x>-1$"},{key:"E",text:"$-3<x<3$"} ],
    answer: "A", solution: "$|x-2|<3\\Rightarrow -3<x-2<3\\Rightarrow -1<x<5$." },
  { id: "tmua-alg-10", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "How many real solutions does $x^2+x+1=0$ have?",
    options: [ {key:"A",text:"$0$"},{key:"B",text:"$1$"},{key:"C",text:"$2$"},{key:"D",text:"infinitely many"},{key:"E",text:"$3$"} ],
    answer: "A", solution: "Discriminant $=1-4=-3<0$, so there are no real solutions." },
  { id: "tmua-alg-11", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "Simplify $\\sqrt{8}+\\sqrt{2}$.",
    options: [ {key:"A",text:"$3\\sqrt2$"},{key:"B",text:"$\\sqrt{10}$"},{key:"C",text:"$4\\sqrt2$"},{key:"D",text:"$2\\sqrt2$"},{key:"E",text:"$6$"} ],
    answer: "A", solution: "$\\sqrt8=2\\sqrt2$, so $\\sqrt8+\\sqrt2=2\\sqrt2+\\sqrt2=3\\sqrt2$." },
  { id: "tmua-alg-12", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 3, marks: 1,
    question: "If $x+\\dfrac1x=3$, what is $x^2+\\dfrac{1}{x^2}$?",
    options: [ {key:"A",text:"$7$"},{key:"B",text:"$9$"},{key:"C",text:"$11$"},{key:"D",text:"$6$"},{key:"E",text:"$3$"} ],
    answer: "A", solution: "$\\left(x+\\tfrac1x\\right)^2=x^2+2+\\tfrac1{x^2}=9$, so $x^2+\\tfrac1{x^2}=7$." },

  { id: "tmua-calc-09", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 1, marks: 1,
    question: "Differentiate $y=x^2+3x$.",
    options: [ {key:"A",text:"$2x+3$"},{key:"B",text:"$2x$"},{key:"C",text:"$x+3$"},{key:"D",text:"$2x+3x$"},{key:"E",text:"$x^2$"} ],
    answer: "A", solution: "$\\dfrac{dy}{dx}=2x+3$." },
  { id: "tmua-calc-10", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 2, marks: 1,
    question: "Evaluate $\\displaystyle\\int_0^2 x\\,dx$.",
    options: [ {key:"A",text:"$2$"},{key:"B",text:"$4$"},{key:"C",text:"$1$"},{key:"D",text:"$\\tfrac12$"},{key:"E",text:"$0$"} ],
    answer: "A", solution: "$\\int_0^2 x\\,dx=\\big[\\tfrac{x^2}{2}\\big]_0^2=2$." },
  { id: "tmua-calc-11", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 2, marks: 1,
    question: "What is the gradient of $y=x^2-4x$ at $x=1$?",
    options: [ {key:"A",text:"$-2$"},{key:"B",text:"$2$"},{key:"C",text:"$-4$"},{key:"D",text:"$0$"},{key:"E",text:"$-3$"} ],
    answer: "A", solution: "$\\dfrac{dy}{dx}=2x-4$; at $x=1$ this is $-2$." },
  { id: "tmua-calc-12", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 3, marks: 1,
    question: "What is the minimum value of $y=x^2-6x+5$?",
    options: [ {key:"A",text:"$-4$"},{key:"B",text:"$5$"},{key:"C",text:"$3$"},{key:"D",text:"$-9$"},{key:"E",text:"$0$"} ],
    answer: "A", solution: "$y=(x-3)^2-4$, so the minimum value is $-4$ (at $x=3$)." },

  { id: "tmua-stat-09", type: "mcq", testId: "tmua", topicId: "tmua-stats", difficulty: 1, marks: 1,
    question: "A fair six-sided die is rolled. What is the probability of an even number?",
    options: [ {key:"A",text:"$\\tfrac12$"},{key:"B",text:"$\\tfrac13$"},{key:"C",text:"$\\tfrac16$"},{key:"D",text:"$\\tfrac23$"},{key:"E",text:"$\\tfrac14$"} ],
    answer: "A", solution: "Even outcomes $\\{2,4,6\\}$ give $\\tfrac36=\\tfrac12$." },
  { id: "tmua-stat-10", type: "mcq", testId: "tmua", topicId: "tmua-stats", difficulty: 2, marks: 1,
    question: "In how many ways can $3$ distinct books be arranged in a row?",
    options: [ {key:"A",text:"$6$"},{key:"B",text:"$3$"},{key:"C",text:"$9$"},{key:"D",text:"$8$"},{key:"E",text:"$1$"} ],
    answer: "A", solution: "$3!=6$." },
  { id: "tmua-stat-11", type: "mcq", testId: "tmua", topicId: "tmua-stats", difficulty: 2, marks: 1,
    question: "Two fair coins are tossed. What is the probability of exactly one head?",
    options: [ {key:"A",text:"$\\tfrac12$"},{key:"B",text:"$\\tfrac14$"},{key:"C",text:"$\\tfrac34$"},{key:"D",text:"$\\tfrac13$"},{key:"E",text:"$1$"} ],
    answer: "A", solution: "Outcomes HT and TH out of four give $\\tfrac24=\\tfrac12$." },
  { id: "tmua-stat-12", type: "mcq", testId: "tmua", topicId: "tmua-stats", difficulty: 3, marks: 1,
    question: "Two fair dice are rolled. What is the probability of at least one six?",
    options: [ {key:"A",text:"$\\tfrac{11}{36}$"},{key:"B",text:"$\\tfrac{1}{6}$"},{key:"C",text:"$\\tfrac{1}{3}$"},{key:"D",text:"$\\tfrac{25}{36}$"},{key:"E",text:"$\\tfrac{1}{36}$"} ],
    answer: "A", solution: "$1-\\left(\\tfrac56\\right)^2=1-\\tfrac{25}{36}=\\tfrac{11}{36}$." },

  { id: "tmua-log-09", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "Which condition is sufficient for $x^2>4$?",
    options: [ {key:"A",text:"$x>3$"},{key:"B",text:"$x>0$"},{key:"C",text:"$x>-2$"},{key:"D",text:"$x=2$"},{key:"E",text:"$x<3$"} ],
    answer: "A", solution: "If $x>3$ then $x^2>9>4$, so it is sufficient. The others allow values with $x^2\\le4$." },
  { id: "tmua-log-10", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "What is the negation of \"for all $x$, $P(x)$\"?",
    options: [ {key:"A",text:"there exists $x$ with not $P(x)$"},{key:"B",text:"for all $x$, not $P(x)$"},{key:"C",text:"there exists $x$ with $P(x)$"},{key:"D",text:"for no $x$, $P(x)$"},{key:"E",text:"$P(x)$ is always true"} ],
    answer: "A", solution: "The negation of a universal statement is an existential one: there exists $x$ for which $P(x)$ fails." },
  { id: "tmua-log-11", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 3, marks: 1,
    question: "\"If it rains, the ground is wet.\" The ground is wet. What can be concluded?",
    options: [ {key:"A",text:"Nothing about whether it rained"},{key:"B",text:"It rained"},{key:"C",text:"It did not rain"},{key:"D",text:"It will rain"},{key:"E",text:"The ground is dry"} ],
    answer: "A", solution: "Affirming the consequent is invalid: a wet ground could have other causes, so we cannot conclude it rained." },
  { id: "tmua-log-12", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "What is the contrapositive of \"if $A$ then $B$\"?",
    options: [ {key:"A",text:"if not $B$ then not $A$"},{key:"B",text:"if $B$ then $A$"},{key:"C",text:"if not $A$ then not $B$"},{key:"D",text:"if $A$ then not $B$"},{key:"E",text:"$A$ and $B$"} ],
    answer: "A", solution: "The contrapositive of $A\\Rightarrow B$ is $\\lnot B\\Rightarrow\\lnot A$, which is logically equivalent." },

  { id: "tmua-dis-09", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 1, marks: 1,
    question: "How many positive factors does $12$ have?",
    options: [ {key:"A",text:"$6$"},{key:"B",text:"$4$"},{key:"C",text:"$5$"},{key:"D",text:"$12$"},{key:"E",text:"$3$"} ],
    answer: "A", solution: "$1,2,3,4,6,12$ — six factors." },
  { id: "tmua-dis-10", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 2, marks: 1,
    question: "What is the remainder when $2^{10}$ is divided by $3$?",
    options: [ {key:"A",text:"$1$"},{key:"B",text:"$2$"},{key:"C",text:"$0$"},{key:"D",text:"$4$"},{key:"E",text:"$8$"} ],
    answer: "A", solution: "$2\\equiv-1\\pmod3$, so $2^{10}\\equiv(-1)^{10}=1\\pmod3$." },
  { id: "tmua-dis-11", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 1, marks: 1,
    question: "What is $1+2+3+\\cdots+10$?",
    options: [ {key:"A",text:"$55$"},{key:"B",text:"$45$"},{key:"C",text:"$50$"},{key:"D",text:"$100$"},{key:"E",text:"$60$"} ],
    answer: "A", solution: "$\\dfrac{10\\cdot11}{2}=55$." },
  { id: "tmua-dis-12", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 2, marks: 1,
    question: "In how many ways can $2$ items be chosen from $5$ distinct items?",
    options: [ {key:"A",text:"$10$"},{key:"B",text:"$20$"},{key:"C",text:"$25$"},{key:"D",text:"$7$"},{key:"E",text:"$5$"} ],
    answer: "A", solution: "$\\binom{5}{2}=\\dfrac{5\\cdot4}{2}=10$." },
];
