// TMUA 练习题扩充包 —— 全部原创，依据 2016–2023 真题的题型分布规律 + 官方考纲 + Paper 2 逻辑证明重点校准。
// 仅用真题做「题型/难度/分布」校准，未复制任何一道真题。
// 权重参照真实分布：Paper 2 逻辑推理为重（必要充分/反例/证明识别/量词否定/找错），
// 叠加 Paper 1 重点主题（对数指数、数列、坐标几何、三角）。
import type { MCQQuestion } from "./types";

export const TMUA_EXPANSION: MCQQuestion[] = [
  // ══════════ 逻辑与推理（tmua-logic）——最高权重，14 题 ══════════
  { id: "tmua-ex-l01", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "For the statement '$x^2>4$', the condition '$x>2$' is:",
    options: [ {key:"A",text:"necessary but not sufficient"},{key:"B",text:"sufficient but not necessary"},{key:"C",text:"both necessary and sufficient"},{key:"D",text:"neither"},{key:"E",text:"undecidable"} ],
    answer: "B", solution: "$x>2\\Rightarrow x^2>4$ (sufficient), but $x^2>4$ also holds for $x<-2$, so $x>2$ is not necessary." },
  { id: "tmua-ex-l02", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "For a triangle to be equilateral, having two equal angles is:",
    options: [ {key:"A",text:"sufficient but not necessary"},{key:"B",text:"necessary but not sufficient"},{key:"C",text:"both"},{key:"D",text:"neither"},{key:"E",text:"cannot be decided"} ],
    answer: "B", solution: "An equilateral triangle has all angles equal, so two equal angles is necessary; but an isosceles triangle has two equal angles without being equilateral, so not sufficient." },
  { id: "tmua-ex-l03", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 3, marks: 1,
    question: "Consider 'if a number ends in $0$ then it is divisible by $5$'. Which is correct about its converse?",
    options: [ {key:"A",text:"converse is true"},{key:"B",text:"converse is false; counterexample $15$"},{key:"C",text:"converse is false; counterexample $20$"},{key:"D",text:"converse equals the original"},{key:"E",text:"converse is 'if not divisible by 5 then does not end in 0'"} ],
    answer: "B", solution: "Converse: 'if divisible by 5 then ends in 0'. This is false: $15$ is divisible by 5 but ends in 5." },
  { id: "tmua-ex-l04", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "The contrapositive of 'if $n$ is a multiple of $6$ then $n$ is even' is:",
    options: [ {key:"A",text:"if $n$ is even then $n$ is a multiple of 6"},{key:"B",text:"if $n$ is odd then $n$ is not a multiple of 6"},{key:"C",text:"if $n$ is not a multiple of 6 then $n$ is odd"},{key:"D",text:"if $n$ is a multiple of 6 then $n$ is odd"},{key:"E",text:"if $n$ is even then $n$ is odd"} ],
    answer: "B", solution: "Contrapositive of $P\\Rightarrow Q$ is $\\lnot Q\\Rightarrow\\lnot P$: 'if $n$ is odd (not even) then $n$ is not a multiple of 6'." },
  { id: "tmua-ex-l05", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "Which value disproves the claim 'for all real $x$, $x^2\\ge x$'?",
    options: [ {key:"A",text:"$x=0$"},{key:"B",text:"$x=1$"},{key:"C",text:"$x=\\tfrac12$"},{key:"D",text:"$x=2$"},{key:"E",text:"$x=-1$"} ],
    answer: "C", solution: "At $x=\\tfrac12$: $x^2=\\tfrac14<\\tfrac12=x$, a counterexample. (At $0,1$ equality holds; at $2,-1$ the inequality holds.)" },
  { id: "tmua-ex-l06", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "The negation of 'there exists an integer $n$ with $n^2=2$' is:",
    options: [ {key:"A",text:"there exists an integer $n$ with $n^2\\ne2$"},{key:"B",text:"for all integers $n$, $n^2\\ne2$"},{key:"C",text:"for all integers $n$, $n^2=2$"},{key:"D",text:"there is no integer"},{key:"E",text:"$n^2=2$ is true"} ],
    answer: "B", solution: "The negation of 'there exists $n$: $P(n)$' is 'for all $n$: not $P(n)$'." },
  { id: "tmua-ex-l07", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "The negation of the statement '$x>0$ and $y>0$' is:",
    options: [ {key:"A",text:"$x<0$ and $y<0$"},{key:"B",text:"$x\\le0$ or $y\\le0$"},{key:"C",text:"$x\\le0$ and $y\\le0$"},{key:"D",text:"$x>0$ or $y>0$"},{key:"E",text:"$x\\ne0$ or $y\\ne0$"} ],
    answer: "B", solution: "By De Morgan, not($A$ and $B$) $=$ (not $A$) or (not $B$): $x\\le0$ or $y\\le0$." },
  { id: "tmua-ex-l08", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 1, marks: 1,
    question: "In TMUA convention, the statement '$A$ or $B$' (inclusive or) is FALSE only when:",
    options: [ {key:"A",text:"$A$ is true and $B$ is false"},{key:"B",text:"$A$ is false and $B$ is true"},{key:"C",text:"both $A$ and $B$ are false"},{key:"D",text:"both $A$ and $B$ are true"},{key:"E",text:"it is never false"} ],
    answer: "C", solution: "Inclusive 'or' is true when at least one holds, so it is false only when both are false." },
  { id: "tmua-ex-l09", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 3, marks: 1,
    question: "A student argues: 'From $x^2=x$, divide both sides by $x$ to get $x=1$.' The flaw is:",
    options: [ {key:"A",text:"there is no flaw"},{key:"B",text:"dividing by $x$ loses the solution $x=0$"},{key:"C",text:"$x^2=x$ has no solutions"},{key:"D",text:"you cannot square-root"},{key:"E",text:"$x=1$ is not a solution"} ],
    answer: "B", solution: "Dividing by $x$ assumes $x\\ne0$; but $x=0$ also satisfies $x^2=x$, so a solution is lost. Correct: $x^2-x=0\\Rightarrow x(x-1)=0\\Rightarrow x=0$ or $1$." },
  { id: "tmua-ex-l10", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "'All squares are rectangles, therefore all rectangles are squares.' The logical error is:",
    options: [ {key:"A",text:"a false premise"},{key:"B",text:"assuming the converse"},{key:"C",text:"dividing by zero"},{key:"D",text:"a counterexample"},{key:"E",text:"proof by contradiction"} ],
    answer: "B", solution: "The argument assumes that $P\\Rightarrow Q$ implies $Q\\Rightarrow P$ (the converse), which is not valid." },
  { id: "tmua-ex-l11", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 1, marks: 1,
    question: "Assuming $\\sqrt3$ is rational in order to derive a contradiction is an example of:",
    options: [ {key:"A",text:"direct proof"},{key:"B",text:"proof by contradiction"},{key:"C",text:"proof by cases"},{key:"D",text:"disproof by counterexample"},{key:"E",text:"proof by induction"} ],
    answer: "B", solution: "Assuming the negation of the claim to reach a contradiction is proof by contradiction." },
  { id: "tmua-ex-l12", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "To show '$n^2+n$ is even for every integer $n$' by treating $n$ even and $n$ odd separately is:",
    options: [ {key:"A",text:"proof by contradiction"},{key:"B",text:"proof by cases"},{key:"C",text:"disproof by counterexample"},{key:"D",text:"a circular argument"},{key:"E",text:"an inductive step"} ],
    answer: "B", solution: "Splitting into exhaustive cases (even/odd) and proving each is proof by cases." },
  { id: "tmua-ex-l13", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "The pattern $1=1$, $1+3=4$, $1+3+5=9$, $\\ldots$ suggests that the sum of the first $n$ odd numbers is:",
    options: [ {key:"A",text:"$2n-1$"},{key:"B",text:"$n^2$"},{key:"C",text:"$\\tfrac{n(n+1)}2$"},{key:"D",text:"$n(n+1)$"},{key:"E",text:"$2^n-1$"} ],
    answer: "B", solution: "The partial sums are $1,4,9,\\ldots=n^2$; making and justifying such a conjecture from small cases is a Paper 2 skill." },
  { id: "tmua-ex-l14", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 3, marks: 1,
    question: "Given that $P\\Rightarrow Q$, $Q\\Rightarrow R$ are both true, and that $R$ is false, what can be concluded?",
    options: [ {key:"A",text:"$P$ is true"},{key:"B",text:"$P$ is false"},{key:"C",text:"$Q$ is true"},{key:"D",text:"nothing"},{key:"E",text:"$R$ is true"} ],
    answer: "B", solution: "By contrapositive chaining: $\\lnot R\\Rightarrow\\lnot Q\\Rightarrow\\lnot P$. Since $R$ is false, $P$ must be false." },

  // ══════════ 代数（tmua-algebra）——9 题 ══════════
  { id: "tmua-ex-a01", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 1, marks: 1,
    question: "Expand and simplify $(1+\\sqrt2)^2$.",
    options: [ {key:"A",text:"$3$"},{key:"B",text:"$3+2\\sqrt2$"},{key:"C",text:"$1+2\\sqrt2$"},{key:"D",text:"$2+\\sqrt2$"},{key:"E",text:"$5$"} ],
    answer: "B", solution: "$(1+\\sqrt2)^2=1+2\\sqrt2+2=3+2\\sqrt2.$" },
  { id: "tmua-ex-a02", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "Solve $\\log_5(2x-1)=2$.",
    options: [ {key:"A",text:"$x=13$"},{key:"B",text:"$x=12$"},{key:"C",text:"$x=5$"},{key:"D",text:"$x=\\tfrac{11}2$"},{key:"E",text:"$x=26$"} ],
    answer: "A", solution: "$2x-1=5^2=25\\Rightarrow x=13.$" },
  { id: "tmua-ex-a03", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "Find the sum of the first $20$ terms of the arithmetic sequence with first term $3$ and common difference $2$.",
    options: [ {key:"A",text:"$400$"},{key:"B",text:"$440$"},{key:"C",text:"$420$"},{key:"D",text:"$460$"},{key:"E",text:"$380$"} ],
    answer: "B", solution: "$S_{20}=\\tfrac{20}{2}\\big(2\\cdot3+19\\cdot2\\big)=10(6+38)=440.$" },
  { id: "tmua-ex-a04", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "How many real roots does $x^2-6x+10=0$ have?",
    options: [ {key:"A",text:"$2$"},{key:"B",text:"$1$"},{key:"C",text:"$0$"},{key:"D",text:"infinitely many"},{key:"E",text:"cannot be determined"} ],
    answer: "C", solution: "Discriminant $=36-40=-4<0$, so there are no real roots." },
  { id: "tmua-ex-a05", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 3, marks: 1,
    question: "Solve the inequality $\\dfrac{x+1}{x-2}>0$.",
    options: [ {key:"A",text:"$-1<x<2$"},{key:"B",text:"$x<-1$ or $x>2$"},{key:"C",text:"$x>2$ only"},{key:"D",text:"$x<-1$ only"},{key:"E",text:"all $x\\ne2$"} ],
    answer: "B", solution: "The quotient is positive when numerator and denominator share a sign: $x>2$ (both positive) or $x<-1$ (both negative)." },
  { id: "tmua-ex-a06", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 1, marks: 1,
    question: "Evaluate $9^{1/2}+27^{1/3}$.",
    options: [ {key:"A",text:"$6$"},{key:"B",text:"$5$"},{key:"C",text:"$9$"},{key:"D",text:"$12$"},{key:"E",text:"$4$"} ],
    answer: "A", solution: "$9^{1/2}=3$ and $27^{1/3}=3$, so the sum is $6.$" },
  { id: "tmua-ex-a07", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "If $2^x=5$, what is the value of $4^x$?",
    options: [ {key:"A",text:"$10$"},{key:"B",text:"$20$"},{key:"C",text:"$25$"},{key:"D",text:"$16$"},{key:"E",text:"$625$"} ],
    answer: "C", solution: "$4^x=(2^x)^2=5^2=25.$" },
  { id: "tmua-ex-a08", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 1, marks: 1,
    question: "The geometric mean of $4$ and $9$ is:",
    options: [ {key:"A",text:"$6$"},{key:"B",text:"$6.5$"},{key:"C",text:"$\\sqrt{13}$"},{key:"D",text:"$36$"},{key:"E",text:"$5$"} ],
    answer: "A", solution: "Geometric mean $=\\sqrt{4\\times9}=\\sqrt{36}=6.$" },
  { id: "tmua-ex-a09", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 3, marks: 1,
    question: "Simplify $\\dfrac{x^2-9}{x^2-x-6}$ (for permissible $x$).",
    options: [ {key:"A",text:"$\\dfrac{x-3}{x-2}$"},{key:"B",text:"$\\dfrac{x+3}{x+2}$"},{key:"C",text:"$\\dfrac{x-3}{x+2}$"},{key:"D",text:"$\\dfrac{x+3}{x-2}$"},{key:"E",text:"$1$"} ],
    answer: "B", solution: "$\\dfrac{(x-3)(x+3)}{(x-3)(x+2)}=\\dfrac{x+3}{x+2}$ after cancelling $(x-3)$." },

  // ══════════ 微积分与坐标几何（tmua-calc）——8 题 ══════════
  { id: "tmua-ex-c01", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 2, marks: 1,
    question: "The derivative of $x^3-2x^2+x$ at $x=1$ is:",
    options: [ {key:"A",text:"$0$"},{key:"B",text:"$1$"},{key:"C",text:"$2$"},{key:"D",text:"$-1$"},{key:"E",text:"$3$"} ],
    answer: "A", solution: "$\\dfrac{d}{dx}=3x^2-4x+1$; at $x=1$: $3-4+1=0.$" },
  { id: "tmua-ex-c02", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 1, marks: 1,
    question: "Evaluate $\\displaystyle\\int_1^3 2x\\,\\mathrm{d}x$.",
    options: [ {key:"A",text:"$6$"},{key:"B",text:"$8$"},{key:"C",text:"$9$"},{key:"D",text:"$4$"},{key:"E",text:"$12$"} ],
    answer: "B", solution: "$[x^2]_1^3=9-1=8.$" },
  { id: "tmua-ex-c03", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 2, marks: 1,
    question: "The gradient of the tangent to $y=\\dfrac1x$ at $x=1$ is:",
    options: [ {key:"A",text:"$1$"},{key:"B",text:"$-1$"},{key:"C",text:"$\\tfrac12$"},{key:"D",text:"$-\\tfrac12$"},{key:"E",text:"$0$"} ],
    answer: "B", solution: "$y'=-x^{-2}$; at $x=1$, $y'=-1.$" },
  { id: "tmua-ex-c04", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 1, marks: 1,
    question: "The minimum value of $y=x^2-6x+11$ occurs at $x=$",
    options: [ {key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$6$"},{key:"D",text:"$-3$"},{key:"E",text:"$11$"} ],
    answer: "B", solution: "$y=(x-3)^2+2$, minimum at $x=3.$" },
  { id: "tmua-ex-c05", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 3, marks: 1,
    question: "The area enclosed between $y=4-x^2$ and the $x$-axis is:",
    options: [ {key:"A",text:"$\\tfrac{16}{3}$"},{key:"B",text:"$\\tfrac{32}{3}$"},{key:"C",text:"$8$"},{key:"D",text:"$16$"},{key:"E",text:"$\\tfrac{20}{3}$"} ],
    answer: "B", solution: "Roots at $x=\\pm2$. $\\int_{-2}^{2}(4-x^2)\\,dx=\\left[4x-\\tfrac{x^3}{3}\\right]_{-2}^{2}=\\tfrac{16}{3}-\\left(-\\tfrac{16}{3}\\right)=\\tfrac{32}{3}.$" },
  { id: "tmua-ex-c06", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 2, marks: 1,
    question: "A line perpendicular to $y=3x+2$ has gradient:",
    options: [ {key:"A",text:"$3$"},{key:"B",text:"$-3$"},{key:"C",text:"$\\tfrac13$"},{key:"D",text:"$-\\tfrac13$"},{key:"E",text:"$-2$"} ],
    answer: "D", solution: "Perpendicular gradients multiply to $-1$: $-\\tfrac13.$" },
  { id: "tmua-ex-c07", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 3, marks: 1,
    question: "The normal to the curve $y=x^2$ at the point $(1,1)$ has gradient:",
    options: [ {key:"A",text:"$2$"},{key:"B",text:"$-\\tfrac12$"},{key:"C",text:"$\\tfrac12$"},{key:"D",text:"$-2$"},{key:"E",text:"$1$"} ],
    answer: "B", solution: "Tangent gradient $y'=2x=2$ at $x=1$; the normal gradient is $-\\tfrac{1}{2}.$" },
  { id: "tmua-ex-c08", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 3, marks: 1,
    question: "How many stationary points does $y=x^4-2x^2$ have?",
    options: [ {key:"A",text:"$1$"},{key:"B",text:"$2$"},{key:"C",text:"$3$"},{key:"D",text:"$4$"},{key:"E",text:"$0$"} ],
    answer: "C", solution: "$y'=4x^3-4x=4x(x-1)(x+1)=0\\Rightarrow x=0,\\pm1$: three stationary points." },

  // ══════════ 离散/计数（tmua-discrete）——5 题 ══════════
  { id: "tmua-ex-d01", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 1, marks: 1,
    question: "In how many ways can $3$ items be chosen from $8$ distinct items?",
    options: [ {key:"A",text:"$24$"},{key:"B",text:"$56$"},{key:"C",text:"$336$"},{key:"D",text:"$512$"},{key:"E",text:"$120$"} ],
    answer: "B", solution: "$\\binom{8}{3}=\\dfrac{8\\cdot7\\cdot6}{6}=56.$" },
  { id: "tmua-ex-d02", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 2, marks: 1,
    question: "How many two-digit numbers are even?",
    options: [ {key:"A",text:"$45$"},{key:"B",text:"$50$"},{key:"C",text:"$40$"},{key:"D",text:"$44$"},{key:"E",text:"$90$"} ],
    answer: "A", solution: "Even two-digit numbers run $10,12,\\ldots,98$: $\\dfrac{98-10}{2}+1=45.$" },
  { id: "tmua-ex-d03", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 2, marks: 1,
    question: "For every integer $n$, the product $n(n+1)$ is always divisible by:",
    options: [ {key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$4$"},{key:"D",text:"$5$"},{key:"E",text:"$6$"} ],
    answer: "A", solution: "Among two consecutive integers one is even, so the product is always divisible by $2.$" },
  { id: "tmua-ex-d04", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 2, marks: 1,
    question: "How many diagonals does a hexagon have?",
    options: [ {key:"A",text:"$6$"},{key:"B",text:"$9$"},{key:"C",text:"$12$"},{key:"D",text:"$15$"},{key:"E",text:"$18$"} ],
    answer: "B", solution: "$\\binom{6}{2}-6=15-6=9$ (all vertex pairs minus the sides)." },
  { id: "tmua-ex-d05", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 1, marks: 1,
    question: "How many subsets does a set with $4$ elements have?",
    options: [ {key:"A",text:"$8$"},{key:"B",text:"$16$"},{key:"C",text:"$4$"},{key:"D",text:"$12$"},{key:"E",text:"$24$"} ],
    answer: "B", solution: "$2^4=16.$" },

  // ══════════ 概率/统计（tmua-stats）——4 题 ══════════
  { id: "tmua-ex-s01", type: "mcq", testId: "tmua", topicId: "tmua-stats", difficulty: 2, marks: 1,
    question: "Two fair dice are rolled. What is the probability that their sum is $7$?",
    options: [ {key:"A",text:"$\\tfrac16$"},{key:"B",text:"$\\tfrac15$"},{key:"C",text:"$\\tfrac{7}{36}$"},{key:"D",text:"$\\tfrac1{12}$"},{key:"E",text:"$\\tfrac18$"} ],
    answer: "A", solution: "There are $6$ ways to make $7$ out of $36$ outcomes: $\\tfrac{6}{36}=\\tfrac16.$" },
  { id: "tmua-ex-s02", type: "mcq", testId: "tmua", topicId: "tmua-stats", difficulty: 2, marks: 1,
    question: "A fair coin is tossed $3$ times. What is the probability of at least one head?",
    options: [ {key:"A",text:"$\\tfrac78$"},{key:"B",text:"$\\tfrac34$"},{key:"C",text:"$\\tfrac12$"},{key:"D",text:"$\\tfrac38$"},{key:"E",text:"$\\tfrac18$"} ],
    answer: "A", solution: "$P(\\text{at least one head})=1-P(\\text{no heads})=1-\\tfrac18=\\tfrac78.$" },
  { id: "tmua-ex-s03", type: "mcq", testId: "tmua", topicId: "tmua-stats", difficulty: 3, marks: 1,
    question: "A card is drawn from a standard $52$-card deck. What is the probability it is a king or a heart?",
    options: [ {key:"A",text:"$\\tfrac{4}{13}$"},{key:"B",text:"$\\tfrac{17}{52}$"},{key:"C",text:"$\\tfrac{1}{4}$"},{key:"D",text:"$\\tfrac{5}{13}$"},{key:"E",text:"$\\tfrac{16}{52}$"} ],
    answer: "A", solution: "$P(K)+P(\\heartsuit)-P(K\\heartsuit)=\\tfrac{4}{52}+\\tfrac{13}{52}-\\tfrac{1}{52}=\\tfrac{16}{52}=\\tfrac{4}{13}.$" },
  { id: "tmua-ex-s04", type: "mcq", testId: "tmua", topicId: "tmua-stats", difficulty: 1, marks: 1,
    question: "The mean of $2, 4, 6, 8, 10$ is:",
    options: [ {key:"A",text:"$5$"},{key:"B",text:"$6$"},{key:"C",text:"$7$"},{key:"D",text:"$30$"},{key:"E",text:"$4$"} ],
    answer: "B", solution: "$\\dfrac{2+4+6+8+10}{5}=\\dfrac{30}{5}=6.$" },
];
