import type { MCQQuestion } from "./types";

export const TMUA_REASONING_ROUND_2: MCQQuestion[] = [
  { id: "tmua-r2-a01", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 3, marks: 1,
    question: "For which values of $k$ does $x^2-2(k+1)x+k^2+1=0$ have two distinct real roots?",
    options: [{key:"A",text:"$k<0$"},{key:"B",text:"$k=0$"},{key:"C",text:"$k>0$"},{key:"D",text:"$k>-1$"},{key:"E",text:"all real $k$"}],
    answer: "C", solution: "The discriminant is $4(k+1)^2-4(k^2+1)=8k$. Two distinct real roots require $8k>0$, hence $k>0$." },
  { id: "tmua-r2-a02", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 3, marks: 1,
    question: "What is the range of $f(x)=\\dfrac{x^2+1}{x^2+2}$ for real $x$?",
    options: [{key:"A",text:"$0<f<1$"},{key:"B",text:"$\\tfrac12\\le f<1$"},{key:"C",text:"$\\tfrac12<f\\le1$"},{key:"D",text:"$0\\le f\\le\\tfrac12$"},{key:"E",text:"$f\\ge\\tfrac12$"}],
    answer: "B", solution: "Write $f=1-1/(x^2+2)$. Since $x^2+2\\ge2$, the minimum is $1/2$ at $x=0$, while $f$ approaches but never reaches $1$." },
  { id: "tmua-r2-a03", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 3, marks: 1,
    question: "How many real solutions does $|x^2-1|=x$ have?",
    options: [{key:"A",text:"$0$"},{key:"B",text:"$1$"},{key:"C",text:"$2$"},{key:"D",text:"$3$"},{key:"E",text:"$4$"}],
    answer: "C", solution: "The right side requires $x\\ge0$. For $0\\le x<1$, $1-x^2=x$ has one positive root. For $x\\ge1$, $x^2-1=x$ has one root at $(1+\\sqrt5)/2$. Total: two." },
  { id: "tmua-r2-a04", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "What is the coefficient of $x^5$ in $(1-x^2)^4(1+x)$?",
    options: [{key:"A",text:"$-6$"},{key:"B",text:"$-4$"},{key:"C",text:"$4$"},{key:"D",text:"$6$"},{key:"E",text:"$12$"}],
    answer: "D", solution: "Only $x$ from $(1+x)$ can combine with an $x^4$ term. The coefficient of $x^4$ in $(1-x^2)^4$ is $\\binom42(-1)^2=6$." },
  { id: "tmua-r2-a05", type: "mcq", testId: "tmua", topicId: "tmua-algebra", difficulty: 2, marks: 1,
    question: "A geometric series has sum $12$, and the sum of the squares of its terms is $48$. Its first term is:",
    options: [{key:"A",text:"$3$"},{key:"B",text:"$4$"},{key:"C",text:"$6$"},{key:"D",text:"$8$"},{key:"E",text:"$9$"}],
    answer: "C", solution: "$a/(1-r)=12$ and $a^2/(1-r^2)=48$. Dividing gives $a/(1+r)=4$. Solving $a=12(1-r)=4(1+r)$ gives $r=1/2$ and $a=6$." },

  { id: "tmua-r2-c01", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 2, marks: 1,
    question: "For which values of $a$ does $f(x)=x^3-3ax$ have two distinct stationary points?",
    options: [{key:"A",text:"$a<0$"},{key:"B",text:"$a=0$"},{key:"C",text:"$a>0$"},{key:"D",text:"$a\\ne0$"},{key:"E",text:"all real $a$"}],
    answer: "C", solution: "$f'(x)=3(x^2-a)$. There are two distinct real stationary points $x=\\pm\\sqrt a$ exactly when $a>0$." },
  { id: "tmua-r2-c02", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 2, marks: 1,
    question: "Evaluate $\\displaystyle\\int_{-2}^{2}\\frac{x^3}{1+x^2}\\,dx$.",
    options: [{key:"A",text:"$-4$"},{key:"B",text:"$-2$"},{key:"C",text:"$0$"},{key:"D",text:"$2$"},{key:"E",text:"$4$"}],
    answer: "C", solution: "The integrand is odd because the numerator is odd and the denominator is even. Its integral over the symmetric interval $[-2,2]$ is $0$." },
  { id: "tmua-r2-c03", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 3, marks: 1,
    question: "The finite region enclosed by $y=x$ and $y=x^2$ has area:",
    options: [{key:"A",text:"$\\tfrac1{12}$"},{key:"B",text:"$\\tfrac16$"},{key:"C",text:"$\\tfrac14$"},{key:"D",text:"$\\tfrac13$"},{key:"E",text:"$\\tfrac12$"}],
    answer: "B", solution: "The curves meet at $x=0,1$, with $x\\ge x^2$ between them. The area is $\\int_0^1(x-x^2)\\,dx=1/2-1/3=1/6$." },
  { id: "tmua-r2-c04", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 3, marks: 1,
    question: "The tangent to $y=\\ln x$ at $x=e$ crosses the $x$-axis at:",
    options: [{key:"A",text:"$x=-e$"},{key:"B",text:"$x=-1$"},{key:"C",text:"$x=0$"},{key:"D",text:"$x=1$"},{key:"E",text:"$x=e$"}],
    answer: "C", solution: "At $x=e$, the point is $(e,1)$ and the gradient is $1/e$. Thus $y-1=(x-e)/e$, so $y=x/e$ and the $x$-intercept is $0$." },
  { id: "tmua-r2-c05", type: "mcq", testId: "tmua", topicId: "tmua-calc", difficulty: 3, marks: 1,
    question: "For $x>0$, the minimum value of $x+\\dfrac4x$ is:",
    options: [{key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$4$"},{key:"D",text:"$5$"},{key:"E",text:"$8$"}],
    answer: "C", solution: "By AM-GM, $x+4/x\\ge2\\sqrt{x(4/x)}=4$, with equality when $x=4/x$, i.e. $x=2$." },

  { id: "tmua-r2-s01", type: "mcq", testId: "tmua", topicId: "tmua-stats", difficulty: 3, marks: 1,
    question: "A bag contains $3$ red and $2$ blue counters. Two are drawn without replacement. Given that at least one is red, what is the probability that both are red?",
    options: [{key:"A",text:"$\\tfrac15$"},{key:"B",text:"$\\tfrac14$"},{key:"C",text:"$\\tfrac13$"},{key:"D",text:"$\\tfrac25$"},{key:"E",text:"$\\tfrac12$"}],
    answer: "C", solution: "There are $\\binom52=10$ pairs, but the one blue-blue pair is excluded by the condition. Of the remaining $9$, $\\binom32=3$ are red-red, giving $3/9=1/3$." },
  { id: "tmua-r2-s02", type: "mcq", testId: "tmua", topicId: "tmua-stats", difficulty: 2, marks: 1,
    question: "A fair six-sided die shows $X$. What is $\\mathbb E(X^2)$?",
    options: [{key:"A",text:"$\\tfrac{35}{6}$"},{key:"B",text:"$\\tfrac{49}{6}$"},{key:"C",text:"$\\tfrac{77}{6}$"},{key:"D",text:"$\\tfrac{91}{6}$"},{key:"E",text:"$\\tfrac{49}{2}$"}],
    answer: "D", solution: "$\\mathbb E(X^2)=(1^2+2^2+3^2+4^2+5^2+6^2)/6=91/6$." },
  { id: "tmua-r2-s03", type: "mcq", testId: "tmua", topicId: "tmua-stats", difficulty: 2, marks: 1,
    question: "A fair coin is tossed four times. The probability of exactly two heads is:",
    options: [{key:"A",text:"$\\tfrac14$"},{key:"B",text:"$\\tfrac38$"},{key:"C",text:"$\\tfrac12$"},{key:"D",text:"$\\tfrac58$"},{key:"E",text:"$\\tfrac34$"}],
    answer: "B", solution: "There are $2^4=16$ equally likely sequences and $\\binom42=6$ with exactly two heads, so the probability is $6/16=3/8$." },
  { id: "tmua-r2-s04", type: "mcq", testId: "tmua", topicId: "tmua-stats", difficulty: 3, marks: 1,
    question: "A random variable $X$ has mean $5$ and variance $4$. If $Y=3X-2$, what are the mean and variance of $Y$?",
    options: [{key:"A",text:"$13,10$"},{key:"B",text:"$13,12$"},{key:"C",text:"$13,36$"},{key:"D",text:"$15,36$"},{key:"E",text:"$17,12$"}],
    answer: "C", solution: "$\\mathbb E(Y)=3(5)-2=13$, while $\\operatorname{Var}(Y)=3^2\\operatorname{Var}(X)=9(4)=36$." },
  { id: "tmua-r2-s05", type: "mcq", testId: "tmua", topicId: "tmua-stats", difficulty: 3, marks: 1,
    question: "Events $A$ and $B$ are independent. If $P(A)=0.6$ and $P(A\\cup B)=0.8$, then $P(B)=$",
    options: [{key:"A",text:"$0.2$"},{key:"B",text:"$0.3$"},{key:"C",text:"$0.4$"},{key:"D",text:"$0.5$"},{key:"E",text:"$0.6$"}],
    answer: "D", solution: "Independence gives $0.8=0.6+p-0.6p=0.6+0.4p$, so $p=0.5$." },

  { id: "tmua-r2-l01", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "Which statement is the negation of 'Every member of $S$ has property $P$'?",
    options: [{key:"A",text:"No member of $S$ has $P$"},{key:"B",text:"Every member of $S$ lacks $P$"},{key:"C",text:"Some member of $S$ lacks $P$"},{key:"D",text:"Some member of $S$ has $P$"},{key:"E",text:"$S$ is empty"}],
    answer: "C", solution: "The negation of $\\forall x\\in S, P(x)$ is $\\exists x\\in S$ such that $\\neg P(x)$." },
  { id: "tmua-r2-l02", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 3, marks: 1,
    question: "Suppose $P\\Rightarrow Q$ and $R\\Rightarrow Q$ are both true. Which conclusion must follow?",
    options: [{key:"A",text:"$P\\Rightarrow R$"},{key:"B",text:"$R\\Rightarrow P$"},{key:"C",text:"$Q\\Rightarrow(P\\lor R)$"},{key:"D",text:"$(P\\lor R)\\Rightarrow Q$"},{key:"E",text:"$P\\Leftrightarrow R$"}],
    answer: "D", solution: "If either $P$ or $R$ holds, the corresponding implication gives $Q$. None of the premises gives a relationship between $P$ and $R$, nor a converse from $Q$." },
  { id: "tmua-r2-l03", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 3, marks: 1,
    question: "Which is a counterexample to the claim: for every integer $n$, if $n^2$ is even then $n$ is divisible by $4$?",
    options: [{key:"A",text:"$n=0$"},{key:"B",text:"$n=1$"},{key:"C",text:"$n=2$"},{key:"D",text:"$n=4$"},{key:"E",text:"$n=8$"}],
    answer: "C", solution: "For $n=2$, $n^2=4$ is even, but $2$ is not divisible by $4$. This makes the hypothesis true and conclusion false." },
  { id: "tmua-r2-l04", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 2, marks: 1,
    question: "The contrapositive of 'If $x>2$, then $x^2>4$' is:",
    options: [{key:"A",text:"If $x^2>4$, then $x>2$"},{key:"B",text:"If $x\\le2$, then $x^2\\le4$"},{key:"C",text:"If $x^2\\le4$, then $x\\le2$"},{key:"D",text:"If $x^2<4$, then $x<2$"},{key:"E",text:"If $x>2$, then $x^2\\le4$"}],
    answer: "C", solution: "The contrapositive of $P\\Rightarrow Q$ is $\\neg Q\\Rightarrow\\neg P$. Here that is $x^2\\le4\\Rightarrow x\\le2$." },
  { id: "tmua-r2-l05", type: "mcq", testId: "tmua", topicId: "tmua-logic", difficulty: 3, marks: 1,
    question: "Which is logically equivalent to 'There is no real $x$ for which both $P(x)$ and $Q(x)$ hold'?",
    options: [{key:"A",text:"For every real $x$, $P(x)\\Rightarrow\\neg Q(x)$"},{key:"B",text:"For every real $x$, $P(x)\\Rightarrow Q(x)$"},{key:"C",text:"There is a real $x$ for which neither holds"},{key:"D",text:"For every real $x$, neither $P(x)$ nor $Q(x)$ holds"},{key:"E",text:"There is no real $x$ for which $P(x)$ holds"}],
    answer: "A", solution: "$\\neg\\exists x(P(x)\\land Q(x))$ is equivalent to $\\forall x\\neg(P(x)\\land Q(x))$, hence $\\forall x(P(x)\\Rightarrow\\neg Q(x))$." },

  { id: "tmua-r2-d01", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 3, marks: 1,
    question: "What is the remainder when $3^{100}$ is divided by $7$?",
    options: [{key:"A",text:"$1$"},{key:"B",text:"$2$"},{key:"C",text:"$3$"},{key:"D",text:"$4$"},{key:"E",text:"$6$"}],
    answer: "D", solution: "Powers of $3$ modulo $7$ have period $6$. Since $100\\equiv4\\pmod6$, $3^{100}\\equiv3^4=81\\equiv4\\pmod7$." },
  { id: "tmua-r2-d02", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 2, marks: 1,
    question: "How many five-character numerical codes can be formed from the digits $0$ to $9$ if no digit is repeated?",
    options: [{key:"A",text:"$15120$"},{key:"B",text:"$27216$"},{key:"C",text:"$30240$"},{key:"D",text:"$59049$"},{key:"E",text:"$100000$"}],
    answer: "C", solution: "A code may begin with zero, so the number is $10\\times9\\times8\\times7\\times6=30240$." },
  { id: "tmua-r2-d03", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 2, marks: 1,
    question: "A graph has $8$ vertices, each of degree $3$. How many edges does it have?",
    options: [{key:"A",text:"$8$"},{key:"B",text:"$10$"},{key:"C",text:"$12$"},{key:"D",text:"$16$"},{key:"E",text:"$24$"}],
    answer: "C", solution: "The sum of degrees is $8\\cdot3=24$. Each edge contributes $2$ to this sum, so there are $24/2=12$ edges." },
  { id: "tmua-r2-d04", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 3, marks: 1,
    question: "A sequence satisfies $a_1=2$ and $a_{n+1}=3a_n-2$. What is $a_4$?",
    options: [{key:"A",text:"$20$"},{key:"B",text:"$24$"},{key:"C",text:"$26$"},{key:"D",text:"$28$"},{key:"E",text:"$30$"}],
    answer: "D", solution: "Subtract the fixed point $1$: $a_{n+1}-1=3(a_n-1)$. Thus $a_n=1+3^{n-1}$, and $a_4=1+27=28$." },
  { id: "tmua-r2-d05", type: "mcq", testId: "tmua", topicId: "tmua-discrete", difficulty: 3, marks: 1,
    question: "How many subsets of an $8$-element set contain an even number of elements?",
    options: [{key:"A",text:"$64$"},{key:"B",text:"$120$"},{key:"C",text:"$127$"},{key:"D",text:"$128$"},{key:"E",text:"$256$"}],
    answer: "D", solution: "Pair each subset with the subset obtained by toggling one fixed element. Exactly one member of each pair has even size, so half of all $2^8$ subsets qualify: $2^7=128$." },
];
