import type { MCQQuestion } from "./types";

// Official-spec gap fill: coordinate geometry/trigonometry and number/ratio/estimation.
// The batch is calculator-free and uses only TMUA Section 1 knowledge.
export const TMUA_SPEC_COVERAGE: MCQQuestion[] = [
  { id: "tmua-spec-g01", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 2, marks: 1,
    question: "The line $L$ passes through $(2,-1)$ and is perpendicular to $3x-2y=7$. Which is an equation of $L$?",
    options: [{key:"A",text:"$3x-2y=8$"},{key:"B",text:"$2x-3y=7$"},{key:"C",text:"$3x+2y=4$"},{key:"D",text:"$2x+3y=7$"},{key:"E",text:"$2x+3y=1$"}],
    answer: "E", solution: "The given line has gradient $3/2$, so $L$ has gradient $-2/3$. Hence $y+1=-\\frac23(x-2)$, which rearranges to $2x+3y=1$." },
  { id: "tmua-spec-g02", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 2, marks: 1,
    question: "What are the centre and radius of $x^2+y^2-6x+4y-12=0$?",
    options: [{key:"A",text:"centre $(-3,2)$, radius $5$"},{key:"B",text:"centre $(3,-2)$, radius $3$"},{key:"C",text:"centre $(3,2)$, radius $5$"},{key:"D",text:"centre $(-3,-2)$, radius $5$"},{key:"E",text:"centre $(3,-2)$, radius $5$"}],
    answer: "E", solution: "Completing squares gives $(x-3)^2+(y+2)^2=25$. The centre is $(3,-2)$ and the radius is $5$." },
  { id: "tmua-spec-g03", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 2, marks: 1,
    question: "A chord of a circle of radius $5$ is at distance $3$ from the centre. What is the chord length?",
    options: [{key:"A",text:"$4$"},{key:"B",text:"$5$"},{key:"C",text:"$6$"},{key:"D",text:"$8$"},{key:"E",text:"$10$"}],
    answer: "D", solution: "The perpendicular from the centre bisects the chord. Half the chord is $\\sqrt{5^2-3^2}=4$, so the full chord is $8$." },
  { id: "tmua-spec-g04", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 3, marks: 1,
    question: "Which line is tangent to $x^2+y^2=25$ at $(3,4)$?",
    options: [{key:"A",text:"$4x+3y=25$"},{key:"B",text:"$3x-4y=25$"},{key:"C",text:"$4x-3y=0$"},{key:"D",text:"$3x+4y=20$"},{key:"E",text:"$3x+4y=25$"}],
    answer: "E", solution: "The radius to $(3,4)$ has gradient $4/3$, so the tangent has gradient $-3/4$. The line through $(3,4)$ is $3x+4y=25$." },
  { id: "tmua-spec-g05", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 1, marks: 1,
    question: "An arc subtends an angle of $140^\\circ$ at the centre of a circle. What angle does the same arc subtend at the circumference?",
    options: [{key:"A",text:"$35^\\circ$"},{key:"B",text:"$60^\\circ$"},{key:"C",text:"$70^\\circ$"},{key:"D",text:"$140^\\circ$"},{key:"E",text:"$280^\\circ$"}],
    answer: "C", solution: "The angle at the centre is twice the angle at the circumference standing on the same arc, so the required angle is $70^\\circ$." },
  { id: "tmua-spec-g06", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 1, marks: 1,
    question: "In a cyclic quadrilateral, one angle is $112^\\circ$. What is the opposite angle?",
    options: [{key:"A",text:"$22^\\circ$"},{key:"B",text:"$56^\\circ$"},{key:"C",text:"$78^\\circ$"},{key:"D",text:"$112^\\circ$"},{key:"E",text:"$68^\\circ$"}],
    answer: "E", solution: "Opposite angles in a cyclic quadrilateral sum to $180^\\circ$, so the angle is $180^\\circ-112^\\circ=68^\\circ$." },
  { id: "tmua-spec-g07", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 2, marks: 1,
    question: "Two sides of a triangle have lengths $5$ and $7$, and their included angle is $60^\\circ$. What is the third side length?",
    options: [{key:"A",text:"$2$"},{key:"B",text:"$\\sqrt{29}$"},{key:"C",text:"$6$"},{key:"D",text:"$\\sqrt{39}$"},{key:"E",text:"$\\sqrt{74}$"}],
    answer: "D", solution: "By the cosine rule, $c^2=5^2+7^2-2(5)(7)\\cos60^\\circ=25+49-35=39$, so $c=\\sqrt{39}$." },
  { id: "tmua-spec-g08", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 2, marks: 1,
    question: "A sector has radius $6$ and angle $2\\pi/3$ radians. What is its area?",
    options: [{key:"A",text:"$4\\pi$"},{key:"B",text:"$6\\pi$"},{key:"C",text:"$8\\pi$"},{key:"D",text:"$24\\pi$"},{key:"E",text:"$12\\pi$"}],
    answer: "E", solution: "Sector area is $\\frac12r^2\\theta=\\frac12(36)(2\\pi/3)=12\\pi$." },
  { id: "tmua-spec-g09", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 1, marks: 1,
    question: "What is the length of an arc of radius $4$ that subtends $3\\pi/5$ radians at the centre?",
    options: [{key:"A",text:"$12\\pi/5$"},{key:"B",text:"$6\\pi/5$"},{key:"C",text:"$8\\pi/5$"},{key:"D",text:"$3\\pi/5$"},{key:"E",text:"$16\\pi/5$"}],
    answer: "A", solution: "Arc length is $r\\theta=4(3\\pi/5)=12\\pi/5$." },
  { id: "tmua-spec-g10", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 3, marks: 1,
    question: "How many solutions does $2\\sin^2x-3\\sin x+1=0$ have for $0\\le x<2\\pi$?",
    options: [{key:"A",text:"$0$"},{key:"B",text:"$1$"},{key:"C",text:"$2$"},{key:"D",text:"$4$"},{key:"E",text:"$3$"}],
    answer: "E", solution: "Factor to $(2\\sin x-1)(\\sin x-1)=0$. The equation $\\sin x=1/2$ has two solutions and $\\sin x=1$ has one, giving three in total." },
  { id: "tmua-spec-g11", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 2, marks: 1,
    question: "Which are all the solutions of $\\tan\\theta=-1$ for $0\\le\\theta<2\\pi$?",
    options: [{key:"A",text:"$\\pi/4,5\\pi/4$"},{key:"B",text:"$3\\pi/4,7\\pi/4$"},{key:"C",text:"$\\pi/4,7\\pi/4$"},{key:"D",text:"$3\\pi/4,5\\pi/4$"},{key:"E",text:"$7\\pi/4$ only"}],
    answer: "B", solution: "Tangent is negative in quadrants II and IV, with reference angle $\\pi/4$. Hence $\\theta=3\\pi/4$ or $7\\pi/4$." },
  { id: "tmua-spec-g12", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 3, marks: 1,
    question: "How many points of intersection are there between $y=2x+1$ and $x^2+y^2=5$?",
    options: [{key:"A",text:"none"},{key:"B",text:"one"},{key:"C",text:"three"},{key:"D",text:"infinitely many"},{key:"E",text:"two"}],
    answer: "E", solution: "Substitution gives $x^2+(2x+1)^2=5$, or $5x^2+4x-4=0$. Its discriminant is $4^2-4(5)(-4)=96>0$, so there are two intersections." },
  { id: "tmua-spec-g13", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 2, marks: 1,
    question: "A circle has centre $(1,2)$ and is tangent to the $x$-axis. Which is its equation?",
    options: [{key:"A",text:"$(x-1)^2+(y-2)^2=1$"},{key:"B",text:"$(x+1)^2+(y+2)^2=4$"},{key:"C",text:"$(x-1)^2+(y+2)^2=4$"},{key:"D",text:"$(x-1)^2+(y-2)^2=4$"},{key:"E",text:"$(x+1)^2+(y-2)^2=2$"}],
    answer: "D", solution: "The distance from the centre to the $x$-axis is $2$, so the radius is $2$. Thus $(x-1)^2+(y-2)^2=4$." },
  { id: "tmua-spec-g14", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 2, marks: 1,
    question: "What is the area of the triangle with vertices $(0,0)$, $(6,0)$ and $(2,4)$?",
    options: [{key:"A",text:"$6$"},{key:"B",text:"$8$"},{key:"C",text:"$10$"},{key:"D",text:"$24$"},{key:"E",text:"$12$"}],
    answer: "E", solution: "Take the base on the $x$-axis: base $=6$ and perpendicular height $=4$. The area is $\\frac12(6)(4)=12$." },
  { id: "tmua-spec-g15", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 2, marks: 1,
    question: "The vectors $\\binom{2}{-1}$ and $\\binom{k}{4}$ are perpendicular. What is $k$?",
    options: [{key:"A",text:"$-4$"},{key:"B",text:"$-2$"},{key:"C",text:"$2$"},{key:"D",text:"$4$"},{key:"E",text:"$8$"}],
    answer: "C", solution: "Perpendicular vectors have zero scalar product: $2k+(-1)(4)=0$, so $2k=4$ and $k=2$." },
  { id: "tmua-spec-g16", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 3, marks: 1,
    question: "Relative to $y=f(x)$, which description gives the graph of $y=f(2x-4)$?",
    options: [{key:"A",text:"stretch horizontally by factor $2$, then translate right $4$"},{key:"B",text:"compress horizontally by factor $1/2$, then translate right $4$"},{key:"C",text:"stretch vertically by factor $2$, then translate left $2$"},{key:"D",text:"compress vertically by factor $1/2$, then translate right $2$"},{key:"E",text:"compress horizontally by factor $1/2$, then translate right $2$"}],
    answer: "E", solution: "Since $2x-4=2(x-2)$, the factor $2$ inside compresses horizontally by $1/2$, and $x-2$ translates the graph $2$ units right." },
  { id: "tmua-spec-g17", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 3, marks: 1,
    question: "The points $(-2,1)$ and $(4,5)$ are endpoints of a diameter of a circle. What is the radius?",
    options: [{key:"A",text:"$\\sqrt5$"},{key:"B",text:"$\\sqrt{10}$"},{key:"C",text:"$2\\sqrt{13}$"},{key:"D",text:"$\\sqrt{13}$"},{key:"E",text:"$\\sqrt{52}$"}],
    answer: "D", solution: "The diameter is $\\sqrt{(4+2)^2+(5-1)^2}=\\sqrt{52}=2\\sqrt{13}$. The radius is half of this, $\\sqrt{13}$." },
  { id: "tmua-spec-g18", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 3, marks: 1,
    question: "In triangle $ABC$, $a=6$, $b=10$ and $A=30^\\circ$. How many possible values of angle $B$ are there?",
    options: [{key:"A",text:"none"},{key:"B",text:"one, and it is acute"},{key:"C",text:"one, and it is obtuse"},{key:"D",text:"three"},{key:"E",text:"two"}],
    answer: "E", solution: "The sine rule gives $\\sin B/10=\\sin30^\\circ/6$, so $\\sin B=5/6$. Both an acute angle and its obtuse supplement are compatible with $A=30^\\circ$, giving two triangles." },
  { id: "tmua-spec-g19", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 1, marks: 1,
    question: "Which are all the solutions of $\\cos x=-1/2$ for $0\\le x<2\\pi$?",
    options: [{key:"A",text:"$2\\pi/3,4\\pi/3$"},{key:"B",text:"$\\pi/3,5\\pi/3$"},{key:"C",text:"$\\pi/3,2\\pi/3$"},{key:"D",text:"$4\\pi/3,5\\pi/3$"},{key:"E",text:"$2\\pi/3$ only"}],
    answer: "A", solution: "Cosine is negative in quadrants II and III with reference angle $\\pi/3$, so $x=2\\pi/3$ or $4\\pi/3$." },
  { id: "tmua-spec-g20", type: "mcq", testId: "tmua", topicId: "tmua-geometry", difficulty: 2, marks: 1,
    question: "A tangent and a chord meet at a point on a circle, forming an angle of $38^\\circ$. What is the angle in the alternate segment subtended by that chord?",
    options: [{key:"A",text:"$19^\\circ$"},{key:"B",text:"$38^\\circ$"},{key:"C",text:"$52^\\circ$"},{key:"D",text:"$76^\\circ$"},{key:"E",text:"$142^\\circ$"}],
    answer: "B", solution: "By the alternate segment theorem, the angle between a tangent and chord equals the angle subtended by that chord in the alternate segment, so it is $38^\\circ$." },

  { id: "tmua-spec-n01", type: "mcq", testId: "tmua", topicId: "tmua-number", difficulty: 2, marks: 1,
    question: "A rectangle has length $8.4$ cm and width $3.2$ cm, each correct to the nearest $0.1$ cm. Which is the upper bound for its area?",
    options: [{key:"A",text:"$26.88$"},{key:"B",text:"$27.04$"},{key:"C",text:"$27.30$"},{key:"D",text:"$27.40$"},{key:"E",text:"$27.4625$"}],
    answer: "E", solution: "The upper bounds are $8.45$ and $3.25$, so the area upper bound is $8.45\\times3.25=27.4625$ cm$^2$." },
  { id: "tmua-spec-n02", type: "mcq", testId: "tmua", topicId: "tmua-number", difficulty: 1, marks: 1,
    question: "Express $0.\\overline{27}$ as a fraction in its lowest terms.",
    options: [{key:"A",text:"$27/100$"},{key:"B",text:"$27/90$"},{key:"C",text:"$9/11$"},{key:"D",text:"$3/11$"},{key:"E",text:"$27/11$"}],
    answer: "D", solution: "Let $x=0.\\overline{27}$. Then $100x-x=27$, so $99x=27$ and $x=27/99=3/11$." },
  { id: "tmua-spec-n03", type: "mcq", testId: "tmua", topicId: "tmua-number", difficulty: 1, marks: 1,
    question: "Given $a:b=3:5$ and $b:c=10:7$, what is $a:c$?",
    options: [{key:"A",text:"$3:7$"},{key:"B",text:"$5:7$"},{key:"C",text:"$6:5$"},{key:"D",text:"$10:7$"},{key:"E",text:"$6:7$"}],
    answer: "E", solution: "Scale $a:b=3:5$ to $6:10$. Combining with $b:c=10:7$ gives $a:c=6:7$." },
  { id: "tmua-spec-n04", type: "mcq", testId: "tmua", topicId: "tmua-number", difficulty: 2, marks: 1,
    question: "$x$ is directly proportional to $y^2$. If $x=18$ when $y=3$, what is $x$ when $y=5$?",
    options: [{key:"A",text:"$30$"},{key:"B",text:"$50$"},{key:"C",text:"$54$"},{key:"D",text:"$75$"},{key:"E",text:"$90$"}],
    answer: "B", solution: "Write $x=ky^2$. Since $18=9k$, $k=2$. When $y=5$, $x=2(25)=50$." },
  { id: "tmua-spec-n05", type: "mcq", testId: "tmua", topicId: "tmua-number", difficulty: 2, marks: 1,
    question: "$t$ is inversely proportional to $\\sqrt n$. If $t=12$ when $n=4$, what is $t$ when $n=9$?",
    options: [{key:"A",text:"$4$"},{key:"B",text:"$6$"},{key:"C",text:"$9$"},{key:"D",text:"$18$"},{key:"E",text:"$8$"}],
    answer: "E", solution: "$t=k/\\sqrt n$. From $12=k/2$, $k=24$. Hence when $n=9$, $t=24/3=8$." },
  { id: "tmua-spec-n06", type: "mcq", testId: "tmua", topicId: "tmua-number", difficulty: 2, marks: 1,
    question: "A solid has mass $2.4$ kg and volume $300$ cm$^3$. What is its density in g/cm$^3$?",
    options: [{key:"A",text:"$0.008$"},{key:"B",text:"$0.8$"},{key:"C",text:"$7.2$"},{key:"D",text:"$8$"},{key:"E",text:"$8000$"}],
    answer: "D", solution: "$2.4$ kg is $2400$ g. Density $=2400/300=8$ g/cm$^3$." },
  { id: "tmua-spec-n07", type: "mcq", testId: "tmua", topicId: "tmua-number", difficulty: 2, marks: 1,
    question: "A map has scale $1:50000$. What real distance is represented by $7.2$ cm on the map?",
    options: [{key:"A",text:"$0.36$ km"},{key:"B",text:"$1.4$ km"},{key:"C",text:"$3.6$ km"},{key:"D",text:"$36$ km"},{key:"E",text:"$360$ km"}],
    answer: "C", solution: "$7.2\\times50000=360000$ cm, which is $3600$ m or $3.6$ km." },
  { id: "tmua-spec-n08", type: "mcq", testId: "tmua", topicId: "tmua-number", difficulty: 1, marks: 1,
    question: "A value of $200$ is decreased by $10\\%$ twice. What is the final value?",
    options: [{key:"A",text:"$160$"},{key:"B",text:"$180$"},{key:"C",text:"$190$"},{key:"D",text:"$198$"},{key:"E",text:"$162$"}],
    answer: "E", solution: "Each decrease multiplies by $0.9$, so the final value is $200(0.9)^2=162$." },
  { id: "tmua-spec-n09", type: "mcq", testId: "tmua", topicId: "tmua-number", difficulty: 1, marks: 1,
    question: "After an increase of $20\\%$, a price is $360$. What was the original price?",
    options: [{key:"A",text:"$300$"},{key:"B",text:"$288$"},{key:"C",text:"$320$"},{key:"D",text:"$340$"},{key:"E",text:"$432$"}],
    answer: "A", solution: "If the original price is $p$, then $1.2p=360$, so $p=300$." },
  { id: "tmua-spec-n10", type: "mcq", testId: "tmua", topicId: "tmua-number", difficulty: 3, marks: 1,
    question: "$a=50$ correct to the nearest integer and $b=4.0$ correct to the nearest $0.1$. Which is the upper bound for $a/b$?",
    options: [{key:"A",text:"$50/4$"},{key:"B",text:"$50.5/4.05$"},{key:"C",text:"$49.5/3.95$"},{key:"D",text:"$49.5/4.05$"},{key:"E",text:"$50.5/3.95$"}],
    answer: "E", solution: "For the largest quotient use the largest possible numerator and smallest possible positive denominator: $50.5/3.95$." },
  { id: "tmua-spec-n11", type: "mcq", testId: "tmua", topicId: "tmua-number", difficulty: 2, marks: 1,
    question: "Write $(6\\times10^7)(4\\times10^{-3})$ in standard form.",
    options: [{key:"A",text:"$24\\times10^{10}$"},{key:"B",text:"$2.4\\times10^{11}$"},{key:"C",text:"$24\\times10^4$"},{key:"D",text:"$2.4\\times10^5$"},{key:"E",text:"$2.4\\times10^4$"}],
    answer: "D", solution: "The product is $24\\times10^4=2.4\\times10^5$, which is in standard form." },
  { id: "tmua-spec-n12", type: "mcq", testId: "tmua", topicId: "tmua-number", difficulty: 2, marks: 1,
    question: "Which is the best estimate of $\\dfrac{19.8\\times0.49}{0.098}$?",
    options: [{key:"A",text:"$1$"},{key:"B",text:"$10$"},{key:"C",text:"$20$"},{key:"D",text:"$50$"},{key:"E",text:"$100$"}],
    answer: "E", solution: "Round to $20\\times0.5/0.1=10/0.1=100$." },
  { id: "tmua-spec-n13", type: "mcq", testId: "tmua", topicId: "tmua-number", difficulty: 2, marks: 1,
    question: "Two similar solids have corresponding lengths in the ratio $2:3$. What is the ratio of their volumes?",
    options: [{key:"A",text:"$4:9$"},{key:"B",text:"$8:27$"},{key:"C",text:"$2:3$"},{key:"D",text:"$16:81$"},{key:"E",text:"$6:9$"}],
    answer: "B", solution: "Volumes scale with the cube of the linear scale factor, so the ratio is $2^3:3^3=8:27$." },
  { id: "tmua-spec-n14", type: "mcq", testId: "tmua", topicId: "tmua-number", difficulty: 3, marks: 1,
    question: "How many litres of a $30\\%$ solution should be mixed with a $50\\%$ solution to make $10$ litres of a $42\\%$ solution?",
    options: [{key:"A",text:"$2$"},{key:"B",text:"$3$"},{key:"C",text:"$5$"},{key:"D",text:"$6$"},{key:"E",text:"$4$"}],
    answer: "E", solution: "If $x$ litres are $30\\%$, then $0.30x+0.50(10-x)=4.2$. Thus $5-0.2x=4.2$, giving $x=4$." },
  { id: "tmua-spec-n15", type: "mcq", testId: "tmua", topicId: "tmua-number", difficulty: 3, marks: 1,
    question: "A car travels the same distance at $60$ km/h and then at $40$ km/h. What is its average speed for the whole journey?",
    options: [{key:"A",text:"$45$ km/h"},{key:"B",text:"$50$ km/h"},{key:"C",text:"$48$ km/h"},{key:"D",text:"$52$ km/h"},{key:"E",text:"$100$ km/h"}],
    answer: "C", solution: "For distance $d$ each way, average speed is $2d/(d/60+d/40)=2/(1/60+1/40)=48$ km/h." },
  { id: "tmua-spec-n16", type: "mcq", testId: "tmua", topicId: "tmua-number", difficulty: 2, marks: 1,
    question: "What is the highest common factor of $84$ and $126$?",
    options: [{key:"A",text:"$6$"},{key:"B",text:"$14$"},{key:"C",text:"$21$"},{key:"D",text:"$42$"},{key:"E",text:"$252$"}],
    answer: "D", solution: "$84=2^2\\cdot3\\cdot7$ and $126=2\\cdot3^2\\cdot7$. Their HCF is $2\\cdot3\\cdot7=42$." },
  { id: "tmua-spec-n17", type: "mcq", testId: "tmua", topicId: "tmua-number", difficulty: 2, marks: 1,
    question: "What is the lowest common multiple of $18$ and $24$?",
    options: [{key:"A",text:"$72$"},{key:"B",text:"$36$"},{key:"C",text:"$48$"},{key:"D",text:"$144$"},{key:"E",text:"$432$"}],
    answer: "A", solution: "$18=2\\cdot3^2$ and $24=2^3\\cdot3$, so the LCM is $2^3\\cdot3^2=72$." },
  { id: "tmua-spec-n18", type: "mcq", testId: "tmua", topicId: "tmua-number", difficulty: 3, marks: 1,
    question: "How many positive factors does $2^4\\cdot3^2$ have?",
    options: [{key:"A",text:"$6$"},{key:"B",text:"$8$"},{key:"C",text:"$10$"},{key:"D",text:"$12$"},{key:"E",text:"$15$"}],
    answer: "E", solution: "A factor may contain $2^0$ through $2^4$ (five choices) and $3^0$ through $3^2$ (three choices), giving $5\\times3=15$." },
  { id: "tmua-spec-n19", type: "mcq", testId: "tmua", topicId: "tmua-number", difficulty: 2, marks: 1,
    question: "What is the smallest non-negative integer that must be added to $4730$ to make it divisible by $9$?",
    options: [{key:"A",text:"$1$"},{key:"B",text:"$2$"},{key:"C",text:"$3$"},{key:"D",text:"$5$"},{key:"E",text:"$4$"}],
    answer: "E", solution: "The digit sum of $4730$ is $14$. Adding $4$ gives $4734$, whose digit sum is $18$, so it is divisible by $9$." },
  { id: "tmua-spec-n20", type: "mcq", testId: "tmua", topicId: "tmua-number", difficulty: 3, marks: 1,
    question: "A quantity is increased by $20\\%$ and then decreased by $20\\%$. What is the overall percentage change?",
    options: [{key:"A",text:"no change"},{key:"B",text:"$2\\%$ decrease"},{key:"C",text:"$2\\%$ increase"},{key:"D",text:"$4\\%$ increase"},{key:"E",text:"$4\\%$ decrease"}],
    answer: "E", solution: "The combined multiplier is $1.2\\times0.8=0.96$, so the final value is $96\\%$ of the original: a $4\\%$ decrease." },
];
