// TSA 问题解决题（批次二）—— 可计算，sympy 计算答案，独立复核。id 前缀 tsa-ps2-*。
import type { MCQQuestion } from "./types";

export const TSA_PROBLEM_2: MCQQuestion[] = [
  { id: "tsa-ps2-001", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "After a $20\\%$ reduction, a jacket costs £$120$. What was its original price?",
    options: [{ key: "A", text: "$155$" },{ key: "B", text: "$96$" },{ key: "C", text: "$150$" },{ key: "D", text: "$140$" },{ key: "E", text: "$144$" }],
    answer: "C", solution: "If original $=y$, then $y(1-20/100)=120$, so $y=\\dfrac{120}{\\frac{4}{5}}=£150.$" },
  { id: "tsa-ps2-002", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "After a $10\\%$ reduction, a jacket costs £$180$. What was its original price?",
    options: [{ key: "A", text: "$162$" },{ key: "B", text: "$205$" },{ key: "C", text: "$200$" },{ key: "D", text: "$198$" },{ key: "E", text: "$190$" }],
    answer: "C", solution: "If original $=y$, then $y(1-10/100)=180$, so $y=\\dfrac{180}{\\frac{9}{10}}=£200.$" },
  { id: "tsa-ps2-003", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "After a $40\\%$ reduction, a jacket costs £$240$. What was its original price?",
    options: [{ key: "A", text: "$336$" },{ key: "B", text: "$144$" },{ key: "C", text: "$405$" },{ key: "D", text: "$280$" },{ key: "E", text: "$400$" }],
    answer: "E", solution: "If original $=y$, then $y(1-40/100)=240$, so $y=\\dfrac{240}{\\frac{3}{5}}=£400.$" },
  { id: "tsa-ps2-004", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "After a $50\\%$ reduction, a jacket costs £$90$. What was its original price?",
    options: [{ key: "A", text: "$135$" },{ key: "B", text: "$185$" },{ key: "C", text: "$180$" },{ key: "D", text: "$45$" },{ key: "E", text: "$140$" }],
    answer: "C", solution: "If original $=y$, then $y(1-50/100)=90$, so $y=\\dfrac{90}{\\frac{1}{2}}=£180.$" },
  { id: "tsa-ps2-005", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "Two trains start $300$ km apart and travel toward each other at $40$ km/h and $60$ km/h. After how many hours do they meet?",
    options: [{ key: "A", text: "$\\frac{15}{2}$ 小时" },{ key: "B", text: "$15$ 小时" },{ key: "C", text: "$4$ 小时" },{ key: "D", text: "$5$ 小时" },{ key: "E", text: "$3$ 小时" }],
    answer: "E", solution: "Closing speed $=40+60=100$ km/h; time $=\\dfrac{300}{100}=3$ hours." },
  { id: "tsa-ps2-006", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "Two trains start $210$ km apart and travel toward each other at $50$ km/h and $20$ km/h. After how many hours do they meet?",
    options: [{ key: "A", text: "$4$ 小时" },{ key: "B", text: "$7$ 小时" },{ key: "C", text: "$\\frac{21}{5}$ 小时" },{ key: "D", text: "$3$ 小时" },{ key: "E", text: "$\\frac{21}{2}$ 小时" }],
    answer: "D", solution: "Closing speed $=50+20=70$ km/h; time $=\\dfrac{210}{70}=3$ hours." },
  { id: "tsa-ps2-007", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "Two trains start $120$ km apart and travel toward each other at $25$ km/h and $35$ km/h. After how many hours do they meet?",
    options: [{ key: "A", text: "$\\frac{24}{7}$ 小时" },{ key: "B", text: "$12$ 小时" },{ key: "C", text: "$3$ 小时" },{ key: "D", text: "$\\frac{24}{5}$ 小时" },{ key: "E", text: "$2$ 小时" }],
    answer: "E", solution: "Closing speed $=25+35=60$ km/h; time $=\\dfrac{120}{60}=2$ hours." },
  { id: "tsa-ps2-008", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "Two trains start $400$ km apart and travel toward each other at $80$ km/h and $120$ km/h. After how many hours do they meet?",
    options: [{ key: "A", text: "$2$ 小时" },{ key: "B", text: "$3$ 小时" },{ key: "C", text: "$\\frac{10}{3}$ 小时" },{ key: "D", text: "$10$ 小时" },{ key: "E", text: "$5$ 小时" }],
    answer: "A", solution: "Closing speed $=80+120=200$ km/h; time $=\\dfrac{400}{200}=2$ hours." },
  { id: "tsa-ps2-009", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "One bus leaves every $6$ minutes and another every $8$ minutes; both leave together now. After how many minutes will they next leave together?",
    options: [{ key: "A", text: "$30$ 分钟" },{ key: "B", text: "$14$ 分钟" },{ key: "C", text: "$48$ 分钟" },{ key: "D", text: "$2$ 分钟" },{ key: "E", text: "$24$ 分钟" }],
    answer: "E", solution: "They coincide at the lowest common multiple: $\\text{lcm}(6,8)=24$ minutes." },
  { id: "tsa-ps2-010", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "One bus leaves every $10$ minutes and another every $15$ minutes; both leave together now. After how many minutes will they next leave together?",
    options: [{ key: "A", text: "$40$ 分钟" },{ key: "B", text: "$30$ 分钟" },{ key: "C", text: "$25$ 分钟" },{ key: "D", text: "$150$ 分钟" },{ key: "E", text: "$5$ 分钟" }],
    answer: "B", solution: "They coincide at the lowest common multiple: $\\text{lcm}(10,15)=30$ minutes." },
  { id: "tsa-ps2-011", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "One bus leaves every $12$ minutes and another every $18$ minutes; both leave together now. After how many minutes will they next leave together?",
    options: [{ key: "A", text: "$48$ 分钟" },{ key: "B", text: "$6$ 分钟" },{ key: "C", text: "$216$ 分钟" },{ key: "D", text: "$36$ 分钟" },{ key: "E", text: "$30$ 分钟" }],
    answer: "D", solution: "They coincide at the lowest common multiple: $\\text{lcm}(12,18)=36$ minutes." },
  { id: "tsa-ps2-012", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "One bus leaves every $9$ minutes and another every $12$ minutes; both leave together now. After how many minutes will they next leave together?",
    options: [{ key: "A", text: "$45$ 分钟" },{ key: "B", text: "$36$ 分钟" },{ key: "C", text: "$108$ 分钟" },{ key: "D", text: "$21$ 分钟" },{ key: "E", text: "$3$ 分钟" }],
    answer: "B", solution: "They coincide at the lowest common multiple: $\\text{lcm}(9,12)=36$ minutes." },
  { id: "tsa-ps2-013", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "One bus leaves every $20$ minutes and another every $30$ minutes; both leave together now. After how many minutes will they next leave together?",
    options: [{ key: "A", text: "$60$ 分钟" },{ key: "B", text: "$50$ 分钟" },{ key: "C", text: "$600$ 分钟" },{ key: "D", text: "$80$ 分钟" },{ key: "E", text: "$10$ 分钟" }],
    answer: "A", solution: "They coincide at the lowest common multiple: $\\text{lcm}(20,30)=60$ minutes." },
  { id: "tsa-ps2-014", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A group of $10$ students averages $60$ marks and another group of $20$ students averages $90$. What is the overall average?",
    options: [{ key: "A", text: "$90$" },{ key: "B", text: "$80$" },{ key: "C", text: "$75$" },{ key: "D", text: "$82$" },{ key: "E", text: "$1200$" }],
    answer: "B", solution: "Overall $=\\dfrac{10\\cdot60+20\\cdot90}{30}=80$ (weighted, not simple, mean)." },
  { id: "tsa-ps2-015", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A group of $5$ students averages $70$ marks and another group of $15$ students averages $50$. What is the overall average?",
    options: [{ key: "A", text: "$60$" },{ key: "B", text: "$70$" },{ key: "C", text: "$57$" },{ key: "D", text: "$55$" },{ key: "E", text: "$550$" }],
    answer: "D", solution: "Overall $=\\dfrac{5\\cdot70+15\\cdot50}{20}=55$ (weighted, not simple, mean)." },
  { id: "tsa-ps2-016", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A group of $8$ students averages $80$ marks and another group of $12$ students averages $55$. What is the overall average?",
    options: [{ key: "A", text: "$\\frac{135}{2}$" },{ key: "B", text: "$650$" },{ key: "C", text: "$80$" },{ key: "D", text: "$67$" },{ key: "E", text: "$65$" }],
    answer: "E", solution: "Overall $=\\dfrac{8\\cdot80+12\\cdot55}{20}=65$ (weighted, not simple, mean)." },
  { id: "tsa-ps2-017", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A group of $20$ students averages $40$ marks and another group of $30$ students averages $65$. What is the overall average?",
    options: [{ key: "A", text: "$57$" },{ key: "B", text: "$55$" },{ key: "C", text: "$65$" },{ key: "D", text: "$1375$" },{ key: "E", text: "$\\frac{105}{2}$" }],
    answer: "B", solution: "Overall $=\\dfrac{20\\cdot40+30\\cdot65}{50}=55$ (weighted, not simple, mean)." },
  { id: "tsa-ps2-018", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A right-angled triangle has the two shorter sides $3$ and $4$. What is the length of the hypotenuse?",
    options: [{ key: "A", text: "$5$" },{ key: "B", text: "$6$" },{ key: "C", text: "$4$" },{ key: "D", text: "$7$" },{ key: "E", text: "$2$" }],
    answer: "A", solution: "Hypotenuse $=\\sqrt{3^2+4^2}=\\sqrt{25}=5.$" },
  { id: "tsa-ps2-019", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A right-angled triangle has the two shorter sides $6$ and $8$. What is the length of the hypotenuse?",
    options: [{ key: "A", text: "$14$" },{ key: "B", text: "$10$" },{ key: "C", text: "$5$" },{ key: "D", text: "$9$" },{ key: "E", text: "$11$" }],
    answer: "B", solution: "Hypotenuse $=\\sqrt{6^2+8^2}=\\sqrt{100}=10.$" },
  { id: "tsa-ps2-020", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A right-angled triangle has the two shorter sides $5$ and $12$. What is the length of the hypotenuse?",
    options: [{ key: "A", text: "$14$" },{ key: "B", text: "$17$" },{ key: "C", text: "$12$" },{ key: "D", text: "$10$" },{ key: "E", text: "$13$" }],
    answer: "E", solution: "Hypotenuse $=\\sqrt{5^2+12^2}=\\sqrt{169}=13.$" },
  { id: "tsa-ps2-021", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A right-angled triangle has the two shorter sides $8$ and $15$. What is the length of the hypotenuse?",
    options: [{ key: "A", text: "$18$" },{ key: "B", text: "$16$" },{ key: "C", text: "$12$" },{ key: "D", text: "$17$" },{ key: "E", text: "$23$" }],
    answer: "D", solution: "Hypotenuse $=\\sqrt{8^2+15^2}=\\sqrt{289}=17.$" },
  { id: "tsa-ps2-022", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A right-angled triangle has the two shorter sides $9$ and $12$. What is the length of the hypotenuse?",
    options: [{ key: "A", text: "$7$" },{ key: "B", text: "$21$" },{ key: "C", text: "$16$" },{ key: "D", text: "$15$" },{ key: "E", text: "$14$" }],
    answer: "D", solution: "Hypotenuse $=\\sqrt{9^2+12^2}=\\sqrt{225}=15.$" },
  { id: "tsa-ps2-023", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A triangle has base $10$ and perpendicular height $6$. What is its area?",
    options: [{ key: "A", text: "$60$" },{ key: "B", text: "$16$" },{ key: "C", text: "$20$" },{ key: "D", text: "$32$" },{ key: "E", text: "$30$" }],
    answer: "E", solution: "Area $=\\tfrac12\\cdot10\\cdot6=30.$" },
  { id: "tsa-ps2-024", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A triangle has base $8$ and perpendicular height $5$. What is its area?",
    options: [{ key: "A", text: "$\\frac{40}{3}$" },{ key: "B", text: "$22$" },{ key: "C", text: "$40$" },{ key: "D", text: "$20$" },{ key: "E", text: "$13$" }],
    answer: "D", solution: "Area $=\\tfrac12\\cdot8\\cdot5=20.$" },
  { id: "tsa-ps2-025", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A triangle has base $12$ and perpendicular height $7$. What is its area?",
    options: [{ key: "A", text: "$19$" },{ key: "B", text: "$42$" },{ key: "C", text: "$44$" },{ key: "D", text: "$28$" },{ key: "E", text: "$84$" }],
    answer: "B", solution: "Area $=\\tfrac12\\cdot12\\cdot7=42.$" },
  { id: "tsa-ps2-026", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A triangle has base $15$ and perpendicular height $4$. What is its area?",
    options: [{ key: "A", text: "$20$" },{ key: "B", text: "$60$" },{ key: "C", text: "$30$" },{ key: "D", text: "$19$" },{ key: "E", text: "$32$" }],
    answer: "C", solution: "Area $=\\tfrac12\\cdot15\\cdot4=30.$" },
  { id: "tsa-ps2-027", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A box measures $5\\times4\\times3$. What is its volume?",
    options: [{ key: "A", text: "$94$" },{ key: "B", text: "$20$" },{ key: "C", text: "$60$" },{ key: "D", text: "$65$" },{ key: "E", text: "$12$" }],
    answer: "C", solution: "Volume $=5\\times4\\times3=60.$" },
  { id: "tsa-ps2-028", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A box measures $10\\times3\\times2$. What is its volume?",
    options: [{ key: "A", text: "$60$" },{ key: "B", text: "$30$" },{ key: "C", text: "$15$" },{ key: "D", text: "$112$" },{ key: "E", text: "$70$" }],
    answer: "A", solution: "Volume $=10\\times3\\times2=60.$" },
  { id: "tsa-ps2-029", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A box measures $7\\times5\\times2$. What is its volume?",
    options: [{ key: "A", text: "$77$" },{ key: "B", text: "$118$" },{ key: "C", text: "$14$" },{ key: "D", text: "$70$" },{ key: "E", text: "$35$" }],
    answer: "D", solution: "Volume $=7\\times5\\times2=70.$" },
  { id: "tsa-ps2-030", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A recipe for $4$ people needs $300$ g of flour. How much is needed for $6$ people?",
    options: [{ key: "A", text: "$50$ g" },{ key: "B", text: "$1800$ g" },{ key: "C", text: "$300$ g" },{ key: "D", text: "$460$ g" },{ key: "E", text: "$450$ g" }],
    answer: "E", solution: "Scale by $\\tfrac{6}{4}$: $300\\times\\tfrac{6}{4}=450$ g." },
  { id: "tsa-ps2-031", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A recipe for $8$ people needs $200$ g of flour. How much is needed for $2$ people?",
    options: [{ key: "A", text: "$50$ g" },{ key: "B", text: "$100$ g" },{ key: "C", text: "$60$ g" },{ key: "D", text: "$400$ g" },{ key: "E", text: "$200$ g" }],
    answer: "A", solution: "Scale by $\\tfrac{2}{8}$: $200\\times\\tfrac{2}{8}=50$ g." },
  { id: "tsa-ps2-032", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A recipe for $3$ people needs $150$ g of flour. How much is needed for $5$ people?",
    options: [{ key: "A", text: "$260$ g" },{ key: "B", text: "$30$ g" },{ key: "C", text: "$150$ g" },{ key: "D", text: "$250$ g" },{ key: "E", text: "$750$ g" }],
    answer: "D", solution: "Scale by $\\tfrac{5}{3}$: $150\\times\\tfrac{5}{3}=250$ g." },
  { id: "tsa-ps2-033", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A recipe for $6$ people needs $240$ g of flour. How much is needed for $4$ people?",
    options: [{ key: "A", text: "$60$ g" },{ key: "B", text: "$960$ g" },{ key: "C", text: "$240$ g" },{ key: "D", text: "$170$ g" },{ key: "E", text: "$160$ g" }],
    answer: "E", solution: "Scale by $\\tfrac{4}{6}$: $240\\times\\tfrac{4}{6}=160$ g." },
  { id: "tsa-ps2-034", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 3, marks: 1,
    question: "$2$ L of a $10\\%$ solution is mixed with $3$ L of a $20\\%$ solution. What is the concentration of the mixture?",
    options: [{ key: "A", text: "$10$ %" },{ key: "B", text: "$16$ %" },{ key: "C", text: "$20$ %" },{ key: "D", text: "$15$ %" },{ key: "E", text: "$17$ %" }],
    answer: "B", solution: "Concentration $=\\dfrac{2\\cdot10+3\\cdot20}{2+3}=16\\%.$" },
  { id: "tsa-ps2-035", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 3, marks: 1,
    question: "$4$ L of a $25\\%$ solution is mixed with $6$ L of a $5\\%$ solution. What is the concentration of the mixture?",
    options: [{ key: "A", text: "$15$ %" },{ key: "B", text: "$14$ %" },{ key: "C", text: "$13$ %" },{ key: "D", text: "$25$ %" },{ key: "E", text: "$5$ %" }],
    answer: "C", solution: "Concentration $=\\dfrac{4\\cdot25+6\\cdot5}{4+6}=13\\%.$" },
  { id: "tsa-ps2-036", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "Two fair dice are thrown. What is the probability that the total is $9$?",
    options: [{ key: "A", text: "$\\frac{1}{9}$" },{ key: "B", text: "$\\frac{1}{3}$" },{ key: "C", text: "$\\frac{5}{36}$" },{ key: "D", text: "$\\frac{1}{4}$" },{ key: "E", text: "$\\frac{1}{6}$" }],
    answer: "A", solution: "There are $4$ ways to score $9$ out of $36$: $P=\\dfrac{4}{36}=\\frac{1}{9}.$" },
  { id: "tsa-ps2-037", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A fair coin is tossed $3$ times. What is the probability of getting at least one head?",
    options: [{ key: "A", text: "$\\frac{3}{4}$" },{ key: "B", text: "$\\frac{1}{2}$" },{ key: "C", text: "$\\frac{3}{8}$" },{ key: "D", text: "$\\frac{1}{8}$" },{ key: "E", text: "$\\frac{7}{8}$" }],
    answer: "E", solution: "$P(\\text{at least one})=1-P(\\text{no heads})=1-\\tfrac1{2^{3}}=\\frac{7}{8}.$" },
  { id: "tsa-ps2-038", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A fair coin is tossed $4$ times. What is the probability of getting at least one head?",
    options: [{ key: "A", text: "$\\frac{1}{16}$" },{ key: "B", text: "$\\frac{1}{4}$" },{ key: "C", text: "$\\frac{1}{2}$" },{ key: "D", text: "$\\frac{7}{8}$" },{ key: "E", text: "$\\frac{15}{16}$" }],
    answer: "E", solution: "$P(\\text{at least one})=1-P(\\text{no heads})=1-\\tfrac1{2^{4}}=\\frac{15}{16}.$" },
  { id: "tsa-ps2-039", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "In how many ways can $3$ people be arranged in a row chosen from $6$ people?",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$120$" },{ key: "C", text: "$126$" },{ key: "D", text: "$20$" },{ key: "E", text: "$216$" }],
    answer: "B", solution: "$^{6}P_{3}=\\dfrac{6!}{(6-3)!}=120.$" },
  { id: "tsa-ps2-040", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "Find the sum of the first $8$ terms of an arithmetic sequence with first term $2$ and common difference $3$.",
    options: [{ key: "A", text: "$23$" },{ key: "B", text: "$100$" },{ key: "C", text: "$16$" },{ key: "D", text: "$108$" },{ key: "E", text: "$184$" }],
    answer: "B", solution: "$S_n=\\tfrac n2(2a+(n-1)d)=100.$" },
  { id: "tsa-ps2-041", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A geometric sequence has first term $2$ and common ratio $3$. What is the $4$-th term?",
    options: [{ key: "A", text: "$24$" },{ key: "B", text: "$128$" },{ key: "C", text: "$54$" },{ key: "D", text: "$56$" },{ key: "E", text: "$162$" }],
    answer: "C", solution: "$u_n=ar^{n-1}=2\\cdot3^{3}=54.$" },
  { id: "tsa-ps2-042", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A geometric sequence has first term $1$ and common ratio $2$. What is the $6$-th term?",
    options: [{ key: "A", text: "$36$" },{ key: "B", text: "$12$" },{ key: "C", text: "$64$" },{ key: "D", text: "$32$" },{ key: "E", text: "$33$" }],
    answer: "D", solution: "$u_n=ar^{n-1}=1\\cdot2^{5}=32.$" },
  { id: "tsa-ps2-043", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A geometric sequence has first term $5$ and common ratio $2$. What is the $3$-th term?",
    options: [{ key: "A", text: "$45$" },{ key: "B", text: "$30$" },{ key: "C", text: "$25$" },{ key: "D", text: "$40$" },{ key: "E", text: "$20$" }],
    answer: "E", solution: "$u_n=ar^{n-1}=5\\cdot2^{2}=20.$" },
  { id: "tsa-ps2-044", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A shop buys an item for £$60$ and marks it up by $20\\%$. What is the selling price?",
    options: [{ key: "A", text: "$48$" },{ key: "B", text: "$12$" },{ key: "C", text: "$77$" },{ key: "D", text: "$72$" },{ key: "E", text: "$80$" }],
    answer: "D", solution: "Selling price $=60(1+20/100)=£72.$" },
  { id: "tsa-ps2-045", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A shop buys an item for £$200$ and marks it up by $15\\%$. What is the selling price?",
    options: [{ key: "A", text: "$235$" },{ key: "B", text: "$30$" },{ key: "C", text: "$215$" },{ key: "D", text: "$230$" },{ key: "E", text: "$170$" }],
    answer: "D", solution: "Selling price $=200(1+15/100)=£230.$" },
  { id: "tsa-ps2-046", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "If $4$ workers take $12$ days to finish a job, how long would $6$ workers take (at the same rate)?",
    options: [{ key: "A", text: "$9$ 天" },{ key: "B", text: "$18$ 天" },{ key: "C", text: "$2$ 天" },{ key: "D", text: "$12$ 天" },{ key: "E", text: "$8$ 天" }],
    answer: "E", solution: "Work $=4\\times12=48$ worker-days; time $=\\dfrac{48}{6}=8$ days." },
  { id: "tsa-ps2-047", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "If $3$ workers take $20$ days to finish a job, how long would $5$ workers take (at the same rate)?",
    options: [{ key: "A", text: "$20$ 天" },{ key: "B", text: "$\\frac{100}{3}$ 天" },{ key: "C", text: "$13$ 天" },{ key: "D", text: "$12$ 天" },{ key: "E", text: "$4$ 天" }],
    answer: "D", solution: "Work $=3\\times20=60$ worker-days; time $=\\dfrac{60}{5}=12$ days." },
  { id: "tsa-ps2-048", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "If $8$ workers take $9$ days to finish a job, how long would $6$ workers take (at the same rate)?",
    options: [{ key: "A", text: "$9$ 天" },{ key: "B", text: "$\\frac{3}{2}$ 天" },{ key: "C", text: "$\\frac{27}{4}$ 天" },{ key: "D", text: "$13$ 天" },{ key: "E", text: "$12$ 天" }],
    answer: "E", solution: "Work $=8\\times9=72$ worker-days; time $=\\dfrac{72}{6}=12$ days." },
  { id: "tsa-ps2-049", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "If $10$ workers take $6$ days to finish a job, how long would $4$ workers take (at the same rate)?",
    options: [{ key: "A", text: "$6$ 天" },{ key: "B", text: "$\\frac{12}{5}$ 天" },{ key: "C", text: "$15$ 天" },{ key: "D", text: "$16$ 天" },{ key: "E", text: "$\\frac{3}{2}$ 天" }],
    answer: "C", solution: "Work $=10\\times6=60$ worker-days; time $=\\dfrac{60}{4}=15$ days." },
  { id: "tsa-ps2-050", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A price of £$200$ has VAT of $20\\%$ added. What is the total price?",
    options: [{ key: "A", text: "$40$" },{ key: "B", text: "$220$" },{ key: "C", text: "$240$" },{ key: "D", text: "$242$" },{ key: "E", text: "$160$" }],
    answer: "C", solution: "Total $=200(1+20/100)=£240.$" },
  { id: "tsa-ps2-051", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A price of £$50$ has VAT of $20\\%$ added. What is the total price?",
    options: [{ key: "A", text: "$60$" },{ key: "B", text: "$10$" },{ key: "C", text: "$40$" },{ key: "D", text: "$70$" },{ key: "E", text: "$62$" }],
    answer: "A", solution: "Total $=50(1+20/100)=£60.$" },
  { id: "tsa-ps2-052", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A price of £$80$ has VAT of $5\\%$ added. What is the total price?",
    options: [{ key: "A", text: "$86$" },{ key: "B", text: "$84$" },{ key: "C", text: "$76$" },{ key: "D", text: "$4$" },{ key: "E", text: "$85$" }],
    answer: "B", solution: "Total $=80(1+5/100)=£84.$" },
  { id: "tsa-ps2-053", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A price of £$120$ has VAT of $25\\%$ added. What is the total price?",
    options: [{ key: "A", text: "$150$" },{ key: "B", text: "$145$" },{ key: "C", text: "$152$" },{ key: "D", text: "$30$" },{ key: "E", text: "$90$" }],
    answer: "A", solution: "Total $=120(1+25/100)=£150.$" },
  { id: "tsa-ps2-054", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A car travels $15$ km on each litre of fuel. How many litres are needed for a journey of $300$ km?",
    options: [{ key: "A", text: "$20$ L" },{ key: "B", text: "$4500$ L" },{ key: "C", text: "$15$ L" },{ key: "D", text: "$\\frac{1}{20}$ L" },{ key: "E", text: "$22$ L" }],
    answer: "A", solution: "Litres $=\\dfrac{\\text{distance}}{\\text{km per litre}}=\\dfrac{300}{15}=20$ L." },
  { id: "tsa-ps2-055", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A car travels $12$ km on each litre of fuel. How many litres are needed for a journey of $240$ km?",
    options: [{ key: "A", text: "$2880$ L" },{ key: "B", text: "$22$ L" },{ key: "C", text: "$\\frac{1}{20}$ L" },{ key: "D", text: "$20$ L" },{ key: "E", text: "$12$ L" }],
    answer: "D", solution: "Litres $=\\dfrac{\\text{distance}}{\\text{km per litre}}=\\dfrac{240}{12}=20$ L." },
  { id: "tsa-ps2-056", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A car travels $9$ km on each litre of fuel. How many litres are needed for a journey of $450$ km?",
    options: [{ key: "A", text: "$50$ L" },{ key: "B", text: "$9$ L" },{ key: "C", text: "$\\frac{1}{50}$ L" },{ key: "D", text: "$4050$ L" },{ key: "E", text: "$52$ L" }],
    answer: "A", solution: "Litres $=\\dfrac{\\text{distance}}{\\text{km per litre}}=\\dfrac{450}{9}=50$ L." },
  { id: "tsa-ps2-057", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A car travels $6$ km on each litre of fuel. How many litres are needed for a journey of $180$ km?",
    options: [{ key: "A", text: "$\\frac{1}{30}$ L" },{ key: "B", text: "$1080$ L" },{ key: "C", text: "$32$ L" },{ key: "D", text: "$6$ L" },{ key: "E", text: "$30$ L" }],
    answer: "E", solution: "Litres $=\\dfrac{\\text{distance}}{\\text{km per litre}}=\\dfrac{180}{6}=30$ L." },
  { id: "tsa-ps2-058", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "What is $15\\%$ of $80$?",
    options: [{ key: "A", text: "$120$" },{ key: "B", text: "$95$" },{ key: "C", text: "$\\frac{16}{3}$" },{ key: "D", text: "$12$" },{ key: "E", text: "$17$" }],
    answer: "D", solution: "$15\\%$ of $80=\\dfrac{15}{100}\\times80=12.$" },
  { id: "tsa-ps2-059", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "What is $30\\%$ of $150$?",
    options: [{ key: "A", text: "$45$" },{ key: "B", text: "$50$" },{ key: "C", text: "$5$" },{ key: "D", text: "$180$" },{ key: "E", text: "$450$" }],
    answer: "A", solution: "$30\\%$ of $150=\\dfrac{30}{100}\\times150=45.$" },
  { id: "tsa-ps2-060", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "What is $12\\%$ of $50$?",
    options: [{ key: "A", text: "$6$" },{ key: "B", text: "$62$" },{ key: "C", text: "$\\frac{25}{6}$" },{ key: "D", text: "$60$" },{ key: "E", text: "$11$" }],
    answer: "A", solution: "$12\\%$ of $50=\\dfrac{12}{100}\\times50=6.$" },
  { id: "tsa-ps2-061", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "What is $45\\%$ of $200$?",
    options: [{ key: "A", text: "$\\frac{40}{9}$" },{ key: "B", text: "$95$" },{ key: "C", text: "$90$" },{ key: "D", text: "$245$" },{ key: "E", text: "$900$" }],
    answer: "C", solution: "$45\\%$ of $200=\\dfrac{45}{100}\\times200=90.$" },
  { id: "tsa-ps2-062", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "What is $8\\%$ of $250$?",
    options: [{ key: "A", text: "$25$" },{ key: "B", text: "$\\frac{125}{4}$" },{ key: "C", text: "$20$" },{ key: "D", text: "$258$" },{ key: "E", text: "$200$" }],
    answer: "C", solution: "$8\\%$ of $250=\\dfrac{8}{100}\\times250=20.$" },
  { id: "tsa-ps2-063", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "What is $\\dfrac{2}{3}$ of $90$?",
    options: [{ key: "A", text: "$62$" },{ key: "B", text: "$45$" },{ key: "C", text: "$60$" },{ key: "D", text: "$135$" },{ key: "E", text: "$30$" }],
    answer: "C", solution: "$\\dfrac{2}{3}\\times90=60.$" },
  { id: "tsa-ps2-064", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "What is $\\dfrac{3}{4}$ of $80$?",
    options: [{ key: "A", text: "$62$" },{ key: "B", text: "$60$" },{ key: "C", text: "$\\frac{320}{3}$" },{ key: "D", text: "$20$" },{ key: "E", text: "$\\frac{80}{3}$" }],
    answer: "B", solution: "$\\dfrac{3}{4}\\times80=60.$" },
  { id: "tsa-ps2-065", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "What is $\\dfrac{5}{6}$ of $60$?",
    options: [{ key: "A", text: "$12$" },{ key: "B", text: "$72$" },{ key: "C", text: "$10$" },{ key: "D", text: "$50$" },{ key: "E", text: "$52$" }],
    answer: "D", solution: "$\\dfrac{5}{6}\\times60=50.$" },
  { id: "tsa-ps2-066", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "What is $\\dfrac{3}{5}$ of $100$?",
    options: [{ key: "A", text: "$60$" },{ key: "B", text: "$\\frac{100}{3}$" },{ key: "C", text: "$\\frac{500}{3}$" },{ key: "D", text: "$62$" },{ key: "E", text: "$40$" }],
    answer: "A", solution: "$\\dfrac{3}{5}\\times100=60.$" },
  { id: "tsa-ps2-067", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A car travels $150$ km in $3$ hours. What is its average speed?",
    options: [{ key: "A", text: "$450$ km/h" },{ key: "B", text: "$55$ km/h" },{ key: "C", text: "$50$ km/h" },{ key: "D", text: "$147$ km/h" },{ key: "E", text: "$\\frac{1}{50}$ km/h" }],
    answer: "C", solution: "Speed $=\\dfrac{\\text{distance}}{\\text{time}}=\\dfrac{150}{3}=50$ km/h." },
  { id: "tsa-ps2-068", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A car travels $240$ km in $4$ hours. What is its average speed?",
    options: [{ key: "A", text: "$\\frac{1}{60}$ km/h" },{ key: "B", text: "$65$ km/h" },{ key: "C", text: "$236$ km/h" },{ key: "D", text: "$960$ km/h" },{ key: "E", text: "$60$ km/h" }],
    answer: "E", solution: "Speed $=\\dfrac{\\text{distance}}{\\text{time}}=\\dfrac{240}{4}=60$ km/h." },
  { id: "tsa-ps2-069", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A car travels $90$ km in $2$ hours. What is its average speed?",
    options: [{ key: "A", text: "$88$ km/h" },{ key: "B", text: "$\\frac{1}{45}$ km/h" },{ key: "C", text: "$50$ km/h" },{ key: "D", text: "$180$ km/h" },{ key: "E", text: "$45$ km/h" }],
    answer: "E", solution: "Speed $=\\dfrac{\\text{distance}}{\\text{time}}=\\dfrac{90}{2}=45$ km/h." },
  { id: "tsa-ps2-070", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A car travels $200$ km in $5$ hours. What is its average speed?",
    options: [{ key: "A", text: "$40$ km/h" },{ key: "B", text: "$195$ km/h" },{ key: "C", text: "$1000$ km/h" },{ key: "D", text: "$\\frac{1}{40}$ km/h" },{ key: "E", text: "$45$ km/h" }],
    answer: "A", solution: "Speed $=\\dfrac{\\text{distance}}{\\text{time}}=\\dfrac{200}{5}=40$ km/h." },
  { id: "tsa-ps2-071", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "£$200$ is exchanged at a rate of $\\frac{6}{5}$ dollars to the pound. How many dollars are received?",
    options: [{ key: "A", text: "$240$" },{ key: "B", text: "$200$" },{ key: "C", text: "$\\frac{500}{3}$" },{ key: "D", text: "$245$" },{ key: "E", text: "$\\frac{1006}{5}$" }],
    answer: "A", solution: "Dollars $=200\\times\\frac{6}{5}=240.$" },
  { id: "tsa-ps2-072", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "£$150$ is exchanged at a rate of $\\frac{9}{10}$ dollars to the pound. How many dollars are received?",
    options: [{ key: "A", text: "$\\frac{500}{3}$" },{ key: "B", text: "$150$" },{ key: "C", text: "$\\frac{1509}{10}$" },{ key: "D", text: "$140$" },{ key: "E", text: "$135$" }],
    answer: "E", solution: "Dollars $=150\\times\\frac{9}{10}=135.$" },
  { id: "tsa-ps2-073", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "£$300$ is exchanged at a rate of $\\frac{11}{10}$ dollars to the pound. How many dollars are received?",
    options: [{ key: "A", text: "$\\frac{3000}{11}$" },{ key: "B", text: "$335$" },{ key: "C", text: "$330$" },{ key: "D", text: "$300$" },{ key: "E", text: "$\\frac{3011}{10}$" }],
    answer: "C", solution: "Dollars $=300\\times\\frac{11}{10}=330.$" },
  { id: "tsa-ps2-074", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "£$80$ is exchanged at a rate of $\\frac{5}{4}$ dollars to the pound. How many dollars are received?",
    options: [{ key: "A", text: "$105$" },{ key: "B", text: "$64$" },{ key: "C", text: "$80$" },{ key: "D", text: "$100$" },{ key: "E", text: "$\\frac{325}{4}$" }],
    answer: "D", solution: "Dollars $=80\\times\\frac{5}{4}=100.$" },
  { id: "tsa-ps2-075", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "In how many ways can a committee of $2$ be chosen from $6$ people?",
    options: [{ key: "A", text: "$15$" },{ key: "B", text: "$30$" },{ key: "C", text: "$21$" },{ key: "D", text: "$36$" },{ key: "E", text: "$12$" }],
    answer: "A", solution: "$\\binom{6}{2}=15$ (order does not matter)." },
  { id: "tsa-ps2-076", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "In how many ways can a committee of $3$ be chosen from $8$ people?",
    options: [{ key: "A", text: "$512$" },{ key: "B", text: "$24$" },{ key: "C", text: "$336$" },{ key: "D", text: "$56$" },{ key: "E", text: "$64$" }],
    answer: "D", solution: "$\\binom{8}{3}=56$ (order does not matter)." },
  { id: "tsa-ps2-077", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "In how many ways can a committee of $3$ be chosen from $7$ people?",
    options: [{ key: "A", text: "$343$" },{ key: "B", text: "$210$" },{ key: "C", text: "$21$" },{ key: "D", text: "$42$" },{ key: "E", text: "$35$" }],
    answer: "E", solution: "$\\binom{7}{3}=35$ (order does not matter)." },
  { id: "tsa-ps2-078", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "In how many ways can a committee of $2$ be chosen from $10$ people?",
    options: [{ key: "A", text: "$100$" },{ key: "B", text: "$90$" },{ key: "C", text: "$45$" },{ key: "D", text: "$55$" },{ key: "E", text: "$20$" }],
    answer: "C", solution: "$\\binom{10}{2}=45$ (order does not matter)." },
  { id: "tsa-ps2-079", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "How much is saved on a £$120$ item reduced by $25\\%$?",
    options: [{ key: "A", text: "$30$" },{ key: "B", text: "$35$" },{ key: "C", text: "$90$" },{ key: "D", text: "$95$" },{ key: "E", text: "$25$" }],
    answer: "A", solution: "Saving $=120\\times25/100=£30.$" },
  { id: "tsa-ps2-080", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "How much is saved on a £$80$ item reduced by $10\\%$?",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$72$" },{ key: "C", text: "$13$" },{ key: "D", text: "$70$" },{ key: "E", text: "$10$" }],
    answer: "A", solution: "Saving $=80\\times10/100=£8.$" },
  { id: "tsa-ps2-081", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "How much is saved on a £$200$ item reduced by $15\\%$?",
    options: [{ key: "A", text: "$185$" },{ key: "B", text: "$170$" },{ key: "C", text: "$15$" },{ key: "D", text: "$35$" },{ key: "E", text: "$30$" }],
    answer: "E", solution: "Saving $=200\\times15/100=£30.$" },
  { id: "tsa-ps2-082", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "How much is saved on a £$60$ item reduced by $20\\%$?",
    options: [{ key: "A", text: "$48$" },{ key: "B", text: "$40$" },{ key: "C", text: "$20$" },{ key: "D", text: "$12$" },{ key: "E", text: "$17$" }],
    answer: "D", solution: "Saving $=60\\times20/100=£12.$" },
  { id: "tsa-ps2-083", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 3, marks: 1,
    question: "The sum of $5$ consecutive integers is $60$. What is the largest of them?",
    options: [{ key: "A", text: "$12$" },{ key: "B", text: "$14$" },{ key: "C", text: "$15$" },{ key: "D", text: "$10$" },{ key: "E", text: "$9$" }],
    answer: "B", solution: "If the first is $a$: $ka+\\tfrac{k(k-1)}2=s$, so $a=10$ and the largest $=a+4=14.$" },
  { id: "tsa-ps2-084", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 3, marks: 1,
    question: "The sum of $8$ consecutive integers is $100$. What is the largest of them?",
    options: [{ key: "A", text: "$16$" },{ key: "B", text: "$8$" },{ key: "C", text: "$17$" },{ key: "D", text: "$\\frac{25}{2}$" },{ key: "E", text: "$9$" }],
    answer: "A", solution: "If the first is $a$: $ka+\\tfrac{k(k-1)}2=s$, so $a=9$ and the largest $=a+7=16.$" },
  { id: "tsa-ps2-085", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 3, marks: 1,
    question: "The sum of $3$ consecutive integers is $45$. What is the largest of them?",
    options: [{ key: "A", text: "$16$" },{ key: "B", text: "$13$" },{ key: "C", text: "$15$" },{ key: "D", text: "$14$" },{ key: "E", text: "$17$" }],
    answer: "A", solution: "If the first is $a$: $ka+\\tfrac{k(k-1)}2=s$, so $a=14$ and the largest $=a+2=16.$" },
  { id: "tsa-ps2-086", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 3, marks: 1,
    question: "The sum of $7$ consecutive integers is $84$. What is the largest of them?",
    options: [{ key: "A", text: "$8$" },{ key: "B", text: "$9$" },{ key: "C", text: "$15$" },{ key: "D", text: "$12$" },{ key: "E", text: "$16$" }],
    answer: "C", solution: "If the first is $a$: $ka+\\tfrac{k(k-1)}2=s$, so $a=9$ and the largest $=a+6=15.$" },
  { id: "tsa-ps2-087", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A film starts $90$ minutes after $2$ h $30 min past midnight. How many minutes past midnight does it start?",
    options: [{ key: "A", text: "$250$ 分钟" },{ key: "B", text: "$240$ 分钟" },{ key: "C", text: "$90$ 分钟" },{ key: "D", text: "$150$ 分钟" },{ key: "E", text: "$60$ 分钟" }],
    answer: "B", solution: "Start $=2\\times60+30+90=240$ minutes past midnight." },
  { id: "tsa-ps2-088", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A film starts $50$ minutes after $1$ h $45 min past midnight. How many minutes past midnight does it start?",
    options: [{ key: "A", text: "$105$ 分钟" },{ key: "B", text: "$55$ 分钟" },{ key: "C", text: "$165$ 分钟" },{ key: "D", text: "$50$ 分钟" },{ key: "E", text: "$155$ 分钟" }],
    answer: "E", solution: "Start $=1\\times60+45+50=155$ minutes past midnight." },
  { id: "tsa-ps2-089", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A film starts $80$ minutes after $0$ h $50 min past midnight. How many minutes past midnight does it start?",
    options: [{ key: "A", text: "$-30$ 分钟" },{ key: "B", text: "$140$ 分钟" },{ key: "C", text: "$80$ 分钟" },{ key: "D", text: "$50$ 分钟" },{ key: "E", text: "$130$ 分钟" }],
    answer: "E", solution: "Start $=0\\times60+50+80=130$ minutes past midnight." },
  { id: "tsa-ps2-090", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A rectangle measures $12$ by $5$. What is its area?",
    options: [{ key: "A", text: "$34$" },{ key: "B", text: "$72$" },{ key: "C", text: "$17$" },{ key: "D", text: "$30$" },{ key: "E", text: "$60$" }],
    answer: "E", solution: "Area $=12\\times5=60.$" },
  { id: "tsa-ps2-091", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A rectangle measures $8$ by $7$. What is its area?",
    options: [{ key: "A", text: "$30$" },{ key: "B", text: "$15$" },{ key: "C", text: "$64$" },{ key: "D", text: "$56$" },{ key: "E", text: "$28$" }],
    answer: "D", solution: "Area $=8\\times7=56.$" },
  { id: "tsa-ps2-092", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A rectangle measures $15$ by $6$. What is its area?",
    options: [{ key: "A", text: "$21$" },{ key: "B", text: "$90$" },{ key: "C", text: "$42$" },{ key: "D", text: "$105$" },{ key: "E", text: "$45$" }],
    answer: "B", solution: "Area $=15\\times6=90.$" },
  { id: "tsa-ps2-093", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A rectangle measures $9$ by $4$. What is its area?",
    options: [{ key: "A", text: "$36$" },{ key: "B", text: "$45$" },{ key: "C", text: "$13$" },{ key: "D", text: "$18$" },{ key: "E", text: "$26$" }],
    answer: "A", solution: "Area $=9\\times4=36.$" },
  { id: "tsa-ps2-094", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A rectangle measures $12$ by $5$. What is its perimeter?",
    options: [{ key: "A", text: "$29$" },{ key: "B", text: "$36$" },{ key: "C", text: "$17$" },{ key: "D", text: "$34$" },{ key: "E", text: "$60$" }],
    answer: "D", solution: "Perimeter $=2(12+5)=34.$" },
  { id: "tsa-ps2-095", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A rectangle measures $8$ by $7$. What is its perimeter?",
    options: [{ key: "A", text: "$32$" },{ key: "B", text: "$15$" },{ key: "C", text: "$30$" },{ key: "D", text: "$56$" },{ key: "E", text: "$23$" }],
    answer: "C", solution: "Perimeter $=2(8+7)=30.$" },
  { id: "tsa-ps2-096", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A rectangle measures $10$ by $3$. What is its perimeter?",
    options: [{ key: "A", text: "$26$" },{ key: "B", text: "$28$" },{ key: "C", text: "$30$" },{ key: "D", text: "$13$" },{ key: "E", text: "$23$" }],
    answer: "A", solution: "Perimeter $=2(10+3)=26.$" },
  { id: "tsa-ps2-097", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "A rectangle measures $6$ by $6$. What is its perimeter?",
    options: [{ key: "A", text: "$36$" },{ key: "B", text: "$26$" },{ key: "C", text: "$18$" },{ key: "D", text: "$24$" },{ key: "E", text: "$12$" }],
    answer: "D", solution: "Perimeter $=2(6+6)=24.$" },
  { id: "tsa-ps2-098", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "Find the mean of $\\{4, 8, 6, 10, 2\\}$.",
    options: [{ key: "A", text: "$30$" },{ key: "B", text: "$7$" },{ key: "C", text: "$6$" },{ key: "D", text: "$2$" },{ key: "E", text: "$10$" }],
    answer: "C", solution: "Mean $=\\dfrac{30}{5}=6.$" },
  { id: "tsa-ps2-099", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "Find the mean of $\\{12, 15, 9, 6, 18\\}$.",
    options: [{ key: "A", text: "$13$" },{ key: "B", text: "$6$" },{ key: "C", text: "$60$" },{ key: "D", text: "$18$" },{ key: "E", text: "$12$" }],
    answer: "E", solution: "Mean $=\\dfrac{60}{5}=12.$" },
  { id: "tsa-ps2-100", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 1, marks: 1,
    question: "Find the mean of $\\{20, 25, 30, 25\\}$.",
    options: [{ key: "A", text: "$25$" },{ key: "B", text: "$26$" },{ key: "C", text: "$100$" },{ key: "D", text: "$20$" },{ key: "E", text: "$30$" }],
    answer: "A", solution: "Mean $=\\dfrac{100}{4}=25.$" },
  { id: "tsa-ps2-101", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A price of £$100$ is increased by $10\\%$ and then decreased by $10\\%$. What is the final price?",
    options: [{ key: "A", text: "$94$" },{ key: "B", text: "$110$" },{ key: "C", text: "$99$" },{ key: "D", text: "$100$" },{ key: "E", text: "$90$" }],
    answer: "C", solution: "Final $=100(1+10/100)(1-10/100)=100(1-10^2/10000)=£99$ — slightly less than the original." },
  { id: "tsa-ps2-102", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A price of £$200$ is increased by $20\\%$ and then decreased by $20\\%$. What is the final price?",
    options: [{ key: "A", text: "$240$" },{ key: "B", text: "$187$" },{ key: "C", text: "$200$" },{ key: "D", text: "$192$" },{ key: "E", text: "$160$" }],
    answer: "D", solution: "Final $=200(1+20/100)(1-20/100)=200(1-20^2/10000)=£192$ — slightly less than the original." },
  { id: "tsa-ps2-103", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A price of £$50$ is increased by $30\\%$ and then decreased by $30\\%$. What is the final price?",
    options: [{ key: "A", text: "$50$" },{ key: "B", text: "$\\frac{81}{2}$" },{ key: "C", text: "$35$" },{ key: "D", text: "$\\frac{91}{2}$" },{ key: "E", text: "$65$" }],
    answer: "D", solution: "Final $=50(1+30/100)(1-30/100)=50(1-30^2/10000)=£\\frac{91}{2}$ — slightly less than the original." },
  { id: "tsa-ps2-104", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "A price of £$80$ is increased by $25\\%$ and then decreased by $25\\%$. What is the final price?",
    options: [{ key: "A", text: "$60$" },{ key: "B", text: "$70$" },{ key: "C", text: "$75$" },{ key: "D", text: "$100$" },{ key: "E", text: "$80$" }],
    answer: "C", solution: "Final $=80(1+25/100)(1-25/100)=80(1-25^2/10000)=£75$ — slightly less than the original." },
  { id: "tsa-ps2-105", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "On a map with scale $1:50000$, two towns are $4$ cm apart. What is the real distance in km?",
    options: [{ key: "A", text: "$200$ km" },{ key: "B", text: "$2$ km" },{ key: "C", text: "$200000$ km" },{ key: "D", text: "$\\frac{1}{12500}$ km" },{ key: "E", text: "$3$ km" }],
    answer: "B", solution: "Real $= 4\\times50000$ cm $=\\dfrac{4\\times50000}{100000}$ km $=2$ km." },
  { id: "tsa-ps2-106", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "On a map with scale $1:25000$, two towns are $6$ cm apart. What is the real distance in km?",
    options: [{ key: "A", text: "$\\frac{5}{2}$ km" },{ key: "B", text: "$\\frac{3}{12500}$ km" },{ key: "C", text: "$\\frac{3}{2}$ km" },{ key: "D", text: "$150000$ km" },{ key: "E", text: "$150$ km" }],
    answer: "C", solution: "Real $= 6\\times25000$ cm $=\\dfrac{6\\times25000}{100000}$ km $=\\frac{3}{2}$ km." },
  { id: "tsa-ps2-107", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "On a map with scale $1:100000$, two towns are $3$ cm apart. What is the real distance in km?",
    options: [{ key: "A", text: "$300$ km" },{ key: "B", text: "$3$ km" },{ key: "C", text: "$\\frac{3}{100000}$ km" },{ key: "D", text: "$300000$ km" },{ key: "E", text: "$4$ km" }],
    answer: "B", solution: "Real $= 3\\times100000$ cm $=\\dfrac{3\\times100000}{100000}$ km $=3$ km." },
  { id: "tsa-ps2-108", type: "mcq", testId: "tsa", topicId: "tsa-problem", difficulty: 2, marks: 1,
    question: "On a map with scale $1:20000$, two towns are $8$ cm apart. What is the real distance in km?",
    options: [{ key: "A", text: "$\\frac{1}{2500}$ km" },{ key: "B", text: "$\\frac{8}{5}$ km" },{ key: "C", text: "$\\frac{13}{5}$ km" },{ key: "D", text: "$160000$ km" },{ key: "E", text: "$160$ km" }],
    answer: "B", solution: "Real $= 8\\times20000$ cm $=\\dfrac{8\\times20000}{100000}$ km $=\\frac{8}{5}$ km." },
];
